gatsbyjs/gatsby

docs/docs/use-static-query.md
Added an advanced example to use `useStaticQuery ` across multiple files.
Related: https://twitter.com/Kikobeats/status/1104344279676317698
=> chore(docs): add useStaticQuery advanced example

docs/sites.yml
=> chore(showcase): add hermanya.github.io

docs/sites.yml
Showcase: Add Hetzner Online Community
=> chore(showcase): Add Hetzner Online

docs/blog/2018-10-04-journey-to-the-content-mesh/index.md
After revisiting the Content Mesh pieces, I realized that it needed a couple of short statements that would help simplify the core message of the piece. 
This PR adds those.
=> chore(blog): update content mesh piece

packages/gatsby/cache-dir/loader.js
spotted a typo and trying to fix it
=> typo(gatsby): fix typo in comment

docs/sites.yml
Added [syracuse.io](https://syracuse.io) to the showcase
=> chore(showcase): Add Syracuse.io to site showcase

docs/sites.yml
Add [Render](https://render.com) [Docs](https://render.com/docs) to sites.yml.
=> feat(showcase): add Render Docs to sites.yml

packages/gatsby-transformer-remark/src/__tests__/extend-node.js, packages/gatsby-transformer-remark/src/__tests__/on-node-create.js, packages/gatsby/package.json, packages/gatsby/src/db/__tests__/node-tracking-test.js, packages/gatsby/src/schema/__tests__/run-query.js, packages/gatsby/src/schema/infer/__tests__/example-value.js, packages/gatsby/src/schema/infer/__tests__/infer.js, packages/gatsby/src/schema/infer/add-inferred-fields.js, packages/gatsby/src/schema/infer/index.js, packages/gatsby/src/schema/schema.js, packages/gatsby/src/schema/types/__tests__/sort-and-filter.js, packages/gatsby/src/schema/types/filter.js, packages/gatsby/src/schema/types/node-interface.js, packages/gatsby/src/schema/types/pagination.js, yarn.lock
Needed for new metadata feature.
=> chore(gatsby): Update graphql-compose version

docs/docs/creating-a-transformer-plugin.md
=> Add example filename

docs/docs/creating-a-transformer-plugin.md
fixed variable name in example
=> chore(docs): tweak unused variable in transformer plugin docs

CODEOWNERS
Add CODEOWNERS for themes related files
=> add codeowners to theme paths

docs/docs/themes.md, docs/docs/themes/conventions.md, docs/docs/themes/introduction.md, docs/docs/themes/theme-composition.md
- Add naming conventions section
- Add layouts section for better theme composition
=> feat(docs): Address some feedback on themes docs

docs/docs/using-gatsby-image.md
=> chore(docs): add missing comma in using-gatsby-image example

docs/blog/2019-03-21-add-auth0-to-gatsby-livestream/index.md, docs/blog/2019-03-22-add-auth0-to-gatsby-livestream/index.md
This is a quick post to share the latest _Learn With Jason_ livestream, which covered adding authentication to Gatsby apps with Auth0.
I need to get better at posting these.
=> docs(www): new post about auth in Gatsby livestream

packages/gatsby/src/schema/__tests__/__snapshots__/kitchen-sink.js.snap, packages/gatsby/src/schema/__tests__/build-schema.js, packages/gatsby/src/schema/__tests__/kitchen-sink.js, packages/gatsby/src/schema/schema.js
=> fix(gatsby): make sure interface implementations in third-party schema

packages/gatsby/src/schema/infer/__tests__/__snapshots__/infer.js.snap, packages/gatsby/src/schema/infer/__tests__/infer.js, packages/gatsby/src/schema/infer/example-value.js, packages/gatsby/src/schema/utils/get-value-at.js
=> fix(gatsby): tolerate null object values

docs/sites.yml
Add [prima](https://www.prima.co) to sites.yml.
=> chore(showcase): add prima

docs/blog/2019-03-22-introducing-gatsby-preview-beta/index.md
Addressing feedback from @marcysutton
=> chore(blog): accomodate feedback

docs/docs/creating-a-transformer-plugin.md
I agree with @ChristopherBiscardi this sentence needs a bit more :-)
=> Make sentence clearer

docs/sites.yml
add https://architudedesign.com/ to showcase
=> chore(showcase): add Architude Design to showcase

packages/gatsby/src/schema/node-model.js
We accidentaly made `getAllNodes` track everything when called. It's not an expected behavioru, because this function is often used to manually filter nodes. Thus, we disable tracking unless you explicitly ask for it. This PR also adds manual tracking function.
=> fix(schema): Don't default to tracking all nodes

docs/sites.yml
add https://autodesk.github.io/react-base-table/ to showcase
=> chore(showcase): add BaseTable to showcase

docs/starters.yml
This repo contains a GitHub personal website for JS developers as the original website is written ruby.
=> chore(starters): Add gatsby-github-personal-website

docs/sites.yml
Added https://herper.io/ to the showcase.
=> chore(showcase): added herper.io to showcase

docs/starters.yml
I started with Gatsby a couple weeks ago and redesigned my website with it. I then had the idea to also create it as a starter guide for people who want a minimal blog. So here is my PR with the starter. I hope you like it.
=> chore(starters): add gatsby-starter-julia

docs/starters.yml
=> chore(starters): add automatic-gatsbyjs-app-landing-page

packages/gatsby-plugin-react-helmet/README.md
=> docs(gatsby-plugin-react-helmet): working around delayed titles with Helmet + offline plugin

packages/gatsby/src/redux/actions.js
=> fix(schema): Fix API docs

lerna.json
Ignore tests when publishing with lerna
=> chore: Ignore tests, mocks and fixtures in lerna publish and lerna version

docs/sites.yml
Add a new site to the showcase.
=> Add morning.photos to showcase

.gitattributes
=> Use merge=union for yaml files so we have less merge conflicts

docs/sites.yml
Adds Pattyrn marketing site to Showcase page
=> Add Pattyrn to sites.yml

packages/gatsby/src/schema/infer/__tests__/merge-types.js, packages/gatsby/src/schema/infer/add-inferred-fields.js
~Pulled out from #12806 since that needs more discussion.~ (merged)
Add tests for correct list counting.
=> fix(schema): Add tests for incorrect list counting

docs/sites.yml
Add Intranet Italia Day to showcase
=> chore(showcase): add Intranet Italia Day - ariadnedigital.it

docs/blog/2019-03-22-introducing-gatsby-preview-beta/index.md
=> chore(blog): tweak opening paragraphs to Gatsby Preview blog post

docs/blog/2019-03-26-what-the-jamstack-means-for-marketing/index.md
=> fix(blog): update links to be more descriptive

docs/starters.yml
Add Serverless Shopify App starter - https://github.com/gil--/gatsby-starter-shopify-app
=> chore(starters): add gatsby-shopify-app

docs/docs/programmatically-create-pages-from-data.md
Changing from Promise/Resolve to Async.
Tried using the Promise/Resolve example in my code and it was throwing errors. Found your debugging async page and used the example there (very similar) and it worked. For consistency, moved that example to the other page as well. Was there a reason you were using Promise/Resolve in this space?
=> chore(docs): Update programmatically-create-pages-from-data.md

packages/gatsby-plugin-subfont/package.json, packages/gatsby-plugin-subfont/src/gatsby-node.js
=> fix(gatsby-plugin-subfont): escape file paths

docs/sites.yml
Add OneDeck (www.onedeck.co) to site showcase
Would love to add the new OneDeck site to the Gatsby showcase. We've loved working with Gatsby.
n/a
=> chore(showcase): Add OneDeck to showcase

.circleci/config.yml
=> tmp(CircleCi): use temporary libvps dists

docs/blog/2019-04-02-integrating-with-gatsby/index.md
Adds an integrating with Gatsby blog post.
=> feat(blog): add integrating with gatsby blog post

docs/blog/2019-04-02-integrating-with-gatsby/index.md
=> Mention the preferred way to update content for Preview

docs/blog/2019-04-02-integrating-with-gatsby/index.md
I found a typo. I fixed it.
#12965
=> blog: fix typo

docs/contributing/community.md, www/src/data/sidebars/doc-links.yaml, www/src/pages/contributing/index.js, www/src/pages/docs/index.js
Add some copy to contributing pages to emphasize how excited we are for everyone to help!
=> feat(docs): add to contributing pages

docs/blog/2018-07-20-why-we-built-the-site-showcase/index.md, docs/blog/2018-07-31-docs-redesign/index.md, docs/blog/2018-12-31-how-we-do-high-impact-ux-research/index.md, docs/blog/2019-03-11-dot-org-prototypes/index.md, docs/contributing/docs-templates.md, docs/contributing/gatsby-style-guide.md, docs/docs/image-tutorial.md, docs/docs/introducing-graphiql.md, docs/docs/using-gatsby-image.md, docs/docs/wordpress-source-plugin-tutorial.md
I believe uppercasing README is a known convention, though if I'm mistaking personal preference here then please do ignore me and close this PR. 😃
=> Uppercase the me in README

docs/starters.yml
=> chore(starters): add gatsby-devto

docs/docs/sourcing-from-netlify-cms.md
As per comment https://github.com/netlify/netlify-cms/issues/1690#issuecomment-465078677
Identity widget conflicts with implicit authentication and should be disabled.
=> Config info for GitLab Client-Side Implicit Grant

docs/docs/awesome-gatsby.md
reorder: group by language
n/a
=> chore(docs): group awesome gatsby resources by language

starters/default/gatsby-config.js
Changing single quotes in gatsby-config.js to backticks to keep consistency. 😊
=> Changing single quotes in gatsby-config.js to backticks

docs/blog/2019-02-08-government-open-data-site-with-gatsby/index.md, docs/blog/2019-02-27-reactiflux-q-and-a/index.md, docs/docs/themes/conventions.md, docs/starters.yml
I found a few places where Gatsby is misspelled.
=> fix(docs): fix spelling of Gatsby in a few places

.eslintrc.json
=> remove unnecessary eslint rule

packages/gatsby/package.json, packages/gatsby/src/commands/develop.js, packages/gatsby/src/commands/serve.js, packages/gatsby/src/utils/detect-port-in-use-and-prompt.js
Because great developer experience and resolves confusion like in https://github.com/gatsbyjs/gatsby/issues/12961
=> feat(gatsby-cli): Detect if something is already running on a port when running gatsby serve

docs/docs/convincing-others.md
=> chore(docs): fix typo in convincing others doc

docs/tutorial/part-two/index.md
Use em dash in place of two hyphens.
Format paragraph to be on one line (apparently the convention).
=> Fix Misuse of Commas, Et Al

docs/sites.yml
Adding gmartinez.dev to showcase list in site.yml
=> chore(showcase): Add gmartinez.dev to showcase

docs/tutorial/part-seven/index.md
Hopefully fix a code formatting issue when in a highlighted section.
=> Fix Comma Usage; Misc Updates

docs/sites.yml
=> Add becreatives.com to showcase

docs/sites.yml
=> Fixed becreatives.com description

docs/starters.yml
Add gatsby-starter-framer-x to starters
=> chore(starters): add gatsby-starter-framer-x

packages/gatsby-plugin-react-helmet/README.md
In the linked issue, it was brought up that documentation should be introduced to alert users of `gatsby-plugin-react-helmet` of the issues Hooks bring, and how to resolve them. This PR is a transcription of the outcomes of that discussion into the documentation, resolving #12357.
#12357
=> docs(gatsby-plugin-react-helmet): add React hooks compatibility information

docs/docs/building-with-components.md
Part 7 is the correct location for generating pages using data. Maybe it used to be part 4.
=> Link to Correct Location in Tutorial

docs/sites.yml
Azer has updated their domain name so I am updating such in the showcase to reflect
=> chore(showcase): Update Azer Koçulu entry

docs/sites.yml
The main_url field was not properly routing without the www in the URL so I added it to the entry
=> chore(showcase): Updating Distrupting Nate entry

docs/sites.yml
EaseCentral changed their marketing to just Ease so I updated the Site Showcase to reflect
=> chore(showcase) Updated EaseCentral to Ease in site showcase

docs/sites.yml
Just adding a site that has recently launched which was built using Gatsby.
=> chore(showcase): add Paul Clifton Photography to showcase

docs/starters.yml
Removing the gatsby-starter-ghost that I had contributed earlier. The Ghost team have contributed their starter now!
=> feat(starters): removing little-wolf-studio gatsby-starter-ghost

docs/docs/themes/getting-started.md
Fixed grammar/typo by replacing the word "With" with the word "When."
Fixed grammar/typo by replacing the word "With" with the word "When."
=> Fixed Typo in getting-started.md

docs/docs/themes/introduction.md
Fixed typo of repeated phrase "you can."
Fixed typo of repeated phrase "you can."
=> Fixed typo in introduction.md

docs/sites.yml
Adding another site that I built using GatsbyJS and Bulma to the showcase.
=>  feat(showcase): add Little Wolf Studio to showcase

docs/docs/babel.md
=> Make clear you can add other presets & plugins to a .babelrc file

docs/blog/2019-04-03-how-we-think-about-product-at-gatsby/index.md
This is a blog post that summarizes our first product summit.
=> feat(blog): Add a new blog about how we think about product at Gatsby

docs/docs/how-gatsby-boosts-career.md
Add an additional para about _why_ Gatsby is a great career investment.
=> chore(docs): update how gatsby boosts careers

docs/sites.yml
Correction - "blog" to "blogs"
=> chore(showcase): fix grammar in site showcase

docs/docs/awesome-gatsby.md
=> chore(docs): add dashbored article to awesome gatsby

www/src/components/site-metadata.js
@pieh knows what I’m doing here :D <3
=> fix(www): Site metadata staticQuery

www/src/pages/contributing/__tests__/stub-list.js
adjusted unit tests after #13308
=> tests(www): adjust mocked result of useStaticQuery hook

docs/sites.yml
=> chore(showcase): Add Filipe's personal site to showcase.

docs/docs/awesome-gatsby.md
Adding 12 Factor GatsbyJS Applications Article to awesome Gatsby
=> Adding 12 Factor GatsbyJS Applications Article to awesome Gatsby

packages/gatsby-source-graphql/src/gatsby-node.js
add params createContentDigest to createSchemaNode LINE:112
Fixes #13239 
https://github.com/gatsbyjs/gatsby/issues/13239
=> fix(gatsby-source-graphql): fix data refetching

docs/starters.yml
=> chore(starters): add lewis-gatsby-starter-blog

docs/sites.yml
=> Jeff Wolff Portfolio site

docs/sites.yml
Submitting my website for Site Showcase as described [here](https://www.gatsbyjs.org/contributing/site-showcase-submissions/)
=> feat(showcase): Adding my portfolio jpvalery.photo

docs/docs/gatsby-vendor-partnership.md
Fixed a broken link per #13325 
fixes #13325
=> docs: fix broken link

docs/sites.yml
added a Pantene website which uses gatsby to site showcase
=> feat(showcase): add Pantene website

docs/starters.yml
chore(starters): add gatsby-starter-haezl
=> chore(starters): add gatsby-starter-haezl

docs/starters.yml
Hoping someone finds this useful :beers:
=> chore(starters): add gatsby-starter-stripe

docs/docs/awesome-gatsby.md
… Awesomw Gatsby
Adding Reading Data From A JSON File With Gatsby + GraphQL Article to Awesomw Gatsby
=> chore(docs): Add "Reading Data From A JSON File With Gatsby + GraphQL" to Awesome list

docs/sites.yml
=> chore(showcase): Add Prevue to Site Showcase

docs/sites.yml
This adds the [site](https://www.krashna.nl) of student music association Krashna Musika from Delft (NL) to the showcase :)
=> feat(showcase): Add krashna.nl site to the showcase

docs/sites.yml
Just another PR to add a site from the space and science field!
=> feat(showcase): Add Fifth Gait to showcase

docs/sites.yml
Cleanup of site showcase entries that are no longer using Gatsby
(using @lannonbr's awesome validation tool - https://github.com/lannonbr/gatsby-site-showcase-validator)
=> chore(showcase): remove sites that are no longer using Gatsby

docs/sites.yml
Adding my portoflio website built wiiiith gatsby to the showcase ❤️.
- [Site](https://nikodemdeja.pl/)
- [Source code](https://github.com/Norem80/nikodemdeja.pl)
=> feat(showcase): Add nikodemdeja.pl to showcase

docs/docs/awesome-gatsby.md
I've added a link to my Gatsby YouTube tutorial per the suggestion from Benjamin Lannon [(tweet)](https://twitter.com/lannonbr/status/1118861148793786369).
=> Add link to new Gatsby tutorial

docs/tutorial/part-eight/index.md, docs/tutorial/part-five/index.md, docs/tutorial/part-four/index.md, docs/tutorial/part-one/index.md, docs/tutorial/part-seven/index.md, docs/tutorial/part-six/index.md, docs/tutorial/part-three/index.md, docs/tutorial/part-two/index.md, docs/tutorial/part-zero/index.md
I found some grammar errors in tutorials and fixed them.
=> chore(tutorials): fixed punctuation, typos and grammar in tutorials.

README.md
=> docs: Added CLI installation instructions in README

docs/sites.yml
Move the showcases from the category `Landing page` to `Landing Page`
Fixes #13479
=> Cleanup showcases

docs/docs/awesome-gatsby.md
Adding Gatsby lifecycle Article to Awesome Gatsby
=> chore(awesome-gatsby): add Gatsby lifecycle article

docs/sites.yml
added a new website for showcase which uses gatsbyjs
=> feat(showcase) : add pella website

docs/sites.yml
I hope this is the correct way of doing this. I changed the repository name, and thus the URL, to account for the technology used.
=> Minor change to source URL for Patrik Arvidsson (sites)

docs/sites.yml
Add my new blog built with Gatsby to the showcase.
=> feat(showcase): Add blog.nikodemdeja.pl to the showcase.

docs/tutorial/index.md
Fix the link to the Quick Start page
=> fix(docs): Fix the link to the Quick Start page

packages/gatsby/src/utils/api-browser-docs.js
I've found a typo https://www.gatsbyjs.org/docs/browser-apis/ and fixed it :)
There are no related issues
Cheers
=> fix(docs): Fix typo in Gatsby Browser APIs

docs/tutorial/part-zero/index.md
Added Command Line instructions for Linux users
=> Added Command Line instructions for Linux users

docs/sites.yml
Add my personal website (tinney.dev) to the showcase.
=> feat(showcase): add tinney.dev to showcase

docs/docs/deploying-to-netlify.md
=> chore(docs): Update deploying-to-netlify.md

docs/starters.yml
Adding my starter to the site 👍
Left a blank line at the end since there was one before.
=> chore(starters): Add Gatsby Doc Starter

docs/starters.yml
Hi I'm requesting to add a new portfolio site starter!
=> chore(starters):add gatsby-clean-portfolio-starter

docs/docs/adding-page-transitions-with-plugin-transition-link.md, e2e-tests/development-runtime/cypress/integration/hot-reloading/arrow-functions.js, packages/gatsby/src/redux/actions.js
=> chore: Fix typos

docs/starters.yml
Added [gatsby-absurd](https://github.com/ajayns/gatsby-absurd) to the starters library
=> chore(starters): add gatsby-absurd

packages/gatsby/src/db/__tests__/nodes.js, packages/gatsby/src/redux/actions.js
It updates deleteNode action so it respects node type owner
#11930
=> fix(gatsby): respect node type owner in deleteNode

docs/sites.yml
=> chore(showcase): add deepmay.io

docs/sites.yml
=> chore(showcase): add monkeywrenchbooks.org

docs/docs/browser-support.md
=> Tiny grammatical error in documentation

docs/docs/gatsby-vendor-partnership.md
=> chore(docs): Fix typo in gatsby-vendor-partnership.md

docs/sites.yml
Respectfully submitting [Liferay.Design](https://liferay.design) to the Gatsby Showcase. 🤓
=> chore(showcase): add Liferay.Design

.circleci/config.yml
https://github.com/lovell/sharp/issues/1632 is resolved so we can remove this now
Reverts https://github.com/gatsbyjs/gatsby/pull/12941
=> chore: revert temporary sharp fix

docs/docs/centralizing-your-sites-navigation.md
=> chore(docs): Fix indentation

www/src/templates/template-creator-details.js
=> fix(www): fix www after git merge problems

docs/docs/mdx/programmatically-creating-pages.md
* Add missing curly bracket in example
* Fix note formatting and update GraphiQL link
* Format code examples to match prettier rules
=> fix(docs): Fix MDX instructions

docs/docs/adding-comments.md
Correct indentation, correct titles, removed placeholder (`...`)
=> fix(docs): "Adding Comments" errors

docs/docs/using-graphql-playground.md
Added missing step to require dotenv package, misc formatting changes
=> chore(docs): Update using-graphql-playground

docs/sites.yml
Adding justgraphql.com built with gatsby to the showcase 🎉
=> feat(showcase): Add justgraphql.com to showcase

docs/docs/adding-an-rss-feed.md, docs/docs/adding-comments.md, docs/docs/adding-search-with-algolia.md, docs/docs/adding-search-with-js-search.md, docs/docs/deploying-to-heroku.md, docs/docs/mdx/programmatically-creating-pages.md, docs/docs/migrating-from-v1-to-v2.md, docs/docs/sourcing-from-buttercms.md, docs/docs/sourcing-from-graphcms.md, docs/docs/themes/api-reference.md, docs/docs/themes/building-themes.md, docs/docs/themes/converting-a-starter.md, docs/docs/themes/getting-started.md, docs/docs/third-party-graphql.md, docs/docs/why-gatsby-uses-graphql.md
Added syntax highlighting and titles to code blocks.
Also changed Type tab from `sh` and `bash` to `shell` as mentioned in doc [Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#code-formatting-type-tab)
=> chore(docs): Update code formatting

docs/sites.yml
Adding personal website to Gatsby showcase
=> chore(showcase): add peter.macinkovic.id.au to showcase

docs/starters.yml
Adding new theme starter to the starters library
=> chore(starters): add gatsby-starter-ggt-material-ui-blog

packages/gatsby/src/utils/api-node-docs.js
=> docs(node-apis): fix missing comma in createResolvers example

packages/gatsby/cache-dir/gatsby-browser-entry.js
Typo in error message found while using TypeScript.
=> fix(typo): fix typos in error message

docs/sites.yml
Submission of my website to the Gatsby showcase. I am mobile + web developer with a 4 year work experience in React. I recently built my personal portfolio site in Gatsby JS and will for it to be hosted on the Gatsby showcase
=> Site submission for Kenneth Kwakye-Gyamfi

docs/docs/caching.md
Link to Now documentation for caching instructions when deploying with Now.
=> Update caching.md with Now instructions

docs/sites.yml
Add new showcase
```yml
- title: blackcater's blog
url: https://www.blackcater.win
main_url: https://www.blackcater.win
source_url: https://github.com/blackcater/blog
description: >
Blog like Medium, for person and team.
categories:
- Blog
- Web Development
built_by: blackcater
built_by_url: https://github.com/blackcater
featured: false
```
Nothing.
=> Add new showcase

packages/gatsby/src/utils/webpack.config.js
This seems to break a few websites with a weird wasm error #13641
=> Revert "fix(gatsby): fixes react-hot-reloader for new react features"

docs/starters.yml
Update gatsby starter blog typescript's url with a proper domain
=> chore(starters): update url

packages/gatsby-plugin-guess-js/src/__tests__/gatsby-ssr.js, packages/gatsby-plugin-guess-js/src/gatsby-ssr.js, packages/gatsby/cache-dir/static-entry.js
TODO (am in person reviewing with Kyle right now)
=> Remove data json from guess

packages/gatsby/src/commands/serve.js, packages/gatsby/src/query/pages-writer.js
TODO (live reviewing with Kyle)
=> Gatsby serve use page data

docs/starters.yml
Fixes typos in the starters.yml file
=> docs: fix typos in starters.yml

docs/docs/glossary.md
Adds routing definition to the new glossary
=> Add definition of routing

docs/sites.yml
corrected a spelling mistake for the feat(showcase) : website name Mailjet
=> corrected a spelling mistake

www/src/components/__tests__/banner.js, www/src/components/banner.js
„Register now“ -> „Watch now“
/cc @lindaleebumblebee
=> feat(www): Update banner link title

www/package.json, www/src/components/plugin-searchbar-body.js
Hello you all!! ☀️ 🌳 Thanks for the awesome work and for making it possible for us to contribute in such a great project! 
This PR updates `react-instantsearch` to v5 following [algolia instructions](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/#upgrade-from-v4-to-v5).
Closes https://github.com/gatsbyjs/gatsby/issues/13686
=> feat(www): update react-instantsearch to v5

www/src/pages/contributing/events.js
copy change requested by @lindaleebumblebee
=> chore(www): copy edit to events page

docs/docs/creating-and-modifying-pages.md, examples/using-i18n/gatsby-node.js
Fixes #13601
Updates the documentation as well.
Reason:
=> fix(using-i18n): Infinite loop

docs/sites.yml
Adding _Let's Do Dish!_ to the Showcase
=> chore(showcase): Adding letsdodish.com

docs/starters.yml
=> chore(starters): Fix wrong tags

docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
A few things have changed in MDX so this seeks to update
the install instructions.
This also adds a site running section before we customize
the index page. Additionally, it adds some file names and
code highlighting to make things a bit more clear.
=> fix(blog): Update MDX install in themes blog post

docs/blog/2019-05-02-growing-housecall-pro-by-973-percent/index.md
=> fix(blog): update housecall pro post

docs/docs/hosting-on-netlify.md
Updated hosting on netlify.md's quick start link
Possibly closes half of #13804 
❤️
=> chore(docs): updated quick start link in netlify hosting doc

docs/docs/hosting-on-netlify.md
Added how to use Environment variables in Netlify.
The other recommendation in #13804
=> chore(docs): add env variables to hosting netlify

.circleci/config.yml
Revert "Revert "tests: add node 12 to tests (#13538)" (#13748)"
This reverts commit b80cfb969d451d2fb8204ff122eefd2c53086945.
=>  test: re-add Node12 CircleCI unit tests job

.github/actions/high-priority-prs/Dockerfile, .github/actions/high-priority-prs/README.md, .github/actions/high-priority-prs/data.json, .github/actions/high-priority-prs/index.js, .github/actions/high-priority-prs/package.json, .github/actions/high-priority-prs/pr-message.js, .github/actions/high-priority-prs/process.js, .github/main.workflow
This is a port of @KyleAMathews PR prioritising Slackbot, [read all about it on his blog](https://www.bricolage.io/bulding-a-slack-bot-to-help-handle-large-numbers-of-prs/). This PR adds the bot as a scheduled GitHub Action.
=> Add high-priority-prs action

docs/sites.yml
Added my latest sideproject BestPricingPages.com
Request to add my website to showcase.
=> chore(showcase): added BestPricingPages.com

docs/sites.yml
Added https://lendo.at to showcase list
=> chore(showcase): added lendo.at

docs/sites.yml
Added IDEO as a featured showcase site. Kept the featured parameter true because the issue called for it.
Fixes https://github.com/gatsbyjs/gatsby/issues/13859
=> Added IDEO as a featured showcase site

docs/starters.yml
Gatsby starter site submission request
=> chore(starters): add gatsby-starter-mdboostrap-jjcav84

docs/sites.yml
Submitting Gatsby site to Showcase
=> chore(showcase): add visualcloudfx.com

docs/tutorial/part-four/index.md
When going through the tutorial, I missed this return completely, it'll be helpful to highlight to users going through the tutorial as I did! 👍
=> chore(docs): Add highlighting to return

docs/contributing/organize-a-gatsby-event.md
Updating copy changes requested by @lindaleebumblebee (just adding a few links to events contribution page)
=> chore(docs): adding links to event page copy

docs/docs/how-gatsby-works-with-github-pages.md
Typo correction - punctuation for new sentence.
=> chore(docs): Typo correction

docs/docs/sourcing-from-kentico-cloud.md
Clarified what language codename was being used after some issues getting started. Moved comment into code.
=> chore(docs): Moved comment to clarify language codename

docs/sites.yml
Add [bennetthardwick.com](https://bennetthardwick.com) to the showcase.
=> chore(showcase): add bennetthardwick.com

docs/sites.yml
=> chore(showcase): Add camiloholguin.me

docs/sites.yml
=> chore(showcase): Updated npm-bookmarks site.

docs/sites.yml
Added verso.digital to Showcase.
=> chore(showcase): Add verso.digital

docs/starters.yml
Added new starter gatsby-material-boilerplate
Let's materialise the world.
=> chore(starters): add gatsby-material-boilerplate

docs/sites.yml
This PR will add kyma-project.io to showcase list
=> chore(showcase): Add kyma-project.io

docs/sites.yml
Adding sindhuka.org to the showcase
=> chore(showcase): Add "Sindhuka.org"

docs/sites.yml
=> chore(showcase): Edit wrong URL of site "Sindhuka.org"

starters/hello-world/gatsby-config.js
Add an empty config file to the hello-world starter
cc @marcysutton 👀
=> chore(starters): Add empty gatsby-config.js

docs/starters.yml
added entry for gatsby-starter-hyperspace starter library based on Hyperspace by HTML5UP
None
=> chore(starters): add gatsby-starter-hyperspace

README.md
I believe this makes it look better, as in, it moves it outside the scope of just contribution, making the Code of Conduct effective to the whole of the GatsbyJS community.
✈️
=> Move CoC outside How To Contribute

packages/gatsby-plugin-google-analytics/README.md
update wording to avoid confusing
i am open for grammar, spelling and correcting suggestions.
#13888
=> doc(gatsby-plugin-google-analytics): update wording for `head` option

packages/gatsby-plugin-google-analytics/README.md
Master is failing because of a lint issue.
=> chore: fix master lint issue

docs/starters.yml
added gatsby-starter-identity based on Identity by HTML5UP
None
=> chore(starters): add gatsby-starter-identity

www/src/pages/plugins.js, www/src/templates/tags.js, www/src/templates/template-contributor-page.js
A small PR that improves the SEO of Gatsby website.
- Added title, meta, OG and Twitter data for Contributor page.
- Added title for plugins page
- Added title for tags view page
=> feat(www): seo improvements

docs/starters.yml
Add gatsby-advanced-blog-system
None
=> chore(starters): add gatsby-advanced-blog-system

docs/blog/2019-05-03-how-gatsby-helped-jump-start-my-engineering-career/index.md
* Github -> GitHub; Javascript -> JavaScript; git -> Git
* Punctuation and grammar
=> Fixed spelling, punctuation, grammar in blog

docs/docs/gatsby-core-philosophy.md, www/src/data/sidebars/doc-links.yaml
Finally getting something up here!
The goal is to get something as tight as [The Tao of Hashicorp](https://www.hashicorp.com/tao-of-hashicorp). 
My basic goal here was not to invent, but rather to collate and summarize. We've written and spoken **a ton** about our philosophy in various forms and outlets; this idea here is to provide a canonical guide with summaries of all of the various points. 
Some key questions:
* **Content**. are there any big concepts I missed? I feel like we have other tooling philosophies I haven't included.
- **Organization**. I like how The Tao of Hashicorp is punchy -- two paragraphs for each one. Yet I also like the idea of providing longer explanations. Perhaps we should provide a short summary for each point, with a dedicated page for each concept as a child …
=> v1 of Gatsby core philosophy

docs/starters.yml
added gatsby-starter-aerial based on Aerial by HTML5UP
None
=> chore(starters): add gatsby-starter-aerial

docs/sites.yml
Added gonzalonunez.com to showcase page.
=> chore(showcase): Add gonzalonunez.com

docs/starters.yml
Added a new starter gatsby-landing-page-starter
none
=> chore(starters): add gatsby-landing-page-starter

docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
Found this typo while the article 😄
=> docs: Fix typo in Publish "Multiple Gatsby Sites..Travis & Now."

docs/docs/adding-website-functionality.md
This page was partially stubbed out so I filled in the content to introduce the section.
Related to #13820
=> chore(docs): Adding intro paragraph for "Add Website Functionality" page

docs/docs/sourcing-from-sanity.md
Fixed typographical error in the Sanity Documentation.
=> docs: Fix typographical error

docs/sites.yml
Measures for Justice just released our rebuilt-with-Gatsby homepage!
=> Add Measures for Justice website to featured pages

docs/blog/2019-05-17-improvements-to-schema-customization/index.md
Few small tweaks (and fixes) to the excellent blog post by @freiksenet! 🚀
=> chore(blog): small tweaks to schema customization blog post

docs/blog/2019-05-17-improvements-to-schema-customization/index.md, packages/gatsby/src/redux/actions.js, packages/gatsby/src/schema/extensions/index.js, packages/gatsby/src/schema/infer/__tests__/infer.js, packages/gatsby/src/schema/infer/__tests__/merge-types.js, packages/gatsby/src/schema/infer/add-inferred-fields.js
=> Fix proxying invalid field names

docs/docs/creating-global-styles.md
Updated from lavenderblush to peachpuff which has more contrast against white and should be more accessible.
As a user with color blindness, I had a hard time picking up lavenderblush.  Peachpuff has more contrast and is still fun!
None.
=> docs: update example css background color to be more accessible

docs/sites.yml
Added Raconteur Agency to showcase and added categories to herper.io
=> feat(showcase): add https://www.raconteur.net/agency

www/package.json
=> chore(www): bump documentation plugin

docs/docs/adding-search-with-algolia.md
Add an extra resource for developers who may experience Algolia config issues. PR prompted by tweet with Jason: https://twitter.com/jlengstorf/status/1129102351703220224
Question - Should I hyperlink Jason's name? I haven't seen any personal promotion like this on the doc site so I left it static.
=> docs(adding-search-with-algolia): embed "Add Algolia search to your Gatsby site (with Bram Adams) — Learn With Jason" video

docs/starters.yml
added gatsby-starter-readonly design by HTML5 UP
None
=> chore(starters): add gatsby-starter-readonly

docs/docs/gatsby-core-philosophy.md
Added in links to the philosophy doc.
=> chore(docs): add links to philosophy

docs/starters.yml
added gatsby-starter-prologue design by HTML5 UP
None
=> chore(starters): add gatsby-starter-prologue

docs/blog/2019-04-25-plugin-authoring-study/index.md
=> fix blog typo

docs/docs/sourcing-from-contentful.md
Existing docs for Prismic and Netlify are linked to the respective sites
=> Added URL to Contentful

docs/sites.yml
Adds Purple11.com to the showcase. It's a site where I publish tips/tricks for photography and retouching.
None
=> chore(showcase): Add purple11.com

docs/starters.yml
=> chore(starters): add gatsby-london

docs/sites.yml
=> chore(showcase): Add perf.reviews

docs/sites.yml
Adding Green Orbit website to the Gatsby Showcase. :)
=> chore(showcase): add greenorbit.com

docs/sites.yml
Added Un Backend Blog website to the Gatsby Showcase.
=> chore(showcase): Add unbackend.pro

docs/sites.yml
Update GreenOrbit title in gatsby showcase sites.yml
=> chore(showcase): Update Green Orbit to GreenOrbit

docs/docs/adding-search-with-algolia.md
This PR updates the Algolia search guide from class to functional components using React Hooks.
=> chore(docs): Algolia search guide from class to functional components

starters/blog/package-lock.json, starters/blog/package.json
Updated gatsby-remark-images dependency fixing the issue defined below.
Fixes #14186
=> chore(starters): updated gatsby-remark-images dependency for blog starter

docs/sites.yml
I have to update my blog information on your sites.yml, Kindly help me. This blog is created on Gatsby and hosting on netlify. 
You can find my information  like below
- title: Hitesh Vaghasiya
main_url: https://hiteshvaghasiya.com/
url: https://hiteshvaghasiya.com/
description: >
This is Hitesh Vaghasiya's blog. This blog helps the developer on an E-Commerce like Magento, Shopify, and BigCommece.
categories:
- Blog
- Programming
- Technology
- Tutorial
- Web Development
- Netlify
featured: true
=> chore(showcase): Add Hitesh Vaghasiya

docs/docs/files-gatsby-looks-for-in-a-plugin.md
Combine feedback from @florantara and @LekoArts in #14227, and add some extra edits of my own
#14227
=> chore(docs): Files Gatsby Looks for in a Plugin (part 2)

packages/gatsby-cli/package.json, yarn.lock
Updated prompts for gatsby-cli to v2.1.0
Fixes #14139
=> chore(gatsby-cli): Update prompts and fix CLI on Node 6

docs/starters.yml
Created a starter that uses the gatsby-source-google-spreadsheet for pulling data from the Google Sheets.
=> chore(starters): add gatsby-starter-googlesheets

packages/gatsby/src/utils/webpack.config.js
https://github.com/gatsbyjs/gatsby/pull/14208#issuecomment-495031331
=> fix(gatsby): fix `gatsby develop` with Yarn PnP

docs/sites.yml
This PR adds Aditus.io website to the showcase websites in the Accessibility and Education categories.
=> chore(showcase): Add Aditus.io

docs/docs/sourcing-from-prismic.md, docs/docs/sourcing-from-sanity.md
Updated most of tge quick-link bugs I could find and did a small change in linking to Prismic's Plugin Docs
=> chode(docs): updated quick links

docs/tutorial/authentication-tutorial.md
add more guides for authentication to gatsby!
=> docs: add Netlify Identity livestream

packages/gatsby-plugin-sharp/src/index.js
Changes the comment slightly so it is in line with the code changes in #14201
=> chore(gatsby-plugin-sharp): adjust comment to match recent code changes

docs/blog/2019-05-17-community-events-support/index.md, docs/blog/2019-05-24-community-events-support/index.md
This PR adds a blog post about Gatsby's support for Community Events.
Includes links to the existing community support page and the store with info about what Gatsby will do to support people hosting events.
=> docs(blog): adding blog post for community events support

packages/gatsby-plugin-sharp/README.md
Changes the comment slightly so it is in line with the code changes in #14201
=> chore(gatsby-plugin-sharp): Adjust docs to match code changes

packages/gatsby-plugin-facebook-analytics/README.md, packages/gatsby-plugin-facebook-analytics/src/__tests__/__snapshots__/gatsby-ssr.js.snap, packages/gatsby-plugin-facebook-analytics/src/__tests__/gatsby-ssr.js, packages/gatsby-plugin-facebook-analytics/src/gatsby-ssr.js
* Adds version, cookie and xfbml config options. Default values ensures backwards compatibility is maintained.
* Fixes tests as snapshots were incorrect which lead to false positive results.
* Updates the README documentation to include further information about using the plugin.
Implements #14310
=> feat(gatsby-plugin-facebook-analytics): Add version, cookie and xfbml config options

www/package.json
=> chore(www) loosen gatsby-plugin-mdx version to allow upgrades

docs/starters.yml
added gatsby-starter-multiverse design by HTML5 UP
None
=> chore(starters): add gatsby-starter-multiverse

docs/starters.yml
This PR adds the gatsby-starter-blockstack to the docs
=> chore(starters): add gatsby-starter-blockstack

docs/starters.yml
added gatsby-starter-highlights design by HTML5 UP
None
=> chore(starters): add gatsby-starter-highlights

docs/starters.yml
Add the-plain-gatsby, a minimalist starter for your personal blog.
=> chore(starters): add the-plain-gatsby

packages/gatsby/src/schema/__tests__/build-schema.js, packages/gatsby/src/schema/schema.js
Plugins owning a type should be able to extend that type.
=> feat(gatsby): Merge type defs owned by same plugin

docs/sites.yml
Added a site to the showcase sites
=> chore(showcase): Add malice

docs/sites.yml
=> chore(showcase): Add Axel Fuhrmann's portfolio

docs/sites.yml
Added a site to the showcase sites
=> chore(showcase): Add nash

docs/docs/centralizing-your-sites-navigation.md
I am not sure what happens and where the original PR branch went, but this PR replaces #12562
=> chore(docs): Update "Centralized Navigation"

docs/sites.yml
Add two new sites and credit designer on my previously listed sites where applicable.
=> chore(showcase): Update sites.yml

docs/sites.yml
=> chore(showcase): add lukesecomb.digital portfolio site

themes/gatsby-starter-theme/content/posts/hello.mdx, themes/gatsby-starter-theme/gatsby-config.js, themes/gatsby-starter-theme/package.json, themes/gatsby-starter-theme/posts/hello.mdx, themes/gatsby-theme-blog/gatsby-browser.js, themes/gatsby-theme-blog/gatsby-config.js, themes/gatsby-theme-blog/gatsby-node.js, themes/gatsby-theme-blog/package.json, themes/gatsby-theme-blog/src/components/bio.js, themes/gatsby-theme-blog/src/components/footer.js, themes/gatsby-theme-blog/src/components/layout.js, themes/gatsby-theme-blog/src/components/toggle.js, themes/gatsby-theme-blog/src/context/theme-context.js, themes/gatsby-theme-blog/src/pages/index.js, themes/gatsby-theme-blog/src/templates/blog-post.js, themes/gatsby-theme-blog/src/utils/typography.js
This sets up the demo site in `themes/gatsby-starter-theme` to use the new `gatsby-theme-blog` theme.
Related to #14276
=> feat(themes): Use new blog theme in example

docs/docs/graphql-reference.md
fixes query that doesn't work currently
=> docs(graphql-reference): update group example query

.github/actions/high-priority-prs/index.js, .github/actions/high-priority-prs/process.js
Ignoring commits with messages like:
- ignore ```merge branch 'master'```
- ignore ```merge remote-tracking branch```
#14205
=> feat(high-priority-prs): ignore master merge commits

docs/starters.yml
=> chore(starters): add gatsby-starter-honey

docs/sites.yml
=> chore(showcase): add globalcitydata website

docs/sites.yml
=> chore(showcase): add wearebrew site to sites.yml

docs/sites.yml
Add Submittable website to potentially featured sites.
=> Add Submittable website

docs/contributing/code-contributions.md, docs/contributing/community.md
Adding the Core Maintainers meeting to some applicable community pages. Thanks @calcsam for the suggestion!
cc @m-allanson @calcsam @marcysutton thoughts?
=> feat(docs): add core maintainers meeting

docs/docs/creating-a-source-plugin.md
add Link to createParentChildLink doc
=> chore(doc): add Link to createParentChildLink doc

docs/docs/creating-a-source-plugin.md
fix typo in creating-a-source-plugin
=> chore(docs): fix typo in creating-a-source-plugin

docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md, docs/blog/2019-05-03-how-gatsby-helped-jump-start-my-engineering-career/index.md, docs/contributing/docs-contributions.md, docs/contributing/triaging-github-issues.md, docs/docs/gatsby-core-philosophy.md, docs/docs/glossary.md, docs/starters.yml, packages/gatsby-plugin-facebook-analytics/README.md, packages/gatsby-transformer-react-docgen/src/on-node-create.js
=> chore(docs): Change Github to GitHub, Javascript to JavaScript and Typescript to TypeScript

docs/docs/mdx/getting-started.md, docs/docs/mdx/writing-pages.md
Relating to problems experienced in this thread: https://twitter.com/ericclemmons/status/1133971242023772161
=> chore(docs): add filesystem source notes to docs

docs/sites.yml
=> chore(showcase): Add Appmantle to showcase

docs/docs/creating-a-source-plugin.md
=> chore(docs): updated selections in link

docs/docs/schema-customization.md
=> fix(docs): update example to use correct frontmatter path

packages/gatsby-plugin-feed/README.md
=> chore(docs): fix spelling on gatsby-plugin-feed

docs/starters.yml
Humbly requesting that my starter be added to the Gatsby Starter Library
=> chore(starters): add gatsby-starter-developer-diary

docs/sites.yml
Add Statistics Dashboard for Gatsby GitHub repository website
=> chore(showcase): Add Gatsby GitHub Stats site

docs/sites.yml
=> added graphicintuitions.com

docs/sites.yml
Added the website https://www.smooper.com which I've created using gatsbyjs
=> added smooper.com

docs/starters.yml
added gatsby-starter-paradigmshift design by HTML5 UP
None
=> chore(starters): add gatsby-starter-paradigmshift

docs/sites.yml
I recently moved my website off gh-pages, and I forgot to update the link here.
=> chore(showcase): replace hermanya.github.io with starikov.dev

docs/starters.yml
added gatsby-starter-phantom design by HTML5 UP
None
=> chore(starters): add gatsby-starter-phantom

www/package.json
Use https://github.com/gatsbyjs/gatsby/pull/14359 on gatsbyjs.org so we can test this PR and fix some rough edges.
#14359
=> feat(www): use per-page-manifest beta package

docs/sites.yml
Added a new site that uses Gatsby.
=> chore(showcase): Add Timeline of Terror

docs/starters.yml
=> feat(starters-showcase): add gatsby-starter-internationalized

docs/sites.yml
Added [myweekinjs](https://www.myweekinjs.com/) to Gatsby Showcase
=> feat(showcase): add myweekinjs site

docs/sites.yml
We just launched our gatsby-based marketing site last week. We really enjoyed the developer experience, the performance we are seeing now is _astounding_. We are proud to show off that we use Gatsby!
=> Add Pill Club to sites.yml

www/src/views/showcase/index.js
Just a small typo correction :+1: 
n/a
=> fix(showcase): fix typo

packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
Somehow the tapable warnings became errors without a webpack major version
release. This fixes that.
fixes #13775
It seems that this looks like a larger change than it is. The changes in this PR are the addition of two of these hook references:
```
resolver.hooks.describedRelative
```
and one tapAsync
```
resolver.hooks.relative.tapAsync(
`GatsbyThemeComponentShadowingResolverPlugin`,
(request, stack, callback) => {
```
=> fix(themes): Upgrade Tapable Calls

docs/sites.yml
Add site showcasing Carine roitfeld
=> feat(showcase): add carine roitfeld site

docs/starters.yml
Add starter template!
https://github.com/JaeYeopHan/gatsby-starter-bee
=> chore(starter): Add new starter template

docs/docs/gatsby-cli.md, packages/gatsby-cli/README.md, packages/gatsby-cli/src/create-cli.js
It implements a help message about plugin authoring as suggested by @shannonbux 
Related #13376
=> feat(gatsby-cli): Add a plugin authoring help in gatsby-cli

docs/sites.yml
Unifies the Tandem URLs listed in the sites showcase.
n/a
=> fix(showcase): Updates Tandem URLs

docs/contributing/community-contributions.md, docs/contributing/setting-up-your-local-dev-environment.md
Link broken on gatsbyjs.org but working in relative repo.
=> Fix(docs) broken links

docs/sites.yml
=> chore(showcase): Add the edit suite

docs/sites.yml
* Added Goulburn Physiotherapy to sites.yml
Added Goulburn Physiotherapy to sites.yml
=> Add Goulburn Physiotherapy to sites.yml

docs/sites.yml
Adding the new TomTom Traffic Index website created in Gatsby and just released.
n/a
=> chore(showcase): Add TomTom Traffic Index website

docs/starters.yml
This is a [starter](https://github.com/hasura/gatsby-gitbook-starter) to build documentation/tutorial web apps using Gatsby and MDX. It is styled based on GitBook and is fully configurable and customisable.
=> chore(starters): add gatsby-gitbook-starter

docs/sites.yml
Hi!
I've been working on this site for the past year. Went through
3 redesigns before both the client and I were both happy. Kinda scared to show it to the world yet,
but we need some quality links for SEO 😂
I just wanna thank this wonderful community for being so helpful and kind to
to newbies. Special thanks to @KyleAMathews for being awesome esp. when I first started and when I attended your workshop last year.
I will def pay it forward and help others as well 💪
Added two new categories:
- 3D printing
- Manufacturing
=> chore(site-showcase): added printaworld and two other categories

docs/docs/building-apps-with-gatsby.md
Corrected a minor typo, changed defualt to default
=> Corrected minor typo defualt to default

docs/tutorial/part-zero/index.md
Apparently the xcode-select may no longer work. So, added alternative instructions that I tested myself.
=> Update instructions for installing XCode CLI

examples/hn/gatsby-node.js
Another automation test
Reverts gatsbyjs/gatsby#14589
=> Revert "Update gatsby-node.js"

docs/starters.yml
added gatsby-starter-directive design by HTML5 UP
None
=> chore(starters): add gatsby-starter-spectral

docs/starters.yml
added gatsby-starter-directive design by HTML5 UP
None
=> chore(starters): add gatsby-starter-directive

docs/docs/adding-a-list-of-markdown-blog-posts.md
In US English, we prefer `customize` to `customise`.
=> chore(docs): fix spelling in adding blog post doc

docs/blog/2019-06-08-delicious-simplicity-case-study-part-1/index.md
=> chore(docs): fix yaml error on blog post

docs/docs/tailwind-css.md
=> Updated the broken quick start link

docs/docs/adding-search-with-js-search.md
Fixed typos (`perfom` to `perform`)
=> docs: fix typos in adding search with js-search doc

docs/docs/adding-markdown-pages.md
=> docs: fix typo in adding markdown pages doc

docs/blog/2019-06-03-integrating-graphiql-explorer/index.md
`<source>` is not needed to close so I removed `</source>`.
cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
=> style(blog): remove unnecessary closing tags

packages/gatsby-remark-graphviz/package.json, packages/gatsby-remark-graphviz/src/__tests__/index.js, packages/gatsby-remark-graphviz/src/index.js
First commit just adds some basic tests - when tests are hopefully red, will push another commit that actually fixes it
=> fix(gatsby-remark-graphviz): fix graphviz on node < 10

www/package.json
=> fix(www): Bump up to gatsby-remark-graphviz@1.0.11 to fix builds on Node < 10

docs/sites.yml
Add `https//:asjas.co.za` website to Gatsby Showcase
=> feat(showcase): Add Asjas Gatsby Site

docs/docs/winning-over-marketers.md
For some reason it's not linked here!
=> chore(docs): add link to Linda's blog post

www/src/components/api-reference/index.js, www/src/pages/docs/browser-apis.js, www/src/pages/docs/node-apis.js, www/src/pages/docs/ssr-apis.js
=> fix(www): temporary workaround to fix .org builds

www/package.json
=> Lock `www` Gatsby version @2.8.8

docs/starters.yml
=> chore(starters): gatsby-starter-github-api

docs/sites.yml
Add glug-infinite site to showcase
=> chore(showcase): Add Glug-Infinite site to showcase

docs/docs/adding-search-with-algolia.md
Found a couple of typos when following along with the Algolia Search tutorial.
=> chore(docs): fix typos for adding search with algolia

packages/gatsby/src/db/common/query.js, packages/gatsby/src/schema/__tests__/queries.js, packages/gatsby/src/schema/resolvers.js
=> fix(gatsby): Fix group and distinct when used with fragments

docs/sites.yml
Updated links and corrected spellings
=> chore(sites): fix spelling and link for Cirston Macarenhas

docs/docs/sourcing-from-sanity.md, packages/gatsby/src/redux/actions/internal.js, packages/gatsby/src/redux/actions/public.js
=> fix(gatsby): Make createPageDependency public again

docs/blog/2019-06-10-how-to-recognize-when-gatsby-is-a-good-fit-for-your-client/index.md
Request from @stephen-gatsby to change the markdown quote to a pullquote:
Becomes:
=> fix: change md quote to pullquote

www/src/components/banner.js
Add details of the new webinar to .org:
=> fix(www): Update webinar banner for upcoming - ImpossibleFoods 

docs/docs/gatsby-core-philosophy.md
Link to @jlengstorf's You Belong Here talk in our philosophy section.
=> chore(docs): include link to Jason's You Belong Here talk

docs/sites.yml
=> chore(showcase): add Bytom Blockchain

docs/starters.yml
=> chore(starters): Add Yellowcake to starters

.github/actions/high-priority-prs/src/process-data.js
Ideally this'd be automated, but manual updates will do for now.
=> chore(actions): Add Kyle G to list of maintainers

docs/docs/upgrading-node-js.md
Add docs on Gatsby's Node support policy, and how to upgrade from Node 6
<details>
<summary>View screenshot </summary>
</details>
Related #14231
=> feat(docs): Add documentation on upgrading from Node 6

docs/contributing/creating-pull-requests.md, docs/contributing/managing-pull-requests.md, www/src/data/sidebars/contributing-links.yaml
Documentation on how to manage Pull Requests! 
<details><summary>Rendered View</summary>
</details>
Fixes https://github.com/gatsbyjs/gatsby/issues/12094
=> docs(www): Managing Pull Requests 

docs/docs/end-to-end-testing.md
Added a section on how to write accessibility tests with cypress in the [End to end testing page](https://www.gatsbyjs.org/docs/end-to-end-testing/).
Addresses #13473
=> docs: end to end testing writing tests.

docs/contributing/docs-templates.md, docs/docs/gatsby-image.md
Two small changes we need for workflows:
- a note about not necessarily needing GraphQL or Gatsby Image on the new API doc
- instructions for adding new recipe categories
=> feat(docs): image and recipe docs updates

docs/docs/bulma.md, www/src/data/sidebars/doc-links.yaml
I wrote a short guide for using bulma.io with Gatsby. It shows the simple steps to get started.
No related issue. 
The "request" for this can be seen from this [tweet by @gatsbyjs](https://twitter.com/gatsbyjs/status/1139986394225336321).
=> Added a guide for Bulma.io

docs/starters.yml
just renamed it and moved it to a new url
=> chore(staters):rename Gatsby Starter Anoun #1

docs/tutorial/prismic-source-graphql-tutorial.md
- Corrected the typo in the title
- Corrected typo on localhost:8000 link
=> chore(docs): Update prismic-source-graphql-tutorial.md

docs/starters.yml
added gatsby-starter-fractal design by HTML5 UP
None
=> chore(starters): add gatsby-starter-fractal

docs/sites.yml
It has changed to using Next.js so I removed it from the showcase
=> chore(showcase): Remove McDonald's Design System site

docs/docs/glossary.md
This PR fixes broken href's in _glossary.md_.
=> Fix broken glossary hrefs.

packages/gatsby-cli/package.json, packages/gatsby-cli/src/reporter/reporters/ink/components/develop.js, yarn.lock
Add node fetch dependency to package.json & explicit require
fixes #14905
=> fix(gatsby-cli): add missing node-fetch dependency

docs/sites.yml
=> chore(sites): fix inactive/invalid Gatsby sites in site showcase

docs/sites.yml
Changed TLD from `me` to `dev` for personal site. Thanks @DSchau for the heads up
Reference #14929
=> chore(sites): fix personal site for showcase

docs/sites.yml
Add the website of The Coffee Collective to showcases.
=> chore(showcase): Add Coffee Collective website

docs/sites.yml
=> fix(showcase): Remove developerecosystem.com

docs/starters.yml
Add new starter `gatsby-starter-quiet`
=> chore(starters): add gatsby-starter-quiet

www/package.json
enables a beta build on www to see if the new PR reduces the amount of failing page-data.json requests.
Related to #14889
=> feat(www): enable new resource-loading feature

docs/sites.yml
=> chore(showcase): Add nehalist.io

docs/starters.yml
Gatsby Starter: Resume/CV Site with Prismic integration :heart:
[Preview here](https://compassionate-morse-5204bf.netlify.com/)
=> chore(starters): add gatsby-starter-prismic-resume

docs/docs/visual-testing-with-storybook.md
i have added the rule for use storybook with typescript.
=> docs: add storybook V5 configuration for typescript project

docs/starters.yml
added gatsby-starter-resume design by startbootstrap
=> chore(starters): add gatsby-starter-resume

docs/sites.yml
=> chore: fix domain issue for GreenOrbit

docs/sites.yml
Adding March And Ash website to Gatsby's site showcase
=> chore(showcase): Add March And Ash site

peril.settings.json
This should fix the new issue and stale rules not running.
=> fix(peril): Fix missing dir name

docs/docs/mdx/getting-started.md, docs/docs/mdx/index.md, docs/docs/mdx/plugins.md, docs/docs/mdx/programmatically-creating-pages.md
=> docs: Replace gatsby-mdx by gatsby-plugin-mdx

docs/contributing/docs-contributions.md, docs/contributing/docs-templates.md
We've gotten some repeated questions about recipes and I've seen a few PRs linking broken images to GitHub, so I updated the contributing docs to clarify these items.
N/A
=> fix(docs): updates for contributing to recipes and docs

docs/blog/2019-06-25-profitable-agency-wordpress/index.md
Update quotes to pullquotes on most recent blog post as per request from @lindaleebumblebee 
<details>
<summary>Screenshot</summary>
</details>
=> fix(blog): pullquotes and linking updates

docs/docs/end-to-end-testing.md
=> fix(docs): add missing comma to code example

packages/gatsby-telemetry/src/telemetry.js, packages/gatsby/src/db/loki/nodes.js, packages/gatsby/src/redux/actions/public.js
To better understand how the nodes are created and updated
=> chore(telemetry): Track createNode utilization

docs/docs/client-data-fetching.md
This Pull Request aims to add context about hydration and build and run time to be easier to understand particularly for beginners
Addresses https://github.com/gatsbyjs/gatsby/issues/14938
=> add context to client data fetching page aiming to be easier to understand

docs/docs/static-vs-normal-queries.md
Added the difference between Static query and Page query
=>  added How StaticQuery differs from page query

docs/docs/sharing-components-across-websites.md
Added Bit (https://github.com/teambit/bit) as an open source tool for sharing components between websites and applications, to increase code reuse and reduce overhead (and copy-pasting).
Key benefits are:
1. Automatic isolation (dependencies, environments etc) of components from the source website for reuse in other projects. This helps to avoid copy-pasting code which can be a painful practice and lead to technical debt.
3. Development and changes to components can be done from any consuming website project, so you can easily adjust the shared component to any new website.
4. Control over both source-code changes and dependency updates to the component across websites.
5. Discoverability and collaboration for shared components.
=> Update sharing-components-across-websites.md / Bit

docs/contributing/how-to-make-a-reproducible-test-case.md
Updated the Title to " How to make a minimal reproduction "
Addresses #15147
=> docs(www): updated title for Minimal Reproduction doc for SEO

README.md
Changes "modern framework" into "modern web framework"
=> docs: update readme with modern web framework

docs/starters.yml
=> chore(starters): add gatsby-ghub

docs/starters.yml
Added Apollo Client feature in starter yml
=> chore(starters): updating gatsby-ghub with feature

packages/gatsby-plugin-page-creator/README.md
=> Make clear you can add additional instances to add additional pages folders

docs/sites.yml
Update March and Ash title, and built by
=> chore(showcase): Update March and Ash details

docs/sites.yml
Adding the website of Prism programming language.
=> chore(sites): - add prism lang website

themes/gatsby-theme-blog/gatsby-node.js, themes/gatsby-theme-blog/src/components/post-footer-content.js, themes/gatsby-theme-blog/src/components/post.js, themes/gatsby-theme-blog/src/components/posts.js, themes/gatsby-theme-blog/src/templates/post.js
Replace the queries for `Mdx` with queries for `BlogPost`. This provides a better potential for future compatibility with generic data interface work.
=> gatsby-theme-blog: Mdx -> BlogPost

docs/sites.yml
I've add arnondora.in.th which using Gastby to build to showcase
=> chore(showcase): Add arnondora.in.th

.gitignore, themes/gatsby-starter-blog-theme/package-lock.json, themes/gatsby-starter-notes-theme/package-lock.json, themes/gatsby-starter-theme/package-lock.json
Because our starters typically have a `package-lock.json`
=> chore(themes): Add lock files for theme starters 

.circleci/config.yml, lerna.json, renovate.json, scripts/clone-and-validate-theme-starters.sh
This is temporary until theme packages are moved over to `/packages` and theme starters are moved over to `/starters`
CC @amberleyromo @ChristopherBiscardi
=> chore(scripts):  mirror theme starters to independent repos and add theme packages to lerna

packages/gatsby-plugin-feed/package.json, packages/gatsby-source-contentful/package.json, packages/gatsby/package.json, yarn.lock
Updates relevant package.json file to use ^15 of hapi/joi.
Fixes #15237
=> chore: update @hapi/joi to ^15.0

themes/gatsby-starter-blog-theme/package-lock.json, themes/gatsby-starter-blog-theme/package.json, themes/gatsby-starter-notes-theme/package-lock.json, themes/gatsby-starter-notes-theme/package.json, themes/gatsby-starter-theme/package-lock.json, themes/gatsby-starter-theme/package.json
=> chore(themes): update starters

docs/starters.yml
Added a new starter that uses Snipcart.
=> chore(starters): add gatsby-snipcart-starter

themes/gatsby-starter-blog-theme/package-lock.json
I had partial changes to package-lock file that I didn't commit in https://github.com/gatsbyjs/gatsby/pull/15366 - this should fix this
=> fix(gatsby-starter-blog-theme): fix package-lock

www/src/components/banner.js
updated the copy and link for the upcoming IBM themes webinar
=> fix(www): copy on banner for IBM Themes Webinar

docs/blog/2018-11-27-gatsby-days/index.md
=> Remove image that breaks blog post

docs/starters.yml
added gatsby-starter-stylish design by startbootstrap
=> chore(starters): add gatsby-starter-stylish

packages/gatsby-plugin-offline/package.json, yarn.lock
add slash as a dependency of gatsby-plugin-offline
#15372
=> add slash as dependency to gatsby-plugin-offline, Fix #15372

www/src/data/diagram/static-hosts.yml
Update Static Web Host Surge.sh URL on main page
=> docs: update surge url

docs/sites.yml
Documentation: add site to sites.yml for sites-showcase
Adding easyfloh.com to sites-showcase
NA
=> chore(showcase): add easyfloh

docs/starters.yml
Updated the list of features provided by my TypeScript starter.
=> Update gatsby-starter-typescript features

packages/gatsby-telemetry/package.json, packages/gatsby-telemetry/src/__tests__/repository-id.js, packages/gatsby-telemetry/src/repository-id.js, packages/gatsby-telemetry/src/telemetry.js, yarn.lock
Please coordinate the release with me
=> chore(telemetry) clean up, optimize and improve repositoryId detection

docs/starters.yml
=> chore(starters): add lewis-gatsby-starter-basic

docs/docs/making-components-discoverable.md
Expanded the stub and added a more elaborate (yet short) description on the advantages of discoverability for reusing modular components, added bit's shared component hub, elaborated on storybook and added styleguidist for component discoverability.
=> docs(www): Update making-components-discoverable.md / Expand

docs/sites.yml
Add kingsdesign.com.au to showcase (sites.yml)
No issue
=> chore(showcase): Add KingsDesign to showcase

docs/tutorial/using-a-theme.md
Replace `gatsby-theme-ui` with `gatsby-plugin-theme-ui`
=> Fix `gatsby-plugin-theme-ui` references

packages/gatsby-plugin-sharp/src/__tests__/process-file.js, packages/gatsby-plugin-sharp/src/process-file.js
updated sharp plugin to sort nested options
Fixes #14551
=> fix(gatsby-plugin-sharp): sort nested options

docs/sites.yml
Add my personal blog to showcase sites
=> chore(showcase): Add devahoy site to showcase list

docs/sites.yml
=> feat(showcase): Add HomeAlarmReport.com

docs/sites.yml
Add onramp.io and writespeakcode.com to the showcase
None
=> chore(showcase): Add onramp and write speak code to showcase

docs/sites.yml
=> chore(showcase): Add Venus Lover to showcase

docs/sites.yml
=> chore(showcase): Added Cosmotory to showcase

packages/gatsby/package.json, packages/gatsby/src/utils/gatsby-dependents.js, yarn.lock
Fixes https://github.com/gatsbyjs/gatsby/issues/15460
=> fix(gatsby): Fix support for yarn workspaces in gatsby-dependents

docs/docs/localization-i18n.md
Just an update to react-intl links
=> docs(localization-i18n.md): fix react-intl links

docs/sites.yml
=> chore(showcase):Updated main_url of Cosmotory

docs/starters.yml
Add a starter that based on [gatsby-serif-theme](https://github.com/JugglerX/gatsby-serif-theme), rewrite with Tailwind CSS, [demo](https://gatsby-tailwind-serif.netlify.com/)
=> chore(starters): add gatsby-tailwind-serif

www/src/components/__tests__/banner.js, www/src/components/banner.js
Pretty self explanatory really.
=> chore(www): update banner text to point users to Gatsby Preview

docs/blog/2019-07-11-user-testing-accessible-client-routing/index.md
When I shared this post in Slack, it became apparent that the excerpt could be worded better. I updated it to include the desired outcome: to make better decisions about accessible page changes in sites built with Gatsby, React, and beyond. I added a few more tags, too!
N/A
=> [blog] update excerpt with desired outcome

packages/gatsby-cli/src/structured-errors/error-map.js, packages/gatsby/src/redux/__tests__/__snapshots__/pages.js.snap, packages/gatsby/src/redux/actions/public.js
=> fix(gatsby): Make createPage action errors structured

docs/sites.yml
Adding marcelhauri.ch to showcase
=> chore(showcase): Add marcelhauri.ch to showcase

packages/gatsby/cache-dir/__tests__/__snapshots__/dev-loader.js.snap, packages/gatsby/cache-dir/__tests__/dev-loader.js, packages/gatsby/cache-dir/dev-loader.js
We didn't add the `notFound = true` field to our dev-404-page which means we were showing a blank page when a 404 doesn't exist.
I changed the baseLoader into prodLoader and copied tests over to dev-loader as well.
Error before fix:
https://github.com/gatsbyjs/gatsby/issues/15429
=> fix(gatsby): blank dev-404-page when no custom 404 page found

docs/starters.yml
Adds gatsby-mdx-netlify-cms to the starters list.
N/A
=> chore(starters): Added gatsby-mdx-netlify-cms

CODE_OF_CONDUCT.md
Added a `CODE_OF_CONDUCT.md` file to root with link to side to make it more visible from GitHub. 
I realized last week I wasn't sure if Gatsby had a CoC. Reason being I'd never seen this file in the repository. Thought adding it here would make it a little more visible to the community. Thanks.
=> chore: and CoC link to repo

docs/starters.yml
Add a starter based on gatsby-starter-blog, with breadcrums and i18n supported.
=> chore(starters): Added gatsby-simple-blog

docs/sites.yml
=> chore(showcase): add Anthony Boyd Graphics

docs/starters.yml
Seems like I accidentally removed a starter when fixing a conflict on #15482
=> chore(starter): bring back starter gatsby-simple-blog

packages/gatsby-cli/src/reporter/index.js
Start tracking bootstrap times 
This change doesn't require any upstream changes
=> chore(telemetry): collect bootstrap times

.circleci/config.yml, e2e-tests/themes/development-runtime/.gitignore, e2e-tests/themes/development-runtime/README.md, e2e-tests/themes/development-runtime/cypress.json, e2e-tests/themes/development-runtime/cypress/fixtures/example.json, e2e-tests/themes/development-runtime/cypress/integration/components.js, e2e-tests/themes/development-runtime/cypress/integration/pages.js, e2e-tests/themes/development-runtime/cypress/integration/site-metadata.js, e2e-tests/themes/development-runtime/cypress/plugins/index.js, e2e-tests/themes/development-runtime/cypress/support/index.js, e2e-tests/themes/development-runtime/gatsby-browser.js, e2e-tests/themes/development-runtime/gatsby-config.js, e2e-tests/themes/development-runtime/package.json, e2e-tests/themes/development-runtime/src/gatsby-theme-about/components/time.js, e2e-tests/themes/development-runtime/src/pages/contact.js, e2e-tests/themes/development-runtime/src/pages/index.js, e2e-tests/themes/development-runtime/src/pages/shadowed.js, e2e-tests/themes/gatsby-theme-about/package.json, e2e-tests/themes/package.json
Follow up to https://github.com/gatsbyjs/gatsby/pull/15637
=> chore(themes): Add development runtime tests

packages/gatsby-cypress/src/commands.js
=> feat(gatsby-cypress): Add ability to pass in options in getTestElement

docs/blog/2019-07-15-theme-jam-contest/index.md
Blog post outlining details of Theme Jam contest, including resources on how to build a theme, and submission guidelines.
This has already been reviewed by [Linda](@lindaleebumblebee), but typographical edits/suggestions are welcome.
=> feat(blog): add Theme Jam blog post

.circleci/config.yml
… more RAM
Previous run OOM'd - https://circleci.com/gh/gatsbyjs/gatsby/172852
=> chore: CI larger machine size

.circleci/config.yml
Still failing - adding maximum RAM.
https://circleci.com/gh/gatsbyjs/gatsby/172904
=> chore: update CI config

docs/docs/mdx/getting-started.md
=> Don't use npx or yarn for installation instructions

.circleci/config.yml
- Sequence build then deploy
- Fix install command
Continues from https://github.com/gatsbyjs/gatsby/pull/15801
=> chore: CI www sequence

.circleci/config.yml
=> chore: cpu count for www ci build

.circleci/config.yml
=> chore: Fix bad key name

.circleci/config.yml
Link to the workflow instead of specific job
=> chore: link to Circle CI workflow

.circleci/config.yml
=> chore: fix cache restore names again

examples/client-only-paths/gatsby-config.js, examples/client-only-paths/package.json
=> fix(example): add client-only-paths rewrites to demo site

www/package.json, www/src/components/feedback-widget/widget-wrapper.js, www/src/components/sidebar/sticky-responsive-sidebar.js
- Courtesy of @fk 
- Blocked till www works with the breaking change in v1
- Set to ~1.0.0 as per recommendation in packages/gatsby-design-tokens/README.md
=> chore(www): Upgrade to design tokens v1

docs/docs/hosting-on-netlify.md
Several [word choice](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#use-you-as-the-pronoun), [formatting](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#grammar-and-formatting) and [readability](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#avoid-emojis-slang-and-metaphors) improvements to "Hosting on Netlify" documentation :mag:
=>  chore(docs): Reformat "Hosting on Netlify" docs 

docs/sites.yml
Adds LaunchDarkly marketing site to showcase
=> chore(showcase): adds LaunchDarkly marketing site

packages/gatsby-cli/package.json, packages/gatsby-cli/src/reporter/reporters/ink/components/messages.js, packages/gatsby-cli/src/reporter/reporters/ink/reporter.js, yarn.lock
Fixes ink not showing all text.
Old:
New:
Fixes #14658
=> fix(gatsby-cli): fix cut off text

www/src/components/code-block/index.js, www/src/utils/typography.js
This fixes some design issues that @fk identified. Thanks Flo!
=> fix(www): back-port typography fixes and change structure

docs/tutorial/building-a-theme.md
=> fix(docs): Fix typos in Building a Theme tutorial

docs/blog/2018-11-01-hacktoberfest-wrapup/index.md, docs/blog/2018-12-17-turning-the-static-dynamic/index.md, docs/blog/2019-07-03-using-themes-for-distributed-docs/index.md, docs/starters.yml, packages/gatsby-transformer-documentationjs/src/gatsby-node.js, scripts/check-repo-fields.js
=> chore(*): fix typos

docs/blog/2018-11-01-hacktoberfest-wrapup/index.md
https://github.com/gatsbyjs/gatsby/pull/15946#pullrequestreview-264785098
/cc @LekoArts
=> Revert to Hacktoverfest

docs/sites.yml
Adds Carbon8 Regenerative Agriculture to Gatsby Showcase:
https://www.carbon8.org.au/
=> chore(showcase): Add Carbon8 Regenerative Agriculture

docs/sites.yml
Would like to add my website to Gatsby showcase :)
=> chore(showcase): Add Jana Desomer website to showcase

packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.js.snap, packages/gatsby-dev-cli/src/__tests__/watch.js, packages/gatsby-dev-cli/src/watch.js, packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.js.snap, packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.js.snap
=> test(gatsby-dev-cli): don't use yarn workspaces code path for tests

packages/gatsby/src/schema/extensions/__tests__/field-extensions.js
=> fix(gatsby): Use UTC dates in test

docs/sites.yml
=> chore(showcase): added reactgo blog

www/src/components/__tests__/copy.js, www/src/components/code-block/__tests__/index.js, www/src/components/copy.js, www/src/utils/__tests__/copy-to-clipboard.js, www/src/utils/copy-to-clipboard.js
Shout-out @wardpeet for letting me know about the feature _and_ for not blocking the other PR to introduce it. The real MVP 🙌
Follow-up to #15983
=> refactor(www): use new clipboard.writeText API if it exists

packages/gatsby-telemetry/src/__tests__/error-helpers.js, packages/gatsby-telemetry/src/error-helpers.js, packages/gatsby-telemetry/src/telemetry.js
We have two convenience functions for tracking errors, this cleans up and unifies the structured error processing for both.
=> chore(telemetry): Clean up error sanitization

docs/starters.yml
Adds my [DatoCMS Starter](https://gatsby-datocms-starter.netlify.com/) to the starters list.
=> chore(starters): add gatsby-datocms-starter

docs/contributing/where-to-participate.md
=> Adding space in bug fixes

docs/sites.yml
=> chore(showcase): Add Saxenhammer & Co.'s site

examples/using-i18n/README.md
Updated the demo url from gatsby.org, which errored out, to the updated Netlify link I received.
=> chore(example): update demo URL for using-i18n

docs/docs/using-fragments.md
Fix GraphQL query on [Using GraphQL Fragments](https://www.gatsbyjs.org/docs/using-fragments/).
=> fix(docs): Fix GraphQL query

docs/starters.yml
Since moving the starter to be using my theme, I removed a bunch of stuff from the starter. Also aligned the description and features with the README of my starter.
=> chore(starters): Update gatsby-starter-portfolio-emma

docs/sites.yml
Changed two minor things on my personal site and added [themes.lekoarts.de](https://themes.lekoarts.de) to the showcase 👍
=> chore(showcase): Update lekoarts.de and add themes.lekoarts.de

docs/docs/introducing-graphiql.md, docs/tutorial/part-five/index.md
Embed GraphiQL explorer screencast in docs.
=> feat(docs): embed graphiql explorer screencast

packages/gatsby-plugin-sitemap/README.md
- Replaces an outdated link with the latest permalink
https://github.com/gatsbyjs/gatsby/pull/5059
=> docs(gatsby-plugin-sitemap): Fix an outdated link

docs/starters.yml
Adding my first Starter Blog to GatsbyJS
=> chore(starters): add AdvancedBlog

docs/sites.yml
=> chore(showcase): Add Cade Kynaston portfolio

docs/tutorial/building-a-theme.md
under event template & events template heading, codes were misplaced, this PR fixes them.
=> docs: fixed minor issue in building-a-theme.md tutorial

docs/sites.yml
=> chore(showcase): Add larsroettig.dev

docs/blog/2019-06-26-live-preview-for-drupal/index.md
There was 1 broken link as well as a link that @lindaleebumblebee wanted changed on the latest blog post about Drupal with Gatsby Preview, this addresses both of those.
=> fix(blog): correct blog links

docs/sites.yml
Pull request to add [Growable site](https://www.growable.io/) to the showcase section
No related issue
=> chore(showcase): Add Growable.io

docs/sites.yml
=> feat(showcase): Add https://simonkoelewijn.nl to showcase

www/src/templates/__tests__/template-starter-page.js, www/src/templates/template-starter-page.js
Wasn't falling back like we were expecting 🙄 JavaScript is hard.
=> fix(www): be fault tolerant for screenshots for starters

docs/docs/mdx/programmatically-creating-pages.md
Added missing parentheses to code example in [MDX tutorial](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages). 
None.
=> Add missing parentheses to docs

docs/sites.yml
=> chore(showcase): Added Raconteur Careers to showcase

packages/gatsby/src/utils/websocket-manager.js
Fixes https://github.com/gatsbyjs/gatsby/issues/15724
=> fix(gatsby): Check if page exists before trying to get page data

docs/sites.yml
Adds Frankly Steve to Gatsby Showcase:
https://www.franklysteve.com/
=> chore(showcase): Add Frankly Steve

packages/gatsby-plugin-sitemap/README.md
Fixes a few basic punctuation mistakes
=> docs(gatsby-plugin-sitemap): Improve grammar

docs/starters.yml
Updated the starter to use a new theme
=> chore(starters): Update Cara entry

docs/tutorial/writing-documentation-with-docz.md
fixed reference to wrong theme in gatsby config in docs
=> docs(tutorial): Update writing-documentation-with-docz

packages/gatsby-cli/src/init-starter.js, packages/gatsby/src/commands/repl.js
Improve tracking for repl and project creation
=> chore(gatsby): Track repl usage in telemetry

docs/docs/localization-i18n.md
=> Fix typo i118n -> i18n

docs/docs/working-with-images-in-markdown.md
=> Revert "docs(gatsby-plugin-mdx): Add gatsby-remark-images to list of plugins for gatsby-plugin-mdx"

packages/gatsby-telemetry/package.json, packages/gatsby-telemetry/src/postinstall.js
Reverts the revert in https://github.com/gatsbyjs/gatsby/pull/16294 and actually fixes https://github.com/gatsbyjs/gatsby/issues/16254
=> fix(gatsby-telemetry): Add back fix and fix files in package.json

docs/docs/recipes.md
Update starter and theme recipe sections to align better with the new recipe structure.
=> feat(docs): update starter and theme recipe sections

docs/sites.yml
Adding DIA Supermercados to Showcase
=> chore(showcase): adding DIA Supermercados to Showcase

docs/docs/schema-customization.md
Documents the `@nodeInterface` type extension added in Gatsby 2.13.22.
=> docs: Add docs for @nodeInterface extension

docs/tutorial/building-a-theme.md
=> docs: Update building-a-theme.md

docs/docs/winning-over-engineering-leaders.md
Just a quick fix from the letter, "Y" to the word "Yes"
=> docs: fix typo on winning-over-engineering-leaders.md

docs/docs/testing-css-in-js.md
=> docs: Update import for Emotion 10

docs/docs/working-with-images-in-markdown.md
Fix typo in `Inline images with gatsby-remark-images` section.
=> docs: Update working-with-images-in-markdown.md

docs/starters.yml
Fully-featured AWS Amplify Auth w/ GatsbyJS.
=> chore(starters): add gatsby-starter-auth-aws-amplify

packages/gatsby-plugin-google-analytics/README.md
Grammatical errors in the README file are corrected.
=> docs(gatsby-plugin-google-analytics): Grammatical errors fixed in README

themes/gatsby-theme-blog/gatsby-node.js
Remove extra use of "//" in comment.
=> fix(gatsby-theme-blog): extra // in comment

packages/gatsby/index.d.ts
fix: update GatsbyNode typings adding `createSchemaCustomization` typings
=> fix(gatsby): createSchemaCustomization typings

docs/sites.yml
Add [QuantumBlack](https://www.quantumblack.com/) to sites.yml so it can be featured in the Site Showcase
=> chore(showcase): Add QuantumBlack

docs/starters.yml
Fixed broken link (I changed my Github username, had to update the link to the starter as a result)
=> chore(starters): Update username in starter entry

docs/sites.yml
Add marketing site for a Toronto web design + videography agency to the Showcase.
=> chore(sites): add coffee shop creative

docs/docs/themes/what-are-gatsby-themes.md
Sentence case article subheader re: [#format-titles-and-headers](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#format-titles-and-headers)
Plus, minor grammar tweak "But" -> "However," :mag:
=> chore(docs): Clean up "What Are Gatsby Themes?" doc

docs/starters.yml
=> chore(starters): add crafty

docs/sites.yml
docs: added dailyhn.com to the showcase
Added dailyhn.com to the showcase; sites.yml
<none>
=> docs(showcase): added dailyhn.com

www/src/components/docs-table-of-contents.js
This PR adds an active style to the selected ToC item.
=> feat(www): Add active style for TableOfContents

.circleci/config.yml, e2e-tests/production-runtime/cypress/integration/accessibility.js, e2e-tests/production-runtime/cypress/integration/compilation-hash.js, e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js
See #16495
hopefully this should pass on CI at least ...
=> fix(tests): Disable broken offline tests

docs/starters.yml
=> chore(starters): add the404blog

packages/gatsby-plugin-canonical-urls/README.md, packages/gatsby-transformer-hjson/README.md
Fixes some prism highlighter warnings.
=> chore: correct code block language tags

docs/sites.yml
Removing my wife's blog, we are still using Gatsby but some crazy creepy people starting sending her facebook messages on her facebook page and asking about how to work with Gatsby and Contentful. 😞 
More info: https://twitter.com/khaled_garbaya/status/1160799359992303616
=> chore(sites): Remove Chocolate Free

docs/starters.yml
Add Gatsby Starter for [@geocine/gatsby-theme-origanization](https://github.com/geocine/gatsby-theme-organization)
=> chore(starters): add gatsby-starter-organization

docs/sites.yml
Gratsy is a static website powered by Whalar
=> chore(showcase): Add Gratsy

packages/gatsby-link/src/index.js
Minor refactor to have a more concise version.
N/A
=> chore(gatsby-link): Minor refactor

docs/tutorial/wordpress-source-plugin-tutorial.md
The filename is written as blog-posts.js a few lines above and following the example throws an error on terminal.
=> docs(wordpress-source-plugin-tutorial): blog-post.js file name should be blog-posts.js

docs/docs/tailwind-css.md
=> chore(docs): fix typo on tailwind page

docs/sites.yml
sites mostly finished :) more updates soon
=> feat(showcase): add deepThreads.com

packages/gatsby-link/src/index.js
Append v signifying version
N/A
=> chore(gatsby-link): Fix error message

docs/docs/post-css.md, docs/docs/sass.md, docs/docs/sourcing-from-drupal.md, docs/docs/sourcing-from-the-filesystem.md, docs/tutorial/part-eight/index.md
Basically Fixes about 5 Quick-Start Link URL bugs. One was in a blogpost(didn't edit that one though)
PS. Sorry for the 5 Commits :sweat_smile:
=> chore(docs): Fix links to Quick Start

docs/starters.yml
Add gatsby starter for [@rmagon/gatsby-starter-interviews](https://github.com/rmagon/gatsby-starter-interview)
=> chore(starters): Add gatsby-starter-interviews

docs/sites.yml
Added smoopit.com to sites.yml !
The landing page is built using Gatsby.
Smoopit helps you schedule meetings without the extra effort of checking your availability or back-and-forth emails.
=> chore(showcase): Add smoopit.com

docs/sites.yml
Updated some details for my site.
=> chore(sites): Update attejuvonen.fi

docs/starters.yml
Added new starter and modified tags for one older starter.
=> chore(starters): Add gatsby-starter-photo-book

docs/docs/recipes.md
A recipe for creating source nodes yourself.
I wrote it in the style that would have made sense to me when I was looking for this information in the recipes a few days ago. Meaning that the reader is not totally new to Gatsby, JavaScript and, GraphQL and knows where to find `gatsby-node.js` for example.
With that being said, all suggestions are more than welcome!
No related issue.
=> docs(recipes): Creating source nodes

themes/gatsby-starter-blog-theme-core/package-lock.json, themes/gatsby-starter-blog-theme-core/package.json, themes/gatsby-theme-blog-core/gatsby-config.js, themes/gatsby-theme-blog-core/package.json, themes/gatsby-theme-blog/gatsby-config.js, themes/gatsby-theme-blog/package.json
=> Release blogs

examples/using-jest/jest.setup.js, examples/using-jest/package.json
- jest-dom moved 
https://github.com/testing-library/dom-testing-library/issues/260
- cleanup-after-each is no longer required 
https://github.com/testing-library/react-testing-library/blob/master/cleanup-after-each.js
=> chore(using-jest): Update jest.setup

docs/categories.yml, docs/starters.yml
A boilerplate for a Gatsby app paired with a Hasura.
Features:
- Demonstrates both query and mutation from the linked Hasura project.
- Uses apollo react hooks for query and mutation.
=> chore(starters): add gatsby-hasura-starter

docs/sites.yml
Added our portfolio site to showcase.
=> chore(showcase): Add Mill3.studio

docs/sites.yml
Add my own portfolio website :)
=> chore(sites): add Dan Farrow portfolio

packages/gatsby-source-wordpress/src/normalize.js
=> fix(gatsby-source-wordpress): fix typo

docs/sites.yml
=> Add Cantas site

docs/sites.yml
Submit fullstackhq site to site showcase
None
=> submit fullstackhq to site showcase

docs/docs/programmatically-create-pages-from-data.md
Adds an example repo made by @jlengstorf to help Chris from Scotch.io while streaming on Twitch, as per suggestion from Chris: https://twitter.com/chrisoncode/status/1162038971439779845
=> docs: add example repo to creating pages programatically

peril/tasks/stale.ts
Noticed a missing space in the stale.ts template that gatsbot uses
None
=> chore(peril): fix typo/missing space

docs/sites.yml
Adding Sheringham Shantymen website
=> chore(sites): add Sheringham Shantymen

packages/gatsby-telemetry/src/event-storage.js
=> chore(gatsby-telemetry): Allow overriding API url from ENV

docs/sites.yml
=> chore(sites): Add Ronald Langeveld

docs/docs/gatsby-core-philosophy.md
=> chore(docs): Fix typo in Core Philosophy Page

docs/starters.yml
Fix typo in URL of `gatsby-starter-organization`
=> style(typo): fix typo

docs/sites.yml
=> chore(showcase): Add Golfonaut.io

.circleci/config.yml, package.json, yarn.lock
Because Azure pipelines are too slow
=> tests: Move Windows unit tests to CircleCI

docs/sites.yml
=> chore(showcase): Add antonsten.com

scripts/clone-and-validate-theme-starters.sh, scripts/publish-starters.sh
=> fix(ci): fail on errors with clone

docs/creators/creators.yml
Added a city that I currently live in for my creator description.
=> chore: Added my city to my creator description

docs/docs/awesome-gatsby.md
I think that Reddit is a good resource for getting help on Gatsby projects and growing as a Gatsby developer. I feel that the more quality resources here the better. Some people prefer Reddit over Dev.to like me, so getting another resource to choose from is better than only having two.
Modified .md to link to Gatsbyjs subreddit
=> docs: Add reddit link to Awesome Gatsby docs

docs/sites.yml
=> chore(showcase): add rashmiap.me

yarn.lock
Cleanup `yarn.lock` to deduplicate all packages.
I've used https://github.com/atlassian/yarn-deduplicate to do this.
=> chore: deduplicate yarn.lock packages

docs/sites.yml
Adding my Gatsby-based site to the showcase site list
=> chore(showcase): Add sheelahb.com

docs/tutorial/part-four/index.md
Add extra space to separate paragraphs, add missing punctuation, replace unnecessary uppercase character for lowercase
=> Minor text modifications for clarity

docs/sites.yml
Add [delinx.digital](https://delinx.digital)
=> chore(showcase): Add delinx.digital

docs/starters.yml
Added gatsby-firebase-starter for programmatically create pages with firestore collections
=> chore(starters): add gatsby-firebase-starter

docs/sites.yml
Added another site to the Gatsby showcase.
=> chore(showcase): Added nucks.co.

docs/docs/prpl-pattern.md
+ Change http to HTTP
+ Use "Server Push" instead of just "push"
=> docs: HTTP text edits

docs/docs/porting-from-create-react-app-to-gatsby.md
Link to Kyle Gill's example on Twitter is broken
=> remove broken Twitter link to example

docs/creators/creators.yml
Added note about course in development
Added note about new course i'm developing 
n/a
=> docs: Update description of steoneill

packages/gatsby-dev-cli/src/utils/traverse-package-deps.js
=> fix(gatsby-dev-cli): typo

packages/gatsby-plugin-less/README.md
Made the sentence appear more meaningful
Made the sentence more meaningful
N/A
=> Fix: tweak

packages/gatsby-page-utils/README.md
=> fix(gatsby-page-utils): minor typo fix

packages/gatsby-plugin-less/README.md
=> fix(gatsby-plugin-less): fix typo

packages/gatsby-transformer-pdf/README.md
Typo fixed in README
Typo fixed.
N/A
=> Fix Minor typo

packages/gatsby-page-utils/README.md
fixed a grammatical error for the documentation of validatePath in gatsby-page-utils
=> fix grammatical error

packages/gatsby-source-wordpress/README.md
=> docs: fix typos

packages/gatsby-remark-prismjs/README.md
=> docs: fix typo in gatsby-remark-prismjs/README.md

packages/gatsby/src/bootstrap/index.js
Made the sentence more meaningful
Typo fixed
N/A
=> docs(gatsby): fix spelling in comment

docs/blog/2017-02-21-1-0-progress-update-where-came-from-where-going/index.md
=> docs: replace produced with produces

packages/gatsby-plugin-stylus/README.md
=> docs(gatsby-plugin-stylus): fix typo

docs/starters.yml
=> chore(starters): add gatsby-starter

docs/sites.yml
Added my site to showcase
None
=> chore(showcase): Add coleruche.com

docs/starters.yml
Inclusion of site to starter library
=> chore(starters): add bonneville

scripts/clear-package-dir.js
=> comment typo fix

docs/docs/sourcing-from-ghost.md
=> typo error fixed

docs/docs/sourcing-from-buttercms.md
=> removed repetition

docs/sites.yml
Adding vermarcsport.com to showcase
None
=> chore(showcase): Add vermarcsport.com

docs/docs/recipes.md
Updating the `recipes` docs to (a) reflect the original [Typefaces](https://github.com/KyleAMathews/typefaces#how) project documentation and (b) make the docs a little clearer on how to implement.
=> Update typefaces docs

www/src/data/sidebars/tutorial-links.yaml
Check the sidebar nav sequencing => https://www.gatsbyjs.org/tutorial/part-zero/#overview-of-core-technologies
=> chore(docs): fixes section sequencing

packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-plugin-feed/src/__tests__/gatsby-node.js, packages/gatsby-plugin-feed/src/gatsby-node.js, packages/gatsby-plugin-feed/src/plugin-options.js
=> fix(gatsby-plugin-feed): replace title feed requirement with a warning

docs/docs/working-with-video.md
Spelling mistakes in working-with-video.md is cleared .
N/A
=> Fix typos in working-with-video.md

docs/blog/2018-2-27-why-i-upgraded-my-website-to-gatsbyjs-from-jekyll/index.md
Fixed the typos by removing the repeated 'to' in index.md .
N/A
=> Docs: Fix typos in index.md

docs/sites.yml
Add wedding photography site to showcase
=> chore(showcase): Add wedding photography site to showcase

examples/using-typescript/package.json, examples/using-typescript/src/layouts/index.tsx, examples/using-typescript/src/pages/index.tsx
Updated packages and types in `using-typescript` example as it was a bit outdated.
=> chore(examples): update typescript example

packages/gatsby-page-utils/README.md
Fixed table on ignorePath section
=> docs(gatsby-page-utils): add escaped pipe characters in table in readme

docs/sites.yml
Added gopeshgopinath.com to site showcase
None
=> chore(showcase): Add gopeshgopinath.com to site showcase

packages/gatsby-remark-smartypants/README.md
=> docs(gatsby-remark-smartypants): Typo fix

docs/sites.yml
Adding my personal website/blog to the showcase
=> chore(showcase): Add taverasmisael site to showcase

docs/docs/production-app.md
=> fixed typos

packages/gatsby-plugin-catch-links/.gitignore, packages/gatsby-plugin-catch-links/README.md, packages/gatsby-plugin-catch-links/src/catch-links.js, packages/gatsby-plugin-catch-links/src/gatsby-node.js
I edited source instead of doc since users are already following current doc.
Fixes #17324
=> fix(gatsby-plugin-catch-links): fix pluginOptions

packages/gatsby-graphiql-explorer/package.json, yarn.lock
=> fix(gatsby-graphiql-explorer): Add missing dep

docs/docs/recipes.md
Typo fix :joy:
Closing html comment so .org builds again.
¯\_(ツ)_/¯
=> fix: close html comment in recipes.md

packages/gatsby-plugin-offline/src/gatsby-browser.js
Ensure that the initial page (usually `/`) is cached, not just pages linked via that page - the initial page does not receive an `onPostPrefetchPathname` API call so currently it is not being cached.
=> fix(gatsby-plugin-offline): set path resources on route update to ensure initial page is cached

packages/gatsby-plugin-sitemap/README.md
=>  chore(docs): fix typo on gatsby-plugin-sitemap

docs/accessibility-statement.md
=> chore(doc): accessibility statement: better link

docs/sites.yml
Applying to Gatsby showcase
Adding LeReacteur.io to sites.yml for https://www.gatsbyjs.org/showcase/
=> chore(showcase): add LeReacteur.io 

docs/tutorial/ecommerce-tutorial/index.md
Added an extra heads up for creating SKUs in Stripe admin. I ran into issues following this tutorial because I hadn't created test data.
=> chore(docs): Clarify SKUs in Stripe guide

packages/gatsby-plugin-manifest/README.md
=> chore(docs): fix typos on gatsby-plugin-manifest

docs/tutorial/writing-documentation-with-docz.md
=> chore(docs): Fix typo in docz documentation

docs/docs/recipes.md
This PR addresses some of the items that were merged in recipes that didn't get a learning review. 
N/A
=> docs: fix up some recipe entries

docs/starters.yml
added gatsby-starter-casual design by startbootstrap
None
=> chore(starters): add gatsby-starter-casual

docs/sites.yml, docs/starters.yml
Fix starters & showcase categories which aren't valid. This has happend becasue of gatsbybot being down.
=> fix: cleanup starters & showcase

docs/docs/preparing-for-deployment.md
This gave me an extra 25 minutes of setting up my deployment pipeline. It would be nice to have it be mapped 1:1 with the output folder, especially since not all shells are case-sensitive.
N/A
=> docs: Change capitalization of Public to public

docs/sites.yml
New website for Toulouse's most iconic concert hall.
https://lebikini.com
=> chore(showcase): Add lebikini.com

docs/docs/layout-components.md, packages/gatsby/cache-dir/api-ssr-docs.js, packages/gatsby/src/utils/api-browser-docs.js
Addressing a common source of confusion with wrapPageElement/wrapRootElement APIs
#11494
#13667
#14479 
#17160
=> chore(gatsby): improve wrapPageElement & wrapRootElement doc

docs/starters.yml
This PR contains a request to add [this starter](https://github.com/hdorgeval/gatsby-starter-ts-hello-world).
=> chore(starters): add hello world typescript starter

docs/docs/typography-js.md
the correct command here is probably `gatsby develop` and not `npm run develop`
=> Change command to gatsby develop

docs/sites.yml
@Hermanya just as a notice. As Herman as moved his personal site over to Create-React-App, I am removing it from the showcase.
N/A
=> chore(showcase): Remove Herman Starikov site

docs/sites.yml
@flaviolivolsi as a notice. Removing the site as it seems the web server is down. Let us know if this an accident or if it is alright to merge and remove from the showcase.
N/A
=> chore(showcase): Removing How to Book Cheap Flights

docs/docs/tailwind-css.md
Update the TailwindCSS documentation to match the current documentation for getting started. 
N/A
=> chore(docs): Update TailwindCSS Documentation to use NPX 

packages/gatsby-plugin-create-client-paths/README.md
Change language for code block highlighting
=> chore(gatsby-plugin-create-client-paths): README highlighting

packages/gatsby-plugin-create-client-paths/README.md
=> doc(gatsby-plugin-create-client-paths): add link to docs

docs/docs/creating-and-modifying-pages.md
@marcysutton I have tried to follow what you wrote in your issue but I'm not sure I've got it right.
Closes #17622
=> chore(docs): Add section on client only routes

docs/contributing/contributor-swag.md
Update contributor-swag.md with marketing email
https://github.com/gatsbyjs/gatsby/issues/17736
=> chore(docs): Update contributor-swag.md with marketing email

www/src/components/layout.js
This PR adds the `docSearch-content` class to the `layout.js` component so that the Actions in the Gatsby API docs get properly indexed in the Algolia search. 
Fixes #16634
=> Add docSearch-content class to layout for Actions in the Gatsby API docs

docs/starters.yml
=> chore(starters): add gatsby-markdown-blog-starter

docs/docs/adding-search-with-js-search.md
=> docs: fixed typos in adding-search-with-js-search

docs/docs/gatsby-repl.md
=> chore(docs): fixed typos

docs/docs/gatsby-in-the-enterprise.md
=> chore(docs): Fix typo

docs/starters.yml
A Gatsby starter template for a Wordpress blog, built using Typescript and Ant Design
=> chore(starters): add gatsby-wordpress-typescript-blog-boilerplate

docs/contributing/community.md
Updated the Contributors  count according to the current date in the community page of the docs. 
N/A
=> Docs: updated month and contributors count

docs/sites.yml
Add a new website in doc/site.yml
=> chore(showcase): Add BBS

docs/sites.yml
This adds the Appes [website](https://appes.co) to showcase.
=> chore(showcase): Add Appes

docs/docs/recipes.md
Added:
'If fonts are not updating following steps above, make sure to replace the existing font-family in relevant CSS.'
underneath the note for more clarity.
Addresses one of the recommendations I made in #17703
=> Update 'Adding a local font' in recipes.md

docs/starters.yml
=> chore(starters): update gatsby-wordpress-typescript-scss-blog

docs/docs/awesome-gatsby.md
=> chore(docs): Update awesome gatsby

packages/gatsby-cli/src/reporter/index.js
=> Revert "fix(gatsby): minor refactor of console functions"

docs/docs/gatsby-lifecycle-apis.md
=> docs: fixed typo in gatsby-lifecycle-apis.md

docs/docs/sourcing-from-buttercms.md
Images were linked to incorrect cache-busting URLs. Have been corrected.
=> docs(sourcing-from-buttercms): Fixing broken images

docs/sites.yml
Add Global Citizen Foundation to the showcase
=> chore(showcase): Add Global Citizen Foundation

docs/sites.yml
This PR adds [Intern](https://intern.imedadel.me), a job board for internships built entirely in GatsbyJS, to the showcase.
=> chore(showcase): Add Intern

docs/sites.yml
I reached out to @MrRobotjs and they are no longer working on this site so I'm removing it from the showcase
=> chore(showcase): Remove BetterDocs

docs/starters.yml
=> chore(starters): add Blogerist

docs/contributing/how-to-open-a-pull-request.md
The doc on [How to Open a Pull Request](https://www.gatsbyjs.org/contributing/how-to-open-a-pull-request/) went live today, and I saw some potential improvements when reading it. This PR includes those updates.
N/A
=> docs: copy updates for How to Open a PR

docs/docs/node-tracking.md
=> docs: Removed dead URL in node-tracking

docs/sites.yml
=> chore(showcase): Add VIA data

docs/sites.yml
I'd like to add my project to the showcase  💜
=> chore(showcase): Add afexnigeria.com to showcase

docs/starters.yml
=> chore(starters): gatsby-wordpress-typescript-scss-blog

docs/sites.yml
Hi i would love to add GatsbyFinds as a showcase to show my love and support for GatsbyJS
=> chore(showcase): add GatsbyFinds

docs/sites.yml
http://frontend-day.com website showcase submission
=> chore(showcase): Add Front End Day Website

docs/sites.yml
Front End Day Event Website built by fields added.
=> chore(showcase): Add built_by key to entry

docs/sites.yml
Adds https://www.madebymutual.com to the Gatsby showcase
=> chore(showcase): Add madebymutual.com

docs/blog/2019-09-26-announcing-gatsby-15m-series-a-funding-round/index.md
joined links to same target
~~maybe typo with inkteam?~~ no typo
=> blog: double links, typo

docs/starters.yml
Adds a starter to submission file
=> chore(starters): add gatsby-starter-monolith

www/src/components/plugin-searchbar-body.js
=> fix(www): fix plugin searchbar query

docs/starters.yml
Adding gatsby-starter-typescript-pwa
=> chore(starters): add gatsby-starter-typescript-pwa

docs/README.md
=> This would be good

docs/sites.yml
Add Runlet to the Site Showcase.
=> chore(showcase): Add Runlet

docs/docs/importing-assets-into-files.md
Linked to "Adding A Local Font" in Recipes. Will hopefully steer people in correct direction as I was confused on how to use this when I first landed on this page.
Addresses one of the recommendations I made in #17703
=> Added link to using an imported font in "Importing Assets into Files"

docs/sites.yml
Adding a site I recently put live to the sites.yml file :-)
=> chore(showcase): Add theodorawarre.eu

docs/sites.yml
This PR adds the my portfolio website to the showcase listing.
=> chore(showcase): Praveen Bisht

docs/starters.yml
Remove duplicate line in starters.yml file
=> Remove duplicate line in docs

docs/tutorial/part-eight/index.md
This PR resolves the issue brought up on the below issue, and shows a clearer path to using an `<SEO>` component in the final part of the tutorial. The component adds more flexibility and sets up the individual completing the tutorial for success 🤓
Issue that is fixed by this PR: #17346
=> chore(docs): Update tutorial part eight to use an SEO component

docs/docs/life-and-times-of-a-gatsby-build.md
This is broken link fix.
See "server-side" link at https://www.gatsbyjs.org/docs/life-and-times-of-a-gatsby-build/ page.
=> docs: broken link fix

packages/gatsby-plugin-preact/package.json
Preact X has released! This works away some bugs related to gatsby-routes.
Related: https://github.com/preactjs/preact/issues/1966
=> chore(gatsby-plugin-preact): Update Preact dependency to 10.0.0

docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
=> chore(docs): fixed broken link to blog

docs/sites.yml
adding a Primer Labs website which is built using gatsbyjs
=> chore(showcase): Add Primer Labs website

docs/docs/awesome-gatsby.md
=> chore(docs): Update awesome-gatsby

www/src/templates/template-blog-post.js
This PR simplifies a boolean check using the opposite operator.
=> chore(www): Use the opposite operator

docs/sites.yml
deadlink removed.
Removed dead link (author link at page https://www.gatsbyjs.org/showcase/bastionbot.org )
=> chore(link): deadlink

docs/sites.yml
Holy buckets! Adds [Women's and Girls' Emergency Centre](https://www.wagec.org.au/) to the Gatsby showcase! 🎉 🎈
=> chore(showcase): add wagec.org.au to showcases

docs/blog/2019-04-26-how-to-build-a-blog-with-wordpress-and-gatsby-part-1/index.md
Changed link to the dead article.
Link to dead article fixed.
=> chores(link): dead link changed
