gatsbyjs/gatsby

packages/gatsby-cli/src/reporter/prepare-stack-trace.js

This PR removes an unnecessary check which was already done a few lines before.

chore: remove unnecessary methodName check

---

benchmarks/plugin-manifest/index.js
e2e-tests/development-runtime/plugins/gatsby-source-fake-data/api.js
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/types/__tests__/date.js
www/src/views/starter-library/starter-list.js

This PR removes unused parameters.

chore: Remove unused parameters

---

docs/blog/2018-07-07-graphic-design-class/index.md

Removed deadlink to the source repository
Removed link to deleted git repository

chore(links): dead link

---

docs/sites.yml

Add https://global24.ua to showcases, according to https://www.gatsbyjs.org/contributing/site-showcase-submissions/

chore(showcase): add global24.ua to showcases

---

docs/sites.yml

Add [`arvind.io`](https://arvind.io) to the Gatsby site showcase.

chore(showcase): Add arvind.io

---

docs/sites.yml

Have added runleeds.co.uk to the showcase.
Thanks for all the hard work!

chore(showcase): Adding runleeds.co.uk to showcase

---

docs/tutorial/wordpress-source-plugin-tutorial.md

chore(docs): Correct spelling

---

docs/sites.yml

Hi guys and girls from Gatsby. Amazing stuff you made... Added my decoupled Drupal website as a feature in docs/sites.yml 
Thanks 😀

chore(showcase): Add Guus van de Wal Portfolio

---

docs/docs/gatsby-core-philosophy.md

chore(docs): Update gatsby-core-philosophy.md

---

docs/tutorial/using-a-theme.md

Correct spelling in the `using a Gatsby theme` tutorial

Correct spelling

---

docs/docs/quick-start.md

Added message about npx to address issues between the video and the tutorial on the quick start page. 
Fixes #18273

docs: update quick-start with note about egghead video and npx

---

docs/docs/building-a-contact-form.md

Fix casing: `ReCAPTCHA` becomes `reCAPTCHA`
None

Fix casing

---

docs/contributing/contributor-swag.md

This fixes #18227 based on this [comment](https://github.com/gatsbyjs/gatsby/issues/13453#issuecomment-484975693)

Add details about swag tiers to docs

---

docs/sites.yml

chore(showcase): Add Tamarisc VC

---

docs/sites.yml

Showcase - MetaProjection ([www.metaprojection.ca](https://www.metaprojection.ca)) -  A Canadian electoral projection aggregator

 chore(showcase): Add MetaProjection.ca

---

docs/docs/scaling-issues.md

docs: Fix typo in scaling-issues

---

docs/tutorial/part-zero/index.md

I'm working on Russian translation of Gatsby, and found a few issues in original document:
- content duplication
- broken markdown heading levels

docs: updates for tutorial/part-zero

---

docs/docs/location-data-from-props.md

Fix to (`Object`) prop in code example

docs: Update location-data-from-props.md

---

packages/gatsby-plugin-preact/README.md

Preact X has released! And as I we’ve already had this plugin dependency updated (on #18057) i imagine it would be nice to update our docs too 👐

chore(gatsby-plugin-preact): update docs after Preact X release

---

docs/sites.yml

feat(showcase): add https://romkravets.netlify.com/

---

www/src/components/navigation.js
www/src/components/search-form.js

https://twitter.com/replaymag_de/status/1181677564101828610 :/ 🙏 
(fully responsive now, holding up fine also on 320px wide viewports)

fix(www): Main nav breaks layout on screens <~400px

---

docs/docs/themes/conventions.md
docs/docs/themes/converting-a-starter.md
docs/docs/themes/shadowing.md
docs/docs/themes/theme-composition.md
docs/docs/themes/using-a-gatsby-theme.md

Changed h2/h3s to sentence case per the Style Guide. Made minor clarifications.
#
Addresses Issue: [#18284](https://github.com/gatsbyjs/gatsby/issues/18284#issue-503707016)

Make minor edits to theme docs

---

docs/docs/schema-customization.md

Updated schema-customization page to adhere to the Gatsby style guide. Mainly changes from "we" to "you".
Addresses #18284

Updated schema-customization.md to adhere to gatsby style guide

---

docs/docs/adding-search-with-algolia.md
docs/docs/centralizing-your-sites-navigation.md
docs/docs/sourcing-from-agilitycms.md

Fixed all the typos that I found in 'docs' directory.

Fix documentation typos

---

packages/gatsby/src/utils/__tests__/__snapshots__/get-ssl-cert.js.snap

tests(gatsby): fix snapshots

---

docs/docs/adding-comments.md

Title Casing, capitalization needed in a link, reduce the overuse of the word "easy".
Followed the Gatsby Style Guide and made some edits to this document. Fixed the title to use Title Case, updated a link that should be capitalized and reduced the use of the word "easy".
[[docs] Gatsby Style Guide blitz for those new to open source #18284](https://github.com/gatsbyjs/gatsby/issues/18284)

docs: Make changes based on the Style Guide

---

docs/contributing/community.md

Added the code quotes around the `gatsby` to look like its a tag instead of bold

Community.md: Added code quotes around gatsby tag

---

docs/docs/recipes.md

Docs: Add SASS/SCSS recipe

---

docs/docs/deploying-and-hosting.md
docs/docs/importing-assets-into-files.md
docs/docs/recipes.md

Styling with CSS --> Using global CSS files without a Layout component --> Additional resources [(https://www.gatsbyjs.org/docs/recipes/#additional-resources-4)](https://www.gatsbyjs.org/docs/recipes/#additional-resources-4)
Updated the link [https://www.gatsbyjs.org/global-css/#adding-global-styles-without-a-layout-component](https://www.gatsbyjs.org/global-css/#adding-global-styles-without-a-layout-component) by replacing with [https://www.gatsbyjs.org/docs/global-css/#adding-global-styles-without-a-layout-component](https://www.gatsbyjs.org/docs/global-css/#adding-global-styles-without-a-layout-component)  
Updated the non-existing tag "deploying" by replacing it with "deployment" on [https://www.gatsbyjs.org/docs/deploying-and-hosting/](https://www.gatsbyjs.org/docs/deploying-and-hosti …

docs: Update broken links and tag

---

docs/docs/sourcing-from-netlify-cms.md

Changes title case and pronouns in `sourcing-from-netlify-cms.md` to match the style guide
* use sentence case for headings
* use "you" instead of "we"

chore(docs): update sourcing-from-netlify-cms.md

---

docs/docs/sourcing-from-prismic.md

Changes title case and pronouns in sourcing-from-prismic.md to match the style guide
* use sentence case for headings
* use "you" instead of "we"

chore(docs): update sourcing-from-prismic.md

---

docs/docs/sourcing-from-graphcms.md

Changes title case and pronouns in sourcing-from-graphcms.md to match the style guide
* use sentence case for headings
* use "you" instead of "we"

chore(docs): update sourcing-from-graphcms.md

---

docs/docs/sourcing-from-buttercms.md

Changes title case and pronouns in sourcing-from-buttercms.md to match the style guide
* use sentence case for headings
* use "you" instead of "we"
* remove capitalized words in sentences

chore(docs): update sourcing-from-buttercms.md

---

docs/docs/sourcing-from-wordpress.md

Remove capital letter in `sourcing-from-wordpress.md` in line with style guide
Relates to #18284

chore(docs): sourcing-from-wordpress.md

---

docs/docs/add-a-manifest-file.md

Main heading needs to be title cased according to the style guide, a quick edit.

Change main heading to Title Case

---

docs/docs/static-folder.md
docs/docs/static-query.md
docs/docs/styled-components.md

Style guide-related fixes for a handful of docs files.
Addresses #18284

chore(docs): title casing and grammar fixes

---

packages/gatsby-image/README.md
packages/gatsby-image/index.d.ts
packages/gatsby-image/src/index.js

Support passing onClick to gatsby-image

---

docs/docs/unit-testing.md
docs/docs/upgrading-node-js.md
docs/docs/use-static-query.md
docs/docs/using-fragments.md
docs/docs/using-gatsby-professionally.md
docs/docs/using-graphql-playground.md
docs/docs/v1-release-notes.md
docs/docs/v2-release-notes.md

Minor style fixes of markdown documentation files according to style guide
- use title case for titles
- use sentence case for headings
- use "you" instead of "we"
- use active instead of passive voice
- use Node.js consistently

docs(docs): Audit markdown files to fit style guide

---

docs/docs/caching.md
docs/docs/client-data-fetching.md
docs/docs/content-and-data.md

Reverts some style changes made in PR #18466, per comments from @marcysutton  
Addresses Issue #18284 
Related to PR #18466

Updates/reverts style changes based on comments on PR #18466

---

docs/sites.yml

Adds Josh Pensky portfolio to Showcase

chore(showcase): Add Josh Pensky portfolio to Showcase

---

packages/gatsby-cli/src/init-starter.js
packages/gatsby-cli/src/structured-errors/error-map.js

Improves cli new command errors.
Original:
New:
Relates to #15019

chore(gatsby-cli): Improvements on cli errors

---

docs/docs/building-a-site-with-asynchronous-data.md

This stub was missing an issue. I have opened #18484 and added it to the stub.

[docs] add issue to stub on async data

---

docs/starters.yml

Looking to contribute to the starter library
Demo: [https://gatsby-starter-material-album.netlify.com](https://gatsby-starter-material-album.netlify.com)
Repository: [https://github.com/JoeTrubenstein/gatsby-starter-material-album](https://github.com/JoeTrubenstein/gatsby-starter-material-album)

chore(starters): add gatsby-starter-material-album

---

docs/docs/creating-a-source-plugin.md
docs/docs/creating-a-transformer-plugin.md
docs/docs/creating-global-styles.md
docs/docs/creating-prefixed-404-pages-for-different-languages.md

Adds correct title case and you/your pronouns to 4 files
Addresses #18284

chore(docs): Updates Title Case and pronouns

---

docs/docs/add-seo-component.md

chore(docs): Update Title Case in "Adding an SEO component"

---

docs/docs/add-custom-webpack-config.md

chore(docs): Update 'add-custom-webpack-config'

---

docs/blog/2017-09-26-embracing-graphql/index.md
docs/blog/2018-04-06-introducing-gatsby-rfc-process/index.md
docs/blog/2019-04-29-component-shadowing/index.md

chore(blog): Updated titles according to Style Guide

---

docs/docs/recipes.md

Just change avoid a `we`
#18284

chore(docs): Updated recipes to adhere to Gatsby style guide

---

docs/docs/graphql-concepts.md

Updated pronouns in the doc to use "you" and "your" instead of "we" and "our"
Updated pronouns in the doc to use "you" and "your" instead of "we" and "our"
[docs] Gatsby Style Guide blitz for those new to open source #18284

chore(docs): Update pronouns in graphql-concepts

---

docs/blog/2019-08-30-speed-up-your-time-to-interactive-by-delaying-third-party-scripts/index.md

Noticed a typo in my blog post, this PR fixes that.

chore(blog): fix typo'd sentence in blogpost

---

renovate.json

Added a timezone and schedule config to Renovate
refs #18615

Renovate Schedule

---

docs/docs/add-page-metadata.md

chore(docs): Update Title Case in 'add-page-metadata.md'

---

docs/docs/multi-core-builds.md

Title Case correction for Style Guide

chore(docs): Title Case Correction

---

docs/docs/programmatically-create-pages-from-data.md

chore(docs): Use “you” as the pronoun

---

docs/docs/api-files-gatsby-config.md

chore(docs): Update title case

---

docs/docs/adding-tags-and-categories-to-blog-posts.md

adding-tags-and-categories-to-blog-posts.md

chore(docs): Update We to You for Style Guide

---

docs/docs/adding-search-with-js-search.md

chore(docs): Update we to you

---

docs/tutorial/part-eight/index.md

chore(docs): Title Casing Correction

---

peril/README.md

docs(peril): add README 

---

docs/sites.yml

- add Edenspiekermann to sites showcase
- add IBM Design to sites showcase
- add featured in categories for Edenspiekermann and IBM Design  
Link to the issue that is fixed by this PR (if there is one)
e.g. Fixes #18610 
Link to related issues (if there are any)
e.g. Related to #18610

[#18610] Add to sites showcase

---

docs/docs/reach-router-and-gatsby.md

chore(docs): Add quotes to title of reach/router doc

---

docs/docs/eslint.md

Mainly change `we` to `you`
#18284

chore(docs): Update eslint to adhere to Gatsby style guide

---

docs/docs/environment-variables.md

Mainly change `we` to `you`
#18284

chore(docs): Updated environment-variables to adhere to Gatsby style guide

---

docs/docs/graphql-api.md
docs/docs/graphql-concepts.md
docs/docs/graphql-reference.md
docs/docs/graphql.md

This PR introduces some changes to the **graphql-files** in the **docs** folder.
- changed some headlines to fit the style guide
- a few text changes
Related to https://github.com/gatsbyjs/gatsby/issues/18284

chore(docs): check titles, headlines & text

---

docs/starters.yml

I have created a starter utilizing Contentful as the CMS, and deployed to Netlify. If there are any issues with my PR, just let me know.

chore(starters): add gatsby-contentful-starter

---

docs/sites.yml

Showcasing my [personal blog](https://haxzie.com) which is built with Gatsby :sparkles:

chore(showcase): Add haxzie.com

---

docs/tutorial/authentication-tutorial.md

chore(docs): Title Casing Update

---

docs/docs/asset-prefix.md

Updated pronouns in docs/docs/asset-prefix.md to match style guide.
#18284

chore(docs): Updated pronouns usage

---

docs/tutorial/index.md

Updated case of heading for tutorial: zero link to match other links on page
Related to #18656

chore(docs): Update index.md to adhere to Gatsby style guide

---

docs/sites.yml

I have added a Gatsby blog side project to the sites.yml

chore(showcase): Add yangmuzi.com

---

starters/README.md

starters(readme): fix broken link

---

docs/docs/awesome-gatsby-resources.md

Added a few resources to awesome-gatsby-resources page
Russian:
- [JAMstack: Как создать свой блог используя Gatsby + Contentful + Netlify (Russian)](https://habr.com/ru/post/439232/)
- [Gatsby.js в деталях (Russian)](https://habr.com/ru/post/442298/)
Ukrainian:
- [JAMstack: створюємо блог з Gatsby + Contentful + Netlify (Ukrainian)](https://dou.ua/lenta/articles/creating-blog-with-jamstack/)
- [Детально про Gatsby.js — інструмент для створення складних веб-сайтів (Ukrainian)](https://dou.ua/lenta/articles/gatsbyjs-guide/)

docs: Added rus and ukr articles to awesome-gatsby-resources

---

docs/docs/post-css.md
docs/docs/preoptimizing-images.md
docs/docs/preparing-for-deployment.md
docs/docs/preparing-your-environment.md
docs/docs/programmatically-create-pages-from-data.md
docs/docs/prpl-pattern.md

This PR introduces some changes to **first part** of the **p-files** in the **docs** folder.
- changed some headlines to fit the style guide
- a few text changes
Related to https://github.com/gatsbyjs/gatsby/issues/18284

chore(docs): p-files Part2 - adjust headlines according to style guide + adjust some texts

---

docs/blog/gatsby-first-beta-release.md

**Minor fixes on the following**
* *Title casing*
* *Grammar*

chore(blog): Grammar fix

---

docs/docs/sanitize-your-stack.md
docs/docs/sass.md
docs/docs/seo.md
docs/docs/setting-up-gatsby-without-gatsby-new.md

Minor update for a few title case and punctuation changes

chore(docs):title case and punctuation fixes

---

docs/sites.yml

Just another personal website built with Gatsby.js <3

chore(showcase): Add robinwieruch.de

---

themes/README.md

Improved documentation
Improved documentation of Gatsby Themes and Starters. The documentation didn't include what is a theme and a starter.

chore(docs): Update README.md

---

docs/docs/reach-router-and-gatsby.md

Adding some basic information about `@reach/router` and Gatsby.
Adding docs per: #18781

docs: removing stub for reach router doc

---

packages/gatsby-plugin-feed/src/gatsby-node.js

fix(gatsby-plugin-feed): Remove wrong overriding in plugin-feed

---

docs/docs/gatsby-on-windows.md
docs/docs/remark-plugin-tutorial.md
docs/docs/sourcing-from-contentstack.md

chore(docs):Replaced the word 'easy' to use more inclusive language.

---

docs/sites.yml

Add restore site built with Sanity & Gatsby

chore(showcase): add visitrestore.com

---

docs/sites.yml

URL change from evergov to papergov coz http://www.udrpsearch.com/naf/1862044#1230

fix(showcase): URL change from evergov to papergov in showcase

---

docs/docs/working-with-gifs.md

Changed "With" in title to lowercase in docs/docs/working-with-gifs.md to adhere to Style Guide and keeping it consistent with other titles that use lowercase for the word "with". Simple change to make it consistent across the docs.

Update title of docs/docs/working-with-gifs.md

---

docs/docs/working-with-gifs.md

Updated with of title to lowercase to make it consistent with other titles.

Updated with of title to lowercase

---

docs/starters.yml

Added MDX to https://github.com/maxpou/gatsby-starter-morning-dew
none.

chore(starters): add MDX to gatsby-starter-morning-dew

---

docs/starters.yml

chore(starters): gatsby-starter-grayscale-promo

---

docs/docs/gatsby-in-the-enterprise.md

Updated "with" in lowercase in title to make it more consistent with other titles.

chore(docs): Updated "with" in lowercase in title.

---

docs/docs/adding-tags-and-categories-to-blog-posts.md
docs/docs/bulma.md

chore(docs): Replace 'our' with 'your' in bulma and blog docs

---

docs/starters.yml

Adds `gatsby-tailwind-emotion-starter` to the starter library
https://gatsby-tailwind-emotion-starter-demo.netlify.com/
https://github.com/pauloelias/gatsby-tailwind-emotion-starter

chore(starters): gatsby-tailwind-emotion-starter

---

docs/docs/working-with-images-in-markdown.md

Update "with" lowercase in title to make it consistent with other titles.

chore(docs): Update with in lowercase in title

---

docs/tutorial/part-one/index.md

While going through the tutorial, I was a little unsure what this was trying to say. I believe the new language clarifies it a tiny bit more. Let me know if it should be different at all.
There are no related issues. I simply felt like this could be clarified a little.

chore(docs): clarify the message about links

---

docs/sites.yml

Just adding another site build with Gatsby to showcase

adding bululueventos.cl

---

docs/blog/2019-10-08-hacktoberfest-2019/index.md

On opening the free swag for developers link, it gives a page not found error.

fix(blog): Fixing the link

---

docs/blog/2019-10-08-hacktoberfest-2019/index.md

Add a gatsby-plugin to Hacktoberfest post.

Add gatsby-plugin-colorblind-filters to Hacktoberfest blog post

---

docs/starters.yml

I've created this simple TypeScript starter with Contentful integrated (plus some sample .tsx files).
https://github.com/wataruoguchi/gatsby-starter-typescript-contentful
https://wataruoguchi-gatsby-starter-typescript-contentful.netlify.com/
I love Gatsby & JAMStack! Thank you so much for building this <3

chore(starters): gatsby-starter-typescript-contentful

---

.github/workflows/schedule-reporting-workflow.yml

Switch from daily to weekly for this action

chore: change workflow schedule

---

docs/docs/headless-cms.md
docs/docs/sourcing-from-gentics-mesh.md
docs/docs/sourcing-from-graphcms.md

This PR adds the sourcing guide for the OSS headless CMS [Gentics Mesh](https://getmesh.io)

chore(docs): Add "Gentics Mesh" guide

---

www/src/components/diagram.js

See also https://github.com/gatsbyjs/gatsby/pull/18998

Don't use "static" to describe what Gatsby does

---

docs/docs/visual-testing-with-storybook.md

The config can be simplified as seen in https://storybook.js.org/docs/guides/guide-react/#step-3-create-the-config-file

docs: Update storybook 5.* configuration

---

docs/sites.yml

chore(showcase): Add veryben.com

---

docs/sites.yml

Update listing for https://iammatthias.com

chore(showcase): Update iammatthias.com entry

---

docs/starters.yml

chore(starters): Add gatsby-starter-point

---

README.md

This PR replaces the text `:rocket:` in README.md with the rocket emoji, with the intention of addressing rendering issues on npmjs.com.

Fix README.md on nomjs.com by replacing :rocket: with rocket emoji

---

docs/docs/reach-router-and-gatsby.md

core(docs): add better link text

---

docs/docs/gatsby-config.md

Changed some 'we' to 'you' adhering to Style Guide
Addresses #18284

changed some we to you

---

docs/tutorial/using-a-theme.md

While reading through the documentation on component shadowing, I was pretty confused about what it was trying to explain. I had to read through other docs to understand it, so hopefully this clears it up a bit.
No related issues. I felt it was unclear when I was going through the tutorial, and I think this helps.

chore(docs): explain shadowing a bit more

---

docs/docs/babel.md

Updated according to Gatsby Style Guide. Shifted perspective from the first-person perspective ("I", "we") to the secondary perspective ("you") per the Gatsby Style guide.

Updated according to Gatsby Style Guide.

---

docs/docs/unit-testing.md

Update Our to Your

---

docs/sites.yml

Adding [kentarom's portfolio](https://kentarom.com/) to showcase list.

chore(showcase): Add kentarom's portfolio to showcase list

---

.github/ISSUE_TEMPLATE/new_translation.md

Add more context to creating new languages

---

docs/starters.yml

#Description
There was no examples on the starters that used storybook with typescript, I believe that some more examples with TS are required to increase its usage and help others devs to pass on the learning curve.

chore(starters): gatsby-typescript-storybook-starter

---

docs/contributing/gatsby-docs-translation-guide.md

Just adding a link to the Polish repo in the docs.

chore(docs): add Language repos to the list

---

docs/sites.yml

Adding Gatsby site hosted via Netlify to Showcase

chore(showcase): Add Fuzzy String Matching

---

docs/starters.yml

Just updated the URL and removed a tag.

chore(starters): update lewis-gatsby-starter-blog

---

docs/docs/centralizing-your-sites-navigation.md
docs/docs/creating-a-sitemap.md
docs/docs/theme-api.md
docs/docs/working-with-video.md

I updated pronouns ("you" and "your" instead of "we" and "our") in couple of files. Most of them in docs were already fixed. 

chore(docs): Update pronouns

---

docs/sites.yml

We use strapi source and host on netlify, we have validated performance and follow all best practices. We will publish some helpful articles for JAMstack.

chore(showcase): Add open techiz website

---

www/src/utils/styles/global.js

Fix warning, following up on #18892

fix(www): No kebab case for CSS properties in objects

---

docs/docs/gatsby-vendor-partnership.md

chore(docs): Fix two things in partnering doc

---

docs/docs/deploying-to-s3-cloudfront.md
peril/README.md

fix language for code highlighting from `sh` to `shell`

chore(docs): fix language for code highlighting from sh to shell

---

docs/docs/gatsby-core-philosophy.md

Correct count of contributors

---

docs/tutorial/part-zero/index.md

Proper nouns should be capitalized

Fix capitalize

---

docs/sites.yml

Submit my Gatsby-based project "Oberion" to site showcase as outlined in the docs <https://www.gatsbyjs.org/contributing/site-showcase-submissions>.
Thanks! 😃

Site submission oberion

---

docs/sites.yml

chore(showcase): Add new BIGBrave websites

---

docs/docs/eslint.md

We consider "just" to be non-approachable language per the style guide. Removing this usage.

Remove the word "just"

---

docs/categories.yml
docs/starters.yml

I would like to share my gatsby starter in the starter library.
I have followed the instruction in [the docs](https://www.gatsbyjs.org/contributing/submit-to-starter-library/).

feat(starters): Kentico Kontent starter based on Photon

---

docs/sites.yml

Adding [Lusta Hair](https://www.lustahair.com) site to showcase list.

chore(showcase): Add Lusta Hair website

---

docs/starters.yml

This PR fixes a small typo / missing letter in the features list of a starter.

docs(starter): fix small typo

---

packages/gatsby/package.json
packages/gatsby/src/schema/print.js
yarn.lock

Fix flatMap import from `graphql/polyfills`
#19191

fix(gatsby): Fix flatMap import in schema/print.js

---

examples/using-stylus/src/pages/index.js

Testing a config change, please ignore.

chore(examples): Testing a config change

---

.circleci/config.yml

`cd <dir>` doesn't seem to persist between steps, so use `working_directory`

fix(circleCi): don't cd, use working_directory

---

scripts/i18n/update-source.js

fix update source issues

---

scripts/i18n/update-source.js

feat(scripts/i18n): more logs, fail job if pushing fails, use commit hash and message

---

docs/sites.yml

Adds [Really Fast Sites](https://reallyfastsites.com/) website as a Gatsby showcase site submission.

chore(showcase): Add 'Really Fast Sites' website

---

docs/starters.yml

Tailwind CSS + Styled-Components + Storybook starter for Gatsby.
Check the repo: https://github.com/denvash/gatsby-tailwind-styled-components-storybook-starter

chore(starters): add gatsby-tailwind-styled-components-storybook-starter

---

docs/sites.yml

We have few entries with categories that are not in our whitelist - this should fix it

fix(showcase): remove not whitelisted categories from entries

---

docs/contributing/setting-up-your-local-dev-environment.md

fix with prettier

---

docs/sites.yml

chore(showcase): Added binaria.com

---

docs/sites.yml

Added https://to-be-created.com to the sites.yml file

chore(showcase): Add To Be Created

---

www/src/components/feedback-widget/feedback-form.js

Fixes scroll issue as given in #19378 
Closes #19378

fix(www): scrolling of feedback widget in docs

---

docs/starters.yml

Add Gatsby-London-After-Midnight

chore(starters): add gatsby-london-after-midnight

---

packages/gatsby/cache-dir/navigation.js

Fix navigate to non-latin name links.

fix(gatsby): non-latin hash link

---

www/src/components/feedback-widget/feedback-form.js

I missed this in the review, this value is a string so should be quoted.
Updates https://github.com/gatsbyjs/gatsby/pull/19435

fix(www): unquoted value

---

docs/categories.yml
docs/sites.yml

chore(showcase): Add B-Engaged

---

docs/sites.yml

WAGEC now has a Gatsby + Shopify shop!
[https://www.wagec.org.au/shop/](https://www.wagec.org.au/shop/)
Updated to add eCommerce category

chore(showcase): Update WAGEC

---

docs/sites.yml

Added two new sites to `docs/sites.yml`: my personal blog and an eCommerce site I built for a client.

chore(showcase): Add Yoseph.tech

---

docs/docs/themes/shadowing.md

I author my themes in TypeScript and people worry that they also have to write TS when shadowing files. But they don't need to :)

chore(docs): Add note about file extensions

---

.github/workflows/schedule-stale.yml

Increase OPERATIONS_PER_RUN and remove some exempt labels

chore: Update stale action

---

docs/sites.yml

Add Pix4D.com in the showcase sites

chore(showcase): add Pix4D to the showcase

---

www/src/data/diagram/static-hosts.yml
www/src/data/sidebars/doc-links.yaml

There were chats between Matt, the founder of Netlify and Sam about stating Netlify is providing hosting as per our partnership and Netlify's Open Source terms, so I'm filing a followup PR. Hi! 👋 Thanks for your time in reviewing it!
Normally I would open an issue but this was discussed already with both teams. :)

Update the readme and the docs site to include Netlify hosting

---

docs/starters.yml

https://github.com/impulse/gatsby-typescript-tailwind

chore(starters): Add gatsby-typescript-tailwind

---

docs/contributing/gatsby-docs-translation-guide.md

I have added the Traditional Chinese language in the Process for starting a new translation section.
- Doc Page :- https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/

chore(docs): Add Traditional chinese language in transalation list

---

www/src/components/banner.js

chore(www): update banner copy

---

packages/gatsby-cli/src/reporter/errors.js
packages/gatsby-cli/src/reporter/index.js

Bring a few jsdocs in line with the code (squashes ide warnings)

chore(gatsby-cli): update some jsdocs

---

www/src/components/__tests__/banner.js
www/src/components/shared/pullquote.js
www/src/gatsby-plugin-theme-ui/index.js

fix(www): pullquote colors/contrast for dark theme

---

docs/contributing/gatsby-docs-translation-guide.md

I have added the Vietnamese language in the Process for starting a new translation section.
Doc Page :- https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/

chore(docs): Add Vietnamese language in transalation list

---

docs/docs/awesome-gatsby-resources.md

chore: add gatsby-templates.io to awesome-gatsby-resources.md

---

docs/docs/end-to-end-testing.md

Added 'npm run' to 'test:e2e' command since the script will not run without it.

Added 'npm run' to 'test:e2e' command

---

docs/sites.yml

This PR adds the [Nordic Microfinance Initiative](https://www.nmimicro.no/) website to the Showcase. Thanks!

chore(showcase): Add nmimicro.no to showcase.

---

docs/contributing/why-contribute-to-gatsby.md
www/README.md

corrected few of the Grammatical errors on the markdown file like removed useless words like "definitely" from the sentence and changed "Contributing in OSS" to "Contributing to OSS" for the simplicity of the reader.

Update why-contribute-to-gatsby.md file

---

.circleci/config.yml

This should persist our workspace no mather what :)
Should fix

fix: circleci workspace checks

---

starters/gatsby-starter-theme/README.md

Changes a few links on the starter theme `README.md` file from HTTP to HTTPS

🔒 Fix links missing HTTPS

---

packages/gatsby/src/utils/source-nodes.js

Improves perf of this function by about 40%!!
Prevent some object creation, prevent using lodash methods in favor of using `Set`s directly, prevent an `Array.from` call on `getNodes()` which always returns an array.
Combined the filter for `flattenedPlugins` (there were two, now there is one)
Creating the `nodeOwnerSet` set on the fly, preventing the temporary array that was used before
Prevent using lodash and internal lodash machinery for this.
Before (~7ms) after (~4ms)

fix(gatsby): Improve discoverPluginsWithoutNodes performance

---

docs/sites.yml

Add https://wtlstudio.com to `sites.xml` 🎉

chore(showcase): Add WTL Studio

---

docs/blog/2019-11-14-announcing-gatsby-cloud/index.md

- Miscellaneous spelling, punctuation and grammar fixes.
- Uniform apostrophes across the post.

fix(docs): spelling, punctuation, and grammar in blog post.

---

docs/sites.yml

chore(showcase): Add ToolsDB

---

docs/starters.yml

Adds https://github.com/arshad/gatsby-starter-phoenix to starters.
Theme: https://github.com/arshad/gatsby-theme-phoenix
Demo: https://gatsby-theme-phoenix-demo.netlify.com/
Thank you

chore(starters): add @arshad/gatsby-starter-phoenix

---

packages/gatsby/src/schema/__tests__/rebuild-schema.js
packages/gatsby/src/schema/schema.js

The problem: `createResolvers` API mutates third-party schema instance. For example, it can add a new field referencing a type from our main schema. Then if we rebuild the schema this old type instance will sneak into the new schema and produce the famous error:
```
Schema must contain uniquely named types but contains multiple types named X
```
This PR cleans up artifacts created by the `createResolvers` API of the previous build so that we return the third party schema to its initial state (hence can safely re-add).
Fixes #19683

fix(gatsby): Clean up third party schema customizations to avoid schema rebuilding failure

---

docs/starters.yml

chore(starters): add gatsby-starter-landed

---

docs/starters.yml

Adding [Tina Grande (tina-starter-grande)](https://github.com/tinacms/tina-starter-grande) to the starters page. :smile:

chore(starters): add tina-starter-grande

---

packages/gatsby-plugin-netlify/src/create-redirects.js

refactor(gatsby-plugin-netlify): use includes

---

docs/sites.yml

Added our Gatsby built site to site.yml for showcase/featured

chore(showcase): Add Whipstitch Webwork

---

www/gatsby-node.js

this code block was removed in "#19495 Remove creator showcase" but reintroduced in #19551
fixes #19738

chore(www): remove code block "creators" in gatsby-node which was reintroduced

---

packages/gatsby/src/redux/actions/public.js

Make warning message more visible
Addresses #19689

chore(gatsby) More visible duplicated path page warning

---

packages/gatsby-plugin-offline/src/sw-append.js

chore(gatsby-plugin-offline): use Array.includes

---

packages/gatsby-source-wordpress/src/fetch.js

refactor(gatsby-source-wordpress): use includes

---

docs/sites.yml

Add blog on software development to the showcase

chore(showcase) Add talkoverflow

---

docs/sites.yml

Add [lesleylai.info](http://lesleylai.info) to `sites.yml`.

chore(showcase): Add lesleylai.info to sites.yml

---

packages/gatsby-cli/src/structured-errors/error-map.js
packages/gatsby/package.json
packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
packages/gatsby/src/query/__tests__/file-parser.js
packages/gatsby/src/query/__tests__/fixtures/query-compiler-schema.graphql
packages/gatsby/src/query/__tests__/query-compiler.js
packages/gatsby/src/query/file-parser.js
packages/gatsby/src/query/graphql-errors.js
packages/gatsby/src/query/query-compiler.js
yarn.lock

Remove relay-compiler to eliminate dependency that is constantly giving us troubles. Still working on proper tests.

fix(gatsby): Remove relay compiler & use our own

---

packages/gatsby-plugin-catch-links/src/catch-links.js

refactor(gatsby-plugin-catch-link): use Array.includes

---

packages/gatsby-transformer-sqip/src/extend-node-type.js

refactor(gatsby-transformer-sqip): use Array.includes

---

docs/sites.yml

Add new sites built using Gatsby by A+E Networks (HISTORY Channel)

chore(showcase): Add HISTORYTalks & HISTORYCon

---

docs/blog/2019-01-25-blazing-fast-development-with-gatsby-and-sanity-io/index.md

apply redir on blog/2019-01-25-blazing-fast-development
#19267

fix(blog): use redir on blog/2019-01-25-blazing-fast-development

---

docs/blog/2017-10-20-from-wordpress-to-developing-in-react-starting-to-see-it/index.md

apply redir to blog/2017-10-20-from-wordpress
#19267

fix(blog): use redir on blog/2017-10-20-from-wordpress

---

docs/docs/modifying-a-starter.md

fix 404 on docs/modifying-a-starter
#19267

fix(docs): 404 on docs/modifying-a-starter

---

docs/docs/migrating-from-v1-to-v2.md

fix 404 on docs/migrating-from-v1-to-v2.md
#19267

fix(blog): 404 on docs/migrating-from-v1-to-v2.md

---

docs/blog/2019-06-17-product-management-at-Gatsby/index.md

fix 404 @ blog/2019-06-17-product-management-at-Gatsby
#19267

fix(blog): 404 on blog/2019-06-17-product-management-at-Gatsby

---

docs/blog/2019-11-20-gazette-october/index.mdx

fix(blog): 404 on blog/2019-11-20-gazette-october

---

docs/sites.yml

Add https://antv.vision/en into showcase.

chore(showcase): Add AntV

---

docs/starters.yml

fix url for starter: gatsby-shopify-starter
#19849

fix(starter): fix url for starter: gatsby-shopify-starter

---

docs/starters.yml

chore(starters): update lewislbr's starters info

---

docs/sites.yml

- Add http://ezekielekunola.com to Gatsby showcase.
- None

Add portfolio to showcase

---

docs/sites.yml

Signed-off-by: isamrish <askmaurya48@gmail.com>
- Add https://uxworks.org to Gatsby Showcase
none

chore(showcase): Add uxworks.org

---

docs/tutorial/part-three/index.md

This fixes a minor grammar type in documentation
There is no issues open for this

chore(docs): Minor grammar fix

---

packages/gatsby-theme/gatsby-theme/cli.js

Updated the usage information which makes more sense as per the context.
N/A

fix: update usage information

---

docs/starters.yml

add a new starter: gatsby-firebase-simple-auth

chore(starters): Add gatsby-firebase-simple-auth

---

docs/sites.yml

Add [Gearbox Development](https://gearboxbuilt.com) to Gatsby showcase.
N/A

chore(showcae): Add Gearbox Development

---

docs/categories.yml
docs/starters.yml

Added a new starter: gatsby-starter-cafe.
Added a new tag category: Leaflet.

chore(starters): Add gatsby-starter-cafe

---

docs/starters.yml

Add https://github.com/antvis/gatsby-starter-theme-antv to https://www.gatsbyjs.org/starters/?v=2
- https://github.com/antvis/gatsby-starter-theme-antv 
- https://github.com/antvis/gatsby-theme-antv

chore(starters): Add gatsby-starter-theme-antv

---

docs/sites.yml

This is requesting my site to be featured as a Gatsby site.

Request my site as featured Gatsby site

---

docs/starters.yml

Add gatsby-starter-storefront-shopify to docs/starters.yml.

chore(starters): add gatsby-starter-storefront-shopify

---

docs/docs/node-tracking.md
docs/docs/query-behind-the-scenes.md

in this docs are broken or wrong links and i added a note
#14228

update(docs): mark more Gatsby internal docs for update

---

docs/docs/glossary.md

Change "the public do" to "the public does"

---

docs/sites.yml

It adds two more open source portfolio sites to `sites.yml` to be displayed in https://www.gatsbyjs.org/showcase/
https://arethaiskandar.com/ and https://www.thomasmaximini.com/

docs: added two portfolios to sites.yml

---

docs/sites.yml

chore(showcase): Add Code Examples blog

---

docs/sites.yml

This PR adds harshil.net, my personal website, to the Gatsby showcase

chore(showcase): Add harshil.net

---

docs/starters.yml

Also adding the Onepage tag to my other Gatsby starters on the list.

chore(starter): Adding Gatsby Lander

---

docs/sites.yml

Added new site listing to Showcase sites.yml (Yearlyglot - Fluent Every Year).

chore(showcase): add Yearlyglot

---

docs/sites.yml

This includes a URL fix from my previous request #19944 - you can ignore that.

chore(showcase): fix repo link for jarodpeachey.netlify.com

---

docs/tutorial/part-one/index.md

Minor quote `"` typo fix
Update in this page `docs/tutorial/part-one/index.md `

Fix (docs) : Minor quote typo fix

---

docs/starters.yml

Added gatsby-starter-keturah to docs/starters.yml.

chore(starters): add gatsby-starter-keturah

---

docs/sites.yml

Updates the showcase screenshot URL for gearboxbuilt.com
N/A

chore(showcase): Updated screenshot URL for Gearbox

---

docs/sites.yml

Added a new site to the showcase list `sites.yml` (Bearer.sh - API Monitoring & Protection for your app)

chore(showcase): add Bearer.sh

---

docs/sites.yml

No longer a Gatsby site as discovered by the site showcase validator

chore(showcase): Remove unionpluscard.com

---

docs/docs/unit-testing.md

Update docs unit testing typescript

---

yarn.lock

Removed node_modules, ran yarn, merging lock file.
Not waiting for tests.

chore(gatsby): Update yarn.lock

---

www/gatsby-node.js
www/src/data/sidebars/doc-links.yaml

This stub had a significant SEO impact, so should have a redirect.
Addressing comments on #19918

redirect and remove sidebar

---

docs/sites.yml

Adds [dispel.io](https://dispel.io) to the showcase.
None

chore(showcase): Add dispel.io to showcase

---

docs/starters.yml

chore(starters): add gatsby-starter-papan01

---

docs/blog/2019-12-10-gatsby-brings-speed-to-mediacurrent-com/index.md

changed the date and path of blog post about mediacurrent as requested in https://github.com/gatsbyjs/gatsby/pull/19667#discussion_r356055539
this blog post is not published until now - no redir is needed 
#19667

fix(blog): changed date in blog mediacurrent

---

docs/docs/glossary/node.md
www/src/data/sidebars/doc-links.yaml

Looks like #19965 was not formatted properly. So now lint checks for docs are failing in CI. This PR should fix it.

fix(docs): run prettier on malformed files

---

docs/docs/adding-search-with-algolia.md

- prexifed => prefixed
- webinterface => web interface

fix(docs): typo in adding-search-with-algolia

---

docs/docs/api-files-gatsby-node.md

Add a missing closing parens on line 30. Copy/pasted this into project and it threw an error.

fix(docs): add missing closing parens in api-files-gatsby-node.md

---

docs/docs/environment-variables.md

docs: add clarity to Gatsby Environment Variables docs
docs/docs/environment-variables.md
@gatsbyjs/learning
Fixes #19387

add clarity to Gatsby Environment Variables docs

---

docs/sites.yml

My [Portfolio](https://rumaan.me) built with Gastby ❤️

chore(showcase): Add rumaan.me to showcase

---

www/src/data/sidebars/tutorial-links.yaml

Fixed a typo in the sidebar YAML links for additional tutorials.
Gatsby docs.

Fixed a typo

---

docs/blog/author.yaml

PR #20103 forgot to introduce me as an author. 
This PR fixes that.

fix(blog): Fix missing author

---

docs/contributing/submit-to-creator-showcase.md
peril/rules/validate-yaml.ts
peril/tests/validate-yaml/validate-yaml-creators.test.ts
www/gatsby-node.js
www/src/components/creator-data.js
www/src/data/sidebars/contributing-links.yaml
www/src/pages/creators/agencies.js
www/src/pages/creators/companies.js
www/src/pages/creators/index.js
www/src/pages/creators/people.js
www/src/templates/template-creator-details.js
www/src/views/creators/badge.js
www/src/views/creators/check.svg
www/src/views/creators/creators-header.js
www/src/views/creators/index.js

Revert "Remove creator showcase"

---

docs/docs/adding-page-transitions-with-plugin-transition-link.md

Hey 👋  I'm the author of this plugin. I noticed there was an outdated API being used and some incorrect info in the doc so I made a couple small changes. Thanks!

fix(docs): transition link

---

docs/sites.yml

DigiGov is an initiative from the Greek Government for the Digital Transformation of the Greek Public Sector

Add DigiGov to showcase

---

docs/starters.yml

chore(starters): change links for chronoblog starters

---

docs/contributing/gatsby-docs-translation-guide.md

I have added the Bengali language in the Process for starting a new translation section.
Doc Page :- https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/

chore(docs): Add Bengali language in transalation list

---

docs/sites.yml

Update links to domains clients have abandoned to their Netlify preview subdomains.

Fix broken sites.yml links

---

docs/sites.yml

- removed comments
- William Owen UK Portfolio / Blog -> uncomment ->  is available again 
- removed a not connected domain (both domains visible in github profile not connected)

fix(showcase): removed comments, uncomment valid site

---

docs/sites.yml

Add the new Zeek Interactive website to the showcase. https://zeek.com
n/a
n/a

chore(showcase): Add Zeek Interactive

---

docs/sites.yml

Hi, i'm adding my theme for site showcase submission

chore(showcase): Add Paul Scanlon Blog

---

docs/blog/100days/index.md

The word Reddit was repeated twice in the original. Also, for good measure, I added links directly to the communities.

Fix typo and add links

---

www/src/components/markdown-page-footer.js
www/src/templates/template-docs-markdown.js

Move edit link markdown (_Edit this page on GitHub_) right under the content to make it more related with content above.
**Before**
**After**
Fixes #19070

Move edit link markdown right under the content

---

docs/sites.yml

Add EF design portfolio website to showcase

chore(showcase): Add EF

---

docs/docs/cheat-sheet.md
docs/docs/gatsby-cli.md
packages/gatsby-cli/src/create-cli.js

This is a follow up PR to #20110 at the request of @muescha and @wardpeet

feat(gatsby-cli): update docs for develop PORT env var

---

docs/blog/2018-04-04-gatsby-contentful-starter-tutorial/index.md

docs: Fix headings in Markdown.

---

docs/docs/winning-over-developers.md

Changes to the 'winning over developers' documentation 
Added a new sub topic 'Data Integration' which specifically points out easy data integration, which is a main source of motivation to developers.
Original Documentation
https://www.gatsbyjs.org/docs/winning-over-developers/
@gatsbyjs/learning

Docs: Add "Data Integration" section in winning-over-developers.md

---

docs/docs/winning-over-developers.md
packages/gatsby-plugin-netlify-cms/src/cms.js

fix(docs): Fix some typos

---

docs/starters.yml

```
$ curl -s -I https://github.com/benjamingrobertson/gatsby-starter-accessibility | grep Location
Location: https://github.com/benrobertsonio/gatsby-starter-accessibility
```

Update starter repo url after user has changed github username

---

docs/blog/100days/start-blog/index.md

This new blog post is for challenge No.1 - create a new blog using Gatsby

(100DaysOfGatsby) Add challenge 1: create blog

---

docs/blog/100days/start-blog/index.md

Update typo from Gatsbyy to Gatsby

Update typo from Gatsbyy to Gatsby

---

docs/sites.yml

Adding my blog to the showcase, thanks y'all 💯

chore(showcase): Add Thomas Wang's Blog

---

docs/sites.yml

Adding Engleezi site to Gatsby showcase

Add Engleezi site

---

packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
yarn.lock

Thanks to @wardpeet this fixes broken tests in master

chore(gatsby): fix broken snapshots

---

docs/sites.yml

My Personal project about Resume Generatign with Gatsby.

Add Resume Generator Example

---

docs/docs/schema-customization.md

docs(schema-customization): Add missing comma

---

docs/sites.yml

chore(showcase): Add Sprucehill

---

docs/starters.yml

Revert a change from yesterday

chore(starters): Remove invalid tags

---

docs/blog/100days/free-hosting/index.md

This challenge asks participants to build and host their Gatsby site using free tools.

100DaysOfGatsby - Challenge 2 - Build and Deploy

---

docs/docs/what-you-dont-need-plugins-for.md

Revert "docs(What-you-dont-need-plugins-for): Grammar change to aid readability "

---

docs/sites.yml

Add personal website to showcase section.

chore(showcase): Add Shivam Sinha portfolio

---

docs/sites.yml

Add www.aboutmonica.com to the Gatsby Showcase. 
N/A

chore(showcase): Add Monica Powell portfolio

---

docs/blog/100days/start-blog/index.md

Fixing a minor oops so we don't have 2 different tags for the "100 Days of Gatsby" challenge.

Fixing “100-Day-of-Gatsby” tag to “100-Days-of-Gatsby” on Challenge 1

---

docs/docs/overview-of-the-gatsby-build-process.md

put file name into code fences
file name introduced in:
- PR #20522 `chore (doc): Update overview-of-the-gatsby-build-process.md`

chore(doc): file name into code fences

---

docs/docs/sourcing-from-ghost.md

* rm redundant path.resolve
* rm extracting createPage from actions since it's used only once

Simplify Ghost page creation code

---

docs/contributing/gatsby-docs-translation-guide.md

Add [gatsby-ja](https://github.com/gatsbyjs/gatsby-ja) to the translation list.

chore(docs): add gatsby-ja to the translation list

---

docs/sites.yml

Adding one of my company's site that use Gatsby to showcase. By [Grupo Fleury](http://www.grupofleury.com.br/)

chore(showcase): Add a+ saude

---

docs/docs/what-you-dont-need-plugins-for.md

chore(docs): Remove whitespace from Markdown link

---

docs/sites.yml

Hi everybody Shayan here!
I've created a [free chord search tool ](https://www.solfej.io/chords) that lets users search through every chord imaginable (over 4000+ single chord pages!). 
Each single chord page includes the notes, intervals, scales, and piano/guitar diagrams for the respective chord.
[Here's an example of a chord page (C major 7th)](https://www.solfej.io/chords/c-major-7th)
Chord search is a great example of what Gatsby can do out of the box. I'm using a simple node script to create ~4000 pages dynamically from a ~200mb dynamically created JSON file.
Let me know what you guys think!

Added Solfej Chord Search To Showcase

---

docs/blog/100days/free-hosting/index.md

Added ZEIT Now as a popular option for hosting Gatsby sites.

Add ZEIT Now

---

packages/gatsby/src/schema/node-model.js

chore(gatsby): Minor refactor in runQuery

---

packages/gatsby/src/query/queue.js

Before it was creating one Promise per job and doing an `await Promise.all` on them.
Afterwards it will listen to the event the queue will emit when all events have finished and then resolves a promise.
This way, at scale, we don't have to create thousands of promises (one per page) which means that this change eliminates one (small) source of scaling problems.

perf(gatsby): Create one promise per queue, not one per job

---

docs/docs/sourcing-from-the-filesystem.md

chore(docs): Add note about `sourceInstanceName`

---

docs/docs/glossary.md
docs/docs/glossary/jamstack.md
www/src/data/sidebars/doc-links.yaml

Updated glossary, sidebar with links to JAMStack entry.

Docs / Encyclopedia: Adds JAMStack entry.

---

packages/gatsby/package.json
yarn.lock

update contains fix of doScroll in ie10 where it before scrolled down, and now scroll left for better experience.
change: https://github.com/mikaelkristiansson/domready/commit/689caa8dfbf2bfeab1f25bd9ed860416ad364682
https://github.com/gatsbyjs/gatsby/issues/20582#issuecomment-574252049

chore(gatsby): updated package @mikaelkristiansson/domready

---

docs/tutorial/part-one/index.md
docs/tutorial/part-zero/index.md

- Add a comma.
- Change "setup" to "set up" (verb instead of noun).
https://www.gatsbyjs.org/tutorial/part-zero/

Adds a comma.

---

docs/docs/seo.md

remove domain from internal link
#20566 docs: improve gatsby-plugin-offline SSR seo

fix(docs): remove domain from internal link

---

docs/blog/2020-01-15-website-uptime/index.md

fix(blog): Fix date in website uptime article 

---

docs/blog/100days/gatsby-image/index.md

fix broken link
#20584 Add challenge 3 of 100DaysOfGatsby 

fix(blog): broken link

---

docs/blog/2017-10-05-portfolio-site-gatsby-wordpress/index.md
docs/blog/2018-11-03-building-an-accessible-lightbox/index.md
docs/docs/styled-components.md
examples/using-styled-components/README.md
packages/gatsby-plugin-styled-components/README.md

fix redirect from https://www.styled-components.com

fix(blog): 307 redirect from https://www.styled-components.com

---

docs/sites.yml

Add krishnagopinath.me to Showcase

chore(showcase): Add krishnagopinath portfolio site to Showcase

---

.github/ISSUE_TEMPLATE/documentation.md

fix a minor typo in the documentation issue template

fix a minor typo

---

docs/starters.yml

chore(starters): add gatsby-starter-material-emotion

---

docs/docs/how-gatsby-boosts-career.md

When @tavareshenrique was translating this page he spotted a incorrect link inside the text. I'm opening this PR to fix link.
Fix clients link

fix: Link inside text

---

docs/sites.yml

Adding my app to the showcase!  Review please :-)

chore(showcase): labelmake.jp to sites.yml

---

docs/docs/recipes/styling-css.md

fix italic format marker outside of code fences
#20679 Update styling-css.md

fix(docs): fix italic format marker outside of code fences

---

docs/docs/performance.md

Updates Addy Osmani's The Cost Of JavaScript to the 2019 release.

docs(performance): Updates article link

---

docs/sites.yml

Add personal website for Adam Bowen https://adamcbowen.com

chore(showcase): Add Adam bowen personal website to showcase 

---

packages/gatsby/src/query/queue.js

remove processing queue and waiting queue
fixes #20664 chore(gatsby): processing queue is never set with a job id

fix(chore): remove processing and waiting queue

---

docs/docs/recipes/working-with-themes.md

A few various typos on this file (most likely due to haste in writing!).
Have found and corrected all typos.
Due to this being a minor fix, I have gone to straight to opening a PR instead of an issue.
From the official Gatsby [Recipes: Working with themes](https://www.gatsbyjs.org/docs/recipes/working-with-themes) page.
N/A

(Docs) Fix typos in recipes/working-with-themes.md

---

docs/sites.yml

Adding See Kids Dream website to showcase

chore(showcase): Add See Kids Dream website to showcase

---

docs/starters.yml

Adds https://github.com/arshad/gatsby-starter-flex to starters.
Theme: https://github.com/arshad/gatsby-themes/tree/master/themes/gatsby-theme-flex
Demo: https://flex.arshad.io
Thank you

chore(starters): add gatsby-starter-flex

---

docs/sites.yml

Adding the personal website of Maarten Afink (https://www.maarten.im/)

chore(showcase): Add Maarten Afink portfolio site to showcase

---

docs/docs/bulma.md
docs/docs/post-css.md
docs/docs/tailwind-css.md

Fixing formatting issues for better readability
https://www.gatsbyjs.org/docs/post-css/ - post-css.md
https://www.gatsbyjs.org/docs/tailwind-css/ - tailwind-css.md
https://www.gatsbyjs.org/docs/bulma/ - bulma.md

chore: add inline codeblocks around some text for readability

---

docs/sites.yml

add qri.io to showcase

---

docs/contributing/docs-contributions.md

Update documentation since we changed the way redirects are listed on www.

Update docs on creating redirects

---

docs/tutorial/ecommerce-tutorial/index.md

Fix typo: Changed initialise to initialize and customise to customize

docs(tutorial): fix typo

---

docs/sites.yml

Add jellypepper.com to the showcase.

Add jellypepper.com to showcase

---

docs/sites.yml

Add https://www.miyamadojinja.com to the showcase.

Add miyamadojinja.com to the showcase

---

docs/docs/building-an-e-commerce-site.md

Fixed the spelling of "e-commerce" as described in issue #20790

Fixed typo: Issue #20790

---

docs/blog/2019-09-11-impossible-foods/index.md

Fixed spelling of "e-commerce" as described in issue #20790

Fixed type: Issue gatsbyjs#20790

---

packages/gatsby-plugin-sharp/src/plugin-options.js

Fix for https://github.com/gatsbyjs/gatsby/issues/20893

fix(gatsby-plugin-sharp): convert rotate boolean to int

---

docs/sites.yml

Add [Calisthenics Skills](https://calisthenicsskills.com) to showcase

Add calisthenics skills to showcase

---

docs/docs/headless-cms.md
docs/docs/sourcing-from-seams-cms.md

This is a document PR that will add the Seams-CMS source plugin in the headless-CMS section of the documentation.

Added source guide for Seams-CMS

---

docs/tutorial/ecommerce-tutorial/index.md

fix of gatsby-config.js of e-commerce Tutorial.
https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/
Fixes #20888

fix docs:ecommerce tutorial

---

docs/blog/2020-01-27-announcing-gatsby-builds-and-reports/index.md

Replace colons after numbers with dots as more standard

---

www/i18n.json

Adding Japanese to i18n, as the translation for the first Gatsby tutorial has been completed :tada: https://github.com/gatsbyjs/gatsby-ja/issues/1

feat: add Japanese to i18n

---

docs/blog/2020-01-27-announcing-gatsby-builds-and-reports/index.md

chore(blog): fix Markdown syntax

---

packages/gatsby/src/query/query-compiler.js

This is a follow up to the following PR: #20936
It addresses one potential issue mentioned in this review comment: https://github.com/gatsbyjs/gatsby/pull/20936/files#r371815743

fix(gatsby): Fix potential issue in fragment cycles detection

---

docs/sites.yml

Added sung.codes to sites.yml at the bottom.
Below is the screenshot (w/ image placeholder)

chore(showcase): Add sung.codes site

---

docs/docs/deploying-to-kintohub.md
docs/docs/preparing-for-deployment.md
www/src/data/sidebars/doc-links.yaml

This PR adds a guide to deploy Gatsby apps on [KintoHub](https://www.kintohub.com).
Not sure if it's the right way to do it or if I should go through any validation first.
Let me know, I'll be happy to answer any questions. 🙏

chore(docs): add KintoHub deployment guide

---

docs/sites.yml

Fix failing categories in sites.yml so tests will pass.

Fix failing categories

---

docs/blog/2020-01-08-git-workflows/index.md

Added clarity so new readers understand what "cloud team" means

fix(blog) Add Gatsby to title/excerpt for clarity

---

docs/docs/using-gatsby-without-graphql.md

Fixed a link to the Graphql documentation

fix(docs): Fix link to graphql docs

---

docs/sites.yml

site added here: #20825 `chore(showcase): Add See Kids Dream website to showcase`
accidently removed here: #20827 `Site Showcase submission request`
- #20825 `chore(showcase): Add See Kids Dream website to showcase`
- #20827 `Site Showcase submission request`

chore(showcase): re-Add See Kids Dream website to showcase

---

www/README.md

minor Typos fixed !

---

docs/docs/creating-a-starter.md

Add a section to the "Creating a Starter" doc for how to run a starter locally.

docs: Add section for how to run a starter locally

---

docs/blog/2019-06-18-dropping-support-for-node-6/index.md
docs/docs/glossary/node.md
docs/docs/preparing-your-environment.md
docs/docs/upgrading-node-js.md

Follow-up of #20762. Realized there were some links to this hash that weren't updated.

fix (www) additional links to "install nodejs"

---

packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/normalize.js

This fixes the flickering progress bar

chore(gatsby-source-drupal): Pass in reporter

---

docs/starters.yml

This PR adds a new starter, [`gatsby-starter-rocket-docs`](https://github.com/rocketseat/gatsby-starter-rocket-docs) 🚀

chore(starters): add gatsby-starter-rocket-docs

---

docs/docs/glossary.md
docs/docs/glossary/static-site-generator.md
www/src/data/sidebars/doc-links.yaml

Adds Static Site Generator article and excerpt, updates docs/glossary.md and doc-links.yaml with links to new article.

Add glossary/static-site-generator entry.

---

docs/blog/100days/mdx/index.md

Noticed a broken markdown link reviewing this week's challenge.
_N/A_
_None_

blog: correct broken markdown link

---

www/src/components/mdx-link.js

Fix file links downloading in MDX.
Fixes: #21100

fix(www): Fix downloading file links in MDX

---

www/src/components/__tests__/mdx-link.js
www/src/components/mdx-link.js

Make tests for the fix in #21101

chore(www): Create tests for mdx-link

---

www/src/components/banner.js

Same link as the previous banner. Slightly new copy.

Update banner for Gatsby Builds

---

docs/sites.yml

Cleaned up some sites from the showcase from findings of the Showcase Validator
remove https://nubrakes.com - Switched to Next.JS
remove https://www.measuresforjustice.org/ - Switched to Next.JS
remove https://axcept.io
remove https://votesaveamerica.com - Switched to Wordpress
remove https://tensiq.com/ - Switched to Wordpress
remove https://hackathons.hackclub.com/ - Switched to Next.JS
Remove https://timelyapp.com

chore(showcase): Clean up showcase

---

docs/starters.yml

chore(starters): add gatsby-starter-default-dark-mode

---

docs/starters.yml

chore(starters): add gatsby-memento-blogpost

---

docs/creators/creators.yml

Reverts gatsbyjs/gatsby#21132
The referenced image was not included in PR and it is breaking builds for now. So reverting this at least until image is added

Revert "Update creators.yml"

---

docs/sites.yml

Added a site to /docs/sites.yml.
(http://virajc.tech/)

chore(showcase): Add Viraj's portfolio site to showcase

---

docs/starters.yml

I think it's very important to establish a Future Action when developing. That's why my template allows me to see the Future Action on top of the page. I also designed it with an intuitive UX.
I hope my template will go up in the Gatsby starter library for other users who might use my template.

chore(staters): Add gatsby-starter-answer

---

docs/docs/deploying-to-zeit-now.md

The Example Project link was updated, so I fixed.
- old url: https://github.com/zeit/now-examples/tree/master/gatsby
- new url: https://github.com/zeit/now/tree/master/examples/gatsby

fix(docs): fix links to Example Project

---

starters/blog/package-lock.json
starters/default/package-lock.json
starters/gatsby-starter-blog-theme-core/package-lock.json
starters/gatsby-starter-blog-theme/package-lock.json
starters/gatsby-starter-notes-theme/package-lock.json
starters/gatsby-starter-theme/package-lock.json
starters/hello-world/package-lock.json

Should hopefully fix starters audit failing currently https://circleci.com/gh/gatsbyjs/gatsby/323994?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

chore(starters): bump @hapi/hoek in starters lock files

---

docs/sites.yml

Updated the source URL to reflect this new change

Update sites.yml to reflect my portfolio site

---

docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md

chore(docs): Putting the T in Twitter

---

www/src/utils/node/showcase.js

Broke in https://github.com/gatsbyjs/gatsby/pull/21217/files

fix(www): Add missing reporter

---

docs/contributing/events.md

We're in the process of revising our community event support process/policy. The new link brings the user to a form where they can submit their event info to be listed on the site.
Related to PR #21371.

Update to events info and link

---

docs/sites.yml

Add The Rift Metz website to the Gatsby Showcase 🚀
http://theriftmetz.com/

chore(showcase): Add The Rift Metz

---

docs/docs/end-to-end-testing.md

Added some basic information about using a GH Action to integrate Cypress into your repo, giving some basic CI function with little cost or setup.
Please let me know if this should be its own subheading, but I felt it fit under the already existing "Continuous Integration" heading.

chore(docs): GitHub Action information for Cypress

---

docs/blog/100days/pwa/index.md

This challenge introduces learners to progressive web apps.

(blog) 100daysofGatsby: challenge 7

---

www/redirects.yaml

add redirect for translation guide refactor

---

docs/sites.yml

Webanaya.com built with Gatsbyjs, Forestry, and Netlify.

include webanaya.com

---

docs/sites.yml

PR is more @signalnerve's deportment, so I'd like for him to approve, especially my sarcastic line 9684 ;)
Add to showcase: Built with (Cloudflare) Workers
I searched all PRs & Showcase, & found this site was missing.
Added "JavaScript" category since most will use JavaScript for some if not all of the Cloudflare Worker code.

[showcase] Built with (Cloudflare) Workers

---

docs/tutorial/part-zero/index.md

While fixing conflicts for the polish version of docs I've noticed this small error.

chore: fix list numbers

---

docs/docs/api-specification.md

#20873  Description
Updating the wording of the API specifications doc as v2 is out along with themes.
This is the docs that is being updated

API Specifications Documentation Update

---

docs/sites.yml

chore(showcase): Add adam.ai site

---

docs/docs/working-with-gifs.md

Spelling mistake corrected

---

.typo-ci.yml

Add config file to exclude words:
https://typoci.com/documentation

chore: Add Typo CI config

---

www/src/components/showcase-details.js

Remove extraneous query fields in site showcase query.

perf(www): Remove extraneous query fields in showcase-details query

---

packages/gatsby/src/redux/run-sift.js
packages/gatsby/src/schema/__tests__/node-model.js

This PR fixes an edge case issue with indexed sift querying.
Fixes #21457

fix(gatsby): Fix an edge case with sift queries using index

---

docs/blog/2018-12-17-turning-the-static-dynamic/index.md

apply redirects on netlify site
- #21186 `Fix config instructions for netlify lambda`

fix(blog): apply redirects on netlify site

---

docs/sites.yml

Please consider adding [Taskade](https://taskade.com) to the showcase! We just moved to Gatsby.

chore(showcase): Added Taskade

---

docs/sites.yml

chore(showcase): Add Lukas Horak website

---

docs/sites.yml

Updated sites.yml to submit my website to the Gatsby Showcase

chore(showcase): Add Matthew's portfolio site to  Showcase

---

docs/sites.yml
docs/starters.yml

A new starter for Gatsby+Contentful: a portfolio website with a blog

chore(starter): add gatsby-contentful-blog-portfolio

---

docs/docs/creating-global-styles.md
docs/docs/css-libraries-and-frameworks.md

Hi Maintainers 👋
This is my suggestion, 
add links on docs is to help understand the meaning of `styling approach`.
Links
- https://www.gatsbyjs.org/docs/creating-global-styles/
- https://www.gatsbyjs.org/docs/css-libraries-and-frameworks/
Thanks!

Add link explaining `styling approach`

---

docs/sites.yml

Add my blog made on Gatsby to the showcase.

Add Artem Sapegin’s Blog to showcase

---

docs/docs/quick-start.md

We do not explicitly have it stated to install gatsby CLI  globally. We do however have the `npm install -g gatsby-cli`.  I added a note to explain that the command handles the global installation.
https://www.gatsbyjs.org/docs/quick-start/
N/A

chore(doc):Add more description  to installing Gatsby-CLI globally

---

www/src/templates/template-blog-post.js
www/src/utils/node/docs.js

* Add back `title` in frontmatter for allMdx
* Change what we pass to pageContext to make more apparent what is being used.

fix(www): add back frontmatter to fix prev and next

---

docs/docs/theme-ui.md

This is a small update for the installation instructions in the Theme UI reference guide to account for changes in v0.3.

docs: Update Theme UI installation instructions for v0.3

---

docs/sites.yml

Add Health Pro Fitness Blog transformed from Wordpress into Full Gatsby Static MDX

Add healthprofitness blog

---

docs/contributing/translation/style-guide.md

(docs) Update translation/style-guide.md

---

packages/gatsby-plugin-google-analytics/README.md

docs(gatsby-plugin-google-analytics): Fixing super tiny issue in README

---

www/redirects.yaml

unify all entries to include trailing slash

chore(redirects): unify all entries to include slash

---

docs/sites.yml

Added ramonak.io site to showcase

---

docs/starters.yml

This pr will introduce a barebones starter for handling Square payments with Gatsby
Fixes #20975
Feel free to provide feedback

chore: add Square Starter to the starters list

---

docs/tutorial/part-two/index.md

Fix a line in tutorial so that it is in context.

chore(docs): Fix a line so be in context

---

docs/starters.yml

chore(starters): add gatsby-animate-starter

---

docs/starters.yml

chore(starters): add gatsby-starter-mountain

chore(starters): add gatsby-starter-mountain

---

docs/docs/using-graphql-playground.md

Filling in some missing syntax highlighting for code snippets in the document.

docs: add missing syntax highlight

---

docs/docs/glossary.md
docs/docs/glossary/markdown.md
www/src/data/sidebars/doc-links.yaml

Updated sidebar, glossary.md with links to new entry.

docs/glossary: Add Markdown article.

---

docs/starters.yml

chore(starters): add gatsby-starter-try-ghost

---

docs/docs/deploying-to-aws-amplify.md

Hi Maintainers 👋
Fixed to display Emoji Fire.
Why?:
Emoji can't be displayed.
Link:
https://www.gatsbyjs.org/docs/deploying-to-aws-amplify/
Thanks!

fix Fire Emoji displayed.

---

docs/starters.yml

I had to close my former PR because it orphaned

chore(starters): add gatsby-starter-redux-storybook

---

docs/sites.yml

Add [Codeful](https://www.codeful.fi/) to Gatsby showcase.

Add codeful.fi to Gatsby showcase.

---

docs/docs/caching.md
docs/docs/gatsby-cli.md

fixed broken_link of gatsby starter #21720

---

docs/blog/100days/accessibility/index.md
docs/blog/100days/seo/index.md

Draft of 100DaysOfGatsby challenge 9 where we invite developers to enhance their sites for SEO concerns. I'll alert the reviewer once the draft becomes finished

(blog)100daysofgatsby challenge 9

---

docs/sites.yml

Hi there :)
This PR adds Playlist Detective to the site showcase, a website that makes Spotify playlist search easy using Algolia.

misc(showcase): add Playlist Detective

---

docs/starters.yml

chore(starters): add gatsby-starter-blog-and-cv

---

docs/sites.yml

Request to add talentpoint.co to the showcase section.
No related issues.

Add TalentPoint.co to sites.yml

---

docs/sites.yml

Request to add vaktija.eu to the showcase section.
No related issues.

chore(showcase):Add vaktija.eu to showcase

---

docs/sites.yml

chore(starters): Update description for gis-netzwerk

---

docs/docs/setting-up-gatsby-without-gatsby-new.md
docs/docs/sourcing-from-kentico-kontent.md

- fix anchor links
- remove link because section removed
#19267 Add link checker for Gatsby Docs

fix(docs): fix anchor links

---

www/src/views/showcase/filtered-showcase.js
www/src/views/starter-library/filtered-starters.js

Fix for #21867.
I fixed to the correct variables.
Fixes #21867

FIx (www):  fixed rendering errors in showcase and starter page.

---

docs/tutorial/part-two/index.md

- Changes "css" to "CSS" where appropriate
- N/A
- N/A

Improve consistent usage of "CSS"

---

www/gatsby-config.js

Add date to rss feed

---

docs/docs/gatsby-cli.md
docs/docs/profiling-site-performance-with-react-profiler.md
packages/gatsby-cli/README.md
packages/gatsby-cli/src/create-cli.js
packages/gatsby/src/commands/build.js
packages/gatsby/src/utils/webpack.config.js
www/src/data/sidebars/doc-links.yaml

Adds profiling to gatsby under the option `--profile`
Fixes #21535

feat(gatsby): add react profiling option

---

docs/blog/author.yaml

Fix blog post author company name (rebranded)

Fix company name of author (rebranded)

---

docs/blog/2020-01-12-faster-sites-with-optimized-media-assets/index.md

Added hyperlinks of the plugin to the blogpost for faster referencing on opening the article.

chore(blog): Add hyperlink in first paragraph

---

docs/starters.yml

chore(starters): add gatsby-sidedrawer

---

docs/tutorial/part-seven/index.md

Closes #21864.
I think some extra information on what a ‘slug’ is could be a nice improvement given how often the term is used the tutorial. Users might not be 100% clear on what exactly ‘path’ is referring to.   
```
Creating slugs for pages 
Creating new pages has two steps:
1. Generate the “path” or “slug” for the page.
2. Create the page.
```
A possible suggestion:
```
Creating slugs for pages
A ‘slug’ is the unique identifying part of a web address, 
such as the `tutorial/part-seven` part of the page https://www.gatsbyjs.org/tutorial/part-seven/.
It is also referred to as the ‘path’ but we will use the term ‘slug’ during this tutorial.
 Creating new pages has two steps:
1. Generate the “path” or “slug” for the page.
2. Create the page.
```
Why should we document this and who will …

(docs) Add a defintion of 'slug' to Part 7 tutorial 

---

docs/sites.yml

Added my recipe website, https://ememrecipes.com, to the sites.yml file. Thanks!

chore(showcase): Add Em Em Recipes website to Showcase

---

packages/gatsby/src/query/graphql-runner.ts
packages/gatsby/src/redux/types.ts

Ports graphql-runner to TypeScript

chore(gatsby): Port gql runner to TypeScript

---

docs/sites.yml

Updated the link to one of the example sites from `www.madewithlove.be` to `madewithlove.com` since we recently moved to a new TLD.

Update madewithlove url since it was moved to a different TLD

---

docs/docs/performance.md

When I was updating another doc and considering linking to the guide overview page on Performance, I noticed it didn't follow the Gatsby Style Guide for pronoun usage. This PR makes that update and adjusts the introductory language.
N/A
N/A

[docs][guides] update Performance doc per style guide

---

docs/docs/profiling-site-performance-with-react-profiler.md

changed:
- fix codeblock language
- #21863 `feat(gatsby): add react profiling option`

fix(docs): react profiling

---

packages/gatsby/src/commands/clean.ts

Port src/commands/clean to TypeScript

chore(gatsby): Convert clean to typescript

---

docs/sites.yml

Submission for xavie.mirmon.co.uk to site showcase.

Adding xavie.mirmon.co.uk to sites.yml

---

docs/categories.yml
docs/docs/sourcing-from-agilitycms.md
docs/starters.yml

Added the Category **CMS: Agility CMS** for starter sites. Also updated the starter docs for Agility CMS, and info regarding the Agility CMS source plugin.

updates to Agility CMS info

---

docs/blog/100days/performance/index.md

- fix 404 internal links
#19267 Add link checker for Gatsby Docs

fix(blog): challenge 10 of 100daysofgatsby

---

packages/gatsby-core-utils/src/create-content-digest.ts
packages/gatsby/src/commands/build-javascript.ts
packages/gatsby/src/commands/build.js

chore(gatsby-core-utils): create-content-digest to TS

---

packages/gatsby-core-utils/src/get-gatsby-version.ts

chore(gatsby-core-utils): get-gatsby-version to TS

---

packages/gatsby-core-utils/src/url.ts
packages/gatsby/src/commands/build-javascript.ts
packages/gatsby/src/commands/build.js

chore(gatsby-core-utils): url to TS

---

packages/gatsby/src/db/loki/nodes-query.js
packages/gatsby/src/redux/run-sift.js
packages/gatsby/src/utils/__tests__/prepare-regex.js
packages/gatsby/src/utils/prepare-regex.ts

Convert `utils/prepare-regex` to typescript

chore(gatsby): Convert utils/prepare-regex to typescript

---

packages/gatsby/src/commands/build-javascript.ts

Cleanup build-javascript

---

docs/sites.yml

Updated sites.yml to submit my website to the Gatsby Showcase

Submit Softblues.io site to Gatsby Showcase

---

packages/gatsby/src/utils/worker/child.js
packages/gatsby/src/utils/worker/page-data.ts

Convert `utils/worker/page-data` and test to typescript

chore(gatsby): Convert utils/worker/page-data to typescript

---

packages/gatsby-plugin-mdx/README.md

There are several broken links in the [configuration](https://github.com/lukePeavey/gatsby/tree/master/packages/gatsby-plugin-mdx#configuration) section of the README (the links do not match headings)
- `[remarkPlugins](#remark-plugins)`
- `[rehypePlugins](#rehype-plugins)`
It looks like these settings were renamed in efc5713e47b375ba4349f4909428d5bf1ad6790f, but the corresponding headings were not updated.
Updated the headings to match the setting names (which fixes the links in the [configuration](https://github.com/lukePeavey/gatsby/tree/master/packages/gatsby-plugin-mdx#configuration) section)
- [`# MD plugins`](https://github.com/lukePeavey/gatsby/tree/master/packages/gatsby-plugin-mdx#md-plugins) -> `# Remark plugins`
- [`# HAST …

docs(gatsby-plugin-mdx): fix broken links in readme

---

packages/gatsby-cli/src/init-starter.ts
packages/gatsby-plugin-sharp/src/sharp-error.js
packages/gatsby-theme/gatsby-theme-debug.js
packages/gatsby/src/bootstrap/__tests__/requires-writer.js
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/schema/__tests__/context.js
packages/gatsby/src/utils/__tests__/jobs-manager.js

chore(gatsby): fix typos across the project

---

docs/sites.yml

Add clipchamp.com to site showcase

chore(showcase): Add clipchamp.com to site showcase

---

docs/sites.yml

Add build_by param to Softblues site in showcase

Add build_by param to Softblues

---

docs/blog/2017-02-21-1-0-progress-update-where-came-from-where-going/index.md
docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
docs/blog/2017-09-18-gatsby-modern-static-generation/index.md
docs/docs/browser-support.md
docs/docs/building-with-components.md
packages/gatsby-plugin-glamor/README.md
packages/gatsby-remark-prismjs/README.md

Updated the ReactJS Home URL

---

docs/docs/awesome-gatsby-resources.md

Adding Building a SaaS app with Gatsby and the JAMstack

feat(docs): Adding Building a SaaS app with Gatsby and the JAMstack

---

docs/docs/write-pages.md

I fixed broken links in write-pages.

docs(gatsby): Fix broken links

---

docs/creators/creators.yml

add description into creators.yml

---

docs/blog/2020-02-11-founding-organizations/index.md
docs/docs/deploying-to-cloudflare-workers.md
examples/recipe-linking-between-pages/README.md
examples/using-square-payments/src/components/paymentForm.js

chore(docs): 🧹 Fix case of GitHub and JavaScript

---

packages/gatsby-plugin-remove-trailing-slashes/README.md

- link directly to current resource location to preserve longevity

Update link to Netlify documentation to avoid redirect

---

docs/docs/sourcing-from-sanity.md

chore(docs): 🧹 Fix Markdown link

---

examples/ecommerce-tutorial-with-stripe/src/pages/page-2.js
packages/gatsby-cli/src/reporter/index.js
packages/gatsby/src/bootstrap/load-plugins/validate.js
peril/rules/validate-yaml.ts
www/src/templates/template-api-markdown.js

chore(docs) : fixed several typos

---

package.json
packages/gatsby/package.json
packages/gatsby/src/utils/cache.ts
yarn.lock

Split from #20727 as it needs additional change (typing fixes after change in `@types/cache-manager` - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42554 )

chore: bump cache-manager

---

www/src/utils/__tests__/i18n.js
www/src/utils/i18n.js
www/src/utils/node/docs.js

Add test coverage for i18n utilities that are used throughout our website codebase.

chore(www) Add unit tests for i18n utils

---

docs/sites.yml

Adds the Mob HQ website to the showcase.
N/A
N/A

chore(showcase):Adds Mob HQ to showcase

---

docs/starters.yml

Adding a new Gatsby Starter built with Netlify CMS, A simple blog for designers and developers
Article: https://w3layouts.com/articles/delog-gatsby-starter-netlify-cms/
Repo: https://github.com/W3Layouts/gatsby-starter-delog
Demo: https://delog-w3layouts.netlify.com/

Adding Gatsby Starter built with Netlify CMS - Delog 

---

docs/docs/adding-analytics.md

chore(docs): add link to GoatCounter analytics

---

packages/gatsby/index.d.ts

fix(gatsby): fix type definition

---

packages/gatsby/src/commands/build.js
packages/gatsby/src/utils/tracer/index.ts

Convert `utils/tracer/index` to typescript.

chore(gatsby): Convert utils/tracer/index to typescript

---

docs/blog/2019-03-15-design-code-blog-post/index.md

#21931  Description
Small fix for linking my updated Twitter handle in the blog 🙏

[blogpost] Updating my twitter profile link in blog post

---

docs/docs/awesome-gatsby-resources.md

Adds a link to my 10-video Gatsby tutorial series to Awesome Gatsby Resources. (Hoping to add more videos soon!)

Add video tutorials to awesome-gatsby-resources.md

---

docs/starters.yml

Submitting a new Gatsby starter, integrated with Airtable.
On-line demo is available at:
https://gatsby-airtable-listing.netlify.com/

chore(starters): add gatsby-airtable-listing

---

docs/sites.yml

Adds [my personal website](https://kelvindecosta.com) to the [site showcase](https://www.gatsbyjs.org/showcase/)

chore(showcase): Add kelvindecosta.com to site showcase

---

docs/blog/100days/apps/index.md

This continues the 100DaysOfGatsby weekly challenges and introduces developers to using Gatsby for webapps.

draft(blog) 100DaysOfGatsby Challenge 12 

---

packages/gatsby-cli/src/reporter/loggers/ink/cli.js

Fix import

---

benchmarks/markdown_id/content/blog/hello-world/index.md
benchmarks/markdown_id/content/blog/my-second-post/index.md
benchmarks/markdown_slug/content/blog/hello-world/index.md
benchmarks/markdown_slug/content/blog/my-second-post/index.md
starters/blog/content/blog/hello-world/index.md
starters/blog/content/blog/my-second-post/index.md
starters/gatsby-starter-blog-theme-core/content/posts/my-second-post.mdx
starters/gatsby-starter-blog-theme/content/posts/my-second-post.mdx

chore(starters): 🔒 Fix missing HTTPS on Wikipedia links

---

docs/blog/2018-2-27-why-i-upgraded-my-website-to-gatsbyjs-from-jekyll/index.md
docs/blog/2019-08-02-what-is-jsx-pragma/index.md
docs/blog/2019-12-12-how-we-accidentally-launched-a-popular-gatsby-plugin/index.md
docs/docs/recipes/working-with-themes.md
docs/docs/sourcing-from-buttercms.md
docs/starters.yml
www/src/pages/guidelines/typography.js

chore(docs): remove whitespace before commas

---

packages/gatsby/src/utils/api-browser-docs.js

Clarify that onRouteUpdate is called on the initial load of the app

---

docs/sites.yml

Following the style used at https://yaml.org/ and also in starters.yml.

chore(showcase): Standardize urls in sites.yml by removing quotes.

---

docs/blog/2019-04-30-how-to-build-a-blog-with-wordpress-and-gatsby-part-2/index.md

changes:
- remove unused import

fix(bog): how-to-build-a-blog pt2 -> remove unused import

---

packages/gatsby/src/schema/types/built-in-types.ts

I converted built-in-types to typescript

chore(gatsby): Convert built-in-types to typescript

---

packages/gatsby/src/utils/feedback.ts

This is a crude - temporary - version of increasing the odds of receiving a feedback request 5x. I tested manually and verified that it does give a 5x chance increase.

chore(gatsby): Increase chances of seeing feedback request 5x

---

docs/docs/adding-an-rss-feed.md

https://github.com/gatsbyjs/gatsby/issues/16018

Fix the setup() function in the documentation

---

packages/gatsby-plugin-manifest/package.json
packages/gatsby-plugin-sharp/package.json
packages/gatsby-remark-images-contentful/package.json
packages/gatsby-transformer-sharp/package.json
packages/gatsby/src/bootstrap/index.js
yarn.lock

chore(gatsby): Update sharp and remove Promise shim for Node 8

---

docs/blog/2020-03-20-dropping-support-for-node-8/index.md

I missed a typo in the original PR.

Fix typo in blog post

---

docs/blog/author.yaml

chore(blog): Update bio for blog

---

docs/tutorial/part-zero/index.md

chore(docs): typo fix

---

docs/contributing/submit-to-creator-showcase.md
docs/creators/creators.yml

changes:
- remove quotes from `creator.yaml`
- remove quotes in `/contributing/submit-to-creator-showcase.md`
- checked changes with yaml validator
- #22223 `chore(showcase): Standardize urls in sites.yml by removing quotes.`

chore(showcase): Standardize urls in creators.yml by removing quotes (3)

---

docs/blog/2020-03-23-Flying-Feature-Flags-with-New-LaunchDarkly-plugin/index.md

changes:
- fix code block
_Note:_
- code inside code block is reformated automatic by linter/prettier
- #22405 `Blog post feature flags`

fix(blog): feature toggle - remove domain and fix code block

---

www/src/pages/guidelines/typography.js

changes:
- remove space before comma
- #22286 `chore(docs): remove whitespace before commas`

fix(docs): remove space before comma

---

docs/sites.yml

changes:
- remove more quotes from sites.yaml
- checked changes with yaml validator
- #22223 `chore(showcase): Standardize urls in sites.yml by removing quotes.`

chore(showcase): Standardize urls in sites.yml by removing quotes (2)

---

docs/blog/2019-12-12-how-we-accidentally-launched-a-popular-gatsby-plugin/index.md

changes:
- put resources path in code blocks

fix(blog): put path in code blocks

---

docs/blog/100days/apps/index.md

changes:
- add linkt to Auth0
- #22382  `draft(blog) 100DaysOfGatsby Challenge 12`

fix(blog): 100DaysOfGatsby Challenge 12 - add auth0 link

---

docs/sites.yml

Add COVID-19 Worldwide Stats to showcase

---

docs/tutorial/using-multiple-themes-together.md

A couple missed changes in #21714

Minor fixes for Multiple Themes Tutorial

---

packages/gatsby/src/bootstrap/schema-hot-reloader.ts
packages/gatsby/src/commands/develop.ts

I converted schema-hot-reloader to typescript

chore(gatsby): Convert schema-hot-reloader to typescript

---

docs/sites.yml

Adding a Folding@Home Stats site: https://folding.traction.one

docs(sites): add Folding@Home Stats site

---

www/i18n.json

Added Marathi in Ongoing Translation Section in Gatsby website.
[Repo](https://github.com/gatsbyjs/gatsby-mr)

chore(contributing): Added Marathi in Ongoing Translation Section

---

docs/sites.yml

**Website**: https://flattenthecurve.co.nz
**Repo**: https://github.com/carlaiau/flatten-the-curve
This has been put together quickly and is still a work in progress directed by community and user feedback.

docs(sites): add flattenthecurve.co.nz to site showcase

---

docs/sites.yml

Website: https://www.takeouttracker.com/

Add TakeoutTracker.com to site showcase

---

docs/contributing/translation/ui-messages.md

changed:
- prims code language
- #21805 `(docs) Guide for translating UI text with Lingui`

fix(docs): Guide for translating UI - code language

---

packages/gatsby-plugin-google-analytics/package.json

This PR add deps what used in code but not included in `packages.json`
Nope
Nope

chore(gatsby-plugin-google-analytics) Add missing deps

---

packages/gatsby-source-contentful/src/extend-node-type.js

This adds a local cache for the base64 image fetcher.
The tl;dr is that this cuts the build time in about half for at least one site that was fetching an image for the page thumbnail during the "run queries" step.
By default it'll put the images in `.cache/remote_cache/images`.
The assumption is that images are immutable so there's no additional roundtrip in case an image is locally cached.
The local cache is using a sha1 hash for file name because the url length may exceed the file name length on certain (or all) OSes.
Regarding SHA-1: While sha1 is cryptographically insecure, I don't think there's a risk for this purpose. Worst case there is a collision and I'm not quite sure in what scenario you would abuse that.
The PR also adds support for a `GATSBY_REMOTE_CACHE` env var (default is …

perf(gatsby-source-contentful): Add cache for remote imgs

---

www/gatsby-node.js
www/src/components/I18nContext.js

This way, changes to www in files with translateable text in them don't cause the PO files to be changed.

chore(www) Disable lingui when not running with localization enabled

---

docs/docs/glossary.md
docs/docs/glossary/server-side-rendering.md
www/src/data/sidebars/doc-links.yaml

doc-links.yaml, docs/glossary.md: Link to server-side rendering entry.

Add Server-Side Rendering article.

---

docs/docs/glossary.md
docs/docs/glossary/content-delivery-network.md
www/src/data/sidebars/doc-links.yaml

Also updated glossary.md and doc-links.yaml with links to the new entry

docs/glossary: Add Content Delivery Network entry

---

www/src/data/locales/en/messages.po
www/src/data/locales/ja/messages.po

There was a commit that caused all the line numbers for translations to be updated but didn't update the PO files. Update them now to keep them in sync. I'll need to think of a better way to keep them in track later.

Update lingui PO files

---

docs/sites.yml

**Description**
Hi, I've added my site to sites.yml to be included in the Gatsby Showcase.
Do let me know if I've missed out anything.
💜Thanks!

chore(showcase): Add Jason Zheng's Portfolio

---

docs/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/index.md

chore(blog) Fix escaped chars in title

---

docs/starters.yml

I think the reason that the two tests didn't pass is again the problem with the node modules vulnerabilities. I experienced the same thing also with my first starter #22077. Nevertheless, it got merged. 
#21831

chore(starters): add gatsby-starter-canada-pandemic 

---

docs/blog/2020-03-23-introducing-gatsby-web-creators/index.md

We've adjusted our schedule for Gatsby Web Creators, so this blog post update makes that official.
Not really applicable, but we've also updated the Gatsbyjs.com landing page and Twitch profile to further document the change. (thanks @caitlinthefirst!)
N/A

fix: change weekly cadence in Web Creators post

---

docs/sites.yml

Adding Tyson Foods websites to sites showcase

Added Tyson Foods websites to sites.yml

---

integration-tests/gatsby-cli/__tests__/feedback.js

Integration tests for gatsby feedback

chore(gatsby-cli): Add integration tests for `gatsby feedback`

---

docs/blog/2020-04-02-community-qa-with-kyle-mathews/index.md

Add blog post for community Q&A

---

docs/blog/100days/use-themes/index.md

This week we're asking developers to use themes

(blog) 100days challenge 14

---

packages/gatsby-plugin-sharp/package.json
packages/gatsby-remark-images/package.json
packages/gatsby-transformer-sharp/package.json
yarn.lock

`minimist` versions less than `0.2.1` and less than `1.2.3` [have a vulnerability](https://www.npmjs.com/advisories/1179). I've updated those where possible
Since the insecure versions of `minimist` were being mostly pulled in by old versions of `mkdirp` I've updated those where I could:
- Updated `potrace` which depends on `jimp@^0.9.6` ([which is when `jimp` added a `^` to their `mkdirp` dependency](https://github.com/oliver-moran/jimp/releases/tag/v0.9.6))
- Updated the `extract-zip@^1.6.6` sub-dependency to `1.7.0` [(when they added a `^` to their `mkdirp` dependency)](https://github.com/maxogden/extract-zip/releases/tag/v1.7.0)
- Updated the `loader-fs-cache@^1.0.0` sub-dependency to `1.0.3` which also uses a `^` for their `mkdirp` dependency
There were however 2 instances of …

fix(dependencies): bump potrace version

---

packages/gatsby/package.json
packages/gatsby/src/recipes/__snapshots__/recipe-machine.test.js.snap
packages/gatsby/src/recipes/apply-plan.js
packages/gatsby/src/recipes/cli.js
packages/gatsby/src/recipes/create-plan.js
packages/gatsby/src/recipes/graphql.js
packages/gatsby/src/recipes/providers/fs/file.js
packages/gatsby/src/recipes/recipe-machine.js
packages/gatsby/src/recipes/recipe-machine.test.js

Chore(Recipes): Add recipes machine tests

---

benchmarks/mdx/package.json

Update the benchmark `willit` version to always use latest.
n/a
n/a

Update benchmark willit version to *

---

docs/sites.yml

Add https://www.hanarecafe.com to the showcase.
There are a bunch of typo warnings including my name but they are all correct Japanese words.

chore(showcase): Add hanarecafe.com to the Showcase

---

docs/starters.yml

The `gatsby-starter-under-construction` was redesigned, renamed and extended into a Gatsby Theme: https://github.com/robinmetral/gatsby-theme-oss ([demo](https://gatsby-theme-oss.netlify.com/)).
This PR updates its details in the Starter Library.
None.
None.

chore(starters): update gatsby-theme-oss

---

docs/starters.yml

added gatsby-starter-song design by s-ong-c
- Mobile friendly and fully responsive
- Emoji (emojione)
- Code syntax highlighting (atom-one-light Style)
- Comment feature ( utterances)
- Post side PostTOC
- Simple fresh design like Medium 
- Readability

chore(starters): add gatsby-starter-song

---

docs/starters.yml

chore(starters): add gatsby-starter-22boxes-uno

---

docs/sites.yml

chore(sites): Add covid19.thegauntlet.ca

---

docs/docs/sourcing-from-graphcms.md

Update broken link in to GraphCMS API docs in `sourcing-from-graphcms.md`

Update broken link in sourcing-from-graphcms.md

---

docs/sites.yml

Added The COVID Tracking Project to the sites file. Thanks for all your great work, we have only been able to deliver this much-needed information quickly because Gatsby is so easy to build with!

chore(docs): Add site The COVID Tracking Project

---

docs/docs/telemetry.md

fix: fix grammar issues with formatting

---

docs/contributing/organize-a-gatsby-event.md

Update to clarify that the program is on hold due to COVID-19.

Update "organize a community event" page

---

docs/contributing/events.md

Updating to clarify that community support is currently suspended.

community event page update

---

docs/docs/telemetry.md
docs/sites.yml

Added mrkaluzny.com

---

docs/starters.yml

Add a `gatsby-starter-kontent-lumen` starter template.

chore(starters): add gatsby-starter-kontent-lumen

---

docs/starters.yml

A starter project that includes Typescript support, @emotion/styled, TailwindCSS and configured eslint.

chore(starters): gatsby-ts-tw-styled-eslint-starter

---

packages/gatsby/src/recipes/providers/fs/file.test.js
packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
packages/gatsby/src/recipes/providers/gatsby/plugin.js
packages/gatsby/src/recipes/providers/gatsby/plugin.test.js

Also moves gatsby plugin provider to new structure for resources.

fix(recipes): Don't duplicate plugin configuration by default

---

docs/tutorial/seo-and-social-sharing-cards-tutorial/index.md

While using the Gatsby documentation I found this little, let's say typo, since it refers to a `data` variable that is not defined.

docs: fix references to undefined data variable

---

packages/gatsby/package.json
packages/gatsby/src/recipes/__snapshots__/create-types.test.js.snap
packages/gatsby/src/recipes/create-types.js
packages/gatsby/src/recipes/create-types.test.js
packages/gatsby/src/recipes/graphql.js
packages/gatsby/src/recipes/providers/fs/__snapshots__/file.test.js.snap
packages/gatsby/src/recipes/providers/fs/file.js
packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
packages/gatsby/src/recipes/providers/gatsby/plugin.js
packages/gatsby/src/recipes/providers/gatsby/plugin.test.js
packages/gatsby/src/recipes/providers/npm/__snapshots__/package-json.test.js.snap
packages/gatsby/src/recipes/providers/npm/package-json.js
packages/gatsby/src/recipes/providers/npm/package-json.test.js
packages/gatsby/src/recipes/providers/resource-test-helper.js

Also updates some provider API signatures.

feat(recipes): Generate graphql schema from resources

---

docs/blog/2020-04-07-virtual-gatsby-days-2020-CFP/index.md

Late-breaking change of days for Gatsby Days Virtual in June, changed for tomorrow's CFP announcement blog post

Date Change for virtual Gatsby Days

---

packages/gatsby/src/query/graphql-runner.ts

Use v8 serialize for context

---

docs/contributing/how-to-file-an-issue.md

I got a question recently from someone asking about a docs improvement, and when I sent them to the "How to file an issue" page they were confused about whether it also extended to docs. I updated the page in this PR to make it more clear what issues can and should include.
N/A
N/A

[contributing] update doc on filing issues

---

packages/gatsby/src/commands/recipes.ts
packages/gatsby/src/recipes/providers/npm/__snapshots__/package-json.test.js.snap
packages/gatsby/src/recipes/providers/npm/package-json.js
packages/gatsby/src/recipes/providers/npm/package-json.test.js
packages/gatsby/src/recipes/providers/resource-schema.js
packages/gatsby/src/recipes/providers/resource-test-helper.js

Fix import statements
Log errors

Fix recipes

---

packages/gatsby/src/commands/recipes.ts
packages/gatsby/src/recipes/apply-plan.js
packages/gatsby/src/recipes/create-plan.js
packages/gatsby/src/recipes/providers/npm/__snapshots__/package-json.test.js.snap
packages/gatsby/src/recipes/providers/npm/__snapshots__/script.test.js.snap
packages/gatsby/src/recipes/providers/npm/package-json.js
packages/gatsby/src/recipes/providers/npm/package-json.test.js
packages/gatsby/src/recipes/providers/npm/script.js
packages/gatsby/src/recipes/providers/resource-schema.js
packages/gatsby/src/recipes/providers/resource-test-helper.js
packages/gatsby/src/recipes/recipe-machine.js
packages/gatsby/src/recipes/todo.md

Fix more recipes stuff

---

docs/blog/2020-04-01-LA-2020-Mathews/index.md
docs/blog/2020-04-02-LA-2020-Schau/index.md
docs/blog/2020-04-05-LA-2020-Gladwell.md

Now that we have days nailed down, want to add that call out to the existing blog posts.

Update blogs with Gatsby Days info

---

docs/blog/2020-04-09-LA-2020-mcmahon/index.md

New video blog post for Thursday 04/08

Add video blog 9 Gatsby Days LA 2020

---

docs/blog/2020-04-07-virtual-gatsby-days-2020-CFP/index.md

Change event time to PST hours and remove errant backslash

Virtual Gatsby Days CFP time change and typo fix

---

docs/blog/2020-04-10-LA-2020-Libere/index.md

Blog got added with some linting issues. This should solve that.

(chore): Fixing linting on blog post

---

packages/gatsby/package.json
packages/gatsby/src/recipes/__snapshots__/create-types.test.js.snap
packages/gatsby/src/recipes/__snapshots__/recipe-machine.test.js.snap
packages/gatsby/src/recipes/apply-plan.js
packages/gatsby/src/recipes/cli.js
packages/gatsby/src/recipes/create-plan.js
packages/gatsby/src/recipes/create-types.js
packages/gatsby/src/recipes/eslint.mdx
packages/gatsby/src/recipes/providers/fs/__snapshots__/file.test.js.snap
packages/gatsby/src/recipes/providers/fs/file.js
packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
packages/gatsby/src/recipes/providers/gatsby/plugin.js
packages/gatsby/src/recipes/providers/npm/__snapshots__/package.test.js.snap
packages/gatsby/src/recipes/providers/npm/__snapshots__/script.test.js.snap
packages/gatsby/src/recipes/providers/npm/package-json.js
packages/gatsby/src/recipes/providers/npm/package.js
packages/gatsby/src/recipes/providers/npm/package.test.js
packages/gatsby/src/recipes/providers/npm/script.js
packages/gatsby/src/recipes/providers/resource-schema.js
packages/gatsby/src/recipes/providers/resource-test-helper.js
packages/gatsby/src/recipes/recipe-machine.js
packages/gatsby/src/recipes/recipe-machine.test.js

https://twitter.com/kylemathews/status/1248050926121701376

feat(recipes): Show recap of operations & show diff for changes to files

---

scripts/e2e-test.sh

Fixes grammar in a code comment

chore(scripts): Fix grammar in comment

---

packages/gatsby/package.json
packages/gatsby/src/recipes/__snapshots__/recipe-machine.test.js.snap
packages/gatsby/src/recipes/__snapshots__/validate-recipe.test.js.snap
packages/gatsby/src/recipes/cli.js
packages/gatsby/src/recipes/providers/fs/__snapshots__/file.test.js.snap
packages/gatsby/src/recipes/providers/fs/file.js
packages/gatsby/src/recipes/providers/npm/package.js
packages/gatsby/src/recipes/providers/resource-schema.js
packages/gatsby/src/recipes/recipe-machine.js
packages/gatsby/src/recipes/recipe-machine.test.js
packages/gatsby/src/recipes/todo.md
packages/gatsby/src/recipes/validate-recipe.js
packages/gatsby/src/recipes/validate-recipe.test.js

We'll make this prettier over time

feat(Recipes): Validate resources & improve file diffing

---

docs/sites.yml

Add Jamify.me to sites.yml

---

.circleci/config.yml

Update the script to run soon so we can test it.

test(.circleci) update weekly sync script

---

docs/blog/2020-04-05-LA-2020-Gladwell/index.md

Fix spelling of Grant's last name.

docs: Update spelling error in 2020-04-05 blog post

---

.circleci/config.yml

Set the weekly i18n sync script to run at 6pm PST.

fix(.circleci) Set the weekly i18n sync script to run at Friday 6pm PST

---

docs/starters.yml

I updated `docs/starters.yml` by adding functionality to the starter I made last time.

chore(starters): update gatsby-starter-typescript

---

docs/sites.yml

Adds duetocovid19.com to the site showcase

Adds duetocovid19.com to sites.yml

---

packages/gatsby/src/recipes/cli.js

Markdown ignores new lines and so should we

feat(recipes): Eliminate new lines from markdown

---

docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md

changes:
- fix code block language from jsx to js
- add code block language so all code blocks have a language
- #22561 `chore(tutorial):Add DatoCMS/Snipcart tutorial`

fix(tutorial): code block language

---

packages/gatsby/package.json
packages/gatsby/src/recipes/cli.js

feat(recipes): Tell people recipes is experimental & point them to the umbrella issue

---

packages/gatsby-plugin-fullstory/src/__tests__/__snapshots__/gatsby-ssr.js.snap
packages/gatsby-plugin-fullstory/src/gatsby-ssr.js

fix(gatsby-plugin-fullstory): Updated to Edge URL + Add Updated JS Code

---

www/src/components/events/__tests__/event-list.js
www/src/components/events/event-list.js

Not going to display upcoming events while they're currently on pause.

Remove upcoming events

---

docs/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/index.md

changed:
- apply formatting like on other [`Why xxx?`-sections](https://www.gatsbyjs.org/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/#why-gatsby), otherwise it is a one big paragraph
- #22602 `Blog case study mag mutual`
- https://www.gatsbyjs.org/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/#why-gatsby

fix(blog): MagMutual - fix format

---

packages/gatsby/package.json
packages/gatsby/src/recipes/README.md
packages/gatsby/src/recipes/cli.js
packages/gatsby/src/recipes/mdx-src/emotion.mdx
packages/gatsby/src/recipes/mdx-src/gatsby-plugin-layout.mdx
packages/gatsby/src/recipes/mdx-src/gatsby-theme-blog.mdx
packages/gatsby/src/recipes/mdx-src/jest.mdx
packages/gatsby/src/recipes/mdx-src/prettier-git-hook.mdx
packages/gatsby/src/recipes/mdx-src/sass.mdx
packages/gatsby/src/recipes/mdx-src/theme-ui.mdx
packages/gatsby/src/recipes/parser/__snapshots__/parser.test.js.snap
packages/gatsby/src/recipes/providers/npm/package-json.js
packages/gatsby/src/recipes/recipe-machine.js
packages/gatsby/src/recipes/todo.md
packages/gatsby/src/recipes/validate-steps.js

feat(Recipes): Show list of recipes when one isn't passed in

---

packages/gatsby/package.json
packages/gatsby/src/recipes/cli.js
packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
packages/gatsby/src/recipes/providers/gatsby/plugin.js
packages/gatsby/src/recipes/todo.md

feat(recipes): Format gatsby-config changes with Prettier

---

packages/gatsby/src/recipes/README.md

Do these make sense @laurieontech?

a couple small nits

---

docs/sites.yml

- Remove Health Pro Fitness as switch to WordPress
- Remove Brent Runs Marathons source_url as repo no longer public
- Remove DatoCMS as switch to Next

chore(showcase): Cleaning up showcase

---

packages/gatsby-image/README.md

updated the link for Image Query Fragments

Update readme link for Image Query Fragments

---

docs/docs/mdx/programmatically-creating-pages.md

changes:
- add missing line for `shortcodes`
- #22944 `docs: update programmatically-creating-pages.md to remove inconsistency` 
i see my prettier/linter removes comma? did i need some setup changes?
🤔

fix(docs):  update programmatically-creating-pages.md add missing shortcodes

---

docs/contributing/how-to-file-an-issue.md

changes:
- add `, and` to the list

fix(docs): contributing - add word and

---

docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md

Remove now private giphy

---

docs/blog/2020-04-15-announcing-gatsby-recipes/index.md

chore(blog): 🧹 Remove whitespace from Markdown link

---

packages/gatsby-recipes/recipes/typescript.mdx

Makes a capital S in the docs for TypeScript 
https://www.staging-typescript.org/branding

[minor] Update typescript.mdx for the capital S in TypeScript

---

packages/gatsby-recipes/src/cli.js

Fix typo in Recipes: eliminateNewLines function

---

docs/starters.yml

Add my Gatsby-Blog-Starter-Dyuzz

---

packages/gatsby-recipes/README.md

feat(recipes): Update gatsby-recipes README.md

---

docs/blog/2020-04-17-gatsby-survey-goes-command-line/index.md

changes:
- brand names
- #23116 `Blog gatsby cli survey`

fix(blog): Blog gatsby cli survey - brand names

---

docs/docs/graphql-reference.md

Found https://twitter.com/danieltott/status/1250777217036140544 and his article: https://www.dtott.com/thoughts/2020/04/16/multiple-date-formats-in-one-gatsby-graphql-query
So let's get that helpful bit in!

chore(docs): Add note to "Aliasing"

---

docs/docs/porting-from-create-react-app-to-gatsby.md

Fix "Porting from CRA to Gatsby" provider section 
Close #23215

docs: fix "Porting from CRA to Gatsby" provider section

---

packages/gatsby-recipes/README.md

Fix the recipes README MDX note. It references a missing newline that's not missing.
n/a
n/a

Fix recipes README MDX note

---

www/src/components/sidebar/accordion.js
www/src/components/sidebar/item-link.js
www/src/components/sidebar/item.js
www/src/components/sidebar/section-title.js

I noticed that we were were creating the sidebar item links in a weird way so I made a quick refactor to simplify the logic of it.

refactor(www): Simplify logic of link component in sidebar

---

docs/starters.yml

Starter got merged with an invalid category by accident.

chore(www): Remove invalid category from starter

---

packages/gatsby-recipes/package.json

As mentioned in the umbrella issue for recipes https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-615838535

fix(recipes): Add missing package cors

---

examples/using-styled-components/package.json

I updated styled-components to v5 in example.

chore(example): update styled-components to v5

---

packages/gatsby-plugin-sitemap/src/internals.js

chore: words spelling

---

docs/docs/mdx/importing-and-using-components.md

fix(docs): Using-MDX link

---

packages/gatsby-image/src/__tests__/index.js

#fbmeme
ht @visualfanatic in #18741

chore(gatsby): drop the the

---

docs/sites.yml

Added [SofaScore corporate web](https://corporate.sofascore.com) to list of showcase sites

chore(showcase):Add SofaScore Corporate web to showcase sites

---

www/src/components/sidebar/sidebar.js

fix(www): fix sidebar

---

benchmarks/source-drupal/package.json
benchmarks/source-drupal/scripts/data-update.ts
benchmarks/source-drupal/scripts/updater.ts

Fix the Drupal data update script.
- Load the `env.NODE_ENV` file as with other parts of the benchmarks
- Install `typescript`
- Remove duplicate protocol from server name
- Autoformat
n/a
n/a

Fix Drupal data update script

---

docs/blog/2020-04-22-announcing-incremental-builds/index.md

Congrats on the launch :heart:

Fix typo on inc builds blog post

---

docs/blog/2020-04-22-announcing-incremental-builds/index.md

Update opening statement Inc Builds announcement blog

---

packages/gatsby-plugin-typescript/README.md

docs: mention passing the .tsx file to createPage

---

docs/sites.yml

This PR is to add 2 sites to the showcase: one is the landing page of my start-up GeneOS and the other is my project COVID KPI, which aggregates COVID-19 data and displays Key Performance Indicators. Please check them out!

chore(showcase): add GeneOS and COVID KPI

---

packages/gatsby-transformer-remark/src/extend-node-type.js

markdownASTToHTMLAst isn't async

---

docs/contributing/index.md

Added Punctuation to bullet point.

---

benchmarks/source-wordpress/package.json
benchmarks/source-wordpress/scripts/data-update.js
benchmarks/source-wordpress/scripts/data-update.ts
benchmarks/source-wordpress/scripts/updater.js

This was copied from the Drupal benchmark and modified to update WPGraphQL instead.

feat(benchmark-wordpress): Add data update script

---

docs/blog/2020-04-14-virtual-gatsby-days-registration/index.md

Link was pointing at a non-existing page. 
Got scared that registering wasn't possible anymore. 
Found the right link.
Steps to reproduce:
1) Love for Gatsby 
2) Anxiety
3) Desire to attend Gatsby Days

Update link for registering [Virtual Gatsby Days]

---

docs/sites.yml

Adding source URL to github repo for portfolio site.

chore(showcase):Added source URL to portfolio site

---

packages/gatsby-recipes/recipes/tailwindcss.mdx

Add a tailwindcss recipe to help users to setup Gatsby with Tailwindcss
Umbrella Issue: #22991

Add tailwindcss recipe

---

docs/tutorial/part-eight/index.md

docs(tutorial): Corrected Helmet import

---

packages/gatsby-recipes/recipes/gatsby-plugin-react-helmet.mdx

Adding a recipe to use `gatsby-plugin-react-helmet`.
Since it is one of the official plugins, the recipe includes a component described in a blog post.

feat(gatsby-recipes): Add Gatsby react helmet recipe

---

docs/blog/2020-04-15-announcing-gatsby-recipes/index.md

Fix some small errors incl. capitalization and a missing word.
cc @KyleAMathews
---
Oh and thanks for Recipes, looks really cool! Excited about the implications for newer developers, especially this part:
> What if tutorials were Recipes but could be still read as tutorials and run as Recipes where they’d ... automate fiddly details like installing packages and plugins, creating files in the right place, etc. that slow learning the concepts and technology
Super awesome. I guess this could be either a browser extension or hooking in via some Recipes URL handler or something. Or maybe the GUI that you're mentioning here:
> A GUI version of Recipes. We’re working on a Desktop app for Gatsby and Recipes

Fix capitalization, missing word

---

packages/gatsby-plugin-manifest/README.md

Update gatsby-plugin-manifest README

---

docs/blog/2020-04-24-unlock-power-of-portfolios-with-gatsby/index.md

Totally strange but fixed now.

Fix image link weirdness

---

docs/sites.yml

This adds a new site to the Showcase.

chore(showcase): add Piotr portfolio site to showcase

---

docs/docs/node-interface.md

docs(node-interface): fix broken link

---

packages/gatsby-recipes/recipes/gatsby-plugin-layout.mdx
packages/gatsby-recipes/src/cli.js

chore(recipes) fix typo and adding gatsby-plugin-react-helmet to cli

---

docs/docs/themes/converting-a-starter.md

This PR fixed outdated section in Theme docs
Related to #23197

Fix outdated section in Themes docs

---

docs/docs/page-build-optimizations-for-incremental-data-changes.md

- Add information on Incremental Builds in Gatsby Cloud 
- Add link to blog announcement
- Add link to Incremental Builds docs

Docs update - page-build-optimizations-for-incremental-data-changes.md

---

docs/sites.yml

This adds a new site to showcase

chore(showcase): add mishal23 portfolio site to showcase

---

packages/gatsby-recipes/README.md

for support added in https://github.com/gatsbyjs/gatsby/pull/23433

feat(gatsby-recipes): document option support for GatsbyPlugin

---

docs/sites.yml

The featured site on the website (GM Capital One) was actually built with Angular and has been in showcase for 2 years 😅
N/A
Fixes #23581

chore(showcase):Remove "GM Capital One" site from showcase

---

docs/tutorial/part-one/index.md

Changes in "Deploying a Gatsby site" section.
Add the requirement to verify email address for newly-created surge account.
Link to current doc: https://www.gatsbyjs.org/tutorial/part-one/#deploying-a-gatsby-site

Update tutorial docs part-one

---

docs/starters.yml

chore(starters): add gatsby-starter-wordpress-twenty-twenty

---

packages/gatsby-recipes/README.md
packages/gatsby-recipes/recipes/README.md

feat(gatsby-recipes): add local dev instructions for gatsby-recipes

---

docs/docs/adding-analytics.md

Add a link to the PostHog analytics plugin to the docs.

chore(docs): Add PostHog to analytics docs

---

docs/blog/author.yaml

Changed my description and switched my website from my defunct site to my active site

(chore) Update Hashim's description

---

docs/sites.yml

Remove Fabian Schultz' Portfolio: Switch to NextJS
Remove Bestvideogame.deals: Switch to WP
Remove BELLHOPS: Switch to CRA

chore(showcase): Removing more sites from the showcase

---

docs/sites.yml

The site showcase validator picked up this site as "not a gatsby site", but it actually just had to redirect to another URL which is still built with Gatsby so I just updated the url in the showcase.

chore(showcase): Update URL for a+ Saúde

---

packages/gatsby-theme-blog-core/gatsby-node.js
packages/gatsby-theme-blog-core/src/templates/post-query.js
packages/gatsby-theme-blog/src/components/post-hero.js
packages/gatsby-theme-blog/src/components/post.js
starters/gatsby-starter-blog-theme/package.json

Image support allows us to add a featured image for blog posts.

Add featured image

---

packages/gatsby/src/redux/index.ts
packages/gatsby/src/utils/websocket-manager.ts

specified the type of store.
It makes type assertion more clear

chore(gatsby): specify the type of store

---

docs/blog/2020-04-29-incredimental-builds/index.md

Updated Josh's blog post with callout component to Gatsby Cloud.

(blog) Add Gatsby Cloud callout

---

www/package.json

Should be good to merge once the cloud build completes

Bump up graphql-request version to fix deprecation notices

---

docs/starters.yml

We have added new skin called Balsa. It is a dream UI for any blogger. Starter provides out of box support for AMP, RSS and Sitemap.

chore(starters): Add gatsby-ghost-balsa-starter to starters

---

docs/starters.yml

We have added new skin called Balsa. It is a dream UI for any blogger. Starter provides out of box support for AMP, RSS and Sitemap.

chore(starters): Add gatsby-wordpress-balsa-starter to starters

---

docs/docs/debugging-html-builds.md

Changed from React Loadable to Loadable Components in Debugging HTML Builds doc page

chore(www): Change from react-loadable to loadable-components

---

benchmarks/source-datocms/package.json
benchmarks/source-datocms/scripts/data-update.ts
benchmarks/source-datocms/scripts/updater.ts
benchmarks/source-datocms/tsconfig.json

Update script that updates the title of a DatoCMS article.

feat(benchmark-datocms): Add data update script to update article title

---

docs/blog/2020-05-05-Butter-CMS-case-study/index.md

Make ButterCMS all one word in title

---

docs/sites.yml

Add [Cognifide Tech](https://tech.cognifide.com/) to Gatsby Showcase list.

Add Cognifide Tech to Gatsby Showcase

---

docs/docs/typescript.md

chore(docs): Fix file extension on TS doc

---

docs/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/index.md

Sam's post about ImpossibleFoods.com using Gatsby to map where hungry users can find an Impossible Burger near them.

add Impossible Burgers case study

---

packages/gatsby-recipes/src/cli.js

fixes https://github.com/gatsbyjs/gatsby/issues/23800

fix(gatsby-recipes): Also call telemetry when selecting a recipe from the list

---

docs/docs/query-behind-the-scenes.md

Found some more broken links in "How Queries Work" and updated them.
Related to #14228

update(docs) Fix broken links in "How Queries Work" article

---

packages/gatsby-theme-blog/src/gatsby-plugin-theme-ui/components.js

Errant file deletion broke prism in theme

---

www/i18n.json

Today I started the [Catalan translation](https://github.com/gatsbyjs/gatsby-ca) and needs to be added in the languages list.
New Translation Request - Catalan (accepted) #22776

Add Catalan to languages

---

www/src/components/tags-section.js

yikes
~master (few commits behind)- https://build-a5c6aa8e-1b56-4f88-a1a4-f0688378d9ae.gtsb.io/_analyze.gz.html
With this change - https://build-55016583-c209-4284-9172-5bc15bbc5374.gtsb.io/_analyze.gz.html

fix(www): allow to tree shake lodash-es

---

docs/docs/deploying-to-clodui.md
www/src/data/sidebars/doc-links.yaml

This PR adds a guide to deploying a Gatsby website to [Clodui](https://www.clodui.com)

chore(docs): add Clodui deployment guide

---

docs/starters.yml

chore(starters): update gatsby-contentful-blog-portfolio

---

packages/gatsby-plugin-react-css-modules/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-react-css-modules/src/__tests__/gatsby-node.js

- setup test using jest on this plugin

chore(plugin-react-css-modules): init test

---

starters/README-template.md

**changes:**
Related Issues
#24019 [Umbrella] Rename Zeit to Vercel
#23961 Rename ZEIT Now to Vercel

fix(www): update zeit to vercel links

---

packages/gatsby-recipes/README.md

Fix missing code block

---

docs/starters.yml

**changes:**
Related Issues
#24019  [Umbrella] Rename Zeit to Vercel
#23961 Rename ZEIT Now to Vercel

fix(docs) - changes( ZEIT to Vercel) in docs/starters.yml

---

docs/docs/caching.md

**changes:**
Related Issues
#24019 [Umbrella] Rename Zeit to Vercel
#23961 Rename ZEIT Now to Vercel

fix(docs) - [Now documentation] link (ZEIT to Vercel)

---

yarn.lock

Lock file wasn't updated when package.json was changed in #24029

fix(gatsby): update yarn lockfile after #24029

---

docs/docs/tailwind-css.md

- Adds support for 1.4.0
- Adds missing setup instructions for custom css/scss files
- Adds missing PurgeCSS documentation
- Minor navigation improvements
This PR is only updating documentation, it does not contain any new features which need to be further documented.
#23952

chore(doc) : Updates Tailwind Installation docs

---

docs/docs/different-organization-types.md
docs/docs/gatsby-for-companies.md
docs/docs/gatsby-for-freelancers.md
docs/docs/how-gatsby-boosts-career.md

**Changes: added trailing slash to helps the user identify the hierarchy of page.**
Fix: Breadcrumb issue resolved for /docs/useGatsbyProfessionally section
Related Issues
#20767

fix(docs): breadcrumb issue resolved in docs/useGatsbyProfessionally

---

docs/docs/deploying-to-cloudflare-workers.md

`wrangler.toml` is not a directory, it's a config file. `workers-site` is a folder.

fix(docs): proper project strucutre in Cloudflare Workers example

---

docs/starters.yml

Adds a new starter: hello world Tailwind CSS starter

Add gatsby-starter-hello-world-tailwind-css to starters.yml

---

docs/starters.yml

Transferred project ownership to DropInBlog

chore(starters): Updated repo URL

---

packages/gatsby-recipes/recipes/preact.mdx
packages/gatsby-recipes/src/cli.js

Create a recipe to make it easier to move to preact as an alternative.

feat(gatsby-recipes): add preact recipe

---

docs/sites.yml

chore(showcase): add hbish.com

---

docs/sites.yml

Add raymondware.com site

---

www/src/templates/template-contributor-page.js
www/src/utils/node/blog.js

* Move the filter by author ID into the query rather than a separate filter in the component
* convert to function component, cause it's 2020.
Code cleanup, something I noticed while doing #23993. I think this helps reduces the page data in the bundle?

perf(www): Optimize contributor query
