packages/gatsby/src/redux/persist.js
Currently, when redux persists its state, the path to the state file is generated when the file is imported.
https://github.com/gatsbyjs/gatsby/blob/a0094f4325bce73cf8be9aaad3408b8a6a7195d1/packages/gatsby/src/redux/persist.js#L4
It would make some situations easier to handle, if the path to use was calculated when the module is used rather than when imported, so that changes to the current directory are reflected in the path used.
This PR changes the generation of the path to a function, which is called when the redux state is loaded or saved.
=> fix(gatsby): Call cwd() when called instead of on import

packages/gatsby/src/utils/api-runner-node.js
This attempts to remove a bunch of BlueBird promises from the api runner, in favor of native Promises.
It also cleans up the core of the api-runner by eliminating a bunch of controls that would never really be used due to how promises get resolved and non-blocking works.
=> chore(gatsby): cleanup api runner promises

packages/gatsby/src/db/sanitize-node.js, packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/infer/inference-metadata.js, packages/gatsby/src/schema/node-model.js
This allows nodes to have a circular dependency without causing stack overflow exceptions when traversing the graph.
Fixes #11364 (hopefully). Will have to confirm this after publishing an update.
Causes somewhere between 0 and 1% perf regression for our 25k page benchmark site. But it's within variance of benchmarking, not even sure if there's a noticable regression at all. See this table:
The first two columns are on master (at the time of writing), the third and fourth column are after this change. (The `(govbook)` lines are printed from within the benchmark site). Shrug.
```
master:                |      branch:                  |
------------------------------------------------------------------------------------------------------
0.025s        0.026s  |       0.026s         0.030s …
```
=> fix(gatsby): do not cause stack overflow over circular refs

packages/gatsby-plugin-netlify-cms/package.json, packages/gatsby-plugin-netlify-cms/src/cms-manual-init.js, packages/gatsby-plugin-netlify-cms/src/cms.js, packages/gatsby-plugin-netlify-cms/src/gatsby-node.js, yarn.lock
Fixes https://github.com/gatsbyjs/gatsby/issues/18245
Fixes https://github.com/gatsbyjs/gatsby/issues/17568
I can split this into two PRs (one per issue) if needed.
Main changes:
1. Mark `netlify-cms-app` and relevant dependencies as externals to avoid re-build during bundle. `netlify-cms-app`,`netlify-identity-widget`, `react` and `react-dom` are already set up for that since they expose a global variable on the window object which Webpack can reference instead of importing the module.
2. The reason `netlify-identity-widget` was still included in the main app bundle [here](https://github.com/gatsbyjs/gatsby/issues/17568) is that it didn't pass Gatsby's default thresholds for code splitting. Forcing it into its own cache group makes sure it's not in the app bundle.
~~It will still be …
=> fix(gatsby-plugin-netlify-cms): Mark relevant dependencies as externals

packages/gatsby-theme-blog/src/components/header.js
This change fixes the position of the moon/sun image on the theme toggle. With the changes in #19673, this became out of place:
Related to #19673
=> fix(gatsby-theme-blog): Dark/light mode switch icon is out of place

docs/tutorial/wordpress-source-plugin-tutorial.md
link not match text in docs/tutorial/wordpress-source-plugin-tutorial
#19267
=> fix(docs): link not match text in docs/tutorial/wordpress-source-plugin-tutorial

docs/blog/2018-03-07-why-we-created-the-plugin-library/index.md
on blog/2018-03-07-why-we-created-the-plugin-library:
- removed link to js.coach
- apply redirect /packages -> /plugins
#19267
=> fix(blog): 404 on blog/2018-03-07-why-we-created-the-plugin-library

docs/blog/2019-02-08-government-open-data-site-with-gatsby/index.md
removed a link with 404 on 2019-02-08-government-open-data-site-with-gatsby
this link is also not on original post: https://revenuedata.doi.gov/blog/homepage-revamp-part-two/#Gatsby-prefetch-error
#19267
=> fix(blog): 404 on 2019-02-08-government-open-data-site-with-gatsby

www/README.md
Add info about `.env.production` for the `GITHUB_API_TOKEN` to the `README.md`. 
When i run `gatsby build` i get the error `A GitHub token is required to build the site. Check the README.` but there is no info about the `.env.production` in readme.
https://github.com/gatsbyjs/gatsby/blob/e5a01a0625ad044bc281e23a7a6644ce2001589d/www/gatsby-node.js#L29-L36
i am open for better wordings of the text.
n/a
=> chore(www): add info about `.env.production`

packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap, packages/gatsby-source-contentful/src/normalize.js
This change adds 2 properties from the Contentful API that are not being surfaced by the gatsby-source-contentful plugin. They are as follows:
- Revision: A field from Contentful that specifies the revision number of a piece of content or content model
- Content Type: For entries, references the content type that the entry is an instance of, including the ID value (useful for apps looking to switch on this field for component lookups)
Fixes #19791
=> [gatsby-source-contentful] Add missing 'sys' properties from Contentful

www/src/templates/template-contributor-page.js
in docs/blog/author.yaml some contributors without twitter handle - for example:
- https://www.gatsbyjs.org/contributors/grant-glidewell/
- https://www.gatsbyjs.org/contributors/maddie-wolf/
this creates a empty link to https://twitter.com/null
#19267
=> fix(www): fix links with null in template-contributor-page.js

packages/gatsby-cli/src/reporter/index.js
This change explicitly throttles the progress bar updates (`tick` and `total`) to be clamped to 10 fps max.
This drops the govbook benchmark from 210 seconds down to 140 seconds. Makes the build about as fast as with `CI=true` and `GATSBY_LOGGER=yurnalist`.
(Note: Many CI's automatically enable this so you won't see a difference there. But many people are unaware of the `CI` flag and this will make a huge difference for larger sites, or sites with many images.)
Fixes #15505
Fixes #17452
Fixes #17966
Fixes #18801
Relates to #17873
Relates to https://github.com/vadimdemedes/ink/issues/212
=> perf(gatsby-cli): throttle progress bar, build much faster this way

packages/gatsby-source-drupal/src/gatsby-node.js
I do not know why, but https://d2.api.demo.centarro.io/jsonapi/action/action returned the following error when trying to build a project w/ gatsby-source-drupal
```
ERROR #11321  PLUGIN
"gatsby-source-drupal" threw an error while running the sourceNodes lifecycle:
Cannot read property 'next' of undefined
TypeError: Cannot read property 'next' of undefined
- gatsby-node.js:109 getNext
[gatsbyjs_commerce_demo]/[gatsby-source-drupal]/gatsby-node.js:109:24
```
when unauthenticated. There is a links object. But it is acting like it is null
=> fix(gatsby-source-drupal): sanity check before accessing field

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
This fix in mono-repo based project the `node_modules` hoist to project root.
=> [gatsby-plugin-netlify-cms] switch to `require.resolve` for modules hoisting

e2e-tests/development-runtime/cypress/integration/functionality/data-update.js, e2e-tests/development-runtime/src/pages/schema-rebuild.js, packages/gatsby/src/bootstrap/schema-hot-reloader.js
This PR is a follow up after #19781. It fixes schema hot reloading which was not handled correctly in the previous PR. It also adds a simple e2e test for schema rebuilding to catch such situations in the future.
=> fix(gatsby): use correct state in the schema hot reloader

docs/docs/mdx/getting-started.md
There is an existing section in the docs on adding MDX support to a site. This process is a bit more complicated for an existing blog site and that's written up in a recent blog post. This addition links to that post from the applicable docs section.
Related to #19412
=> chore(docs): Add reference to MDX blog post to main docs

docs/blog/2018-08-24-gatsby-aws-hosting/index.md, docs/blog/2018-12-19-kentico-cloud-and-gatsby-take-you-beyond-static-websites/index.md, docs/blog/2019-01-24-swag-store/index.md, docs/blog/2019-04-30-how-to-build-a-blog-with-wordpress-and-gatsby-part-2/index.md, docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md, docs/blog/2019-08-07-theme-jam/index.md, docs/blog/2019-08-13-Localised-strings-from-Kentico-Cloud-GatsbyJS-GraphQL/index.md, docs/blog/2019-08-14-strivectin-case-study/index.md, docs/blog/gatsby-v1.md, docs/docs/add-404-page.md, docs/docs/adding-comments.md, docs/docs/preprocessing-external-images.md, docs/docs/remark-plugin-tutorial.md, docs/docs/running-queries-with-graphiql.md, docs/docs/sourcing-from-the-filesystem.md, docs/docs/using-graphql-playground.md, docs/tutorial/wordpress-source-plugin-tutorial.md
make all images equal using `[](./images)` (not `[](/images)` and not `[](images)`)
=> fix(docs): fixed images links to use always ./images

.circleci/config.yml
Skip running some tests over the weekend. This avoids some Slack notifications.
=> chore(CI): skip experimental tests at weekends

packages/gatsby-source-drupal/src/gatsby-node.js
The JSON:API Schema module (https://www.drupal.org/project/jsonapi_schema) adds a `describedby` link to resources. This payload doesn't contain a JSON:API document, but information describing the object's schema. It's not a valid source of content.
After debugging, it is the original cause of #19867
Related to #19867
=> fix(gatsby-source-drupal): skip jsonapi_schema endpoint

packages/gatsby-plugin-feed/README.md, packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-ssr.js.snap, packages/gatsby-plugin-feed/src/__tests__/gatsby-ssr.js, packages/gatsby-plugin-feed/src/gatsby-ssr.js, packages/gatsby-plugin-feed/src/plugin-options.js
This add the possibility to configure a custom link for rss meta generation.
=> feat(gatsby-plugin-feed): Allows to override default feed url generation

packages/gatsby-plugin-offline/README.md
Replaced cacheOnly with cacheFirst within the runtimeCaching config for static assets (JS, CSS etc)
Spotted by @m-allanson inside my [previous pull request ](https://github.com/gatsbyjs/gatsby/pull/19817/commits/eb0b57ef6266fca681f0ebd2f8df2b776b827103)
=> fix(gatsby-plugin-offline): Replaced cacheOnly with cacheFirst

packages/gatsby/src/schema/__tests__/rebuild-schema.js, packages/gatsby/src/schema/infer/__tests__/inference-metadata.js, packages/gatsby/src/schema/infer/add-inferred-fields.js, packages/gatsby/src/schema/infer/inference-metadata.js
This PR should make the processing of `___NODE` convenience fields consistent for `one-to-one` and `one-to-many` relations (currently `one-to-many` works as expected while `one-to-one` doesn't). 
Take this example with `one-to-one` relation:
```
createNode({
internal: { type: `MyType` },
related___NODE: `FooTypeNode1`,
})
createNode({
internal: { type: `MyType` },
related___NODE: `BarTypeNode1`,
})
```
The expected inference result is a union type:
```
type MyType {
related: FooBar
}
union FooBar = Foo | Bar
```
The actual result is a first registered object type:
```
type MyType {
related: Foo
}
```
The same example for `one-to-many` relation produces an expected result:
```
createNode({
internal: { type: `MyType` },
related___NODE: [`FooTypeNode1`],
})
createNode({
internal: { type: …
```
=> fix(gatsby): support union types for one-to-one ___NODE relations

www/src/views/starter-library/starter-list.js
Seems to fix:
```
21:36:45 PM: error Building static HTML failed for path "/starters/"
21:36:45 PM: 104 | </span> 105 | <span css={{ display: `flex` }}> > 106 | {gatsbyMajorVersion[0][1] === `2` && ( | ^ 107 | <span 108 | sx={{ 109 | alignItems: `center`, WebpackError: TypeError: Cannot read property '1' of undefined - starter-list.js:106 StartersList.starters.map src/views/starter-library/starter-list.js:106:46 - starter-list.js:63 StartersList src/views/starter-library/starter-list.js:63:19
21:36:46 PM: ERROR Failed to compile: Error: Exited with code 1
```
Not sure if there is a nicer way to fix this in the query 🙈
=> fix(www): handle case when gatsbyMajorVersion is unset in a starter

packages/gatsby-telemetry/package.json
This really is a hack for a bug in npm, but some other packages,
including core-js [does this hack](https://github.com/zloirock/core-js/blob/v2.6.10/package.json#L41).
To repro:
```
$ docker run --rm -it ubuntu bash
$ npm install -g gatsby-cli
```
and it will fail with
```
> gatsby-telemetry@1.1.41 postinstall /root/.nvm/versions/node/v10.17.0/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry
> node src/postinstall.js
sh: 1: node: Permission denied
```
the || true will just make it exit happily, even though we were unable
to run the postinstall script.
=> fix(gatsby-telemetry): gracefully handle postinstall script permission errors

packages/gatsby-source-contentful/package.json, packages/gatsby-source-contentful/src/gatsby-node.js, packages/gatsby-transformer-sharp/package.json, packages/gatsby-transformer-sharp/src/gatsby-node.js
Since https://github.com/gatsbyjs/gatsby/pull/15284, fragments no longer need to be copied over to the `.cache` directory because gatsby looks through `node_modules`
This PR removes that copying mechanism from `gatsby-transformer-sharp` and `gatsby-source-contentful` and updates its peer dependencies to `"gatsby": "^2.12.1"`
=> chore(gatsby-transformer-sharp): remove fragment copying from plugins

packages/gatsby-source-drupal/README.md, packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json, packages/gatsby-source-drupal/src/__tests__/fixtures/schema.json, packages/gatsby-source-drupal/src/__tests__/index.js, packages/gatsby-source-drupal/src/gatsby-node.js
Adds a `disallowedLinkTypes` setting that allows you to exclude specific link types.
By default it excludes `self` and `describedby`, meeting the current state. This allows skipping link types on `/jsonapi`. This way someone could exclude certain resource links from being crawled, so it actually allows someone to add performance enhancements when building.
I've added a test fixture and test.
Fixes #19921
Relates  #19867
Relates #19879
=> fix(gatsby-source-drupal): allow specifying disallowed link types

docs/docs/creating-dynamic-navigation.md, docs/docs/rendering-sidebar-navigation-dynamically.md, www/gatsby-node.js, www/src/data/sidebars/doc-links.yaml
This existing page can be more appropriately named to match its content. It's first header "Creating Dynamic Navigation in Gatsby" should be the page title, and the now redundant stub for "Rendering Sidebar Navigation Dynamically" can be removed. 
Addresses #18993
=> Rename Routing Doc and remove duplicate stub

.github/PULL_REQUEST_TEMPLATE.md
Updating the PR template to include a docs prompt, to get changes written down while they're fresh and minimize docs debt from being shipped. Information provided in initial PRs will be helpful to all teams, but particularly Learning and Marketing. Feedback welcome. CC @m-allanson and @laurieontech per our discussion.
N/A
=> Update PR template with docs prompt

packages/gatsby-transformer-remark/src/__tests__/extend-node.js, packages/gatsby-transformer-remark/src/__tests__/on-node-create.js, packages/gatsby/src/schema/__tests__/run-query.js, packages/gatsby/src/schema/infer/__tests__/inference-metadata.js, packages/gatsby/src/schema/infer/build-example-data.js, packages/gatsby/src/schema/infer/index.js, packages/gatsby/src/schema/infer/inference-metadata.js
While trying to investigate objects vs maps I ended up refactoring the inference-metadata bits
- Move example builder to its own file
- Drop some destructuring juggling, both upward and downwards
- Drop the juggling down of `dirty` in favor of passing on the object that contains the flag to be set if dirty
- Drop some destructuring
- Renamed `typeInfo.props` to `typeInfo.dprops` for easier greppability
The end should be simpler and (very slightly) more performant.
I've tried to make `typeInfo.dprops` a Map but my experiments did not yield a win so I did not commit that. We may try again in the future as it may be caused by other complexities / conversions.
=> chore(gatsby): Refactor schema/infer/inference-metadata.js

docs/docs/recipes.md
I noticed that importing the Link component is missing from the code example. This PR fixes it.
=> Importing the Link component is missing

packages/gatsby-source-shopify/src/gatsby-node.js
This is https://github.com/gatsbyjs/gatsby/issues/18249 issue fix.
Issue replication repo: https://github.com/paveli/gatsbyjs-issue-18249
Wrong object path was passing to queryAll thus page nodes were not creating.
Changed object path to meet the format requirements.
Fixes https://github.com/gatsbyjs/gatsby/issues/18249
=> fix(gatsby-source-shopify): allShopifyPage node creation issue #18249 fix

www/src/pages/index.js
This component didn't seem to be doing anything. However, it was triggering an error in the browser console:
```
Warning: Failed prop type: The prop `children` is marked as required in `HomepageSection`, but its value is `undefined`.
```
For reference, here is where HomepageSection is defined: https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/homepage/homepage-section.js
n/a
n/a
=> chore(www): Remove blank component

docs/docs/deploying-to-firebase.md, www/src/data/sidebars/doc-links.yaml
This PR should add a tutorial explaining how to deploy a Gatsby site to [Firebase Hosting](https://firebase.google.com/docs/hosting)
=> docs: add 'Deploying to Firebase Hosting' tutorial

packages/gatsby/src/utils/worker/pool.js
As outlined in https://github.com/gatsbyjs/gatsby/issues/19974, the number of `jest-worker` instances created to build the static HTML does not respect the number specified by the environment variable GATSBY_CPU_COUNT. This can result in `ENOMEM` when running in a containerised environment. 
This PR stops forcing the `ignoreEnvVar` argument to `true`. https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/cpu-core-count.js#L4
As a result of this change, we stopped experiencing ENOMEM issues, but also a bump in page generation speed.
https://github.com/gatsbyjs/gatsby/issues/19974
I'm happy to add any tests for this if required. Sorry if this PR is premature.
=> fix(gatsby): Ensure the number of jest-workers respects GATSBY_CPU_COUNT env var

scripts/i18n/update-source.js
This script was running for quite some time using `test-update` branch in https://github.com/gatsbyjs/gatsby-i18n-source as target. 
Check history for the branch how it syncs docs updates: https://github.com/gatsbyjs/gatsby-i18n-source/commits/test-update
I think we can be confident enough with it to switch it to `master` now
For context - referenced repository is used as source of truth for translation repositories:
- right now when creating new language repository we use this is a base
- in future that repo will be used to sync updates from gatsbyjs/gatsby to translation repos
=> chore(i18n/update-source): use master over test branch

packages/gatsby-dev-cli/src/watch.js
The issue is that yarn and npm will chmod a bin file on install. when gatsby-dev copies files over, the copied file needs to be chmod'd again.
Also in here, I noticed that gatsby-dev was copying over `__mocks__` files, so those were added to the ignore list.
Fixes #18809
=> fix(gatsby-dev-cli): chmod gatsby bin on copy

packages/gatsby-plugin-page-creator/README.md
=> fix(gatsby-plugin-page-creator): typo in README.md

packages/gatsby-plugin-netlify/README.md
=> fix(gatsby-plugin-netlify): typo in README.md

packages/gatsby-theme-blog/src/components/home-footer.js
This PR fixes the issue #19976 
Fix for #19976
=> fix(gatsby-theme-blog): Fix home-footer in Night mode

packages/gatsby-source-graphql/package.json, packages/gatsby-source-graphql/src/__tests__/gatsby-node.js, packages/gatsby-source-graphql/src/gatsby-node.js, packages/gatsby-source-graphql/src/transforms.js, yarn.lock
Avoid additional layer of delegation.
Switches to graphql-tools-fork, a maintained fork of the original repository with continued support for schema stitching. The fork allows for embedding a remote schema configuration within the call to transform schema, removing an additional layer of delegation within root fields and merging by defaultMergedResolver.
=> feat(gatsby): use embedded remote schemas

benchmarks/query/bin/runQueryTiming.sh, packages/gatsby-transformer-screenshot/chrome/buildChrome.sh, scripts/assert-changed-files.sh, scripts/e2e-test.sh, scripts/prepublish.sh, scripts/publish-canary.sh, scripts/publish-site-from-npm.sh, scripts/publish-starters.sh, scripts/validate-starters.sh
Fix linting in shell scripts to conform to [ShellCheck](https://github.com/koalaman/shellcheck) standards. ShellCheck is a static analysis tool that offers suggestions to catch potential warnings and errors.
Specifically, the following rules have been fixed: [SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090), [SC1117](https://github.com/koalaman/shellcheck/wiki/SC1117), [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086), [SC2129](https://github.com/koalaman/shellcheck/wiki/SC2129), [SC2148](https://github.com/koalaman/shellcheck/wiki/SC2148) and [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164)
N/A
N/A
=> chore: lint all shell scripts

docs/sites.yml
The site moved to a new domain (https://www.canumeet.com/) and is no longer a Gatsby site
=> chore(showcase): Remove Smoopit

packages/gatsby/package.json, yarn.lock
A security breach was found in **serialize-javascript** (versions < 2.1.1) which is one of the dependencies of gatsby's **terser-webpack-plugin** dependency.
This PR bumps the version of **terser-webpack-plugin** to 2.2.2 to fix the security breach. See https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/CHANGELOG.md.
You can find the security alert here: https://github.com/advisories/GHSA-h9rv-jmmf-4pgx.
Even if the version update was a major one, the build seems to be passing.
=> chore(deps): bump terser-webpack-plugin to v.1.4.2

packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap, packages/babel-preset-gatsby-package/index.js, packages/babel-preset-gatsby-package/package.json
This means we can do `a ?? b` in node now (this should not affect output of, say, webpack).
Note that the `??` operator (together with the `?.` operator, which we already added earlier) have been accepted to be added to the JS spec. For all intentions and purposes; that means it's now part of JS.
=> feat(gatsby): support nullish coalescing operator in gatsby

docs/docs/working-with-images-in-markdown.md
It may be helpful to include sample configurations for gatsby-transformer-remark as well as gatsby-plugin-mdx. If a user were to accidentally try to use the gatsbyRemarkPlugins option on the gatsby-trasformer-remark plugin, then the image loading process on markdown files would fail silently without any warnings or errors.
=> Add config for gatsby-transformer-remark

docs/sites.yml
React website is definitely an example of technical documentation. I came looking for examples of docs built with Gatsby and was surprised not to find React among them.
=> Add the "Documentation" tag to React website

packages/gatsby-source-graphql/package.json, packages/gatsby-source-graphql/src/__tests__/gatsby-node.js, packages/gatsby-source-graphql/src/gatsby-node.js, packages/gatsby-source-graphql/src/transforms.js, yarn.lock
This reverts commit 588eaf78f438a21864d1e78c8b16f71dac843eb0.
=> Revert "feat(gatsby): use embedded remote schemas (#19504)"

docs/sites.yml
This adds an entry about 8fit.com to Gatsby's showcase.
8fit.com was rebuilt entirely over the course of the last year using a JAM stack setup with Gatsby at its core.
=> chore(showcase): Add 8fit.com to sites.yml

docs/contributing/managing-pull-requests.md
We've started using [topic: internal](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aopen+is%3Aissue+label%3A%22topic%3A+internal%22) to label PRs that are part of an internal project or hiring process, where contributions should be limited to core or learning team members. To make sure this is communicated to the broader community, I've added a note to the contributing docs. Looking forward to hearing what @gatsbyjs/core and @gatsbyjs/learning think about this. 
N/A
=> chore(www): [contributing] add note about internal PR label

packages/gatsby-plugin-mdx/loaders/mdx-loader.test.js
Minor fix. Was seeing the warning while running `yarn jest`, now I don't.
Backstory: The Babel parser used to be called Babylon and you still see this name come back every now and then. In fact, we still have a sub-dependency on the old babylon parser (`yarn why babylon`). But that's not super relevant for us.
=> chore(gatsby-plugin-mdx): stop using "babylon" as parser in test

docs/docs/what-you-dont-need-plugins-for.md
- Ant Design needs a plugin to handle tree shaking and to import the styles.
- Material-UI needs a plugin to handler server-side style sheets, with JSS. In the future, we will rely on gatsby-plugin-styled-components.
The problem was reported at https://github.com/mui-org/material-ui/issues/18197. It was introduced in #6099.
*You might have noticed that I have switch the order between the two libs, of course, it's not biased, happy to follow the alphabetical ASC order if you prefer 🙃*
=> Material-UI and Ant Design requires a plugin

packages/babel-preset-gatsby/README.md, packages/babel-preset-gatsby/package.json, packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap, packages/babel-preset-gatsby/src/index.js
After this change you should be able to use the new `?.` and `??` operators at runtime (so in the resulting site). They will be transformed by Babel.
Basically tested with an empty repo in dev mode, added `console.log(SEO?.foo ?? 'bar')` before and after this change. Before it would crash on the new syntax and afterwards it would work. Both `develop` and `build`.
=> feat(gatsby): support `?.` and `??` in generated pages

www/src/data/sidebars/doc-links.yaml
fixed link from:
`/docs/glossary/nodejs`
to
`/docs/glossary/node`
#19965 Docs: Encyclopedia: Add entry for Node.js
=> fix(docs): fix 404 sidebar link to glossary / nodejs

packages/gatsby/src/schema/resolvers.js
Consider a schema like, 
```
type Item {
name: String
}
type Collection {
items: [Item]! @link(by: "id", from: "items___NODE")
}
```
And a query like, 
```
allCollection {
nodes {
items {
name
}
}
}
```
If a collection has no items, this currently returns `items` set to `null` as opposed to `[]` (even if it is non nullable as shown in the schema above). 
This happens because the link resolver sets the `{ in: value }` operator in case the field value is an array. This however doesn't make sense for an empty array. 
This PR adds an early return to fix this 🙂 
@Simply007 discovered this issue when building `gatsby-source-kentico`. You can find a reproduction at https://github.com/Simply007/gatsby-null-instead-of-array
=> fix(gatsby): Add early return in link resolver for empty arrays

packages/gatsby-plugin-typescript/README.md
The snippet in the README for adding the plugin results in an array of characters. E.g.:
```javascript
[...`gatsby-plugin-typescript`]
// ["g", "a", "t", "s", "b", "y", "-", "p", "l", "u", "g", "i", "n", "-", "t", "y", "p", "e", "s", "c", "r", "i", "p", "t"]
```
This can cause confusing errors for beginners who copy and paste.
=> docs(gatsby-plugin-typescript): fix plugin instructions

www/src/components/docs-table-of-contents.js
there are some mdx that have left off a header in the tree:
```markdown
```
- [docs/how-code-splitting-works.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-code-splitting-works.md#L84-L92) -> https://www.gatsbyjs.org/docs/how-code-splitting-works/
- [docs/production-app.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/production-app.md#L118-L122) -> https://www.gatsbyjs.org/docs/production-app/
then an element is inserted to the header array with just `items:`:
```javascript
{ 
url: '#2header', 
title: '2. Header', 
items:
[
{ 
items: 
[ 
{ 
url: '#4header', 
title: '4. Header' 
}
]
}
]
}
```
it creates: 
- then the TOC create empty Links with `undefined` in href: 
```html
<a class="css-1wk9u7" href="/docs/how-code-splitting-works/undefined"></a>
```
- it …
=> fix(compontent): fix links with undefined in docs-table-of-contents.js

packages/gatsby-transformer-react-docgen/src/extend-node-type.js
Schema rebuilding introduced in #19092 requires fresh instances of GraphQL types on each rebuild. So plugins using `setFieldsOnGraphQLNodeType` or `createSchemaCustomization` APIs with original graphql.js types must provide new type instances on each API call.
This is an unfortunate restriction caused by `graphql-compose` design which mutates types under the hood. Therefore we can not reliably re-use old types for a new schema.
This issue doesn't apply to plugins using SDL or type builders to define GraphQL types as we produce fresh type instances for them automatically.
Fixes #20043
=> fix(gatsby-transformer-react-docgen): support schema rebuilding

packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-remark-images/src/__tests__/index.js, packages/gatsby-remark-images/src/index.js
Attempts to fix images created by `gatsby-remark-images` using the `withWebp` option.
It seems #19888 changed the styles to be inline, but didn't add the styles on the webp variant.
I also added a test that calls the plugin with `withWebp` in hopes this gets caught in the future.
Fixes #20085
=> fix(gatsby-remark-images): add styles to webp `img` tags

docs/docs/gatsby-on-linux.md
brand names:
- curl -> cURL
- Windows Store -> Microsoft Store
- removed brackets
notes:
- added a note from page [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/#windows-subsystem-for-linux) about rebuilding node modules and reinstall dependencies 
PR #18263 chore(docs): Update the "Gatsby on Linux" page
should the section "Windows Subsystem for Linux" on [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/#windows-subsystem-for-linux) be with less content and point direct to the WSL section on "Gatsby on Linux"?
=> fix(docs): brand names linux pages, add hint about rebuilding dependencies

docs/tutorial/part-seven/index.md
Corrected some spelling and grammatical error.
Corrected some spelling error.
Changed "frontpage"  to "front page". Added spacing between words. For the simplicity of the reader.
=> fix(docs): tutorial - part seven - fix spelling

docs/contributing/docs-templates.md
New users can sometimes be confused about yarn vs. npm. Our documentation uses npm, but when working through a starter and then using the instructions in a plugin, this may not match.
This PR adds additional instructions for plugin creators to include in their README. It also accounts for theme READMEs that follow this same template.
=> Docs plugin readme

packages/gatsby-transformer-asciidoc/README.md
Fixed the gatsby-transformer-asciidoc's custom converter example because it was old.
`asciidoctor` has latest update than `asciidoctor.js`
https://www.npmjs.com/package/asciidoctor
https://www.npmjs.com/package/asciidoctor.js
The following error occurs when using `asciidoctor.js`
```
ERROR
Error in "/Users/takuya.tokuyama/Develop/reblitz-env/repos/reblitz-dev-guideline/node_modules/gatsby-transformer-asciidoc/gatsby-node.js": Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
- setPrototypeOf
- opal.js:450 Object.Opal.allocate_class
[reblitz-dev-guideline]/[asciidoctor-opal-runtime]/src/opal.js:450:7
- opal.js:518 Opal.klass
[reblitz-dev-guideline]/[asciidoctor-opal-runtime]/src/opal.js:518:18
- opal.js:4919 …
```
=> fix(docs): custom converter example

packages/gatsby-cli/src/init-starter.js
Re-implements #729/#730.
I'm having trouble figuring out where the change from #730 was removed, but it looks like it was originally added to `packages/gatsby/lib/utils/init-starter.js` in 35b971be55f7cafc19bc04ac33fe2f98e09bf456/#899, then copied over to `packages/gatsby-cli/src/init-starter.js` d737cd3b0185d0d110e21d30614f03832c8cbe70.
Using `--depth=1` instead of `--single-branch` shaved a couple seconds off of `gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog`.
Related to #729/#730
=> Use git clone --depth-1 instead of --single-branch to clone starters

packages/gatsby-source-hacker-news/README.md, packages/gatsby-source-hacker-news/package.json, packages/gatsby-source-hacker-news/src/gatsby-node.js
Start using [schema customization API](https://www.gatsbyjs.org/docs/schema-customization/) for `gatsby-source-hacker-news`
N/A. Will be probably a separate PR with recipes after #20069
Part of #20069
=> feat(gatsby-source-hacker-news): use schema customization API

packages/gatsby-plugin-sharp/src/trace-svg.js
use `createContentDigest`
#8805 feat: update gatsby plugins to use new createContentDigest helper
=> chore(gatsby-plugin-sharp): Use createContentDigest helper

docs/docs/debugging-the-build-process.md
When trying to debug the build process using the VS Code Debugger on a Windows machine using the `node --nolazy --inspect-brk node_modules/.bin/gatsby develop` command mentioned in the [docs](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/debugging-the-build-process.md#vs-code-debugger-auto-config), I get the following error:
```
$ node --nolazy --inspect-brk node_modules/.bin/gatsby develop
Debugger listening on ws://127.0.0.1:9229/2dab2d65-35db-4539-bb00-2f32bd25bd50
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
E:\Workspaces\hello-world\node_modules\.bin\gatsby:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^
SyntaxError: missing ) after argument list
at Module._compile (internal/modules/cjs/loader.js:721:23)
at …
```
=> docs(gatsby): add note to solve debugging build process on windows

packages/gatsby-source-shopify/src/queries.js
After adding fields for presentmentPrices to enable a multi currency Gatsby shop, we needed to get **compareAtPrice** fields in different prices as well.
Shopify API supports this field on the ProductVariantPricePair
https://help.shopify.com/en/api/storefront-api/reference/object/productvariant/productvariantpricepair
N/A
Thank you
=> feat(gatsby-source-shopify): Add compareAtPrice to presentment prices

packages/gatsby-source-shopify/src/constants.js, packages/gatsby-source-shopify/src/gatsby-node.js, packages/gatsby-source-shopify/src/nodes.js, packages/gatsby-source-shopify/src/queries.js
Following the implementation of adding metafields to Product Nodes ([PR #16312](https://github.com/gatsbyjs/gatsby/pull/16312)), this PR adds metafields to the Variant Nodes as well. Shopify Supports metafields on almost all entities, but Product/Variants are _usually_ the ones that are used the most, as a way to extend data on product entities.
N/A
Thanks!
=> feat(gatsby-source-shopify): add metafields to each product variant node

packages/gatsby/src/commands/develop.js
When running node in Docker for Windows, polling needs to be used for any kind of hot reloading to work. 
There is a webpack setting to enable polling, but it is currently not being passed to `webpack-dev-middleware`. 
This solves the issue by passing the webpack `devServer.watchOptions` to the middleware. 
Addresses #9625
=> Use webpack watchOptions config for webpack-dev-middleware

docs/docs/themes/shadowing.md
As we're talking about `bio.tsx` it only makes sense that the other file of the theme is also `.tsx`.
=> chore(docs): Fix little typo

package.json, scripts/lint-shell-scripts.sh
Adds a `lint:scripts` task in package.json to lint all shell scripts using the ShellCheck tool 
N/A
See: https://github.com/gatsbyjs/gatsby/pull/19991#issuecomment-563440299
=> chore: Add package script for shellcheck linting

www/gatsby-node.js, www/package.json, www/src/components/homepage/homepage-ecosystem.js
This fixes the most frequent issues I've run into when building .org in gatsby cloud build. 
1. Try fixing issues with ```
error Error getting repo data for starter "<any starter name>": request to https://api.github.com/graphql failed, reason: socket hang up```
I've tried this and I haven't seen a single Github API error, but maybe I just had too good of luck...
I'd like to propose using my fork with the fix for a bit and if things work reliably we should try to port to fix to upstream
---
2. fixes some weird errors where we get bad data. I'm happy to leave this out if this isn't the proper fix.
=> chore(www): Improve build reliability

starters/blog/package-lock.json, starters/blog/package.json, starters/default/package-lock.json, starters/default/package.json, starters/gatsby-starter-blog-theme-core/package-lock.json, starters/gatsby-starter-blog-theme-core/package.json, starters/gatsby-starter-blog-theme/package-lock.json, starters/gatsby-starter-blog-theme/package.json, starters/gatsby-starter-notes-theme/package-lock.json, starters/gatsby-starter-notes-theme/package.json, starters/gatsby-starter-theme/package-lock.json, starters/gatsby-starter-theme/package.json, starters/hello-world/package-lock.json, starters/hello-world/package.json
The `starters_validate` script was failing in CI because of an npm audit reporting vulnerabilities in versions of webpack. Updating the related gatsby version fixed this.
=> fix(gatsby): Address npm audit that blocked CI

packages/gatsby-theme-notes/gatsby-node.js
use `createContentDigest`
#8805 feat: update gatsby plugins to use new createContentDigest helper
=> chore(gatsby-theme-notes): Use createContentDigest helper

packages/gatsby/src/redux/nodes.js, packages/gatsby/src/redux/run-sift.js
The generator eliminated by this commit was working fine but felt a little redundant. And since it was ranking at the top of the perf chart, I changed it to a plain `forEach` loop, which dropped it from the benchmark chart.
Additionally dropped two `Array.from` because they were redundant.
This seems to improve a simple MD site with 5000 pages that built in about 98s by one or two seconds.
Before:
After:
=> perf(gatsby): Eliminate generator

packages/gatsby-plugin-sharp/src/index.js
First PR 😄
Fix for #19220
https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/
=> fix(#19220): added default args for generateBase64 function

docs/starters.yml
This repo has been removed or made private:
```
$ curl https://github.com/bvlktech/blogerist -I
HTTP/1.1 404 Not Found
Date: Tue, 17 Dec 2019 11:59:05 GMT
Content-Type: text/html; charset=utf-8
Server: GitHub.com
Status: 404 Not Found
```
=> chore(starters): Remove starter that no longer exists in github

packages/gatsby/src/db/__tests__/__snapshots__/sanitize-node.js.snap, packages/gatsby/src/db/__tests__/sanitize-node.js, packages/gatsby/src/db/sanitize-node.js, packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
Due to default parameters being omitted the reference fix in #19802 was insufficient. Cementing it by removing the default args (we don't need them right now) and explicitly passing on the args instead.
Updated tests which now did catch the problem before fixing it.
ht @cameron-martin for pushing for the fix in #11364
=> fix(gatsby): fix circular ref stack overflow checks

e2e-tests/production-runtime/cypress/integration/1-production.js, e2e-tests/production-runtime/gatsby-node.js, e2e-tests/production-runtime/src/templates/static-page-from-cache.js, packages/gatsby/src/bootstrap/requires-writer.js
Async-requires paths are relative to the file which lives in .cache folder. If a component is inside the .cache folder our import breaks because it's being required from cwd and not the current directory. Prepending ./ cache so it's getting resolved from the current file.
Fixes #19931
=> fix(gatsby): add ./ prefix to paths in async-requires

packages/gatsby-telemetry/src/flush.js, packages/gatsby-telemetry/src/index.js
Suppressing telemetry flush calls when disabled through env should help with https://github.com/gatsbyjs/gatsby/issues/20125
=> fix(gatsby-telemetry): suppress flush if disabled

docs/docs/environment-variables.md
Prettier.js suggests using a constant since `activeEnv` is never reassigned and also use single quotes.
=> docs(environment-variables.md): use `const` instead of `let` if we are not re-assigning it

e2e-tests/development-runtime/cypress/integration/navigation/linking.js, e2e-tests/production-runtime/cypress/integration/1-production.js, packages/gatsby/cache-dir/production-app.js
enhanced the fix implemented as part of PR https://github.com/gatsbyjs/gatsby/pull/15552 for issue #15500 
Fixes #19462 (special characters part).
=> fix(gatsby): support unicode characters for 404 page

packages/gatsby/src/schema/infer/inference-metadata.js
Gatsby uses data inference to build GraphQL types. When sourcing nodes we aggregate meta-information about each node field. There are situations when two or more nodes contain conflicting field types. A simple example:
```js
createNode({ foo: "foo", internal: { type: "Foo" } });
createNode({ foo: 2, internal: { type: "Foo" } });
```
It is impossible to understand the type of the field `foo` from those nodes. We still produce GraphQL type in this case but remove `foo` field from it and also emit a warning.
Before this PR schema would rebuild when the type with conflicts updates. For example, it could rebuild on a new node (e.g. sourced statefully):
```js
createNode({ foo: "bar", internal: { type: "Foo" } });
```
(there are several other conditions to actually trigger the rebuild but I omit …
=> fix(gatsby): do not rebuild schema having identical conflicts

packages/gatsby-transformer-remark/src/extend-node-type.js
TypeScript and the ES module spec say that a module exports always has to be an object, (5 years later this is still a bit pain https://github.com/Microsoft/TypeScript/issues/2719 ) 
This means that TS emits an object with a `default` function when doing `export default function` - so when running through the plugins, want to guess which one of these was transpiled by typescript?
```
// Plugins: 
[Function]
[Function]
[AsyncFunction]
[Function]
[Function]
{ default: [Function: remarkShiki],
remarkShiki: [Function: remarkShiki] }
[Function]
[Function]
{ [Function] visitor: [Function: visitor] }
{ [Function] visitor: [Function: visitor] }
[Function]
[Function]
```
In user-land code, this can be worked around using `"esModuleInterop": true,` - but this code isn't in user-land and so this PR …
=> Allow gatsby-remark plugins to use ES spec conforming default funcs (e.g. TS emitted JS)

docs/docs/recipes/querying-data.md, docs/docs/recipes/sourcing-data.md
- fix 404 on image in recipes
- fix 404 on link to repo
#20113 [docs] move recipes to individual pages
=> fix(docs): 404 on image and links in recipes

docs/docs/adding-search.md
FlexSearch seems to be a pretty good option if you want to go with a client-side search engine. The search engine has all the features you might need, its docs are pretty awesome, and there are Gatsby and React integrations available. (A Gatsby plugin for indexing and a React hook for searching.)
https://github.com/nextapps-de/flexsearch
=> Add flexsearch (client-side engine) to site search overview docs

packages/gatsby/src/bootstrap/index.js
The analytics data currently often contains many copies of some plugin name-version-pairs. Only sending in unique pairs keeps the data a little cleaner.
=> fix(gatsby-telemetry): only report unique plugins

docs/docs/graphql-reference.md
GraphQL has a built-in `@skip` and `@include` directives which are useful for conditional data fetching. Adding some documentation about those in our graphql reference guide.
Affects [existing GraphQL reference](https://www.gatsbyjs.org/docs/graphql-reference/)
N/A
=> docs: Add documentation about GraphQL `skip` and `include` directives

packages/gatsby/src/schema/infer/__tests__/infer.js, packages/gatsby/src/schema/infer/add-inferred-fields.js, packages/gatsby/src/schema/infer/is-file.js
This PR fixes file inference on fields other than `[a-zA-Z0-9_]` which was broken before. Take an example:
```js
createNode({
id: `1`,
"file-here": `./file_1.jpg`,
parent: null,
children: [],
internal: { type: `Test` },
})
```
Before this PR, `file-here` was always inferred as `String` not `File`. But if you were to change the field name to `file_here` it correctly inferred it as `File`.
After this PR both `file-here` and `file_here` are inferred as `File` (and any field with special characters in general).
N/A
Fixes #20151
=> fix(gatsby): support file inference for any field name (not just [a-zA-Z0-9_])

packages/gatsby-cli/src/create-cli.js
This add support to `gatsby develop` command so that the port can be assigned through an environment variable called `PORT`.
This matches the behavior of `create-react-app` as seen [here](https://github.com/facebook/create-react-app/blob/71946b1ebab445d7e4f9efca39bf0fe0d4be30f3/packages/react-scripts/scripts/start.js#L60).
I'm not sure about the docs here but I'm open to suggestions 😄 
Fixes https://github.com/zeit/now/issues/3410
Fixes #17001
Related to #6280
=> feat(gatsby-cli): support for develop PORT env var

packages/gatsby/src/redux/__tests__/run-sift.js, packages/gatsby/src/redux/run-sift.js
For [Kentico Kontent source plugin] - there is a schema definition implemented (https://github.com/Kentico/gatsby-source-kontent/pull/95 - still in progress).
During testing, when I try to load a node that has a definition, but **does not have the data provided** - no node is created:
So then this query:
```gql
{
kontentItemTextContentTypeWithNoItem {
id
}
}
```
I am getting this error:
```json
{
"message": "Cannot read property 'id' of undefined",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"kontentItemTextContentTypeWithNoItem"
],
"stack": [
"TypeError: Cannot read property 'id' of undefined",
"    at LocalNodeModel.trackInlineObjectsInRootNode (C:\\projects\\gatsby-content-type-not-in-schema\\node_modules\\gatsby\\dist\\schema\\node-model.js:281:42)",
"    at …
```
=> fix(gatsby): Fix sift query against empty nodes

docs/contributing/setting-up-your-local-dev-environment.md
`-v` is implemented now (#19459) in `gatsby-dev-cli` so it can be used same here, the way as with `gatsby -v` in line 47
#19459 PR: feat(gatsby-dev-cli): Add --version 
#19348 Issue: feature request: add version to gatsby-dev-cli
=> fix(docs): use new -v for gatsby-dev-cli

packages/gatsby-source-shopify/README.md, packages/gatsby-source-shopify/src/__tests__/create-client.js, packages/gatsby-source-shopify/src/create-client.js
Fixes https://github.com/gatsbyjs/gatsby/issues/19055 and allows the shopify plugin to work with shops that run on a custom domain.
See the ticket for a discussion of the issue.
=> feat(gatsby-source-shopify): Add support for custom domains

www/src/views/shared/collapsible.js, www/src/views/showcase/showcase-list.js, www/src/views/starter-library/starter-list.js
Hey 👋
Fixing a couple of accessibility issues with the showcase page:
- Icon links had no text: https://dequeuniversity.com/rules/axe/3.4/link-name?application=AxeChrome
- Category toggle was implemented as an `h4` but was clickable and "toggleable" https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
Before:
After:
=> fix(www): Improve accessibility of showcase page

packages/gatsby-source-filesystem/src/gatsby-node.js
Fixes info messages when filesystem detects changes. When a new file is created we use the `add` word, when updating we use the `changed` verb.
This might lead to confusion
Fixes #17885
=> fix(gatsby-source-filesystem): fix add/change text

packages/gatsby/src/query/query-runner.js
We are writing out internal thing to `page-data` currently that is not needed for actual runtime, so this is waste of user's bandwidth (few bytes, but still) that is not needed:
before / after
```diff
-{"componentChunkName":"component---node-modules-gatsby-plugin-offline-app-shell-js","path":"/offline-plugin-app-shell-fallback/","result":{"pageContext":{"isCreatedByStatefulCreatePages":false}}}
+{"componentChunkName":"component---node-modules-gatsby-plugin-offline-app-shell-js","path":"/offline-plugin-app-shell-fallback/","result":{"pageContext":{}}}
```
This could be moved further and not write out `pageContext` at all if it's empty, but I feel this small change is safe bet that provide value
=> fix(gatsby): don't write out `isCreatedByStatefulCreatePages` to page-data files

.github/workflows/schedule-site-showcase-validator-workflow.yml
@pieh and I discussed how it would be possible to reduce the amount of notifications of failures from the Site Showcase Validator for forks of the repo. I modified the workflow so it will check if the repo is `gatsbyjs/gatsby` and if it is not, it will skip the run of the action. This doesn't disable the workflow on other forks, but this will reduce the notification spam for forks as it never actually runs the validator.
=> chore(actions): Run the site showcase validator only on the base repo

.github/ISSUE_TEMPLATE/documentation.md
Especially now that the Learning team has grown significantly, it seems likely that we'll be writing lots of issues related to documentation. I think it would be helpful to incorporate an issue template specific to suggestions for _new_ documentation. The goal here is to help streamline the process of requesting new docs for both Gatsby team members and members of the community. A similar strategy seems to have worked well in preparation for past Hacktoberfests. I'm open to suggestions on how to make this better but I don't expect feedback til the new year!
=> docs: Add documentation issue template

docs/docs/winning-over-developers.md
Corrected some spelling errors
fixed the spelling of "fontend" to "frontend" in the file
=> fix(docs): fix spelling in winning-over-developers

packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap, packages/gatsby-source-contentful/src/normalize.js
The gatsby-source-contentful [fixIds](https://github.com/gatsbyjs/gatsby/blob/c4a7c40d63538704f8964cdeb1df8a04285e9b21/packages/gatsby-source-contentful/src/normalize.js#L57-L67) method is recursively "fixing" contentful node ids, but only adding a contentful_id field one level deep.
Fixes #15426
=> fix(gatsby-source-contentful): Add contentful_id field recursively

packages/gatsby-cypress/README.md
`getByText` has been deprecated in `@testing-library/cypress` and will throw an error. This PR updates the example in the `gatsby-cypress` README.
It also updates the GitHub repo URL to the `testing-library` org.
Docs PR.
None.
=> docs(gatsby-cypress): update example to use findByText

docs/docs/testing-css-in-js.md
The Jest option `setupTestFrameworkScriptFile` has been renamed to `setupFilesAfterEnv`. The legacy name is deprecated.
Source: https://jestjs.io/docs/en/configuration#setupfilesafterenv-array
This PR updates the option in the `Testing CSS-in-JS` guide.
// noop
None.
=> docs: update Jest option setupFilesAfterEnv

docs/tutorial/part-zero/index.md
Command doesn't work as written: `gatsby develop -- --host:0.0.0.0`. Does work with extra `-- ` removed.
=> fix(docs): Remove superfluous `-- ` from `gatsby develop` cmd

packages/gatsby-remark-autolink-headers/README.md, packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-remark-autolink-headers/src/__tests__/index.js, packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js, packages/gatsby-remark-autolink-headers/src/index.js
Introduce boolean `isIconAfterH` prop in `gatsby-remark-autolink-headers` that will place the icon inline, after the header text. ( Defaults to `before` the title ) 
Also refactor to absolutely position icon relative to the header ( and make the header `position: relative` to make this possible. This removes the need for a float 👍 )
=> feat(gatsby-remark-autolink-headers): Allow `after` option to make icon appear after header text

packages/gatsby-remark-prismjs/src/escape-html.js
If a comma appeared in a code block in markdown with the Remark/PrismJS plugin, it was being rendered as the string `undefined`. This PR fixes that so commas are now rendered as commas.
I'll need help with updating the documentation.  This bug affects Gatsby's website and it will have to be rebuilt with this fix.
Fixes #20270
=> Fix commas in code blocks of markdown

packages/gatsby-source-graphql/package.json
Updates graphql-tools-fork to v8.0.1 which addresses #20280.
=> fix(gatsby-source-graphql): filter unused variables

docs/tutorial/index.md
I found a small typo while reading the documentation.
=> Fix small typo in tutorial index page

docs/docs/graphql-concepts.md
Add the `id` field back to the query in the snippet named `src/pages/index.jsx`. I proposed this since `node.id` is still referenced in the anonymous component in `index.jsx`, but the `id` field does not appear in the query there nor in the query fragment in `src/components/IndexPost.jsx`
=> Readd missing id field in refactored Index query

packages/gatsby-plugin-netlify-cms/src/cms.js
Fixes https://github.com/gatsbyjs/gatsby/issues/19898
Netlify CMS supports registering Gatsby components as preview templates. Some of these components (`gastby-link` in the issue above) use global window variables set [here](https://github.com/gatsbyjs/gatsby/blob/deb41cdfefbefe0c170b5dd7c10a19ba2b338f6e/packages/gatsby/cache-dir/production-app.js#L28).
The CMS plugin bundles the CMS as a separate React app thus needs to set these manually.
I'm stubbing the `___loader` since preloading is not required for the CMS previews.
Not sure this is the best approach though.
=> fix(plugin-netlify-cms): set global window vars required for Gatsby components

examples/using-local-plugins/README.md
Two of the examples link to each other, and one of them was renamed; this fixes a lingering dead-link.
Related to #10904, #10782
Thanks!
=> fix(docs): update link to using-gatsby-without-graphql example

docs/starters.yml
Adds `gatsby-starter-robin` to Starter Library
None.
None.
=> chore(starters) add gatsby-starter-robin

docs/sites.yml
fix description with `{titleofthesite}`
n/a
n/a
=> chore(showcase): fix description with `{titleofthesite}`

docs/starters.yml
It is a resume/CV starter with Netlify CMS as the headless CMS for editing content.
=> chore(starters): add gatsby-starter-resume-cms

packages/gatsby-transformer-remark/package.json, yarn.lock
We are using a rather old version of `remark-stringify@^5.0.0` . It has several issues that were fixed in newer versions. Also, The `remark` package itself uses a newer version `6.0.4`
Tried it with blog starter and www.
Fixes #20230
=> chore(gatsby-transformer-remark): bump `remark-stringify` to ^6.0.4

peril/rules/pull-request-on-starter.ts
=> Improve comment for when we auto-close a PR in a starter repo

docs/contributing/site-showcase-submissions.md
As contributor I would like to have a clear understanding of "[submit site to showcase](https://www.gatsbyjs.org/contributing/site-showcase-submissions/)" contribution. The issue I see in this doc is a `{titleofthesite}, {username}` variables misunderstanding. Some of contributors threat it as a real variable which they can put to e.g. `description section` and it will be replaced on built time. But it does not work this way. 
This fix should prevent contributors to use `{titleofthesite}` and `{username}` by making clear that these are not variables.
https://www.gatsbyjs.org/contributing/site-showcase-submissions/
Related to: https://www.gatsbyjs.org/contributing/submit-to-starter-library/
Related to #20365
Related to #20332
=> chore(doc): Fix variable issue in submit to showcase/starter docs

package.json, yarn.lock
- Cleans up the yarn lock file (there were changes in package.json which were not reflected in the lock file which we were seeing in various new PR's)
- Bump three Babel packages to a new patch version
=> chore(gatsby): bump babel packages

docs/docs/glossary.md, docs/docs/glossary/webpack.md, www/src/data/sidebars/doc-links.yaml
Adds a new documentation page that explains webpack and how Gatsby uses it. Also updates glossary page and sidebar navigation with links to the new page.
=> webpack glossary/enclyclopedia entry

packages/gatsby-cli/src/__tests__/index.js
Node.js v11 has been already deprecated and v13 is active now.
Please see https://nodejs.org/en/about/releases/
=> test(gatsby-cli): update active NodeJS version

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap, packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js, packages/babel-plugin-remove-graphql-queries/src/index.js, packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap, packages/gatsby/src/query/__tests__/file-parser.js, packages/gatsby/src/query/file-parser.js
Currently useStaticQuery can only be imported like this to work:
```js
import { useStaticQuery } from 'gatsby'
```
I'm in process of writing bindings to Gatsby for ReasonML/Bucklescript. Currently it compiles every ES6 import like this
```js
import * as Gatsby from 'gatsby'
...
Gatsby.useStaticQuery(...)
```
With this syntax the static query is not extracted in the babel plugin. This PR fixes that.
I don't think this needs to be a documented feature. It is nice though that it works for people that prefer this syntax for various reasons, but it shouldn't be the sanctioned way to import useStaticQuery.
=> feat(gatsby): Allow alternative import syntax for useStaticQuery

packages/babel-plugin-remove-graphql-queries/src/index.js, packages/gatsby/src/query/file-parser.js
Small change recommended by @pvdz (https://github.com/gatsbyjs/gatsby/pull/20330#discussion_r363658996)
=> Improve syntax

package.json, packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.js.snap
This fixes the bootstrap issue we are seeing in CI. Not sure when or why this was removed but we need it to compile the typescripts
=> chore(gatsby): Fix bootstrap CI

.eslintrc.js
This is a quick follow up from #20246 based on @LekoArts's suggestion!
=> chore(gatsby): Prevent eslint from changing type string quotes into backticks

.github/ISSUE_TEMPLATE/config.yml
See docs for this at https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
=> chore(github): Disable blank issues and link to Discord and AskGatsbyJS

docs/docs/graphql-concepts.md, docs/docs/winning-over-developers.md, packages/gatsby-plugin-netlify-cms/src/cms.js
=> Fix some typos

docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
Updated URL since there was an issue using the URL pointing to the blog since it should not be https (no SSL when using local gatsby develop, at least with default configurations). Of course, the production env file will be different and HTTPS would be recommended on the production one.
=> Update URL for development dot env file

docs/docs/unit-testing.md
The recommended test ignore patterns hit us hard recently b/c our project had the word `public` in the repository name on GitHub so basically when our CI cloned the repository and ran `jest`, it wouldn't find any files. We spent a good number of hours investigating why it wasn't working only to find out that jest was ignoring all of the files due to the fact that the word public was causing an entire project folder to be excluded.
=> chore(docs): Fix test ignore patterns

packages/gatsby-remark-katex/README.md
Updated katex repo URL to current one, that is (https://github.com/KaTeX/KaTeX).
Previously, it was (https://github.com/Khan/KaTeX) and it is now a redirect.
=> chore(gatsby-remark-katex): Change to new URL and avoid redirect

packages/gatsby-plugin-google-tagmanager/README.md
I just came across this issue where our cookie consent manager was not able to withhold cookies based on consent because it was initiated using our gtm container; by swapping the order of the analytics plugin and gtm plugin in gatsby-config.js, I was able to resolve the issue.
=> chore(gatsby-google-tagmanager): Update README

docs/docs/making-your-site-accessible.md
Name of plugin 'eslint-plugin-jsx-a11y' is misspelled as 'eslint-jsx-plugin-a11y', which can confuse readers as the package does not exist on npm's package repository.
[https://www.gatsbyjs.org/docs/making-your-site-accessible/#linting-with-eslint-jsx-plugin-a11y](https://www.gatsbyjs.org/docs/making-your-site-accessible/#linting-with-eslint-jsx-plugin-a11y)
=> chore(docs): Fix typo in 'eslint-plugin-jsx-a11y'

docs/contributing/pair-programming.md
Require an issue or PR selected when arranging pair programming calls.
=> docs(pair-programming): Require issue or PR and remove getting started sessions

docs/sites.yml
- Artivest: Moved over off Gatsby to Wordpress
- Moteefe: Changed to HTTPS
- Ema Suriano's Portfolio: Removed source_url as it is no longer available
- kepinski.me: Site migrated over to Next. Removing.
- Kenneth Kwakye-Gyamfi Portfolio Site: Removed source_url as they renamed their github username and it seems the project is now private.
- React Resume Generator: the main_url was pointing to the github repo which is incorrect.
- GatsbyFinds: Removed source_url as bvlktech has deleted their GitHub account it seems.
=> chore(showcase): Updates according to the validator

docs/blog/2018-10-26-export-a-drupal-site-to-gatsby/index.md
Thanks to https://www.drupal.org/u/klokie who sent some fixes and suggestions via email for this blog post:
1. After `git init`, the next step should be `npm install` and then `npm i
--save-dev better-sqlite3`.
2. You mention that you named the script `src/scripts/migrate.js`, but refer
to it afterward as `src/scripts/import.js`, so it should probably be named
`src/scripts/import.js`.
3. `aliases` is never defined - what should it be?
=> fix(blog): fixes for the export drupal to gatsby post

packages/gatsby-source-contentful/src/extend-node-type.js, packages/gatsby-transformer-sharp/src/customize-schema.js
The generated graphql schema have a lot of nullable fields which are required for images (i.e. the src of an image). This makes it incompatible to use it with type generators and TypeScript. 
This PR changes the gatsby-source-contentful and the gatsby-transformer-sharp to be at least compatible with the gatsby-image type definitions. 
Docs should exist already. I don't expect that they include such details. 
This PR should close #17003.
=> fix(gatsby-transformer-sharp): define required image fields as non-null in schema

docs/blog/100days/free-hosting/index.md
fix for:
```shell
warn Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non
RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2020-1-8, _f: undefined, _strict: undefined, _locale: [object Object]
```
n/a
fixes #20486
=> chore(docs): fix moment deprecation warning

docs/contributing/triaging-github-issues/index.md
The contributor flow was altered in an earlier PR and a couple outstanding issues remained. This PR fixes header consistency and makes mention of saved replies in a few key places.
Related to #20242
=> fix headers and add saved replies references

packages/gatsby-cli/README.md
Updates defaults in gatsby-cli ReadMe to note the fallback to `env.PORT` if it is provided.
Updates reference not caught in #20250 and thus fixes #20214.
=> docs: Update gatsby-cli ReadMe for develop PORT env var

docs/docs/what-you-dont-need-plugins-for.md
Also added hyperlink to styled-component
While reading through the Doc for plugins, I saw that the introduction statement for the second paragraph could be a bit more detailed 😄
https://www.gatsbyjs.org/docs/what-you-dont-need-plugins-for/
Related to #19277
=> docs(What-you-dont-need-plugins-for): Grammar change to aid readability 

docs/docs/upgrading-node-js.md, packages/gatsby-cli/src/__tests__/index.js, packages/gatsby-cli/src/index.ts
Now that Node 8 has hit EOL, we will stop actively supporting it and raise our minimum supported Node version to the next LTS (10.13) as per [support policy](https://www.gatsbyjs.org/docs/upgrading-node-js/#gatsbys-nodejs-support-policy). 
However, we won't stop support _immediately_ because we currently have roughly 6% of our users using Node < 10.13 (based on data over the past month).
This PR adds a deprecation warning for now and should set the stage for dropping support in a month from now.
=> chore(gatsby-cli): Add notice for Node 8 EOL

packages/gatsby-plugin-netlify-cms/src/cms.js
Removes CMS preview styles so they don't collide with the CMS's styles
Fixes #20428
=> fix(netlify-cms-plugin): remove preview styles from global context

packages/gatsby-remark-autolink-headers/src/gatsby-browser.js, packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js
Calculates scroll position in autolink-headers relative to document top instead of closest relative parent
Fixes #20362
=> fix(gatsby-remark-autolink-headers): Scroll to document top

docs/docs/overview-of-the-gatsby-build-process.md
Added a note on the 'Build manifest and related icons' build process.
The readers of this article may not immediately know (or care to find out) what this process does so I felt it would be useful to add a little note.
=> chore (doc): Update overview-of-the-gatsby-build-process.md 

docs/tutorial/writing-documentation-with-docz.md
The documentation to install `docz` is outdated and will not install the core `docz` if you follow the documentation.
Additionally, as it currently stands, we are pulling in the alpha versions of packages. This is risky. We should update this to pull in the `latest` stable version of the package instead of `next`.
Changing the docs to `npm install --save docz@latest gatsby-theme-docz@latest` would better suit this guide and allow for a working install.
Fixes #20386
=> docs(writing-documentation-with-docz): Update guide to fix dependencies

packages/gatsby-plugin-feed/src/__tests__/gatsby-node.js, packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
Jest has deprecated `describe(() => async`, so this removes the two instances we had, which weren't even really used.
=> chore(gatsby): Drop deprecated (and unused) async describe blocks

docs/docs/component-libraries.md
Looks like IBM's Carbon design system link doesn't work without the `www` (without it, it redirects to a dreamhost error page. This PR adds that + https for the link
=> Fix link to Carbon Design System in documentation

packages/gatsby-plugin-no-sourcemaps/README.md
Added an install heading to instruct users to install the plugin.
=> chore(gatsby-plugin-no-sourcemaps): Add install header to Readme

packages/gatsby-plugin-google-analytics/index.d.ts
Fix `gatsby-plugin-google-analytics` type definition.
The `value` parameter for `trackCustomEvent` should be a `number` instead of `string`.
Docs of this plugin and [Google Analytics docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#event_fields)
=> fix(gatsby-plugin-google-analytics): Value typing

packages/gatsby/index.d.ts
Typing for gatsby ssr api is wrong and too generic
=> fix(typing): more precise typing for ssr api

.circleci/config.yml, benchmarks/README.md, benchmarks/markdown_id/package.json, benchmarks/markdown_slug/package.json, scripts/build-benchmark.sh
Run each benchmark in CircleCI.
One run for each value of NUM_PAGES
Each benchmark needs to ensure that any generated files are cleaned before the build starts (specifically it needs to clean during the postinstall script).
Co-authored-by: Dustin Schau <dustinschau@gmail.com>
=> feat(benchmarks): add circleci job

packages/gatsby-plugin-netlify-cms/README.md
Since https://github.com/netlify/netlify-identity-widget/pull/223 is published I updated the Readme to reflect the fix
=> docs(plugin-netlify-cms): don't warn about GitLab implicit auth when using identity widget

packages/gatsby-cli/src/index.ts, packages/gatsby-cli/src/util/ensure-windows-drive-letter-is-uppercase.js, packages/gatsby-cli/src/util/normalize-windows-cwd.js
This PR ensures that the current working directory on Windows always has an uppercase drive letter (i.e., C: vs. c:).
Different utils like "true-case-path", "normalize-path", "slash" treat Windows drive letter differently. "true-case-path" will [uppercase](https://github.com/Profiscience/true-case-path/issues/3), others usually don't care. As a result path normalization produces different results depending on current cwd (c: vs. C:) which manifests in weird issues that are very hard to debug (see related issues bellow).
Ad-hoc fixes like the one introduced in #17492 address the part of the problem but anytime you want to compare a path that is normalized this way you must remember about it and normalize the other side of the comparison the same way.
This is not maintainable (and is …
=> fix(gatsby-cli): normalize case of windows drive letter

packages/gatsby-source-mongodb/README.md
=> docs(gatsby-source-mongodb): fix typo

packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-browser.js, packages/gatsby-plugin-google-tagmanager/src/gatsby-browser.js
gatsby-plugin-google-tagmanager is supporting renamed data layer from PR #16304. The later on fixing of "captures incorrect page title #13968" ignores these changes in dataLayerName feature.
This PR is created to address the issue described in issue #20536, by adding dataLayerName check, it falls back to dataLayer if dataLayerName is not defined.
Fixes #20536
=> Add dataLayerName check before push in event.

docs/blog/100days/gatsby-image/index.md
This blog post invites the community to learn about and use `gatsby-image`
=> Add challenge 3 of 100DaysOfGatsby

docs/docs/seo.md, packages/gatsby-plugin-offline/README.md
We get a lot of questions about view-source not working 100% correctly when using gatsby-plugin-offline as we ship a reduced payload to our users.
I've tried to improve these docs based on this issue
https://github.com/gatsbyjs/gatsby/issues/20235
https://github.com/gatsbyjs/gatsby/issues/20235
=> docs: improve gatsby-plugin-offline SSR seo

packages/gatsby-plugin-netlify-cms/README.md
Includes note on `gatsby-plugin-netlify-cms` for disabling widget JS within frontend. cc @erezrokah
https://github.com/gatsbyjs/gatsby/issues/17568#issuecomment-573771892
=> Add note about disabling frontend inclusion of netlify-identity-widget

docs/docs/recipes/working-with-themes.md
Using a Theme" recipe requires you to use a starter. For people wanting to know how to install and use a theme, starters create extra cognitive overhead: "what if I want to install a theme that isn't part of a starter? This PR adds a section for "Creating a new site using a theme"
https://www.gatsbyjs.org/docs/recipes/working-with-themes
Related to #20114
=> chore(recipe):Creating a new site using a theme

packages/gatsby-plugin-netlify-cms/src/cms.js, packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
This aims to provide more straightforward approach to add preview styles to netlify-cms previews during `develop` without workarounds. Basically this reverts some of the changes introduced in #19575 and enables `MiniCssExtractPlugin.loader` with HMR mode for most of the webpack rules that handle css including `sass` and `less`.
Related to #19575
Fixes #15126 and #20428
=> refactor(gatsby-plugin-netlify-cms) preview styles during development using MiniCssExtractPlugin and HMR

packages/gatsby/src/query/query-runner.js
A Map is designed for this work where an object will deoptimize after a handful of different keys.
=> perf(gatsby): Use a Map instead of Object for job id lookups

packages/gatsby/src/redux/run-sift.js
Noticed a site was going through the slow path even though there was no good reason for it. One of the reasons was that this check failed, even though it should pass.
We use unique `id`s internally for nodes, so if a query finds a node it can't find more than one node. So the check for `firstOnly` is redundant here.
This hopefully leads to a performance improvement for some other sites.
=> perf(gatsby): Drop `firstOnly` requirement for `isEqId` check

packages/gatsby-source-contentful/README.md
**TLDR: The main problem is that if you follow the current documentation, you end up with raw markdown in your pages instead of the expected formatted content**
As shown here: https://github.com/gatsbyjs/gatsby/issues/3205#issuecomment-351603320
> The source plugins still exposes the raw markdown but generally you'd want to use the transformed HTML as in the above code sample.
this means doing the following will return raw markdown instead of html.
```{
body{
body
}
}
```
You have to use a transformer plugin to transform the markdown into html.
The doc was misleading since it suggested that using LongText can be used without a transformer, and said that the markdown was transformed by Gatsby (incorrect). As a result, if someone were to follow the example, he would get raw markdown …
=> fix(gatsby-source-contentful): LongText fields require markdown transformer

docs/sites.yml
Submit to Showcase site named [gatsby-animate-blog](https://github.coms/luffyZh/gatsby-animate-blog).
It's a simple && cool gatsby blog starter.
=> Update sites.yml - Add a gatsby-animate-blog site

packages/gatsby/src/redux/nodes.js, packages/gatsby/src/redux/run-sift.js
While there is a check for queries by `id`, this one circumvents a few more steps. It prevents having to build up an array based on type. Instead, if it sees a query by `id`, it will immediately just fetch that node directly.
This makes many large sites that use plain queries by id a helluvalot faster. One site that made me look into this problem with 145k pages went down from 4.5 hours to about 5 minutes (that is not a typo).
=> perf(gatsby): Shortcut trivial queries by id, potential huge win

packages/gatsby-plugin-sitemap/README.md, packages/gatsby-plugin-sitemap/src/__tests__/internals.js, packages/gatsby-plugin-sitemap/src/internals.js
Now `gatsby-plugin-sitemap` treats `/foo/bar/` and `/foo/bar` as the same,
which removes unnecessary confusion when using the `exclude` option,
as previously `gatsby-plugin-sitemap` wouldn't work correctly with trailing slashes in `exclude` option.
Also fixed some inconsistencies in `README.md`
=> fix(gatsby-plugin-sitemap): allow paths with trailing slash in `exclude` option

packages/gatsby/src/utils/eslint-config.js
The current implementation loads the shared config by sending the name to ESLint, which doesn't know from where to resolve it. As a result, it resolves it from the cwd (so the project directory), which is wrong: it should be resolved from Gatsby itself.
Similarly, the `resolvePluginsRelativeTo` option need to be set for ESLint to know that the `graphql` plugin is meant to be loaded from Gatsby rather than the cwd.
- cf [`resolvePluginsRelativeTo`](https://eslint.org/docs/developer-guide/nodejs-api#cliengine)
=> Makes the ESLint configuration work regardless of the hoisting

scripts/check-publish-access/index.js, scripts/get-unowned-packages/index.js
The publish script was failing to recognise if the user was not logged-in to npm if they _were_ logged-in to yarn. This prevents Yarn being clever.
=> fix: npm permissions check

packages/gatsby-transformer-sharp/src/customize-schema.js
a race condition existed between existsSync() and .copy() for the same file causing the underlying fs-extra to randomly fail on unlink / chmod syscalls
now keeping track of copies in progress to prevent multiple parallel copies of the same file.
fixes https://github.com/gatsbyjs/gatsby/issues/20602
thanks to @pieh for the proposed fix
=> fix(gatsby-transformer-sharp): prevent duplicate copy of the same file

docs/tutorial/part-three/index.md
Following the "[Creating Nested Layout Components](https://www.gatsbyjs.org/tutorial/part-three/)" tutorial it uses the `gatsby-plugin-typography` and so it applies styles that change the default ones.
At the end of the tutorial page in the section [Add navigation links between pages](https://www.gatsbyjs.org/tutorial/part-three/#-add-navigation-links-between-pages) this image is added
but with the `gatsby-plugin-typography` applied the link colors are changed like so:
=====
=> Docs/Creating Nested Layout Components - Changed provided picture so it matches styles from following the tutorial

docs/docs/process-payments-with-stripe.md, www/src/data/sidebars/doc-links.yaml
Close issue #20199 by adding reference guide for Stripe. Also updated the doc-links to include the guide under building an e-commerce site. 
Closes #20199
=> chore(docs): Add Stripe reference guide

packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-image/src/__tests__/index.js, packages/gatsby-image/src/index.js
This PR is for the `gatsby-image` plugin.
Placeholders and layout-adjusting elements are unnecessary in the accessibility tree, so I have removed them using the `aria-hidden` attribute.
This prevents assistive technologies from recognizing blank elements.
https://www.gatsbyjs.org/packages/gatsby-image/#fixed-queries
https://www.gatsbyjs.org/packages/gatsby-image/#fluid-queries
Fixes #20181
=> fix(gatsby-image): Added aria-hidden attribute to layout elements

packages/gatsby-theme-blog/README.md
Closes #20631
This adds a table of information describing the fields a blog post has available based on the `gatsby-node` file's node interface in the schema.
=> docs(gatsby-theme-blog): Include Blog Post Fields

packages/gatsby-theme-blog-core/README.md
Closes #20631
This adds a table of information describing the fields a blog post has available based on the `gatsby-node` file's node interface in the schema.
=> docs(gatsby-theme-blog-core): include Blog Post Fields

packages/gatsby/src/redux/reducers/inference-metadata.js, packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
Looks like PR #19781 broke the ability to disable type inference on `SitePage`. So the following adjustment didn't work anymore:
```js
// gatsby-node.js
exports.createSchemaCustomization = ({ actions }) => {
actions.createTypes(`
type SitePage implements Node @dontInfer {
path: String!
}
`)
}
```
This PR fixes it. So it should be working as advertised again.
[Scaling Issues](https://www.gatsbyjs.org/docs/scaling-issues/#switch-off-type-inference-for-sitepagecontext) (was not working before this fix, works after)
Fixes #20395
=> fix(gatsby): Respect `@dontInfer` directive on `SitePage` type

www/src/data/tags-docs.js
- for 100days Gatsby i set the link for `Read the documentation` wrong (`/docs/100days` should be `/blog/100days`) in  #20519
- but this is not a documentation - so i remove this link
bug introduced in #20519 chore(blog): add tags for 100days
=> fix(blog): remove wrong link

docs/starters.yml
Adding my starter template to the starter.yml.
This is a blog boilerplate that focuses on displaying webcomics and art.  The layout is inspired by webcomics such as Magical Game Time and Dakota McFadzean.
The associated template can be found here: https://github.com/JLDevOps/gatsby-starter-webcomic
A demo can be found here: https://gatsby-starter-webcomic.netlify.com/
You can more information about the starter on the README- https://github.com/JLDevOps/gatsby-starter-webcomic
N/A
=> chore(starters): add gatsby-starter-webcomic

benchmarks/markdown_id/package.json, benchmarks/markdown_slug/package.json
Cloud currently requires that the version of `gatsby` be at least `2.1.0`, which is not the same as `*`.
From https://www.npmjs.com/package/semver#x-ranges-12x-1x-12- :
> * := >=0.0.0 (Any version satisfies)
Bump the version so we can test the benchmarks sites in Cloud.
=> chore(benchmarks): Increase minimum version of gatsby to meet Cloud requirement

docs/blog/100days/gatsby-image/index.md, docs/blog/2018-1-18-strapi-and-gatsby/index.md, docs/contributing/index.mdx, docs/docs/creating-a-starter.md
remove space from markdown links / image captions
similar to #20541
=> fix(docs): remove space from markdown links / image captions

packages/gatsby-plugin-benchmark-reporting/.babelrc, packages/gatsby-plugin-benchmark-reporting/.gitignore, packages/gatsby-plugin-benchmark-reporting/.npmignore, packages/gatsby-plugin-benchmark-reporting/README.md, packages/gatsby-plugin-benchmark-reporting/index.js, packages/gatsby-plugin-benchmark-reporting/package.json, packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Start of a plugin to report meta data back when running a benchmark (that includes this plugin).
This is different from and unrelated to the telemetry package. 
- For one this benchmark plugin is not automatically enabled, you have to explicitly add it to your site.
- Another reason is the way that stats are reported; this plugin will send everything after the benchmark, assumes no crash will occur.
- Everything is logged at once, rather than incrementally
- And finally this plugin sends a lot of meta data about the state of the repo, code, and state machine. This helps reporting and debugging regressions. We don't have to concern with privacy with this plugin.
This plugin is a shim to get the ball rolling. It will collect some time points and send them as a session id.
Server credentials …
=> feat(gatsby-plugin-benchmarks): Create benchmark reporting plugin

docs/docs/static-vs-normal-queries.md
Fix a small typo in a doc (docs/static-vs-normal-queries).
=> fix: typo in docs (docs/static-vs-normal-queries)

packages/gatsby-plugin-google-gtag/README.md
Adding code highlighting to gatsby build && gatsby serve command
=> Update gatsby-plugin-google-gtag docs

packages/gatsby/src/bootstrap/__tests__/graphql-runner.js, packages/gatsby/src/query/graphql-runner.js
This PR introduces a cache for GraphQL parsing and validation steps in the `graphql-runner`, which
improves the performance of query running for about 18% on our synthetic [`benchmarks/query`][1] site.
It is inspired by an [experiment][2] of @pieh with `graphql-jit`. We saw positive numbers from the
`graphql-jit` branch, but it turns out most benefits came from avoiding re-parsing and re-validating
the same query.
Here are some numbers on my laptop (queries per second, higher is better):
Node 10.17.0:
|                 | graphql-js     | graphql-jit |
| --------------- | -------------- | ----------- |
| without caching | 460 (baseline) | 422 (-8.2%) |
| with caching    | 543 (+18%)     | 561 (+22%)  |
Node 13.1.0 (surprisingly slower in general in this benchmark):
|                 | …
=> perf(gatsby): cache parsing and validation results in graphql-runner

docs/docs/porting-from-create-react-app-to-gatsby.md
Add `sessionStorage` to list of common globals needing protection during `gatsby build` in Server-side rendering and browser APIs section of `porting-from-create-react-app-to-gatsby.mdx`.
I use `sessionStorage` enough that I felt a reminder might be nice if I were starting out with Gatsby or looking to move an existing Create React App website to the framework.
https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/#server-side-rendering-and-browser-apis
=> docs(porting-from-create-react-app-to-gatsby): Add `sessionStorage` to list of common globals

docs/docs/using-graphql-fragments.md
Fix "Querying Data with GraphQL - Fragments" link on "Using GraphQL Fragments" page
=> fix(docs): Fix link on "Using GraphQL Fragments"

docs/docs/themes/shadowing.md
In [Shadowing other themes](https://www.gatsbyjs.org/docs/themes/shadowing/#shadowing-other-themes), it says that If we want to change the theme from `gatsby-plugin-theme-ui` while using the  `gatsby-theme-blog`, we have to create a file at: `user-site/src/gatsby-theme-blog/gatsby-plugin-theme-ui/index.js`. This doesn't work right now. 
Instead, as [Chris Biscardi suggests](https://www.christopherbiscardi.com/post/component-shadowing-in-gatsby-child-themes/), we have to create a file at `user-site/src/gatsby-plugin-theme-ui/index.js`. I changed the docs to reflect that. 
For a reproduction: 
- Use the `gatsby-starter-blog-theme` starter: `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`
- Then try to shadow the `gatsby-plugin-theme-ui/index.js` file. …
=> Docs: Update shadowing other themes

starters/default/src/components/layout.js
Makes a small tweak to the inline CSS from the default starter layout. I noticed as I was playing with it that it had a `paddingTop` call immediately after a `padding` shorthand that set the value of padding-top to the same value. When I removed the `paddingTop` property, it broke the `padding` shorthand up into long-form for everything but Top, potentially causing issues.
The fix for the secondary issue was to change the shorthand's top value to `0` instead of `0px`.
=> fix(gatsby-starter-default): Removes extraneous paddingTop

www/src/views/starter-library/starter-list.js
Resolves #20686
Also ensures the version and stars are always pinned to the top most
corner instead of sometimes floating based on the length of the author's
name
=> fix(www): fix background on gatsby version indicator in showcase

packages/gatsby/src/utils/api-runner-error-parser.js
The repro was too big to wrap in a test, but I did debug this to a point where I've verified and observed in the devtools that this value was an array. As such I'm adding a check and taking the first element of that array.
Technically there could be multiple errors in that array and perhaps we should do something with that. As it stands, printing an error is better than printing "cannot call match on undefined" :)
=> chore(gatsby): Fix case where the error parser receives an array

packages/gatsby/package.json, packages/gatsby/src/utils/__tests__/jobs-manager.js, packages/gatsby/src/utils/jobs-manager.js
Seems like slash isn't a dependency in gatsby. I could have sworn we used it on multiple places but it seems like it didn't.
https://github.com/gatsbyjs/gatsby/issues/20740
=> fix(gatsby): use slash from gatsby-core-utils

packages/gatsby-plugin-google-analytics/src/index.js
Add the ability to pass the event category, label, and action as properties to the `<OutboundLink>` component.
Addresses #20337
=> feat(gatsby-plugin-google-analytics) Pass additional props to the <OutboundLink>

packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js, packages/gatsby-plugin-manifest/src/gatsby-node.js, scripts/gatsby-plugin-checker/index.js
- Make sure to throw proper errors (see ##20749)
=> make sure to throw proper errors

packages/gatsby-source-lever/src/gatsby-node.js
Start using [schema customization API](https://www.gatsbyjs.org/docs/schema-customization/) for `gatsby-source-lever`
Part of #20069 
I'm not sure whether I've done this PR correctly, so I could use some help from @vladar
=> feat(gatsby-source-lever): use schema customization API (#20069)

packages/gatsby/index.d.ts
This improves the TS types for the `gatsby` package.
This adds the required types to be in line with the documentation for [createTypes](https://www.gatsbyjs.org/docs/actions/#createTypes).
=> fix(gatsby): Improve `gatsby` TS types for `sourceNodes`

.github/actions/gatsby-site-showcase-validator/README.md, www/src/components/showcase-details.js, www/src/templates/template-showcase-details.js, www/src/views/showcase/featured-sites.js, www/src/views/showcase/showcase-item-categories.js, www/src/views/showcase/showcase-list.js
all showcase links without a trailing slash result in a redirect
example:
```shell
curl -I https://www.gatsbyjs.org/showcase?filters%5B0%5D=WordPress
HTTP/2 301                                                                                                                                                              
location: /showcase/?filters%5B0%5D=WordPress         
```
and 
```shell
curl -I https://gatsbyjs.org/contributing/site-showcase-submissions/
HTTP/2 301                                                                                                                                                              
location: https://www.gatsbyjs.org/contributing/site-showcase-submissions/ …
```
=> fix(showcase): showcase redirects

docs/contributing/docs-and-website-components.md, docs/contributing/index.mdx, docs/docs/building-with-components.md, docs/docs/gatsby-lifecycle-apis.md, docs/docs/glossary.md, docs/docs/graphql-concepts.md, docs/docs/index.md, docs/docs/overview-of-the-gatsby-build-process.md, www/src/gatsby-plugin-theme-ui/components.js
Make (most) website components used in MDX files globally available. This allows them to be easily referenced in translated docs pulled in from other repos.
The only ones not made available are `<APIReference>` and `<GraphqlApiQuery>`, which we'll do as part of #18704.
Fixes: #19036
=> chore(www): Make components used in MDX globally available

packages/gatsby-source-contentful/src/extend-node-type.js
Fix Contentful schema validation for `null` nodes for `fixed` or `fluid` media assets.
N/A
#20696
=> fix(gatsby-source-contentful): Bypass schema validation for null nodes for fixed/fluid media assets

docs/blog/2017-10-17-building-i18n-with-gatsby/index.md, docs/docs/how-gatsby-boosts-career.md
removed unnecessary component state
there is no need to have a state in this component, we can use props directly
this is part of the documentation of LanguageSwitcher, is a code example.
=> Removed unnecessary component state, used props instead

docs/blog/2019-07-23-google-sheets-gatsby-acroyoga-video-explorer/index.md
add code fences to not create a clickable link from an example link
should it not be more like a full link like:
`https://domain.tld/path/super-image.png`
=> fix(blog): add code fences to not create a link from example

packages/gatsby/cache-dir/navigation.js
The `1px` height style on the `gatsby-announcer` div adds a `1px` line to the bottom of `100vh` pages. We want the announcer element to be visually hidden on the page, and have followed best practices from [WebAIM](https://webaim.org/techniques/css/invisiblecontent/#offscreen). 
> `width:1px; height:1px; overflow:hidden;` tells the browser to make the element 1px by 1px in size and to visually hide everything that does not fit into these dimensions. While this is a likely a little overkill and can probably be omitted in most circumstances, there are a few instances where positioning may be disabled, but all other styles remain enabled. In this case, the element will remain in its original position, but will only take 1 pixel of space.
To remove the line at the bottom of `100vh` pages, …
=> fix: remove 1px line from gatsby-announcer on 100vh pages

packages/gatsby/src/query/queue.js
The queue was retained for develop mode which led to the same event handlers being registered over and over again, which led to strange artefacts in the output.
With this change the events are aggressively deregistered from the queue when it finishes or fails.
Regression introduced in #20606
Fixes #20787
=> chore(gatsby): Deregister all events to the queue after batch

docs/docs/recipes.md
Showcasing the option for using a Gatsby theme on a site, from the recipe landing page would help Gatsby users  find this option faster. 
https://www.gatsbyjs.org/docs/recipes/#4-working-with-themes
https://www.gatsbyjs.org/docs/recipes/working-with-themes 
Related to #20595
=> chore(doc): Listing new gatsby theme recipe on recipes landing page

docs/blog/100days/react-component/index.md
This prompt asks you to add a third-party React library to your site - specifically Formik.
=> (blog) Add challenge 4 of #100DaysOfGatbsy

docs/docs/add-404-page.md, docs/docs/add-custom-webpack-config.md, docs/docs/basic-hardware-software-requirements.md, docs/docs/how-shadowing-works.mdx
Use soft-line instead of hard-line wrap for couple of old documentations.
This pull request does not cover all documentations. 
(Wasn't sure how long a pull request should be, I'm new. Let me know if I could improve how this is done.)
The change does not alter visuals of docs.
https://www.gatsbyjs.org/docs/how-shadowing-works/
https://www.gatsbyjs.org/docs/add-404-page/
https://www.gatsbyjs.org/docs/add-custom-webpack-config/
https://www.gatsbyjs.org/docs/basic-hardware-software-requirements/
Related to: #20769
=> chore(docs): Use soft wraps for old docs

package.json
Adds two `yarn`/`npm run` aliases;
- `yarn jest:inspect` will run jest through `node --inspect`
- `yarn jest:inspect-brk` will run jest through `node --inspect-brk`
The difference is that one (`--inspect-brk`) will wait for the devtools to connect and pause at the start. This one requires you to explicitly press the start button before the code starts running (once hooked up). The other one (`--inspect`) will start running immediately after connecting to devtools.
(For anyone looking at this; The way you use this is to go to chrome/chromium and open the pseudo-url `about:inspect`. In there click the "open dedicated window for node" link (see screencap). Once that window is open, `node --inspect` and `node --inspect-brk` will automatically start debug sessions in that devtools popup. To …
=> chore(gatsby): Add yarn shortcuts for running tests with devtools

packages/gatsby/src/utils/api-runner-node.js
Reverts #19664 because it exposed a timing problem in promises ultimately leading to `gatsby develop` triggering a number of redundant rebuilds.
At the core to this is listening to the api queue drain event, `API_RUNNING_QUEUE_EMPTY`, which before would only fire once. After this change, that event fires three times for the same sequence of events (a file changing).
The reason seems to relate to the difference in how BlueBird resolves its promise vs doing it natively. In this case, changing the promise led to the queue draining before the next api call had a chance to fill it up again. And again. So each of these calls would now see an empty queue, fill it, completely run (in pseudo sync time), and drain the queue again. Each call would lead to announcing the start and drain of the api …
=> fix(gatsby): revert #19664 fix duplicate runs in develop mode

docs/docs/glossary.md, docs/docs/glossary/headless-cms.md, www/src/data/sidebars/doc-links.yaml
Add a brief overview of what a headless CMS is, how it's different
from a traditional CMS, and why you might choose it for your project.
Updated glossary, doc-links.yaml with links to Headless CMS article.
=> Docs/Glossary: Headless CMS entry

packages/gatsby/ipc.json, packages/gatsby/src/utils/__tests__/jobs-manager.js, packages/gatsby/src/utils/jobs-manager.js
Enable external job execution through IPC messaging. If IPC is enabled & `ENABLE_GATSBY_EXTERNAL_JOBS` is true. We serialize the job object and send it to the main process. Now the main process can execute it on gatsby's behalf or run it on different hardware.
We enable 3 IPC actions:
- JOB_COMPLETED: let gatsby know if a job is completed
- JOB_FAILED: let gatsby know if a job has failed
- JOB_NOT_WHITELISTED: let gatsby know it should run the job locally
The parent process listens on the `JOB_CREATED` action which holds the whole job object.
https://github.com/gatsbyjs/gatsby/issues/19831
=> feat(gatsby): enable external jobs with ipc

docs/sites.yml
=> Site Showcase submission request

docs/tutorial/using-a-theme.md
Minor path change: Src needed to come first.
=> Update file path for bio-content in using-a-theme tutorial

docs/tutorial/ecommerce-tutorial/index.md
Fixed spelling of "e-commerce" as described in issue #20790
=> Fixed type: Issue #20790

docs/docs/build-caching.md
If you don't persist both .cache & public then there'll be errors when repeatedly building sites along the lines of `Can't resolve '../../public/static/d/856328897.json' in '/zeit/71ceb58f/src/components'`
=> Update build-caching.md to mention that build outputs are also in public

docs/blog/2020-01-23-why-typescript-chose-gatsby/index.md
I never managed to get a working preview of [the blog post](https://www.gatsbyjs.org/blog/2020-01-23-why-typescript-chose-gatsby/) (too many screenshots of websites on launching the site)  so I never spotted that `tsx` doesn't work in the code samples. I've switched it to TS, which should probably work.
=> Update "why TS uses Gatsby" a bit

packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap, packages/gatsby/src/query/__tests__/fixtures/query-compiler-schema.graphql, packages/gatsby/src/query/__tests__/query-compiler.js, packages/gatsby/src/query/query-compiler.js
We introduced an unintentional BC break in #19665 (when replaced Relay compiler with our own solution)
Before that PR relay compiler was adding extra fields to queries automatically:
1. An `id` field if it existed on the type
2. A `__typename` field if the type was a union or an interface.
In other words the following query:
```graphql
{
unionField {
... on TypeWithId {
foo
}
}
}
```
was transformed to:
```graphql
{
unionField {
__typename
... on TypeWithId {
id
foo
}
} 
}
```
Current PR mimics Relay compiler behavior and restores backwards compatibility.
This "feature" is not documented and shouldn't be. It is not recommended to rely on it as it [will be removed](https://github.com/gatsbyjs/gatsby/issues/15277#issuecomment-577573161) in Gatsby v3.0
Fixes #20290
=> fix(gatsby): Add `__typename` and `id` fields in queries to match previous behavior of relay-compiler

docs/docs/sourcing-content-from-json-or-yaml.md
The name stateless functional component seems to be deprecated now.
Changed the term to "functional component"
Related to: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364
Related to: https://github.com/gatsbyjs/gatsby-ja/pull/112
=> docs: fix React terminology

examples/image-processing/src/pages/index.js
Fixes the source image for `cropBottomLeft` described in [issue 20851](https://github.com/gatsbyjs/gatsby/issues/20851).
Fixes #20851
=> fix(image-processing-example): use same image for all `crop` examples

packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-plugin-sharp/src/__tests__/utils.js, packages/gatsby-plugin-sharp/src/gatsby-node.js, packages/gatsby-plugin-sharp/src/index.js, packages/gatsby-plugin-sharp/src/scheduler.js, packages/gatsby-plugin-sharp/src/utils.js
Note: This is very hacky - primarly the jobs v2 handling:
plugins right now don't know if they create duplicate jobs - this is internal gatsby core feature that is not exposed to plugins, so plugins potentially would need to implement duplicate jobs tracking themselves (duplicate functionality already built into gatsby). This is not ideal because implementation might not end up 1:1 (or implementations can drift over time)
Instead I listen to internal actions here, which are guaranteed not be emitted for duplicates (for jobs v2 code path). Legacy jobs / jobsv1 don't have any of this and this requires plugins to track things, so we already do that in sharp plugin - I just moved progress bar handling to "better" location so it doesn't display duplicates.
Long/medium term we should have Jobs …
=> fix(gatsby-plugin-sharp): hot fix for "Generating image thumbnails" progress bar reporting duplicates that don't do actual processing

packages/gatsby-plugin-sharp/src/process-file.js
=> fix(gatsby-plugin-sharp): honor `stripMetadata` setting for webp output images

packages/gatsby-plugin-sharp/src/scheduler.js
When testing @pieh's progress bar fix for image-sharp I noticed that we still rebuild some images on the old gatsby versions. I removed it from my refactor as I think it's bad behavior of the plugin to only check if it exists and not the hash of the file content.
This brings it back to have the same behavior as before. If people want better caching they'll need to upgrade gatsby.
=> fix(gatsby-plugin-sharp): add output file cache back for non job api

docs/tutorial/gatsby-image-tutorial/index.md
Fix typo: changed where as to whereas
=> docs(tutorial): fix typo

packages/gatsby/src/query/graphql-runner.js
this makes `GraphQLRunner.query` to return promise on validation errors
Before that if there was error in query executed in gatsby-node.js we would see error like this:
```
success building schema - 0.313s
ERROR #11321  PLUGIN
"gatsby-node.js" threw an error while running the createPages lifecycle:
runner.query(...).then is not a function
9 | module.exports = (store, reporter) => {
10 |   const runner = new GraphQLRunner(store);
> 11 |   return (query, context) => runner.query(query, context).then(result => {
|                                                           ^
12 |     if (result.errors) {
13 |       const structuredErrors = result.errors.map(e => {
14 |         // Find the file where graphql was called.
File: node_modules/gatsby/dist/bootstrap/graphql-runner.js:11:59
TypeError: …
```
=> fix: wrap `GraphQLRunner.query` return in Promise.resolve

www/src/utils/styles/global.js
Adds the little "ts" or "tsx" label onto TypeScript codeblocks
=> chore(www): Add labels on TypeScript and TSX code blocks

packages/gatsby/src/utils/api-runner-error-parser.js
Addresses this comment: https://github.com/gatsbyjs/gatsby/pull/20730#issuecomment-578171960
Observed a case where the `err` value is actually a string. This fix should resolve that case too (although to be fair we should always throw an `Error` instance or something similar)
=> fix(gatsby): structured error might be a string

packages/gatsby-plugin-mdx/gatsby/on-create-node.js, packages/gatsby-plugin-mdx/gatsby/source-nodes.js, packages/gatsby-plugin-mdx/utils/gen-mdx.js, packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
The gatsby-plugin-mdx plugin runs remark plugins almost identically to gatsby-transformer-remark, but omits several of the [node API helpers](https://www.gatsbyjs.org/docs/node-api-helpers/) when calling them. This PR ensures the rest of those helpers are passed all the way through.
Open to adding a test for this, but didn’t see any likely candidates for where it should go.
As far as I can tell, the fact that gatsby-transformer-remark passes all the API helpers to its plugins is undocumented, though extremely helpful. The gatsby-plugin-mdx docs simply say that you can use gatsby-transformer-remark plugins, so calling them with the same inputs should be a given.
Didn’t see any
=> fix(gatsby-plugin-mdx): Pass node API helpers from onCreateNode and sourceNodes to remark plugins

.circleci/config.yml
We are building gatsbyjs.org on Gatsby Cloud now 🎉 so we don't need CircleCI to do that anymore
=> chore: don't build gatsbyjs.org on CircleCI

www/src/utils/i18n.js, www/src/utils/sidebar/get-active-item.js
Fix styling of active links in the sidebar for localized versions of the gatsby site. Also update the `getLocalizedPath` to be more robust.
Fixes: #20796
=> fix(www): Fix styling of active links in the sidebar for localizations

docs/docs/sourcing-from-netlify-cms.md
Disclaimer: I'm new to React and Netlify 
When I created a post using netlify on my demo site images wok OK if the page is in the root directory
But not when I make a page in a subdirectory - I think the public_folder of netlify config should be an absolute path so that images still work for netlify content in subdirectories
=> docs(sourcing-from-netlify-cms): absolute path for public folder

packages/gatsby/src/query/__tests__/query-compiler.js, packages/gatsby/src/query/query-compiler.js
This PR fixes stack overflow caused by circular fragments. Stack overflow was first introduced here: https://github.com/gatsbyjs/gatsby/pull/19665 
Fixes #20826
=> fix(gatsby): Fix stack overflow on queries with circular fragments

www/src/utils/styles/global.js
In the little "ts" label on TypeScript codeblocks, text should be white on blue
=> chore(www): Change ts codeblock color

packages/gatsby/src/redux/__tests__/run-sift.js, packages/gatsby/src/redux/nodes.js, packages/gatsby/src/redux/reducers/resolved-nodes.js, packages/gatsby/src/redux/run-sift.js, packages/gatsby/src/schema/__tests__/fixtures/node-model.js, packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
This takes a more generic approach to shortcircuiting `eq` filters one exactly one property, including a chain of properties.
To be clear; this can make a HUGE perf difference at scale. It is a followup of https://github.com/gatsbyjs/gatsby/pull/20609 which only applied to index by `id` and dropped a site runtime from 4.5h to 5 minutes.
__This PR seems to improve perf the same for that site, but now for `slug` or any other property!__
This means a filter like `allISomeSource(filter: { fields: { slug: { eq: $slug } } }) {` can now be as fast as using `id`, which before was the only thing being indexed.
This PR is not finished (hence in a draft state). The graphql guru's need to take a closer look at this and then there are some (for me) obvious points that need to be addressed;
- I've now …
=> perf(gatsby): Create index on the fly for non-id index

docs/starters.yml
Noticed the "Danger" bot for another PR based on a couple starters having incompatible tags. This PR addresses those.
=> fix failing starter tags

packages/gatsby-source-contentful/src/__tests__/normalize.js, packages/gatsby-source-contentful/src/normalize.js
Currently recursion is used to walk the content models in `normalize/fixIds`. This results in quite a big overhead when run on big models (long call stack). Our app has entries that have 70k+ keys in them (entries that are linked to a lot of other entries) so call stack becomes quite big when using recursion.
This change removes the usage of recursion in favour of plain `while` loop and array of objects to fixIds in.
I tested it on our app with following content stats:
```
contentTypes fetched 47
Updated entries 6802
Deleted entries 0
Updated assets 2805
Deleted assets 0
```
I also replaced `Object.getOwnPropertyNames` with `Object.keys` since we don't care about non-enumerable keys in this scenario. This change shaves off ~5s in my tests.
No change needed.
=> perf(gatsby-source-contentful): remove recursion in fixIds

packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap, packages/gatsby/src/query/__tests__/query-compiler.js, packages/gatsby/src/query/query-compiler.js
A follow up for #20849 That PR doesn't take into account aliases. So when alias for `id` exists, we shouldn't auto-add `id` field to the query
#20943
=> fix(gatsby): Do not add field `id` to the query when `id` alias exists

packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap, packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap, packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap, packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js, packages/gatsby/src/schema/types/built-in-types.js
Using schema customization to define non-null fields for SitePage.
https://www.gatsbyjs.org/docs/schema-customization/
Closes #18806
=> refactor(gatsby): Add built-in GraphQL type for SitePage

www/gatsby-config.js
Changed autolink headers offset because of changed scroll based on page position instead of container in #20363
Fixes #20967
=> Changed autolink headers offset

docs/blog/2019-04-06-security-for-modern-web-frameworks/index.md
This fixes a simple typo for `hurtle` -> `hurdle`. Low impact, but excited to contribute! 😄 
n/a
No issue was created or exists since this is just a typo correction.
=> Fix typo in blog post

packages/gatsby-plugin-google-analytics/index.d.ts
Currently when using `<OutboundLink>` with eventAction, eventCategory or eventLabel properties, it shows an error (if type checking is enabled) as those properties are not added to the interface.
=> fix(gatsby-plugin-google-analytics) Add eventAction, eventCategory and eventLabel in OutboundLinkProps interface

www/src/data/sidebars/tutorial-links.yaml
At some point we changed the heading without updating the slugs that link to it, so I'm updating it here now.
What it is now:
https://www.gatsbyjs.org/tutorial/part-zero/#-install-nodejs-and-npm
What it should be:
https://www.gatsbyjs.org/tutorial/part-zero/#install-nodejs-for-your-appropriate-operating-system
=> fix(www) - Fix anchor link in tutorial sidebar

packages/gatsby-plugin-manifest/src/gatsby-node.js
Currently, I'm seeing the following error coming from `gatsby-plugin-manifest` when I'm using only the `icon` option:
```
The "path" argument must be of type string. Received type undefined
```
This happens because the `start_url` option is undefined unless set by the user, yet we're passing it as an argument to `path.posix.join`, which expects each argument to be a string. This change adds a condition around the line reassigning `manifest.start_url` to make sure it exists first.
=> fix(gatsby-plugin-manifest): Only reassign start_url if it already exists

www/gatsby-config.js
fix the error `Cannot read property 'resolve' of undefined`
- the double comma result in an `undefied` plugin
- the comma after `104` value added by prettier
see #21021 
fixes #21021 `chore(www): Cannot read property 'resolve' of undefined`
introduced in #20989 `Changed autolink headers offset`
=> fix(www): Cannot read property 'resolve' of undefined

packages/gatsby-source-lever/src/gatsby-node.js
Removed inference opt out `dontInfer` in order to allow developers to add custom fields with `createNodeField`.
https://www.gatsbyjs.org/docs/schema-customization/#opting-out-of-type-inference
Fixes https://github.com/gatsbyjs/gatsby/issues/21009
=> fix(gatsby-source-lever): Removed inference opt out dontInfer

packages/babel-preset-gatsby-package/package.json, packages/gatsby-plugin-typescript/package.json
I've got errors when tried to using yarn@berry which doesn't support implicit transitive peer deps anymore.
```
➤ YN0002: │ babel-preset-gatsby-package@npm:0.2.3 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-class-properties@npm:7.5.5
➤ YN0002: │ babel-preset-gatsby-package@npm:0.2.3 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-optional-chaining@npm:7.2.0
➤ YN0002: │ babel-preset-gatsby-package@npm:0.2.3 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-syntax-dynamic-import@npm:7.2.0
➤ YN0002: │ babel-preset-gatsby-package@npm:0.2.3 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-transform-runtime@npm:7.5.5
➤ YN0002: │ babel-preset-gatsby-package@npm:0.2.3 doesn't provide @babel/core@^7.0.0-0 requested …
```
=> chore: add babel/core to peer dependencies

packages/gatsby-source-contentful/README.md, packages/gatsby-source-contentful/src/__tests__/fetch.js, packages/gatsby-source-contentful/src/__tests__/plugin-options.js, packages/gatsby-source-contentful/src/fetch.js, packages/gatsby-source-contentful/src/plugin-options.js
_This is my first PR in gatsby. Please let me know of any adjustments or improvements I could make._
It is possible with Contentful that you have too much Content to receive
in the default 1000 page size, so you may need to add a custom page
limit to not get rate limited.
`Common error message: "400 Response size too big. Maximum allowed response size: 7340032b"`
I've added a new `pageLimit` plugin option to the `gatsby-source-contentful` plugin that allows the user to select the page size to use when downloading content from Contentful.
I added basic documentation to the `README.md` file in the `gatsby-source-contentful` package. Should I add any additional documentation for this?
Fixes #21026
=> Add page limit to gatsby-source-contentful

docs/tutorial/part-seven/index.md
The color used previously (bbb) had a contrast ratio of 1.91:1 which fails WCAG AA as well as WCAG AAA tests on both normal & large text.
The new color I've implemented (555) has a contrast ratio of 7.15:1 which passes WCAG AA as well as WCAG AAA tests on both normal & large text. Also, the new color passes the UI Components WCAG AA test.
Passing WCAG Test is better as it allows better readability.
The page affected by this commit is https://www.gatsbyjs.org/tutorial/part-seven/
@gatsbyjs/learning
Fixes #20694
=> Changed color on tutorial part-seven for better visibility

docs/docs/recipes/working-with-themes.md
The current recipe includes an example of configuration that will cause problems for gatsby blog theme users.
The issue is `mdx: false`, this is only meant to be used when another plugin configures mdx for you. In this example, it causes the blog posts not to appear.
I'm also removing the changes to directory paths. There isn't a reason to override them without knowing the users context and the comment is great at explaining the default behavior.
=> Remove misleading configuration from gatsby themes example

starters/blog/src/components/layout.js, starters/blog/src/components/seo.js, starters/blog/src/pages/404.js, starters/blog/src/pages/index.js, starters/blog/src/templates/blog-post.js
Simplify JS syntax in `gatsby-starter-blog` to make it easier to understand for JS beginners:
- only use [_arrow_ functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) instead of both _regular_ and _arrow_ functions
- only use [_function components_](https://reactjs.org/docs/components-and-props.html#function-and-class-components) instead of both _class_ and _function_ components
Fixes #20985
=> chore(gatsby-starter-blog): Refactor/simplify js syntax

packages/gatsby-theme-blog-core/README.md, packages/gatsby-theme-blog/README.md, packages/gatsby-theme-notes/README.md
When walking through theme setup I noticed that the READMEs would benefit from additional instructions for those not using a starter. This PR addresses the READMEs for the blog, blog core, and notes theme.
=> Update Theme READMEs with more explicit instructions

packages/gatsby-theme-blog/src/components/header.js
Remove call to css call from theme-ui for iconCss in header file of gatsby-theme-blog
No updates required
Fixes #20326
=> fix(gatsby-theme-blog): fix functions that are interpolated in css

docs/contributing/gatsby-docs-translation-guide.md
We've had a couple of issues with folks not realizing they can/should [check "allow maintainers to edit"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) when they make a PR, particularly in the i18n repos. Code owners have tried to make changes or apply suggestions but not had permission to do so. I think it makes sense to add a note to the contributing docs!
=> (docs) Add tip on allowing maintainers to edit PR branches

docs/docs/adding-search-with-elasticlunr.md, docs/docs/data-storage-redux.md, docs/docs/gatsby-for-freelancers.md, docs/docs/maintaining-a-plugin.md
Add missing `issue:` in frontmatter of stub pages.
Issues created: #21066 #21067 #21068 #21069
Part of: https://github.com/gatsbyjs/gatsby/pull/21064
=> add missing issues on gatsby stubs

packages/gatsby-source-filesystem/package.json, packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js, packages/gatsby-source-filesystem/src/create-remote-file-node.js, yarn.lock
gatsby-source-filesystem has a problem where downloads would stall and never timeout or error. Eventually all the concurrent downloads were stalled, preventing any more starting. This was causing builds to stall indefinitely. 
This PR adds a timeout in `createRemoteFileNode`. If no `data` events are received in the download stream for 30 seconds then the download is cancelled and retried up to three times. In tests this unblocks the downloads on the first attempt.
WIP while I'm writing unit tests.
=> fix(gatsby-source-filesystem): Retry stalled remote file downloads

packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js
In `gatsby-remark-autolink-headers`, this code snippet https://github.com/gatsbyjs/gatsby/blob/5e7ccd13f79e54036869a72e423bf7cf4ab486af/packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js#L51-L67
contains 2 instances of hardcoded "let" keyword, which  is being rendered into the HTML without transpilation. This makes the script crash in old browsers, such as IE (all versions).
This commit replaces "let" to "var". Care should be taken because this is an unsafe transformation, due to var scope hoisting. My initial tests show that everything is good.
I initially encountered this error while porting https://nextstrain.org to IE: https://github.com/nextstrain/nextstrain.org/issues/113
This fix should help scientists researching 2019-nCoV outbreak (some of them still use Internet Explorer) …
=> fix(gatsby-remark-autolink-headers): remove hardcoded "let" keyword

packages/gatsby/index.d.ts
I'm unsure if the TypeScript declarations have test coverage like with the DefinitelyTyped project, but I tried the changes in my own project and noted that my `onCreatePage` handler both types and runs properly.
Improve types for `onCreatePage` handler.
Fixes #20870
=> fix(gatsby): fix onCreatePage typings

docs/contributing/docs-templates.md, docs/contributing/managing-pull-requests.md
In talking to @laurieontech and @AishaBlake about learning team PR expectations (and a few stumbles with new recipes), I updated the contributing docs to provide more instructions for:
- Listing recipes on the overview page
- Instructing docs creators to test out their material
- Instructing PR reviewers to test out material and check if blog posts are approved
- Updated the CODEOWNER for @gatsbyjs/learning in the Managing PRs doc, which still pointed to @gatsbyjs/docs (which doesn't exist)
These are docs updates. So meta.
N/A
=> [contributing] add notes about docs and PR expectations

docs/docs/glossary.md, docs/docs/glossary/headless-wordpress.md, www/src/data/sidebars/doc-links.yaml
- Adds new article about headless WordPress.
- Adds a 'Headless WordPress' excerpt to glossary.md
- Adds an article link to `doc-links.yaml`
=> docs/glossary: Headless WordPress entry.

www/gatsby-node.js
Get rid of unneeded properties on the graphql query in www/gatsby-node.js. This saves around ~10s running locally. (The queries still like... 14 minutes, but it's better than nothing 🤷‍♀️)
=> perf(www): get rid of unnecessary items in query

docs/tutorial/ecommerce-tutorial/index.md
delete following line because, it is never used in `jsx:title=src/pages/advanced.js`
```
import { Link } from "gatsby"
```
https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/
Fixes: #21090
=> fix doc: delete import { Link } from "gatsby"

docs/tutorial/ecommerce-tutorial/index.md
There are two types quote in following tutorial, single-quote and double quotes.
Integrate two types of quotes into double quotes.
https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/
Fixes: #21092
=> fix doc: integrate quote type

docs/docs/gatsby-link.md, docs/docs/location-data-from-props.md, packages/gatsby-link/index.d.ts, packages/gatsby-link/src/__tests__/index.js, packages/gatsby-link/src/index.js
Adds Type, PropType, tests, and docs for `state` prop
Updates https://www.gatsbyjs.org/docs/location-data-from-props/#example-of-providing-state-to-a-link-component to agree with https://www.gatsbyjs.org/docs/gatsby-link/ and cross links both documents.
Another relevant page is https://www.gatsbyjs.org/docs/linking-between-pages/ but this already links to the GatsbyLink API docs, so I'm avoiding link soup here. Can add more cross linking if required.
Related to: https://github.com/gatsbyjs/gatsby/pull/3552
=> fix(gatsby-link): Adds Type, PropType, tests, and docs for `state` prop

examples/using-gatsby-image/gatsby-config.js, packages/gatsby-plugin-sharp/src/index.js
With jobs-api we need to make sure that gatsby-plugin-sharp is set inside the gatsby-config array. It should always have been this case, this shows a valid error when it happens.
=> fix(gatsby-plugin-sharp): throw error when not added to gatsby-config

packages/gatsby/src/query/__tests__/query-compiler.js, packages/gatsby/src/query/query-compiler.js
This PR fixes a bug in fragment cycle detection, which was causing an "Unknown fragment" error in several edge cases (when the same fragment was referenced twice in one query in specific positions and then was referenced in the other query).
It contains a fix and a test that fails without the fix.
Fixes #20984
=> fix(gatsby): Fix invalid algorithm of fragment cycles detection

packages/gatsby/package.json, yarn.lock
https://github.com/reach/router/commit/0a8af930398570d07d380ef1b6f80833501c8a29 which was released 6 days ago as part of `@reach/router` 1.3.0 broke `gatsby` because we depend on `location.href` to fetch resources on url change in https://github.com/gatsbyjs/gatsby/blob/20df97b33e76c0d2b6cb763400b2d9571b148b7f/packages/gatsby/cache-dir/ensure-resources.js#L16
Fixes https://github.com/gatsbyjs/gatsby/issues/20918
Fixes https://github.com/gatsbyjs/gatsby/issues/21139
=> fix(gatsby): Pin reach since they do not pass in location.href anymore

packages/gatsby-plugin-netlify-cms/README.md
We recently moved from Gitter to Slack.
=> docs(plugin-netlify-cms): update support link to slack

docs/docs/gatsby-cli.md
Technically, `0.0.0.0` is a non-routable IP, so it's not even supposed to work. The fact that hitting `http://0.0.0.0:8000/` works on some OSes is an oddity with the networking stack. Always using either `localhost` or the network IP is the best thing to do on every OS, not just on Windows.
=> Adjust Windows-specific notice about 0.0.0.0:8000

docs/docs/preparing-for-deployment.md
The missing link to the ["Deploying to Firebase Hosting"](https://www.gatsbyjs.org/docs/deploying-to-firebase/) page has been added to the ["Preparing a Site for Deployment"](https://www.gatsbyjs.org/docs/preparing-for-deployment/) page.
=> Add link to the Firebase Hosting docs

docs/blog/100days/index.md
changes:
- fix link to relative link to image
Notes:
- surprising it not show an error on blog page - but other image links in md* are relative with a dot 
- -> or asked the reverse way: why i there no "image not found" with this wrong absolute path? 
( i created #21174 `absolute image path not throw an error`)
#20228 `[blog] add 100 days of Gatsby and new email capture form`
=> fix(blog): fix link to relative link to image

docs/blog/2018-1-18-strapi-and-gatsby/index.md
- fix links to localhost
- some rewording needed to inline the plain links in text (i am open for better suggestions) 
- #20756 `[docs] Mark localhost URLs as code snippets`
=> fix(docs): fix links to localhost, rewording (on strapi blog post)

packages/gatsby-graphiql-explorer/src/app/app.js
This PR allows graphiql to set initial query variables from the following, in order: 
- `variables` query parameter in the URL
- `graphiql:variables` from localstorage
If both are not found, the initial query variables is set to `null`. 
Fixes #20192.
=> fix(gatsby-graphiql-explorer): Allow graphiql to set initial query variables from query string

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Use the telemetry session id so that we can correlate the data
=> feat(gatsby-plugin-benchmark-reporting): Use the telemetry session id

docs/sites.yml
Hi we're a Nottingham based dev studio, and we'd absolutely love it if you'd be able to showcase our site on the official Gatsby website. We're huge believers in Gatsby, to the degree that we have pivoted our entire dev process to focus on producing ultra-fast, SEO rich website using Gatsby.js and we're proactive in a lot of Headless CMS/JAMstack projects out there.
If there's any changes you'd love to see, drop a message across, we're always looking to improve the site.
=> chore(showcase): Add Roboto Studio site  to showcase

docs/docs/graphql-reference.md
GraphQL queries that include the 
``` 
edges {
node
}
```
pattern can replace that piece of the query with `nodes`. It's important to note that this is available when using Gatsby v2.2.0 or later.
=> Add note about nodes replacing edges, node in queries

docs/docs/naming-a-plugin.md
I erroneously thought plugins had to be named `gatsby-theme-*` to take advantage fo theme features. This adjust the plugin naming doc to account for that.
_None_
=> docs: update naming-a-plugin for actual theme conventions

docs/tutorial/building-a-theme.md
Removed extra 'the' in description of createPage. Added 'rendering' to phrase describing component shadowing.
=> Fixed typo

www/gatsby-node.js, www/src/templates/template-creator-details.js
Add an additional filter in the search query for sites. Before, we were querying the entire set of site screenshots each time, which gets expensive. This saves ~1s per creator page (playing around with the graphql editor, at least) for a total save of ~45s.
=> perf(www): Add additional filter when searching sites in creator-details template

examples/using-wordpress/src/templates/page.js, examples/using-wordpress/src/templates/post.js
Replace non-existing siteMetadata.subtitle with siteMetadata.description in the 'using-wordpress' example. This resolves the otherwise failing example.
Not applicable
None to my knowledge
=> Replace siteMetadata 'subtitle' with 'description'

docs/docs/recipes/deploying-your-site.md
When I try to deploy to netlify following [directions in documentation](https://www.gatsbyjs.org/docs/recipes/deploying-your-site#directions-1), I encountered timeout error.
```
Deploying to live site URL...
✔ Finished hashing 0 files
🕛✔ CDN requesting 0 files
✔ Finished uploading 0 assets
dp Waiting for deploy to go live... ›   Warning: 
›   {
›      "name": "TimeoutError"
›   }
›
b Waiting for deploy to go live...TimeoutError: Promise timed out after 1200000 milliseconds
at Timeout._onTimeout (~/.nodenv/versions/12.14.1/lib/node_modules/netlify-cli/node_modules/p-timeout/index.js:27:54)
```
I could solve this problem by adding `-d .` option to the command.
Reference: https://community.netlify.com/t/deploy-with-gatsby-is-hanging/6775
- …
=> doc: fix netlify command option

docs/blog/2018-12-17-turning-the-static-dynamic/index.md
The post originally instructed netlify-lambda to build to and serve from the `lambda` folder via .netlify.toml, whilst `developMiddleware` is configured to proxy `functions`, and the example `fetch`es `/.netlify/functions/hello`.
This results in the example fetch returning html from the Gatsby's development 404 page, which logs the error:
> Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
In making these references consistent so that the example works, I opted for `functions` because it seemed more conventional, but we could make it `lambda` consistently if anyone prefers! 
Note that there are unchanged references to `functions` later in the file which are not highlighted in the diff 👍
Thanks for the tutorial!
CC @sw-yx
Updates: …
=> Fix config instructions for netlify lambda

docs/docs/porting-an-html-site-to-gatsby.md
Fixed closing bracket synthax error in breadcrumbs array.
Issue is located in this code snippet:
https://www.gatsbyjs.org/docs/porting-an-html-site-to-gatsby/#porting-other-pages
=> docs: fixed closing bracket synthax error in breadcrumbs array

www/src/components/email-capture-form.js
Convert `<EmailCaptureForm>` to a function component.
It's a component with UI text that should be localized, and I want don't want to use [HOC injection](https://github.com/gatsbyjs/gatsby/pull/21024/files#diff-f772c656e3adc950a1dfc1c014c753e1R445) to do it.
=> refactor(www): Convert email-capture-form to a function component

packages/gatsby-plugin-mdx/gatsby/create-webpack-config.js, packages/gatsby-plugin-mdx/loaders/mdx-loader.js
This is a follow-up to #20879, doing exactly the same thing, but from the loader entrypoint rather than the sourceNodes and onCreateNode entrypoints.
=> fix(gatsby-plugin-mdx): Pass node API helpers through mdx-loader to remark plugins

www/src/pages/features.js
Add slashes to the links in the features overview so that the pages are marked as 'active' in the sidebar.
Not having the slashes means the page doesn't show as "active" in the sidebar:
https://www.gatsbyjs.org/features/jamstack
But adding the slashes fixes it:
https://www.gatsbyjs.org/features/jamstack/
=> fix(www): Add slashes to links in features overview

docs/docs/recipes/deploying-your-site.md, docs/docs/recipes/pages-layouts.md, docs/docs/recipes/querying-data.md, docs/docs/recipes/sourcing-data.md, docs/docs/recipes/styling-css.md, docs/docs/recipes/transforming-data.md, docs/docs/recipes/working-with-images.md, docs/docs/recipes/working-with-starters.md, docs/docs/recipes/working-with-themes.md
Set the table of contents depth for the recipes pages so that only the names of the recipes are listed. The subheadings take a lot of space in the TOC and are the same for each one ("Prerequisites", "Directions", "Additional Resources").
Before, the names of most recipes are under the fold:
Removing these subheadings puts all the recipes above the fold and makes it easier to find things:
// TODO result screenshot
=> fix(docs): Set table of contents depth for recipes

www/gatsby-node.js, www/src/components/page-with-plugin-searchbar.js, www/src/layouts/index.js, www/src/pages/plugins.js, www/src/templates/template-docs-local-packages.js, www/src/templates/template-docs-remote-packages.js
Reorganize the way the plugin pages/templates use layouts:
* Use `@loadable/component` instead of our custom thing
* Get rid of the custom logic in `gatsby-node` and `layouts/index.js`
* Import <Layout> and <PageWithPluginSearchbar> directly in the the plugin pages/templates
=> refactor(www): Reorganize plugin pages layout

www/src/data/sidebars/contributing-links.yaml
Move the page ["Setting Up Your Local Dev Environment](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)", which deals specifically with setting up the local dev environment for code contributions, under the ["Code Contributions"](https://www.gatsbyjs.org/contributing/code-contributions/) page. "Docs Contributions" and "Community Contributions" already have subpages, so it's not adding a new level of hierarchy that doesn't exist yet.
=> fix(docs): Move "Setting Up Your Local Dev Environment" under "Code Contributions"

docs/contributing/docs-contributions.md, docs/contributing/events.md, docs/contributing/index.md, docs/contributing/stub-list.md, docs/docs/index.md, www/src/templates/template-docs-markdown.js
Add a new `description` frontmatter tag to enable custom SEO descriptions and add documentation for it.
Add descriptions back to the following pages that were converted to MDX recently:
* docs/index.md (#18014)
* contributing/index.md (#19057)
* contributing/events.md (#21227)
* contributing/stub-list.md (#21287)
=> feat(www): Add the ability to add custom descriptions to docs

www/src/pages/plugins.js, www/src/templates/template-docs-local-packages.js, www/src/templates/template-docs-remote-packages.js
Fix failing dot-org build by getting the location prop for remote and local package templates.
=> fix(www): get location prop for remote and local package templates

www/src/components/layout/layout-with-heading.js, www/src/components/layout/page-heading.js, www/src/pages/ecosystem.js
Fix weird styling in gatsbyjs.org/ecosystem by inheriting from the same Layout used everywhere else.
The current /ecosystem page has some issues:
* The link to "Gatsby Cloud" in the banner is double-underlined
* All text is slightly more bold than in all other pages of the site
By pulling in the normal `<Layout>` component and making some adjustments, we resolve these issues:
=> fix(www): inherit from layout in ecosystem page and fix weird styling

packages/gatsby-plugin-netlify-cms/src/cms-identity.js
When initializing NetlifyCMS with the identity widget, CSS programmatically injected into the Preview Pane (via `styled-components`) does not appear. By deferring initialization to next tick via `setImmediate` it fixes the problem. 
See [here](https://github.com/damassi/toolshed-soundlab/blob/master/src/cms/injectStyles.jsx) for example how I'm injecting styles into the preview pane. Unfortunately, it is unclear why `enableIdentityWidget: true` creates this conflict.
=> fix(gatsby-plugin-netlify-cms): Prevent injected CSS clashes in Preview Pane

docs/starters.yml
This PR adds a WP GraphQL starter to the Starters area.
The idea behind the starter is to have "A super simple, bare-bone starter based on the Gatsby Starter for the front end and the WP GraphQL plugin on your WordPress install."
This is a basic "headless CMS" setup. This starter will pull posts, pages, categories, tags, and a menu from your WordPress site. You should use either the TwentyNineteen or TwentyTwenty WordPress themes on your WordPress install.
The example here uses the WordPress Theme Unit Test Data for post and page dummy content.
This Stater should get you started at 100 across the board in Chrome Lighthouse test.
Here's the [DEMO](https://wp-graphql-gatsby-starter.netlify.com/).
See the repo for more instructions on how to get set up …
=> chore(starter): Add a WordPress GraphQL Gatsby Starter

packages/gatsby/src/schema/node-model.js
Use the argument to update the cache.
As suggested by @blainekasten in https://github.com/gatsbyjs/gatsby/pull/20729#pullrequestreview-350948674
=> fix(gatsby): Use argument for updating cache

docs/starters.yml
`gatsby-starter-typescript-plus` no longer uses TSLint for its linting tools (it's been migrated to ESLint for quite some time)
N/A
N/A
=> Update gatsby-starter-typescript-plus details

docs/blog/2020-02-11-founding-organizations/index.md
Fixed two typos in the headings
=> fix(blog): founding organizations typos

packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap, packages/gatsby/src/query/__tests__/query-compiler.js, packages/gatsby/src/query/query-compiler.js
Don't audo add `id` field at all.
Reproduce steps: https://github.com/gatsbyjs/gatsby/issues/20943#issuecomment-581733538
https://github.com/antvis/gatsby-theme-antv/pull/105/checks?check_run_id=424609520#step:4:166
Fixes  #20943
=> fix(gatsby): revert auto-adding id field to queries

packages/gatsby-image/README.md
Removed `fluidImages` and `fixedImages` from [gatsby image docs](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images)
These props are no longer used as the functionality for art directing images is handled by passing arrays to `fluid` or `fixed` props
[gatsby image docs](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images)
=> Removed deprecated fluidImages and fixedImages props from docs

docs/docs/path-prefix.md
gatsby build --prefix-paths don't guarantee all the components will be serve using the prefix, only the links.
what about gh-pages?
There's no documentation telling about serve --prefix-paths (on prefix path documentation)
https://github.com/gatsbyjs/gatsby/issues/14898
https://github.com/gatsbyjs/gatsby/issues/21313
=> serve with --prefix-paths

packages/gatsby/src/bootstrap/graphql-runner.js
Hot reloading is broken on certain configurations due to node materialization.
Child objects in the node model are not updated when a node is recreated
This has something to do with the recent materialization update
By resetting the runner on these events the node model is forced to be recreated
See details in issue #18661, this is a dirty fix but allows me to edit files without
gatsby crashing
Resets the GraphQLRunner in `packages/gatsby/src/bootstrap/graphql-runner.js` on events
* `DELETE_CACHE`,
* `CREATE_NODE`,
* `DELETE_NODE`,
* `DELETE_NODES`,
* `SET_SCHEMA_COMPOSER`,
* `SET_SCHEMA`,
* `ADD_FIELD_TO_NODE`,
* `ADD_CHILD_NODE_TO_PARENT_NODE`,
This is a direct translation of comments by @pieh [here](https://github.com/gatsbyjs/gatsby/issues/18661#issuecomment-546893796)
Fixes #18661
=> fix(gatsby): Reset graphql runner on certain node events

docs/contributing/organize-a-gatsby-event.md
We're going to be updating our community event support process, policy, and offerings in the next few weeks. In the short term, this page needs to be updated to reflect that community event support is currently on hold.
=> Community Event Support on hold

www/src/components/modal.js
Seems like this was missing in https://github.com/gatsbyjs/gatsby/pull/21276
=> fix(www): import design tokens from gatsby-design-tokens in modal.js

examples/using-gatsby-image/src/pages/prefer-webp.js
fixes a missing space between the words "with" and "withWebp" on the page https://using-gatsby-image.gatsbyjs.org/prefer-webp/
=> fixes typo on the page "prefer-webp"

docs/docs/schema-customization.md
Just a quick fix, ran into this when I was playing around with schema customization and ran the code example.  The example had 'action' but should be 'actions'.
=> chores(docs): typo in schema customization

www/gatsby-config.js, www/package.json
In plugin library we render content that we don't own and sometimes it will have images using `http://` which cause "mixed content" issues. This enforces usage of `https://` - it might break some images, but they are already broken:
It's using plugin I authored outside of this repo - https://github.com/pieh/gatsby-remark-http-to-https
What the plugin does - it will change absolute image urls if they contain `http://` to `https://`
=> fix(www): replace image url using http:// with https://

packages/gatsby-source-contentful/src/normalize.js
As described in the linked issue, currently when querying an empty "long text" field with the `gatsby-source-contentful` package, a string with a single whitespace character is returned. It seems this whitespace serves no purpose and makes falsy checks unintuitive and overcomplicated. This PR simply removes the unnecessary whitespace.
Fixes #20579
=> fix(gatsby-source-contentful): Remove whitespace from default long text value

docs/contributing/how-to-file-an-issue.md
Stumbled across some minor grammatical errors in the How to File an Issue section of the docs.
https://www.gatsbyjs.org/contributing/how-to-file-an-issue/
=> fix(docs): Fix some grammatical errors in How to File an Issue

www/src/utils/node/docs.js, www/src/utils/node/starters.js
It looks like there're a couple of fields in graphql queries we don't use within gatsby-node or in the template component. Having these fields will probably not affect the performance significantly, but it would be good to get rid of them I guess.
Cc: @tesseralis @dvrylc
=> refactor(www): remove unused fields from graphql queries

docs/blog/100days/pwa/index.md
Made the YouTube embed in the article more accessible by adding a title tag.
Thank you @marcysutton for the prompt.
=> fix(blog): Add title to YouTube embed

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
This adds a few new fields to the benchmark plugin: git repo hash, ci status, siteId, cwd, ci name, node version, gatsby version, gatsby cli version, sharp version (if present), webpack version, node memory (straight dump of `process.memoryUsage()`), size of all `js` files in root folder of `public`, and the number of images found recursively in `public` or `.cache`.
It also groups the versions and counts into a struct.
The plugin now reports the text of a 500 error, if any.
~Need to update big query schema before pulling this.~ @jamo  has updated the schema accordingly.
This change is not windows friendly due to the execSyncs using `find`, `wc`, `bc`, and forward slashes. There are probably one or two more subtleties that I can't test for. For the time being this plugin is intended to …
=> chore(gatsby-plugin-benchmark-reporting): Add more meta data

docs/docs/gatsby-project-structure.md
Fixes documentation order to match the file structure talked about in the doc
This is a documentation PR already
N/A
=> Moving Documentation Order To Match File Structure

docs/docs/location-data-from-props.md
Under '[Example of providing state to a link component](https://www.gatsbyjs.org/docs/location-data-from-props/#example-of-providing-state-to-a-link-component)', closing link bracket showed <Link ... }}> instead of <Link ... />.
Can be found in "Routing" section in docs under "[Location Data from Props](https://www.gatsbyjs.org/docs/location-data-from-props/)".
=> fix: Routing docs - location data code example typo

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
This fixes an error in the container environment where this is intended to run, which does not have `bc`.
=> fix(gatsby-plugin-benchmark-reporter): Do not rely on env for js size

packages/gatsby-plugin-mdx/README.md
In the README for `gatsby-plugin-mdx`, the name of the plugin was sometimes in plain text ("gatsby-plugin-mdx") and was sometimes in code backticks (`gatsby-plugin-mdx`). This simply updates all references to use code backticks for consistency.
n/a
n/a
=> docs(gatsby-plugin-mdx): consistent backticks

www/src/components/showcase-details.js
When you go to [Gatsby Showcase](https://www.gatsbyjs.org/showcase/) and click on a site that is not a featured one (e.g. https://www.gatsbyjs.org/showcase/www.ventura-digital.de), the page is broken -- it doesn't show anything. Turns out we're querying data only for featured sites and it's breaking the details view for other sites. This PR removes the filter to get only featured sites from the query and everything looks to be working fine.
**Before:**
**After:**
=> fix(www): Fix Gatsby Showcase Details View

packages/gatsby-design-tokens/CHANGELOG.md
Manually fix the `gatsby-design-tokens` 2.0.0 changelog, and add a description for the 2.0.1 bugfix release.
@sidharthachatterjee
=> chore(gatsby-design-tokens): Manually fix CHANGELOG

packages/gatsby-source-drupal/README.md, packages/gatsby-source-drupal/src/__tests__/fixtures/article-includes.json, packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi-includes.json, packages/gatsby-source-drupal/src/__tests__/index.js, packages/gatsby-source-drupal/src/gatsby-node.js
Drupal's JSON:API module supports [includes](https://www.drupal.org/docs/8/modules/jsonapi/includes), a method for including relationships data. 
This PR adds very simple and basic support for creating Gatsby data out of the data in the `included` property of the JSON:API result. This way only data that is used is included in Gatsby, without having to fetch all data for a certain resource type.
See #21379 for the full motivation.
Updated documentation in the README.md of the `gatsby-source-drupal` plugin.
Addresses #21379
=> feat(gatsby-source-drupal): Add Drupal JSON:API Includes support

packages/gatsby-plugin-offline/README.md
Change docs to be compliant with the code: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/src/gatsby-node.js#L132
Using current example from docs prints following error to console:
```
Specifying 'cacheFirst'' in a 'runtimeCaching[].handler' option is deprecated. Please update your config to use 'CacheFirst'
```
=> docs(gatsby-plugin-offline): Change runtimeCaching handlers

docs/blog/2020-02-10-accessible-client-side-routing-improvements/index.md
- use same syntax (`React.Fragment`) in both examples
- fix indention
- fix syntax highlighter
- removed closing `div`
- #21018 `Blog 2020-02-05 Accessible Routing`
=> chore(blog):  use React fragment in example , intention, remove div. 

docs/sites.yml, packages/gatsby-transformer-remark/utils/time-to-read.js
Updated sites.yml file to add site showcase contributions for review
=> Submitting Multiple Site Showcase Contributions

www/src/pages/blog/tags.js, www/src/templates/tags.js, www/src/views/creators/index.js
Add missing footer links to the following pages/templates
- https://gatsbyjs.org/blog/tags
- https://www.gatsbyjs.org/blog/tags/themes (and other tag pages)
- https://www.gatsbyjs.org/creators/
https://github.com/gatsbyjs/gatsby/issues/21482
=> Fix missing <FooterLinks> from gatsby.org pages

www/src/components/homepage/homepage-ecosystem.js
In devices like iPhone X and Pixel 2 XL, the plugins and starter section in the home page of GatsbyJS is broken. This was because on these devices in landscape mode, styles are applied for breakpoint md. (See [ecomsystem-section.js](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/ecosystem/ecosystem-section.js#L15)) 
The max-height set to 60vh was causing the problem. So a change was made in [homepage-ecosystem.js](https://github.com/TheFirstMe/gatsby/blob/thefirstme/broken-ui-on-gatsbyjs-21446/www/src/components/homepage/homepage-ecosystem.js#L39) to set max-height to none. 
Before the fix: 
After the fix:
Fixes #21446
=> fix(www): Fixes broken UI on home page of gatsbyjs.org in landscape orientation

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
This makes it easier to graph out commit time progression, hopefully also makes it easier to triage regressions by mapping it to actual timelines.
=> feat(gatsby-plugin-benchmark-reporting): Also submit commit time

packages/gatsby-cli/package.json, renovate.json, yarn.lock
Requiring latest `react` version in `gatsby-cli` (for `ink`) causes trouble with npm installs - if user specified `react` version doesn't satisfy `>= 16.8` constraint then it seems like `npm` can't properly resolve `node_modules` hierarchy
This does not take care of https://github.com/gatsbyjs/gatsby/issues/19827 completely, but it limits scenario when this error will happen (with this change it should only happen when user specified version of react is in range `>= 16.3 && < 16.8` (instead of `>= 16.3 && 16.12`):
```
npm WARN ink@2.7.1 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
```
```
gatsby-shopify-starter@0.1.0 /Users/misiek/test/marcuswelds-gatsby-test
├─┬ UNMET PEER DEPENDENCY gatsby@2.19.18-cli-react-from-ink.35
│ └─┬ …
```
=> fix(gatsby-cli): lower required react version

docs/docs/glossary.md, docs/docs/glossary/continuous-deployment.md, www/src/data/sidebars/doc-links.yaml
- Updated glossary.md with new entry.
- Updated doc-links to add link to new entry.
=> docs/glossary: Continuous deployment article, excerpt

docs/tutorial/part-zero/index.md
before "writing a given set of instructions ..."
Fix missing quotation mark
=> chore(docs): Fix missing quotation mark

.typo-ci.yml
The typo bot is currently far too noisy. Going to try and ignore js/ts files in the hope it can quiet down.
=> Ignore JS files with typo bot

www/redirects.yaml
different pages are shown with and without trailing slashes
- no redirect:
`https://www.gatsbyjs.org/docs/themes/getting-started/` ([link](https://www.gatsbyjs.org/docs/themes/getting-started/))
it is a valid page
- redirect:
from: `https://www.gatsbyjs.org/docs/themes/getting-started` ([link](https://www.gatsbyjs.org/docs/themes/getting-started))
to: `https://www.gatsbyjs.org/docs/themes/using-a-gatsby-theme/`
- fixes #21480 `chore(docs): obsolete redirects of themes/getting-started`
=> fix(docs): fix obsolete redirects of themes/getting-started

docs/docs/testing-components-with-graphql.md
Missing line in example code: import { StaticQuery } from "gatsby"
I added a missing line to the example code.
```import { StaticQuery } from "gatsby"```
=> Update doc, missing line in example code

docs/docs/gatsby-internals-terminology.md
The links to GitHub in the docs in the internals `page.context` section 404: https://www.gatsbyjs.org/docs/gatsby-internals-terminology/#pagecontext 
This updates the links to point to the current code.
This is an update to the docs.
None.
=> fix(doc): Internal page-context links to code 404

docs/contributing/gatsby-style-guide.md
This PR introduces a policy in the contributing docs of .org for referencing and pointing to Gatsby Cloud uses.
With this set we can begin to add Gatsby Cloud as a technology solution in the OSS docs.
=> Add policy for gatsby cloud references in OSS

docs/blog/100days/accessibility/index.md
GitHub doesn't like #21486 so recreating it in the hopes we can get it merged.
=> redo this PR to bypass github issue

packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap, packages/gatsby/src/query/__tests__/file-parser.js, packages/gatsby/src/query/file-parser.js
Before this PR following component would have caused an error during static query parsing:
```js
import { graphql, useStaticQuery } from 'gatsby'
export { Bar } from 'bar'
export default () => {
const data = useStaticQuery(graphql`query StaticQueryName { foo }`);
return <div>{data.doo}</div>;
}
```
This was happening because of the presence of `export { Bar } from 'bar'` which was treated incorrectly while trying to follow static query variable chain
This issue was introduced in #20330
Fixes #21212
=> fix(gatsby): Fix static query parsing for for a special case

packages/gatsby-plugin-sass/README.md
#21062  Description
Removing brackets in documentation surrounded import statement
`import("./src/index.scss")` to `import "./src/index.scss".`
Fixes webpack build error.
=> Updating README.md - importing index.scss

.eslintrc.js
Before eslint would complain about calling a function from another function if the called function appeared later in the file:
```
function f() { g() }
function g() {}
```
Requiring that the order is reversed. However, in JS that doesn't really matter and should be fine to do. In TS that doesn't seem to be different so it's fine to relax the rule to ignore functions. (Note that this rule is entirely disabled for JS files)
=> feat(gatsby): Tweak eslint not to emit no-use-before-define on funcs

docs/contributing/translation/maintainers.md, docs/contributing/translation/new-translations.md, docs/contributing/translation/translators.md
- apply redirects
- fix 404
- #21254 `(docs) Split translation guide into multiple pages for clarity`
=> fix(docs): fix 404 and apply redirects

packages/gatsby-design-tokens/src/fonts.js
Intermediate step needed to replace the system font stack with excellent [Inter](https://rsms.me/inter/) (for .com, the Gatsby Cloud dashboard). Why?
- consistency across/control of the experience across all platforms (not least, a consistent set of font weights)
- improve typography for users on Windows (and replace Segoe, which has problems) and Android (Roboto, also has problems)
- potentially benefit from specific typeface features that Inter provides (tabular numbers, case alternates, stylistic sets 1 (alternate digits) and 2 (disambiguation))
- great language support
- variable font available
- drop-in replacement for at least Apple's San Francisco
- open source
---
Along the way: Fix `fonts.sans` and `.brand` aliases.
=> feat(gatsby-design-tokens): Add "Inter" font stack

scripts/check-ts.js
Before this PR TypeScript check output on windows was:
```
$ node ./scripts/check-ts
TS Check: Running...
TS Check: Checking ./packages/undefined
TS Check: Checking ./packages/undefined
TS Check: Success
```
Note the `undefined`. After this PR:
```
$ node ./scripts/check-ts
TS Check: Running...
TS Check: Checking ./packages/gatsby
TS Check: Checking ./packages/gatsby-cli
TS Check: Success
```
=> chore(gatsby): Fix minor bug with ts check output for Windows

www/src/data/sidebars/contributing-links.yaml
TOC is not selected with a link with a trailing slash `/`
- fixes #21604 `docs: redirect not select TOC`
- #21254 `(docs) Split translation guide into multiple pages for clarity`
- #21413 `add redirect for translation guide refactor`
=> fix(docs): links are not selected in TOC

docs/starters.yml
`gatsby-starter-monolith` can't be found any more:
https://github.com/danspratling/gatsby-starter-monolith
Remove it so that it doesn't break the build of gatsbyjs.org
@danspratling, if this is a mistake, please let us know.
=> fix(www): Fix dot-org build by removing missing starter

packages/gatsby-plugin-manifest/README.md
- Added missing punctuation, words, and fixed phrasing.
- Made hyperlinks more semantic (https://www.gatsbyjs.org/contributing/gatsby-style-guide/#use-clear-hyperlinks).
- Fixed abbreviations and terms that weren't spelled correctly (https://www.gatsbyjs.org/contributing/gatsby-style-guide/#abbreviate-terms).
- Replaced hyphens with em dashes wherever appropriate.
- Few, careful stylistic changes (text formatting).
I made all changes in accordance with the guidelines at https://www.gatsbyjs.org/contributing/gatsby-style-guide/ and https://www.thepunctuationguide.com/ and to the best of my knowledge. I also compared to how other plugins’ README files and the official Gatsby docs are written.
Since I'm not a native speaker though, there may be some errors, so I'd be glad if you point out …
=> docs(gatsby-plugin-manifest): Fixing gatsby-plugin-manifest README

packages/gatsby-source-contentful/README.md, packages/gatsby-source-contentful/package.json, packages/gatsby-source-contentful/src/__tests__/normalize.js, packages/gatsby-source-contentful/src/__tests__/plugin-options.js, packages/gatsby-source-contentful/src/__tests__/rich-text.js, packages/gatsby-source-contentful/src/gatsby-node.js, packages/gatsby-source-contentful/src/normalize.js, packages/gatsby-source-contentful/src/plugin-options.js, packages/gatsby-source-contentful/src/rich-text.js, yarn.lock
When rich-text fields reference an entry or asset, the fields of the entry or asset don't have their locales resolved like the rest of the GraphQL response.
For example, consider the following GraphQL query:
```graphql
{
contentfulArticle(slug: { eq: "my-article" }, node_locale: { eq: "en-US" }) {
title
bodyRichText {
json
}
}
}
```
The response will look like this: 
```javascript
{
contentfulArticle: {
title: 'My article',
bodyRichText: {
json: {
content: [
{
nodeType: 'embedded-entry-block',
data: {
target: {
fields: {
title: {
'en-US': 'My other article',
'de-DE': 'Meine andere Artikel'
}
}
}
}
}
]
} 
}
}
}
```
Note that, while the title of the outer article has a resolved locale — that is, the `title` property is simply the title string in the requested locale — the title of the inner …
=> feat: add an option to resolve locales in entries referenced by rich text

packages/gatsby-source-contentful/src/normalize.js
If someone doesn't have a `richText` setting in their `gatsby-config`, this extension breaks, complaining that it can't access `resolveFieldLocales` on `undefined`.
It looks like the `default` Joi option used in `plugin-options` isn't working. I've created this hotfix to get around that issue.
`packages/gatsby-source-contentful/README.md`
=> fix: check that richTextOptions exists before using it

packages/gatsby-transformer-asciidoc/src/gatsby-node.js
Added `base_dir` convert [option](https://asciidoctor-docs.netlify.com/asciidoctor.js/processor/convert-options/) for [asciidoc.js](https://asciidoctor-docs.netlify.com/asciidoctor.js/).
This enables the use of asciidoc includes `include::folder/_doc-to-include.adoc[]`when used in combination with unsafe.
```
{
resolve: 'gatsby-transformer-asciidoc',
options: {
safe: 'unsafe'
}
},
```
The resulting document will have the included document's content embedded instead of a link.
=> fix: Allow include in asciidoc

packages/gatsby-source-contentful/src/__tests__/fetch.js, packages/gatsby-source-contentful/src/fetch.js
Panics when a user defined configuration causes no locales to be found from Contentful.  When no locales are found the gatsby-source-contentful plugin is unable to build any default content model fragments and causes GraphQL errors to be thrown. 
https://github.com/gatsbyjs/gatsby/issues/21651
=> fix(gatsby-source-contentful): Add panic messaging to builds with no locales

docs/docs/testing-components-with-graphql.md
Fix the indentation of GraphQL queries on the component testing page to match the 2 space indentation of other code.
This is an update to the documentation.
None.
=> fix(docs): GraphQL query indentation

docs/contributing/pair-programming.md
Created a google form for registering pairing sessions instead of a calendly link. I've created a gatsby-dev alias in case we want to change our workflow. `https://gatsby.dev/pair-programming` was taken so I'm using `https://gatsby.dev/register-pair-programming`. Happy to change it to something else.
Gatsby members will see a notification in slack
**I'm marking as draft to get some feedback first.**
=> feat(www): update pairing session

packages/gatsby-theme-notes/package.json, packages/gatsby-theme-notes/src/gatsby-plugin-theme-ui/colors.js, packages/gatsby-theme-notes/src/gatsby-plugin-theme-ui/components.js, packages/gatsby-theme-notes/src/gatsby-plugin-theme-ui/index.js, packages/gatsby-theme-notes/src/gatsby-plugin-theme-ui/prism.js, packages/gatsby-theme-notes/src/gatsby-plugin-theme-ui/styles.js, packages/gatsby-theme-notes/src/gatsby-plugin-theme-ui/typography.js
…use in markdown
This PR improves the styling and functionality available for the notes theme. It also resolves #20992.
=> fix(gatsby-theme-notes): fix styling clash with gatsby-theme-blog

packages/gatsby-theme-blog-core/README.md, packages/gatsby-theme-blog-core/gatsby-config.js, packages/gatsby-theme-blog/README.md, packages/gatsby-theme-notes/README.md, packages/gatsby-theme-notes/gatsby-config.js
Currently, the `mdx` flag is confusing as a configuration setting. It's meant to prevent multiple plugins from attempting to configure MDX on the same site.
My proposal is to change the key name to `mdxOtherwiseConfigured` and set it to `false` by default. Users can explicitly set it to `true` if they need to and the READMEs reflect that.
The reason I opted for this instead of `configureMdx` with a default to `true` is that users who anticipate only using `.md` files may misunderstand the flag. This implementation should prevent that confusion.
=> feat: Change mdx flag into mdxOtherwise to prevent confusion

docs/sites.yml
Adds [www.chrisvogt.me](https://www.chrisvogt.me) to the GatsbyJS showcase.
I'm curious to see what your screenshot captures because I use [`react-visibility-sensor`](https://www.npmjs.com/package/react-visibility-sensor) to only render images when visible in the viewport. 🤞 
Thank you! 🙏
=> chore(showcase): add chrisvogt.me to the site showcase list

www/package.json
The already included GraphiQL is superior to GraphQL playground, so there's no reason to use that.
=> fix(www): Remove GraphQL playground

docs/starters.yml
There was some weirdness with a PR that appeared to include an existing starter entry unintentionally. It has now been merged and that site appears twice. This PR removes the duplicate.
=> Remove duplicate entry in starters

packages/gatsby-source-wordpress/README.md
Adding Polylang Pro to the WordPress Plugin list in gatsby-source-wordpress README.md: https://github.com/dannyvaughton/wp-rest-polylang-pro
This plugin adds translation support for posts & taxonomies for Polylang Pro users (unlike the existing wp-rest-polylang plugin).
=> docs(gatsby-source-wordpress): Add wp-rest-polylang-pro plugin to readme

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_translation.md, .github/ISSUE_TEMPLATE/question.md
Add labels to github issue templates. Cause what's the point of templates if you don't label 'em?
Github docs: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> chore: add labels to github issue templates

.circleci/config.yml
- Make windows unit tests run the same command as the node8 unit tests
- This means the windows tests no longer runs the linting etc
=> chore(gatsby): Skip linting in the windows ci step

packages/gatsby-plugin-netlify/src/__tests__/__snapshots__/build-headers-program.js.snap, packages/gatsby-plugin-netlify/src/__tests__/build-headers-program.js, packages/gatsby-plugin-netlify/src/build-headers-program.js, packages/gatsby-plugin-netlify/src/constants.js
Improve netlify headers by adding page-data & app-data to HTTP preload, this will let the browser start the download sooner.
It works :) You can see the difference in these snapshots, the important part is when our images start to load. As these are our indicators when our js is being executed.
**Mobile 4G**:
https://webpagetest.org/video/compare.php?tests=200224_T2_3323f0e578a9efc861f44ddcd2bd4250%2C200224_F2_68e33c289ced2e9c826d9617f4e8f18a&thumbSize=200&ival=100&end=full
**Desktop 4G**:
https://webpagetest.org/video/compare.php?tests=200224_DW_f3516a43d45095def0edab713dd22f73%2C200224_8C_75beb58838faed97672a522b7b21458b&thumbSize=200&ival=100&end=full
**Desktop fast internet**:
https://webpagetest.org/video/compare.php?tests=200224_MV_a147387f2c846b1685f05bc407ef5ac7%2C200224_MT_d1b1094 …
=> fix(gatsby-plugin-netlify): add page-data & app-data to preload list

docs/docs/creating-and-modifying-pages.md
In the **Note**, it was said that path shouldn't be a property in the context object.
=> chore(docs): Change path to pagePath

docs/sites.yml
Add https://trolleytravel.org in the showcase list. Followed instructions from https://www.gatsbyjs.org/contributing/site-showcase-submissions/
None - See https://www.gatsbyjs.org/contributing/site-showcase-submissions/
None
=> Add trolleytravel.org to the showcase

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
This fixes the benchmarks which currently assume `gatsby` is available in `$PATH` which is not always the case. So instead the benchmarks are now assumed to run from `node_modules/.bin/gatsby`, which should be true for our own benchmarks (which is what this plugin is targeting in the first place).
It also fixes the unnecessary cli output problem which was triggered by calling `webpack --version` without a global webpack installation. Reading from `node_modules` should be fine.
=> chore(gatsby-plugin-benchmark-reporter): Read versions from node_modules

packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap, packages/gatsby/src/redux/__tests__/index.js, packages/gatsby/src/redux/persist.ts, packages/gatsby/src/redux/types.ts
We are using `v8.serialize` to write and read the redux state. This is faster than `JSON.parse`. Unfortunately, as reported in #17233, this can lead to a fatal when the contents of the redux state is too big to be serialized to a Buffer (hard max of 2GB). Alternatively, we also hit this problem on large site like a million small md pages.
The solution is to shard the `nodes` property, which holds all the page data. In this change I've added a simple heuristic to determine the max chunk size (mind you, currently that's basically `Infinity`). It will serialize about 11 individual nodes, measure their size, and based on the biggest node determine how many nodes would fit in 1.5GB.
The serialization process is updated to no longer put the `nodes` in the main redux file, but rather sharded …
=> fix(gatsby): Chunk nodes when serializing redux to prevent OOM

packages/gatsby-plugin-catch-links/README.md
It was corrected because it did not exist id.
=> chore(docs): fix url fragment of link in gatsby-plugin-catch-links README

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_translation.md, .github/ISSUE_TEMPLATE/question.md
Well, apparently GitHub thought that yaml lists are too cool for them and decided labels should be a comma separated list.
=> fix(.github): try to fix issue template labels

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
It seems `gatsby-cli` isn't installed in all repo's explicitly so the change to use `require('gatsby-cli/package.json').version` fails in some cases. So instead let's use `node_modules/.bin/gatsby --version`.
=> fix(gatsby-plugin-benchmark-reporting): Read gatsby-cli version from n_m

docs/docs/sourcing-from-woocommerce.md, www/src/data/sidebars/doc-links.yaml
There's a lot of work being done on the WP source plugin but a lot of visitors to the site are requesting information on WooCommerce specifically. I'm proposing this as a sort of in-between to at least point people in the right direction while that work is being done. This guide presents some options for working with WordPress and WooCommerce.
I went back and forth about including some more Woo-specific instructions (things done in the dashboard). Thoughts on whether I should I add that back in?
Addresses #20222
=> (docs): Reference guide for using WooCommerce

starters/README-template.md
This PR adds ZEIT Now to the template README, allowing a deployment button to be generated for Gatsby starters.
=> chore(starters): Add ZEIT Now Deployment badge

packages/gatsby-source-contentful/src/gatsby-node.js
This prevents an issues during the `sourceNodes` lifecycle when an entry has been unpublished. Specifically, without `touchNode`, the `typeOwners` entry for these nodes can be `undefined`, which can prevent all Contentful graphql queries from working.
The initial symptom is:
```
"gatsby-source-contentful" threw an error while running the sourceNodes lifecycle:
The plugin "gatsby-source-contentful" deleted a node of a type owned by another plugin.
The node type "ContentfulBlogPost" is owned by "undefined".
```
But also, before this change, all the GraphQL queries related to Contentful go missing in the unpublished-entry scenario. This has even more negative implications in the case of TypeScript, when the available queries are used to generate types, such that even non-Contentful …
=> fix(gatsby-source-contentful): prevent unpublished Contentful entries from breaking content sync

starters/blog/gatsby-config.js, starters/blog/src/components/bio.js, starters/blog/src/components/seo.js
The blog starter template is a great way to have a blog site up and running, but while most of the stuff can be configured from the `gatsby-config.js` file, the author summary is missing and is hardcoded in `src/components/bio.js`.
Fixes  #21747
=> fix(gatsby-starter-blog): Move hardcoded author summary to site metadata (#21747)

packages/gatsby-transformer-sharp/src/create-resolvers.js, packages/gatsby-transformer-sharp/src/on-node-create.js, packages/gatsby-transformer-sharp/src/supported-extensions.js
This PR fixes a recent regression introduced in https://github.com/gatsbyjs/gatsby/pull/20782, where a mix of `import` and `require` caused file extension warnings (e.g. `You can't use childImageSharp together with x.png — use publicURL instead. The childImageSharp portion of the query in this file`).
Fixed https://github.com/gatsbyjs/gatsby/issues/21776
I would love to introduce more safety nets in the code to avoid this problem in the future. Any plans to embrace TypeScript? Or limit the mix of `import`, `default export`, `export`, `module.exports` and `require` (this could be done using eslint)?
=> fix(gatsby-transformer-sharp) remove default export

docs/docs/glossary/static-site-generator.md
- fix 404
- fix broken links and changed links to main glossary
- #20824 `Add glossary/static-site-generator entry.`
=> fix(docs): 404 on static site generator

docs/sites.yml
This adds the recently relaunched [Marathon Oil](https://www.marathonoil.com) website to the site showcase.
=> chore(showcase):Add Marathon Oil to the Site Showcase

docs/starters.yml
Fix builds crashing due to not finding a starter:
Error getting repo data for starter “gatsby-starter-auth-aws-amplify”: Could not resolve to a User with the username ‘ben-siewert’.: {“response”:{“data”:{“repository”:null},“errors”:[{“type”:“NOT_FOUND”,“path”:[“repository”],“locations”:[{“line”:3,“column”:15}],“message”:“Could not resolve to a User with the username ‘ben-siewert’.“}],“status”:200},“request”:{“query”:“\n query {\n repository(owner:\“ben-siewert\“, name:\“gatsby-starter-auth-aws-amplify\“) {\n name\n stargazers {\n totalCount\n }\n createdAt\n pushedAt\n owner {\n login\n }\n nameWithOwner\n }\n }\n “}}
=> fix(www): Remove crashing starter

docs/sites.yml
I noticed danger bot was picking up an error in a category tag for another PR. Which was causing an error so I fixed it 
#21817
=> chore(showcase):Remove category causing danger bot error for showcase

benchmarks/README.md, benchmarks/create-pages/README.md, benchmarks/image-processing/README.md, benchmarks/markdown_id/README.md, benchmarks/markdown_slug/README.md, benchmarks/markdown_table/README.md, benchmarks/query/README.md, benchmarks/query/recording.md, docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/index.md, docs/docs/creating-a-local-plugin.md, docs/docs/gatsby-project-structure.md, docs/docs/graphql-concepts.md, docs/docs/loading-plugins-from-your-local-plugins-folder.md, docs/docs/recipes/pages-layouts.md, examples/styleguide/src/components/Button/README.md, examples/using-MDX/README.md, packages/gatsby-source-contentful/README.md
fixed in code blocks:
- add missing language marker
- changed some language marker `sh` and `bash` to `shell` -> to unify it in one readme 
- add missing language marker `text` to directory trees 
- prettier tool done some automatic reformatting while syntax change
=> chore(doc):add or fix syntax highlight language

packages/gatsby-transformer-sqip/src/extend-node-type.js
I wondered why my projects stopped to output the SQIP generated previews.
This one line change fixes it, as the plugin was just checking the file type in the wrong way.
=> fix(gatsby-transformer-sqip): properly check for correct input file type

www/src/utils/styles/global.js
This PR adds some styles to how Prism renders empty lines so that our code blocks are more readable.
Here's how it looks on the left, compared to what .org shows on the right:
The code blocks in the docs have newlines so clicking the copy button accurately copies the code with line breaks preserved, but when rendered there is an element created by Prism with no content inside. By giving it a minimum height and updating it's display property it pushes the content below it down to display like the code is represented in reality.
None (that I know of), noticed this problem a while ago
=> www(fix): update line height for newlines in code blocks

scripts/i18n/pages.json
Update the list of core docs for translation.
* recipes has been split up into multiple files
* added API files, which are all now .md files and can be translated (though content in jsdoc still cannot be translated)
=> chore(scripts): update the list of core pages for translation

www/plugins/gatsby-plugin-i18n/gatsby-node.js
- add declaration to field in for/in loop
- i did see approximately the same amount of `let` vs `const` in code base, but since the value is not changed i decided for `const`
- #21632 `feature(www): Create localized versions of all pages`
=> fix(www): add declaration to field in for/in loop

docs/docs/caching.md
Remove a prettier-ignore comment that was somehow interpreted wrong by our mdx parser. The content was originally ignored because it was ugly when formatted, but we're trying to restructure the content anyways so it shouldn't matter that much.
=> fix(www): remove prettier ignore comment causing MDX parsing error

docs/sites.yml
Removing Gratsy from showcases since it was moved to somewhere else (not because Gatsby JS, we love it, but because other business reasons).
Related to #16558
=> chore(showcase): Remove Gratsy

www/src/views/showcase/featured-sites.js
The same icon was imported twice with a different name.
=> fix(www): cleanup "ArrowForwardIcon" imports

packages/gatsby-plugin-preload-fonts/README.md
A hint, that Puppeteer can be configured with environment variables, which is required in some configurations (e.g. Alpine Linux)
fixes #21778
=> docs(gatsby-plugin-preload-fonts): add external chrome env var

packages/gatsby-plugin-emotion/package.json
This is for yarn-pnp compatibility.  Without `@babel/core` listed as a peer dependency, yarn will be unable to build.
No related issues, as of right now.
=> chore(gatsby-plugin-emotion): add @babel/core as peer dependency for pnp

packages/gatsby/index.d.ts
Once I started using shared fragments, all the auto-generate types tooling broke, so I went manual. 
I started using this type in TypeScript v2 and figured it'd be better that I give it to Gatsby instead. Effectively gives people a base type to build on top of for describing the data in their 
This is how I define my types which have both a query and custom context from `createPage`.
( and yah yah, `lang` vs `langKey` - I couldn't find docs on `langKey` so I just used my own everywhere) 
When there's official TS docs, this should go in as a way to describe your own props - I included a bunch of examples inline which you can copy & paste later
I do not know what these are/do:
- `"*"` could be on the props, but I included it because it was on the older one (it doesn't show up in any of my …
=> Offer a base Page props type which folks can extend

packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap, packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
This creates a new node type `SiteBuildTime`, with one node that includes a `buildTime` field. It then replaces the buildTime field on `Site` with a resolver that returns the value from the `SiteBuildTime` node. This prevents changes to buildTime affecting the Site node contentDigest, which would mark any page that uses siteMetadata as dirty.
Based on discussion https://github.com/gatsbyjs/gatsby/pull/21795#issuecomment-591979862
Replaces #21795
=> Move buildTime into new node type

benchmarks/image-processing/README.md
images added in: 
- #21283 `Add more images to benchmark from Open Images Dataset`
- #21283 `Add more images to benchmark from Open Images Dataset`
=> fix(benchmark/readme): adjust images count

packages/gatsby-plugin-subfont/README.md, packages/gatsby-plugin-subfont/package.json, packages/gatsby-plugin-subfont/src/gatsby-node.js
Add gatsby-plugin-subfont configurable option feature
Update subfont version (Maybe issue #16840?)
see: packages/gatsby-plugin-subfont/README.md
Related to #16840
=> feat(gatsby-plugin-subfont): Make async, add configurable option

packages/gatsby/src/schema/schema.js, packages/gatsby/src/utils/api-node-docs.js
Useful for theme authors who want to extend plugin types if they exist.
I updated the jsdoc comments
I also did not see any tests for createResolvers otherwise I would have written one
=> feat(gatsby): Allow silencing the warning for adding resolvers for missing types

packages/gatsby/src/query/query-runner.js
See context in #21838 
I tested this change locally by just updating Gatsby in node_modules. It worked!
--
Note: I tried using optional chaining but I had issues so I just went with good ol' `&&`
#21838
=> fix(gatsby): Check for nullable locations in query-runner

packages/gatsby/cache-dir/loader.js, packages/gatsby/cache-dir/navigation.js
When page-data.json results in a 500 or when we can't fetch a component we've hit some js errors instead of our own. So now we are actually throwing gatsby errors and error trackers make more sense.
**Before:**
- When component can't be loaded we had: `TypeError: e.components[t] is not a function` and loaded the 404 page.
- when page-data results in 500 we had: `TypeError: Cannot read property 'webpackCompilationHash' of undefined` and refresh the page.
**After:**
- When component can't be loaded we have: `Error: page resources for /stale/ not found. Not rendering React` and loaded the 404 page.
- when page-data results in 500 we have: `Error: page resources for /new-beginnings/ not found. Not rendering React' of undefined` and refresh the page. …
=> fix(gatsby): fix codepaths that result in js errors

packages/gatsby-plugin-mdx/gatsby/source-nodes.js, packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js, packages/gatsby-plugin-mdx/utils/interop-default.js
This PR fixes an issue where plugins that have `default` exports are not required properly by `gatsby-plugin-mdx`.  I had this problem with my own plugin which is written in ES6 - and Babel transpiles it to have `exports.default`.
To check :
1. Clone an mdx starter
```gatsby new my-mdx-starter https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic```
2. Install `gatsby-remark-shiki` (my plugin with default exports) and add `gatsby-remark-shiki` to `gatsbyRemarkPlugins` of `gatsby-plugin-mdx` config in `gatsby-config.js`:
```
{
resolve: `gatsby-plugin-mdx`,
options: {
gatsbyRemarkPlugins: ["gatsby-remark-shiki"],
defaultLayouts: { default: path.resolve("./src/components/layout.js") }
}
},
```
3. Run `gatsby-dev --packages gatsby-plugin-mdx` in gatsby repo with this branch checked …
=> fix:(gatsby-plugin-mdx) Require a default export when needed

docs/starters.yml, www/src/utils/node/starters.js
Should fix failing starters when a GitHub rename has happened.
Some extra context, the GitHub API doesn't follow GitHub username renames, it will throw a NOT FOUND error. When this happens we try to follow the redirect by doing a head request and retry our query. When only try this once per repo, if we fail the second time, we fail hard but that should only happen because of GitHub.
We should occasionally check our build pipeline to rename starters.
Fixes https://github.com/gatsbyjs/gatsby/issues/21813
=> fix(www): fallback to github renamed owner (starters)

www/src/data/sidebars/doc-links.yaml
unify all links and add trailing slashes
=> fix(docs): add trainling slashes to doc-links.yaml

packages/gatsby/src/schema/schema.js
This PR improves a warning message that is shown when some plugin is trying to override/extend built-in GraphQL types using schema customization APIs.
Before this PR the warning looks like this:
```
Plugin `bad-plugin` tried to define the GraphQL type `File`, which has already been defined by the plugin `null`
```
After this PR it looks like this:
```
Plugin `bad-plugin` tried to define built-in Gatsby GraphQL type `File`
```
We introduced built-in GraphQL types here: #19951
#21673
#21636
=> fix(gatsby): Improve warning for built-in GraphQL type overrides

docs/features/gatsby-features-specs.csv, www/src/components/features/simple-evaluation-table.js
add a description to the overview of features table to show up when clicked
Fixes [#21247](https://github.com/gatsbyjs/gatsby/issues/21247)
=> chore(www): adds a description to the overview of features

packages/gatsby/src/utils/get-ssl-cert.js
This is super hacky hot fix for `gatsby develop` in environments that don't have `process.env.HOME` set, as `devcert` relies on those right now to be set (otherwise just importing `devcert` cause fatal error)
/cc @benrobertsonio
=> fix: hot fix for `gatsby develop` when HOME is not set

www/src/views/starter-library/filtered-starters.js
Fixes #21916 
The problem was caused by #21792 which simplified node access. It inadvertedly forgot one case of `edge` (how''d that happen?) which got fixed in #21792 but that did not fix the "unboxing" of the edge, leading to an unguarded property access on `undefined`.
Also refactored a few things. See middle commit for the meat.
=> fix(gatsby/www): Tried to unbox an edge but it is already a node

packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
https://github.com/gatsbyjs/gatsby/pull/21523 wasn't synced with master in quite some time and didn't have some changes to tests done in meantime, so it broke some snapshot assertions.
This syncs snapshot.
=> test: fix snapshot after merging #21523

packages/gatsby/src/schema/resolvers.js
This PR fixes a performance issue with resolving of linked interface fields. We've discovered that 
```graphql
type Foo {
bar: [InterfaceType] @link(by: "id", from: "bar___NODE")
}
```
Is much slower than 
```graphql
type Foo {
bar: [ObjectType] @link(by: "id", from: "bar___NODE")
}
```
We had a special path for interfaces which was introduced in #17942
But this doesn't seem necessary anymore. Tests are passing without it. Tried this PR on a local project with schema customization. It gave a 10x speed increase for this kind of query.
N/A - this is a performance fix
=> fix(gatsby): Resolve linked interfaces consistently with object and union types

www/src/views/starter-library/filtered-starters.js
The `starters` array used to be an array of edges and is "now" an array of nodes so accessing `.node` is no longer necessary. So dropping the access should make it work again.
Fixes #21942
Bug was introduced by #21792
=> fix(www): starter is already a node

docs/blog/2019-04-19-gatsby-why-we-write/index.md
That tweet is no longer available - https://twitter.com/mattconvente/status/1099706762897342465 - trying to handle this break builds currently
=> fix(blog): remove tweet that is no longer available

rfcs/typescript-refactor.md
[Rendered RFC](https://github.com/gatsbyjs/gatsby/blob/8f9e722e2fb073b83b006408ba3e061d6a379ca2/rfcs/typescript-refactor.md)
=> [RFC] TypeScript Refactor

packages/gatsby/src/redux/persist.ts
Loki does not use the nodes at all so it would invalide the cache by default. That wasn't the intention.
=> fix(gatsby): Prevent cache  invalidation case for loki

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Add some data sent to the reporting url via pluginOptions / env
These values are used internally so I didnt add them to the docs
=> feat(gatsby-plugin-benchmark-reporting): Add more fields to the report

packages/babel-plugin-remove-graphql-queries/tsconfig.json, packages/babel-preset-gatsby-package/tsconfig.json, packages/babel-preset-gatsby/tsconfig.json, packages/gatsby-core-utils/tsconfig.json, packages/gatsby-image/tsconfig.json, packages/gatsby-link/tsconfig.json, packages/gatsby-page-utils/tsconfig.json, packages/gatsby-react-router-scroll/tsconfig.json, packages/gatsby-telemetry/tsconfig.json, scripts/check-ts.js
From the recent RFC #21798 that was merged, we have defined the core packages that we are interested in converting to TypeScript. 
This PR just sets up the infrastructure for each of those packages so as we start getting community contributions they do not have to fight with tooling.
The change to the script is to make sure we don't invoke `tsc` if a package doesn't have `.ts` files. Which is the case for many packages after this PR. So this is a safe-guard to let us set up the tsconfig.json without crashing `yarn typecheck`
=> chore: Ts/setup typescript for all

packages/gatsby-theme-blog/README.md
Adds more installation instructions for the existing site section regarding the usage of the avatar image located in the defined assets directory that then renders in every post's post footer.
Fixes #21985
=> docs(gatsbt-theme-blog): add instructions on avatar image

packages/gatsby-core-utils/package.json
This file now depends on `configstore`, so the dependency needs to be defined:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/get-config-store.js
Cf a failing test here:
https://github.com/yarnpkg/berry/runs/490908199
=> Adds a missing dependency on `configstore`

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
There was a clash with the variable name `incomingHookBody` that made the JSON.parse fail.
=> Fix variable names

packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js, packages/gatsby-plugin-typescript/src/gatsby-node.js
Support Webpacks's rule.loader shortcut syntax in typescript plugin
[Module | webpack](https://webpack.js.org/configuration/module/#ruleloader)
Fixes #22002
=> fix(gatsby-plugin-typescript): Broader webpack support

packages/gatsby/src/commands/build-javascript.ts, packages/gatsby/src/commands/build.js
Port src/commands/build-javascript.js to TypeScript
=> chore(gatsby): Port build-javascript to TypeScript

packages/gatsby/src/commands/repl.ts, packages/gatsby/src/redux/types.ts
=> chore(gatsby): Convert repl to typescript

packages/gatsby-cli/src/reporter/loggers/ink/cli.js, packages/gatsby-cli/src/reporter/loggers/ink/components/error.js, packages/gatsby-cli/src/reporter/loggers/ink/components/messages.js
This was tested on https://github.com/pieh/ink-stress-test/blob/master/gatsby-node.js
and it dropped from ~5-6s to ~1s locally
There is more we can do for CLI perf - particularly we do use development react build, which has additional perf overhead. (tho with those changes impact is greatly minimilized - at least for my testing sample https://github.com/pieh/ink-stress-test)
=> perf(gatsby-cli): avoid unnecesary rerenders for static messages in CLI

packages/gatsby-remark-copy-linked-files/src/__tests__/index.js, packages/gatsby-remark-copy-linked-files/src/index.js
Currently `gatsby-remark-copy-linked-files` doesn't support copy of video posters. This PR add support by parsing "poster" attribute in video tags. Results in copy of poster image when "poster" attribute is specified in video element.
Also I've added `isRequired` field in argument object of `processUrl` function. It's necessary because this plugin ussually ignores image extensions (which video paster has) and allow `gatsby-remark-images` plugin to handle them. But `gatsby-remark-images` plugin shouldn't handle video posters.
=> feat(gatsby-remark-copy-linked-files): Add support for poster attribute in video elements

docs/sites.yml
- Removed Cole Walker's Portfolio: Switched to Vue
- Removed SEOmonitor: Switched to Wordpress
- Removed het Groeiatelier: Switched to Webflow
- Removed GreenOrbit: Switched to Wordpress
- Removed Asjas Portfolio: Switched to Hugo
- Removed Raconteur Careers
- Removed Lusta Hair: Switched to Shopify
- Removed Bearer - Switched to Webflow
- Removed Tenon-UI Documentation - Site no longer online
- Removed source_url for Serverless: site repo no longer available
- Removed source_url for Daniel Spajic: site repo no longer available
=> chore(showcase): Site Showcase maintainence

packages/gatsby/src/bootstrap/index.js, packages/gatsby/src/utils/__tests__/browserslist.js, packages/gatsby/src/utils/browserslist.ts
Convert `utils/browserslist` to typescript
=> chore(gatsby): Convert utils/browserslist to typescript

packages/gatsby-cli/src/reporter/loggers/ink/cli.js, packages/gatsby-cli/src/reporter/loggers/ink/components/progress-bar.tsx, packages/gatsby-cli/src/util/calc-elapsed-time.js, packages/gatsby-cli/src/util/calc-elapsed-time.ts
Migrate `ProgressBar` component and `calc-elapsed-time` util in gatsby-cli to typescript.
#21995
=> chore(cli): migrate progress-bar to typescript

docs/docs/porting-from-create-react-app-to-gatsby.md
Adds MDN links to the common globals specified in https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/#server-side-rendering-and-browser-apis
Fixes https://github.com/gatsbyjs/gatsby/issues/20678
=> docs: Add MDN links to globals section of porting from CRA to Gatsby

packages/gatsby/src/commands/build.js, packages/gatsby/src/utils/app-data.ts
Convert `utils/app-data.js` to typescript
=> chore(gatsby): Convert src/utils/utils/app-data.js to typescript

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
=> feat(gatsby-plugin-benchmark-reporting): allow passing a secret to benchmark reporting endpoint

packages/gatsby/src/utils/__tests__/get-cache.ts, packages/gatsby/src/utils/api-runner-node.js, packages/gatsby/src/utils/get-cache.ts
Convert `utils/get-cache` to typescript
=> chore(gatsby): Migrate utils/get-cache.js to ts

.circleci/config.yml
- Update the CircleCI benchmarks to use necessary environment variables for benchmark runs
- `BENCHMARK_CONTENT_SOURCE`
- `BENCHMARK_REPO_NAME`
- `BENCHMARK_SITE_TYPE`
- Extract the benchmark run into a command
- Note a specific cold vs. warm environment variable in `BENCHMARK_BUILD_TYPE` for subsequent runs
I don't know how to test this. We wait and see if this works?
cc/ @nicholascapo
=> Update CircleCI benchmarks with new env variables

packages/gatsby-cli/.babelrc, packages/gatsby-cli/package.json
hotfix for `progress-bar` not being in the built output. The infrastructure was set up for `.ts` files, but not for `.tsx` files. Thus they were not being built and currently `gatsby-cli@2.10.3` does not work.
Related #22109
=> fix(gatsby-cli): Update build script to properly handle .tsx files

packages/gatsby-core-utils/src/get-config-store.ts
=> chore(gatsby-core-utils): get-config-store to TS

packages/gatsby-core-utils/src/cpu-core-count.ts
=> chore(gatsby-core-utils): cpu-core-count to TS

packages/gatsby-core-utils/src/path.ts, packages/gatsby/src/commands/build-javascript.ts, packages/gatsby/src/commands/build.js
=> chore(gatsby-core-utils): path to ts

packages/gatsby/src/redux/actions/public.js
This replaces a `_.uniq` with a `.includes` which is called `N` times, once for each node, while the array of nodes is building up (or on the full set even?). The only reason, I think, is to make sure the newly inserted child does not already exist in the array of children. The `includes` simply does a subset of things `uniq` does.
Another change is that a new array is no longer created; `parent.children` remains the same array reference after this step now.
Addresses a problem surfaced by @tsriram in #21447
Drops the `source and transform` step by about 33% at scale. This step in a benchmark of 100k pages drops from 30s to 20s, a 150k pages bench drops from 45s to 30s.
This is the long hanging fruit. There's still a lot of room for improvement.
=> perf(gatsby): more efficient parent-child check through arrays

packages/gatsby/index.d.ts
Hi, and thanks for a great project! This (my first) PR is just a small thing proposing an update to the typescript types. It should possibly be opened as an issue first, but since the changes are so small I thought it would be easiest to make it a PR directly – a PR which of course can be closed if I've misunderstood anything.
I propose updated types for the interfaces `WrapPageElementBrowserArgs` and `WrapPageElementNodeArgs` with a more detailed `props` definition. PR #21542 introduced a new detailed interface for page props and I figured this interface can also be used for the types for `wrapPageElement`.
I could of course be wrong ([the docs](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement) and [the current interface](https://github.com/gatsbyjs/gatsby/blob/509339f2aeecc261 …
=> fix(gatsby): Update types for WrapPageElement*Args

docs/starters.yml
This PR updates the URL listed for `gatsby-starter-tailwind` to the current one.
=> Fix URL for gatsby-starter-tailwind

packages/gatsby-source-contentful/src/gatsby-node.js
This touches the `gatsby-source-contentful` nodes indicated by the `localFile___NODE` identifier, so that in `GATSBY_CONTENTFUL_OFFLINE` mode, startup does not crash on attempting to infer GraphQL types for these files (see #21463).
I haven't yet added any tests - partly because I haven't found any for the rest of this file, and partly because I just wanted to validate this fix. Open to suggestions here on how other parts of the codebase are testing this *kind* of change.
In debugging, I found that in `gatsby-source-contentful/src/gatsby-node.js`, the `getNodes()` collection (called [here](https://github.com/gatsbyjs/gatsby/blob/f8b02b859fcc33d223f258349a2c42697773e939/packages/gatsby-source-contentful/src/gatsby-node.js#L52)) included the relevant nodes that went missing by the time the …
=> fix(gatsby-source-contentful): Don’t crash when GATSBY_CONTENTFUL_OFFLINE and downloadLocal are used

packages/gatsby-cli/README.md
Fixes relative link usage on README.md
Fixes #21720
=> Fix readme links

docs/docs/tailwind-css.md
added Twin docs for versions 1.0.0+ of Tailwind
Tailwindcss support for the CSS-in-JS macro `tailwind.macro` has depreciated, users of v1.0.0+ should use forked project Twin `twin.macro`
API is identical with some new features, future support for classes and soon to be released plugin support [Twin](https://github.com/ben-rogerson/twin.macro)
=> tailwind.macro has depreciated

packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js, packages/gatsby/src/utils/__tests__/path.ts, packages/gatsby/src/utils/path.ts, packages/gatsby/src/utils/webpack.config.js
Convert `utils/path` and test to typescript
=> chore(gatsby): Convert utils/path to typescript

packages/gatsby/src/commands/build-html.ts
=> Cleanup build-html

packages/gatsby-cli/src/index.ts, packages/gatsby-cli/src/util/ensure-windows-drive-letter-is-uppercase.ts
Convert `ensure-windows-drive-letter-is-uppercase` to typescript
=> chore(gatsby-cli): Convert ensure-windows-drive-letter-is-uppercase to typescript

packages/gatsby/src/schema/infer/add-inferred-fields.js, packages/gatsby/src/schema/infer/inference-metadata.js, packages/gatsby/src/schema/infer/is-32-bit-integer.js, packages/gatsby/src/schema/infer/is-32-bit-integer.ts, packages/gatsby/src/utils/__tests__/is-32-bit-integer.ts, packages/gatsby/src/utils/is-32-bit-integer.js, packages/gatsby/src/utils/is-32-bit-integer.ts
I converted two `is-32-bit-integer` to TypeScript.
- `utils/is-32-bit-integer`
- `schema/infer/is-32-bit-integer`
=> chore(gatsby): Convert is-32-bit-integer to TypeScript

packages/gatsby-cli/src/init-starter.ts
follow-up of  https://github.com/gatsbyjs/gatsby/pull/22086#discussion_r390360897
=> chore(gatsby-cli): Tweak init-starter types

docs/docs/cli-feedback.md, docs/docs/environment-variables.md
In looking at the new doc on [CLI Feedback](https://www.gatsbyjs.org/docs/cli-feedback/), I noticed it didn't follow the Gatsby Style Guide. I added a link to info about environment variables, and noticed that one had style guide issues as well. So this PR updates both of those docs to use the correct pronouns and improve some formatting.
N/A
N/A
=> Update Feedback/Env Var docs to follow style guide

packages/gatsby-dev-cli/src/__tests__/watch.js, packages/gatsby-dev-cli/src/watch.js
Themes aren't built/compiled like most packages in the gatsby monorepo so we shouldn't ignore their src directories. This now ensures that `gatsby-dev --packages gatsby-theme-blog` behaves as we'd expect.
~~**Note**: Right now the test is failing because the `gatsby/src` test is failing, I'd imagine because we're calling the add event directly which happens _after_ the watchers. So, in all reality then, my tests aren't actually testing anything. Is there some way to test this functionality that I'm missing?~~
**Edit**: We opted to not test here because it would require digging deeply into the chokidar mocking.
=> fix(gatsby-dev-cli): Include theme src directories

packages/gatsby-plugin-sharp/src/index.js
Looks like the latest release had a console.log left in it!
=> remove console log from gatsby-plugin-sharp

packages/gatsby-cli/src/create-cli.js, packages/gatsby-cli/src/init-starter.ts
In our recent TypeScript changes, we've been switching from `module.exports` to ES6 module syntax. The interop between those modules and commonjs `require` results in a different API (e.g., `require('foo').default`). 
In the future we will be more mindful of all importing modules when making these changes to avoid this.
Fixes #22157
=> fix(gatsby-cli): Fix an import change that broke `gatsby new`

packages/gatsby/src/commands/build.js, packages/gatsby/src/commands/develop.ts, packages/gatsby/src/commands/jobs-manager.ts, packages/gatsby/src/utils/commands/jobs-manager.ts
Extract duplicate `waitUntilAllJobsComplete` function out of `build` & `develop` command
=> refactor(gatsby): Extract waitUntilAllJobsComplete out of build and develop command

packages/gatsby/src/commands/build.js, packages/gatsby/src/commands/develop.ts, packages/gatsby/src/utils/wait-until-jobs-complete.ts
Based on feedback from @wardpeet in https://github.com/gatsbyjs/gatsby/pull/22059/files
=> chore(gatsby): Clean up file name and dir for wait-until-jobs-complete

starters/hello-world/package-lock.json
Update `@babel/helper-compilation-targets` dependency in order to work on `node v.13.10+` with the starter template `hello-world`, which is mentioned in the tutorial on Gatsby [tutorial](https://www.gatsbyjs.org/tutorial/part-zero/) page.
No particular documentation required for this fix.
#22145
=> fix(babel helper): fix version for compilation targets

docs/docs/running-a-gatsby-preview-server.md, www/src/data/sidebars/doc-links.yaml
Based on feedback from users, we need a docs page on Running a Gatsby Preview Server. It has been unclear for quite a while that there are multiple options–not totally limited to Gatsby Cloud–so this PR intends to put important details in a single place that users can find them.
cc @KyleAMathews 
N/A
Related to https://github.com/gatsbyjs/gatsby/issues/10328
=> [docs][guides] Running a Gatsby Preview Server

packages/gatsby/src/db/loki/nodes-query.js, packages/gatsby/src/redux/run-sift.js, packages/gatsby/src/schema/infer/is-file.js, packages/gatsby/src/schema/resolvers.js, packages/gatsby/src/utils/__tests__/get-value-at.ts, packages/gatsby/src/utils/get-value-at.ts
Convert `utils/get-value-at` and `__tests__/get-value-at` to Typescript
=> chore(gatsby) Convert get-value-at to typescript

packages/gatsby-plugin-sitemap/README.md, packages/gatsby-plugin-sitemap/src/__tests__/internals.js, packages/gatsby-plugin-sitemap/src/gatsby-node.js, packages/gatsby-plugin-sitemap/src/internals.js
Resolves some of the issues discussed in #20692.
- Previously when querying pages using `allSitePage.nodes` instead of `allSitePage.edges` was impossible because the serializer and internal page filter expected the edges object structure. 
- Previously you had to set your siteUrl at `site.siteMetaData.siteUrl` or the default resolver would fail. This seemed pointless when using other methods to resolve siteUrl. You can now define a function that receives the query result as "data", and you can return a string that will be used for siteUrl.
While this solution works there is a lot of "odd" things i had to do to make it backwards compatible. Specifically when filtering pages I convert the the data structure to an array of pages from either the `edges` or `nodes` structure. But it also still …
=> feat(gatsby-plugin-sitemap): handle different query structures and allow custom siteUrl resolution

packages/gatsby-plugin-mdx/loaders/mdx-scopes.js
Otherwise webpack will not rebuild when new scpoes is writed into cache. This can happen if you change mdx file when `gatsby develop`.
=> fix(gatsby-plugin-mdx): add context dependency to mdx-scopes loader

packages/gatsby-source-filesystem/src/utils.js
changed:
- fix doc parameter name
=> chore(gatsby-source-filesystem): fix jdoc

.gitignore
Removed `yarn.lock` from `.gitignore`
Fixes #22072
=> chore(gatsby): remove yarn.lock from gitignore

packages/gatsby-cli/package.json, packages/gatsby/package.json, packages/gatsby/src/redux/index.ts, yarn.lock
This is split from https://github.com/gatsbyjs/gatsby/pull/20727. That PR is blocked on other things (which https://github.com/gatsbyjs/gatsby/pull/22224 tries to solve).
This PR is mostly to make sure fixed renovate PR will not need any additional code changes
=> chore: bump redux

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap, packages/babel-plugin-remove-graphql-queries/src/index.js
I have some generated code (bucklescript/graphql_ppx) whereby the reference of the query is used in another data structure (which is also unused, but it is still referenced). So if this is removed from the code Gatsby won't build. I think removing this shouldn't need to happen in the babel plugin as it will happen anyway in the dead code removal of webpack (I believe).
=> fix: dont remove query declaration hash, terser will remove it anyway and it can be useful for 3rd party tools

packages/gatsby-source-drupal/src/gatsby-node.js
Adds a safety check for datum while creating nodes.
Fixes #22212
Fixes: https://www.drupal.org/project/gatsby/issues/3118764
=> fix(gatsby-source-drupal): Add safety check for existence of datum.

packages/gatsby/src/utils/__tests__/api-runner-error-parser.ts, packages/gatsby/src/utils/api-runner-error-parser.ts
- The `api-runner-node` assumes that `api-runner-error-parser` always returns something. (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/api-runner-node.js#L381-L411)
- That's not the case if the error is a string (as is the case for `gatsby-plugin-manifest`)
This makes `api-runner-error-parser` a bit more robust by returning a default error if we didn't manage to parse it.
I'll fix the `gatsby-plugin-manifest` in another PR
=> fix: ensure that errorParser always returns something

www/gatsby-node.js
Based on [Netlify's breaking change](https://community.netlify.com/t/changed-behavior-in-redirects/10084) we need existing redirects for .org to use the force flag. Behind the scenes in the netlify plugin this will set `!` on the redirect. Netlify previously treated redirects as forced by default and no longer will, resulting in this change being necessary.
=> fix(www): Netlify redirect rules require force

packages/gatsby-cli/src/structured-errors/error-map.ts
https://github.com/gatsbyjs/gatsby/pull/20597 renamed some field names for consistency with other errors, but this is dangerous because errorMap and error showing are in different packages which versions might drift, so we do need to add a bit of compat code (to fallback to previous fieldname if new one is undefined)
=> fix: make 11321 and 11330 error formatters backward compatible

packages/gatsby/src/commands/serve.ts
Convert `commands/serve` to typescript
=> chore(gatsby): Convert serve to typescript

packages/gatsby-core-utils/package.json
This is follow up to https://github.com/gatsbyjs/gatsby/pull/22143.
With `typegen` now being part of build, we do need `typescript` to get `tsc` in `node_modules/.bin`. Otherwise if system doesn't have global typescript installed it will fail to build the package - as example https://circleci.com/gh/gatsbyjs/gatsby/351790?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```shell
> gatsby-core-utils@1.0.33-dev-1584140132901 prepare .
> cross-env NODE_ENV=production npm run build && npm run typegen
> gatsby-core-utils@1.0.33-dev-1584140132901 build /home/circleci/project/packages/gatsby-core-utils
> babel src --out-dir dist/ --ignore **/__tests__ --ignore **/__mocks__ --extensions ".ts"
Successfully compiled 10 files with Babel.
> …
```
=> chore(gatsby-core-utils): add typescript as dev dependency

packages/gatsby-cli/src/util/version.ts
chore(gatsby-cli): Convert util/version to typescript
=> chore(gatsby-cli): Convert util/version to typescript

packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.js.snap, packages/gatsby/src/utils/__tests__/webpack-utils.js
This is meant to have snapshot assertion be more resilient to to node_modules hierarchy.
For example in https://github.com/gatsbyjs/gatsby/pull/20727 this test breaks because `babel-loader` lands in different spot. This will keep spirit of the test, just making sure that loader is a string containing `babel-loader`.
=> test: use property matcher to not rely on relative location of loader package

docs/categories.yml
Added the [Milligram](https://github.com/milligram/milligram) CSS framework to the `categories.yml`.
I used this framework for my gatsby [starter](https://github.com/masoudkarimif/gatsby-starter-clean-resume).
=> chore(categories): add Milligram 

packages/gatsby/src/redux/types.ts, packages/gatsby/src/utils/js-chunk-names.ts
I converted js-chunk-names to typescript
=> chore(gatsby): Convert js-chunk-names to typescript

packages/gatsby/src/utils/worker/child.js, packages/gatsby/src/utils/worker/render-html.ts
Convert `util/worker/render-html ` to typescript.
=> chore(gatsby): Convert util/worker/render-html to typescript

packages/gatsby-plugin-typescript/README.md, packages/gatsby-plugin-typescript/package.json, packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js, packages/gatsby-plugin-typescript/src/gatsby-node.js
Seems like we broke our typescript plugin for many users so reverting
Fixes https://github.com/gatsbyjs/gatsby/issues/21913
=> Revert "feat(gatsby-plugin-typescript): Supports linting (#18721)"

www/redirects.yaml
changes:
- add trainling slashes
- point path without `.md`
- add missing beginning slash
-  #21908 `Rename Theme tutorials to Plugin and Theme Tutorials and update redir…`
=> fix(doc): redirects

docs/docs/deploying-to-cloudflare-workers.md
changed:
- add code block languages
__yaml is reformatted by prettier/link - are the new spaces right this way?__
- #21658 `docs: add Cloudflare Workers documentation`
=> fix(docs): add Cloudflare Workers documentation

docs/contributing/translation/ui-messages.md, packages/gatsby-source-contentful/README.md
changes:
- add missing code block languages
- #21740 `Update Readme with information for multiple spaces`
=> fix(readme): Update Readme gatsby-source-contentful missing code languages

.circleci/config.yml
This adds the `BENCHMARK_BRANCH` environment variable to benchmarks. It is only `master` in this particular instance, but it is a variable that we want to capture in case we run benchmarks on different branches in the future.
This is already captured in the benchmark plugin, so this is only to add the variable to the benchmark runs in the CircleCI config.
None.
None.
=> Add branch name env var for benchmarks

CHANGELOG.md
Previously it was pointing to = https://github.com/babel/babel/
Now, it's updated to = https://github.com/babel/babel/tree/master/packages
=> Minor fix to update the link of babel

packages/gatsby-plugin-offline/src/gatsby-node.js
This makes `gatsby-plugin-offline` write `app-shell.js` to the user's cache directory before using `createPage()`.
The reason for this is because `true-case-path` doesn't work well with yarn 2's virtual dependency paths.  The paths normally read:
`/path/to/project/.yarn/$$virtual/package-name/<number>`
As soon as `true-case-path` reaches `$$virtual`, it only finds the contents of `/path/to/project/.yarn`.  Which means it won't ever find `$$virtual/package-name/<number>`.  It wouldn't even be able to pick up a valid path again until it reaches the number that follows the package name (which resolves to wherever the yarn cache is located).
This explains why `gatsby-plugin-offline` throws an exception when trying to call `createPage()` with `${__dirname}/app-shell.js` as the component.  By …
=> fix(gatsby-plugin-offline): Run app-shell.js from user cache directory for pnp compatibility

docs/docs/deploying-to-cloudflare-workers.md
changes:
- 🧹 Fix case of GitHub
=> fix(docs): 🧹 Fix case of GitHub

packages/gatsby/src/utils/webpack-plugins.ts, packages/gatsby/src/utils/webpack-utils.js
Part of #21995 
I migrated `webpack-plugins.js` to TypeScript
#21995
=> chore(gatsby): migrate webpack-plugins to TypeScript

docs/docs/typography-js.md
Putting the install snippet in its own code block makes it easier for people to copy the snippet. I believe this is also consistent with other doc pages.
N/A
N/A
=> Put install in its own code block

docs/docs/glossary.md, docs/docs/glossary/build.md, docs/docs/glossary/continuous-deployment.md, www/src/data/sidebars/doc-links.yaml
Update doc-links and glossary.md. Added a link to Build article from the Continuous Deployment entry.
=> Add docs/glossary/build article

packages/gatsby-plugin-preload-fonts/src/gatsby-ssr.js
Fixes #21814. A detailed description of the problem can be found in the issue.
=> fix(gatsby-plugin-preload-fonts): lookup routes with and without trailing slash

packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-image/src/__tests__/index.js, packages/gatsby-image/src/index.js
When art directing multiple images and no media query matches, the current implementation chooses the first image with a media query.
This PR will choose the first image without `media` if no images match current `window`. This reflects what one would expect [from the documentation](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images) (right now the mobile image would never be selected)
The documentation reflects what one would expect from mobile-first design.
I don't believe this is a breaking change. Any client that has `media` with every image will continue to work the same way. Any client that has an image without `media` probably expects the behavior that this PR implements.
Addresses documentation error mentioned above
Addresses #15189 when adding a …
=> fix(gatsby-image): When art-directing images, default the padding aspect ratio to first image without a media query when no media query matches

packages/gatsby-source-filesystem/src/extend-file-node.js
As discussed in #22244, this patch lets `gatsby-source-filesystem` use the same generated URL as `gatsby-remark-copy-linked-files`, i.e. the content digest as a parent directory so that the filename does not change.
Should it? However it makes sense to notify users that their URLs will probably change.
Fixes #22244 which addressed #9777.
=> feat(gatsby-source-filesystem): Unify publicURL

docs/tutorial/part-zero/index.md
Update latest version numbers for nvm and npm in part-zero of tutorial.
nvm: v0.35.1 to v0.35.3
node: 10 to 12
The documentation in https://www.gatsbyjs.org/tutorial/part-zero/ does not use the latest version number of nvm and node, but it says that it is the latest version.
=> chore(docs): Update version numbers in tutorial

packages/gatsby/src/redux/actions/public.js
Simply adds a link to [gatsby-plugin-meta-redirect](https://www.gatsbyjs.org/packages/gatsby-plugin-meta-redirect/) which is quite helpful for redirects independent of your hosting solution.
=> Add link to gatsby-plugin-meta-redirect

docs/sites.yml
Adding a [covid-19 tracker](https://coronavirus.traction.one/) to the site showcase.
=> docs(sites): add a site to showcase

packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.js, packages/gatsby/src/utils/local-eslint-config-finder.ts, packages/gatsby/src/utils/webpack.config.js
Convert local-eslint-config-finder to typescript
=> chore(gatsby): Convert local-eslint-config-finder to typescript

packages/gatsby/index.d.ts
This PR fixes the incorrect type for `PackageJson`. 
Fixes #22394.
=> fix(gatsby): Incorrect PackageJson type

renovate.json5
This will not automatically create PRs for specific packages (below 1.0.0), instead those will need approval in [Renovate issue](https://github.com/gatsbyjs/gatsby/issues/16840)
Follow up to https://github.com/gatsbyjs/gatsby/pull/22224
=> chore: adjust renovate config

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Fixes https://github.com/gatsbyjs/gatsby/issues/22386
Netlify Identity Widget provides two build outputs:
1. [`netlify-identity-widget.js`](https://github.com/netlify/netlify-identity-widget/blob/05152b12587e5093940c004f647d59799daaa21f/webpack.config.babel.js#L14) which initializes the widget on [DOMContentLoaded](https://github.com/netlify/netlify-identity-widget/blob/05152b12587e5093940c004f647d59799daaa21f/src/index.js#L11).
2. [`netlify-identity.js`](https://github.com/netlify/netlify-identity-widget/blob/05152b12587e5093940c004f647d59799daaa21f/webpack.umd.config.babel.js#L6) which doesn't initialize the widget.
This PR switches from number 1 to number 2 to avoid duplicate initialization as the widget is already initialized here …
=> fix(plugin-netlify-cms): use 'netlify-identity.js' instead of 'netlify-identity-widget.js'

docs/contributing/translation/sync-guide.md
changed
- fix missing link - i guessed a possible link to markdown frontmatter section
- #21753 `feat(docs): Guide for syncing translation repos`  
=> fix(docs): Guide for syncing translation repos

docs/docs/glossary/markdown.md, packages/gatsby-design-tokens/CHANGELOG.md
Found 2 Markdown files with trailing whitespace.
=> chore(docs): 🧹 remove trailing whitespace from Markdown.

packages/gatsby/package.json, yarn.lock
=> chore(gatsby): upgrade `null-loader`

docs/blog/2020-03-23-Flying-Feature-Flags-with-New-LaunchDarkly-plugin/index.md
Build on `master` is failing because of a lint conflict, this PR fixes it.
=> chore(docs): Fix Markdown formatting

docs/docs/schema-customization.md
Was looking into createSchemaCustomisation as was previously using `sourceNodes` API. Scrolled down and found this tiny typo.
Couldn't find this paragraph with ctrl-F.
=> chore(docs): fix typo in schema customization

packages/gatsby/src/query/query-compiler.js, packages/gatsby/src/query/query-watcher.js, packages/gatsby/src/utils/gatsby-dependents.ts, packages/gatsby/src/utils/webpack.config.js
This PR migrates `packages/gatsby/src/utils/gatsby-dependents` to TypeScript.
Part of #21995.
=> chore(gatsby): Migrate gatsby-dependents to TypeScript

packages/gatsby/src/utils/webpack-utils.ts
When #22381 was merged builds started failing for `www` (the docs site). The error looks like this:
```
11:01:06 AM: error { "commentNumber": null, "level": 1, "id": "827a9a3a-6d53-5ec1-bde7-32147298b648", "parent": "ec28ebff-f198-59bc-9d97-9f0662e37679", "children": [ "f923a690-d5e9-5170-a02b-b51a17706ae7", "4bddd280-f7d7-5922-821a-89604b600b2f", "ed3d70f6-d142-5e7b-92f7-29ede823380d" ], "internal": { "type": "DocumentationJs", "contentDigest": "358a5703a82d2d403134479c9cf283fe", "counter": 7689, "owner": "gatsby-transformer-documentationjs" }, "kind": "function", "memberof": "plugins", "name": "minifyJs", "scope": "static", "examples": [], "tags": [], "optional": false, "docsLocation": { "start": { "line": 519, "column": 2 }, "end": { "line": 522, "column": 5 } }, "codeLocation": { …
```
=> fix(www): remove comments that are causing builds to fail

www/src/components/dark-mode-toggle.js
This fixes incorrect title and aria-label issue of dark mode toggle button
Related: https://github.com/gatsbyjs/gatsby/pull/21633
Note that I haven't tested this fix locally yet because `gatsby develop` in `www` is taking too much time on my PC.
=> fix(www/dark-mode-toggle): title and aria-label[object Object] issue

docs/docs/tailwind-css.md
Small fix, the new command for Tailwind is `tailwindcss` not `tailwind`.
=> docs: update tailwind init command

docs/docs/mdx/programmatically-creating-pages.md
changes:
- use code block for links to avoid 404
- put file names in code block
=> fix(docs): use code block for links to avoid 404

docs/docs/typography-js.md
changes:
- put install command in own code block like in #22359
- remove `--save` from install command
- #22359 `Put install in its own code block`
=> fix(docs): typography - put install in its own code block

docs/docs/sourcing-content-from-json-or-yaml.md
It appears the title of the JSON section changed, so the link to that section is no longer valid. This updates it to make it valid again.
N/A
N/A
=> update link to json section

docs/blog/2020-03-20-dropping-support-for-node-8/index.md
changes:
- #22400 `chore: bump node min version to 10.13.0` 
=> fix(blog): bump node min version -> remove local domain

packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-plugin-sharp/src/__tests__/trace-svg.js, packages/gatsby-plugin-sharp/src/trace-svg.js
Fixes the scaling issue of Traced SVG placeholdes as described in issue #22169.
No documentation existing. Not worth documenting in my opinion, as it is just a bugfix.
Fixes #22169
=> fix(gatsby-plugin-sharp): fix Traced SVG scaling issue in Internet Explorer

docs/blog/2020-03-11-netlify-functions-and-gatsby-cloud/index.md, www/src/data/tags-docs.js
changes:
- fix 404 on external link
- fix 404 of missing blog tag
- point to gatsby cloud 
- add code block language for tree view
- #22115 `docs(blog): Add Netlify Functions post` 
=> fix(blog): netlify functions 404, code block language and more

packages/gatsby/src/bootstrap/resolve-module-exports.js, packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap, packages/gatsby/src/utils/babel-parse-to-ast.ts
Convert `src/utils/babel-parse-to-ast.js` to TypeScript.
I could not use `ParserOptions` Interface exported by `@babel/parser` to declare the return value of the getBabelParserOptions function. 
Because the `ParserOptions` interface and `PARSER_OPTIONS` declared in the `babel-parse-to-ast.js` file are incompatible.
So instead of `ParserOptions` interface, I temporarily declared the return value of the `getBabelParserOptions` function as `object` type.
=> chore(gatsby): Convert babel-parse-to-ast to TypeScript

docs/docs/deploying-to-gitlab-pages.md
It is safe (and recommended!) to cache the `.cache/` directory as per conversation in issue #20285. This PR makes that change.
Related to #20285
=> Add ./cache to cache paths for gitlab-ci template

starters/gatsby-starter-plugin/README.md, starters/gatsby-starter-plugin/gatsby-node.js, starters/gatsby-starter-plugin/package.json
Adding the plugin starter broke the `publish-starters` script for not having a name in the `package.json` that matches a repo on the Gatsby org. This change should push to the repo here with new changes (I believe): https://github.com/gatsbyjs/gatsby-starter-plugin
https://circleci.com/gh/gatsbyjs/gatsby/360016
=> fix(starters): rename starter-plugin to comply with publish starters script

docs/docs/testing-css-in-js.md
Add `@emotion/babel-preset-css-prop` to the `jest-preprocess.js` file. This allows for the stringificaiton of CSS properties in snapshot testing. Currently, with Emotion 10, if the babel option is not set, you will not have readable css properties. @emotion/babel-preset-css-prop is shipped by default with Emotion 10 and does not need to be installed seperately by npm.
[https://github.com/emotion-js/emotion/tree/master/packages/babel-preset-css-prop](https://github.com/emotion-js/emotion/tree/master/packages/babel-preset-css-prop)
=> chore(doc):Add babel preset css prop to jest-preprocess.js

docs/docs/recipes/working-with-plugins.md
Adds an Egghead video for the new plugin recipes on installing and using a plugin in a Gatsby site. (I'll probably get around to adding another one for using the plugin starter soon)
_None_
=> docs: add egghead video for installing plugins

packages/gatsby-plugin-sharp/src/process-file.js
Currently the `defaultQuality` is not being applied when compressing jpg or webp as the wrong args are used.
https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/
Fixes #13807
=> fix(gatsby-plugin-sharp): Apply transformArgs on compressJpg and compressWebP

docs/tutorial/using-multiple-themes-together.md
This provides an updated header.js component for the multiple themes tutorial that will work - is a functioning component and gets rid of that hanging semi-colon.  This way if someone copy and pastes at least they will get something that works out of the box.
I think this is better than what we have there right now.  Feel free to reject this and close it if you want. I was trying to get rid of that semi-colon and realized in the process that we could give people a "working" component at least.
=> chore(docs): better example header.js in multiple themes

docs/sites.yml
Removing sites after looking at site showcase validator.
Remove deepThreads: Site no longer routing to a valid site
Remove danieljs.tech source_url
Remove Patrik Arvidsson's portfolio: Site switched to Next
Remove yerevancoder: Site no longer online (and username on github has dissapeared)
Remove Pravdomil: Site no longer built with Gatsby
Remove William Owen UK Portfolio / Blog: Site not online anymore
Remove Hubba: specific URL no longer routing and main site is just React and not Gatsby
Remove justaskusers.com: Site no longer online
=> chore(showcase): Remove sites from showcase

docs/docs/preprocessing-external-images.md
After adding this, someone can modify `*.md`, then the rebuilding by 'gatsby develop' will not break the type inference for a foreign-key field created by the plugin.
Fix #22127
=> docs: fix the lost of external file node after rebuilding

docs/starters.yml
I've been using Shards UI for 3 of my projects now, and I was getting really tired of repeating myself every project. To avoid this redundancy I created a special template that uses all of the standards to start your own Gatsby Project. Those are typescript, styled-components, and a UI framework.
I mostly created this out of frustration from having to recreate the same type of projects every time, I hope it serves everyone in terms of getting up to speed with Shards UI - which is a clean React UI library. Embedded in the starter is typescript, styled-components, and bootstrap.
The documentation should be [here](https://github.com/wcisco17/gatsby-typescript-shards-starter)
=> chore(starters): Created a Template using Shards UI library

docs/docs/themes/conventions.md
I'm still learning Gatsby, but from what I've read, overriding files is done with shadowing. If that's true, using the word shadow here instead is more precise and clear.
=> Is `shadow` a better term here?

docs/docs/themes/conventions.md
The maximal prefix is `gatsby-theme-` so make sure both instances of that string include the final `-` for consistency.
=> Add `-` to end of second `gatsby-theme` prefix str

docs/contributing/translation/ui-messages.md
changed
- fix redirect to right section (section moved in #21806)
- #21805 `(docs) Guide for translating UI text with Lingui`
- #21806 `chore(www) reorganize contributing section`
=> fix(docs): Guide for translating UI - 404

packages/gatsby-plugin-mdx/loaders/mdx-loader.test.js, packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Since getSourcePluginsAsRemarkPlugins is called on
every MDX file, the getNodes call became expensive
at scale with thousands of MDX files.
This was encountered when attempting to find
underlying issues for #22521. @pvdz had a hunch that
node traversal may be a culprit. This doesn't fully
address all underlying performance issues but
is a quick win.
8k MDX pages: 440s => 350s
16k MDX pages: 1100s => 750s
=> fix(gatsby-plugin-mdx): Use getNodesByType for plugin transformation

packages/gatsby-source-graphql/.gitignore, packages/gatsby-source-graphql/README.md, packages/gatsby-source-graphql/package.json, packages/gatsby-source-graphql/src/batching/__tests__/dataloader-link.ts, packages/gatsby-source-graphql/src/batching/__tests__/merge-queries.ts, packages/gatsby-source-graphql/src/batching/dataloader-link.ts, packages/gatsby-source-graphql/src/batching/merge-queries.ts, packages/gatsby-source-graphql/src/gatsby-node.js, packages/gatsby/src/query/queue.js, yarn.lock
This PR allows `gatsby-source-graphql` users to improve performance 2-10 times by introducing query batching strategy along with a new environment variable for controlling query concurrency.
By default, `gatsby-source-graphql` executes each query in a separate network request. Query batching strategy implemented in this PR merges several queries into a single query and sends it to the server.
Consider the following queries:
```js
{
query: `query(id: Int!) {
node(id: $id) {
foo
}
}`,
variables: { id: 1 },
}
```
```js
{
query: `query(id: Int!) {
node(id: $id) {
bar
}
}`,
variables: { id: 2 },
}
```
They will be merged into a single query:
```js
{
query: `
query(
$gatsby0_id: Int!
$gatsby1_id: Int!
) {
gatsby0_node: node(id: $gatsby0_id) {
foo
}
gatsby1_node: node(id: $gatsby1_id) {
bar
}
} …
```
=> feat(gatsby-source-graphql): Query batching

docs/docs/adding-comments.md
The service is shutting down and should no longer be recommended - https://just-comments.com/blog/2020-03-06-just-comments-is-shutting-down.html
=> chore(docs) Remove JustComments

packages/gatsby-plugin-manifest/README.md, packages/gatsby-plugin-offline/README.md
I added the documentation describing why icons not cached when using gatsby-plugin-manifest with gatsby-plugin-offline.
Documented in gatsby-plugin-offline & gatsby-plugin-manifest
This PR will close #19870
=> [docs] add explanation to why icons not cached by offline & manifest plugin

docs/docs/loading-plugins-from-your-local-plugins-folder.md, examples/using-multiple-local-plugins/README.md, examples/using-plugin-options/README.md
Looks like prism doesn't like `sh`, so changing those mentions to `shell`.
=> docs: fix language codes

docs/blog/100days/comments/index.md
New 100daysofgatsby challenge. This week is all about comments. Ready for review
=> (blog) 100days challenge 13

docs/blog/2020-03-23-introducing-gatsby-web-creators/index.md, www/src/templates/template-blog-post.js
Here's hoping this PR fixes the issue I attempted to cover in #22535: this PR removes a query height parameter from the blog post template for images, which was cropping my horizontal image into a square in production and looking generally terrible. When I tested it locally, somehow it wasn't exhibiting the same behavior–you can even see my commit history of playing with this in the last PR.
After talking with the team internally, removing one of the image dimensions should eliminate the awkward cropping. I also made a content update for a question we got regarding the livestream length.
N/A
N/A
=> chore: fix livestream social sharing

packages/gatsby/index.d.ts, packages/gatsby/src/redux/actions/restricted.js
It would be great to have the plugin argument optional, to avoid workaround like:
```js
api.actions.createFieldExtension({
name: "TestType",
extend: () => ({
resolve: () => "resolved"
})
}, 
{name: "plugin name"} // Forced to be passed in typescript
```
Showcase:
* https://github.com/Simply007/gatsby-kontent-packages/blob/master/packages/gatsby-source-kontent/src/createSchemaCustomization.items.ts#L81
=> fix(gatsby): Mark plugin parameter as optional for actions

.circleci/config.yml
This updates
- The CircleCI benchmark cron schedule to match that of other platforms for consistency.
- The machine type to use the default machine type to match using defaults in other platforms for consistency. https://circleci.com/docs/2.0/configuration-reference/#docker-executor
n/a
n/a
=> Update benchmark cron schedule and machine type

starters/blog/src/components/layout.js
text-decoration: none is already set, earlier in the cascade,
maybe through typography.js?
This css rule has been there since 077cb982 but I can't tell if it was effective then.
=> fix(gatsby-starter-blog): Remove superfluous text-decoration:none

packages/gatsby/src/utils/worker/child.js, packages/gatsby/src/utils/worker/child.ts
Migrate `src/utils/worker/child` to TypeScript
=> chore(gatsby): Migrate utils/worker/child to TypeScript

docs/contributing/gatsby-style-guide.md
Updated a small typo in a code block within the Gatsby style guide. 
The typo was 'glossay', updated to 'glossary'.
https://www.gatsbyjs.org/contributing/gatsby-style-guide/
=> Update a small typo in style guide

packages/gatsby/src/commands/build-javascript.ts
`gatsby build` doesn't propagate all relevant errors up to its error reporter. webpack's stats `hasErrors()` is a child compilation aware call, thus, so too should be gatsby's error stats error collector
n/a
closes #22597
=> fix(gatsby): Collect nested webpack compilation stats errors

packages/gatsby/src/redux/__tests__/run-sift.js, packages/gatsby/src/redux/nodes.ts, packages/gatsby/src/redux/run-sift.js
This will support the fast filter cache for filters with multiple paths (all leading to `eq`).
Before this commit, the fast filter would only apply to "flat" filters leading to eq. That means `filter: {a: {b: {c: {eq: 5}}}}` would be fast but `filter: {a: {b: {c: {eq: 5}, d: {eq: 6}}}}` (and all varieties) would be slow, take the sift path.
After this commit, any number of filters should take the fast(er) path. It'll not be as fast as a flat path because it needs to do an intersection of all filter conditions (of course), but should still be faster than going through sift.
=> Multi path fast filters

docs/docs/debugging-the-build-process.md
Fixed `Debugging the Build Process` documentation by making `Node` lowercase
=> fix(docs): Lowercase Node

docs/docs/creating-a-generic-plugin.md
Fixes the example in the `sourceNodes` section of the `node-apis` documentation
=> fix(docs): Fixed example in creating generic plugin

packages/gatsby/src/bootstrap/index.js, packages/gatsby/src/redux/plugin-runner.ts
Migrate `src/redux/plugin-runner` to TypeScript
=> chore(gatsby): Migrate src/redux/plugin-runner to TypeScript

package.json, packages/gatsby/package.json, packages/gatsby/src/utils/tracer/index.ts, packages/gatsby/src/utils/tracer/zipkin-local.ts, packages/gatsby/src/utils/tracer/zipkin-types.d.ts, yarn.lock
Convert `utils/tracer/zipkin-local` to typescript.
=> chore(gatsby): Migrate utils/tracer/zipkin-local to TypeScript

packages/gatsby-telemetry/src/__tests__/telemetry.js, packages/gatsby-telemetry/src/index.js
Fixed the isTrackingEnabled being exported as a function returning a function instead of a function returning a value
As #22531 mentions, the telemetry module is exporting a _function that returns a function_ instead of a _function that returns a boolean value_.
I've gone through the entire codebase, we don't use it as a returning function anywhere.
Also, added a minor test for `telemetry.js`
Fixes #22531
=> fix(telemetry): fix isTrackingEnabled always truthy

docs/docs/recipes/working-with-plugins.md
Adds an Egghead video for the new plugin recipe on generating a new plugin with the plugin starter. This is a follow up to #22517 where I made the first screencast for installing plugins.
_None_
=> docs(recipes): add a screencast for generating a plugin with the plugin starter

integration-tests/gatsby-cli/__tests__/develop.js
Gatsby box merged a PR that got a false positive green pass in CI. This fixes the test. We can't use `lsof` in CI apparently.
=> [hotfix]: Gatsby cli develop tests fix

packages/gatsby/src/redux/nodes.ts, packages/gatsby/src/redux/run-sift.js
Abstracts the key generation into a single function, creates a "opaque type" (a string with semantic meaning, has no runtime implications), and updates types accordingly.
No semantic change in this PR.
=> chore(gatsby): create single filter cache key generator

packages/gatsby-plugin-google-gtag/src/index.js
update gatsby-plugin-google-gtag OutboundLink component to forward ref onto DOM element.
Fixes #22704
=> fix(gatsby-plugin-google-gtag): OutboundLink Forward Ref

docs/docs/page-build-optimizations-for-incremental-data-changes.md
The current text copy suggested to only persist `.cache/redux.state` between builds, while in fact we need to persist both `.cache` and `public` directories.
https://github.com/gatsbyjs/gatsby/issues/22641
/cc @TAGraves
=> docs: clarification about `.cache` and `public` persistance when using GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES

docs/docs/preprocessing-external-images.md
changes:
- #22528 `docs: fix the lost of external file node after rebuilding`
=> fix(docs): remove local domain from preprocessing external images

packages/gatsby/src/schema/__tests__/fixtures/queries.js, packages/gatsby/src/schema/__tests__/queries.js, packages/gatsby/src/schema/resolvers.js
Before this PR gatsby breaks when grouping using reserved keywords for grouping value. See #22508 for details and repro.
Fixes #22508
=> fix(gatsby): Support grouping by reserved keywords

integration-tests/gatsby-cli/__tests__/build.js, integration-tests/gatsby-cli/__tests__/develop.js
I was going to write tests for gatsby clean, but then I realized I had before and after hooks doing what gatsby clean does. So now instead, we just invoke that command. It's sort of an implicit test on `gatsby clean`
There's also a few other micro clean ups in there.
=> chore(gatsby-cli): use `gatsby clean` in tests to test `gatsby clean`

packages/gatsby-source-contentful/src/extend-node-type.js
Noticed a problem after upgrading to gatsby-source-contentful@2.2.5 where all our images were using the same base64 placeholder. I managed to track down the source of the issue to #22551 where caching was introduced but the cache key was the same for all images since it was based on the string `requestUrl` instead of the interpolation `${requestUrl}`.
Related to #22551
=> fix(gatsby-source-contentful): use request url for base64 image cache key

docs/docs/processing-payments-with-stripe.md
changes:
- there is still a 404 on starters -> #22733 `bug(starters): starter pages are not created for some starter repos` 
- #22431 `Update docs/processing-payments-with-stripe`
- #22733 `bug(starters): starter pages are not created for some starter repos` 
=> fix(docs): remove local domain from processing payments with stripe

docs/blog/2020-03-26-service-relief-project/index.md
changes:
- Links: remove domain from internal links
- Links: `http` to `https`
- brand names: `GatsbyJS` to `Gatsby`
- brand names: `Github` to `GitHub`
- markdown: remove space for bold markup - to only apply to the line (you see it in github code view with the markdown highlighting in bold)
- changed `help out':'` to `help out:`
- ~~is there a special meaning for this format `help out':'`?~~ 
answer: it was a typo (https://github.com/gatsbyjs/gatsby/pull/22548#issuecomment-607445467 and see #22727)
- the TOC is broken (see bug: #22728 `markdown anchor links for a header with html`) but this can be a followup PR  
- #22548 `(blog) service relief project`
- #22728 `markdown anchor links for a header with html`
=> fix(blog): service relief project - link fixes, brand names 

benchmarks/source-datocms/gatsby-config.js, benchmarks/source-datocms/gatsby-node.js, benchmarks/source-datocms/src/pages/index.js
- Fixes the DatoCMS benchmarks. There is no `path` available in `allDatoCmsArticle`.
- Auto-formatting
n/a
n/a
=> Fix DatoCMS benchmarks

packages/gatsby/src/recipes/providers/fs/file.js, packages/gatsby/src/recipes/providers/fs/file.test.js, packages/gatsby/src/recipes/providers/gatsby/fixtures/gatsby-config.js, packages/gatsby/src/recipes/providers/gatsby/plugin.js, packages/gatsby/src/recipes/providers/gatsby/plugin.test.js, packages/gatsby/src/recipes/providers/gatsby/shadow-file.js, packages/gatsby/src/recipes/todo.md
Begins to address some feedback by not overwriting files by default, handling object style plugins in the config, using `fs-extra` and adding more thorough tests.
=> recipes: Improve providers

packages/gatsby-link/index.d.ts, packages/gatsby-link/package.json, yarn.lock
Recent PR to `@types/reach__router` added `innerRef` typing ( https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43367 ):
```ts
innerRef?: React.RefCallback<HTMLAnchorElement>;
```
which is incompatible with `innerRef` that we have:
```ts
innerRef?: Function
```
and this is causing following error (we extend `@reach/router`'s `Link` props):
```
node_modules/gatsby-link/index.d.ts:4:18 - error TS2430: Interface 'GatsbyLinkProps<TState>' incorrectly extends interface 'LinkProps<TState>'.
Types of property 'innerRef' are incompatible.
Type 'Function | undefined' is not assignable to type '((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | null | undefined'.
Type 'Function' is not assignable to type '((instance: HTMLAnchorElement | null) => void) | …
```
=> fix(gatsby-link): drop custom innerRef typing and reuse one from @reach/router

packages/gatsby/src/query/graphql-runner.ts
=> fix(gatsby): Fix OOM from telemetry storing too much

package.json, yarn.lock
We used to only inherit it transitively via @types/prop-types, but a lot
of typings actually need it.
This will helps us pull the latest @type/reach__router package, which
(only implicitly, unfortuately) depends on more recent react types than
the ones we have.
N/A
For example, helps in #22563.
=> chore: Upgrade and consolidate @types/react

packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Update the `pageCount` to use `NUM_PAGES` for consistency. Counting pages in `page-data` could include artifacts from SSR, the 404 page and other pages.
n/a
n/a
=> fix(gatsby-plugin-benchmark-reporting): Update pageCount to use NUM_PAGES

.circleci/config.yml, benchmarks/README.md, benchmarks/mdx/README.md, benchmarks/mdx/package.json
Update MDX benchmarks to match "normal" benchmark interface.
Add jobs to CirlceCI.
=> ci: add mdx benchmark to cronjob, adjust content source in remark benchmarks to differentiate mdx and remark

.circleci/config.yml
Fix an incorrect `working_directory` for an individual benchmark.
n/a
n/a
=> Fix incorrect benchmark working directory

yarn.lock
Update `decompress` to fix a vulnerability that causes warnings in audits.
[Quoted from npm](https://www.npmjs.com/advisories/1217):
> ### Overview
> Versions of `decompress` prior to 4.2.1 are vulnerable to Arbitrary File Write. The package fails to prevent extraction of files with relative paths, allowing attackers to write to any folder in the system by including filenames containing `../`.
> ### Remediation
> Upgrade to version 4.2.1 or later.
Fixes #21791
=> chore(monorepo): bump decompress in yarn.lock 

docs/starters.yml
Nothing earth-shattering here, simply a starter with  *just* react-bootstrap and sass
support. Many other existing starters bring a lot of additional bells and whistles.
Preview: https://mik3y.github.io/gatsby-starter-basic-bootstrap/
https://github.com/mik3y/gatsby-starter-basic-bootstrap#-quick-start
=> chore(starters): add gatsby-starter-basic-bootstrap

docs/docs/creating-a-generic-plugin.md
Inconsistent formatting in Generic plugin example
Fixes #22844
=> chore(docs): Update formatting

packages/gatsby-source-graphql/src/batching/__tests__/dataloader-link.js, packages/gatsby-source-graphql/src/batching/__tests__/merge-queries.js, packages/gatsby-source-graphql/src/batching/dataloader-link.js, packages/gatsby-source-graphql/src/batching/merge-queries.js
Convert files using Typescript back to vanilla JS in `gatsby-source-graphql`. The reason for this is that the decision has not been made yet if we want to convert plugins to Typescript (as this would make contributions harder).
So the usage of Typescript in `gatsby-source-graphql` was a bit premature as we don't have a common build configuration for Typescript in plugins.
Fixes #22785
=> fix(gatsby-source-graphql): Convert ts to plain js until better times

docs/docs/using-gatsby-image.md
This updates the example snippets on the /docs/using-gatsby-image
documentation page to use PageQueries instead of StaticQueries, because
the example snippets have a src/pages/index.js filename.
The hope is that since the snippet filenames are in the pages directory,
it's more consistent with other documentation to use PageQueries when
in a src/pages/*.js file instead of a StaticQuery, which from the
documentation appears to be used in places like src/components/*.js.
This documentation exists at https://www.gatsbyjs.org/docs/using-gatsby-image/
=> docs: use PageQuery in gatsby image example snippet

docs/docs/glossary.md, docs/docs/glossary/hydration.md, www/src/data/sidebars/doc-links.yaml
Also updated glossary.md, doc-links.yaml with links to new article.
=> Add docs/hydration entry.

docs/docs/adding-page-transitions-with-plugin-transition-link.md
The installation docs link was pointing to transition-portal docs. Fixed it.
=> Fix transition-link installation docs link

packages/gatsby-plugin-twitter/README.md
Went to use this plugin and didn't understand how to actually include the tweet! Did some googling and I'm not alone. So figured we should update this :)
=> Improve README for twitter plugin

docs/docs/telemetry.md, packages/gatsby-image/src/index.js, packages/gatsby-image/src/withIEPolyfill/index.js
When using `gatsby-image/withIEPolyfill` some special styles are applied to the image, based on the `objectFit` and `objectPosition` props. However, those special styles are not applied to the placeholder image (e.g. traced SVG). This PR fixes this problem.
Fixes #22856
=> apply IE polyfill styles to placeholder images too

benchmarks/source-contentful/README.md, benchmarks/source-contentful/bin/site.js, benchmarks/source-contentful/package.json
There is a problem with Contentful benchmark sites. Occasionally Contentful silently fails to process images (detecting width, height, mime type, etc) which causes benchmark builds to fail.
This PR provides command-line tools to find and fix broken images.
Added in README.md in this PR.
=> chore(benchmarks): Add ability to fix broken images for contentful sites

docs/docs/gatsby-on-windows.md
adding `--vs2015` parameter for install the Visual Studio 2015 Build tools instead of the Visual Studio 2017 ones.
install manualy or via CMD/Powershell
windows-build-tools [README.md](https://github.com/felixrieseberg/windows-build-tools/blob/master/README.md) 
Related to #4694
=> [Docs] adding additional parameter for Install Visual Studio 2015 Build Tools

docs/docs/add-seo-component.md
Update the [Add SEO Component](https://www.gatsbyjs.org/docs/add-seo-component) to utilize React Hooks (`useLocation` and `useStaticQuery`).
None.
=> 🎣 add hooks to SEO example

docs/blog/2020-03-26-service-relief-project/index.md
changed:
- fix toc to match the autogen anchor links (suggested in https://github.com/gatsbyjs/gatsby/issues/22728#issuecomment-607946738 )
- #22548 `(blog) service relief project`
- #22728 `bug: markdown anchor links for a header with html`
- #22730 `Feature Request: Table of Content (TOC) for blogs`
=> fix(docs): toc in service relief blog post 

docs/blog/100days/comments/index.md
changes:
- fix brand name from `Discus` -> `Disqus`
- #22568 `docs(blog): 100days challenge 13`
=> fix(blog): brand name Disqus

docs/blog/2018-04-10-how-to-handle-comments-in-gatsby-blogs/index.md
changed:
- brandname from `staticman` to `Staticman`
- https://www.gatsbyjs.org/contributing/gatsby-style-guide/#capitalize-proper-nouns
=> fix(docs): brand name staticman

packages/gatsby-plugin-mdx/utils/gen-mdx.js
The `modules` option for Babel must be a boolean, not a string.
=> fix(gatsby-plugin-mdx): pass on proper `modules` option value to babel

docs/contributing/setting-up-your-local-dev-environment.md, packages/gatsby-dev-cli/README.md
changes:
- added a "how to revert changes" from `gatsby-dev` (https://github.com/gatsbyjs/gatsby/issues/21027#issuecomment-585361320 and https://github.com/gatsbyjs/gatsby/issues/21027#issuecomment-609612670)
PS:
help on the right wording is welcome
- fixes #21027 `gatsby-dev-cli: how to remove the installed plugins`
=> docs: add revert info for gatsby-dev

docs/docs/creating-a-generic-plugin.md
changes:
- lower case in one word 
- #20527 `chore (doc):Create a files for "Building a generic plugin" and link "Files gatsby looks for in plugin" closes` 
=> fix(docs): remove link to local domain in Building a generic plugin

docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/index.md
changes:
- remove domain from internal links 
- #22020 `fix(blog): Building multilingual sites with Gatsby`
- #21517 `(blog) Bulding multilingual sites with Gatsby`
=> fix(blog): multilingual sites: remove local domain

packages/gatsby/src/db/__tests__/fixtures/ensure-loki.js, packages/gatsby/src/redux/__tests__/run-sift.js, packages/gatsby/src/redux/nodes.ts, packages/gatsby/src/redux/run-sift.js, packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/__tests__/run-query.js, packages/gatsby/src/schema/node-model.js
The filter for `elemMatch` is basically a sub-match on elements of an array. So rather than matching one explicit path, it matches any of the n paths, splitting off at an array. Other than testing paths through each element in an array, it behaves the same as a regular filter. The `elemMatch` filters can be nested.
These filters weren't before optimized and couldn't take the fast index path. This PR changes that.
I've modified "the ifsc" benchmark site and added a silly simple array with three elements to the nodes. Then I modified the query to add an `elemMatch` (aside the already existing `eq` filter on `id`) and ran the before-after benchmark on 500, 5.000, 10.000, and 50.000 pages. The results were as stunning as when first introducing the indexed filters :rocket: See below.
This PR …
=> perf(gatsby): support `elemMatch` as fast filter

docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/index.md
_NOTE: i split to to separate PR - see last comment_
adjustments:
- fix relative path on internal links
- fix codeblock languages
- add code fences at some constants
- changed all intends to 2 tabs
- add code line from previous example, to show where variable `person` comes from
- #21517 `(blog) Bulding multilingual sites with Gatsby`
=> fix(blog): Building multilingual sites with Gatsby

www/src/data/sidebars/doc-links.yaml
changes:
- unify all links and add trailing slash 
- #22628 `chore(docs): Add Snipcart reference guide`
=> fix(docs): add trainling slashes to doc-links.yaml 

docs/docs/adding-a-shopping-cart-with-snipcart.md
changes:
- #22628 `chore(docs): Add Snipcart reference guide` 
=> fix(docs): Add Snipcart reference guide: fix 404 link

packages/gatsby/src/utils/webpack.config.js
Improves commons chunking:
- only combine modules that are requested initially (no require.ensure or import() statements)
- Make sure to only create a commons chunk when we have 2 or more pages.
Fixes #22749
=> fix(gatsby): improve async commons chunking

packages/gatsby/src/redux/persist.ts
The path was omitted which led to `cwd()` being used, whatever it was. `gatsby build` is assumed to be called from the project root, and since it should be able to create `.cache` there, it should also create other temp folders there.
Yet, who knows, it may have caused some of the WSL issues we've been seeing (#21982, #22562) and even if it's not, it prevents these tmp dirs from lingering in the project root in case the build gets cancelled prematurely.
=> fix(gatsby): Use tmp dir for tmp redux cache folder

docs/docs/using-gatsby-image.md
While this really nice use of grammar , I feel like maybe just saying “ Feels like a task that can never be completed” in place of “ Sisyphean” would reduce the cognitive load in this part of the Doc
https://www.gatsbyjs.org/docs/using-gatsby-image/
N/A
=> Replace "Sisphean labour" for readability reasons

docs/blog/2020-04-15-LA-2020-estevez/index.md
Last one! Gatsby Days LA video 11 to run on April 15th, Yuraima Estevez on building accessible components.
=> Add Gatsby Days LA video 11

docs/blog/2020-04-14-LA-2020-Kim/index.md
Daniel Kim on teaching beginner webdevs using Gatsby
=> Add video blog post 10 for April 14th

docs/docs/mdx/programmatically-creating-pages.md
There is a slight inconsistency in the docs for the final steps of the `Make a template for your posts` section. 
The docs have separated this section into two steps (creating an MDX layout component + adding a GraphQL query) but when showing the completed component code (`src/components/posts-page-layout.js`)  the component is missing some imports and the `<MDXProvider>` component that were present in the first step of this section.
- [https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/#make-a-template-for-your-posts](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/#make-a-template-for-your-posts)
=> docs: update programmatically-creating-pages.md to remove inconsistency

www/gatsby-config.js, www/gatsby-node.js, www/src/components/I18nContext.js, www/src/utils/i18n.js
Add an `i18nEnabled` constant instead of checking against `process.env.LOCALES` every time.
=> maintenance(www) value to check if i18n is enabled for this build

scripts/i18n/README.md, scripts/i18n/package.json, scripts/i18n/run-all.js
Create a run-all script that runs a script using every language code as a param. This is needed so that we can run the `sync` script across all the different languages.
TODO:
* parallelization
Depends on: #22617
=> maintenance (scripts/i18n) Create run-all i18n script

packages/gatsby-source-drupal/src/utils.js
There are certain types of entities in Drupal that are sent to the preview server that can not be processed. This adds a check to verify the nodes exist before trying to loop through and process the updates.
Fixes #22724
=> fix(gatsby-source-drupal): Verify nodes exist before looping through them

packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-transformer-documentationjs/src/gatsby-node.js
this used the same parent for every doc node, leading to `id` collisions for overloads with the same path. Also `lineNumber` seems broken from documentationjs, in a few cases it confusing different nodes for each other.
=> fix: create unique Nodes

packages/gatsby-cli/src/init-starter.ts
We have our gatsby starter (https://github.com/ueno-llc/ueno-gatsby-starter) and one folder is a submodule to another git repository.
It would allow us to pass `--recursive` after the starter-url and be able to clone the git submodule folder.
_**Not ready yet on this part:**_
```
gatsby new my-awesome-submodule-site https://github.com/gatsbyjs/gatsby-starter-blog --recursive
```
or through node with our current usage
```
process.argv[2] = 'new';
process.argv[3] = 'myAwesomeSubmoduleSite';
process.argv[4] = `https://github.com/ueno-llc/ueno-gatsby-starter#master --recursive`;
require('gatsby-cli');
```
=> feat(gatsby-cli): allow --recursive git url

packages/gatsby/index.d.ts
Instead of `Function` expose some more detail of `graphql` to allow for type safety.
Same as #14575 just for `onPreBuild`, `onPostBuild`.
=> chore(gatsby): Improve graphql type definitions in BuildArgs

.circleci/config.yml
Testing the automation of the sync script to update translation PRs from the source.
=> Automate i18n sync

scripts/i18n/sync.js
* Use `GITHUB_AUTH_TOKEN` instead of `GITHUB_BOT_AUTH_TOKEN`
* Change `git ci` to `git commit`
* Specify the token in the git URL
=> fix(scripts/i18n) Make the sync script work better for integration

docs/docs/glossary.md, docs/docs/glossary/npm.md, www/src/data/sidebars/doc-links.yaml
Update glossary.md, doc-links.yaml with links to new entry.
=> Adds NPM article.

scripts/i18n/sync.js
Meant to put this in the last PR #22981 but it got merged beforehand :P
=> fix(scripts/i18n) Add better error logging + dedupe logic of sync script

packages/gatsby-plugin-react-helmet/package.json
Version `6.0.0` of `react-helmet` was just released:
https://www.npmjs.com/package/react-helmet 
Currently, installing `gatsby-plugin-react-helmet` alongside `react-helmet@6.0.0` causes the following warning:
```
warning " > gatsby-plugin-react-helmet@3.2.1" has incorrect peer dependency "react-helmet@^5.1.3".
```
This `peerDependency` can be bumped to support both versions as the only breaking change for v6 is the removal of the default export in favour of the named export, as explained in the [upgrade guide](https://github.com/nfl/react-helmet/wiki/Upgrade-from-5.x.x----6.x.x-beta).
`gatsby-plugin-react-helmet` already uses the named export thanks to a commit (99b57c1484f5876751829d81674a34996f627b6b) by @Ehesp which explains the same rationale. This commit just brings the …
=> fix(gatsby-plugin-react-helmet): allow the use of `react-helmet@6`

packages/gatsby/index.d.ts
This PR add extra type definition for `replaceHydrateFunction` function in Gatsby Browser API which will not cause return type of this function to call explicit `any` type error
This PR doe not require docs, it's type improvements
=> chore(gatsby): properly typed return types of replaceHydrateFunction

packages/gatsby-plugin-mdx/README.md, packages/gatsby-plugin-mdx/gatsby/source-nodes.js
`gatsby-plugin-mdx` fails to truncate non-latin language excerpts correctly. The result is always just whitespace. The reason is the `prune` function from `underscore.string` library that is used by `gatsby-plugin-mdx` . It is a long standing bug of  `underscore.string`: esamattis/underscore.string#418
`gatsby-transformer-remark` had the same issue before: see #6916. Here I literally take the same solution as in the PR for that issue: `truncate` option to use lodash's `truncate` function.
Checked on [`gatsby-starter-blog-mdx`](https://github.com/hagnerd/gatsby-starter-blog-mdx) with `gatsby-dev`.
#22390
#6916
=> fix(gatsby-plugin-mdx): Truncate non-latin language excerpts correctly

packages/gatsby-cli/src/reporter/__tests__/patch-console.ts, packages/gatsby-cli/src/reporter/patch-console.ts, packages/gatsby-cli/src/reporter/reporter.ts
Fixes gatsby-cli. Currently it's doing this:
```
success run queries - 0.050s - 2/2 39.61/s
undefined
You can now view gatsby-starter-hello-world in the browser.
undefined
http://localhost:8001/
undefined
View GraphiQL, an in-browser IDE, to explore your site's data and schema
undefined
http://localhost:8001/___graphql
undefined
Note that the development build is not optimized.
To create a production build, use gatsby build
undefined
success Building development bundle - 3.567s
```
This is because of typescript forcing us to seperate the args, we were then passing undefined into util.format instead of nothing
=> fix(gatsby-cli): Address an issue that caused empty logs to print undefined

docs/docs/using-cloudinary-image-service.md
=> chore(docs): 🧹 Remove whitespace from Markdown link

.circleci/config.yml
Run `yarn run-all sync` in the "weekly i18n sync" workflow to test that nothing goes wrong with doing run-all.
=> test (.circleci): Test `run-all sync` functionality

scripts/i18n/sync.js
Add the `sync` label even when the conflicts PR isn't created.
=> fix (scripts/i18n) Add label to the sync PR even if no conflicts

packages/gatsby/src/redux/__tests__/index.js, packages/gatsby/src/redux/persist.ts
This PR is a copy of https://github.com/gatsbyjs/gatsby/pull/23005 by @drmats + a fix for the test cases. Copy paste from that PR:
Using `fs.renameSync(oldpath, newpath)` throws `EXDEV: cross-device link not permitted` error when `oldpath` and `newpath` are not on the same mounted filesystem. [`moveSync()`](https://github.com/jprichardson/node-fs-extra/blob/master/lib/move-sync/move-sync.js) from `fs-extra` package addresses this.
This patch uses it to rename redux cache directory.
Fixes #22999
=> fix(gatsby): Use `moveSync` over `renameSync` to fix cross mount cases

packages/gatsby-plugin-sitemap/src/__tests__/internals.js, packages/gatsby-plugin-sitemap/src/internals.js
#21948 broke custom data queries and only passed required data. This PR correctly filter's the required data and passes the other queried data 
fixes #22703
=> fix(plugin-sitemap): missing data in query results

packages/gatsby/src/bootstrap/__tests__/requires-writer.js, packages/gatsby/src/bootstrap/requires-writer.js
Ensure component order - and therefore the build hash - is deterministic when writing out `.cache/async-requires.js`. When using page build optimisation, this ensures pages are not rebuilt when no content or code has changed.
Fixes #22964
=> fix: Ensure component order is deterministic

packages/gatsby/src/query/queue.js
Query resolvers can hang indefinitely right now which can be confusing to debug as there's no indication of what's happening.
With a timeout set, eventually the hanging query will fail with an error like this which should help people figure out where to investigate.
From investigation of https://github.com/gatsbyjs/gatsby/issues/23033
=> fix(gatsby): Set a timeout of 15 seconds on queries

packages/gatsby/src/bootstrap/schema-hot-reloader.ts, packages/gatsby/src/commands/develop.ts
**tl;dr** This PR fixes an issue with schema rebuilding in `__refresh` endpoint by moving rebuild call from schema hot reloader directly to `__refresh` controller.
Schema rebuilding (introduced in #19092) is triggered in two situations:
1. When `__refresh` endpoint is hit
2. When nodes change outside of `sourceNodes` API, usually via some watcher (e.g. when editing a file)
Originally we handled both cases in a single `schemaHotReloader` which listened for a special event `API_RUNNING_QUEUE_EMPTY` and tried rebuilding the schema if needed.
But the `API_RUNNING_QUEUE_EMPTY` event proved to be problematic for `__refresh`. The expected sequence of actions in `__refresh`:
1. Call `createSchemaCustomization`
2. Call `sourceNodes`
3. Rebuild schema
But `createSchemaCustomization` trigger …
=> fix(gatsby): call schema rebuild manually on __refresh

benchmarks/source-wordpress/package.json
This fixes build timeouts and errors related to media file sourcing
=> chore(wordpress-benchmark): upgrade to latest packages and remove unneeded packages

scripts/check-ts.js
Gives us some context on how our migration is going. `yarn typecheck` will give output like this:
```
TS Check: Running...
TS Check: Checking ./packages/babel-preset-gatsby 
- TS Files: 1 
- JS Files: 4 
- Percent Converted: 20%
TS Check: Checking ./packages/gatsby 
- TS Files: 82 
- JS Files: 202 
- Percent Converted: 28.9%
TS Check: Checking ./packages/gatsby-cli 
- TS Files: 27 
- JS Files: 16 
- Percent Converted: 62.8%
TS Check: Checking ./packages/gatsby-core-utils 
- TS Files: 16 
- JS Files: 1 
- Percent Converted: 94.1%
TS Check: Checking ./packages/gatsby-image 
- TS Files: 0 
- JS Files: 3 
- Percent Converted: 0%
TS Check: Checking ./packages/gatsby-link 
- TS Files: 0 
- JS Files: 4 
- Percent Converted: 0%
TS Check: Success
- Total TS Files: 230 
- Total JS Files: 230 
- …
```
=> chore(scripts): Add conversion metrics to typecheck command

docs/docs/building-an-e-commerce-site.md
Access the page in question: https://www.gatsbyjs.org/docs/building-an-e-commerce-site/
N/A
N/A
=> chore(docs): fix e-commerce showcase link

packages/gatsby-cli/src/reporter/__tests__/patch-console.ts, packages/gatsby-cli/src/reporter/patch-console.ts
This is a follow up to #23000 where I incorrectly handled falsy values.
=> fix(gatsby-cli): Fix console methods incorrectly handling falsy values

docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md
changes:
- fix brand names from `Node`:`Node.js` and `github`:`GitHub`
- #22561 `chore(tutorial):Add DatoCMS/Snipcart tutorial`
=> fix brand names

docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md
changes:
- remove domain from internal links 
- put links to localhost into code blocks
- escape the ` 
- #22561 `chore(tutorial):Add DatoCMS/Snipcart tutorial`
=> fix(tutorial): Add DatoCMS/Snipcart tutorial - fix links

docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md
changes:
- fix casing in Image Captions: start with uppercase like all other captions in new blowposts/docs
- fix one word `selecting` from uppercase to lowercase
- #22561 `chore(tutorial):Add DatoCMS/Snipcart tutorial`
=> fix(tutorial): fix casing in Image Captions
