- www/src/components/navigation-mobile.js
Fix the text not showing up on mobile navigation
Before:
After:
> fix (www) Fix mobile nav bar text

- docs/tutorial/building-a-theme.md
This was born out of a community question. Our example code for theme authoring sets default values in gatsby-config and gatsby-node. Both options are valid, but a theme author only needs to do one. Adding a note to that effect.
> Make a note about duplicate behavior in theme authoring

- docs/docs/security-in-gatsby.md
changes:
- fix code block language from `js` to `jsx`, and `js` to `html`
- fix intend
- #22395 `Docs/security in gatsby`
> fix(docs): security in Gatsby - fix code block language

- docs/docs/security-in-gatsby.md
changes:
- brand names
- #22395 `Docs/security in gatsby`
> fix(docs): security in Gatsby - fix brand names

- packages/gatsby/src/query/queue.js
Reverts gatsbyjs/gatsby#23036
This breaks builds for several users of Gatsby. In addition, this causes a structured error that isn't defined in a structured error map, causing broken stacktraces.
> Revert "fix(gatsby): Set a timeout of 15 seconds on queries"

- packages/gatsby/src/schema/__tests__/node-model.js
Gatsby [allows](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/db/sanitize-node.js#L72) storing `Date` instances in node fields. But `sift` filtering seems to be broken in this case as it requires filters to be passed as `Date` instances ([docs](https://github.com/crcn/sift.js#date-comparison))
The problem is that we don't know how a date field is stored when querying (as `string` or as a `Date` instance). So we can't adjust filters accordingly.
Ideally, we should disallow `Date` instances or always convert them to `string` when sanitizing. But that would be a breaking change.
So, for now, I just added a failing test but we should address it in the next major.
> chore(gatsby): Test sift filtering on date instances (skipped for now)

- docs/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/index.md
changed:
- brandname from `GatsbyjS` to `Gatsby
- brandname from magmutual.com to MagMutual.com (like other MagMutual.com on the page)
- fixed link from `http` to `https`
- #22602 `Blog case study mag mutual`
> fix(blog): MagMutual - brand names

- packages/gatsby-source-graphql/package.json
- packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
- packages/gatsby-source-graphql/src/gatsby-node.js
- packages/gatsby-source-graphql/src/transforms.js
- yarn.lock
GraphQL Tools Fork was merged into GraphQL Tools v5
> chore(gatsby-source-graphql): Use GraphQL Tools again

- www/src/components/sidebar/section-title.js
- www/src/data/locales/en/messages.po
- www/src/data/locales/ja/messages.po
Fix the aria-label for the section toggles in the sidebar. The issue was that the lingui macro wasn't triggering correctly because there was a conditional inside the `i18n._` call.
Before:
After:
> fix(www) Fix translated aria-label for sidebar section toggles

- packages/gatsby-plugin-google-analytics/README.md
It will save time if users have DNT enabled and forgets to turn off.
> Update README.md suggestions for DNT

- packages/gatsby-theme-blog/src/components/post-date.js
- packages/gatsby-theme-blog/src/components/post-link.js
- packages/gatsby-theme-blog/src/components/post-list.js
- packages/gatsby-theme-blog/src/components/post-title.js
- packages/gatsby-theme-blog/src/components/post.js
- packages/gatsby-theme-blog/src/components/posts.js
- packages/gatsby-theme-blog/src/components/seo.js
This will improve the extensibility for users that want to use component shadowing because they can extend/customize components at a [more granular level](https://johno.com/component-organization-with-gatsby-themes/).
Since this PR is only splitting up components it _shouldn't_ be a breaking change because any existing usages of shadowing by end users would be shadowing further up the component tree already.
> feat(gatsby-theme-blog): Refactor some larger components to be smaller

- docs/contributing/docs-contributions.md
A follow up for prettier upgrade #22520. Fixes a minor issue with docs formatting that leaked through: https://github.com/gatsbyjs/gatsby/pull/22520#discussion_r408975839
> fix(docs): Prevent invalid prettier formatting in docs

- docs/docs/recipes/deploying-your-site.md
changes:
- #22648 `Recipe google analytics` 
> fix(docs): recipe google analytics -  fix 404 link

- packages/gatsby-source-medium/src/gatsby-node.js
Use createSchemaCustomization for explicit type declarations in `gatsby-source-medium` plugin.
Umbrella issue => #20069
> feat(gatsby-source-medium): define types explicitly via createSchemaCustomization (#20069)

- docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
changes:
- brand names:
- ASP.Net -> ASP.NET
- .net -> .NET
- Stackpath -> StackPath
- github -> GitHub
- cms -> CMS
- Casing (because all other usages on this page are `API Keys`)
- API keys -> API Keys 
- #22985 `Add blog post Agility CMS upgrades to Gatsby with author avatar`
> fix(blog): agility - fix brand names

- packages/gatsby-plugin-google-analytics/src/index.js
Google defines all the tracked events in Google Analytics as interactive per default. In current implementation of plugin the `nonInteraction` parameter of `trackCustomEvent` has default value of `true` which is opposite of default implementation.
To follow the Google documentation `nonInteraction` parameter has to be set to `false`.
[Google Analytics Documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#non-interaction_events)
> [gatsby-plugin-google-analytics] Set nonInteraction param default value to false

- starters/default/package-lock.json
- starters/default/package.json
- starters/default/src/components/seo.js
Remove warning caused by pre-v6 `react-helmet` in default starter (see #17865)
#17865
Closes #17865
cc @lannonbr
> fix(starters): Upgrade react-helmet in default starter

- www/src/components/sidebar/accordion.js
Change the sidebar accordion to use JSX conditionals instead of `display: none` to hide child nodes.
This makes the docs page more "snappy" when switching between pages (when the sidebar isn't fully expanded) since the page does not need to load the full sidebar hierarchy.
> perf(www): Change the way child items are hidden in the docs sidebar

- packages/gatsby-plugin-sharp/src/plugin-options.js
The validation of Sharp's trim option is wrong, it turns `trim` into a boolean instead of keeping it float.
```graphql
allEntity {
nodes {
logo {
file {
childImageSharp {
fixed(height: 70, trim: 10) {
...GatsbyImageSharpFixed
}
}
}
}
}
}
```
> fix(gatsby-plugin-sharp): trim option failed

- packages/gatsby-plugin-sharp/src/index.js
This adds an error when dimensions for an image can't be determined. This happens when a file is corrupt. Previously the only error we got was `TypeError: Cannot read property 'width' of null`. I explored using another image dimensions package that gives us more meaning errors but it was giving other unrelated errors and seems like a risky change. Since the current package returns null if it can't find dimensions, I just error on null dimensions here and provide a generic message.
> fix(gatsby-plugin-sharp): error if we can't determine dimensions for image

- packages/gatsby-cli/package.json
- packages/gatsby-cli/src/create-cli.js
- packages/gatsby-cli/src/recipes.ts
- packages/gatsby/package.json
- packages/gatsby/src/commands/types.ts
There is no reason to have gatsby-recipes part of gatsby, we should only add it to gatsby-cli.
Waiting for https://github.com/gatsbyjs/gatsby/pull/23188 to be merged
> chore(gatsby-cli): move recipes out of gatsby

- docs/docs/glossary.md
- docs/docs/glossary/yarn.md
- www/src/data/sidebars/doc-links.yaml
Included sections on installing Yarn, using Yarn to install Gatsby, and using Yarn instead of npm as the default package manager.
- Updated glossary.md, and doc-links.yaml to point to new piece.
- Added a description to the front matter.
> docs/glossary: Add Yarn glossary entry.

- benchmarks/mdx/package.json
This PR upgrades to the latest `willit` data generator so we can use the `--use-pregenerated-data` flag and keep the mdx benchmark data consistent.
> chore(gatsby-benchmark-mdx): update mdx benchmark packages to use pregenerated data

- packages/gatsby-design-tokens/src/theme-gatsbyjs-org.js
Edit the color of the social links to be more accessible, based on [feedback](https://github.com/gatsbyjs/gatsby/pull/22955#issuecomment-613366389) from #22955.
> enhancement(gatsby-design-tokens): improve the color of social links

- packages/gatsby-recipes/recipes/gatsby-plugin-layout.mdx
Update path to layout component to pull source from raw gist instead of the parent page.
> fix(recipes): adjust path to layout component

- packages/gatsby-remark-prismjs/src/index.js
As @muescha mentioned in https://github.com/gatsbyjs/gatsby/pull/22899#issuecomment-614058668
https://github.com/gatsbyjs/gatsby/blob/2a7cb8c10dff4f847ca8e13db2486ad877c80dfb/packages/gatsby-remark-prismjs/README.md#L209-L210
#22899
> fix(gatsby-remark-prismjs): Update useCommandLine

- packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js
- packages/gatsby/src/bootstrap/resolve-module-exports.js
See #21382
This change adds an error that then will look like:
```
ERROR #11329 
Your plugins must export known APIs from their gatsby-ssr.js.
See https://www.gatsbyjs.org/docs/ssr-apis/ for the list of Gatsby ssr APIs.
- Your local gatsby-ssr.js is using the API "export default [optional-name]" which is not a known API.
```
IMO the `default export` message should be enough to lead to the right solution.
I couldn't directly find a fitting doc to put this info into, any suggestions?
Fixes #21382
> fix(gatsby): Throw error on default export in gatsby-ssr/browser

- docs/docs/graphql-concepts.md
Fixes #23255
Apollo re-did their blog and apparently their redirect doesn't work for this link. So replacing it with the working link.
> fix(docs): Link to apollo blog

- docs/docs/recipes/styling-css.md
There was a small part in the `styling-css` recipe docs that was misleading.  It stated you could `require()` your CSS in `gatsby-config` to use it globally in your site.  This just changes it to say `gatsby-browser` instead of `gatsby-config`.
Closes #23236
Related: #23039
> fix(docs): change gatsby-config mention for global CSS import

- docs/docs/data-fetching.md
The changes introduced by this PR include some changes that were asked to be made 
to the https://www.gatsbyjs.org/docs/data-fetching/ page. One change was to add a comment
in the code example stating that the nameWithOwner and url fields are arbitrary fields from the data, and another change was to add a line explicitly stating that node fields can be arbitrary.
This issue is concerned with the Gatsby GraphQL docs and is located on this [page](https://www.gatsbyjs.org/docs/data-fetching/)
Addresses #21962
> docs: added details signifying that node fields can be arbitrary

- docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
- fix links to localhost in to code blocks
- #22985 `Add blog post Agility CMS upgrades to Gatsby with author avatar`
> fix(blog): agility - fix local links

- docs/contributing/docs-and-blog-components.md
- docs/docs/gatsby-lifecycle-apis.md
- docs/docs/graphql-concepts.md
- docs/docs/overview-of-the-gatsby-build-process.md
- www/src/components/layer-model/component-model/index.js
- www/src/components/layer-model/image-model/index.js
- www/src/components/layer-model/layer-model.js
After merging #23115, we realized there were a couple of places in the docs still referencing the `LayerModel` component which should now be referencing `ComponentModel`. 
While `LayerModel` was abstracted so that it could be reused in that PR, the documentation on it in `docs-and-blog-components.md` also needed to be updated to reflect the new `ComponentModel`. Notably missing in this PR is documentation on how to construct a _new_ component from `LayerModel`. I don't know how much we necessarily want to encourage that vs make it an _option_, so I left this page pretty much intact.
> chore(docs): Reference new ComponentModel component rather than generic LayerModel

- docs/blog/2020-04-02-community-qa-with-kyle-mathews/index.md
changes:
- brand names
- #22737 `Add blog post for community Q&A`
> fix(blog): Q&A - fix brand names

- www/src/components/sidebar/__tests__/sidebar.js
- www/src/components/sidebar/sidebar.js
Follow-up to #23301.
* Use `||` instead of `??` for proper resolution.
* Modified a test to account for the bug before.
The implemented solution resulted in a bug where clicking on a link won't expand the hierarchy for that link if coming from another page. To repro, go to any page on the gatsby docs and go to a different page in a different hierarchy (for example, from /docs/recipes/ to /docs/reference-guides).
> fix(www): Fix sidebar expansion behavior

- packages/gatsby-recipes/README.md
> chore(gatsby-recipes): Update README typo

- packages/gatsby-plugin-mdx/gatsby/on-create-page.js
- packages/gatsby-plugin-mdx/gatsby/preprocess-source.js
- packages/gatsby-plugin-mdx/utils/gen-mdx.js
Currently the `remarkPlugins` field in `gatsby-plugin-mdx` doesn't support using plugins with the second argument `file`. This PR add support by passing [`filepath`](https://github.com/mdx-js/mdx/blob/790d8e3fa86221482f42419eb8458ebc8747f966/packages/mdx/index.js#L106-L108) in mdx. Results in creating a `vfile` instance when applying mdx.
N/A
N/A
> [gatsby-plugin-mdx] Add support for file argument in remark plugins

- benchmarks/markdown_id/package.json
- benchmarks/markdown_id/scripts/data-update.ts
- benchmarks/markdown_slug/package.json
- benchmarks/markdown_slug/scripts/data-update.ts
- benchmarks/markdown_table/package.json
- benchmarks/markdown_table/scripts/data-update.ts
- benchmarks/mdx/package.json
- benchmarks/mdx/scripts/data-update.ts
- benchmarks/source-contentful/package.json
- benchmarks/source-contentful/scripts/data-update.ts
- benchmarks/source-datocms/package.json
- benchmarks/source-datocms/scripts/data-update.ts
- benchmarks/source-wordpress/package.json
- benchmarks/source-wordpress/scripts/data-update.ts
This adds a noop `data-update` script (https://github.com/gatsbyjs/gatsby/blob/67730fdfa8fa1f123a5999a2ddf9834775f7d98b/benchmarks/source-drupal/scripts/data-update.ts) for the remainder of the benchmarks so that we can safely run `npm run data-update` for any of these benchmarks while testing the Drupal example.
n/a
n/a
> Add noop data update scripts for all benchmarks

- docs/docs/glossary.md
In taking another look at https://github.com/gatsbyjs/gatsby/pull/21378, I saw the word "transpile" and my first thought was "is that in the glossary?" It wasn't, so I added it here. There were already entries for Compilation, Babel, and ECMAScript, so I adjusted some to add the definition of transpilation, which is a type of compilation but is used more specifically with things like TypeScript and Babel. 
N/A
N/A
> [docs] add glossary definition for Transpile

- renovate.json5
Don't renovate types and renovate examples and starters. We should have starters always up to date.
> chore(renovate): Don't renovate types and renovate examples and starters

- docs/sites.yml
Remove Markets.com: Now on WordPress
Remove Equithon: Site no longer online
Remove source_url for The Bastion Bot
Remove manu.ninja: No longer a Gatsby site
Remove Sindhuka: Site no longer online
Remove Fourpost: Site no longer online
> chore(showcase): Showcase Cleanup

- packages/gatsby-recipes/README.md
- packages/gatsby-remark-autolink-headers/README.md
- packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
- packages/gatsby-remark-autolink-headers/src/__tests__/index.js
- packages/gatsby-remark-autolink-headers/src/index.js
See issue #23250 for full details.
This PR adds a new option to `gatsby-remark-autolink-headers` that enables a user to generate anchors for a subset of header tags, rather than generating anchors for all header tags.
The new option is called `elements`. It is an optional string array:
```js
{
resolve: `gatsby-remark-autolink-headers`,
options: {
elements: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']
},
}
```
Rules:
- If no `elements` option is provided, default to generating anchors for all header elements (this is the current behavior and retains backwards compatibility).
- If `elements` is provided, generate anchors for header elements whose tag appears in the array.
- If `elements` is an empty array (`[]`), do not generate anchors, (we honor the configuration and assume it is deliberately …
> feat(gatsby-remark-autolink-headers): Optionally specify header element types

- docs/sites.yml
Adding a new site to the site showcase on gatsbyjs.org.
The site, Resume on the Web, is my personal portfolio built with GatsbyJS.
**I implore you to please check the site and its source code,  
and consider it to be featured on the official website.**
There is a corresponding PR for my Creator Profile as well, #23370 which links this site.
```yaml
- title: Resume on the Web
main_url: https://amruthpillai.com
url: https://amruthpillai.com
source_url: https://github.com/AmruthPillai/ResumeOnTheWeb-Gatsby
description: >
Everyone needs their own little spot on the interwebs, and this is mine. Welcome to my resume, on the web!
categories:
- Blog
- Design
- Freelance
- Gallery
- JavaScript
- Landing Page
- Mobile Development
- Open Source
- Photography
- Portfolio
- Technology
- Web …
```
> chore(showcase): add Resume on the Web

- packages/gatsby-recipes/recipes/eslint.mdx
Like it mentioned [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-recipes#props-4), the content url of `<File />` should be to the raw of a gist instead.
Related to #22991
> fix(gatsby-recipes): link to the raw gist of .estlintrc.js

- packages/babel-preset-gatsby-package/tsconfig.json
We closed #22039 realizing that package doesn't benefit from conversion. This removes the tsconfig.json, meaning we don't check it with tsc anymore.
> chore(gatsby-preset-gatsby-package): Remove tsconfig.json

- www/src/components/search-form/__tests__/search-form.js
- www/src/components/search-form/search-form.js
Basically this PR fixes a bug described in #21705.
You can find more details on the solution in the thread on an issue.
Fixes #21705
> fix(www): tweak docsearch to init algolia when tabbed into

- packages/gatsby/src/query/graphql-runner.ts
- packages/gatsby/src/redux/run-sift.js
We want to know how frequent the fast indexes fail to find anything when they're actually supposed to find something. This is currently not tracked and leads to skewed/incomplete results. By counting how frequent Sift finds something when fast indexes fail or bail, we can get more relevant insight into how well fast indexes are actually performing, and/or whether we need to start thinking about eliminating Sift altogether to prevent having to fall back on it for empty sets. tbd.
> chore(gatsby): count sift hits in telemetry

- renovate.json5
Update renovate config so that:
1. We have clear update groups (packages/www/starters+examples), remove unnecessary groups.
2. Dependency rules apply to all groups
3. We don't update @types by default
> Improve renovate

- packages/gatsby-plugin-typescript/README.md
I hope this isn't too heavy-handed, but I think that philosophically, this plugin doesn't provide "support" for typescript at all, it just disables it. Typescript _is_ type checking! I admit I don't fully understand the scope of this plugin, but I'm aware of a great number of people on unrelated projects who thought gatsby was doing type checking on build after installing this plugin.
This is it :)
Native TypeScript support #18983
> chore(docs): Be more vocal about not doing type checking

- packages/gatsby-theme-blog/src/components/post-footer.js
- packages/gatsby-theme-blog/src/components/post-link.js
- packages/gatsby-theme-blog/src/components/post.js
HTML for `gatsby-starter-blog` was updated in https://github.com/gatsbyjs/gatsby/pull/16557. This ports those same changes to `gatsby-theme-blog`. The original description of the changes,
> - Wrap whole blog post in `<article>`
> - Wrap blog post header details in `<header>`.
> - Wrap blog post content itself with `<section>`.
> - Wrap footer navigation to next/previous posts in `<nav>`.
> As I was looking at tweaking some of the blog post rendering for my new site using Gatsby, I noticed that the markup used in the blog starter didn't seem to be using as semantic a markup set as it could be. This PR should theoretically make the markup more accessible to screen readers, etc, although I've not had a chance to personally verify this.
No documentation changes necessary. …
> refactor(gatsby-theme-blog-core): Use more semantic HTML for articles

- packages/gatsby-recipes/recipes/theme-ui.mdx
- packages/gatsby-recipes/src/cli.js
- packages/gatsby-recipes/src/recipe-machine.js
closes https://github.com/gatsbyjs/gatsby/issues/23360
> feat(gatsby-recipes): While apply a step, show the time elapsed after 10 seconds

- packages/gatsby-recipes/src/__snapshots__/validate-recipe.test.js.snap
- packages/gatsby-recipes/src/validate-recipe.js
- packages/gatsby-recipes/src/validate-recipe.test.js
Currently, if you attempt to use an unknown component/resource in your recipe it silently fails. This will make it more obvious if you make a typo or use a component we don't currently support.
> fix(gatsby-recipes): Raise an error when an unknown resource is used

- .circleci/config.yml
- .jestSetup.js
- jest.config.js
- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
- packages/gatsby-recipes/src/providers/utils/get-diff.js
- yarn.lock
* Strip ansi colors on diff during tests
* Use tmpdir to run fixtures
* Fix snapshots having wrong fixture formatting
> Fix recipe test problems

- www/src/components/showcase-details.js
- www/src/views/showcase/filtered-showcase.js
This PR makes the showcase modal work in consistent with selected filters in the showcase list. Closes #21467 
Before:
After:
Couple of questions:
1. I've directly exported the `filterByCategories` function from `filtered-showcase.js` -- should it be moved to some util and be used in both these components?
2. I've changed the query in `showcase-details.js` to include `edges` (instead of directly querying `nodes`) to make it work with `filterByCategroies` function. We could also modify the query for the showcase list to just get `nodes` instead of `edges` and refactor `filterByCategories`, but it'll make this PR slightly bigger. If that's preferred, can it be done in a follow-up PR?
> www: Persist filters on Site Showcase in opened modals

- packages/gatsby/src/schema/infer/build-example-data.ts
- packages/gatsby/src/schema/infer/inference-metadata.ts
- packages/gatsby/src/schema/infer/type-conflict-reporter.ts
Migrated `schema/infer/build-example-data` to TypeScript. As with a previous PR (#23264), I've switched off the complaints about using a function before defining it in order to help with the diff.
ref #21995
> chore(gatsby): Migrate build-example-data to TS

- packages/babel-plugin-remove-graphql-queries/src/index.js
- packages/gatsby/src/query/file-parser.js
This fixes a bug where the GrahpQL query extractor chokes on particular syntax because of possible `unidentified` fields.
Fixed this by explicit checks on these fields.
Fixes: #21212
> Fix graphql extraction error

- packages/babel-preset-gatsby/src/__tests__/optimize-hook-destructuring.js
- packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts
This fixes hook destructuring for cases when some elements are skipped - for example:
```
const [, setCount] = useState(0);
```
Fixes #23413
> fix(optimize-hook-destructuring): handle skipped items

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/joi-to-graphql/helpers/joi-to-graphql.js
- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/fixtures/gatsby-starter-blog/gatsby-config.js
- packages/gatsby-recipes/src/providers/gatsby/plugin.js
- packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
- packages/gatsby-recipes/src/providers/gatsby/utils/build-plugin-node.js
- packages/gatsby-recipes/src/providers/gatsby/utils/build-plugin-node.test.js
- packages/gatsby-recipes/src/providers/gatsby/utils/constants.js
- packages/gatsby-recipes/src/providers/gatsby/utils/get-object-from-node.js
- packages/gatsby-recipes/src/providers/gatsby/utils/get-object-from-node.test.js
- packages/gatsby-recipes/src/providers/gatsby/utils/is-default-export.js
- packages/gatsby-recipes/src/providers/resource-schema.js
- yarn.lock
Adds initial support for plugin options (#23299). This functionality won't address config options that contain javascript.
~~Before this is deemed truly stable we will also need to implement a resource identifier for the GatsbyPlugin resource because there's no way to handle plugins that are composed together (#23300).~~ This PR now adds support for [keyed values for gatsby plugin config](https://github.com/johno/gatsby/pull/1)
> feat(gatsby-recipes): Allow for basic config objects in plugin resource

- packages/gatsby-recipes/package.json
It's an optionalDependency of gatsby-cli so mostly/kinda worked accidentally. Let's depend on it for realz.
> fix(gatsby-recipes): add missing dependency

- packages/gatsby-recipes/recipes/mdx-pages.mdx
Mistake source plugin in recipe docs. Was meant to say `gatsby-source-filesystem` instead `gatsby-source-wordpress`
> fix(gatsby-recipes): Fix wording in mdx pages recipe

- packages/gatsby-theme-notes/src/templates/note.js
In #23229 we removed problematic (`npm audit`) `gatsby-plugin-og-image` from deps and config, but we didn't adjust the code itself to not make use of it. This removes query and allow starter to build.
For reference - https://circleci.com/gh/gatsbyjs/gatsby/387504?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link this is example where bumping `gatsby-theme-notes` to newest version (with removed dependency) breaks the build for `gatsby-starter-theme-notes`
I didn't see any actual usage in theme or our starter - but this might be breaking change to theme, because the `Note.js` (which can be shadowed) no longer will get `image`.
Follow up to #23229
> fix(gatsby-theme-notes): remove ogImage from query

- packages/gatsby/src/utils/webpack.config.js
In some cases `@pmmmwh/react-refresh-webpack-plugin` will not be hoisted in root `node_modules`. Because this is imported in `cache-dir` (which is copied to `<project_dir>/.cache`) in https://github.com/gatsbyjs/gatsby/blob/74463e927210bd3b2ff32a1f9d06fd3966a9b82a/packages/gatsby/cache-dir/error-overlay-handler.js#L1
We need to make sure this will be resolved. We do this by nudging webpack to exact location it is installed in (resolving this in `gatsby` package code/context will ensure it because it is `gatsby` package that have it in dependencies - https://github.com/gatsbyjs/gatsby/blob/74463e927210bd3b2ff32a1f9d06fd3966a9b82a/packages/gatsby/package.json#L22)
Fixes #22250
Fixes #22684
> fix(webpack): ensure resolution of react-refresh-webpack-plugin

- docs/docs/porting-an-html-site-to-gatsby.md
- docs/tutorial/part-eight/index.md
- docs/tutorial/seo-and-social-sharing-cards-tutorial/index.md
The SEO component code snippet was causing a gatsby build warning and error in my environment. Adding brackets around Helmet resolves the issue.
> chore(docs): Fix react-helmet named import

- benchmarks/markdown_id/package.json
- benchmarks/markdown_slug/package.json
- benchmarks/markdown_table/package.json
- benchmarks/mdx/package.json
- benchmarks/source-contentful/package.json
- benchmarks/source-datocms/package.json
- benchmarks/source-drupal/package.json
- benchmarks/source-wordpress/package.json
We may be running benchmarks in some platforms in a fashion that would not by default install `devDependencies.` Move all necessary packages to `dependencies`.
n/a
n/a
> Move all benchmark dependencies out of devDependencies

- packages/gatsby-recipes/recipes/mdx-images.mdx
(My) tests are flaky--this pull request adds a missing dependency. 
The CLI throws an error if `/src/images/` doesn't exist (i.e., after running this recipe in an empty `hello-world` project.) Is this okay?
> fix(gatsby-recipes): remove gatsby-transformer-remark package from mdx-images recipe

- packages/gatsby/src/redux/reducers/index.js
- packages/gatsby/src/redux/reducers/static-query-components.ts
- packages/gatsby/src/redux/types.ts
This commit migrates the `static-query-components` reducer to TypeScript with few adjustments to the existing IGatsbyState interface.
The main adjustment is the update of the type of the key used for the map storing each static query from `number` to `string`.
This change reflect the fact that the key is described as being the `id` field of the interface, and this field is described as a `string` in the object definition.
Relates to #21995
> chore(gatsby): migrate static-query-components reducer to TypeScript

- docs/sites.yml
Remove Hyperplay: Site's had an expired cert for 2 months so likely no longer maintained
Remove Zensum: No longer a Gatsby site
Remove Engleezi: Site's immediately closing on open
Remove Hack Club: Switched to Next
Remove GBT: Site no longer routing to anything
Remove Bululu Eventos: Site no longer routing to anything
Remove Hand in Hand Preschool: Site no longer routing to anything
> chore(showcase): Cleaning up showcase

- packages/gatsby-plugin-mdx/README.md
- packages/gatsby-plugin-mdx/gatsby/source-nodes.js
- packages/gatsby-transformer-remark/.gitignore
- packages/gatsby-transformer-remark/README.md
- packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
- packages/gatsby-transformer-remark/src/__tests__/extend-node.js
- packages/gatsby-transformer-remark/src/extend-node-type.js
- packages/gatsby-transformer-remark/src/utils/time-to-read.js
I've been wanting this for a while (since not everyone reads at 265 wpm) and had some time to work on it this evening.
This PR makes `timeToRead` calculation user configurable. I went with the simple solution to start.
```js
{ 
// Mimics a reading rate of 42 words per minute
timeToRead: (wordCount, html, md) => wordCount / 42
}
```
It would make sense to give the user more access to the markdown node for more flexible and precise calculation (e.g. code samples and complex graphs). I was thinking this could look like 
```js
{
timeToRead: (wordCount, { markdownNode, getAST, getMarkdownAST, getHeadings, getTableOfContents, getHTMLAst, getHTML, getExcerptAst, getExcerpt }) => wordCount / 42
}
```
It essentially gives access to all of the `markdownNode` field resolvers. `wordCount` would now …
> feat(gatsby-transformer-remark, gatsby-plugin-mdx) Make timeToRead configurable

- packages/gatsby/src/schema/__tests__/run-query.js
This improves the filter tests. It makes them more rebust and less tightly-coupled with the test data set. It will check for each test whether there were nodes (if some were expected) and, if so, whether they indeed match the filter. Rather than just checking whether `id=1` or something, which may change if somebody changes the data set.
Some new tests were added as well around `null` checks and ordering.
No runtime semantics were changed.
> chore(gatsby): Update filter tests

- docs/docs/add-custom-webpack-config.md
changes: 
- brandnames:
- eslint -> ESLint
- typesscript -> TypeScript
- JS -> JavaScript
- file name in code fences
- fix code language
- add title to code block
- #22750 `Added doc for absolute import from gatsby eslint rules or other tools`
> fix(docs): add webpack - brand names, code language, code fences

- docs/tutorial/part-four/index.md
Changed `components**—in` to  `components** -- in` for consistency, as found on lines 213 and 291
Closes #23487
> Update to Index.md

- docs/docs/glossary/hydration.md
Hi, There was a word repeating issue in [the hydration document page](https://www.gatsbyjs.org/docs/glossary/hydration/):
I removed the duplicate "a clicking".
This exists on [the glossary hydration page.](https://www.gatsbyjs.org/docs/glossary/hydration/)
> chore(docs): Remove duplicate words from hydration.md

- docs/docs/add-seo-component.md
Was there a specific reason this was made all uppercase? We keep all code in the monorepo lower case as different OSs treat case differently and it gets confusing to have an import work with the wrong case on e.g. a mac & then fail on a Linux build system.
> Use lowercase for component file names

- www/__mocks__/gatsby.js
When window.location is updated due to a click event on an `a` tag with an
href attribute, jsdom was logging an error to the console even though the tests
were passing.
This wraps the onClick prop passed to the `Link` mock in a function that prevents
the default behavior of the click, so that we can test the onClick
callback's behavior without triggering an update to window.location.
Just test maintenance, no doc updates. 
There's still a warning about using `componentWillMount`, but I think that's coming from `react-side-effect`, which is pulled in by `react-helmet`. `react-helmet` was updated to a new major version a few weeks ago that pulls in a new version of `react-side-effect` which shouldn't have that deprecation warning anymore. I can try pulling in that update too, but I wasn't …
> chore(www): Prevent default click behavior on Link mock

- CODEOWNERS
This moves ownership of blog content on gatsbyjs.org from learning team to content team. There will be some overlap in learning and content team members.
---
Notes about CODEOWNERS ( from https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners ):
> Order is important; the last matching pattern takes the most precedence.
Which means that added rule for `/docs/blog/` below `/docs/` one, will overwrite it, making "content" team sole owner of this part of repository
> chore(CODEOWNERS): assign `/docs/blog/` to content team

- packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
- packages/gatsby/src/redux/__tests__/__snapshots__/status.js.snap
- packages/gatsby/src/redux/__tests__/status.js
- packages/gatsby/src/redux/reducers/index.js
- packages/gatsby/src/redux/reducers/status.ts
- packages/gatsby/src/redux/types.ts
This commit migrates the status reducer to TypeScript by adding the relevant types for each actions.
In order to make sense of the condition protecting the `SET_PLUGIN_STATUS` action, I had to transform the `&&` operator to `||`. Without this change, the typecheck would fail. But in the end, it should not change the behaviour of this early-termination.
> chore(gatsby): migrate status reducer to TypeScript

- packages/gatsby/src/schema/infer/__tests__/inference-metadata.ts
- packages/gatsby/src/schema/infer/build-example-data.ts
- packages/gatsby/src/schema/infer/inference-metadata.ts
We've caught a small bug while converting inference metadata to Typescript in #23539 
It affects dirty checking of the schema when a referenced node changes (when using `___NODE` convention)
Before this PR changes to referenced nodes are not detected, after this PR those changes are detected by Gatsby (and schema is rebuilt if actually dirty)
#23264
#23389
> fix(gatsby): fix dirty check for inference metadata with related nodes

- packages/gatsby-transformer-remark/.gitignore
https://github.com/gatsbyjs/gatsby/pull/19763/files removed `utils` from the .gitignore.
But now a `yarn bootstrap` will yield build files in a commit:
> chore(gatsby-transformer-remark): Re-Add `utils` to .gitignore

- packages/gatsby-cli/package.json
- packages/gatsby-cli/src/init-starter.ts
- yarn.lock
They were missing before, adding them improves type safety and
removes one "any" type from the codebase
No changes needed
> chore(gatsby-cli) Add TypeScript definitions for hosted-git-info

- docs/starters.yml
Repo: https://github.com/SaimirKapaj/gatsby-markdown-personal-website
Demo: https://gatsby-markdown-personal-website.netlify.app
Images used in the project are downloaded from https://unsplash.com/
PS. The starter is based on https://github.com/SaimirKapaj/gatsby-markdown-typescript-personal-website starter (from the same author).
> chore(starters): add gatsby-markdown-personal-website

- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/plugin.js
- packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
> feat(gatsby-recipes): Create default gatsby-config.js when installing a plugin if one doesn't exist

- www/package.json
Pins version of gatsby-plugin-mdx to avoid OOMing issues caused by generating HTML for timeToRead.
"Fixes" #23614, but temporarily until we fix the underlying issue.
Relates to #23614
> chore: pin version of gatsby-plugin-mdx

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
This is the same implementation as the `lte`, in reverse.
In my benchmark it definitely shows an improvement but only by 1.5x and that is affected by the random input data distribution. I don't have a proper benchmark for this. Regardless, there's definitely a consistent improvement and it should do the same as it did for `lte`.
> perf(gatsby): support fast filters for gte

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/schema/__tests__/run-query.js
This is a quick fix for the binary search of fast filters which was incorrectly setting the next pivot.
Added tests and confirmed that they cover this failure. This code will be improved but this is a hotfix to mitigate the core problem as reported by @reltuk in #23625
The bug is that the next pivot is not properly adding `min` and so it always just moves to the left, ultimately leading to an empty result if the result would be high, or worse, an infinite loop.
> fix(gatsby): fix binary search incorrectly setting next pivot + tests

- packages/gatsby/src/utils/webpack.config.js
Granular chunks was bound by async requests of 6, this could lead to bundle bloat. I had to set it to Infinity to make sure we never hit that limit. One downside is that the limit of initial 25 requests can be broken now. I'm pretty sure this will hardly happen.
Fixes https://github.com/gatsbyjs/gatsby/issues/23221
Fixes https://github.com/gatsbyjs/gatsby/issues/23402
> fix(gatsby): add maxAsyncRequests to infinity to reduce bundle size

- examples/using-typescript/package.json
- examples/using-typescript/tsconfig.json
Tweaks some typescript settings to help avoid bundling issues.
closes #23595
> chore(docs): Tweak tsconfig for using typescript.

- peril.settings.json
- peril/rules/apply-triage-needed.ts
This will auto apply "status: triage needed" for all new issues and pull requests.
I tested this on my fork: https://github.com/pieh/gatsby (you can check `peril.settings.json` and rule file). You can open test pr and issue there to verify.
[ch5540]
> chore(peril): auto-apply "status: triage needed" to new issues and pull requests

- docs/categories.yml
- docs/starters.yml
Originally added in https://github.com/gatsbyjs/gatsby/pull/22281 but it doesn't warrant its own category as it's not a major library and another Milligram project was already under Styling:Other
> chore(docs): Remove Milligram category from starters showcase

- packages/gatsby-plugin-sitemap/README.md
Adds a missing letter at the `nodes` word on the [`gatsby-plugin-sitemap`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap)
> Add missing letter at gatsby-plugin-sitemap docs

- scripts/e2e-test.sh
So it doesn't try to globally sudo install it.
> chore(e2e): Make e2e-test check for an installed version of gatsby-dev

- .circleci/config.yml
- package.json
- packages/gatsby-telemetry/src/telemetry.js
- packages/gatsby/src/bootstrap/index.js
- packages/gatsby/src/db/index.js
- packages/gatsby/src/db/loki/__tests__/nodes-query-test.js
- packages/gatsby/src/db/nodes.js
- packages/gatsby/src/redux/__tests__/index.js
- packages/gatsby/src/redux/persist.ts
- packages/gatsby/src/redux/reducers/index.js
This PR prevents Loki from being used anymore within Gatsby.
The PR is only disabling Loki specific code paths, not removing them. That'll be a followup commit that's much more invasive than this one.
Basically, after this commit, `GATSBY_DB_NODES=loki` shouldn't change anything anymore in terms of how Gatsby works.
Also tried to disable circle ci checks for loki.
> chore(gatsby): disable loki stuff without dropping it

- packages/gatsby-transformer-remark/README.md
In the "How to use" section there is an example of what you might put in your gatsby-config.js file.  There is a missing comma at the end of the `timeToRead` value.
(First pull request, hope I'm doing this right.)
This simply adds the comma to the end of the line in the README example.
This is a documentation only change.
> Missing comma in gatsby-transformer-remark README

- packages/gatsby-recipes/recipes/storybook-js.mdx
- packages/gatsby-recipes/src/cli.js
This PR adds a recipe to`packages/gatsby-recipes`. 
The recipe adds Storybook (js) to your Gatsby project. I've named this recipe `storybook-js` as it'll _**only**_ create the Webpack config required for Storybook to work with **JavaScript** Gatsby projects. 
There are some linked "template" files that live on my GitHub... not sure where you're planning on hosting supporting files for recipes so i'm happy to change that if you have feedback?
I have a second recipe in the making which creates the correct Webpack required for Storybook to work with **TypeScript** Gatsby projects.
More info can be found in the [GitHub repo](https://github.com/PaulieScanlon/gatsby-recipe-storybook-js) repo, and I wrote a short blog post explaining how it works …
> add Storybook (js) to recipes

- docs/docs/quick-start.md
This PR replaces the quick-start video in the documentation to not reference `npx`,and remove note in doc for `npx`.  See clubhouse story: https://app.clubhouse.io/gatsbyjs/story/2500/record-new-quick-start-video   
https://www.gatsbyjs.org/docs/quick-start/
N/A
> chore(doc):Re-record Quick Start video to not reference npx, and remove note on doc

- .circleci/config.yml
I broke starters-publish in ci when updating ci workflow in https://github.com/gatsbyjs/gatsby/pull/23303
> chore: fix starters-publish in ci

- .github/workflows/schedule-stale.yml
This adjust the stalebot to ignore issues labeled with `status: triage needed`
I used README from https://github.com/gatsbyjs/stale to see how to define multiple labels. I didn't test it out myself yet (not sure how stable action and README is)
[ch5876]
> chore(stale): add "status: triage needed" to exempt labels

- packages/gatsby-plugin-netlify/src/build-headers-program.js
Minor change that adds a missing space in transformHeader check error message
> fix(gatsby-plugin-netlify): Add missing space in error message

- docs/docs/making-your-site-accessible.md
The `warning` field is supposed to be `warn` for eslint rules.
> chore(docs): Update making-your-site-accessible

- packages/gatsby/src/schema/infer/__tests__/inference-metadata.ts
- packages/gatsby/src/schema/infer/inference-metadata.ts
This is basically a follow up for #23472 which contained a bug resulting in false positives for schema dirty checking (in some edge cases).
N/A
Fixes #23633
> fix(gatsby): Fix dirty check for schema rebuilding

- .circleci/config.yml
`bootstrap` job might short circuit using `assert-changed-files` before it persists workspace, in which case `e2e_tests_pnp` wouldn't have be able to restore anything - see https://circleci.com/gh/gatsbyjs/gatsby/395045?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link - in particular "Attaching workspace" step, which says "persisted no files" (that's because "bootstrap" in this workflow never persisted - https://circleci.com/gh/gatsbyjs/gatsby/395024)
This also will skip running those tests on content only changes
> test(e2e_tests_pnp): check if test should run

- packages/gatsby-plugin-netlify/src/create-redirects.js
Currently if the `_redirects` file includes the header comment, we overwrite it without accounting for any static redirects added by the `static` folder in Gatsby
> fix(gatsby-plugin-netlify): Fix heuristic for appending redirects

- package.json
Right now our git hooks running `eslint --fix` don't handle typescript files - this should fix it 🤞
> chore(lint-staged): add `.ts(x)` files to rule running `eslint --fix`

- docs/tutorial/authentication-tutorial.md
This removes an unnecessary import of `Component` from React in the `PrivateRoute` [section](https://www.gatsbyjs.org/tutorial/authentication-tutorial/#controlling-private-routes) of the authentication tutorial.
Fixes #23721
> fix(docs): Remove unnecessary import in PrivateRoute example

- docs/docs/creating-and-modifying-pages.md
you don't replace the new page with the new but the contrary replace the old page with the new page.
> corrected a typo

- packages/babel-preset-gatsby/src/dependencies.ts
- packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
- packages/gatsby/src/utils/webpack-utils.ts
Apply `babel-plugin-transform-react-remove-prop-types` for dependencies (similar to how we do it in https://github.com/gatsbyjs/gatsby/blob/05151c006974b7636b00f0cd608fac89ddaa1c08/packages/babel-preset-gatsby/src/index.js#L106-L112 already for `src` and themes
This was mostly copy & paste from `index.js` file (with addition of passing `stage` option to this preset)
Discovered in https://github.com/gatsbyjs/gatsby/issues/23550 (but doesn't fix it)
> fix(babel-preset-gatsby): remove prop-types in production for dependencies

- docs/sites.yml
Adds [St. Jude Cloud](https://www.stjude.cloud) to the Gatsby showcase.
N/A
N/A
>  chore(showcase): add St. Jude Cloud to showcase

- docs/features/gatsby-cms-specs.csv
Squarespace is mentioned nowhere else in the features comparison. Not clear what it is doing here. 
Also Stating that wordpress includes built-in hosting is confusing. Wordpress.com is a paid service that offers hosting but it isn't 'built-in' to wordpress. Wordpress and Drupal must be hosted. It's not really an option not to. This category makes more sense for the JAMstack comparison than it does for the CMS one.
_None_
> docs: remove references to squarespace from features comparison

- packages/gatsby-source-drupal/src/gatsby-node.js
This adds support for correctly handling the webhookBody in gatsby-source-drupal. This is used with the __refresh callback and is required for incremental builds to work correctly.
> fix(gatsby-source-drupal): Add webhookBody support to gatsby-source-drupal for inc builds

- scripts/i18n/update-source.js
Fixes problems when commit message in master contains single quotes - like https://github.com/gatsbyjs/gatsby/commit/091194bd469cd5d670e46331f6a52afadc633a05 - which caused https://circleci.com/gh/gatsbyjs/gatsby/395925?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> fix(i18n/update-source): handle single quotes in commit messages

- docs/docs/actions.md
https://github.com/gatsbyjs/gatsby/pull/22297 migrated `actions/restricted.js` to `actions/restricted.ts` but our API docs were not updated to use new extension
fixes #23668
> fix(www): update jsdoc source for actions after typescript migration

- packages/gatsby-transformer-asciidoc/src/__tests__/gatsby-node.js
- add test on `asciidoc` transformer
- mock `asciidoctor` usage because it was quite complicate to make it work in the jest context
- we could complete with more test in a second time to keep this PR small
> test(gatsby-transformer-asciidoc): init some tests

- packages/gatsby-cli/src/structured-errors/error-map.ts
- packages/gatsby/src/utils/webpack-error-utils.ts
Paired with @laurieontech on this. Starting point was [her PR](https://github.com/system-ui/theme-ui/blob/14a21cca9c846cf15890f5bf82a9fde3c59db988/packages/gatsby-plugin-theme-ui/gatsby-node.js#L3-L17) on the theme-ui repo that added an error message for missing an install of a package. It showed her error and the generic 98123 webpack error.
So we added a new error 98124 that matches on `Can't resolve [...]` errors and prints out the additional `Perhaps you need to install ...?`.
This PR also changes the `context.message` to `context.sourceMessage` to align it with the rest in the error map.
Adds an error parser to the webpack utils so that the webpack error can be more fine tuned in the future.
> fix: Add 98124 error to better help with "Can't resolve [...]" errors

- docs/blog/2020-04-29-incredimental-builds/index.md
Changed title in frontmatter because Incredimental Builds on its own was getting missed in SEO
> Adjust blog title to boost SEO

- docs/tutorial/part-seven/index.md
Added a clarification to avoid a common error when following the tutorial, which is to forget to add `getNode` to the function parameters.
This happeed to me, and looks like it's [happened to a few others](https://stackoverflow.com/questions/53870443/getnode-method-not-found-in-gatsby-node-js-with-the-latest-version-of-gatsby) too.
Hopefully this will help avoid other people making the same mistake.
> docs: clarify Tutorial Part 7

- docs/docs/performance.md
> docs: fix a typo in a Markdown link

- packages/gatsby-theme-blog-core/gatsby-node.js
- packages/gatsby-theme-blog-core/src/templates/post-query.js
- packages/gatsby-theme-blog/README.md
- packages/gatsby-theme-blog/src/components/post.js
As mentioned by @ehowey (https://github.com/gatsbyjs/gatsby/issues/23640#issuecomment-623853743) users may prefer a social image that differs from their featured image. This PR adds an additional field. If no image is found, the social image defaults to the featured image.
> Add separate social image field

- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/plugin.js
- packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
This is a follow up for #23433 that updates the `all` function which admin will use to leverage the new plugin resource shape that includes a name and options.
> fix(gatsby-recipes): Fix gatsby config all function

- packages/gatsby-source-wikipedia/package.json
- packages/gatsby-source-wikipedia/src/fetch.js
- remove `@babel/runtime` useless dependency
- add missing `bluebird` dependency (used in package but not listed)
- remove usage of `axios` to use `node-fetch` which seems to be most used fetch lib in packages
-  💡We may need to harmonize usage of fetching libs
- `querystring` is sadly not maintained now and `query-string` is used in many packages 
- 💡We may need to harmonize queryString libs in the monorepo
- add it to dependencies
💡I could add some test with jest in a dedicated PR
💡I could add option to load wikipedia depending on local
> chore(source-wikipedia): ugrade dependencies

- packages/gatsby-image/README.md
> chore(docs): Updated read-me with punctuation where necessary

- benchmarks/source-wordpress/README.md
- benchmarks/source-wordpress/scripts/data-update.js
- benchmarks/source-wordpress/scripts/updater.js
Since this benchmark already relies on a `BENCHMARK_WPGRAPHQL_URL` environment variable we might as well re-use that one in the data-update script instead of having the redundant `BENCHMARK_WORDPRESS_BASE_URL`.
> chore(benchmark-wordpress): Reuse existing BENCHMARK_WPGRAPHQL_URL env variable

- docs/tutorial/remark-plugin-tutorial.md
I just came across a broken image in the docs on [Creating a Remark Transformer Plugin](https://www.gatsbyjs.org/tutorial/remark-plugin-tutorial/#loading-in-changes-and-seeing-effect). This PR fixes the image path in there so that the image is loaded properly.
> fix(www): Update remark-plugin-tutorial.md

- packages/gatsby/package.json
- packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js
This PR includes filtering capabilities to the dev 404 page so it can be linked with custom query string parameters that trigger an initial search.
Fixes #23617
> feat(gatsby/dev-404-page): support reading and writing filter to `?filter` query string

- docs/docs/browser-apis.md
- docs/docs/node-apis.md
- packages/gatsby/scripts/output-api-file.js
- packages/gatsby/src/bootstrap/load-plugins/index.js
- packages/gatsby/src/utils/api-browser-docs.ts
- packages/gatsby/src/utils/api-node-docs.ts
In order to continue the conversion, this PR converts `api-browser-docs` and `api-node-docs` to TS.
> Convert api-browser and api-node docs to TS

- packages/gatsby-source-contentful/src/normalize.js
Git blame (https://github.com/gatsbyjs/gatsby/blame/5d2b510a59e4147c74277ddd2f6d670467f79690/packages/gatsby-source-contentful/src/normalize.js#L472 @KyleAMathews !) is useless here because I suspect the loop used to do something but those lines have actually been stripped and when this happened for the last side effect, the actual loop wasn't cleaned up.
Anyways, this can be dropped. It's not doing anything.
> chore(gatsby-source-contentful): drop noop loop

- docs/docs/gatsby-image.md
Following this example leads to a console error `Warning: Failed prop type: Invalid prop "fadeIn" of type "string" supplied to "Image", expected "boolean". I updated the example fadeIn prop to a bool from a string.
> chore(docs): Update fadeIn prop to bool

- packages/gatsby/src/bootstrap/index.js
This will help to triage many sites. If node count is high, certain problems are obvious. Also helps with triaging sites on sources that generate an excessive amount of nodes unexpectedly.
```
success createSchemaCustomization - 0.008s
success source and transform nodes - 29.579s - Now have 100128 nodes with 7 types: [SitePage:1, SitePlugin:22, Site:1, SiteBuildMetadata:1, Directory:1, File:101, IfscCsv:100001]
success building schema - 0.337s
success createPages - 42.945s - Now have 200129 nodes with 7 types: [SitePage:100002, SitePlugin:22, Site:1, SiteBuildMetadata:1, Directory:1, File:101, IfscCsv:100001]
success createPagesStatefully - 0.058s
```
> perf(gatsby): include node counts in output after sourcing steps

- packages/gatsby/src/bootstrap/load-plugins/load.js
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/.gitignore
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/gatsby-config.js
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/gatsby-config.js
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/node_modules/gatsby-theme-parent/gatsby-config.js
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/node_modules/gatsby-theme-parent/node_modules/gatsby-plugin-added-by-parent-theme/package.json
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/node_modules/gatsby-theme-parent/package.json
- packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/package.json
- packages/gatsby/src/bootstrap/load-themes/__tests__/index.js
- packages/gatsby/src/bootstrap/load-themes/index.js
- packages/gatsby/src/utils/__tests__/merge-gatsby-config.js
- packages/gatsby/src/utils/merge-gatsby-config.js
Because of the nature of package managers like pnpm and yarn 2, there are issues when resolving plugins for themes.
When Gatsby is resolving plugins from themes, it attempts to do a simple `require.resolve()`, which  essentially tries to resolve the package from the current working directory.  In effect, its `require()` method for these theme's plugins is scoped to the current project.  This is okay when using yarn/npm's, because of their hoisting mechanism.
PNPM uses a `node_modules` structure that limits each package to its own assigned dependencies.  If you have a dependency installed in a theme and used in its `gatsby-config`, but you don't have it installed in the consumer project, then the previously mentioned `require.resolve()` will fail miserably.
The same goes for Yarn 2.  Yarn …
> fix(gatsby): use scoped requires for theme plugins

- docs/docs/sourcing-from-sanity.md
Fixes an error within an example code block of the sourcing-from-sanity doc.
- Adds missing comma between properties
None
(It's my first PR here, I hope I did this right!)
> fix(docs): add missing comma between properties in code example

- integration-tests/structured-logging/__tests__/to-do.js
- packages/gatsby/src/redux/index.ts
- packages/gatsby/src/utils/__tests__/mett.ts
- packages/gatsby/src/utils/mett.ts
Saves ~25% of the bootstrap at scale for some baseline benchmarks because mitt uses an array to maintain handlers which it splices when removing a handler. When thousands of handlers get added to this array and you splice, things get quite expensive. Using a `Set` instead fixes this problem.
The `mett` code is ready for TypeScript although in this PR it implements the event name as `string` and payload as `any`. In some future somebody probably will want to go through each use of the emitter and define strict eventName+payload type pairs. I expect this not to be very easy but there are ways.
> perf(gatsby): replace `mitt` with a modern Map/Set based version of it

- packages/gatsby-dev-cli/src/local-npm-registry/index.js
- packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
- packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
- packages/gatsby-dev-cli/src/local-npm-registry/verdaccio-config.js
- packages/gatsby-dev-cli/src/watch.js
I was checking on one instance of "expected manifest" error and seems like in some cases using `dist-tag` over concrete version when installing dependencies was triggering this problem (problem in `yarn` perhaps?). Using concrete versions seems to solve it (at least in reproduction I had).
There are also few QoL improvements:
- increase request retries for npm registry uplink - on flaky connections (or maybe when npm registry is getting hammered) installation would sometimes fail because of those - this adds bit more resilience
- don't display those annoying and not actionable "Installation of dependencies after initial scan is not implemented" messages when package.json is being changed by `gatsby-dev` itself while publishing dev versions of packages
- in case of `yarn` installation …
> fix(gatsby-dev-cli): fix "expected manifest" errors

- packages/gatsby-recipes/recipes/storybook-js.mdx
- packages/gatsby-recipes/recipes/storybook-ts.mdx
- packages/gatsby-recipes/src/cli.js
This PR adds a recipe to `packages/gatsby-recipes`
The recipe adds Storybook (ts) to your Gatsby project. I've named this recipe `storybook-ts` as it creates the Webpack config required for Storybook to work with **_both_** **JavaScript** and **TypeScript** Gatsby projects. 
There are some linked "template" files that live on my GitHub... not sure where you're planning on hosting supporting files for recipes so i'm happy to change that if you have feedback?
More info can be found in the [GitHub repo](https://github.com/PaulieScanlon/gatsby-recipe-storybook-ts) repo, and I wrote a short blog post explaining how it works [here](https://paulie.dev/posts/2020/05/gatsby-recipe-storybook-ts/)
This PR is related to a previously merged PR for `gatsby-recipe-storybook-js` which can be seen …
> add Storybook (ts) to recipes

- packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
- packages/gatsby-remark-images/src/index.js
Currently gatsby-remark-images enforces a `max-width` on each image equal to the `presentationWidth` returned by gatsby-plugin-sharp. Any user-specified `max-width` in the `wrapperStyle` is simply ignored.  
Use case for custom `max-width` is described in #15578.
This PR adds support for specifying a `max-width` in the `wrapperStyle` which will be used instead of the `presentationWidth`.
Previously submitted half a year ago in #15952, but abandoned by me. This PR uses the cleaner solution suggested by @pieh.
Fixes #15578.
> fix(gatsby-remark-images): allow default max-width to be overwritten with `wrapperStyle`

- docs/docs/node-tracking.md
This fixes broken links in "Node Tracking" article of "Gatsby Internals" section.
Related to #14228
> update(docs) Fix broken links in node-tracking.md

- packages/gatsby-link/src/__tests__/index.js
- packages/gatsby-link/src/index.js
Hello!
I'd like to start by thanking you for this awesome project.
Sorry if this contribution doesn't match the guidelines, but I hope I understood them well.
This change makes `<GatsbyLink>` ask `navigate` to use replaceState rather than pushState when navigating on a link that is the current page. This fixes an issue where a history item would be pushed multiple times for the current page, while this is not the expected behaviour.
If a developer forced "replace" using the prop, their choice takes priority.
This uses the same technique as @reach/router when they fixed it upstream: https://github.com/reach/router/commit/11e9ed615c5752cfa1265a998c51a9bb478c857a
I did not copy the
```
const { key, ...restState } = { ...location.state };
shouldReplace = shallowCompare({ ...state }, …
```
> fix(gatsby-link): replace current path in history rather than pushing it

- packages/gatsby-theme-blog-core/gatsby-node.js
Massive thanks to @vladar for his help on this one!
The previous implementation resulted in an inconsistent race condition where in the image file was not created at the type the blog post node was generated.
This implements a custom resolver that solves that issue.
> Theme blog image resolution

- www/src/templates/template-api-markdown.js
Currently API docs filter out definitions that do not include a `memberof` field. This is not set in top level exports in TypeScript files, so was causing the Node API docs to go missing.
This PR just removes that filter. I don't _think_ this should include any unexpected definitions.
Fixes #23857
> fix(www): Allow API docs to reference top level TS exports

- docs/blog/2020-04-29-incredimental-builds/index.md
- docs/contributing/docs-and-blog-components.md
- www/src/components/__tests__/blog-post-metadata.js
- www/src/components/blog-post-metadata.js
- www/src/components/page-metadata.js
- www/src/templates/template-blog-post.js
Adds a new field to frontmatter, `seoTitle`. Uses it in the blog-post template, if provided, instead of the article title.
> feat(www): Meta title support

- packages/gatsby-dev-cli/src/index.js
We were misusing `.nargs` function previously but it worked, but recent `yargs` bump cause it to fail now.
https://github.com/yargs/yargs/blob/master/docs/api.md#nargskey-count
> The number of arguments that should be consumed after a key. This can be a useful hint to prevent parsing ambiguity.
`set-path-to-repo` requires one argument, otherwise it turns into boolean switch
> fix(gatsby-dev-cli): fix `set-path-to-repo` command after yargs bump

- packages/gatsby/src/bootstrap/index.js
I introduced a second import to the reporter not realizing that it was already imported under a slightly different name (`report` instead of the `reporter` name we widely use). So I'm dropping the new import and renaming the usage to `reporter` to conform to how we use this file elsewhere.
> chore(gatsby): cleanup double import of reporter

- packages/gatsby-theme-blog-core/src/components/bio-content.js
- packages/gatsby-theme-blog-core/src/components/bio.js
- packages/gatsby-theme-blog-core/src/components/header.js
- packages/gatsby-theme-blog-core/src/components/headings.js
- packages/gatsby-theme-blog-core/src/components/home-footer.js
- packages/gatsby-theme-blog-core/src/components/layout.js
- packages/gatsby-theme-blog-core/src/components/post-footer.js
- packages/gatsby-theme-blog-core/src/components/post.js
- packages/gatsby-theme-blog-core/src/components/posts.js
- packages/gatsby-theme-blog-core/src/components/seo.js
- packages/gatsby-theme-blog-core/src/templates/post-query.js
- packages/gatsby-theme-blog-core/src/templates/posts-query.js
- packages/gatsby-theme-blog/src/components/post-link.js
- packages/gatsby-theme-blog/src/components/post.js
After discussions about re-architecture, moving forward the gatsby-theme-blog-core 2.0 version will be more than just the data layer. It will act as a semantic HTML unstyled blog implementation.
This is the initial PR for that functionality which will be merged into the larger #23351 PR.
Note that functionality in #23353 will live in blog-core going forward, but is not included here just yet.
> Update blog-core 

- packages/gatsby-theme-blog-core/README.md
- packages/gatsby-theme-blog-core/gatsby-node.js
- packages/gatsby-theme-blog-core/src/templates/post-query.js
- packages/gatsby-theme-blog/README.md
- packages/gatsby-theme-blog/src/components/post.js
- packages/gatsby-theme-blog/src/components/seo.js
The `keywords` meta tag was removed for `gatsby-starter-blog` in https://github.com/gatsbyjs/gatsby/pull/14122 since it's not used by Google, Bing, or Yahoo as discussed in https://github.com/gatsbyjs/gatsby/issues/12454. This removes it in `gatsby-theme-blog` and `gatsby-theme-blog-core`.
No documentation changes necessary.
Fixes https://github.com/gatsbyjs/gatsby/issues/12454
> refactor(gatsby-theme-blog): Remove keywords from seo

- benchmarks/source-contentful/.env.example
- benchmarks/source-contentful/README.md
- benchmarks/source-contentful/bin/site.js
- benchmarks/source-contentful/package.json
- benchmarks/source-contentful/scripts/data-update.ts
Script for benchmarking data updates for Contentful.
Someone has added a skeleton for this script in the past but I didn't use it because we already have scripting infra in this benchmark. It was way easier to re-use it instead of writing it again.
Also, there are two commits here, first one was just a minor refactoring. The feature commit is: https://github.com/gatsbyjs/gatsby/commit/cb3c47fa4bd4a2fd51da69c7663e9391897084b0 (easier to review)
Added notes in README.md on how to use it.
> feat(benchmarks): Add script to update 1 Contentful article (for benchmarking data updates)

- docs/blog/2020-05-05-Butter-CMS-case-study/index.md
This change makes the meta title match searches for "ButterCMS Gatsby", a term I found while doing SEO research for ButterCMS topics
> (chore) add seoTitle to ButterCMS blog post

- benchmarks/md/scripts/data-update.ts
- benchmarks/mdx/scripts/data-update.ts
This changes the name of the environment variables for the `md` and `mdx` benchmark webhooks to easily distinguish between them in the various platforms.
n/a
n/a
> Update data update webhooks env naming

- packages/gatsby-recipes/recipes/tailwindcss.mdx
- packages/gatsby-recipes/src/__snapshots__/recipe-machine.test.js.snap
- packages/gatsby-recipes/src/cli.js
- packages/gatsby-recipes/src/graphql.js
- packages/gatsby-recipes/src/recipe-machine.js
- packages/gatsby-recipes/src/recipe-machine.test.js
fixes https://github.com/gatsbyjs/gatsby/issues/23817
fixes https://github.com/gatsbyjs/gatsby/issues/23818
fixes https://github.com/gatsbyjs/gatsby/issues/23603
We previously erased markdown text from recipes after a step was completed which meant that users couldn't reference them again while running the recipe or after.
Also with longer recipes, the step summaries could get lost so we now also print out at the end a list of all actions that were taken.
> feat(gatsby-recipes): Improve ongoing summary of steps + add end summary

- docs/docs/adding-markdown-pages.md
- examples/using-markdown-pages/gatsby-node.js
- examples/using-markdown-pages/src/markdown-pages/post-1.md
- examples/using-markdown-pages/src/markdown-pages/post-2.md
- examples/using-markdown-pages/src/pages/index.js
- examples/using-markdown-pages/src/templates/blogTemplate.js
While researching for something else I stumbled upon our docs page: https://www.gatsbyjs.org/docs/adding-markdown-pages/
I recognized that nothing was passed in via `context` which is necessary for the query in the template. So I updated the doc and example.
Moreover, I renamed the frontmatter from `path` to `slug` as the former is not allowed inside `context` - it's a reserved constant.
I also removed the `const path = require('path')` to not confuse people with another "path" variable (used `require.resolve()` instead).
Last but not least I added another blog post example so that the filtering can show.
> fix(using-markdown-pages): Example and docs

- docs/docs/typescript.md
changes:
- #23547 `feature(gatsby): Support TypeScript by default by compiling TS files`
> fix(docs): typescript - 404

- www/src/data/sidebars/doc-links.yaml
changes:
- unify all links and add trailing slash 
- #23547 `feature(gatsby): Support TypeScript by default by compiling TS files`
> fix(docs): add trainling slash to doc-links.yaml

- yarn.lock
This failed deps install - https://circleci.com/gh/gatsbyjs/gatsby/402326?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link caught my attention as it has some weird npm registry mirror.
This pr get rid of those weird ones I spotted
> chore: get rid of weird registry mirrors from lock

- packages/gatsby-cli/src/create-cli.js
Resolves #23941 there is no log-pages cli arg option
https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/
#23941
> fix(gatsby-cli): don't fail when using `--log-pages` and/or `--write-to-file`

- packages/gatsby/cache-dir/navigation.js
This PR fix error thrown `TypeError: Cannot read property 'innerText' of null` in `navigation.js:177` when doing client side redirect.
No documentation.
Fixes: https://github.com/gatsbyjs/gatsby/issues/23955
> fix: handle nullish announcementRef to fix client side redirect error

- www/redirects.yaml
PR #23961 renamed `/docs/deploying-to-zeit-now/` to `/docs/deploying-to-vercel/`. This adds a redirect.
> Add redirect for Vercel docs

- packages/gatsby-theme-blog/src/components/post.js
- packages/gatsby-theme-blog/src/components/seo.js
We should make use of alt text in social cards as well.
> Extend image seo for blog theme

- packages/gatsby-source-npm-package-search/src/__tests__/__snapshots__/gatsby-node.js.snap
- packages/gatsby-source-npm-package-search/src/__tests__/gatsby-node.js
- packages/gatsby-source-npm-package-search/src/gatsby-node.js
- packages/gatsby-source-npm-package-search/src/search.js
- Add test with jest on package source-npm-package-search
- need to split algolia search to a dedicate file to be able to mock it nicely
- this package is now covered, I'm ready for the next one
> test(source-npm-package-search): init test

- packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
This change allows the benchmark reporter to start benchmarking arbitarily after a previous run finished, without having to explicitly request it. This allows us to benchmark incremental builds more reliably, which don't necessarily trigger all the events.
> feat(gatsby-plugin-benchmark-reporting): allow arbitrary restart

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
This PR will support fast filters for `elemMatch` on values that aren't arrays. I believe this is an edge case but it turned out that Sift supports doing this and fast filters was not, so this achieves parity on that regard.
This PR will expose a new flag to check whether the previous call to `runSift` (which is sync blocking, despite technically async) went through Sift or only used a fast filter index.
This allows us to get a good overview in the tests which ops and specific routes are using the fast filter and which are using the slow (sift) path. And to confirm that each test will test both sift and fast filters.
Followup to #23348 (and all the fast filter related PR's, I guess)
> fix(gatsby): allow elemMatch on non-arrays, fix tests

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
This piggy backs on the work done for `lte` and `gte` already.
I duplicated the code because there are subtle differences and I think it's easier to maintain this way, rather than spaghetti all the edge cases between lt/lte/gt/gte in one function. I mean, that's doable but then nobody will ever touch it again.
The tests to cover lt/gt are already in place. Tighter test checks are added in #23634 which I intend to merge around the same time.
> perf(gatsby): enable fast filters for lt and gt

- www/src/data/diagram/static-hosts.yml
changes:
- unify all links and add trailing slash 
- #24014 `Feature Request: add test for trailing slashes in yaml files with links`
> fix(docs): add slashes to links in static host yaml

- www/src/data/sidebars/doc-links.yaml
changes:
- fix link 
- #24019 `[Umbrella] Rename Zeit to Vercel`
- #23961 `Rename ZEIT Now to Vercel` 
> fix(docs): links in sidebar to vercel

- packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Fixes unchecked global variable reference.
> fix(gatsby-plugin-benchmark-reporting): Fix invalid refernece to var that may be null

- www/src/components/homepage/homepage-blog-posts.js
Hello! This is my very first PR to the gatsby repo and I'm so happy to be able to contribute fixing this one 🥳: #24035
I don't really know why was the div using overflow: hidden but seems that not using it fixes the problem. Let me know if I did something wrong!
Thank you so much! 
Fixes  #24035
> Fix a11y outline on homepage view all posts button

- docs/accessibility-statement.md
Update the Accessibility Statement to use the new a11y alias.
Also update supported WCAG version to 2.1.
> Use new a11y email alias & update WCAG version

- packages/gatsby-source-filesystem/src/extend-file-node.js
I have some larger assets in one of my Gatsby projects that I pull in with gatsby-source-filesystem. Due to the file sizes involved, I want to avoid committing those files to git. Instead I'm using git-annex which replaces the files with relative symbolic links (e.g. `../../../../.git/annex/objects/...`. Currently, gatsby-source-filesystem copies the link itself to the public folder when building the site which breaks the link.
This PR adds the "dereference" option to the copy call which will cause the actual file content to be copied and produce a working build even if symbolic links are involved.
As far as I am aware it is not documented how symlinks are handled. Not sure if it needs to be, I would expect symlinks to be dereferenced anyways.
None that I am aware of.
> fix(gatsby-source-filesystem): dereference symlinks when copying files with `publicURL`

- packages/gatsby-transformer-toml/package.json
- add missing dependency lodash
- remove babel/runtime because, it is not used here
- remove Bluebird, it is not used here
Should we add `eslint` check on dependencies ? 
https://www.npmjs.com/package/eslint-plugin-import 
With rules [like that](https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/no-extraneous-dependencies.md) we could detect package with missing dependencies.
I could work on that 🕺
> chore(transformer-toml): fix dependencies declaration

- packages/gatsby-transformer-json/src/gatsby-node.js
It was previously difficult to locate a json file with a syntax error in it, this patch improves the error message to include the path.
> fix(gatsby-transform-json): improve json parse error so it's easier to locate problematic content

- packages/gatsby-theme-blog/README.md
- packages/gatsby-theme-blog/gatsby-node.js
- packages/gatsby-theme-blog/src/components/layout.js
- packages/gatsby-theme-blog/src/hooks/configOptions.js
Allow users to include a webfont URL in their options that will be included in their head tag.
There may be a more performant way to do this.
> Webfont option for blog theme

- packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
If the benchmark runs more than once in the same session then the type will update to something that can be controlled from an env var with a default of 'DATA_UPDATE'.
> feat(gatsby-plugin-benchmark-reporter): change type of incremental benchmark after first run

- packages/gatsby/index.d.ts
- packages/gatsby/package.json
This allows to type location state using and additional TypeScript prop.
Example:
```tsx
interface LocationState {
// data sent from previous page using <Link to="/page/" state={{foo: "OK"}} />
foo: string
}
const MyPage: React.FC<PageProps<null, null, LocationState>> = ({ location }) => {
// location.state.foo is recognized as a string
return <div>Test: {location.state?.foo}</div>
}
```
Fixes #23298.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44081
> fix(gatsby): add generic locationState to types

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
This enables the fast filters for $ne. Future improvement pending, current implementation makes it useful for $nin as well.
> perf(gatsby): enable fast filters for $ne

- packages/gatsby-theme-blog-core/README.md
- packages/gatsby-theme-blog-core/gatsby-config.js
- packages/gatsby-theme-blog/README.md
- packages/gatsby-theme-blog/src/components/seo.js
Other plugins and docs make use of site URL in metadata as `siteUrl` rather than `siteURL`. We should be consistent.
> Use consistent cases for siteUrl in themes

- docs/starters.yml
Hi team, 
Due to DNS changes in our starters, we are making this pull request with updated URLs which points to the continuously updated demo of starters.
> chore(starters): Updated starter URLs due to DNS changes

- docs/docs/recipes/working-with-themes.md
- docs/docs/themes/using-a-gatsby-theme.md
Adding all the theme options to comments in docs creates technical debt. This changes that pattern and highlights the README section that lists them.
> Don't list all options in docs

- packages/gatsby-cli/src/__tests__/index.js
- packages/gatsby-cli/src/index.ts
Currently the CLI panics if the version of Node does not satisfy the minimum version requirements. As the semver spec says that prerelease versions never satisfy a range requirement, unless specifically included, prerelease verisons of Node cannot be used. This could be useful for testing, so this PR adds the `includePrerelease: true` option for semver, which allows prerelases to satisfy the constraint. It adds a warning if a prerelease version is being used, as we do not support this even if we permit it.
#23945
> Allow, but warn for, pre-release versions of Node

- packages/gatsby/scripts/__tests__/api.js
- packages/gatsby/scripts/output-api-file.js
#23936  Description
A recent TS conversion broke the apis.json script in an unexpected way. Here is how it broke:
- [Currently latest apis.json](https://unpkg.com/gatsby@2.21.24/apis.json)
- [Old working version](https://unpkg.com/gatsby@2.20.0/apis.json)
This fixes the script to make it output the same structure that we currently see in the `Old working version`
#23688
> fix(gatsby): update script to generate apis.json to accomodate Typescript

- packages/gatsby-remark-autolink-headers/src/gatsby-browser.js
This PR improves the `getTargetOffset` calculation to include a potential `scroll-margin-top` to enable controlling the scroll offset on the component level via CSS.
No docs exist for this, afaik.
None.
> fix(gatsby-remark-autolink-headers): include scroll-margin in getTargetOffset

- packages/gatsby/src/query/__tests__/query-compiler.js
- packages/gatsby/src/query/query-compiler.js
Just having `gatsby-transformer-sharp` installed (not even in gatsby-config) and not having any image nodes cause query-compiler to fail validation because we use prevalidate rules that include `KnownTypeNamesRule` on every extracted graphql document. This PR removes that rule from prevalidation.
We also later run full validation on constructed document that stitches query and used fragments, so this PR doesn't completely removes it - it just makes sure that we run it only on fragments that are actually used (I added 2 tests to verify it - one for not used fragment that is using unknown type - which passes validation and one for used fragment that is using unknown type which errors out as expected)
`gatsby-transformer-sharp` already define schema for `ImageSharp` so we should not see …
> fix(gatsby): don't fail validation on fragments that are not used

- packages/gatsby-recipes/src/cli.js
Another try on https://github.com/gatsbyjs/gatsby/pull/23996
> fix(gatsby-recipes): format code blocks without indentation as that makes copy/paste difficult

- examples/using-typescript/src/pages/404.tsx
- examples/using-typescript/src/pages/index.tsx
Add missing `PageProps` to page interface in typescript example
https://www.gatsbyjs.org/docs/typescript/#example
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L55
> fix(docs): TypeScript Example PageProps

- packages/gatsby/src/utils/webpack-utils.ts
Updates our usage of FastRefresh to a recent breaking change from 0.2 -> 0.3.
#24078
> fix(gatsby): Update to handle changes to fast refresh webpack plugin

- docs/blog/2019-08-13-Localised-strings-from-Kentico-Cloud-GatsbyJS-GraphQL/index.md
- fix links to localhost/sample sites in to code blocks tot avoid 404
> fix(blogs): code block for example link with 404

- docs/contributing/contributor-swag.md
The backslashes next to the "$" characters disappear when viewing this document's rendered HTML on GitHub or in VS Code's Markdown preview...But they looked odd on gatsbyjs.org.
I promise I'm not making this change *just* to unlock Tier 2 swag 👀
> docs: unescape dollar signs in free swag details

- docs/docs/glossary.md
**Changes: added trailing slash to helps the user identify the hierarchy of page.**
`Fix: Breadcrumb issue resolved in /docs/docs/glossary.md`
#20767
#22628
#22933
> fix(docs): added trailing slash to glossary.md

- docs/docs/recipes.md
**Changes: added trailing slash to helps the user identify the hierarchy of page.**
`Fix: Breadcrumb issue resolved in /docs/docs/recipes.md`
#20767
> fix(docs): added trailing slash to recipes.md

- packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
- packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
- packages/gatsby/src/schema/__tests__/pagination.js
- packages/gatsby/src/schema/resolvers.ts
- packages/gatsby/src/schema/type-definitions.ts
- packages/gatsby/src/schema/types/pagination.ts
For the uniformity, there is no point of having this not be pageInfo as it might be important to display the pageInfo.
> feat(gatsby): Add total count to pageInfo

- docs/docs/glossary.md
- docs/docs/glossary/jsx.md
- www/src/data/sidebars/doc-links.yaml
Updates docs/docs/glossary, and doc-links.yaml with links to entry.
Fixed alphabetization of Infrastructure as Code and JAMStack.
> docs/glossary: JSX article

- docs/docs/awesome-gatsby-resources.md
Added link to Guiding Digital's "Gatsby" YouTube playlist to the Gatsby tutorials section.
> Added Guiding Digital link to Gatsby tutorials section

- .circleci/config.yml
- jest.config.js
- packages/gatsby-transformer-hjson/src/__tests__/gatsby-node.js
- Related to this [discussion](https://github.com/gatsbyjs/gatsby/pull/23851#issuecomment-628053372)
- Linked to #23851 
- Fix usage of jest reporters to let the default jest reporter 
- this PR is failing for the demo
- [Jest doc about reporters](https://jestjs.io/docs/en/configuration#reporters-arraymodulename--modulename-options)
> chore(unit): fix re-add `jest-silent-reporter` to unit test CI output

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/connection-filter-on-linked-nodes.js
- packages/gatsby/src/schema/__tests__/run-query.js
This enables fast filters for the `in` comparator. This means this doesn't have to go through Sift for most of the cases.
> perf(gatsby): enable fast filters for `in` comparator

- packages/gatsby-plugin-manifest/src/__tests__/gatsby-ssr.js
- packages/gatsby-plugin-manifest/src/gatsby-node.js
- packages/gatsby-plugin-manifest/src/gatsby-ssr.js
gatsby-ssr was using `fs` to get `contentdigest` of the icon to use as cacheKey. If we want to move to a distributed world. Fs shouldn't run in ssr mode.
Only internal stuff has changed so no need for updates
> fix(gatsby-plugin-manifest): remove fs from ssr

- benchmarks/markdown_id/package.json
- benchmarks/markdown_slug/package.json
- benchmarks/markdown_table/package.json
- benchmarks/md/package.json
- benchmarks/mdx/package.json
- benchmarks/source-contentful/package.json
- benchmarks/source-datocms/package.json
- benchmarks/source-drupal/package.json
- benchmarks/source-wordpress/package.json
Adds a clean command to all markdown, mdx and source benchmarks.
> chore(benchmarks): Ensure all source and md[x] benchmarks have a clean command

- packages/gatsby/src/redux/actions/public.js
- packages/gatsby/src/redux/persist.ts
updated public.js to send a warning when pageContext exceeds approx 500kb limit
Fixes #14213
> feat(gatsby): Warn when pageContext is over 500k

- docs/tutorial/wordpress-image-tutorial.md
This PR resolves the issue with the broken demo link on the 'Adding Images to a WordPress Site' tutorial page.
Not applicable.
n/a.
> Correct WordPress Demo Site URL

- docs/starters.yml
Adjust the feature list to not list the CMS features, but the starter's ones.
Related to https://github.com/Kentico/kontent-gatsby-packages/issues/136
> Update Kontent starter features

- docs/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/index.md
- docs/blog/2020-05-12-strapi-instant-content-preview-plugin/index.md
- docs/contributing/docs-and-blog-components.md
- docs/docs/deploying-and-hosting.md
- www/src/components/shared/cloud-callout.js
This change is an attempt to update the language around Gatsby Cloud to fit the tone of the docs a little better. We aren't actually using the `CloudCallout` component in too many places and most remain the same because they're quick sentence fragments. I've also updated the two (identical) uses in blog posts. Those are in a separate commit.
This was an internal request.
> chore(docs): Update CloudCallout language

- docs/sites.yml
This adds my SaaS startup, [runly.io](https://www.runly.io/), to the site showcase. It is completely built with Gatsby:
* the marketing and landing pages
* the written docs and tutorials
* the generated C# docs
* the backend dynamic app portion
We were able to do a lot of powerful things and merge in data from a lot of places that would have been very difficult to do without Gatsby. :wink:
> Add runly.io to site showcase

- www/src/views/creators/index.js
Added a null check for the location.state of the creators page before filtering which prevents it from crashing. Previously, when using "Skip to main content" componentDidUpdate fired with `location.key = 'initial'` and `location.state` was not set in that case.
Fixes #24081
> fix: check if location.state is set for filtering

- www/src/components/page-with-sidebar.js
- www/src/components/sidebar/__tests__/sidebar.js
- www/src/components/sidebar/sidebar.js
Remove local storage functionality from sidebar so that other sections close when navigating to a new page.
The performance of the docs pages is proportional to how many sections in the sidebar are open: when more sidebar sections are open, more nodes need to be loaded into the DOM and everything slows down. With our current local-storage based implementation:
1. navigating to a page opens the section that its in
2. sections that aren't manually closed remain open even when navigating away from the page.
This means as you navigate the docs over time, performance becomes slower as more and more docs sections are opened, unless you manually close the sections you're visiting or click the "Expand All" button and then the "Collapse All" button.
> perf(www): Close other sections when navigating to a new page

- packages/gatsby-recipes/README.md
- fix jsx in readme
- #23599 `feat(gatsby-recipes): document option support for GatsbyPlugin` 
- #24142 `Reature Request: format check for README.md`
> fix(readme): fix jsx in recipes readme

- docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
- docs/docs/deploying-to-vercel.md
changes:
- fix brand name casing: VERCEL to Vercel
- #24019 `[Umbrella] Rename Zeit to Vercel`
> fix(docs): change VERCEL to Vercel

- packages/gatsby-recipes/README.md
- add code block to `<File` so it is visible
- fix missing code blocks so that all in jsx code stlye
- fix language to shell
- #22709 `feat(Gatsby Recipes): Initial release`
- #24142 `Feature Request: format check for README.md`
> fix(readme): fix code blocks in recipes readme

- benchmarks/md/package.json
- benchmarks/mdx/package.json
I don't think there's any reason we want to pin these benchmarks to an older version of the reporting plugin, and this version doesn't work with refresh.
> chore(benchmarks): Don't pin gatsby-plugin-benchmark-reporting version

- benchmarks/source-contentful/bin/site.js
This PR is a fix for the Contentful benchmark site. Specifically for `data-update` script that is supposed to update a single article in Contentful benchmark. The problem is that we must also `publish` the updated article, otherwise, the change is not visible on a subsequent build.
This PR adds publishing step.
> fix(benchmarks): Publish changes in contentful data update script

- packages/gatsby-cli/src/structured-errors/error-map.ts
I recently added the 98124 error. However, it's also thrown when people require local files and it fails. So it would say something like `Perhaps you need to install the package '../../content/image.png'?`. This update accounts for that.
> fix(gatsby-cli): Improve wording for 98124 error message

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
This enables fast filters for the `$nin` comparator.
This basically does the same thing as the `$ne` comparator. The difference is that `$ne` only removes nodes for one value where `$nin` removes all nodes matching zero or more values.
> perf(gatsby): Enable fast filters for $nin comparator

- www/src/templates/tags.js
UI of buttons on blog page is broken on devices having width less than 400px
1. Go to Gatsby website on a mobile device having width less than 400px.
2. Go to Blog Page of the Gatsby website.
3. Click on the **View all Tags** button.
4. Click on the **themes** tag from popular tags
5. **The View all tags** and **Read the documentation** buttons are touching each other
> fix(www): responsive ui of buttons on blog page

- packages/gatsby/src/commands/develop.ts
This PR as per the issue I opened yesterday: https://github.com/gatsbyjs/gatsby/issues/24165
Gatsby offers proxy functionality while in dev so if React needs to call, say, a RESTful api to fetch data, no special dev configuration is needed beyond updating `gatsby-config.js` with the proxy's location.
However, Gatsby's proxy does not include the cors middleware, which means the proxy fails for any proxied DELETE (and PUT and PATCH) requests. It will work for GET and POST and I think OPTIONS. Not sure about the others.
So the proxy is only half-functional right now.
The fix is a few keystrokes: you add `cors()` to the proxied requests when initialized. That's what I've done in this PR.
I have not written any tests because I'm not sure where to put them. However, there do not appear to be …
> Gatsby Dev Proxy forwards 'complex' HTTP calls like DELETE now

- packages/gatsby-cli/src/create-cli.ts
- packages/gatsby-cli/src/recipes.ts
We broke gatsby recipes with our recent TS conversion. This fixes it.
Fixes #24198
> fix(gatsby-cli): Fix recipes cli invocation

- www/src/components/sidebar/accordion.js
- www/src/components/sidebar/item-link.js
- www/src/components/sidebar/item.js
- www/src/utils/sidebar/item-list.js
Fixes indentation of sidebar bullets when parent link has `ui: steps`-property (i.e. in Tutorials section). For this I used a new prop called `parentUi` which is set on items.
Result looks like this:
Fixes #24093
> fix(www): sidebar bullets indention for steps

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
This enables fast filters for the `$regex` and `$glob` comparators. Internally `$glob` is automatically converted to `$regex` so this change also applies it to `$glob`.
The implementation may see some future improvements. But these comparators are not used very frequently (<1% according to analytics) and probably shouldn't be used in large scaling sites because it's slow by nature.
> perf(gatsby): Enable fast filters for $regex/$glob

- .typo-ci.yml
> chore(typobot): Add ESLint to typobot ignore list

- www/src/pages/blog/tags.js
I was going through the code of Gatsby website and found that key prop is missing when we are looping through the **POPULAR_TAGS** and creating **<PopularTagButton />** component and it shows missing key prop warning in the console when we are running website on localhost.
File path is
**gatsby/www/src/pages/blog/tags.js**
> fix(www): key prop missing warning

- packages/gatsby/src/commands/develop.ts
`gatsby develop` command is broken on windows now
There are backslashes in `developProcessPath`, what should be properly escaped.
> fix develop command on windows

- docs/docs/adding-search-with-algolia.md
Added a hint about why we prune excerpts and Algolia's default record limit.
> fix: add hint about prune length for records

- packages/gatsby-core-utils/src/service-lock.ts
- packages/gatsby/cache-dir/app.js
- packages/gatsby/src/commands/develop.ts
- packages/gatsby/src/utils/restarting-screen.ts
In #22759 I introduced a service discovery mechanism to allow for coordination between all the various processes.
Unfortunately, while it worked it was implemented completely wrong. It created a lock _per site_, which meant if you wanted to run multiple services per site it would fail on the second `createServiceLock` call, as the site would already be locked. (I noticed as I need this functionality for #23733)
I reworked the service discovery mechanism to create a lock _per service_ instead. While I was at it, I also made it store JSON rather than strings to allow for more complex data to be discovered in the future and give more semantic information about the data automatically.
Here is what the service discovery folder structure would look like when starting a site and two services …
> fix(gatsby-core-utils): create lock per service, rather than per site

- packages/gatsby-source-contentful/src/download-contentful-assets.js
Update the source url to use `https` instead of `http`. 
As per https://www.contentful.com/developers/docs/references/http-details/ , https is the recommended approach.
Fixes #24130
> fix(gatsby-source-contentful): Use https instead of http when downloading assets

- docs/docs/location-data-from-props.md
Clarify in https://www.gatsbyjs.org/docs/location-data-from-props/ how the `location` prop is passed, what it contains, and fix some random Title Casing.
> docs: clarify props.location

- docs/docs/creating-and-modifying-pages.md
should the `product` need to destructed from `pageContext`?
- #23136 `chore(docs): Add section to document best practice usage of pageContext`
> fix(docs): creating and modifying pages - pageContext

- www/src/components/card.js
- www/src/components/diagram.js
- www/src/components/homepage/homepage-features.js
1. The diagram section of homepage is having extra left and right padding(1.5rem) which is making it very narrow on mobile devices, also inconsistent with the other sections on homepage.
2. The features sections of homepage is also narrow because the cards inside of it are having extra left and right padding(1.5rem).
3. The features section is not having any padding bottom on mobile devices which is making it attached to the divider.
The styles have only been touched for devices with size smaller than **mediaQueries.sm**, others have been untouched.
1. Go to the homepage on mobile device
2. Scroll down to the diagram and features section
3. The section should not include the extra padding and should not shrink
4. The features sections should have padding-bottom similar to the padding-top
> fix(www): fixes the padding issues on homepage for mobile screen sizes

- packages/gatsby/package.json
- yarn.lock
> Versions of http-proxy prior to 1.18.1 are vulnerable to Denial of Service
https://www.npmjs.com/advisories/1486
> chore(gatsby): update http-proxy to fix vulnerability

- packages/gatsby/cache-dir/create-react-context.js
Our `create-react-context` alias which is useful for saving few kbs for bundles when some legacy components are used doesn't match exports structure of actual package we are aliasing. In some cases this cause problems - particularly when package is using `const createReactContext = require('create-react-context')`, because our babel setup creates just `exports.default` and not the `module.exports` one
Fixes #23645
> fix(gatsby): adjust `create-react-context` alias to match actual package exports

- packages/gatsby/src/utils/eslint-config.ts
adds `control-has-associated-label` rule back into eslint-config, looks like it wasn't added with the other rules and should definitely be included
> fix(gatsby): add control-has-associated-label rule into eslint-config

- packages/gatsby-source-drupal/src/__tests__/fixtures/file.json
- packages/gatsby-source-drupal/src/__tests__/index.js
- packages/gatsby-source-drupal/src/normalize.js
* if prefix found - allow basicAuth object to include credentials only for files whose prefix is 'public:'
* for other prefixes ('S3:' for example) use an empty auth object
( for use with Drupal's s3fs module, to store images on S3 - without the prefix check sending credentials on the file download request will fail)
When using a Drupal configuration that stores images on S3 (using s3fs module), the images fail to download when supplying Basic Authentication credentials.
Added a check to remove credentials in that case.
Fixed #23632
> fix(gatsby-source-drupal): added check for node.uri.value prefix

- docs/docs/deploying-to-surge.md
The existing instructions there don't work. It appears that the CNAME file has to be in the public directory in order to run the "surge public" command. The Surge.sh docs also appear to not work at the moment. (I posted there too.)
This is my first pull request here. If I should do something differently, please let me know. :) 
This updates a part of the documentation that is out of date.
Full description in the issue: https://github.com/gatsbyjs/gatsby/issues/24206
Fixes #24206
> Update surge CNAME instructions

- docs/docs/mdx/getting-started.md
Not sure why the opening backtick was escaped.
> docs: fix code formatting for MDX getting-started

- docs/docs/glossary/yarn.md
fix brand name:
- yarn to Yarn
- #23049 `docs/glossary: Add Yarn glossary entry.`
> fix(docs): glossary yarn: change yarn to Yarn

- docs/docs/local-https.md
fix brand names:
- windows -> Windows
- linux -> Linux
- MacOS -> macOS
- #18703 `fix(gatsby): Add self-signed cert to node trust store (https)`
> fix(docs): local https - fix brand names

- docs/docs/eslint.md
fix brand names:
- ESlint -> ESLint
- #12998 `Updated es-lint docs to instruct how to install eslint-config-react-app`
> fix(docs): eslint - fix ESlint to ESLint

- packages/gatsby-recipes/package.json
Fix missing detect port dependency in `gatsby-cli`.
> fix(gatsby-cli): add detect port to dependencies

- starters/blog/src/components/seo.js
I was attempting to deploy my site on Netlify for two days and had zero luck because I kept getting an error about `Helmet`. I paired with a friend that can better read the docs and he told me to just put curly braces around the import in the `seo.js` component.
**Current:**
`import Helmet from "react-helmet"`
**My Branch:**
`import { Helmet } from "react-helmet"`
Helmet was updated to version 6 and has breaking changes. I am assuming this is a big breaking change and will cause some headaches if anyone is trying to deploy with Netlify and getting failures.
After making this change in my own personal project code, I re-deployed to Netlify and everything worked perfect!
https://github.com/nfl/react-helmet/releases/tag/6.0.0
> fix: adds curly braces around Helmet import in seo.js component.

- packages/gatsby/src/commands/develop.ts
In my previous PR (#24233) I was proposing to fix develop command by escaping string, but it was updated to use custom `slash()` function instead.
I recommend to keep `JSON.stringify()` there too.
This is not the same case like the one @KyleAMathews referred here:
https://github.com/gatsbyjs/gatsby/pull/24233#issuecomment-631138932
Here, the value is used to build another string so it should be properly escaped. It is not very likely there will be other unsafe chars since it is a file path, but it is possible. For example, on linux path can contain quotation mark, backslash, newline...
Try to rename project folder, or any parent and include quote:
```
$ mv my-project my-\"project\"
$ cd my-\"project\"
.cache/tmp-2897-NEAUzfcqHpYg:2
const cmd = …
```
> fix(gatsby) escape string in develop command

- packages/gatsby-plugin-feed/src/gatsby-node.js
I hope I'm not oversimplifying this, but I think we can slip in this `await` on the result of `serializer` with no consequences- we're already in an `async` function.
I'd like to use a unified processor in my serializer, but it seems quite difficult to use async plugins in a synchronous function.
I think the only necessary change would be just to mention that `serializer` can be asynchronous in the README. I'll add that to the PR and edit this line (I'm in the web UI currently)
I didn't create an issue, nor could I find an existing one.
> [gatsby-plugin-feed] Await async serializers

- packages/gatsby-recipes/src/renderer/index.test.js
- packages/gatsby-recipes/src/renderer/render.test.js
Storing actual version of latest gatsby is problematic because we would need to update snapshot each time we publish :)
> test(gatsby-recipes): don't store actual version in snapshots

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
This supports a fast path for queries without filters.
This happens frequently for sites that unconditionally want all nodes of a particular set of types, perhaps sorted or with some other transformation.
I created a separate early path for this, which also caches the set of nodes.
There's also some cleanup for the return type of various functions in this path and dropping some legacy op support checking code (no longer needed now that fast filters supports everything). Suggest to review commit by commit.
> perf(gatsby): support empty filters without sift

- yarn.lock
In my previous PR about this (#24294) I forgot to remove a vulnerable version of http-proxy from the lockfile.
This change is not really important for end users, but does help anyone working on the Gatsby codebase
> remove vulnerable http-proxy version from lockfile

- packages/gatsby-recipes/recipes/gitlab-ci-cd.mdx
This PR adds a new recipe that automates basic CI/CD configuration by creating a minimal .gitlab-ci.yml file, on the root of the project
This is related to this: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/gitlab-continuous-integration.md
> feat(recipes): add recipe for Gitlab CI/CD

- docs/docs/actions.md
- docs/docs/browser-apis.md
- docs/docs/node-api-helpers.md
- docs/docs/node-apis.md
- docs/docs/node-model.md
- docs/docs/ssr-apis.md
- www/gatsby-config.js
- www/src/utils/node/docs.js
Instead of sourcing the entire `/packages` directory, source only from `/packages/gatsby` for docs.
Previously we were sourcing the entire packages directory in order to get package READMEs for local plugins. Since we now get those from npm, there's no more reason to get the entire thing. The only thing we need is the source for gatsby-core in order to generate API documentation.
> perf(www) Only source gatsby core instead of the whole packages directory

- packages/gatsby/src/utils/develop-proxy.ts
Currently ws doesn't work for our websocket-manager (which we use to emit updates) because the newly added develop proxy server doesn't handles upgrades or pass through `ws` messages.
Data updates work nonetheless because socket.io gracefully downgrades to polling but that is not ideal. 
This fixes that.
> fix(gatsby): Pass through ws in proxy

- starters/gatsby-starter-theme-workspace/example/src/pages/index.js
Replace anonymous function with named function in gatsby-starter-theme-workspace
Follows conventions used in docs e.g. named regular functioned (not arrow function)
As per this issue - #23575
> fix(gatsby-theme-starter-workspace): Change anonymous function to named function

- docs/docs/sourcing-from-builder-io.md
fix brand name, because on all other places at this doc it is named Builder.io:
- Builder -> Builder.io
- on the homepage [Builder.io](Builder.io) the Brand name is always only `Builder`
i don't know, but would the link `BuilderIO Gatsby starter` not better also `Builder.io Gatsby starter`?
- #22650 `[Docs] add sourcing from builder.io doc` from @teleaziz
> fix(docs): change Builder to Builder.io

- docs/docs/creating-dynamic-navigation.md
The following import seems to be missing:
`import PropTypes from "prop-types"`
https://www.gatsbyjs.org/docs/creating-dynamic-navigation/#using-the-header-component-to-display-the-navigation
> chore(docs): add missing prop-types import

- docs/blog/2020-04-15-announcing-gatsby-recipes/index.md
> fix(blog): recipes - fix 404 link

- docs/docs/page-creation.md
changes:
- fix 404 link (js -> ts)
> fix(docs): page creation - 404

- docs/docs/node-creation.md
changes:
- fix 404 link (js -> ts)
> fix(docs): node creation - 404

- packages/gatsby-recipes/recipes/pwa.mdx
should this not be an png icon, since we add a `icon.png` file? or is there some autoconvert (which i don't find in the docs of the manifest)?
changes:
- icon format
- #23563 `feat(gatsby-recipes): Add PWA recipe + improving diffing for binary files`
> fix(recipes): icon format

- docs/docs/themes/converting-a-starter.md
changes: 
- re-add a link which get lost in #23572
- #23572 `Fix outdated section in Themes docs`
> fix(docs): themes - convert starter to theme - re-add link

- docs/docs/how-code-splitting-works.md
changes:
- fix 404 link (js -> ts)
- apply redirect
> fix(docs): code splitting - 404

- packages/gatsby-plugin-catch-links/src/catch-links.js
If the clickedAnchor with no href attribute has clicked then jump to the page top. Expect to do nothing. 
Avoid setting href to an empty string.
* If clickedAnchor has no href attribute like `<a>example</a>`, the href getter returns the empty string.
* The empty string is a relative path.
refs: https://html.spec.whatwg.org/multipage/links.html#concept-hyperlink-url-set
> fix(gatsby-plugin-catch-links): fix href attribute

- docs/docs/production-app.md
updated link to build-javascript as it was converted to `ts` few days ago so, link turned obsolete
> chore(docs): update link to build-javascript

- packages/gatsby/package.json
- packages/gatsby/src/utils/webpack-utils.ts
- packages/gatsby/src/utils/webpack.config.js
After upgrading to latest, I have begun to have issues with `url-loader` being able to resolve `file-loader`, and `.cache/app.js` being able to resolve `socket.io-client`.  This is likely because I am using pnpm in my particular repository.
`url-loader` uses a [fallback of `file-loader`](https://github.com/webpack-contrib/url-loader/blob/v1.1.2/src/utils/normalizeFallback.js#L4), but it only provides a simple string.  `url-loader` also doesn't provide `file-loader` as a production dependency, nor does it list it as a peer dependency, so it would need to get it from somewhere else.
I'm not sure why this only started breaking now, but this is the error I get:
```sh
ERROR #98123  WEBPACK
Generating JavaScript bundles failed
Cannot find module 'file-loader'
Require stack:
- <require stack …
```
> fix(gatsby): add explicit dependency on `socket.io-client` and explicitly set `url-loader` fallback

- packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js
- packages/gatsby/src/bootstrap/resolve-module-exports.js
Fixes https://github.com/gatsbyjs/gatsby/issues/24458
Relevant ASTExplorer: https://astexplorer.net/#/gist/a67d7a00ab34ed73711045da5ab348df/b2bc30b3e138e37851000e7c12770df01a71d29d
Previously it only checked for `astPath.node.declaration.declarations[0].id.name`, now it also checks for `astPath.node.declaration.id.name`.
> fix(gatsby): Also traverse `FunctionDeclaration`

- packages/gatsby-recipes/src/parser/index.test.js
We see alot of test flakiness in CircleCI with tests not finishing within 5s (default timeout for async tests). This one increase timeout in one of the test files that was very often failing based on just not resolving fast enough in CI
> test(gatsby-recipes): increase timeout values

- packages/gatsby/src/bootstrap/index.js
- packages/gatsby/src/bootstrap/requires-writer.ts
- packages/gatsby/src/commands/develop-process.ts
This adds type annotations to `requires-writer.js` from the `gatsby` package
I had to introduce one assertion for `matchPath !== undefined` as `IGatsbyPage` it's of type `string | undefined`, but everything in `requires-writer.js` assumes that it's a `string`. It would throw an error anyway, I just made a bit more pretty with `reporter.panic()`
NOTE:
`requires-writer.js` uses the reporter from `gatsby-cli`, and not the TS source, but the compiled version. Not sure if it's ok. Maybe we should extract reporter into a separate package if it is used in both `gatsby` and `gasby-cli`
No changes required
> chore(gatsby) Rewrite requires-writer.js to TypeScript

- .circleci/config.yml
- packages/gatsby-recipes/foo
- packages/gatsby-recipes/package.json
The current test pattern only reports webpack errors (`ERROR #`), not raw errors (`Error: ...`). This is typically not a problem because raw errors cause the process to abort, but it appears this isn't necessarily the case with `gatsby-recipes`:
https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/41626/workflows/00a80c3c-735a-4bc0-8deb-c9a82d380fa4/jobs/418447/parallel-runs/0/steps/0-112
I'll also add in this diff the missing dependencies that didn't get reported until now.
> fix(gatsby-recipes): add missing dependencies

- packages/gatsby-recipes/README.md
In the definition of props in the Recipe API section, some of the props were followed by a colon and some weren't. This was especially confusing because it appeared to repeat the property name twice (ex. "name name"). I added a colon after each one for consistency.
> chore(gatsby-recipes): Update prop definitions in Gatsby Recipes readme

- packages/gatsby/src/redux/types.ts
changes:
- `sireUrl` -> `siteUrl`
i guess the bug was not catched because of the default `[key: string]: unknown`
- #23620 `fix(gatsby): log config validation errors`
> fix(code): redux types - sireUrl -> siteUrl

- packages/gatsby-cli/package.json
Follow up #24285 
With typegen now being part of build, we do need typescript to get tsc in node_modules/.bin. Otherwise if system doesn't have global typescript installed it will fail to build the package
> fix(gatsby-cli): build properly in CI

- packages/gatsby-graphiql-explorer/src/app/app.js
Resolves #24250 by defaulting to `undefined` instead of `null`, so that the variables prop is not passed when unset
> fix(graphiql-explorer): variables on edit

- packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Ensures `getNodesByType` is passed on to Gatsby Remark plugins
Docs already exist that suggest this should be passed on (see issue).
Fixes #24400
> fix(gatsby-plugin-mdx): Ensure getNodesByType helper is passed to gatsbyRemarkPlugins

- www/src/data/sidebars/doc-links.yaml
We list a ton of options for deploying Gatsby sites in the documentation but Gatsby Cloud is buried towards the end of that list. This change moves Gatsby Cloud towards the top, just under "Preparing a Site for Deployment".
This was an internal request!
> chore(docs): Move Cloud up in Deploying & Hosting list

- packages/gatsby/src/bootstrap/__mocks__/resolve-module-exports.ts
- packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js
- packages/gatsby/src/bootstrap/load-plugins/__tests__/validate.js
- packages/gatsby/src/bootstrap/load-plugins/validate.js
- packages/gatsby/src/bootstrap/resolve-module-exports.ts
This PR migrates `packages/gatsby/src/bootstrap/resolve-module-exports` to TypeScript.
Unblocks #22504. Part of #21995.
> chore(gatsby): Update resolve-module-exports to TS

- packages/gatsby-graphiql-explorer/package.json
- packages/gatsby-graphiql-explorer/src/app/app.css
- yarn.lock
GraphiQL Explorer could use a few minor versions update. This might fix a few outstanding issues.
I also removed the actions dropdown for now, using `:nth-selector` which could be fragile. A PR to `graphiql-explorer` is the next step.
I tested this locally with latest master gatsby-cli, and everything seemed to work fine.
- possibly resolves #15805 (cannot confirm without OSX)
- was hoping it would help with #24250 but it does not.
> chore(graphiql-explorer): upgrade graphiql-explorer

- docs/categories.yml
- docs/starters.yml
Added a starter that connects the default starter to Microsoft's newly announces Azure static Web Apps. This includes automatic CI/CD using GitHub actions, as well as behind the scene staging environments etc.
> Chore(starters) add gatsby starter azure swa

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/providers/utils/get-graphql-fields.js
- packages/gatsby-recipes/src/providers/utils/get-graphql-fields.test.js
- yarn.lock
This will be used for CMS providers so that we can provision content types:
```mdx
---
export const blogPostSchema = `
type BlogPost {
title: String!
body: String! @metadata(type: "Text", title: "Content")
}
`
Provision content types for the blog post:
<ContentfulSpace name="blog">
<ContentfulEnvironment name="production">
<ContentfulType schema={blogPostSchema} />
</ContentfulEnvironment>
<ContentfulEnvironment name="staging">
<ContentfulType schema={blogPostSchema} />
</ContentfulEnvironment>
</ContentfulSpace>
```
> feat(gatsby-recipes): Implement utility for turning graphql sdl to fields

- packages/gatsby-theme-ui-preset/README.md
changes:
- brand name: `Theme-UI` -> `Theme UI`
- brand name: `theme-ui` -> `Theme UI`
- #23144 `Create new gatsby-theme-ui-preset theme`
> fix(docs): theme ui preset: fix brand name Theme UI

- docs/docs/overview-of-the-gatsby-build-process.md
changes:
- #23695 `chore(gatsby): convert build to typescript` 
> fix(docs): build process - fix 404

- docs/docs/performance-tracing.md
changes:
- #23656 `chore(gatsby): jaeger-local to TypeScript` 
> fix(docs): performance tuning - fix 404

- starters/default/src/pages/index.js
- starters/default/src/pages/page-2.js
- starters/default/src/pages/using-typescript.tsx
Fixes https://github.com/gatsbyjs/gatsby/issues/24388
We also talked about this internally on Slack.
I reverted the `page-2.js` page and added a new `using-typescript.tsx` file. I added some more complexity but it'll be a common use case to have your GraphQL query and data.
I think adding more information to https://www.gatsbyjs.org/docs/typescript/ would be out-of-scope for this PR but once we have more integrations we definitely need to update that page.
https://github.com/gatsbyjs/gatsby/issues/18983
> fix(gatsby-starter-default): Clear up TS usage example

- packages/gatsby/src/utils/eslint-config.ts
Turns off `react/jsx-pascal-case` in ESLint due to warnings in the console with Theme-UI and the `<Styled>` component. At the end of the day this isn't a big deal, but it does really clutter up the console when building sites with Theme-UI.
Looks like this:
```shell
warn ESLintError: 
/Users/erichowey/Coding/gatsby-theme-catalyst/themes/gatsby-theme-catalyst-helium/src/components/post-list.js
26:11  warning  Imported JSX component h1 must be in PascalCase or SCREAMING_SNAKE_CASE  react/jsx-pascal-case
130:19  warning  Imported JSX component h2 must be in PascalCase or SCREAMING_SNAKE_CASE  react/jsx-pascal-case
138:21  warning  Imported JSX component a must be in PascalCase or SCREAMING_SNAKE_CASE   react/jsx-pascal-case
142:19  warning  Imported JSX component p must be in PascalCase or …
```
> fix(gatsby): Turn off react/jsx-pascal-case in ESLint to fix Theme-UI warnings

- docs/docs/schema-generation.md
Fixes `ProcessedNodeType` link in  schema-generation section of docs
n/a
Fixes a couple of links raised by #24313, specifically in the section schema-generation
> docs: Update documentation links

- packages/gatsby/src/redux/actions/public.js
There was a mix of singular and plural in this short description which didn't make sense.
> chore(doc): Fix grammatical error in documentation

- packages/gatsby/index.d.ts
Add better public-facing typing for `NodePluginArgs` interface, which corresponds to the documentation in [Node API Helpers](https://www.gatsbyjs.org/docs/node-api-helpers/). All documentation copied over from the corresponding file with minor changes (e.g. no redundant type definitions).
https://www.gatsbyjs.org/docs/node-api-helpers/
* Since we're typing things more strictly, it might cause type errors for people depending on Gatsby types. Does this count as a breaking change?
> enhancement(gatsby): add better typing and documentation for Gatsby Node Helper APIs

- packages/gatsby-dev-cli/src/__tests__/watch.js
- packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
- packages/gatsby-dev-cli/src/utils/promisified-spawn.js
- packages/gatsby-dev-cli/src/watch.js
`gatsby-dev-cli` is currently hiding output of various `yarn` commands we run under the hood unless `DEBUG` env var is set - this was done to prevent quite large console spam in case we need to go through verdaccio path, but tradeoff of frustration when something fails without clear reason is not worth having clean terminal output.
With this PR output of commands is hidden only when using `--quiet` flag. And if we hit errors with `--quiet` flag there is hopefully helpful message to drop `--quiet` switch to see the output.
> fix(gatsby-dev-cli): show spawned processes output unless `--quiet` is used

- docs/docs/building-an-ecommerce-site-with-shopify.md
- docs/starters.yml
Adds the new gatsby-starter-hello-world-shopify starter, which includes the necessary boilerplate to set up a Shopify store using Gatsby being the least opinionated about the structure of the site.
It also includes being mentioned in the post Building an E-commerce site with Shopify, under additional resources.
> Adds the gatsby-starter-hello-world-shopify starter

- packages/gatsby/src/commands/serve.ts
use mutated port variable to generate the urls that inform the user about where is the server running.
Fixes #24518
> fix(gatsby): show correct `serve` info when running on another port

- packages/gatsby-recipes/src/gui.js
- packages/gatsby-recipes/src/providers/contentful/environment.js
- packages/gatsby-recipes/src/providers/contentful/type.js
- packages/gatsby-recipes/src/providers/utils/get-graphql-fields.js
- packages/gatsby-recipes/src/providers/utils/get-graphql-fields.test.js
- packages/gatsby-recipes/src/renderer/render.js
- packages/gatsby-recipes/src/renderer/resource-provider.js
- packages/gatsby-recipes/src/renderer/transform-to-plan-structure.js
- packages/gatsby-recipes/src/resources.js
First pass at a Contentful provider to provision a space and a content type. Also adds support for nested resources in the GUI.
```
CONTENTFUL_ACCESS_TOKEN=123abc
```
```mdx
---
Provision a blog space.
<ContentfulSpace name="blog8">
<ContentfulType schema={`
type BlogPost {
title: String @metadata(type: "Text", name: "Title")
body: String @metadata(type: "Text", name: "Content")
}
`} />
</ContentfulSpace>
```
> feat(gatsby-recipes): Spike out contentful provider and basic rendering

- packages/gatsby-recipes/package.json
This ensures that there aren't any files being left around when the build runs for publishing.
> fix(gatsby-recipes): Clean up dist folder before build

- packages/gatsby-recipes/src/graphql-server/index.js
- packages/gatsby-recipes/src/graphql-server/server.js
fixes https://github.com/gatsbyjs/gatsby/issues/24656
> fix(gatsby-recipes): Don't use 4000 as default recipes port as commonly used by people in apps

- www/src/views/starter-library/starter-list.js
https://github.com/gatsbyjs/gatsby/pull/21792 didn't also change the starter sort. So it was actually broken for a couple of months now 😮 
Fixes https://github.com/gatsbyjs/gatsby/issues/24616
> fix(www): Starter star sorting

- benchmarks/source-cosmicjs/package.json
- benchmarks/source-sanity/package.json
Update the benchmark reporting plugin versions in the new benchmarks to match the others.
n/a
n/a
> Update benchmark reporting plugin verisons

- docs/sites.yml
Our MobileUI framework product website. The framework is about cross-platform app development.
Built with Gatsby, WPGraphQL and Apollo for the dynamic user area, that is connected to WordPress.
It consists of a landing page, a blog (https://mobileui.dev/blog/), and a private user area with e-commerce content.
> chore(showcase): Add mobileui.dev

- packages/gatsby/src/bootstrap/create-graphql-runner.ts
- packages/gatsby/src/query/query-compiler.js
- packages/gatsby/src/utils/wait-until-jobs-complete.ts
- packages/gatsby/src/utils/websocket-manager.ts
This PR tightens up a few types, and exports several interfaces. Functionally, it also returns the result of waitUntilAllJobsComplete rather than void.
This is part of the develop state machine refactor.
> chore(gatsby): Export and improve types

- packages/gatsby-recipes/package.json
strip-ansi is used by gatsby-recipes/src/providers/utils/get-diff.js, which makes it a dependency rather than devDependency. Make it so.
Addresses #20949
> fix(gatsby-recipes): move strip-ansi to dependencies

- docs/blog/2020-05-13-virtual-gatsby-day-speakers/index.md
changes:
- remove domain from local links
- fix brand name: Sendgrid -> SendGrid
- #24069 `Blog gatsby day speakers`
> fix(blog): gatsby days speakers - remove local domain, fix branding

- packages/gatsby-recipes/recipes/preact.mdx
changes:
- fix brand name: preact -> Preact
```diff
- Add the preact plugin to your Gatsby config.
+ Add the `gatsby-plugin-preact` plugin to your Gatsby config.
````
- #24156 `feat(gatsby-recipes): add preact recipe`
> fix(recipe): Preact - brand name

- docs/docs/location-data-from-props.md
Clarify when the `location` prop is automatically passed to components.
https://www.gatsbyjs.org/docs/location-data-from-props/
[Demo](https://codesandbox.io/s/gatsby-location-clarifications-f2l5c?file=/src/pages/index.js)
Related to #8787
> docs: the location prop is only passed to page components

- www/src/components/guidelines/color/swatch.js
1. The class based `<Swatch/>` component in color page of guidelines has been converted to function component.
2. It was using state called `displayCopied` to show the **Copied to clipboard!** text after the color code has been copied to clipboard, now this state is being managed by useState hook.
3. It was having another state set in constructor called `value: this.props.color.hex`, it was redundant because value of hex can be retrieved directly from color which we were getting by props destructuring.
Go to the following link mentioned below, the component should work same in both the local and production link, just the implementation of component is now different.
**Local URL:** http://localhost:8000/guidelines/color/
**Production URL:** https://www.gatsbyjs.org/guidelines/color/
> feature(www): convert the class based swatch component to function component

- docs/blog/2020-05-14-introducing-gatsby-theme-catalyst/index.md
changes:
- remove domain from local links
- relative path for images
- fix brand names:
- Wordpress -> WordPress
- Theme-UI -> Theme UI
- SANITY.io -> Sanity.io
- #24083 `Blog gatsby-theme-catalyst` 
> fix(blog): Theme Catalyst - remove local domain, fix branding

- docs/starters.yml
changes:
fix brand names
- GatsbyJS -> Gaysby
- ReactJS -> React
- Typescript -> TypeScript
- Tailwindcss -> Tailwind CSS
- Theme-UI -> Theme UI  (should also changed `Styling:Theme-UI` -> `Styling:Theme UI`)
- Wordpress -> WordPress
> chore(starter): fix brand names in starters

- www/redirects.yaml
changes: 
- unify all entries to include trailing slash
- #21608 `chore(redirects): unify all entries to include slash`
> chore(redirects): unify all entries to include slash

- docs/docs/glossary/decoupled-drupal.md
- docs/docs/glossary/headless-cms.md
- docs/docs/glossary/npm.md
**Changes: added trailing slash to helps the user identify the hierarchy of page.**
`Fix: Breadcrumb issue resolved in /docs/docs/glossary.md`
- #20767 `[docs] Breadcrumb shouldn't be dependent on trailing slash`
- #22628 `chore(docs): Add Snipcart reference guide`
- #22933 `fix(docs): add trainling slashes to doc-links.yaml`
- #24068 `fix(docs): added trailing slash to glossary.md` 
> fix(docs): add trailing slashes to glossary links

- packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
When using `yarn@1.22` it has different shape of `yarn workspaces info --json` command than previous versions of yarn - because gatsby-dev-cli relies on this output when running it in workspaces - we need some error catching / sanitization
> fix(gatsby-dev-cli): support workspaces in yarn@1.22

- packages/gatsby/src/query/graphql-runner.ts
Regression introduced in https://github.com/gatsbyjs/gatsby/pull/22851
The problem seems to be that these calls to `v8.serialize` trigger the gc to start a full hold-the-world mark-and-sweep step sooner. In a benchmark of 150k pages, the step would trigger almost always after between 100k and 110k queries had run, and it would pause the process for 60+ seconds.
Example benchmark results from before and after that PR:
```
info bootstrap finished - 86.758 s
success Building production JavaScript and CSS bundles - 9.404s
success run queries - 205.676s - 150002/150002 729.31/s
success Building static HTML for pages - 142.800s - 150002/150002 1050.44/s
info Done building in 451.33 sec
```
```
info bootstrap finished - 85.933 s
success Building production JavaScript and CSS bundles - 8.335s …
```
> perf(gatsby): drop severe scaling regression caused by analytics

- www/src/components/guidelines/color/swatch.js
1. Converted the `<Swatch/>` component to theme-ui
2. Some CSS rules were repeating, they are fixed
**Local URL:** http://localhost:8000/guidelines/color/
**Production URL:** https://www.gatsbyjs.org/guidelines/color/
> chore(www): convert swatch component to theme-ui

- docs/docs/recipes/gitlab-continuous-integration.md
- packages/gatsby-recipes/recipes/gitlab-ci-cd.mdx
fix brand names:
- Gitlab -> GitLab
- #23367 `docs: Create gitlab-continuous-integration.md`
> fix(recipes): CI recipes - change Gitlab to GitLab

- docs/docs/glossary.md
changes for consistency with Glossary Page ( https://www.gatsbyjs.org/docs/glossary/infrastructure-as-code/ )
- `Infrastructure As Code` -> `Infrastructure as Code`
> ```diff
> -### [Infrastructure As Code](/docs/glossary/infrastructure-as-code/)
> +### [Infrastructure as Code](/docs/glossary/infrastructure-as-code/)
> ```
> 
> I think we can refer to this as Infrastructure as Code or IaC throughout. As long as "as" isn't capitalized and we're consistent all the way through, I'm good.
> 
> _Originally posted by @AishaBlake in https://github.com/gatsbyjs/gatsby/pull/23431/files_
- #23431 `Glossary, encyclopedia: Add Infrastructure As Code article.`
> fix(glossary): IaC - fix name for consistency

- docs/docs/glossary/infrastructure-as-code/index.md
change:
- code language from `markdown` -> `mdx`
- #23431 `Glossary, encyclopedia: Add Infrastructure As Code article.`
> fix(docs): glossary IaC - fix code language to MDX

- docs/docs/glossary/infrastructure-as-code/index.md
Changes:
- `Node` -> `Node.js`
- #23431 `Glossary, encyclopedia: Add Infrastructure As Code article.`
> fix(docs): glossary IaC - brand names

- docs/blog/2020-03-11-netlify-functions-and-gatsby-cloud/index.md
- docs/docs/deploying-to-gatsby-cloud.md
- docs/starters.yml
- rfcs/text/0005-docs-decision-tree.md
- rfcs/text/0011-move-rfcs-to-monorepo.md
> chore(docs): Fix brand name for GitHub

- docs/docs/recipes/gitlab-continuous-integration.md
- packages/gatsby-recipes/CHANGELOG.md
- packages/gatsby-recipes/recipes/gitlab-ci-cd.mdx
> chore(docs): Fix brand name for GitLab

- docs/starters.yml
Adds a new starter, namely [gatsby-starter-simple](https://www.gatsbyjs.org/contributing/submit-to-starter-library/) via the process described [here](https://www.gatsbyjs.org/contributing/submit-to-starter-library/).
**gatsby-starter-simple** is a simple Gatsby starter for a small static site. It replaces Prettier with ESLint (AirBnB style), and adds TypeScript and Firebase hosting.
The only code changed in this PR is: `docs/starters.yml`
The documentation for the new starter is available at it's repo [here](https://github.com/rickkln/gatsby-starter-simple), and there is a demo available at [simple.rickkln.com](https://simple.rickkln.com/).
> chore(starters): add gatsby-starter-simple

- docs/blog/2020-04-22-announcing-incremental-builds/index.md
- docs/blog/2020-05-27-announcing-series-b-funding/index.md
> chore(blog): 🔒 Fix missing HTTPS on gatsbyjs.com links

- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
The sorting was being overly generic which was hurting some fast paths where sorting was not necessary. Instead I've made sure that all buckets are sorted (and assert that they must be deduped by definition, for regular and elemMatch queries). This attempts to push most of the sort time in the one-time cache moment, rather than having to do it for every filter regardless.
This means that anything that pulls only one bucket from the cache shouldn't need to do any sorting/deduping. Anything that does merge or get the buckets differently, still needs to, like `$eq null` or range ops. But regular `$eq`, by far the most common case, etc should now not be burdened by this requirement.
> perf(gatsby): be more conservative in when to sort

- www/src/utils/node/starters.js
Rather than panicking when a showcase entry is missing, this PR warns and removes the node for that site.
> chore(www): Don't panic on missing showcase entry

- packages/gatsby-link/src/index.js
Adds null check so that an empty `to` prop isn't fatal, but instead warns
> fix(gatsby-link): Fail gracefully on empty `to` prop

- docs/docs/deploying-to-azure.md
links where 404
now they point correctly
> fixing some 404 links

- packages/gatsby/src/commands/develop-process.ts
- packages/gatsby/src/utils/develop-proxy.ts
Bind top level server to host provided by user (we fallback to `localhost` if not specified). 
https://github.com/gatsbyjs/gatsby/issues/24272#issuecomment-638330741
> fix(gatsby): bind develop-proxy server to host specified by user

- packages/gatsby/index.d.ts
Fixes https://github.com/gatsbyjs/gatsby/issues/24645
Since we don't generate types yet it's probably best to just copy/paste this.
> fix(gatsby): TypeScript typings import error

- packages/gatsby/src/query/__tests__/data-tracking.js
- packages/gatsby/src/schema/__tests__/node-model.js
- packages/gatsby/src/schema/node-model.js
We currently are adding abstract connection as data dependency when querying for `allX` if `X` is interface with `@nodeInterface`. Doing so doesn't allow us to mark query as dirty when nodes of type that implement `X` change, because those concrete node type names don't match interface type name. You can check https://github.com/gatsbyjs/gatsby/issues/24705#issuecomment-638041594 for bit more details.
To solve this problem I overwrite `createPageDependency` in `node-model` and in case of connections I use already existing `toNodeTypeNames` function to get list of concrete type names and add each of those as dependency (instead of adding abstract one as we do today)
This is not a problem for individual nodes with data tracking because we use node ids there and there is no mention of types …
> fix(gatsby): add connection data dependency on concrete types when abstract type is queried

- packages/gatsby/src/redux/__tests__/run-sift.js
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/node-model.js
- packages/gatsby/src/schema/__tests__/queries.js
- packages/gatsby/src/schema/__tests__/run-query.js
This is a minimal version of https://github.com/gatsbyjs/gatsby/pull/24345 where we only uncomment the Sift call (and anything in tests that relied on it).
This is _potentially_ a breaking change, although the status quo should already be that everything is handled by fast filters. Before this PR the empty results were still routed through Sift as a safety backup, but we now have a high enough confidence that this is no longer necessary.
__We will do a minor bump for this change__, to err on the safe side of this assumption. We will try to fix-forward anything that might still be broken. But worst case we can still back this out to unblock.
Please tag me message asap if you think this commit causes any kind of problem.
The plan is to actually remove the Sift specific code in about two …
> perf(gatsby): stop using Sift as fallback

- packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
- packages/babel-plugin-remove-graphql-queries/src/index.js
- packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
- packages/gatsby/src/query/__tests__/file-parser.js
This strips spaces and comments from query text before hashing them so that 
```
{
site {
siteMetadata {
github
}
}
}
```
is the same as 
```
{
site {
siteMetadata {
github
}
}
}
```
This will lead to better caching and query reuse 🙂
> fix(babel-plugin-remove-graphql-queries): Strip ignored characters from query text for better caching and deduping

- packages/gatsby/src/query/query-watcher.js
Currently, if a page contains an inline static query (and not a page query), the result of the static query incorrectly gets included in the page's `page-data.json` file. 
This fixes that.
> fix(gatsby): Fix issue where inline static query in page gets added to page data

- packages/gatsby-transformer-react-docgen/package.json
- packages/gatsby-transformer-react-docgen/src/__tests__/displayname-handler.js
- yarn.lock
changes as suggested in https://github.com/gatsbyjs/gatsby/issues/24487#issuecomment-638416213:
- update react-docgen: ^5.0.0
- fix tests 
note: i need help because the `yarn.lock` need also an update 
i can not do it, because i can not use the yarn.lock from the repo, because i need to delete the yarn.lock to get packages installed on my local machine :(
- bug(tests): docgen.parse #24487
> fix(gatsby-transformer-react-docgen): update react-docgen, fix tests

- docs/blog/2020-05-21-gatsby-recipes/index.md
changes:
- brand name `CommonJs` -> `CommonJS`
- brand name `Webpack` -> `webpack`
- remove domain from local links
- create talking links, avoid `here` as link text for a11y
- fix code language `sh` -> `shell`
- fix code language `javascript` -> `mdx`
- place file name in `title=...`
- fix code language `text` for directories
- relative link for images
- #24287 `Blog - Gatsby Recipes`
> fix(blog): recipes -  code block languages, brand names, local links

- packages/gatsby/src/utils/validate-page-component.ts
Since the check is only valid for ts|js(x) files, calculating the includesDefaultExport check before extension check is unnecessary.
Ref : #24813
> Improved includesDefaultExport Check

- docs/docs/deploying-to-surge.md
changes:
- remove domain on local links
- #24278 `Update surge CNAME instructions` 
> fix(docs): surge - remove local domain

- packages/gatsby-remark-embed-snippet/README.md
the README is displayed in https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/#hide-lines
go to `JavaScript Examples`
examples not show commands
changes:
- change code block language `no-highlight` to show commands
> fix(gatsby-remark-embed-snippet): readme - change code language

- examples/using-reach-skip-nav/README.md
changes:
- add `title=` to code blocks
- add file name into code block because title is not visible in readme on github
- add code fences to function names
- add code block and mark treeviews with `text` language
- fix closing code fences tag
- fix brand name cypress -> Cypress
- #21376 `Reach skip nav example`
> fix(examples): skip nave Readme - code blocks, brand names

- packages/gatsby/src/utils/validate-page-component.ts
changes:
- simplify regex (suggestion from @pvdz https://github.com/gatsbyjs/gatsby/pull/24837#discussion_r436270883)
- avoid wrong positive tests ( true: `.jsm`, `.tsxt` etc)
- #24837 `perf(gatsby): Improved includesDefaultExport Check` 
- #24813 `fix(gatsby): Mdx integration broken since Gatsby 2.22.21`
> chore(gatsby): validate-page-component - simplify regex

- docs/docs/third-party-graphql.md
After busting my head and got help from the Slack channel I'm adding an example repo for creating dynamic pages with Drupal+GraphQl.
> Adding an "Example with Drupal" link

- packages/gatsby-source-wordpress/README.md
Fix heading typo in gatsby-source-wordpress README
gatsby-source-wordpress
None at present
> Fix typo in gatsby-source-wordpress README

- packages/gatsby/src/redux/actions/public.js
Because `typeof null === "object"` this would throw if page context was null. This adds a truthiness check. This is enough, because context can only be JSON-safe types.
Fixes #24884
> fix(gatsby): Add null context check

- docs/blog/2017-11-06-migrate-hugo-gatsby/index.md
- docs/blog/2018-05-24-launching-new-gatsby-company/index.md
- docs/blog/2018-10-26-export-a-drupal-site-to-gatsby/index.md
- docs/docs/ab-testing-with-google-analytics-and-netlify.md
- docs/docs/localization-i18n.md
- docs/starters.yml
- examples/styleguide/src/templates/ComponentPage/components/ComponentPreview/prism-theme.css
- packages/gatsby-source-wordpress/README.md
- packages/gatsby-transformer-toml/README.md
By default `github.io` subdomains are served over `HTTPS`
> chore(docs): 🔒 Fix missing HTTPS on github.io links

- packages/gatsby-transformer-remark/README.md
Line 181 of gatsby-transformer-remark's README.md, read "You might use this if you have a blog post whose **an** excerpt contains markdown content." I removed "an".
> docs(gatsby-transformer-remark): Removed superfluous "an" from README

- docs/tutorial/ecommerce-tutorial/index.md
All new Stripe users now use the Products API instead of Orders API, so new stripe accounts will not be able to complete the e-commerce tutorial without figuring out that the code snippet is wrong.
- Adds updated code snippet for Stripe redirectToCheckout to use Products API instead of the deprecated Orders API.
- Adds a deprecation snippet for existing Stripe users who are still using Orders API
Closes: #24883 
Reference URLs:
- Gatsby Ecommerce Stripe Tutorial: https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/#create-a-checkout-component-that-loads-stripejs-and-redirects-to-the-checkout
- Stripe Checkout Documentation: https://stripe.com/docs/payments/checkout/client#generate-checkout-button
- Stripe Deprecated Orders API: https://stripe.com/docs/orders
> docs: update Stripe ecommerce tutorial

- packages/gatsby-plugin-offline/README.md
Clarify in `gatsby-plugin-offline` README how the service worker is generated, and that it uses the Workbox library.
> docs: gatsby-plugin-offline mentions Workbox

- www/src/components/ecosystem/ecosystem-board.js
1. Converts the class based `<EcosystemBoard/>` component to function component.
2. Now, it **setupScrollersObserver** and **unobserveScrollers** inside `useEffect` hook instead of `componentDidMount()` and `componentWillUnmount()`.
Go to the following link mentioned below, the component should work same in both the local and production link, just the implementation of component is now different.
**Local URL:** http://localhost:8000/ecosystem/
**Production URL:** https://www.gatsbyjs.org/ecosystem/
> refactor(www): convert EcosystemBoard to function component + cleanup

- www/src/components/sidebar/sticky-responsive-sidebar.js
1. The class based `<StickyResponsiveSidebar/>` has been converted to function component.
2. It was using state called `open` to toggle the opening and closing behaviour of the sidebar, now this state is being managed by useState hook. Also, name of `open` has been changed to `isOpen` because it contains boolean value.
3. Functional updates have been used to toggle the state `isOpen`.  
```onClick={() => setOpen(open => !open)}```
The `<StickyResponsiveSidebar/>` component is used in `<PageWithSidebar/>` component
1. Go to https://www.gatsbyjs.org/docs/ page.
2. Open this page in responsive device.
3. Click on the floating button on the bottom right of screen.
4. A sidebar will open up from the left side of the device.
5. Clicking again on the floating button will close the sidebar or …
> refactor(www): convert sticky-responsive-sidebar to function component

- www/src/views/shared/collapsible.js
1. Converts the class based `<Collapsible/>` component to function component.
2. It was using state called `collapsed` to toggle between the collapsing behaviour, now this state is being managed by useState hook.
3. At some places css rules were applied using `css` prop and at other using `sx` props, now all of the css rules are applied using `sx` props of theme-ui.
**There is not change functionality wise, just the implementation is different.**
The `<Collapsible/>` component is used in the following two pages
**Local URL:** http://localhost:8000/showcase/
**Production URL:** https://www.gatsbyjs.org/showcase/
**Local URL:** http://localhost:8000/starters?
**Production URL:** https://www.gatsbyjs.org/starters/?v=2
> refactor(www): convert the class based collapsible to function component

- www/src/components/banner.js
1. Convert the `<Banner/>` component to theme-ui
2. Center the banner text on mobile devices, right now it is not perfectly centered.
1. Go to the homepage
2. The banner is at the top having text "New! Try Incremental Builds with Gatsby Cloud!"
3. This banner should work same on desktop but the banner text should be centered on the mobile devices(less than md width).
**Local URL:** http://localhost:8000/
**Production URL:** https://www.gatsbyjs.org/
> refactor(www): convert <Banner/> component to theme-ui + cleanup

- www/src/components/markdown-page-footer.js
1. The class based `<MarkdownPageFooter/>` component has been converted to function component.
2. It was using state defined in constructor called `feedbackSubmitted` which was not getting used anywhere it has been removed.
3. It was having a horizontal rule with display property set to none, it is redundant. 
```<hr sx={{ display: `none` }} />```
Go to the following link mentioned below, the component should work same in both the local and production link, just the implementation of component is now different.
Scroll down to the end of tutorial, you will see MarkdownPageFooter component, this component is being used in multiple pages, I have provided a link of one page below.
**Local URL:** http://localhost:8000/tutorial
**Production URL:** https://www.gatsbyjs.org/tutorial/
> refactor(www): cleanup of MarkdownPageFooter + convert to function component

- www/src/components/react-hubspot-form.js
We have used componentWillUnmount() lifecycle method inside react-hubspot-form.js, but we are not doing any cleanup in this method, which makes it redundant.
> chore(www): removes unused componentWillUnmount lifecycle method

- www/src/components/guidelines/avatar.js
- www/src/components/guidelines/color/overview.js
Convert the `<Overview/>` component used in guidelines/color page, to theme-ui.
**There is not change functionality wise, just the implementation is different.**
**Local URL:**  http://localhost:8000/guidelines/color/
**Production URL:** https://www.gatsbyjs.org/guidelines/color/
> chore(www): convert the overview component to theme-ui

- www/src/components/guidelines/avatar.js
- www/src/components/guidelines/cards/blog.js
Convert the `<Avatar/>` component used in `<BlogCard/>` of guidelines/typography/ page, to theme-ui.
**There is not change functionality wise, just the implementation is different.**
**Local URL:**  http://localhost:8000/guidelines/typography/
**Production URL:** https://www.gatsbyjs.org/guidelines/typography/
> refactor(www): convert avatar of guidelines to theme-ui

- www/src/components/guidelines/color/card.js
The following changes have been done in the card component which is imported as ColorSwatch in guidelines/logo page
1. Import the `<Box/>` and `<Flex/>` component from theme-ui
2. Fix the typo in flexBase css property, changed it to flexBasis
1. Go to the links mentioned below
Local URL: http://localhost:8000/guidelines/logo/
Production URL: https://www.gatsbyjs.org/guidelines/logo/
2. Scroll down to the colors section
> fix(www): card component imported as ColorSwatch in guidelines/logo page

- www/src/components/features/evaluation-table.js
1. Convert the `<EvaluationTable/>` to function component from class based component
2. Use theme-ui's array syntax and remove import of mediaQueries
3. CSS cleanup
**There is no change functionality wise, just the implementation is different.**
The table used on features/jamstack and features/cms page is EvaluationTable
**Local URL:** 
http://localhost:8000/features/jamstack/
https://www.gatsbyjs.org/features/cms/
**Production URL:** 
https://www.gatsbyjs.org/features/jamstack/
https://www.gatsbyjs.org/features/cms/
> refactor(www): convert EvaluationTable to function component

- www/src/components/features/simple-evaluation-table.js
1. Convert the `<SimpleEvaluationTable/>` to function component from class based component
2. Use theme-ui's array syntax and remove import of mediaQueries
3. CSS cleanup
**There is no change functionality wise, just the implementation is different.**
The table used on features page for comparing features is the SimpleEvaluationTable
**Local URL:** http://localhost:8000/features/
**Production URL:** https://www.gatsbyjs.org/features/
> refactor(www): convert SimpleEvaluationTable to function component

- docs/docs/client-only-routes-and-user-authentication.md
Just a minor fix from my last commit to this page.
> docs: add forgotten paren to client-only routes

- docs/docs/adding-a-list-of-markdown-blog-posts.md
Fix for the misleading aforementioned docs:
Cannot query field "path" on type "MarkdownRemarkFrontmatter"
Since there is no mention of `path` on the docs 'Adding Markdown Pages' on createPages api of gatsby-node.js.
Using path would throw the error. Hence using slug as it is aforementioned in the adding markdown pages helps.
> docs(gatsby): Update path to slug

- docs/docs/glossary/markdown.md
changed:
- change `bash` to `shell` regarding the [code style guides to prefer `shell`](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#code-formatting-type-tab)
- https://www.gatsbyjs.org/contributing/gatsby-style-guide/#code-formatting-type-tab
- extracted from #22899 `fix(docs): change bash to shell in code language blocks`
> fix(docs): glossary/markdown - change bash to shell

- docs/docs/glossary/build.md
- docs/docs/glossary/infrastructure-as-code/index.md
- docs/docs/glossary/jamstack.md
- docs/docs/glossary/npm.md
This PR removes a few `<abbr>` elements that aren't needed, as the text is defined in surrounding body copy.
N/A
Closes https://github.com/gatsbyjs/gatsby/issues/24505
> docs(gatsby): remove unnecessary abbr tags

- packages/gatsby-recipes/recipes/travis-deploy-github-pages.mdx
- packages/gatsby-recipes/src/cli.js
changes:
- brand names
- Github -> GitHub
- travis-ci -> Travis CI
- Travis -> Travis CI
- #23669 `feat(recipes): add github pages deployment with travis`
> fix(recipe): GitHub Pages - brand names

- packages/gatsby/src/commands/develop.ts
This should fix Codesandbox sometimes exposing the wrong port.
They simply expose the first port that is ever opened at `:80`, which before could be the random port assigned to the actual develop process.
By always starting the proxy at `:8000` (or the user selected port), Codesandbox _should_ always expose that port at `:80`, resolving any incompatibilities.
> Start develop proxy before actual develop process

- packages/gatsby/src/commands/serve.ts
Currently if we generate a page which name starts with a dot `.` it will not be served correctly by `gatsby serve`. The actual behavior is even stranger because the server returns the `404` page, but then the client side rendering picks it up and actually re-renders the page.
This change fixes this behavior by allowing the serving of `dotfiles` from the static `public` directory.
> feat(gatsby): allow serving of dotfiles from public folder

- packages/gatsby-source-filesystem/index.d.ts
This PR fixes broken typings of `createRemoteFileNode` (in `gatsby-source-filesystem`).
Using `NodePluginArgs["cache"]` instead of `GatsbyCache` because it is compatible with both - new and old versions of gatsby. Using `GatsbyCache` will only work with `gatsby@^2.22.13` and will break with older versions.
N/A
Fixes #24735
> fix(gatsby-source-filesystem): Update typings for createRemoteFileNode

- packages/gatsby/index.d.ts
Typo in the usage documentation for the PageProps generic type. There is currently a circular reference of IndexPageProps. This PR updates the first generic type argument in the example to be the DataProps, as reflected in the [default starter](https://github.com/gatsbyjs/gatsby-starter-default/blob/f91dd295d9df896d1c5521a2886567f2dae93b40/src/pages/using-typescript.tsx#L14).
> update documentation for PageProps type definition

- docs/docs/adding-a-list-of-markdown-blog-posts.md
In the page of the tutorial named [Adding Markdown Pages](https://www.gatsbyjs.org/docs/adding-markdown-pages/), the variable used to define the path in the Markdown frontmatter is called `slug`.
The next page, [Adding a List of Markdown Blog Posts](https://www.gatsbyjs.org/docs/adding-a-list-of-markdown-blog-posts/), uses variable `path` in the remindering frontmatter and in the PostLink component code.
This PR is a quick & simple fix that uses the variable name `slug`.
Did not find any related issue by looking for "[slug](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+sort%3Aupdated-desc+slug+)" or "[PostLink](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+sort%3Aupdated-desc+PostLink)" in recent GitHub issues.
> chore(docs): Update adding-a-list-of-markdown-blog-posts

- packages/gatsby/src/redux/__tests__/run-sift.js
- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/node-model.js
- packages/gatsby/src/schema/__tests__/run-query.js
Drops some Sift related stuff from the tests. Was already unused, just dropping the "framework" of testing with and without Sift, if you will.
Suggest to read diff without whitespace changes ;)
> chore(gatsby): cleanup some sift remnants from tests

- starters/blog/src/pages/index.js
- starters/blog/src/pages/using-typescript.tsx
Follow-up of https://github.com/gatsbyjs/gatsby/pull/24565
Didn't realize that we also need to change it in the `blog` starter
> fix(gatsby-starter-blog): Move typescript usage to other file

- packages/gatsby/src/db/nodes.js
- packages/gatsby/src/redux/__tests__/run-sift.js
- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
- packages/gatsby/src/schema/__tests__/run-query.js
- packages/gatsby/src/utils/__tests__/__snapshots__/prepare-regex.js.snap
- packages/gatsby/src/utils/__tests__/prepare-regex.js
This removes a couple of mentions of Sift, also as part of variable and function names. 
Also some refactoring in run-sift.js which should not change the semantics.
> chore(gatsby): remove mentions of sift and refactor

- packages/gatsby/index.d.ts
Rather than re-implementing the `Reporter` types, this re-exports the types from gatsby-cli, which is now properly typed.
> chore(gatsby): Re-export reporter types from gatsby-cli

- packages/gatsby/package.json
- yarn.lock
Removes `sift` as a Gatsby dependency.
> chore(gatsby): remove `sift` as a Gatsby depency 

- packages/gatsby-cli/package.json
https://github.com/gatsbyjs/gatsby/pull/24381 introduced chain where `gatsby-cli` source files try to use build `gatsby-cli` files:
- https://github.com/gatsbyjs/gatsby/blob/96dbf2b42239efd892a9a1d2384daf1fff36b7be/packages/gatsby-cli/src/reporter/loggers/ink/context.tsx#L3
- https://github.com/gatsbyjs/gatsby/blob/96dbf2b42239efd892a9a1d2384daf1fff36b7be/packages/gatsby/src/redux/types.ts#L7
- https://github.com/gatsbyjs/gatsby/blob/96dbf2b42239efd892a9a1d2384daf1fff36b7be/packages/gatsby/src/schema/infer/inference-metadata.ts#L64
- https://github.com/gatsbyjs/gatsby/blob/96dbf2b42239efd892a9a1d2384daf1fff36b7be/packages/gatsby/src/schema/infer/type-conflict-reporter.ts#L2
This weirdly doesn't cause issues other than `tsc` errors when trying to build already built package and it manifest …
> chore(gatsby-cli): delete *.d.ts files before creating new ones

- CODEOWNERS
Right now `/benchmarks/` is partially owned by core (`*`) and learning (`**/README.md`) which makes it frustrating to maintain code there for folks who really own that code. This PR adds actual owners.
I can create `bechmarks` team if we don't want individual accounts mentioned in CODEOWNERS
> chore(CODEOWNERS): define rule for /benchmarks/

- www/README.md
- www/gatsby-config.js
Add two new env variables, `DISABLE_SOURCE_DOCS` and `DISABLE_NPM_SEARCH` to provide a way to run the Gatsby site without expensive sourcing.
The gatsby site usually takes ~30 mins to run. When these env variables are turned on, the build time is ~30 seconds.
This makes it easier to build the site for devs who just want to edit components that aren't in these pages, and for contributors to work on the website without having to download all the docs/blog (using `git clone —sparse`).
More granular ways to enable sections — for example, being able to disable everything except `tutorials/` and `starters/`. I was thinking of using the `ignore:` property on `gatsby-source-filesystem` but I haven't been able to get the globs to play nice with me. 🤷‍♀️ 
This PR builds off work from #24943
> maintenance(www): add environment variables to disable sourcing from docs/plugins

- packages/gatsby/src/bootstrap/create-graphql-runner.ts
Instead of re-creating the GQL runner on every node change, we set it to undefined and then re-create it when next needed
> perf(gatsby): Lazily re-create GraphQL runner

- packages/gatsby-core-utils/src/__tests__/create-content-digest.ts
- packages/gatsby-core-utils/src/create-content-digest.ts
When buffer we should just use crypto as node-object-hash isn't working correctly with coerce false.
Fixes https://github.com/gatsbyjs/gatsby/issues/21840
> fix(gatsby-core-utils): fix hash for buffers

- packages/gatsby/src/redux/actions/public.js
Value can be anything, not just string.
Closes #23852
> chore(docs): Update documentation for createNodeField

- packages/gatsby-plugin-offline/src/gatsby-node.js
> fix(sw): use NetworkFirst strategy for page-data

- packages/gatsby/src/utils/__tests__/webpack-utils.ts
- packages/gatsby/src/utils/webpack-utils.ts
- Changed types for PostCSS plugins from webpack `Plugin` type to PostCSS
`Plugin<T>` type.
- Added a check of each plugin's `postcssPlugin` property; a plugin
with a `postcssPlugin` property equal to `autoprefixer` will have its
options assigned to the default.
Hopefully this is just a fix and should not change the public interface. There are however references to it here https://www.gatsbyjs.org/docs/post-css/#postcss-plugins and here https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass#postcss-plugins
Addresses #15509, #17428, #11984
> fix(gatsby): allow amending autoprefixer options

- packages/gatsby/src/utils/eslint-config.ts
Refine a11y linting rules so that some trigger alerts or dialogs instead of warnings.
Fixes #24582
> chore(eslint-config): change eslint to better match strict ruleset

- packages/gatsby-source-drupal/README.md
- packages/gatsby-source-drupal/src/__tests__/fixtures/webhook-file-update.json
- packages/gatsby-source-drupal/src/__tests__/index.js
- packages/gatsby-source-drupal/src/gatsby-node.js
- packages/gatsby-source-drupal/src/utils.js
This PR adds a skipFileDownloads config option to gatsby-source-drupal. This is useful when using a Drupal site and some third party image processing solution. By enabling this config option Gatsby will not download the remote files which will significantly speed up builds that don't use Gatsby's image processing.
This is documented in the gatsby-source-drupal plugin README file.
This change would help with issues like this #24257
> feat(gatsby-source-drupal): Add skipFileDownloads config option

- packages/gatsby-source-shopify/src/queries.js
Shopify Storefront API provides a handle field for Article + Blog queryable objects. gatsby-source-shopify package is missing the field for these queries.
> feat(gatsby-source-shopify): Add handle field to blog + article queries

- starters/gatsby-starter-blog-theme/package-lock.json
- starters/gatsby-starter-blog-theme/package.json
For some reason theme-ui is not being hoisted in the blog theme when using npm. This bug does not exist when using yarn.
As a workaround, adding theme-ui to the starter dependencies.
Closes #25093
> chore(starters): Add theme ui as dependency to solve npm bug

- docs/docs/client-only-routes-and-user-authentication.md
This PR briefly points to how to configure nginx and apache for enabling client-only routes.
> docs: configure nginx and Apache for client-only routes

- docs/tutorial/part-four/index.md
Removed "easily" word from sentence following issue #18702 to appear more interactive.
Addresses #18702
> docs(tutorial-part-four): remove word "easily"

- docs/docs/how-gatsby-works-with-github-pages.md
Closes https://github.com/gatsbyjs/gatsby/issues/24979
Just changed `:warning:` to a real emoji character. If the emoji is not allowed (I don't know the documentation rules) we can maybe remove it?
> Fix warning section in the "deploying to GitHub pages" documentation

- docs/docs/troubleshooting-common-errors.md
This recently came up in #24815  but is littered throughout GitHub issues with many emoji responses. This PR puts the solution/fix directly in the common troubleshooting docs.
I felt that's where it was most appropriate, but open to other ideas as well.
> Documentation: fs solution is found in multiple GitHub issues and should be in the docs

- docs/docs/debugging-the-build-process.md
Minor English fixes in https://www.gatsbyjs.org/docs/debugging-the-build-process/.
What I think would be of great value in this guide, is advice on [how to debug server-side component rendering within React components](https://github.com/gatsbyjs/gatsby/issues/25037).
> docs: improve English in Debugging the build process

- packages/gatsby-cli/cli.js
- packages/gatsby-cli/package.json
- packages/gatsby/cli.js
- packages/gatsby/package.json
Currently we point `bin` to files that have to be built. That means that first time running `yarn` will not create actual `node_modules/.bin` files. This cause problems in CI in some cases - like in https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/43431/workflows/5f2af482-c297-489f-aecf-dbfec72a45b8/jobs/440080/steps where `gatsby-admin` can't be built because `bin` for neither `gatsby` nor `gatsby-cli` is created yet
> fix(bin): point bin to always existing files

- docs/docs/mdx/migrate-remark-to-mdx.md
- www/src/data/sidebars/doc-links.yaml
A documentation page on migrating a Gatsby site using gatsby-transformer-remark to use MDX.
Closes #23502
> feat(docs): page on migrating remark -> mdx

- docs/docs/tailwind-css.md
Twin.macro is now out of alpha and so I've updated the usage example.
> Update twin.macro installation instructions

- packages/gatsby/src/utils/page-data.ts
- packages/gatsby/src/utils/worker/child.ts
Remove every trace of page-data from jest-worker. https://github.com/gatsbyjs/gatsby/pull/23991/ included our reporter inside a jest-worker and messed up ipc communication for a worker.
This doesn't fix the underlying issue but at least unblocks us for now.
> fix(gatsby): remove page-date from jest-worker

- packages/gatsby-remark-embed-snippet/README.md
changes:
- add source code snippets with `no-highlight` to be rendered nice on https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/#highlighting-lines
- shoud we add a `source` and `result` line before each?
- on github https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-embed-snippet/README.md they would rendered twice (because highlight lines commands are not processed)
- while on Gatsby docs page https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/#highlighting-lines they rendered as source/result
- #24821 `fix(gatsby-remark-embed-snippet): readme - change code language`
> fix(gatsby-remark-embed-snippet): readme - add example sources

- www/src/components/skip-nav-link.js
I was testing something on the Gatsby site and noticed the skip link has some extra cruft in it from a find and replace or something, so this PR cleans it up.
N/A
The code was introduced in this commit: https://github.com/gatsbyjs/gatsby/commit/a6008314655eabafcd00388a94f21758b4d64733#diff-c8638feb462d5fe251bbae9403d62616
> chore: skip link markup cleanup

- docs/docs/creating-and-modifying-pages.md
This PR adds a brief note at https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages that Date objects are also subject to serialization.
> docs: mention pageContext serialization affect on Dates

- docs/docs/debugging-the-build-process.md
change: 
- brand name `Node` -> `Node.js`
- #25035 `docs: improve English in Debugging the build process`
> fix(docs):  debugging-the-build-process -> brand name Node -> Node.js

- docs/contributing/how-to-label-an-issue.md
In the how to label an issue doc (https://www.gatsbyjs.org/contributing/how-to-label-an-issue/) the `Help Wanted` link currently points to https://github.com/gatsbyjs/gatsby/labels/%F0%9F%93%8D%20status%3A%20help%20wanted which returns no results. Updated to point to https://github.com/gatsbyjs/gatsby/labels/help%20wanted
> chore(docs): update help wanted label link

- starters/blog/package.json
- starters/default/package.json
- starters/hello-world/package.json
This and derived starter templates have .ts or .tsx files that are not being processed by Prettier when running.
This PR addresses that.
If I search for `prettier --write` in the monorepo there are other occurrences where this might need to be fixed. 
Should I send another PR fixing all of those?
Example:
> chore: add typescript formatting to prettier

- examples/using-i18n/src/components/localizedLink.js
Fixes https://github.com/gatsbyjs/gatsby/issues/25170
Without the slash the path was relative and thus the current path was added.
https://github.com/gatsbyjs/gatsby/pull/24054
> fix(using-i18n): Add slash to make absolute path, not relative

- packages/gatsby/src/utils/__tests__/jobs-manager.js
- packages/gatsby/src/utils/jobs-manager.js
We didn't always show error messages correctly, especially on our cloud platform.
> fix(gatsby): show error message instead of [Object object]

- packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
This will prevent the benchmark plugin from emitting "not yet finished flushing" stack traces when an error happened during building and no reporter url was given in the first place.
> chore(gatsby-plugin-benchmark-reporting): dont emit flush error without url

- packages/gatsby/src/bootstrap/index.ts
- packages/gatsby/src/commands/build.ts
- packages/gatsby/src/commands/develop-process.ts
This just shuffle services around in preparation for more concrete features from https://github.com/gatsbyjs/gatsby/pull/24903 (which will need queries to run before webpack, as well as requires-writer to run after queries (and before webpack) )
Tracking PR for data-driven code-splitting - https://github.com/gatsbyjs/gatsby/pull/24903
> refactor: run page queries together with static queries and run requires writer after queries

- packages/gatsby/src/redux/run-fast-filters.ts
Converts the `module.exports` pattern to es6 `export` syntax in `packages/gatsby/src/redux/run-fast-filters.ts`
> fix(gatsby): convert module.exports to es6 in redux/filters

- packages/gatsby-dev-cli/src/watch.js
https://github.com/gatsbyjs/gatsby/pull/25121 changed bin files, but `gatsby-dev-cli` doesn't know about those and it's not applying executable permissions on those files. This PR fixes it
Related PR: https://github.com/gatsbyjs/gatsby/pull/25121
> fix(gatsby-dev-cli): chmod new bin files

- packages/gatsby/cache-dir/query-result-store.js
- packages/gatsby/src/utils/page-data.ts
- packages/gatsby/src/utils/websocket-manager.ts
This changes our websocket manager to emit full body of `page-data` and not just query results + streamlines what we pass to `emitPageData`. 
This change on its own it's not doing much, it's just preparation to pass `page-data` emitted by websocket to run through `loader` to make sure we load modules that could have been added as a result of query running
Tracking PR for data-driven code-splitting - https://github.com/gatsbyjs/gatsby/pull/24903
> refactor(websocket): unify page-data emitting

- packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
- packages/gatsby/src/utils/__tests__/webpack-utils.ts
- packages/gatsby/src/utils/__tests__/webpack.config.js
- packages/gatsby/src/utils/babel-loader.js
- packages/gatsby/src/utils/webpack-utils.ts
Mover terser & babel cache into .cache folder instead of default node_modules location. This helps to make sure changes like #15601 actually get applied.
https://twitter.com/wardpeet/status/1266504690704973824
Related to #5880 (I'll comment and close that one)
> chore(gatsby): move cache folders to .cache

- packages/gatsby/src/db/nodes.js
Refactors a use of `Promise` to an `async function`.
Also caches the result of calling `loadNodeContent`, as I believe was intended.
Suggest to ignore whitespace when reviewing.
Next step will be to convert this file to TS, but I didn't want to combine those two steps in one PR.
> chore(gatsby): convert loadNodeContent to async and cache it

- www/src/components/api-reference/doc-block.js
Fixes #24914 
Links to source for api docs is broken. (See https://www.gatsbyjs.org/docs/browser-apis/, https://www.gatsbyjs.org/docs/ssr-apis/, etc.)
https://github.com/gatsbyjs/gatsby/pull/24330 made it so only the `/packages/gatsby` dir is sourced, which I think is what broke the source link for api docs. Linking to `/packages/gatsby/` instead of just `/packages` fixes the 404 for the link to source.
> fix(www): fix APILink to source pointing to wrong location

- packages/gatsby-react-router-scroll/src/scroll-handler.tsx
@blainekasten introduced a number of improvements to scroll handling in https://github.com/gatsbyjs/gatsby/pull/24306.
In the `scrollToHash` function, we should use `document.getElementById` to find the correct node instead of `document.querySelector`.
The HTML standard allows almost any string to be used as an `id` attribute:
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
From: https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute
`document.querySelector` expects a valid CSS selector string, and will throw an exception if you do not supply one:
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector …
> fix(gatsby-react-router-scroll): replace querySelector with getElementById

- packages/gatsby-cli/package.json
Add missing `common-tags` types, which otherwise generates the following error when compling with `noImplicitAny`:
```
node_modules/gatsby-cli/lib/reporter/reporter.d.ts:23:25 - error TS7016: Could not find a declaration file for module 'common-tags'. '/Users/gosha/Documents/git/repro-no-common-tags-types/node_modules/common-tags/lib/index.js' implicitly has an 'any' type.
Try `npm install @types/common-tags` if it exists or add a new declaration (.d.ts) file containing `declare module 'common-tags';`
23     stripIndent: import("common-tags").TemplateTag; 
```
Fixes #25129
> fix(gatsby-cli) add missing @types/common-tags

- docs/contributing/rfc-process.md
The docs are out of date since we deprecated the rfcs repo. This is just an update to the location of the RFCs
> chore(rfcs): Update documentation on RFC for its location in gatsbyjs/gatsby

- docs/starters.yml
A landing page starter with PaperCSS useful for multiple occasions, such as workshops, concepts, or websites for educational material.
> chore(starters): add gatsby-starter-paper-css-landing-page

- packages/gatsby-plugin-sharp/src/__tests__/index.js
- packages/gatsby-plugin-sharp/src/index.js
@jamo reported this issue, while we change the image of the content we do not update the base64 as the cachekey uses nodeId and not contentdigest.
> fix(gatsby-plugin-sharp): use contentdigest for base64 cache

- docs/docs/tailwind-css.md
changes:
- fix typo `postCSSPlugins` to `postCssPlugins`
> docs: fix typo postCssPlugins in tailwind-css docs

- packages/gatsby-source-contentful/package.json
- packages/gatsby-source-contentful/src/__fixtures__/starter-blog-data.js
- packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-node.js.snap
- packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
- packages/gatsby-source-contentful/src/fetch.js
- packages/gatsby-source-contentful/src/gatsby-node.js
- packages/gatsby-source-contentful/src/normalize.js
This PRs is an attempt to fix missing data on content changes at contentful.
the gatsby-source-plugin is using the Contentful SDK which is calling the sync API behind the scene for the first sync the SDK will have all the data available to it so it can perform the link resolution however in the subsequent sync the API will return only the changed entries which is not enough data for the SDK to do the link resolution.  
By saving the previous sync data and using it later to do link resolution we make sure that all links are resolved
* https://github.com/contentful/rich-text/issues/94
> fix(gatsby-source-contentful): fix missing data with rich text fields

- docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
Ref. https://github.com/gatsbyjs/gatsby/issues/25240, https://github.com/gatsbyjs/gatsby/pull/25239
<3 @sidharthachatterjee
> chore(blog): Bring back links in `Pullquote citation`

- docs/blog/2020-06-23-Reconfiguring-Gatsby-Days/index.md
This converts the images linking to YouTube in https://www.gatsbyjs.org/blog/2020-06-23-Reconfiguring-Gatsby-Days/ to embedded YouTube videos (via [`gatsby-remark-embedder`](https://www.gatsbyjs.org/packages/gatsby-remark-embedder/)).
We loose control over what placeholder image is shown, yes — but that's about the only drawback I can see.
Hmmmm, well, on second thought … maybe a bit of SEO sauce?
Still _looks_ OK IMO — while _working_ much better IMO — as a user, I expect these to be playable without having to leave the page:
> chore(blog): YouTube videos via `gatsby-remark-embedder`

- dictionary.txt
Add missing dictionary definition causing lint to break.
> fix(docs): Add missing definition

- www/src/components/docsearch-content.js
- www/src/components/page-with-sidebar.js
- www/src/components/slider.js
Give name to the anonymous function exported by `<PageWithSidebar/>`, `<DocSearchContent/>` and `<Slider/>` component, also convert them to function declaration.
There is some CSS cleanup also.
**Why should we consider giving them name?**
Anonymous functions have no useful names to display in stack traces, which can make debugging more difficult. Also a descriptive name helps self-document the code.
> fix(www): give name to anonymous exported function

- www/src/utils/is-official-package.js
As we transition to the new themes repo we want themes to be marked as official plugins on the website. This will allow for that.
> Change official plugins testing condition

- docs/docs/internal-data-bridge.md
This PR updates the docs at this page https://www.gatsbyjs.org/docs/internal-data-bridge/#site to provide more info about the `Site.siteMetadata` field.
The todo on that page mentions https://github.com/gatsbyjs/gatsby/issues/14228 but I'm not totally sure that that's the right issue since that's about Schema Customization and this is about the internal data bridge.
> feat(docs): Add explanation of Site.siteMetadata field

- packages/gatsby-plugin-sass/README.md
I know it's nitpicky, but just wanted to make it follow the Sass brand guidelines. 😄
> chore(docs): Correct capitalization for Sass

- package.json
- packages/gatsby/package.json
- packages/gatsby/src/utils/start-server.ts
- yarn.lock
This pull request just exposes ability to `pause`/`resume` webpack watching, but doesn't make any use of it yet. Main reason to split this to its own PR is the hairy TS situation:
- missing types (upstream) on `webpack-dev-middleware` - `context` is skipped there, but according to https://github.com/webpack/webpack-dev-middleware/issues/656#issuecomment-639516772 `context` is public API and needs documentation
- missing types (upstream) on `webpack.Watching` - https://github.com/webpack/webpack/pull/9214 added `suspend`/`resume` to `Watching` but those are missing from `@types/webpack`
Tracking PR for data-driven code-splitting - #24903
[CH9864]
> refactor(develop): expose APIs to suspend/resume webpack watching to gatsby internals

- packages/gatsby-plugin-mdx/gatsby/source-nodes.js
Add the `childOf` extension to the `Mdx` node type to aid in populating types.
This is equivalent to:
```
type Mdx implements Node @childOf(mimeTypes: ["text/markdown", "text/x-markdown"]) {
}
```
This makes the typing more robust so that anything with `@mimeTypes(types: ["text/markdown", "text/x-markdown"])` immediately get `childMdx` even if no nodes are created.
> fix(gatsby-plugin-mdx): set childOf extension for Mdx type definition

- packages/gatsby-transformer-documentationjs/src/gatsby-node.js
* Add `@childOf` directive to `DocumentationJs` type to verify it's a descendant of File nodes.
* Add `type DocumentationJSComponentDescription` and add a `@mimeTypes` to specify it's a Markdown node.
#25112
> fix(gatsby-transformer-documentationjs): Add childOf, mimeTypes and fill in other schema typings

- www/src/components/guidelines/box-with-border.js
- www/src/components/guidelines/color/card.js
- www/src/pages/guidelines/logo.js
1. Convert the `<BoxWithBorder/>` component to theme-ui
2. Cleanup of CSS
1. Go to the https://www.gatsbyjs.org/guidelines/logo/ page.
2. The BoxWithBorder component is used in multiple sections of this page.
3. The production and local should look similar, just the implementation of component is different.
**Local URL:** http://localhost:8000/guidelines/logo/
**Production URL:** https://www.gatsbyjs.org/guidelines/logo/
> chore(www): convert BoxWithBorder to theme-ui

- www/src/components/banner.js
Clean up some code in 
* code the styles directly (`innerContainerStyles`) instead of creating wrapper components
* apply the styles for OutboundLink directly
* get rid of a mediaQuery
* move inner content to a `BannerContent component`.
> refactor(www): Clean up "styled components" in <Banner />

- www/src/components/shared/pullquote.js
Refactor the `<Pullquote>` component to use theme-ui instead of styled-component style. In addition, refactor the styling for the star positions to make it more clear what the styles are doing.
Follow-up of #25282
> refactor(www): Convert Pullquote to use theme-ui

- www/src/components/homepage/homepage-logo-banner.js
Switch from template literal/string styles to [`sx`](https://theme-ui.com/sx-prop) and object styles.
> chore(www): Refactor `homepage-logo-banner`

- packages/gatsby-design-tokens/package.json
Running `yarn run watch` on Gatsby is currently broken. This is because `microbundle` 0.12.2 does not seem to support being passed regexps on the command line anymore; replacing files specified as regexps by a list of time.
Fixes #25368
> fix(gatsby-design-tokens): yarn run watch broken

- docs/categories.yml
Hi Team,
With rise of Ghost as Headless CMS, it would be helpful for Gatsby community to add and filter starters with CMS:Ghost.
-Regards,
Keyur
> Add Ghost as CMS in starter tags.

- www/gatsby-node.js
- www/src/utils/node/creators.js
- www/src/utils/node/docs.js
- www/src/utils/node/packages.js
- www/src/utils/node/showcase.js
- www/src/utils/node/starters.js
Rearrange the various node APIs in www by the their step in the build process, so e.g. `onCreateNode` comes before `createPages`.
> refactor(www): Rearrange node apis in gatsby-node by build step

- packages/gatsby-transformer-documentationjs/src/gatsby-node.js
Followup of #25113. Fix the `@childOf` declaration in the `DocumentationJs` type so that the parent types properly get `childrenDocumentationJs` instead of `childDocumentationJs`.
> fix(gatsby-transformer-documentationjs) Add  many: true to @childOf declaration in DocumentationJS

- www/src/templates/template-blog-post.js
I ran the axe extension against my most recent blog post about accessibility, and found a quick win with the blog avatar image which was missing alt text. Now the link wrapping it will have alternative text and be more usable in assistive tech!
N/A
N/A
> fix: add alt text to blog avatar image

- www/package.json
- www/src/utils/node/docs.js
Remove the handwritten schema overrides for DocumentationJS nodes in www. This allows us to turn www into a plugin while still being flexible with whether sources exist or not.
Follow-up of #25113 #25394 #25112.
> maintenance(www): Remove schema overrides for documentationJS

- docs/docs/mdx/migrate-remark-to-mdx.md
changes:
- fix values for plugin
- fix gatsby-config to gatsby-config.js
- fix code block language
- #23832 `feat(docs): page on migrating remark -> mdx`
> fix(docs): Migrate to MDX -> code fences, code block language

- dictionary.txt
- docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
In this PR we reference issue #25290 where they have asked to: put filenames like .htaccess in code blocks.
We do this by finding all instances of `.htaccess` that are not in code blocks yet and then add a code block around them. I then remove .htaccess from the dictionary.
> enhancement(docs): dictionary.txt -> .htaccess -> File names in code blocks

- docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
changes:
- unify email to be same like in line 75
- no need for markdown syntax around emails
- #25173 `Blog: Announcing partner program` 
- 38eed44 `Fix linting`
- #25198 `fix(blog): Mail link in partner program`
> fix(blog): Partner Program - remove markdown links from email

- docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
changes:
- change references from now to vercel
- #24019 `[Umbrella] Rename Zeit to Vercel`
> fix(blog): publish multiple sites: change now to vercel

- packages/gatsby/src/services/build-schema.ts
- packages/gatsby/src/services/calculate-dirty-queries.ts
- packages/gatsby/src/services/create-pages.ts
- packages/gatsby/src/services/run-page-queries.ts
- packages/gatsby/src/services/run-static-queries.ts
- packages/gatsby/src/services/source-nodes.ts
- packages/gatsby/src/services/write-out-requires.ts
- packages/gatsby/src/utils/assert-store.ts
Adds a helper function to assert the existence of a Redux store. I'd normally say we should make this more generic and pass in a message or something, but I have done this specific check so many times I think it justifies having a specific version that includes the error message. There are several files that use it in master, and a lot more in the state machine branches.
> refactor(gatsby): Move store assertion into helper

- docs/docs/ab-testing.md
- docs/docs/adding-app-and-website-functionality.md
- docs/docs/adding-page-transitions.md
- docs/docs/adding-search.md
- docs/docs/api-reference.md
- docs/docs/conceptual-guide.md
- docs/docs/css-in-js.md
- docs/docs/css-libraries-and-frameworks.md
- docs/docs/customization.md
- docs/docs/debugging.md
- docs/docs/deploying-and-hosting.md
- docs/docs/graphql.md
- docs/docs/guides.md
- docs/docs/headless-cms.md
- docs/docs/partnering-with-gatsby.md
- docs/docs/performance.md
- docs/docs/plugins-themes-and-starters.md
- docs/docs/preparing-for-site-launch.md
- docs/docs/preparing-your-environment.md
- docs/docs/releases-and-migration.md
- docs/docs/styling.md
- docs/docs/testing.md
- docs/docs/themes.md
- docs/docs/using-gatsby-professionally.md
- www/src/templates/template-docs-markdown.js
- www/src/utils/node/docs.js
Remove an unused `overview` label from frontmatter.
> maintenance(docs, www): Remove unnecessary overview from frontmatter

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-source-filesystem/package.json
- packages/gatsby/package.json
- packages/gatsby/src/redux/machines/page-component.ts
- yarn.lock
`xstate@4.11.0` was released few hours ago and is causing some problems, this PR explicitly updates `xstate` (which users can install right now themselves if lock files are not used)
See https://github.com/davidkpiano/xstate/releases/tag/xstate%404.11.0 
In particular:
> New property introduced for eventless (transient) transitions: always, which indicates a transition that is always taken when in that state. Empty string transition configs for transient transitions are deprecated in favor of always
```diff
// ...
states: {
playing: {
+   always: [
+     { target: 'win', cond: 'didPlayerWin' },
+     { target: 'lose', cond: 'didPlayerLose' },
+   ],
on: {
// ⚠️ Deprecation warning
-     '': [
-       { target: 'win', cond: 'didPlayerWin' },
-       { target: 'lose', cond: 'didPlayerLose' …
```
> chore: update xstate and adjust code to not use deprecated transient transitions

- packages/gatsby-design-tokens/src/theme-gatsbyjs-org.js
- packages/gatsby-design-tokens/src/theme.js
- www/src/components/banner.js
Add borders to the design tokens theme so that we can do stuff like #25460.
> fix(gatsby-design-tokens): Add border definitions to theme

- packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap
- packages/gatsby-transformer-documentationjs/src/__tests__/fixtures/same-name.ts
- packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js
- packages/gatsby-transformer-documentationjs/src/gatsby-node.js
Wasn't finding typedefs for interfaces with the same name as the typed thing; e.g.
```ts
interface Foo {}
const Foo: Foo
```
Also adds a guard and more helpful error when unavoidable loops occur due to type naming
> fix: incorrect typedef parsing for interfaces

- www/src/components/sidebar/__tests__/sidebar.js
- www/src/utils/sidebar/get-active-item.js
Getting the active item for breadcrumbs and the sidebar fails if the pathname does not end in a trailing slash. This is because all the links in docs item list end with a trailing slash.
There are different ways I could approach fixing this. I thought the easiest would just be to add a trailing slash if it was missing, let me know if you think a different approach would be better.
Fixes: #20767
> fix(www): Fix getting active item when pathname does not end with /

- docs/docs/unit-testing.md
`jest.preprocess.js` should be `jest-preprocess.js`
> chore(docs): Fix file name typo

- dictionary.txt
- docs/docs/schema-gql-type.md
- docs/docs/schema-input-gql.md
In this PR we reference issue #25290 where they have asked to: put code like inferInputObjectStrctureFromNodes in code blocks. I have identified there are a few more cases of these code which I have also taken care of.
We do this by finding all instances of all strings prefixed with infer[X] that are not in code blocks yet and then add a code block around them. I then remove all of those strings from the dictionary.
> enhancement(docs): dictionary.txt -> Infer* -> putting all code prefixed with infer into code blocks

- packages/gatsby/cache-dir/__tests__/static-entry.js
- packages/gatsby/cache-dir/app.js
- packages/gatsby/cache-dir/production-app.js
- packages/gatsby/cache-dir/static-entry.js
- packages/gatsby/package.json
- packages/gatsby/src/bootstrap/requires-writer.ts
- packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts
- packages/gatsby/src/utils/webpack-utils.ts
- packages/gatsby/src/utils/webpack.config.js
- yarn.lock
This avoids adding `fs` involved when we dynamically generate `(a)sync-requires` and `match-paths.json`files.
**Why using `fs` is problematic?**
It adds unnecessary async code to the pipeline, writing is fine (in fact I don't remove writing in this PR - see comment in `requires-writer.ts` for reaosns). It's about when we (or rather webpack watching) react to fs changes events - webpack watcher have some debounced/aggregation logic (200ms afaik) + any system level delays (from writing to fs, to receiving FS change event in watchpack/chokidar).
This PR on its own is not solving lot of problems, but it makes it easier for future PRs that try to coordinate our services to avoid pitfalls of some debounced state transitions
[CH9862]
> refactor(gatsby): use virtual modules for `(a)sync-requires` and `match-paths.json`

- packages/gatsby-source-contentful/.npmignore
It wasn't ignoring the fixtures. I also made it ignore any `__tests__` rather than just the one in `src`.
> fix(gatsby-source-contentful): dont ship fixtures when publishing

- docs/contributing/how-to-contribute.md
- docs/contributing/where-to-participate.md
Removed references to specific Gatsby personnel in favor of group-monitored, generic avenues.
> docs(contributing): Anonymized contact information for reaching DevRel

- docs/blog/gazette-june-2020/index.md
changes:
- remove local domain
- plugin name in code fences
- #25423 `(blog) Draft of June Gatsby Gazette`  
> fix(blog): gazette june - remove local domain, add plugin name in code fences

- packages/gatsby/src/commands/develop.ts
`gatsby develop` currently exits with `0` code in some scenarios where it shouldn't - in particular when fatal out-of-memory happens in develop child process:
When OOM happens child process exit handler will get `code = null` and `signal = "SIGABRT"`, because right now we don't check signal part we exit parent process with `null` code (`process.exit(null)`), which actually translates into `process.exit(0)` which is wrong.
> fix(gatsby): correctly pass through exit signals from child process

- docs/sites.yml
changes:
- fix 404 link ellingtonhammond.com -> ellington-hammond.com
- one typo
- #25301 `chore(showcase): add ellingtonhammond.com`
- #25357 `chore(showcase): https://lidabox.com website`
> fix(showcase): 404 link ellingtonhammond.com -> ellington-hammond.com

- packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
- packages/gatsby-source-contentful/src/download-contentful-assets.js
- packages/gatsby-source-contentful/src/gatsby-node.js
Gatsby maintains an internal cache of nodes by type. Before this PR the Contentful plugin would do a `getNodes().filter(n => n.type === 'ContentfulAsset')`, which is doing that. The ``n.internal.owner === `gatsby-source-contentful` `` part is redundant because in the only function that calls this function all nodes are already tagged like that so this is never false.
The expected perf gain is minor but at scale this is one fewer times of looping through all nodes.
> perf(gatsby-source-contentful): use internal cache to get nodes by type

- packages/gatsby-source-contentful/src/fetch.js
- packages/gatsby-source-contentful/src/normalize.js
This adds an experimental flag, `EXPERIMENTAL_CONTENTFUL_SKIP_NORMALIZE_IDS`, to skip the normalization step when sourcing from Contentful.
This step would take the `sys.id` and force it to a string and not start with a number. This step is quite expensive at scale, easily taking 5 minutes or more, because it has to traverse every property on every object of the content retrieved by Contentful.
While this step may have been necessary a long time ago, everybody agrees that today it's not required.
We may concretely remove the step in the future, but since that's a breaking change (people can query the `contentful_id` field in graphql, or access the `contentful_id` property directly inside a node) that's going to take a little longer to be published. This flag serves as a workaround until …
> perf(gatsby-source-contentful): experimental flag to skip id normalization

- packages/gatsby-recipes/package.json
Ink-box requires React, so gatsby-recipes needs to provide it. The peer dependency is currently missing.
https://github.com/yarnpkg/berry/runs/840615717?check_suite_focus=true
> Adds react as a peer dependency

- www/src/utils/get-prev-and-next.js
- www/src/utils/node/docs.js
Clean up and simplify the get-prev-and-next utility function used to calculate the previous and next doc page. This also fixes a small bug where [Docs and Blog Components](https://www.gatsbyjs.org/contributing/docs-and-blog-components/) leads to a link that does not exist.
> refactor(www): clean up get-prev-and-next

- packages/gatsby-plugin-mdx/utils/gen-mdx.js
- packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Tiny refactor, no semantic change.
All the args to the toplevel `genMDX` call are passed on to mdx plugins and it's unclear what gets tucked into `...helper` there, but some keys _are_ explicit and we should be consistent in mentioning them.
At a later point we may want to get rid of this `helper` binding altogether. Or TS solves this for us. Whichever comes first.
I'm not happy about passing on these `getNode*` api's because they are raw unprotected API's that are dangerous to build perf for sites at scale. So being explicit here is also important for visibility.
> chore(gatsby-plugin-mdx): be more explicit in explicit api

- docs/categories.yml
Hi Team,
We've been seeing a lot of Ghost blogs using Gatsby front-end now. WordPress is already a category, Ghost should be too.
Thanks in advance.
-Tanmay
> chore(categories): Add Ghost to list of categories

- .circleci/config.yml
Our config doesn't exactly match the circleCI schema - the `condition` should have single condition and we currently have array (of 1). This doesn't match the schema documented in https://circleci.com/docs/2.0/configuration-reference/#logic-statements and appears that CircleCi only just recently tighten config validation in this regard as we started to see CI errors like https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/45270/workflows/81dbbd81-7189-412d-b9f0-79dd5ad40fc3/jobs/460147
> chore(circleci): fix conditional step configuration

- dictionary.txt
- docs/contributing/site-showcase-submissions.md
- docs/contributing/submit-to-starter-library.md
- docs/docs/sourcing-from-netlify-cms.md
In this PR we reference issue #25290 where they have asked to: put filenames like .yml in code blocks.
We do this by finding all instances of `.yml` that are not in code blocks yet and then add a code block around them. I then remove .yml from the dictionary.
> enhancement(docs): dictionary.txt -> .yml -> File names in code blocks

- dictionary.txt
- docs/docs/babel.md
- docs/docs/migrating-from-v1-to-v2.md
In this PR we reference issue #25290 where they have asked to: put filenames like .babelrc in code blocks.
We do this by finding all instances of `.babelrc` that are not in code blocks yet and then add a code block around them. I then remove .babelrc from the dictionary.
> enhancement(docs): dictionary.txt -> .babelrc -> File names in code blocks

- docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md
- docs/blog/2019-07-23-google-sheets-gatsby-acroyoga-video-explorer/index.md
- packages/gatsby-source-contentful/README.md
- packages/gatsby-transformer-remark/README.md
In this PR we reference issue #25290 where they have asked to: Standardize names of libraries and brands (for example, GraphQL instead of Graphql or graphQL)
We do this by finding all instances of Graphql or graphQL and replacing them with GraphQL.
> enhancement(docs): standardising graphQL and Graphql into GraphQL in README files

- www/src/components/docs-markdown-page.js
- www/src/templates/template-api-markdown.js
- www/src/templates/template-docs-markdown.js
Pull out common fields on `template-docs-markdown` and `template-api-markdown` to a GraphQL fragment.
> refactor(www) factor out common doc page content to a fragment

- packages/gatsby-plugin-mdx/gatsby/on-create-node.js
- packages/gatsby-plugin-mdx/utils/__tests__/__snapshots__/import-parser.js.snap
- packages/gatsby-plugin-mdx/utils/__tests__/import-parser.js
- packages/gatsby-plugin-mdx/utils/gen-mdx.js
- packages/gatsby-plugin-mdx/utils/import-parser.js
The mdx plugin was doing its default parsing step for every time it got called. At sourcing time it's only called to retrieve the import bindings and for this we can be much faster by manually processing the import statements. So that's what this does.
This change __reduces _baseline_ mdx processing by 30%__ by skipping a Babel parse step in one of the bootstrap steps
A very simple flat no-image mdx benchmark cuts down sourcing time in half for this change.
This are the numbers for a simple, flat, local sourced, zero-image, mdx benchmark where each mdx file is automatically generated and look like this:
```
---
articleNumber: 1
title: "Maiores iusto autem dolorum."
path: 'maiores-iusto-autem-dolorum.'
date: 2018-04-14
---
import { Link } from "gatsby"
<Link to="/">Go Home</Link> …
```
> perf(gatsby-plugin-mdx): prevent babel parse step at sourcing time

- packages/gatsby/src/utils/__tests__/api-runner-node.js
- packages/gatsby/src/utils/api-runner-node.js
In cases when plugins don't `.end()` all activities that they started, we end up with always in progress spinner / progress bars. This change make sure that if activity was started in one of gatsby-node lifecycle hooks, core will end any still in-progress activities
Open question is if this should be applied to all lifecycles. Not yet tested this out with `gatsby-plugin-sharp` which wants to actually have long running progress activity that is not tied to lifecycles, so if this would cause troubles - this is where I could see them.
This is catch-all code (for all plugins) that recently was implemented in drupal plugin ( https://github.com/gatsbyjs/gatsby/pull/25447 ) - it's still better to fix this in plugins than rely on this, because plugins can know if they should fail activity or not …
> fix(gatsby): end activity if plugin didn't do it

- docs/docs/schema-customization.md
Add documentation on `@childOf` and `@mimeTypes` schema extensions. We don't document these features *anywhere* in the docs — the only documentation that exists is the unit tests for these features. This will help plugin authors explicitly type their docs.
> enhancement(docs): Add documentation on the @childOf and @mimeTypes extensions

- docs/blog/2020-06-18-Gatsby-cli-survey-2/index.md
- examples/using-multiple-themes/README.md
I greped the repo for `)[docs` and found the following two occurrences of non-absolute links to the documentation.
> Docs links that start with docs/ rather than /docs/

- www/src/components/diagram.js
- www/src/components/homepage/homepage-get-started.js
- www/src/pages/index.js
1. Clean up the styles in `<IndexRoute/>` component
2. Create a separate component for Getting Started section
3. Move the `<Diagram/>` styles to the `<Diagram/>` component
4. Replace **css** to **sx** 
5. setupScrollersObserver & unobserveScrollers using useEffect() hook
6. Convert IndexRoute to function component
Go to the following link mentioned below and scroll down a little bit, the component should work same in both the local and production link, just the implementation of component is now different.
**Local URL:** http://localhost:8000
**Production URL:** https://www.gatsbyjs.org
> chore(www): refactor, tidy and convert Gatsby homepage to function component

- packages/gatsby-admin/src/components/navbar.tsx
- packages/gatsby-admin/src/components/providers.tsx
- packages/gatsby-admin/src/pages/index.tsx
I implemented the color treatment (i.e. "dark mode") of Admin by manually overwriting the colors of every gatsby-interface components that I use, for example:
```js
<Button sx={{ color: `white` }} />
```
However, this is tech debt that doesn't scale. To skin even the Button component with all its states (!) is difficult this way, not to mention trying to do the same for the more complex compound components in gatsby-interface like the inputs.
Instead, the color treatment and style should always be determined by the global theme, which is why this PR removes most custom colors from the codebase (except where they make sense).
As we are still figuring Admin's specific style out, I'm not going to spend any time trying to match the current design with the global theme and instead simply use …
> chore(gatsby-admin): remove all custom color treatment

- www/gatsby-node.js
Make sure to *return* the promise that is mapped to `Promise.all`. This was causing an issue in #25588 where the the console would [spam createPages](https://github.com/gatsbyjs/gatsby/pull/25588#issuecomment-655913280).
> fix(www) Promise.all for api sections

- packages/gatsby/src/query/query-runner.ts
- packages/gatsby/src/utils/page-data.ts
Currently we skip writing queries if the result hash matches the hash of an existing query with that ID (i.e. the data is unchanged). However, both inc builds and conditional page builds delete `page-data.json` when pages are deleted. In the scenario where a page is unpublished and then republished with identical content, the query runner thinks that the query is already in the cache, so skips writing it out. However it no longer exists on disk, so the page build will fail.
This PR adds a check to see if the page data actually exists before skipping the write.
> fix(gatsby): Check if page data exists when hash matches

- packages/gatsby-plugin-mdx/utils/__tests__/__snapshots__/import-parser.js.snap
- packages/gatsby-plugin-mdx/utils/__tests__/import-parser.js
- packages/gatsby-plugin-mdx/utils/import-parser.js
The regex was expecting only whitespace after the path string of an import, not a semi-colon (or comments). See new test cases.
> fix(gatsby-plugin-mdx): ignore anything after an import in mdx

- docs/tutorial/using-a-theme.md
changes:
- fix 404 link
- #25076 `Documentation: Tutorial changes for blog theme 2.0`
> fix(docs): tutorial theme - fix url 404

- www/src/utils/is-official-package.js
Scope isOfficialPackage() helper to monorepo to prevent broken links for /gatsbyjs packages outside the monorepo.
For example the "View on GitHub" link for `gatsby-source-wordpress-experimental` is broken here https://www.gatsbyjs.org/packages/gatsby-source-wordpress-experimental/?=gatsby-source-wordpress-experimental
> Fix(www): scope isOfficialPackage() helper to monorepo to prevent broken links

- dictionary.txt
- docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
- docs/blog/2017-12-07-taking-gatsby-for-a-spin/index.md
- docs/docs/running-queries-with-graphiql.md
Make sure it's GraphiQL, not Graphiql or GraphiQl (it's mostly alt text that does this)
> fix(docs): Proper spelling of GraphiQL

- dictionary.txt
- docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
- docs/blog/2018-2-7-jam-out-your-blog/index.md
- docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
- docs/docs/creating-a-source-plugin.md
- docs/docs/mdx/getting-started.md
- docs/docs/mdx/programmatically-creating-pages.md
- docs/docs/recipes/styling-css.md
- docs/docs/typescript.md
Add backticks around names of file extensions such as `.html` or `.js` in docs.
> fix(docs) Add backticks on file extensions in docs

- docs/blog/2020-07-07-wordpress-source-beta/index.mdx
changes:
- add "Gatsby Cloud" to the Excerpt
- remove loftover `]` from commit 2a00a474d15b320f24802210e8abde52bc44f50c 
- #25558 `(blog) New WordPress source plugin`
> fix(blog): WordPress V4 -> typos

- www/gatsby-node.js
- www/src/utils/node/api-calls.js
- www/src/utils/node/docs.js
Move the related code for `api-call` out to its own section so that it doesn't clutter up `docs.js`. It's essentially its own plugin — we just can't make it a local plugin because themes/plugins can't have local plugins.
> refactor(www) Move API call out to its own file

- www/src/components/docs-markdown-page.js
- www/src/templates/template-docs-markdown.js
Move the "See the issue relating to this stub" link to `doc-markdown-page` so that API pages can have stubs as well.
> refactor(www): Enable API pages to be stubs as well

- www/src/components/__tests__/docs-markdown-page.js
- www/src/components/docs-markdown-page.js
- www/src/templates/template-api-markdown.js
Override page object passed in to `<DocMarkdownPage>` instead of having a totally separate prop for calculating table of contents.
> refactor(www) Override page object instead of passing in more props to docs-template

- www/src/components/features/evaluation-cell.js
- www/src/components/features/evaluation-table-section-header-bottom.js
- www/src/components/features/evaluation-table-section-header-top.js
- www/src/components/features/evaluation-table-section-title.js
- www/src/components/features/evaluation-table.js
- www/src/components/features/features-footer.js
- www/src/components/features/legend-table.js
- www/src/components/features/simple-evaluation-table.js
Refactors the following components
1. legend-table
2. evaluation-table-section-title
3. evaluation-table-section-header-top
4. evaluation-table-section-header-bottom
5. simple-evaluation-table
6. features-footer
Go to the following link mentioned below, the component should work same in both the local and production link, just the implementation of component is now different.
**Local URL:** http://localhost:8000/features/
**Production URL:** https://www.gatsbyjs.org/features/
> chore(www): refactor evaluation table components

- packages/gatsby/src/utils/__tests__/api-runner-node.js
- packages/gatsby/src/utils/api-runner-node.js
https://github.com/gatsbyjs/gatsby/pull/25470 introduced regression where setting `total` on progress activities in plugins just doesn't do anything
This is because of creating new activity with spreading, and it appears that spreading doesn't preserve setters:
And `total` is using setter: https://github.com/gatsbyjs/gatsby/blob/b7ed68bb3b1ac9f23dd0703941c1f51ff3579d14/packages/gatsby-cli/src/reporter/reporter-progress.ts#L126-L129
Instead of creating copy of activity, this mutates `start`/`end`/`done` to achieve same tracking mechanism
> fix(gatsby): fix setting total in progress activities created by plugins

- packages/gatsby/src/utils/__tests__/webpack.config.js
- packages/gatsby/src/utils/webpack.config.js
Some packages make assignments to `process.env` in certain codepaths. While not a great practice, Gatsby currently generates code with syntax errors when that happens:
```
{}.FOO = 42;
```
This diff changes the replacement string from `{}` to `({})`, which makes it safe to use in most contexts. The only one that could be a problem is `process.env = foo` but I can't see a way to support it (I mean, there's `({a:{}}).a` but ... is it worth it?).
n/a 
Found while investigating a problem in the TS playground.
> fix(gatsby): Fixes process.env replacement for some packages

- .eslintignore
eslint is complaining about gatsby-admin build artifacts as they are not ignored.
> fix(gatsby-admin): ignore build artifacts with eslint

- CODEOWNERS
Now that themes are no longer a part of the monorepo we can remove this line from the CODEOWNERS file.
> Remove themes directory from CODEOWNERS

- docs/sites.yml
We just launched the beta of our new Paths application and would love to have our landing page featured in the Gatsby showcase. If I missed anything or is have any questions, please let me know. Thanks in advance for your time and support.
> add Paths.io to showcase

- docs/tutorial/wordpress-image-tutorial.md
- docs/tutorial/wordpress-source-plugin-tutorial.md
- packages/gatsby-source-wordpress/README.md
- packages/gatsby-source-wordpress/src/gatsby-node.js
This PR adds a deprecation notice to the cli output, the top of the README, and to the 2 tutorials. We're currently publishing the beta of `gatsby-source-wordpress@v4` on a separate package name to allow for an easy upgrade path. Users can install the beta alongside `gatsby-source-wordpress@v3` and have them both active at once during migration.
> chore(gatsby-source-wordpress): add deprecation notice and link to beta WP source plugin

- packages/gatsby-source-shopify/src/queries.js
Add missing resource handle to GraphQL queries
* Article: https://shopify.dev/docs/storefront-api/reference/object/article?api[version]=2019-07#fields-2019-07
* Blog: https://shopify.dev/docs/storefront-api/reference/object/blog?api[version]=2019-07#fields-2019-07
* ShopPolicy: https://shopify.dev/docs/storefront-api/reference/object/shoppolicy?api[version]=2019-07#fields-2019-07
https://shopify.dev/graphiql/storefront-graphiql
```graphql
{
articles(first: 12) {
edges {
node {
handle
}
}
}
blogs(first: 12) {
edges {
node {
handle
}
}
}
shop {
privacyPolicy {
handle
}
refundPolicy {
handle
}
termsOfService {
handle
}
}
}
```
```json
{
"data": {
"articles": {
"edges": [
{
"node": {
"handle": "127283971-first-post"
}
}
]
},
"blogs": {
"edges": [
{
"node": {
"handle": "news"
}
}
]
},
"shop": …
```
> fix(gatsby-source-shopify): resource handle

- packages/gatsby-react-router-scroll/package.json
- packages/gatsby-react-router-scroll/src/__tests__/session-storage.ts
- packages/gatsby-react-router-scroll/src/session-storage.ts
- yarn.lock
This fixes #25745 and #25522.
The problem is that on page load, the location key is a constant of `initial`. So when you navigate between two pages that uses full page reloads - the key is going to be `initial` between each page which then matches in the state and reuses the value.
The solution is to add the `pathname` to the key. So the key that we store in localStorage for a scroll position for a page should always include pathname and key if it's provided. 
Fixes #25745
Fixes #25522
> fix(gatsby-react-router-scroll): Properly scroll to 0 for new pages

- packages/gatsby/src/schema/extensions/index.js
- packages/gatsby/src/schema/infer/add-inferred-fields.js
- packages/gatsby/src/schema/infer/inference-metadata.ts
- packages/gatsby/src/schema/schema-composer.js
- packages/gatsby/src/schema/types/__tests__/date.js
- packages/gatsby/src/schema/types/__tests__/sort-and-filter.js
- packages/gatsby/src/schema/types/date.ts
- packages/gatsby/src/schema/types/filter.js
Part of #21995 
I migrated `types/date.js` to typescript.
#21995
> chore(gatsby): migrate date to TypeScript

- packages/gatsby/src/schema/infer/add-inferred-fields.js
- packages/gatsby/src/schema/schema.js
- packages/gatsby/src/schema/types/derived-types.ts
- packages/gatsby/src/schema/types/filter.js
- packages/gatsby/src/schema/types/sort.js
Part of #21995 
I migrated `derived-types.js` to TS.
#21995
> chore(gatsby): migrate derived-types to TypeScript

- docs/docs/conditional-page-builds.md
- packages/gatsby/src/commands/build.ts
Context: When using the experimental page build on data changes, the output files `newPages.txt` and `deletedPages.txt` are generated when new pages were added, pages were updated or pages were deleted during the build process.
Problem: The output files `newPages.txt` and `deletedPages.txt` are not up to date on subsequent builds, if there are no changes to them. Using these files for anything post-build (e.g. generating a report) might result in wrong feedback. 
Resolution: The files get written with empty contents if they do not change during the new build.
Removed documentation saying the files are not being generated in `docs/docs/conditional-page-builds.md`.
> fix(gatsby) write empty files when no pages created or no pages removed

- packages/gatsby/src/utils/feedback.ts
changes:
- fix feedback test
problems:
- it was not calculating a day within a quarter (between startday/lastday of quarter)
- it becomes less chances to match on each new quarter (Q2:½ Q3:⅓ Q4:¼)
- it should be more within the 90days of a quarter roughly
- https://github.com/gatsbyjs/gatsby/pull/21841#discussion_r389864028
> tests(gatsby): fix feedback tests: random selection - randomNumberWithinQuarter

- packages/gatsby/src/bootstrap/requires-writer.ts
- packages/gatsby/src/services/start-webpack-server.ts
The async `writeAll()` function can cause webpack invalidation. Right now we mark webpack run as pending after we finish writing every file to disk. But depending on timing, webpack can start running in the middle of `writeAll` execution which means that we mark webpack as pending too late. With virtual modules webpack receives `invalid` event immediately so moving activity pending call to `invalid` hook is much more reliable.
It also feels much better approach that webpack service mark itself as pending, as opposed to different service marking it as pending
> fix(gatsby): fix timing issue around marking webpack as pending due to requires-writer run

- packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js
I encountered a subtile bug in the logic for handling `createFileNodeFromBuffer`. My intention is to create file nodes nested inside folders. When I try this currently (without this PR), the containing folder hierarchy is not created, since the call to `fs.ensureDir` is passed a different directory than `writeBuffer`. This PR fixes that.
The docs for `createFileNodeFromBuffer` are [here](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createfilenodefrombuffer).
There are no related issues that I could find.
> fix(gatsby-source-filesystem): Support creating file nodes for paths containing folders

- CODEOWNERS
New words that we want the linter to recognize need to be added to `dictionary.txt`. This file is in the root `gatsby` directory and therefore the Core team is automatically tagged when it gets updated. This change assigns ownership to the `@gatsbyjs/learning` (Documentation) team.
More info on [updating the dictionary](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#updating-the-dictionary) may be found in the Style Guide.
> Add dictionary to CODEOWNERS

- packages/gatsby-source-filesystem/src/create-remote-file-node.js
Specifies remote timeout to start after the connection has been made
gatsby-source-filesystem's remote file node will occasionally throw a [got.TimeoutError](https://github.com/sindresorhus/got#gottimeouterror) if the TCP socket was queued. The solution was to target the specific `send` timeout which starts when the socket is connected and ends with the request has been written to the socket. This keeps with what I assume is the intended purpose of the timeout while hopefully throwing the error simply because the TCP connection was queued.
This also removes the retries option from the got request since the [docs](https://github.com/sindresorhus/got#retry) note streams ignore this option due to the errors that would cause a retry would need to be handled correctly to avoid duplicates …
> fix(gatsby-source-filesystem): Removes erroneously added retries option

- docs/blog/2020-04-15-announcing-gatsby-recipes/index.md
I added a link from the Recipes launch blog post to the infrastructure as code glossary definition.
> (blog) Recipes link to infra-as-code 

- www/gatsby-config.js
changes:
- fix regex `.*.svg` -> `.*\.svg`
- `.*.svg` -> `.*svg`, but i think the previous is more precise for fileextension
- #25282 `maintenance(www): use gatsby-plugin-react-svg for icons`
> chore(www): fix regex in gatsby-config

- packages/gatsby-plugin-mdx/package.json
We recently began using a new API in MDX with #25437 which
doesn't exist for all versions below 1.5.9. This updates the
peer dep for MDX to ensure that the new minimum version is
specified.
Fixes #25691
> fix(gatsby-plugin-mdx): Specify new minimum peerDep version for MDX

- packages/gatsby-plugin-mdx/package.json
> Revert "fix(gatsby-plugin-mdx): Specify new minimum peerDep version for MDX"

- dictionary.txt
- docs/tutorial/part-three/index.md
- yarn.lock
This removes "with-layout2" from the dictionary and replace "with-layout2" in alt texts with a more descriptive phrase.
No documentation is required for this.
Addresses #25290.
> enhancement(docs): dictionary.txt -> with-layout2 -> Remove file name from image alt text and dictionary

- packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
- packages/gatsby-source-contentful/src/normalize.js
Howdy all!
In my Gatsby project, I have a need to create a reproducible ETag & Last Modified of a tree of Contentful entries.  To generate my last-modified date, I take the max of all the `updatedAt` timestamps of all the entries in my tree.  Unfortunately I can't yet include Assets in my tree, so when asset descriptions change I'm forced to republish the root element that links to the asset in order to update the last-modified.
I propose to add the same fields that exist on the "Entry" node to "Asset" as well.  I am including only the fields that the linked documentation says are available to both Entries and Assets.
Appreciate your hard work and the product!
https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes
> feat(gatsby-source-contentful): Give "Asset" the same Sys fields as "Entry"

- packages/gatsby-plugin-mdx/loaders/mdx-loader.js
Fixes #21866.
`gatsby-plugin-mdx` was not picking up (some?) plugins that were given in `gatsbyRemarkPlugins`. This adds the logic to do so in `mdx-loader` used by webpack.
https://github.com/gatsbyjs/gatsby/issues/21866
> Fix issue with gatsby-plugin-mdx not picking up gatsbyRemarkPlugins

- docs/docs/node-interface.md
Switch the language of the node definition in `node-interface.md` to typescript, based on the actual definition in `index.d.ts`. I noticed that this was the only code block that used the `flow` language. Since we don't support flow any more and are switching to TS, I figure it would be good to update the docs to reflect that as well.
> docs(docs) Switch node definition language to TS and update some text

- packages/gatsby-plugin-mdx/gatsby/on-create-node.js
- packages/gatsby-plugin-mdx/loaders/mdx-loader.js
- packages/gatsby-plugin-mdx/loaders/mdx-loader.test.js
- packages/gatsby-plugin-mdx/utils/create-mdx-node.js
- packages/gatsby-plugin-mdx/utils/gen-mdx.js
This Babel step was used to get exports and remark header but we can use the mdast for this purpose, just like for imports.
> This cuts off **20 to 30%** of the total runtime of a baseline mdx benchmark!
---
The following numbers are comparing this branch vs its base branch (~gatsby@2.24.2) on a dedicated nuc. The benchmark site will randomly generate the requested number of page files, will all look something like this:
```mdx
---
articleNumber: 119
title: "Accusamus non dignissimos sed maxime autem."
path: 'accusamus-non-dignissimos-sed-maxime-autem.'
date: 2018-03-05
---
import { Link } from "gatsby"
export const author = "Fred Flintstone"
export default props => <main {...props} />
<Link to="/">Go Home</Link>
Officia modi et qui ... <truncated paragraph of text>
Et eos eum sint …
```
> perf(gatsby-plugin-mdx): drop another babel step during sourcing

- CODEOWNERS
The themes docs should be owned and triaged by @AishaBlake and team. They can tag in themes as necessary, but they shouldn't be separate from a domain perspective.
By removing this line the toplevel docs -> learning codeowner tag will be respected.
> Remove themes as docs codeowners

- docs/docs/gatsby-core-philosophy.md
The original list in the corrected sentence shows 3 items. Here they are, listed:
"They can..."
1. "...be easy to build and iterate on"
2. "...have great SEO"
3. "...fun to work on"
The last one does not make sense, and should have "be" at the beginning. This PR adds that "be".
> grammar fix: make all list items start with a verb

- packages/gatsby-cli/src/structured-errors/error-map.ts
- packages/gatsby/src/redux/actions/public.js
Several files that we write as part of the build process use the page path as a base for their names. Paths longer than filename limits hence cause a `ENAMETOOLONG` that fails the build process. This PR enables autotruncation for such paths. 
We were already panicking on build for these. Now we warn on both develop and build but _always_ autotruncate. 
Fixes https://github.com/gatsbyjs/gatsby/issues/4125
Fixes https://github.com/gatsbyjs/gatsby/issues/25647
> fix(gatsby): Autotruncate long paths

- www/src/data/sidebars/doc-links.yaml
Change the order of the pages in `doc-links.yaml`
- placed "Working with Images in Gatsby" at first, then "Using gatsby-image".
Fixes #25829 
Signed by - @[Neilblaze](https://github.com/Neilblaze)
> Changed the order of the pages in doc-links.yaml

- dictionary.txt
- docs/blog/2020-07-13-i18n-pain-points/index.md
changes:
- fix brand name `transifex` -> `Transifex`
- put plugin-name in code-fences
- #25713  `chore(blog): Add "Research on i18n with Gatsby"`
> fix(blog): i18n - brand names, code in code fences

- packages/gatsby-plugin-less/README.md
changes:
- variable in code fences
- #24893 `chore(gatsby-plugin-less): less-loader version 6.1.0 with tests and doc…`
> fix(readme): gatsby-plugin-less - variable in code fences

- docs/docs/tailwind-css.md
Numbered headers at https://www.gatsbyjs.org/docs/tailwind-css/#4-add-custom-cssscss-files when from 2 to 4.  I had changed headers numbered 4 and 5 to 3 and 4 respectively.
https://www.gatsbyjs.org/docs/tailwind-css/#4-add-custom-cssscss-files
No matching issues found. Decided it is a small enough change that it doesn't warrant opening an issue.
> Fix numbering for headers

- packages/gatsby-plugin-google-analytics/README.md
- packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js
Added storage option as described [in this part of the docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies), from there it links to the full field reference page with an anchor link to #storage but the storage field is missing.
What it does is let you set 'storage' to 'none' which means no _ga cookies are ever set and combined with anonymize causes analytics to work more like a basic pageview tracker but with a lot more GDPR compliance.
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies
> feat(gatsby-plugin-google-analytics): Added cookie storage option

- dictionary.txt
- docs/tutorial/part-six/index.md
The PR fixes the alt texts in `docs/tutorial/part-six/index.md` and removes "markdown-autocomplete" from `dictionary.txt`.
No documentation required for this change.
Addresses #25290.
> enhancement(docs): Fix alt texts in docs/tutorial/part-six/index.md

- packages/gatsby-plugin-manifest/README.md
- packages/gatsby-plugin-offline/README.md
I updated the README.md regarding issue about globPatterns caching everything in public folder
Docs can be found in `packages/gatsby-plugin-manifest` & `packages/gatsby-plugin-offline`
This PR fixes #24480
> Update docs about globPatterns in manifest & offline plugin

- examples/using-MDX/package.json
This PR updates versions of react-charts and MDX that were causing /examples/using-mdx breaking. 
/examples/using-mdx
> Update React-chart and MDX versions

- packages/gatsby-source-shopify/README.md
- packages/gatsby-source-shopify/src/__tests__/__snapshots__/index.js.snap
- packages/gatsby-source-shopify/src/__tests__/fixtures/shop-details.json
- packages/gatsby-source-shopify/src/constants.js
- packages/gatsby-source-shopify/src/gatsby-node.js
- packages/gatsby-source-shopify/src/nodes.js
- packages/gatsby-source-shopify/src/queries.js
Add a new GraphQL query to `gatsby-source-shopify` which returns the shop name, description and money format
The README has been updated to document the new query type
> feat(gatsby-source-shopify): Add shopifyShop query

- packages/gatsby-telemetry/src/__tests__/is-truthy.ts
- packages/gatsby-telemetry/src/event-storage.js
- packages/gatsby-telemetry/src/is-truthy.ts
Simple transition for `isTruthy` and test
#21995
> chore(gatsby-telemetry): Migrate is-truthy to TypeScript

- docs/docs/page-node-dependencies.md
This updates https://www.gatsbyjs.org/docs/page-node-dependencies/ (Gatsby internals section) with 
It drops all code links as those get quickly outdated. The hope here is that references to function name / action type / redux namespace in this document could be used to search code base to find actual locations of related code in codebase (at least as starting point so people could follow code from there). Maybe flow like this could be explicit by adding "grep keywords" appendix?
[CH6148]
> docs(gatsby-internals): update page -> node dependency tracking

- README.md
Location: Repo's main README.md
Removing the word `and` from the second to last item in the performance list.  "and" should only be present after the last comma in the sentence for this use case.
```
Gatsby automates code splitting, image optimization, inlining critical styles, lazy-loading, ~~and~~ prefetching resources, and more to ensure your site is fast — no manual tuning required.
Gatsby automates code splitting, image optimization, inlining critical styles, lazy-loading, prefetching resources, and more to ensure your site is fast — no manual tuning required.
```
> remove surplus `and` from performance comma list

- packages/gatsby/src/utils/get-static-dir.ts
Adds `dereference: true` when copying static directories in order to support symlinks
> fix(gatsby): Support symlinks in static directories

- packages/gatsby-recipes/README.md
> Added the link to 'MDX'

- packages/gatsby-source-shopify/README.md
change (to the same like in line 395):
- case `Description` -> `description`
- name `Currency` -> `money formats` 
- #25763 `feat(gatsby-source-shopify): Add shopifyShop query`
> fix(readme): gatsby-source-shopify: unify variable names

- packages/gatsby-admin/src/pages/index.tsx
This renders the list of pages of a Gatsby site on the homepage of Gatsby Admin. Replacement for the (currently technically infeasible) #25637. Here is what Gatsby Admin shows for the https://feedback.fish Gatsby site:
> feat(gatsby-admin): list all pages of site

- packages/gatsby/src/commands/develop.ts
- packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts
Seems like it got accidentally removed during a big PR? DX with the `gatsby develop` command regressed as a result, if you had an existing process using port 8000, you would get the following:
```
/.asdf/installs/nodejs/14.4.0/.npm/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
throw ex;
^
Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
at Server.setupListenHandle [as _listen2] (net.js:1313:16)
at listenInCluster (net.js:1361:12)
at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
Emitted 'error' event on Server instance at:
at emitErrorNT (net.js:1340:8)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
code: …
```
> fix: Restore CLI port in use prompt feature

- packages/gatsby-telemetry/src/repository-id.ts
- packages/gatsby-telemetry/src/telemetry.ts
Dig up repository info from heroku for gatsby-telemetry. this works at least with the github integration
> Capture repositoryId from heroku

- docs/docs/visual-testing-with-storybook.md
Addition of the `__BASE_PATH__` definition to the storybook configuration in order to prevent some other storybook errors as mentioned on [this comment](https://github.com/gatsbyjs/gatsby/issues/10668#issuecomment-639014099) in issue #10668
This is only an update to the documentation page for Visual testing with Storybook
- [This comment](https://github.com/gatsbyjs/gatsby/issues/10668#issuecomment-639014099) in issue #10668
> Add __BASE_PATH__ definition to storybook config

- packages/gatsby/src/bootstrap/requires-writer.ts
- packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts
- packages/gatsby/src/utils/webpack-utils.ts
- packages/gatsby/src/utils/webpack.config.js
Virtual modules are now being placed in `node_modules` (rationale was that it makes it easy to import them), but it cause some issues as files that previously were under `.cache` cause weird interactions with chunk splitting (see https://github.com/gatsbyjs/gatsby/issues/21701#issuecomment-656718518 ) and custom webpack rules (see https://github.com/gatsbyjs/gatsby/pull/25642 ).
This PR moves virtual modules outside of `node_modules` restoring previous behaviours.
> fix(gatsby): don't place virtual modules in node_modules directory

- docs/docs/deploying-to-digitalocean-droplet.md
- www/src/data/sidebars/doc-links.yaml
Hi,
This PR will **close #24549**.
I've added the **doc to deploy to digitalocean droplet**. The method demonstrated is tested and works perfect.
Points covered are:
1. How to take gatsby site files to digitalocean droplet
2. Installing nodejs and npm and building gatsby site
3. Installing nginx server and configuring it to serve /public directory from gatsby build
4. Ngnix configuration to add domain and a free Lets Encrypt SSL
Let's discuss in case of any doubts or further enhancements.
> chore(doc):Add guide to Deploy Gatsby to DigitalOcean droplet. 

- docs/docs/migrating-from-v1-to-v2.md
Was reading through and saw a missing comma.
> fix(docs): missing comma in migrating-from-v1-to-v2.md

- dictionary.txt
- docs/docs/deploying-to-digitalocean-droplet.md
The retext-spell bot isn't running on PRs unfortunately, so we often miss issues with the dictionary. I merged the DigitalOcean PR just now and it had some issues, so this PR fixes those.
N/A
N/A
> fix dictionary for digitalocean guide

- docs/docs/creating-a-source-plugin.md
The example code showing how to proactively update nodes used `getNodesByType` but didn't destructure it from the function parameters. This PR fixes that omission.
> fix(docs): show where `getNodesByType` comes from

- docs/contributing/setting-up-your-local-dev-environment.md
- www/src/data/sidebars/contributing-links.yaml
Talked to @polarathene on Discord and was made aware of some missing peaces around syncing/running `yarn run bootstrap` again to solve some issues in tests.
Also the sidebar entry was falsely moved in https://github.com/gatsbyjs/gatsby/pull/21806 - moved it back to "Code contributions" where it belongs.
Also improved the doc a bunch.
> chore(docs): Changes to "Setting Up Your Local Dev Environment" doc

- packages/gatsby/src/utils/print-instructions.ts
When `gatsby develop` is run with Admin enabled, the logs now point to it next to GraphiQL:
> chore(gatsby): add log to gatsby develop if Admin is enabled

- docs/docs/deploying-to-digitalocean-droplet.md
The MDX includes a non-escaped `<my-gatsby-app>` in the markdown, which means builds are failing for .org.
> fix(docs): Fix broken mdx

- jest.config.js
- packages/gatsby-admin/package.json
- packages/gatsby/package.json
Closes #25908
@freiksenet I'm not sure how to verify or enforce that this uses the local version of Gatsby. 🤔  Any ideas?
> Move gatsby-admin to postbuild of gatsby

- docs/docs/quick-start.md
An update to the quick start page to direct users to use the hello world starter to try to ease the onboarding. As of 7.21.20, 62,438 users have failed to ever run `gatsby develop` because they run into the following error:
```
There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.
```
After some analysis with @DSchau, we concluded that this is most likely due to an `npm install` failure resulting in an incomplete install. Most often that failure comes from `image-sharp` failing.
Since the default starter uses `gatsby-image` and requires `image-sharp`, we wanted to run an experiment to see if directing Quick Start users to …
> docs: use hello-world starter in quick start guide instead of default starter

- packages/gatsby-admin/package.json
> @mxstbr You should cleanup the the previous assets as well cause gatsby we'll keep getting bigger and bigger.
>
> – @wardpeet in https://github.com/gatsbyjs/gatsby/pull/25940#discussion_r458902767
> chore(gatsby-admin): cleanup stale artifacts pre build

- packages/gatsby/src/commands/develop-process.ts
- packages/gatsby/src/query/query-watcher.js
- packages/gatsby/src/services/index.ts
- packages/gatsby/src/services/listen-for-mutations.ts
- packages/gatsby/src/services/listen-to-webpack.ts
- packages/gatsby/src/services/recompile.ts
- packages/gatsby/src/services/start-webpack-server.ts
- packages/gatsby/src/services/types.ts
- packages/gatsby/src/state-machines/develop/actions.ts
- packages/gatsby/src/state-machines/develop/index.ts
- packages/gatsby/src/state-machines/develop/services.ts
- packages/gatsby/src/state-machines/query-running/index.ts
- packages/gatsby/src/state-machines/waiting/index.ts
Instead of allowing the webpack dev server to recompile any changed files whenever they change, this PR moves the handling of these into the state machine. We listen to the webpack `invalid` event, which means that a file has been invalidated (i.e. changed). We use this to set a flag in context, which means that we rebuild the JS bundle when we get to that stage in the build process, and if we're currently idle we kick off a build.
> feat(gatsby): Handle webpack in state machine

- packages/gatsby-admin/src/components/providers.tsx
- packages/gatsby-admin/src/pages/index.tsx
@LekoArts hit an issue with Admin but couldn't tell me what it is :blush: This shows the error message(s) in the interface so folks can tell us about them!
While I was at it I also cleaned up the loading and null state for the provider fetching.
> fix(gatsby-admin): show error messages in the interface

- packages/gatsby-admin/README.md
@gatsbyjs/core does this make sense, is there anything else you are unsure about that I should elaborate on? :pray:
> docs(gatsby-admin): more detailed architecture explanation

- packages/gatsby/src/schema/__tests__/node-model.js
- packages/gatsby/src/schema/node-model.js
This PR fixes a bug we've discovered via `gatsby-plugin-mdx` here:
https://github.com/gatsbyjs/gatsby/blob/ce0ec317b09bb6337ca26e0a4746813ffbb8a41b/packages/gatsby-plugin-mdx/gatsby/source-nodes.js#L141-L144
The issue is that the `nodeWithContext` can be of any type here, not just `File` due to how `findRootNodeAncestor` is implemented (it doesn't check against the predicate for the top-most node).
> fix(gatsby): call predicate for the root ancestor in findRootNodeAncestor

- packages/gatsby-admin/src/pages/index.tsx
> The three quick design wins I can see are make the "install plugins" header the same size as the other headers, add just a little more space between the 3 sections of the page, and reduce the amount of space between the plugin name and its description by a bit!
>
> – @shannonbux in https://github.com/gatsbyjs/gatsby/pull/25744#issuecomment-662563128
> fix(gatsby-admin): small design tweaks

- packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
- packages/gatsby-source-filesystem/src/create-remote-file-node.js
The existing message made tracing down a bug from within the new WP source plugin harder than necessary.
Old message: `wrong url: ${url}`
Updated message: `url passed to createRemoteFileNode is either missing or not a proper web uri: ${url}`
> feat(gatsby-source-filesystem): improve wrong url rejection message

- packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.ts.snap
- packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
- packages/babel-preset-gatsby/src/dependencies.ts
- packages/babel-preset-gatsby/src/index.js
Re-enable transform-regenerator to properly transform generators. I made a mistake when adding polyfill chunk to disable transform-regenerator. I was confused with `regenerator` option in `plugin-transform-runtime`.
Fixes https://github.com/gatsbyjs/gatsby/issues/25753
> fix(babel-preset-gatsby): enable transformer-regenerator

- docs/docs/deploying-to-digitalocean-droplet.md
changes:
- `bash` -> `shell` code language 
- #24652 `chore(doc):Add guide to Deploy Gatsby to DigitalOcean droplet.`
> fix(docs): bash to shell

- packages/gatsby/src/utils/__tests__/map-templates-to-static-query-hashes.js
- packages/gatsby/src/utils/map-templates-to-static-query-hashes.ts
Windows static query paths generation is broken. Gatsby uses slash utility to convert component paths to unix based ones. Webpack has windows file paths so they never match.
I added a simple test to it to illustrate the problem and the fix. The feature itself has great e2e coverage so that's why this is just a simple test.
Fixes https://github.com/gatsbyjs/gatsby/issues/25909
Fixes https://github.com/gatsbyjs/gatsby/issues/25920
Fixes https://github.com/gatsbyjs/gatsby/issues/25949
> chore: add tests to static-query filepaths

- packages/gatsby-plugin-mdx/gatsby/on-create-node.js
- packages/gatsby-plugin-mdx/loaders/mdx-loader.js
- packages/gatsby-plugin-mdx/loaders/mdx-loader.test.js
- packages/gatsby-plugin-mdx/utils/create-mdx-node.js
- packages/gatsby-plugin-mdx/utils/gen-mdx.js
Reverts gatsbyjs/gatsby#25757 due to #25975. Will create a backwards compatible option.
> Revert "perf(gatsby-plugin-mdx): drop another babel step during sourcing"

- .circleci/config.yml
- integration-tests/gatsby-cli/__tests__/build.js
- integration-tests/gatsby-cli/__tests__/develop.js
- integration-tests/gatsby-cli/__tests__/recipes.js
- integration-tests/gatsby-cli/__tests__/repl.js
- integration-tests/gatsby-cli/gatsby-sites/gatsby-build-errors/.eslintrc
- integration-tests/gatsby-cli/gatsby-sites/gatsby-build-errors/package.json
- integration-tests/gatsby-cli/gatsby-sites/gatsby-build-ssr-errors/.eslintrc
- integration-tests/gatsby-cli/gatsby-sites/gatsby-build-ssr-errors/package.json
- integration-tests/gatsby-cli/gatsby-sites/gatsby-build/.eslintrc
- integration-tests/gatsby-cli/gatsby-sites/gatsby-build/package.json
- integration-tests/gatsby-cli/gatsby-sites/gatsby-develop/.eslintrc
- integration-tests/gatsby-cli/gatsby-sites/gatsby-develop/package.json
- integration-tests/gatsby-cli/gatsby-sites/gatsby-repl/package.json
- integration-tests/gatsby-cli/test-helpers/invoke-cli.js
- packages/gatsby/src/services/rebuild-schema-with-site-pages.ts
- packages/gatsby/src/state-machines/develop/index.ts
- packages/gatsby/src/state-machines/develop/services.ts
Due to an error in our CircleCI config, CLI integration tests have not been running, but have been reporting as passed anyway. Enabling them uncovered lots of failing tests. This PR re-enables the tests and updates them where needed (mostly because of changes from the state machine). Many of the tests would pass locally but fail in CI. To avoid this, the environment is now normalised, meaning that `NODE_ENV` is set to `development` or `production` rather than `test`. `CI` is true, and `GATSBY_LOGGER` is `ink`. This means that tests that pass or fail locally should pass or fail in the same way on the server.
I have disabled one test for now, which is the recipes test. I'm not currently aware how to get recipes to run successfully in a CI environment.
> fix: Enable CLI integration tests

- docs/docs/glossary.md
In doing some writing about Gatsby, I found myself wanting to link to a glossary definition on client-side rendering (including how client-side routing works into it). There was already an entry on [server-side rendering](https://www.gatsbyjs.org/docs/glossary#server-side-rendering), so this seemed like a gap that should be filled.
N/A
N/A
> [docs][glossary] add new entry for client-side rendering

- packages/gatsby-plugin-sharp/src/trace-svg.js
- packages/gatsby-remark-copy-linked-files/src/index.js
- packages/gatsby-remark-images-contentful/src/index.js
- packages/gatsby-remark-images/src/index.js
- packages/gatsby-remark-responsive-iframe/src/index.js
I was adding [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin) to gatsbyjs.com and I saw that our config changed sometimes out of the blue. There were some timing issues that augment pluginOptions and also the webpackConfig. This meant we we're rebuilding more than we needed.
> fix: do not augment plugin-options

- docs/docs/glossary.md
I found some js code which was not highlighted so I wrapped it in js code block,
secondly, I added the link to reach/router as it was confusing if its react/router or reach/router
> Added extra markup

- packages/gatsby-graphiql-explorer/src/app/app.js
- packages/gatsby/src/utils/start-server.ts
Adds a "Refresh Data" button to GraphiQL. This will only be visible if the `ENABLE_GATSBY_REFRESH_ENDPOINT` is enabled and will take into consideration the `GATSBY_REFRESH_TOKEN`
> Add support for cache refresh via GraphiQL

- www/gatsby-config.js
- www/package.json
The new static query loading is problematic with `gatsby-plugin-offline`
Temporarily removing it till I patch gatsby-plugin-offline
> www: Remove sw

- packages/gatsby/src/state-machines/develop/actions.ts
- packages/gatsby/src/state-machines/develop/index.ts
This adds top-level error handling to the state machine, to catch anything that isn't handled elsewhere and prevent us getting into a stuck state.
> feat(gatsby): Add top-level error handling to state machine

- yarn.lock
The root yarn.lock has been out of date since 8868896edadeabb0a5486fc3369b8eb90c70d1b7
> chore: Update stale yarn.lock

- packages/gatsby/src/services/create-pages.ts
- packages/gatsby/src/services/customize-schema.ts
- packages/gatsby/src/services/post-bootstrap.ts
- packages/gatsby/src/state-machines/develop/index.ts
- packages/gatsby/src/utils/create-schema-customization.ts
- packages/gatsby/src/utils/start-server.ts
Deferred node mutation is currently opt-in, because we don't want to use it during `gatsby build`. This PR enables deferral for more APIs. For example, we had encountered a bug where mutations inside `onCreateDevServer` were not triggering builds. This PR also ensure that `refresh` is passed to `createSchemaCustomization` after first run.
> fix(gatsby): Defer node mutation in more APIs

- packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap
- packages/gatsby-image/src/__tests__/index.js
- packages/gatsby-image/src/index.js
Prevents the rendering from crashing if Gatsby image is called without any parameters. The error message that was printed before this change was not helpful to users.
Fixes #25370
> fix(gatsby-image): add required check for one of fluid or fixed

- packages/gatsby/cache-dir/__tests__/public-page-renderer-dev.tsx
- packages/gatsby/cache-dir/__tests__/public-page-renderer-prod.tsx
- packages/gatsby/cache-dir/public-page-renderer-prod.js
ProdPageRenderer is currently broken. This fixes it.
> fix(gatsby): Load resources in ProdPageRenderer

- packages/gatsby-admin/src/pages/index.tsx
- packages/gatsby-admin/src/pages/pages.tsx
This moves the list of pages to a hidden page at /pages:
> chore(gatsby-admin): move sitemap to /pages

- package.json
- packages/gatsby-image/src/__tests__/index.js
- yarn.lock
Better for maintenance, but also because I need a better API surface of `matchMedia()` for a [`gatsby-image` PR](https://github.com/gatsbyjs/gatsby/pull/26119) that fails tests otherwise. Better than expanding on the current DIY mock I think.
> chore(gatsby-image): Add `jest-matchmedia-mock` to replace DIY mock

- packages/gatsby-plugin-sharp/package.json
- packages/gatsby-remark-images/package.json
- packages/gatsby-transformer-sharp/package.json
- yarn.lock
Upgrade `potrace` in order to upgrade `jimp`, which currently depends on a vulnerable version of `jpeg-js`.
- Vulnerability: https://github.com/advisories/GHSA-w7q9-p3jq-fmhm
- Jimp Pull Request: https://github.com/oliver-moran/jimp/pull/892
- Potrace Pull Request: https://github.com/tooolbox/node-potrace/pull/9
Also to be upgraded in the massive Renovate bot PR https://github.com/gatsbyjs/gatsby/pull/25546
> Address Uncontrolled Resource Consumption in jpeg-js

- packages/gatsby/src/redux/index.ts
- packages/gatsby/src/services/initialize.ts
We want to track cache status of builds with telemetry.
> feat(gatsby-telemetry): Track if cache was purged

- packages/gatsby/src/services/run-mutation-batch.ts
- packages/gatsby/src/state-machines/develop/actions.ts
- packages/gatsby/src/utils/call-deferred-api.ts
There are two places where the node mutation queue is drained. Previously there were two versions of the callRealApi function that performed the actual call, once of which didn't include promise resolution. This was an oversight, and caused a bug where createNode called triggered during waiting never resolved. This PR moves the function to a shared util.
> fix(gatsby): Resolve node mutations in waiting state

- packages/gatsby-plugin-mdx/loaders/__snapshots__/mdx-loader.test.js.snap
- packages/gatsby-plugin-mdx/package.json
- yarn.lock
Starting in MDX version 1.6.16, the makeShortcode function
is only added to compiled MDX when it is needed. This
caused the gatsby-plugin-mdx snapshots to fall out of
date. MDX is now bumped to 1.6.16 with the snapshots
updated.
**Related:**
- https://github.com/gatsbyjs/gatsby/pull/24595#discussion_r462906399
- https://github.com/mdx-js/mdx/pull/1088
- [ch12755]
> chore(gatsby-plugin-mdx): Upgrade MDX and snapshots

- dictionary.txt
- docs/docs/other-css-frameworks.md
- www/src/data/sidebars/doc-links.yaml
Adds a new Reference Guide to the [CSS Libraries and Frameworks](https://www.gatsbyjs.org/docs/css-libraries-and-frameworks/) section for Other CSS Frameworks. 
Closes #21541
> [docs][guides] other css frameworks

- docs/blog/2019-04-25-plugin-authoring-study/index.md
Not sure why this just started to fail, did something change with the linter so the ignore statements weren't being followed anymore? This PR makes unique heading content which the lint rule was trying to warn about, rather than trying to disable it.
N/A
Related to all the failed builds on master.
> fix: headings in plugin authoring study post failing linter

- docs/blog/2020-07-13-i18n-pain-points/index.md
- docs/blog/2020-07-28-introducing-gatsby-i18n-theme/index.md
changes:
- use gatsby.dev/discord for links
- file name in code fences
- fix indention for diff code block
- `localhost` -> `http://localhost`
- #26065 `chore(blog): Add i18n theme blog post`
> fix(blog): i18n themes - link to discord, indentions in diff, filename in code fences

- packages/gatsby-source-wordpress/README.md
changes:
- remove escaping code fences
- #25623 `chore(gatsby-source-wordpress): add deprecation notice and link to beta WP source plugin`
> fix(readme): gatsby-source-wordpress: remove escaping code fences

- docs/docs/basic-hardware-software-requirements.md
changes:
- `Mac OSX` -> `macOS` (renamed since Sierra)
- `Node` -> `Node.js`
- #25583 `[docs] add info on basic hardware/software system requirements`
> fix(docs): hardware requirements -> fix brand names

- docs/docs/seo.md
This PR changes the linked metadata testing tool on the SEO page in the docs. The current tool shows a big banner in the bottom right corner saying "This tool is being shut down. Please use X instead."
This PR is implementing that change.
Docs-only.
None
> docs: Change SEO metadata testing tool as its deprecated

- docs/contributing/contributor-swag.md
There were some questions about what to do if you get the wrong t-shirt size through contributing, and the answer is on the swag store FAQ's. Rather than repeat the information, I added a link to more details. Open to other suggestions, though.
N/A
Maintainer discussion: https://github.com/orgs/gatsbyjs/teams/maintainers/discussions/93
> [contributing] add link to swag FAQ's in contributing section

- www/src/data/sidebars/doc-links.yaml
I noticed when replying to a GitHub issue about hybrid app pages with a link to the docs that the Redux store doc wasn't listed in the sidebar. There's no good reason why it shouldn't be listed, so I added it in this PR.
I also shortened the "Adding App and Website Functionality" breadcrumb title so it wouldn't be so repetitive. The E-commerce pages in particular were quite long, so making it shorter seemed like a fine idea.
N/A
N/A
> [docs] add redux doc to sidebar

- packages/gatsby-plugin-mdx/utils/__tests__/__snapshots__/import-parser.js.snap
- packages/gatsby-plugin-mdx/utils/__tests__/import-parser.js
- packages/gatsby-plugin-mdx/utils/import-parser.js
The "shorthand" syntax is an import that only imports a path, without declaring any symbols:
```js
import "./foo.css"
```
This happened in the real world so we have to support it.
This fixes https://github.com/gatsbyjs/gatsby/issues/25734
> fix(gatsby-plugin-mdx): support import shorthand syntax

- packages/gatsby-plugin-mdx/utils/__tests__/fixtures/test-plugin.js
- packages/gatsby-plugin-mdx/utils/__tests__/gen-mdx.js
- packages/gatsby-plugin-mdx/utils/gen-mdx.js
This makes `findImports(...)` also run the `run(...)` phase from `unified`/`remark`. This is needed to allow plugins to inject ESM imports via AST modifications. I have also added a test to cover this use case.
#25437 broke a use case that I had a custom plugin for. Basically, I need to inject imports via a plugin to enable code demos.
> Fix gatsby-plugin-mdx not running plugins on findImports(...)

- rfcs/text/0013-file-system-routing-expanded.md
- rfcs/text/0013-secret.md
> RFC: File System Routing Improvements

- packages/gatsby-recipes/.babelrc.json
`node: "current"` isn't what we wanted
> fix(gatsby-recipes): Set node version for recipes babelrc to earliest supported version

- docs/docs/deploying-to-iis.md
I've deployed my gatsby site with this web.config with few changes and noticed that `.json` files in other locations are getting cached. Culprit for that was this line,
```xml
<add input="{REQUEST_FILENAME}" pattern="(.*\.js)|(.*\.css)" />
```
Since this regex does not detect end of line, it take `.json` files also as `.js` and add permanent cache header to it. Fix for it is add tracking end of line to `IsCachePermanentlyFile` pre-condition like this,
```
<add input="{REQUEST_FILENAME}" pattern="((.*\.js)|(.*\.css))$" />
```
Suggesting to fix this for future users like me. 😊
This an update to documentation itself which address an issue when tracks file caching using `web.config`.
None
> Fixed precondition where it adds perma cache to .json files

- packages/gatsby-recipes/package.json
The peer dependency got removed in https://github.com/gatsbyjs/gatsby/pull/24595/files, but it's not clear why since it's still a mandatory dependency, so it being missing causes the resolution to fail, or generally be incorrect.
https://github.com/yarnpkg/berry/runs/944500417
> Adds back peer dependency

- docs/blog/gazette-july-2020/index.md
changes:
- fix 404 links
- #26171 `(blog) Gatsby Gazette for July` 
- #19267 `Add link checker for Gatsby Docs
> fix(blog): juli gazette: fix links 404

- README.md
Remove repo README support link to Spectrum (support for it has been discontinued and it is going to be sunsetted) and replace with a link to the AskGatsbyJS Twitter account
> Remove README link to Spectrum

- packages/gatsby-source-contentful/src/gatsby-node.js
and add support for the `useNameForId` option
> fix: use content type id by default to create reference gql types

- www/src/views/starter/details.js
- www/src/views/starter/header.js
- www/src/views/starter/source.js
When selecting a starter from the starter library in dark mode, the page title is now white and links to CodeSandbox, Netlify, and the dependencies are purple to match the rest of the website.
@gatsbyjs/learning
Fixes #26182
> fix(www): Starter library dark mode set text colors

- packages/gatsby-remark-code-repls/package.json
- packages/gatsby-remark-embed-snippet/package.json
- packages/gatsby/package.json
No breaking changes in this release: https://github.com/jonschlinkert/normalize-path#v30
> chore: Update normalize-path dependency

- integration-tests/structured-logging/__tests__/ipc-send.js
- packages/gatsby/src/commands/develop.ts
This opens the door to enable jobs API for develop and not just `gatsby build` this was broken when develop got reworked.
You can test it with installing `yarn add gatsby@ipc-develop` and running it on https://github.com/wardpeet/gatsby-ipc-tester
> fix(gatsby): enable ipc messaging on develop

- packages/gatsby-recipes/README.md
The NPMPackageJson API was not documented in the Recipes README.  Adding here.
> Add NPMPackageJson Docs

- packages/gatsby-source-npm-package-search/src/__tests__/__snapshots__/gatsby-node.js.snap
- packages/gatsby-source-npm-package-search/src/gatsby-node.js
This PR adds to GraphQL Schema Node types NpmPackage and NPMPackageReadme.
**I didn't add types for fields that seemed too random:**
- *tags:* NPMPackageTags
- *dependencies:* NPMPackageDependencies
- *devDependencies:* NPMPackageDevDependencies
- *bin:* NPMPackageBin
I left them to be inferred by Gatsby.
**Before the following fields have different types:**
- *owner:* NPMPackageOwner
- *owners:* [NPMPackageOwners]
- *lastPublisher:* NPMPackageLastPublisher
Now they all use the same type: NPMPackageOwner
Fixes #25011
> feat(gatsby-source-npm-package-search): add Node type NpmPackage

- packages/gatsby-plugin-netlify/README.md
A conversation between @KyleAMathews and @blainekasten resulted in this explanation from Kyle. I had a misunderstanding about what the plugin actually did for client only routes and figured it'd make sense to add a little more clarity.
A slack conversation 😬
> docs(gatsby-plugin-netlify): update README with more detail for client only routes

- docs/docs/other-css-frameworks.md
changes:
- change `Material UI` to `Material-UI`
- #26087 `[docs][guides] other css frameworks`
> fix(docs): css-framworks: fix brand name

- packages/gatsby-recipes/src/parser/index.js
- packages/gatsby-recipes/src/parser/index.test.js
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-recipes/src/recipe-machine/index.test.js
- packages/gatsby-recipes/src/resolve-recipe.js
Before the parser was sort of overloaded because it
was also tasked with figuring out how to resolve the
recipe. This moves it to a separate step in the state
machine which separates concerns and will set us
up nicely for when we allow recipes to import other
recipes.
> chore(gatsby-recipes): Move recipe resolving to its own step in state machine

- packages/gatsby-recipes/src/cli/index.js
- packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
- packages/gatsby-recipes/src/providers/npm/package-json.js
- packages/gatsby-recipes/src/renderer/render.js
Also threw in improvement to install output
> fix(gatsby-recipes): fix for when recipes have multiple NPMPackageJSON resources

- packages/gatsby/src/services/build-schema.ts
This PR adds a flag `GATSBY_EXPERIMENTAL_DISABLE_SCHEMA_REBUILD` that allows disabling schema rebuilding on data refresh.
By default, Gatsby rebuilds the schema in `develop` when data structure changes. It makes sense in `develop` as it allows a developer to modify his code according to the latest schema changes without the node process restart.
But this adds unnecessary overhead in Gatsby Preview. Even if the schema changes, the code remains the same and so it doesn't matter if you rebuild the schema or not.
In some cases, schema rebuilding becomes quite costly, so it makes sense to disable it.
> feat(gatsby): add flag to disable schema rebuilding

- .eslintignore
You'd get errors locally after bootstrapping when running `yarn lint:code` because this folder was not ignored.
> chore(eslint): ignore generated gatsby/gatsby-admin-public folder

- packages/gatsby-recipes/package.json
- yarn.lock
Running `yarn workspace gatsby-admin develop` on a fresh pull and yarn install of master results in this error:
```
~/projects/gatsbyjs/gatsby 
❯ yarn workspace gatsby-admin develop
yarn workspace v1.21.0
yarn run v1.21.0
/Users/mxstbr/projects/gatsbyjs/gatsby/packages/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
throw ex;
^
Error: Cannot find module 'ink-box'
Require stack:
- /Users/mxstbr/projects/gatsbyjs/gatsby/packages/gatsby-recipes/dist/cli.js
- /Users/mxstbr/projects/gatsbyjs/gatsby/packages/gatsby-recipes/dist/index.js
- /Users/mxstbr/projects/gatsbyjs/gatsby/packages/gatsby-cli/lib/recipes.js
- /Users/mxstbr/projects/gatsbyjs/gatsby/packages/gatsby-cli/lib/create-cli.js
- …
```
> chore(gatsby-recipes): add missing ink-box dependency

- packages/gatsby-plugin-offline/src/gatsby-node.js
As a result of https://github.com/gatsbyjs/gatsby/pull/26242, static query results are now stored in `/public/page-data/sq/`
This PR adjusts the glob in `gatsby-plugin-offline` so that caches these files as well.
> fix(gatsby-plugin-offline): Update regex to catch new static query results

- packages/gatsby-plugin-offline/README.md
Updated `README.md` of `gatsby-plugin-offline` with current default workbox config as in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/src/gatsby-node.js#L121
> docs: Updated gatsby-plugin-offline README with correct default workbox config

- packages/gatsby/src/utils/validate-page-component.ts
Page components don't support export { default } syntax #25927
Added condition to evaluate `export {default} from X` as valid
Fixes https://github.com/gatsbyjs/gatsby/issues/12384
> fix(gatsby): Added { default } to default exports

- packages/gatsby-recipes/src/graphql-server/server.js
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-recipes/src/renderer/render.js
- share validation cache
- run reconcilier less often
Before this change, a recipe with 200 resources took ~14 seconds to run, after the same recipe takes ~2.3s to run.
> fix(gatsby-recipes): speedup recipe runs for recipes with large numbers of resources

- docs/starters.yml
Added gatsby-starter-netlify-docs, an MDX-based documentation starter integrated with Netlify CMS
> chore(starters): add gatsby-starter-netlify-docs

- docs/tutorial/gatsby-image-tutorial/index.md
- docs/tutorial/wordpress-image-tutorial.md
- packages/gatsby-image/src/index.js
[Some users are still using these props accidentally](https://github.com/gatsbyjs/gatsby/pull/25371#issuecomment-670830933) due to their visibility in guides.
For context, these two props were [deprecated once v2 arrived](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#rename-responsive-image-queries).
My old PR: https://github.com/gatsbyjs/gatsby/pull/14158/commits/844a496aefec6e46405c109563568c5b402f9004#r285505388
Originally during review this was pointed out if it should also log deprecation notices for these two props, but it was resolved and merged without a response. I've included that in this PR in the event I've missed some other old docs, or users try following dated third-party guides for some reason.
> docs(gatsby-image): Deprecate `sizes` and `resolutions` props

- packages/gatsby-dev-cli/src/local-npm-registry/verdaccio-config.js
We're seeing payload size errors on tests for a few PRs. This should fix that.
> Increase verdaccio max_body_size

- docs/contributing/code-contributions.md
With migration to the new repo the official themes development docs are outdated. This updates them.
> Update themes development instructions

- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/question.md
This PR removes references and links to the Gatsby Spectrum community from github issue templates. Specifically, the link to Spectrum still exists in the `documentation.md` issue template and `question.md` issue template.
No applicable - this is a change to github issue templates; no change to any Gatsby code.
Fixes #26276
> Docs update issue templates

- packages/gatsby-recipes/src/renderer/render.js
Further testing revealed this.
> fix(gatsby-recipes): remove trailing config as we do want it to run again to ensure all resource updates are flushed

- packages/gatsby/src/bootstrap/requires-writer.ts
Code we generate in `(a)sync-requires.js` (virtual) modules currently doesn't pass `no-mixed-operators` eslint rule. This is quick change to make it pass. This is for cases when users might use some custom eslint setups (tho I probably should follow up and see if we have documentation for `eslint-loader` modifications anywhere and possibly adjust `ignore` setting there to ignore modules from `_this_is_virtual_fs_path_/$virtual` (as user might have very speciffic rules that would warn/error on code we autogenerate)
Fixes #26319
> chore(requires-writer): update auto-generated code to not trigger no-mixed-operators eslint warnings/errors

- packages/gatsby/src/utils/develop-proxy.ts
This is necessary in order for sites to run with nosniff, see #24862 for more context. Closes #24862
> fix(gatsby): set correct content-type header for socket.io.js

- packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
- packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
- packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
- packages/gatsby-plugin-page-creator/src/gatsby-node.ts
- packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
Resolves an issue where something was imported from `gatsby-cli` without depending on it.
We'd rather not have a plugin depend on the cli directly and since the `reporter` is already passed on into it we'd rather juggle it forward.
Fixes #26345
> fix(gatsby-plugin-page-creator): juggle reporter dont depend on cli

- packages/gatsby-admin/gatsby-ssr.js
We have a `wrapPageElement` method in gatsby-browser.js that wraps every page in our `<Layout />` component, which adds some global styling and wraps the page in all kinds of context providers—most notably, the theme providers!
So far, that worked fine and looked alright. However, we started using some gatsby-interface components that rely on the theme being in the context during `gatsby build`. That suddenly broke the build process with errors such as [this](https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/47577/workflows/35caf132-f7d5-4f4c-b454-baed3c7b4d82/jobs/485815) and [this](https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/47662/workflows/a268e5b7-4090-431b-b9ad-1884bdac2ca4/jobs/486879), yet the develop process kept working fine.
I realised this morning that the …
> chore(gatsby-admin): fix built html not having layout wrappers

- packages/gatsby/src/commands/develop.ts
See  #26214 for context:
> This appears to be an issue with our service discovery mechanism not correctly releasing locks on CTRL+C. While I don't know how to resolve that, we already use the minimum possible stale duration for the lockfiles of 5s so after five seconds it should work again.
> That means we could quickly patch this annoyance for users by changing the error log to something like "Looks like develop for this site is already running, can you visit http://localhost:8000? If it is not, try again in five seconds!"
Closes #26214
> fix(gatsby): improve the log for service lock issues

- peril.settings.json
Disable automated invitations on closed PR for now—retaining the rule algorithm/process itself. 
[ch11697]
> chore(peril): remove invite-collaborator rule

- packages/gatsby-cli/package.json
- packages/gatsby-plugin-manifest/package.json
- packages/gatsby-plugin-sharp/package.json
- packages/gatsby-remark-images-contentful/package.json
- packages/gatsby-transformer-sharp/package.json
- packages/gatsby/package.json
Upgrades semver across the board. Changelog: https://github.com/npm/node-semver/blob/master/CHANGELOG.md
Relevant breaking changes:
7.0.0 - removes node 6 support (no longer a concern for gatsby)
6.0.0 - changes `intersects` logic (not used by gatsby)
Uses of semver:
`satisfies`, `lt`, `gt`. All of which are still supported and appear unchanged
> chore(gatsby): update semver

- packages/gatsby-telemetry/src/__tests__/telemetry.ts
- packages/gatsby-telemetry/src/declarations.d.ts
- packages/gatsby-telemetry/src/event-storage.ts
- packages/gatsby-telemetry/src/index.ts
- packages/gatsby-telemetry/src/telemetry.ts
- packages/gatsby-telemetry/tsconfig.json
This PR 
* Makes it possible to customize the default metadata telemetry sends (componentId/version)
* Attempts to fix some TS issues with the imports
It seems that for proper TS support, we need to do the `exports function` for all methods exposed in src/index.js
However, apparently we need to also keep the module.exports for this. Please advise if there are nicer ways to do this.
> Parameterise telemetry constructor 

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/site-metadata.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/plugin.js
- packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
- packages/gatsby-recipes/src/providers/gatsby/site-metadata.js
- packages/gatsby-recipes/src/providers/gatsby/site-metadata.test.js
- packages/gatsby-recipes/src/providers/lock.js
- packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
- packages/gatsby-recipes/src/providers/npm/__snapshots__/script.test.js.snap
- packages/gatsby-recipes/src/providers/npm/fixtures/package.json
- packages/gatsby-recipes/src/providers/npm/package-json.js
- packages/gatsby-recipes/src/providers/npm/package-json.test.js
- packages/gatsby-recipes/src/providers/npm/script.js
- packages/gatsby-recipes/src/providers/npm/script.test.js
- yarn.lock
Found this was problem similar to NPMPackageJSON in https://github.com/gatsbyjs/gatsby/pull/26281
Did fancy batching technique there like with NPMPackage but realized that was overkill if writing is cheap.
Install npm package is very expensive so we want to batch those. Writing to package.json is extreamly cheap
so using a simple locking mechanism is a lot easier so added that to NPMScript & replaced the batching
code in NPMPackageJSON to use the same locking (which was necessary anyways to make sure NPMScript & NPMPackageJSON
don't clobber each other).
> fix(gatsby-recipes): fix NPMScript for parallel calls

- dictionary.txt
- docs/docs/query-filters.md
Linter was failing on dictionary words. This fixes a handful of typos and adds the rest to the dictionary.
> Fix typos and linter dictionary errors

- packages/gatsby-cli/src/reporter/redux/__tests__/integration.ts
- packages/gatsby-cli/src/reporter/redux/__tests__/internal-actions.ts
- packages/gatsby-cli/src/reporter/redux/index.ts
- packages/gatsby-cli/src/reporter/redux/internal-actions.ts
The `setStatus` action creator calls are not working correctly right now. This PR aims to add bunch of tests first (some of which will fail), and add code changes showing that hose fixes some problems later.
> fix(structured-logging): fix wrongly reporting status as success when we should still be in pending state

- packages/gatsby-recipes/recipes/storybook-ts.mdx
Dependencies were being added as direct dependencies, against what's suggested in the storybook documentation.
> fix(recipes): Install storybook dependencies with development type on typescript recipe

- packages/gatsby-image/index.d.ts
- packages/gatsby-image/withIEPolyfill/index.d.ts
GatsbyImage should require one of "fluid" or "fixed". Currently they are both optional.
Self documenting types. Not changing file exports.
> fix(gatsby-image): Fix typings for fixed and fluid props

- packages/gatsby-recipes/recipes/storybook-js.mdx
As suggested in the storybook documentation, those dependencies should be added as devDependencies.
> fix(deps): install deps as devDependencies on storybook recipe

- packages/gatsby-source-graphql/package.json
Before this PR we were using specific version of `graphql-tools`. Turns out it may cause issues when there are multiple versions of graphql-tools in the project.
Fixes #26313
> fix(gatsby-source-graphql): use the latest version of graphql-tools
