gatsbyjs/gatsby

- docs/sites.yml
> Add testing.thanawatgulati.com to showcase

- docs/sites.yml
Adds [Spotify.Design](https://spotify.design/) as a featured website.
Closes #24207
> Adds Spotify.Design as a featured website

- docs/starters.yml
A few tags are causing danger bot to go off. This will keep it from complaining.
https://github.com/gatsbyjs/gatsby/pull/24189
> chore(starters): remove broken tags

- examples/simple-auth/README.md
The simple auth example mentioned only two providers. This PR offers a more balanced and impartial short overview of authentication options.
> docs: more impartial auth recommendations

- docs/starters.yml
> chore(starters): add gatsby-starter-blog-material-clarisse

- packages/gatsby-cli/src/__tests__/index.ts
This brings our conversion of gatsby-cli to 100%!!!!
> chore(gatsby-cli): Migrate unit test to typescript

- docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md
- docs/tutorial/source-plugin-tutorial.md
removed double words
- of of
- the the
> fix(docs): remove double words

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/index.js
- yarn.lock
Fixes https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-632713137
> fix(gatsby-recipes): Remove import-jsx, use built cli

- docs/blog/2020-05-22-happy-fifth-bday-gatsby/index.md
> chore: fix lint

- starters/gatsby-starter-theme-workspace/gatsby-theme-minimal/README.md
Updated README for gatsby-starter-theme-workspace
- Typo/grammar fixes
- Replaced anonymous function with named function as per this issue - #23575
> chore(gatsby-starter-theme-workspace): Update README

- docs/docs/tailwind-css.md
Change lowercase css to uppercase CSS in places where it hasn't been
> chore(docs): Fix CSS capitalisation

- www/src/data/sidebars/doc-links.yaml
changes:
- brandname TailwindCSS -> Tailwind CSS
> fix(sidebar): brand name TailwindCSS -> Tailwind CSS

- packages/gatsby-recipes/recipes/tailwindcss.mdx
changes:
- brandname Tailwindcss -> Tailwind CSS
- #23217 `Add tailwindcss recipe`
> fix(recipes): Brand name Tailwindcss -> Tailwind CSS

- docs/tutorial/remark-plugin-tutorial.md
Take the user directly to the result of the search, rather than requiring them to search for it
> chore(docs): Update remark-plugin-tutorial

- docs/docs/using-gatsby-image.md
Increase the description around the links to match the example on this page https://www.gatsbyjs.org/docs/using-cloudinary-image-service/
> chore(docs): Update using-gatsby-image

- docs/blog/2020-04-29-incredimental-builds/index.md
changes:
- Buzzfeed -> BuzzFeed
- Wordpress -> WordPress
- Webpack -> webpack
- #23576 `Add blog post`
> fix(blog): incremental builds - fix brand names

- docs/blog/2020-04-27-building-Serverless-site-faster-with-Gatsby/index.md
changes:
- remove domain on local links
- #23521 `Blog codebrahma serverless`
> fix(blog): Serverless - remove domain on local links

- docs/docs/node-tracking.md
changes:
- update linked line numbers
> fix(docs): node tracking - update linked line number

- docs/blog/2020-04-29-incredimental-builds/index.md
changes:
- remove local links
- apply redirects
- #23576 `Add blog post`
> fix(blog): incremental builds - remove local links

- docs/sites.yml
Update Tools of Golf URL
Remove Futrli: Switched off Gatsby
Remove NEON: Moved to Webflow
> chore(showcase): Showcase updates

- docs/sites.yml
Adding our website Stackrole to Showcase via sites.yml
> chore(showcase): Adding Stackrole

- docs/blog/2020-05-21-gatsby-recipes/index.md
Just some small spelling things and i added a some markdown lists
_Michelle Gienow has pre-approved this post_
> Blog - Gatsby Recipes - amend

- packages/gatsby-recipes/recipes/gatsby-theme-notes.mdx
- packages/gatsby-recipes/src/cli.js
New recipe for adding the notes theme to your site
> Add notes theme recipe

- docs/sites.yml
Adding `https://aparnajoshi.netlify.app/` to showcase
> chore(showcase): Adding aparnajoshi.netlify.app

- docs/docs/theme-api.md
updated link to merge-gatsby-config as it was converted to ts few days ago so, link turned obsolete
> chore(docs): update link to merge-gatsby-config

- docs/docs/theme-api.md
updated link to merge-gatsby-config as it was converted to ts few days ago so, link turned obsolete
n/a
n/a
> chore(docs):  fixed links in merge-gatsby-config

- docs/blog/2020-05-27-announcing-series-b-funding/index.md
> feat(blog): add funding announcement blog post

- docs/docs/gatsby-internals-terminology.md
- docs/docs/query-extraction.md
updated couple of links to query-runner in the docs
n/a
n/a
> chore(docs): updated links in gatsby-internals-terminology

- docs/blog/2020-05-27-announcing-series-b-funding/index.md
> Remove escaped char, add link for Willit.build

- docs/docs/gatsby-internals-terminology.md
updated link to query-watcher
n/a
n/a
> fixed link to query-watcher

- docs/sites.yml
This adds my open sourced site to the showcase. I open source this to simplify development with GatsbyJS and a headless WordPress CMS easier. I plan to also strip this down and convert it into a starter.
It has the main features:
- 🔥 Fast load speeds. Under 1s on mobile and desktop.
- 💯 High Lighthouse scores. Almost 100 on mobile and desktop.
- 📐 Minimal and precise layout for easy customizations
- 🌐 Multilingual support via i18n _(Work in progress)_
- 📝 Editor-friendly setup with accurate previews from WordPress
- 🤖 SEO optimised site
- ✅ Accessibility optimised site _(Work in progress)_
- 🔃 Programmatic page creation
- ⭐️ Gutenberg support _(Work in progress)_
- 👍 WordPress theme optimised for headless
- 💯 High TypeScript coverage and high type safety
Please let me know if you have …
> Add simonhalimonov.com to showcase

- docs/starters.yml
It adds my gatsby starter into the starters.yml file
The gatsby starter repo you can see it [here](https://github.com/GeorgeSteel/gatsby-fire-starter)
> chore(starters): add my-gatsby-fire-starter

- docs/starters.yml
- Adds `gatsby-starter-catalyst-helium`
- Updates `gatsby-starter-catalyst-writer` -> `gatsby-starter-catalyst-hydrogen`
> chore(starters): add gatsby-starter-catalyst-helium

- docs/docs/overview-of-the-gatsby-build-process.md
updated link to build as it was converted to ts 
n/a
n/a
> fixed link in overview-of-the-gatsby-build-process.md

- docs/blog/2020-05-29-gazette/index.md
Fixed link to Strapi tutorial.
> (chore) Fix Strapi link

- www/starter-redirects.json
changes:
- add redirect for the previous starter (see changes in #24193)
- #24193 `New contentful starter`
> fix(starter): add redirect for previous path

- docs/blog/2020-05-19-little-agency-big-impact/index.md
changes:
- remove domain on local links
- #24244 `add Little and Big agency case study` 
> fix(blog): Little & Big - local domain

- packages/gatsby-recipes/recipes/ava.mdx
- packages/gatsby-recipes/src/cli.js
changes:
- fix brand name:
- Ava -> AVA
- #23801 `feat(recipes): add Ava recipe`
> fix(recipe): AVA - fix brand name

- docs/blog/2019-04-18-gatsby-commitment-to-accessibility/index.md
changes:
- use new a11y email
- #23989 `Use new a11y email alias & update WCAG version`
> fix(blog): a11y - use new a11y email

- packages/gatsby-source-filesystem/src/create-remote-file-node.js
We have logic to auto-guess extension if it can't be derived from `url` provide to `createRemoteFileNode`. This currently doesn't work on warm cache, because 304 reponses don't have body, so temp file is 0 bytes and there is nothing to guess extension from. To fix that we cache extension guessed on initial 200 response and use it whenever we get 304 response for same url.
Fixes #24453
> fix(gatsby-source-filesystem): fix extension guessing on warm cache

- docs/starters.yml
The repo and example links changed and wanted to add some more features to the list.
> chore(starters): Relinking repo, adjusting features gatsby-starter-payments, gatsby-starter-donations

- docs/sites.yml
This adds my personal site (nagarjun.co) to the showcase.
N/A
N/A
> chore(showcase): Add nagarjun.co to showcase

- docs/blog/2020-05-05-Butter-CMS-case-study/index.md
changes:
- fix brand names
- `Wordpress` -> `WordPress`
- `Butter` -> `ButterCMS`
- `Canada Car Loans` -> `Car Loans Canada`
- `car loans Canada` -> `Car Loans Canada`
- #23783 `add buttercms blog post`
------
changes:
- add link to PRPL
- i heard this PRPL the first time, so there can be a link helpful
- Change A: 
```diff
- PRPL
+ PRPL (Push, Render, Pre-cache, Lazy-load)
```
- Change B: 
```diff
- PRPL
+ Push, Render, Pre-cache, Lazy-load (PRPL)
```
- #23783 `add buttercms blog post`
> fix(blog): ButterCMS & Car Loans Canada - fix branding

- packages/gatsby-theme-blog/README.md
variable is changed in PR #24056 to siteUrl
changes:
- siteURL -> siteUrl
- #24056 `Use consistent cases for siteUrl in themes`
> change siteURL to siteUrl

- benchmarks/source-sanity/update-post.js
Fix a bug in the Sanity benchmark data update script.
n/a
n/a
> Actually commit the patch

- docs/docs/deploying-to-gitlab-pages.md
changes:
- add point to file name
- add code fences
> fix(docs): deploying to gitlab - missing point in file name

- docs/docs/sourcing-from-buttercms.md
changes:
- branding: `Butter CMS` -> `ButterCMS`
n/a
> fix(docs): fix branding ButterCMS

- docs/docs/node-creation.md
changes:
- fix filetype in link text
> fix(docs): node creation - file type

- .eslintrc.js
> chore(gatsby): Fix spelling in .eslintrc.js

- docs/blog/2017-12-07-taking-gatsby-for-a-spin/index.md
> chore(blog): 🔒 Fix missing HTTPS on Twitter link

- docs/tutorial/part-eight/index.md
> chore(docs): Fix typographical error

- benchmarks/markdown_id/gatsby-config.js
- benchmarks/markdown_slug/gatsby-config.js
- starters/blog/gatsby-config.js
Revert the lint operations done with inconsistent style in https://github.com/gatsbyjs/gatsby/pull/23808.
> style(starter): lint with Prettier

- docs/starters.yml
Adds `gatsby-starter-woo` to `starters.yml`
- [Demo](https://gatsby-starter-woo.surge.sh/)
- [Repo](https://github.com/desmukh/gatsby-starter-woo)
> chore(starters): add gatsby-starter-woo

- packages/gatsby/src/utils/validate-page-component.ts
> Fix #24809

- integration-tests/gatsby-cli/__tests__/recipes.js
> chore(gatsby-recipes): Implement a basic recipes integration test for the cli

- docs/docs/deploying-to-azure.md
changes:
- fix code language to text
- fix code language to shell
- #24230 `chore(docs): Add deploy to Azure guide`
> fix(blog): deploying to azure - code block languages

- docs/blog/2018-07-07-graphic-design-class/index.md
- docs/docs/using-cloudinary-image-service.md
- docs/tutorial/blog-netlify-cms-tutorial/index.md
- examples/using-javascript-transforms/README.md
By default Netlify subdomains use HTTPS.
> chore(docs): Fix Netlify app links change .com to .app.

- docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/index.md
> Adjust frontmatter because errors

- docs/blog/2020-06-11-you-belong-here-commitment/index.md
changes:
- remove domain from local links
- #24934 `Add blog post about commitment to equity and how we are going to do i…` 
> fix(blog): you belong here - remove local domain

- packages/gatsby-admin/package.json
- yarn.lock
> fix(gatsby-admin): add missing `nodemon` dependency

- docs/docs/api-files.md
> docs(gatsby): update api-files.md to clarify plugins can implement the same files

- packages/gatsby/src/db/common/__tests__/query.js
- packages/gatsby/src/db/common/query.ts
- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/run-sift.js
Remove some obvious code left behind by sift from run-sift.js
> chore(gatsby): cleanup sift remnants from run-sift.js

- docs/sites.yml
Add bold.org into showcase sites
not sure if any other category matches.
> chore(showcase): Add bold.org into showcase

- packages/gatsby-plugin-offline/src/gatsby-node.js
- packages/gatsby-plugin-offline/src/sw-append.js
> fix(gatsby-plugin-offline): versioned import of idb-keyval

- starters/gatsby-starter-blog-theme-core/package-lock.json
- starters/gatsby-starter-blog-theme-core/package.json
- starters/gatsby-starter-blog-theme/package-lock.json
- starters/gatsby-starter-blog-theme/package.json
- starters/gatsby-starter-notes-theme/package-lock.json
- starters/gatsby-starter-notes-theme/package.json
> Manually bump starters to solve issue from old Gatsby version

- docs/blog/2020-06-18-Gatsby-cli-survey-2/index.md
> fix(blog) linting in blog cli survey

- benchmarks/source-sanity/package.json
This PR upgrades the dependencies for the Sanity benchmark site, including an update to the sanity source plugin that better supports incremental builds.
> upgrade dependencies

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/components/mdx.js
- packages/gatsby-recipes/src/create-plan.js
- packages/gatsby-recipes/src/graphql-server/server.js
- packages/gatsby-recipes/src/gui.js
- packages/gatsby-recipes/src/parser/index.js
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-recipes/src/renderer/babel-plugin-remove-shortcodes.js
- packages/gatsby-recipes/src/renderer/index.js
- packages/gatsby-recipes/src/renderer/index.test.js
- packages/gatsby-recipes/src/renderer/input.js
- packages/gatsby-recipes/src/renderer/reconciler.js
- packages/gatsby-recipes/src/renderer/render.js
- packages/gatsby-recipes/src/renderer/transform-to-plan-structure.js
- yarn.lock
> feat(gatsby-recipes): fix MDX rendering for exports

- docs/docs/adding-analytics.md
Adding a link to the Plausible Analytics plugin
> Adding Plausible Analytics plugin

- docs/docs/adding-analytics.md
changes:
- fix brand name: Plausible Analytics -> Plausible
- #24777 `Adding Plausible Analytics plugin`
> fix(docs): adding-analytics - fix brand name: Plausible Analytics -> Plausible

- docs/sites.yml
changes:
- brand name: `TailwindCSS` to `Tailwind CSS`
- remove empty line
- #24784 `chore(showcase): Add suganthan.com`
> fix(showcase): fix brand name TailwindCSS to Tailwind CSS

- docs/docs/gatsby-on-linux.md
Fix a small typo in docs/gatsby-on-linux.md
https://www.gatsbyjs.org/docs/gatsby-on-linux/
> chore(docs): Fix a typo in docs/gatsby-on-linux.md

- docs/sites.yml
Updates to reflect domain name change for a site that has been moved.
N/A
Fixes parkersarsfield/blog#11
> chore(showcase): update broken link

- docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
> Blog: Announcing partner program

- docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
CI:lint is failing on https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-auto-link-without-protocol
> fix(blog): Mail link in partner program

- docs/docs/tailwind-css.md
changes:
- add code fences
- #24666 `Update twin.macro installation instructions`
> fix(doc): Tailwind-CSS: add code fences

- docs/docs/troubleshooting-common-errors.md
changes:
- brand name: Webpack -> webpack
- highlight line in code
- #25072 `Documentation: fs solution is found in multiple GitHub issues and should be in the docs`
> fix(docs): troubleshooting-common-errors -> brand name, highlight line

- packages/gatsby/src/commands/develop.ts
> fix(gatsby): Fix SSL for develop

- docs/blog/2020-06-23-Reconfiguring-Gatsby-Days/index.md
Rollup blog with product and program announcements planned for Gatsby Days live event
> Blog gatsby days reconfigured

- docs/sites.yml
> update submissions to site showcase

- docs/sites.yml
Add my Gatsby blog to the showcase.
> chore(showcase): Adding `Hippocampus's Garden` to the showcase

- docs/blog/2020-06-23-Reconfiguring-Gatsby-Days/index.md
> Correct Ward Peeters name misspell 😞

- docs/docs/convincing-others.md
This PR fixes a small typo in docs/convincing-others.md
https://www.gatsbyjs.org/docs/convincing-others/
> chore(docs): fix typo in docs/convincing-others.md

- docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
Reverts gatsbyjs/gatsby#25251 — AFAIU with this change in `master`, all subsequent deploys will fail, which we don't want.
> Revert "chore(blog): Bring back links in `Pullquote citation`"

- docs/docs/static-vs-normal-queries.md
> chore(docs): Typo in static-vs-normal-queries

- packages/gatsby-remark-images/README.md
> Docs: Adjust image usage README Instructions

- www/src/components/ecosystem/ecosystem-section.js
Switch from template literal/string styles to [`sx`](https://theme-ui.com/sx-prop) and object styles.
> chore(www): Refactor `ecosystem-section`

- docs/starters.yml
chore(starters): add 7sferry-contentful-blog-starters
> chore(starters): add 7sferry-gatsbyan-contentful-starter

- docs/starters.yml
add gatsby-mui-layout-starter to starters.yml
None
None
> chore: 🤖 update starters.yml to include mui starter

- www/gatsby-node.js
Create a utility function for logic of running each node API in the different sections of the site (and add some documentation)
> refactor(www): Utility for running node API in each section

- docs/sites.yml
Add my open-sourced personal [Gatsby site](https://gabrielgiordano.com) to the showcase.
[Source code](https://github.com/gabrielgiordan/gabrielgiordano.com)
> chore(showcase): Add `gabrielgiordano.com` to the showcase

- docs/blog/author.yaml
Just updating my Twitter, thanks!
> chore(docs): Updating Thomas Wang in author.yaml

- docs/docs/graphql-concepts.md
Link to the anatomy of a graphql query is broken, so I updated the link.
> chore(docs): anatomy of graphql query link

- .circleci/config.yml
- packages/gatsby/package.json
- packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js
- packages/gatsby/src/bootstrap/resolve-module-exports.ts
- yarn.lock
When I rebased #25233 to master I'm getting type errors. I don't know how this slipped through the nets but at least we should do a full typecheck on master.
I also fixed typing in that file.
> fix(gatsby): fix typings in resolve-module-exports

- packages/gatsby/src/utils/feedback.ts
Seems like dates weren't calculated correctly, new month, new issues XD
> tests(gatsby): fix feedback tests

- dictionary.txt
- docs/blog/gazette-june-2020/index.md
Fixing few linting errors introduced in https://github.com/gatsbyjs/gatsby/pull/25423
> fix(blog): fix linting errors

- www/src/components/plugin-searchbar-body.js
- www/src/components/stub-list.js
- www/src/pages/creators/agencies.js
- www/src/pages/creators/companies.js
- www/src/pages/creators/index.js
- www/src/pages/creators/people.js
- www/src/pages/ecosystem.js
- www/src/pages/features.js
- www/src/pages/plugins.js
- www/src/pages/showcase.js
- www/src/pages/starters.js
- www/src/templates/template-blog-list.js
- www/src/templates/template-blog-post.js
- www/src/templates/template-creator-details.js
- www/src/templates/template-feature-comparison.js
- www/src/views/creators/creators-header.js
Convert everything to function components when there is no `state` involved.
> refactor(www): Make easy-to-convert class components into function components

- www/src/components/pagination/index.js
Turn `pagination` to a function component.
> refactor(www): Turn pagination to function component

- docs/blog/2018-08-01-partner-program/index.md
- www/src/components/hubspot-form.js
Refactor HubspotForm into a function component and simplify its props
> refactor(www): Turn HubspotForm to function component

- docs/sites.yml
My main site is no longer powered by Gatsby so I am removing it from the showcase.
> chore(showcase): Removing my site from the showcase

- docs/starters.yml
There were many typos and grammatical errors in the Starters. There were also many proper nouns that needed to be capitalized.
All of the starters are here: https://www.gatsbyjs.org/starters
Didn't find any related issues for these typos.
> chore(starters): starters.yml -> Fixed many typos, capitalization, and grammatical errors

- docs/sites.yml
Add ivjose.com  to gatsby showcase
> chore(showcase): Add ivjose.com

- www/src/components/homepage/homepage-newsletter.js
Switch from template literal/string styles to [`sx`](https://theme-ui.com/sx-prop) and object styles.
> chore(www): Refactor `homepage-newsletter`

- www/src/components/languages/language-thumb.js
- www/src/pages/languages.js
> fix linting for langauges page

- docs/sites.yml
DeveloperEcosystem.com is proudly powered by Gatsby :)
> chore(showcase): Add DeveloperEcosystem.com

- www/src/components/breakout.js
Cleanup `<Breakout/>` component
> chore(www): tidy breakout component

- docs/blog/2018-07-20-why-we-built-the-site-showcase/index.md
- docs/blog/2018-12-19-gatsby-scales-with-expertise-and-scope/index.md
- docs/blog/2019-07-30-how-i-used-theme-ui-to-build-my-gatsby-themes-library/index.md
- docs/blog/author.yaml
- docs/creators/creators.yml
Before the blog migration, change my name and description in the author.yaml
> chore(blog): Uupdate some of my mentions

- packages/gatsby-source-contentful/src/fetch.js
> chore(gatsby-source-contentful): fix typo

- docs/docs/api-specification.md
This reverts commit f2aac07d4e206c07f2179d18fb5723897c7060b0.
The change was blocking master due to linting errors
cc @Ekwuno
> Revert "Update API Specification doc"

- docs/docs/sourcing-from-wordpress.md
> fix: correct wp blog link

- yarn.lock
> chore(gatsby): update yarn lock file

- yarn.lock
Just ran `yarn` in a clean master
> chore(gatsby): fix dirty yarn lock

- packages/gatsby-source-wordpress/README.md
> add reference to WP plugin

- docs/docs/awesome-gatsby-resources.md
Add Sam Julien's episode on Real Talk JavaScript that was focused on Gatsby.
https://realtalkjavascript.simplecast.com/episodes/episode-67-jamstacking-with-the-great-gatsby-sam-julien
> chore(docs): Add Podcast to Resources

- www/src/utils/get-prev-and-next.js
More refactors for get-prev-and-next in preparation for #25588
> refactor(www): more refactors for get-prev-and-next

- www/src/components/homepage/homepage-ecosystem.js
> fix(www): Fix homepage ecosystem icons

- www/src/components/tech-with-icon.js
Refactor, cleanup and simplify TechWithIcon component
> chore(www): cleanup TechWithIcon component

- docs/docs/internal-data-bridge.md
changes:
- add file name to code block
- #25208 `feat(docs): Add explanation of Site.siteMetadata field`
> fix(docs): internal data bridge - add title to code block

- dictionary.txt
- docs/docs/bulma.md
- docs/docs/recipes/styling-css.md
- docs/docs/troubleshooting-common-errors.md
changes:
- add Sass to dictinary
-  #25290 `enhancement (docs): Improvements to retext-spell`
> enhancement(docs): dictionary.txt -> fix brand name -> add Sass

- packages/gatsby-plugin-offline/src/get-resources-from-html.js
Check to make sure the URL exists so gatsby build doesn't crash
Related to https://github.com/gatsbyjs/gatsby/issues/25374
> Fix gatsby build issue

- docs/sites.yml
Adding [Glee](https://glee.traction.one) to showcase.
> Add Glee to showcase

- packages/gatsby-recipes/README.md
> Minor text edits to recipe README

- docs/docs/basic-hardware-software-requirements.md
- www/src/data/sidebars/doc-links.yaml
After discovering there was a neglected stub on Basic Hardware and Software System Requirements in Gatsby, I set out to fill in the content. This PR adds a first attempt on it: feedback welcome!
N/A
https://github.com/gatsbyjs/gatsby/pull/23336
> [docs] add info on basic hardware/software system requirements

- docs/docs/sourcing-from-sanity.md
Fixed a little typo in the "Sourcing from Sanity" doc.
> Fix little typo in sourcing from sanity

- docs/tutorial/part-zero/index.md
Removed word "just" from sentence following issue #18702 to appear more interactive.
Addresses #18702
> fix(docs): remove word "just"

- docs/tutorial/seo-and-social-sharing-cards-tutorial/index.md
Removed word "just" and "simply" from sentence following issue #18702 to appear more interactive.
Addresses to #18702
> fix(docs): Removed word "just" and "simply"

- dictionary.txt
- docs/blog/2020-05-21-gatsby-recipes/index.md
- docs/docs/debugging-html-builds.md
changes: 
- Webpack -> webpack (always lowercase)
-  #25290 `enhancement (docs): Improvements to retext-spell`
> fix(docs): dictionary.txt -> fix brand name -> Webpack - webpack

- packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
This is not an exhaustive change, but after a recent bug fix it was clear that this piece of the themes resolution code was hard to follow. This refactor makes it a bit easier to follow.
> (Chore): Refactor themes resolution code for readability

- dictionary.txt
- docs/blog/2020-07-08-blog-2.0/index.md
changes:
- fix brand name `twitter` -> `Twitter`
- update `dictionary.txt`
-  #25568 `Blog theme blog`
> fix(blog): theme 2.0 - brand name Twitter

- dictionary.txt
changes:
- remove `poject`
- #25782 `fix typo` 
- #25290 `enhancement (docs): Improvements to retext-spell`
> enhancement(docs): dictionary.txt -> poject -> remove

- docs/blog/2019-09-26-announcing-gatsby-15m-series-a-funding-round/index.md
changes;
- remove double link
n/a
> fix double link

- packages/gatsby-source-shopify/src/__tests__/__snapshots__/index.js.snap
- packages/gatsby-source-shopify/src/gatsby-node.js
- packages/gatsby-source-shopify/src/nodes.js
Adds a product field to the type ShopifyProductVariant.
Addresses #21602
> feat(gatsby-source-shopify): set link from product variant to product

- packages/gatsby-plugin-google-analytics/README.md
- packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js
Added the option to set cookieFlags.
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#cookieFlags
Addresses #25904
> added a cookieflags option

- docs/sites.yml
This PR adds a new site to the showcase, the [MongoDB Developer Hub](https://developer.mongodb.com).
None
None
> chore(showcase): Add MongoDB Developer Hub

- docs/blog/2020-07-20-Khaled-Garbaya-Life-After-Recipes/index.md
changes: 
- add file names to code blocks
- #25816 `Blog post by Khaled Garbaya on Gatsby Recipes`
> Add file names to code blocks

- dictionary.txt
- docs/docs/building-a-contact-form.md
changes:
- remove `Codepen` -> `CodePen`
- #25290 `enhancement (docs): Improvements to retext-spell`
> enhancement(docs): dictionary.txt -> CodePen -> fix brand name

- packages/gatsby-source-contentful/package.json
implements https://github.com/contentful/contentful-resolve-response/issues/30 to fix https://github.com/gatsbyjs/gatsby/issues/25464
> perf(gatsby-source-contentful): speed up resolving of huge spaces

- dictionary.txt
- docs/contributing/rfc-process.md
> chore(docs): Fix RFC typo

- package.json
- packages/gatsby-cli/src/create-cli.ts
- packages/gatsby-cli/src/recipes.ts
- packages/gatsby-recipes/README.md
- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/cli.js
- packages/gatsby-recipes/src/components/mdx.js
- packages/gatsby-recipes/src/graphql-server/index.js
- packages/gatsby-recipes/src/graphql-server/server.js
- packages/gatsby-recipes/src/graphql-server/start-dev-cli-server.js
- packages/gatsby-recipes/src/gui.js
- packages/gatsby-recipes/src/providers/contentful/environment.js
- packages/gatsby-recipes/src/providers/contentful/type.js
- packages/gatsby-recipes/src/providers/fs/__snapshots__/file.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/__snapshots__/shadow-file.test.js.snap
- packages/gatsby-recipes/src/providers/gatsby/plugin.js
- packages/gatsby-recipes/src/providers/git/__snapshots__/ignore.test.js.snap
- packages/gatsby-recipes/src/providers/npm/__snapshots__/script.test.js.snap
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-recipes/src/renderer/index.js
- packages/gatsby-recipes/src/renderer/index.test.js
- packages/gatsby-recipes/src/renderer/input-provider.js
- packages/gatsby-recipes/src/renderer/reconciler.js
- packages/gatsby-recipes/src/renderer/render.js
- packages/gatsby-recipes/src/renderer/render.test.js
- packages/gatsby-recipes/src/renderer/resource-provider.js
- packages/gatsby-recipes/src/renderer/transform-to-plan-structure.js
- packages/gatsby-recipes/src/transform-recipe-mdx.js
- yarn.lock
> feat(gatsby-recipes): Refactor CLI UI for new one-shot show plan

- packages/gatsby-plugin-mdx/README.md
> highlighted plugins

- docs/sites.yml
This PR adds a new site to the showcase - leanier.com
None
None
> chore(showcase): Add leanier.com site

- docs/docs/conditional-page-builds.md
> Docs: Add a warning about static queries

- docs/sites.yml
Removed built by from Tatjana Volbeke Portfolio.
> chore(showcase): Minor changes Showcase Tatjana Volbeke Portfolio

- docs/blog/2020-07-28-introducing-gatsby-i18n-theme/index.md
> chore(blog): Add i18n theme blog post

- packages/gatsby-recipes/src/providers/gatsby/page.js
Admin needs this to determine the owner of specific pages
> Add plugincreator to API

- packages/gatsby-admin/src/pages/index.tsx
This is roughly styled but will need more. At the moment this only accounts for a single source.
> Add plugin source for page

- docs/blog/2020-07-21-Gatsby-Days-Reconfigured-Benedicte-Raae/index.md
changes:
- add missing prolog like in all other Gatsby Days Reconfigured
- #25840 `create Gatsby Days video blog Benedicte Raae`
> fix(blog): Gatsby Days with Benedicte Raae - add missing prolog

- docs/docs/scroll-restoration.md
Small documentation fix – added missing brackets in the code examples
> chore(docs): Added closing brackets missing in documentation

- yarn.lock
> chore(gatsby): cleanup yarn lock

- packages/gatsby-recipes/src/cli/index.js
- packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
- packages/gatsby-recipes/src/providers/npm/package-json.js
Fixes for bugs reported by @graysonhicks
> fix(gatsby-recipes): Handle string values in NPMPackageJSON + more robust showing of validation errors on install

- packages/gatsby-recipes/src/cli/index.js
> fix(gatsby-recipes): also show general errors

- benchmarks/source-strapi/gatsby-node.js
Hello!
This is a small follow-up to the #26245 PR from yesterday.
Following @moonmeister 's advice, I moved a require statement out of a loop to improve performance.
> Improve Strapi benchmark performance

- docs/docs/configuring-usage-with-plugin-options.md
> chore(docs): Fix links to gatsby-theme-blog and -core

- docs/docs/naming-a-plugin.md
> chore(docs): Fix broken link to the gatsby-theme-blog

- packages/gatsby-recipes/package.json
- packages/gatsby-recipes/src/apply-plan.js
- packages/gatsby-recipes/src/create-plan.js
- packages/gatsby-recipes/src/graphql-server/server.js
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-recipes/src/recipe-machine/index.test.js
- packages/gatsby-recipes/src/renderer/index.js
- packages/gatsby-recipes/src/renderer/reconciler.js
- packages/gatsby-recipes/src/renderer/render.js
- packages/gatsby-recipes/src/validate-steps.js
> feat(gatsby-recipes): live stream updates from creating resources

- docs/sites.yml
Showcase site: The Mezzofanti Guild
> mezzoguild showcase

- dictionary.txt
- docs/blog/100days/apps/index.md
- docs/blog/100days/cms/index.md
- docs/blog/100days/comments/index.md
- docs/blog/100days/create-themes/index.md
- docs/blog/100days/free-hosting/index.md
- docs/blog/100days/gatsby-image/index.md
- docs/blog/100days/mdx/index.md
- docs/blog/100days/pwa/index.md
- docs/blog/100days/react-component/index.md
- docs/blog/100days/serverless/index.md
- docs/blog/100days/use-themes/index.md
- docs/blog/2020-03-23-introducing-gatsby-web-creators/index.md
changes:
- twitter name to `AskGatsbyJS`
- #25290 `enhancement (docs): Improvements to retext-spell`
> enhancement(docs): dictionary.txt -> fix tiwtter  name -> AskGatsbyJS

- docs/starters.yml
> chore(starters): update gatsby-vapor

- docs/starters.yml
Added a TypeScript variant of awesome-gatsby-starter - https://github.com/South-Paw/awesome-gatsby-starter-ts
Cheers 👍
> chore(starters): add awesome-gatsby-starter-ts

- docs/sites.yml
Introduces redcentral.co.uk to the Showcase.  Also makes some very minor content tweaks to johnkavanagh.co.uk in Showcase (adds an apostrophe).
As with my previous Merge Request, I've deliberately placed the new showcase 'up' from the bottom of `sites.yml` - this (hopefully) avoids merge conflicts arising when other changes to this file are merged in ahead.
> chore(showcase): Add redcentral.co.uk

- docs/sites.yml
**DO NOT FEATURE**
Adding alexperronnet.io to sites.yml.
N/A
N/A
> chore(showcase): add alexperronnet.io

- docs/sites.yml
Update's the entry for "lowmess.com" in sites.yml to reflect the new repo URL.
> update lowmess repo

- docs/sites.yml
Adds Laputan Schools - schools.laputan.com.au to sites.yml
N/A
> chore(showcase): Add Laputan Schools (schools.laputan.com.au)

- docs/starters.yml
This is a request to bring my starter site into gatsby's official starter collection.
Please see the ```README.md``` file for documentation
None
> chore(starters): add gatsby-starter-hoa

- docs/starters.yml
adding my `gatsby-starter-github-repositories`
> chore(starters): adding gatsby-starter-github-repositories

- packages/gatsby-recipes/src/__tests__/__snapshots__/find-dependency-match.js.snap
- packages/gatsby-recipes/src/__tests__/find-dependency-match.js
- packages/gatsby-recipes/src/find-dependency-match.js
- packages/gatsby-recipes/src/providers/gatsby/plugin.js
- packages/gatsby-recipes/src/recipe-machine/index.js
- packages/gatsby-recipes/src/renderer/render.js
Follow-up to https://github.com/gatsbyjs/gatsby/pull/26386 w/ fixes suggested by @pvdz & @laurieontech
> fix(gatsby-recipes): some code cleanups + tests

- docs/tutorial/part-zero/index.md
- starters/gatsby-starter-theme/package.json
Bump gatsby from 2.24.41 to current version of 2.24.42 in package.json. Resolves issue #26412.
Update tutorial documentation for creating a new gatsby site with hello-world starter files.
> Bump gatsby to 2.24.42.

- docs/tutorial/part-three/index.md
> Change mention from gatsbyjs.org to gatsbyjs.com

- packages/gatsby-plugin-sitemap/README.md
Fixed a typo: Alternativly -> Alternatively
> chore(docs): Fixed a typo: Alternativly -> Alternatively

- packages/gatsby/package.json
- yarn.lock
> fix(gatsby): update devcert

- packages/gatsby/src/utils/__tests__/get-value-at.ts
- packages/gatsby/src/utils/get-value-at.ts
Fixes an edge case with file type inference (the bug is actually in a related utility function). 
Fixes #26531
> fix(gatsby): take into account possible invalid values in getValueAt

- starters/README-template.md
- starters/gatsby-starter-notes-theme/README.md
- starters/gatsby-starter-plugin/README.md
- starters/gatsby-starter-theme-workspace/README.md
- starters/gatsby-starter-theme/README.md
- starters/hello-world/README.md
changed all old Links in READMEs , fixed links which were left behind after other PRs
You can find the open PRs which have already done correction on other files in /starters here:
#26587 and #26588
> fix(starters): change .org to .com

- docs/docs/path-prefix.md
Just a simple grammatical fix.. :)
> chore(docs): Fix a typo

- docs/docs/bulma.md
* Changed lets to let's (let us).
* Added a comma in "Then, add the.."
> chore(docs): Fix typos

- packages/gatsby-transformer-remark/README.md
Updates an instance of the word graphql to GraphQL to be consistent with the rest of the documentation.
> chore(docs): Update GraphQL spelling in README.md

- docs/docs/adding-comments.md
> chore(docs): Add Utterances

- docs/tutorial/part-seven/index.md
This is a minor improvement to clarify what specifically is being logged for noobs like me.
Small lift, but also small effort 🤞 
@gatsbyjs/learning for review, pairing, polishing of the documentation
> chore(tutorial): Clarify onCreateNode log in Tutorial

- packages/gatsby-core-utils/README.md
- packages/gatsby-core-utils/src/ci.ts
Last bit of https://github.com/gatsbyjs/gatsby/issues/24019
Fixes https://github.com/gatsbyjs/gatsby/issues/24019
> chore: Rename ZEIT to Vercel

- packages/gatsby/src/commands/build-javascript.ts
While trying to debug some cases of missing static query results I noticed that we call `mapTemplatesToStaticQueryHashes` potentially multiple times for single run. It turns out that `compilation` tap also is triggered for child compilations (i.e. `mini-css-extract-plugin`) which we don't want to handle and want only to handle main compilation.
I doubt this is actually fixing anything (probably due to timing, the main compilation was still the last one that would emit `seal` event), but at least it is more correct
> fix(gatsby): tap just into main compilation in webpack-dep-tree-plugin

- packages/gatsby-transformer-remark/src/extend-node-type.js
Introduced in https://github.com/gatsbyjs/gatsby/pull/12878
> chore(gatsby-transformer-remark): undo const->let change

- yarn.lock
When doing some local work within the monorepo I ran `yarn audit` on master: 
```
[~100K lines of output]
26324 vulnerabilities found - Packages audited: 4397
Severity: 21 Low | 22 Moderate | 26281 High
Done in 21.57s.
```
I then modified `yarn.lock` to remove all the affected packages for which the fixes fit within the appropriate semver ranges. The remaining vulnerabilities are either fixed in semver-incompatible versions (ts-jest dependents, assetgraph -> lodash), or not patched yet (utils-extend).
A few can be fixed by updating dependencies to newer versions, specifically danger (major), documentation (major), subfont (major), verdaccio (minor, fixed by Renovate #25546), and yargs (major). Some are addressed in #26709, but since that is so large and still WIP, I'll separate them out …
> fix(yarn.lock): reduce monorepo vulnerabilities by over 1000x

- starters/blog/src/pages/index.js
- starters/blog/src/templates/blog-post.js
Add schema tags to Post in order to improve SEO
Reference: https://schema.org/Article
> feat(gatsby-starter-blog): Post schema tags

- packages/gatsby-plugin-preact/package.json
- yarn.lock
Upgrades prefresh to latest stable version
> chore(gatsby-plugin-preact): update prefresh

- packages/gatsby-admin/src/components/layout.tsx
- packages/gatsby-admin/src/components/pageview-tracker.tsx
- packages/gatsby-admin/src/utils/use-telemetry.tsx
This tracks Admin pageviews to telemetry.
> feat(gatsby-admin): track pageviews to telemetry

- benchmarks/gabe-csv-text/package.json
Replace the copy-pasted plugin with the cvs plugin
> fix(benchmarks): add missing plugin to package.json

- integration-tests/cache-resilience/__tests__/cache.js
- integration-tests/cache-resilience/package.json
- integration-tests/structured-logging/__tests__/ipc-send.js
- integration-tests/structured-logging/__tests__/logs.js
- integration-tests/structured-logging/__tests__/panic.js
- integration-tests/structured-logging/__tests__/status.js
- integration-tests/structured-logging/__tests__/to-do.js
- integration-tests/structured-logging/package.json
Add a few missing deps and also changed the way we invoke
> tests: fix integration test

- benchmarks/gabe-csv-text/README.md
changes:
- fix name because its renamed in #26948
- #26948
> fix benchmark name

- packages/gatsby-recipes/recipes/gatsby-image.mdx
- packages/gatsby-recipes/src/recipes-list.js
Adds a built in recipe for Gatsby Image
> feat(gatsby-recipes): Add a built in recipe for Gatsby Image

- docs/blog/gatsby-v1.md
> docs: updated https

- docs/blog/2018-07-17-announcing-gatsby-preview/index.md
> chore: Update index.md

- docs/contributing/community.md
> chore(docs): updated https

- docs/contributing/community.md
> updated https

- packages/gatsby-telemetry/src/telemetry.ts
Adds siteName to the telemetry tags schema
> Add new fields to ITelemetryTagsPayload

- packages/gatsby-core-utils/src/ci.ts
Work for improving CI detection
> Try detecting codesandbox and mark it as CI

- yarn.lock
Run a `yarn bootstrap` on the current master.
> chore: Fix dirty lock file

- docs/tutorial/part-zero/index.md
Hello! :wave: 
According to the Arch wiki, the command `sudo pacman -Sy` is explicitly discouraged without the `-u` flag, for upgrading the system:
- "never run `pacman -Sy`; instead, always use `pacman -Syu`" from the Arch wiki, [System maintenance > Upgrading the system > Avoid certain pacman commands](https://wiki.archlinux.org/index.php/System_maintenance#Upgrading_the_system)
Partial upgrades (e.g. `pacman -Sy`) are not supported by Arch and could lead to broken packages (source: https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).
Also in the Arch and Manjaro wikis, the instructions on how to uprade the system include the `-u` flag:
- Arch: [Pacman > Upgrading packages](https://wiki.archlinux.org/index.php/Pacman#Upgrading_packages)
- Manjaro: …
> chore(docs): add -u flag to pacman update cmd

- peril.settings.json
Try pinning joi version
<details>
<summary>heroku log</summary>
```
2020-10-02T09:40:35.574507+00:00 app[web.1]: info: status.failure on unknown skipped
2020-10-02T09:40:36.145531+00:00 app[web.1]: Unable to evaluate the Dangerfile
2020-10-02T09:40:36.145540+00:00 app[web.1]:  { ValidationError: {
2020-10-02T09:40:36.145541+00:00 app[web.1]:   "base": {
2020-10-02T09:40:36.145541+00:00 app[web.1]:     "type": "string",
2020-10-02T09:40:36.145541+00:00 app[web.1]:     "$_root": {
2020-10-02T09:40:36.145541+00:00 app[web.1]:       "_types": [
2020-10-02T09:40:36.145542+00:00 app[web.1]:         "alternatives",
2020-10-02T09:40:36.145542+00:00 app[web.1]:         "any",
2020-10-02T09:40:36.145542+00:00 app[web.1]:         "array",
2020-10-02T09:40:36.145542+00:00 app[web.1]: …
```
> chore: pin joi version in peril

- docs/docs/localization-i18n.md
Easy navigation and easy reading for others.
> chore(docs): typo in i18n doc

- docs/docs/adding-analytics.md
- Adds `gatsby-plugin-gtag` description to `analytics.md`
- Informs user on why `gtag.js` is more preferable than using `analytics.js`
Fixes #27065
> chore(docs): Update analytics with gatsby-plugin-gtag

- packages/gatsby-source-shopify/README.md
It has a much better getting started guide
> chore(gatsby-source-shopify): Link to the Shopify tutorial

- packages/gatsby/src/bootstrap/page-hot-reloader.ts
Convert `page-hot-reloader.js` to typescript.
> chore(gatsby): Migrate page-hot-reloader to typescript

- docs/tutorial/gatsby-image-tutorial/index.md
> chore(docs): Fix typo in image tutorial

- docs/contributing/docs-contributions.md
- docs/docs/api-specification.md
I fix a small typo in docs-contributions.md and update the links.
> chore(docs): Fix typo in docs-contributions and update links

- packages/gatsby-plugin-react-helmet/src/gatsby-node.js
The plugin doesn't take any options, however if we specify that we can validate that and adjust potential future UIs with that information!
> chore(gatsby-plugin-react-helmet): add pluginOptionsSchema

- packages/gatsby-plugin-styled-components/src/gatsby-node.js
> chore(gatsby-plugin-styled-components): add pluginOptionsSchema

- docs/docs/deploying-to-netlify.md
This is just a simple spelling correction.
> chore(docs): Spelling: Continous -> Continuous

- packages/gatsby-admin/README.md
> chore(gatsby-admin): add user information to readme

- packages/gatsby-source-contentful/src/normalize.js
> contentful: improve dropping of fixids

- packages/gatsby-source-filesystem/src/gatsby-node.js
> chore(gatsby-source-filesystem): add pluginOptionsSchema

- docs/docs/gatsby-lifecycle-apis.md
Easy navigation and easy reading for others
> chore(docs): fix a broken url

- .eslintrc.js
> chore: prettier on eslint

- benchmarks/gabe-csv-markdown/gatsby-node.js
- benchmarks/gabe-fs-text/gatsby-node.js
> chore(gabe): add unstable_shouldOnCreateNode handlers to relevant gabe benchmarks

- integration-tests/gatsby-cli/__tests__/feedback.js
- packages/gatsby/src/commands/build.ts
- packages/gatsby/src/commands/clean.ts
- packages/gatsby/src/commands/develop-process.ts
- packages/gatsby/src/utils/__tests__/feedback.ts
- packages/gatsby/src/utils/feedback.ts
We should ask for specific user feedback after their first 7 days.
[ch17397]
> (feat): 7 Day Feedback survey

- packages/gatsby-plugin-utils/src/types.ts
- packages/gatsby-plugin-utils/src/validate.ts
- packages/gatsby/index.d.ts
> fix: duplicate types to solve circular dependency

- dictionary.txt
- docs/contributing/translation/index.md
Changes:
- Whatsapp -> WhatsApp
- #25290 `enhancement (docs): Improvements to retext-spell`
> enhancement(docs): dictionary.txt -> fix brand names

- docs/docs/sourcing-from-etsy.md
These configuration options have changed. See the [readme](https://github.com/dylanon/gatsby-source-etsy#installation)
The configuration options have changed and the ones documented no longer work. 
Where is this feature or API documented?
https://github.com/dylanon/gatsby-source-etsy#installation
> chore(docs): Updating configuration options api_key, shop_id

- docs/docs/building-a-contact-form.md
- docs/docs/themes/building-themes.md
Fixed and updated links for the theme templates
> chore(docs): Fix links to example themes #19011

- packages/gatsby/index.d.ts
> fix(gatsby): add missing printTypeDefinitions

- docs/docs/graphql.md
Improved visual perception of text.
> chore(docs): Update wording on graphql doc

- dictionary.txt
- docs/tutorial/wordpress-image-tutorial.md
This PR:
- adds `SVG` and `SVGs` to `dictionary.txt`
- standardizes all occurrences of the word
- Related to #25290
> fix(docs): add SVG to dictionary.txt and standardize it

- docs/docs/adding-a-shopping-cart-with-snipcart.md
The entry that was linked is no longer existing. I found a newer blog entry about Gatsby and replaced the old one with it.
> chore(docs): Updated Snipcart blog entry

- README.md
changes:
- fix brand name GatsbyJS -> Gatsby
- #27050 `docs: readme`
> fix(docs): Gatsby README - fix brand name GatsbyJS -> Gatsby

- packages/gatsby-plugin-guess-js/README.md
changes:
- add code block around file and directory names
- place commands in shell code block
- adjust names
- #25876 `chore(docs): Update gatsby-plugin-guess-js README`
> fix(docs): Update gatsby-plugin-guess-js README

- packages/gatsby-plugin-cxs/package.json
- packages/gatsby-plugin-cxs/src/__tests__/gatsby-node.js
- packages/gatsby-plugin-cxs/src/gatsby-node.js
Just like @mxstbr did in #27356
> chore(gatsby-plugin-cxs): Add pluginOptionsSchema validation

- packages/gatsby-plugin-cxs/package.json
> chore(gatsby-plugin-cxs): Fix dependency version

- packages/gatsby/src/utils/api-node-docs.ts
Update parameters documentation in createPages
Add API parameter documentation for createPages
Fixes #25805
> fix(docs): Update documentation for createPages

- packages/gatsby/src/query/graphql-runner.ts
If it smells like a promise and it returns a promise then it's probably async.
> chore(gatsby): async refactor in graphql-runner

- packages/gatsby-cli/src/reporter/reporter.ts
- packages/gatsby-telemetry/src/event-storage.ts
> chore(telemery): ensure plugin validation errors are captured

- packages/gatsby-telemetry/src/telemetry.ts
> chore(gatsby-telemetry): add two more value placeholders.

- packages/gatsby-transformer-asciidoc/src/gatsby-node.js
> chore(gatsby-transformer-asciidoc): use optional chaining

- packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Just some cleanup (use ignore whitespace)
> chore(gatsby-plugin-mdx): refactor lodash and debug use out

- docs/reference/release-notes/v2.26/index.md
Fix a broken link in our release notes. A follow up for #27970
> fix(docs): fix broken link

- docs/docs/add-seo-component.md
Typo: location -> pathname
Fixes a small typo in the docs
> chore(docs): Update add-seo-component

- packages/gatsby-telemetry/src/telemetry.ts
Add a new generic string array type for telemetry payload
> chore(telemetry): Add new telemetry field for a generic string array

- docs/docs/deploying-to-firebase.md
There's an extra `cache-control` in the header value
> docs(docs): correct firebase headers example

- packages/gatsby-recipes/src/recipes-list.js
This PR adds chakra-ui #27721 to the recipes-list file
> feat(recipes-list): add chakra-ui

- packages/create-gatsby/src/cmses.json
> Add Netlify CMS to create-gatsby

- docs/reference/release-notes/v2.27/index.md
> Add mention of GATSBY_EXPERIMENTAL_FAST_DEV

- packages/gatsby-source-contentful/src/gatsby-node.js
This flag was broken in the .next push but that was no big deal as it's only for debugging locally.
> fix(gatsby-source-contentful): fix GATSBY_CONTENTFUL_EXPERIMENTAL_FORCE_CACHE

- docs/reference/release-notes/v2.27/index.md
> link to issue fixed inside release notes

- scripts/publish-starters.sh
Currently master is broken due to this test.
> Fix: starters publish script

- scripts/publish-starters.sh
> fix: Update publish-starters.sh

- packages/gatsby/src/services/initialize.ts
Decent number of people have tried it now w/ no reported problems so let's keep rolling it out
> feat(gatsby): bump % that get invited to try dev_ssr to 5% from 1%

- starters/gatsby-starter-minimal/README.md
- starters/gatsby-starter-minimal/src/pages/index.js
This adds utm tags to the starter links, and updates the readme to reflect the fact this is now being used for create-gatsby
> starters(gatsby-minimal-starter): Update links and readme

- packages/gatsby-recipes/recipes/chakra-ui.mdx
The Chakra UI plugin was renamed during its 1.0 release. This PR updates the recipe to account for the new package name, updated dependencies, and links to documentation.
> fix(gatsby-recipes): updated chakra ui recipe after v1 release

- packages/gatsby-link/src/__tests__/__snapshots__/index.js.snap
- packages/gatsby-link/src/__tests__/index.js
- packages/gatsby-link/src/index.js
Backporting #28307 to the release branch
(cherry picked from commit 36661308db47696a3b29d2348c190817d81f1595)
> fix(gatsby-link): don't prefetch same page (#28307)

- packages/gatsby-plugin-react-helmet/README.md
Easy navigation and easy reading for others.
> chore(docs): fix broken url

- integration-tests/ssr/__tests__/ssr.js
- packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
Lets us restore part of the integration-test that was failing
> fix(gatsby): handle in dev-ssr when a page is deleted

- packages/gatsby/src/services/run-page-queries.ts
Let's get more testers so we can get this shipped for everyone!
> chore(gatsby): Invite more people to try QUERY_ON_DEMAND

- packages/gatsby/src/utils/flags.ts
> fix(gatsby): fix telemetryId for LAZY_IMAGES

- docs/reference/release-notes/v2.27/index.md
The `gatsby new` behavior wasn't actually shipped in that release!
> Fix v2.27 release notes

- packages/gatsby/src/services/initialize.ts
Good to know how many people are using flags in general
> feat(gatsby): Track the use of flags in gatsby-config.js

- packages/gatsby-recipes/src/providers/gatsby/plugin.js
fix bug reported https://github.com/gatsbyjs/gatsby/discussions/22991#discussioncomment-136280
> fix(gatsby-recipes): add isLocal to schema for GatsbyPlugin

- integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
- packages/gatsby/src/utils/__tests__/__snapshots__/develop-html-route.ts.snap
- packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
- packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
> feature(gatsby): style the SSR error page

- examples/styleguide/README.md
> Remove Broken Link.

- docs/docs/quick-start.md
Update quickstart to account for new `npm init gatsby` command.
[ch17777]
> Docs: Quickstart update

- packages/gatsby/src/utils/flags.ts
https://github.com/gatsbyjs/gatsby/discussions/28331#discussioncomment-144948
> feature(gatsby): add new cache flags to FAST_DEV

- packages/gatsby/src/utils/flags.ts
See how actively people are clicking on things
> chore(gatsby): use gatsby.dev links in flags.ts

- yarn.lock
> fix: Push dirty yarn.lock

- packages/gatsby-codemods/package.json
- yarn.lock
Was missing the execa dependency.
> fix(gatsby-codemods): Missing dependency

- packages/gatsby-codemods/package.json
- packages/gatsby-codemods/src/transforms/gatsby-plugin-image.js
- yarn.lock
These packages are all used during runtime.
> fix(gatsby-codemods): Need as dependencies and not devDependencies

- packages/create-gatsby/src/__tests__/init-starter.ts
- packages/create-gatsby/src/__tests__/utils.ts
- packages/create-gatsby/src/index.ts
- packages/create-gatsby/src/init-starter.ts
- packages/create-gatsby/src/utils.ts
Fixes some edge cases in the auto-generated package/folder names and add tests
> fix(create-gatsby): Fix kebabcase edge cases and tests

- packages/gatsby-codemods/README.md
- packages/gatsby-plugin-image/README.md
Codemod is finished and working. Wanted to clean up the docs and make sure they're accurate in both READMEs.
> fix: Update docs for codemod

- SECURITY.md
Simple contact change [ch19053]
> chore: Update policy contact

- packages/gatsby-plugin-netlify-cms/README.md
Updates the Slack link to the correct value
Not relevant
Fixes https://github.com/netlify/netlify-cms/issues/4695
> chore(plugin-netlify-cms): update Slack link

- benchmarks/source-wordpress/scripts/updater.js
Fix broken import statement so that the `data-update` script can run for the Willitbuild templates.
> Fix broken import statement

- starters/gatsby-starter-minimal/src/pages/index.js
> (gatsby-minimal-starter): Update docs links and style to match relaunch

- docs/docs/mdx/writing-pages.md
> chore(docs): Fixing broken link

- docs/docs/tutorial/part-eight/index.md
fixed the description of Lighthouse to match what I saw in Chrome
> chore(docs): Update lighthouse instructions in tutorial

- examples/client-only-paths/README.md
> chore(examples): Remove Broken Link

- docs/docs/tutorial/part-eight/index.md
Just ran `yarn format` on master
> fix(lint): ran formatter

- packages/gatsby-plugin-netlify/src/gatsby-node.js
change:
- typo `MATH_ALL_KEYS` to `MATCH_ALL_KEYS`
- #27420 `chore(gatsby-plugin-netlify): add pluginOptionsSchema export`
> fix(gatsby-plugin-netlify): fix typo

- docs/docs/using-typography-js.md
change:
- brand name `Typography.js`
- code fences around file name
> chore(docs): typography - brand name

- docs/docs/how-to/sourcing-data/headless-cms.md
added tina docs and guide in list of headless-cms
Fixes #28932
> chore(docs): Add Tina in list of Headless CMS

- docs/docs/reference/release-notes/v2.31/index.md
Adds release notes for gatsby-plugin-image
> Add image notes

- docs/docs/reference/release-notes/v2.31/index.md
Small copy changes + add more context around performance improvements so it's clearer what types of sites will be impacted.
> Update 2.31 release notes

- docs/docs/how-to/testing/testing-react-components.md
Hey there :wave:
I was just skimming (one of) the pages on testing and this teeny tiny typo jumped out at me, so here's a PR I guess lol.
> docs: fix a small typo

- docs/docs/how-to/sourcing-data/sourcing-from-netlify-cms.md
> chore(docs): Netlify CMS added branch to backend settings

- docs/docs/how-to/sourcing-data/sourcing-from-databases.md
- Add cassandra to list of database sources
Plugin page
- If docs exist:
- Update any references, if relevant. This includes Guides and Gatsby Internals docs.
- If no docs exist:
- Create a stub for documentation including bullet points for how to use the feature, code snippets (including from happy path tests), etc.
- Tag @gatsbyjs/documentation for review, pairing, polishing of the documentation
-->
> chore(docs): Add cassandra to list of database sources

- packages/gatsby-plugin-image/graphql-utils.d.ts
- packages/gatsby-plugin-image/graphql-utils.js
- packages/gatsby-plugin-image/package.json
Some files were missing from the npm package
> fix(gatsby-plugin-image): Add missing files

- packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
- packages/gatsby-plugin-image/src/components/static-image.server.tsx
- packages/gatsby-plugin-image/src/image-utils.ts
> fix(gatsby-plugin-image): Fixes to plugin utils types

- packages/gatsby-telemetry/src/telemetry.ts
- packages/gatsby/src/commands/build-html.ts
- packages/gatsby/src/commands/build.ts
- packages/gatsby/src/commands/develop-process.ts
Make a distinction between total number of pages versus number of html files to write 
[ch23149]
> feat(gatsby): distinguish total number of pages from number of written html files

- docs/contributing/gatsby-style-guide.md
Update relative path example code
> chore(docs): Fix typo in contributing style guide

- docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Updates outdated links to Gatsby Cloud docs.
> Updates links to gatsby cloud docs.

- packages/create-gatsby/src/features.json
In this version we can switch to installing the new image plugin
> chore(create-gatsby): Use new image plugin

- packages/gatsby-source-wordpress/docs/tutorials/using-self-signed-certificates.md
There were a couple small things that needed to be corrected here.
> docs(gatsby-source-wordpress): Update using-self-signed-certificates.md tutorial

- docs/docs/creating-and-modifying-pages.md
One of the code examples has one extra curly brace which is producing error during. So I found it out and fixed it...
> chore(docs): Remove extra curly brace

- packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
- packages/gatsby-source-filesystem/src/__tests__/utils.js
- packages/gatsby-source-filesystem/src/create-remote-file-node.js
- packages/gatsby-source-filesystem/src/utils.js
> chore: remove progressbar

- packages/gatsby/scripts/__tests__/api.js
- packages/gatsby/src/utils/api-node-docs.ts
> remove generateSideEffects API

- packages/gatsby/src/redux/__tests__/index.js
- packages/gatsby/src/redux/persist.ts
> chore: address core package todos

- docs/docs/how-to/routing/adding-markdown-pages.md
More clarity that the user must create the gatsby-node.js file as it's not there by default.
https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/
> chore(docs): Update adding-markdown-pages

- packages/gatsby-plugin-image/src/components/hooks.ts
- packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Revert 3f7f06cb6f0c7be2ddde709283b7d116fa88cd6a
> fix: Revert accidental master push

- packages/gatsby-source-contentful/CHANGELOG.md
This PR fixes a broken example in the Contentful plugin's changelog. Plugin documentation has been updated by someone else but the changelog has not been updated yet.
This PR updates a documentation entry.
There are a few issues that are already closed that referenced this problem. The documentation has been updated but the changelog is still showing a broken example.
> Update the changelog of Contentful plugin to show a working example

- docs/docs/how-to/performance/improving-site-performance.md
Finally adding a fairly-comprehensive guide here!
> Improving site performance doc

- packages/gatsby-plugin-netlify-cms/package.json
- packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
- yarn.lock
Updates webpack dependencies to match compatibility. I haven't tested the widget itself but at least sites are building. That's enough for now.
[ch25449]
> feat(gatsby-plugin-netlify-cms): fix compatibility for webpack5

- docs/docs/tutorial/part-zero/index.md
> chore(docs): Add note on reloading bash configuration.

- starters/blog/gatsby-config.js
- starters/blog/package-lock.json
- starters/blog/package.json
- starters/default/gatsby-config.js
- starters/default/package-lock.json
- starters/default/package.json
Prepping for some exciting changes we'll announce at Gatsby Conf! We want to ensure that any starters that we're using Gatsby Cloud are fully compatible with some of the changes that we'll be introducing.
> chore(starters): Add Gatsby Cloud plugin to default & blog

- packages/gatsby-plugin-image/src/resolver-utils.ts
Improve description of placeholder parameter exposed by `gatsbyImageData`
N/A
N/A
> chore: improve description of placeholder parameter

- integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
- integration-tests/ssr/gatsby-config.js
> fix(gatsby): Fix snapshot for integration-tests/ssr tests

- .circleci/config.yml
Fail test if yarn.lock is dirty after bootstrap
> tests: Check for dirty yarn.lock

- yarn.lock
> chore: Fix dirty lockfile

- .circleci/config.yml
- scripts/check-lockfile.sh
CIrcleCI didn't like the syntax of the other check. Changing to a script.
> tests: Fix lockfile check

- docs/docs/how-to/performance/improving-site-performance.md
Cherrypicking this change over.
> Improving site performance doc (#29373)

- packages/gatsby/src/utils/__tests__/__snapshots__/sample-site-for-experiment.ts.snap
- packages/gatsby/src/utils/__tests__/sample-site-for-experiment.ts
Mock getRepositoryId so that tests don't break with forked repos
> tests(gatsby): Make experiments test deterministic

- docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Updates links to Gatsby Cloud knowledge base.
> chore: update links to cloud docs.

- .circleci/config.yml
- integration-tests/ssr/__tests__/ssr.js
> fix: update tests

- docs/docs/conceptual/choosing-a-cms.md
- docs/docs/conceptual/gatsby-for-ecommerce.md
- docs/docs/glossary/npm.md
- docs/docs/how-to/performance/improving-site-performance.md
- packages/gatsby-plugin-schema-snapshot/README.md
- packages/gatsby-plugin-sharp/src/gatsby-node.js
- packages/gatsby-source-wordpress/docs/getting-started.md
- packages/gatsby-source-wordpress/src/models/image-nodes.js
- packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
- rfcs/README.md
- rfcs/text/0004-native-graphql-source.md
> chore: fix spelling, remove whitespace and fix link

- docs/docs/reference/release-notes/v3.0/index.md
> Update v3 release notes

- starters/gatsby-starter-minimal/package.json
- starters/gatsby-starter-minimal/src/pages/index.js
Upgrades minimal starter to gatsby@^3.0.0 and react 17. Adds a link from the homepage to Cloud.
DO NOT MERGE UNTIL 3 IS RELEASED
[ch25847]
> chore(starters): Upgrade minimal starter and add link to cloud

- docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
> docs(gatsby-plugin-image): remove beta

- docs/docs/reference/release-notes/v3.0/index.md
Clarify a bit and fix broken link to README
> chore(docs): Make note about cloud plugin more precise

- docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Fixes link to "Using Gatsby Image" documentation
> chore(docs): Fix link to /docs/conceptual/using-gatsby-image

- starters/README-template.md
> chore(starters): update template to use hosting

- packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js
Relates to https://github.com/gatsbyjs/gatsby/issues/29704
> feat(gatsby-source-wordpress): Log when nodes are duplicates

- docs/features/gatsby-jamstack-specs.csv
> chore(docs): Update features table

- packages/gatsby-plugin-sass/README.md
Update outdated README
Part of https://github.com/gatsbyjs/gatsby/issues/29955
> chore(gatsby-plugin-sass): Update README

- docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Added information about `process` is not defined.
[ch26415]
> chore: add process information to migration guide

- packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
- packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
- packages/gatsby-plugin-sass/src/gatsby-node.js
Reverts gatsbyjs/gatsby#29986
fixes #30037 30037
> Revert "fix(gatsby-plugin-sass): Change `modules` option around"

- packages/gatsby-source-wordpress/README.md
Updating version in the README file.
> chore(gatsby-source-wordpress): Remove version from README

- docs/docs/upgrading-node-js.md
Saw that a lot of people visit this page and we haven't updated it with v3
> chore(docs): Update "Upgrading NodeJS"

- docs/docs/how-to/styling/using-web-fonts.md
Fixed package name to valid (from deprecated `fontsource-open-sans`)
None
> chore(docs): Update using-web-fonts

- docs/docs/reference/graphql-data-layer/schema-customization.md
Extending link directive docs from convo in https://github.com/gatsbyjs/gatsby/discussions/30157
> chore(docs): Add example to link directive

- docs/docs/deploying-to-digitalocean-droplet.md
Bolded the `Note:` from my previous PR.
`deploying-to-digitalocean-droplet.md`
No related issues.
> chore(docs): Update deploying-to-digitalocean-droplet

- docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Some minor fixes to the new image CDN/CMD docs
> docs: Fixes to image CDN doc

- examples/using-type-definitions/gatsby-node.js
This PR fixes wrong resolve id for CommentJson type. Instead of resolving to `parent.author` it should resolve to `parent.blog` 
**Steps to test:**
1. `cd examples/using-type-definitions`
2. `npm start` (make sure you have all dependencies installed)
3. Open the following link:
```
http://localhost:8000/___graphql?query=query%20TestQuery%20%7B%0A%20%20commentJson(blog%3A%20%7Bid%3A%20%7Beq%3A%20%22blog-1%22%7D%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20text%0A%20%20%7D%0A%7D%0A&operationName=TestQuery
```
4. Run the query
5. It should return data.
**Before:**
**After:**
Fixes #30357
> fix(gatsby): Fix wrong resolve id for CommentJson type

- docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
> chore(docs): Fix typo in using-gatsby-image-plugin

- packages/gatsby-source-contentful/src/extend-node-type.js
* set default placeholder to `dominantColor`
* set default layout to `constrained`
> fix(contentful): set proper defaults for gatsby-plugin-image

- docs/docs/quick-start.md
Some explanatory text got added to the code block.
> fix(docs): fix what is in code block on quick start

- docs/docs/reference/built-in-components/gatsby-plugin-image.md
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/
> fix(docs): minor tweak to copy on https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/

- README.md
- packages/gatsby/README.md
* Adds handy link to release notes.
* Updates note about v2 contributions accepted.
[ch27938]
[ch28055]
> chore(docs): Add release notes link & v2 contrib note to readme

- docs/docs/reference/built-in-components/gatsby-link.md
Add heading & rewrite content somewhat
> fix(docs): clarify performance section of gatsby Link

- docs/docs/reference/gatsby-cli.md
- packages/gatsby-cli/README.md
> fix(docs): edit copy for gatsby cli docs

- docs/docs/how-to/sourcing-data/sourcing-from-wordpress.md
> chore(gatsby-source-wordpress): Link to source WP plugin

- docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md
Updated all 'master' references to 'main.'
> chore(docs): Update how-gatsby-works-with-github-pages

- examples/using-remark/src/pages/2018-01-27---custom-components/index.md
#30475
Updated example in src/pages/2018-01-27/index.md
Closes #30475.
> fix(gatsby-example-using-remark) fix broken example for typescript users

- docs/docs/reference/config-files/gatsby-browser.md
> fix(docs): Clarify explanations for gatsby-browser.js intro

- starters/blog/README.md
- starters/default/README.md
- starters/gatsby-starter-blog-theme-core/README.md
- starters/gatsby-starter-blog-theme/README.md
- starters/gatsby-starter-mdx-basic/README.md
- starters/gatsby-starter-minimal/README.md
- starters/gatsby-starter-notes-theme/README.md
- starters/gatsby-starter-theme-workspace/README.md
- starters/gatsby-starter-theme/README.md
- starters/gatsby-starter-wordpress-blog/README.md
> chore: Add cloud hosting option for starter READMEs

- docs/docs/tutorial/part-two/index.md
> chore(docs): Add tailwind to more options at tutorial part 2

- docs/docs/how-to/performance/resolving-out-of-memory-issues.md
Add documentation on resolving out-of-memory issues.
> add new doc

- integration-tests/functions/src/api/i-am-typescript.ts
- packages/gatsby/index.d.ts
- packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
TBD on what we want to do with extra Express functions.
> feat(gatsby): Add Typescript types for function requests/responses

- integration-tests/functions/__tests__/__snapshots__/functions-dev.js.snap
- integration-tests/functions/__tests__/__snapshots__/functions-prod.js.snap
- integration-tests/functions/src/api/cookie-me.ts
- integration-tests/functions/test-helpers.js
- packages/gatsby/index.d.ts
- packages/gatsby/package.json
- packages/gatsby/src/commands/serve.ts
- packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
> feat(gatsby): parse cookies in functions to req.cookies

- docs/docs/how-to/performance/improving-site-performance.md
Some last-minute details from the talk did not make it into the doc. Fixing that!
> chore(docs): Add more detail to improving site performance doc

- docs/docs/how-to/performance/improving-build-performance.md
Add Build Performance documentation
> add build performance documentation

- integration-tests/functions/src/api/redirect-me.ts
- integration-tests/functions/test-helpers.js
- packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
> feat(gatsby): test redirects

- docs/accessibility-statement.md
Fixes https://github.com/gatsbyjs/gatsby/issues/31001
> chore(docs): Update a11y statement

- README.md
- packages/gatsby/README.md
Fix grammar error:
You should use `Thanks go out to...` or `A thanks goes out to...` not `Thanks goes out to...`
> chore: Fix grammar error in README

- e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
- e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
> test: unskip eslint rules for fast refresh tests

- packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js
- packages/gatsby/src/services/start-webpack-server.ts
- packages/gatsby/src/utils/api-runner-node.js
Just testing potential changes to https://github.com/gatsbyjs/gatsby/pull/31104
> just testing changes to 31104

- benchmarks/query-filters-sort/README.md
- benchmarks/query-filters-sort/gatsby-config.js
- benchmarks/query-filters-sort/gatsby-node.js
- benchmarks/query-filters-sort/package.json
- benchmarks/query-filters-sort/src/pages/index.js
- benchmarks/query-filters-sort/src/templates/elemMatch-eq.js
- benchmarks/query-filters-sort/src/templates/eq.js
- benchmarks/query-filters-sort/src/templates/gt-lt.js
- benchmarks/query-filters-sort/src/templates/gt.js
- benchmarks/query-filters-sort/src/templates/in.js
- benchmarks/query-filters-sort/src/templates/lt.js
- benchmarks/query-filters-sort/src/templates/ne.js
- benchmarks/query-filters-sort/src/templates/nin.js
- benchmarks/query-filters-sort/src/templates/regex.js
New benchmark site to test various filters (with/without sorting).
> feat(benchmarks): add filters and sorting benchmark

- docs/docs/how-to/plugins-and-themes/maintaining-a-plugin.md
Adds GitHub discussion to doc
cc @pragmaticpat 
[ch28622]
> chore(docs): Add Plugin updates discussion to "maintaining a plugin"

- docs/docs/how-to/sourcing-data/sourcing-from-prismic.md
Hello Gatsby team, I'm opening a new PR for this Gatsby and Prismic page.
1. [I added links to our new documentation](https://prismic.io/docs/technologies/gatsby).
2. Some minor changes to match the correct plugin configuration
3.  Minor change to the gatsby-node query to generate the pages using the post.url value from the query.
4. And, a validation before saving the query responses. e.g., `if (!data) return null`
Let me know if you have any comments.
Thanks
> chore(docs): Update sourcing-from-prismic

- yarn.lock
Ran `npx yarn-deduplicate yarn.lock` on our repo
> chore: run yarn deduplicate

- packages/gatsby-source-shopify/README.md
Helps users use the latest Shopify source plugin (until it's merged into the monorepo)
> Updates Shopify README

- packages/gatsby-source-shopify/README.md
> fix(gatsby-source-shopify): fix linting

- docs/docs/how-to/functions/getting-started.md
Fixes risen from ux session with @calcsam
> feat(docs): Add notice that functions need flag enabled + simplify description of req/res

- docs/docs/how-to/functions/getting-started.md
> feat(docs): Add examples to functions getting started page

- packages/gatsby-source-wordpress/docs/tutorials/configuring-wp-gatsby.md
> Update typo in docs

- docs/docs/conceptual/choosing-a-cms.md
Easy navigation and easy reading for others
> chore(docs): Update "choosing a CMS"

- docs/docs/tutorial/part-0/index.mdx
- docs/docs/tutorial/part-1/index.mdx
- docs/docs/tutorial/part-2/index.mdx
Adds a UTM tracking parameter to the Gatsby Cloud links in the Tutorial, so that we can see whether the Tutorial is impacting conversion rates.
> docs(tutorial): add UTM param to Gatsby Cloud links

- docs/docs/how-to/functions/getting-started.md
Get people going quick if they want to try adding a form that submits to a function.
> feat(docs): Add sample form/function code to the function docs

- packages/gatsby-source-drupal/src/gatsby-node.js
> feat(gatsby-source-drupal): Add option validation

- integration-tests/functions/__tests__/__snapshots__/functions-dev.js.snap
- integration-tests/functions/__tests__/__snapshots__/functions-prod.js.snap
- integration-tests/functions/src/api/parser.js
- integration-tests/functions/test-helpers.js
- packages/gatsby/src/commands/serve.ts
- packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
We don't yet support handling raw file streams — that will come another time.
> feat(gatsby): Support uploading files as part of forms

- docs/docs/how-to/functions/middleware-and-helpers.md
Forgot to do this as part of https://github.com/gatsbyjs/gatsby/pull/31470
> chore(docs): document how to access uploaded files

- docs/docs/how-to/adding-common-features/adding-search.md
> chore(docs): Update adding-search

- integration-tests/functions/package.json
- packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
To ensure bootstrap is always fast regardless of how many functions a site has or how big they get.
> feat(gatsby): lazily compile functions in development

- packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
Content was wrapping in certain instances and inline styles were not being applied to svg's.
> fix content wrapping style issue

- packages/gatsby/src/datastore/in-memory/in-memory-datastore.ts
- packages/gatsby/src/datastore/index.ts
- packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
- packages/gatsby/src/datastore/types.ts
- packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
- packages/gatsby/src/redux/index.ts
- packages/gatsby/src/redux/nodes.ts
- packages/gatsby/src/redux/reducers/index.ts
- packages/gatsby/src/redux/reducers/nodes-by-type.ts
- packages/gatsby/src/redux/reducers/nodes.ts
- packages/gatsby/src/redux/types.ts
- packages/gatsby/src/utils/flags.ts
- packages/gatsby/src/utils/is-strict-mode.ts
Add `GATSBY_EXPERIMENTAL_STRICT_MODE` flag (disabled by default)
> feat(gatsby): add GATSBY_EXPERIMENTAL_STRICT_MODE flag

- docs/docs/reference/release-notes/v2.26/index.md
- docs/docs/reference/release-notes/v2.27/index.md
- docs/docs/reference/release-notes/v2.28/index.md
- docs/docs/reference/release-notes/v2.29/index.md
- docs/docs/reference/release-notes/v2.30/index.md
- docs/docs/reference/release-notes/v2.31/index.md
- docs/docs/reference/release-notes/v2.32/index.md
- docs/docs/reference/release-notes/v3.0/index.md
- docs/docs/reference/release-notes/v3.1/index.md
- docs/docs/reference/release-notes/v3.2/index.md
- docs/docs/reference/release-notes/v3.3/index.md
- docs/docs/reference/release-notes/v3.4/index.md
- docs/docs/reference/release-notes/v3.5/index.md
- docs/docs/reference/release-notes/v3.6/index.md
Add `title` frontmatter to release notes to have proper title in SEO tags
> chore(docs): Add title to release notes

- examples/creating-source-plugins/source-plugin/gatsby-node.js
> Fixed syntax error in example

- docs/docs/how-to/routing/client-only-routes-and-user-authentication.md
> chore(docs): Correct nginx spelling

- packages/gatsby/src/utils/flags.ts
Adds the umbrella issue to the flag
> chore(gatsby): Add umbrellaIssue to lmdb

- packages/gatsby/src/utils/flags.ts
We eventually want to publish this for everyone, so let's bump the automatic opt in
[ch31429]
> chore(gatsby): Bump `PRESERVE_WEBPACK_CACHE` flag to 20%

- packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
- packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
- packages/gatsby/src/bootstrap/load-plugins/load.ts
- packages/gatsby/src/internal-plugins/functions/package.json
- packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
- packages/gatsby/src/utils/flags.ts
We want to ship Gatsby Functions for all users! This PR gets rid of the experimental feature flag and ships it for all! Rejoice!
> feat(gatsby): Turn on Functions experiment for everybody

- packages/gatsby-source-drupal/src/normalize.js
> Fixes bug where datum have no attributes and attributes have no langcode.

- benchmarks/gabe-fs-markdown/README.md
Fixed Grammar Issue regarding documentation
> chore(docs): Fix grammar issue

- packages/gatsby/src/utils/worker/__tests__/schema.ts
ref https://github.com/gatsbyjs/gatsby/pull/31919
> fix: do not hang on schema in worker unit tests

- docs/docs/reference/release-notes/v3.8/index.md
Release notes for v3.8. Please add anything you would like to mention from this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-3.8/docs/docs/reference/release-notes/v3.8/index.md)
> docs: 3.8 release notes

- docs/docs/reference/release-notes/v3.8/index.md
Fix incomplete entry in release notes
> docs: remove TODO from release notes

- docs/docs/tutorial/part-1/index.mdx
> chore(docs): Fix typo in tutorial

- packages/gatsby-plugin-sitemap/README.md
Clarify some language on what files are created and why.
Fixes https://github.com/gatsbyjs/gatsby/issues/31282
> chore(gatsby-plugin-sitemap): Clarify language on entryLimit

- starters/README-template.md
> chore(starters): Add a Gatsby CLI instructions link

- docs/docs/tutorial/part-1/index.mdx
- docs/docs/tutorial/part-2/index.mdx
- docs/docs/tutorial/part-4/index.mdx
This PR:
* Tweaks some copy in Parts 1, 2, and 4 of the Tutorial.
* Embeds the livestream video for Part 1.
* `/docs/tutorial/part-1/`
* `/docs/tutorial/part-2/`
* `/docs/tutorial/part-4/`
> docs(tutorial): copy edits for parts 1, 2, 4

- docs/docs/reference/routing/file-system-route-api.md
Cleanups & more consistency in how we describe things
> feat(docs): edit file system route API docs page

- docs/docs/reference/release-notes/v3.9/index.md
Release notes for v3.9. Please add anything you would like to mention from this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-3-9/docs/docs/reference/release-notes/v3.9/index.md)
> docs: 3.9 release notes

- docs/docs/how-to/adding-common-features/seo.md
- docs/docs/how-to/performance/improving-build-performance.md
We have additional deep-dives in the form of webinars we've done on some of these topics that will be helpful for folks trying to dive deep.
> feat(docs): add additional resource links

- packages/gatsby-cli/src/reporter/redux/actions.ts
- packages/gatsby-cli/src/reporter/reporter-phantom.ts
- packages/gatsby-cli/src/reporter/reporter-progress.ts
- packages/gatsby-cli/src/reporter/reporter-timer.ts
- packages/gatsby-cli/src/reporter/reporter.ts
- packages/gatsby-cli/src/reporter/types.ts
- packages/gatsby/src/utils/worker/__tests__/reporter.ts
- packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
- packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
- packages/gatsby/src/utils/worker/child/index.ts
- packages/gatsby/src/utils/worker/messaging.ts
- packages/gatsby/src/utils/worker/pool.ts
- packages/gatsby/src/utils/worker/reporter.ts
In workers log action creators are not dispatching actions, but instead send "LOG_INTENT" to parent process and action creators are called inside main process 
[ch31778]
> feat(pqr): handle structured logs

- packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
Some large Gatsby Cloud sites OOM while writing out the _headers.json file.
I replicated this with a 100k page test site which showed locally a ~700mb
spike in memory while writing out a ~50mb `_header.json` file.
About 300mb of that is from stringifying the JSON and the remainder from
`fs.writeFile`. Switching to a write stream eliminates the later portion of the
memory spike. We could refactor our headers data model to allow using
https://www.npmjs.com/package/JSONStream but given other refactors coming soon,
that's probably not worth it.
> fix(gatsby-plugin-gatsby-cloud): lower peak memory usage by stream writing the _header.json file

- packages/gatsby-source-wordpress/src/gatsby-node.ts
> fix(gatsby-source-wordprepss): delete auth details earlier v2

- packages/gatsby/src/redux/save-state.js
Tracking duration of save-state.
[ch32214]
> feat(gatsby): Track persistence time of save-state

- packages/gatsby/src/utils/flags.ts
Adds an experimental flag for PQR that also activated `LMDB_STORE`. Copied the `testFitness` as it stays the same.
[ch34214]
> chore(gatsby): Add PQR feature flag

- docs/docs/ab-testing.md
nitpick.
Just a quick nitpick. Javascript -> JavaScript
no related issues
> chore(docs): Correct JavaScript spelling

- packages/gatsby-source-contentful/src/__tests__/__snapshots__/extend-node-type.js.snap
- packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
- packages/gatsby-source-contentful/src/extend-node-type.js
closes #29784
This adds the corner radius feature of the Contentful Image API.
> feat(contentful): add support image corner radius

- docs/docs/how-to/adding-common-features/seo.md
Removes an unnecessary bullet point found in the docs
N/A
N/A
> chore(docs): SEO remove typos & outdated information

- docs/docs/reference/release-notes/v3.10/index.md
Release notes for v3.10. Please add anything you would like to mention from this release.
[Rendered Version](https://github.com/gatsbyjs/gatsby/blob/docs/release-notes-3.10/docs/docs/reference/release-notes/v3.10/index.md)
[ch34608]
> chore(docs): 3.10 Release Notes

- packages/gatsby/src/utils/worker/pool.ts
Make chunkSize configurable by an env var.
> fix(gatsby): Configurable PQR chunksize by env var

- starters/README-template.md
- Fixed sentence clarity and grammatical errors
- Updated the links
> chore(starters): Update links in README-template

- docs/docs/how-to/routing/migrate-remark-to-mdx.md
"Importing and Using Components in MDX" is now pointing to the correct resource.
> Removed another broken link and fixed

- examples/creating-source-plugins/source-plugin/gatsby-node.js
> fix(examples): Correct typo in comment

- packages/gatsby-plugin-gatsby-cloud/package.json
cp is not a valid windows command so using a cli tool instead
> chore(gatsby-plugin-gatsby-cloud): update copy script for windows

- packages/gatsby-source-wordpress/docs/plugin-options.md
Typo fix from wether to whether
N/A
N/A
> Fix typo of wether to whether

- docs/docs/how-to/adding-common-features/localization-i18n.md
Add additional language to intro paragraph to be more descriptive of whole localization efforts needed
> add intro paragraph

- docs/tutorial/remark-plugin-tutorial.md
Some followers of the tutorial may not see the intended effect (heading one getting colored with rebecca purple). Assuming that they follow it correctly, the solution may be simply clearing out the cache or hard refresh the borwser.
[Debugging cache issues](https://www.gatsbyjs.com/docs/debugging-cache-issues/)
None
> chore(docs): Remark plugin, add tip for gatsby clean

- docs/docs/conceptual/image-plugin-architecture.md
Looks like this doc is missing a title. Adding it back. 😄
> chore(docs): Add title for image-plugin-architecture

- docs/docs/conceptual/security-in-gatsby.md
Add clarification of exactly what security benefits Gatsby has
> chore(docs): Update security-in-gatsby

- docs/docs/reference/release-notes/v3.12/index.md
[View Rendered](https://github.com/gatsbyjs/gatsby/blob/release-notes-3.12/docs/docs/reference/release-notes/v3.12/index.md)
[ch36381]
> chore(docs): 3.12 Release Notes

- docs/docs/how-to/adding-common-features/localization-i18n.md
- docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Previous PRs did not have proper formatting, fixing!
> chore(docs): Add formatting for changed docs

- packages/gatsby/src/utils/start-server.ts
Small typing error, as it's never of the https.Server type
> fix(gatsby): Correct server type

- docs/docs/tutorial/part-4/index.mdx
> chore(docs): Fixes typo in tutorial part 4

- docs/docs/tutorial/part-6/index.mdx
> chore(docs): Fix typo in tutorial part 6

- packages/gatsby-source-wordpress/src/steps/preview/index.ts
Fixes https://github.com/gatsbyjs/gatsby/issues/32732
Related to https://github.com/gatsbyjs/wp-gatsby/pull/184
> fix(gatsby-source-wordpress): make sure remoteUrl exists before using it

- packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
> tests(gatsby-source-contentful): fix snapshot

- .circleci/config.yml
This PR enables auto-updating changelogs on releases (via separate PRs). A follow up for #32886
> chore: enable changelog updates on releases

- packages/gatsby-legacy-polyfills/package.json
- packages/gatsby-legacy-polyfills/src/__tests__/polyfills.js
- packages/gatsby-recipes/src/providers/npm/__snapshots__/package.test.js.snap
- renovate.json5
- scripts/renovate-config-generator.js
- yarn.lock
> chore: fix broken recipes test

- packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
- packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
- packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
- packages/gatsby/src/schema/__tests__/node-model.js
- packages/gatsby/src/schema/types/built-in-types.ts
Add built-in types `SitePlugin` and `SiteBuildMetadata`
[ch37400]
> fix(gatsby): add missing built-in types 

- docs/docs/glossary/decoupled-drupal.md
- docs/docs/glossary/headless-cms.md
- docs/docs/glossary/headless-wordpress.md
Added educational content to the article
> chore(docs): Update docs about "Headless CMSs"

- docs/docs/conceptual/making-your-site-accessible.md
This PR will fix some typos and improve the Concepts section of the
> chore(docs): Update "Making your site accessible"

- scripts/gatsby-changelog-generator/generate.js
- scripts/gatsby-changelog-generator/update-and-open-pr.js
Fix commit message for changelog auto-updates. Also, exclude commits that update changelogs from changelogs 😄
A follow up for #32886 and #32965
> chore: correct messages for auto-changelog PRs

- starters/blog/src/components/bio.js
- starters/default/src/pages/index.js
Fixing Type '["AUTO", "WEBP", "AVIF"]' is not assignable to type 'ImageFormat'.
starter template change.
Non.
> fix(starters): Formats for StaticImage

- docs/docs/how-to/performance/improving-site-performance.md
Thanks @LekoArts for the note!
> chore(docs): Fix links in perf doc

- starters/blog/gatsby-config.js
- starters/blog/package-lock.json
- starters/blog/package.json
- starters/default/gatsby-config.js
- starters/default/package-lock.json
- starters/default/package.json
removes `gatsby-plugin-gatsby-cloud` plugins from starters
> chore: remove gatsby-cloud-gatsby-plugin

- packages/gatsby/src/redux/actions/public.js
- packages/gatsby/src/schema/graphql-engine/print-plugins.ts
- packages/gatsby/src/utils/page-data.ts
This PR includes several fixes to the experimental engines. See inline comments for details.
> fix(gatsby): fix experimental engines

- packages/gatsby/src/schema/graphql-engine/entry.ts
> fix(gatsby): fix onPluginInit api calls in engine

- docs/docs/tutorial/part-3/index.mdx
Gatsby cloud is not used further on (it doesn't appear in the next snippet in the next lesson) and wasn't introduced previously
Remove  "gatsby-plugin-gatsby-cloud" from a code snippet inside documentation
Updated
> chore(docs): Correct gatsby-cloud plugin in tutorial part 3

- packages/gatsby-transformer-documentationjs/src/gatsby-node.js
move createTypes to createSchemaCustomization
> feat(gatsby-transformer-documentationjs): move createTypes to createSchemaCustomization

- docs/docs/tutorial/part-0/index.mdx
- docs/docs/tutorial/whats-next/index.mdx
* Updates minimum Node version to 14.15 for Gatsby 4
* Adds DSG and SSR links to the What's Next section
[sc-37946](https://app.shortcut.com/gatsbyjs/story/37946/update-tutorial-for-g4)
* /docs/tutorial/part-0
* /docs/tutorial/whats-next
> chore: update tutorial for v4

- packages/gatsby-plugin-gatsby-cloud/src/__tests__/routes.js
- packages/gatsby/src/commands/serve.ts
- packages/gatsby/src/redux/actions/public.js
- packages/gatsby/src/redux/types.ts
Changes name from DSR to DSG
[sc-38297]
> chore(gatsby): move to DSG instead of DSR

- docs/docs/how-to/rendering-options/using-deferred-static-generation.md
A how-to guide on using DSG
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/v4-docs-howto-dsg/docs/docs/how-to/rendering-options/using-deferred-static-generation.md)
References some other (currently not existing) documents, so those should also be created before this goes public.
[ch37940]
> chore(docs): How-To DSG

- docs/docs/how-to/rendering-options/using-server-side-rendering.md
A how-to guide on using SSR
References some other (currently not existing) documents, so those should also be created before this goes public.
[ch37902]
> chore(docs): How-To SSR

- integration-tests/structured-logging/__tests__/to-do.js
- packages/gatsby/src/commands/build.ts
> test(structured-logging): adjust for v4

- docs/docs/reference/release-notes/v3.14/index.md
Fix `v3.14` release notes formatting.
> chore(docs): fix formatting

- packages/gatsby/src/utils/start-server.ts
In develop mode we check if the page exists, if not we add status code 404.
> tests: fix functions integration tests

- docs/docs/reference/functions/getting-started.md
People keep asking how this works so I figure I should actually document https://github.com/gatsbyjs/gatsby/pull/31466 😅
> feature(docs): Document how functions work in plugins/themes

- docs/docs/how-to/rendering-options/using-deferred-static-generation.md
Correct the description of the DSG code snippet
> chore(docs): Grammar fix in using-deferred-static-generation

- e2e-tests/development-runtime/cypress/integration/functionality/query-data-caches.js
- packages/gatsby/src/utils/start-server.ts
https://github.com/gatsbyjs/gatsby/pull/33258 introduced some changes that need fixing/adjusting e2e dev runtime tests
> tests(e2e-dev): handle edge cases introduced with 404 for not existing pages

- docs/docs/how-to/performance/improving-site-performance.md
Fix missing space and quote in _Improving Site Performance_ how-to guide.
> chore(docs): fix typo in site perfomance guide

- docs/docs/tutorial/part-1/index.mdx
- docs/docs/tutorial/part-5/index.mdx
- docs/docs/tutorial/part-6/index.mdx
This PR includes some small tweaks to the tutorial instructions based on my experience walking through it. All very small copy changes.
N/A as this is updating the tutorial, which is essentially documentation.
sc-37809
> chore(docs): Tutorial walkthrough feedback tweaks

- docs/docs/how-to/performance/improving-site-performance.md
> docs: fix "(r)esource congestion"

- packages/gatsby-plugin-manifest/README.md
Some links like https://www.w3.org/TR/appmanifest/#dfn-directionality-capable-members are broken. Update them may be good.
> chore(gatsby-plugin-manifest): Update README links

- docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
- docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
- docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.md
Upgrade our main source plugin guide + migration guide to help people use `createRemoteFileNode` correctly
> chore(docs): Upgrade guides about file linking

- docs/docs/add-a-service-worker.md
This PR fixes minor punctuation and grammatical errors.
Minor documentation fixes.
N/A
> chore(docs): Improve "Adding a service worker"

- packages/gatsby-plugin-mdx/__tests__/gatsby-node.js
- packages/gatsby-plugin-mdx/gatsby-node.js
Fixes https://github.com/gatsbyjs/gatsby/pull/30669#issuecomment-956434334
> chore(gatsby-plugin-mdx): Add commonmark to pluginOptionsSchema

- examples/gatsbygram/data/posts.json
- examples/gatsbygram/src/components/Avatar.js
The URLs to Instagram where no longer working, so just replacing it with a placeholder
Fixes https://github.com/gatsbyjs/gatsby/issues/33744
> chore(examples): Fix Gatsbygram

- scripts/gatsby-changelog-generator/update-and-open-pr.js
Fixes changelog auto-updates in CI (maybe, needs some testing)
> chore: fix changelog auto-updates in ci

- docs/docs/how-to/rendering-options/using-deferred-static-generation.md
- docs/docs/reference/rendering-options/deferred-static-generation.md
- docs/docs/reference/rendering-options/server-side-rendering.md
- docs/docs/reference/routing/file-system-route-api.md
Should be merge when https://github.com/gatsbyjs/gatsby/pull/33788 is also merged
[ch40829]
> chore(docs): Update docs for DSG in FS Routes

- packages/gatsby/src/utils/start-server.ts
> fix(gatsby): apply getServerData response header in develop

- scripts/gatsby-changelog-generator/update-and-open-pr.js
Error handling for update changelogs script (do not leak the token in case of errors)
> chore: error handling for update changelogs script

- packages/gatsby/src/schema/infer/inference-metadata.ts
Correct the typescript
Fixes #33838
> chore(gatsby): Update inference-metadata type

- packages/gatsby/src/schema/graphql-engine/entry.ts
Just wrap graphql engine initialization related spans under single root span.
Best viewed by ignoring whitespace changes - https://github.com/gatsbyjs/gatsby/pull/33898/files?diff=unified&w=1
> fix(gatsby): wrap graphql engine initialization in activity

- packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
> fix(gatsby-plugin-gatsby-cloud): Preview UI tooltip

- docs/docs/how-to/routing/client-only-routes-and-user-authentication.md
Making some changes to fix some grammar issues I noticed while reading the docs.
- Fix typo
- Rephrase sentence to make it grammatically correct
> chore(docs): Update client-only doc

- docs/docs/processing-payments-with-square.md
> chore(docs): Typo in docs/processing-payments-with-square

- examples/creating-source-plugins/README.md
> chore(examples): Typo in creating-source-plugins

- examples/functions-google-oauth/README.md
> chore(examples):Typo in  functions-google-oauth/README

- docs/docs/how-to/performance/improving-build-performance.md
Since it doesn't exist anymore.
> chore(docs): remove mention of willitbuild.com

- packages/create-gatsby/src/cmses.json
- packages/create-gatsby/src/features.json
- packages/create-gatsby/src/styles.json
Order everything alphabetically
> fix(create-gatsby): Order inputs alphabetically

- docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
- docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.md
We've seen some people get tripped up by this so adding a note about limitation of engine bundling
> chore(docs): Note about engine bundling

- packages/gatsby-recipes/package.json
- packages/gatsby/package.json
- yarn.lock
Fixes https://github.com/gatsbyjs/gatsby/issues/33713
> fix(gatsby-recipes): Pin `remark-mdx` to `2.0.0-next.7`

- packages/gatsby/src/utils/jobs/manager.ts
This is just to have separate progress bar for each job type for few reasons:
1. `Running jobs` isn't that descriptive to users on its own (users don't have to know what a job is in gatsby context). This will add `gatsby-plugin-sharp.IMAGE_PROCESSING` to progress bar labels that should make it easier to tell what it is (still not that great, but that's metadata we already have and seems good enough).
2. If/when we add other job types we won't need to adjust progress bar then and labels of activities won't need to change then
This is against https://github.com/gatsbyjs/gatsby/pull/34061 PR (not against `master`)
> feat: add job type to progress label, so each job type has separate progress bar

- packages/gatsby-cli/src/reporter/redux/diagnostics.ts
- packages/gatsby-cli/src/reporter/reporter.ts
- packages/gatsby-cli/src/structured-errors/error-map.ts
- packages/gatsby/src/services/initialize.ts
This adds addional section to stuck messages that contain up to 5 in-progress jobs (avoided printing all in-progress as that might spam console heavily, and 5 should be enough to find why they are stuck).
<details>
<summary>Example output</summary>
```
warn This is just diagnostic information (enabled by GATSBY_DIAGNOSTIC_STUCK_STATUS_TIMEOUT):
Gatsby is in "IN_PROGRESS" state without any updates for 30.000 seconds. Activities preventing Gatsby from transitioning to idle state:
- Activity "build" of type "hidden" is currently in state "IN_PROGRESS"
- Activity "Running jobs v2" of type "hidden" is currently in state "IN_PROGRESS"
Additional debugging logs:
Unfinished jobs (showing 4 of 4 jobs total):
[
{
"id": "28a3ec94-e626-4629-9175-0c511d3d177b",
"name": "IMAGE_PROCESSING", …
```
> chore(gatsby): log pending jobs when build is stuck

- docs/docs/reference/release-notes/v4.3/index.md
[View rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-4.3/docs/docs/reference/release-notes/v4.3/index.md)
> chore: Release-notes for 4.3

- docs/docs/reference/release-notes/v4.3/index.md
> chore: update release-notes

- packages/gatsby/src/redux/actions/public.js
PR to include more description about `updatedAt` parameter at DatoCMS team's request. https://github.com/datocms/gatsby-source-datocms/pull/180#issuecomment-983637294
> chore(docs): update createNodeManifest action updatedAt description

- docs/docs/how-to/plugins-and-themes/adding-gatsby-image-support.md
Adds missing comma in object  in code example
> chore(docs): Add missing comma to code example

- docs/docs/why-gatsby-uses-graphql.md
> docs: fix typo in gatsby-image

- docs/docs/mdx/programmatically-creating-pages.md
Before: `gastby-plugin-mdx`
After: `gatsby-plugin-mdx`
https://www.gatsbyjs.com/docs/mdx/programmatically-creating-pages/#create-pages-from-sourced-mdx-files
Null
> docs: change gastby to gatsby

- docs/docs/how-to/adding-common-features/localization-i18n.md
> chore(docs): Update localization doc

- README.md
Pluralize **Choose your Rendering Option** -> **Choose your Rendering Options**
Adding "s" to **Choose your Rendering Option**
N/A
> chore: Fix typo

- docs/docs/how-to/images-and-media/preprocessing-external-images.md
- docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Correct args for createRemoteFileNode
> chore(docs): Update processing external images guide

- packages/gatsby-source-wordpress/docs/features/media-item-processing.md
> chore(gatsby-source-wordpress): Fix typo

- docs/docs/quick-start.md
Feedback came in that it was unclear if the CLI would create a folder or if the user needs to create it. Also updated outdated links while at it
> chore(docs): Update quick-start guide

- docs/docs/how-to/adding-common-features/adding-search.md
Adding MeiliSearch option to the `API-based search engine` section
> chore(docs): Add MeiliSearch

- e2e-tests/contentful/cypress/integration/tags.js
- e2e-tests/contentful/src/pages/tags.js
- packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
- packages/gatsby-source-contentful/src/__tests__/normalize.js
- packages/gatsby-source-contentful/src/normalize.js
- packages/gatsby-source-contentful/src/source-nodes.js
> fix(contentful): enable tag support for assets

- scripts/check-lockfile.sh
Just minor wording update, so that message is clearly actionable (how to address it)
> chore: make dirty yarn.lock message more actionable

- packages/gatsby/src/utils/source-nodes.ts
TL/DR: for now this is just swapping from array to iterable, but it doesn't actually solve potential high memory usage/OOM during this step - see explanation below
**UPDATE**:
There is a way to GC things actually in sync scenarios so while everything below is true today, there will be changes coming to `iterateNodes()` internals to allow for things to GC.
This alone in practice doesn't have an effect on memory usage due to function chain here being fully sync and us using lmdb's cache setting. I'm still researching it, but it seems like LMDB cache is using `WeakRef` and object that are wrapped with it CAN'T be garbage collected within same "tick" (?). Per [WeakRef spec](https://github.com/tc39/proposal-weakrefs/blob/99c96cfbaf919f8405d329e76df166e7aab34d7a/history/spec.md) creating or …
> chore(gatsby): use lazy iterable instead of fully realized arrays for detecting stale nodes

- docs/docs/how-to/previews-deploys-hosting/deploying-to-netlify.md
Use less flowery words to describe features.
> chore(docs): Update doc

- packages/gatsby-source-wordpress/docs/usage-with-popular-wp-graphql-extensions.md
Handles https://github.com/wp-graphql/wp-graphql/issues/2129
> chore(gatsby-source-wordpress): Add WPGraphQL WPML

- docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
This PR:
- Adds docs describing how to enable the new "Eager redirects" feature in Content Sync
- Makes a few small tweaks to other language in the supporting Content Sync section
> docs: Content Sync Eager Redirects

- e2e-tests/trailing-slash/cypress/integration/static.js
Hopefully fixes flakyness in trailing-slash e2e test
> chore: Update trailing-slash static E2E test

- packages/create-gatsby/src/questions/features.json
Fixes https://github.com/gatsbyjs/gatsby/issues/34706
> fix(create-gatsby): Use MDX v1

- starters/gatsby-starter-minimal-ts/gatsby-config.js
- starters/gatsby-starter-minimal-ts/package-lock.json
- starters/gatsby-starter-minimal-ts/package.json
Two smaller things I noticed while trying the starter out:
1. Indendation of siteUrl
2. Moving TS deps to `devDeps`
> chore: Update TS minimal starter

- examples/route-api/src/pages/index.js
> chore(examples): Typo fix

- docs/tutorial/building-a-theme.md
Addresses discrepancies between written tutorial and egghead.io video tutorial.
Fixes #34728
> chore(docs): Update "building a theme" tutorial

- docs/docs/reference/release-notes/v4.7/index.md
Currently in public beta - we don't want to set the wrong expectation with our users. Thanks!
> chore(docs): Updated release notes for trailing slash

- packages/gatsby-plugin-image/README.md
I only fixed a small spelling error in `gatsby-plugin-image`
> chore(gatsby-plugin-image): update readme typo

- README.md
- packages/gatsby/README.md
Changing one line in the readme to reflect our north star.
> chore(gatsby): Update North Star in README

- docs/docs/how-to/adding-common-features/adding-search.md
Update some details in search providers
> chore(docs): Add search details

- scripts/gatsby-changelog-generator/generate.js
Fix generated markdown for changelogs failing lint check.
N/A
N/A
> chore: Fix changelog generator script failing lint

- integration-tests/cache-resilience/gatsby-node.js
> fix cache reslience setup

- starters/gatsby-starter-minimal-ts/gatsby-config.js
> Update typo in gatsby-config.js

- docs/docs/creating-a-starter.md
The link was broken. It looks like it was moved from Medium to another platform (dev.to).
> chore(docs): Update link to "How to create a Gatsby Starter" 

- renovate.json5
- scripts/renovate-config-generator.js
Group Parcel dependencies into its own group
> chore: Update renovate config for Parcel

- examples/using-vanilla-extract/README.md
- examples/using-vanilla-extract/gatsby-config.ts
- examples/using-vanilla-extract/package.json
- examples/using-vanilla-extract/tsconfig.json
> chore(examples): Update vanilla-extract

- docs/docs/how-to/custom-configuration/typescript.md
- docs/docs/reference/release-notes/v4.9/index.md
Release notes for 4.9
[Rendered View](https://github.com/gatsbyjs/gatsby/blob/release-notes-4.9/docs/docs/reference/release-notes/v4.9/index.md)
[ch46996]
> chore(docs): 4.9 Release Notes

- docs/contributing/gatsby-governance-model.md
Clarify wording as per @ascorbic comments
> chore(docs): Clarify wording on governance doc

- packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
- packages/gatsby/src/schema/graphql-engine/lmdb-bundling-patch.ts
> fix(gatsby): fix pnp for lmdb

- docs/docs/query-extraction.md
> chore(docs): Update query-extraction link to relay

- docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Adds docs for enabling Image CDN to source plugin authors
> chore(docs): Add image CDN enablement docs

- packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
- packages/gatsby-source-contentful/src/create-schema-customization.js
- packages/gatsby-source-contentful/src/gatsby-node.js
- packages/gatsby-source-contentful/src/report.js
Show proper error when gatsby-plugin-image is not available or configured.
With this PR:
Before:
> feat(gatsby-source-contentful): improve gatsby-plugin-image errors

- docs/docs/query-extraction.md
> docs(gatsby): Update `query-watcher` to reference TS file

- docs/docs/query-execution.md
- Fix broken link to source code (JS file is now a TS file)
- Remove line reference since that can change at any time
> chore(docs): Update query-execution.md

- docs/docs/how-to/custom-configuration/typescript.md
- docs/docs/reference/release-notes/v4.9/index.md
Some clarifying comments as per https://github.com/gatsbyjs/gatsby/issues/35079
> chore(docs): Clarify TS release doc

- docs/docs/glossary.md
Include definition and references to docs.
> chore(docs): Add Deferred Static Generation to glossary

- packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
- yarn.lock
> chore: cleanup yarn.lock

- packages/gatsby-plugin-benchmark-reporting/package.json
- packages/gatsby-transformer-sqip/package.json
Fix forgotten dependencies in package.json and fix tests
> chore: fix dependencies

- docs/tutorial/prismic-source-graphql-tutorial.md
- Update the prismic source graphql tutorial docs
> chore(docs): Update prismic source graphql tutorial docs

- docs/docs/reference/release-notes/v4.11/index.md
talk about react 18 and not RC.
https://twitter.com/reactjs/status/1508838714180612100
> docs: update react 18 notes

- docs/docs/how-to/adding-common-features/adding-search.md
Hi Gatsby team 👋
We changed the way of writing Meilisearch, I take the opportunity to update this reference.
Thanks for your great work!
Fix Meilisearch spelling in `docs/docs/how-to/adding-common-features/adding-search.md`
N/A
> chore(docs): Fix Meilisearch spelling

- docs/docs/api-files.md
- docs/docs/glossary.md
- docs/docs/how-to/custom-configuration/typescript.md
- docs/docs/reference/config-files/gatsby-browser.md
- docs/docs/reference/config-files/gatsby-config.md
- docs/docs/reference/config-files/gatsby-node.md
- docs/docs/reference/config-files/gatsby-ssr.md
- docs/docs/reference/gatsby-project-structure.md
Updating some of our docs to point out that you can now author files in TS
[ch48480]
> chore(docs): Update config files TS refs

- packages/gatsby/cache-dir/production-app.js
Copy what we do in `app.js` to account for e.g. gatsby-plugin-offline
Fixes https://github.com/gatsbyjs/gatsby/issues/35193
> fix(gatsby): React 18 Hydration with offline plugin

- docs/docs/how-to/adding-common-features/adding-forms.md
> chore(docs): Typo on "Adding forms"

- docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Just a small change to make this easier to understand
> docs(gatsby): image cdn author docs tweak

- docs/docs/reference/release-notes/gatsby-version-support.md
Widget feedback said that the information on the page is slightly incorrect or unclear. So fixed that.
> chore(docs): Update version support page

- e2e-tests/contentful/cypress/integration/rich-text.js
- e2e-tests/contentful/snapshots.js
- packages/gatsby-source-contentful/package.json
- yarn.lock
This will add support for rendering tables via Contentful Rich Text.
> feat(contentful): add support for tables in Rich Text

- docs/docs/reference/built-in-components/gatsby-script.md
Documentation for the Gatsby Script implementation.
[sc-48161]
> chore(docs): Gatsby Script docs

- docs/docs/reference/functions/middleware-and-helpers.md
[46901]
Update the documentation for Gatsby Functions Configs.
> chore(docs): Add ability to configure body parsing in Gatsby Functions

- docs/contributing/rfc-process.md
Updates the template to include also the "Try it out" section
> chore(docs): Update RFC template

- examples/using-shopify/README.md
- examples/using-square-payments/README.md
- examples/using-type-definitions/README.md
Small update to make the "Deploy" section consistent with the rest of our examples.
> Updated hosting links

- packages/gatsby-script/.babelrc
- packages/gatsby-script/src/gatsby-script.tsx
- packages/gatsby/src/commands/serve.ts
- packages/gatsby/src/internal-plugins/partytown/gatsby-browser.tsx
- packages/gatsby/src/internal-plugins/partytown/gatsby-node.ts
- packages/gatsby/src/internal-plugins/partytown/proxy.ts
Miscellaneous comments from @wardpeet in #35403
N/A
N/A
> refactor(gatsby,gatsby-script): Misc review comments

- packages/gatsby-script/src/gatsby-script.tsx
Adjust logic for warning if collect script context is not found.
N/A
> fix(gatsby-script): Adjust warning control flow

- packages/gatsby-source-drupal/src/gatsby-node.js
Added a check for data prop before destructuring it. 
Fixes #35718
> fix(gatsby-source-drupal): Add a check for data prop

- packages/gatsby/src/bootstrap/load-plugins/utils/handle-gatsby-cloud.ts
> fix(gatsby): correctly auto-load preview plugin

- packages/gatsby-plugin-gatsby-cloud/README.md
> chore(gatsby-plugin-gatsby-cloud): add note about auto installation

- docs/docs/awesome-gatsby-resources.md
This will add two articles to the resources doc in the tutorials category
* [Image Processing in Gatsby](https://www.useanvil.com/blog/engineering/gatsby-image-processing/)
* [Improving build times in Gatsby](https://www.useanvil.com/blog/engineering/build-times-in-a-static-site-generated-website/)
> chore(docs): Add articles to awesome gatsby resources

- benchmarks/create-pages/package.json
> chore(benchmarks): Upgrade create-pages benchmark to v4

- docs/docs/reference/built-in-components/gatsby-script.md
> chore(docs): Remove typo in Script guide

- .circleci/config.yml
> test: run mdx-less-babel in circleci

- docs/docs/reference/release-notes/v4.16/index.md
> chore(docs): add changelog URL to 4.16 release notes

- docs/docs/how-to/adding-common-features/adding-analytics.md
Made reference to Gatsby script component used for loading performant scripts
> chore(docs): Add Gatsby Script component to "Adding Analytics"

- packages/gatsby-cli/src/create-cli.ts
The reproduction in https://github.com/gatsbyjs/gatsby/issues/35018 showed that the main process and query workers were using different LMDB files. It showed that the main process used the test file:
https://github.com/gatsbyjs/gatsby/blob/db682079e722f0ac1214be917d7bc24d4f6a847a/packages/gatsby/src/utils/cache-lmdb.ts#L5-L14
And the workers the correct LMDB files.
This PR moves the `process.env.NODE_ENV` call to before we require `gatsby` (and initiate LMDB).
Fixes https://github.com/gatsbyjs/gatsby/issues/35018
[ch52019]
> fix(gatsby-cli): Set `NODE_ENV` earlier in commandHandler

- docs/docs/tutorial/part-1/index.mdx
In my case I couldn't "Select" the project I had to click on "Import", we could update the copy here.
> chore(docs): Update copy in tutorial part 1

- packages/gatsby/cache-dir/__tests__/head/utils.js
- packages/gatsby/cache-dir/head/utils.js
- packages/gatsby/cache-dir/page-renderer.js
- packages/gatsby/cache-dir/static-entry.js
- packages/gatsby/index.d.ts
Filter out props that are passed to `head` to only valid ones. Also create a valid `HeadProps` type
[ch52630]
> feat(head-function-export): Correct props

- packages/gatsby-source-contentful/src/normalize.js
- yarn.lock
Fix wrong parent field. This becomes problematic when we look at improving our datalayer
> fix(gatsby-source-contentful): remove faulty parent

- packages/gatsby-plugin-mdx/README.md
fix a typo in the  plugin's v3 to v4 migration guide
> docs(gatsby-plugin-mdx): fix a typo in v3 to v4 migration guide

- packages/gatsby-plugin-mdx/README.md
Adds steps to migrate to the new MDX docs
> MDXv2: docs: add steps to migrate

- packages/gatsby-plugin-typescript/src/gatsby-node.js
Make `Head` function export work in tsx files.
N/A
[sc-53058]
> fix(head-function-export): Make tsx pages work

- docs/docs/basic-hardware-software-requirements.md
Update the docs added Platform specific issues topic with a general note describing the Platform specific issues.
Updated Documentation of Basic Hardware and Software Requirements
Fixes #36000
> chore(docs): Update to Basic Hardware and Software Requirements

- packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
We make sure DSG understands our image-cdn flag to not use native sharp.
Partially fixes https://github.com/gatsbyjs/gatsby/issues/35937
> fix(gatsby): add GATSBY_CLOUD_IMAGE_CDN

- docs/docs/reference/release-notes/v4.19/index.md
> chore(docs): Typo in 4.19 release notes

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- docs/contributing/how-to-make-a-reproducible-test-case.md
- docs/contributing/rfc-process.md
> chore: Improve docs around minimal reproduction

- docs/docs/tutorial/part-1/index.mdx
Corrected text that says "It may useful for..." to "It may be useful for ..."
> Grammar typo fixed

- docs/docs/debugging-html-builds.md
Minor typo fix in debugging-html-builds.md
To replace **localstorage** with  **localStorage**
> chore(docs): Typo fix in debugging-html-builds

- packages/gatsby-telemetry/package.json
- yarn.lock
> chore(gatsby-telemetry): upgrade git-up

- packages/gatsby/package.json
- yarn.lock
> chore(gatsby): upgrade multer

- packages/gatsby-plugin-react-helmet/src/gatsby-node.js
Fix typo - modyfing → modifying
> fix(gatsby-plugin-react-helmet): Typo in `onPreInit` warning

- docs/docs/tutorial/part-6/index.mdx
The code snippet in the tutorial had a bug (the path to the component was incorrect).
NA
NA
> chore(docs): Fix path to components in part 6

- packages/gatsby-plugin-mdx/README.md
fix `gatsby-source-filesytem` to `gatsby-source-filesystem` @ line 36
> chore(docs): Fix `gatsby-source-filesystem` typo

- packages/gatsby/src/utils/flags.ts
Fix feature flag for partial hydration. Semver constraint was wrong for experimental react.
> fix(gatsby): fix partial hydration constraints

- packages/gatsby/index.d.ts
Updates URL of the `deleteNode` action doc.
> chore(docs): update url of `deleteNode`

- packages/create-gatsby/src/questions/cmses.json
We didn't install `gatsby-plugin-image` and its deps + didn't add it to the `gatsby-config` 🙈 
[ch55379]
> fix(create-gatsby): Missing "plugins" in cmses.json

- .circleci/config.yml
- e2e-tests/contentful/package.json
- e2e-tests/development-runtime/package.json
- e2e-tests/mdx/package.json
- e2e-tests/path-prefix/package.json
- e2e-tests/production-runtime/package.json
- e2e-tests/themes/package.json
- e2e-tests/trailing-slash/package.json
- e2e-tests/visual-regression/package.json
- integration-tests/artifacts/package.json
- integration-tests/cache-resilience/package.json
- integration-tests/functions/package.json
- integration-tests/gatsby-cli/package.json
- integration-tests/gatsby-pipeline/package.json
- integration-tests/gatsby-source-wordpress/package.json
- integration-tests/head-function-export/package.json
- integration-tests/images/package.json
- integration-tests/long-term-caching/package.json
- integration-tests/node-manifest/package.json
- integration-tests/ssr/package.json
- integration-tests/structured-logging/package.json
- packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts
- packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts
- packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
- packages/gatsby-plugin-mdx/src/remark-path-prefix-plugin.ts
- packages/gatsby/src/utils/webpack/bundle.ts
- yarn.lock
Backporting #36544 to the 4.22 release branch
(cherry picked from commit 2a2489a7b9de0c13b02bb5dd66a9bcb6bea69f76)
> fix: ci pipeline (#36544)

- packages/gatsby/src/redux/actions/restricted.ts
> chore(gatsby): Track when SlicesAPI is used

- packages/gatsby/src/services/initialize.ts
> chore(gatsby): copy edit on initialize.ts comment

- docs/docs/conceptual/react-hydration.md
Remove a mobile link in the doc.
> chore(docs): Swap mobile url for regular url

- docs/docs/conceptual/rendering-options.md
> fix(docs): tiny grammatical correction

- docs/docs/reference/cloud/monorepos.md
Add monorepo docs for recent NX support added to Cloud
- @wardpeet added NX support to Gatsby Cloud in recent weeks
- We should probably add an example at some point (maybe gatsbyjs/gatsby/examples?)
> chore(docs): Update monorepo docs

- packages/gatsby/src/redux/persist.ts
> chore(gatsby): minor typo fix

- e2e-tests/development-runtime/gatsby-script-scripts.js
Maybe fix currently failing CI tests? Switch failing Three.js to cloudflare to hopefully fix that
> chore: Partytown CDN URL

- docs/docs/how-to/testing/visual-testing-with-storybook.md
Updates main.js examples to be consistant.
- partaial code example did not match the relevent code in the full example.
> chore(docs): Update storybook main.js examples to be consistant

- docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
This the migration guide to move from v4 to v5.
> chore(docs): Migration Guide from v4 to v5

- scripts/apply-patches.js
Convenience script since we often need to apply patches locally for work on next major.
N/A
N/A
> chore: Create apply patches script

- packages/gatsby-codemods/README.md
Adds https://github.com/gatsbyjs/gatsby/discussions/36242 to README
> chore(gatsby-codemods): Add `sort-and-aggr-graphql` to README

- packages/gatsby/cache-dir/static-entry.js
> chore: provide slice rendering context to <HTML>

- docs/docs/tutorial/part-2/index.mdx
add exports and imports so that users who are new to React/Javascript can use the example code out of the box
> chore(docs): Tutorial Part 2 - add exports and imports for component example

- docs/docs/how-to/performance/using-slices.md
- docs/docs/reference/built-in-components/gatsby-slice.md
- docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
Fixes some small docs pieces as well as adds information about Slice Queries to slices docs.
[sc-56725]
> chore(docs): Slices docs updates + slice queries

- docs/docs/tutorial/part-2/index.mdx
fix import error introduced in commit 4fb7dcdcc5d24fa560e12b4100d3feaf5a771a71
- #36818 chore(docs): Tutorial Part 2 - add exports and imports for component example
> chore(docs): Tutorial Part 2 - Fix import

- docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
was not caught because apparently navitate is word (to google docs at least)..ablative singular of nāvitās (latin)
> Typo: changed useNavitate to useNavigate

- packages/gatsby/cache-dir/loader.js
- packages/gatsby/cache-dir/production-app.js
- packages/gatsby/cache-dir/slice.js
- packages/gatsby/src/bootstrap/load-config/index.ts
- packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
- packages/gatsby/src/utils/worker/child/render-html.ts
Make partial hydration and slices features work simultaneously.
Check if we have it mentioned anywhere that slices is not enabled when partial hydration is and remove it
[sc-57892]
> feat(gatsby): Slices <> partial hydration interop

- docs/docs/tutorial/part-6/index.mdx
Import Path of Seo component not correct when following the instructions.
> chore(docs): Add import to Seo component in part 6

- packages/gatsby-cli/src/__tests__/handlers/__snapshots__/plugin-add.ts.snap
Change that introduced the need to update snapshots: https://github.com/gatsbyjs/gatsby/pull/36963
> test: update snapshots after adding js codehints to minimal starter

- packages/gatsby/src/query/query-runner.ts
(from code comments)
For static queries we use hash for a file path we output results to.
With automatic sort and aggregation graphql codemod it is possible to have same result, but different query text hashes which would skip writing out file to disk if we don't check query hash as well
Without change like that we get following error after applying codemod on static queries:
```
ENOENT: no such file or directory, open '<site-dir>/public/page-data/sq/d/<new-hash>.json'
```
[ch-58083]
> fix(gatsby): write out sq files when result doesn't change but query hash changes

- docs/docs/how-to/adding-common-features/adding-analytics.md
Use the Google Analytics plugin with recommended gtag.js
> chore(docs): Google Analytics: use gtag.js plugin

- renovate.json5
- scripts/renovate-config-generator.js
Trying to use https://docs.renovatebot.com/configuration-options/#constraints now to fix correct lock file version for https://github.com/gatsbyjs/gatsby/pull/37009
/tableflip
> chore: Add constraints to renovate

- packages/gatsby-cli/src/structured-errors/error-map.ts
- packages/gatsby/cache-dir/slice.js
- packages/gatsby/index.d.ts
Change v5.gatsbyjs.com to gatsbyjs.com in our errors and typedef
> chore: Update internal links to website

- docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
add missing `$Id` argument in the query
> chore(docs): add missing argument

- .circleci/config.yml
Add `esm-in-gatsby-files` integration test to circleci config
[sc-58547]
> test(gatsby): Add esm-in-gatsby-files integration test to circleci config

- packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.ts
> test(gatsby): Make `resolveModuleExports` tests pass

- packages/gatsby/src/schema/node-model.js
While working on https://github.com/gatsbyjs/gatsby/pull/37111 I saw that the docs of some functions could use example. So here I'm adding them
Will improve https://www.gatsbyjs.com/docs/reference/graphql-data-layer/node-model/
> chore(gatsby): Improve node-model docs

- docs/docs/how-to/cloud/working-with-redirects-and-rewrites.md
Place the `createRedirect` into its proper `createPages` API wrapper
> chore(docs): Wrap proxy redirect with createPages

- docs/docs/reference/cloud/monorepos.md
Add pnpm to Cloud monorepos doc
> chore(docs): Add pnpm to Cloud monorepos

- packages/gatsby-plugin-gatsby-cloud/README.md
Updates the README:
- More accurate code blocks
- Up-to-date links
- Clarify how to preload stuff that is imported through webpack
[ch59130]
> chore(gatsby-plugin-gatsby-cloud): Update README

- SECURITY.md
Updating our security policy to reflect the Gatsby 5.x release.
> chore(docs): Update SECURITY.md to reflect supported versions

- docs/docs/reference/built-in-components/gatsby-slice.md
Minor typo fixed.
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-slice/#queries
> chore(docs): fix typo in reference guide

- docs/docs/how-to/testing/visual-testing-with-storybook.md
* changed from -d to --save-dev for better npm support
* added the current configuration on the proper section since the following section just includes this same configuration. I believe this will help newcomers not be so confused when trying to understand how to add storybook to Gatsby
> chore(docs): Update Storybook instructions

- packages/gatsby/package.json
- yarn.lock
Bump partytown dep to latest.
N/A
Resolves https://github.com/gatsbyjs/gatsby/issues/37420
> chore(deps): Bump partytown

- docs/docs/how-to/previews-deploys-hosting/deploying-to-other-services.md
This PR adds **Kinsta Application Hosting** to `other services`.
It's documentation related.
None
> chore(docs): Adds Kinsta Application hosting to other services

- packages/gatsby-source-filesystem/README.md
While working on https://github.com/gatsbyjs/gatsby/pull/37464 I realized that the README could use some much needed love. It's one of the most downloaded plugins to make sure it's a great README :)
[Preview](https://github.com/gatsbyjs/gatsby/blob/docs/filesystem-readme/packages/gatsby-source-filesystem/README.md)
> chore(gatsby-source-filesystem): Improve README

- docs/docs/how-to/cloud/unified-hosting.md
There was some confusion around whether or not Unified Hosting is a separate product. This clears it up!
> chore(docs): Clarify Unified Hosting is built on top of Gatsby Cloud Hosting

- examples/using-remark/src/pages/author.yaml
> chore: Update using-remark example

- packages/gatsby-script/package.json
- packages/gatsby/package.json
- yarn.lock
This is to force updated version containing fix from https://github.com/gatsbyjs/reach-router/pull/11
> chore(gatsby): bump @gatsbyjs/reach-router

- .github/PULL_REQUEST_TEMPLATE.md
Figured "Tests" would be a good addition to the pull request template
> chore: Add "Tests" section to pull request template

- markdown.config.js
- starters/README-template.md
- starters/README.md
- starters/blog/README.md
- starters/default/README.md
- starters/gatsby-starter-minimal-ts/README.md
- starters/gatsby-starter-minimal/README.md
- starters/gatsby-starter-theme-workspace/README.md
- starters/gatsby-starter-wordpress-blog/README.md
- starters/hello-world/README.md
Use "Deploy to Netlify" words in starter READMEs
> chore: Update READMEs to included "Deploy to Netlify"

- packages/gatsby-source-shopify/__tests__/__snapshots__/create-operations.ts.snap
- packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
- packages/gatsby-source-shopify/src/query-builders/products-query.ts
Seems like I made a mistake when querying interfaces in Shopify. This works
> fix(gatsby-source-shopify): Correct interface query

- docs/docs/how-to/adding-common-features/adding-analytics.md
To address https://github.com/gatsbyjs/gatsby/pull/36984/files/f0e87f6202fe1cc568e37b9a7ad2d5e022e67c60
> chore(docs): correct redundant closing brackets in adding-analytics.md

- packages/gatsby-parcel-namer-relative-to-cwd/README.md
- packages/gatsby-parcel-namer-relative-to-cwd/package.json
Addresses https://github.com/gatsbyjs/gatsby/issues/38047
> chore(@gatsbyjs/parcel-namer-relative-to-cwd): Improve README

- packages/gatsby/src/redux/types.ts
Correct Spellings:
https://github.com/search?q=repo%3Agatsbyjs%2Fgatsby+onPreBootstrap&type=code
https://github.com/search?q=repo%3Agatsbyjs%2Fgatsby+onPostBootstrap&type=code
> fix: GatsbyNodeAPI types

- docs/docs/reference/cloud/managing-environment-variables.md
> chore(docs): Update managing-environment-variables.md

- yarn.lock
Fix unit tests like this (plus just using latest db overall is good idea): https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/92203/workflows/2850501b-1ba6-4ad1-94e9-5a1d836e42f8/jobs/1120143/tests#failed-test-0
> chore: bump caniuse-lite

- benchmarks/plugin-manifest/package.json
> chore: add missing angle bracket 

- packages/gatsby/src/utils/webpack/plugins/cache-folder-resolver.ts
This is causing a build error during sourcing for dotcom. The marketing team is trying to update the redirects there.
> fix(gatsby): remove jsx tag from comment

- e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
- e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
> test: adjust adapter e2e tests
