gatsbyjs/gatsby

yarn.lock
A follow-up for #26392 (forgot to include updated `yarn.lock`).
=> fix: update yarn.lock after recent gatsby-source-graphql version bump

docs/starters.yml
Add a portfolio or blog starter with Categories, Typescript, Markdown, and eslint/prettier all preconfigured with SEO best practices. Updated the starters.yml file with the required sections as per [the documentation](https://www.gatsbyjs.org/contributing/submit-to-starter-library/).  Ensured tags are all valid :)
Let me know if I need to change anything
=> chore(starters): add gatsby-typescript-markdown-starter

packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
Yurnalist logger have unexpected output when using `reporter.verbose` (and using `--verbose` flag):
This change result in following output:
---
For reference - this is output when using Ink:
It's not exactly the same (yurnalist seems to add timing informtion, which is quite neat and potentially helpful, but I think it's workable (if anything I would think of adding timing info to ink as well)
=> fix(reporter): add missing verbose/debug log handler to yurnalist logger

docs/docs/gatsby-image.md
Minor change to the section header to reflect how _withWebp is used with a lowercase letter, while _withWebP gives an error
=> Change to lowercase p on 'About withWebP' header

packages/gatsby/src/utils/__tests__/map-templates-to-static-query-hashes.js, packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts, packages/gatsby/src/utils/map-templates-to-static-query-hashes.ts
There are some plugins that traditionally were excluding `.cache` directory from being checked (for example default configuration for `gatsby-plugin-eslint`). With the move to virtual modules, our autogenerated modules ( `(a)sync-requires.js`) where no longer "placed" in `.cache` resulting in quite a lot of problems for `gatsby-plugin-eslint` users. This PR moves autogenerated modules to back to `.cache` (virtually at least), so any custom webpack loaders that were using `.cache` in their configuration work as they did before introducing virtual modules.
Fixes #26393
Fixes #26319
=> fix(gatsby): place auto-generated virtual modules in `.cache`

packages/gatsby-recipes/src/cli/index.js
=> fix(gatsby-recipes): add missing var for the recipes selector

README.md, benchmarks/source-agilitycms/README.md, e2e-tests/development-runtime/README.md, examples/data-fetching/README.md, examples/ecommerce-tutorial-with-stripe/README.md, examples/graphql-reference/README.md, examples/using-MDX/README.md, examples/using-jest/README.md, examples/using-multiple-themes/README.md, examples/using-shopify/README.md, examples/using-square-payments/README.md, examples/using-type-definitions/README.md, packages/gatsby/README.md, starters/README-template.md, starters/README.md, starters/blog/README.md, starters/default/README.md, starters/gatsby-starter-blog-theme-core/README.md, starters/gatsby-starter-blog-theme/README.md, starters/gatsby-starter-minimal/README.md, starters/gatsby-starter-notes-theme/README.md, starters/gatsby-starter-plugin/README.md, starters/gatsby-starter-theme-workspace/README.md, starters/gatsby-starter-theme/README.md, starters/hello-world/README.md
The new change in the official website's domain has broken all the logos, this fixes the logos for all README files
Fixes #26449 for all READMEs
=> chores(docs): #26449 update logo url in all READMEs

docs/contributing/docs-writing-process.md
Replace reference to `gatsby.org` with `gatsby.com` to reflect the merging of the two websites.
Fixes typo in _Docs Writing Process_ doc now that `gatsby.org` and `gatsby.com` have been combined.
Fixes #26426
=> chore(docs): use gatsby.com in doc-writing-process.md

docs/docs/environment-variables.md, docs/docs/refreshing-content.md, www/src/data/sidebars/doc-links.yaml
=> Add refresh content docs

docs/tutorial/part-zero/index.md
Code on L.214 doesn't work on my environment and this behaviour is expected to be common in many other environments.
Indeed, the page https://github.com/gatsbyjs/gatsby/tree/master/starters shows a proper code:
`gatsby new my-blazing-fast-site https://github.com/gatsbyjs/gatsby-starter-hello-world`,
instead of the previous one `gatsby new hello-world https://github.com/gatsbyjs/gatsby/tree/master/starters/hello-world`.
Then I propose the change also on the index.md.
=> fix(docs): revert starter url in tutorial

packages/gatsby/index.d.ts
Export additional TypeScript types. Need those types in https://github.com/vladar/gatsby-graphql-toolkit
Also, we already export `GatsbyGraphQLObjectType`, so exporting other types is consistent with that.
=> chore(gatsby): export gatsby graphql TS types

packages/gatsby-source-shopify/package.json
Fix typo "Shopfiy" in gatsby-source-shopify package description. It looks like this got missed back when the package was originally renamed (https://github.com/angeloashmore/gatsby-source-shopify/commit/66af94a62373800b30d4ee9e1ba48d8948872479) This was the only instance of the typo I found.
=> fix(gatsby-source-shopify): Fix typo "Shopfiy" in package description

docs/contributing/translation/maintainers.md
changes:
- fix 404 link
- #21574 `docs: split up docs templates into different pages`
=> fix(docs): page maintainers -> 404 link

README.md, docs/contributing/docs-contributions.md
fixed old link (gatsbyjs.org) to gatsbyjs.com :smile: 
I was going through the gatsby repository and i came to know that the links in the file hasn't changed. I have changed the old links _gatsbyjs.org_ to _gatsbyjs.com_  
Sorry for the repeated edit of the PR title, its my first time ;-;
=> Fix(README.md): Changed old link gatsbyjs.org to gatsbyjs.com in README.md

.github/workflows/schedule-stale.yml
This adjusts the stalebot workflow to only close stale issues after 60 days (keeping the 20 day labeling). 
We'll further adjust stalebot itself and labeling as part of longer-term adjustments.
[ch13127]
=> chore(stale): extend threshold for stale issues

packages/gatsby-remark-images/src/index.js
As described in #26471, pictures are not shown on Gatsby sites with `pathPrefix` when `gatsby-remark-images` has `withWebp` enabled.
This PR just adds the parameter `{ pathPrefix }` to the args passed to [fluid](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L433) when building `webpFluidResult`, as is done when building `fluidResult` with the main `options` object (built in [line 38](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L38))
Despite not beign oficially documented as a valid param, [gatsby-plugin-sharp](https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp/), makes use of the `pathPrefix` param, as can be [seen](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index …
=> fix(gatsby-remark-images): Use pathPrefix also with WebP files

docs/docs/gatsby-link.md
Will hopefully save people time on issues like [this](https://github.com/gatsbyjs/gatsby/issues/26450).
=> docs(gatsby-link): Clarify that navigate() accepts a pathname, not a full URL.

docs/docs/tailwind-css.md
The link in the doc to "learn more about how to use Tailwind in your CSS" doesn't link to any section in the Tailwind doc. It's probably outdated. This PR fixes that.
=> fix(doc): broken link in tailwind doc

docs/README.md
As everything is moving to gatsbyjs.com I think changing the docs link also to gatsbyjs.com will save many redirects.
Not any as only changing the link in the docs itself.
NA
=> chore: Use gatsbyjs.com instead of gatsbyjs.org for docs

docs/contributing/how-to-open-a-pull-request.md
Removes note in doc describing an avenue for opening a PR no longer available to community contributors (who are no longer Gatsby Maintainers as of August 12th, 2020).
Updates existing doc
Fixes #26429
=> chore(docs): update how-to-open-a-pull-request final note

starters/gatsby-starter-blog-theme-core/README.md, starters/gatsby-starter-blog-theme/README.md
Changed .org links to .com to prevent redirect to new website and resulting to faster loading of website.
=> fix(starters): change .org to .com in links

starters/default/README.md, www/README.md
Changed .org links to .com to prevent redirect to new website and resulting to faster loading of website.
=> fix(starters): change .org to .com

docs/contributing/community.md
Removed Doc part saying auto addition of contributors to organisation as policy has been updated.
As of about a week or two ago, the policy that contributors will be added to organisation after getting there PR merged was removed (See https://www.gatsbyjs.com/blog/2020-08-04-gh-community-permissions-changes-gatsbyjs ). I saw it was still mentioned here.
Fixes #26615
=> chore(docs): removed old info

docs/contributing/code-contributions.md, docs/contributing/community.md, docs/contributing/pair-programming.md, docs/contributing/setting-up-your-local-dev-environment.md, docs/contributing/where-to-participate.md, docs/docs/cheat-sheet.md, docs/docs/gatsby-cli.md, docs/docs/gatsby-magic.md, docs/docs/mdx/plugins.md, docs/docs/mdx/programmatically-creating-pages.md, docs/docs/mdx/writing-pages.md, docs/docs/modifying-a-starter.md, docs/docs/recipes/styling-css.md, docs/docs/seo.md, docs/docs/themes/building-themes.md, docs/docs/themes/getting-started.md, docs/docs/winning-over-content-creators.md, www/README.md
- Removed links to website-contribution doc
- Moved absolute .org links to relative links
- Changed a bunch of .org instances to .com
- Removed note that we auto-invite people to the github org
- Renamed packages to plugins
- Removed a spectrum notice
- Updated the `www` README
=> chore(docs): Unification/doc updates

.github/workflows/schedule-stale.yml
Since the org restructure people can't add those labels themselves anymore.
Part of https://github.com/gatsbyjs/gatsby/issues/26489
=> chore: Remove outdated stale comment

packages/gatsby/src/utils/webpack-utils.ts
I had an issue with consuming a third-party library packaged to ESM with a rollup. They use yaml files for some default configs and rollup bundles them as `module.yml.js`. Imports in distributed code look like this:
```
import ImportName from './module.yml.js'
```
With Gatsby's current webpack config for yaml loader, such import ends up being processed as a yaml module instead of a js module. The proposed change is a no brainer as it simply makes the yaml rule test more strict requiring module paths to end with yaml or yml, just like the rest of the rules Gatsby generates.
=> fix(gatsby): add an end-of-string assert in yaml webpack rule test

packages/gatsby/.npmignore, packages/gatsby/package.json, packages/gatsby/src/__mocks__/gatsby-telemetry.js
By mocking gatsby-telemetry in our tests we see a massive speed increase in our tests. Gatsby telemetry does a lot of things at bootup which we don't want in our tests.
Before:
After:
=> chore(tests): speedup gatsby tests

packages/gatsby-cli/src/reporter/redux/diagnostics.ts, packages/gatsby-cli/src/reporter/redux/index.ts, packages/gatsby-cli/src/reporter/redux/internal-actions.ts, packages/gatsby-cli/src/reporter/redux/reducer.ts, packages/gatsby-cli/src/reporter/redux/types.ts, packages/gatsby-cli/src/reporter/redux/utils.ts
This PR allows to run Gatsby with following env vars (you can use one of those or both or ... well none):
- `GATSBY_DIAGNOSTIC_STUCK_STATUS_TIMEOUT` - to just log information when Gatsby is stuck in `IN_PROGRESS`
- `GATSBY_WATCHDOG_STUCK_STATUS_TIMEOUT` - to terminate the process when stuck in `IN_PROGRESS`
Way it determines wether Gatsby is stuck is by (re)setting timer(s) on every log activity - it might mean log line, it might be `tick()` in progress bar, it might even be things not visible to users (setting activity as pending or using one of those hidden activities that are too fine grained to display in UI).
Few notes about usage:
- when setting env var to a number (just any other than "1" - more about it in a sec) - it will try to use those numbers as timeout delay (but I did add, …
=> feat(gatsby-cli): log what activities prevent from transitioning to idle when stuck

packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
This PR fixes an edge case in Gatsby materialization. The bug shows up when filtering by nested fields of a field with a custom resolver.
See #26056 for full details and my investigation on this bug. Also, the test case in this PR demonstrates a situation when this error occurs.
Fixes #26056
Maybe also #23549
=> fix(gatsby): fix filtering by sub-fields of the field with custom resolver

packages/gatsby-cli/package.json, packages/gatsby-cli/src/reporter/redux/internal-actions.ts, packages/gatsby-plugin-benchmark-reporting/package.json, packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js, packages/gatsby-plugin-sharp/package.json, packages/gatsby-plugin-sharp/src/scheduler.js, packages/gatsby-recipes/package.json, packages/gatsby-source-graphql/package.json, packages/gatsby-source-graphql/src/gatsby-node.js, packages/gatsby-telemetry/package.json, packages/gatsby-telemetry/src/in-memory-store.ts, packages/gatsby-telemetry/src/telemetry.ts, packages/gatsby/package.json, packages/gatsby/src/redux/__tests__/jobsv2.js, packages/gatsby/src/utils/__tests__/jobs-manager.js, packages/gatsby/src/utils/create-node-id.ts, packages/gatsby/src/utils/jobs-manager.ts, yarn.lock
Relevant changelog: https://github.com/uuidjs/uuid#upgrading-from-uuid3x
=> Chore: uuid major upgrade

benchmarks/mdx-without-images/package.json
This sets the semver range for all direct dependencies to the latest minor/patch of the given major. This prevents major breakages while still automatically bumping to the last reasonable version for given packages.
This is for benchmarking only so shouldn't matter to anyone else.
=> chore(benchmarks): set semver to match any patch/minor for most deps

packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
Fixes an error in Gatsby materialization. Before this PR Gatsby fails with the following error when resolving an array of complex values containing nulls:
```
UNHANDLED REJECTION Cannot read property 'internal' of null
```
A test case in this PR demonstrates the situation that causes this issue.
Reported in #23549
=> fix(gatsby): fix materialization edge case with nullish values

packages/gatsby/src/redux/nodes.ts, packages/gatsby/src/schema/__tests__/node-model.js
This PR fixes an error that leaked through in TS conversion in #21010
Also added a regression test.
Fixes #23549
=> fix(gatsby): fix error from ts conversion

packages/gatsby-cli/src/create-cli.ts, packages/gatsby/src/commands/develop.ts
Default arguments in yargs caused to always run node debugger when `gatsby develop` was run. This fixes it.
Fixes https://github.com/gatsbyjs/gatsby/issues/26708
=> fix(gatsby): only enable debugger when argument is given

docs/docs/query-execution.md
Fixed some links to query execution files and rectified the file names .
=> chore(docs):fixed file names and links in query-execution

.gitignore, package.json, scripts/clear-package-dir.js, yarn.lock
I changed clean-scripts directive to use npm-packlist to figure out the right files instead our own logic. This takes care of README.md, package.json, main, ...
=> chore: use npm-packlist to calculate packed files in cleanup-script

packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
Recent spelling update ( https://github.com/gatsbyjs/gatsby/pull/26693 ) caused some snapshots to get out of sync - this sync it back up.
This is just to unblock main branch. Ideally there is follow up to adjust those tests to not snapshot test content of other package's README (or at least some mock package is used, and not package that still receive frequent updates)
=> chore(gatsby-recipes): update snapshot

docs/blog/2019-07-15-theme-jam-contest/index.md, docs/docs/configuring-usage-with-plugin-options.md, docs/docs/naming-a-plugin.md
Fixes 404 links in docs which still pointed to this repo `https://github.com/gatsbyjs/gatsby/tree/master/packages`. Affected themes: gatsby-theme-blog, gatsby-theme-blog-core and gatsby-theme-notes.
This PR points them to the new repo `https://github.com/gatsbyjs/themes/tree/master/packages`.
=> fix(docs): 404 links to gatsby-themes

docs/contributing/translation/maintainers.md
Fix a broken link to the article "How to Write a Reference Guide".
=> Fix a link to the reference guide overview pages

dictionary.txt, docs/blog/2019-02-20-introducing-use-static-query/index.md
This removes "excited.gif" from the dictionary, and replaces "excited.gif" alt text in a blog post's index.md with a more descriptive phrase.
No documentation required for this change.
Addresses #25290.
=> enhancement(docs): Remove excited.gif from the dictionary

docs/docs/visual-testing-with-storybook.md
Add global.__BASE_PATH__ Variable
Adding this prevents the following error message (which appears as soon as you use the Link Component) inside Storybook: 
```
__BASE_PATH__ is not defined
ReferenceError: __BASE_PATH__ is not defined
at getGlobalBasePrefix (http://localhost:6006/vendors~main.469e315f5400e05928a7.bundle.js:91271:3)
at withPrefix (http://localhost:6006/vendors~main.469e315f5400e05928a7.bundle.js:91249:14)
at rewriteLinkPath (http://localhost:6006/vendors~main.469e315f5400e05928a7.bundle.js:91300:33)
at http://localhost:6006/vendors~main.469e315f5400e05928a7.bundle.js:91432:24
at LocationProvider.render (webpack://storybook_docs_dll//Users/shilman/projects/baseline/storybook/node_modules/@reach/router/es/index.js?:203:41)
at finishClassComponent …
```
=> chore(docs): Update visual-testing-with-storybook

.github/workflows/schedule-site-showcase-validator-workflow.yml
The site showcase validator runs against yaml files in this repo. The yaml files are no longer powering the content for the showcase so it's not providing meaningful info. The script is valuable and would be worth re-implementing to test against the WordPress data, but as a short term solution these changes "unschedule" the action by setting it to run on Feb. 31st (a date that doesn't exist).
Related to #26690
=> chore(actions): unschedule showcase validator action

dictionary.txt
change:
- remove unused `runInitialQuerys` from dictionary.txt - word removed in #26680 
- #26680 `chore(docs):fixed file names and links in query-execution`
=> fix(docs): remove unused runInitialQuerys from dictionary.txt

renovate.json5
With gatsbyjs.com living somewhere else, there's currently no need to run Renovate for `www`.
=> chore: Remove `www` from Renovate

dictionary.txt, docs/docs/deploying-to-bip.md, www/src/data/sidebars/doc-links.yaml
Added a short tutorial on how to deploy to [Bip](https://bip.sh). Bip contains automatic framework detection for Gatsby, so this is reflected in the guide. 
An example Gatsby project hosted on Bip is available at https://gatsbyexample.bip.sh, which utilises the [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog)
=> chore(docs): add Deploying to Bip tutorial

docs/docs/migrating-from-v1-to-v2.md
Some typos were found in migrating-from-v1-to-v2.md and they were fixed. This is an internal doc.
This PR links to #26189
=> chore(docs): fix typos in migrating-from-v1-to-v2

benchmarks/gabe-mdx/package.json
Minor cleanup, try to get it consistent with other gabe benchmarks
=> chore(benchmarks): cleanup gabe-mdx package.json

docs/docs/deploying-to-vercel.md
This pull request updates the Deploy to Vercel documentation to use the preferred method of deployment from Vercel, so that users have the best chance of success when deploying.
Current URL is here: https://www.gatsbyjs.com/docs/deploying-to-vercel/
N/A
=> chore(docs): Update Deploy to Vercel documentation

docs/docs/adding-comments.md
At FastComments we've recently launched our React plugin, and have been testing it with Gatsby (which you can see [here](https://github.com/FastComments/fastcomments-gatsbyjs-example)).
I've included the link to the example usage as part of this change.
I thought it would be helpful to add FastComments to the list of supported solutions. :)
=> chore(docs): Adding FastComments to comments doc

packages/gatsby-image/src/__tests__/index.js, packages/gatsby-image/src/index.js
According to the [spec](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element), a `source` tag without the `srcset` attribute is invalid, this small PR makes sure the tag is not rendered in this case.
=> fix(gatsby-image): do not render the source tag if no srcSet is provided

packages/gatsby-dev-cli/README.md
Add missing command to the `gatsby-dev-cli` tool.
I did not find any reference anywhere, so I guess is missing. Please re-recheck my description, which might be not 100% accurate. 
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-dev-cli/README.md
No related issues found
=> chore(docs): add force install command

docs/docs/babel.md
This PR changes the example from [How to use a custom .babelrc file](https://www.gatsbyjs.org/docs/babel/#how-to-use-a-custom-babelrc-file) to use a different plugin, for two reason:
1. The current plugin, optional chaining, is now included in [the default TypeScript setup](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typescript/src/gatsby-node.js)
2. The decorators proposal plugin is commonly used with the `{ legacy: true }` option, which gives the opportunity to include a copy&paste-able example of passing options to a Babel plugin.
=> docs: show how to pass plugin options to Babel

packages/gatsby/cache-dir/api-ssr-docs.js
Improves the example for onRenderBody (https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody),
from:
```
const { Helmet } = require("react-helmet")
exports.onRenderBody = (
{ setHeadComponents, setHtmlAttributes, setBodyAttributes },
pluginOptions
) => {
const helmet = Helmet.renderStatic()
setHtmlAttributes(helmet.htmlAttributes.toComponent())
setBodyAttributes(helmet.bodyAttributes.toComponent())
setHeadComponents([
helmet.title.toComponent(),
helmet.link.toComponent(),
helmet.meta.toComponent(),
helmet.noscript.toComponent(),
helmet.script.toComponent(),
helmet.style.toComponent(),
])
}
```
to:
```
// Object of props
const HtmlAttributes = {
"data-whatever": "content"
}
// Magic
exports.onRenderBody = (
{ setHtmlAttributes }
) => {
setHtmlAttributes(HtmlAttributes)
}
// Output
<html …
```
=> docs(api-ssr-docs): Improve onRenderBody example

docs/contributing/gatsby-governance-model.md
changes:
- fix links `/docs/contributing` -> `/contributing`
- #25390 `Create governance.md`
=> fix(docs): governance model -> fix 404 on internal links

packages/gatsby-plugin-manifest/README.md
I received an error in my browser during a lighthouse audit, wherein an icon listed in the manifest returned a 404 not found. This issue was due to a conflict between the apache websever and gatsby-plugin-manifest. 
I created an issue and had it checked by @marcysutton, who then requested someone created a pull requests to add this short text to the docs for plugin-manifest.
https://github.com/gatsbyjs/gatsby/issues/24764
=> chore(docs): apache troubleshooting section to gatsby-plugin-manifest

docs/docs/location-data-from-props.md
Describes the differences in the `location` object between the client side and server side.
This is my first commit so thankful for feedback on style!
Fixes #21946
=> chore(docs): Documented that location does not include href

packages/gatsby/src/commands/build.ts
=> Add additional logging around conditional page builds

packages/gatsby-cli/src/create-cli.ts, packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx, packages/gatsby-telemetry/package.json, packages/gatsby-telemetry/src/index.ts, packages/gatsby-telemetry/src/telemetry.ts, packages/gatsby-telemetry/tsconfig.json
Add a typegen step to the gatsby-telemetry package, which is already fully converted to TS
=> chore(gatsby-telemetry): Generate typings

packages/gatsby/src/commands/develop.ts
It's a hotfix to remove the uncaught exception thrown on MacOS when `gatsby develop` is run with npm.
This just swallows the error message. It's not a proper fix but it will do for now.
You can test it using `npm install gatsby@lockfile --registry=https://registry.wardpeet.dev`
I could test it with:
1) rm -rf node_modules
1) npm install
1) npm run develop
1) wait until localhost is ready and hit ctrl+c
Fixes #26792
=> fix(gatsby): catch when lock already unlocked

docs/tutorial/wordpress-source-plugin-tutorial.md, integration-tests/gatsby-pipeline/README.md
Removed the word 'simply' to make the tutorial more language inclusive
Related to #18702
=> chore(docs): Remove "simply" wordpress-source-plugin-tutorial

packages/gatsby/src/commands/develop.ts
Console currently prints this error message (#26360):
```text
ERROR 
Looks like develop for this site is already running, can you visit http://://localhost:8000 ? If it is not, try again in five seconds!
```
This tiny PR fixes the URL.
=> fix(gatsby-cli): Fix typo (repeated ://)

peril/README.md
Removed Doc part saying auto addition of contributors to organisation as policy has been updated.
Description
As of now, the policy that contributors will be added to organisation after getting there PR merged was removed (See https://www.gatsbyjs.com/blog/2020-08-04-gh-community-permissions-changes-gatsbyjs ). I saw it was still mentioned here.
related issue: #26615
=> chore: changes according to policy update -> removed old info

packages/gatsby-plugin-page-creator/package.json
Currently it is not possible to build projects using the latest version of the plugin, because the dependency `chokidar` is missing.
```
Error: Cannot find module 'chokidar'
Require stack:
- /home/dev/node_modules/gatsby-plugin-page-creator/watch-collection-builder.js
- /home/dev/node_modules/gatsby-plugin-page-creator/create-pages-from-collection-builder.js
- /home/dev/node_modules/gatsby-plugin-page-creator/create-page-wrapper.js
- /home/dev/node_modules/gatsby-plugin-page-creator/gatsby-node.js
- /home/dev/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
- /home/dev/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /home/dev/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /home/dev/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- …
```
=> fix(gatsby-plugin-page-creator) Add missing chokidar dependency

packages/gatsby-cli/package.json, packages/gatsby-cli/src/reporter/redux/internal-actions.ts, packages/gatsby-plugin-benchmark-reporting/package.json, packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js, packages/gatsby-plugin-sharp/package.json, packages/gatsby-plugin-sharp/src/scheduler.js, packages/gatsby-recipes/package.json, packages/gatsby-source-graphql/package.json, packages/gatsby-source-graphql/src/gatsby-node.js, packages/gatsby-telemetry/package.json, packages/gatsby-telemetry/src/in-memory-store.ts, packages/gatsby-telemetry/src/telemetry.ts, packages/gatsby/package.json, packages/gatsby/src/redux/__tests__/jobsv2.js, packages/gatsby/src/utils/__tests__/jobs-manager.js, packages/gatsby/src/utils/create-node-id.ts, packages/gatsby/src/utils/jobs-manager.ts, yarn.lock
Note: this was a manual revert since github would not let me automate it.
The bump to v8 as applied in #26636 gave us no benefits and are giving problems with imports in certain cases. Maintainers have made it clear they won't offer any support for node 13, which we will want to support for a while as well.
In due time we'll replace this library with something simpler as the maintenance burden will be too high. For now we revert and pin to 3.4.0, the last stable version that does what we want.
Fixes #26812
=> chore(gatsby): revert #26636; and pin uuid to v3.4.0

packages/gatsby-source-filesystem/README.md
Just a minor update to the readme to clarify the usage of the `createFilePath()` `basePath` option.
Fixes: #26470
=> fix(gatsby-source-filesystem) Clarify createFilePath docs

packages/gatsby-recipes/src/providers/gatsby/plugin.js
Recipes load an npm package's readme from unpkg.com. This PR caches this, and also ensures that the returned value for this and the description are always strings. The latter fixes the snapshot errors in #26699
=> fix(gatsby-recipes): Cache readme and always return string

packages/gatsby-plugin-mdx/index.d.ts, packages/gatsby-plugin-mdx/mdx-renderer.js
Removing the components from MDXRenderer based on discussion in https://github.com/gatsbyjs/gatsby/issues/21682
As far as i can see documentation is fine, as https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#mdxprovider already has no mention of 'components'
Fixes #21682
=> fix(gatsby-plugin-mdx): mdxrender should not accept components

packages/gatsby-recipes/src/providers/gatsby/plugin.test.js, packages/gatsby-recipes/src/providers/gatsby/shadow-file.test.js, packages/gatsby-recipes/src/providers/gatsby/site-metadata.test.js, packages/gatsby-recipes/src/test-helper.js
The recipes plugin provider loads package READMEs from upkg.com. It's bad practice (and slow) to load things from the network in unit tests. This PR mocks node-fetch so that it returns a static value for READMEs when testing.
=> tests(gatsby-recipes): Mock loading of readme from unpkg

renovate.json5
Removes prettier from the "packages" group in Renovate. Unblocks #25546, see #26686 for reasoning. prettier remains safe for updating in "starters/examples" since that doesn't break any CI or code.
=> fix(renovate): remove prettier from "packages" group

packages/gatsby/src/state-machines/data-layer/actions.ts, packages/gatsby/src/state-machines/data-layer/index.ts, packages/gatsby/src/state-machines/develop/index.ts, packages/gatsby/src/state-machines/waiting/actions.ts, packages/gatsby/src/state-machines/waiting/index.ts
Previously we were batching node mutations when re-creating pages (i.e. running create pages after a data change), and while running a batch of enqueued mutations triggered in idle state. This was causing problems for MDX, which was having to repeatedly run builds as multiple cascading mutations were triggered and enqueued while rebuilding a page. This changes them to run immediately, meaning cascading actions can run in one go.
=> fix(gatsby): Run actions while recreating pages and draining mutation queue

packages/gatsby/src/state-machines/waiting/index.ts
Fix to ensure that if a node mutation arrives immediately after a file change, it correctly transitions to re-running queries. This was causing updates to go missing in develop for some sites. This fixes the `Warning: Event "xstate.after(1000)#waitingMachine.batchingNodeMutations" was sent to stopped service "waitingMachine". This service has already reached its final state, and will not transition.
Event: {"type":"xstate.after(1000)#waitingMachine.batchingNodeMutations"}` message too.
Related bugs: #26443, #26192, #26839
=> fix(gatsby): Handle node mutations immediately after file change

docs/docs/debugging-the-build-process.md
* Removes `--inspect-brk` flag to address #26708
* Sets `"type": "pwa-node"` to opt into the new Node.js debugger
* Removes `"protocol"`, which does nothing with `"request": "launch"`
* Removes default values for `"autoAttachChildProcesses"` and `"stopOnEntry"`
* Removes `"sourceMaps": false` which no longer seems to be needed
* Adds `"console": "integratedTerminal"` to show Gatsby output in the terminal
=> chore(docs): Fix and simplify VS Code launch.json

packages/gatsby/src/utils/__tests__/test-require-error.ts, packages/gatsby/src/utils/test-require-error.ts
Windows powershell users will come across a false positive because of the double `\\` in file paths. 
More details on this fix here: https://github.com/gatsbyjs/gatsby/issues/17008
And the underlying issue + reproduction here: https://github.com/wesbos/master-gatsby/issues/28
=> Allow for double slashes on windows

packages/gatsby/src/commands/develop.ts, packages/gatsby/src/utils/telemetry-server.ts
As we noticed in #26627, gatsby-telemetry can only run in a node context. In order to add telemetry to Admin we created a HTTP server that exposes the telemetry methods for Admin to POST to in #26832.
This PR starts said telemetry server on `gatsby develop` and stores it as a service for Admin to discover.
=> feat(gatsby): start telemetry server on gatsby develop for Admin

docs/tutorial/building-a-theme.md
Super minor typo, spotted when running through the tutorial
N/A
N/A
=> chore(docs): Minor Typo In Tutorial - Theme-UI Directive

packages/gatsby-telemetry/src/index.ts, packages/gatsby-telemetry/src/service.ts, packages/gatsby/package.json, packages/gatsby/src/commands/develop.ts, packages/gatsby/src/utils/telemetry-server.ts
As we noticed in #26627, gatsby-telemetry can only run in a node context. In order to add telemetry to Admin we need to create a HTTP server that exposes the telemetry methods for Admin to POST to.
=> feat(gatsby): create telemetry service and start it during develop

docs/tutorial/blog-netlify-cms-tutorial/index.md
Fixes #26880
Fixed broken links
=> chore(docs): Fix broken links in blog-netlify-cms-tutorial

packages/gatsby/src/schema/__tests__/build-schema.js, packages/gatsby/src/schema/schema.js
After a discussion with @freiksenet we decided to give second birth to #16928 with a wider scope. This PR allows both plugins and themes to customize the same GraphQL type.
But when they attempt to do so - gatsby will emit a warning so that users knew where to look at in case of conflicts:
```
warn Plugin `foo` has customized the GraphQL type `Bar`, which has already been defined by the plugin `baz`.
```
This is mainly useful for themes.
See discussion in #16529
Fixes #16529
Required for #26854
=> feat(gatsby): merge GraphQL types defined by different plugins (with a warning)

packages/gatsby-admin/src/components/recipes-gui/index.js, packages/gatsby-recipes/package.json, yarn.lock
This switches the dependency on the unmaintained [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch) library, added in https://github.com/gatsbyjs/gatsby/pull/24595, to use [`cross-fetch`](https://github.com/lquixada/cross-fetch).
`isomorphic-fetch` has a dependency on an old version of `node-fetch`, which is currently affected by this security advisory: https://github.com/node-fetch/node-fetch/security/advisories/GHSA-w7rc-rwvf-8q5r
No documentation - only a dependency switch.
Related to #24595
Related discussion: [`694f9e6` (#26709)](https://github.com/gatsbyjs/gatsby/pull/26709/commits/694f9e608e1f8bf2f60fa0d45e563e030d36830b#r480058158)
=> Security: Switch isomorphic-fetch to cross-fetch

renovate.json5
Ran renovate-config-validator and got some errors, these are the new configuration options
=> chore: fix renovate configuration

packages/gatsby/cache-dir/socketIo.js, packages/gatsby/src/utils/webpack.config.js, packages/gatsby/src/utils/websocket-manager.ts
When socket.io is running for a long time or it gets overwhelmed it responds more slowly. This can lead to disconnect cause timeout happen. We do not retry the current inFlight requests which could lead to blank pages.
While at it I also changed the protocols to start with websocket and only send the relevant static queries for a page.
You can try it out `npm install gatsby@socket-resend`
- it makes the timeout larger
- forces websockets on first try
- retries page-data when socket disconnects
- only send relative static-query data per page instead of everything
- correctly treat socket io as external in webpack
=> fix(gatsby): resend pageData when socket disconnect

packages/gatsby-admin/package.json, packages/gatsby-admin/src/components/error-tracker.tsx, packages/gatsby-admin/src/components/providers.tsx, packages/gatsby-admin/src/utils/use-telemetry.tsx, packages/gatsby-telemetry/src/error-helpers.ts, packages/gatsby/src/utils/telemetry-server.ts, yarn.lock
=> feat(gatsby-admin): track errors

packages/gatsby/src/commands/build.ts
Before this PR it would ignore the verbose flag on `gatsby build --verbose`, where `yarn build --verbose` would work. After this PR `gatsby build --verbose` works too.
ht @pieh for the fix, basically :)
=> fix(gatsby-cli): pass --verbose flag to gatsby build properly

e2e-tests/development-runtime/cypress/integration/types/site-data.js, e2e-tests/development-runtime/gatsby-config.js, e2e-tests/development-runtime/src/pages/site-data.js, e2e-tests/production-runtime/cypress/integration/types/site-data.js, e2e-tests/production-runtime/src/pages/site-data.js, packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap, packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js, packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap, packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap, packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap, packages/gatsby/src/schema/__tests__/build-schema.js, packages/gatsby/src/schema/schema.js, packages/gatsby/src/schema/types/built-in-types.ts
An alternative to #26854 (and a follow up for #26864)
It should improve DX for cases when people delete `siteMetadata` from their `gatsby-config`. Before this PR they would've seen the build error: `Cannot query field "siteMetadata" on type "Site"`.
This PR does several things:
1. Moves the `Site` type definition from internal-data-bridge to built-in Gatsby types. 
2. Adds built-in `SiteSiteMetadata` type
3. Adds a way to mark some built-in types as overridable (which suppresses a warning when a plugin tries to provide its own definition for this type)
See #9802 (pretty sure there were other reports about it as well)
=> feat(gatsby): add `Site` and `SiteSiteMetadata` to built-in GraphQL types

packages/gatsby/src/services/create-pages.ts, packages/gatsby/src/services/source-nodes.ts
Prints the node counts as an `info`. In verbose mode also prints a breakdown of the node count per node type.
=> feat(gatsby): print node counts in CLI

e2e-tests/development-runtime/cypress.json, e2e-tests/development-runtime/cypress/integration/functionality/restarting-prompt.js, e2e-tests/development-runtime/cypress/plugins/gatsby-config.js, e2e-tests/development-runtime/cypress/plugins/index.js, packages/gatsby/cache-dir/app.js, packages/gatsby/src/commands/develop.ts, packages/gatsby/src/utils/restarting-screen.ts
In order to make the prompt-to-restart work (#22759), we added a websocket server to the develop parent process that emits certain events. At the time, we decided to make them specific to the use case and have events such as "develop:needs-restart" when certain IPC messages arrived from the child process.
This PR changes it to emit a "structed-log" event that forwards _all_ structured logs. We will need this anyway to show the logs in Admin, and it's cleaner (less custom stuff and more reusability === better!). It also introduces a new structured log that is exclusive to the websocket server to note that the develop process needs to be restarted which looks like this:
```JS
{
type: "LOG_ACTION",
payload: {
type: "DEVELOP",
payload: "RESTART_REQUIRED"
}
}
```
I don't think the naming is …
=> chore(gatsby): expose full structured logs over the develop status websocket server

packages/gatsby/src/state-machines/query-running/actions.ts, packages/gatsby/src/state-machines/query-running/index.ts
In the query running state machine, if a source file is changed while we're running queries we need to go back and extract queries again. In the existing implementation we jump back immediately. However this meant that dirty queries were not run, and then weren't showing as dirty anymore after they were next extracted. This PR changes the behaviour to instead flag the file as dirty, rather than jumping straight to extracting, ensuring that we finish running queries before jumping back to extract any new ones. 
Fixes #26287
=> fix(gatsby): Finish running queries if source files change

packages/gatsby-plugin-manifest/src/__tests__/gatsby-ssr.js, packages/gatsby-plugin-manifest/src/gatsby-browser.js, packages/gatsby-plugin-manifest/src/gatsby-ssr.js
`gatsby-plugin-manifest` adds a `<link>` element to the head (via `gatsby-ssr.js`'s `onRednerBody` export) which links to the `manifest.webmanifest` file that is created during build. In the `href` attribute, Gatsby's `withAssetPrefix` util is used, so as to prefix the file path both with a `pathPrefix` and an `assetPrefix`, if either or both are set. While this is appropriate for other files generated by this plugin (e.g. icon files), it's not appropriate in the case of the manifest file, because Gatsby's core utils run these components through a sanitation step that explicitly and specifically strips away the `assetPrefix` portion of a `<link>`'s `href` if and only if that element has `rel="manifest"`. For reference, see the source code where this sanitation occurs: …
=> Fix gatsby-plugin-manifest using withAssetPrefix in manifest file link, where it gets improperly sanitized

scripts/e2e-test.sh
Gatsby-dev copies files and installs them as well. For e2e we want the same experience as a user would install them. We use --force-install so only an installation is done.
=> chore: use install instead of copy in e2e tests

renovate.json5
Currently Renovate must wait 3 days to check stability of every package. This is a great thing for the most part but causes updates to gatsby-interface and packages within this monorepo (e.g. gatsby-core-utils) to delay all other updates within each Renovate PR. Since Gatsby updates are pushed so frequently, this effectively prohibits the stabilityDays check from ever passing. This PR introduces a rule that removes internal Gatsby packages from the stabilityDays check, allowing Renovate to update gatsby-interface and packages that are sourced from this repo as soon as they are published, while still checking stability for all externally sourced packages.
=> chore(renovate): allow updates to Gatsby packages immediately after publish

packages/gatsby-source-contentful/README.md
Fix gatsby-source-contentful readme typo.
=> chore(gatsby-source-contentful): README typo

docs/tutorial/part-five/index.md
This PR fixes a path to the image on one of tutorial's pages.
=> chore(docs): Set correct path to the image

packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap, packages/gatsby/src/bootstrap/load-plugins/load.ts
Provides an option to disable the automatic set up of `gatsby-plugin-typescript`.
When `gatsby-plugin-typescript` is enabled, it disallows the use of any other Typescript transpiler (with type-checking enabled).  This means that using something like `ts-loader` with Typescript transformer plugins is impossible.  In order to allow this again, `gatsby-plugin-typescript` needs to be disabled.
There were a few options I could see for achieving this:
1. Move the logic that adds `gatsby-plugin-typescript` to the plugin array above `default-site-plugin`.
* :+1: Easiest method for developer.
* :+1: Doesn't add any more surface area to the `gatsby-config` api.
* :-1: While this would allow the default site to filter that plugin out, if it's desired, that process can be laborious and error prone.
* …
=> feat(gatsby): Expose typescript transpiler to default site in plugin list

e2e-tests/development-runtime/cypress/integration/navigation/redirect.js, e2e-tests/development-runtime/gatsby-node.js, e2e-tests/development-runtime/src/pages/redirect-me.js, packages/gatsby/cache-dir/loader.js, packages/gatsby/src/utils/websocket-manager.ts
In the client side loader, if a page in the db is null it is not shown as "not found". This causes an error in some situations with client-side redirects. See #26988 for an example. This returns true for `isPageNotFound` if the page is null. Additionally, it doesn't register a path in websocket manager if it is null, which would otherwise occur in this case with a client-side redirect.
Fixes #26988
=> fix(gatsby): Recognise null pages as not found

e2e-tests/mdx/gatsby-config.js, packages/gatsby-plugin-mdx/utils/gen-mdx.js
Fix a regression where `gatsby-plugin-mdx` fails to pass the file path to remark plugins.
Tested both manually and using the added e2e test.
https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#remark-plugins
Related to #21489
=> fix(gatsby-plugin-mdx): Fix not passing file path to remark plugins

benchmarks/gabe-csv-markdown/.gitignore, benchmarks/gabe-csv-markdown/gen.js, benchmarks/gabe-csv-text/.gitignore, benchmarks/gabe-csv-text/gen.js, benchmarks/gabe-fs-markdown/.gitignore, benchmarks/gabe-fs-mdx/.gitignore
Mostly ignores yarn.lock file
Also fixes how the csv-markdown site generates the csv
=> chore(benchmarks): cleanup the gabe benchmarks a bit

packages/gatsby-plugin-graphql-config/README.md
changes:
- brand name: 
- `gatsby` -> `Gatsby`
- `typescript` -> `TypeScript`
- `graphql` -> `GraphQL`
- `graphql config` -> `GraphQL Config`
- remove `--save` from `npm install`
- unify code snippets: put filename as comment, all same `javascript` tag
- #26829 `chore: write graphql schema, fragments and config file to cache`
=> chore(gatsby-plugin-graphql-config): README typos

yarn.lock
https://github.com/gatsbyjs/gatsby/pull/26689 updated the package.json files but not `yarn.lock`
=> chore: Fix dirty lock file

packages/gatsby-cli/src/init-starter.ts
Addressing [this comment](https://github.com/gatsbyjs/gatsby/pull/26856#issuecomment-698230049) where the new CLI changes are not compatible with yarn 2. If yarn is used for the command, we'll set yarn as the package manager.
=> Fix gatsby-cli changes for yarn2

packages/gatsby-remark-smartypants/README.md
Clarify the plugin this uses, as it uses a retext, rather than remark plugin
=> chore: Update link to retext-smartypants

packages/gatsby-cypress/package.json, packages/gatsby-plugin-coffeescript/package.json, packages/gatsby-plugin-postcss/package.json, packages/gatsby-plugin-sass/package.json, packages/gatsby-plugin-stylus/package.json
Fix the README.md file contents not displaying on the Gatsby plugin library page https://www.gatsbyjs.com/plugins/gatsby-plugin-postcss/
=> fix(docs): remove README.md not displaying on Gatsby plugin library

packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-remark-autolink-headers/src/index.js
gatsby-remark-autolink-headers always use relative positioning. However, this doesn't always work fine. This Pull Request aims to fix this issue and provide relative positioning only when the icon is present.
Fixes #26961
=> fix(gatsby-remark-autolink-headers): option to disable "position: relative" when icon is not present

docs/docs/recipes/working-with-plugins.md
Hello!
I noticed an extra "you" in a sentence from the [Recipes: Working with Plugins](https://www.gatsbyjs.com/docs/recipes/working-with-plugins/) page.
After checking Gatsby's contributing documentation (and the comments in this PR), I think that the PR is fine as it is for such a small change, but I'd be more than happy to modify if it is not!
- https://www.gatsbyjs.com/docs/recipes/working-with-plugins/
- @gatsbyjs/documentation
N/A
=> chore(docs): remove extra "you" (typo)

packages/gatsby-plugin-mdx/README.md
In the section for `MDXProvider`, the `{..props}` was there for the `MyH1` component, but not for the `MyParagraph` component, which would leave the paragraph empty.
=> chore(docs): Add props to MyParagraph

docs/docs/using-web-fonts.md
Fix spelling from `yard` to `yarn` in gatsby [docs/using-web-fonts](https://www.gatsbyjs.com/docs/using-web-fonts/#reach-skip-nav)
=> chore(docs): fix spelling from `yard` to `yarn`

starters/blog/src/pages/index.js
Since posts are a collection of items that are **sorted/ordered** by date, they should be rendered as an ordered list in order to improve the page structure which will help search engines and screen readers to interpreter the content.
```html
<ol>
<li>
<article>…</article>
</li>
</ol>
```
Moved from https://github.com/gatsbyjs/gatsby-starter-blog/pull/202
=> fix(gatsby-starter-blog): Use `ol` for blog post list

packages/gatsby-dev-cli/src/index.js, packages/gatsby-dev-cli/src/watch.js
This is just QoL:
Right now our test script for e2e and integration tests all use `gatsby-dev-cli` to install deps. Next PR in the series will remove `gatsby-cli` dep from https://github.com/gatsbyjs/gatsby/blob/master/integration-tests/gatsby-cli/package.json which would make our test setup just not install anything currently (even `jest`).
---
This is part of PR series:
1. [`feat(gatsby-dev-cli): install deps if there are no gatsby deps but --forceInstall was used`](https://github.com/gatsbyjs/gatsby/pull/27055) __(THIS PR)__
2. [`test(integration/gatsby-cli): use sandboxed directory to "globally" install gatsby-cli`](https://github.com/gatsbyjs/gatsby/pull/27056) 
3. [`chore(gatsby-recipes): bundle dependencies`](https://github.com/gatsbyjs/gatsby/pull/27057)
4. [`chore(gatsby-cli): …
=> feat(gatsby-dev-cli): install deps if there are no gatsby deps but --forceInstall was used

packages/gatsby-plugin-google-tagmanager/src/__tests__/__snapshots__/gatsby-ssr.js.snap, packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js
This PR makes the official Google Tag Manager plugin WCAG compliant. Various tools are pointing out that `iframe` without a `title` attribute violates the accessibility requirements. However, it doesn't make sense to include a title because Google Tag Manager's iframe is used in headless mode. So I'm adding `aria-hidden="true"` instead. 
This was verified by running an audit using [SortSite](https://www.powermapper.com/products/sortsite/).
**Before:**
**After:**
Resources:
- https://webaim.org/techniques/frames/
- https://www.w3.org/TR/WCAG20-TECHS/H64.html
=> fix(gatsby-plugin-google-tagmanager): Add "aria-hidden"

.circleci/config.yml
Currently bootstrap and typecheck tests aren't run unless there are changes in the `packages` directory. This means changes to the top-level yarn.lock are ignored. This causes errors like those in #27077 to be missed.
=> tests: run CircleCI tests when only yarn.lock changes

packages/gatsby-telemetry/README.md, packages/gatsby-telemetry/src/index.ts
- Exports some Typescript types
- `trackCli` is not a very good name for capturing an event. Adding a method called `captureEvent` doing the same thing as trackCli
In the readme (inside the file modified)
=> fix(gatsby-telemetry): export Typescript types, add captureEvent method

packages/gatsby-source-contentful/src/extend-node-type.js
This PR adds the .base64 file extension to all files created in the "remote_cache" directory (.cache/remote_cache/images)
We noticed when using Azure WebApps (Linux based) where we host preview server(s) using the instructions on [Running a Gatsby Preview Server](https://www.gatsbyjs.org/docs/running-a-gatsby-preview-server/) (Which are docker containers under the hood) we get alot of " no such file or directory, open '.cache/remote_cache/images/80f[0m  [0m[97m[41mcfcfd88d0e8d6272c698ab6dc2257c192c4b9'[0m" (Please ignore the color codes included in the logging, this is not the issue currently)
When you try to remove/access the file via one of the methods (viewing it on ssh/remote or via FTP) you also get an access denied errors and/or file not found. 
Since i noticed it was using …
=> fix(gatsby-source-contentful): Add file-extension to remote cached items

packages/gatsby-plugin-catch-links/src/__tests__/catch-links.js, packages/gatsby-plugin-catch-links/src/catch-links.js
In some browsers like Internet Explorer, Samsung Internet and Chrome Android, Opera Mini (see https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString), SVGAnimatedString is not available. This produces a runtime UndefinedVariableError.
I propose we check if `SVGAnimated` is available in `window` before checking if `clickedAnchor.href` is an instance of it.
=> Fix(gatsby-plugin-catch-links): SVGAnimatedString may not be available in some browsers.

.circleci/config.yml
Since we merged .org and .com and moved the code to a private repository there's no use in running the tests for `www`.
=> chore(circleci): Remove unit tests for www

packages/gatsby-plugin-static-image/src/get-custom-sharp-fields.ts, packages/gatsby-plugin-static-image/src/image-processing.ts, packages/gatsby-plugin-static-image/src/utils.ts
`webP` and `tracedSVG` weren't handled since they were implemented in custom resolvers in `gatsby-transformer-sharp` which is bypassed by this static image plugin. 
This takes the implementation there and roughly copies it into this plugin.
_There are likely some issues with TypeScript and a few TODOs that I left commented but I was trying to get something up before my end of day since I'll be gone tomorrow, Oct 1st_ 🙂 
https://github.com/gatsbyjs/gatsby/pull/26924#issuecomment-701435232
=> fix(gatsby-plugin-static-images): add missing static image fields

integration-tests/gatsby-cli/__tests__/new.js, integration-tests/gatsby-cli/jest.boot.js, integration-tests/gatsby-cli/jest.config.js, integration-tests/gatsby-cli/package.json, integration-tests/gatsby-cli/test-helpers/invoke-cli.js, scripts/e2e-test.sh
Relies on https://github.com/gatsbyjs/gatsby/pull/27055
This installs gatsby-cli in some `/tmp` directory and let tests use that installation to invoke global gatsby-cli commands.
Those changes are looking to catch problems like https://github.com/gatsbyjs/gatsby/issues/26919 which was not caught by any automatic testing (it worked on CI because executed gatsby-cli was in nested monorepo directory so it had access to all `node_modules` which did hide some problems)
---
This is part of PR series:
1. [`feat(gatsby-dev-cli): install deps if there are no gatsby deps but --forceInstall was used`](https://github.com/gatsbyjs/gatsby/pull/27055)
2. [`test(integration/gatsby-cli): use sandboxed directory to "globally" install gatsby-cli`](https://github.com/gatsbyjs/gatsby/pull/27056) __(THIS …
=> test(integration/gatsby-cli): use sandboxed directory to "globally" install gatsby-cli

package.json, yarn.lock
Upgrade danger to use the new GitHub token API, as it was removed yesterday.
=> chore: update peril bot

docs/docs/mdx/plugins.md, packages/gatsby-remark-images/README.md, packages/gatsby-remark-images/src/__tests__/index.js, packages/gatsby-remark-images/src/constants.js, packages/gatsby-remark-images/src/index.js
add a keyword `GATSBY_EMPTY_ALT` to enable that an img tag with an empty alt attribute can be created
add the keyword description @gatsbyjs/documentation
Fixes #20179
=> fix(gatsby-remark-images): enable creating img tag with empty alt attribute

peril.settings.json
After `peril` upgrade we noticed problems with merge-on-green that consistently fails because required environment variables are not passed to it. Until the problem is fixed, let's disable this automation because it just doesn't work right now and can cause confusing CI check failures. 
Issue (and potential upstream fix) in peril (for tracking purposes) - https://github.com/danger/peril/issues/474
=> chore(peril): disable merge-on-green

packages/gatsby-remark-embed-snippet/README.md
=> chore(gatsby-remark-embed-snippet): Add prismjs install

docs/docs/deploying-to-netlify.md
- move "Continuous deployment" under "Git repository setup" because continuous deployment is only possible with a Git repository
- add secondary default branch for deployment as `main`
=> chore(docs): Update deploying-to-netlify

packages/gatsby-image/README.md
DatoCMS nowadays support GatsbyDatoCmsFluid_tracedSVG and GatsbyDatoCmsFixed_tracedSVG fragments so I have added it to the doc.
Fixes #27288
=> chore(gatsby-image): Add more DatoCMS fragments

docs/docs/global-css.md
On line 13, the link to index.js points to a commit from 2018.  The link is there to demonstrate how a Layout component is implemented, and this implementation has changed from 2018 to 2020.  For me, the way it's done in the latest commit is much easier to understand.
Also, when I clicked on the link from documentation, at first I didn't realize that I wasn't looking at the latest commit and it caused a bit of confusion for me.
Not sure if you want to link to the [commit on May 28th, 2020:](https://github.com/gatsbyjs/gatsby-starter-default/blob/e1e2a960f8a54e2a1234d1694d390b1cc26b7947/src/pages/index.js#L9) 
Or just link to the [latest commit:](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/pages/index.js#L9) 
In the proposed change, I updated the link to the May 28th …
=> chore(docs): Update the link to global css example

packages/gatsby/src/commands/develop-process.ts
We track `pagesCount` for builds ( https://github.com/gatsbyjs/gatsby/blob/7bf2bdbf0de545db7c8a1b540cfffb0641a7137a/packages/gatsby/src/commands/build-html.ts#L118-L120 ), but we don't do it for `gatsby develop`.
This is needed to prepare potential calculations around real world savings that users could see from implementing https://github.com/gatsbyjs/gatsby/issues/7348 - because number of pages is huge factor currently that impact time to boot up dev server, doing any analisys without bucketing by site page size wouldn't be able to provide needed nuanced information of potential impact.
=> chore(gatsby): track number of pages in develop sessions

packages/gatsby/cache-dir/app.js
Fixes #27294
Should only affect `gatsby develop` when using `--https`
=> fix(gatsby): support protocol relative link when using `--https` in develop

packages/gatsby-plugin-mdx/gatsby/on-create-page.js, packages/gatsby-plugin-mdx/utils/create-mdx-node.js, packages/gatsby-plugin-mdx/utils/extract-exports.js
Fixes https://github.com/gatsbyjs/gatsby/issues/26446
Apparently Babel had a breaking requirement for directly calling `babel.transform` and this dependency bump causes our MDX plugin to now trigger this fatal in Babel.
=> fix(gatsby-plugin-mdx): babel.transform requires filename field now

docs/docs/client-only-routes-and-user-authentication.md
In "[Client-only Routes & User Authentication](https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/#adjusting-routes-to-account-for-authenticated-users)" doc page, a code example include this import directive:
`import React, { Component } from "react"`
I think that `Component` should not have been imported here.
A `Component` variable name is next used in the example, but it is as renamed destructured prop.
Not as an imported component.
=> Remove extraneous import

packages/gatsby-plugin-preact/package.json, packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js, packages/gatsby-plugin-preact/src/gatsby-node.js, yarn.lock
Seems like we didn't have the correct deps in package.json and we didn't use the correct lifecycle to add a babel plugin.
Fixes #27151
=> fix(gatsby-plugin-preact): add babel-plugin properly

packages/gatsby-plugin-mdx/README.md
Document the usage of configuration options in `remarkPlugins` and `rehypePlugins` with `gatsby-plugin-mdx`.
This PR is docs-only.
https://github.com/gatsbyjs/gatsby/issues/15826
=> chore(gatsby-plugin-mdx): Add config to remark and rehype plugins examples

packages/gatsby/src/bootstrap/redirects-writer.ts, packages/gatsby/src/query/redirects-writer.ts
We found that the redirect section of our app bundle was 1MB parsed size, this was somewhat non-ideal. This PR removes some data that is unnecessary for the browser to be aware of, to slim down the size of the bundle. The browser doesn't need to know if a redirect should work on the browser, as *all* of the ones in the file should work in the browser. As for permanent redirects, there is no such thing as a permanent or temporary redirect to the browser.
This change took our redirect file from 1MB to 400kB. This is a 60% improvement for realistically no problem.
=> perf(redirect): minified redirect file size

.prettierignore
This solves an issue where tests couldn't be run locally because the linter failed. This change adds the following two directories to `.prettierignore`:
* `packages/gatsby-admin/public`
* `packages/gatsby/gatsby-admin-public`
N/A
For additional context: Without this change, when I clone the repo and run `yarn bootstrap` and then `yarn test` locally from the root directory, I see the following error:
```
packages/gatsby-admin/public/styles.24bf1742e3764eb5de3c.css
packages/gatsby/gatsby-admin-public/styles.24bf1742e3764eb5de3c.css
Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prettier: `prettier "**/*.{md,css,scss,yaml,yml}" "--check"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prettier script.
npm …
```
=> fix: add gatsby-admin public folders to prettierignore

peril.settings.json
Enable merge on green after fix of https://github.com/danger/peril/pull/475
=> Revert "chore(peril): disable merge-on-green"

e2e-tests/development-runtime/cypress/integration/navigation/linking.js, e2e-tests/development-runtime/cypress/support/commands.js, e2e-tests/development-runtime/src/pages/page-2.js, packages/gatsby/cache-dir/navigation.js
Rendering is occurring before `onPreRouteUpdate` when it should be after.
Please see Issue https://github.com/gatsbyjs/gatsby/issues/26608 for a full description.
Fixes https://github.com/gatsbyjs/gatsby/issues/26608
=> fix(gatsby): route lifecycle ordering

packages/gatsby-plugin-page-creator/src/gatsby-node.ts
The changed code was doing `.has` and `.filter` on a purely informational data structure. This is a Set.
Should improve perf a little bit at scale for certain sites (linear search through 100k elements is not fun. Doing a `.filter` just to remove one element even worse.)
~Open question: in `develop`, how often is this lifecycle called? Because I don't think the `watchDirectory` is torn down. Does that mean we're creating more and more chokidars if a site uses this path at all?~ Yeah, should only be called once.
=> perf(gatsby-plugin-page-creator): use set for tracking existing files

e2e-tests/development-runtime/cypress/integration/unified-routing/client-side-routes.js, e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js, e2e-tests/development-runtime/cypress/support/commands.js, e2e-tests/development-runtime/gatsby-node.js, e2e-tests/development-runtime/src/pages/client-dynamic-route/named-splat/[...name].js, e2e-tests/development-runtime/src/pages/client-dynamic-route/products/[brand]/[product].js, e2e-tests/development-runtime/src/pages/collection-routing/index.js, e2e-tests/development-runtime/src/pages/collection-routing/root.js, e2e-tests/development-runtime/src/pages/collection-routing/{FakeData.uuid}.js, e2e-tests/development-runtime/src/pages/collection-routing/{ImageSharp.parent__(File)__name}.js, e2e-tests/development-runtime/src/pages/collection-routing/{MarkdownRemark.fields__slug}.js, packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts, packages/gatsby-plugin-page-creator/src/__tests__/get-match-path.ts, packages/gatsby-plugin-page-creator/src/derive-path.ts
The overall mission is to look through all tests and see if they work as intended and cover all use cases.
- Replaced the old logic of `getTestElement` with `findByTestId`
- Also assert the correct route (that helped with catching a bug)
- Bug found: The `/` replacement for slugs like `/my-slug/` didn't work and left the url in `replaced-my-slug-replaced` state
- Add some more E2E and unit test cases
[ch16062]
=> fix(gatsby-plugin-page-creator): Update Route API tests & Fix slash replacement

packages/gatsby-cli/src/reporter/redux/internal-actions.ts, packages/gatsby-cli/src/reporter/redux/types.ts, packages/gatsby-cli/src/structured-errors/error-map.ts
Add category for `USER` on plugin validation errors.
Also fixes the paths for imports, which fixes https://github.com/gatsbyjs/gatsby/issues/27339
=> fix(gatsby-cli): Categorize plugin validation error

packages/gatsby-cli/src/init-starter.ts
Fixes https://github.com/gatsbyjs/gatsby/issues/27338
Steps to reproduce :
1. Uninstall yarn
2. Verify that PackageManager is setted to 'yarn' in config.json
3. Run gatsby-cli new
It failed with
```
ERROR
Command failed with ENOENT: yarnpkg
spawn yarnpkg ENOENT
Error: Command failed with ENOENT: yarnpkg
spawn yarnpkg ENOENT
- child_process.js:268 Process.ChildProcess._handle.onexit
internal/child_process.js:268:19
- child_process.js:464 onErrorNT
internal/child_process.js:464:16
- task_queues.js:80 processTicksAndRejections
internal/process/task_queues.js:80:21
```
=> Remove async statement around sync function

benchmarks/gabe-csv-markdown/gatsby-node.js, benchmarks/gabe-csv-text/gatsby-node.js, benchmarks/gabe-fs-markdown/gatsby-node.js, benchmarks/gabe-fs-mdx/gatsby-node.js, benchmarks/gabe-fs-text/gatsby-node.js, benchmarks/gabe-json-text/gatsby-node.js, benchmarks/gabe-yaml-text/gatsby-node.js
This happened as I changed the `edges` to `node` and cloned the result to all these benchmarks.
ht @LekoArts for reporting
=> fix(benchmarks): dont access .node because its already a node

packages/gatsby/src/query/query-watcher.ts
Migration of `gatsby/src/query/query-watcher.js` to TypeScript
Related to https://github.com/gatsbyjs/gatsby/issues/21995#issuecomment-704254164
=> chore(gatsby): Migrate query-watcher to ts

packages/gatsby-plugin-google-analytics/src/gatsby-node.js, packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
`trackingId` wasn't a mandatory option before schema validation. We need to keep this behaviour until a major release goes out.
Credits to @wardpeet.
Relates to https://github.com/gatsbyjs/gatsby/pull/27242
=> fix(gatsby-plugin-google-analytics): remove required on trackingId

packages/gatsby-plugin-utils/src/test-plugin-options-schema.ts, packages/gatsby/index.d.ts, packages/gatsby/src/bootstrap/load-plugins/validate.ts
As discussed in #27242, the type for `pluginOptionsSchema` in the `GatsbyNode` interface should be optional, so not everybody who configures their Gatsby nodes needs to define it.
Maybe there should be a separate interface, so every plugins eventually defines their schema, but this is up to another PR after the discussion.
See #27242
See #27242
=> fix(gatsby): Make pluginOptionsSchema optional

packages/gatsby-plugin-sitemap/package.json, packages/gatsby-plugin-sitemap/src/gatsby-node.js
Adds options schema for gatsby-plugin-sitemap. Includes external validator for the query syntax.
=> chore(gatsby-plugin-sitemap): Add options schema

packages/gatsby-plugin-sharp/src/gatsby-node.js
As per #27370, wrap the export in a conditional so old Gatsby versions don't complain
=> chore(gatsby-plugin-sharp): Wrap pluginOptionsSchema in env conditional

e2e-tests/development-runtime/cypress/integration/hot-reloading/page-queries.js, e2e-tests/development-runtime/src/pages/page-query.js, packages/gatsby/src/state-machines/query-running/index.ts
This PR fixes a problem with hot-reloading of page query results. Before this PR updated queries were not executed after extraction and were only executed on a subsequent update of the page component.
The correct flow for query running is:
1. Extract queries from updated components
2. **Enqueue extracted queries for execution**
3. Execute dirty queries (including enqueued extracted queries)
But we had this instead:
1. Extract queries from updated components
2. Execute dirty queries (including enqueued extracted queries)
3. **Enqueue extracted queries for execution**
The culprit is `setTimeout` here which triggers enqueuing too late:
https://github.com/gatsbyjs/gatsby/blob/961f3d5fbf7103512a8b200ecbafde82a881f9a9/packages/gatsby/src/redux/machines/page-component.ts#L132-L139
So when we run …
=> fix(gatsby): wait for extracted query enqueuing before running queries

packages/babel-preset-gatsby/README.md
- previously it pointed to an actual package, however, there is no such
package and so this link 404'd
- looking through the blames, this seems to be a plugin implemented
within preset-gatsby itself, not as a separate package
- point to correct location there instead
- would probably be good to have a separate package for it though!
I stumbled upon `babel-preset-gatsby` a few weeks ago while looking for how other large projects handle Babel configs to get some ideas for TSDX (particularly https://github.com/formium/tsdx/issues/383#issuecomment-705965398 / https://github.com/formium/tsdx/issues/634) and found this plugin that I had never heard of, but then hit a 404. Took the time to fix that 404 today!
It's a docs PR itself!
#19943 is the original proposal. …
=> chore(babel-preset-gatsby): fix broken link to optimize-hook-destructuring

packages/gatsby-plugin-postcss/src/__tests__/__snapshots__/gatsby-node.test.js.snap, packages/gatsby-plugin-postcss/src/gatsby-node.js
This is a proposed fix for https://github.com/gatsbyjs/gatsby/issues/27417, which I just reported with a more detailed description of the problem itself.
The issue appears to be this line of `gatsby-plugin-postcss`: https://github.com/gatsbyjs/gatsby/blob/3a3c3e7f0942578b5ee113056d4883c7c277bdd3/packages/gatsby-plugin-postcss/src/gatsby-node.js#L33
The `postcssOptions` object is being used with the spread (`...`) syntax, meaning that its properties are being included directly to the object literal passed to the `options` property of the PostCSS loader. This means that the `options` property evaluates to `{ sourceMap: !isProduction, plugins: [/* plugin objects */] }`.
This is invalid because the [postcss-loader](https://github.com/webpack-contrib/postcss-loader#options) only accepts three …
=> fix(gatsby-plugin-postcss): Add required additional level of nesting for postcss-loader options.

packages/gatsby/src/utils/validate-page-component.ts
The error 11328 expects a `context.fileName` but only `context.component` was passed until now. This was changed in https://github.com/gatsbyjs/gatsby/commit/64858b12b34a3fab45b1bb06a6b65803231569e2
With this the path is printed again:
Fixes https://github.com/gatsbyjs/gatsby/issues/27410
=> fix(gatsby): Error context for 11328

packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
This PR ensures that if a field has a custom resolver we always use it in materialization (and only read a field value directly when there is no resolver)
It fixes another edge case with materialization. See #27368 for a detailed explaination.
Fixes #27368
=> fix(gatsby): materialization should always use resolver when defined

packages/gatsby-transformer-remark/package.json, packages/gatsby-transformer-remark/src/__tests__/gatsby-node.js, packages/gatsby-transformer-remark/src/gatsby-node.js
Add plugin schema options in `gatsby-transformer-remark`
Relates to https://github.com/gatsbyjs/gatsby/pull/27242 and https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/
=> chore(gatsby-transformer-remark): add pluginOptionsSchema export

packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
Adds a schema for `gatsby-plugin-google-tagmanager`
=> chore(gatsby-plugin-google-tagmanager): Add schema

packages/gatsby-plugin-netlify/package.json, packages/gatsby-plugin-netlify/src/__tests__/gatsby-node.js, packages/gatsby-plugin-netlify/src/gatsby-node.js
Add plugin options schema to gatsby-plugin-netlify.
- [The plugin documentation](https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify)
- Relates to https://github.com/gatsbyjs/gatsby/pull/27242
Here are the potential options to pass to the plugin:
```javascript
plugins: [
{
resolve: `gatsby-plugin-netlify`,
options: {
headers: {}, // option to add more headers. `Link` headers are transformed by the below criteria
allPageHeaders: [], // option to add headers for all pages. `Link` headers are transformed by the below criteria
mergeSecurityHeaders: true, // boolean to turn off the default security headers
mergeLinkHeaders: true, // boolean to turn off the default gatsby js headers
mergeCachingHeaders: true, // boolean to turn off the default caching headers
transformHeaders: (headers, …
```
=> chore(gatsby-plugin-netlify): add pluginOptionsSchema export

packages/gatsby-plugin-postcss/src/gatsby-node.js
This is a followup to https://github.com/gatsbyjs/gatsby/pull/27418, where I realized that my fix didn't completely fix the problem. See [this comment of mine](https://github.com/gatsbyjs/gatsby/pull/27418#issuecomment-707936348) that describes the issue in a bit more detail.
The steps for reproducing are still the same as https://github.com/gatsbyjs/gatsby/issues/27417, and the error message is still the same, but the internal data structures in the code are a little bit different than before.
In this PR, I have restored the `delete` statement back to what it was previously, since I think it was intentionally trying to delete the property at the outer level and not the inner level. I don't feel that I understand why this is happening, so I'd appreciate some input on whether this is the …
=> fix(gatsby-plugin-postcss): Delete invalid plugins property from outer options object.

packages/gatsby-source-contentful/src/gatsby-node.js
This adds an experimental flag that, when used, uses `v8.serialize()` to store the data received by Contentful verbatim to the file passed on with it. In subsequent calls, if the requested file exists it will attempt to load the data from that file, verbatim. 
Using this tool should no longer require Contentful authentication after the first time and allow people like me to debug and profile large sites properly without triggering Contentful's rate limiter (not to mention I don't care about the remote time spent in my tests and don't want to wait for it either).
```
GATSBY_CONTENTFUL_EXPERIMENTAL_FORCE_CACHE=contentful_remote_cache gatsby build --verbose
```
=> feat(gatsby-source-contentful): add tool to force-cache remote data to debug

packages/gatsby-cli/src/reporter/reporter.ts, packages/gatsby-cli/src/structured-errors/error-map.ts
I cherry-picked this commit from a WIP branch in which I used `setErrorMap` in a gatsby-node.ts file (a plugin). TS complained about my usage of e.g. `type: "ERROR"` as it expected an enum. For the `id` it would also be wrong to propose our internal set of IDs as we don't want people to use the exact same ones, thus I simply changed it to a `string`.
=> chore(gatsby-cli): Change `setErrorMap` & `IErrorMapEntry` type

packages/gatsby-plugin-offline/package.json, packages/gatsby-plugin-offline/src/__tests__/gatsby-node.js, packages/gatsby-plugin-offline/src/gatsby-node.js
Add plugin schema options in `gatsby-plugin-offline`
Relates to #27242 and https://www.gatsbyjs.com/plugins/gatsby-plugin-offline/
=> chore(gatsby-plugin-offline): add pluginOptionsSchema export 

packages/gatsby-remark-images/.gitignore, packages/gatsby-remark-images/package.json, packages/gatsby-remark-images/src/__tests__/gatsby-node.js, packages/gatsby-remark-images/src/gatsby-node.js
Add plugin schema options in `gatsby-remark-images`
Relates to #27242 and https://www.gatsbyjs.com/plugins/gatsby-remark-images/
=> chore(gatsby-remark-images): add pluginOptionsSchema export

packages/gatsby-plugin-sitemap/README.md
Updated defaultOptions line number in README.md link
N/A
N/A
=> chore(gatsby-plugin-sitemap): Update defaultOptions line number

.eslintignore, .prettierignore
Until we remove the `www` folder (or do something with it) it's not necessary to run ESLint/Prettier on it and fix things. Will help with https://github.com/gatsbyjs/gatsby/pull/27159 as unnecessary errors go away.
=> chore: Update ignore files

packages/gatsby-source-contentful/src/gatsby-node.js
Before it was doing a `.includes` on an array, searching for a particular sys.id. But that list could potentially have thousands of elements.
By this changes it creates a single `Set` of deleted ids, which has a much better lookup time, and can be used by both loops.
=> perf(gatsby-source-contentful): dont linear search on a maybe large set

packages/gatsby-source-contentful/src/normalize.js
Had a case where this function was called with n=96 m=73529 . The old code would 96x filter the list of 73k elements. The new code buckets it once.
Before it would take 650ms, after it takes 31ms. Not a major win in absolute time but massive win in relative perf.
=> perf(gatsby-source-contentful): change O(n*m) loop to O(n+m)

packages/gatsby-plugin-mdx/__tests__/gatsby-node.js, packages/gatsby-plugin-mdx/gatsby-node.js, packages/gatsby-plugin-mdx/package.json
Add plugin schema options in `gatsby-plugin-mdx`
Relates to #27242 and https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx
=> chore(gatsby-plugin-mdx): add pluginOptionsSchema export

packages/gatsby/src/utils/webpack-utils.ts
Make sure we only make it a default for react 17+. Not all libraries have moved to support automatic mode.
Related #26652
=> fix(gatsby): add runtime check for react 17

e2e-tests/README.md
Fwiw, this worked for me to reproduce a problem uncovered on CI where the existing instructions did not.
=> docs(e2e-tests): add alternative hint of running the e2e tests

packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap, packages/gatsby-cli/src/reporter/redux/internal-actions.ts, packages/gatsby-cli/src/reporter/redux/types.ts, packages/gatsby-cli/src/structured-errors/error-map.ts, packages/gatsby-cli/src/structured-errors/types.ts
Categorize a first set of errors that I'm pretty sure are all ErrorCategory.USER.
=> chore(gatsby-cli): Categorize errors

packages/gatsby-plugin-image/README.md, packages/gatsby-plugin-image/src/babel-plugin-parse-static-images.ts, packages/gatsby-plugin-image/src/components/static-image.server.tsx
Now that we have published the alpha, we know the minimum supproted version of Gatsby. This PR updates the README and error messages to reflect this.
=> chore(gatsby-plugin-image): Update now we know min gatsby version

packages/gatsby-plugin-page-creator/src/gatsby-node.ts
Fixes a bug reported here: https://github.com/gatsbyjs/gatsby/issues/26375#issuecomment-708940572
We [camelcase the type](https://github.com/gatsbyjs/gatsby/blob/c76ab29a8c28ce8449fbca4a6b4566164d8ed469/packages/gatsby/src/schema/schema.js#L242) for our queryAll, so for checking against it we'll also need to do this here :)
=> fix(gatsby-plugin-page-creator): Use correct queryAll name

.eslintrc.js
To be used in https://github.com/gatsbyjs/gatsby/pull/27442
=> chore: allow `unstable_` for API prefix

docs/docs/configuring-usage-with-plugin-options.md, packages/gatsby/src/utils/api-node-docs.ts
This improves the documentation for the new `pluginOptionsSchema` Node API (introduced in #27166 and #27242) and adds a section about it to the existing "Configuring Plugin Usage with Plugin Options" doc.
[ch15947]
=> docs: document pluginOptionsSchema

e2e-tests/development-runtime/content/error-recovery/page-query.json, e2e-tests/development-runtime/content/error-recovery/static-query.json, e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/compile-error.js, e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/page-query-result-runtime-error.js, e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/query-validation-error.js, e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/runtime-error.js, e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/static-query-result-runtime-error.js, e2e-tests/development-runtime/cypress/support/commands.js, e2e-tests/development-runtime/gatsby-config.js, e2e-tests/development-runtime/package.json, e2e-tests/development-runtime/scripts/update.js, e2e-tests/development-runtime/src/pages/error-handling/compile-error.js, e2e-tests/development-runtime/src/pages/error-handling/page-query-result-runtime-error.js, e2e-tests/development-runtime/src/pages/error-handling/query-validation-error.js, e2e-tests/development-runtime/src/pages/error-handling/runtime-error.js, e2e-tests/development-runtime/src/pages/error-handling/static-query-result-runtime-error.js, packages/gatsby/cache-dir/error-overlay-handler.js, packages/gatsby/package.json, yarn.lock
This adds crude recovery mechanism: once runtime error was found attach listeners to refresh the browser on either webpack update or data update.
Recently we fixed queueing of query running when editing query text ( https://github.com/gatsbyjs/gatsby/pull/27408 ). However in runtime when users update query and component at the same time, runtime can get in error state because webpack and data updates are not applied at the same time (meaning that we can have either older component or older content for some period of time that can lead to runtime errors). This change allow to recover from situation like that.
--edit:
Please note that the change here is not just for case described above and it's rather generic. Above we ideally fix at some point by synchronising applying updates from …
=> fix(gatsby): refresh browser when receiving update and runtime errored

packages/gatsby-transformer-remark/src/__tests__/on-node-create.js, packages/gatsby-transformer-remark/src/gatsby-node.js, packages/gatsby-transformer-remark/src/on-node-create.js, packages/gatsby-transformer-sharp/src/gatsby-node.js, packages/gatsby-transformer-sharp/src/on-node-create.js, packages/gatsby/index.d.ts, packages/gatsby/scripts/__tests__/api.js, packages/gatsby/src/utils/api-node-docs.ts, packages/gatsby/src/utils/api-runner-node.js
This change allows a plugin to register a `shouldOnCreateNode` callback which is called when Gatsby is about to schedule a callback for the (async) `onCreateNode` callback. The scheduling is relatively expensive at scale and the test is often cheap. As a result, this saves roughly 20% of a certain step during bootstrap for some cases (lot's of conditions, but this will apply to most sites to a certain degree). In the site I was benchmarking it drops a minute from a five minute step.
The problem is particular to `onCreateNode` because it will call the callback for each plugin for every node generated, even though in many cases the plugin may not care about that particular node (sharp does not care about markdown nodes, callback is still scheduled and invoked async).
Turns out that these …
=> perf(gatsby): test sync before calling onCreateNode

packages/gatsby/package.json, yarn.lock
This fixes `npm audit` that currently is displayed when installing gatsby:
```
➜  gatsby npm audit
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │ …
```
=> chore(gatsby): major dep bump for eslint-plugin-graphql 

packages/gatsby-plugin-manifest/src/gatsby-node.js
=> chore(gatsby-plugin-manifest): add pluginOptionsSchema

packages/gatsby-plugin-sass/package.json, packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js, packages/gatsby-plugin-sass/src/gatsby-node.js
Add plugin schema options in `gatsby-plugin-sass`
Relates to #27242 and https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/
Notes:
- Many options come from https://github.com/sass/node-sass
- I didn't manage to make some special cases using [`Joi.when()`](https://joi.dev/api/?v=17.2.1#anywhencondition-options) like the following: `file or data must be specified` (one or the other is strictly required)
- I'm not overly confident about this plugin options since it owns a lot of options and sub module options 😓
=> chore(gatsby-plugin-sass): add pluginOptionsSchema export

packages/gatsby-plugin-google-analytics/src/gatsby-node.js
As discussed with @mxstbr in https://github.com/gatsbyjs/gatsby/pull/27242#discussion_r506326021, I added `onPreInit` again in case `GATSBY_EXPERIMENTAL_PLUGIN_OPTION_VALIDATION` isn't `true`
=> fix(gatsby-plugin-google-analytics): Fix gatsby-node so we still have a warning on older gatsby versions

packages/gatsby-plugin-sharp/src/__tests__/index.js, packages/gatsby-plugin-sharp/src/index.js
The current way we get the sizes of input images is very inefficient, particularly with large source images. This PR adds a much faster async function, which can be used by `fixed()`, which is already async. It also optimises the sync version, which we can't currently remove because it's used in various sync functions.
The results of benchmarking the various options:
| Implementation | Time for 100x reads of 15MB image (ms) |
| -------------- | -------------------------------------- |
| Current sync   | 8600                                   |
| Optimised sync* | 470                                    |
| Async*          | 87                                     |
\* This PR
=> perf(gatsby-plugin-image): Optimise image size functions

packages/gatsby-recipes/recipes/wordpress.mdx
Implemented the fix that Kyle requested at https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-710151717
Just add the `isLocal={true}` prop to the <GatsbyPlugin /> call in the wordpress recipe.
=> fix(gatsby-recipes): Added isLocal prop to wordpress recipe

integration-tests/long-term-caching/__tests__/long-term-caching.js, packages/gatsby/src/services/initialize.ts
This PR adds a warning and wipes the `.cache` when the `public` folder is missing but the `.cache` folder exists.
Builds can break if someone deletes the `public` folder but not the `.cache` (with cryptic errors about missing `page-data` files).
There is one case when doing this still leads to accidentally working builds: when the project only has pages without any queries. This behavior actually relies on our "bug" - at the moment we always re-run page queries without dependencies (or in other words - pages without graphql queries in them).
This skipped test sums up the problem: 
https://github.com/gatsbyjs/gatsby/blob/ecc0ad37f3fb6d542964c95c2f853c25cc99d5b8/packages/gatsby/src/query/__tests__/data-tracking.js#L1241-L1243
That's exactly what happens in `gatsby-admin` and our …
=> fix(gatsby): notify when Gatsby cache is incomplete

packages/gatsby-cli/src/create-cli.ts
Start tracking the `gatsby options` usage, I didn't test this out yet with the canary
=> chore(cli) track package manager usage

packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts, packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts, packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts, packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts, packages/gatsby-plugin-page-creator/src/derive-path.ts, packages/gatsby-plugin-page-creator/src/error-utils.ts, packages/gatsby-plugin-page-creator/src/gatsby-node.ts, packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts, packages/gatsby-plugin-page-creator/src/path-utils.ts, packages/gatsby-plugin-page-creator/src/validate-path-query.ts
Part of https://github.com/gatsbyjs/gatsby/pull/27424
I used yarn resolutions and the normal dependencies field to install those versions. After installation I checked with `yarn why` if they are really installed. Then I used `gatsby-dev` to copy over the new contents of `gatsby-plugin-page-creator`.
```
"gatsby": "2.15.37",
"gatsby-cli": "2.8.30"
```
```
"gatsby": "2.24.67",
"gatsby-cli": "2.12.102"
```
```
"gatsby": "2.24.67",
"gatsby-cli": "2.12.107"
```
```
"gatsby": "latest",
"gatsby-cli": "latest"
```
With https://github.com/gatsbyjs/gatsby/pull/27547 merged
---
[ch16760]
[ch16755]
=> fix(gatsby-plugin-page-creator): Move to Structured Errors

integration-tests/structured-logging/__tests__/plugin-errors.js, integration-tests/structured-logging/plugins/structured-plugin-errors/gatsby-node.js, packages/gatsby/src/utils/api-runner-node.js
While working on https://github.com/gatsbyjs/gatsby/pull/27441 I discovered the 4 cases that `gatsby` and `gatsby-cli` could be in and how `setErrorMap` API behaves with it. To keep our internal/maintained plugins backwards compatible we'll be already prefixing `id` with the `pluginName` so that older versions already have this.
This change is necessary for https://github.com/gatsbyjs/gatsby/pull/27441 to be eventually be merged into `master` as the current behavior otherwise would be that `id` is double prefixed, e.g. `gatsby-plugin-page-creator_gatsby-plugin-page-creator_12345`.
The plugins will use a little helper like [this function](https://github.com/gatsbyjs/gatsby/blob/unified-routes/structured-errors/packages/gatsby-plugin-page-creator/src/error-utils.ts#L16-L18) to prefix the …
=> fix(gatsby): Handle double prefix case for `extendErrorIdWithPluginName`

packages/gatsby-transformer-asciidoc/README.md
This patch makes a correction to the actual Custom Converter section of
the documentation in gatsby-transformer-asciidoc. It is referenced by current version
as a TemplateConverter, but is in fact a CustomConverter.
This patch also extends the doc regarding the actual usage.
closes #27511
=> Improve doc for CustomConverter in gatsby-transformer-asciidoc

packages/gatsby-source-contentful/README.md, packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js, packages/gatsby-source-contentful/src/download-contentful-assets.js, packages/gatsby-source-contentful/src/gatsby-node.js
With large Contentful sites, the number of assets can open too many connections for Node to handle. This leads to the download stalling. While the issue is unlikely to be encountered on a CI instance, on a local machine it can freeze downloads or even crash the machine in some cases. This PR adds a workload distribution system that limits the number of concurrent downloads, fixing the issue. The number is also configurable using a plugin option.
Docs in the readme are updated.
=> fix(gatsby-source-contentful): fixed contentful asset download stalling with high number of assets

packages/gatsby-plugin-utils/tsconfig.json
This adds `skipLibCheck` to the tsconfig for `gatsby-plugin-utils`, which means the typegen doesn't also typecheck all of the lib's dependencies. This avoids a race condition where types cannot be generated unless gatsby-cli has already been compiled. This doesn't affect compilation or type-checking, just typegen, and the types in question are already checked in the scripts for those packages.
=> fix(gatsby-plugin-utils): skip libcheck during typegen

packages/gatsby-source-contentful/src/download-contentful-assets.js
https://github.com/gatsbyjs/gatsby/pull/27563 introduced a `assetDownloadWorkers` but the function that generated the workers could still receive `undefined`. This sets the default to make sure it's always getting some value.
=> fix(gatsby-source-contentful): set default for contentful asset workers

e2e-tests/development-runtime/cypress/integration/navigation/linking.js, e2e-tests/development-runtime/src/pages/navigation-effects.js, packages/gatsby/cache-dir/navigation.js
Fixes issue: https://github.com/gatsbyjs/gatsby/issues/27351
Currently, when you change a route/location search param or hash, no effect will occur.
The expected behaviour is that if the route/location changes at all then effects should be triggered.
Please see https://github.com/gatsbyjs/gatsby/issues/27351 for more details on this bug.
Fixes issue:  https://github.com/gatsbyjs/gatsby/issues/27351
=> fix(gatsby): trigger location effects in navigation

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Updated the custom Netlify CMS compilation message to display the expected URL Netlify CMS is running at based on the `--port` and `--https` flags the user provided when running `gatsby develop`.
I first tried to use the same format as used in `gatsby-plugin-graphql-config`:
`${program.https ? `https://`:`http://`}${program.host}:${program.port}`
This worked for the protocol, but not for `program.port`, as it seems the `program` const is initialized at a different moment between those two plugins. For this reason, I opted to use `program.proxyPort` instead.
Fixes #27429
=> Report URL with expected protocol and port

docs/docs/sourcing-from-graphcms.md
Removal of beta notes from the GraphCMS [data sourcing guide](https://www.gatsbyjs.com/docs/sourcing-from-graphcms/#reach-skip-nav), now that [`gatsby-source-graphcms`](https://github.com/GraphCMS/gatsby-source-graphcms) is available on `latest` tag.
* N/A
* N/A
=> docs(guide): Remove beta notes from GraphCMS sourcing guide

packages/gatsby-cli/src/reporter/redux/diagnostics.ts, packages/gatsby-cli/src/structured-errors/error-map.ts
Adds an error code to the watchdog termination log and makes the message slightly more user friendly.
=> chore(diagnostics): Adds error code and friendlier message for diagnostics

packages/gatsby/src/utils/webpack-utils.ts
Disable automatic react runtime option by default. The ecosystem hasn't adapted yet, projects like theme-ui, mdx, .. haven't adopted it yet. When people us react@17, their site might break
https://github.com/gatsbyjs/gatsby/pull/27468#issuecomment-713619785
You can test it by adding the following to a page and using react, react-dom
```
/** @jsx createElement */
import React, { createElement } from "react"
```
=> feat(gatsby): disable automatic by default

packages/gatsby-source-filesystem/src/error-utils.js, packages/gatsby-source-filesystem/src/extend-file-node.js, packages/gatsby-source-filesystem/src/gatsby-node.js, packages/gatsby-transformer-sharp/src/customize-schema.js, packages/gatsby-transformer-sharp/src/error-utils.js, packages/gatsby-transformer-sharp/src/gatsby-node.js
> Related to Cloud functionality
In effort to improve the Cloud user experience, we need to make sure "Error copying file from..." errors are appropriately captured/categorized for Builds and Previews.
This PR simply updates the locations where log this error so that it uses `reporter.panic` instead of `console.error`
1. [x] What `id` should be used for this error? - _Any 5-digit number; this is an arbitrary value and contained within the context of the plugin (e.g., there is no risk error code conflicts between modules)_
=> fix(gatsby-source-filesystem,gatsby-transformer-sharp): Use custom errors

packages/gatsby/src/services/initialize.ts
A follow up for #27549. That PR didn't take into account that the `.cache` directory exists in `develop` by the moment we call `initialize`. In develop the `.cache` directory is actually created here:
https://github.com/gatsbyjs/gatsby/blob/ed31b3583f6f94797697f04b2c887e697c658507/packages/gatsby/src/commands/develop.ts#L99-L102
This PR uses a different heuristic to check for cache presence by just checking for `.cache/json` folder. We ensure this dir exists in the same `initialize` method, so it seems an appropriate target for this check:
https://github.com/gatsbyjs/gatsby/blob/ed31b3583f6f94797697f04b2c887e697c658507/packages/gatsby/src/services/initialize.ts#L315
Fixes #27641
=> fix(gatsby): better heuristic for automatic cache purging

packages/gatsby-plugin-manifest/package.json, packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js, packages/gatsby-plugin-manifest/src/gatsby-node.js
Using the latest version with the experimental feature flag (e.g. in gatsby-starter-blog) results in this error:
> warn Plugin "gatsby-plugin-manifest" has an invalid options schema so we cannot verify your configuration for it.
[ch17522]
=> fix(gatsby-plugin-manifest): fix plugin option schema and add a test for it

packages/gatsby-plugin-manifest/package.json, packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
After https://github.com/gatsbyjs/gatsby/pull/27565 was merged our `scripts/check-versions` script (it runs on `yarn bootstrap`) that makes sure we rely on latest deps from monorepo started failing:
```sh
➜  gatsby git:(master) yarn check-versions   
yarn run v1.21.0
$ babel-node scripts/check-versions.js
gatsby-plugin-manifest: 
Depends on "gatsby-plugin-utils@0.2.35" 
instead of "gatsby-plugin-utils@0.2.39". 
error Command failed with exit code 1.
```
This just bumps the dep version to "latest"
=> chore(gatsby-plugin-manifest): sync version of gatsby-plugin-utils dependency

packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
This PR addresses one of our memory leaks in `develop` with refresh endpoint (in this case in internal plugin `internal-data-bridge`).
Refresh endpoint always re-runs `sourceNodes` and we keep re-creating chokidar listeners that retain current redux state at the moment of the `sourceNodes` call. So we basically retain as many state "snapshots" as there were `sourceNode` API calls (i.e. refreshes).
To confirm I've run the https://github.com/reactjs/reactjs.org website with a 200MB node memory limit and kept hitting the `__refresh` endpoint. Before this PR it was OOMing on the 14-16th refresh, after this PR somewhere after 30th (so other memory leaks in play)
To clarify: this is not the only leak 😢 We have others. It is possible that chokidar listeners in `gatsby-source-filesystem` are also …
=> fix(gatsby): leak less in chokidar listeners

packages/gatsby/src/utils/__tests__/create-node-id.ts, packages/gatsby/src/utils/create-node-id.ts
This PR will cache the `uuid` calls when you call `createNodeId` repetitively with the same id/namespace.
This saves a large chunk at scale, especially for plugins like Contentful which call this API many times with the same key. Contentful tends to have a lot of nodes and a site that generates 1.6M nodes saves about 60 seconds just for doing this. Most sites won't see much difference.
It also caches the `uuid.v5` call for the namespace, which is often the same.
This is a fork of https://github.com/gatsbyjs/gatsby/pull/27661
> gabe-fs-text (128k pages)
```
success source and transform nodes - 56.154s
success createPages - 28.945s
info bootstrap finished - 89.735s
info Done building in 267.619 sec
```
```
success source and transform nodes - 52.153s
success createPages - 28.687s
info …
```
=> perf(gatsby): cache `createNodeId` locally

packages/gatsby-plugin-typescript/README.md
This PR explains how to add TypeScript-related Babel plugins by pointing to the Gatsby Babel docs page.
It should alleviate the need for [decorator support](https://github.com/gatsbyjs/gatsby/pull/23936) (though I haven't yet been able to actually use `@babel/plugin-proposal-decorators`, but that's a separate issue).
=> docs(gatsby-plugin-typescript): how to add Babel TS plugins

docs/docs/build-caching.md
Update 'Build Caching' [page](https://www.gatsbyjs.com/docs/build-caching/) example code
Changes:
- Remove unused `store` parameter
- Replace 3600000 milliseconds, which amounts to one hour, not one day, with twenty-four hours in milliseconds as a variable
N/A
N/A
=> chore(docs): Update 'Build Caching' example code

dictionary.txt, docs/docs/creating-and-modifying-pages.md, docs/docs/data-storage-redux.md, docs/docs/debugging-replace-renderer-api.md, docs/docs/how-plugins-apis-are-run.md, docs/docs/how-shadowing-works.md, docs/docs/html-generation.md, docs/docs/node-creation.md, docs/docs/node-tracking.md, docs/docs/page-node-dependencies.md, docs/docs/preprocessing-external-images.md, docs/docs/query-execution.md, docs/docs/query-extraction.md, docs/docs/schema-inference.md, docs/docs/write-pages.md
Changes:
- redux -> Redux
'redux' is blocklisted with an asterisk.
#25290 `enhancement (docs): Improvements to retext-spell`
=> fix (docs): dictionary.txt: 'redux' -> 'Redux'

packages/gatsby-remark-autolink-headers/README.md
Add instructions on how to style svg in gatsby-remark-autolink-headers
Fixes #20982
=> chore(gatsby-remark-autolink-headers): add styling instructions

packages/gatsby-plugin-emotion/README.md
Previous syntax was incorrect/not working with gatsby-config.js
=> chore(gatsby-plugin-emotion): Remove invalid options syntax

packages/gatsby-plugin-mdx/__tests__/gatsby-node.js, packages/gatsby-plugin-mdx/gatsby-node.js
The documented form to configure `gatsby-plugin-mdx` with `remark/hypePlugins` is to require them:
```JS
{
resolve: `gatsby-plugin-mdx`,
options: {
remarkPlugins: [require(`remark-slug`)]
}
}
```
The current `pluginOptionsSchema` for `gatsby-plugin-mdx` throws an error with this (valid!) configuration, stating that "remarkPlugins[0] should be object or array", which is inaccurate.
This fixes it by adding the correct type (function) to the possibilities for this array. Verified it works as expected by running the fix against the theme-ui docs website, which fails before this fix but works as expected afterwards.
=> fix(gatsby-plugin-mdx): remark/hypePlugins options schema

packages/gatsby/src/bootstrap/load-plugins/load.ts
Currently we print a very generic "failed to find plugin, are you sure it exists" message when the plugin exists but threw an error. This PR attempts to allow you to at least show the real error in verbose mode.
Without the `--verbose` flag it will show you the current state, with a small tweak to indicate it may have also been a different problem apart from not existing. And a hint that you can get the real error by using verbose mode.
With the `--verbose` flag you get the actual error and its stack trace.
=> fix(gatsby): print real plugin loading error in verbose

benchmarks/gabe-fs-markdown-route-api/package.json, e2e-tests/development-runtime/package.json, e2e-tests/development-runtime/src/pages/collection-routing/{ImageSharp.parent__(File)__name}.js, e2e-tests/production-runtime/package.json, e2e-tests/production-runtime/src/pages/collection-routing/{Product.name}.js, examples/route-api/gatsby-config.js, examples/route-api/package.json, examples/route-api/parks/park.yaml, examples/route-api/src/pages/index.js, examples/route-api/src/pages/parks/{park.meta__location__type}/[name].js, examples/route-api/src/pages/parks/{park.meta__location__type}/{park.name}.js, examples/route-api/src/pages/parks/{park.name}.js, examples/route-api/src/views/park-view.js, packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts, packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts, packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts, packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts, packages/gatsby-plugin-page-creator/src/babel-remove-collection-graphql.ts, packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts, packages/gatsby-plugin-page-creator/src/extract-query.ts, packages/gatsby-plugin-page-creator/src/gatsby-node.ts, packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts, packages/gatsby-plugin-page-creator/src/path-utils.ts, packages/gatsby/cache-dir/gatsby-browser-entry.js, packages/gatsby/index.d.ts, packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
Part of https://github.com/gatsbyjs/gatsby/pull/27424
In the process of updating the example I've also fixed some bugs and did some necessary changes for GA. List of changes:
- Removed the `GATSBY_EXPERIMENTAL_ROUTING_APIS` flag from any scripts (benchmarks and example)
- Renamed `unstable_collectionGraphql` to `collectionGraphql`
- Updated the example:
- Latest dependencies
- Added a new type called "park" to demonstrate lowercased types
- Added examples for `/{Model.id__field}/{Model.name}`, `/{Model.id__field}/[name]`, `collectionGraphql`
- Changed `generateQueryFromString` in `extract-query.ts` to account for lowercased type names by using lodash camelCase
- Changed `isValidCollectionPathImplementation` to also account for that
- Changes in `path-utils`
- Moved the regex out to …
=> File System Route API: Improve example & fix couple of bugs

packages/gatsby-source-contentful/src/extend-node-type.js
Renames `GATSBY_REMOTE_CACHE` to `GATSBY_CONTENTFUL_EXPERIMENTAL_REMOTE_CACHE` and adds deprecation warning for the old name. We can drop that in a few weeks or whatever (probably right now but let's give it a little bit of time).
=> chore(gatsby-source-contentful): rename env var to proper struct

packages/gatsby/src/services/create-pages.ts, packages/gatsby/src/utils/state-machine-logging.ts
Small tweak. Even if `--verbose` is not used, gatsby would still generate the strings before they are discarded. That's negligible for simple string concats but these cases were not that trivial.
=> chore(gatsby): dont generate heavy verbose payload we wont use

packages/gatsby/src/redux/reducers/jobsv2.ts, packages/gatsby/src/redux/types.ts, packages/gatsby/src/services/initialize.ts
We consider Gatsby cache to be corrupt when a user deletes the `public` folder but not the `.cache` folder. In this case we purge the cache for him (via #27549) and also call `DELETE_CACHE` to purge the redux state that is already in memory by this point.
But `jobsV2` reducer doesn't clear job cache on `DELETE_CACHE` action. This makes sense because sharp jobs can survive `.cache` folder removal. But they can't survive the `public` folder removal (as that's where job results are physically stored).
This PR changes the behvaior of `jobsV2` reducer and makes it purge the job cache when the cache is corrupt (so only when the `public` folder is deleted).
Fixes #27699
=> fix(gatsby): purge jobsV2 results when cache is corrupt

packages/gatsby-source-contentful/src/fetch.js
When building with `--verbose`, gatsby-source-contentful will now log enough information to identify of API issues.
This will simplify debugging, especially for out friends at Gatsby & Contentful support.
This might get pretty verbose on big spaces, but will help a lot to identify problems :)
```
verbose get /: 200 OK (size: 325B, response id: 75ea2c57-635f-4941-a17e-35e1a9e4df05, cache: HIT)
verbose get /locales: 200 OK (size: 538B, response id: 3e8ace80-73b6-484b-a1b6-e1b981e98b42, cache: HIT)
verbose get /sync: 200 OK (size: 67857B, response id: 5d30f4ec-6538-4740-b2b5-fecfcc62171c, cache: HIT)
verbose get /sync: 200 OK (size: 58682B, response id: 51b4e75a-d648-41f7-9759-c48f316aef66, cache: HIT)
verbose get /sync: 200 OK (size: 51482B, response id: …
```
=> feat: log Contentful API responses when --verbose flag is set

packages/gatsby/package.json
The `package.json` file in the `gatsby` module lists individual files to include, but that list does not include `graphql.d.ts`. This means that if you import from `gatsby/graphql` in a typescript project, it does not find the typings.
This PR simply adds that file to the list of files to be published.
=> fix(gatsby): include graphql type definition in published files

packages/gatsby-plugin-mdx/__tests__/gatsby-node.js, packages/gatsby-plugin-mdx/gatsby-node.js
Turns out, there is a use-case for specifying `plugins: [...]` in `gatsby-plugin-mdx` as explained in this comment as a workaround for gatsby-browser/node/... support in `rehype/markPlugins`: https://github.com/gatsbyjs/gatsby/issues/15486#issuecomment-510153237
This adds plugins to the plugin options schema for gatsby-plugin-mdx! :+1:
=> fix(gatsby-plugin-mdx): allow plugins: [...] in options schema

packages/gatsby-recipes/src/create-types.js, packages/gatsby-recipes/src/index.js, packages/gatsby-recipes/src/renderer/render.js, packages/gatsby-recipes/src/renderer/resource-components.js, packages/gatsby-recipes/src/renderer/transform-to-plan-structure.js, packages/gatsby-recipes/src/resources.js, packages/gatsby-recipes/src/validate-recipe.js
Adds exports for recipes providers, so they can be used by other packages
=> feat(recipes): Export providers

packages/gatsby-cli/src/create-cli.ts, packages/gatsby/src/commands/plugin-add.ts, packages/gatsby/src/commands/plugin.ts
This creates a stub `gatsby plugin <cmd> [plugins...]` command, ready for the add and configure subcommands. It moves across the `docs` command that already existed, though we'll probably want to change it.
=> feat: Add "gatsby plugin" command

packages/gatsby/cache-dir/socketIo.js, packages/gatsby/src/utils/webpack.config.js
Add an env var so we can set the default websocket type. It should fix long running websocket issues. When a faulty transport is given than socket.io will fallback to polling anyway.
=> feat(gatsby): allow configuration of default socket type

packages/gatsby/src/commands/plugin/configure.ts
In an attempt to start addressing some of the TODOs from https://github.com/gatsbyjs/gatsby/pull/27727 I added a couple additions:
I hardcoded options matching `accessToken` to sensitive in this example:
#27727
=> feat(gatsby): more `gatsby plugin configure` additions

packages/gatsby-cli/src/structured-errors/error-map.ts, packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts, packages/gatsby/src/bootstrap/load-plugins/index.ts, packages/gatsby/src/bootstrap/load-plugins/validate.ts
When a user uses a theme that has a invalid plugin configuration in its gatsby-config.js, the user will see a blocking error:
```
❯ GATSBY_EXPERIMENTAL_PLUGIN_OPTION_VALIDATION=true yarn start
yarn run v1.22.4
success open and validate gatsby-configs - 0.064s
ERROR #11331  PLUGIN
Invalid plugin options for "gatsby-plugin-mdx":
- "plugins" must contain 0 items
not finished load plugins - 3.026s
error Command failed with exit code 1.
```
However, the user doesn't even have `gatsby-plugin-mdx` in their gatsby-config and cannot fix this since they might not have control over the theme that incorrectly uses this plugin! :scream:
This patch fixes that case by instead 1) logging the directory of the faulty gatsby-config and 2) not blocking `yarn develop` if the error is from a …
=> fix(gatsby): show theme that has faulty config

packages/gatsby-recipes/src/cli/index.js
This fixes showing the correct install command when running recipes from the recipes list shown when running `gatsby recipes`
=> fix(gatsby-recipes): Only remove the ".mdx" ending if running local recipe

packages/gatsby-transformer-remark/src/gatsby-node.js
=> fix(gatsby-transformer-remark): add excerpt_separator to plugin options schema

packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js, packages/gatsby-plugin-manifest/src/gatsby-node.js
It's possible to have directories nested multiple layers deep or potentially that `public` isn't defined.
=> fix(gatsby-plugin-manifest): create directories recursively

packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js, packages/gatsby-plugin-sass/src/gatsby-node.js
`cssLoaderOptions` is not defined in the schema, so it will return an error when passing in these options.
See readme: 
```
If you need to override the default options passed into css-loader: Note: Gatsby is using css-loader@1.0.1.
plugins: [
{
resolve: `gatsby-plugin-sass`,
options: {
cssLoaderOptions: {
camelCase: false,
},
},
},
]
```
=> fix(gatsby-plugin-sass): add missing options

packages/gatsby-source-contentful/src/gatsby-node.js
In the validation schema the `localeFilter` default value was a function that returned an invalid value
Fixes #27787
=> fix(gatsby-source-contentful): default function returned invalid value

packages/gatsby-plugin-offline/src/gatsby-node.js
This PR enables the networkTimeoutSeconds option when using the NetworkFirst strategy.
https://developers.google.com/web/tools/workbox/guides/common-recipes#force_a_timeout_on_network_requests
=> Use NetworkFirst with networkTimeoutSeconds option configured

packages/create-gatsby/package.json, packages/create-gatsby/src/index.ts, packages/create-gatsby/src/plugin-schemas.json
This is a mess of poorly typed code that introduces a WIP form of prompting users for required plugin options when they select plugins in the create gatsby flow.
=> feat(create-gatsby): add wip plugin configuration forms

packages/gatsby/src/utils/__tests__/feedback.ts, packages/gatsby/src/utils/feedback.ts
The tests for the analytics did not reset the 7 day feedback date in config so it failed for me locally. This fixes it.
=> fix(gatsby): feedback test did not reset 7day check

lerna.json
After this change `yarn run publish` will publish a pre-release (for safety). We will add separate commands for publishing stable after manual testing
=> chore: update lerna config for the new release process

packages/gatsby-remark-autolink-headers/src/gatsby-node.js
Closes #27813. This should be defaulted to `undefined`, as `true` isn't supported.
=> fix(gatsby-remark-autolink-headers): remove incorrect default value for icon option

packages/gatsby-recipes/recipes/gatsby-image.mdx
changes:
- place directory name in brackets
- #27012 feat(gatsby-recipes): Add a built in recipe for Gatsby Image
=> fix(recipe): add brackets to directory names

packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js, packages/gatsby-plugin-sass/src/gatsby-node.js
- The default `outputStyle` cannot be `"nested"`, as that's not supported by dart-sass
- Since these plugin options are mainly passed through to the Sass implementation, there is a large surface area of options we support but don't know about. Mentioned in #27796 are two, `webpackImporter` and `cssLoader`, but I'm sure there's others. In order to avoid future issues with options we don't know about, I decided to let unknown options pass through for this plugin only.
Closes #27796
=> fix(gatsby-plugin-sass): fix default output style & allow unknown options

packages/gatsby/src/utils/api-node-docs.ts
Remove an incorrect getsbyVersion annotation in the docs for `createPages`. This was introduced in #27735, and broke snapshots.
=> fix(gatsby): Remove version annotation in createPages

packages/gatsby-recipes/rollup.config.js, packages/gatsby-recipes/src/providers/gatsby/__snapshots__/shadow-file.test.js.snap, packages/gatsby-recipes/src/providers/gatsby/shadow-file.js
Discovered this while testing #27721
- don't throw if read returns undefined (the NPMPackage might be installed)
- don't throw if the shadow file does not exist (same)
- return `dependsOn` for the theme's equivalent `NPMPackage` to ensure it's installed before we try to create the shadowed file
=> fix(gatsby-recipes): fix GatsbyShadowFile resource — don't error if package isn't installed

packages/gatsby-recipes/rollup.config.js, packages/gatsby-recipes/src/providers/gatsby/__snapshots__/shadow-file.test.js.snap, packages/gatsby-recipes/src/providers/gatsby/shadow-file.js
Backporting #27790 to the current release
* fix(gatsby-recipes): fix GatsbyShadowFile resource — don't error if package isn't installed
* Update snapshots
* Turn comment into verbose log
* Somehow utila started causing errors w/ rollup 🤷‍♂️
* remove reporter
* revert addiing utila to rollup externals
(cherry picked from commit 3817174822c61aeafd3efac5fb670604d895d89d)
=> fix(gatsby-recipes): fix GatsbyShadowFile resource — don't error if package isn't installed (#27790)

packages/gatsby-plugin-sitemap/src/gatsby-node.js
The Joi configuration validation setup for the sitemap plugin was missing the sitemapSize option, causing builds using the option to fail now that configuration is strictly validated. This adds the Joi entry for this option.
=> fix(gatsby-plugin-sitemap): fixed missing sitemapSize config entry

packages/gatsby/src/query/queue.ts
We should log something out when experimental flags are active.
=> chore(gatsby): log out when experimental concurrency flag is used

packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts, packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts, packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts, packages/gatsby-plugin-page-creator/src/__tests__/get-collection-route-params.ts, packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts, packages/gatsby-plugin-page-creator/src/__tests__/validate-path-query.ts, packages/gatsby-plugin-page-creator/src/derive-path.ts, packages/gatsby-plugin-page-creator/src/extract-query.ts, packages/gatsby-plugin-page-creator/src/get-collection-route-params.ts, packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts, packages/gatsby-plugin-page-creator/src/path-utils.ts
Part of https://github.com/gatsbyjs/gatsby/pull/27424
- I forgot to remove some bits about `collectionGraphql` in https://github.com/gatsbyjs/gatsby/pull/27824 so I did this here. Namely:
- Removing outdated tests with name `supports a special fragment`
- Removing `fragmentInterpolator` and check for `...CollectionPagesQueryFragment` in src/extract-query.ts
- Until now the assumption in the code was that for every part between `/` only one `{Model.foo__bar}` is allowed, so e.g. `/blog/{Model.foo}/{Model.bar}.js`
- This fixes this assumption and thus also allowes a `/blog/{Model.foo}-{Model.bar}.js`
- I changed the extractions to give back array of strings, not strings as now multiple matches are counted
[ch18291]
=> File System Route API: Support `/{Model.foo}-{Model.bar}`

packages/gatsby/src/utils/cache.ts
- The `directory` getter should really be a regular property that gets instantiated in the constructor
- The `get` and `set` methods return a Promise, so let's add the keyword for clarity. They still need to create their own promise because they pass down the `resolve` function, but it's way out of scope of this PR to improve that.
=> chore(gatsby): small refactor in cache

packages/gatsby-plugin-sitemap/src/gatsby-node.js
Backporting #27866 to the release branch
(cherry picked from commit f0689ffce82e8b59a02df5c338470bd31a5154f2)
=> fix(gatsby-plugin-sitemap): fixed missing sitemapSize config entry (#27866)

packages/gatsby-source-filesystem/src/gatsby-node.js
Back-porting #27849 to the release branch.
(cherry picked from commit 253b1af728de1b007eb582d63286d0ce2476e41b)
=> fix(gatsby-source-filesystem): allow regex and functions for ignore option (#27849)

packages/gatsby-source-contentful/src/__tests__/fetch.js, packages/gatsby-source-contentful/src/fetch.js, packages/gatsby-source-contentful/src/report.js
This adds error codes to `reporter.panic` calls that occur in `fetch.js`. Adding these codes helps us to categorize our build and preview failures.
=> Add error codes to reporter.panic in Contentful source plugin

packages/gatsby-source-filesystem/src/create-remote-file-node.js
This is an experimental env flag to help with debugging. It replaces any remote asset that is fetched through `createRemoteFileNode` with a local placeholder file. The path is used as is.
This helps with debugging and profiling sites where the remote assets are not necessary but still take minutes to download. Not meant to be used with regular sites so it's only exposed as an experimental flag.
=> feat(gatsby-source-filesystem): env flag to placeholder remote assets

packages/gatsby-plugin-google-tagmanager/package.json, packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-node.js, packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
Added support for function type in the plugin gatsby-plugin-google-tagmanager. This should solve #27874 
This actually helps validate the docs for gatsby-plugin-google-tagmanager found at [https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-tagmanager](url)
The docs mention that defaultDataLayer prop can accept both object and function, but using a function throws an error.
#27874
=> fix(gatsby-plugin-google-tagmanager): allow functions for defaultDataLayer option

renovate.json5
[express-graphql](/graphql/express-graphql) includes breaking changes in its minor releases. This is semver-compatible since the package is still below v1, but it breaks Renovate PRs that include this package. I'll investigate manually adapting to the changes, specifically [express-graphql#608](/graphql/express-graphql/pull/608) which seems to be the root of the errors generated after updating.
=> fix(renovate): move express-graphql and react-reconciler from minor to major update groups

packages/gatsby-plugin-google-tagmanager/package.json, packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-node.js, packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
Backporting #27886 to the release branch
* Added check for function type for defaultDataLayer prop
* Fixing lint issues
* More lint fixes
* Add tests
(cherry picked from commit 631f3c401ed7c4d659604d5dd3170521bd477a61)
=> fix(gatsby-plugin-google-tagmanager): allow functions for defaultDataLayer option (#27886)

docs/docs/creating-and-modifying-pages.md
No direct changes. I have just added require("path") to the example to avoid confusion. The way it was before would result in an error.
=> chore(docs): Add required `path` import to modifying-pages doc

packages/gatsby-plugin-offline/src/__tests__/gatsby-node.js, packages/gatsby-plugin-offline/src/gatsby-node.js
=> fix(gatsby-plugin-offline): add workboxConfig.maximumFileSizeToCacheInBytes to options schema

packages/gatsby-plugin-google-analytics/src/gatsby-node.js
Actually closes #27833! I added all other options but forgot this one in #27914 :facepalm:
=> fix(gatsby-plugin-google-analytics): add cookieFlags to options schema

packages/gatsby-plugin-google-analytics/src/gatsby-node.js
Backporting #27923 to the release branch
(cherry picked from commit 557139ed20fb18db08686db42284511ab8f9bdfd)
=> fix(gatsby-plugin-google-analytics): add cookieFlags to options schema (#27923)

packages/gatsby-plugin-offline/src/__tests__/gatsby-node.js, packages/gatsby-plugin-offline/src/gatsby-node.js
Backporting #27913 to the release branch
(cherry picked from commit e4fd0ad8cda56996f42e0a2b9fd6b580823289c9)
=> fix(gatsby-plugin-offline): add workboxConfig.maximumFileSizeToCacheInBytes to options schema (#27913)

packages/gatsby/src/redux/reducers/__tests__/queries.ts, packages/gatsby/src/redux/reducers/queries.ts, packages/gatsby/src/redux/types.ts
Turns out a payload of the `DELETE_NODE` action can be `undefined` in some edge cases (no idea when exactly). And refactor from #27504 didn't account for this. This causes `Cannot read property 'id' of undefined'` error (again, hard to say in which circumstances).
This PR fixes this problem by using the same strategy as other reducers (just treats this situation as a no-op). Example from other reducer:
https://github.com/gatsbyjs/gatsby/blob/557139ed20fb18db08686db42284511ab8f9bdfd/packages/gatsby/src/redux/reducers/nodes.ts#L21-L26
=> fix(gatsby): account for edge case when payload of DELETE_NODE is undefined

packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Lazily fetch the list of `File` nodes. Before it would always generate the list of file nodes (which does a shallow copy, which is expensive at scale). Afterwards it only does this when the files are actually read, by adding a "getter" property.
Benchmark numbers on gabe-fs-mdx (no plugins), for just 10k pages:
```
info bootstrap finished - 110.731s
success run page queries - 176.578s - 10002/10002 56.64/s
info Done building in 297.347 sec
```
to
```
info bootstrap finished - 96.578s
success run page queries - 159.652s - 10002/10002 62.65/s
info Done building in 266.202 sec
```
(This snippet is used at sourcing time and as part of resolvers so run queries is also affected, so it saved roughly 2x 15s)
=> perf(gatsby-plugin-mdx): lazily fetch file nodes for remark plugins

packages/gatsby-transformer-remark/src/__tests__/extend-node.js, packages/gatsby-transformer-remark/src/extend-node-type.js, packages/gatsby/src/utils/__tests__/api-runner-node.js, packages/gatsby/src/utils/api-runner-node.js, packages/gatsby/src/utils/cache.ts, packages/gatsby/src/utils/get-cache.ts
The first commit allows us to run markdown in serial mode again (the remark plugin was not awaiting the cache plugins so it was not properly running in serial).
This may also fix a race condition where the same source is parsed twice at the same time, since the cache.set call of the first may not have been completed when the second starts. But that's a very unlike scenario as these caches are more likely to be hit for subsequent builds, not the same session.
The remaining commits refactor the code. I can be okay to drop most of them if people feel it's too much.
=> fix(gatsby-transformer-remark): wait for cache promises before returning

packages/gatsby/index.d.ts
Update Typescript types for gatsby's Node and NodeInput interfaces to allow `parent` property to be nullable
Fixes #26553
=> fix(gatsby): Update TS types to allow Node 'parent' to be nullable

docs/docs/styled-components.md
Including this could create confusion 😕 for noobs, who might think that like other 'Layout' HOCs we have to try to _render_ `children`.
=> chore(docs): Add children to styled-components doc

dictionary.txt, docs/docs/deploying-to-kintohub.md
Changed all the instances of "kintoblock" to the proper "KintoBlock" in  [deploying to kintohub](https://www.gatsbyjs.com/docs/deploying-to-kintohub/) by appending an asterik in dictionary.txt. 
Addresses [#25290](https://github.com/gatsbyjs/gatsby/issues/25290) enhancement (docs): Improvements to retext-spell.
More specifically, 4. Standardize names of libraries and brands
=> fix(docs): dictionary.txt -> KintoBlock-kintoblock

packages/gatsby-plugin-image/README.md
Simplify and update the plugin docs. This removes some of the detail on implementation and advanced usage, in favour of a more streamlined guide to trying the plugin and components
=> docs(gatsby-plugin-image): Update readme

packages/gatsby/src/utils/start-server.ts
This lowers the amount of data transfered for one site from 5.8mb -> 1.3mb which speeds up
loading the preview especially in remote situations.
Most of that drop was from the commons.js bundle which dropped from 5.2mb -> 0.6mb.
=> feat(gatsby): enable compression in the dev server

packages/gatsby-transformer-asciidoc/src/gatsby-node.js
Check if title field exists. If not, use empty string. 
As mentioned in issue, according to https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#document-header title field is optional. This PR does the existence check for title. 
https://github.com/gatsbyjs/gatsby/issues/27714
Fixes #27714
=> fix(gatsby-transformer-asciidoc): fails when doc doesn't have title

packages/gatsby/src/commands/build-javascript.ts, packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap, packages/gatsby/src/redux/reducers/pending-page-data-writes.ts, packages/gatsby/src/redux/types.ts, packages/gatsby/src/services/start-webpack-server.ts, packages/gatsby/src/utils/page-data.ts
Before this PR a page-data `flush` utility assumed that all queries for a given template were executed before it was called. I am referring to this function: https://github.com/gatsbyjs/gatsby/blob/b1b56e434934d189ddf21ffb87868b53fd1a7c41/packages/gatsby/src/utils/page-data.ts#L111
With query on demand, this assumption will be wrong as some queries for a template may be executed but others can still be in a pending (or dirty) state.
So this PR switches from per-component to per-page tracking of page data writes.
Required for #27620
=> refactor(gatsby): track page-data writes per-page

packages/gatsby/src/utils/api-runner-node.js
I'm not exactly sure why but stack trace for transpiled files have original/source file immediately when constructing error: 
Not sure if there is weird side effect that something overwrites `Error` prototype?
This currently can result in hiding real errors when we try to print codeframe pointing to origin of it, because we try to read file content without error handling and in case file doesn't exist we print file reading error and not the original one.
This PR adds error handling ... by try-catching part that reads the file and just doing nothing if it errors out (best check diff with hiding white-space setting enabled - https://github.com/gatsbyjs/gatsby/pull/27953/files?diff=unified&w=1)
=> fix(gatsby): don't hide original error if stack-trace point to not existing file

packages/gatsby-transformer-asciidoc/src/gatsby-node.js
Backporting #27865 to release branch
(cherry picked from commit ce43564edae4bf5e11b3e58fa59f4b48d564919f)
=> fix(gatsby-transformer-asciidoc): fails when doc doesn't have title (#27865)

packages/gatsby/src/utils/api-runner-node.js
Backporting #27953 to release branch
(cherry picked from commit 5e2b3eeb4af46a203de80fa8ce45774f9c6c3fa5)
=> fix(gatsby): don't hide original error if stack-trace point to not existing file (#27953)

packages/gatsby/package.json, packages/gatsby/src/cache/__tests__/cache-fs.js, packages/gatsby/src/cache/cache-fs.ts, packages/gatsby/src/cache/json-file-store.ts, packages/gatsby/src/cache/wrap-callback.ts, packages/gatsby/src/utils/cache.ts, yarn.lock
The cache object that we send to plugins relies on a fs-based locking mechanism to prevent race conditions from clobbering cache files. However this is causing a lot of io pressure, to the point where a baseline markdown benchmark drops 10%-15% just for this change.
Markdown is significantly affected because it aggressively caches the parsing steps. Other plugins might too, I've seen improvements in MDX for example. But really anything that heavily calls `cache.get` and `cache.set` should see a boost from this change.
This PR pulls in the plugin that we use for this cache: https://github.com/rolandstarke/node-cache-manager-fs-hash
The first commit copies it and only applies prettier/lint style fixes.
The second commit makes TS happy
The third commit replaces the `lockfile` library with a …
=> perf(gatsby): pull in cache lib and change lock from fs to mem

packages/gatsby-transformer-sharp/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-transformer-sharp/src/__tests__/gatsby-node.js, packages/gatsby-transformer-sharp/src/on-node-create.js
Currently `gatsby-transformer-sharp` only checks for extension field on node when deciding wether to create child node. Problem is it actually relies on other properties of the node too, so if there are non `File` nodes with extension fields this can cause problems ( see original issue reported by user https://github.com/craftcms/gatsby-source-craft/issues/6 )
Fixes #27924
=> fix(gatsby-transformer-sharp): create child nodes only for Files

packages/gatsby-transformer-sharp/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-transformer-sharp/src/__tests__/gatsby-node.js, packages/gatsby-transformer-sharp/src/on-node-create.js
Backport #27992 to the release branch.
(cherry picked from commit 001e045c92dfd37a7d573d75ee9d81ae44c8e7a5)
=> fix(gatsby-transformer-sharp): create child nodes only for Files (#27992)

packages/gatsby-remark-images/src/__tests__/gatsby-node.js, packages/gatsby-remark-images/src/gatsby-node.js
Fix the `withWebp` option in `gatsby-remark-images` option schema
https://github.com/gatsbyjs/gatsby/pull/27437#discussion_r520549965
=> fix(gatsby-remark-images): adding missing plugin options

packages/gatsby-remark-images/src/__tests__/gatsby-node.js, packages/gatsby-remark-images/src/gatsby-node.js
`showCaptions` can receive either boolean (`true` which internally translates into array of `['title', 'alt']`) or array of valid strings - see https://github.com/gatsbyjs/gatsby/blob/001e045c92dfd37a7d573d75ee9d81ae44c8e7a5/packages/gatsby-remark-images/src/index.js#L84-L88
Fixes #27983
=> fix(gatsby-remark-images): allow showCaptions to accept array of valid strings

packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts, packages/gatsby/src/bootstrap/load-plugins/validate.ts
[ch18531]
Requires #27949 to land first, as that adds support for `valueString` to the `trackCli` flags!
=> fix(gatsby): allow unknown plugin options

packages/gatsby/src/commands/develop.ts
Fix #26359: Support HTTPS for the develop status server
It introduces a breaking change as now the `--https` CLI flag also uses a HTTPS server for the develop status server. But, from my understanding, it was a bug as this server was not usable without this fix. The error in Google Chrome is:
```
GET https://myDomain.com:8001/socket.io/?EIO=3&transport=polling&t=NMq6XUt net::ERR_SSL_PROTOCOL_ERROR
```
Inspired by https://github.com/gatsbyjs/gatsby/blob/76cddc7ff2e4d7d2db6d5bc2d1e2dc765af62c1d/packages/gatsby/src/utils/develop-proxy.ts#L81-L83
Since it is my first contribution to Gatsby I may have missed something, so feel free to discard this PR. 
We would like to reduce the amount of differences between development & production environments.
Having a nginx running in front of `gatsby …
=> Fix #26359: Support HTTPS for the develop status server

packages/gatsby-source-contentful/CHANGELOG.md
Clean up change log for gatsby-source-contentful. Superseeds https://github.com/gatsbyjs/gatsby/pull/27999. :)
=> docs(gatsby-source-contentful): clean up changelog

packages/create-gatsby/src/features.json, packages/create-gatsby/src/index.ts, packages/create-gatsby/src/install-plugins.ts, packages/create-gatsby/src/plugin-options-form.ts, packages/gatsby-cli/src/plugin-add.ts
For discussion, this is a possible approach to allow plugin dependencies and plugin options. It handles possible duplicate plugin entries for e.g. source filesystem by allowing entries with the form `"name:key"`, e.g. `"gatsby-source-filesystem:pages"`
=> Add support for plugin dependencies

e2e-tests/development-runtime/cypress/integration/navigation/redirect.js, e2e-tests/development-runtime/cypress/plugins/block-resources.js, packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js, packages/gatsby/src/utils/page-data.ts, packages/gatsby/src/utils/start-server.ts
Adds explicit handler and not use `express-static` for `page-data` fetch requests. This allow us to find exact page browser request resources for and will enable triggering query on demand.
Side-effect will also be that we won't serve "stale" page-data resources in develop (builds already handle it by deleting files - https://github.com/gatsbyjs/gatsby/pull/26937 )
[ch18448]
=> feat(develop): add explicit express handler for page-data requests

packages/create-gatsby/package.json
Missed this change before the merge. Currently blocking gatsby bootstrap despite tests passing before merge.
=> Fix: create-gatsby utils dependency

packages/gatsby-recipes/src/providers/gatsby/utils/get-object-from-node.js
Currently, the parsing of a gatsby-config file will include "names" of config items it shouldn't.
The blog starter has a good example: 
```
`gatsby-plugin-react-helmet`,
// this (optional) plugin enables Progressive Web App + Offline functionality
// To learn more, visit: https://gatsby.dev/offline
// `gatsby-plugin-offline`,
```
All commented lines were included as plugins in the config, causing the `all` function to fail to process those since their names could not be matched to legitimate plugins. 
Whether comments are real plugins or just comments, they should not be processed as part of the active site config.
=> Fix: (gatsby-recipes) Disgregard comments in config

packages/create-gatsby/package.json
Not sure why this wasn't flagged in the tests, but it's getting flagged elsewhere. See pnp test in #28018.
=> Fix: (create-gatsby) missing dependency

benchmarks/gabe-fs-mdx/gatsby-config.js
=> chore(benchmarks): remove option because it is not yet published

packages/create-gatsby/README.md, packages/create-gatsby/cli.js, packages/create-gatsby/package.json, packages/create-gatsby/src/components/placeholder.js, packages/create-gatsby/src/get-config-store.ts, packages/create-gatsby/src/index.ts, packages/create-gatsby/src/init-starter.ts, packages/create-gatsby/tsconfig.json, packages/gatsby-cli/src/plugin-add.ts
The create-gatsby bundle was getting too large, so I've switched to using microbundle to compile it. I'm bundling almost all dependencies too, so we don't need to wait to install those. Unfortunately readable-stream doesn;t work with rollup, so we can't bundle that. I may switch to a different way of handling the streams, as I'm only using it via stream-filter to filter out npm install warnings.
In order to allow the bundling this makes a few other changes, such as including the configstore file from core-utils.
=> chore(create-gatsby): Microbundle package

packages/gatsby-remark-images/src/__tests__/gatsby-node.js, packages/gatsby-remark-images/src/gatsby-node.js
Backporting **two** PRs into the release branch: #27944 and #27998 The latter one requires the former and can't be cherry-picked individually. The downside is that in the release branch they will be squashed into a single commit but they both just fix plugin options of the same plugin, so I don't see a big problem here as long as we mention original commits in the message.
The alternative is to cherry-pick serially and wait for the full test suite on #27944, merge and then cherry-pick #27998 separately.
(cherry picked from commit 3675467)
(cherry picked from commit 08447bd)
=> fix(gatsby-remark-images): adding missing plugin options (#27944 and #27998)

packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js, packages/gatsby-plugin-sass/src/gatsby-node.js
Backporting #27829 to the release branch
(cherry picked from commit ac3759932c582663999aa4384e8e38f9935d7f29)
=> fix(gatsby-plugin-sass): loosely check postCssPlugins (#27829)

packages/gatsby-telemetry/src/telemetry.ts
Backporting #27949 and #28025 to the release branch. Required for backporting #28010 
(cherry picked from commit c6d754a83683e505466e6d2b63e04395f4c67ea8)
(cherry picked from commit d5807ac1d1641b8f181fae6bc6a4b3fdc05ef898)
=> chore(gatsby-telemetry): add two more value placeholders. (#27949 and #28025)

packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts, packages/gatsby/src/bootstrap/load-plugins/validate.ts
Backporting #27938 to the release branch
(cherry picked from commit 412b523fcb2909eabc3fae00f4bba5c3b59cc466)
=> fix(gatsby): allow unknown plugin options (#27938)

packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-ssr.js.snap, packages/gatsby-plugin-manifest/src/gatsby-ssr.js
This PR is an extension of #27566, with the requested changes from https://github.com/gatsbyjs/gatsby/pull/27566#pullrequestreview-523823336
=> Make optional SVG favicon come after the fallback

packages/create-gatsby/package.json, packages/create-gatsby/src/index.ts, packages/create-gatsby/src/init-starter.ts, packages/create-gatsby/src/reporter.ts, yarn.lock
We now don't emit output from the subprocesses runnign git and npm, unless there is an error. Fixes a bug that message up output in Windows (and reduces bundle size again!)
[ch18836]
=> fix(create-gatsby): Better subprocess handling

packages/create-gatsby/package.json, yarn.lock
One of the transient dependencies of create-gatsby tries to import `worker_threads` inside a try/catch block to find the pid, and falls-back to 0 if it can't load it. Because rollup hoists this import outside the block it fails on Node 10 where the package is behind a flag. This PR aliases worker_threads to [a shim](https://github.com/ascorbic/worker-threads-shim) that just returns 0 for the pid.
=> fix(create-gatsby): Shim worker_threads

packages/gatsby-source-mongodb/README.md, packages/gatsby-source-mongodb/src/gatsby-node.js
Currently there is now way to add a query when getting a collection data from mongo. There is a possibility that the collection is very large and we'd like to specify a query to limit the number of rows we retrieve from the database. This query pluginOption allows us to do that.
Example usage:-
```
{
resolve: `gatsby-source-mongodb`,
options: {
connectionString: `mongodb+srv://test:test@mymongodbserver/?retryWrites=true`,
dbName: `my-db`,
collection: [`myCollection`],
query: {
myCollection: {
as_of: {
$gte: 1604397088013,
},
}
}
},
},
```
=> add query pluginOption for mongodb plugin

docs/reference/release-notes/v2.26/index.md
Instructions for lazy images setup were misleading: the feature is enabled by default in the `lazy-images` canary. But instructions implied it had to be enabled separately.
=> fix(docs): fix lazy-images install instructions

packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap, packages/gatsby/src/redux/reducers/__tests__/__snapshots__/queries.ts.snap, packages/gatsby/src/redux/reducers/__tests__/queries.ts, packages/gatsby/src/redux/reducers/queries.ts, packages/gatsby/src/redux/types.ts
A recent refactor of dirty query implementation #27504 caused a performance regression in the query running step. The old implementation before that PR could wipe all data dependencies for queries at once after all of them were executed.
With queries on demand, we will run queries individually and so can't remove data dependencies in a single batch - we have to wipe them for individual queries.
It requires slightly different data structures to make it fast. 
Before this PR we were tracking data dependencies per node/connection:
```ts
const queriesByNode. = new Map<string, Set<string>>()
const queryIds: Set<string> = queriesByNode.get(nodeId)
```
This is enough to efficiently mark all queries related to a given node as dirty. But if you want to remove a single query from node dependencies …
=> perf(gatsby): fix performance regression with query dependency cleaning

README.md
Changed the ".org" extension to ".com"
=> chore: change .org to .com

packages/gatsby-plugin-manifest/README.md, packages/gatsby-plugin-manifest/package.json, packages/gatsby-plugin-manifest/src/gatsby-node.js, packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Backporting #27951 to the release branch
(cherry picked from commit 88b990ab44c1cd9acc9e1b7367991a3c194dd308)
=> fix(plugin-manifest): Allow for all valid WebAppManifest properties (#27951)

packages/gatsby-plugin-image/README.md, packages/gatsby-transformer-sharp/src/customize-schema.js
This replaces the scary alpha warning when using `gatsbyImageData` with a more reassuring beta warning, directing users to the RFC to give feedback. It also removes a comment about dominant color being disabled, because we have now upgraded sharp
=> chore(gatsby-transformer-sharp): Replace alpha warning for gatsbyImageData

e2e-tests/development-runtime/cypress.json, packages/gatsby-cypress/src/commands.js
Recently added runtime cache tests ( https://github.com/gatsbyjs/gatsby/pull/28060 ) seems to be flaky, let's bump the timeout to see if the problem is just not enough time waiting for things in CircleCI
=> test(e2e-development-runtime): bump timeout for those flaky test that seems to timeout sometimes in CI

packages/gatsby/src/services/calculate-dirty-queries.ts, packages/gatsby/src/services/listen-for-mutations.ts, packages/gatsby/src/services/types.ts, packages/gatsby/src/state-machines/develop/actions.ts, packages/gatsby/src/state-machines/develop/index.ts, packages/gatsby/src/state-machines/query-running/actions.ts, packages/gatsby/src/state-machines/query-running/index.ts, packages/gatsby/src/state-machines/query-running/types.ts
The changes in this PR are meant to be part of https://github.com/gatsbyjs/gatsby/pull/27939 (hence it targets that branch), but because the other PR is quite large already - this is separate PR to check it as "standalone"
Query on demand will emit `QUERY_RUN_REQUESTED` event with path to query that we need to run (only when we don't have results cached yet, or the results are not up to date)
The idea of this PR is to just keep appending requested path to `pendingQueryRuns` Set stored in context (we have same field in main `develop` machine and in `query-running` machine).
When we are idle (`waiting` state) we do conditional transient transition to `query-running` if the `pendingQueryRuns` is not empty. We also forward `QUERY_RUN_REQUESTED` events to `query-running` machine if we are in …
=> feat(state-machine): add query on demand transitions

packages/gatsby/src/cache/cache-fs.ts, packages/gatsby/src/cache/json-file-store.ts
Fixes a race condition by reserving the lock sync, rather than doing it in the `.then()` callback. Doing it in the callback was causing a race condition because it allowed other lock requests to also be granted in the mean time. `*`raises fist`*`
Also adds a try/catch around a JSON.parse call to show the complete output of what is being parsed in case we need to debug this again next time.
=> fix(gatsby): fix race condition in cache lock

benchmarks/source-contentful/gatsby-config.js
The limit was raised and it should be raised for the wib benchmark as well.
=> benchmarks(contentful): use the new max pageLimit

packages/gatsby/src/utils/show-experiment-notice.ts
This adds utility to help showing targeted experiment notices in CLI when some work takes more than predefined time threshold. To avoid potentially frustrating spam in CLI it tracks last time it showed that notice and will show it at most once a day (similar to how feedback survey doesn't show too often for same user).
For example usage see https://github.com/pieh/gatsby/commit/03168276459b09ce5fcb8a28b7cdb45ee10d977d which would invite user to check out query on demand experiment if their page queries run for at least 2 minutes
=> feat: add utility to show experiment invitation notices

packages/create-gatsby/src/index.ts
Remove the warning when running create-gatsby
=> chore(create-gatsby): Remove alpha warning

packages/create-gatsby/package.json, packages/create-gatsby/src/index.d.ts, packages/create-gatsby/src/index.ts, packages/create-gatsby/src/tracking.ts, packages/create-gatsby/src/types.d.ts, packages/gatsby-telemetry/src/in-memory-store.ts
Add telemetry to `create-gatsby`
=> feat(create-gatsby): add telemetry tracking

docs/docs/recipes/styling-css.md, docs/docs/using-web-fonts.md
This PR changes the documentation for Gatsby's local hosting font solutions which was previously dependent on [Typefaces](https://github.com/KyleAMathews/typefaces) to [Fontsource](https://github.com/fontsource/fontsource).
Kyle and I were discussing this privately and he stated that he is deprecating the Typefaces project and no longer maintaining it in favour of Fontsource. The latest commits on his repo should reflect that and we're working on making a couple last changes.
The two docs that were changed:
- https://www.gatsbyjs.com/docs/recipes/styling-css/#using-google-fonts
- https://www.gatsbyjs.com/docs/using-web-fonts/#using-google-fonts
=> chore(docs): replace typefaces with fontsource

packages/gatsby/cache-dir/dev-loader.js, packages/gatsby/cache-dir/ensure-resources.js, packages/gatsby/cache-dir/loader.js, packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap, packages/gatsby/src/redux/actions/internal.ts, packages/gatsby/src/redux/reducers/__tests__/__snapshots__/queries.ts.snap, packages/gatsby/src/redux/reducers/__tests__/queries.ts, packages/gatsby/src/redux/reducers/queries.ts, packages/gatsby/src/redux/types.ts, packages/gatsby/src/services/calculate-dirty-queries.ts, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/page-data.ts, packages/gatsby/src/utils/webpack.config.js, packages/gatsby/src/utils/websocket-manager.ts
This is final piece for implementation of query on demand feature flag
It relies on https://github.com/gatsbyjs/gatsby/pull/27939 ( so target branch is that until it gets merged )
=> feat(develop): add query on demand behind feature flag

packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/__tests__/__snapshots__/sample-site-for-experiment.ts.snap, packages/gatsby/src/utils/__tests__/sample-site-for-experiment.ts, packages/gatsby/src/utils/sample-site-for-experiment.ts
Includes a new utility for determanistically bucketing sites for choosing for experiments
=> feat(gatsby): invite (1%) of Gatsby users to try out develop ssr

packages/gatsby/cache-dir/__tests__/dev-loader-lazy.js, packages/gatsby/cache-dir/app.js, packages/gatsby/cache-dir/dev-loader.js, packages/gatsby/cache-dir/gatsby-browser-entry.js, packages/gatsby/cache-dir/loader.js, packages/gatsby/src/bootstrap/requires-writer.ts, packages/gatsby/src/utils/start-server.ts
=> fix(gatsby): rename env var for lazy dev bundling to make consistent with other experiments

packages/gatsby-source-filesystem/package.json, packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js, packages/gatsby-source-filesystem/src/create-remote-file-node.js, yarn.lock
This is a copy of https://github.com/gatsbyjs/gatsby/pull/27559 because that branch got deleted. Copying desc verbatim;
- - -
Uses [`fromFile()`](https://github.com/sindresorhus/file-type#filetypefromfilefilepath), [`fromBuffer()`](https://github.com/sindresorhus/file-type#filetypefrombufferbuffer) methods to infer filetype/extension from the file/buffer, if not specified.
This fixes an issue where `createRemoteFileNode` may fail on URLs without an extension in the path.
* N/A
* Fixes #21901
=> fix(gatsby-source-filesystem): Use new FileType methods to read file extension

packages/gatsby/src/services/initialize.ts
`GATSBY_EXPERIMENTAL_FAST_DEV=true gatsby develop`
=> feat(gatsby): enable all dev improvements with one env var

packages/gatsby/src/utils/__tests__/get-page-data.ts, packages/gatsby/src/utils/get-page-data.ts
This PR adds a timeout and retries to `getPageData` utility introduced in #27939 
Also adds missing test coverage.
All credits for this PR go to @pieh 😄
=> fix(gatsby): get-page-data should timeout gracefully

packages/gatsby-source-filesystem/package.json, packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js, packages/gatsby-source-filesystem/src/create-remote-file-node.js, yarn.lock
Backporting #28156 to the 2.27 release branch
(cherry picked from commit 616e9e3e264e58a750f94aaa428cc7803891ae44)
=> fix(gatsby-source-filesystem): Use new FileType methods to read file extension (#28156)

packages/gatsby/src/utils/__tests__/get-page-data.ts, packages/gatsby/src/utils/get-page-data.ts
Backporting #28131 to the 2.27 release branch
(cherry picked from commit c517b605b7572171607be140175be279748de7fa)
=> fix(gatsby): get-page-data should timeout gracefully (#28131)

packages/gatsby/src/services/initialize.ts
Backporting #28147 and #28166 to the upcoming release (together because they just update the same file and also the second fixes an issue in the first)
=>  feat(gatsby): enable all dev improvements with one env var (#28166)

.circleci/config.yml
we have few e2e cypress tests that don't upload results to cypress dashboard (which is really quite nice and it does often is useful - especially when alternative is to check terminal output in CircleCI)
=> chore: add cypress dashboard config to e2e tests that don't have it yet

packages/gatsby/src/services/run-page-queries.ts
This will show notice about query on demand opt-in feature when page query running takes longer than 2 minutes - very similar to https://github.com/gatsbyjs/gatsby/pull/28116
=> feat(gatsby): invite people with long page query running to try out query on demand feature

packages/gatsby/src/services/run-page-queries.ts
Backporting #28181 to the release branch
(cherry picked from commit 413888b61ad3014b9cd3fc9d846b5382a1ec82f9)
=> feat(gatsby): invite people with long page query running to try out query on demand feature (#28181)

packages/gatsby/cache-dir/loader.js, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
- typo on env var
- make sure page-data.json is created before SSRing
=> fix(gatsby): pull out a few bug fixes from https://github.com/gatsbyjs/gatsby/pull/28149/

packages/gatsby/cache-dir/loader.js, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
Backporting #28186 to the release branch
(cherry picked from commit f9fd11d319b3ec097cce6378ccedb86a7f2f8cc8)
=> fix(gatsby): pull out a few bug fixes from https://github.com/gatsbyjs/gatsby/pull/28149/ (#28186)

docs/reference/release-notes/v2.27/index.md
Release notes for v2.27. Please add anything you would like to mention from this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-2-27/docs/reference/release-notes/v2.27/index.md)
=> docs: release notes for v2.27

benchmarks/gabe-fs-mdx/gatsby-config.js
Enable the flag that was published in 2.7.0
=> chore(benchmarks): enable the lessBabel flag for fs-gabe-mdx

packages/gatsby-source-filesystem/src/extend-file-node.js
Fixes the race condition as discussed in #27984. @pieh: Please review.
=> fix(gatsby-source-filesystem): fix race condition when using `publicURL` field

packages/gatsby-plugin-sitemap/src/gatsby-node.js
Simple change to allow async operations in the serialize function. its already in an async block and runs on postbuild
=> feat(gatsby-plugin-sitemap): allow `serialize` plugin option to be async function

packages/gatsby-source-filesystem/src/extend-file-node.js
Backporting #28176 to the release branch
(cherry picked from commit 1abf65c335f397e9f891d25c4113ceee0e3fc138)
=> fix(gatsby-source-filesystem): fix race condition when using `publicURL` field (#28176)

packages/gatsby/src/services/initialize.ts
We want to see when this is used vs. just the individual flags
=> feat(gatsby): track usage of GATSBY_EXPERIMENTAL_FAST_DEV

packages/gatsby/src/state-machines/develop/index.ts, packages/gatsby/src/state-machines/waiting/index.ts, packages/gatsby/src/state-machines/waiting/types.ts
Our state machine ignores some of the `SOURCE_FILE_CHANGED` events. Namely, when it is in the `recompiling` phase and an event occurs **during** recompilation.
In this case, after recompilation, we mark source files as clean although they are not. As a result, we transition to `waiting` state but never recompile the bundle. And `webpack` waits when do this to resume watching files ([see those lines](https://github.com/webpack/webpack/blob/2efeb4b5787e868e69233aa9dec469c200fa3b2c/lib/Watching.js#L98-L105)).
And so `webpack` stops emitting `invalid` hook events on source file changes and our HMR gets completely stuck.
This PR does two things:
1. Marks source files as clean on recompilation start (vs. on done previously). This way if `SOURCE_FILE_CHANGED` event occurs during `recompilation` …
=> fix(gatsby): do not ignore source file changes during recompilation

packages/gatsby/src/services/initialize.ts
Backporting #28223 to the release branch
(cherry picked from commit 849b3bd4ec871ecb7596819940f8004ce9ec3793)
=> feat(gatsby): track usage of GATSBY_EXPERIMENTAL_FAST_DEV (#28223)

packages/gatsby/src/services/initialize.ts
Backporting #28223 to the release branch
(cherry picked from commit 2b494c34b5a8bb798fa1134a8a482165afc72fce)
=> feat(gatsby): bump % that get invited to try dev_ssr to 5% from 1% (#28232)

docs/docs/emotion.md
The next major of `gatsby-plugin-emotion` will be released somewhere next week (see #27981). In the meantime, the tutorial is still broken. This PR is just a temporary fix that works with the latest version of the emotion plugin.
We should revert it on the next stable publish.
P.S. Ideally, we should just publish docs from the release branch. Then docs will be on par with the current stable version.
#27981
#28063
=> docs: temporary fix to emotion tutorial

packages/gatsby-transformer-remark/src/extend-node-type.js
Add `getNodesByType()` to the other parameters so it is correctly passed through to Gatsby Remark plugins.
https://www.gatsbyjs.com/tutorial/remark-plugin-tutorial/
=> fix(gatsby-transformer-remark): ensure `getNodesByType()` is passed through

packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
There is a pretty complex set of conditions that causes Gatsby sorting to be skipped. Those are:
1. Run one query with `regex` filter without sorting
2. This filter must be run against a field **without a custom resolver**
3. Run the second query with the same `regex` filter but now also with sorting
4. The sorting must run against a field **with custom resolver**
(this situation is demonstrated in the added test)
The first query adds nodes to the fast filters cache. The second query fetches results from this cache. But when we get results from the cache we bypass `__gatsby_resolved` assignment (assuming it was set when we originally added nodes to cache).
But it was not set because of this line:
https://github.com/gatsbyjs/gatsby/blob/70b81a6e825c583387728c02d83a70e0d4e16072/packages/gats …
=> fix(gatsby): fix materialization edge case

packages/gatsby-plugin-page-creator/package.json, packages/gatsby-plugin-page-creator/src/gatsby-node.ts, yarn.lock
`gatsby-plugin-page-creator` has a different version of `graphql` than the rest of gatsby. This causes multiple versions of GraphQL to be installed and produces various related errors.
This PR removes `graphql` from dependencies of `gatsby-plugin-page-creator`. Instead, we import directly from `gatsby/graphql` to use the exact same version of graphql.
=> fix(gatsby-plugin-page-creator): use graphql from gatsby

packages/gatsby/src/schema/__tests__/node-model.js, packages/gatsby/src/schema/node-model.js
Backporting #28244 to the release branch
(cherry picked from commit 807589bf759b01fe5a5235282bbcdc5a9a969265)
=> fix(gatsby): fix materialization edge case (#28244)

packages/gatsby-transformer-remark/src/extend-node-type.js
Backporting #28218 to the release branch.
(cherry picked from commit 7867897c5cc4f627a4fb91c939b24d884497ee20)
=> fix(gatsby-transformer-remark): ensure `getNodesByType()` is passed through (#28218)

packages/gatsby/src/state-machines/develop/index.ts, packages/gatsby/src/state-machines/waiting/index.ts, packages/gatsby/src/state-machines/waiting/types.ts
Backporting #28237 to the release branch
(cherry picked from commit 41488778ddcb102a5147b7acfb9631565ede958e)
=> fix(gatsby): do not ignore source file changes during recompilation (#28237)

packages/gatsby/cache-dir/ensure-page-component-in-bundle.js
Increase timeout for loading a component from 5 seconds to 30 seconds. The only reason for this is to avoid having ever churning XHR requests from bad requests but many pages will take 5-20s to compile so the lower timeout hurt UX
=> fix(gatsby): Increase timeout for fetching component to 30 seconds

packages/create-gatsby/src/init-starter.ts, packages/gatsby-cli/src/init-starter.ts, scripts/publish-starters.sh
The current start publish script has a syntax error. This also revealed an issue where `yarn import` breaks in yarn 2, and is [considered a bad idea](https://github.com/gatsbyjs/gatsby/issues/28238#issuecomment-732506607) anyway. This PR fixes the publish script and removes the import step from gatsby-cli and create-gatsby
Fixes #28238
=> fix: Fix starter publish and scripts

packages/gatsby-source-filesystem/package.json
Currently it's "Gatsby plugin which parses files within a directory for further parsing by other plugins" which is rather opaque and CS-y.
This PR changes it to better describe how someone would actually use it — "build websites with data from your local filesystem"
=> fix(gatsby-source-filesystem): Improve the description

packages/gatsby-telemetry/src/repository-id.ts
This is quite weird issue - sometimes on Windows when using default "Command prompt" there would be cmd.exe windows popping up and immediately hiding (see videos in #28233 both from issue author and from me).
I used https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to track down what those actually try to execute and found that it's our repository id getter function:
`childProcess.execSync` (and all the other similar too) have `windowsHide` option that is disabled by default, which I flip here to handle the issue.
Seperate issue is that we call it multiple times - just from different processes, so memoization we have in https://github.com/gatsbyjs/gatsby/blob/e7976580111c4baa15db8170abf2ae792f94bb9c/packages/gatsby-telemetry/src/telemetry.ts#L176-L181 doesn't address cross …
=> fix(gatsby-telemetry): use windowsHide to not show windows command prompt windows

packages/gatsby/src/redux/reducers/visited-page.ts
Always compile the home page (most people will visit it so it's a worse experience to immediately have to wait for it to finish)
=> fix(gatsby): Always compile the index page (if it exists)

packages/gatsby/src/cache/cache-fs.ts
The warning was shown whenever a lock got older than 10s and ignored but this turned out to be quite noisy.
=> chore(gatsby): Only warn for cache lock timeout once

.circleci/config.yml
Currently our e2e pnp tests pin yarn 2 versions to quite outdated rc version and recently started failing constantly. This is due to some patches that needs to be applied to typescript to work with PnP. I'm very light on details here, check comments I linked below. At the time comments were made patch was already updated, but wasn't released yet (it might have been already released, it might not - TBD, will see how tests run on this PR I guess and we will be able to rerun them periodically if it wasn't released yet).
Removing pinning was suggested by Yarn 2 maintainers (in one of linked comments)
This was PR unrelated to PnP, but comments there are actually relevant
https://github.com/gatsbyjs/gatsby/pull/28218#issuecomment-732422940 …
=> chore(e2e-pnp): don't pin berry version

packages/create-gatsby/src/init-starter.ts, packages/gatsby-cli/src/init-starter.ts, scripts/publish-starters.sh
Backporting #28260 to the release branch
(cherry picked from commit f6417dd58360bd3e243a955c413dd46138608af6)
=> fix: Fix starter publish and scripts (#28260)

packages/gatsby/src/redux/reducers/visited-page.ts
Backporting #28265 to the release branch
(cherry picked from commit f75e358a79a104b597a97993088b27268a9a9242)
=> Always compile the index page (if it exists) (#28265)

packages/gatsby/cache-dir/ensure-page-component-in-bundle.js
Backporting #28264 to the release branch
(cherry picked from commit bd0a7f4d717c49306c968fd99a3b2e6466dada15)
=> Increase timeout to fetching component to 30 seconds (#28264)

packages/gatsby-telemetry/src/repository-id.ts
Backporting #28258 to the release branch
(cherry picked from commit e416368c42971a77ae7059376d764f17032f62ff)
=> fix(gatsby-telemetry): use windowsHide to not show windows command prompt windows (#28258)

packages/gatsby-cli/package.json, yarn.lock
The update-notifier package had a bug in earlier versions where some users didn't see version numbers to update to
and from as well as the update command, instead they saw template variables.
Fixes #28201.
=> chore(gatsby-cli): Bump up update-notifier version to 5.0.1

docs/docs/adding-analytics.md
Hey, all! 👋   This PR adds [Vercel Analytics](https://vercel.com/blog/gatsby-analytics) to the analytics documentation as an option. This allows Gatsby users to track [Core Web Vitals](https://vercel.com/docs/analytics/overview#web-vitals) over time with zero configuration.
For more information, check out [this post](https://vercel.com/blog/gatsby-analytics).
Current documentation: https://www.gatsbyjs.com/docs/adding-analytics/#other-gatsby-analytics-plugins
=> Add Vercel Analytics to documentation.

docs/docs/conditional-page-builds.md
Hi everyone, this PR fixes the `Incremental Builds` link which was giving a 404 error in the referenced issue.
Please review it
Fixes #28175
=> chore(docs): Fix link to inc builds

packages/gatsby-dev-cli/src/utils/check-deps-changes.js
Can't use gatsby-dev-cli with new package otherwise
=> fix(gatsby-dev-cli): Correctly catch 404s from NPM when a package hasn't been published yet

docs/docs/gatsby-cli.md, integration-tests/gatsby-cli/__tests__/new.js, packages/gatsby-cli/src/create-cli.ts
We added this feature flag in #27954. Once we feel comfortable releasing the new interactive `gatsby new` experience for all our users we should merge this PR to remove the feature flag and update the docs for `gatsby new`!
[ch19029]
=> feat(gatsby-cli): remove feature flag for new interactive `gatsby new` experience

packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
Fixing the missing placeholder background color for constrained and fluid in gatsby-plugin-image.
To test, modify the following query and change "CONSTRAINED" by "FLUID" or "FIXED"
```js
export const query = graphql`
query {
file(relativePath: { eq: "gatsby-icon.png" }) {
childImageSharp {
gatsbyImageData(
layout: CONSTRAINED
maxWidth: 256
height: 125
placeholder: DOMINANT_COLOR
)
}
}
}
`
```
=> fix(gatsby-plugin-image): Fix placeholder bg color

packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
I was occasionally seeing SSR errors where the page component wasn't found but which
would be fixed when I refreshed. It turns out I'd setup a timeout for waiting
for the bundle but hadn't handled this.
5*300ms == 1.5s which is a relatively short-timeout but SSR isn't generally needed so the right tradeoff seems
to not make people wait.
=> fix(gatsby): Actually handle timeout while waiting for page component to be bundled

docs/docs/configuring-usage-with-plugin-options.md
changes:
- add file extension
- code block language `text`
- add quotation marks to `"text"` (like on on other places with string in same doc)
- #27337 `docs: document pluginOptionsSchema` 
- #27541 `docs(plugins): more in-depth pluginOptionsSchema documentation`
=> fix(docs): document pluginOptionsSchema - add file extension, code block language, quotation marks

docs/docs/deploying-to-render.md
The flow for creating static sites in the Render dashboard was recently simplified, as reflected in these changes. See https://render.com/docs/deploy-gatsby.
=> chore(docs): Update Deploying to Render guide

e2e-tests/gatsby-static-image/cypress/integration/intesection-observer.js, e2e-tests/gatsby-static-image/cypress/integration/native-lazy-loading.js, e2e-tests/gatsby-static-image/src/pages/lazy-loading.js, packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Add E2E tests for native image lazy loading and intersection observer loading
=> test(gatsby-plugin-image): add E2E tests for native and intersection obs

packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Fix for incorrect CSS in image. Fixes https://github.com/gatsbyjs/gatsby/discussions/28311
=> fix(gatsby-plugin-image): Correct img CSS

e2e-tests/gatsby-static-image/cypress.json, e2e-tests/gatsby-static-image/cypress/integration/intesection-observer.js
Using mocha assertions instead of jest ones in Cypress tests 🤦🏻
=> fix(test): wrong assert method for plugin-image

packages/gatsby-plugin-sharp/src/index.js
fix joi error when image conversion fails
previously just passing the error object would produce the following joi error
```
Failed to validate error Error [ValidationError]: "name" is not allowed
at Object.exports.process (/myproject/node_modules/@hapi/joi/lib/errors.js:202:19)
at internals.Object._validateWithOptions (/myproject/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
at internals.Object.validate (/myproject/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
at constructError (/myproject/node_modules/gatsby-cli/lib/structured-errors/construct-error.js:52:32)
at Reporter.error (/myproject/node_modules/gatsby-cli/lib/reporter/reporter.js:135:59)
at Reporter.panic (/myproject/node_modules/gatsby-cli/lib/reporter/reporter.js:75:34)
at Object.panic …
```
=> fix(gatsby-plugin-sharp): avoid joi validation error when using reporter.panic

packages/gatsby-plugin-sharp/src/index.js
Backporting #28291 to the 2.27 release branch
(cherry picked from commit 231cf9f8c0ad077c8c1324a5c89c791a2da775a1)
=> fix: avoid joi validation error when using reporter.panic (#28291)

packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Backporting #28317 to the 2.28 release branch
(cherry picked from commit bfd86dfc5bdad881e9b4363fc00c4186e0124833)
=> fix(gatsby-plugin-image): Correct img CSS (#28317)

packages/create-gatsby/src/index.ts, packages/create-gatsby/src/site-metadata.ts
Add the created site's name to `siteMetadata`. Currently this is the folder name chosen by the user. We might want to prompt separately for the human-readable name, so this is nicer-looking.
[ch19597]
=> feat(create-gatsby): Add name to site metadata

packages/gatsby-source-shopify/src/__tests__/__snapshots__/index.js.snap, packages/gatsby-source-shopify/src/nodes.js
This adds numeric variant of `price` field called `priceNumber` (better naming suggestion welcomed). We can't modify type of existing field as users might rely on it being string, so this seems only backward compatible way.
The change result in following:
`price` is current way of getting price (and it is a string) - you can see that first part sorted by `price` result following order `"19.99"` < `"5.99"` < `"799.00"`.
`priceNumber` is the new field that cast to a number and sorting by it allow for proper "sorting by price": `5.99` < `19.99` < `799.00`
Closes #28215
=> feat(gatsby-source-shopify): add "priceNumber" field that will allow for proper sorting

examples/using-drupal/gatsby-config.js, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/handle-flags.ts
=> feature(gatsby): Warn when there's unknown flags in gatsby-config.js & suggest fixes to potential typos

.circleci/config.yml
Similar to https://github.com/gatsbyjs/gatsby/pull/28169 this just adds needed env var keys to be able to upload cypress run results to cypress dashboard for fast refresh variant of our e2e dev runtime tests
=> chore: add cypress dashboard config to e2e dev runtime for fast refresh variant

packages/gatsby-plugin-manifest/README.md
https://github.com/gatsbyjs/gatsby/issues/28350 showed that another helpful guide for the icon_options could be linked
=> chore(docs): Add note about icon_options

packages/gatsby-plugin-manifest/README.md
Current link of the `pluginOptionsSchema.js` redirects to a non-existent (404) page at [`gatsby-plugin-manifest`](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/#plugin-options-validation).
This commit fixes and points it to the actual file on the repository.
This issue can be found at https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/#plugin-options-validation.
None found yet!
=> chore(gatsby-plugin-manifest): Update pluginOptionsSchema link

packages/create-gatsby/src/index.ts, packages/create-gatsby/src/init-starter.ts
This fixes a number of bugs, edge cases and papercuts in the `create-gatsby`/`gatsby new` process.
1. Fixes bug where git repo was left dirty, by moving the git init after the package install
2. Fixes a bug where whitespace was not trimmed from the created directory name
3. Improves feedback when installing, by not silencing the npm progress bar
4. Sets the site name in package.json [ch19597]
5. Sets the author's name in package.json if it's available from git (sorry, @laurieontech : you're not the author of every site anymore)
6. Replaces the starter's description in the package.json with a more relevant one
6. More consistency in logging output
=> fix(create-gatsby): Improve install

packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
Backporting #28325 to 2.27 release
(cherry picked from commit a9f9a23705edaf393466b30bc89546b59de59158)
=> fix(gatsby): handle in dev-ssr when a page is deleted (#28325)

packages/gatsby/src/services/run-page-queries.ts
Backporting #28327 to the 2.27 release branch
(cherry picked from commit a84f78e075901d3195e4a81a949aaaa48979ff5b)
=> chore(gatsby): Invite more people to try QUERY_ON_DEMAND (#28327)

packages/gatsby-source-contentful/src/gatsby-node.js
The part first builds up a set of existing names and then loops through the received data to find new data.
A site I was testing with had n at 80k elements. So this was doing an unguided search through 80k elements for 80k times.
This little fix literally drops this 5 minute step in incremental builds (and perhaps others) for that case, down to be sub-second.
=> perf(gatsby-source-contentful): fix unguided search in expensive loop

e2e-tests/development-runtime/content/query-data-caches/adding-static-query-A-to-B-to-A-link.json, e2e-tests/development-runtime/cypress/integration/functionality/query-data-caches.js, e2e-tests/development-runtime/src/components/query-data-caches/adding-static-query-blank.js, e2e-tests/development-runtime/src/components/query-data-caches/adding-static-query-with-data.js, e2e-tests/development-runtime/src/pages/query-data-caches/adding-static-query-A-to-B-to-A-link/page-A.js, e2e-tests/development-runtime/src/pages/query-data-caches/adding-static-query-A-to-B-to-A-link/page-B.js, packages/gatsby/cache-dir/dev-loader.js, packages/gatsby/cache-dir/ensure-resources.js, packages/gatsby/cache-dir/loader.js, packages/gatsby/src/utils/websocket-manager.ts
Currently we don't reprocess page-data's `staticQueryHashes` array in develop when those change, which means if we have cached page-data we will not handle fetching any additions to that array. If the new static queries are not cached already this results in "Cannot fetch static query result", which can be fixed by refresh (but is bad experience of course).
This will mark cached pageData entries as stale which will cause dev runtime to refetch it next time `loadPage` is called instead of using (now stale) cached result and run all the regular processing (which will fetch static queries that are not fetched/cached yet).
This is not complete fix however. It doesn't exactly fix the problem when `staticQueryHashes` changed for a page user currently view in the browser ( note TODO comments I …
=> fix(develop): emit stale page data messages when staticQueryHashes change

docs/reference/release-notes/v2.27/index.md
fix link to umbrella issue + mention it didn't work out
=> Update release notes

packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/handle-flags.ts
People who are using one flag are probably more likely to want to know to know about other flags and try them out as well.
Not sure how well this will scale but we need a way to increase visibility of flags & this is a good way right now.
h/t for idea to @ascorbic
=> feat(gatsby): people who are using a flag, invite them to try out other flags

docs/docs/gatsby-config.md
Flags are being released in 2.28 and needs docs!
=> feature(docs): Add mention of flags to the gatsby-config.js doc page

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/components/layout-wrapper.tsx, packages/gatsby-plugin-image/src/components/static-image.server.tsx, packages/gatsby-plugin-image/src/components/static-image.tsx, packages/gatsby-plugin-image/src/image-utils.ts, packages/gatsby-plugin-image/src/utils.ts, packages/gatsby-plugin-image/tsconfig.json
This fixes the interface for StaticImage props, and adds `propTypes` validation. Previously doing something like passing a string for "width" would lead to the image not resolving, rather than giving a helpful error. This now also enforces proptypes based on the layout, e.g. requiring width and forbidding maxWidth in fixed layout images. It also stops passing through all props to the DOM element, as that was causing react errors
=> fix(gatsby-plugin-image): Fix StaticImage props interface and add propTypes 

packages/gatsby/src/bootstrap/requires-writer.ts, packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
The listeners were gettiing reattached on every SSR.
Also... ssr changes weren't getting compiled w/o a save. So this fixes two bugs.
=> fix(gatsby): move starting dev-ssr listener inside function & only init listeners once

scripts/assert-changed-files.sh
Our script asserting if anything related changed has flaw that it never allow tests to run on master - because it compares current branch to master and master compared to master shows no changes ;)
=> fix(assert-changed-files): don't skip running tests on master

packages/create-gatsby/src/__tests__/plugin-options-form.ts, packages/create-gatsby/src/plugin-options-form.ts
Snapshotting output of `makePluginConfigQuestions` and add a tiny refacto
=> test(create-gatsby): snapshot plugins-options-form and tiny refactoring 

scripts/assert-changed-files.sh
Reverts gatsbyjs/gatsby#28400
That seemed to cause very weird issues for windows tests for PRs that don't contain the change itself ( see https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/54414/workflows/4c08227f-9226-42e7-b8bb-1532a7ae15a2/jobs/570991 for example ):
```
#!bash.exe
./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*"
error: unable to create file scripts/assert-changed-files.sh: Permission denied
Branch has conflicts with master, rolling back test.
fatal: There is no merge to abort (MERGE_HEAD missing).
error: unable to create file scripts/assert-changed-files.sh: Permission denied
fatal: Could not reset index file to revision 'HEAD@{1}'.
271 file(s) matching 'packages/*|(e2e|integration)-tests/*|.circleci/*'; continuing.
CircleCI …
```
=> Revert "fix(assert-changed-files): don't skip running tests on master"

packages/create-gatsby/src/__tests__/init-starter.ts, packages/create-gatsby/src/index.ts, packages/create-gatsby/src/init-starter.ts, packages/create-gatsby/src/utils.ts
Adding some tests for init starter
=> test(create-gatsby): some for init starter

examples/using-drupal/gatsby-config.js, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/handle-flags.ts
Backporting #28326 to the 2.28 release branch
(cherry picked from commit c4978e948c5b0cebf85ef9af62da523169994bf9)
=> feature(gatsby): Warn when there's unknown flags in gatsby-config.js & suggest fixes to potential typos (#28326)

integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap, packages/gatsby/src/utils/__tests__/__snapshots__/develop-html-route.ts.snap, packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/dev-ssr/develop-html-route.ts, packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js, packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
=> feature(gatsby): let users skip out of dev SSR

packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/hooks.ts
We expect breaking changes with CSS for users with element selectors, but those passing a classname should expect similar behavior. Adding this rule back in will make the new component more compatible.
=> fix(gatsby-plugin-image): Add overflow hidden back to wrapper CSS

e2e-tests/development-runtime/cypress/integration/navigation/linking.js, e2e-tests/development-runtime/src/pages/navigation-effects.js, packages/gatsby/cache-dir/navigation.js
Fix for issue: [Using navigate() function with a state change doesn't re-render the page #27617](https://github.com/gatsbyjs/gatsby/issues/27617)
Currently we are comparing location props in the `RouteUpdates` component to see if it needs to be updated, however because we are comparing props we need to also check if the location state has been changed as well.
We can do this by:
1. Checking if it is equal to null or not
2. Checking if the state `key` property has changed between the previous and next set of props.
The `key` prop is always added to each route state update via `@reach/router` [here](https://github.com/reach/router/blob/master/src/lib/history.js#L79).
**This seems to be part of a bigger issue where in an ideal world we should probably just leave these comparisons to the …
=> fix(gatsby): re-render route when location state changes

packages/gatsby/src/query/graphql-runner.ts
Before this PR `GraphQL Query` trace was reporting incorrect numbers. It was always reporting `0-5ms` because we didn't wait for the query promise to resolve. So the tracer was ending immediately after the `execute()` call.
=> fix(gatsby): correct tracing for GraphQL queries

packages/gatsby/cache-dir/navigation.js
`getSavedScrollPosition()` in `shouldUpdateScroll` doesn't pass `key` to SessionStorage, so the storage can't find the stored position.
I pass `args.key` as `key` so that SessionStorage can generate the correct key. 
relates to #27349
=> fix(gatsby): scroll restoration issue in browser API

docs/reference/release-notes/v2.28/index.md
Just some updates to 2.28 release notes.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/20aa9c1899b0a9ecd80d6706977ac45287a9091e/docs/reference/release-notes/v2.28/index.md)
=> docs: note about emotion major bump, slightly restructured notes

packages/gatsby/src/utils/start-server.ts
=> fix: PRESERVE_WEBPACK_CACHE notice should actually show after 30 seconds

docs/docs/emotion.md
After `gatsby-plugin-emotion@5.0.0` is published the temporary documentation fix from https://github.com/gatsbyjs/gatsby/pull/28248 is not needed anymore.
This reverts commit b3468048
=> Revert "docs: temporary fix to emotion tutorial (#28248)"

packages/gatsby/src/query/index.js
In followup to https://github.com/gatsbyjs/gatsby/pull/28377
This folds three loops (filter, map, map) over the query ids into a single loop that does 'em all.
=> chore(gatsby): fold three loops into one

packages/gatsby/src/schema/schema.js
These two cases used `await` while waiting for a function that didn't return a promise in the first place.
In the second case, the resolver was made sync because it didn't need to be async anymore.
=> chore(gatsby): remove `async/await` where not needed

packages/gatsby-source-contentful/src/extend-node-type.js
This adds a `reject()` case for when the disk write fails.
=> chore(gatsby-source-contentful): trap base64 disk write

packages/gatsby-source-contentful/src/extend-node-type.js
This PR does three things twice;
- Drop a `Promise.resolve` for a value that is not a promise in a function (resolver) that can but does not need to return a promise
- Makes the resolver a proper method, rather than an arrow property
- Drop a few cases of `_.get` in favor of actual `?.` syntax
=> chore(gatsby-source-contentful): drop unnecessary promise, _.get

packages/gatsby/src/query/queue.ts
I think it looks nicer this way? I don't think it changes anything else. I don't think better-queue cares about the return value of the `process` method (promise or otherwise) since it's driven by the callback.
=> chore(gatsby): refactor into await syntax

packages/gatsby-source-contentful/src/extend-node-type.js
Before this was doing `_.pickBy(obj, _.identity)`, which is essentially a `.filter(Boolean)`. But `qs` will already ignore `undefined` properties, whether they exist or not, so we don't really need to jump through those hoops. So that's what I've done.
=> chore(gatsby-source-contentful): simplify url arg generation

packages/gatsby-source-contentful/src/extend-node-type.js
Drops the last remaining cases of lodash from this file.
See inline comments for clarification
=> chore(gatsby-source-contentful): drop last usages of lodash

packages/gatsby-transformer-remark/src/extend-node-type.js
Trivial change to not generate the key twice
=> chore(gatsby-source-contentful): cache the cache key

packages/gatsby-source-contentful/src/extend-node-type.js
Currently the base64 fetch will prefer to read from local cache if the url is known, or do a remote fetch if the url is unknown. It does not do an in-flight check which means the same url could be scheduled and fetched multiple times, as long as one has not completed. This applies to remote fetch and local cache fetches.
This PR introduces two caches (separate commits):
- an in flight cache containing any request that has not resolved
- a resolved cache, containing the payload of resolved requests
The function will now prefer to return the data sync, from the resolved cache. If the url is not known there then it will check the in flight cache. This cache may contain the promise if it is still in flight, or if the request rejected (it will not retry). If that cache doesn't have it then the …
=> perf(gatsby-source-contentful): prevent redundant fs/remote fetches for base64

docs/docs/why-gatsby-uses-graphql.md
A brief explanation of what created `allProductsJson` has been added. It refers to the `gatsby-transformer-json` plugin.
The change is related to this doc: https://www.gatsbyjs.com/docs/why-gatsby-uses-graphql/
Please can @gatsbyjs/documentation review this PR?
Fixes #15235
=> [docs][guides] improvements to Why Gatsby Uses GraphQL #15235

docs/tutorial/ecommerce-tutorial/index.md
Gatsby E-commerce Tutorial codeblock [Add the Stripe source plugin](https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/ecommerce-tutorial/index.md#add-the-stripe-source-plugin) indicates config should include `STRIPE_SECRET_KEY` but does not mention `STRIPE_PUBLISHABLE_KEY`.
For users supplying *only* the `STRIPE_SECRET_KEY` (without also adding `STRIPE_PUBLISHABLE_KEY`), `gatsby-source-stripe` fails to load `allStripePrice` as a field to be tested in GraphiQL; a browser pointed at http://localhost:8000 responds with:
_Error: There was an error in your GraphQL query: Cannot query field "allStripePrice" on type "Query". Did you mean "allSitePage"?_
With this one-liner we can avoid newcomers being put off by an ambiguous instruction being given in tutorial codeblocks.
Fixes #28385
=> Tell user to supply BOTH keys in .env.development for Gatsby E-commerce Tutorial.

packages/create-gatsby/src/__tests__/install-plugins.ts, packages/create-gatsby/src/install-plugins.ts, packages/create-gatsby/src/require-utils.ts
Unit test to catch and lock error on the the install plugins step of the create-gatsby cli
=> test(create-gatsby): add test for handling errors in install plugins

package.json, yarn.lock
The transitive dependency `extract-files@9.0.0` has a `engines` field set that is incompatible with our minimum supported node version. This adds a resolutions field to pin it to 8.1.0, which is API-compatible. This won;t fix things for npm, but will at least let the monorepo build.
=> fix(gatsby-source-graphql): Pin resolution of extract-files

packages/gatsby-plugin-sharp/src/gatsby-node.js
Found this on my blog. Also reported in the umbrella issue https://github.com/gatsbyjs/gatsby/discussions/27603#discussioncomment-139695
=> fix(gatsby-plugin-sharp): decode URL so it matches the cache key

package.json, packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js, scripts/e2e-test.sh, yarn.lock
Revert #28459, as it was breaking gatsby-source-graphql. Instead add the `--ignore-engines` flag to the dev cli so that e2e tests can at least run
=>  fix: Back out resolutions, and add ignore-engines to dev cli

starters/gatsby-starter-minimal/package.json
I was missing this when using `npm init gatsby` :)
=> chore(gatsby-starter-minimal): Add `serve` script

packages/gatsby/cache-dir/api-ssr-docs.js, packages/gatsby/index.d.ts
Add missing `bodyComponent` to `replaceRenderer` typedefs and api docs. Fixes #28454 28454
=> fix(gatsby): Add bodyComponent to replaceRenderer args

packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Adds support to plugin options for share_target, which is a draft supported by Chrome. I have only included the keys in [the draft spec](https://w3c.github.io/web-share-target/), but have allowed unknown keys because Google already seems to be adding more.
Fixes #28455
=> feat(gatsby-plugin-manifest): Add support for share_target

package.json
Replace backticks as they spawn a subshell on mac os and actually run those commands within backticks.
=> chore: fix publish script

package.json, packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js, scripts/e2e-test.sh, yarn.lock
Backporting #28459 and #28464 to the 2.28 release branch
(cherry picked from commit 4ef4bf5)
(cherry picked from commit 4add7d2)
=> Backport #28459 and #28464 to 2.28 release branch

packages/create-gatsby/src/components/select.js
=> fix(create-gatsby): Remove race condition/duplicate render

packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.ts, packages/gatsby/src/utils/webpack-utils.ts
This PR fixes a bug when `gatsby develop` breaks in the unfortunate (and very rare) edge case when the `eslint` loader is removed from the webpack config (in site's `onCreateWebpackConfig`).
Before this PR we assume eslint loader always exists. This PR removes this assumption and makes the failing code more robust.
Fixes #28429
=> fix(gatsby): do not fail in develop when eslint loader is removed

packages/gatsby/src/utils/dev-ssr/develop-html-route.ts, packages/gatsby/src/utils/develop-preload-headers.ts, packages/gatsby/src/utils/start-server.ts
Development runtime currently has network request waterfall where we wait to fetch critical resources to render a page until `common.js` is fetched, parsed and executed which triggers fetching those resources.
Adding preload header allow us to avoid network request waterfalls
This PR:
- master - https://www.webpagetest.org/result/201203_DiFG_cd254e0dc1016ba4683a1aa8faaa54b3/
- this PR - https://www.webpagetest.org/result/201203_DiH5_55548d47e77b4bc91427d4c43d01215a/
Running
```
performance.getEntriesByType('paint').find(entry => entry.name === 'first-contentful-paint').startTime
```
in dev tools console (with `slow-3g` throthling) result in:
- master: 20529.959999985294
- this PR: 16223.045000020647
(above was from single runs, so take it with grain of salt)
[ch20207]
=> feat(gatsby): add preload headers for critical resources so those can started fetching before common.js is fetched

packages/gatsby-page-utils/package.json, packages/gatsby-page-utils/src/ignore-path.ts, packages/gatsby-page-utils/src/index.ts, packages/gatsby-plugin-page-creator/README.md, packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts, packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts, packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts, packages/gatsby-plugin-page-creator/src/derive-path.ts, packages/gatsby-plugin-page-creator/src/gatsby-node.ts
Fixes https://github.com/gatsbyjs/gatsby/discussions/28470
We use [slugify](https://github.com/sindresorhus/slugify) in our [derivePath](https://github.com/gatsbyjs/gatsby/blob/b6b5207979370c244e32977c87242064f067842c/packages/gatsby-plugin-page-creator/src/derive-path.ts#L82) function to generate the path for every File System Route API page. Since people are able to choose their own path when using `createPages` API we should also expose the options for this functionality to offer the most flexibility.
With this PR I'm simply passing the option through to the derivePath function. As it's a bit nested a bunch of functions needed to be changed.
The TS types for the `IOptions` interface on `createPagesStatefully` were also incorrect, so I had to enable type generation on our …
=> feat(gatsby-plugin-page-creator): Add slugify option

packages/gatsby/src/schema/infer/__tests__/infer.js, packages/gatsby/src/schema/infer/add-inferred-fields.js, packages/gatsby/src/schema/print.js
This PR addresses a deprecation warning displayed when the type definition is missing inferred extension. Currently, the warning text is a bit confusing:
```
Deprecation warning - adding inferred resolver for field Test.date.
In Gatsby v3, only fields with an explicit directive/extension will get a resolver.
```
After this PR the warning text will be this:
```
Deprecation warning: adding inferred extension `dateformat` for field `Test.date`.
In Gatsby v3, only fields with an explicit directive/extension will be resolved correctly.
Add the following type definition to fix this:
type Test implements Node {
date: Date @dateformat
}
https://www.gatsbyjs.com/docs/actions/#createTypes
```
=> fix(gatsby): better text for missing inferred extension

packages/gatsby/src/schema/extensions/__tests__/child-relations.js, packages/gatsby/src/schema/schema.js
This PR addresses a confusing deprecation warning when the `@childOf` directive is not set for some parent. Warning text before this PR:
```
The type `Parent` does not explicitly define the field `childChild`.
On types with the `@dontInfer` directive, or with the `infer ` extension set to `false`, automatically adding fields for
children types is deprecated. In Gatsby v3, only children fields explicitly set with the `childOf` extension will be added.`
```
After this PR:
```
Deprecation warning: In Gatsby v3 field `Parent.childChild` will not be added automatically
because type `Child` does not explicitly list type `Parent` in `childOf` extension.
Add the following type definition to fix this:
type Child implements Node @childOf(types: ["Parent"]) {
id
} …
```
=> fix(gatsby): improve deprecation text for missing childOf directive

packages/gatsby/src/commands/build.ts
Plugins can currently run queries in `onPostBuild` if they like. If these queries trigger side effects like jobs, they are currently _not_ awaited in `onPostBuild`. This is a bug. 
We fix this by waiting till the jobs queue is empty. 
An example of a community plugin that does this is https://github.com/dominicfallows/gatsby-plugin-json-output
=> fix(gatsby): Wait for jobs to complete in onPostBuild

packages/gatsby/package.json, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/services/run-page-queries.ts, packages/gatsby/src/services/start-webpack-server.ts, packages/gatsby/src/utils/__tests__/__snapshots__/show-experiment-notice.js.snap, packages/gatsby/src/utils/__tests__/show-experiment-notice.js, packages/gatsby/src/utils/show-experiment-notice.ts, packages/gatsby/src/utils/start-server.ts
Also track when we show invites so we get a sense of how often that is happening
=> fix(gatsby): show multiple invites together & at end where people are more likely to see them

packages/gatsby/src/commands/develop-process.ts
This justs add `/` (index) page for list of queries to run initially. Main reason for doing so is that there is very high chance of user visiting it as we do print following message when dev server boots up that make it very likely for user to visit it:
```
You can now view [name-of-site] in the browser.
⠀
http://localhost:8000/
```
[ch20215]
=> chore(query-on-demand): prerun query for homepage for initial run

packages/gatsby-remark-images/src/__tests__/gatsby-node.js, packages/gatsby-remark-images/src/gatsby-node.js
Currently plugin validation schema only supports `true/false`, but plugin does support setting detailed settings with object notation too - https://github.com/gatsbyjs/gatsby/blob/70b81a6e825c583387728c02d83a70e0d4e16072/packages/gatsby-remark-images/src/index.js#L262
Fixes #28217
=> fix(gatsby-remark-images): allow tracedSVG to accept object with settings

packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-transformer-documentationjs/src/__tests__/fixtures/code.js, packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js, packages/gatsby-transformer-documentationjs/src/gatsby-node.js
I want to display the description and some examples on how to use components via `gatsby-transformer-documentationjs`
Here is how it would look like in one of my components:
```js
/**
* Amazing description
*
* @example <caption>My custom example title</caption>
* doSth()
* ...
*/
export default function SomeComponent({
...
```
See: https://jsdoc.app/tags-example.html
If I now try to get the caption value of the example via GraphQL, I get the following:
```
String cannot represent value: { type: "root", children: [[Object]], position: { start: [Object], end: [Object] } }
```
Means: Captions support is at the moment broken, if your code contains captioned examples and you try to query them, it will fail.
We expect a string for `examples.caption`: …
=> fix(documentationjs): fix example caption string

packages/gatsby/src/schema/resolvers.ts
Drop the `async` keyword from the `wrappingResolver` that wraps all resolvers passed on to graphql. This keyword _forces_ the return value to be a promise, injecting tiny delays in each call. Most of the time you wouldn't notice these but at scale they add up.
In this case a large site was triggering the link resolver 35 million times. Only 1.5 million times did the wrapped resolver return a promise. And graphql will properly deal with promises vs non-promises. So we can drop the keyword.
The PR also updates the `linkResolver` to take the fast path (when target key is `id` and the resolver is our own `defaultResolver`) sync rather than also force it to be async. The `defaultResolver` already has no `async` keyword.
Doing so drops roughly 5-10% from the runtime of the site I was testing …
=> perf(gatsby): do not force resolvers to be async

packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap, packages/gatsby/src/redux/reducers/__tests__/queries.ts, packages/gatsby/src/redux/reducers/queries.ts, packages/gatsby/src/utils/__tests__/get-page-data.ts, packages/gatsby/src/utils/get-page-data.ts, packages/gatsby/src/utils/page-data.ts
We currently have potential dead lock situation as we skip writing `page-data` (in query on demand only!) when query is marked as dirty. This means that `getPageData` can not resolve (or rather resolve with stale data due to timeout guards) if:
- page query did run but didn't flush yet and query was marked as dirty at some point after running query and before flushing
This PR only skips flushing page-data if query didn't run yet ( `FLAG_DIRTY_NEW_PAGE` check instead of checking if query is dirty for whatever reason) and triggers another run of `doGetPageData` that checks if query is dirty / running / pending to trigger another run if it's in fact still dirty after flushing page-data.
I'm uncertain about not touching part that does emit websocket message - in this case we **might not** …
=> fix(query-on-demand): don't resolve get-page-data if query is marked as dirty

packages/babel-plugin-remove-graphql-queries/src/index.ts, packages/gatsby/src/query/file-parser.js
Compilation was failing in e2e tests because babel was failing when trying to extract queries from a compiled JS bundle. This adds some optional chains to avoid checking for propererties of undefined objects
=> fix(gatsby): Avoid undefined object errors

packages/create-gatsby/src/index.ts
The `-y` flag bypassed all of the prompts at the start of the interactive experience, but it still asked you to confirm if you wanted the site to be created. This removes that prompt and some of the extraneous reporter info calls to streamline the stdout and prevent the user from needing to interact at all.
=> fix (create-gatsby): Ignore confirmation prompt

packages/gatsby-source-drupal/src/normalize.js
Currently the `downloadFile` function (which is used to download a file using `createRemoteFileNode` and to create a `File` node for it) wraps all logic in a try block and ignores any errors that are caught. 
This is problematic because it swallows real errors and can be frustrating to an end user because it makes debugging harder, for example a sharp transform may fail due to a broken download instead of the broken download itself failing. 
We fix this by removing the try catch block entirely.
=> fix(gatsby-source-drupal): Do not swallow errors

packages/gatsby-source-contentful/src/__tests__/fetch.js, packages/gatsby-source-contentful/src/fetch.js, packages/gatsby-source-contentful/src/gatsby-node.js
Changes to the Contentful SDK and Axios slipped through and broke our graceful error catching.
This PR will do the following:
=> fix: improve error handling, always show API response status and message

packages/gatsby-recipes/recipes/tailwindcss.mdx
The currently included Tailwind recipe is broken because it does not install PostCSS as recommended in https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
This PR fixes that by adding `postcss` as a dependency
=> fix(gatsby-recipes): Add postcss as a dependency

e2e-tests/production-runtime/cypress/integration/scroll-behavior.js, packages/gatsby-react-router-scroll/src/scroll-handler.tsx
Currently we do not navigate correctly to hashes unless the scroll position is zero. If you're scrolled to any position other than the top, you will need to click twice to scroll to the correct position. This behaviour is completely broken at the moment. 
This PR fixes this (albeit not completely) by _always_ respecting the hash and scrolling to it irrespective of if there is browser scrolling state or not. This is iteratively better than our current behaviour. However, the ideal behaviour (which we ought to handle in a separate PR) is to respect hash except when navigating back in the browser (in which case, we ought to restore scroll position). Reach currently has this bug which we can track at https://github.com/reach/router/issues/228
Closes #25778
=> fix(gatsby-react-router-scroll): Respect hash as source of truth for scroll position

packages/gatsby/src/schema/extensions/__tests__/child-relations.js, packages/gatsby/src/schema/schema.js
Add a missing piece to the incorrect warning text introduced in #28532 (didn't push this commit in that PR) 🤦‍♂️
=> fix(gatsby): correct GraphQL warning text

packages/create-gatsby/src/styles.json
Styles from the `create-gatsby` package didn't seem to be in any particular order. This clarifies the title for PostCSS and orders the other plugins by number of downloads.
=> chore(create-gatsby): reorder style options by popularity and change postcss title

benchmarks/source-wordpress/package.json, benchmarks/source-wordpress/src/templates/article.js
* Update `gatsby-source-wordpress-experimental` so that it's using the latest version (`^5.0.0`)
* Fix broken query after updating
=> Update gatsby-source-wordpress-experimental and fix queries to work with update

packages/gatsby/cache-dir/app.js, packages/gatsby/cache-dir/dummy.js
We don't actually have to fetch async chunk to cause `__webpack_require__.e` to be added to webpack runtime - we just need to have `import()` somewhere in code
This avoids making additional network request at a time where this a lot of contention for network requests
=> chore(develop): don't actually fetch async dummy.js chunk

packages/gatsby/src/utils/start-server.ts
So we can see how long things get out in the wild. They're generally fast in testing but there's edge cases that can cause long runs hurting the user experience that might need protected against.
=> feat(gatsby): track how long query-on-demand querying takes

packages/gatsby-source-contentful/src/gatsby-node.js
Fix the output when using this flag because it was failing to print the actual location because `.info` does not accept multiple parameters like `console.log` does.
```
info GATSBY_CONTENTFUL_EXPERIMENTAL_FORCE_CACHE was set. Skipping remote fetch, using data stored in
```
=> chore(gatsby-source-contentful): fix output of debug message

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx, packages/gatsby-plugin-image/src/components/static-image.server.tsx
This PR adds several props that were previously included in gatsby-image. I'm not 100% sure whether we should include all of them, particularly the ones that can be set using CSS. The additions are:
- `imgStyle`: passed to the `<img>` tag
- `imgClassName`: passed to the `<img>` tag
- `objectFit`: Added to `imgStyle`
- `objectPosition`: Added to `imgStyle`
- `backgroundColor`: added to `style`, which is passed to the wrapper. This is not the same as the `backgroundColor` that comes from the resolver, which is applied to the *placeholder*, so disappears when the main image has loaded. This one is applied to the wrapper, so will remain after loading and can be used for transparent images for example.
=> feat(gatsby-plugin-image): Add extra props to GatsbyImage

packages/gatsby-plugin-sharp/src/gatsby-node.js
Before this PR lazy images run all possible image transformations when a single transformed image is requested. After this PR only the requested image variant is processed and returned.
All the remaining transformations are still stored in the cached job, so whenever another image variant is requested - it will be also lazily transformed and returned.
Tried it on my current image-heavy test site. All transforms:
```
success Generating image thumbnails - 53.272s - 72/72 1.35/s
```
The same example with this PR:
```
success Generating image thumbnails - 25.650s - 24/24 0.94/s
```
#27603 - umbrella discussion
=> feat(gatsby-plugin-sharp): run a single transformation for lazy images

packages/gatsby/cache-dir/app.js, packages/gatsby/cache-dir/debug-log.js, packages/gatsby/cache-dir/loading-indicator/index.js, packages/gatsby/cache-dir/loading-indicator/indicator.js, packages/gatsby/cache-dir/loading-indicator/portal.js, packages/gatsby/cache-dir/loading-indicator/style.js, packages/gatsby/cache-dir/navigation.js, packages/gatsby/cache-dir/root.js, packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/loading-indicator.ts, packages/gatsby/src/utils/start-server.ts
This shows loading indicator in `gatsby develop` when using query on demand. It will show fixed element in bottom left if first render or navigation takes over 1s and dismiss it just before first render or when navigation completes.
TODO:
- ability to disable it:
- ~[x] permenently (gatsby-config)~ I backed out of it, because it sets precedent for configuration in flags which we might regret - it doesn't mean something like won't be added in the future - just that it needs more thinking and discussions
- ~[ ] e2e tests~ indicator being shown in shadow-dom make it not feasible to test with our version of cypress - it seems like newer versions of cypress do support it, but upgrading cypress version is bigger lift and should be out of scope for this PR
closes #28182
[ch19091]
=> feat(query-on-demand): loading indicator

packages/gatsby-plugin-sharp/src/gatsby-node.js
We incorrectly decode path segments with `decodeURI`. Instead, we should be using `decodeURIComponent` because the encoding is done with `encodeURIComponent` here:
https://github.com/gatsbyjs/gatsby/blob/498fbbfc5ecdd3da5d8f3dbe6a10ae908af2786a/packages/gatsby-plugin-sharp/src/index.js#L106
`encodeURI` and `encodeURIComponent` encode stuff differently so we must be consistent. To clarify:
`encodeURI` will not encode any of those: `~!@#$&*()=:/,;?+` characters (as a result, `decodeURI` won't decode those too).
`encodeURIComponent` will encode all the characters except `-_.!~*'()`
#27603 - Umbrella discussion
=> fix(gatsby-plugin-sharp): fix image url decoding for lazy images

packages/gatsby-plugin-image/package.json
I keep looking for it in /plugins and not finding it!
=> feat(gatsby-plugin-image): add keywords to package.json so it shows up in the plugin search

packages/gatsby/src/utils/flags.ts
Ops, my change that was only meant for local testing ended up commited and pushed to https://github.com/gatsbyjs/gatsby/pull/28387
It was never meant to be `100` (ops)
=> fix(gatsby): correct opt-in percentage for QUERY_ON_DEMAND and LAZY_IMAGES

packages/gatsby-source-contentful/src/gatsby-node.js
Before:
```
verbose 4.236316237 All locales: [object Object],[object Object],[object Object],[object Object], default: en, after plugin.options.localeFilter: [object Object]
```
After:
```
verbose 4.097874197 Default locale: en.   All locales: en, fr, es
verbose 4.098036228 After plugin.options.localeFilter: en
```
=> chore(gatsby-source-contentful): fix locale debug output, again

e2e-tests/development-runtime/cypress.json, e2e-tests/development-runtime/cypress/integration/functionality/data-update.js, e2e-tests/development-runtime/cypress/integration/functionality/query-data-caches.js, e2e-tests/development-runtime/cypress/integration/gatsby-preview/refreshing.js, e2e-tests/development-runtime/cypress/integration/gatsby-preview/updating.js, e2e-tests/development-runtime/cypress/integration/hot-reloading/page-queries.js, e2e-tests/development-runtime/cypress/integration/navigation/linking.js, e2e-tests/development-runtime/package.json, e2e-tests/development-runtime/plugins/gatsby-source-fake-data/api.js, e2e-tests/development-runtime/plugins/gatsby-source-fake-data/gatsby-node.js, e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/api.js, e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/gatsby-node.js, e2e-tests/development-runtime/scripts/update.js
I had to skip adding e2e tests for loading indicator in https://github.com/gatsbyjs/gatsby/pull/28562 because we use old version of cypress that doesn't seem to have shadow dom support, newer ones seem to have - so let's see how this will go.
There some additional niceties here, like auto-retry (will see how that goes). I also added some cleanup after some of tests because running tests does leave mess behind and we need to clean that mess up manually if we want to rerun tests (when iterating on it).
Also ... some query data caches had `.only` on one of tests (yikes), luckily we didn't mess with runtime in that would affect it (I think), but just unskipping rest of tests too
=> chore(e2e-development): bump cypress version

docs/docs/recipes/styling-css.md
The [typography-js](https://www.gatsbyjs.com/docs/typography-js/) hyperlink given in the additional resources in [css styling](https://www.gatsbyjs.com/docs/recipes/styling-css/) was a dead one. I have replaced it with the correct [one](https://www.gatsbyjs.com/docs/using-typography-js/)
[docs link](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/styling-css.md)
=> Updated dead link for typography-js in styling-css.md

packages/create-gatsby/src/features.json
The current version of create-gatsby offers to install gatsby-plugin-image. That made sense when they were due to be launched around the same time, but gatbsy-plugin-image isn't planned for GA until January. This PR switches it to install gatsby-image for now.
=> fix(create-gatsby): Default to gatsby-image until the plugin is GA

docs/docs/file-system-route-api.md
Docs fix a typo for file-system-route-api.md.
There was extra curly brackets and a missing backtick in 2 the examples. Noticed when I copy pasted an example.
=> Fixed typo brackets in file-system-route-api.md

e2e-tests/gatsby-static-image/src/pages/fluid.js, packages/gatsby-plugin-image/package.json, packages/gatsby-plugin-image/src/__tests__/babel-utils.ts, packages/gatsby-plugin-image/src/babel-helpers.ts, packages/gatsby-plugin-image/src/components/static-image.server.tsx
Check layout proptype in StaticImage. Be more forgiving about capitalisation of prop values
[ch21131]
=> fix(gatsby-plugin-image): Better propType handling for StaticImage

packages/gatsby/src/utils/flags.ts
Backporting #28579 to the 2.29 release branch
(cherry picked from commit c21dac9e8cf97093e00889e850c5a441aef46bda)
=> fix(gatsby): correct opt-in percentage for QUERY_ON_DEMAND and LAZY_IMAGES (#28579)

packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/handle-flags.ts
This doesn't change behaviour - this is only to address message that is displayed.
Currently when user explicitly opt-in in config AND site get's picked for auto opt-in we do display message that site was auto opted-in - this is confusing because user already did opt-in manually and we should prefer that over auto opt-in message.
=> fix(gatsby): Only set auto optin flags if not in config

packages/gatsby-source-contentful/src/gatsby-node.js
Backporting #28582 to the 2.29 release branch
(cherry picked from commit 6a79ffcf0c464fac9a8153103e47868071e8415d)
=> chore(gatsby-source-contentful): fix locale debug output, again (#28582)

e2e-tests/gatsby-static-image/src/pages/fluid.js, packages/gatsby-plugin-image/package.json, packages/gatsby-plugin-image/src/__tests__/babel-utils.ts, packages/gatsby-plugin-image/src/babel-helpers.ts, packages/gatsby-plugin-image/src/components/static-image.server.tsx
Backporting #28606 to the 2.29 release branch
(cherry picked from commit 52027db80559a728d4a85c729d282ec3abccf5b2)
=> fix(gatsby-plugin-image): Better propType handling for StaticImage (#28606)

e2e-tests/gatsby-static-image/src/pages/lazy-loading.js, packages/gatsby-plugin-image/src/babel-helpers.ts, packages/gatsby-plugin-sharp/src/image-data.ts
Backporting #28618 to the 2.29 release branch
(cherry picked from commit 912f30c099f98fa382fe653a3a2c07253bd6b452)
=> fix(gatsby-plugin-image): Correctly handle formats in StaticImage (#28618)

packages/create-gatsby/src/features.json
Backporting #28607 to the 2.29 release branch
(cherry picked from commit 84f3d08ac4ae2830bdb946da30a51c41ecb00ed1)
=> fix(create-gatsby): Default to gatsby-image until the plugin is GA (#28607)

packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/handle-flags.ts
Backporting #28627 to the 2.29 release branch
(cherry picked from commit b81e6bdb70fbda4f02739728f79b12c166b1a188)
=> fix(gatsby): Only set auto optin flags if not in config (#28627)

packages/gatsby/src/utils/start-server.ts
Add status-code and extra information when it's not available. This will help us adopt the /__refresh/<pluginname> endpoint. This makes it easier to feature detect the specific endpoint.
=> feat(gatsby): improve refresh endpoint output

docs/reference/release-notes/v2.26/index.md, docs/reference/release-notes/v2.27/index.md, docs/reference/release-notes/v2.28/index.md
Adds lists of external contributors to our older release notes via https://github.com/LekoArts/thanks-contributors
=> chore: Add contributors to 2.26/2.27/2.28 release notes

packages/gatsby/src/utils/start-server.ts
Backporting #28621 to the 2.29 release branch
(cherry picked from commit deb4e1ebdfbf4c9e9f4516bb6c24afbaf61e81ff)
=> feat(gatsby): improve refresh endpoint output (#28621)

docs/reference/release-notes/v2.29/index.md
Release notes for 2.29 -- please add anything you want mentioned/highlighted in this release via PR suggestions.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-2.29/docs/reference/release-notes/v2.29/index.md)
=> docs: release notes for 2.29

packages/gatsby/src/utils/webpack-utils.ts
**Description:**
Currently, gatsby allows to include as images supported image types (for example, jpeg, gif, webp). Most browsers recently added AVIF image support, but gatsby does not recognize AVIF as images and tries to include AVIF file in the bundle
*Expected behavior*:
`<img src="file.avif">` should create avif file in the folder with output and generate `<img src="path-to-file.avif">` in the resulting HTML file
*Current behavior*:
Gatsby tries to include the file (which is of binary format) in the bundle and crashes doing that
=> feat(gatsby): Add AVIF file support to image loader in webpack config

packages/gatsby/src/commands/develop.ts
Closes #28495, thank you @maxtruxa!
=> fix(gatsby): require gatsby-config.js before accessing process.env

packages/create-gatsby/src/styles.json
Switches the sass dependency to `sass` from `node-sass` because of https://github.com/gatsbyjs/gatsby/pull/27991/
It needs to be released alongside gatsby-plugin-sass@3.0.0
=> fix(create-gatsby): Switch dependency to sass

packages/gatsby-plugin-page-creator/package.json
We import `gatsby-telemetry` in `gatsby-plugin-page-creator` but we don't set it as dependency so sometimes depending how package managers install `node_modules` this can result in "Module not found" errors
https://github.com/gatsbyjs/gatsby/blob/787bc2325b5f02a86a2ab984725214e2a972d86c/packages/gatsby-plugin-page-creator/src/gatsby-node.ts#L12
Fixes #28646
=> fix(gatsby-plugin-page-creator): add missing telemetry dependency

docs/docs/add-seo-component.md, docs/docs/conceptual/building-with-components.md, docs/docs/conceptual/graphql-concepts.md, docs/docs/data-fetching.md, docs/docs/data-storage-redux.md, docs/docs/glossary/static-site-generator.md, docs/docs/how-to/plugins-and-themes/theme-conventions.md, docs/docs/how-to/querying-data/static-query.md, docs/docs/how-to/querying-data/use-static-query.md, docs/docs/how-to/sourcing-data/sourcing-from-private-apis.md, docs/docs/porting-from-create-react-app-to-gatsby.md, docs/docs/programmatically-create-pages-from-data.md, docs/docs/recipes/pages-layouts.md, docs/docs/recipes/querying-data.md, docs/docs/recipes/sourcing-data.md, docs/docs/reference/built-in-components/gatsby-image.md, docs/docs/reference/graphql-data-layer/graphql-api.md, docs/docs/reference/release-notes/migrating-from-v1-to-v2.md, docs/docs/sourcing-from-graphcms.md, docs/docs/static-vs-normal-queries.md, docs/docs/tutorial/part-four/index.md
Some pages were recently moved (#28165 I think) from `how-to/sourcing-data` to `how-to/querying-data` but the references were not updated.
```
how-to/querying-data
├── page-query.md
├── running-queries-with-graphiql.md
├── static-query.md
├── use-static-query.md
└── using-gatsby-without-graphql.md
how-to/sourcing-data
├── headless-cms.md
├── sourcing-from-contentful.md
├── sourcing-from-databases.md
├── sourcing-from-drupal.md
├── sourcing-from-hosted-services.md
├── sourcing-from-json-or-yaml.md
├── sourcing-from-netlify-cms.md
├── sourcing-from-prismic.md
├── sourcing-from-private-apis.md
├── sourcing-from-the-filesystem.md
└── sourcing-from-wordpress.md
```
=>  fix(docs): dead links sourcing-data -> querying-data

packages/gatsby-plugin-page-creator/package.json
Backporting https://github.com/gatsbyjs/gatsby/pull/28652 to the 2.29 release branch
(cherry picked from commit a13827f1bea8282fa3ba85f73b4cdc910338b066)
=> fix(gatsby-plugin-page-creator): add missing telemetry dependency (#28652)

packages/gatsby-plugin-sharp/src/index.js, packages/gatsby-plugin-sharp/src/report-error.js
Backporting #28614 to the 2.29 release branch
(cherry picked from commit 02860da8f8871c21c647fae5c0e81380f6809166)
=> fix(gatsby-plugin-sharp): catch errors when writing base64 images (#28614)

packages/gatsby/src/commands/build-html.ts, packages/gatsby/src/commands/build.ts, packages/gatsby/src/utils/start-server.ts
Decouple html ssr bundling from rendering pages to get better metrics on where html rendering is slow.
=> feat(gatsby): decouple html activities

e2e-tests/gatsby-static-image/src/pages/constrained.js, e2e-tests/gatsby-static-image/src/pages/fixed.js, e2e-tests/path-prefix/src/pages/index.js, e2e-tests/production-runtime/src/components/header.js, e2e-tests/visual-regression/src/pages/static-images/constrained.js, e2e-tests/visual-regression/src/pages/static-images/fixed.js, packages/gatsby-plugin-image/README.md, packages/gatsby-plugin-image/src/__tests__/image-utils.ts, packages/gatsby-plugin-image/src/components/static-image.server.tsx, packages/gatsby-plugin-image/src/image-utils.ts, packages/gatsby-plugin-sharp/src/image-data.ts, packages/gatsby-transformer-sharp/src/customize-schema.js
Based on discussions about new defaults, this makes the following changes:
- Default layout is "constrained"
- Dimensions are no longer required!
- If layout is fixed and no dimensions are provided, width is taken from the size of the source image
- If layout is constrained, maxWidth is taken from the size of the source image
- If layout is fluid, maxWidth is **half** the width of the source image. This is so the largest generated image is the size of the source image.
=> feat(gatsby-plugin-image): Make dimensions optional and default to constrained

docs/docs/how-to/styling/bulma.md, docs/docs/how-to/styling/sass.md, docs/docs/how-to/styling/tailwind-css.md, docs/docs/recipes/styling-css.md
Need to partially revert changes of https://github.com/gatsbyjs/gatsby/pull/27991 until 2.30 is released and docs are allowed to update, too.
=> Partially revert "BREAKING(gatsby-plugin-sass): sass-loader to v10 & …"

packages/gatsby-plugin-image/src/components/main-image.tsx, packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Shows an image if JS is disabled. Adds a preload link for loading=eager images.
=> perf(gatsby-plugin-image): Handle disabled js, and add preload link

packages/gatsby/src/query/query-runner.ts
I've experienced some odd behavior with `try/catch` and `await` and this way we don't need to `await` the promise inside this call. Instead we can return the promise that should still stop the timeout-timer before resolving further promises.
=> chore(gatsby): refactor try/finally to .finally

packages/gatsby/src/commands/develop-process.ts
Avoids activating the inspector if already active, which cases issues https://github.com/gatsbyjs/gatsby/issues/26708
The behavior to throw was introduced in response to https://github.com/nodejs/node/issues/33012, where previously it just resulted in weird/broken behavior.
Fixes https://github.com/gatsbyjs/gatsby/issues/26708
=> fix(gatsby): Do not activate inspect if already active

packages/gatsby-source-npm-package-search/package.json, packages/gatsby-source-npm-package-search/src/search.js
Upgrade algoliasearch js client to latest version. It is more stable and has better timeout defaults out of the box
```connect: 2 * 1000,
read: 5 * 1000,
write: 30 * 1000
```
versus 
```connect: 1 * 1000
read: 2 * 1000,
write: 30 * 1000```
Should make builds for gatsbyjs.com and other users more stable
=> chore(gatsby-source-npm-package-search): Upgrade algoliasearch

packages/gatsby-source-filesystem/src/create-remote-file-node.js
When downloading a file from a remote under pressure, we have seen cases where the download might be incomplete, especially in cases of images. Such files will break `sharp` when it attempts to process them with an Error because they are corrupt. 
One (not exhaustive) nice to have check to prevent this is to assert that the bytes written to disk and equal to the `Content-Length` sent in HTTP headers (when present). 
This PR adds that check and retries if the check fails.
=> fix(gatsby-source-filesystem): Retry a download if a file is incomplete

packages/gatsby-plugin-image/package.json
This reverts commit e304ddddcabe648ba2938feb83b528e2c942ca72 #28082
=> fix(deps): Revert postcss upgrade which broke css macro

e2e-tests/mdx/gatsby-config.js, e2e-tests/mdx/plugins/gatsby-plugin-test-regression1/gatsby-node.js, e2e-tests/mdx/plugins/gatsby-plugin-test-regression1/package.json, e2e-tests/mdx/src/pages/regressions/index.mdx, packages/gatsby/src/query/file-parser.js
This PR fixes a bug where we incorrectly mark a component as having a query extraction error. Very edge case, pretty well explained in the test case:
```
This is a regression test for query extraction bug in Gatsby.
All of the following is required to hit this bug:
1. `gatsby-plugin-mdx` should be installed + at least one other plugin implementing `preprocessSource`
2. This plugin must be listed before `gatsby-plugin-mdx` in `gatsby-config.js`
3. MDX file must contain the word `graphql`
```
MDX is not requirement - any two plugins implementing `preprocessSource` could hit this. But it was easier to reproduce and write a test case with mdx.
=> fix(gatsby): remove redundant dispatch of query extraction error

packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
It only makes sense to return the actual value from the `preprocessSource` if it changes the content. Otherwise, it causes a redundant babel parsing when `gatsby-plugin-image` is used alongside other plugins, i.e. `gatsby-plugin-mdx`.
Some context. We run this `preprocessSource` hook here when extracting queries:
https://github.com/gatsbyjs/gatsby/blob/8138b97d025b5aaa8f3a46e7d9911484a00591f7/packages/gatsby/src/query/file-parser.js#L83-L91
And then doing additional `babelParseToAst` for every returned value.
If we return `undefined` instead, results of `gatsby-plugin-image` will be simply ignored here and won't be added to `transpiled` array above. Here is where we filter empty plugin results:
https://github.com/gatsbyjs/gatsby/blob/8138b97d025b5aaa8f3a46e7d9911484a00591f7/packages/gatsby …
=> fix(gatsby-plugin-image): do not return from preprocessSource if nothing is changed

docs/docs/reference/release-notes/v2.27/index.md, docs/docs/reference/release-notes/v2.28/index.md, docs/docs/reference/release-notes/v2.29/index.md
Some old relative links that worked on GitHub no longer work on our live website. So changing these :)
https://www.gatsbyjs.com/docs/reference/release-notes/v2.27 and others should work fine again after these changes
=> chore(docs): Fix links to release notes

starters/gatsby-starter-minimal/src/pages/404.js
Since this is the starting point for users we shouldn't duplicate the component name.
=> fix(gatsby-stater-minimal): 404 Page should not also be IndexPage

integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-added/scenario.js, integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-changed/scenario.js, integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-removed/scenario.js, integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-added/scenario.js, integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-changed/scenario.js, integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-removed/scenario.js
Currently not required cache resilience tests needed to be updated in https://github.com/gatsbyjs/gatsby/pull/28656 but we slapped merge on green which doesn't require "not required" tests to pass (ops). This just updates snapshots for those tests to match change from that PR (always adding both `childX` and `childrenX` fields. Snapshots here introspect schema for various scenarios and compares what happens to schema when adding/removing plugins between runs.
It only have cases for single child scenario so it did had just `childX` before - with change from PR we now have to account for `childrenX` too.
https://github.com/gatsbyjs/gatsby/pull/28656
=> test(cache-resilience): update snapshots

packages/gatsby/src/redux/actions/public.js
https://github.com/gatsbyjs/gatsby/blob/3ce476b1eac97aedd16f9d150cd6a81f36255380/packages/gatsby/src/bootstrap/requires-writer.ts#L336-L345 will uncodindionally run `requires-writer` on `CREATE_SERVER_VISITED_PAGE` actions. Let's skip emitting those actions that will be functionally no-ops (but still cause some extra work)
=> chore(dev-ssr): don't dispatch CREATE_SERVER_VISITED_PAGE if component is already tracked

packages/gatsby-plugin-image/gatsby-browser.js, packages/gatsby-plugin-image/src/components/later-hydrator.tsx, packages/gatsby-plugin-image/src/index.browser.ts
Preloads the lazy-hydrate bundle, outside of the render path. This ensure there's no delay when navigating to a page with an image
=> fix(gatsby-plugin-image): Preload lazy-hydrator

packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap, packages/gatsby-source-contentful/src/__tests__/normalize.js, packages/gatsby-source-contentful/src/gatsby-node.js, packages/gatsby-source-contentful/src/normalize.js
A warm build will currently still attempt to create the node even if it already exists. This PR will do an early check, compare the digest (`entry.sys.updatedAt`), and return early if the node already exists for that digest.
There might be a simpler solution but for now, this cuts the warm "no changes" build for a 2 million node site down from to about 894s (120s for node createion step) down to 512s (35s for the node creation step), saving about 5 minutes.
Need verification from Contentful that this approach is sound. But I think it is. (Tests will fail too, will fix them before we merge)
=> perf(gatsby-source-contentful): dont re-create nodes

packages/gatsby-source-graphql/README.md
Add a section to the [gatsby-source-graphql](https://www.gatsbyjs.com/plugins/gatsby-source-graphql/) plugin docs about Apollo links and how to compose them.
See https://github.com/gatsbyjs/gatsby/discussions/28680
=> chore(gatsby-source-graphql): docs on how to use apollo links

packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap, packages/gatsby/src/schema/__tests__/print.js, packages/gatsby/src/schema/extensions/__tests__/child-relations.js, packages/gatsby/src/schema/schema.js
Fixes a bug with schema printing of inferred `childOf` directive. Before this PR if we print a schema with infered child fields (e.g. `File.childImageSharp`) it won't include `childOf` directive:
```graphql
type ImageSharp implements Node @dontInfer {
id: ID!
}
```
After this PR it correctly prints this:
```graphql
type ImageSharp implements Node @dontInfer @childOf(types: ["File"]) {
id: ID!
}
```
This fixed variant will correctly wotk in Gatsby v3. The variant before this PR will fail to work in Gatsby v3 (the printed schema snapshot won't add the `File.childImageSharp` field).
Worked around breaking change via #28656
<details>
<summary>
See details (no longer actual)
</summary>
Requires a bit of investigation. To illustrate a possible break. With this change, we automatically apply the …
=> fix(gatsby): print childOf directive for implicit child fields

packages/gatsby/src/commands/build.ts
This adds an option in program for the build command that allows one to specify that they would like to keep `public/render-page.js` around
=> chore(gatsby): Keep page renderer around

packages/gatsby/cache-dir/ssr-develop-static-entry.js, packages/gatsby/src/utils/webpack.config.js
We don't need React's dev hints & we want SSR to be as fast as possible on CI
=> feat(gatsby): use production React for dev-ssr when CI=true

packages/gatsby/src/services/initialize.ts, packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/flags.ts, packages/gatsby/src/utils/handle-flags.ts
This PR "graduates" query on demand mode to default in non-CI environment. 
Main change here is adding support for `LOCKED_IN` setting for flags - this is done mainly to display more meaningful message in terminal. Removing the flag from the list would result in "unknown" flag message that could be confusing.
=> chore(gatsby): enable query on demand (and lazy images) by default for local development

packages/gatsby-telemetry/src/telemetry.ts
ChildProcesses added to `gatsby develop` caused us to have multiple `sessionId`s per develop process, making it seem users run develop in parallel. this tries to address it.
=> chore(telemetry): ensure forked develop child processes have the same sessionId

packages/gatsby-plugin-image/src/babel-helpers.ts, packages/gatsby-plugin-sharp/src/image-data.ts
Fix a bug where auto-format images didn't pass-through the format-specific options
=> fix(gatsby-plugin-sharp): Pass format-specific options in image data resolver

docs/docs/recipes/styling-css.md
Fontsource released a major update that contains some [breaking changes](https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md#40x). This PR just updates the package installs with the new scoped format, as well as clean up any references to font styles as the "-normal.css" variant of these packages have been removed.
Previous issue for reference: #27313.
=> Update Fontsource Documentation

packages/gatsby-transformer-csv/README.md
=> chore(gatsby-transformer-csv): fix whitespace

docs/docs/how-to/styling/tailwind-css.md
Updated the "Twin + Gatsby + Emotion installation guide" link. The old one returned a 404.
Updated the "Twin + Gatsby + Emotion installation guide" link. The old one returned a 404.
=> chore(docs): Updated Twin + Gatsby + Emotion link

packages/gatsby-plugin-image/src/node-apis/image-processing.ts, packages/gatsby-plugin-image/src/node-apis/watcher.ts
Logs the source image and the message when image processing fails
=> fix(gatsby-plugin-image): Better error logging

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/static-image.server.tsx
This PR contains two bugfixes to the handling of styles in gatsby-plugin-image. First, it correctly applies some styles that were msising in SSR. Second it fixes a compatibility issue when using preact, where the "class" prop was not intercepted, and was instead passed-down to the img tag. The same would happen if using the class prop in React (instead of className), but it less of an issue as that's not explicitly allowed (though does normally work).
Fixes bug reported in https://github.com/gatsbyjs/gatsby/discussions/27950#discussioncomment-252289
=> fix(gatsby-plugin-image): Correct image styles

docs/docs/how-to/routing/migrate-remark-to-mdx.md
Clarified that `result.data.allMarkdownRemark.nodes` also needs to be changed to `result.data.allMdx.nodes`, otherwise creating the pages will fail.
=> chore(docs): Update migrate-remark-to-mdx

docs/docs/reference/release-notes/v2.30/index.md
Adds info about AVIF and remote image URLs. I'd like to add links to the demo site when it's ready too
=> docs: Add avif and remote image release notes

docs/docs/how-to/routing/migrate-remark-to-mdx.md, e2e-tests/gatsby-static-image/cypress/integration/constrained.js, e2e-tests/gatsby-static-image/cypress/integration/fixed.js, e2e-tests/gatsby-static-image/cypress/integration/fluid.js, e2e-tests/gatsby-static-image/src/pages/constrained.js, packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
The sizes prop was being incorrectly handled in SSR. It should be using the property of the fallback image, not a top-level sizes prop.
=> fix(gatsby-plugin-image): Fix handling of sizes prop in SSR

packages/create-gatsby/src/tracking.ts
- fix(create-gatsby) the sessionId is supposed to be the same for the whole duration of the session
=> fix(create-gatsby) the sessionId is supposed to be the same for the whole duration of the session

docs/docs/reference/release-notes/v2.30/index.md
Adds a warning about AVIF not currently working in Cloud
=> docs: Add caveat for avif support

packages/gatsby-plugin-sharp/src/process-file.js
Adds explicit `avif()` call to pipeline. It works locally without this, but fails in cloud worker
=> fix(gatsby-plugin-sharp): Add avif to pipeline

docs/docs/reference/release-notes/v2.30/index.md
Release notes for v2.30. Please add anything you would like to mention in this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-2.30/docs/docs/reference/release-notes/v2.30/index.md)
=> docs: release notes for v2.30

docs/docs/conceptual/overview-of-the-gatsby-build-process.md
This is very short mention in how query on demand make `gatsby develop` different than `gatsby build` when it comes to page query running. Mostly highlighting change in number of page queries it will run initially
[ch19538]
=> docs: update gatsby develop overview for query on demand

packages/gatsby-admin/package.json, packages/gatsby/package.json, yarn.lock
Fixes https://github.com/gatsbyjs/gatsby/issues/28877 as otherwise a breaking change would be pulled in.
=> fix(gatsby,gatsby-admin): Pin socket.io version to 2.3.0

docs/docs/how-to/plugins-and-themes/creating-a-generic-plugin.md, docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md, docs/tutorial/using-multiple-themes-together.md, examples/creating-source-plugins/README.md, packages/gatsby-admin/README.md, packages/gatsby-design-tokens/README.md
changes:
- add `https://` to `localhost`
=> chore(docs): add http to localhost

packages/gatsby/index.d.ts
The `flags` were missing from the `GatsbyConfig` interface.
Side note: In a later iteration we could think of creating string literals instead of `string` so that people would get type hints for all experiments based of our current flags (so dynamically created)
=> chore(gatsby): Add `flags` to GatsbyConfig interface

benchmarks/source-strapi/README.md, docs/docs/how-to/styling/using-web-fonts.md, packages/gatsby-admin/README.md, packages/gatsby-recipes/CONTRIBUTING.md, starters/gatsby-starter-mdx-basic/README.md
changes:
- change code block language from `sh` to `shell`
- change code block language from `bash` to `shell`
=> chore(docs): fix code block language to shell

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
Right now, fluid and constrained images trigger a re-layout because the sizer div (living in LayoutWrapper) hasn't loaded yet. This is not a challenge for SSR, but for route navigation.
This updates the dangerouslySetInnerHTML hack to use the sizer elements that fluid and constrained need.
[ch21582]
=> Fix(gatsby-plugin-image): Render LayoutWrapper prior to loading of lazy-hydrate

docs/docs/conceptual/gatsby-for-ecommerce.md
Add an overview of the considerations necessary when building an e-commerce site with Gatsby and eg Shopify
=> ecommerce conceptual guide

packages/gatsby-plugin-utils/README.md
changes:
- add `js` file extension to `gatsbay-config`
- add code block around filenames and plugin names, and function names
- fix link to example file
- fix code block: add missing comma
- #27364 `chore(docs): add docs for testPluginOptionsSchema`
=> docs(readme): add file extension, fix code block, fix link, fix code

packages/gatsby-plugin-sass/CHANGELOG.md, packages/gatsby-plugin-sass/README.md, packages/gatsby-plugin-sass/package.json, packages/gatsby-plugin-sass/src/gatsby-node.js
changes:
- change `sass`/`SASS` to `Sass`
- add code block around names
- #27466 `chore(gatsby-plugin-sass): add pluginOptionsSchema export`
=> fix(gatsby-plugin-sass): fix brand name, code block around names

docs/docs/node-creation.md
change:
- fix brand name `Redux`
- #27252 `chore(docs): Remove non-inclusive language`
=> doc(node-creation): fix brand name

packages/gatsby-source-contentful/README.md
changes:
- fix brand names (Contentful, JSON, API)
- code block around names and plugins
- `Content Type` -> `content type`
- #27563 `fix(gatsby-source-contentful): fixed contentful asset download stalling with high number of assets`
=> chore(docs): plugin contentful - fix brand name, code blocks for names

packages/gatsby-plugin-google-analytics/README.md
changes:
- info about upgrade to gtag (see #27065 `Update analytics doc to include google-plugin-gtag`)
- fix code sample, add `from 'react'`
- #27065 `Update analytics doc to include google-plugin-gtag`
- #27081 `chore(docs): Update analytics with gatsby-plugin-gtag`
=> chore(docs): google plugin analytics - upgrade to gtag, fix code

packages/gatsby/src/schema/node-model.js
Do not spread all the nodes of a particular type on a function call. When the set of nodes exceeds 64k elements you'll see stack overflow errors. This PR rewrites it such that the spread is no longer necessary. (The new spread is going to be one or a very low number since you're not going to have thousands of types in a Gatsby site unless you're trying hard for it)
This was blocking images at scale. However, the image stuff no longer goes through this path after https://github.com/gatsbyjs/gatsby/pull/28891 but this function should still not spread potentially thousands of nodes.
I tested a few strategies and then picked the one in this PR because it was the least invasive to the code base while being about equal in performance. Tested against an 8k image benchmark that hit this path six …
=> fix(gatsby): rewrite a spread that would break at scale

starters/default/src/components/layout.js, starters/default/src/pages/using-typescript.tsx
The gatsby-default-starter is not already formatted according to prettier i.e. running `npm run format` cause some changes in code.
N/A
N/A
=> chore(default-starter): format code using prettier

docs/docs/reference/release-notes/v2.26/index.md, docs/docs/reference/release-notes/v2.27/index.md, docs/docs/reference/release-notes/v2.28/index.md, docs/docs/reference/release-notes/v2.29/index.md, docs/docs/reference/release-notes/v2.30/index.md
changes:
- fix code block language to `jsx`, `shell`
- add code fences to constants, plugins, file names	
- #27970 `docs: 2.26 release notes`
- #28836 `docs: release notes for v2.30`
=> chore(docs): realease notes - code fences, code language

docs/docs/quick-start.md
The default site name is now `my-gatsby-site` in the cli flow so I have updated the docs to reflect this change 
```
√ Shall we do this? (Y/n) · Yes
√ Created site from template
PS C:\Users\source\repos\gatsby-app> cd gatsby-site
Set-Location: Cannot find path 'C:\Users\source\repos\gatsby-app\gatsby-site' because it does not exist.
PS C:\Users\source\repos\gatsby-app> cd my-gatsby-site
PS C:\Users\source\repos\gatsby-app\my-gatsby-site> npm run develop
```
=> chore(docs): Change cd path to "my-gatsby-site"

docs/docs/reference/routing/file-system-route-api.md
changes:
- brand name `Markdown`
- code language to `jsx` for all `src/pages`
- code block around constants / plugin names
- #27665 `File System Route API - Documentation`
=> chore(docs): routing - brand name, code language, code block

packages/gatsby/src/utils/api-runner-node.js
In `gatsby develop` we use debug build of `bluebird` currently which adds quite significant overhead. This is particularly visible on larger sites with large amount of nodes when we spawn tens of thousands `onCreateNode` runs.
- In tested site `gatsby develop` was crashing with OOM error. This change allow to not hit this crash without adjusting `--max_old_space_size`.
- Tested site with `--max_old_space_size=10000` before and after this change - source nodes step drops from ~67.87s (average across 3 runs) to ~21.7s (average across 3 runs)
Fixes https://github.com/gatsbyjs/gatsby/issues/28916
Fixes https://github.com/datocms/gatsby-source-datocms/issues/123
Fixes https://github.com/datocms/gatsby-source-datocms/issues/134
[ch21729]
=> perf(develop): don't use debug config for bluebird

docs/docs/how-to/styling/bulma.md, docs/docs/how-to/styling/sass.md, docs/docs/how-to/styling/tailwind-css.md, docs/docs/recipes/styling-css.md
At the moment docs for `gatsby-plugin-sass` are outdated. We had a major bump of `gatsby-plugin-sass` in #27991 which also included the new docs.
But then we had to revert those docs in #28666 until the new version is actually published. Now that the new major of this plugin is published, we restore the correct docs from #27991.
This reverts commit 9dbd02b1
=> docs: restore the most actual docs for gatsby-plugin-sass

docs/docs/reference/graphql-data-layer/schema-customization.md, docs/docs/schema-generation.md
Updated docs for GraphQL to accommodate changes in #28656
Originally those docs were included as a part of that PR but had to remove them until the new release. Now that the release is published we are safe to update those docs.
This reverts commit 8687e2c0
=> docs: update GraphQL docs for child fields

packages/gatsby-plugin-image/package.json, packages/gatsby-plugin-image/src/node-apis/image-processing.ts, packages/gatsby-plugin-image/src/node-apis/watcher.ts
Right now gatsby-plugin-image will break builds if gatsby-source-filesystem and gatsby-plugin-sharp are not included as dependencies. 
This should not happen if filesystem isn't there as it's only needed for StaticImage, not GatsbyImage.
plugin-sharp should error, but with a more descriptive error than the generic webpack one. [ch22339]
=> fix(gatsby-plugin-image): Conditionally require dependencies and give better warnings

packages/gatsby/src/schema/node-model.js
All the filter code is sync so this `await` is redundant.
Unfortunately it makes no difference to perf in my quick tests. Maybe at very large scale but even then it would be minimal.
=> chore(gatsby): remove unused await

packages/gatsby-telemetry/src/__tests__/telemetry.ts, packages/gatsby-telemetry/src/telemetry.ts
Allow reading telemetry data from a file
=> chore(telemetry): allow sharing tags in a file and read it only when things change

packages/gatsby-plugin-image/src/components/main-image.tsx
This PR removes the preload tag, because there's no way to offer multiple image types without the browser downloading them all, and the speed benefit seems to be minimal.
=> fix(gatsby-plugin-image): Remove preload tag

packages/gatsby/src/utils/__tests__/eslint-config.ts, packages/gatsby/src/utils/eslint-config.ts, packages/gatsby/src/utils/eslint/required.js, packages/gatsby/src/utils/webpack-utils.ts, packages/gatsby/src/utils/webpack.config.js
Change building on https://github.com/gatsbyjs/gatsby/pull/28689 (so targeting that branch and not `master`.
This should ensure fast-refresh related rules are included even if user have custom config or disable set of builtin rules. Those required rules are warnings only so they will not block building webpack bundle.
Note - this was tested when adding local `.eslintrc` file in 2 variants: without using `gatsby-plugin-eslint` and using it. It likely might not work when `eslint-loader` is added to webpack differently (as in it will add second instance of `eslint-loader`), but given that `gatsby-plugin-eslint` looks like "go-to" approach, it might be fine to leave as is
[ch22490]
=> feat(gatsby): add required eslint rules even if user has custom eslint config

docs/docs/how-to/styling/other-css-frameworks.md
The Gatsby plugin has been renamed from gatsby-plugin-chakra-ui to @chakra-ui/gatsby-plugin.
The official chakra site states and recommends that you "have updated this when installing Chakra UI in your next Gatsby project.". This caused a burden for me, personally, when I tried to figure out why the old plugin was being installed but not working correctly out of the box. 
Link to official chakra ui + gatsby migration notes: https://chakra-ui.com/guides/integrations/with-gatsby
Also it seems we already have the correct info on gatsby own page but it was still linking to the old one. 
I updated the links in https://www.gatsbyjs.com/docs/how-to/styling/other-css-frameworks/#chakra-ui referencing the new correct Chakra-UI plugin. 
Closes #29017
=> chore(docs): Updating Chakra UI docs

packages/gatsby-source-contentful/README.md
This improves the examples about using Rich Text
=> chore(docs): adjust Contentful Rich Text example codes

packages/gatsby-plugin-image/src/node-apis/image-processing.ts
Remote images are no more experimental than the rest of the image plugin now, so I think it's fine to unflag them.
=> chore(gatsby-plugin-image): Unflag remote images

packages/gatsby/cache-dir/app.js
This is so we error with message when there's a mismatch between SSRed html and client-side HTML. Hydration errors are a common problem in production so we want to highlight then in dev.
With this PR, hydration problems now error like this in dev:
=> feat(gatsby): Hydrate in development when the page was server rendered

packages/gatsby-plugin-sharp/src/duotone.js, packages/gatsby-plugin-sharp/src/image-data.ts
Adds try/catch blocks where `gatsby-plugin-sharp` reads and writes images.
[`gatsby-plugin-sharp` documentation.](https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp/)
Fixes #28640
=> fix(sharp) wrap sharp calls in try/catch to avoid crashing on bad images

docs/docs/how-to/adding-common-features/adding-search.md
Updated search documentation --- cleaned up some awkward copy, some took unnecessary details out (they are in more detailed documentation that is linked if useful), updated in a world where `<GuideList>` doesn't exist anymore.
=> Edit search documentation

packages/gatsby-source-contentful/package.json, packages/gatsby-source-contentful/src/extend-node-type.js
This replaces the no more maintained `base64-img` package with a more native implementation.
Additionally it fixes the following bug:
* images that are too big for Contentful's Images API resulted in HUGE base64 placeholders.  (See limit in docs: https://www.contentful.com/developers/docs/references/images-api/#/introduction)
This should fix the security vulnerabilities from #24679
=> fix(gatsby-source-contentful): Improve base64 placeholders

packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
The imgStyle prop was working in develop, but not being handled in hydrated SSR
=> fix(gatsby-plugin-image): Handle imgStyle in SSR

packages/gatsby/src/utils/get-react-hot-loader-strategy.ts
Use `fast-refresh` for React 17. This can only be merged after https://github.com/gatsbyjs/gatsby/pull/28689 is merged so that incorrect components are highlighted.
[ch19790]
=> fix(gatsby): Use fast-refresh for React 17

packages/gatsby/src/schema/resolvers.ts
Our resolver tracing is broken ATM. Tracing simply counts sync resolver call. It doesn't await the returned promise and ends the activity immediately. So it kinda tracks sync resolvers but not async.
With this change, we track correctly in both cases.
=> fix(gatsby): fix broken GraphQL resolver tracing

packages/gatsby/src/redux/__tests__/index.js, packages/gatsby/src/redux/index.ts, packages/gatsby/src/services/initialize.ts
This is a solution to be able to temporarily disable cache persistance in case of hitting fatal process crash:
```
../src/node_buffer.cc:451:v8::MaybeLocal<v8::Object> node::Buffer::New(node::Environment*, char*, size_t, bool): Assertion `length <= kMaxLength' failed.
1: 0xa9d570 node::Abort() [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
2: 0xa9d5f7 [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
3: 0xa7e022 [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
4: 0xb1190a [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
5: 0xc7491c [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
6: 0xc76727 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
7: 0x145cef9 [/opt/hostedtoolcache/node/13.8.0/x64/bin/node]
Aborted (core …
```
=> allow to skip cache persistence

packages/gatsby-plugin-image/src/gatsby-ssr.tsx
We previously removed the onload listener if _any_ image had already been hydrated. This was causing a race condition where it was removed before some images had loaded.
=> fix(gatsby-plugin-image): Fix onload race condition

packages/gatsby-plugin-mdx/__tests__/gatsby-node.js, packages/gatsby-plugin-mdx/gatsby-node.js, packages/gatsby-plugin-mdx/utils/default-options.js
Some users use `root` option and a warning is thrown for that. I couldn't really find what it does, so please comment if you know
=> fix(gatsby-plugin-mdx): Add `root` to plugin validation

packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js, packages/gatsby-plugin-typescript/src/gatsby-node.js, yarn.lock
Added missing field validations, as all options are passed to @babel//preset-typescript.
I'm not sure if the docs need to be updated. They already link to Babel docs.
https://www.gatsbyjs.com/plugins/gatsby-plugin-typescript/
Closes #29063
=> fix(gatsby-plugin-typescript): add missing options validations

packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/fluid.input.js, packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-options.input.js, packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-options.output.js, packages/gatsby-codemods/src/transforms/__tests__/gatsby-plugin-image-test.js, packages/gatsby-codemods/src/transforms/gatsby-plugin-image.js
We now nest a lot of the options to clean up the gatsby-plugin-sharp API. The codemod warns for things related the specific image type processing because we don't have an exhaustive list and they're less often used.
For transformOptions, we use the codemod to nest them for the user.
This PR also fixes the scenario where maxHeight was mapped to height for fullWidth images instead of being deleted.
=> feat(gatsby-codemods): Handle or warn on nested options changes

packages/gatsby/src/utils/flags.ts
The partial rollout this past release has been *mostly* smooth but a few bugs popped up in the [umbrella issue](https://github.com/gatsbyjs/gatsby/discussions/28138) so let's get more testers to ensure we've covered all our bases.
=> feat(gatsby): bump opt-in % to dev-ssr to 20%

packages/gatsby/cache-dir/ssr-develop-static-entry.js
For client-only pages, we just want to render an empty body but we do want the other components rendered.
Fixes problem raised by @martinhj and verified in @nikoladev's reproduction https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-285207
=> fix(gatsby): Always render the body component to ensure needed head & pre/post body components are added

docs/docs/how-to/adding-common-features/add-404-page.md
I've fixed the phrasing in the add-404-page.md document:
```diff
- To create a 404 page create a page whose path matches the regex `^\/?404\/?$` (`/404/`, `/404`, `404/` or `404`). Most often you'll want to create a React component page at `src/pages/404.js`.
+ To create a 404 page create a page whose path matches the regex `^\/?404\/?$` (`/404/`, `/404`, `404/` or `404`), most often you'll want to create a React component page at `src/pages/404.js`.
```
N/A
N/A
This is my first PR to gatsby, if there's anything I should do please tell me.
=> chore(docs): Fix grammar in add-404-page

docs/docs/reference/release-notes/v2.31/index.md
Release notes for v2.31. Please add anything you would like to mention in this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-2.31/docs/docs/reference/release-notes/v2.31/index.md)
=> docs: Release notes for 2.31

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
This is documentation for the new plugin. I'd see it sitting alongside the old docs for now, outside of the main navigation. I've split off the API docs, which I will add separately. 
[rendered version](https://github.com/gatsbyjs/gatsby/blob/docs/using-image-plugin/docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md)
[ch19266]
=> docs: Add gatsby-plugin-image How-To guide

docs/docs/reference/release-notes/v2.31/index.md
Fixes a broken link in release notes that sneaked through in #29089
=> docs: fix broken link in 2.31 release notes

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md, docs/docs/reference/built-in-components/gatsby-plugin-image.md
These were accidentally swapped in the wrong docs. This commit fixes the issue by putting the explanation of the restrictions in the Reference Guide and the callout in the How-To Guide.
* How-To Guide: /docs/how-to/images-and-media/using-gatsby-plugin-image
* Reference Guide: /docs/reference/built-in-components/gatsby-plugin-image
#28935 and #28917
=> fix: swap StaticImage restrictions explanation and callout

packages/gatsby-plugin-image/src/components/picture.tsx
The new `gatsby-plugin-image` currently does not pass down the `sizes` prop to the `<source>` element, which cause the highest image to always be chosen by the browser. Only passing it to `<img>` is not sufficient.
By passing it down, the browser can now properly choose the right image based on the `sizes` property.
Also, the previous `gatsby-image` was working this way, so this is simply a bug fix and nothing more.
#29093
=> fix(gatsby-plugin-image): pass down missing sizes attribute to <sources> (fixes #29093)

packages/gatsby-source-contentful/package.json, packages/gatsby-source-contentful/src/fetch.js, yarn.lock
Reverts gatsbyjs/gatsby#29028
Is a breaking change as node 12 is necessary.
=> Revert "fix(gatsby-source-contentful): Add header"

packages/gatsby/src/utils/eslint-config.ts
https://github.com/gatsbyjs/gatsby/pull/28911 introduced some problems in case user has their own `.eslintrc` specifically when using `eslint` that is incompatible with version used currently by gatsby (we use `^6` now, `^7` is latest).
This change disallow using `.eslintrc` for minimal required config for fast-refresh rules ( 1.). But this is not sufficent change. after dissalowing the use of it, we end up with:
```
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
/Users/misiek/test/i29105/src/pages/index.jsx
1:1  error  Parsing error: The keyword 'import' is reserved
```
So `parserOptions` were added (2.) to handle that part are pretty much copy&paste from https://github.com/facebook/create-react-app/blob/0f6fc2bc71d78f0dcae67f3f08ce98a42fc0a57c/packages/eslint-confi …
=> fix(eslint-config): don't use .eslintrc and set parser settings

docs/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options.md
The `testPluginOptionsSchema` returns `Promise` so that calling it should be in `async` `await` construct for test code sample.
* Passing tests for Kontent source plugin with `async` `await`: https://github.com/Kentico/kontent-gatsby-packages/blob/master/packages/gatsby-source-kontent/tests/pluginOptionsSchema.spec.ts 
Found during implementation https://github.com/Kentico/kontent-gatsby-packages/pull/167
=> Update plugin option schema validation code sample

packages/gatsby/index.d.ts
Adds the missing `prevLocation` property to the TypeScript definition for `RouteUpdateArgs`
https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#onRouteUpdate
Fixes #29124
=> fix(gatsby): Add missing prev location TS property for RouteUpdateArgs

packages/babel-plugin-remove-graphql-queries/package.json, packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap, packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js, packages/babel-plugin-remove-graphql-queries/src/index.ts
Added slash to babel-plugin-remove-graphql-queries so imports are following esm syntax on every platform.
`public\\sq\\d\\<hash.json` => `public/sq/d/<hash.json`
I've updated the tests to actually test this behaviour.
[ch22209]
=> fix(babel-plugin-remove-graphql-queries): make sure imports are posix

packages/gatsby-plugin-image/src/babel-helpers.ts, packages/gatsby-plugin-image/src/image-utils.ts, packages/gatsby-plugin-sharp/src/image-data.ts, packages/gatsby-transformer-sharp/src/customize-schema.js
Unifies API to support backgroundColor on both the component and the resolver. This is a breaking API change, as poreviously the resolver took `background`. However that was not actually implemented, so was ignored.
New behaviour is to pass the prop to sharp, so when resizing with a crop fit of e.g. `contain`, sharp uses that as the background color for letterboxing. The value is also set as the background color of the container, meaning that if the image has transparency, if there is no placeholder, or the placeholder is tracedSVG then the background is visible.
[ch22667]
=> feat(gatsby-plugin-image): Add support for backgroundColor in sharp

packages/gatsby-plugin-styled-components/src/gatsby-node.js
Adds the namespace option to `gatsby-plugin-styled-components`.
Since this is used as part of a classname, the regex `/^-?[_a-zA-Z]+[_a-zA-Z0-9-]*$/` could also be used, but I haven't included it
Already included in styled-components docs
Fixes #29057
=> fix(gatsby-plugin-styled-components): add `namespace` option

packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/image-utils.ts
These fixes are mainly for image providers that generate images on the fly. It correctly handles auto fileformats, for image hosts that use content negotiation instead (like Cloudinary), where prviously it was failing to generate the img tag.  It also adds a large number of breakpoints by default, as they're effectively free.
=> fix(gatsby-plugin-image): Handle breakpoints and auto-format in plugin utils

e2e-tests/gatsby-static-image/cypress/integration/image.js, packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Constrained images were getting an inline style of inline-block which users could not override without a !important. We consider that too opinionated but it's a necessary fallback when images are not otherwise in a container with a display rule.
=> fix(gatsby-plugin-image): Use inline-block in class so users can override

packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Fixes https://github.com/gatsbyjs/gatsby/issues/29112
The latest draft (https://www.w3.org/TR/appmanifest/#platform-member) points the platform members to: https://github.com/w3c/manifest/wiki/Platforms
It now also contains `webapp` which I added here.
=> fix(gatsby-plugin-manifest): Add `webapp` key

packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx, packages/gatsby-plugin-image/src/components/picture.tsx, yarn.lock
This results in sizes on the source element. However, we're still testing to make sure it's appropriately picked up by the browser.
=> fix(gatsby-plugin-image): Pass sizes for source

packages/gatsby-source-contentful/src/fetch.js
When the Contentful API returns an error during sync, `response.data` is not populated here and the fetch fails with `Cannot read property 'items' of undefined`
Move the "Sync progress" below the error handling so we don't attempt to read `response.data.items` (which fails) and instead log the error.
If you have an idea how to test this, I'm happy to do so but it seems the `responseLogger` is currently not really test covered.
=> fix(gatsby-source-contentful): sync crash with error response

yarn.lock
Renovate bot updates left a dirty yarn.lock
=> chore: Dirty yarn.lock

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/image-utils.ts
width and height are not optional. This was causing a type error.
=> fix(gatsby-plugin-image): Update types

docs/docs/how-to/testing/unit-testing.md
Adding `@types/jest` and `@types/react-test-renderer` was an extra step that I had to do in order to get tests to work with TypeScript and Gatsby, so I thought it would be a good contribution to the official docs.
This is the docs 😊
N/A
=> chore(docs): Update TypeScript Unit Testing Docs

packages/gatsby/package.json, packages/gatsby/src/utils/page-data.ts, yarn.lock
Dropped write time for 100k create-pages benchmark from 69s -> 15s for a ~78% decrease
=> fix(gatsby): queue fs writes so event loop not overwhelmed on large sites

packages/gatsby-source-contentful/src/gatsby-node.js
When using contentful environment, we would fail validation as you can setup api keys to only be available to reach the specific environment. By default it's master.
Moved to https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-types/content-type/get-a-single-content-type/console/curl api
=> fix(gatsby-source-contentful): validation with environment

packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Fixes https://github.com/gatsbyjs/gatsby/issues/29112#issuecomment-768449357
According to [the docs](https://joi.dev/api/?v=17.3.0#objectorpeers-options) with `or` already one of the two is required:
> Defines a relationship between keys where one of the peers is **required** (and more than one is allowed)
So having `required()` on both of them leads to the error that it's still required.
=> fix(gatsby-plugin-manifest): Fix `or` Joi assertion

packages/gatsby/package.json, yarn.lock
Upgrades [v8-compile-cache](https://github.com/zertosh/v8-compile-cache/). It's a major bump, but the only [breaking change](https://github.com/zertosh/v8-compile-cache/blob/master/CHANGELOG.md#2018-04-30-version-200) seems to be dropping Node 5 support.
Fixes #29224
=> fix(gatsby): Upgrade v8-compile-cache

packages/gatsby-plugin-image/gatsby-browser.js
Using CJS modules was causing errors in an example project
=> fix(gatsby-plugin-image): Use ESM for gatsby-browser

packages/gatsby/package.json, packages/gatsby/src/utils/api-runner-node.js, yarn.lock
Reduces overhead to invoking APIs by ~40%.
Real-world impact seems around 10-20% for sourcing/transforming data.
=> feat(gatsby): cache/memoize hot functions in runAPI

packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/index.browser.ts, packages/gatsby-plugin-image/src/index.ts
This PR adds a hook to support basic art direction in gatsby-plugin-image. It adds a custom hook, which is passed a "default image" and an array of "art-directed images", which take media queries. It returns an imagedata  object that can be passed to the GatsbyImage component. The layout, placeholder, dimensions etc are all taken from the default image, so if you need to change aspect ratio etc, you need to pass a `className` with media query.
Usage example:
```jsx
import { GatsbyImage, getImage, useArtDirection } from "gatsby-plugin-image"
import "./style.css"
export function MyImage({ data }) {
const images = useArtDirection(getImage(data.largeImage), [
{
media: "(max-width: 1024px)",
image: getImage(data.smallImage),
},
])
return  <GatsbyImage className="art-directed" image={images} /> …
```
=> feat(gatsby-plugin-image): Add useArtDirection hook

packages/gatsby-plugin-sharp/package.json, packages/gatsby-plugin-sharp/src/trace-svg.js, yarn.lock
Ensures that the generated filename is valid. It was breaking on WIndows as the digest included colons.
Fixes #29071
=> fix(gatsby-plugin-sharp): Sanitize tmp filename

packages/gatsby-source-contentful/src/gatsby-node.js
Backporting #29228 to the 2.31 release branch
(cherry picked from commit fb38f8a49c1421b62dcda55f39ce95a721ae92e3)
=> fix(gatsby-source-contentful): validation with environment (#29228)

packages/gatsby-plugin-sharp/src/index.js
The gatsby-image-sharp plugin accepts (among others) a `failOnError` option. This option is not passed down properly during the creation of Base64 images. So if you send a "corrupted" file to it, it will fail, causing the whole build to fail.
Addresses https://github.com/gatsbyjs/gatsby/issues/28203
=> make sure to pass the failOnError option to base64 generation

packages/gatsby-plugin-sharp/src/index.js
Backporting #29254 to the 2.32 release branch
(cherry picked from commit bc0f5c8f12c3bfd01c653e428566ffba5f01edcc)
=> fix(gatsby-plugin-sharp): make sure to pass the failOnError option to base64 generation (#29254)

packages/gatsby-plugin-image/src/components/static-image.server.tsx
Fix the proptype comparison, as it was trying to compare a lower-case value with a camel-case option. I think it's fine to insist on correct casing here.
=> fix(gatsby-plugin-image): Correct layout proptypes in StaticImage

packages/gatsby-plugin-image/src/components/static-image.server.tsx
Backporting #29298 to the 2.32 release branch
(cherry picked from commit 0b6f2e31ec01ee277d9d1e9c91ae0450add3dcfa)
=> fix(gatsby-plugin-image): Correct layout proptypes in StaticImage (#29298)

packages/gatsby-source-contentful/README.md
This adds some brief documentation on how to use the experimental support for gatsby-plugin-image with Contentful
=> docs(gatsby-source-contentful): Add info to readme on use with new image plugin

packages/gatsby-source-contentful/README.md
Backporting #29297 to the 2.32 release branch
(cherry picked from commit c9d4f07f7784b6e3e236c54f324669c7b0c629ae)
=> docs(gatsby-source-contentful): Add info to readme on use with new image plugin (#29297)

docs/docs/reference/release-notes/v2.32/index.md
[Commits](https://github.com/gatsbyjs/gatsby/compare/gatsby@2.32.0-next.0...release/2.32)
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-2-32/docs/docs/reference/release-notes/v2.32/index.md)
=> docs: release notes for v2.32

docs/docs/reference/release-notes/v2.32/index.md
Rendering the release notes as MDX seems to break builds of content sourcing from here (ie on gatsbyjs.com):
```
unknown: Expected corresponding JSX closing tag for  (57:273)
56 | <li parentName="ul">
> 57 | <p parentName="li"><a parentName="p" {...{"href":"https://github.com/Grsmto"}}>{`Grsmto`}</a>{`: fix(gatsby-plugin-image): pass down missing sizes attribute to `}<sources>{` `}<a parentName="p" {...{"href":"https://github.com/gatsbyjs/gatsby/pull/29092"}}>{`PR #29092`}</a></p>
|                                                                                                                                                                                                                                                                                  ^
58 | </li>
```
MDX thinks <sources> …
=> chore: fix mdx for release notes with backticks around <sources>

packages/gatsby-plugin-manifest/src/__tests__/common.js, packages/gatsby-plugin-manifest/src/__tests__/node-helpers.js, packages/gatsby-plugin-manifest/src/common.js, packages/gatsby-plugin-manifest/src/gatsby-node.js, packages/gatsby-plugin-manifest/src/node-helpers.js
This is just slight refactor - it moves code that use `fs` from `common.js` that is shared by `gatsby-node` and `gatsby-ssr` to separate helper to avoid using `fs` in SSR
=> refactor(gatsby-plugin-manifest): don't import fs in ssr code

packages/gatsby-link/index.d.ts, packages/gatsby-link/src/__tests__/index.js, packages/gatsby-link/src/index.js, packages/gatsby-link/src/parse-path.js, packages/gatsby/index.d.ts
This removes these deprecated `gatsby-link` APIs:
- `push`
- `replace`
- `navigateTo`
[ch23293]
=> gatsby-link: remove deprecated APIs

packages/gatsby-source-contentful/package.json, packages/gatsby-source-contentful/src/__tests__/download-with-retry.js, packages/gatsby-source-contentful/src/cache-image.js, packages/gatsby-source-contentful/src/download-with-retry.js, packages/gatsby-source-contentful/src/extend-node-type.js, yarn.lock
Contentful users with a huge number of assets might run into issues when requesting to many low quality image previews.
This adds a concurrency of 100 to the download process and a retry logic based on https://github.com/JustinBeckwith/retry-axios.
The very same logic will be applied when detecting the dominant color and creating a traced svg variant, for both gatsby-image and gatsby-plugin-image
=> feat(contentful): add retry logic to asset downloading

packages/gatsby-cli/src/__tests__/index.ts, scripts/assert-changed-files.sh
=> fix(assert-changed-files): reset to PR branch and not to some history that might not have been changed

.circleci/config.yml, scripts/assert-changed-files.sh
Make assert file more resilient
=> chore: fix reset hard in assert-changed-files

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx, packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Backporting #29333 to the 2.32 release branch
(cherry picked from commit 1443ecde5fe5f6e4b0072239bd3f2688ecb3d260)
=> fix(gatsby-plugin-image): Fix blur up on navigate issue (#29333)

packages/gatsby-source-wordpress/docs/tutorials/querying-data.md
When following these steps I ran into errors as `const { allWpPost } = result.data` was being ran before the graphql promise had finished, `await` was not being used. Adding `await` fixed said errors.
I have added `await` before the `graphql` function in 2 snippets
=> chore(gatsby-source-wordpress): Update querying-data tutorial

docs/docs/building-an-ecommerce-site-with-shopify.md
Correct the `gatsby-node.js` configuration on building-an-ecommerce-site-with-shopify page.
In the document,
> Each page gets assigned a URL in the format of /products/[product handle].
but the sample `gatsby-node.js` configuration on the page is
```
createPage({
path: `/product/${node.handle}`,
```
=> chore(docs): Fix product slugs for building-an-ecommerce-site-with-shopify page

packages/gatsby-source-wordpress/docs/tutorials/configuring-wp-gatsby.md
Links to assets have been broken after migration from `wordpress-experimental` pointing to root `docs/assets` folder.
The proper URL should be prefixed with `/packages/gatsby-source-wordpress`
=> docs(wordpress): fix broken assets link after migration

integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
SSR snapshot tests are failing because of whitespace changes in the stacktrace
=> fix(tests): Update SSR error page snapshot

packages/gatsby-plugin-offline/src/gatsby-node.js
Adds AVIF to the static assets pattern. Related to #29375
=> fix(gatsby-plugin-offline): Cache avif images

.circleci/config.yml
Node 14 tests are now set as required, but currently they're not set to run on every PR, just weekly. This PR makes them run every time, and removes the weekly run
=> chore(tests): Enable node 14 tests

packages/gatsby-source-wordpress/README.md
Adds v3 docs to the README as some people can't switch yet.
Fixes https://github.com/gatsbyjs/gatsby/issues/29358
=> chore(gatsby-source-wordpress): Add v3 docs link

docs/docs/resource-handling-and-service-workers.md, packages/gatsby/cache-dir/api-runner-browser.js, packages/gatsby/cache-dir/loader.js, packages/gatsby/cache-dir/page-renderer.js, packages/gatsby/index.d.ts, packages/gatsby/scripts/__tests__/api.js, packages/gatsby/src/utils/api-browser-docs.ts
This removes `getResourcesForPathnameSync`, `getResourcesForPathname`, and `replaceComponentRenderer`.
[ch23864]
=> chore(gatsby): Remove deprecated `gatsby-browser` APIs

packages/gatsby-source-wordpress/docs/migrating-from-other-wp-source-plugins.md
This PR adds a section to the docs on migrating from `gatsby-source-wordpress-experimental`.
=> docs(gatsby-source-wordpress): add migration from experimental instructions

packages/gatsby-source-wordpress/docs/features/preview.md
This PR adds a couple extra considerations folks need to make when setting up preview or debugging non-functional previews.
=> docs(gatsby-source-wordpress): Add preview caveats

packages/gatsby-plugin-image/package.json, packages/gatsby-source-contentful/package.json, packages/gatsby-transformer-sharp/package.json
These deps are missing from package.json and they fail with yarn2 resolutions.
=> fix: add common-tags to package.jsons

packages/gatsby/src/redux/reducers/queries.ts, packages/gatsby/src/redux/types.ts, packages/gatsby/src/utils/page-data.ts
Deleting stale page-data files from previous builds doesn't clean up our query tracking state. This can result in following kind of errors at SSG step:
```
error: ENOENT: no such file or directory, open '/Users/misiek/dev/pgs-gatsby/integration-tests/artifac
ts/public/page-data/stale-pages/only-in-first/page-data.json'
```
It can be reproduced by conditionally adding/removing page between builds where we wouldn't clear cache in between runs:
- page 1: build page X
- page 2: don't build page X (just not create this page) - here page-data for page X will be deleted, but `queries` reducer will still keep track of it
- page 3: build page X again (page-data doesn't exist but we don't recreate page-data because cache thinks it still exists) -> result in error trying to read file that doesn't …
=> fix: clear tracked queries when deleting stale page-data files

packages/gatsby-plugin-offline/src/gatsby-node.js
Backporting #29394 to the 2.32 release branch
(cherry picked from commit 0a42d07b55644835ded4de2f8a6952a9f3f81602)
=> fix(gatsby-plugin-offline): Cache avif images (#29394)

docs/docs/how-to/sourcing-data/sourcing-from-the-filesystem.md, docs/docs/recipes/querying-data.md, docs/docs/recipes/sourcing-data.md, docs/docs/reference/gatsby-cli.md
This PR updates a number of outdated links in the docs.
The links to `/docs/introducing-graphiql/` have been updated to  `/docs/how-to/querying-data/running-queries-with-graphiql/` on:
o https://www.gatsbyjs.com/docs/reference/gatsby-cli/
o https://www.gatsbyjs.com/docs/recipes/querying-data/
o https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-the-filesystem/
o https://www.gatsbyjs.com/docs/recipes/sourcing-data/
The link to `docs/gatsby-starters/` has been updated to `docs/starters/` on:
o https://www.gatsbyjs.com/docs/reference/gatsby-cli/
=> Fix outdated docs links

docs/docs/reference/graphql-data-layer/schema-customization.md, packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap, packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap, packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap, packages/gatsby/src/schema/__tests__/build-schema.js, packages/gatsby/src/schema/__tests__/print.js, packages/gatsby/src/schema/extensions/__tests__/child-relations.js, packages/gatsby/src/schema/extensions/__tests__/interfaces.js, packages/gatsby/src/schema/extensions/index.js, packages/gatsby/src/schema/print.js, packages/gatsby/src/schema/schema.js
This PR adds support for interface inheritance that effectively replaces `@nodeInterface` directive. Now you can write:
```graphql
interface TeamMember implements Node {
id: ID!
}
```
The previous format is still supported but deprecated and will be removed in Gatsby v4:
```graphql
interface TeamMember @nodeInterface {
id: ID!
}
```
TODO:
See https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#queryable-interfaces-with-the-nodeinterface-extension
=> feat(gatsby): support interface inheritance

packages/gatsby-plugin-image/src/components/hooks.ts, packages/gatsby-plugin-image/src/index.browser.ts, packages/gatsby-plugin-image/src/index.ts
By giving the helper function hook names (beginnign with `use`), the eslint React hooks plugin enforces rules of hooks. This is not needed, and prevents people e.g. using them inside loops or in other functions. As we don;t use any React hooks ourselves, we're free to choose other names.
=> fix(gatsby-plugin-image): Rename hooks

packages/gatsby-source-wordpress/README.md
This change updates the README to not use multiple h1s, per SEO and a11y best practices
=> chore(gatsby-source-wordpress): remove multiple h1s from README

packages/gatsby/package.json, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/__tests__/show-experiment-notice.js, packages/gatsby/src/utils/handle-flags.ts, packages/gatsby/src/utils/show-experiment-notice.ts
There is weird interaction in some terminals with our usage of terminal-link and ink where following lines turn blank.
Let's just remove our usage of terminal-link as value it provides is not worth spending a lot of time on figuring exact reason for this.
For details on how problem looks like, check #29293
Note - we do still use `terminal-link` in `create-gatsby` and `gatsby-recipes`, but it's not clear if it's usage there cause problems or not, so this PR is scoped just to `gatsby` core package
Fixes #29293
=> fix: drop terminal-link

packages/gatsby-source-wordpress/docs/tutorials/index.md
fix `Back to README.md` link for tutorials markdown file
=> docs(gatsby-source-wordpress): fix back to readme.md link

packages/gatsby-plugin-styled-components/README.md, packages/gatsby-source-graphql/README.md
Updating a couple official plugins to not use multiple h1 tags in their READMEs to adhere to SEO and a11y best practices
=> chore: remove multiple h1s from official plugin docs

packages/gatsby/package.json, packages/gatsby/src/utils/__tests__/handle-flags.ts, packages/gatsby/src/utils/__tests__/show-experiment-notice.js, packages/gatsby/src/utils/handle-flags.ts, packages/gatsby/src/utils/show-experiment-notice.ts
Backporting #29472 to the 2.32 release branch
(cherry picked from commit 260c29795537bb2e5bf04f0f719b5aeadbb3cc16)
=> fix: drop terminal-link (#29472)

packages/gatsby-recipes/package.json, packages/gatsby/package.json, packages/gatsby/src/schema/types/__tests__/filter-input.js, packages/gatsby/src/schema/types/sort.ts, yarn.lock
This PR restores the behavior of v2 when converting types to input types. Now, whenever we see a field of union type we won't add it to the input type.
This fix in `graphq-compose` has made this possible: https://github.com/graphql-compose/graphql-compose/pull/318
=> fix(gatsby): skip unions in input types

packages/gatsby/src/query/__tests__/graphql-runner.ts, packages/gatsby/src/query/graphql-runner.ts, packages/gatsby/src/query/query-runner.ts
When querying `deprecated` field, argument or input field in your query Gatsby will show a deprecation warning in CLI.
Example type def:
```js
exports.createSchemaCustomization = ({ actions }) => {
const { createTypes } = actions
createTypes(`
type MarkdownRemark implements Node {
frontmatter: Frontmatter
}
type Frontmatter {
description: String @deprecated(reason: "Use title instead.")
}
`)
}
```
Example query:
```graphql
query {
allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }) {
nodes {
frontmatter {
description
}
}
}
}
```
Will produce a warning like this:
=> feat(gatsby): display GraphQL deprecations as CLI warnings

starters/gatsby-starter-minimal/src/pages/index.js
This fixes react runtime errors in the console regarding missing key values for the HTMLLineItemElement
=> Update index.js to stop React errors in console about the 'key'

docs/docs/how-to/sourcing-data/sourcing-from-json-or-yaml.md
Updating how-to guide in section "Configure Gatsby pages" with suggested yaml.load function.
Error says "Function yaml.safeLoad is removed in js-yaml 4. Use yaml. load instead, which is now safe by default."
=> chore(docs): Update sourcing-from-json-or-yaml
