gatsbyjs/gatsby

packages/gatsby-recipes/package.json
packages/gatsby/package.json

`graphql-compose` is so deeply integrated into our GraphQL layer that even minor changes there can cause unexpected side effects for schema building. We want to stay on a safer side of things with this key dependency.
So changing semver dependency from `minor` level to `patch`.

chore(gatsby): pin graphql-compose version to patch

---

packages/babel-plugin-remove-graphql-queries/src/index.ts
packages/gatsby/cache-dir/__tests__/static-entry.js
packages/gatsby/cache-dir/api-runner-ssr.js
packages/gatsby/cache-dir/develop-static-entry.js
packages/gatsby/cache-dir/static-entry.js
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/services/initialize.ts
packages/gatsby/src/utils/start-server.ts
packages/gatsby/src/utils/worker/child.ts
packages/gatsby/src/utils/worker/render-html.ts

refactor(html-ssr): remove fs from ssr bundle, remove static queries from ssr bundle

---

integration-tests/gatsby-cli/__tests__/new.js

The CLI tests are failing because they're looking for specific messages from npm which aren't there. I've removed them, because it's not relevant to our own tests.

tests: Fix cli integration test

---

packages/gatsby-recipes/recipes/sass.mdx

Changes `https://sass-lang.com/documentationb` to `https://sass-lang.com/documentation`, I checked `documentationb` to make sure and it 404s

Fix URL typo in sass recipe

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/gatsby-node.js
integration-tests/artifacts/gatsby-ssr.js
integration-tests/artifacts/src/components/post-body-components-ssr.js
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
packages/gatsby/src/redux/reducers/html.ts
packages/gatsby/src/redux/types.ts

For `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES`:
Html files also will need to regenerate when SSR bundle changes (it can change even if browser bundle did not, which is what this feature was only tracking so far)
PR builds on https://github.com/gatsbyjs/gatsby/pull/29473
[ch23314]

feat(conditional-page-builds): track ssr compilation hash

---

docs/docs/conditional-page-builds.md
integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/gatsby-node.js
integration-tests/artifacts/src/pages/static-query-result-tracking/rerun-query-but-dont-recreate-html.js
integration-tests/artifacts/src/pages/static-query-result-tracking/should-invalidate.js
integration-tests/artifacts/src/pages/static-query-result-tracking/stable.js
packages/gatsby/src/commands/build-utils.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/query/query-runner.ts
packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
packages/gatsby/src/redux/reducers/html.ts
packages/gatsby/src/redux/types.ts

For GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES:
Tracks static query results and mark html files as dirty if static query used by a template changes
PR builds on #29482
[ch23312]

feat(conditional-page-builds): track static query results

---

packages/gatsby-source-wordpress/README.md

There are a couple broken links on the WP readme

docs(gatsby-source-wordpress): remove broken links

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/gatsby-node.js
integration-tests/artifacts/src/templates/deps-page-query-alternative.js
packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
packages/gatsby/src/redux/reducers/html.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/page-data.ts

For GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES:
Tracks page-data content and not just page query result (this will cover changes like used `component` (template) etc)
PR builds on #29486
[ch23316]

fix(conditional-page-builds): track page data and not page query

---

packages/gatsby/src/utils/webpack/static-query-mapper.ts

webpack 5: ensure static query hashes array has deterministic order, only dispatch actions if that list changed

---

packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/webpack/tmp-mini-css-extract-contenthash-overwrite.ts

hack: overwrite contenthash set by mini-css-extract-plugin

---

packages/gatsby-plugin-styled-components/src/gatsby-node.js

Put back the option in the plugin: https://github.com/styled-components/babel-plugin-styled-components/pull/288

fix(gatsby-plugin-styled-components): Support `topLevelImportPaths` option

---

packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/commands/build.ts

This just moves "nitty-gritty" details into service-like function to make `build.ts` command leaner and easier to scan
PR builds on https://github.com/gatsbyjs/gatsby/pull/29498

chore(build): move html generation to separate function

---

packages/gatsby-source-contentful/src/cache-image.js
packages/gatsby-source-contentful/src/extend-node-type.js

Current release is broken. We made a mistake by mixing require and import syntax 😅

fix(contentful): fix import

---

packages/gatsby-source-shopify/src/nodes.js

This fixes [a bug](https://github.com/gatsbyjs/gatsby/issues/29409) where old images remain cached in Gatsby after they are updated in Shopify. 
Fixes #29409

fix(gatsby-source-shopify): Don't remove version string from Shopify image URLs

---

packages/gatsby-plugin-image/src/resolver-utils.ts
packages/gatsby-source-contentful/src/extend-node-type.js
packages/gatsby-source-contentful/src/schemes.js

Contentful doesn't support AVIF. This fixes the resolver, and adds a check in the url builder

fix(gatsby-source-contentful): Correct supported image formats

---

packages/gatsby/cache-dir/gatsby-browser-entry.js

Fixes
```
warn export 'push' (reexported as 'push') was not found in 'gatsby-link' (possible exports: __esModule, default, navigate, parsePath, withAssetPrefix,
withPrefix)
warn export 'replace' (reexported as 'replace') was not found in 'gatsby-link' (possible exports: __esModule, default, navigate, parsePath, withAssetPrefix,
withPrefix)
warn export 'navigateTo' (reexported as 'navigateTo') was not found in 'gatsby-link' (possible exports: __esModule, default, navigate, parsePath,
withAssetPrefix, withPrefix)
```

fix(gatsby): fix deprecation export messages

---

packages/gatsby/src/redux/actions/public.js

With the v3 change to touchNode, a subtle bug was introduced - previously calling touchNode on an id for a node that no longer exists worked fine, now Gatsby will throw errors about accessing `id` on undefined. This PR accounts for that situation 👍

fix(gatsby): prevent errors when backwards compat node.nodeId is for a deleted node in touchNode

---

docs/docs/conceptual/choosing-a-cms.md
docs/docs/conceptual/gatsby-for-ecommerce.md
docs/docs/conceptual/using-gatsby-image.md
packages/gatsby-remark-embed-snippet/README.md
packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md
packages/gatsby/CHANGELOG.md

Changes were:
- `Github` -> `GitHub`
- `Javascript` -> `JavaScript`
- `Typescript` -> `TypeScript`
- `Wordpress` -> `WordPress`

docs: fix case of GitHub, JavaScript, TypeScript and WordPress

---

docs/docs/caching.md

`setup` → `set up` (`setup` is the noun form; `set up` is the verb form)

chore(docs): Fix caching typo

---

integration-tests/gatsby-cli/__tests__/new.js

Backporting #29525 to the 2.32 release branch
(cherry picked from commit 6ef2f802c345796dab975c0f20802d18baf63fcd)

tests: Fix cli integration test (#29525)

---

packages/gatsby-plugin-image/src/components/hooks.ts
packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx

Apply inline styles to the wrapper element if the plugin isn't installed. Add width and height props to the img tag. They're not needed as we use CSS, but Lighthouse warns about them anyway

fix(gatsby-plugin-image): Apply inline styles and img size

---

packages/gatsby-plugin-image/src/resolver-utils.ts

Although the ENUM is `[AUTO, WEBP]`, the string value of `AUTO` is `""`, so this was causing errors.

fix(gatsby-plugin-image): Correct default enum value

---

packages/gatsby-source-npm-package-search/src/gatsby-node.js

https://github.com/gatsbyjs/gatsby/pull/29369 prevented `childMarkdownRemark` from ever being added due to `@dontInfer`, so let's actually annotate type, so remark handling children are attached (`MarkdownRemark` and `Mdx`) 
Due to https://github.com/gatsbyjs/gatsby/pull/29369

fix(npm-package-search): declare mimeType so markdown trasformer children are added

---

packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/commands/build.ts

just cleaning things up, `--log-pages` and `--write-to-file` are handled by yargs, so let's not check `process.argv` separately
https://github.com/gatsbyjs/gatsby/pull/29548#discussion_r577589506
[ch25550]

chore(build): use params from yargs and don't check process.argv

---

packages/gatsby/src/redux/reducers/html.ts

This is just adding some context why `html` reducer doesn't "care" directly about page query result
Addressing comment - https://github.com/gatsbyjs/gatsby/pull/29498#discussion_r576984765
[ch25549]

chore(html): add context about not handling page query result directly in html reducer

---

packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/types.ts

Cleanup after https://github.com/gatsbyjs/gatsby/pull/29473 which removed `setPageData` usage, but not action creator and corresponding types
[ch25548]

chore(conditional-page-builds): remove dead `setPageData` action

---

packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/utils/__tests__/__snapshots__/sample-site-for-experiment.ts.snap
packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
packages/gatsby/src/utils/webpack-utils.ts
packages/gatsby/src/utils/webpack.config.js

I did some more researching and we can disable fullySpecified in better way for all ESM modules. This allows us to skip fullySpecified on all js loaders.
`import ky from "ky"` inside your project to trigger this bug.

fix(gatsby): cleanup fullySpecified resolving

---

packages/gatsby/package.json

Noticed in one of recent PRs that we still had `friendly-errors-webpack-plugin` package as dependency even tho we didn't use it for a long time.
lock file not changed because this package is still used in https://github.com/gatsbyjs/gatsby/blob/7e03dc75971e325987712d4f8c5c821db28812d8/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

chore(gatsby): drop unused friendly-errors-webpack-plugin dep

---

packages/gatsby-plugin-sharp/README.md
packages/gatsby-plugin-sharp/src/__tests__/plugin-options.ts
packages/gatsby-plugin-sharp/src/plugin-options.js

Backporting #29564 to the 2.32 release branch
(cherry picked from commit 107926a7d23901fa3e645a966bd6aa793fb0ddd3)

fix(gatsby-plugin-sharp): Fix defaults handling (#29564)

---

packages/gatsby/package.json
packages/gatsby/src/utils/webpack.config.js
yarn.lock

https://github.com/sysgears/webpack-virtual-modules/pull/78 seems to break recompiling virtual modules in webpack@5, so this PR downgrades us back to previous version
[ch25574]

fix(webpack): don't disable webpack's cache

---

packages/gatsby-plugin-image/src/components/__tests__/hooks.ts
packages/gatsby-plugin-image/src/components/hooks.ts
packages/gatsby-plugin-image/src/index.browser.ts
packages/gatsby-plugin-image/src/index.ts

This allows the `getImage` and `getSrc` helpers to take nodes other than `File` nodes, as long as they include a `gatsbyImageData` field, for example `ContentfulAsset`s, and allows `getSrc` to take imageData directly. It also adds a stack of unit tests, and a similar `getSrcSet` helper.

feat(gatsby-plugin-image): Allow image helpers to take other node types

---

packages/gatsby-source-contentful/package.json
packages/gatsby-source-contentful/src/gatsby-node.js
yarn.lock

Network errors can happen any time, our credential check had no retry which broke some builds because of network hick-ups.
This adds a small retry wrapper to the fetch call via https://github.com/vercel/fetch-retry to solve this issue.
Will add tests for (retrying of) network errors later on when adding retry to other parts of the plugin the near future.

fix(contentful): retry on network errors when checking credentials

---

packages/gatsby-image/README.md
packages/gatsby-plugin-image/README.md
packages/gatsby-transformer-sharp/src/customize-schema.js

This adds a warning when using the fixed and fluid resolvers, as well as a warning to the top of the gatsby-image readme. It also removes the beta warnings for the new resolver.
[ch24890]

chore: Deprecate gatsby-image and old image resolvers

---

.circleci/config.yml
scripts/assert-changed-files.sh

Backport #29328 to release 2.32 so that Windows tests work in the release branch
(cherry picked from commit 79518c4e1e8d7559f49a46f192ea87584dd4bbfc)

chore: fix reset hard in assert-changed-files (#29328)

---

packages/gatsby/cache-dir/app.js

This handle 2 issues:
1) > Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8000/commons.css".
When there is no css, we add `commons.css` link but we don't actually generate it, so we serve our `index.html` instead for that request, which cause warning as above + generally is wonky
2) In develop when you remove "last" .css import - the styles stay behind, because `commons.css` is not "regenerated" but it continue to exist in `webpack-dev-middleware` in-memory filesystem. Having that blank `.css` import actually ensure that when user removes their last `.css` `commons.css` updates (to empty file), meaning that we don't leave stale styles behind
[ch25434]

fix(develop): add blank .css to ensure mini-css-extract-plugin always has something to extract

---

packages/gatsby-plugin-canonical-urls/src/gatsby-node.js

Fix https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-342251
With `DEV_SSR`, the plugin now errors if you don't set the required `siteUrl` option. It didn't actually work before but at least it didn't work silently :-D

feat(gatsby-plugin-canonical-urls): Add plugin validation

---

packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts
packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
packages/gatsby-plugin-page-creator/src/derive-path.ts
packages/gatsby-plugin-page-creator/src/error-utils.ts
packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
packages/gatsby-plugin-sharp/src/__tests__/index.js
packages/gatsby-plugin-sharp/src/__tests__/utils.js
packages/gatsby-plugin-sharp/src/image-data.ts
packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js
packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
packages/gatsby-source-filesystem/src/__tests__/utils.js
packages/gatsby-source-wordpress/src/models/logger.ts
packages/gatsby-source-wordpress/src/steps/preview/index.ts
packages/gatsby-source-wordpress/src/steps/temp-prevent-multiple-instances.ts
packages/gatsby-transformer-remark/src/__tests__/extend-node.js
packages/gatsby/package.json
packages/gatsby/reporter.d.ts
packages/gatsby/reporter.js

Shimming the reporter in gatsby allows us to refactor it in the future without a breaking change. I was supprised so little packages were relying on the direct import of reporter.
[ch23107]

feat: shim reporter from gatsby

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/src/components/magic-comments/prefetch.js
integration-tests/artifacts/src/components/magic-comments/preload.js
integration-tests/artifacts/src/pages/dynamic-imports-magic-comments.js
packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts
packages/gatsby/src/utils/worker/render-html.ts

This re-adds prefetch/preload links from webpack's magic comments ( `import(/* webpackChunkName: "<chunk_name>", webpackPrefetch: true */ "<path_to_module>")`)
TODO:
[ch25483]

fix(gatsby): re-add prefetch/preload links for child assets

---

docs/docs/debugging-html-builds.md

We're rolling out SSR for the develop server so people will need to adjust custom/plugin code to account for the `develop-html` stage as well as `build-html`.

chore(docs): Update debugging-html-builds

---

package.json

Let's look at all files so we're sure things are correct. It should remove weirdness between machines.

chore: remove --cache from eslint

---

packages/gatsby-plugin-gatsby-cloud/package.json

Updating the manifest plugin for use with Webpack 5 and updating Gatsby peer dependency to 3

chore(gatsby-plugin-gatsby-cloud): Update for gatsby v3

---

e2e-tests/development-runtime/cypress/support/commands.js

Just noticed this in some tests - did it work at all?

fix(e2e-development-runtime): fix typo / optiosn is not defined

---

docs/docs/graphql-reference.md
packages/gatsby/src/schema/__tests__/fixtures/regex-query.js
packages/gatsby/src/schema/__tests__/queries.js
packages/gatsby/src/utils/prepare-regex.ts

attempt to fix character escape sequences in `regex` filters, i.e. queries like:
```js
export const query = graphql`
{
allFile(filter: {base: {regex: "/\\w+\\.PNG$/i"}}) {
nodes { base }
}
}
`
```
this is a follow-up to #25047 which was closed prematurely.
- removes the backslash `replace`ing from [`utils/prepare-regex.ts`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/prepare-regex.ts#L9-L12) which is not needed (any more? might have been before the switch away from relay)
- removes comment about double-escaping from the docs
- in tests, double-escaping is necessary when query is inline (see e.g. [this test here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/__tests__/prepare-regex.js#L21-L55)). i have added two query tests in this pr …

fix(gatsby): character escape sequences in regex filter in graphql queries

---

.eslintrc.js
packages/create-gatsby/src/index.ts
packages/gatsby-admin/src/components/plugin-search.tsx
packages/gatsby-admin/src/components/providers.tsx
packages/gatsby-admin/src/utils/use-npm-data.tsx
packages/gatsby-cli/src/reporter/reporter.ts
packages/gatsby-plugin-image/src/components/hooks.ts
packages/gatsby-plugin-image/src/components/later-hydrator.tsx
packages/gatsby-plugin-image/src/components/placeholder.tsx
packages/gatsby/src/redux/actions/restricted.ts
packages/gatsby/src/utils/webpack-utils.ts

I made a mistake in the syntax when I upgraded the typescript-eslint rules

chore: Fix broken eslint rule

---

packages/gatsby-plugin-image/src/image-utils.ts

Fix a bug in the image plugin toolkit where default layout and formats were not set if width and height were provided

fix(gatsby-plugin-image): Apply defaults when width and height are set

---

packages/gatsby-source-contentful/package.json
yarn.lock

As we are about to have a major release, this bumps the Contentful SDK to the latest version.
Breaking: Minimum node version is now v12

chore(gatsby-source-contentful): migrate to latest Contentful SDK

---

.circleci/config.yml

This reverts commit d85638fb from #29728 to unblock us.
The check will be restored in https://github.com/gatsbyjs/gatsby/pull/29730

Revert "tests: Check for dirty yarn.lock (#29728)"

---

packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/root.js

Backport https://github.com/gatsbyjs/gatsby/pull/29692 to 2.32

fix(gatsby): render QoD overlay in its own root element to avoid hydration issues

---

packages/gatsby-plugin-sharp/src/index.js

fix(gatsby-plugin-sharp): Add srcSetType `image/avif` to gatsby-plugin-sharp

---

packages/gatsby/src/redux/actions/public.js

One deprecation warning per plugin is enough - let's not spam terminal output for each usage
[ch25797]

fix: don't print deprecation warning for deleteNode for the sample plugin multiple times

---

packages/gatsby/src/redux/actions/public.js

One deprecation warning per plugin is enough - let's not spam terminal output for each usage
[ch25565]

fix: don't print deprecation warning for touchNode for the sample plugin multiple times

---

packages/gatsby-plugin-feed/package.json
packages/gatsby-plugin-feed/src/gatsby-node.js

…(#29616)
Co-authored-by: Hector Alcazar <halcaza@US-C02DKA1XMD6M>
Co-authored-by: gatsbybot <mathews.kyle+gatsbybot@gmail.com>
(cherry picked from commit 5fb606416a2d0697319501787a0a47cf74142001)

fix(gatsby-plugin-feed): Replace deprecated "fs.exists" call (#29616)

---

docs/docs/reference/built-in-components/gatsby-plugin-image.md

Adds documentation for the helper functions `getImage`, `getSrc`, `getSrcSet` and `withArtDirection`. Also adds clarification on using the plugin with CMSs.
[rendered file](https://github.com/gatsbyjs/gatsby/blob/docs/art-direction/docs/docs/reference/built-in-components/gatsby-plugin-image.md)
[ch24526]

docs(gatsby-plugin-image): Add docs on helper functions

---

packages/gatsby/package.json
yarn.lock

The latest release of `mini-css-extract-plugin` breaks us (discovered this via failing production e2e tests). This PR pins `mini-css-extract-plugin` to the previous working version to unblock us (for now).
This PR seems to cause the problem for us: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/703

fix(gatsby): temporarily pin mini-css-extract-plugin version

---

packages/gatsby-plugin-mdx/gatsby/on-create-node.js

Fix relative import resolution in mdx for windows
```mdx
import image from './your-image.png'
```
It generates `import image from "..\\..\\..\\..\\content\\your-image.png";`
With this PR we convert it to `import image from "../../../../content/your-image.png";`

fix(gatsby-plugin-mdx): fix relative imports

---

.eslintrc.js
packages/gatsby-link/index.d.ts
packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts
packages/gatsby/src/joi-schemas/joi.ts
packages/gatsby/src/redux/plugin-runner.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/schema/infer/__tests__/inference-metadata.ts
packages/gatsby/src/utils/api-node-docs.ts
packages/gatsby/src/utils/fast-refresh-module.ts
packages/gatsby/src/utils/webpack/__tests__/corejs-resolver.ts

The eslint config for our monorepo was in a broken state, which led to my IDE complaining about it and the affected rules not working.
Since `naming-convention` now works I had to change stuff a bit. I just wanted the errors to go away, didn't fix any. We should do that sometime later and actually enforce our styleguide.

chore: Fix our internal eslint config for monorepo

---

packages/gatsby-plugin-less/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-less/src/gatsby-node.js
packages/gatsby-plugin-netlify-cms/package.json
packages/gatsby-plugin-postcss/src/__tests__/__snapshots__/gatsby-node.test.js.snap
packages/gatsby-plugin-postcss/src/gatsby-node.js
packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-sass/src/gatsby-node.js
packages/gatsby-plugin-stylus/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-stylus/src/__tests__/gatsby-node.js
packages/gatsby-plugin-stylus/src/gatsby-node.js
packages/gatsby/package.json
packages/gatsby/src/utils/webpack-utils.ts
yarn.lock

This moves back to setup we had in v2 pretty much.
https://github.com/gatsbyjs/gatsby/pull/29773
https://github.com/webpack-contrib/mini-css-extract-plugin/pull/703#issuecomment-786118190

fix(mini-css-extract): don't use loader in ssr

---

packages/create-gatsby/src/features.json

Adds support for installing the cloud plugin with npm init gatsby

feat(create-gatsby): Add support for cloud plugin

---

packages/gatsby-plugin-subfont/README.md

docs(gatsby-plugin-subfont): correct property name

---

packages/gatsby/package.json
packages/gatsby/src/utils/eslint-config.ts

Fix eslint issues when .eslintrc is present + overall improvements
- Disable require babelrc file
- force @babel/eslint-parser for default eslint rules

fix(gatsby): eslint linting

---

examples/using-css-modules/src/pages/another-page.js
examples/using-css-modules/src/pages/index.js
examples/using-css-modules/src/pages/sassy-page.js
examples/using-css-modules/src/styles/another-page.module.css

This PR fixed a broken using-css-modules example.
In Gatsby v3, CSS Modules are imported as ESModules.

fix(example): import styles as ESModules

---

packages/gatsby/src/schema/schema.js

We've noticed that the query running step on v3 is pretty slow. After investigation, the issue was discovered in `graphql-compose`: https://github.com/graphql-compose/graphql-compose/issues/319
This PR is a workaround for it. But the proper fix should be added in `graphql-compose` itself. Once fixed upstream, we can remove this workaround.

fix(gatsby): workaround graphql-compose issue

---

e2e-tests/development-runtime/cypress/integration/hot-reloading/gatsby-browser.js
e2e-tests/development-runtime/gatsby-browser.js
e2e-tests/development-runtime/src/wrap-root-element.js
packages/gatsby/cache-dir/api-runner-browser.js
packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/root.js
packages/gatsby/src/utils/webpack-utils.ts
packages/gatsby/src/utils/webpack.config.js

After dropping `react-hot-loader` we need to accept hot updates ourselves. We do so today for page templates but not above those. Anything imported by `gatsby-browser` files is above page templates in webpack's hierarchy and so those are not handled.
TODO:
https://github.com/system-ui/theme-ui/issues/1440 (not in our repo, but pretty much our issue)

fix(hmr): accept hot updates for modules above page templates

---

examples/simple-auth/src/components/Form/index.js
examples/simple-auth/src/components/Header/header.module.css
examples/simple-auth/src/components/Header/index.js
examples/simple-auth/src/components/Layout/index.js
examples/simple-auth/src/components/Status/index.js
examples/simple-auth/src/components/View/index.js

This PR fixed a broken simple-auth example.
In Gatsby v3, CSS Modules are imported as ESModules.
* rename Invalid style name(`header__link--home`) as ESModule. 
* remove unused styles.
related #29818

fix(example): import styles as ESModules in simple-auth

---

packages/gatsby/cache-dir/loading-indicator/indicator.js

This PR fixes the query on-demand loading indicator always being active when using gatsby with preact.
This is caused by preact not rendering attributes with a literal bool `false` value. Turning the bool value into a string before passing it to preact solved the issue.
Fixes #29051

fix: query on demand loading indicator always active on preact.

---

examples/using-page-transitions/README.md

This PR fixed outdated docs.
[react-pose has been deprecated by framer motion](https://popmotion.io/pose/).

fix(docs): update library link in docs

---

packages/gatsby/cache-dir/fast-refresh-overlay/style.js

- Add explicit `color` for the normal text & links
- Rename css vars to semantic ones (preparation for dark mode)

fix(gatsby): Improve Fast Refresh overlay styles

---

packages/gatsby/cache-dir/fast-refresh-overlay/index.js

Fix fast-refresh for gatsby-plugin-preact.
The runtime module isn't being loaded when using preact so gatsbyEvents is not set. This also disables our error modals :grimacing: that's another bug to fix but at least this fixes updates

fix(gatsby-plugin-preact): fix fast-refresh

---

e2e-tests/development-runtime/cypress/integration/styling/plain-css.js
e2e-tests/development-runtime/src/pages/styling/not-visited-plain-css-not-imported-initially.css
e2e-tests/development-runtime/src/pages/styling/not-visited-plain-css.css
e2e-tests/development-runtime/src/pages/styling/not-visited-plain-css.js
e2e-tests/development-runtime/src/pages/styling/plain-css-not-imported-initially.css
e2e-tests/development-runtime/src/pages/styling/plain-css.js
packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/webpack/force-css-hmr-for-edge-cases.ts

Add test cases for issues described in:
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/706
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/708
Current status (tests for removing imports only pass because adding imports doesn't do anything :) ):
With this veeeeeery hacky ~fix~ workaround:
[ch25603]
[ch25604]

fix(gatsby): fix some css HMR edge cases

---

e2e-tests/production-runtime/cypress/integration/scroll-behavior.js
packages/gatsby-react-router-scroll/src/scroll-handler.tsx

Added debounce function to improve scrolling performance.
Fixes #26878

fix(gatsby-react-router-scroll): debounce function for scollListener

---

packages/gatsby-source-contentful/package.json
packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
packages/gatsby-source-contentful/src/download-contentful-assets.js

Improves contentful progress bar. It flickered on windows as the progressbar was fighting with ink-cli.

fix(gatsby-source-contentful): use reporter progressbar instead of own

---

packages/create-gatsby/src/__tests__/init-starter.ts
packages/create-gatsby/src/init-starter.ts

Two npm 7 fixes. Passes `--legacy-peer-deps` to npm when setting-up, to align behaviour across versions. Also formats package.json, as installing no longer does

fix(create-gatsby): Use legacy peer deps

---

packages/gatsby-plugin-gatsby-cloud/package.json
packages/gatsby-plugin-sharp/package.json
packages/gatsby-remark-embed-snippet/package.json
packages/gatsby-remark-images/package.json
packages/gatsby-source-contentful/package.json
packages/gatsby-source-wordpress/package.json
packages/gatsby-transformer-javascript-frontmatter/package.json
packages/gatsby-transformer-sharp/package.json
packages/gatsby-transformer-sqip/package.json

Make sure peerdeps are pointing to new version
We should figure a better version strategy out :D

chore: update peerdeps to latest major versions

---

docs/docs/conceptual/gatsby-core-philosophy.md
docs/docs/images-and-files.md
docs/docs/plugins.md
docs/docs/porting-an-html-site-to-gatsby.md
docs/docs/porting-from-create-react-app-to-gatsby.md
docs/docs/reference/built-in-components/gatsby-image.md
docs/docs/working-with-images.md

We have good docs coverage for the new plugin, but we're not replacing every single existing doc/reference. We'll do that over time, but this should prevent people from going down the wrong path.

docs(gatsby-plugin-image): Point people to the new plugin

---

docs/docs/how-to/testing/unit-testing.md

chore(docs): add paths to unit-testing using typescript

---

packages/gatsby-plugin-image/package.json

Updates peer dependencies to latest major, and remove gatsby-image peerdep

fix(gatsby-plugin-image): Update peerdeps

---

packages/gatsby/cache-dir/fast-refresh-overlay/components/graphql-errors.js
packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js

With some custom `.babelrc` configs those can result in wrong transpiled code:
```
var deduplicatedErrors = react__WEBPACK_IMPORTED_MODULE_6__.useMemo(function () {
return [].concat(new Set(errors));
}, [errors]);
```
`Array.from` does same thing without above:
```
var deduplicatedErrors = react__WEBPACK_IMPORTED_MODULE_6__.useMemo(function () {
return Array.from(new Set(errors));
}, [errors]);
```

fix(gatsby): with some custom babel configs array spreading with Set is not safe

---

packages/gatsby-transformer-sharp/src/customize-schema.js

Formats can be changed with gatsby-plugin-sharp options. This works for StaticImage but currently breaks for GatsbyImage because gatsby-transformer-sharp defaults it for you. Since we're already handling it inside plugin-sharp we can remove the resolver default.

fix(gatsby-transformer-sharp): Fix options override

---

packages/gatsby/cache-dir/fast-refresh-overlay/components/overlay.js

Adds a "ltr" [direction](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) to prevent issues when working within "rtl" sites. The most problematic fix is the stack trace which gets completely mangled:

fix(gatsby): Add dir=ltr to Fast Refresh overlay

---

docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md

I've updated the details for how a user should add hosting details for their site based on the new functionality we're launching in Gatsby Cloud.

chore(docs): Update hosting instructions in OSS page for Cloud

---

examples/gatsbygram/gatsby-config.js
examples/using-contentful/src/pages/image-api.js
examples/using-emotion-prismjs/package.json
examples/using-emotion-prismjs/src/components/layout.js
examples/using-emotion-prismjs/src/pages/index.js
examples/using-emotion-prismjs/src/prism-styles.js
examples/using-emotion-prismjs/src/templates/blog-post.js
examples/using-emotion/package.json
examples/using-emotion/src/pages/index.js
examples/using-gatsby-image/package.json
examples/using-gatsby-image/src/components/image-gallery.js
examples/using-gatsby-image/src/components/navigation.js
examples/using-gatsby-image/src/components/page-title.js
examples/using-gatsby-image/src/pages/index.js
examples/using-remark-copy-linked-files/gatsby-config.js
examples/using-shopify/src/components/image-picker.js
examples/using-shopify/src/components/product-list.js
examples/using-shopify/src/components/product.js
examples/using-square-payments/package.json
examples/using-stylus/src/pages/css-modules.js

All of them build except for the WordPress sites which haven't yet been upgraded for the major release of gatsby-source-wordpress.
The following sites emit warnings about upgrading to gatsby-plugin-image:
- gatsbygram
- using-mdx
- using-cypress
- using-drupal
- using-gatsby-image
- using-multiple-themes
- using-shopify

fix(gatsby): Update example sites to build with Gatsby v3

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

Includes drafted content up to, and including "escape sequence for `regex` filter".
[Rendered view](https://github.com/gatsbyjs/gatsby/blob/docs/v3-migration-guide/docs/docs/reference/release-notes/migrating-from-v2-to-v3.md)
[ch24734]
---
Previous two migration guides:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/reference/release-notes/migrating-from-v0-to-v1.md
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/reference/release-notes/migrating-from-v1-to-v2.md

chore(docs): Migrating from v2 to v3

---

docs/docs/reference/release-notes/v3.0/index.md

chore(docs): Improve `fs` section of release notes

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

I thought we'd already made this change, but making it now. This is an invalid config.

docs (gatsby-plugin-image): Remove filesystem from config

---

docs/docs/reference/release-notes/v3.0/index.md

fix(release-notes): adjust casing in link to migration guide

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

This document is no longer "work in progress" - we still might add to it as we will find specific quirks and edge cases mostly exposed by upstream bumps and user reports, but this document does already cover all Gatsby specific changes

docs(migrating-from-v2-to-v3): drop "work-in-progress" note

---

starters/blog/src/components/bio.js
starters/default/src/pages/index.js
starters/hello-world/README.md
starters/hello-world/package-lock.json
starters/hello-world/package.json

Update hello-world (same as https://github.com/gatsbyjs/gatsby/pull/29919) and use AVIF in blog/default

chore(starters): Update hello-world and AVIF

---

scripts/publish-starters.sh

Two things here:
1. push to current branch and don't presume it's `master` branch
2. skip `gatsby-starter-wordpress-blog` publishing for now as there are some changes in starter repo that are not here - so until we update starter in this repo, let's not push from it.

fix(publish-starters): don't presume 'master' is default branch

---

scripts/publish-starters.sh

Apparently `==` doesn't work :)
so reverting to single `=` we had before for line 38 and applying it in skip check
should fix:
```
./scripts/publish-starters.sh: 22: [: gatsby-starter-wordpress-blog: unexpected operator
./scripts/publish-starters.sh: 38: [: null: unexpected operator
```

fix(publish-starters): fix syntax

---

docs/docs/how-to/styling/css-modules.md
docs/docs/recipes/styling-css.md
docs/docs/reference/release-notes/migrating-from-v1-to-v2.md
docs/docs/tutorial/part-two/index.md

Just a quick update of all docs mentioning CSS modules with a new syntax. Ideally we should rewrite those using ES modules, so something like this: 
```js
import { container } from "./container.module.css"
```
But it is much more involved. This is just a quick fix to not confuse our users.
Originally flagged in #29931

chore(docs): update css modules docs

---

e2e-tests/development-runtime/cypress/integration/navigation/linking.js
e2e-tests/development-runtime/gatsby-node.js
e2e-tests/development-runtime/src/pages/index.js
e2e-tests/production-runtime/cypress/integration/1-production.js
e2e-tests/production-runtime/gatsby-node.js
e2e-tests/production-runtime/src/pages/index.js
packages/gatsby/package.json
yarn.lock

fix(gatsby): fix routing for paths with characters like `@` etc

---

packages/gatsby-plugin-image/src/babel-plugin-parse-static-images.ts

We were importing @babel/template without adding it as a dep. It works because this is including in the core package, so we should grab it accordingly.

fix(gatsby-plugin-image): Use template from core package

---

packages/gatsby-source-wordpress/__tests__/process-node.test.js
packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js

This PR adds a test for html field link transforms (from absolute urls to relative paths).

chore(gatsby-source-wordpress): Test html link transforms

---

packages/gatsby/src/utils/webpack.config.js

Move away from browserlist config until we have a better way to set browserlist properly in gatsby
Fixes #29943

fix(gatsby): change browserlist to web/es5

---

packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
packages/gatsby-plugin-sass/src/gatsby-node.js

Luckily for us, with v4 the `modules` option is set to `true` by default. https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#400-2020-07-25
So we can explicitly set it to `false` for the non-module rule (because it increases performance: https://github.com/webpack-contrib/css-loader#modules) and for the module rule we don't have to set it to `true` anymore.
Fixes https://github.com/gatsbyjs/gatsby/issues/29955
[ch26275]

fix(gatsby-plugin-sass): Change `modules` option around

---

packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js
packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js

Backport #29813 to 2.32 release
(cherry picked from commit 28124dd74b87902f9fa8cf3895ff8b4d54bc0fd6)

fix(gatsby-source-wordpress): image fixes (#29813)

---

e2e-tests/production-runtime/cypress/integration/resource-loading-resilience.js
e2e-tests/production-runtime/cypress/plugins/block-resources.js
packages/gatsby/cache-dir/__tests__/dev-loader.js
packages/gatsby/cache-dir/dev-loader.js
packages/gatsby/cache-dir/loader.js
packages/gatsby/cache-dir/production-app.js

Adding some better error messages in our runtime code so people can actually see what's going wrong in their error trackers.
It should help us solve https://github.com/gatsbyjs/gatsby/issues/19618
When you have a runtime error in your page component before React kicks in
```js
if (typeof window === 'undefined') {
throw new Error('GATSBY');
}
export default function MyPage(){}
```
When Static Query fails we got an unexpected JSON error, now we get:
When Page Query fails, it's still the same:
Related to https://github.com/gatsbyjs/gatsby/issues/19618

feat(gatsby): improve error messages at runtime

---

packages/gatsby-source-filesystem/README.md

This PR updates the docs to clarify that `STALL_RETRY_LIMIT`, `STALL_TIMEOUT`, and `CONNECTION_TIMEOUT` need the `GATSBY_` prefix when set as env variables. This also makes it consistent with earlier in the doc where `GATSBY_CONCURRENT_DOWNLOAD` is referenced.

docs: clarify env variable prefix in gatsby-source-filesystem docs

---

packages/gatsby-link/src/index.js
packages/gatsby-react-router-scroll/src/scroll-handler.tsx
packages/gatsby-react-router-scroll/src/use-scroll-restoration.ts
packages/gatsby/cache-dir/navigation.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/root.js
packages/gatsby/cache-dir/static-entry.js

There are cases where our webpack alias is not used (see https://github.com/gatsbyjs/gatsby/issues/29964 ) so let's adjust imports we have to package that is actually is used and not rely just on webpack alias. Alias will work fine for cases when users import it in their client-only-paths so it need to stay
Fixes #29964
[ch26417]

chore: adjust @reach/router imports to not rely just on webpack alias

---

packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.ts.snap
packages/gatsby/src/redux/__tests__/babelrc.ts
packages/gatsby/src/utils/babel-loader-helpers.js
packages/gatsby/src/utils/babel-loader.js

Before v3 `babel-preset-gatsby` was using `process.env.GATSBY_BUILD_STAGE` variable to capture current build phase (and was adjusting config accordingly).
But we've removed this for v3 [here](https://github.com/gatsbyjs/gatsby/pull/29413/files#diff-dcb4ddac648696585a5660cbb8eaeccbd5e4d87f4d256ca2b1bc347a73e8488fR35):
```diff
- // TODO(v3): Remove process.env.GATSBY_BUILD_STAGE, needs to be passed as an option
- const stage = options.stage || process.env.GATSBY_BUILD_STAGE || `test`
+ const stage = options.stage || `test`
```
I guess the idea was to always pass `stage` in babel-loader options. But we don't do this now for user-defined .babelrc.
This PR fixes it and always passes the `stage` option with `babel-preset-gatsby` even if it was set in user-defined `.babelrc`.
Without it, …

fix(gatsby): always pass `stage` option to `babel-preset-gatsby`

---

packages/gatsby-plugin-image/README.md

Fixed two broken documentation links in the Gatsby Plugin Image readme.
The first broken link can be found in this [section](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-image#restrictions-on-using-staticimage). The link was pointing towards this [relative path](https://github.com/gatsbyjs/gatsby/blob/master/docs/reference/built-in-components/gatsby-plugin-image#restrictions-on-using-staticimage) which returned a 404. The updated link in this PR now points to the [correct URL](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#restrictions-on-using-staticimage).
The second broken link can be found in this [section](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-image#dynamic-images). The link was pointing …

fix(gatsby-plugin-image): broken documentation links

---

docs/docs/reference/release-notes/image-migration-guide.md

Documentation change:
Previously this guide suggested that art direction was no longer supported.
This change adds a link to the reference docs where the new API is explained. 
As above
n/a

chore(docs): Add link to art direction docs

---

packages/gatsby-plugin-postcss/README.md

The example given in the README for the postcss plugin uses syntax from css-loader version 1. Gatsby is now using version 5 and the API for setting the camelCase option has gone through two revisions. I have amended the example to be functionally identical, while actually working with the latest version of Gatsby.
I added a bit of text describing what else needs to change for the option to be applied, as this took me some time to debug and figure out myself.
The updated usage comes straight out of css-loader's README: https://github.com/webpack-contrib/css-loader#exportlocalsconvention
I was not able to find any related issues.

chore(gatsby-plugin-postcss): Update README to show correct usage

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

Adds a section about version mismatches to the migration guide (see related issue).
Also changed webpack to correct casing (all lower case)
Fixes https://github.com/gatsbyjs/gatsby/issues/29975

chore(docs): Add version mismatch info to migration guide

---

packages/gatsby/src/utils/api-runner-node.js

Fix a broken call to `reporter.activityTimer`

fix(gatsby): Fix broken reporter call

---

package.json

V3 is out and this should be latest, but we still will be releasing patches for v2 so those stable releases should not be tagged as `latest`

chore: adjust npm release dist tag for v2

---

packages/gatsby-source-contentful/src/extend-node-type.js

When generating image data, use the source image format coming from Contentful, rather than making the plugin helper infer it from the file extention. Fixes #30069

fix(gatsby-source-contentful): Set image source format

---

packages/gatsby/src/state-machines/develop/index.ts

We are currently ignoring `SOURCE_FILE_CHANGED` event in `reloadingData` state. This seems to cause problems:
If we are in this state and we ignore that event, but 
https://github.com/gatsbyjs/gatsby/blob/a8f7101e1ff6f1b437c44d78bb9f3eafa81dc539/packages/gatsby/src/services/start-webpack-server.ts#L47-L55
will mark webpack recompilation to run but it won't (until something else potentially in the future trigger another recompilation).
This _might_ result in at least some runs getting stuck - `GATSBY_DIAGNOSTIC_STUCK_STATUS_TIMEOUT` reporting things like:
```
Activity "Building development bundle" of type "pending" is currently in state "NOT_STARTED"
```
This might also be source of at least some of double save issues

fix(gatsby): don't ignore SOURCE_FILE_CHANGED event

---

packages/gatsby/cache-dir/.eslintrc.json
packages/gatsby/cache-dir/fast-refresh-overlay/style.js

Adds darkmode support to the Fast Refresh overlay.
I also improved the focus style as until now it showed the default browser outline (in Chrome a black border), added a bit of padding to `a` (to have a larger click area if on mobile).
Both the already existing light syntax highlighting theme + now the new dark one is from https://github.com/ericwbailey/a11y-syntax-highlighting/tree/main/dist/highlight to have an accessible theme 👍 
Video of an error with the Accordion and a link:
https://user-images.githubusercontent.com/16143594/110101058-6d30fb80-7da3-11eb-9dd6-8075b3674b56.mp4
Video of an error with some proper syntax highlighting show-off:
https://user-images.githubusercontent.com/16143594/110101148-8174f880-7da3-11eb-97db-df664b0f8c80.mp4
[ch26074]

feat(gatsby): Add darkmode support to Fast Refresh overlay

---

packages/gatsby/src/commands/build.ts
packages/gatsby/src/commands/develop-process.ts

Small adjustment for https://github.com/gatsbyjs/gatsby/pull/29708#pullrequestreview-607185166
Without this change we won't log state transition changes with `VERBOSE` env var: https://github.com/gatsbyjs/gatsby/pull/29708#pullrequestreview-607185166

fix(gatsby): set program.verbose when VERBOSE env var is used

---

packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
packages/gatsby/src/schema/schema.js

The PR https://github.com/gatsbyjs/gatsby/pull/29822 introduced an issue: types derived from `SitePage` are not updated correctly because the `Query` type gets frozen too early and doesn't receive needed updates when rebuilding the schema with `SitePage`.
This PR moves type freezing to a safer stage - after the schema is updated with `SitePage` and all of it's derived types.
Fixes #30107

fix(gatsby): freeze the schema only after rebuilding with SitePage

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

Add a section that helps user troubleshoot the various integration points that may break down in configuring and using gatsby-plugin-image.
This will also serve as a place to send people when they're opening bugs so we can get a better idea of where in the flow there is data loss.

docs(gatsby-plugin-image): Add a troubleshooting section

---

packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md
packages/gatsby-source-wordpress/src/steps/preview/index.ts

To make debugging preview on Cloud a bit easier, I've added an env var to enable preview debug mode for WP (`WP_GATSBY_PREVIEW_DEBUG`).

feat(gatsby-source-wordpress): Add WP_GATSBY_PREVIEW_DEBUG env var to enable preview debug mode

---

packages/gatsby-plugin-image/src/__tests__/image-utils.ts
packages/gatsby-plugin-image/src/image-utils.ts

We are currently not passing through the placeholder URL in the image plugin toolkit, so blurred and traced SVG placeholders aren't working properly.

fix(gatsby-plugin-image): Handle placeholder in plugin toolkit

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

The current for the `process/browser` polyfill are not correct:
- they are missing the argument declaration 
- `plugins.provide` is not a constructor but a functions
- the build will crash if you set the polyfill outside of the `build-javascript` or `develop` stage
I therefore updated the documentation accordingly

chore(docs): set process polyfill correctly

---

e2e-tests/mdx/cypress/integration/html-field.js
e2e-tests/mdx/gatsby-node.js
e2e-tests/mdx/package.json
e2e-tests/mdx/src/pages/html.mdx
packages/gatsby-plugin-mdx/utils/render-html.js

`html` field in gatsby-plugin-mdx was not working due its usage of webpack and not migrating it to work with `webpack@5`:
- webpack's compilation object now release actual source from memory after emitting so `asset.source()` was just not working anymore, because it was already `SizeOnlySource` that we can only grab size stats from (ref https://webpack.js.org/blog/2020-10-10-webpack-5-release/#sizeonlysource-after-emit )
- lack of `node` externals preset resulted in various module like `stream` or `util` not being available
This changes how it currently work to straight import produced file (similar as we do in core for ssr rendering) and skip messing with compilation object to grab source and then materialize/evaluate it (and using additional webpack plugin just for that)
Fixes #29983

fix(gatsby-plugin-mdx): fix html field resolver to work with webpack@5

---

e2e-tests/mdx/cypress/integration/html-field.js
e2e-tests/mdx/gatsby-node.js
e2e-tests/mdx/package.json
e2e-tests/mdx/src/pages/html.mdx
packages/gatsby-plugin-mdx/utils/render-html.js

Backporting #30158 to the 3.0 release branch
(cherry picked from commit 0a6c6eb40409ac92d30917e00f26a0bc4c9ca9e5)
Had to fix conflicts caused by #29988

fix(gatsby-plugin-mdx): fix html field resolver to work with webpack@5 (#30158)

---

packages/gatsby/cache-dir/__tests__/ensure-resources.tsx
packages/gatsby/cache-dir/ensure-resources.js
packages/gatsby/cache-dir/loader.js

Updated the correct error message in develop so people know where to look
Before:
After:
Fixes https://github.com/gatsbyjs/gatsby/issues/30046
[ch26500]

fix(gatsyby): improve error messages for errors outside of react"

---

docs/docs/conceptual/using-gatsby-image.md

This PR fixes an outdated link to gatsby image plugin.

fix(docs): update conceptual gatsby image doc

---

docs/docs/deploying-to-digitalocean-droplet.md

Related to: `Deploying to a DigitalOcean Droplet`
https://www.gatsbyjs.com/docs/deploying-to-digitalocean-droplet/
Changed `sudo apt-get install node` to `sudo apt-get nodejs`. I couldn't install `node` as `node`, I had to install it as `nodejs`. I've seen other online tutorials also install `node` using `nodejs`.
In the deployment guide to a DigitalOcean droplet (`deploying-to-digitalocean-droplet.md`). I'm not sure where else this issue exists (if at all)
Didn't find any issues related to this.

chore(docs): Update deploying-to-digitalocean-droplet

---

packages/gatsby-plugin-netlify/src/create-redirects.js

Fixes https://github.com/gatsbyjs/gatsby/issues/29779
Currently we add all values to the redirects file for Netlify. This PR changes that behaviour to only do so for values that are known and documented in https://docs.netlify.com/routing/redirects/

fix(gatsby-plugin-netlify): Add an allow list for redirect options

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

chore(docs): Fix typo in migration guide

---

packages/gatsby/src/bootstrap/__tests__/requires-writer.js
packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts
packages/gatsby/src/utils/start-server.ts

Gather around, I will tell a story ...
`gatsby develop` react to `invalid` events coming from webpack to decide wether webpack need to recompile or not, however first compilation has some issues with virtual modules - because those are not real modules first time we start watching, `watchpack` will report all virtual modules as "deleted" ( https://github.com/webpack/watchpack/blob/f1b5e2da2d5dfd46f99b9b405c97b9d6441687d5/lib/watchpack.js#L176-L180 ). This doesn't result in `invalid` event because those only happen on `change` events ( https://github.com/webpack/webpack/blob/3f7f059d502e1e174f0c9432d927c3ec9b028241/lib/node/NodeWatchFileSystem.js#L68-L70 ). Funnily enough - deletion however do cause `aggregated` event ( https://github.com/webpack/watchpack/blob/f1b5e2da2d5dfd46f99b9b405c97b …

fix(gatsby): workaround some webpack issues causing first save after running gatsby develop to not have any effect

---

starters/gatsby-starter-wordpress-blog/README.md

https://github.com/gatsbyjs/gatsby/tree/master/starters/gatsby-starter-wordpress-blog#-quick-start
Readme file has incorrect starter name in the Quick Start section. 
Currently:
```
gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog
```
Should be:
```
gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-wordpress-blog
```
It should be corrected so that users who copy-paste from the readme file will get the correct starter.
Correct the starter blog name in the Quick Start section.
Replace:
```
gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog
```
With:
```
gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-wordpress-blog
```
---
Fixes https://github.com/gatsbyjs/gatsby/issues/30208

chore(starters): Update WordPress blog README

---

docs/docs/glossary/markdown.md

Fixes link to the "Markdown Syntax" page from the "Markdown" glossary page

chore(docs): Fix link to markdown-syntax

---

docs/docs/deploying-to-digitalocean-droplet.md

Added `sudo ufw allow 443/tcp`.
In my setup, I had to explicitly allow access on port 443 before my site could allow traffic on https. I followed the guide (including `sudo ufw allow 'Nginx HTTPS'`) but I still had to explicitly allow access on port 443.
`Update deploying-to-digitalocean-droplet.md`
Haven't found any related issues

chore(dosc): Update deploying-to-digitalocean-droplet

---

e2e-tests/development-runtime/.eslintrc
e2e-tests/development-runtime/content/error-recovery/page-query.json
e2e-tests/development-runtime/content/error-recovery/static-query.json
e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/compile-error.js
e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/page-query-result-runtime-error.js
e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/query-validation-error.js
e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/runtime-error.js
e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/static-query-result-runtime-error.js
e2e-tests/development-runtime/cypress/support/commands.js
e2e-tests/development-runtime/package.json
e2e-tests/development-runtime/src/components/image.js
e2e-tests/development-runtime/src/pages/error-handling/compile-error.js
e2e-tests/development-runtime/src/pages/error-handling/page-query-result-runtime-error.js
e2e-tests/development-runtime/src/pages/error-handling/query-validation-error.js
e2e-tests/development-runtime/src/pages/error-handling/runtime-error.js
e2e-tests/development-runtime/src/pages/error-handling/static-query-result-runtime-error.js

This adds a suite of tests for our Hot Reloading and the new Fast Refresh overlay.
It tests our three kinds of overlays we have:
- Compile errors
- Runtime errors (page query, static query, normal runtime error)
- GraphQL errors
It validates:
- Correct title (by `#gatsby-overlay-labelledby`
- Correct description (by `#gatsby-overlay-describedby`)
- Correct accordion title / file names
- After fixing the error the overlay goes away
[ch19707]
Re-Adds tests from https://github.com/gatsbyjs/gatsby/pull/27467

chore: Add Fast Refresh/Hot Reloading E2E tests

---

packages/gatsby/cache-dir/ssr-builtin-trackers/http.js
packages/gatsby/cache-dir/ssr-builtin-trackers/https.js
packages/gatsby/cache-dir/ssr-builtin-trackers/tracking-unsafe-module-wrapper.js

This PR looks to make tracking of unsafe builtins a bit more relaxed - few cases that we gathered so far:
- creatting `http(s).Agent` itself doesn't have sideeffects, so just preparing it without making request should be safe (relevant when using `algoliasearch` package as an example)
- `node-gyp-build` used to load some binaries should be safe to ignore (relevant when using `subscriptions-transport-ws` as an example)
[ch26858]

fix(gatsby): be less aggressive when marking builtin methods as unsafe

---

packages/create-gatsby/tsconfig.json
packages/gatsby-plugin-netlify/package.json
packages/gatsby-source-wordpress/tsconfig.json
yarn.lock

Some deprecation errors are showing from `gatsby build` when `gatsby-plugin-netlify` is in use, this fixes the problem by upgrading the `webpack-assets-manifest` version to the same used in the rest of gatsby codebase.
Fixes #29974

fix(gatsby-plugin-netlify): upgrade webpack-assets-manifest for compatibility with webpack@5

---

docs/docs/tutorial/part-one/index.md

👋 Hey all, with the launch of Hosting, we wanted to let users deploy on Gatsby Cloud instead of Surge during Step One of our tutorial. Edits and suggestions welcome.

chore(docs): Updated tutorial deployment step.

---

docs/docs/reference/release-notes/v3.1/index.md

Release notes for v3.1. Please add anything you would like to mention from this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-changelog-3.1/docs/docs/reference/release-notes/v3.1/index.md)

docs: release notes for v3.1

---

docs/docs/reference/release-notes/v3.1/index.md

chore: use 2 for release instead of 1

---

packages/gatsby-plugin-image/package.json
packages/gatsby-plugin-image/src/babel-helpers.ts
packages/gatsby-plugin-image/src/node-apis/image-processing.ts
packages/gatsby-plugin-image/src/node-apis/parser.ts
packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
yarn.lock

The error when props were not resolved in StaticImage was unclear, leading to a lot of confusion, e.g. in #30143 . This PR uses the babel node path to generate a structured error, with a codeframe and link to the docs

fix(gatsby-plugin-image): Better StaticImage errors

---

packages/gatsby/cache-dir/ssr-builtin-trackers/http.js
packages/gatsby/cache-dir/ssr-builtin-trackers/https.js
packages/gatsby/cache-dir/ssr-builtin-trackers/tracking-unsafe-module-wrapper.js

Backporting #30216 to the 3.1 release branch
(cherry picked from commit 331d76e41533db65d896df2c08c55b929219d124)

fix(gatsby): be less aggressive when marking builtin methods as unsafe (#30216)

---

docs/docs/how-to/images-and-media/using-gatsby-image.md
docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

Add a deprecation banner to gatsby-image doc, and remove the beta warning from gatsby-plugin-image

docs: Update beta/deprecation status of image plugins

---

docs/docs/releases-and-migration.md

We have https://www.gatsbyjs.com/docs/reference/release-notes/ now so we don't need this doc anymore.
Should be merged with mansion PR.
[ch26376]

chore(docs): Remove duplicate "releases & migration" doc

---

packages/gatsby-plugin-image/package.json
packages/gatsby-plugin-image/src/babel-helpers.ts
packages/gatsby-plugin-image/src/node-apis/image-processing.ts
packages/gatsby-plugin-image/src/node-apis/parser.ts
packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
yarn.lock

Backporting #30271 to the 3.1 release branch
(cherry picked from commit 8a0a4e82e3c782393621608a294b4b23b1e6753d)

fix(gatsby-plugin-image): Better StaticImage errors (#30271)

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

Several people have been trying to use the new image plugin for background images, and having trouble trying to use it with third party background image components. This PR adds some docs about using CSS grid to create a hero image with a background image using `StaticImage`

docs: Add background images docs

---

packages/gatsby-plugin-less/README.md
packages/gatsby-plugin-postcss/README.md
packages/gatsby-plugin-sass/README.md
packages/gatsby-plugin-stylus/README.md

Improve docs for packages that support CSS modules

chore: Update styling READMEs CSS modules info

---

packages/gatsby/src/schema/__tests__/rebuild-schema.js
packages/gatsby/src/schema/schema.js

Workaround for an edge case typical for Relay Classic-compatible schemas. It is easier to explain with an example.
For example, GitHub API fed to `gatsby-source-graphql` contains this piece:
```graphql
type Query {
github: GitHub
}
type GitHub {
relay: Query
}
```
During the initial schema building, we replace the third-party `Query` type with our own `Query` type. `graphql-compose` does that by mutating the original `GraphQLSchema` instance of the third-party schema.
**The problem:**
When we rebuild the schema our own instance of `Query` type from the previous build leaks into the new schema (via mutated third-party `GraphQLSchema` instance) and produces the dreaded error:
```
Schema must contain uniquely named types but contains multiple types named "Foo"
```
In theory, it should not …

fix(gatsby): do not fail on 3rd-party schemas with relay-classic support

---

packages/gatsby-plugin-image/src/components/__tests__/hooks.ts
packages/gatsby-plugin-image/src/components/hooks.ts

Previously we were using default breakpoints in the runtime image helper for all layouts. Thsi changes it to just fullWidth, as other layouts should default to calculating it from the output dimensions. This also adds tests for the helper.

fix(gatsby-plugin-image): Only use default breakpoints for fullwidth

---

integration-tests/images/__tests__/images.ts
packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
packages/gatsby-plugin-image/src/components/picture.tsx
packages/gatsby-plugin-image/src/gatsby-ssr.tsx

Removed in #30221 and shouldn't have been

feat(gatsby-plugin-image): data-srcset should be used to prevent overly eager loading on chrome

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

GraphCMS now supports the image plugin

docs(gatsby-plugin-image): Add GraphCMS to supported list

---

packages/gatsby/src/utils/api-node-docs.ts

The action is `createPage` and not `createPages`.
Fix a documentation typography. The action seems to be `createPage` and not `createPages`.

chore(docs): Fix typo in createPages doc

---

packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
packages/gatsby/src/query/__tests__/file-parser.js
packages/gatsby/src/query/file-parser.js

This is just DX change to not terminate dev server - this is specifically annoying when migrating as we get 1 error per `gatsby develop` and not full list when `panic`-icking on first file that doesn't import graphql.

chore(gatsby): don't terminate dev server if graphql wasn't imported from gatsby

---

packages/gatsby-source-contentful/README.md

Based on a conversation with @axe312ger, we'd like to update the description of the downloadLocal configuration to be clearer on what it does and how to use it.

chore(gatsby-source-contentful): updates to downloadLocal description

---

packages/gatsby-source-drupal/README.md
packages/gatsby-source-drupal/src/__tests__/fixtures/article-includes.json
packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi-includes.json
packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json
packages/gatsby-source-drupal/src/__tests__/fixtures/text.json
packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/normalize.js
packages/gatsby-source-drupal/src/utils.js

1) Drupal supports fetching a forward revision of content. This is typically used to fetch a draft version.
This is done via appending ?resourceVersion=rel:working-copy to the URI as a user with appropriate permissions.
2) Drupal module `paragraphs` stores the relationship between the parent content and the paragraph item using the [entity reference revisions](https://www.drupal.org/project/entity_reference_revisions) module. With paragraphs, the relationship between the entity, and the entity that it references can vary by revision. For example, a draft node, can have a draft paragraph.
3) This means that for draft content, with a paragraphs field, it is not enough to reference the relationship using ID alone
4) To allow for this, the relationship field for a paragraph includes the …

fix(drupal): Support forward revisions for Drupal paragraphs

---

packages/gatsby-remark-images/src/index.js

Fixes a unresolved promise which stalls the sourceNodes call

fix(gatsby-remark-images): fix unresolved promise

---

packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
packages/gatsby/src/schema/types/derived-types.ts

We properly clean up types when rebuilding with site page. But with new `graphql-compose` we must also explicitly cleanup input types. This PR adds missing pieces for it.
Fixes #30203

fix(gatsby): update nested input types when rebuilding SitePage

---

packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js

This passes in `pluginOptions` to the `createRemoteFileNode` call so that user defined [media item request concurrency](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#typemediaitemlocalfilerequestconcurrency) is honored. 
See: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js#L382
Fixes #29744
Addresses #30347

fix(gatsby-source-wordpress): requestConcurrency

---

docs/docs/reference/built-in-components/gatsby-plugin-image.md

The `StaticImage` component doesn't work with higher-order components like the `styled` function from styled-components or Emotion. This explains how you should use the css prop instead.

docs(gatsby-plugin-image): Warn about `styled(StaticImage)` usage

---

packages/gatsby/src/schema/resolvers.ts

Instead of using reduce and concat, use forEach and a Set. For a query on 30k items, this reduced the query time from around 10s to under 1s

perf(gatsby): Optimise `distinct` queries

---

packages/gatsby-plugin-functions/src/gatsby-node.ts

Getting errors running functions written with default exports
```
ERROR 
/Users/abhiaiyer/gatsby/gatsby-functions/src/functions/dog.ts:3
export default async (req, res) => {
^^^^^^
SyntaxError: Unexpected token 'export'
```
So moved the require to the compiled dir.

Require files from the .cache directory so user can run es/commonjs

---

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx

Forces the use of render rather than hydrate if the loading prop has changed. This fixes a bug where a browser without native lazy loading was hydrating with a different prop than the SSR'd value. Fixes #30423

fix(gatsby-plugin-image): Force render if props have changed

---

packages/gatsby/src/schema/__tests__/connection-input-fields.js
packages/gatsby/src/schema/resolvers.ts

Correctly handle arrays of dates in `distinct` queries, and add test

fix(gatsby): Handle arrays of dates in distinct

---

packages/gatsby-plugin-image/src/__tests__/image-utils.ts
packages/gatsby-plugin-image/src/image-utils.ts

When width and height are both set we weren't returning the calculated aspect ratio. This is needed in generateLowResolutionImageURL.

fix(gatsby-plugin-image): Correctly calculate aspect ratio when width and height are both set

---

packages/gatsby-plugin-mdx/gatsby/source-nodes.js

It's possible to have an mdx components without words for example we sometimes have embedded videos/ youtube.
So in this use case the `getCounts` function returns `words` property of `undefined` because the AST visitor never hits a word/paragraph. Thus the calculation for `timeToRead` (`Math.round(words / avgWPM)`) returns `NaN`. 
I propose we fallback to `0` for these properties returned in `getCounts` and then `timeToRead` can default to `1`.  
https://github.com/gatsbyjs/gatsby/issues/30490

fix(gatsby-plugin-mdx): timeToRead returns NaN when word count is undefined

---

packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/schema.js

This PR unifies the behavior for `Object` and `Interface` types when merging inherited interfaces. GraphQL 15 supports interface inheritance, so we can have the same merging logic for both `Objects` and `Interfaces`.
Discovered by @TylerBarnes . See also https://github.com/gatsbyjs/gatsby/pull/30496

fix(gatsby): merge inherited interfaces when merging types

---

README.md

Ref. https://twitter.com/natfriedman/status/1375430850620256257:
> GitHub now automatically creates a table of contents for your http://README.md files from your headers.
The main repo README has three `<h3>`s following the main (`<h1>`) headline.  
This "broken" heading hierarchy results in a slightly weird indention in the auto-generated ToC;
also we IMO don't want the three emojis nor the "Fast in every way…" in it:
This PR
* replaces the first two `<h3>`s with `<p>` — renders a bit smaller, but now these do not appear in the ToC anymore
* turns the last `<h3>` into a `<h2>`
Link to the rendered doc (unfortunately no way to preview the ToC it seems): https://github.com/gatsbyjs/gatsby/blob/f855bc55e0c18afbb8dbbd46ade9e96410226970/README.md

chore(README): Adjust heading hierarchy

---

packages/gatsby-legacy-polyfills/src/exclude.js

Enable dom iterables polyfill for nodeList.forEach and others.
You can test it with this snippet in IE11
```
import React from "react"
export default function Home() {
const myRef = React.useRef()
React.useEffect(() => {
// console.log(myRef.current)
myRef.current.querySelectorAll("li").forEach(node => {
console.log(node.innerHTML)
})
}, [])
return (
<div>
<ul ref={myRef}>
<li>hello</li>
<li>hi</li>
<li>yo</li>
</ul>
</div>
)
}
```
Fixes #30473

fix(gatsby-legacy-polyfills): add dom collections to polyfills

---

examples/using-contentful/gatsby-config.js
examples/using-contentful/gatsby-node.js
examples/using-contentful/package.json
examples/using-contentful/src/pages/image-api.js

* restructures page creation to wait for createPage
* get example running again by removing very old fragments
* rewrite the image-api subpage to use the new gatsby-plugin-image integration

fix(examples): Update using-contentful to use gatsby-plugin-image

---

packages/gatsby-source-contentful/src/__tests__/fetch-backoff.js
packages/gatsby-source-contentful/src/__tests__/fetch-network-errors.js
packages/gatsby-source-contentful/src/__tests__/fetch.js
packages/gatsby-source-contentful/src/fetch.js
packages/gatsby-source-contentful/src/plugin-options.js

* increase default pageLimit to 1000
* add backoff logic that retries with a lower pageLimit till we are able to sync data from Contentful
The first commit in here should be replaced by #30257

feat(gatsby-source-contentful): Increase Contentful sync by up to 10x

---

packages/gatsby-source-contentful/README.md
packages/gatsby-source-contentful/src/__tests__/fetch.js
packages/gatsby-source-contentful/src/fetch.js

When working with environments, we need access to master environment as well. This is due to a limitation of the Contentful JS SDK.
Additionally adjusts readme to contain all limitations/restrictions I am aware of.

feat(gatsby-source-contentful): update docs and improve errors

---

packages/gatsby-source-contentful/src/gatsby-node.js

oops forgot the JOI validation

fix(gatsby-source-contentful): Contentful page limit backoff

---

packages/gatsby-source-contentful/.npmignore

Fragments are broken in current state. This will make them available again.
--edit by @pieh
This is fixing regression introduced in https://github.com/gatsbyjs/gatsby/pull/30414 which ignored untranspiled `fragments.js` file and therefore Gatsby didn't extract and register those making old-school Contentful gatsby-image fragments broken. Issue was discovered in https://github.com/gatsbyjs/gatsby/pull/30390

fix(contentful): ensure fragments are properly distributed

---

packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/schema.js

Backporting #30501 to the 3.2 release branch
(cherry picked from commit e1f1656b36e4912c1712cada0124fc38f4b4e07e)

fix(gatsby): merge inherited interfaces when merging types (#30501)

---

packages/gatsby-plugin-mdx/gatsby/source-nodes.js

Backporting #30489 to the 3.2 release branch
(cherry picked from commit 75e234ac9116e16fbd177d24f3b98d7c14409b4e)

fix(gatsby-plugin-mdx): timeToRead returns NaN when word count is 0 (#30489)

---

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx

Backporting #30491 to the 3.2 release branch
(cherry picked from commit e584b8a33f079ba5a07419173b57bb5dabb824d7)

fix(gatsby-plugin-image): Force render if props have changed (#30491)

---

packages/gatsby/src/schema/__tests__/connection-input-fields.js
packages/gatsby/src/schema/resolvers.ts

Backporting #30460 to the 3.2 release branch
(cherry picked from commit 2f87f8934c4bf5a14d6ac5297d8f0ce37f55e223)

fix(gatsby): Handle arrays of dates in distinct (#30460)

---

docs/docs/tutorial/part-eight/index.md

Encouraging people to use service workers in Gatsby sites has caused more trouble than it's helped. We've removed/disabled it elsewhere but hadn't updated the tutorial as it turns out.

fix(tutorial): Remove gatsby-plugin-offline from the tutorial

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/gatsby-node.js
packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
packages/gatsby/src/redux/__tests__/run-fast-filters.js
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/nodes.ts
packages/gatsby/src/redux/reducers/status.ts
packages/gatsby/src/redux/types.ts

This PR fixes a bug with query filters that occurs in a very edge case. All of the following must be true in order for you to hit this bug:
1. You must have at least one source plugin that relies on `touchNode` (such as `gatsby-source-contentful`, `gatsby-source-contentstack`, etc)
2. You must use multiple filters in a single query
3. Filtered results must have an intersection
4. You must start the build/develop with the warm cache
5. The stars must converge in a certain way 
If all of the above is true - you will see this issue.
The problem is that we rely on `node.internal.counter` to perform fast intersections of filtered results here:
https://github.com/gatsbyjs/gatsby/blob/f628c3801226f5b500d74b5b41bca4caa72a9e00/packages/gatsby/src/redux/nodes.ts#L1099-L1117
And this …

fix(gatsby): fix incorrect intersection of filtered results

---

packages/gatsby-source-wordpress/src/models/develop.ts
packages/gatsby-source-wordpress/src/models/gatsby-api.ts
packages/gatsby-source-wordpress/src/models/preview.ts
packages/gatsby-source-wordpress/src/steps/preview/index.ts

PINC builds almost works with WP except that WP doesn't know to start up in preview mode. This PR fixes that.

fix(gatsby-source-wordpress): Enable preview mode in PINC builds

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

This PR makes sure that the `StaticQueryMapper` plugin isn't used by the webpack instance of `gatsby-plugin-netlify-cms`.
The Netlify CMS plugin is spinning an extra webpack instance with almost every plugin from gatsby. Reusing the `StaticQueryMapper` plugin [caused issues](https://github.com/gatsbyjs/gatsby/issues/29951) given how it's dealing with a Gatsby state. 
This PR also:
- Removes the `cssTests` variable which wasn't used anymore
- Adds a clear TODO comment for how to get `excludeAssets` to be taken into account again. A webpack plugin had been removed to make this package compatible with webpack 5, but the functionality hasn't been put back. (Edit: this means that since `gatsby-plugin-netlify-cms` was made compatible with webpack 5, all of the CSS that is imported is included …

fix(gatsby-plugin-netlify-cms): Don't use StaticQueryMapper

---

docs/docs/reference/config-files/gatsby-node.md
packages/gatsby/src/utils/api-node-docs.ts

Small edits.
It'd be nice to have a lifecycle diagram at the top for when APIs are called as it's not really clear reading through it.

fix(docs): edits to Gatsby Node APIs doc

---

docs/docs/tutorial/part-seven/index.md

Add link to next tutorial (currently, tutorial 7 is a dead end). Note: /docs/tutorial/part-eight gives a 404 error, so I have *not* used a relative link.

chore(docs): Add link to part 8 tutorial

---

e2e-tests/development-runtime/cypress/integration/functionality/babelrc.js
e2e-tests/development-runtime/package.json
e2e-tests/development-runtime/scripts/update.js
e2e-tests/development-runtime/src/pages/babelrc/add/.babelrc-fixture
e2e-tests/development-runtime/src/pages/babelrc/add/index.js
e2e-tests/development-runtime/src/pages/babelrc/base/.babelrc
e2e-tests/development-runtime/src/pages/babelrc/base/index.js
e2e-tests/development-runtime/src/pages/babelrc/edit/.babelrc
e2e-tests/development-runtime/src/pages/babelrc/edit/index.js
e2e-tests/development-runtime/src/pages/babelrc/remove/.babelrc
e2e-tests/development-runtime/src/pages/babelrc/remove/index.js
e2e-tests/production-runtime/cypress/integration/babelrc.js
e2e-tests/production-runtime/package.json
e2e-tests/production-runtime/src/pages/babelrc/base/.babelrc
e2e-tests/production-runtime/src/pages/babelrc/base/index.js

This is adding e2e test cases for `.babelrc` support. Goal of it is to make sure that https://github.com/gatsbyjs/gatsby/pull/28738 (and any changes to our babel handling in future) doesn't introduce regressions
- Add cases for develop HMR:

test(e2e): add base babelrc support tests for dev and prod

---

docs/docs/how-to/styling/tailwind-css.md

[The Tailwind install guide](https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/) seems to be missing the required module `autoprefixer` in the inital command. This is required for `npx tailwindcss init` to run in the next step. This is what you get if you init without `autoprefixer` installed:
Fixes #30537

chore(docs): include autoprefixer in tailwind install command

---

packages/gatsby-cli/src/structured-errors/error-map.ts

Saw these old links over and over again, so had to fix them 😁

fix(gatsby-cli): Update docs links in error-map

---

docs/docs/tutorial/part-eight/index.md

Fixed uppercase typo and two readability issues.

chore(docs): Update wording of tutorial part 8

---

packages/gatsby-source-wordpress/src/steps/preview/index.ts

fix(gatsby-source-wordpress): pass missing property "helpers" to gql fetch util

---

packages/gatsby-source-contentful/package.json
packages/gatsby-source-contentful/src/extend-node-type.js

fix(contentful): make gatsby-plugin-image a peer dependency

---

packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
packages/gatsby-plugin-image/src/components/hooks.ts
packages/gatsby-plugin-image/src/gatsby-node.ts
packages/gatsby-plugin-image/src/global.d.ts

The image plugin currently defines `global.GATSBY___IMAGE` to detect when the plugin is installed, which causes problems with thrid-party plugins. This changes it to just create a bare global `GATSBY___IMAGE`, and updates types to match. 
Thanks @kelvindecosta for his PR, but there were some issues in the approach there so I have opened this instead.
Fixes #30093, fixes #30094, fixes #30456, fixes #30609

fix(gatsby-plugin-image): Use bare GATSBY___IMAGE global

---

docs/docs/reference/release-notes/image-migration-guide.md

Add info on `tracedSVGOptions` to the migration guide
[ch25082]

docs(gatsby-plugin-image): Note on tracedSVG options name change

---

packages/gatsby/src/utils/babel-loader-helpers.js
packages/gatsby/src/utils/babel-loader.js
packages/gatsby/src/utils/webpack.config.js

On certain site:
Current:
```
success Building development bundle - 162.795s
success Building development bundle - 171.725s
success Building development bundle - 171.985s
success Building development bundle - 162.793s
success Building development bundle - 183.253s
```
With this change:
```
success Building development bundle - 113.453s
success Building development bundle - 110.612s
success Building development bundle - 112.168s
success Building development bundle - 112.159s
success Building development bundle - 110.889s
```
Just the `packages/gatsby/src/utils/babel-loader-helpers.js` change (biggest gain of all the caching added in this PR - at least for site I was benchmarking)
```
success Building development bundle - 118.803s
success Building development bundle - 123.173s
success …
```

perf(gatsby): cache babel config items

---

docs/docs/how-to/local-development/troubleshooting-common-errors.md

fix(docs): Add link to how to enable DEV_SSR for fixing inconsistent css styles between dev/prod

---

docs/docs/debugging-html-builds.md

Heard request on Discord for a react example

fix(docs): Copy edits for debugging html doc + add React-specific example

---

.gitignore
scripts/backport.js

Adds https://gist.github.com/pieh/1c011bb76593c29b96dd858c4021adca to our monorepo
I also added `dotenv` so that I can use a `.env` file inside `scripts`

chore: Add backport script

---

docs/docs/resource-handling-and-service-workers.md
examples/simple-auth/README.md
packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts

Just something I found while browsing our stuff and a community plugin. Changed the public occurrences of "whitelist" (we still have whitelist/blacklist in code, e.g. variable names)

chore(docs): Change "whitelist" to "allow list"

---

packages/gatsby-plugin-image/src/gatsby-ssr.tsx

Setting `all: inherit` on `img` was causing issues with props not being applied to the element. The specific bug is #30666, which is where draggable is not being applied. I'm not sure why we needed this rule in the first place, but it seems to work fine without it.

fix(gatsby-plugin-image): Allow draggable=false on images

---

packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js

Yesterday Kyle and I fixed https://github.com/gatsbyjs/gatsby/pull/30727 and we were a bit over confident and didn't try out the fix. Turns out there was an additional problem that this PR fixes.

fix(gatsby-source-wordpress): only log out duplicate nodes if we have all the data we want to log

---

packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js

Backporting #30751 to the 3.2 release branch
(cherry picked from commit 2bdd5a5865b696e0d31dd8ff3c0dde6fdd7cb181)
Fixes https://github.com/gatsbyjs/gatsby/issues/30722

fix(gatsby-source-wordpress): only log out duplicate nodes if we have all the data we want to log (#30751)

---

docs/docs/scaling-issues.md

Coming from https://github.com/gatsbyjs/gatsby/discussions/30765

chore(docs): Add link to perf implications siteContext

---

packages/gatsby/src/commands/build.ts
packages/gatsby/src/utils/worker/render-html.ts

This PR lowers peak memory consumption of gatsby builds up to 2x.
Before this PR we put massive pressure on memory and FS while running SSR in workers. This PR restricts concurrency of html-file writes as well as page-data file reads which greatly reduces this pressure.
The improvement is proportional to the number of CPU cores and the size of your page-data files and HTML. On my test site, memory consumption per SSR worker dropped from 500MB+ to ~200MB.
For a machine with 4 physical cores, it means ~1200MB reduction of peak memory.
Also, I've noticed that we create SSR worker pool twice. One worker pool was effectively used for develop and the other - for builds but they both were created for `gatsby build`.
This PR unifies the build and develop behavior - now both use the same Worker …

fix(gatsby): lower memory pressure in SSR

---

packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js

Dev server is throwing `console.warning() is not a function` and exiting when it should just log the message on the console.

fix(gatsby-source-wordpress): error when sourcing nodes, change `console.warning` to `console.warn`

---

docs/docs/tutorial/part-four/index.md

In the place where we should have used 'style' we used 'css' and it was not working for me.

fix(docs): change attribute name

---

docs/contributing/docs-contributions/docs-structure.md
docs/contributing/docs-contributions/how-to-write-a-conceptual-guide.md
docs/contributing/docs-contributions/how-to-write-a-how-to-guide.md
docs/contributing/docs-contributions/how-to-write-a-reference-guide.md

The Diátaxis documentation framework used by Gatsby is now maintained
and updated at https://diataxis.fr.

chore(docs): Update links to Diátaxis framework

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

Many/most plugins should just update their peerDependencies with no other changes.

chore(docs): Update migration guide for plugins that support both v2 & v3

---

renovate.json5

Updates `renovate.json5` to exclude breaking minor updates from minor update PRs. Should unblock #27092, #27134, #28358, #29380 once their manual override boxes are checked in #16840.

fix(renovate): add breaking minor updates to major updates list

---

packages/gatsby-core-utils/src/fetch-remote-file.ts

When downloading a remote file using `got`, in some cases the remote server won't return `Content-Length` header.  When this happens, the `total` property on the `downloadProgress` results will be `undefined`.
https://github.com/sindresorhus/got#downloadprogress
I can only assume that it may sometimes return `null` as well, since this already accounts for it?  I am also assuming that the reason the `null` check is there is to assume the download was successful even if there was no `total` reported.
I've just added the `undefined` check to the `downloadProgress` event listener as well so that it also doesn't fail the download when there is no `Content-Length` header

fix(gatsby-core-utils): fetch-remote-file download failure when missing content-length header

---

packages/gatsby-source-contentful/src/extend-node-type.js
packages/gatsby-source-contentful/src/schemes.js

Because this plugin uses `setFieldsOnGraphQLNodeType` rather than `createSchemaCustomization`, type names are not merged and deduped. This leads to [bugs like this](https://github.com/gatsbyjs/gatsby-source-shopify-experimental/issues/65). This PR is a quick fix that renames the offending types. The proper fix though is to switch to the newer API that handles types properly.

fix(gatsby-source-contentful): De-dupe type names

---

packages/gatsby/src/bootstrap/load-plugins/load.ts
packages/gatsby/src/bootstrap/load-plugins/validate.ts

This moves the plugin `rootDir` <-> `parentDir` resolution into the `resolvePlugin()` function, instead of relying on callers to set the correct `rootDir`
PR #29787 broke pnpm/yarn2 because it reused `resolvePlugin()` in order to resolve a plugin's details, but didn't respect the `parentDir` property set on the plugin objects.  By moving that path resolution inside of the function and documenting that the plugin object should be the preferred parameter, hopefully this can be avoided in the future?
Related to PR #29787

fix(gatsby): handle plugin path resolution in resolvePlugin function

---

packages/gatsby/src/utils/eslint-config.ts

Fixes the webpack error "Cannot find module 'babel-preset-gatsby'" when running in `develop` mode.
This is very likely an issue with pnpm, and so will probably be an issue with yarn2 as well.
When these babel presets/plugins are not resolved to an absolute path, babel attempts to resolve them relative to its current working directory.  `babel-preset-gatsby` does not exist as a dependency of my project, so babel is unable to find it.
This change will resolve the preset based on the location of the `eslintConfig()` function instead.
Installing `babel-preset-gatsby` in the default site project fixes the issue, because then babel is able to resolve the package.
Related to (fixes?) #30110
- I can't say for sure if the cause of that issue is the same, because it doesn't really look like any of …

fix(gatsby): "Cannot find module 'babel-preset-gatsby'" error

---

packages/gatsby/src/commands/build.ts
packages/gatsby/src/services/start-webpack-server.ts
packages/gatsby/src/utils/webpack-error-utils.ts

Fixes https://github.com/gatsbyjs/gatsby/issues/30780
Related: https://github.com/facebook/create-react-app/pull/9943
You can use a canary version of Gatsby with this fix by installing `gatsby@webpack-split-fix`

fix(gatsby): webpack warnings are no longer in object format by default

---

packages/gatsby-plugin-styled-components/README.md

As noted in https://github.com/gatsbyjs/gatsby/issues/30543#issuecomment-817204219 — the v4 release isn't mentioned.

chore(gatsby-plugin-styled-components): Remove breaking changes section

---

examples/using-contentful/package.json
examples/using-contentful/src/layouts/index.js
examples/using-contentful/src/pages/image-api.js
examples/using-contentful/src/pages/index.js
examples/using-contentful/src/templates/category.js
examples/using-contentful/src/templates/product.js

This is a follow up for #29526 which removes all left-overs from `gatsby-image`
As the output looked very unfinished, I gave the layout and output a few css updates.
The code related to gatsby-image removal is in the first commit

Refactor: using-contentful to use gatsby-plugin-image exclusively

---

starters/gatsby-starter-wordpress-blog/src/templates/Post.js

I was wondering why i hadn't alt... ;)
Thanks for this marvellous starter!
Hubert

fix(gatsby-starter-wordpress-blog): Fix altText

---

docs/docs/reference/release-notes/v3.3/index.md

There'll be small sites w/ few pages or ones w/ small page-query.json files that won't see much of a difference.

fix(release notes): Add qualifier to peak memory claim

---

packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js

For Preview, revisions of a node type can have data that updates unnecessarily
This PR fixes that. The result being that less queries are invalidated in Gatsby. For example if you have a query where you're getting the latest published post using the date field, that data should be static but each preview updates the date field on the node being previewed (because the revision has a new date). So if we prevent the fields in this PR from changing, this will be less problematic.
This makes preview for GatsbyJS.com significantly faster

fix(gatsby-source-wordpress): invalidate less queries during previews

---

docs/docs/reference/release-notes/v3.3/index.md

Release notes for v3.3. Please add anything you would like to mention from this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-3.3/docs/docs/reference/release-notes/v3.3/index.md)

docs: release notes for 3.3

---

docs/docs/reference/release-notes/v3.3/index.md

When rendered on .com notes contain incorrect `mailto:` links: https://www.gatsbyjs.com/docs/reference/release-notes/v3.3
This PR fixes it.

docs: fix invalid mailto links in 3.3 release notes

---

packages/gatsby-plugin-image/README.md

This PR updates the required gatsby version for gatsby-plugin-image to work.
Closes #30757

chore(gatsby-plugin-image): Remove version note

---

packages/gatsby/cache-dir/loading-indicator/style.js

Increase `z-index` of loading-indicator + remove unused `normal` style

fix(gatsby): z-index for loading-indicator

---

packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx

Check for root container before attempting to lazy hydrate. Fixes #29982

fix(gatsby-plugin-image): Check for root container before render

---

packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
packages/gatsby-plugin-image/src/components/hooks.ts
packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx

Apply the `objectFit` and `objectPosition` properties to the placehodler as well as the main image. Fixes #30841

fix(gatsby-plugin-image): Apply object-fit and object-position to placeholder

---

docs/docs/how-to/local-development/troubleshooting-common-errors.md

Fixed a really small typo ("Nodules" instead of "Modules")

Fix small typo

---

packages/gatsby/cache-dir/app.js

Adding `./navigation` seemingly fixes some Fast Refresh reload issues when e.g. the components below `<Root />` don't satisfy the constraints set by Fast Refresh
Fixes https://github.com/gatsbyjs/gatsby/issues/30387
[ch23105]

fix(gatsby): Better Fast Refresh handling for <Root />

---

packages/gatsby-source-graphql/README.md

Fix typo in docs.
After spending too much time figuring out why i was getting a `only absolute urls are supported` from `node-fetch` it was because of a typo in the docs. The `uri`'s fallback is set to `/graphql`.
Where is this feature or API documented?
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-graphql/README.md#performance-tuning

chore(gatsby-source-graphql): Update README url => uri

---

packages/gatsby-source-wordpress/docs/tutorials/using-wordpress-menus.md

I think it is easier for beginners to use the function, because the default value for the id key is 'id', not 'key'

Change the 'idKey' parameter's default value

---

starters/README-template.md

Follow up to https://github.com/gatsbyjs/gatsby/pull/30792
We forgot to update the template that creates the actual READMEs in the remote repos

chore: Add cloud hosting option to starter README template

---

packages/gatsby/src/utils/feedback.ts

Change the order of feedback disabled heuristics to check first if we are in CI, avoiding the getConfigStore() call in that case
Fixes #30647

fix(gatsby): change order of feedbackDisabled checks to allow CI AWS lambda build

---

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
packages/gatsby/src/query/__tests__/file-parser.js
packages/gatsby/src/query/file-parser.js

Noticed other tests are all es6 so a bit of precaution to prevent possible regressions.
This also looks like it solves at least some people's problems with static queries https://github.com/gatsbyjs/gatsby/issues/24902#issuecomment-822689489 — turns out we were never checking for commonjs requires for `useStaticQuery` in `file-parser.js` which meant that these components' queries weren't loaded correctly.

fix(gatsby): add support for useStaticQuery with commonjs/require

---

packages/gatsby/src/redux/reducers/queries.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/page-data.ts

Reverts https://github.com/gatsbyjs/gatsby/pull/29431 which was workaround needed for clearing up state due to not persisting pages across builds. https://github.com/gatsbyjs/gatsby/pull/28590 start persisting pages so this workaround is not needed anymore.
Part of series:
- https://github.com/gatsbyjs/gatsby/pull/28590
- https://github.com/gatsbyjs/gatsby/pull/28760
Addressing https://github.com/gatsbyjs/gatsby/pull/28590#issuecomment-776881321

Revert "fix: clear tracked queries when deleting stale page-data files (#29431)

---

packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
packages/gatsby/src/utils/__tests__/handle-flags.ts
packages/gatsby/src/utils/handle-flags.ts

Noticed weird CLI messages during work on https://github.com/gatsbyjs/gatsby/pull/30857 where message wouldn't be displayed correctly due https://github.com/gatsbyjs/gatsby/blob/06687500de521d8ce8710a96ec817f87430f80a0/packages/gatsby/src/utils/handle-flags.ts#L145-L155
not being satisfied and not displaying which flags are active because `lockedInFlags` would contain flags for develop which were not actually enabled.
This also make it so only applicable flags (so flags that satisfy CI condition and command condition) are listed in messages (i.e. `DEV_SSR` won't be printed for builds)

fix(gatsby): filter out not applicable flags (isCi / command) when constructing flags message

---

packages/gatsby-image/README.md

The Gatsby site doesn't support converting the `:warning:` string to a symbol, so I replaced it with the emoji character itself to fix this. This is probably a temporary workaround, as ideally the Gatsby site would parse the `:warning:` string into an emoji.

chore(docs): Updated warning icon to use emoji

---

packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
packages/gatsby/src/utils/__tests__/handle-flags.ts
packages/gatsby/src/utils/handle-flags.ts

1. Allows disabling included flags via gatsby-config (i.e. when `FAST_DEV` is enabled users couldn't disable `DEV_SSR`).
2. This also fixes some issues when printing information about other available flags. Number didn't match, sometimes information was not printed etc (noticed when I was adding tests for 1.)
Fixes #30950

fix(gatsby): honor flags disabled via config when deciding wether to add included flags

---

packages/gatsby-plugin-offline/src/gatsby-browser.js
packages/gatsby/cache-dir/production-app.js

Changed the logic in gatsby to filter falsy values from "registerServiceWorker". We check for the length on the array and not which value they return.
With filter(Boolean) we do check if all values are falsy. There is one caveat still that we need to fix in a follow up PR. The code of the service worker that should not be installed will still be present in code as Gatsby api runner is not checking that piece.

fix(gatsby,gatsby-plugin-offline): register offline plugin when not on preview

---

docs/docs/how-to/performance/resolving-out-of-memory-issues.md

Follow up for https://github.com/gatsbyjs/gatsby/pull/30989 fixing missing alt text and some styleguide things

chore(docs): Fix issues in Resolving Out-of-Memory Issues

---

packages/gatsby/cache-dir/fast-refresh-overlay/components/build-error.js
packages/gatsby/cache-dir/fast-refresh-overlay/utils.js

Try to get the correct line number from the error message in fast refresh.

fix(gatsby): try to get linenumber from compile error

---

packages/gatsby-plugin-manifest/src/gatsby-node.js
packages/gatsby-plugin-sharp/src/gatsby-worker.js
packages/gatsby/src/utils/webpack-utils.ts
packages/gatsby/src/utils/worker/pool.ts

Not every part of Gatsby is using `cpuCoreCount` and we should always do -1 to make sure the main process is left alone.

fix: use cpuCount for all parallel parts

---

packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts

There are scenarios where the filesystem route API will create pages with the same path for many pages. This would happen where a page is created based on a non-unique property of the node, which is useful for creating listing or index pages based on a field that isn;t a node type itself. e.g.
`src/pages/products/{ShopifyProduct.productType}/index.jsx` which would try to create `/products/toys/` for every product with the `"toys"` type. Currently we will create a new page with the same path for every node. This could potentially happen hundreds or thousands of times, e.g. the 30k SKU shopify site recreates each "type" page around 2000 times on each build, with similar numbers for `tags` pages.
This PR adds a `knownPagePaths` `Set` which tracks which paths have been created in that …

perf(gatsby-plugin-page-creator): De-dupe collection pages

---

packages/gatsby-plugin-sharp/src/image-data.ts
packages/gatsby-plugin-sharp/src/plugin-options.js

This PR includes two fixes to the handling of fractional image sizes.
- Fix `healOptions` to correctly round the dimensions. Fixes #31014
- Fix `generateImageData` to correctly find the default image when StaticImage passes a fractional size.

fix(gatsby-plugin-sharp): Handle fractional image sizes

---

renovate.json5

Changes `renovate.json5` to update `typescript` as its own group. minor Typescript updates introduce new compiler options that can break builds.

chore(renovate): update typescript as its own group

---

packages/gatsby/src/utils/flags.ts

If someone modifies their config for the `build-html` stage and haven't for `develop-html`, they'll probably also need to update it to modify `develop-html` stage as well https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-598599
The docs for the most common use case here (using `loader.null()` for problematic modules) was updated a while ago but people with old code can still run into this https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/debugging-html-builds.md#fixing-third-party-modules

feat(gatsby): Add note to DEV_SSR flag about custom webpack config

---

examples/using-remark/gatsby-config.js
packages/gatsby-transformer-remark/README.md
packages/gatsby-transformer-remark/package.json
packages/gatsby-transformer-remark/src/__tests__/gatsby-node.js
packages/gatsby-transformer-remark/src/extend-node-type.js
packages/gatsby-transformer-remark/src/gatsby-node.js
yarn.lock

Re-enables footnotes in gatsby-transformer-remark and removes options removed from Remark in 13.0.0.
https://github.com/fshowalter/gatsby/blob/topics/fix-footnotes-in-gatsby-transformer-remark/packages/gatsby-transformer-remark/README.md
Fixes #30964.

fix(gatsby-transformer-remark): Activate footnotes by default & remove included options with remark v13

---

packages/gatsby/src/commands/__tests__/build-utils.ts
packages/gatsby/src/commands/build-utils.ts

On Windows and MacOs if you change casing of page path it results in page being generated and then deleted. 
Consider scenario of creating `/TEST/` page and then in `onCreatePage` adjust page path to lower case which results in `/test/` page. What currently happen is that `/test/` is generated and `/TEST/` is scheduled for deletion. In case insensitive filesystems it means we will delete same files we just created.
fixes #31055

fix(gatsby): handle case of changing page path casing on case-insensitive fs

---

e2e-tests/contentful/gatsby-config.js
e2e-tests/contentful/schema.gql

This adds the schema of the Contentful e2e tests to the repo. This will allow us to review changes to the schema as we soon will introduce schema generation for Contentful. See #30855

test(e2e-contentful): add schema.sql for comparision with later updates

---

docs/docs/sourcing-from-agilitycms.md

Updating content for the [Sourcing From Agility CMS](https://www.gatsbyjs.com/docs/sourcing-from-agilitycms) documentation.
[Agility CMS and Gatsby Documentation](https://help.agilitycms.com/hc/en-us/articles/360039879872)
- `/docs/sourcing-from-agilitycms`
N/A

chore(docs): Update sourcing from agility cms

---

integration-tests/functions/package.json
integration-tests/gatsby-pipeline/gatsby-config.js
integration-tests/gatsby-pipeline/package.json
integration-tests/gatsby-pipeline/src/components/seo.js
packages/gatsby-plugin-gatsby-cloud/src/copy-functions-manifest.js
packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js

This was introduced in https://github.com/gatsbyjs/gatsby/pull/30904. When having `gatsby-plugin-gatsby-cloud` installed but not using functions then the manifest file doesn't exists and thus can't be copied.
In the first step of this PR I added `gatsby-plugin-gatsby-cloud` to an integration test without any function call and the test fails as expected: https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/62308/workflows/159728d1-333c-4f51-bba2-10ab0b0b6a7b/jobs/680283
The second commit fixed it by checking for the existence of the manifest file and the test `gatsby-pipeline` now should pass.
Fixes https://github.com/gatsbyjs/gatsby/issues/31090

fix(gatsby-plugin-gatsby-cloud): Copying manifest

---

packages/gatsby-plugin-netlify-cms/package.json
packages/gatsby/package.json
yarn.lock

Aligns `mini-css-extract-plugin` to 1.5.1
Release notes here: https://github.com/webpack-contrib/mini-css-extract-plugin/releases
No breaking behavior expected
Fixes https://github.com/gatsbyjs/gatsby/issues/31102

chore: Update `mini-css-extract-plugin` to 1.5.1

---

packages/gatsby-plugin-netlify-cms/package.json
yarn.lock

**TLDR**: having mismatching versions of `mini-css-extract-plugin` in Gatsby and the Netlify CMS plugin causes build errors.
In Gatsby v3 this was fixed by aligning the versions, but the fix was not back ported to v2.
This PR ports back the fix to a branch named `gatsby-plugin-netlify-cms_v4` which is based on the tag `gatsby-plugin-netlify-cms@4.10.0`. I believe `v4.10.0` is the last non v5 release of the plugin.
To fix the issue for Gatsby v2 users, we'll need to merge this PR and release a new version of the plugin based on the `gatsby-plugin-netlify-cms_v4` branch (probably `gatsby-plugin-netlify-cms@4.10.1`).
Fixes https://github.com/gatsbyjs/gatsby/issues/24577 for Gatsby v2 users per https://github.com/gatsbyjs/gatsby/issues/24577#issuecomment-784329598 and …

fix(plugin-netlify-cms): align mini-css-extract-plugin version

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/gatsby-config.js
integration-tests/artifacts/src/components/file-that-will-change-extension.js
integration-tests/artifacts/src/pages/extension-change.js

This is adding test case for changing imported file extension between builds that currently fails when persisting caching (which is behind feature flag) is enabled.
Discovered in https://github.com/gatsbyjs/gatsby/pull/30857#pullrequestreview-642037115 / https://github.com/gatsbyjs/gatsby/pull/30857#issuecomment-824859955
[ch29635]

test(artifacts): add case for changing file extension between builds

---

packages/gatsby/src/utils/webpack.config.js

Shuffles react aliases so webpack picks the right one when using `--profile` flag. 
Fixes https://github.com/gatsbyjs/gatsby/issues/31098

fix(gatsby): fix profiler for build

---

packages/gatsby/package.json
packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
packages/gatsby/src/bootstrap/load-plugins/index.ts
packages/gatsby/src/bootstrap/load-plugins/load.ts

Enable auto-enable gatsby-plugin-gatsby-cloud when it's installed but not configured. This allows us to automatically enable it in Gatsby Cloud

feat(gatsby): enable gatsby-plugin-gatsby-cloud by default

---

docs/docs/how-to/styling/built-in-css.md
docs/docs/how-to/styling/using-local-fonts.md
docs/docs/how-to/styling/using-web-fonts.md

Carve out the basics of styling with Gatsby into one top-level doc with links to all the many sub-pages/plugins/examples

feat(docs): Add new top-level CSS doc + plus clean up local/web font docs pages

---

docs/docs/how-to/routing/adding-markdown-pages.md

Can delete 1/4 of the tutorial with the new collection routes!

fix(docs): Update 'Adding Markdown Pages' to use Collection Routes

---

docs/docs/deploying-to-cloudflare-workers.md

- Remove references to Workers KV (key value store). This was never used/ beneficial for Gatsby deployments because it doesn't use KV. It's also free now, not $5. I suspect it was added because of [this](https://developers.cloudflare.com/workers/platform/sites/start-from-worker), but we are not using an *existing worker* to serve these files and we're not using the KV api's (`import { getAssetFromKV } from "@cloudflare/kv-asset-handler"`).
- Add step about `npm run build` because `wrangler publish` uploads local files, so it needs to be there.
- Added alternatives: Gatsby Hosting and Cloudflare Pages
Note: I was not able to build the doc site, so I cannot confirm that the markdown links (`[Gatsby Cloud Hosting](/docs/how-to/previews-deploys/hosting/deploying-to-gatsby-cloud.md)`) are …

Update Cloudflare Workers Sites deployment documentation

---

packages/gatsby-plugin-sitemap/src/__tests__/__snapshots__/gatsby-ssr.js.snap
packages/gatsby-plugin-sitemap/src/__tests__/gatsby-ssr.js
packages/gatsby-plugin-sitemap/src/gatsby-ssr.js

All this PR does is allow developers to set the `output` option on the `gatsby-sitemap-plugin` to `""` (empty string) so that the files can be written to the root of the public folder.
Some (like me) might prefer that instead of creating a subfolder to store the files, plus this mitigates a separate issue where the index file always points to the root folder instead of the specified output folder.
https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/
Fixes #31095

Allows sitemap output on root of public folder

---

packages/gatsby/src/services/initialize.ts

See discussion about preserving the file download cache. https://github.com/gatsbyjs/gatsby/discussions/28331#discussioncomment-661715
The `caches` folder was getting removed that then removed the `gatsby-source-filesystem` folder. This prevents the removal of the `caches` folder and then removes everything under it apart from the `gatsby-source-filesystem` folder.
Currently discussed on https://github.com/gatsbyjs/gatsby/discussions/28331
No related issue, just the comment in the discussion.
https://github.com/gatsbyjs/gatsby/discussions/28331#discussioncomment-661715

Don't remove gatsby-source-filesystem

---

packages/gatsby-plugin-netlify-cms/package.json
yarn.lock

There's a typo in the webpack semver, which is invalid and not resolved by yarn 2+
Fixes #30291

fix(gatsby-plugin-netlify-cms): Fix typo in semver

---

docs/docs/how-to/local-development/environment-variables.md

As it's not very clear from the doc, I thought I'd stick it at the end, but I'm obviously open for suggestions: I even saw it mentioned in an SO answer that gatsby was setting GATSBY_ACTIVE_ENV to development in dev, and production in prod, but this wasn't actually the case. It took me a while to figure out. It has to explicitly be set, otherwise it's just `undefined`.

chore(docs): GATSBY_ACTIVE_ENV is undefined by default

---

packages/gatsby/index.d.ts

This PR adds the missing generic type on `GatsbyFunctionResponse` interface in `gatsby` package.
Fixes https://github.com/gatsbyjs/gatsby/issues/31135

fix(gatsby): add generic type to GatsbyFunctionResponse

---

packages/gatsby-plugin-image/package.json

When resolving the dependencies of a project using `gatsby-plugin-image` with Yarn 2, the following warning is printed:
```
➤ YN0002: │ gatsby-plugin-image@npm:1.4.0 [558ef] doesn't provide @babel/core (p64f0e), requested by babel-plugin-remove-graphql-queries
```
This adds the peer dependency [as recommended by Yarn](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency).
Related to #20949.
You can work around this warning in your projects by adding this to your `.yarnrc.yml` in the meantime:
```
packageExtensions:
'gatsby-plugin-image@*':
peerDependenciesMeta:
'@babel/core':
optional: true
```

fix(gatsby-plugin-image): add @babel/core peer dependency

---

packages/gatsby/package.json
yarn.lock

The plugin got updated to Webpack v5 and postcss 8:
https://github.com/webpack-contrib/css-minimizer-webpack-plugin/releases
Fixes https://github.com/gatsbyjs/gatsby/issues/31108

fix(gatsby): upgrade css-minimizer-webpack-plugin to v2

---

packages/gatsby-cli/src/create-cli.ts

gatsby-recipes isn't alwasy needed so let's lazily require it.
This change dropped the number of required modules (at the end of src/services/initalize.ts) from 9552 -> 8726 (8% drop). The process time to get to that point dropped from 3s to 2.4s (20% improvement).
Investigation helped out by this handy package: https://github.com/Jaguard/time-require
Before:
After:

feat(gatsby): speedup cli startup by lazily requiring modules

---

packages/gatsby-telemetry/src/telemetry.ts

For yarn workspaces (when `process.cwd()`) is not the parent directory where `node_modules` includes `gatsby`, the current code is unable to read the installed gatsby version. This attempts to fix that. 
Remember that `main` for the `gatsby` package is `cache-dir/commonjs/gatsby-browser-entry.js` so we need to strip out three segments to be able to resolve to root
Co drafted with the wonderful @jamo

fix(gatsby-telemetry): Read installedGatsbyVersion correctly for workspaces

---

docs/docs/how-to/custom-configuration/babel.md

Currently I tried to override my projects' babel configuration. However, adding a `.babelrc` at the project root (as suggested [here](https://www.gatsbyjs.com/docs/how-to/custom-configuration/babel/#how-to-use-a-custom-babelrc-file) and at other places in the documentation) showed no effect at all as I kept on receiving babel error messages.
Turns out: Monorepo projects are better off calling this file `babel.config.json` (as explained [here](https://babeljs.io/docs/en/configuration)) which, indeed, resolves earlier errors thrown by babel compiler.
Updates babel.md

docs: Updates file name suggestion in babel.md

---

packages/gatsby-plugin-mdx/loaders/mdx-loader.js

While working on my own site I noticed a bug:
- Use `gatsby-remark-images` with `gatsby-plugin-mdx`
- use `lessBabel: true` option
- `src/pages/art/index.mdx`
- That MDX file uses an image in the same directory:
```mdx
Some text blabla
```
When running `gatsby develop` the process failed on `TypeError: getNode is not a function` on this line:
https://github.com/gatsbyjs/gatsby/blob/3bcb6e26d5a44ee0687894eb4b02dcfcf013770a/packages/gatsby-remark-images/src/index.js#L132
All the helper functions including `getNode` were `undefined`.
I don't understand why they are not all passed down anyways but for now I only added `getNode`

fix(gatsby-plugin-mdx): Img w/ lessBabel option in src/pages not working

---

e2e-tests/development-runtime/.eslintignore
e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
e2e-tests/development-runtime/src/pages/eslint-rules/limited-exports-page-templates.js
e2e-tests/development-runtime/src/pages/eslint-rules/no-anonymous-exports-page-templates-function.js
e2e-tests/development-runtime/src/pages/eslint-rules/no-anonymous-exports-page-templates.js

While looking at logs of https://github.com/gatsbyjs/gatsby/pull/31061 I was pretty annoyed by the repeated logs of ESLint. This PR only adds the invalid syntax when the test is run + it ignores two files that we don't test and can safely ignore.

test: Conditionally test ESLint rules

---

e2e-tests/contentful/src/pages/rich-text.js
packages/gatsby-source-contentful/package.json
packages/gatsby-source-contentful/src/__tests__/rich-text.js
packages/gatsby-source-contentful/src/generate-schema.js
packages/gatsby-source-contentful/src/rich-text.js
yarn.lock

This converts the Gatsby Rich Text field type structure to the same as the Contentful GraphQL API uses.
```graphql
type ContentfulRichTextRichText {
raw: String
references: [ContentfulAssetContentfulContentReferenceContentfulLocationContentfulTextUnion] @link(by: "id", from: "references___NODE")
}
union ContentfulAssetContentfulContentReferenceContentfulLocationContentfulTextUnion = ContentfulAsset | ContentfulContentReference | ContentfulLocation | ContentfulText
```
```graphql
type ContentfulNodeTypeRichText @dontInfer {
json: JSON
links: ContentfulNodeTypeRichTextLinks
}
type ContentfulNodeTypeRichTextLinks {
assets: ContentfulNodeTypeRichTextAssets
entries: ContentfulNodeTypeRichTextEntries
}
type ContentfulNodeTypeRichTextAssets {
block: [ContentfulAsset]!
hyperlink: …
```

refactor: align Rich Text field structure to Contentful GraphQL API

---

e2e-tests/contentful/src/pages/gatsby-image.js
e2e-tests/contentful/src/pages/gatsby-plugin-image.js
packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
packages/gatsby-source-contentful/src/cache-image.js
packages/gatsby-source-contentful/src/extend-node-type.js
packages/gatsby-source-contentful/src/generate-schema.js
packages/gatsby-source-contentful/src/normalize.js
packages/gatsby-transformer-sqip/src/extend-node-type.js

This simplifies the asset data structure to match Contentfuls GraphQL API schema.
https://www.contentful.com/developers/docs/references/graphql/#/reference/schema-generation/assets
```graphql
type ContentfulAsset implements ContentfulInternalReference & Node @dontInfer {
file: ContentfulAssetFile
title: String
description: String
sys: ContentfulInternalSys
}
type ContentfulAssetFile {
url: String
details: ContentfulAssetFileDetails
fileName: String
contentType: String
}
type ContentfulAssetFileDetails {
size: Int
image: ContentfulAssetFileDetailsImage
}
type ContentfulAssetFileDetailsImage {
width: Int
height: Int
}
```
```graphql
type ContentfulAsset implements ContentfulInternalReference & Node @dontInfer {
sys: ContentfulInternalSys
title: String
description: String
contentType: String …
```

refactor: flatten Contentful asset data structure to match GraphQL API schema

---

integration-tests/functions/package.json
integration-tests/functions/src/api/error-send-function-twice.js
integration-tests/functions/test-helpers.js
packages/gatsby/src/commands/serve.ts
packages/gatsby/src/internal-plugins/functions/gatsby-node.ts

We catch errors from functions and previously always then sent that to the browser. That crashes the
server when the error is "Cannot set headers after they are sent to the client" which happens
when the function does e.g. a `res.send('hi')` followed by another `res.send` e.g. an early return
that wasn't returned.

feat(gatsby): Don't send error for function errors if headers are already sent

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

I'm just updating the list of dependencies that needs to goes into this example using Apollo Client V3 where you only need to install @apollo/client graphql subscriptions-transport-ws ws.

docs: Update example to apollo-client v3

---

docs/docs/conceptual/image-plugin-architecture.md

These are technical docs describing the internals of the image plugins. Its audience is anybody working on Gatsby open source, mainly internal staff.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/docs/image-plugin-architecture/docs/docs/conceptual/image-plugin-architecture.md)
[ch29926]

docs: Add image plugin architecture doc

---

docs/docs/how-to/routing/mdx.md
docs/docs/mdx/programmatically-creating-pages.md

Updating gatsby documentation to tell the user to pass frontmatter in MDXRenderer component.
As suggested in this issue: https://github.com/gatsbyjs/gatsby/issues/21241
docs here: https://www.gatsbyjs.com/docs/mdx/programmatically-creating-pages/
@gatsbyjs/documentation please review
Fixes #21241

chore(docs): Update MDX frontmatter for programmatic pages

---

docs/docs/adding-search-with-algolia.md

Added memoization to example to avoid re-creating the Algolia search client unnecessarily, which impacts performance
In the existing example, it will recreate the Algolia search client every time the user types in the search box (as the query changes, causing the Search component to be re-rendered, which creates a new instance of the search client). This change adds memoization to the example, so that the search client is not re-created on every re-render. This is important for performance, as with the existing implementation, you would notice that every keystroke would cause two requests to be sent to Algolia, and any caching is destroyed by the fact that the client is constantly re-created. Since performance is important to Gatsby, this change to the example ensures that the search …

chore(docs): Update "Adding Search with Algolia" guide

---

packages/gatsby-plugin-image/src/node-apis/image-processing.ts

Hello 
i got general error message "Error loading image" over and over and I could not know what was causing the error,
therefore we should print the error details.
in my case the error details was "EPERM: operation not permitted, open...."
that happened because I only worked with YARN and to solve this specific problem i had to run once `npm install`.
Thank you for this wonderful plugin!

fix(gatsby-plugin-image): print error details

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
docs/docs/reference/built-in-components/gatsby-plugin-image.md
packages/gatsby-plugin-image/README.md

Added documentation for customizing `gatsby-plugin-image` default options.
You might find yourself using the same options (like `placeholder`, `formats` etc.) with most of your `GatsbyImage` and `StaticImage` instances.
You can customize the default options with `gatsby-plugin-sharp`.
The following configuration describes the options that can be customized along with their default values:
```javascript
// In gatsby-config.js
module.exports = {
plugins: [
{
resolve: `gatsby-plugin-sharp`,
options: {
defaults: {
formats: [`auto`, `webp`],
placeholder: `dominantColor`
quality: 50
breakpoints: [750, 1080, 1366, 1920]
backgroundColor: `transparent`
tracedSVGOptions: {}
blurredOptions: {}
jpgOptions: {}
pngOptions: {}
webpOptions: {}
avifOptions: {}
}
}
},
`gatsby-transformer-sharp`, …
```

docs(gatsby-plugin-image): Add docs for customizing default options

---

renovate.json5

Not all new packages where part of renovate config. I added them

chore: update renovatebot config to support more packages

---

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-plugin-offline/package.json
packages/gatsby-remark-copy-linked-files/package.json
packages/gatsby-remark-graphviz/package.json
packages/gatsby-remark-images-contentful/package.json
packages/gatsby-remark-images-contentful/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-images/package.json
packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-prismjs/package.json
packages/gatsby-remark-responsive-iframe/package.json
packages/gatsby-source-wordpress/package.json
packages/gatsby/src/bootstrap/__tests__/__snapshots__/resolve-module-exports.js.snap
yarn.lock

`cheerio v1.0.0-rc.6` introduced some slight parsing differences that have no impact on production code but cause tests to fail. Today's merger of #31163 did not account for the snapshot updates and only updated the `package.json` of `gatsby-remark-copy-linked-files`, but it deduped `cheerio` for the monorepo to `v1.0.0-rc.9` and thus broke testing. This PR updates `cheerio` in all packages to `v1.0.0-rc.9` and updates the failing snapshots.

fix(tests): update cheerio snapshots

---

packages/gatsby/src/utils/__tests__/handle-flags.ts
packages/gatsby/src/utils/handle-flags.ts

`gatsby develop` due to some `LOCKED_IN` flag was always priting other flag suggestions even tho there was no explicit flags enabled by users or flags auto opted-in (both of which would print some message). It was resulting in confusing output like:
```
info
There are 6 other flags available that you might be interested in:
- FAST_DEV · Enable all experiments aimed at improving develop server start time
- DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on full reloads during develop. Helps you detect SSR bugs
and fix them without needing to do full builds.
- PRESERVE_WEBPACK_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Use webpack's persistent caching and don't delete webpack's cache
when …
```

fix(gatsby): don't print out flag suggestions if none are enabled or opted-in

---

packages/gatsby/src/utils/flags.ts

feat(gatsby): Functions aren't GA but they're not longer EXPERIMENTAL

---

packages/gatsby/src/utils/handle-flags.ts

Was doing some user testing with @calcsam earlier and he said whenever he sees the "EXPERIMENTAL" label flash by, it feels like something is broken. Which is a good point. Red is error while yellow is warning so let's change the color.

feat(gatsby): change bgcolor of 'EXPERIMENTAL' label so it does look like an error

---

packages/gatsby/index.d.ts
packages/gatsby/package.json
tsconfig.json

Follow-up of https://github.com/gatsbyjs/gatsby/pull/30819
The error wasn't caught because of: https://github.com/gatsbyjs/gatsby/issues/31324#issuecomment-838084897
Fixes https://github.com/gatsbyjs/gatsby/issues/31324

fix(gatsby): Fixes incorrect type

---

docs/docs/how-to/adding-common-features/adding-forms.md
docs/docs/how-to/functions/getting-started.md
docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
docs/docs/reference/built-in-components/gatsby-plugin-image.md

Start the sprinkling of examples around the docs

feat(docs): Add more links to examples

---

docs/docs/tutorial/part-2/index.mdx

Just noticed the following issue in tutorial part 2.
This is just to put the missing closing ``` in place.

chore(docs): Fix missing closing ```

---

packages/gatsby-cli/src/create-cli.ts

Follow-up to https://github.com/gatsbyjs/gatsby/pull/31134
I realized that gatsby-recipes is only used in develop by Admin so put loading recipes behind a flag. A follow-up could be making starting the recipes server conditional upon visiting Admin — e.g. put accessing the API behind a proxy which starts the API when it gets a request.

feat(gatsby): Only load gatsby-recipes in develop if Admin is enabled

---

packages/gatsby-plugin-mdx/loaders/mdx-loader.js

Current code doesn't work as expected on windows as `requestPath` result in in values like `/src\\pages\\test.mdx` and apparently webpack looses backslashes along the way (?)
In any case, good old `slash` to use slashes instead fixes the issue
fixes #31392

fix(gatsby-plugin-mdx): fix gatsby develop on windows

---

docs/docs/reference/built-in-components/gatsby-plugin-image.md

Our current documentation is slightly incorrect. It was probably assumed that the `css` prop behaves the same across libraries, however that's not the case.
While Emotion generates a `React.createElement` call (https://emotion.sh/docs/css-prop#get-started), styled-components just calls `styled` function under the hood (https://styled-components.com/docs/api#css-prop) -- and that styled function is not supported.
I've also added a note about the className props in regards to libraries like e.g. linaria
Fixes https://github.com/gatsbyjs/gatsby/issues/30880

chore(docs): Correct image guide on CSS-in-JS usage

---

packages/gatsby-cli/README.md
packages/gatsby-cli/src/create-cli.ts

Hello Gatsbytes! 
The recent PR #26712 that I merged added support for using `HOST` to set the host to listen for develop. Unfortunately, the `HOST` var is often populated by default, and in those cases the develop server doesn't listen on localhost, but just on the value of the var. This PR switches it to use an env var that is Gatsby-specific, so that it doesn't happen by mistake.

fix(gatsby-cli): Switch host env to GATSBY_ prefix

---

packages/gatsby-plugin-netlify-cms/package.json
packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
yarn.lock

My changes to `friendly-errors-webpack-plugin` were merged quite a bit ago so there's no reason to use my fork anymore. However `friendly-errors-webpack-plugin` doesn't "support" webpack@5 ( https://github.com/geowarin/friendly-errors-webpack-plugin/issues/123 ) so opting to yet another fork that has webpack@5 "support" (well peerDep really, as it seems things work correctly either way)
https://github.com/gatsbyjs/gatsby/discussions/31441

fix(gatsby-plugin-netlify-cms): use friendly-errors-webpack-plugin package that satisfies webpack@5 peerDependency

---

packages/gatsby-plugin-sitemap/src/gatsby-node.js

Gatsby Cloud is using the `verbose` mode and on a large site (even with 500 pages) logging everything makes the "Raw logs" unusable

fix(gatsby-plugin-sitemap): Remove reporter.verbose calls

---

packages/gatsby-source-wordpress/docs/plugin-options.md
packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts

~~A regular expression literal generate a RegExp object at compile time. We need to allow string or object in the option schema.~~
EDIT: I decided to remove the documentation entry recommending a Regex literal, instead of the above solution.
Improvements can be made in the future.
cc @TylerBarnes
Fix #31411
Related to #31091

fix(gatsby-source-wordpress): Remove search and replace regex literal recommendation

---

docs/docs/reference/built-in-components/gatsby-plugin-image.md

The config options JSON was missing some commas

chore(docs): Fixing JSON in configuration options

---

packages/gatsby-source-drupal/src/gatsby-node.js

This fixes the bug related to filters being appended multiple times in gatsby-source-drupal. I made it so that filters are only added to the url query params if they don't exist already, since jsonapi in Drupal automatically adds them to the url after the first page of results.
Fixes #31123

Fixes a bug related to filters appended onto next links for gatsby-source-drupal.

---

packages/gatsby/src/internal-plugins/functions/gatsby-node.ts

This speeds up building Functions in the functions integration test from 2.3s to 0.65s.
Minification is much more useful for preparing JS for browsers vs. serverless functions as many browsers are running on slow devices on slow networks so we want to make JS bundles as small as possible.
Serverless functions, on the other hand, are loaded by servers over very fast networks so the extra CPU/memory costs to minify isn't worth it.

feat(gatsby): Speedup building Functions by disabling minification

---

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-plugin-offline/package.json
packages/gatsby-remark-copy-linked-files/package.json
packages/gatsby-remark-graphviz/package.json
packages/gatsby-remark-images-contentful/package.json
packages/gatsby-remark-images-contentful/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-images/package.json
packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-prismjs/package.json
packages/gatsby-remark-responsive-iframe/package.json
packages/gatsby-source-wordpress/package.json
packages/gatsby/src/bootstrap/__tests__/__snapshots__/resolve-module-exports.js.snap
yarn.lock

Backporting #31298 to the `release/3.5` branch
(cherry picked from commit e06599d9acc53442f8830b04f8fa2c749a820cc5)
Conflicts:
- packages/gatsby-plugin-offline/package.json
- packages/gatsby-remark-images/package.json
- packages/gatsby-remark-prismjs/package.json

fix(tests): update cheerio snapshots (#31298)

---

packages/gatsby-source-drupal/src/normalize.js

This fixes the issue that the filename of a Drupal file is based on the `node.uri.url` property returned by jsonapi. Because jsonapi URL encodes this parameter a file named `filename with spaces.pdf` is saved as `filename%20with%20spaces.pdf`.
The fix passes the `name` parameter to the `createRemoteFileNode` call, passing it through `decodeURIComponent` so it is saved as `filename with spaces.pdf`.
Note that my first idea was to use the `node.filename` property returned by jsonapi. The problem however is that this is not necessarily the filename on the filesystem. When a file is created in Drupal with the same name as an existing file Drupal will append an incremented number to the filename stored in the filesystem, but it will leave the filename property of the entity alone.
Using an …

fix(gatsby-source-drupal): Filenames imported from Drupal via jsonapi are saved URL encoded

---

packages/gatsby-transformer-sharp/src/customize-schema.js

Without dereferencing the symlink itself is copied which has two problems:
* It might point at the wrong location for a relative symlink.
* The next time around the copy operation will fail with an EEXIST (file already exists) error. This requires then a `gatsby clean` to be able to build again.
As this is the second time, I stumble upon an issue of this sort it Gatsby, I wonder if anything can be done to prevent the same issue from cropping up again in the future? But I don't see anything obvious or cheap solution ...
My Gatsby site has many images and committing them directly to the Git repository wouldn't be a good idea due to the file size.Instead I'm using git-annex which replaces the files with relative symbolic links.
An equivalent fix was previously done for …

fix(gatsby-transformer-sharp): Dereference symlinks when copying files

---

packages/gatsby-source-wordpress/src/models/remoteSchema.ts

@TylerBarnes  PR to add an alias for the field 'fields' when sourcing form from Wordpress using wp-graphql-ninja-forms as discussed in the slack channel.

feat(gatsby-source-wordpress): auto-alias any field named `fields` to prevent conflicts with Gatsby core

---

packages/gatsby-source-contentful/src/cache-image.js

Sets the "focus" parameter correctly to `f` instead of `crop`, also fixes dominant color for cropped images.
N/A
Fixes #30927

fix(gatsby-source-contentful): use correct name for crop parameter in query string

---

packages/gatsby/src/utils/webpack.config.js

I've spent a couple of hours trying to figure out why React Fast Refresh was not working in our Gatsby applications. The console output was correct when files were modified, but changes didn't appear for React components, just for e.g. SCSS files. 
```
[HMR] bundle rebuilding
client.js:250 [HMR] bundle rebuilt in 4637ms
process-update.js:51 [HMR] Checking for updates on the server...
process-update.js:125 [HMR] Updated modules:
process-update.js:127 [HMR]  - ../../../libs/gatsby-theme-myci/src/pages/index.js
process-update.js:132 [HMR] App is up to date.
```
The reason was that we were overriding the default JSX rule by a custom one. However, we were using a shorthand loader syntax that [Webpack supports](https://webpack.js.org/configuration/module/#ruleloader) in addition to specifying …

fix(gatsby): better detection of Babel rules for HMR when customizing the Webpack config

---

packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/src/utils/flags.ts

React is moving forward with concurrent mode. It's going to rebrand it to React concurrent features. We'll be adding early support for it.
Swapping `ReactDOM.render` to `ReactDOM.unstable_createRoot`. It should be 99% equal to regular hydrate but some behavior changes might occur.
There is no hydration callback anymore so I swapped it to `onMount`.

feat(gatsby): enable concurrent features

---

packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
packages/gatsby-plugin-gatsby-cloud/src/plugin-data.js
packages/gatsby-plugin-netlify/src/__tests__/build-headers-program.js
packages/gatsby-plugin-netlify/src/build-headers-program.js
packages/gatsby-plugin-netlify/src/plugin-data.js
packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
packages/gatsby/src/redux/reducers/components.ts
packages/gatsby/src/redux/types.ts

This helps gatsby-plugin-gatsby-cloud avoid looping over all pages to get `componentChunkName`s. This is slow plus it caused a `Maximum call stack size exceeded` error for sites with 100k+ pages.
Fixes https://github.com/gatsbyjs/gatsby/issues/31545

fix(gatsby): add componentChunkName to components list so don't need to loop over pages

---

packages/gatsby/cache-dir/fast-refresh-overlay/components/hooks.js

Catch error that caused infinite loop.
Fixes #31553

fix(gatsby): prevent infinite loop in fast-refresh-overlay

---

packages/gatsby-source-wordpress/docs/features/compatibility-api.md

chore(gatsby-source-wordpress): Fix typos

---

packages/gatsby-plugin-gatsby-cloud/package.json

The gatsby-plugin-gatsby-cloud plugin has a mix of ESM & CJS which makes it difficult for webpack to figure out if sideffects are happening. We add sideEffects false to the list so wepback can remove unnecessary code
This shows that a gatsby-plugin-bundler would be a good idea.
Fixes #31597

fix(gatsby-plugin-gatsby-cloud): fix cloud being bundled

---

packages/gatsby-source-contentful/src/fetch.js

For some reason the progress bar is messed up for me with the latest Contentful plugin (on Windows/cmder):
https://user-images.githubusercontent.com/115628/118710341-59485200-b848-11eb-9538-4d74c62394ba.mp4
So what's happening is that we don't update the total count and so current progress is always greater than the total count which messes CLI rendering of the progress.
With this PR it seems to be working correctly:
https://user-images.githubusercontent.com/115628/118710512-97de0c80-b848-11eb-9605-e18a8664fa70.mp4
Code from this PR was originally in the plugin. But it was removed in #30257. Not sure if it was intentional or not @axe312ger ? If not, then we should restore it back I guess.

fix(gatsby-source-contentful): fix progress bar

---

packages/gatsby-source-contentful/src/cache-image.js
packages/gatsby-source-contentful/src/extend-node-type.js

This will fix an issue discovered by @njbmartin at https://github.com/gatsbyjs/gatsby/pull/29268#pullrequestreview-668390019
With the reporter passed, the retry will now work on assets as well.

fix(contentful): pass reporter to retry function

---

packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts

:wave: 
It is possible to get this output from the response:
```json
{
"responsePath": "https://<xxx>/graphql",
"path": "/graphql",
"url": "https://<xxx>/graphql"
}
```
instead of
```json
{
"responsePath": "/graphql",
"path": "/graphql",
"url": "https://<xxx>/graphql"
}
```
It doesn't make sense to reject the request with the error: _GraphQL request was redirected_
as the responsePath _is_ the url.
I tried this fix to build my website, and it works fine.

feat(gatsby-source-wordpress): Fix false positive error if the URL and the responsePath are the same

---

docs/docs/how-to/performance/improving-build-performance.md

Fixed few typos in the `General best practices` section.

Fix typos in improving-build-performance.md

---

docs/docs/how-to/testing/unit-testing.md

Due to change in Jest v27.0.0, the code snippet in jest-preprocess.js will throw an error because of function, `createTransformer` being exported as `default`. 
In this PR, I have updated the docs to fix this change.
Fixes #31618

chore(docs): Update Jest instructions for v27

---

packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/schema.js

When merging abstract types Gatsby should also merge `resolveType` when it is available. Otherwise, users may see an error like this one:
Thanks to @andris-sevcenko for reporting this.

fix(gatsby): merge resolveType when merging abstract types

---

packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/content-update-interval.js

It looks like the WP data update watcher code was in some cases running multiple times. It was also running before the dev server was ready. Since data updates emit a WEBHOOK_RECEIVED event to Gatsby, this was causing problems when the dev server wasn't yet ready. We were also potentially emitting this while a WEBHOOK_RECEIVED event was already being processed. This RP fixes all of these issues.

fix(gatsby-source-wordpress): Prevent "EADDRINUSE: address already in use 127.0.0.1" error

---

docs/docs/tutorial/part-0/index.mdx
docs/docs/tutorial/part-1/index.mdx
docs/docs/tutorial/part-2/index.mdx

Adds trailing slashes to the URLs in the "Continue to Part X" links at the end of each section. This should fix the redundant URLs in Google Analytics.

fix(tutorial): add trailing slashes to 'next part' links

---

.circleci/config.yml
packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
packages/gatsby/src/redux/__tests__/index.js

We've renamed the env variable from `GATSBY_EXPERIMENTAL_STRICT_MODE` to `GATSBY_EXPERIMENTAL_LMDB_STORE` in #31371 but missed changing it in cricleci config.
This PR sets the correct variable and fixes tests that were actually failing (rather minor things)

fix(gatsby): fix tests for state persistence with lmdb

---

packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/webpack/cache-folder-resolver.ts

Add an extra resolver to route dependencies used in the .cache folder from "gatsby" package to actually route properly through PNP.
Fixes #30114 #19316
[ch32208]

fix(gatsby): fix PNP resolving from the .cache folder

---

docs/docs/conceptual/using-gatsby-image.md

Changed typo from than -> that

docs(gatsby-plugin-image): Fix minor typo

---

docs/docs/tutorial/part-2/index.mdx

Fixes a typo in one of the imports in a code example in the Tutorial.
`/docs/tutorial/part-2`

docs(tutorial): fix import typo

---

packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/src/utils/flags.ts

In latest version of react/react-dom@experimental, there is no `unstable_` prefix for `createRoot`
See https://github.com/facebook/react/pull/21488

fix(gatsby): fix signature for latest experimental version of react-dom

---

packages/gatsby/src/bootstrap/index.ts
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/services/initialize.ts
packages/gatsby/src/services/types.ts
packages/gatsby/src/state-machines/data-layer/types.ts
packages/gatsby/src/utils/start-server.ts
packages/gatsby/src/utils/worker/pool.ts
packages/gatsby/src/utils/worker/render-html.ts
packages/gatsby/src/utils/worker/types.ts
packages/gatsby/src/utils/worker/worker.d.ts

Currently our worker pool has type `any` when actually interacting with it (in `build-html.ts`), this just adds types to exposed functions

chore(gatsby): type exposed workerpool functions

---

packages/gatsby-plugin-gatsby-cloud/.babelrc
packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
packages/gatsby-plugin-gatsby-cloud/src/gatsby-browser.js

Global styles may affect the indicator when rendering in a React Portal. To solve this issue, we render the component in a Shadow DOM so no styles can interact between the users site and the Preview Indicator
- Fixed `box-sizing` style that sometimes relied on a global style
- `wrapRootElement` tests have to be skipped for now as testing-library does not play nicely with a Shadow DOM.

refactor(gatsby-plugin-gatsby-cloud): Render indicator in shadow root

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

- Fix a few typos.
- Update link for `@imgix/gatsby` package, as this was a dead link.
- Update links for Source plugins: Contentful, DatoCMS, GraphCMS and Sanity

chore(docs): Update gatsby-plugin-image typos

---

docs/docs/deploying-to-digitalocean-droplet.md

The ppa for certbot has been deprecated. This update adds the new instructions for installing Certbot with Nginx on Ubuntu. The steps described are directly from the [new page](https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx).
Haven't found any issues related to this, but I had to resolve this issue on my server. I updated the document with my process.

chore(docs): Update digitalocean certbot instructions

---

docs/docs/reference/release-notes/upgrade-gatsby-and-dependencies.md

Add a relative link for v2 to v3 guidance to the list of migration guides.

chore(docs): Add link to latest migration doc

---

packages/gatsby-remark-copy-linked-files/src/__tests__/index.js
packages/gatsby-remark-copy-linked-files/src/index.js

Remove checking whether parent node is `File` type so that even though the markdown node has different type of parent node, the plugin still can process it. Then, we just need to make sure its parent node has `dir` value to get directory path for the files.
This detail was posted at https://github.com/gatsbyjs/gatsby/discussions/31592

fix(gatsby-remark-copy-linked-files): replace checking parent node type to 'dir'

---

integration-tests/ssr/test-output.js
packages/gatsby/cache-dir/static-entry.js

This PR fixes an edge case when Gatsby adds multiple `style` tags with the same `id`. It cannot happen with default Gatsby setup but when using a plugin like [gatsby-plugin-split-css](https://github.com/staffe/gatsby-plugin-split-css/blob/master/gatsby-node.js) - webpack will generate multiple css files and we will get multiple style tags with the same id.
Originally the `id` attribute was added here: https://github.com/gatsbyjs/gatsby/pull/27432/files#diff-4cd5b620539129dfa79254b9cdae3bd9b619426b83b412d2647cfb416730d362
But it was only used in integration tests: https://github.com/gatsbyjs/gatsby/pull/27432/files#diff-e441aad1b67dcbd399b4013a3c9bf3c84033436213bdceb1ebdf92f07e5fed1dR25
So this change should be (relatively) safe. In theory, this can be breaking if someone relies on this id …

fix(gatsby): do not add global id to style tag

---

docs/docs/reference/functions/getting-started.md

Updates the links within the functions docs, now that they've moved from the How-To section to the Reference section.
`/docs/reference/functions/*`

docs(functions): update links in functions docs

---

integration-tests/ssr/__tests__/ssr.js
integration-tests/ssr/package.json
integration-tests/ssr/test-output.js

Turns out our `ssr` integration tests were not working correctly. They were not capturing errors because of the test setup. Basically, jest runs `test-output` script under the hood:
https://github.com/gatsbyjs/gatsby/blob/132d829e01b3b2ca50bfbe4533ae47b57b55a50c/integration-tests/ssr/__tests__/ssr.js#L27-L31
This script was returning code `0` but also emitted this _warning_ to the standard output:
```
(node:952) UnhandledPromiseRejectionWarning: Error: Cannot find module 'cheerio'
```
In other words, the script was failing but tests were passing. This PR handles promise rejections correctly, adds all missing dependencies, and adds some sanity checks to the test case to make sure we get the expected output.

fix(integration-tests): fix false negatives in SSR tests

---

jest.config.js
packages/gatsby/package.json
packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
packages/gatsby/src/utils/worker/__tests__/datastore.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/index.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/jest-helpers.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/wrapper-for-tests.js

Building on https://github.com/gatsbyjs/gatsby/pull/31768
This adds setup and helpers to be able to execute tests covering workerpool. This adds single test that checks if worker can get node created by different process. But main point of this PR is to setup test helpers and structure for the future.
Overview of setup:
- `createTestWorker` creates actual worker (separate process)
- `packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts` is a place to add additional helper functions so tests could interact with worker that shouldn't be available in actual production worker pool
- `itWhenLMDB` is just convience wrapper around jest's `it` to only execute tests when `LMDB_STORE` flag/env is set
[ch32034]

test(gatsby): check if worker can access node created in different process

---

packages/gatsby-cli/src/reporter/start-logger.ts
packages/gatsby/src/utils/worker/__tests__/reporter.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
packages/gatsby/src/utils/worker/pool.ts

Temporary workaround for worker crashes when reported is used in worker. For now logs are discarded (for IPC), but eventually we will need a way to properly handle logs originating in worker processes.

chore: don't crash child process when reporter is used

---

docs/docs/reference/release-notes/v3.7/index.md

Release notes for v3.7. Please add anything you would like to mention from this release.
[Rendered version](https://github.com/gatsbyjs/gatsby/blob/release-notes-3-7/docs/docs/reference/release-notes/v3.7/index.md)

docs: release notes for 3.7

---

docs/docs/reference/release-notes/v3.7/index.md

Fixes a typo in the link to lmdb-store

docs: fix broken link in the 3.7 release notes

---

packages/gatsby-telemetry/src/index.ts

fix(gatsby-telemetry): Export captureEvent via module.exports as well

---

.circleci/config.yml
renovate.json5
scripts/renovate-config-generator.js

Update renovate config to hopefully have a better merging strategy.
Run `node scripts/renovate-config-generator.js` to generate renovate.json5
1. PR Patch & minors for Dev dependencies with auto merge **enabled**
2. PR Major for Dev dependencies with auto merge **enabled**
3. PR Patch & minors for dependencies with auto merge disabled
4. Major updates are handled by [the Renovate dashboard](https://github.com/gatsbyjs/gatsby/issues/16840)
5. Dependencies with version <1.0.0 get a minor update they are marked as major
6. Dependencies with version <1.0.0 get a patch update they are marked as patch
Why enable automerge for dev deps? Tests and our build should break when an update happens. Mostly these are testing libs, helpers or babel plugins. If we're not comfortable enabling automerge, …

chore: generate renovate config

---

packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js

Collect node count and pages count in onPostBuild and send via telemetry. This logic currently is in gatsby cloud but the way we retrive this data is not memory efficient. Moving it here will allow us to be future proof as the store changes

feat(gatsby-plugin-gatsby-cloud): Add telemetry event for `GATSBY_CLOUD_METADATA`

---

integration-tests/gatsby-cli/__tests__/build.js
integration-tests/gatsby-cli/__tests__/develop.js
integration-tests/gatsby-cli/__tests__/repl.js
packages/gatsby-cli/src/reporter/prepare-stack-trace.ts
packages/gatsby/src/bootstrap/load-config-and-plugins.ts
packages/gatsby/src/bootstrap/load-plugins/load.ts
packages/gatsby/src/bootstrap/load-themes/index.js
packages/gatsby/src/services/initialize.ts
packages/gatsby/src/utils/worker/__tests__/config.ts
packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/gatsby-config.js
packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/plugins/gatsby-plugin-test/gatsby-node.js
packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/plugins/gatsby-plugin-test/package.json
packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
packages/gatsby/src/utils/worker/child/index.ts
packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
packages/gatsby/src/utils/worker/child/render-html.ts

This PR allows worker process to load `gatsby-config` and therefore also execute node APIs
[ch32027]

refactor(gatsby): load config and plugins in worker

---

docs/docs/tutorial/part-3/index.mdx

Adds missing code block to Part 3 examples
`/docs/tutorial/part-3`

docs(tutorial): add missing export to part 3 code example

---

packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js

Updates remote node fetch to use the `send` propety for timeout and adds overrides for timeouts (#31737)
When a remote node is fetched by `got` there are competing timeouts that will cause the fetch to fail, and therefore, builds to fail due to requests being queued by the socket or the hosting service (i.e., AWS). 
The plugin relies on a retry method for `got` to retry the request for specific status codes and network errors, however, `got` does not use this method for streams.
The change allows overriding of the `CONNECTION_TIMEOUT`, `STALL_TIMEOUT`, and `STALL_RETRY_LIMIT` variables using the same environment variables used by [gatsby-source-filesystem](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/).
Additionally, the change updates the timeout property used for `got` to …

fix(gatsby-source-wordpress) Use send property for timeout (#31737)

---

packages/gatsby/src/utils/eslint-config.ts

Both rules were deprecated:
- https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md
- https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/accessible-emoji.md
Fixes https://github.com/gatsbyjs/gatsby/issues/31895

fix(gatsby): Update eslint a11y config

---

packages/gatsby-source-contentful/src/extend-node-type.js

In my application, I was getting the following error logged hundreds of
times:
```
[gatsby-source-contentful] Please install gatsby-plugin-sharp
```
I had gatsby-plugin-sharp installed as a plugin though. I added logging
of the error to the log line and it turns out the error had to do with
`cacheImage` not being able to load an image and not the fact that
gatsby-plugin-sharp was not installed.
This commit moves the `require` of gatsby-plugin-sharp to it's own `try`
block and updates the error messaging of this block to have the error
when an exception is thrown.

fix(gatsby-source-contentful): improve error message when dominant color can't be generated

---

packages/gatsby-cli/README.md
packages/gatsby-codemods/README.md
packages/gatsby-design-tokens/README.md
packages/gatsby-dev-cli/README.md
packages/gatsby-plugin-gatsby-cloud/README.md

Fixed multiple grammatical issues.

chore(docs): Fix multiple grammar issues

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

This adds a few missing commas in the gatsby-plugin-image defaults section which allows for easier copy pasting.

docs: Fix missing commas in plugin-image defaults

---

packages/gatsby-source-shopify/package.json

chore(gatsby-source-shopify): remove prepublish script from package json

---

packages/gatsby-plugin-sitemap/README.md
packages/gatsby-plugin-sitemap/src/gatsby-node.js
packages/gatsby-plugin-sitemap/src/internals.js
starters/default/gatsby-config.js
starters/gatsby-starter-minimal/gatsby-config.js

Since the `resolvePages` function was before the `resolveSiteUrl` function it couldn't throw the error about missing `siteUrl`. We also didn't show GraphQL errors if there were ones that we didn't account for. So I've added logging for `errors`, too. Lastly, I've added `siteUrl` to our default and minimal starter.
I've updated the README a bit.
Fixes https://github.com/gatsbyjs/gatsby/issues/31903
[ch32958]

fix(gatsby-plugin-sitemap): Properly throw error on missing siteUrl

---

packages/gatsby-source-shopify/src/gatsby-node.ts

We added a regex check to make sure the store URL is what we expected and give better error messages for the users but forgot to allow numbers the URL. This PR adds `0-9` to the allowed characters in the store name.

fix shopify source store url check

---

docs/docs/how-to/local-development/environment-variables.md

The old version of the doc has a lot of unnecessary information and buries the lead (i.e. how to use dotenv) far down the page.
User testiing showed people struggled to understand it.

fix(docs): rewrite environment variables docs to simplify explanations and focus on the essentials

---

packages/gatsby/src/utils/worker/__tests__/queries.ts
packages/gatsby/src/utils/worker/__tests__/schema.ts
packages/gatsby/src/utils/worker/child/index.ts
packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
packages/gatsby/src/utils/worker/child/queries.ts
packages/gatsby/src/utils/worker/child/schema.ts
packages/gatsby/src/utils/worker/child/state.ts

Adds the ability for PQR workers to run static queries. Adds a `runQueries` function inside the child that accepts a `queryIds` argument. Eventually this function will be called by the pool with a chunked amount of `queryIds`.
[ch32050]

feat(gatsby): PQR worker can run static queries

---

packages/gatsby-source-contentful/src/download-contentful-assets.js

Prevents `gatsby-source-contentful` from ignoring failed asset downloads. Currently if `createRemoteFileNode` fails for any reason (most likely a network failure), the error is ignored and no `localFile` link is created. This usually causes errors later in the build when pages are being created and unexpected null references are hit.
This doesn't fix all the problems mentioned in #23123 but it does make it obvious when an asset has failed to download.
Addresses #23123

fix(gatsby-source-contentful): Don't ignore errors thrown when fetching assets

---

packages/gatsby-source-contentful/src/extend-node-type.js

With the rewrite to gatsby-plugin-image and Gatsby v3 we are more strict when calling the [Contentful Images API](https://www.contentful.com/developers/docs/references/images-api/)
Unfortunately, as we now always pass a image format. This broke gif support:
Before we called like this: `https://images.ctfassets.net/k8iqpp6u0ior/2uMYE0Za3MOF9eVrx7eyiW/ace850f7bf6cbf52e3922b5db8379b7a/gatsby-monogram-animated.gif?w=150`
Now we call like this: `https://images.ctfassets.net/k8iqpp6u0ior/2uMYE0Za3MOF9eVrx7eyiW/ace850f7bf6cbf52e3922b5db8379b7a/gatsby-monogram-animated.gif?w=150&fm=gif`
Which unfortunately fails:
```
{
"sys": {
"type": "Error",
"id": "ParameterValuesNotAllowed",
"details": {
"error": "required fm: 'gif' valid transformation: False"
}
}
}
```
*Good news:* This is a configuration …

fix(contentful): reenable support for gif images

---

packages/gatsby/src/utils/flags.ts

Sets webpack caching to 100% for all users

feat(gatsby): enable webpack caching for all

---

packages/gatsby-source-shopify/README.md
packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
packages/gatsby-source-shopify/__tests__/node-builder.ts
packages/gatsby-source-shopify/src/gatsby-node.ts
packages/gatsby-source-shopify/types/interface.d.ts

The usage of `apiKey` is no longer required, we can get rid of references of it and remove it from being required in the plugin options. This gives us more flexibility as we no longer need to obtain an api key when setting up a user's site.

feat(gatsby-source-shopify): removed apikey references/usage from shopify plugin

---

packages/gatsby-plugin-mdx/gatsby-node.js
packages/gatsby-plugin-mdx/gatsby/create-schema-customization.js

Moves sourceNodes into createSchemaCustomisation. We we're only creating types in there so I moved all of it
Fixes [ch31994]

feat(gatsby-plugin-mdx): swap sourceNodes to createSchemaCustomization

---

packages/gatsby-source-drupal/package.json
packages/gatsby-source-drupal/src/gatsby-node.js
yarn.lock

Talking to Gatsby/Drupal users — most set long max-age for the Drupal cache to
keep their edge http cache as fresh as possible as Drupal can directly purge
its edge http cache.
But this has the unfortunate side-effect with the recent http client change in
https://github.com/gatsbyjs/gatsby/pull/31514 that API calls aren't
revalidated. Meaning that a user could change some content in Drupal and not
see those updates in their Gatsby site until the Drupal cache expires in the
Gatsby cache.
We tested using etag for validation but the overhead of reading/writing to the Gatsby
cache + http revalidation made it somewhat slower than just refetching every time.
While working on this PR, I also noticed that we were missing an http2 agent which
helped speed up requests on large Drupal sites.
I also …

feat(gatsby-source-drupal): Disable caching + add http/2 agent

---

docs/docs/reference/release-notes/v2.26/index.md
docs/docs/reference/release-notes/v2.27/index.md
docs/docs/reference/release-notes/v2.28/index.md
docs/docs/reference/release-notes/v2.29/index.md
docs/docs/reference/release-notes/v2.30/index.md
docs/docs/reference/release-notes/v2.31/index.md
docs/docs/reference/release-notes/v2.32/index.md
docs/docs/reference/release-notes/v3.0/index.md
docs/docs/reference/release-notes/v3.1/index.md
docs/docs/reference/release-notes/v3.2/index.md
docs/docs/reference/release-notes/v3.3/index.md
docs/docs/reference/release-notes/v3.4/index.md
docs/docs/reference/release-notes/v3.5/index.md
docs/docs/reference/release-notes/v3.6/index.md
docs/docs/reference/release-notes/v3.7/index.md

As we always added a `# heading` to the release notes and recently added the `title` in frontmatter we currently have two `<h1>` in the doc:
I've removed the `# heading` as the same information is one line below.

chore(docs): Remove extraneous h1 headings from release notes

---

packages/gatsby-source-drupal/package.json
packages/gatsby-source-drupal/src/gatsby-node.js
yarn.lock

Backporting #32012 to the 3.8 release branch.
(cherry picked from commit 113e43e19b1086e74c55f7092e4a66b7e9fe7c95)

feat(gatsby-source-drupal): Disable caching + add http/2 agent (#32012)

---

packages/gatsby-source-shopify/src/gatsby-node.ts

We need a fallback of an empty string for the `salesChannel` otherwise it throws an error when the sales channel env variable is not present.

fix(gatsby-source-shopify): set default salesChannel to empty string

---

packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

Until we can see if https://github.com/szmarczak/http2-wrapper/issues/73 can get resolved.
Fixes https://github.com/gatsbyjs/gatsby/issues/32043

fix(gatsby-source-drupal): Comment out http2-wrapper

---

packages/gatsby-source-shopify/.babelrc
packages/gatsby-source-shopify/__tests__/fixtures.ts
packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
packages/gatsby-source-shopify/src/gatsby-node.ts
packages/gatsby-source-shopify/src/node-builder.ts
packages/gatsby-source-shopify/src/operations.ts
packages/gatsby-source-shopify/src/processors/incremental-products.ts
packages/gatsby-source-shopify/src/processors/index.ts
packages/gatsby-source-shopify/src/processors/product-variants.ts
packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
packages/gatsby-source-shopify/src/query-builders/products-query.ts

Breaking product variants into a separate operation so that presentment prices can be added.
Shopify's bulk API has a limit on the number of connections that can be requested in a single query, so in order to support presentmentPrices requested by community members, we need to pull variants out into a separate operation.
https://app.clubhouse.io/gatsbyjs/story/32892/move-product-variants-into-a-separate-operation
https://github.com/gatsbyjs/gatsby-source-shopify/issues/161

Break variants into separate operation

---

docs/docs/tutorial/part-4/index.mdx

I fixed 2 typos I found on index.mdx of the new [Gatsby v3 tutorial](https://www.gatsbyjs.com/docs/tutorial/part-4/) part 4.

docs: Fix typos in tutorial 4

---

packages/gatsby-source-shopify/package.json

Adds `keywords` to gatsby-source-shopify plugin `package.json`. Makes plugin discoverable in [plugin library ](https://www.gatsbyjs.com/plugins?=gatsby-source-shopify).

chore(gatsby-source-shopify): add keywords

---

packages/gatsby/index.d.ts

As described in #19993, we generally use `createParentChildLink` when we create a child during `onCreateNode`.
However, we don't have the child complete node returned from `createNode` nor that we need anything special, but just the `id` field from the child node. See below
https://github.com/gatsbyjs/gatsby/blob/eed610813da645356316826a4558640ecc4365b5/packages/gatsby/src/redux/actions/public.js#L1026-L1039
Therefore, I'm proposing this tiny change to fix #19993.
Fixes #19993

fix(gatsby): correct args type in createParentChildLink

---

packages/gatsby-plugin-mdx/README.md

I added a comment describing why `rehype-slug` is `require`d in this example config, which illustrates the use of rehype plugins with `gatsby-plugin-mdx`. I was referencing this example earlier today, but I missed the require line for `rehype-slug`, which caused `rehype-autolink-headings` to do nothing. Apparently, this has happened to someone else as well; see [StackOverflow](https://stackoverflow.com/questions/68138781/gatsby-plugin-mdx-with-rehype-autolink-headers-only-working-with-wrap-option).
I realize that this example config is perhaps intended to illustrate the use of rehype plugins in general, not `rehype-autolink-headers` specifically. I thought I'd put it out here though, and let you all decide :slightly_smiling_face:

chore(gatsby-plugin-mdx): Add comment why rehype-slug is required

---

packages/gatsby-source-drupal/src/gatsby-node.js

Messed this up during my refactor in https://github.com/gatsbyjs/gatsby/pull/32012
Fixes https://github.com/gatsbyjs/gatsby/issues/32119

fix(gatsby-source-drupal): getNext no longer returns a value

---

packages/gatsby/src/utils/webpack-utils.ts

Fix SVGs in CSS files by implementing solution described by @nakedible-p [in the issue descussion](https://github.com/gatsbyjs/gatsby/issues/31878#issuecomment-860039495).
This is a small code fix, I don't think we need to update any documentation.
Fixes #31878
Fixes #31876
Fixes #32058
Related to #31620

fix(gatsby): leave `xmlns` element when optimizing SVGs

---

docs/docs/tutorial/part-0/index.mdx
docs/docs/tutorial/part-1/index.mdx
docs/docs/tutorial/part-2/index.mdx
docs/docs/tutorial/part-3/index.mdx
docs/docs/tutorial/part-4/index.mdx

Since the Tutorial is part of the gatsbyjs.com domain, we shouldn't use UTM parameters for internal links. This removes the URL parameters from pages in the Tutorial.
Reported internally

chore(docs) remove UTM parameter from Tutorial links

---

packages/gatsby/src/bootstrap/__tests__/__snapshots__/remove-stale-jobs.ts.snap
packages/gatsby/src/bootstrap/__tests__/remove-stale-jobs.ts
packages/gatsby/src/bootstrap/remove-stale-jobs.ts
packages/gatsby/src/redux/__tests__/__snapshots__/jobsv2.js.snap
packages/gatsby/src/redux/actions/internal.ts
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/index.ts
packages/gatsby/src/redux/reducers/jobsv2.ts
packages/gatsby/src/redux/types.ts

Just some busy work extracted to separate PR preparing refactor so that we can easily create/execute jobs created in PQR workers (by messaging `internalJob` objects which are serializable as opposed to job + plugin which might not be serializable due to plugin options)

refactor(jobs): make it possible to start running job from internalJob

---

packages/gatsby-plugin-netlify-cms/package.json
packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
yarn.lock

During the migration from Gatsby v2 to v3, `html-webpack-exclude-assets-plugin` was commented out since it doesn't support webpack 5.
This PR uses `html-webpack-skip-assets-plugin` to restore the same functionality as before.
Without this fix `cms.css` is added to the CMS `index.html`, thus styles are applied globally (to the CMS itself).
With the fix styles are only applied to the CMS preview pane via https://github.com/gatsbyjs/gatsby/blob/44257b636fe0cc4d4294673f9cb76f26b72f91b5/packages/gatsby-plugin-netlify-cms/src/cms.js#L25
Fixes https://github.com/gatsbyjs/gatsby/issues/31909

fix(plugin-netlify-cms): exclude cms.css from index.html

---

packages/gatsby-source-contentful/src/extend-node-type.js

If I did not overlook something here, we did not format our base64 previews to JPEG when resizing them. That would lead to bigger embedded images / html payload as needed.
This enforces JPG for all base64 previews

fix(gatsby-source-contentful): force base64 previews to be formatted as JPEG

---

benchmarks/query-filters-sort/gatsby-node.js
benchmarks/query-filters-sort/src/templates/elemMatch-eq.js
benchmarks/query-filters-sort/src/templates/eq.js
benchmarks/query-filters-sort/src/templates/gt-lt.js
benchmarks/query-filters-sort/src/templates/gt.js
benchmarks/query-filters-sort/src/templates/in.js
benchmarks/query-filters-sort/src/templates/lt.js
benchmarks/query-filters-sort/src/templates/ne.js
benchmarks/query-filters-sort/src/templates/nin.js
benchmarks/query-filters-sort/src/templates/regex.js

There were several issues with `query-filters-sort` benchmark:
1. It was fetching only 5 items - switched to 100 for more realistic results
2. Disabled schema inference as it is unrelated to what this benchmark is measuring but takes time
3. Switched to random text because apparently, v8 is smart enough to deduplicate huge chunks of identical text, so the previous approach for `TEXT` parameter was useless
Plus did some cleanup there

chore: update query-filters-sort benchmark

---

packages/gatsby/src/datastore/__tests__/run-fast-filters.js
packages/gatsby/src/datastore/in-memory/run-fast-filters.ts
packages/gatsby/src/datastore/types.ts
packages/gatsby/src/schema/__tests__/pagination.js
packages/gatsby/src/schema/__tests__/run-query.js
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/resolvers.ts
packages/gatsby/src/schema/type-definitions.ts

This is a refactoring PR in preparation to querying LMDB directly (using secondary indexes). It affects pagination, nodeModel and fast filters methods.
Currently our pagination needs full result after `filter + sort` operation to do the work. Basically if the result contains `100,000` items and we only need `20`, pagination expects an array of all `100,000` items.
It is not a problem at all for in-memory store but when working with any database you don't want to fetch `100,000` items to discard `99,980` of them in pagination.
Essentially, we need to change the way our current pagination works to support sliced subset of data returned from datastore. All changes below are needed to make it happen:
1. Now `limit` and `offset` are applied in datastore itself (not pagination resolver)
2. …

refactor(gatsby): refactor pagination in preparation to querying lmdb directly

---

packages/gatsby-plugin-netlify-cms/package.json
yarn.lock

Bump webpack version of gatsby-plugin-netlify-cms to match the webpack version of the main gatsby package. (5.35.0)
* Fixes potential webpack version conflicts.
N/A
N/A

chore(netlify-cms): Bump webpack version to match gatsby

---

.circleci/config.yml

Should fix our failing `starters_publish` and nightly-react scripts

chore: Install python in various CircleCI job to get them running

---

e2e-tests/development-runtime/cypress/integration/hot-reloading/new-file.js
e2e-tests/development-runtime/src/pages/index.js
packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/dev-loader.js

This PR fixes a bug where a newly created page cannot be visited via client-side navigation because of stale `async-requires` in dev loader. It is reproducible with this tutorial step: https://www.gatsbyjs.com/docs/tutorial/part-4/#task-create-a-new-blog-page
The new test in this PR demonstrates the failing scenario.

fix(gatsby): update async requires in dev loader

---

packages/gatsby/src/datastore/__tests__/run-fast-filters.js
packages/gatsby/src/datastore/common/__tests__/iterable.ts
packages/gatsby/src/datastore/common/iterable.ts
packages/gatsby/src/datastore/common/query.ts
packages/gatsby/src/datastore/in-memory/in-memory-datastore.ts
packages/gatsby/src/datastore/in-memory/indexing.ts
packages/gatsby/src/datastore/in-memory/run-fast-filters.ts
packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
packages/gatsby/src/datastore/types.ts
packages/gatsby/src/schema/__tests__/run-query.js
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/resolvers.ts

This PR mostly affects various utilities related to querying:
1. Extract some tools from fast-filters that could be re-used by `lmdb` `runQuery` implementation.
2. Add convenience tools for query running as well as various convenience methods to `GatsbyIterable` 
3. Switch to `GatsbyIterable` for `runQuery` and various node iteration methods
There are several minor behavior changes, I'll comment on them inline.

refactor(gatsby): use GatsbyIterable + extract common tools for querying

---

packages/gatsby-source-drupal/src/gatsby-node.js

This PR fixes issues with webhook deletes triggers by the Gatsby Drupal module. Namely this fixes two issues:
1. After multilingual support was added to gatsby-source-drupal, deletes triggered by a Drupal webhook were not correctly getting the nodeId causing the node not be deleted correctly.
2. Bulk deletes were not being triggered correctly by Drupal webhooks. The source plugin now handles multiple deletes when the data is an array containing information for multiple Drupal entities
Note: Since deletes were not working this is not really a breaking change, however, users will need to upgrade gatsby-source-drupal and their Gatsby Drupal module for this to work correctly.

fix(gatsby-source-drupal): Fix Drupal webhook delete issues

---

packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/schema.js

In some cases, interface types are created first as placeholders (due to some discrepancies in `graphql-compose`):
https://github.com/gatsbyjs/gatsby/blob/e5574c848f8bafa6675af74e9c216650d39245b9/packages/gatsby/src/schema/schema.js#L640-L652
In this case, they don't have any `resolveType` implementation. We later do override those placeholders with actual interface types and merge their `resolveType` methods (see https://github.com/gatsbyjs/gatsby/pull/31710).
But there is another edge case when the custom interface type doesn't provide `resolveType` implementation assuming it will get a default one. But with this code path where the placeholder is created first, the final interface never receives the default `resolveType` implementation.
This PR effectively adds this default …

fix(gatsby): add fallback for resolveType

---

.eslintignore
.prettierignore
packages/gatsby-worker/README.md
packages/gatsby-worker/src/__tests__/fixtures/test-child.ts
packages/gatsby-worker/src/__tests__/integration.ts
packages/gatsby-worker/src/child.ts
packages/gatsby-worker/src/index.ts
packages/gatsby-worker/src/types.ts

This adds messaging API to `gatsby-worker` so that parent can message workers (and vice-versa) at any time. This will be needed for PQR workers to "forward" some things to main process (for example jobs handling should be managed by main process, so that deduping and in-flight jobs are handled when same job would originate from different workers)
TODO:
[ch33225]

feat(gatsby-worker): add messaging api

---

.circleci/config.yml
renovate.json5
scripts/renovate-config-generator.js

Added better error message to renovate check.
I've also fixed a bug where we include monorepo preminors in the list which we shouldn't as renovate is not updating them anyway

chore: renovate - don't include monorepo packages in preMinors

---

docs/docs/query-filters.md

The posts containing Alex as an author are ids 1 and 4. You write the ids are 1 and 3.
gatsby/docs/docs/query-filters.md

Wrong post ids in example author name filter

---

packages/gatsby/package.json
yarn.lock

Fixes an npm audit warning too.

chore(gatsby): Update PostCSS to 8.3.5 and unfix the version

---

renovate.json5
scripts/renovate-config-generator.js

Ignore gatsby-interface to see if gatsby-interface is the problem or not.
More info at https://github.com/renovatebot/renovate/discussions/10386

chore: ignore gatsby-interface to test renovate

---

docs/docs/how-to/testing/visual-testing-with-storybook.md

- Updated Storybook v6 section as per this [guide](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324) to use Webpack v5 version
- Since [Webpack v5 bundler experimental support](https://storybook.js.org/blog/storybook-for-webpack-5/) will work without much fuss in the upcoming v6.3.0 (currently in beta), this guide may require slight modification in the coming days

chore(docs): Update Storybook guide to v6

---

renovate.json5
scripts/renovate-config-generator.js

There are many @babel packages waiting in the [renovate dashboard issue](https://github.com/gatsbyjs/gatsby/issues/16840).
It shouldn't be the case as we have a global monorepo package, that might be ignored for some reason. I'll open an issue to get more information but for now this should do the trick

chore: disable babel packages upgrades per package

---

packages/gatsby/package.json
packages/gatsby/scripts/check-declaration.js
packages/gatsby/src/utils/node-manifest.ts

Importing type like that was messing `.d.ts` file generation - see https://unpkg.com/browse/gatsby@3.7.0/dist/, there are no `.d.ts` files in root, but there are in `gatsby` and `gatsby-cli` dirs.

fix: don't import from other package src (even just types)

---

packages/gatsby-source-shopify/src/create-schema-customization.ts

We are relying on the schema to be inferred, so if the user doesn't have any nodes with a `tag` then an error will be thrown during querying for `ShopifyProduct` as `ShopifyProduct` wouldn't have the `tags` field.
To handle this we define optional `tags` in the schema customization function.

fix(gatsby-source-shopify): add tags to schema

---

packages/gatsby-source-wordpress/src/steps/preview/index.ts
packages/gatsby-source-wordpress/src/steps/source-nodes/index.ts

This check helps users who have misconfigured their Gatsby site and are trying to preview from a different WP instance than the one the Gatsby site is sourcing data from.
This check always existed but stopped working after a large preview scalability refactor. The check was running too late (after we made the request with incorrect credentials to pull pending previews) so it was never being hit. I moved it to be the first check in preview logic so it works again.
related: https://github.com/gatsbyjs/wp-gatsby/pull/176

fix(gatsby-source-wordpress): Move the remote url !== options url check earlier in previews

---

benchmarks/query-filters-sort/README.md
benchmarks/query-filters-sort/gatsby-node.js
benchmarks/query-filters-sort/src/templates/elemMatch-eq.js
benchmarks/query-filters-sort/src/templates/eq-id.js
benchmarks/query-filters-sort/src/templates/eq-two-fields.js
benchmarks/query-filters-sort/src/templates/eq-uniq.js
benchmarks/query-filters-sort/src/templates/eq.js
benchmarks/query-filters-sort/src/templates/gt-lt.js
benchmarks/query-filters-sort/src/templates/gt.js
benchmarks/query-filters-sort/src/templates/in.js
benchmarks/query-filters-sort/src/templates/lt.js
benchmarks/query-filters-sort/src/templates/ne.js
benchmarks/query-filters-sort/src/templates/regex.js

Update `query-filter-sort` benchmark site. 
1. Add new `FILTER` values:
- `eq-id`
- `eq-uniq`
- `eq-two-fields`
2. Add new modifier `COUNT` that includes `totalCount` in graphql query.
3. Add ability to set custom sort order with `SORT=foo,bar`
4. Updated docs
Update all other filters to capture a consistent amount of nodes - O(N) where possible.

chore: add more scenarios to query-filter-sort benchmark

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

Fixes a missing `)` on [Creating a Source Plugin page](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/creating-a-source-plugin/)

fix: added missing parentheses in creating a source plugin tutorial

---

packages/gatsby-telemetry/src/telemetry.ts

We write machineId to disk every time we try to request it, even if it's already there.
On windows I get
```
Error: EPERM: operation not permitted, rename '<HOME>.config\gatsby\config.json.2888574204' -> '<HOME>.config\gatsby\config.json'
at Object.renameSync (fs.js:772:3)
at Function.writeFileSync [as sync] (<ROOTDIR>gatsby\tmp\gatsby-tmp-ssr\node_modules\write-file-atomic\index.js:244:8)
at Configstore.set all [as all] (<ROOTDIR>gatsby\tmp\gatsby-tmp-ssr\node_modules\configstore\index.js:61:20)
at Configstore.set (<ROOTDIR>gatsby\tmp\gatsby-tmp-ssr\node_modules\configstore\index.js:91:12)
at EventStorage.updateConfig (<ROOTDIR>gatsby\tmp\gatsby-tmp-ssr\node_modules\gatsby-telemetry\lib\event-storage.js:124:24)
at AnalyticsTracker.getMachineId …
```

fix(gatsby-telemetry): reduce save to config

---

docs/docs/how-to/adding-common-features/adding-forms.md
docs/docs/how-to/adding-common-features/creating-a-form-in-react.md

- Adding key concepts like data validation, sending data to a third party service or using a third-party widget and explaining how they are achieved with Gatsby
- Explaining when vanilla React forms are probably fine and when you should turn to eg Formik
- Better referencing the React docs which have a very good, slightly less dated toy example

feat(docs): rewrite adding forms documentation

---

packages/gatsby/src/redux/index.ts

https://github.com/gatsbyjs/gatsby/pull/31152/files#diff-6ee77de28b1beb0ecf3d06711bb988175b0164e52bdc4f43f10dcb6b91c40d52L81-R84
Did set return type that doesn't allow for thunks breaking type checks elsewhere. This PR just adds thunks type support back

chore: allow thunks to be dispatched

---

packages/gatsby/src/services/initialize.ts

When the main process and workers communicate they save parts of their redux state to .cache/worker. We should clean this directory to remove stale files that a worker might accidentally reuse then.
[ch33143]

fix(gatsby): Delete `.cache/worker` before each run

---

.circleci/config.yml
packages/gatsby/package.json
packages/gatsby/src/datastore/common/query.ts
packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
packages/gatsby/src/datastore/lmdb/query/README.md
packages/gatsby/src/datastore/lmdb/query/__tests__/filter-using-index.ts
packages/gatsby/src/datastore/lmdb/query/__tests__/suggest-index.ts
packages/gatsby/src/datastore/lmdb/query/common.ts
packages/gatsby/src/datastore/lmdb/query/create-index.ts
packages/gatsby/src/datastore/lmdb/query/filter-using-index.ts
packages/gatsby/src/datastore/lmdb/query/run-query.ts
packages/gatsby/src/datastore/lmdb/query/suggest-index.ts
packages/gatsby/src/datastore/types.ts
packages/gatsby/src/query/__tests__/data-tracking.js
packages/gatsby/src/schema/__tests__/connection-filter-on-linked-nodes.js
packages/gatsby/src/schema/__tests__/kitchen-sink.js
packages/gatsby/src/schema/__tests__/run-query.js
packages/gatsby/src/schema/extensions/__tests__/interfaces.js
yarn.lock

This PR introduces secondary indexes for LMDB data storage. Implementation details are available in the README.md inside this PR (see [rendered version](https://github.com/gatsbyjs/gatsby/blob/vladar/lmdb-secondary-indexes/packages/gatsby/src/datastore/lmdb/query/README.md)).
This PR is a part of the parallel query running initiative.
Some (incomplete) benchmarks are published here: https://github.com/DoctorEvidence/lmdb-store/discussions/68#discussioncomment-963542
[ch33144]
[ch32057]
[ch33037]

feat(gatsby): experimental secondary indexes in lmdb

---

packages/gatsby/src/bootstrap/load-plugins/index.ts
packages/gatsby/src/services/initialize.ts
packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts

We were running `unstable_onPluginInit` before `.cache` is initialized resulting in plugins implementing it having faulty cache. This was very similar to https://github.com/gatsbyjs/gatsby/pull/26810 , but in this case we rather want cache already initialized before calling `onPluginInit`. 
Closes https://github.com/gatsbyjs/gatsby/issues/32288

fix(gatsby): delay 'unstable_onPluginInit' lifecycle to after cache is initialized

---

docs/docs/reference/functions/getting-started.md
docs/docs/reference/gatsby-project-structure.md
docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

`src/api` is a reserved directory now and some people were tripped up by this.
Fixes https://github.com/gatsbyjs/gatsby/issues/32186

chore(docs): Mention Functions in v3 migration guide

---

packages/gatsby/cache-dir/navigation.js

On the navigate function, when Gatbsy detects service worker has been updated, forces a hard reload stripping query params from the url
Fixes #25889

fix(gatsby): Pass search/hash to location after swUpdated

---

packages/gatsby/src/commands/develop.ts

Ref https://github.com/gatsbyjs/gatsby/issues/28011
Avoid the [`UNHANDLED REJECTION write EPIPE` error when using <kbd>ctrl</kbd>-<kbd>c</kbd>](https://github.com/gatsbyjs/gatsby/issues/28011)
Fix, no docs
Closes #28011

Avoid UNHANDLED REJECTION error on ctrl-C

---

packages/gatsby/src/commands/build-html.ts

Currently when a page build fails, we only log the node error stack. Sometimes this error stack is opaque as to what is happening, so we are adding more logs to hopefully give more context on opaque errors.
- adding logging for `page-data.json` of the page that failed

feat(gatsby): add page data for failed page to logs

---

e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
e2e-tests/development-runtime/gatsby-node.js
e2e-tests/development-runtime/src/pages/index.js
e2e-tests/development-runtime/src/pages/redirect-search-hash.js
packages/gatsby/cache-dir/navigation.js

So the use case is:
```js
createRedirect({
fromPath: `/from-path`,
toPath: `/to-path`,
isPermanent: true,
redirectInBrowser: true,
})
```
And then the `from-path` might have some query parameters or anchors or both. And they should be forwarded to the `to-path`, e.g.
- `/from-path#anchor` => `/to-path#anchor`
Before this PR the `#anchor` was stripped from the toPath.
Implements https://github.com/gatsbyjs/gatsby/discussions/27582
Fixes https://github.com/newrelic/docs-website/issues/2139
[ch31143]

feat(gatsby): Redirect passes search & hash parameter to final URL

---

packages/gatsby-source-wordpress/src/gatsby-node.ts

This is an additional fix needed for #32303. It seems simple sites were fine with just #32303 for some reason but more complex sites require this PR as well.

fix(gatsby-source-wordpress): run setGatsbyApiToState in onPreInit to delete auth options

---

packages/gatsby/src/schema/index.js
packages/gatsby/src/schema/schema.js
packages/gatsby/src/utils/worker/child/schema.ts

We've implemented a workaround for one `graphql-compose` issue in https://github.com/gatsbyjs/gatsby/pull/29822
But it is not applied in the workers' code path. This PR effectively enables the fix from #29822 for workers.
[ch34307]

fix(gatsby): freeze the schema in workers

---

benchmarks/query-filters-sort/gatsby-config.js
benchmarks/query-filters-sort/package.json
packages/gatsby/src/utils/worker/child/queries.ts

Previously, every worker and its `runQueries` call initiated a `new GraphQLRunner()` call which was quite expensive time and memory wise. The problem with that is that it basically resets all fast filters cache on each chunk. It means in turn that we need to re-visit all nodes of a type on each chunk which could be pretty slow on big datasets.
So with this change it's not created every time 😆 
In some tests (although not super representative as memory inside WSL2 is a bit weird and other stuff was running) this yielded these results:
With `GATSBY_CPU_COUNT=7 NUM_NODES=150000 NUM_PAGES=10000 FILTER=eq-uniq yarn bench --verbose`:
Before: ~10GB RAM and 14s with 696 queries/s
After: ~2.5GB RAM and 3s with 3200 queries/s
[ch34193]

fix(gatsby): Use shared gql runner in PQR workers

---

docs/tutorial/building-a-theme.md

Changed 'Styled' to 'Themed' - as of Theme UI 0.6, Styled components dict was renamed to Themed to avoid confusion with styled components constructor function from @emotion/styled.

chore(docs): Update building-a-theme to latest Theme UI

---

packages/gatsby/src/services/run-page-queries.ts
packages/gatsby/src/services/run-static-queries.ts

This hides the `run page queries` and `run static queries` for PQR workers as otherwise the overview will be flooded with this and it can clog up the process itself. It only shows the `run queries in workers` now.
There will be a follow-up to this (see clubhouse story) that is less hacky.
[ch34423]

fix(gatsby): Hide page/static queries activities for PQR

---

packages/gatsby-worker/src/__tests__/fixtures/test-child.ts
packages/gatsby-worker/src/__tests__/integration.ts
packages/gatsby-worker/src/index.ts
packages/gatsby-worker/src/utils.ts
packages/gatsby/src/commands/build.ts

This PR adds two things:
1. New feature for `gatsby-worker` - ability to restart worker pool
2. Actually restart worker pool after query running in workers
We need this because query workers are heavy and we don't need them holding all this memory when generating HTML or persisting state (which are also memory-heavy steps)
[ch34422]

feat(gatsby): restart worker pool after query running in workers

---

packages/gatsby/src/commands/build.ts

Workers may accumulate some garbage in memory during PQR and HTML generation and it doesn't make sense to keep them around when they are not needed anymore.
This PR moves the shut down step of our WorkerPool to an earlier stage - before state persistence. State persistence is rather expensive and it often consumes a significant amount of memory so stopping worker processes earlier should lower memory pressure a bit at this step.
[ch34426]

fix(gatsby): shut down worker pool after html generation

---

packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js

This fixes an issue @graysonhicks was debugging. 
WPGraphQL's pageInfo field is nullable, so we need to make sure we're not accessing hasNextPage on null.

fix(gatsby-source-wordpress): WPGraphQL pageInfo is nullable, make sure we're not accessing hasNextPage on null

---

SECURITY.md

Updating vulnerability reporting guidelines

Security md update

---

packages/gatsby/src/utils/__tests__/cache-lmdb.ts
packages/gatsby/src/utils/cache-lmdb.ts
packages/gatsby/src/utils/get-cache.ts

When LMDB is used we now also use it for `.cache/caches` directory (now `.cache/caches-lmdb`). Some plugins put large data into this cache and keeps this stuff in memory. LMDB does everything our existing cache does but doesn't keep values in memory forever.
This cache also unlocks the possibility to write temporary query results to LMDB, too.
[ch34444]

feat(gatsby): Add cache-lmdb implementation

---

packages/gatsby/src/schema/__tests__/pagination.js
packages/gatsby/src/schema/resolvers.ts

This PR fixes the `hasNextPage` field in the `pageInfo` data for paginated queries. When querying for paginated content using `skip` and `limit`, the `hasNextPage` field was returning `false` for anything other than the first page, even if it a next page of nodes exists.
Example query:
```graphql
{
allPrismicPage(limit: 2 skip: 2) {
nodes {
id
}
pageInfo {
hasNextPage
}
}
}
```
If there were a total of 6 nodes, `hasNextPage` was returning `false`. It now returns `true`.
The logic for determining the value of `hasNextPage` is edited in this PR and includes comments describing the logic.
Existing documentation: https://www.gatsbyjs.com/docs/schema-root-fields/#pagination-types
There is no need to update the documentation as this is a bug fix.
None

fix(gatsby): correct hasNextPage pagination info when resultOffset is provided

---

packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
packages/gatsby/cache-dir/app.js

Move to `createRoot` for gatsby-plugin-image and indicator
https://github.com/gatsbyjs/gatsby/discussions/31943

fix(gatsby,gatsby-plugin-image): fix createRoot on React 18

---

packages/gatsby/src/commands/build-html.ts

Extra error details added in https://github.com/gatsbyjs/gatsby/pull/32301 assume that all errors will have `.context.path`. But errors can be not specific to any particular page and can be thrown when just importing html rendering bundle (example of such error would be https://github.com/gatsbyjs/gatsby/blob/a0b542be35c15e71f8fe76cc5400576dfd0b1391/integration-tests/gatsby-cli/gatsby-sites/gatsby-build-errors/src/pages/index.js)

fix(gatsby): handle errors thrown when importing html renderer

---

docs/docs/tutorial/part-1/index.mdx
docs/docs/tutorial/part-2/index.mdx
docs/docs/tutorial/part-3/index.mdx
docs/docs/tutorial/part-4/index.mdx
docs/docs/tutorial/part-5/index.mdx

* Adds `Announcement` component with an embedded livestream video to parts 2-5 of the Tutorial.
* Adds a start time to the part 1 livestream embed (to skip over the initial chitchat).
Livestream embeds are at the bottom of the Introduction section
* /docs/tutorial/part-1
* /docs/tutorial/part-2
* /docs/tutorial/part-3
* /docs/tutorial/part-4
* /docs/tutorial/part-5

docs(tutorial): add livestream links to parts 2-5, update start time for part 1

---

packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx

The named imports were a bit over eager in the initial PR (https://github.com/gatsbyjs/gatsby/pull/32378) so this switches it to default import via `ReactDOM`. We do the same in `cache-dir/app.js`.
Fixes https://github.com/gatsbyjs/gatsby/issues/32451
[ch34846]

fix(gatsby-plugin-image):  Switch react-dom import to remove createRoot warning

---

packages/gatsby-plugin-sharp/src/gatsby-node.js
packages/gatsby/index.d.ts
packages/gatsby/src/utils/api-node-helpers-docs.js
packages/gatsby/src/utils/api-runner-node.js
packages/gatsby/src/utils/cache-lmdb.ts
packages/gatsby/src/utils/cache.ts

Introduction of lmdb implementation of cache (passed to plugins) is missing `.cache` internal cache being exposed (as "legacy" cache does). This cause `gatsby-plugin-sharp` that want to use `.del` on that internal cache instance to crash in `gatsby develop`.
This PR does few things:
a) adds compat mode to lmdb cache implementation (add `.cache` property that is just reference to itself)
b) adds `.del` method on public interface (and implement it in both legacy cache and lmdb cache)
c) future proofs `gatsby-plugin-sharp` to use public `.del` if available (ideally we remove access to internal cache implementation in v4) 
Fixes #32445

fix: expose ".del" function on lmdb cache

---

packages/gatsby/src/utils/cache-lmdb.ts

Coming from https://github.com/gatsbyjs/gatsby/discussions/32389#discussioncomment-1032935 it showed that plugins (like gatsby-source-wordpress) can exchange serializable values between plugin APIs and uses the cache for that. With LMDB we'd need to change to another encoding to fix this.
Follow-up:
We could maybe use https://github.com/kriszyp/msgpackr#custom-extensions to just ignore/strip functions and continue to use msgpackr
[ch34877]

fix(gatsby): Add encoding option to GatsbyCacheLmdb

---

packages/gatsby-admin/package.json

add allow list to gatsby-admin to only include necessary files. I'm not sure why people are installing it as it shouldn't be.

chore(gatsby-admin): add allowlist of files

---

scripts/validate-starters.sh

We don't particularly care about this (inaccurate) check anyways and it blocked the check from actually working correctly and checking if everything works (since the step always stopped at `npm audit`)

chore(validate-starters): Remove `npm audit` step

---

docs/docs/reference/markdown-syntax.md

I found a minor typo in the markdown syntax documentation. It seems trivial but it might confuse some people
https://www.gatsbyjs.com/docs/reference/markdown-syntax/#blockquote

chore(docs): Fix a minor typo "with" > "will"

---

packages/gatsby-plugin-mdx/gatsby/create-schema-customization.js

This PR is a performance improvement for one specific usage scenario of the MDX plugin. It addresses inefficiency in the plugin when multiple GraphQL fields are requested that require MDX processing. An example query that is affected:
```graphql
{
mdx {
mdxAST
body
}
}
```
In this case, the plugin starts two MDX processing tasks concurrently as shown on this chart:
This PR accounts for such a scenario and only processes MDX once. For MDX-heavy sites using this pattern, e.g. https://github.com/newrelic/docs-website
This translates to the following difference in query running time:
Before this PR:
```
success run page queries - 2776.543s - 8324/8324 3.00/s
```
After this PR:
```
success run page queries - 1919.154s - 8324/8324 4.34/s
```
(image processing also affects those numbers, on a …

fix(gatsby-plugin-mdx): generate mdx once when multiple mdx fields requested

---

packages/gatsby-worker/src/index.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/redux/__tests__/index.js
packages/gatsby/src/redux/index.ts
packages/gatsby/src/redux/reducers/__tests__/queries.ts
packages/gatsby/src/redux/reducers/queries.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/worker/__tests__/queries.ts
packages/gatsby/src/utils/worker/child/index.ts
packages/gatsby/src/utils/worker/child/queries.ts
packages/gatsby/src/utils/worker/pool.ts

This PR is a follow-up to #32305 After benchmarking on a heavy site we've learned that replaying actions for data dependencies is expensive. So basically this PR implements solution described in https://github.com/gatsbyjs/gatsby/pull/32305#issuecomment-880692093:
> If data dependencies will be too expensive to sync this way - we can do a hybrid approach - forward/replay some actions and merge expensive parts all at once in the end.
Now we merge the data dependency state at the end of the build. It is still expensive but far less expensive than replaying all data dependency actions: `21s` vs `250s` for this heavy test site:
```
success run queries in workers - 378.129s - 25789/25789 68.20/s
success Merge worker state - 21.678s
```
But query state files are huge, so maybe this is not a …

fix(gatsby): merge data deps state instead of replaying actions

---

packages/gatsby/src/schema/__tests__/pagination.js
packages/gatsby/src/schema/__tests__/queries.js
packages/gatsby/src/schema/resolvers.ts

This PR fixes an issue with incorrect pagination logic introduced in a recent refactor: #32135
The previous attempt in #32319 in fact contains incorrect assumptions about pagination logic. The actual issue was not in `paginate` function itself but one level higher in the method that accounts for item paddings.
This PR fixes the issue and adds tests at the correct level of abstraction. The first commit is just a revert of #32319 so the actual fix is in the second commit (for the review): https://github.com/gatsbyjs/gatsby/commit/1d19c0825c03f238bb11524272ebb1e79a3fe20b
Fixes #32485
[ch35018]

fix(gatsby): correct pagination logic

---

docs/docs/how-to/previews-deploys-hosting/asset-prefix.md

Typo; assetPrefix instead of pathPrefix.
A reference indented as `assetPrefix` was mistakenly written as `pathPrefix`.

chore(docs): Fix typo in assetPrefix doc

---

docs/docs/reference/routing/file-system-route-api.md

Typo; pageContext instead of context.
A reference indented as pageContext was mistakenly written as context.

chore(docs): Fix typo in File System Route API doc

---

packages/gatsby/src/commands/build.ts

When using PQR we saw one site successfully going through the `run queries in workers` step only to fail on `Received message about completed job that wasn't scheduled by this worker` - this probably happened because the pool was restarted before all jobs finished.
This change adds the explicit waiting step
[ch35140]

fix(gatsby): PQR - Wait for Jobs to be Completed before restarting

---

docs/docs/tutorial/part-2/index.mdx
docs/docs/tutorial/part-4/index.mdx

Updates the semantic HTML in the Layout component.
* Only wrap page-specific elements in the `<main>` element.
* Use `<header>` element for page title in Part 4.
* /docs/tutorial/part-2
* /docs/tutorial/part-4

docs(tutorial): improve a11y of layout component

---

docs/docs/graphql-reference.md

This replaces the GraphiQL iframes in the GraphQL Reference section with static code blocks. The current setup, using Gatsby Preview will stop working once the new Preview experience is fully rolled out.
I made some light copy edits to avoid language related to the interactive iframes and am looking for proofreading and editing suggestions.
Reported internally [ch32387]

Docs: fix GraphQL Reference 

---

packages/gatsby/src/utils/worker/__tests__/queries.ts
packages/gatsby/src/utils/worker/child/queries.ts
packages/gatsby/src/utils/worker/pool.ts

I noticed that we load `components` and `staticQueryComponents` (to get access to extracted queries) for each batch, but really we only need to do this once

fix(gatsby): load page and static queries texts in PQR only once per worker

---

e2e-tests/development-runtime/package.json
e2e-tests/production-runtime/package.json

There was a breaking change in minor `graphql-config` release ( see https://github.com/kamilkisiela/graphql-config/pull/699#issuecomment-889831229 ). We can't really fix it as it's transitional dependency, so trying to pin it just for e2e tests (hopefully `graphql-config` will handle that in some way, because right now users on Node `<12.20` using `yarn` will get engines not satisfied errors.

test: pin graphl-config

---

packages/gatsby/src/redux/actions/public.js

Make clear that this isn't generally what people want.

fix(docs): clarify redirectInBrowser option

---

renovate.json5
scripts/renovate-config-generator.js

Add some global packages to renovate that are widely used to reduce multiple PRs for the same package
- semver
- cheerio
- core-js
- chokidar
I've also disabled @types/node as they should be equal to our node engines.

chore: add some extra global groups to renovate

---

packages/gatsby-core-utils/src/fetch-remote-file.ts

This just breaks circular imports happening right now - index re-exports from `./create-content-digest` and `create-content-digest` imports from index.

fix(gatsby-core-utils): avoid circular imports

---

docs/docs/how-to/previews-deploys-hosting/asset-prefix.md

This was missing from the docs

fix(docs): Document how to do asset prefix build with env variable

---

packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js

This is mostly useful when using the dev server to run a preview instance where you
don't want the dev-focused 404 page.
To use this, you'd run your develop instance with the environment variable `GATSBY_DISABLE_CUSTOM_404` set to true e.g.
```shell
GATSBY_DISABLE_CUSTOM_404=true gatsby develop
```

feat(gatsby): allow sites to disable the dev 404 page

---

docs/docs/reference/built-in-components/gatsby-plugin-image.md

Fixed an incorrect URL in the documentation for Sharp.

chore(docs): Fix URL to sharp

---

docs/docs/reference/release-notes/v3.11/index.md

Release notes for v3.11. Please add anything you would like to mention from this release.
[Rendered Version](https://github.com/gatsbyjs/gatsby/blob/sid/ch35605/3-11-release-release-notes/docs/docs/reference/release-notes/v3.11/index.md)
[ch35605]

docs: release notes for v3.11

---

starters/blog/src/pages/using-typescript.tsx
starters/default/src/pages/using-typescript.tsx

Small typo fix on /using-typescript page in gatsby starter templates. TypeScript `tsconfig.json` file does not have a dot infront of it.
n/a
n/a

chore(starters): Typo on tsconfig

---

packages/gatsby-source-shopify/README.md
packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts

Recently we added extra fields to product variant in order to be able to manage multiple locations in your shopify shop.
These extra fields require additional permission (Inventory read permission), so we need to make sure that these extra fields only get added when the user opts into using `locations` collection.
Brought up in issue https://github.com/gatsbyjs/gatsby/issues/32702

fix(gatsby-source-shopify): only add inventory fields to product variant when using locations

---

.eslintrc.js
global.d.ts
package.json
packages/babel-preset-gatsby-package/.babelrc
packages/babel-preset-gatsby-package/.gitignore
packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
packages/babel-preset-gatsby-package/__tests__/babel-transform-compiler-flags.js
packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/default/input.js
packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/default/output.mjs
packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/unused/input.js
packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/unused/options.json
packages/babel-preset-gatsby-package/__tests__/fixtures/options.js
packages/babel-preset-gatsby-package/__tests__/index.js
packages/babel-preset-gatsby-package/package.json
packages/babel-preset-gatsby-package/src/babel-transform-compiler-flags.ts
packages/babel-preset-gatsby-package/src/index.js
packages/babel-preset-gatsby-package/src/resolver.js
packages/babel-preset-gatsby-package/tsconfig.json
tsconfig.json
types/gatsby-monorepo/global.d.ts
types/gatsby-monorepo/package.json
yarn.lock

Added an extra feature to babel-preset-gatsby-package to enable [Conditional compilation](https://en.wikipedia.org/wiki/Conditional_compilation). It's a fancy word to add if cases that are evaluated at build time. In the long run, we'll have a real bundle that would also compile the code path away.
To enable the features you have to set availableCompilerFlags as an option in the babel-preset-gatsby-package.
```
{
"presets": [["babel-preset-gatsby-package", { "availableCompilerFlags": ["GATSBY_MAJOR"] }]]
}
```
In code you can set it:
```
if (_CFLAGS_.GATSBY_MAJOR === '4') {
// THIS IS ONLY HIT WHEN COMPILER OPTION GATSBY_MAJOR=4 is set
} else {
// THIS IS ONLY HIT WHEN NO COMPILER_OPTION IS SET OR GATSBY_MAJOR != 4
}
```
These flags are parsed from `process.env.COMPILER_OPTIONS`, the …

feat(babel-preset-gatsby-package): add conditional compilation plugin

---

packages/gatsby/src/utils/fast-refresh-module.ts

Fix fast-refresh-module to work with non-window environments like Workers.
Fixes #30687

fix(gatsby): Worker support in fast-refresh-module

---

packages/gatsby-remark-images-contentful/src/__tests__/index.js
packages/gatsby-remark-images-contentful/src/index.js

fix(gatsby-remark-image-contentful): show useful error message for files that can not be rendered as image

---

packages/gatsby-source-wordpress/src/steps/preview/index.ts

We've had an issue with a self hosted Gatsby Preview instance crashing and restarting after duplicating a post (with `duplicate-post` plugin v 4.1.2).
The error message right before the instance crashes is:
> success  gatsby-source-wordpress  diff schemas - 0.604s
> success  gatsby-source-wordpress  ingest WPGraphQL schema - 0.856s
> success createSchemaCustomization - 0.894s
> warn  gatsby-source-wordpress  cG9zdDoyMTUy page was updated, but no data was
> returned for this node.
> 
>  ERROR
> 
> Cannot read property 'databaseId' of null
> 
> 
> 
>   TypeError: Cannot read property 'databaseId' of null
>   
>   - index.ts:316 sourcePreview
>     [app]/[gatsby-source-wordpress]/src/steps/preview/index.ts:316:29
>   
>   - runMicrotasks  
>   
>   - task_queues.js:93 …

Fix "TypeError: Cannot read property 'databaseId' of null" in gatsby-source-wordpress previews

---

packages/gatsby-source-wordpress/docs/plugin-options.md
packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts
packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js

This PR adds support for webp image format.
Previously the plugin created scaled versions of the source images in the same format as the source image (e.g. only `.png` for `.png` files). This PR additionally generates `.webp` so that webp images would be served to the browsers that support it.
Fixes #30895

feat(gatsby-source-wordpress): generate webp images

---

docs/docs/how-to/routing/migrate-remark-to-mdx.md

The new link doesn't produce a 404 error and provides the expected resource.

Fixed broken link "Using MDX Plugins"

---

packages/gatsby/src/schema/types/sort.ts

Fixes typos in string enum members.
None.
None.

chore(gatsby): fix typo in string enum member

---

packages/gatsby/src/commands/develop.ts

As per https://nodejs.org/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback:
> The optional callback is a function that is invoked after the message is sent but before the child may have received it. The function is called with a single argument: null on success, or an Error object on failure.
> If no callback function is provided and the message cannot be sent, an 'error' event will be emitted by the ChildProcess object. This can happen, for instance, when the child process has already exited.
So we provide a callback now so that it doesn't emit an 'error' event.
Fix https://github.com/gatsbyjs/gatsby/issues/28011
[ch35874]

fix(gatsby): Silence process.send Error

---

packages/gatsby/src/datastore/lmdb/query/__tests__/common.ts
packages/gatsby/src/datastore/lmdb/query/common.ts
packages/gatsby/src/datastore/lmdb/query/filter-using-index.ts
packages/gatsby/src/datastore/lmdb/query/run-query.ts
packages/gatsby/src/schema/__tests__/run-query.js

> This PR doesn't affect stable codepath or even LMDB_STORE one. Only experimental codepath behind `GATSBY_EXPERIMENTAL_LMDB_INDEXES` flag
Before this PR range filters (`lt`, `lte`, `gt`, `gte`) were reversed in an edge case when the filter was not satisfied by the index and the results were post-filtered in node.
See the inline comment below for more details on this fix.

fix(gatsby): fix incorrect filtering with experimental LMDB indexes

---

packages/gatsby/src/internal-plugins/functions/gatsby-node.ts

Adds an env var `GATSBY_PRECOMPILE_DEVELOP_FUNCTIONS` to disable lazy function compilation in develop. This allows them to be dynamically imported without needing to make an HTTP request.

feat(gatsby): add env flag to disable lazy function compilation in develop

---

packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
packages/gatsby-source-shopify/src/make-source-from-operation.ts

The ENV variable `IS_PRODUCTION_BRANCH` that we were relying on to check if we were in a preview or production build only checks the branch in which we are building off of. Preview and Production builds by default build from the same branch. To get the behaviour we wanted we are using the env var `GATSBY_IS_PREVIEW` to check if the build is a preview, if it is, then it is not a priority build.

fix(gatsby-source-shopify): env variable to check if on preview or production

---

packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/introspect-remote-schema.js
packages/gatsby-source-wordpress/src/steps/preview/index.ts

Initially I thought building the manifest ID on the Gatsby side would be enough. Then I noticed if a preview build fails and then is triggered again but the user is still sitting on the preview loader they will be waiting for a manifest id that will never exist even though the preview might still succeed. So in https://github.com/gatsbyjs/wp-gatsby/pull/180 I'm storing manifest ID's on each preview action in WP so that they can be queried in `gatsby-source-wordpress` and each can be processed.
This makes WP preview more stable with the upcoming preview loader.
To prevent making a breaking change and needing to release v6 of `gatsby-source-wordpress` due to requiring a new minimum remote version of WPGatsby I added a new helper to check if a field name exists on a type in the remote schema …

feat(gatsby-source-wordpress): process multiple manifest ids on a preview action

---

packages/gatsby-source-wordpress/src/steps/preview/index.ts

After merging https://github.com/gatsbyjs/gatsby/pull/32723 I got a notification that linting was failing for changes in that PR. Weirdly the lint test succeeded in the PR though.
https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/68458/workflows/8c79aa7e-8e15-486c-ae8c-294ab5fdce7f/jobs/778629

fix(gatsby-source-wordpress): linting error

---

docs/docs/how-to/performance/improving-build-performance.md

In an audit of sites on Gatsby Cloud, 20-30% had slower than expected createPages time due to this issue.

feat(docs): Add note about speeding createPages to build perf doc

---

packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js

This fixes a Gatsby Cloud customer issue where this was failing builds

fix(gatsby-source-wordpress): not all stored nodes are media items - protect against that

---

package.json
scripts/clear-package-dir.js
scripts/release-cli.js
scripts/release-next-major.js
types/gatsby-monorepo/readme.md

Create a simple release scripts to publish the next premajor. It allows us to put patch files in patches/v4/ to update package.json and dependencies.
**What does this file do?**
- it checks if you have publish access
- it checks if we have any uncommited files -- if so, we exit
- it cleans all non git files to make sure we have clean directory
- run patches in patches/v4
- commits the patches so lerna can publish
- run full boostrap with COMPILER_OPTIONS
- Publish premajor
- cleanup patch commit

chore: add release-cli for next major

---

docs/docs/how-to/performance/improving-build-performance.md
packages/gatsby/src/services/create-pages.ts

Follow-up to https://github.com/gatsbyjs/gatsby/pull/32750
A GraphQL query should almost never take longer than a second regardless of
the size of site so if the query takes more than 10s, they're probably
querying something really expensive like markdown html or images, etc.
which aren't needed for creating pages.

feat(gatsby): measure how long GraphQL takes to run in createPages and warn if > 10s

---

packages/gatsby/src/utils/api-browser-docs.ts

Clarifies when `getSavedScrollPosition` will return null.
`shouldUpdateScroll` in Gatsby Browser APIs docs:
https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#shouldUpdateScroll
Closes #32546

chore(docs): Improved getSavedScrollPosition API desc

---

packages/gatsby/src/utils/page-data.ts
packages/gatsby/src/utils/worker/__tests__/queries.ts
packages/gatsby/src/utils/worker/child/queries.ts

For reference - when adjusted e2e_dev_runtime tests (to run on node14 and use lmdb-store)- without anychanged - we got failing tests - https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/68624/workflows/f8b1b752-3b09-43a6-81b3-eea1e5e712d7/jobs/781979
With changes in this PR - tests are happy - https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/68670/workflows/d2a8dd21-e410-4bd6-bff6-9008cccb7e65/jobs/782817
[ch35936]

fix(develop): fix "Couldn't find temp query result for X." errors when using LMDB_STORE

---

packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts

If a user does not have any `shopifyConnections`, `includeLocations` would be `undefined` and fail the gql query because we are using this variable in an `if` directive.

fix(gatsby-source-shopify): coerce variable to boolean

---

packages/gatsby/cache-dir/production-app.js

Wraps `performance.mark` in a safety check. This is currently violating the commitment of browser support as it isn't polyfilled and isn't supported on all browsers
Fixes #32279

fix(gatsby): Wrap performance mark in check

---

packages/gatsby-source-shopify/src/client.ts
packages/gatsby-source-shopify/src/create-schema-customization.ts
packages/gatsby-source-shopify/src/query-builders/collections-query.ts
packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
packages/gatsby-source-shopify/src/query-builders/products-query.ts

Brought up in https://github.com/gatsbyjs/gatsby/issues/32722. Shopify recently deprecated the `valueType` field on metafields so shops that were using metafields would be failing. Shopify recommended either removing the `valueType` field on the query or updating to the new API version that supports a more robust `type` field.
I decided to update it as there seem to be no breaking changes that concern the plugin.

fix(gatsby-source-shopify): update api version to fix metafield type issue

---

packages/gatsby/src/bootstrap/requires-writer.ts
packages/gatsby/src/commands/build-utils.ts
packages/gatsby/src/query/index.ts
packages/gatsby/src/query/query-runner.ts
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/page-data.ts

Adds new property `defer` to public createPage and internally new `mode`
[ch35562]

feat(gatsby): Add `defer` to createPage

---

packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/gatsby-node.js

Working to track down why sometimes this value isn't set

feat(gatsby-source-drupal): log value of lastFetched

---

packages/gatsby-source-contentful/README.md

Added a code example in the [gatsby-source-contentful readme](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/README.md) for embedding an image in a rich-text field.
https://www.gatsbyjs.com/plugins/gatsby-source-contentful/?=gatsby-so#contentful-rich-text
Fixes #32099

docs(gatsby-source-contentful) provide a code example for rendering rich-text embedded assets images

---

packages/create-gatsby/src/index.ts

Make it clearer how it's intended to be used
Fixes https://github.com/gatsbyjs/gatsby/issues/32826
[ch36420]

fix(create-gatsby): Clarify multi-choice instructions

---

packages/gatsby/src/utils/flags.ts

We [added caching support for webpack in development in 3.10](https://www.gatsbyjs.com/docs/reference/release-notes/v3.10#experimental-webpack-persistent-caching-for-gatsby-develop) and it's gotten a fair bit of usage since.
Let's now opt-in 20% of users for a final test before release.

feat(gatsby): Opt in 20% of users to webpack dev server caching

---

packages/gatsby-plugin-image/package.json
yarn.lock

v3 includes error handling and it’s also the only one i’m really maintaining atm

gatsby-plugin-image: bump do-sync to v3

---

packages/gatsby/src/utils/webpack-utils.ts

Another follow-up to https://github.com/gatsbyjs/gatsby/issues/31878
So `removeDimensions` is removed.
I also sorted the list alphabetically now and commented which plugins are disabled by default.
[ch36479]

fix(gatsby): Remove `removeDimensions` from svgo config

---

docs/docs/reference/release-notes/v3.0/index.md

Fixes a typo in the release notes

chore(docs): Fix typo in v3.0 release notes

---

docs/tutorial/building-a-theme.md

The [**Bulding a theme guide**](https://www.gatsbyjs.com/tutorial/building-a-theme) is missing the development dependencies installation info that leads to an error when the development server is started on theme directory.
The guide only explains on how to install [peer dependencies](https://www.gatsbyjs.com/tutorial/building-a-theme#add-peer-dependencies-to-gatsby-theme-events) which fails when locally running a development server for the theme that we are building as the `devDependencies` are required when testing locally.
This PR introduces those missing part.
Reference: [Building a theme](https://www.gatsbyjs.com/tutorial/building-a-theme)

chore(docs): Remove outdated information from Theme Guide

---

e2e-tests/production-runtime/cypress/integration/redirects.js
e2e-tests/production-runtime/gatsby-node.js
e2e-tests/production-runtime/package.json
e2e-tests/production-runtime/src/pages/index.js
e2e-tests/production-runtime/src/pages/redirect-search-hash.js
packages/gatsby/cache-dir/navigation.js

Follow-up to https://github.com/gatsbyjs/gatsby/pull/32334
I didn't add any tests to production runtime (somehow forgot) so didn't catch that it doesn't behave correctly for `production-runtime` on **direct visits**.
Fixes https://github.com/newrelic/docs-website/issues/2139
[ch36705]

fix(gatsby): Hashes and anchors in redirects also work in production

---

integration-tests/node-manifest/__tests__/create-node-manifest.test.js
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/query/index.ts
packages/gatsby/src/utils/node-manifest.ts
packages/gatsby/src/utils/page-data.ts

In order to statically determine if the corresponding page-data.json file for the node in a node manifest is fully deployed and the changes have propagated globally, I've added a content digest of the page-data.json file to each node manifest. This allows a client to compare it against a digest of the page-data.json that they've requested to make sure it's deployed. 
The location I've moved `processNodeManifests` to is in order to make sure page-data files are written for `gatsby build` as well as inc builds when node manifests are processed.

feat(gatsby): add node manifest page data digest

---

docs/docs/tutorial/part-5/index.mdx

I just found a small typo while reading the tutorial
None needed
None

chore(docs): Fix typo in part 5 of the tutorial

---

packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/create-redirects.js.snap
packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-redirects.js
packages/gatsby-plugin-gatsby-cloud/src/create-redirects.js

If a user removes all redirects, we continue to keep the existing _redirects.json file intact. This PR will overwrite that file if empty

fix(gatsby-plugin-gatsby-cloud): Always create redirects.json

---

docs/tutorial/remark-plugin-tutorial.md

The current example for walking the Markdown syntax tree using asynchronous behaviour, [gatsby-remark-code-repls](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-code-repls/src/index.js) no longer uses it. Hence, I propose changing the example to [gatsby-responsive-iframe](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-responsive-iframe/src/index.js).
[Creating a Remark transformer plugin](https://www.gatsbyjs.com/tutorial/remark-plugin-tutorial/)
None

chore(docs): Change example for using async in Remark plugin

---

docs/docs/tutorial/part-2/index.mdx

Fixed export for GalleryPage and added import React line
Fixing the GalleryPage example
Changed from `export const GalleryPage` to `export default GalleryPage`
None? In the Tutorial documentation itself
None that I know of

chore(docs): Update Gallery example in tutorial part 2

---

docs/docs/tutorial/part-2/index.mdx

- Replace `.modules.css` with `.module.css`
- **Syntax Hint** at 6th Step in https://www.gatsbyjs.com/docs/tutorial/part-2/#style-components-with-css-modules

chore(docs): Fix CSS Modules extension typo

---

packages/gatsby-remark-images/src/__tests__/index.js
packages/gatsby-remark-images/src/index.js

`gatsby-remark-images` will incorrectly attempt to convert videos and other files, only disallowing gifs and svgs. This PR adds an explicit allow list instead.
This helps it play nicer with plugins such as [`gatsby-remark-videos`](https://github.com/Mike-Dax/gatsby-remark-videos).

chore(gatsby-remark-images): Only convert supported image extensions

---

docs/docs/building-an-ecommerce-site-with-shopify.md

Update docs on building eCom with Shopify to work with latest versions
- Updated graphql queries
- Updated options needed for `gatsby-source-shopify`
- Removed reference to `shopify-buy` as it's not used in this tutorial

chore(docs): Update Building eCom with Shopify to work with latest versions

---

packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
packages/gatsby-plugin-gatsby-cloud/src/ipc.js

Let Cloud know which files of type `File` are generated and should be uplaoded.
[ch36492]

feat(gatsby-plugin-gatsby-cloud): Files manifest

---

patches/v4/0-node-version.patch
patches/v4/1-lmdb-default.patch
patches/v4/2-gatsby-peerdeps.patch
scripts/release-next-major.js

- fix patches
- commit yarn changes
Because of many package upgrades and cleanups the patch file diverged. These fixes them and also adds an extra commit when yarn.lock changes

chore: fix patches for v4 to be compatible again

---

packages/babel-plugin-remove-graphql-queries/package.json
packages/babel-preset-gatsby-package/package.json
packages/create-gatsby/package.json
packages/gatsby-admin/package.json
packages/gatsby-cli/package.json
packages/gatsby-core-utils/package.json
packages/gatsby-design-tokens/package.json
packages/gatsby-legacy-polyfills/package.json
packages/gatsby-plugin-benchmark-reporting/package.json
packages/gatsby-plugin-graphql-config/package.json
packages/gatsby-plugin-image/package.json
packages/gatsby-plugin-mdx/package.json
packages/gatsby-plugin-netlify-cms/package.json
packages/gatsby-plugin-no-sourcemaps/package.json
packages/gatsby-plugin-page-creator/package.json
packages/gatsby-plugin-preact/package.json
packages/gatsby-plugin-preload-fonts/package.json
packages/gatsby-plugin-schema-snapshot/package.json
packages/gatsby-plugin-styletron/package.json
packages/gatsby-plugin-subfont/package.json
packages/gatsby-plugin-utils/package.json
packages/gatsby-recipes/package.json
packages/gatsby-source-shopify/package.json
packages/gatsby-source-wikipedia/package.json
packages/gatsby-transformer-screenshot/package.json
packages/gatsby-worker/package.json

This PR adds `@babel/runtime` as a dependency to all packages that are missing it. Because packages are all compiled with `@babel/plugin-transform-runtime`, they all need it as a dependency. It usually works ok because it is a dependency of `gatsby`, but it's good practice to not rely on transitive dependencies, and in some situations can be tree-shaken away.

chore: add missing `@babel/runtime` dependencies

---

docs/docs/tutorial/part-1/index.mdx
docs/docs/tutorial/part-4/index.mdx
packages/create-gatsby/src/features.json

In doing a test run of the tutorial, I realized that we're still asking people to install the gatsby cloud plugin in the `gatsby new` cli interface. We autoinstall this on Cloud now, so it's no longer necessary.
I updated the tutorial references to it and that seems to the be the extent of the documentation around this specific feature.

docs: Remove cloud plugin from `gatsby new` and tutorial

---

packages/gatsby/src/services/initialize.ts

`FAST_DEV` flag right now results in multiple copies of same logs (one for each worker), due to transitional import in https://github.com/gatsbyjs/gatsby/blob/88e1559c444156d668cc2c4ec732e6c39aff2dac/packages/gatsby/src/utils/worker/child/queries.ts#L1-L5 and fact that we handle env var at import time.
This is absolutely not ideal, but we also can't easily move the code from import time path as it might be handled too late otherwise.
[ch35984]
https://github.com/gatsbyjs/gatsby/discussions/32389#discussioncomment-1153345

fix(gatsby): don't log FAST_DEV message for each worker

---

packages/gatsby/src/redux/__tests__/index.js
packages/gatsby/src/redux/index.ts

Use `trackCli` to capture cache status

fix(gatsby): Proper cache status event

---

packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-redirects.js
packages/gatsby-plugin-gatsby-cloud/src/__tests__/routes.js
packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
packages/gatsby-plugin-gatsby-cloud/src/create-redirects.js
packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
packages/gatsby-plugin-gatsby-cloud/src/ipc.js

Adds backpressure to IPC to prevent message loss in case of process exiting early. As mentioned in [docs on `process.send`](https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback):
> `subprocess.send()` will return false if the channel has closed or when the backlog of unsent messages exceeds a threshold that makes it unwise to send more. Otherwise, the method returns true. The callback function can be used to implement flow control.
Also related: https://github.com/nodejs/node/issues/7657#issuecomment-253744600
This PR also adds batching for `emitRoute` IPC calls.
P.S. GitHub diff here is pretty messy, use `Files Changed -> Settings -> Hide whitespace characters` to make it readable.
Apparently, Jest sets up an …

fix(gatsby-plugin-gatsby-cloud): add backpressure for IPC

---

packages/gatsby-graphiql-explorer/src/app/snippets.js

This adds a `createPage` snippet to the GraphiQL explorer.  Often, a developer will begin creating the site by examining their data layer in GraphiQL.  They will then want to create pages based off of their initial query.  For example:
```graphql
query MyQuery {
allContentfulBlogPosts {
nodes {
id
slug
}
}
}
```
Currently, the user must then either:
- find the documentation on creating pages in gatsby-node, copy, paste and replace or
- type the createPage functionality by hand
This snippet allows for a direct copy and paste from GraphiQL.  The user will then only have to fill in:
- the path to the page template
- the field being used as the slug
- manually add desired fields to pageContext 
The above query would generate the following snippet:
```javascript
const path = require(`path`) …
```

Add a createPages snippet to GraphiQL explorer

---

packages/gatsby-source-contentful/src/extend-node-type.js

When retrying asset downloads to get the dominant color, the build failed. This fixes this issue.
(I basically forgot to pass the reporter to the function)
`[gatsby-source-contentful] Could not getDominantColor from image TypeError: Unable to download asset from http://images.ctfassets.net/... Cannot read property 'verbose' of undefined`
Related: #30391

fix(contentful): asset download retry

---

packages/gatsby/cache-dir/navigation.js

Fix https://github.com/gatsbyjs/gatsby/issues/18866
The error happens when a user loads a page and while they have it open, a new version of the site is deployed. Then when they try to navigate and the Gatsby app tries to load a js chunk, the chunk might no longer exist on the server and so the
app crashes.
This PR is a port of my code snippet for a site's gatsby-browser that a number of people have tested with good results https://github.com/gatsbyjs/gatsby/issues/18866#issuecomment-844449917

feat(gatsby): catch webpack chunk loading errors and completely reload the app

---

docs/contributing/docs-and-blog-components.md
docs/contributing/docs-contributions/index.md
docs/contributing/docs-writing-process.md
docs/contributing/how-to-open-a-pull-request.md
docs/docs/modifying-a-starter.md

[ch37501](https://app.clubhouse.io/gatsbyjs/story/37501/broken-links-docs-contribution)
Fixes broken links on the /contributing/docs-contributions/ page
`/contributing/docs-contributions/`

docs(ch37501): fix broken links from docs contribution page

---

packages/gatsby-transformer-sqip/src/extend-node-type.js

This is the same issue as fixed yesterday in #33024

fix(sqip): ensure failed asset downloads do not break build

---

packages/gatsby-plugin-sharp/src/__tests__/index.js
packages/gatsby-plugin-sharp/src/__tests__/trace-svg.js
packages/gatsby-plugin-sharp/src/image-data.ts
packages/gatsby-plugin-sharp/src/index.js
packages/gatsby-plugin-sharp/src/process-file.js
packages/gatsby-plugin-sharp/src/trace-svg.js
packages/gatsby-plugin-sharp/src/utils.js

Converts sharp usage based on file paths to file streams, e.g.
```js
// Before
const imgStats = await sharp(file.absolutePath).stats()
// After
const pipeline = sharp()
fs.createReadStream(file.absolutePath).pipe(pipeline)
const imgStats = await pipeline.stats()
```
For the writing of files we use `sharpPipeline.toBuffer() + fs.writeFile()` for now. We probably will change it to filestream in future PR (will just need to revert https://github.com/gatsbyjs/gatsby/pull/33029/commits/31cfaf32663fb945a8d983227493e6f5f24761a0).
Running the `image-processing` benchmark didn't show any major speed improvement/degradation
[ch37488]

feat(gatsby-plugin-sharp): Use file streams instead of file paths

---

packages/gatsby/cache-dir/static-entry.js
packages/gatsby/package.json
packages/gatsby/src/internal-plugins/bundle-optimisations/gatsby-node.js
packages/gatsby/src/utils/webpack.config.js

Removes lodash from static-entry and changes webpack config to improve performance:
Tested it on blog-starter
- Drops page-renderer from 827kb => 295kb (decrease of 64.33%)
- Perf cold build 1.8s => 1.3s
- Perf warm build (no change): 1s -> 0.5s

fix(gatsby): reduce page-renderer-size

---

packages/gatsby-telemetry/src/telemetry.ts

Remove gatsby-cli import when bundling query-engine

fix(gatsby-telemetry): don't require gatsby-cli

---

packages/gatsby/cache-dir/page-ssr/index.d.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/utils/client-assets-for-template.ts
packages/gatsby/src/utils/page-data-helpers.ts
packages/gatsby/src/utils/page-data.ts
packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
packages/gatsby/src/utils/page-ssr-module/entry.ts
packages/gatsby/src/utils/static-query-utils.ts
packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/worker/child/render-html.ts

I suggest to use "Hide whitespace changes" in diff viewer - https://github.com/gatsbyjs/gatsby/pull/33067/files?diff=unified&w=1
Building on top of GraphQL Engine introduced in https://github.com/gatsbyjs/gatsby/pull/33030
> This feature is disabled by default. Only available when building gatsby itself with `COMPILER_OPTIONS="GATSBY_MAJOR=4"`
This adds generation of "page engine" - importable standalone module that allows generation of page-data and html content. It uses "query engine" (introduced in https://github.com/gatsbyjs/gatsby/pull/33030 ) under the hood.
Example usage (after initial `gatsby build`):
```js
const { GraphQLEngine } = require(`./.cache/query-engine`)
const { getData, renderHTML, renderPageData } = require(`./.cache/page-ssr`)
const graphqlEngine = new …
```

feat(gatsby): page engine

---

patches/v4/3-gatsby-plugin-mdx-subplugin.patch

Depend on https://github.com/gatsbyjs/gatsby/pull/33030
This moves `gatsby-plugin-mdx` away from requiring arbitrary modules inside plugin and instead relying on `subPlugins` helper to automatically load those modules.
Same as https://github.com/gatsbyjs/gatsby/pull/33039 - just for `gatsby-plugin-mdx` package

feat(gatsby-plugin-mdx): use subplugin annotation to use automatic subplugin module loading

---

packages/gatsby-transformer-remark/src/create-schema-customization.js
packages/gatsby-transformer-remark/src/extend-node-type.js
packages/gatsby-transformer-remark/src/gatsby-node.js

Depend on https://github.com/gatsbyjs/gatsby/pull/33030
This moves `gatsby-transformer-remark` away from requiring arbitrary modules inside plugin and instead relying on `subPlugins` helper to automatically load those modules.
Same as https://github.com/gatsbyjs/gatsby/pull/33040 - just for `gatsby-plugin-mdx` package

feat(gatsby-transformer-remark): use subplugin annotation to use automatic subplugin module loading

---

packages/gatsby-source-drupal/README.md

After upgrading to Gatsby 3 our builds started failing because Drupal was returning files that no longer existed on the file system.
In the perfect world, these files are marked as Temporary by Drupal and then garbage collected by cron. However, the automatic mark as temporary is currently disabled by default. When these files are marked as temporary there's still a period of time they will exist on the file system based on the `temporary_maximum_age` setting.
See:
1. https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/file/file.module#L702
1. https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/file/src/FileUsage/FileUsageBase.php#L52 
In any case, I still think it would be best practice to filter out temporary files and it may be worth documenting this in …

chore(gatsby-source-drupal): Document filtering temporary files

---

packages/gatsby-source-wordpress/src/constants.ts
packages/gatsby-source-wordpress/src/gatsby-node.ts

For Gatsby v4 we need to move the code from `onPreInit` to `onPluginInit` to make sure global state as well as the error map is set properly. We also check to see if the current gatsby version supports the stable or unstable version of the new lifecycle node.

feat(gatsby-source-wordpress): Support on plugin init

---

scripts/release-next-major.js

When running it locally the spawned child process didn't find my `nvm` installation and versions and thus said that I didn't have any Node installed 😅 
This makes sure we have all `process.env` in the child process, too.

chore: Fix premajor script to find nvm

---

packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

Fixes https://github.com/gatsbyjs/gatsby/issues/26932 & related to an earlier issue https://github.com/gatsbyjs/gatsby/issues/22212
Fix some errors we've seen on Drupal sites from updates coming. Ideally
we iron out too whatever is triggering malformed/missing updates from coming in.
This will at least not break builds + give us some more info to track down
the deeper issue.

fix(gatsby-source-drupal): validate webhook bodies & updated node data

---

packages/gatsby/src/commands/build.ts

Send a message over IPC to anyone listening once engines are ready and written to disk 
https://app.clubhouse.io/gatsbyjs/story/37824/listen-to-log-action-when-engine-is-ready-and-prewarm

fix(gatsby): Send IPC message when engines are ready

---

packages/gatsby/src/utils/page-ssr-module/entry.ts

fix(gatsby): fix client-only-paths rendering in page engine

---

patches/v4/0-node-version.patch

With some of recent changes first patch wasn't applying cleanly (conflict in `packages/gatsby/src/utils/webpack.config.js`), so this just updates the patch

fix(patches): fix applying v4 patches

---

packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
packages/gatsby/src/bootstrap/redirects-writer.ts

Our warning was incorrect. Pages take precedence over redirects
[ch37028]

fix(gatsby): Update redirects warning

---

packages/gatsby-source-drupal/src/utils.js

fix(gatsby-source-drupal): guard against already deleted nodes

---

docs/docs/performance-tracing.md
packages/gatsby/src/commands/build.ts
packages/gatsby/src/query/file-parser.js
packages/gatsby/src/query/query-compiler.js
packages/gatsby/src/redux/save-state.js

Fix spans that don't nest correctly. 
Also [OpenTracing](https://opentracing.io/) is now merged into a new project called [OpenTelemetry](https://opentelemetry.io/) with wide support among vendors. This PR adds an example of how to make Gatsby's tracing work with this new standard.

fix(gatsby): fix nesting of tracing spans + add docs for OpenTelemetry

---

packages/gatsby/src/utils/webpack-utils.ts

Gatsby is supposed to remove locale files when bundling moment however this doesn't seem to be working as expected. This is because the arguments for the plugin that Gatsby uses for this changed for webpack 5, as shown in [the docs](https://webpack.js.org/plugins/ignore-plugin/).
This PR restores the optimisation by updating the plugin syntax to work with the latest version of webpack.

fix(gatsby): Don't bundle moment locale files

---

packages/gatsby-source-shopify/package.json
packages/gatsby-source-shopify/src/error-map.ts
packages/gatsby-source-shopify/src/gatsby-node.ts
packages/gatsby-source-shopify/types/interface.d.ts

For V4 Compatibility we need to set the Error map in `onPluginInit` while still setting the error map as normal if using v3.

feat(gatsby-source-shopify): v4 compatibility through onPluginInit

---

packages/gatsby/src/utils/page-data.ts

A follow-up for #33095. Turns out the fix in that PR was not enough. There are other code paths that could lead to a stack overflow when writing page-data files.

fix(gatsby): prevent stack overflow when writing page-data with DSG

---

patches/v4/2-gatsby-peerdeps.patch

Adding other peerdeps like gatsby-plugin-sharp to v4 constraints

chore: add other peerdeps to correct version Gatsby 4

---

packages/gatsby-plugin-gatsby-cloud/README.md

There's a difference between asterix and asterisk ;)

Fix typo: asterix -> asterisk

---

docs/docs/how-to/testing/visual-testing-with-storybook.md

Add brief note that components that use `StaticImage` are not supported in Storybook right now

chore(docs): Add note to Storybook guide about StaticImage

---

packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
packages/gatsby-source-drupal/src/__tests__/fixtures/article.json
packages/gatsby-source-drupal/src/utils.js

In this case, when trying to deleting a node's references nodes, we were
crashing if the referenced node had already been deleted.

fix(gatsby-source-drupal): handle edge case with deleting nodes

---

examples/functions-hello-world/src/pages/index.js

Since this example is for functions, this title is not really necessary.  A <title> should only be used inside a <head>, but adding react-helmet or dynamically setting the page title is not necessary here.

Remove <title> from inside <main>

---

packages/gatsby-plugin-gatsby-cloud/package.json
yarn.lock

Fixes when installing next version of gatsby-plugin-gatsby-cloud. It got copied inside a directory with the same name
```
error An unexpected error occurred: "ENOTDIR: not a directory, lstat '/home/circleci/project/cloud/gatsbyjs.com/src/dashboard/node_modules/gatsby-plugin-gatsby-cloud/components/index.d.ts/index.d.ts'".
```

chore(gatsby-plugin-gatsby-cloud): fix copy type file

---

docs/docs/mdx/getting-started.md

Fixed a link on [Getting Started with MDX](https://www.gatsbyjs.com/docs/mdx/getting-started/) that had been moved and was hitting a 404 ([original link](https://www.gatsbyjs.com/docs/how-to/routing/mdx/writing-pages)) to the [new page location](https://www.gatsbyjs.com/docs/mdx/writing-pages)
None

docs: Fix broken link on Getting Started with MDX page

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
packages/gatsby/webpack.d.ts
packages/gatsby/webpack.js
patches/v4/5-plugins-use-webpack-from-gatsby.patch

- chore(gatsby): add webpack export
- add patch file to move to gatsby/webpack
We want to make sure people are using the same webpack versions between plugins. This enables us to do so. It's similar to our graphql export

chore(gatsby): add webpack file to export same version

---

packages/gatsby/index.d.ts
packages/gatsby/src/bootstrap/index.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
packages/gatsby/src/redux/plugin-runner.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/services/create-pages.ts
packages/gatsby/src/services/initialize.ts
packages/gatsby/src/services/source-nodes.ts
packages/gatsby/src/state-machines/query-running/actions.ts
packages/gatsby/src/utils/page-data.ts

Found a number of activities that were missing their parentSpans so they were left orphaned when
examining traces.

fix(gatsby): Assign parentSpan to activities that were missing them

---

packages/gatsby/cache-dir/page-ssr/index.d.ts
packages/gatsby/src/commands/serve.ts
packages/gatsby/src/utils/get-server-data.ts
packages/gatsby/src/utils/page-ssr-module/entry.ts

This exposes custom headers set by `getServerData` to engine integration and actually allows setting those reponse headers in `gatsby serve`
[ch37799]

feat(gatsby): let serve use getServerData headers

---

integration-tests/gatsby-source-wordpress/__tests__/index.js
integration-tests/gatsby-source-wordpress/docker/wordpress/install-wp-graphql-plugins.sh

Fix error being swallowed in int tests and fix docker tests that were failing when running composer install in wp-graphql.

fix(gatsby-source-wordpress): fix failing test docker setup

---

packages/gatsby/package.json

Seems like I forgot to add it to the exports list

fix(gatsby): add webpack export to npm

---

packages/gatsby/src/bootstrap/load-plugins/validate.ts

We now bombard people with warnings when peerDeps are not matching. I understand that I might end up with problems but Gatsby doesn't have to yell at me
<details>
<summary>Log</summary>
```
.0.0-next.0 - It requires gatsby@^3.0.0-next.0
warn Plugin gatsby-remark-autolink-headers is not compatible with your gatsby version  
4.0.0-next.0 - It requires gatsby@^3.0.0-next.0
warn Plugin gatsby-remark-custom-blocks is not compatible with your gatsby version     
4.0.0-next.0 - It requires gatsby@^3.0.0-next.0
warn Plugin gatsby-remark-images is not compatible with your gatsby version
4.0.0-next.0 - It requires gatsby@^3.0.0-next.0
warn Plugin gatsby-remark-prismjs is not compatible with your gatsby version
4.0.0-next.0 - It requires gatsby@^3.0.0-next.0
warn Plugin gatsby-remark-smartypants is …
```

fix(gatsby): only show peerdep warnings outside of workers

---

packages/gatsby/src/commands/build.ts

Engines rely on current (temporary) `build-ssr` stage, so we should make sure it's compiled before potentially emitting `ENGINES_READY` message.
Note that this is rather hot-fix. Nicer fix is in https://github.com/gatsbyjs/gatsby/pull/33054 but it's a bit larger and also might need adjustments in more places
[ch38214]

fix: make sure we emit ENGINES_READY after build-ssr

---

.eslintrc.js
packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts
packages/gatsby/index.d.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/commands/develop-process.ts
packages/gatsby/src/commands/develop.ts
packages/gatsby/src/utils/start-server.ts
packages/gatsby/src/utils/worker/child/index.ts
packages/gatsby/src/utils/worker/pool.ts
types/gatsby-monorepo/global.d.ts

When multiple workers fetch the same file we end up with multiple requests to that file. We write to a seperate tmp file but the end result writes (fs.move) to the same file.
This can lead to corrupt files if other parts of the application are resolving it. This PR creates some hacky mutex implementation to make it only write once. It's still possible to write multiple tmp files.
1) Add global build id so mutex can be cleared per build.
2) When fetch is in progress save metadata into cache with worker id & build id
3) When fetch is complete and we're going to write - check cache again and only continue with worker from metadata. Other workers poll end result.
As an adittion I took the inFlight cache from https://github.com/gatsbyjs/gatsby/pull/30391 and implemented it as well to do less …

feat(gatsby-core-utils): add fetch mutex for PQR

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/utils/worker/pool.ts

This "handles" currently unhandled exceptions for running queries in workers step and add a note pointing to pqr feedback discussions. Functionally there should be no changes - process will still crash.
Couple of examples of what this change result in, depending on some scenarios:
- error thrown in main process: 
- error thrown in resolver (executed in worker):
- `reporter.panic(onBuild)` called in resolver (executed in worker):
The errors that originate from worker are far from ideal - specifically there are 2 separate errors shown, but making those single error (and not showing "worker exited before finishing task") would likely be quite big undertaking
[ch38130]

feat(pqr): print message pointing to pqr feedback if running queries throws

---

packages/gatsby/package.json
packages/gatsby/src/internal-plugins/bundle-optimisations/gatsby-node.js
packages/gatsby/src/utils/webpack.config.js
yarn.lock

Add `global.fetch` and `fetch` in gatsbys SSR bundle by default so you don't have to import it

feat(gatsby): provide fetch in ssr bundle by default

---

packages/gatsby/src/utils/eslint-rules/__tests__/limited-exports-page-templates.ts
packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts

This fixes fast-refresh related warnings showing up in develop once `getServerData` export is added. I covered same ones as we currently have in https://github.com/gatsbyjs/gatsby/blob/25378f15fdc1908b61db42ead3610db77a8976ed/packages/gatsby/src/redux/actions/public.js#L420-L429
There are probably a lot more variations possible, but at least most common ones should be handled

fix(eslint): don't warn about getServerData exports

---

packages/gatsby-cli/package.json
packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
packages/gatsby-cli/src/util/generate-page-tree.ts
yarn.lock

Adds a pages output with different page modes
INK-CLI:
YURNALIST:

feat(gatsby-cli): enable gatsby pages output

---

packages/gatsby/cache-dir/loader.js

https://github.com/gatsbyjs/gatsby/pull/33134 worked if pagePath matches "normalizedPath". This make sure we store it under normalize key when prewarming pageData cache.
~I do think this will cause troubles with `matchPath` cases, so PR is draft for now until I do discovery on that (I don't want make it worse!)~ Won't cause problems with `matchPath` because of `requires-writer` skipping non-ssg matchPath pages (and tested locally)
[ch38318]

fix(gatsby): fix hydration flicker on initial render of ssr page for more cases

---

docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.md
docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.mdx

Migration guide to v4 for source plugins.

chore(docs): create v4 source plugin migration guide

---

package.json

If people push canaries with a name that starts with a letter above n (next) we will not get the right version. We tell people to use alpha- but sometimes gets forgotten. By adding zz- we are more sure that we are last

chore: use zz-next as prerelease id to make sure it's last

---

packages/gatsby-cli/src/reporter/constants.ts
packages/gatsby-cli/src/reporter/loggers/ink/components/develop.tsx
packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
packages/gatsby-cli/src/reporter/redux/actions.ts
packages/gatsby-cli/src/reporter/redux/index.ts
packages/gatsby-cli/src/reporter/redux/internal-actions.ts
packages/gatsby-cli/src/reporter/redux/reducers/logs.ts
packages/gatsby-cli/src/reporter/redux/reducers/page-tree.ts
packages/gatsby-cli/src/reporter/redux/types.ts
packages/gatsby-cli/src/reporter/reporter.ts
packages/gatsby-cli/src/reporter/types.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/redux/reducers/index.ts

Fixes the reporter pageTree rendering by adding a private method. I've also removed some types as they are misleading

fix(gatsby-cli): fix pagetree global cli

---

docs/docs/reference/rendering-options/deferred-static-generation.md
docs/docs/reference/rendering-options/server-side-rendering.md

Split up into two parts so that overview on https://www.gatsbyjs.com/docs/reference/ is better + DSG might get another API in the future
- [Rendered DSG doc](https://github.com/gatsbyjs/gatsby/blob/v4-docs-ren-opt-ref/docs/docs/reference/rendering-options/deferred-static-generation.md)
- [Rendered SSR doc](https://github.com/gatsbyjs/gatsby/blob/v4-docs-ren-opt-ref/docs/docs/reference/rendering-options/server-side-rendering.md)
[ch38037]

chore(docs): Reference guides on SSR & DSG

---

docs/docs/reference/release-notes/migrating-from-v3-to-v4.md

Migration Guide for v4 beta.
[See rendered version](https://github.com/gatsbyjs/gatsby/blob/v4-docs-migration-guide/docs/docs/reference/release-notes/migrating-from-v3-to-v4.md)
Only ready before the actual GA release. Needs adaption then to e.g. rewrite `next` to `latest` etc.
[ch37888]

chore(docs): v4 Migration Guide

---

packages/gatsby/src/schema/graphql-engine/print-plugins.ts

**This issue is for the Gatsby 4 beta.**
This PR fixes DSG-enabled builds when a plugin's options contain `null` at certain depths. It adds an additional `value !== null` check.
TypeScript did not pick up this error since `value` is typed as `any`.
https://v4.gatsbyjs.com/docs/how-to/rendering-options/using-deferred-static-generation/
https://github.com/gatsbyjs/gatsby/issues/33226

fix(gatsby): allow null plugin option values on build

---

integration-tests/cache-resilience/gatsby-node.js

This just changes hacky snapshots that are generate with test site to be compatible with `lmdb-cache` (vs previous legacy cache).

test(cache-resilience): adjust for v4/lmdb

---

packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
packages/gatsby-source-drupal/src/__tests__/fixtures/image-gallary.json
packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json
packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

In https://github.com/gatsbyjs/gatsby/pull/33079 I thought that Drupal entities had to have an `attributes` field. This wasn't the case (paragraph entities often don't) so backed that out and added tests for fetching/updating entities without an `attributes` field.

fix(gatsby-source-drupal): some entities don't have attributes so add tests with this

---

packages/gatsby/package.json
yarn.lock

LMDB tests were failing in CircleCI because CircleCI was using an old version of `glibc`.
https://github.com/DoctorEvidence/lmdb-store/issues/87

chore(gatsby): upgrade lmbd to 1.6.8

---

packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts

Do the page-tree yurnalist log in one print, instead of multiple ones to make sure cloud renders it correctly

fix(gatsby-cli): make sure to put all yurnalist logs in one log

---

starters/blog/gatsby-config.js
starters/default/gatsby-config.js

On PTO I read https://css-tricks.com/meta-theme-color-and-trickery/ and remembered a discussion on my repo: https://github.com/LekoArts/gatsby-themes/discussions/643
In order to not force every website made with Gatsby to have a purple tab bar on iOS/Safari 15 we can remove it as it's optional: https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color

chore(starters): Make `theme_color` optional

---

packages/gatsby-cli/src/reporter/prepare-stack-trace.ts

With https://github.com/gatsbyjs/gatsby/pull/33054 our handling for printing codeframe on html rendering errors somewhat broke - it only printed codeframe when it originated from entry of `render-page` but was missing those when it originated from split template files.
This hacks a bit to handle all `.map` files in page renderer directory and test all of them until it finds a match. I tried to keep "public" api of related functions untouched to not cause potential compat issues with previous versions etc given that changes had to happen in `gatsby-cli` and not core `gatsby` package

fix(gatsby): fix codeframe generation for html errors

---

jest.config.js

https://github.com/kriszyp/weak-lru-cache/commit/4f3a59da6167a54fb2064701a39736335d005c31 is not handled by jest module resolution (both on version we use in repo as well as in latest jest), so this adds a workaround for it
Changing just jest.config file doesn't actually result in running tests - so here's example workflow with those changes - https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/74106/workflows/6225c8e5-ca73-442d-83ee-e0b1f452e290 (`unit_tests_node14_lmdb_store` is passing there)

fix(tests): fix `unit_tests_node14_lmdb_store` tests

---

packages/gatsby-source-contentful/README.md

Hi everyone! 
First of all, I want to thank you and congratulate you on the amazing job you've been doing through these years. I love Gatsby and the way it's evolving 💜. Also sending hugs and high-fives cause they're great conversation starters.
I was reading the documentation about [Contentful + Gatsby integration](https://www.gatsbyjs.com/plugins/gatsby-source-contentful/) and I've spotted a dummy issue in the documentation, where the aim of this dummy PR is trying to fix.
In the [#rendering](https://www.gatsbyjs.com/plugins/gatsby-source-contentful/#rendering) section there's a mistake; the destructured property is  `bodyRichText` while in the `renderRichText` function it's being lifted `richTextField` where it should be `bodyRichText`. So:
```jsx
import { BLOCKS, MARKS } from …
```

chore(gatsby-source-contentful): Fix RichText example

---

packages/gatsby/index.d.ts

`getNode` may return undefined if the given id is not found (could be due to wrong id or node got deleted whatsoever).
Also see the source https://github.com/gatsbyjs/gatsby/blob/302bac57037b0f294ad10c7a2068ca8f7bfe5b3f/packages/gatsby/src/datastore/index.ts#L17-L18

fix(gatsby): correct the definition for getNode

---

packages/gatsby-telemetry/src/__tests__/telemetry.ts

Cleanup gatsby-telemetry package.json

chore(gatsby-telemetry): remove deps that are global

---

docs/docs/creating-a-source-plugin.md

- `mediaType` isn't required (and regardless, this isn't html)
- `content` should only be set if transformers need access to the raw content to transform

fix(docs): Remove unneeded/wrong fields from createNode example

---

docs/docs/building-an-ecommerce-site-with-shopify.md
packages/gatsby-source-shopify/README.md

There are some inconsistencies across our shopify documentation. I think we should use the `gatsby-starter-shopify` way of doing things as the source of truth and make our other documents reflect that experience.

fix(gatsby-source-shopify): inconsistencies in shopify docs

---

packages/gatsby-plugin-feed/README.md
packages/gatsby-plugin-feed/src/plugin-options.js

Solve TODOs
Updated description + improved example.
Already added a note about this in the v3 => v4 migration guide.
[ch38700]

gatsby-plugin-feed: Make `feeds` & `serialize` required

---

docs/docs/building-an-ecommerce-site-with-shopify.md

This will make it clearer for users to ensure the  `Read product tags` and `Read customer tags` boxes are checked on Shopify. If these boxes are not checked, the site won't build.

chore(docs): Improve Shopify guide

---

packages/gatsby-source-wordpress/src/constants.ts
packages/gatsby-source-wordpress/src/gatsby-node.ts
packages/gatsby-source-wordpress/src/utils/run-steps.ts

The gatsby-node for the WP plugin was meant to be a jumping off point that didn't include any logic. This PR refactors that file so that continues to be the case. It also allows us to reuse this first-supported-api-name logic for any node API in the future if framework adds new node API's.

chore(gatsby-source-wordpress): refactor logic for supported node api names

---

integration-tests/gatsby-source-wordpress/__tests__/index.js
packages/gatsby-source-wordpress/src/constants.ts
packages/gatsby-source-wordpress/src/gatsby-node.ts
packages/gatsby-source-wordpress/src/steps/set-gatsby-api-to-state.ts
packages/gatsby-source-wordpress/src/utils/run-steps.ts

I based this on #33296 because I thought they were related. Turns out not at all! In any case we should merge that PR first.

fix(gatsby-source-wordpress): fix refresh builds error

---

packages/gatsby/src/datastore/__tests__/nodes.js
packages/gatsby/src/query/__tests__/data-tracking.js
packages/gatsby/src/redux/__tests__/nodes.ts
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/schema/infer/__tests__/infer.js

Remove warnings added in https://github.com/gatsbyjs/gatsby/pull/29245 & https://github.com/gatsbyjs/gatsby/pull/29205
Already noted in migration guide
[ch38692]
[ch38693]

gatsby: Remove deprecation warnings for touchNode/deleteNode

---

packages/gatsby-transformer-remark/README.md
packages/gatsby-transformer-remark/src/gatsby-node.js

- Remove `commonmark` and `pedantic` option
- Improve README

feat(gatsby-transformer-remark): Remove two obsolete options & improve README

---

packages/gatsby-source-graphql/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
packages/gatsby-source-graphql/src/gatsby-node.js

This PR updates `gatsby-source-graphql` to support Gatsby 4. The following changes were made:
- Move `addThirdPartySchema` from `sourceNodes` to `createSchemaCustomization`
- Add `pluginOptionsSchema` to validate options for all Gatsby Node APIs
Without this PR, `gatsby-source-graphql` fails to build when using Gatsby 4 due to the third-party schema not being available in time.
Note: This does not address supporting DSG. It simply fixes existing functionality.
- https://www.gatsbyjs.com/plugins/gatsby-source-graphql/
- https://www.gatsbyjs.com/docs/third-party-graphql/
Updates to the existing documentation are not necessary. Functionality and the plugin options API are unchanged.
None

fix(gatsby-source-graphql): support Gatsby 4

---

packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

Big thanks to @kszot-ref for finding the root problem of the issue he was noticing with his Drupal/Gatsby site in https://github.com/gatsbyjs/gatsby/pull/33285#issuecomment-928921306.
Fixes #33284
The bug is fairly subtle. The plugin currently updates backreferences on nodes by
directly mutating them. This means that for already existing nodes, Gatsby wasn't able
to tell that they'd changed because when it tried to compare the "new" version of the node
with the "old" version, they were the same because we'd mutated the old node object directly.
The fix is to always do a deep clone of the node object before making modifications to it
so Gatsby knows the node has changed and re-runs any pages depending on it.
I wonder now how common this issue is in other source plugins.

fix(gatsby-source-drupal): Clone nodes before adding back references so Gatsby knows the node has changed (so knows to re-run queries)

---

packages/gatsby/index.d.ts

Fixes #33318, and opportunistically adds a TSDoc for `useStaticQuery`.
Note this isn't just narrowing a type; it's actually fixing an incorrect `void` type, which is why I called this a bug.
`toString()` is there to offer typesafe access to the static query hash, like so:
```diff
-console.debug(`Static query ID: ${staticQuery as unknown as string}`);
+console.debug(`Static query ID: ${staticQuery.toString()}`);
```
Otherwise the only permissible use of `StaticQueryDocument` is to provide it to `useStaticQuery` (or `StaticQuery`).
LMK if you think I missed anything here.

chore(gatsby): Fix static query types, document useStaticQuery

---

packages/gatsby/src/query/index.ts
packages/gatsby/src/utils/page-data.ts

We've noticed significant memory usage by some sites with LMDB store enabled (even without parallel query running).
After investigating this, it turned out that there is huge pressure on the microtask queue of the event loop that essentially blocks ticks of its task queue. This in turn prevents `lmdb-store` cache from starting persisting temporary `page-data` results that are accumulated in memory and eventually cause OOMs. 
This happens for sites having very fast queries with basically no IO and no event loop ticks. LMDB read operations are sync, so there is no IO there (at least in terms of NodeJS). GraphQL resolvers may return promises but those never actually perform any IO tasks. And so event loop gets stuck in a microtask queue and has no chance to proceed to the task queue. …

fix(gatsby): unblock event loop when running queries

---

packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts

Title says it all for this one.

fix(gatsby): Fix typos in build output

---

packages/gatsby/src/utils/flags.ts

Make sure DEV_SSR is not turned on when using FAST_DEV

fix(gatsby): remove DEV_SSR from FAST_DEV

---

packages/gatsby-source-contentful/README.md

Added explicit statement for required `contentful_id` field when querying for references in rich text.  

chore(gatsby-source-contentful): Improve README on rich text ref

---

packages/gatsby/src/schema/types/built-in-types.ts

This is a follow-up for #33319. Disables inference for other internal types. Still keeps inference for `File` type as it will be a bigger lift - requires changing all user plugins to incorporate `@childOf` directive for children types.
Also still keeps inference for `Site` type - it is inexpensive and disabling inference for it means adding type definition manually to basically every site out there.

feat(gatsby): disable inference for internal types

---

packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts

In `watch` mode rewriting those files without changes causes unnecesary recompilations, this just prevents them if nothing actually changed

fix(gatsby): don't re-write chunk-map.json and webpack.stats.json without changes

---

packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
packages/gatsby-source-drupal/src/__tests__/fixtures/image-gallary.json
packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json
packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

Several changes:
- better logging for fastbuild updates (most useful is it links to URL of changed entity)
- skip running fastbuilds sync API call if `lastFetched` isn't set as this call is a) pointless as we know we need to do a full-fetch and b) pretty expensive.
- only call touchNodes on the first call to sourceNodes as Gatsby (currently) doesn't update that information for subsequent calls so we can save some time there.
- more tests for relationships updating code

feat(gatsby-source-drupal): port hot-fixes for Drupal/Gatsby customer to package

---

packages/gatsby-plugin-image/src/gatsby-node.ts
packages/gatsby-plugin-image/src/resolver-utils.ts
packages/gatsby-source-shopify/src/gatsby-node.ts
packages/gatsby-source-shopify/src/resolve-gatsby-image-data.ts

This PR allows Gatsby apps to use more than one source that uses [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/).
For example, users can use `gatsby-source-prismic` and `gatsby-source-shopify` together on the same app with this PR.
Without this PR, using multiple sources that use gatsby-plugin-image results in the following error during Gatsby's bootstrap phase:
```
[ Truncated log ]
success Checking for changed pages - 0.001s
success source and transform nodes - 12.721s
ERROR
Missing onError handler for invocation 'building-schema', error was 'Error: Schema must contain uniquely named types but contains multiple types named "GatsbyImageLayout".'.
Stacktrace was 'Error: Schema must contain uniquely named types but contains multiple types named …
```

feat(gatsby-plugin-image): support multiple sources using gatsby-plugin-image

---

.circleci/config.yml
integration-tests/gatsby-source-wordpress/gatsby-config.js
integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts

Backporting #33256 to the 3.14 release branch
(cherry picked from commit 1d8ebb2588e3549105305000dd5d6572396b1f0e)
This PR is required to fix tests failing in 3.14 branch

chore: Fix tests for WordPress, Contentful & update CircleCI (#33256)

---

docs/docs/reference/config-files/gatsby-config.md
packages/gatsby/index.d.ts
packages/gatsby/src/joi-schemas/joi.ts
packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.ts.snap
packages/gatsby/src/redux/actions/__tests__/internal.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
packages/gatsby/src/utils/babel-loader-helpers.js
packages/gatsby/src/utils/babel-loader.js
packages/gatsby/src/utils/did-you-mean.ts
packages/gatsby/src/utils/eslint-config.ts
packages/gatsby/src/utils/flags.ts
packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.ts
packages/gatsby/src/utils/merge-gatsby-config.ts
packages/gatsby/src/utils/webpack-utils.ts

Follow up to #32972.
Allow automatic react runtime to be enabled through config, the current workaround is to start manually setting babelPlugins and eslint config. There's going to be very few people doing this for something that is supposed to work out the box
Fixes #28657
Fixes #30373

feat(gatsby): Add JSX Runtime options to `gatsby-config.js`

---

.circleci/config.yml

Adding GATSBY_CPU_COUNT to make sure circleci doesn't use to much memory and CPU cores. The default machine only has 2 cores

chore: add GATSBY_CPU_COUNT to tests

---

docs/docs/reference/config-files/gatsby-config.md

https://github.com/gatsbyjs/gatsby/discussions/33798 uncovered that the doc needs an update as `id` now is `jsonId`/`yamlId` instead

chore(docs): Update mapping node types after v4 breaking changes

---

packages/gatsby-source-wordpress/src/supported-remote-plugin-versions.ts

We just published WPGatsby v2.0.0 and now I'm realizing that `gatsby-source-wordpress` has a hardcoded check to only work for WPGatsby v1 right now.

feat(gatsby-source-wordpress): Update supported-remote-plugin-versions.ts

---

packages/gatsby/index.d.ts
scripts/check-ts.js

We sadly can't really catch those things in CI at the moment as we have to use `skipLibCheck` for `gatsby` as our webpack types are messed up (we have webpack 4 types in lock file due to some outdated libs/type libs). You can see this by running `npx tsc packages/gatsby/index.d.ts --noEmit` in the repo root
So for now we just manually fix this
Fixes https://github.com/gatsbyjs/gatsby/issues/33747

chore(gatsby): Fix index.d.ts file

---

e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
packages/gatsby/src/utils/eslint-rules/__tests__/limited-exports-page-templates.ts
packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts

Don't warn when someone uses `config` in page templates.
[ch40832]

fix(gatsby): Don't warn about `config` in ESLint

---

e2e-tests/production-runtime/cypress/integration/1-production.js
e2e-tests/production-runtime/gatsby-node.js
e2e-tests/production-runtime/src/templates/search-param-render.js
packages/gatsby/cache-dir/production-app.js

We were missing query params when redirecting to canonnical path
Fixes #33787

fix(gatsby): preserve query params on pages without trailing slashes

---

integration-tests/structured-logging/__tests__/to-do.js

The previous PR #33664 fixed several issues with `integration_tests_structured_logging` but introduced another issue - we wait too long before trying to terminate the process in `develop` tests. We wait for `5 seconds` and sometimes it is enough to complete `develop` session (and get the `SUCCESS` event prematurely).
We probably don't need to wait for those additional 5 seconds at all after #33664 - we can just wait for the first IPC event and send SIGTERM right after it.
P.S. I re-ran tests 4 times on this PR: no flaky occurrences so far

chore: make structured logs tests less flaky

---

packages/gatsby/src/utils/worker/child/index.ts

feat(gatsby): let Gatsby clear the module cache in workers for `render-page.js`

---

rfcs/text/0009-telemetry.md

I found a few issues in the 0009-telemetry.md file which have been fixed.

chore(docs): fix issues in 0009-telemetry RFC

---

packages/gatsby-source-drupal/src/gatsby-node.js

Fixes issue where params such as api-key were not added correctly to the API URL.

fix(gatsby-source-drupal): Add missing `params` from options to API urls

---

packages/gatsby/index.d.ts

Added `unstable_createNodeManifest` to `Action` types so it can be accessed as a property in plugin code.

fix(gatsby): TS type for `unstable_createNodeManifest` action 

---

docs/docs/creating-and-modifying-pages.md

Update createPages documentation to reflect use of the ownerNodeId parameter for content sync. 
Approval requires [#33866](https://github.com/gatsbyjs/gatsby/pull/33866) to be merged first.

chore(docs): Update `createPage` documentation w/ Content Sync

---

packages/gatsby/src/redux/actions/public.js

Updates the public action documentation for `unstable_createNodeManifest` as the current one is incorrect: https://www.gatsbyjs.com/docs/reference/config-files/actions/#unstable_createNodeManifest

fix(gatsby): API doc about `unstable_createNodeManifest`

---

packages/gatsby-plugin-google-analytics/README.md

Updates the documentation to reflect which of the plugins we recommend between gatsby-plugin-google-analytics and  gatsby-plugin-gtag
https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/

chore(gatsby-plugin-gatsby-google-analytics): Highlight the plugin we recommend  

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

We currently do not retry on certain status codes and network errors. This can cause issues when building projects that use a lot of remote assets that need to be fetched.
This replaces #30391.
Status:

feat(gatsby-core-utils): Add retry on HTTP status codes to `fetchRemoteFile`

---

packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
packages/gatsby-source-drupal/src/__tests__/fixtures/webhook-body-multiple-nodes.json
packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

Fix issue reported by @jstramel where when he created a new page w/ a new media entity, the media entity wouldn't be attached to the page node in Gatsby as it wasn't yet created.
We solve this by creating all new nodes before we update node relationships.

fix(gatsby-source-drupal): Ensure all new nodes are created before creating relationships

---

docs/docs/reference/release-notes/migrating-from-v3-to-v4.md

Add a note about removal of `SitePage.context`. Requested in https://github.com/gatsbyjs/gatsby/discussions/32860#discussioncomment-1617559

chore(docs): mention `SitePage.context` removal in v4 migration guide

---

e2e-tests/contentful/cypress/integration/gatsby-plugin-image.js
e2e-tests/contentful/src/pages/gatsby-plugin-image.js
packages/gatsby-source-contentful/src/gatsby-plugin-image.js
packages/gatsby-source-contentful/src/image-helpers.js
packages/gatsby-source-contentful/src/schemes.js

As we can see on https://www.contentful.com/developers/docs/references/images-api/#/reference/changing-formats/image-format Contentful now supports avif on the API. This will add support for avif images.

feat(contentful): modifying schemes to add support for AVIF images

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

There are some issues with downloads, especially if PQR worker did download a file, and later main process attempts to download it (it will receive `undefined` instead of filepath)
In particular after file was downloaded by a worker (and therefore there is `cacheEntry` for given url already) and `fetchRemoteFile` is called in MAIN process for same url https://github.com/gatsbyjs/gatsby/blob/a67d339ff87ad0db5a519594ad1ecc8afd1c5be7/packages/gatsby-core-utils/src/fetch-remote-file.ts#L234-L246 will return undefined because of https://github.com/gatsbyjs/gatsby/blob/a67d339ff87ad0db5a519594ad1ecc8afd1c5be7/packages/gatsby-core-utils/src/fetch-remote-file.ts#L102-L111
I see 2 options here:
- (one used right now in PR) use cache locks for all processes (main and workers)
- just wrap "second" …

fix(gatsby-core-utils): fix fetchRemoteFile when called in main process after being called in worker

---

packages/gatsby/src/utils/__tests__/node-manifest.ts
packages/gatsby/src/utils/node-manifest.ts

Writing node manifest files is failing on Windows and this provides a fix for that.
Resolves #33743

fix(gatsby): ensure that writing node manifests to disk does not break on Windows

---

docs/docs/recipes/pages-layouts.md

Currently links to `Part 7: Add Dynamic Images from Data`
This change updates the linked page to `Part 6: Create Pages Programmatically` to match the link description

fix(docs): incorrect link "programmatically creating pages from data"

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

Make sure the file we write has the original filename and digest instead of worker appended one.

fix(gatsby-core-utils): handle 304 correctly between builds

---

packages/gatsby-source-graphql/src/fetch.js

require the default function from node-fetch.
This fixes the bug the `gatsby-source-graphql` failed to DSG in production.
Caused by the issue in node-fetch when bundled with webpack: node-fetch/node-fetch#450
Fixes https://github.com/gatsbyjs/gatsby/issues/33906

fix(gatsby-source-graphql): Use default export from node-fetch

---

packages/gatsby-source-graphql/README.md

As it doesn't yet support inc builds or preview.
This trips people up some time and we should be clear about the plugin's limitation.

chore(gatsby-source-graphql): warn people that source-graphql is slow for larger sites

---

.circleci/config.yml

Cleaning up our CircleCI config a little bit + updates.
- Update Node from 14.17.0 to 14.18.1
- Remove ignores for `/blog/` since there are no blog contributions anymore to this repo
- Remove `_lmdb_store` test as the `node14` runs by default now. Once we work on indexes again we'll need to update the node14 test one (added a comment)
- remove i18n sync actions since this project is on hold for a while now (and it fails regularly)

chore: CircleCI updates

---

packages/gatsby-source-wordpress/src/gatsby-browser.ts

importing the default from react-dom removes the warning.
```
warn ./node_modules/gatsby-source-wordpress/dist/gatsby-browser.js Attempted import error: 'createRoot' is not exported from 'react-dom' (imported as 'ReactDOM').
```
fixes #33990
fixes [sc-41206]

fix(gatsby-source-wordpress): fixes createRoot not exists warning

---

packages/gatsby-source-wordpress/src/gatsby-browser.ts

Gatsby-plugin-image only needs to hydrate in develop mode on first occurence. On production we inject a small code snippet to do the first hydration outside of React.
Fixes #33985

fix(gatsby-source-wordpress): always hydrate in develop for images

---

packages/gatsby/index.d.ts
packages/gatsby/src/utils/api-node-helpers-docs.js

add the `getCache` helper to the `NodePluginArgs` interface
https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#getCache
Fixes  #33963

chore(gatsby): add `getCache` helper to `NodePluginArgs`

---

packages/gatsby/index.d.ts

When `getServerData is used for SSR a `serverData` prop is provided but is missing from the TypeScript definition, this PR adds it in.

chore(gatsby): Add `getServerData` to PageProps type

---

packages/gatsby-plugin-manifest/src/gatsby-node.js

Currently Gatsby is adding a `cacheDigest` property to the root of the generated webmanifest.
It is an invalid property and triggers an error when running a PWA test on Gatsby projects.
See:
See https://webhint.io/docs/user-guide/hints/hint-manifest-is-valid/?source=devtools.

fix(gatsby-plugin-manifest): Delete `cacheDigest` from generated webmanifest

---

packages/gatsby/cache-dir/static-entry.js

Uses new `renderToPipeableStream` - https://github.com/reactwg/react-18/discussions/104. Old api got removed in favor of this one as it's more simple and works with "pipe"
Fixes #34002

fix(gatsby): use new `renderToPipeableStream`

---

packages/gatsby-source-shopify/package.json

Fix incorrect peerDeps. Added an OR to not make this a breaking change.
Fixes https://github.com/gatsbyjs/gatsby/issues/34039

fix(gatsby-source-shopify): Correct `gatsby-plugin-image` peerDep

---

packages/gatsby-plugin-nprogress/README.md
packages/gatsby-plugin-nprogress/package.json
packages/gatsby-plugin-nprogress/src/__tests__/gatsby-browser.js
packages/gatsby-plugin-nprogress/src/gatsby-browser.js
yarn.lock

Replaces nprogress module with accessible-nprogress module to make gatsby-plugin-nprogress more accessible.
If you used the `template` option you might need to adjust your plugin options to now use `className="bar"`, see: https://github.com/nmackey/accessible-nprogress#template
Fixes [#33875](https://github.com/gatsbyjs/gatsby/issues/33875)

feat(gatsby-plugin-nprogress): Replace `nprogress` with `accessible-nprogress`

---

packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
packages/gatsby-cli/src/reporter/redux/internal-actions.ts
packages/gatsby-cli/src/reporter/redux/reducers/logs.ts
packages/gatsby-cli/src/reporter/redux/types.ts

This removes memory "leak" when using non-ink logger (in particular in CIs)
Memory usage of same site continously refreshing (blue with this change, orange is current "baseline"):
All credits for the find goes to @vladar 
Note that with Ink logger and this PR we will still retain logs. This PR focuses on long running CI usage so scope of change is minimized for that. For Ink case there could be refactor to use https://github.com/vadimdemedes/ink#writedata instead of `<Static>` (or maybe play with `<Static>` and see if we can remove/consume messages after they are rendered)

perf(gatsby-cli): dont retain logs in memory in non-ink loggers

---

packages/gatsby-source-drupal/src/gatsby-node.js

fixes https://github.com/gatsbyjs/gatsby/issues/34034
https://github.com/gatsbyjs/gatsby/pull/33668 added a timeout of 15s so if API requests stall, we catch those and retry them. But in practice, this doesn't seem long enough as some requests hit the timeout consistently. We'll switch the timeout to 30s to see if this resolves the issue.

fix(gatsby-source-drupal): Bump timeout from 15s to 30s to avoid unnecessary API request timeouts

---

docs/docs/how-to/local-development/troubleshooting-common-errors.md

Update the resolution approach fallback approach in line with Webpack 5 and its new interface
[Webpack's doc on resolve](https://webpack.js.org/configuration/resolve/#resolvefallback)

chore(docs): Update webpack fs resolution

---

packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts

Removed ink & inquirer from the engine bundles. Reduced page-engine/query-engine by 1.5mb and small perf win while bundling (3s) on hello-world example
If we want to gain more we will have to look at gatsby-cli as there are many unnecessary deps

perf(gatsby): remove unnecessary code from engines

---

packages/gatsby-cli/src/reporter/redux/diagnostics.ts
packages/gatsby-cli/src/reporter/redux/index.ts

Our watchdog messages were missing almost all activities (except `build`) and therefore causing quite a bit of confusion related to debugging stuck builds.
Reason for failing was that we used original `gatsby-cli` redux store, which we later swap out for `gatsby` store but diagnostic never swapped stores and therefore using stale data to print messages

fix(gatsby-cli): fix stuck warnings not showing all the in-progress activities

---

package.json
yarn.lock

The resolutions for `theme-ui` and `csstype` were added in https://github.com/gatsbyjs/gatsby/pull/23734 and are obsolete now with the removal of `gatsby-admin`.

chore: Remove obsolete resolutions

---

packages/gatsby-source-contentful/README.md

This should reduce confusion in the docs of gatsby-source-contentful.
See https://github.com/gatsbyjs/gatsby/issues/33323#issuecomment-979522146
Fixes https://github.com/gatsbyjs/gatsby/issues/33323

chore(gatsby-source-contentful): Add note to Rich Text docs

---

integration-tests/node-manifest/__tests__/create-node-manifest.test.js
integration-tests/node-manifest/gatsby-node.js
integration-tests/node-manifest/package.json
packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/index.d.ts
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/reducers/node-manifest.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/__tests__/node-manifest.ts
packages/gatsby/src/utils/node-manifest.ts
packages/gatsby/src/utils/page-data-helpers.ts
packages/gatsby/src/utils/page-data.ts

For the next iteration of `unstable_createNodeManifest`
- We want to control the logic of how manifests are created (in terms of time updatedAt)
- abstract away some of the logic that sourcePlugins were initially concerned of.
- Make it more performant by removing hashing of the pageData and instead append the `manifestId` to the `pageData` when we initially create the page data.
- Reduce noise from logs, by default we log once for each "Warning type" rather than for each node. A user can enable verbose logs to see logs from each node.
- record the time it takes to process all manifests
The api will now be called like so
```javascript
actions.unstable_createNodeManifest({
manifestId: string,
node: Node,
updatedAtUTC?: string | number,
maxDaysOld?: number,
})
```
`updatedAtUTC` and …

feat(gatsby): Node manifest api v2

---

packages/gatsby/src/utils/node-manifest.ts
packages/gatsby/src/utils/page-data.ts

Because of how pending page data writes are flushed on Gatsby Cloud, the latest `createNodeManifest` changes don't work with inc-builds without this change

fix(gatsby): node manifests v2 inc builds

---

packages/gatsby-transformer-json/src/gatsby-node.js

> What changed with v4 is we now write data to LMDB which is more costly than writing to memory. The sync forEach loop doesn't allow LMDB to flush data to disk meaning in progress changes accumulate. Switching to async solves as does using e.g. process.nextTick to let the event loop run through again.
Closes #34081

fix(gatsby-transformer-json): Fix high memory consumption

---

packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/schema.js

First commit add a test case that fails with:
```
Error: Cannot get type name from ThunkComposer({ _thunk: [function ], _typeName: "CustomInterface" })
at getComposeTypeName (/home/circleci/project/node_modules/graphql-compose/lib/utils/typeHelpers.js:199:13)
at ObjectTypeComposer.hasInterface (/home/circleci/project/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1047:58)
at ObjectTypeComposer.addInterface (/home/circleci/project/node_modules/graphql-compose/lib/ObjectTypeComposer.js:1052:15)
at forEach (/home/circleci/project/packages/gatsby/src/schema/schema.js:377:56)
at Array.forEach (<anonymous>)
at mergeTypes (/home/circleci/project/packages/gatsby/src/schema/schema.js:377:26)
at forEach (/home/circleci/project/packages/gatsby/src/schema/schema.js:1256:7)
at Array.forEach …
```

fix(gatsby): create placeholder interface if it doesn't exist yet when merging SDL type
