gatsbyjs/gatsby

docs/docs/building-an-ecommerce-site-with-shopify.md

As a default my new project didn't have read_products checked in the Admin API .

chore(docs): Add missing permission for Shopify Admin API

---

packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
packages/gatsby-plugin-sitemap/src/gatsby-node.js

Fixes pathPrefix handling correctly with gatsby-plugin-sitemap.
The generated paths inside the sitemap are prefixed with `basePath`and the sitemap URLs are prefixed with assetPrefix + pathPrefix like we expect
Fixes #34010
Fixes [sc-42532]

fix(gatsby-plugin-sitemap): fix pathPrefix handling

---

packages/gatsby-source-wordpress/src/steps/preview/index.ts

For Node Manifest API V2, we want Gatsby to handle which nodes get manifests created for them. Wordpress is different however because we collect manifestIds on the WP backend and send them when data is previewed. So we create a manifest for any content that is previewed already, we don't need to worry about an updatedAt time. However we do need to remove the logs that inform you which manifests are created bcause the new API handles that.

chore(gatsby-source-wordpress): remove log for manifests created

---

docs/docs/sourcing-from-sanity.md

Simple PR to remove reference to an outdated Gatsby/Sanity example site.

chore(docs): remove reference to outdated example site

---

packages/gatsby-plugin-manifest/src/__tests__/gatsby-browser.js
packages/gatsby-plugin-manifest/src/gatsby-browser.js
packages/gatsby-plugin-manifest/src/get-manifest-pathname.js

Apps built with `--pathPrefix` need to consider `pathPrefix` when getting localized manifest from plugin config. This PR address that
https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/#localization-configuration
fixes #33965

fix(gatsby-plugin-manifest): consider path prefix when getting localized manifest

---

packages/gatsby-source-contentful/package.json
packages/gatsby-source-contentful/src/normalize.js

Remove logic that creates manifests depending on the updatedAt time, the new manifest API accepts the updatedAt time and abstracts that away from source plugins having to worry about that.

feat(gatsby-source-contentful): Update contenful nodemanifest api

---

packages/gatsby-source-drupal/package.json
packages/gatsby-source-drupal/src/gatsby-node.js
packages/gatsby-source-drupal/src/utils.js

This PR adds support for node manifest api 2.0 as well as creating manifests on cold builds. You can read about the updates here https://github.com/gatsbyjs/gatsby/pull/34024
We default to creating manifests for content up to 30 days old but this can be changed with an env var `NODE_MANIFEST_MAX_DAYS_OLD`

feat(gatsby-source-drupal): update drupal to use latest nodemanifest api

---

docs/docs/how-to/performance/improving-site-performance.md

Clarify a note that adding a script via html.js is the same as using onPreRenderHTML.

Clarify html.js vs. onPreRenderHTML

---

packages/gatsby-source-filesystem/src/create-remote-file-node.js

fastq implementation uses strict equality for queue `concurrency` parameter: https://github.com/mcollina/fastq/blob/3b9f23d8bcf2d9399fc2095d77ded7285c35128a/queue.js#L99
That's why `process.env.GATSBY_CONCURRENT_DOWNLOAD` must be converted to integer. If parseInt returns NaN fallback user value to 0 to throw validation error on queue initialization.

fix(gatsby-source-filesystem): Ensure fastq concurrency parameter of the correct type

---

docs/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options.md

There was a missing comma on an object in one of the code examples. (Line 77)

Add missing Comma to Plugin Options page

---

packages/gatsby/src/query/query-runner.ts

There was some confusion on Discord about what this warning means and whether it's a problem to be fixed.
I reworded the warning slightly to a) be clear what "long" means (15s) and b) be clear it's not necessarily a problem and if it is a problem, an indication of what it could be.

fix(gatsby): Reword warning about long running queries

---

docs/docs/reference/built-in-components/gatsby-link.md

Remove note that you can't use navigate w/ query params or hashes and show it imported from gatsby.
Not sure why docs say you specifically *can't* do this, when it works for me and the documented way does not 😅 
Fixes #34216

chore(docs): Update navigate helper w/ query params

---

packages/gatsby-plugin-emotion/package.json
packages/gatsby-plugin-emotion/src/__tests__/gatsby-node.js
packages/gatsby-plugin-emotion/src/gatsby-node.js

Detect user's gatsby config of `jsxRuntime` and set right babel config for `emotion`
N/A
Fixes #33936
cc @wardpeet

feat(gatsby-plugin-emotion): Use correct babel preset with `jsxRuntime`

---

docs/docs/how-to/previews-deploys-hosting/path-prefix.md
packages/gatsby/index.d.ts
packages/gatsby/src/utils/api-node-docs.ts
packages/gatsby/src/utils/api-node-helpers-docs.js

Before now, the documentation does not explain `basePath` at all, It doesn't also explain what happens when you combine both `assetPrefix` and `pathPrefix` in your `gatsby-config.js`. This PR addresses that with more usage examples, also adds a missing type (`basePath`)
Fixes #34175
[sc-42991]

chore(gatsby): Update documentation around pathPrefix and assetPrefix combination

---

packages/gatsby/index.d.ts
packages/gatsby/src/utils/api-node-helpers-docs.js

Builds on dotcom are still failing after #34234. I haven't confirmed this locally, but it looks like these new code comments are  not being parsed correctly in MDX

Hotfix: Add backticks to inline code comments

---

packages/gatsby-plugin-offline/package.json

Replaces `cpx` with `cpy-cli` since the former is unmaintained and uses an ancient chokidar & fsevents dependency. No `yarn.lock` file change since we already use it in the monorepo.
Together with https://github.com/gatsbyjs/gatsby/pull/33277 it will remove an annoying issue with `fsevents`

chore(gatsby-plugin-offline): Replace cpx with cpy-cli

---

.circleci/config.yml
integration-tests/cache-resilience/gatsby-node.js
integration-tests/cache-resilience/package.json
integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-added/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-changed/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-removed/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-added/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-changed/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-removed/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-node-fields/source-added/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-node-fields/source-changed/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-node-fields/transformer-added/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-node-fields/transformer-changed/scenario.js
integration-tests/cache-resilience/plugins/source-and-transformers-node-fields/transformer-removed/scenario.js
integration-tests/cache-resilience/plugins/source/plugin-added/scenario.js
integration-tests/cache-resilience/plugins/source/plugin-removed/scenario.js
packages/gatsby/src/utils/worker/child/schema.ts

Even with `InferenceMetadata` schema building can make datastore access (like figuring out concrete `childX` fields based on children nodes types).
We already print graphql schema for engines. It contains directives that allow us to skip that additional "inference" in workers.
[ch33736]
[ch40615]

perf(gatsby): use saved schema snapshot in PQR workers

---

packages/gatsby/src/query/file-parser.js

Pretty minor, but without it we need one of other keywords to discover config

fix(gatsby): fix running config when page doesnt contain graphql or getServerData or gatsby-plugin-image

---

.circleci/config.yml

This fixes applying GATSBY_CPU_COUNT env var when e2e tests provide some of their own (before this change e2e test specific env var would overwrite base env vars, essentially losing them in Gatsby trying to use 18 cores there - :yikes:) 
Diff of `circleci config process .circleci/config.yml` (which constructs final config merging all aliases and anchors etc) - https://www.diffchecker.com/4Dm01tX9 
In particular effect of this on Contentful test setup:

tests(circleci): merge base e2e env vars in all e2e tests

---

packages/gatsby-transformer-screenshot/package.json

I missed this a couple years ago. The identifier in use here is deprecated - it should be replaced or removed.

chore(gatsby-transformer-screenshot): Update old name

---

docs/docs/conceptual/security-in-gatsby.md

Try to fix https://github.com/gatsbyjs/gatsby/issues/34317 , use `en-US` mdn links
cc @wardpeet @DillonBroadus 
Fixes https://github.com/gatsbyjs/gatsby/issues/34317

docs: use en-US version mdn links

---

docs/tutorial/building-a-theme.md

Without this code, a further command in the tutorial will fail
Match egghead.io video instructions
N/A

docs: Match egghead.io video instructions

---

packages/gatsby-plugin-image/src/image-utils.ts
packages/gatsby-plugin-preact/.babelrc
packages/gatsby-plugin-preact/package.json
packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
packages/gatsby-plugin-preact/src/gatsby-browser.js
packages/gatsby-plugin-preact/src/gatsby-node.js
yarn.lock

Fixes alias resolution for Preact now that they switched to exports field.
Fixes #34263

fix(gatsby-plugin-preact): fix exports resolution webpack

---

packages/gatsby-remark-prismjs/README.md

Changes `prismjs` links from
`http` => `https`
Null
Null

docs(gatsby-remark-prismjs): Update http links to use https

---

docs/docs/how-to/styling/sass.md

- Add shell block around `npm install` command to be able to copy to clipboard
- format `sass` syntax
- remove link to starters using `sass`: none of the starters now use `sass`
https://www.gatsbyjs.com/docs/how-to/styling/sass/

docs: Add shell code block & remove starter link for sass

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

✏️ fix(typo) : gatby-node.js -> gatsby-node.js
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#process-is-not-defined
Null

docs: fix typo gatby-node.js -> gatsby-node.js

---

packages/gatsby-source-contentful/src/normalize.js
packages/gatsby/src/redux/actions/public.js

`createNode` should always return a promise but returns undefined when the node hasn't changed, this PR fixes that and adds some protective code in `gatsby-source-contentful` so it doesn't always treat the return value as a promise (for previous `gatsby` versions).

fix(gatsby): createNode return promise

---

packages/gatsby/src/utils/page-data.ts

fix(gatsby): Only start write page-data.json activity if there's pages to write

---

packages/gatsby-worker/README.md
packages/gatsby-worker/src/index.ts
packages/gatsby/src/utils/validate-engines/index.ts

Duplicate/unnecessary output was being seen from the validate-engines worker. This PR gives each worker the ability to ignore output using `fork`s `silent` option.
Example from `validate-engines`:
```
const worker = new WorkerPool<typeof import("./child")>(
require.resolve(`./child`),
{
numWorkers: 1,
env: {
// Do not "inherit" this env var for validation,
// as otherwise validation will fail on any imports
// that OpenTracing config might make
GATSBY_OPEN_TRACING_CONFIG_FILE: ``,
},
silent: true,
}
)
```
Documented within the `gatsby-worker`'s `README.md`. 
[sc-39755]

chore(gatsby): Give option to ignore output from workers and silence validate-engines

---

docs/docs/plugins.md

The URL for the `gatsby-plugin-segment-js` docs was wrong - it was missing the leading `/`, so it was taking people to a 404.
Current: https://www.gatsbyjs.com/docs/plugins/gatsby-plugin-segment-js
This PR updates to: https://www.gatsbyjs.com/plugins/gatsby-plugin-segment-js/

Update plugins.md to have correct URL for gatsby-plugin-segment-js

---

examples/functions-auth0/gatsby-config.js
examples/functions-auth0/package.json

Remove usage of `gatsby-plugin-create-client-paths` in the Auth0 example since the plugin will be deprecated. In this case, it wasn't needed anyway so there isn't a replacement needed.
[ch44096]

chore: Remove deprecated client paths plugin references

---

packages/gatsby-plugin-create-client-paths/README.md

Update the `gatsby-plugin-create-client-paths` readme to include brief migration information.
[ch44094]

chore(gatsby-plugin-create-client-paths): Update client paths plugin readme with migration info

---

deprecated-packages/gatsby-recipes/package.json
integration-tests/gatsby-cli/package.json
integration-tests/ssr/package.json
packages/gatsby-cli/package.json
packages/gatsby/package.json

This updates `strip-ansi` to version ^6.0.1 to fix this vulnerability issue: https://www.npmjs.com/advisories/1004946.
**I don't know how to test this, but would gladly help, if I can get a bit of guidance.**
- According to https://github.com/chalk/strip-ansi/releases/tag/v6.0.0, upgrading to version 6 requires changing `import stripAnsi from 'strip-ansi';` to `import stripAnsi = require('strip-ansi');`. I did not make this change because VSCode only accepted the current syntax, and my experience is that VSCode is usually right about these things. 🙂
- I have updates to ^6.0.1 across all packages including the ones that already were on ^6.0.0 to align the version and to make it clear that v6.0.0 should be avoided.
- I have not upgrade to version 7 because that changes `strip-ansi` to the …

Upgrade to strip-ansi ^6.0.1

---

docs/docs/gatsby-internals-terminology.md
docs/docs/page-creation.md
docs/tutorial/authentication-tutorial.md

Either change mentions of `gatsby-plugin-create-client-paths` to use the File System Route API or remove entirely to avoid confusion.
[ch44099]

chore(docs): Adjust doc mentions of gatsby-plugin-create-client-paths

---

packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
packages/gatsby/src/bootstrap/redirects-writer.ts

Fix misspelling of "precedence" in log message

---

packages/gatsby-plugin-manifest/.babelrc
packages/gatsby-plugin-manifest/src/gatsby-browser.js
packages/gatsby-plugin-manifest/src/gatsby-node.js

On windows icon generation sometimes get stuck and hangs forever, moving to processing images sequentially fixes it. Probalby an issue with open handlers in sharp or how we do the resize.
Fixes #25216

fix(gatsby-plugin-manifest): generate icons sequentially

---

docs/tutorial/building-a-theme.md

This reverts commit bd3524e81590abe07d3dda46a6ec46d069fde054.
Reverts https://github.com/gatsbyjs/gatsby/pull/34315
The  instructions in the egghead video are outdated and the text is the source of truth now.
cc @fagiani @wardpeet

Revert "docs: Match egghead.io video instructions (#34315)"

---

integration-tests/ssr/__tests__/ssr.js
integration-tests/ssr/test-output.js

Fix a recurrent integration test flake that's been causing some confusion.
- https://github.com/gatsbyjs/gatsby/pull/34383#issuecomment-1003938845
- https://github.com/gatsbyjs/gatsby/pull/34182#issuecomment-1006758251
[sc-44269]

test(ssr): Fix flakes

---

packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js

Partially revert https://github.com/gatsbyjs/gatsby/pull/28464 with its `ignore-engines` change. Should hopefully catch breaking engines changes like in https://github.com/gatsbyjs/gatsby/pull/33786

fix(gatsby-dev-cli): Do not ignore engines

---

packages/gatsby-core-utils/src/site-metadata.ts

Re-Exports something we renamed in https://github.com/gatsbyjs/gatsby/pull/34094 and that now causes problem sometimes.
Fixes https://github.com/gatsbyjs/gatsby/issues/34455

fix(gatsby-core-utils): Re-Export updateSiteMetadata

---

docs/contributing/gatsby-style-guide.md

Webpack can now be written with a capital at the beginning of sentences according to their [documentation](https://webpack.js.org/branding/#the-name)

chore(docs): webpack branding guidelines updated

---

scripts/gatsby-changelog-generator/generate.js

Enshrine incorrect next release for `gatsby-plugin-utils` in map of messed-up releases.
Related to https://github.com/gatsbyjs/gatsby/pull/34182

chore(gatsby-plugin-utils): Override changelog for incorrect release

---

packages/gatsby/cache-dir/production-app.js

I introduced regression in https://github.com/gatsbyjs/gatsby/pull/34225 for cases when `loader.loadPage` returns `undefined`. This adds just check wether nested properties are defined.
Proper error handling is below, but we still want to potentially check for `webpackCompilationHash` before that (to potentially reload instead of just throwing error)
Fixes #34484

fix(gatsby): handle loaded page being potentially undefined

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/DOCUMENTATION.yml
.github/PULL_REQUEST_TEMPLATE.md

Updating our templates to remove some outdated information + in the issue templates the labels should be an array.

chore: Update issue/PR templates

---

packages/gatsby-source-wordpress/src/steps/preview/index.ts

This fixes a case where a preview callback didn't get cleaned up and then the next preview was for the same post as the one that wasn't cleaned up. Before this change the second preview would be ignored.

fix(gatsby-source-wordpress): cleanup callbacks at the end instead of the beginning of preview logic

---

docs/docs/conceptual/content-sync.md
packages/gatsby/src/utils/node-manifest.ts

This PR makes it easier to debug Content Sync. Sometimes we just want verbose mode for node manifests and don't need the additional noise of all other verbose logs.
I also added a note on how to see full node manifest warnings using this new env var and in the conceptual guide I linked to source plugin author docs.

feat(gatsby): content sync debugging tweaks

---

packages/gatsby/src/datastore/lmdb/query/run-query.ts
packages/gatsby/src/schema/__tests__/queries.js
packages/gatsby/src/schema/node-model.js

It seems we lost our fast path for simple `id.eq` queries and only had path like that for LMDB (experimental) indexes. I moves this to much earlier in pipeline (node-model).
This should mean fast filters WON'T create lookup table for it. Idea here is to limit usage of it where possible, as (right now) those lookup tables cause nodes to be retained in memory and also not needed as we can already grab nodes by id.
[sc-44551]

perf: move id: eq fast path handling to node-model so it's shared between query running strategies

---

packages/gatsby/cache-dir/production-app.js

fix(gatsby): handle session storage not being available

---

.circleci/config.yml

Seems like most recent `renovate` CLI version introduced fatal issue (at least when running through `npx`) - https://github.com/renovatebot/renovate/issues/13630
Pinning for now

chore(circleci): pin renovate cli version

---

packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-site-config.js
packages/gatsby-plugin-gatsby-cloud/src/constants.js
packages/gatsby-plugin-gatsby-cloud/src/create-site-config.js
packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js

In https://github.com/gatsbyjs/gatsby/pull/34411 the createSiteConfig functionality was removed and merged into the main trailing slash PR (https://github.com/gatsbyjs/gatsby/pull/34268). Due to compatibility reasons, this PR adds createSiteConfig functionality again to work side by side with the newly added IPC message.
[sc-44573]

fix(gatsby-plugin-gatsby-cloud): Revert removal of _gatsby-config.json functionality in gatsby-plugin-gatsby-cloud

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

The way the function getNode is extracted on the code example is incorrect.

docs(migrating-from-v2-to-v3): correct getNode snippet

---

docs/docs/reference/release-notes/migrating-from-v3-to-v4.md

The way getNode is extracted on the code example is incorrect

docs(migrating-from-v3-to-v4): correct getNode snippet

---

packages/gatsby-plugin-schema-snapshot/gatsby-node.js

Fixes a compatibility issue with parallel queries. With multiple sources, `createSchemaCustomization` is called a number of times. Setting the `update` option will try to remove the file, resulting in a race condition, so this has been moved to `onPluginInit` so it is only removed once.
N/A
N/A

fix(plugin-schema-snapshot): unlink file on init

---

.circleci/config.yml

The cherry-pick in https://github.com/gatsbyjs/gatsby/pull/34438 fails because of https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/78506/workflows/b1b1ca96-fed2-4858-a2e6-e0025e8d8955/jobs/927155
We won't be changing the renovate config in the v3 branch so this seemed to be the easiest way to solve this.

chore: Removate validate-renovate from v3-latest branch

---

packages/gatsby-plugin-sharp/package.json
packages/gatsby-react-router-scroll/package.json

`gatsby-plugin-sharp` and `gatsby-react-router-scroll` is depending on some packages without without declaring them so this PR makes them explicit
N/A

fix: add missing dependencies

---

docs/docs/reference/routing/file-system-route-api.md

- Add explicit code examples of difference between `[...].js` and `[...name].js` client only splat routes
- Add note about colocating regular client only routes in the same directory not being possible
- https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#splat-routes
- Related to https://github.com/gatsbyjs/gatsby/pull/34538
- [sc-44809]

chore(docs): Update FS route api client only splat description

---

packages/gatsby/src/schema/graphql-engine/webpack-remove-apis-loader.ts

https://github.com/gatsbyjs/gatsby/pull/33484 introduced a regression where `gatsby-plugin-sharp` doesn't init in engine and that result in errors on usage:
```
error Gatsby-plugin-sharp wasn't setup correctly in gatsby-config.js. Make sure you add it to the plugins array.
```
Currently
https://github.com/gatsbyjs/gatsby/blob/3659ec236ad54e87dff26effe11593c5663c31ed/packages/gatsby-plugin-sharp/src/gatsby-node.js#L132-L145
is getting bundled as
```
if (coreSupportsOnPluginInit) {
// to properly initialize plugin in worker (`onPreBootstrap` won't run in workers)
if (true) {} else {}
}
```
With this change it becomes
```
if (coreSupportsOnPluginInit) {
// to properly initialize plugin in worker (`onPreBootstrap` won't run in workers)
if (true) {
exports.onPluginInit = async ({
actions
}, …
```

fix(gatsby): don't remove onPluginInit in graphql-engine

---

packages/gatsby-cli/src/structured-errors/error-schema.ts

Seems like https://github.com/babel/babel/pull/14130 introduced extra fields in `location` that our current validation fails on.

fix(gatsby-cli): relax error location validation and ignore extra fields

---

e2e-tests/trailing-slash/package.json
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/services/initialize.ts

Adds trailing slash option to plugin hashes so a new hash gets created when `trailingslash` option changes. This ensures that we're creating new cache content when `trailingSlash` option changes without explicitly needing to do a `gatsby clean`
[sc-44577]

feat(gatsby): clear cache when trailing slash option changes

---

e2e-tests/trailing-slash/cypress/integration/always.js
e2e-tests/trailing-slash/cypress/integration/ignore.js
e2e-tests/trailing-slash/cypress/integration/legacy.js
e2e-tests/trailing-slash/cypress/integration/never.js
e2e-tests/trailing-slash/src/pages/client-only-splat/[...name].js
e2e-tests/trailing-slash/src/pages/fs-api-simple/{Post.slug}.js
e2e-tests/trailing-slash/src/pages/fs-api/{Post.slug}/index.js
e2e-tests/trailing-slash/src/pages/index.js

- Adds test case for trailing slash client only splat case
- Removes a couple duplicated tests
- Adjusts names and logically groups splat cases (one in `fs-api` and new one in `client-only-splat`)
Colocating `[...name].js` and `[name].js` in the same `client-only` directory as directed in the ticket did not work. Nested routes (e.g. `/client-only/hello/world`) did not exist. Created separate `client-only-splat` directory to test client only splat separately.
If this is expected, I may update the documentation to note this. Otherwise it may be something to investigate.
- [sc-44588]

test(gatsby): Trailing slash client only splat

---

packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/destructured-export/input.mjs
packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/destructured-export/output.mjs
packages/gatsby/src/utils/babel/__tests__/index.js
packages/gatsby/src/utils/babel/babel-module-exports-helpers.ts
packages/gatsby/src/utils/babel/babel-plugin-remove-api.ts

This PR adds support for another module export syntax in `babel-plugin-remove-api`:
```javascript
export const { foo } = () => {}
```
- Relates to https://github.com/gatsbyjs/gatsby/issues/33998
- Relates to https://github.com/gatsbyjs/gatsby/issues/34496
- Relates to #34582
- [sc-45025]

fix(gatsby): Handle export const syntax in babel-remove-api plugin

---

packages/gatsby-transformer-react-docgen/src/parse.js

My TS component are not properly picked up by react-docgen. The default handlers parse my function components before the https://github.com/Winner95/typescript-react-function-component-props-handler handler is even called.
The current code allows only adding new handlers. These are always called after the default ones.
Most of the cases, you want to add handlers because the default ones either do not catch it, or catch it the wrong way.
With this PR I want to propose the most simple fix:
Run the user handlers before the default ones. (One might argue thats a breaking change ¯\\\_(ツ)\_/¯)
We could extend the configuration behaviour to allow completely skipping the default handlers. It would be a breaking change tough:
1. If a users passes handerls, only the user handlers are used. If one …

fix(react-docgen): run user handlers before default ones

---

packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
packages/gatsby-plugin-gatsby-cloud/src/components/buttons/LinkIndicatorButton.js
packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js

- Fixes build state
- Fixes issue where error and success state show tooltip on hover

fix(gatsby-plugin-gatsby-cloud): usability updates for the info and link indicator buttons

---

e2e-tests/development-runtime/cypress/integration/functionality/modified-exports.js
e2e-tests/development-runtime/src/components/unmodified-exports.js
e2e-tests/development-runtime/src/pages/modified-exports.js
e2e-tests/production-runtime/cypress/integration/modified-exports.js
e2e-tests/production-runtime/src/components/unmodified-exports.js
e2e-tests/production-runtime/src/pages/modified-exports.js
packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
packages/gatsby/src/utils/__tests__/webpack-utils.ts
packages/gatsby/src/utils/babel-loader-helpers.js
packages/gatsby/src/utils/babel-loader.js
packages/gatsby/src/utils/webpack-utils.ts
packages/gatsby/src/utils/webpack.config.js

This PR handles page templates separately in our main webpack config so we only use `babel-plugin-remove-api` for page templates.
- Fixes https://github.com/gatsbyjs/gatsby/issues/33998
- Fixes https://github.com/gatsbyjs/gatsby/issues/34496
- Relates to #34581
- [sc-44331]

fix(gatsby): Scope remove api babel plugin to page templates

---

packages/gatsby/package.json
packages/gatsby/src/query/__tests__/graphql-runner.ts
packages/gatsby/src/schema/schema.js
packages/gatsby/src/schema/types/derived-types.ts
yarn.lock

Large nested queries take a long time. Most time is spent inside graphql-compose as it fetches type information for every field for each query.
A lot of data is being passed around and it causes lots of GC.
The latest grahpql-compose version does memoisation of getTypes increases drops performance of these queries dramatically.
https://github.com/graphql-compose/graphql-compose/releases/tag/v9.0.0
You can try the canary with `gatsby@graphql-compose`
Some numbers to share:
<details>
<summary>customer 1</summary>
before:
```
success building schema - 256.133s
success createPages - 993.229s
success createPagesStatefully - 0.094s
```
after:
```
success building schema - 181.002s
success createPages - 156.464s
success createPagesStatefully - 0.144s
```
</details>
<details>
<summary>customer …

feat(gatsby): upgrade graphql-compose to latest for speed improvements

---

packages/gatsby/index.d.ts

While playing with `createPage` and DSG in a `gatsby-node.ts` file I saw that `defer` was missing

chore(gatsby): Add `defer` to `createPage` type

---

packages/gatsby-plugin-google-gtag/README.md
packages/gatsby-plugin-google-gtag/src/__tests__/gatsby-ssr.js
packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js

Add the ability to change the domain where the google-gtag is hosted to prevent ad-blocking of the gtag.js

feat(gatsby-plugin-google-gtag): add selfHostedOrigin option

---

packages/gatsby/src/utils/api-runner-node.js

This PR tries to handle the breaking of stack trace from Async functions This would resolve the error generated as the Gatsby plugin tries to open invalid filename from the stack.
This is not really a documentation change.
This PR fixes https://github.com/gatsbyjs/gatsby/issues/24863

fix(gatsby): fixes stacktraces from async functions break error reporting

---

packages/gatsby-plugin-remove-trailing-slashes/README.md
packages/gatsby-plugin-remove-trailing-slashes/src/gatsby-node.js

Note: The documentation for trailing slash in Gatsby is not released yet. Ideally, we want to merge this after the docs is ready
Add deprecation notice since Gatsby now provides support for trailing slash config out of the box
https://gatsby.dev/trailing-slash
[sc-44960]
https://github.com/jon-sully/gatsby-plugin-force-trailing-slashes/pull/23

chore(gatsby-plugin-remove-trailing-slashes): add deprecation warnings 

---

docs/contributing/how-to-open-a-pull-request.md
docs/docs/glossary.md

While reading the contribution documentation, I came across a couple links to https://www.gatsbyjs.com/contributing/setting-up-your-local-dev-environment/#gatsby-repo-install-instructions and noticed the "gatsby-repo-install-instructions" fragment doesn't exist. I believe it was intended to be https://www.gatsbyjs.com/contributing/setting-up-your-local-dev-environment/#gatsby-repo-instructions

chore(docs): fix links to repo instructions

---

docs/docs/recipes/styling-css.md

I noticed some links on https://www.gatsbyjs.com/docs/recipes/styling-css/ aren't taking the reader to the intended content so I'm fixing the following here:
* "More about layout components" link now takes user to https://www.gatsbyjs.com/docs/tutorial/part-2/#create-a-reusable-layout-component
* "More on Using CSS Modules" link now takes user to https://www.gatsbyjs.com/docs/tutorial/part-2/#style-components-with-css-modules
* The "If you don’t know how to import styles, take a look at Styling with CSS" link now takes the user to https://www.gatsbyjs.com/docs/how-to/styling/built-in-css/

chore(docs): fix links on styling-css page

---

packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
packages/gatsby-plugin-preact/src/gatsby-node.js

Adds an alias for `react/jsx-runtime` to the Preact plugin
Preact's alias documentation: https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact
None that I see in the tracker, but ran across this Stack Overflow issue while managing Preact's issues: https://stackoverflow.com/q/70904210/15388164

fix(gatsby-plugin-preact): Adding missing alias for `react/jsx-runtime`

---

packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/index.ts

Depending on what stage the build was at (if it was already in a SUCCESS state for example), build polling wouldn't start, and thus `shouldPoll` passed into `usePollForNodeManifest` would be `false` and no re-render would happen to make it `true`, causing it to never start looking for node manifest files (for Content Sync). The end effect would be the user was sometimes stuck with a "Building a new preview" message and loading spinner, but nothing would actually be happening.

fix(gatsby-plugin-gatsby-cloud): Preview UI race condition

---

packages/gatsby-plugin-preact/src/gatsby-node.js

Fix an alias for react-dom/server in `gatsby-plugin-preact`. Avoid replacing the extension because not find preact/compat/server.module.js
https://github.com/preactjs/preact/blob/1b6fbc723020f66b74581e9eea067f74380eb1f9/package.json#L61
Fixes #34686

fix(gatsby-plugin-preact): Fix alias for react-dom/server

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

I struggled with understanding how to add images from a json file I was creating, particularly with files that are stored locally.  So I have amended this to make it clearer.  Hope it makes sense.

chore(docs): Update gatsby-plugin-image to mention local data source

---

packages/gatsby/src/schema/__tests__/fixtures/queries.js
packages/gatsby/src/schema/__tests__/queries.js
packages/gatsby/src/schema/node-model.js

The PR https://github.com/gatsbyjs/gatsby/pull/34520 introduced a regression, see https://github.com/gatsbyjs/gatsby/issues/34693
This fixes it.
Fixes https://github.com/gatsbyjs/gatsby/issues/34693
[ch45642]

fix(gatsby): Local file lookups in `eq: $id` queries

---

packages/create-gatsby/src/questions/styles.json

Adds vanilla-extract to styling option. Shows the vanilla-extract option when your language preference is set to TypeScript 
[sc-44814]

feat(create-gatsby): Add vanilla extract to stying options

---

packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js

Fixing a regression in polling logic. The poll interval reset has been occurring in a nested loop, causing polling to happen only once. Extracting this logic out is causing polling happen on regular 2 second intervals.

fix(gatsby-plugin-gatsby-cloud) Fix polling logic for non eager redirected urls.

---

docs/docs/debugging-html-builds-and-runtime-ssr.md
docs/docs/debugging-html-builds.md

…nd-runtime-ssr.md
Updating HTML build docs to include information about about "browser globals" during "runtime SSR"
Fixes #34519

chore(docs): Update "Debugging HTML builds" to include `getServerData`

---

docs/docs/reference/graphql-data-layer/schema-customization.md

Without it you get `Definition object should contain 'type' property: Object({ resolve: [function resolve] })`

chore(docs): Added required `type` attribute to resolver

---

packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js

Fixing the unintuitive/frustrating behavior of the "This page has been updated" and "there has been an error building your site" preview pop ups.
**Changes:**
1. Preview pop up defaults to showing (previously it would not show, but display a red dot noting that there is a notification)
2. Hovering over any part of the tooltip while a SUCCESS/ERROR notification is up will not cause the notification to disappear
3. Notification can be dismissed by using "x" icon or clicking on the button (pre existing behavior)

fix(gatsby-plugin-gatsby-cloud) Force click-only behavior for SUCCESS and ERROR statuses.

---

packages/gatsby/package.json
packages/gatsby/src/utils/webpack.config.js
yarn.lock

Removing v8-compile-cache as it doesn't play well with ESM and you get cryptic errors.
This could make builds a little bit slower
https://github.com/zertosh/v8-compile-cache/pull/39

chore(gatsby): remove v8-compile-cache

---

integration-tests/ssr/__tests__/ssr.js
integration-tests/ssr/test-output.js

Fix persistent flaky SSR integration test. Last attempted fix fixed the issue but changed the timeout.
This reverts the timeout to original time from https://github.com/gatsbyjs/gatsby/pull/28394/commits/b96c520ce537018d6e7ecbdb4d4439278baff075

test(ssr): Remove flake

---

docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md

This PR adds [Prismic](https://prismic.io/) to the list of `gatsby-plugin-image`-compatible CMSs. `gatsby-source-prismic` supports `gatsby-plugin-image` via `@imgix/gatsby` or `gatsby-transform-sharp`.
See: https://prismic.io/docs/technologies/template-fields-gatsby#image-processing
https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/#source-plugins
N/A

chore(docs): Add Prismic to `using-gatsby-plugin-image`

---

packages/gatsby-link/src/rewrite-link-path.js

We weren't checking for `__TRAILING_SLASH__ ` not being set in prod environments. I wanted to add a test for this as well, but looks like we do similar checks elsewhere so we can't utest this in a simulated prod environment.
If anyone looks at this in the future, here's the test we could add:
```
['development', 'production'].forEach(nodeEnv => {
it(`handles option not set in ${nodeEnv} (legacy behavior)`, () => {
process.env.NODE_ENV = nodeEnv
delete global.__TRAILING_SLASH__
expect(rewriteLinkPath(`/path`, `/`)).toBe(`/path`)
expect(rewriteLinkPath(`/path/`, `/`)).toBe(`/path/`)
expect(rewriteLinkPath(`/path#hash`, `/`)).toBe(`/path#hash`)
expect(rewriteLinkPath(`/path?query_param=hello`, `/`)).toBe(
`/path?query_param=hello`
)
expect(rewriteLinkPath(`/path?query_param=hello#anchor`, …
```

fix(gatsby-link): trailing slash undefined check for prod env

---

packages/gatsby-plugin-mdx/README.md

Tell users to use `@v1` for now as v2 is not compatible with gatsby-plugin-mdx

chore(gatsby-plugin-mdx): Use MDX v1 for install instructions

---

docs/docs/how-to/testing/unit-testing.md
docs/docs/reference/release-notes/v4.7/index.md
examples/using-jest/jest.config.js

Necessary for when you now test `gatsby-link` as https://github.com/facebook/jest/issues/9771 is not supported yet and users have to update their `jest.config.js`.

chore(docs): Update Unit Testing instructions to update `moduleNameMapper`

---

packages/gatsby-source-wordpress/src/gatsby-browser.ts

Fixes https://github.com/gatsbyjs/gatsby/issues/33745
Tested this from desktop Safari 10.1 to 15.2 and latest IOS Safari (on Ipad) and it works great 👍 
A canary is available as `gatsby-source-wordpress@6.7.0-alpha-gatsby-source-wordpress.7+eb08d8a7d9`

fix(gatsby-source-wordpress): patch safari bug in source-wordpress' gatsby-browser

---

README.md

This Pull Request adds a temporary banner for [GatsbyConf 2022](https://gatsbyconf.com) to the repository README file.
N/A
There are no related issues for this PR, but pinging @pragmaticpat and @LekoArts for your :eyes: on this PR and any feedback you have about it. 😄

chore: Add GatsbyConf 2022 banner to README

---

integration-tests/node-manifest/__tests__/create-node-manifest.test.js
integration-tests/node-manifest/gatsby-node.js
integration-tests/node-manifest/src/templates/four.js
packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/types.ts
packages/gatsby/src/utils/node-manifest.ts

This change allows Gatsby Preview (content sync) to work with more sites by default. Many Contentful sites use node.slug in page context to query for entries by their slug. This isn't good practise because slugs aren't unique in contentful (id's would be better), but it's done commonly enough that we can use it to match node manifests to pages for Content Sync routing. So this makes more Contentful sites work with Preview without needing to add an `ownerNodeId`

feat(gatsby): Match node manifest pages by page context slug

---

docs/docs/conceptual/choosing-a-cms.md

docs: update typo Forestry

---

packages/gatsby/src/utils/node-manifest.ts

I recently discovered Content Sync no longer works with DSG. I could've sworn it used to but it doesn't now. This fix will be less performant for large sites. I'm going to follow this PR up with another that will improve performance but since we have a marketing release of Content Sync next week I don't want to make too many code changes before then. This is the most minimal change required to make Content Sync work w/ DSG.

fix(gatsby): Content Sync DSG bug

---

packages/gatsby/package.json
packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/__tests__/print.js
packages/gatsby/src/schema/print.ts
packages/gatsby/src/schema/schema.js
packages/gatsby/src/schema/types/sort.ts
yarn.lock

Changes:
- bump to get fix in `graphql-compose` ( https://github.com/graphql-compose/graphql-compose/pull/373 )
- swap schema printer to use TypeComposers instead of `graphql-js` types - we do print schema before all "derived types" (such as our various filter and sort inputs etc) are created. This meant we couldn't ever reference such derived types and be able to print schema, because at the time of printing the type doesn't exist yet (causing printing to throw). I did try initially moving printing to after we create derived types but this changed too many things - it started printing everything and then we were getting exceptions that we try to create types reserved for Gatsby - https://github.com/gatsbyjs/gatsby/blob/d846f8981cdf2dd866cec3d7d191b8f64bbbc2b3/packages/gatsby/src/schema/sc …

feat(gatsby): allow referencing derived types in schema customization

---

docs/docs/how-to/testing/unit-testing.md
examples/using-jest/jest.config.js
jest.config.js
packages/gatsby-core-utils/README.md
packages/gatsby-core-utils/package.json
packages/gatsby-core-utils/src/__tests__/mutex.ts
packages/gatsby-core-utils/src/mutex.ts
packages/gatsby-core-utils/src/utils/get-lmdb.ts
packages/gatsby-core-utils/src/utils/get-storage.ts
packages/gatsby/src/services/initialize.ts
yarn.lock

Adding a multi-process mutex that works 100% of the time by leveraging LMDB. LMDB's `ifNoExists` helps us with thread/process safety. 
The API supports a `createMutex` function that expects a key. This function returns an object with two functions `acquire` and `release.` Acquire will wait for the mutex to be available and release will release the current mutex. This is a powerful mechanism.
For this change, lmdb 2.0 is necessary as lmdb 1.0 didn't make sure only one proc went through. So I try to get the lmdb instance from gatsby. If it's not available, it will use its own.
A proper integration test will be written with `fetchRemoteFileNode` in a follow-up

feat(gatsby-core-utils): create proper mutex

---

packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts

`expirer` setting explained in https://github.com/kriszyp/weak-lru-cache#expirer
This just removes strong references from lmdb cache. It doesn't mean nodes WILL be GCed - it just makes it possible (if memory need to be freed).

chore(gatsby): cache shouldn't reference nodes strongly

---

packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
packages/gatsby-source-contentful/src/source-nodes.js

In #34584 we improved logging to separate between new and updated nodes.
For the existing ones, we forgot to divide by locale count. As multiple existing Gatsby nodes reflect one single Contentful node, this should make it more clear how many Contentful nodes the system already knew on a warm build.

fix(gatsby-source-contentful): avoid confusion of Gatsby node and Contentful node count in logs

---

rfcs/text/0011-move-rfcs-to-monorepo.md

While browsing through the rfcs I found this small typo error.

fix(docs): small typo error

---

packages/gatsby-source-contentful/src/source-nodes.js

This causes issues with metric gathering on Gatsby Cloud as we treat
each activity name as a unique thing so prefer to keep the numbers of
these labels small.

fix(gatsby-source-contentful): Don't use unique/personal info in activity labels

---

packages/create-gatsby/src/questions/styles.json

Add required dependencies that are no longer deps of the latest version of theme-ui. See https://github.com/system-ui/theme-ui/blob/develop/CHANGELOG.md
Fixes https://github.com/gatsbyjs/gatsby/issues/34882

fix(create-gatsby): Add required deps for theme-ui option

---

docs/docs/tutorial/part-1/index.mdx

We recently added flags(`-y`, `-ts`) to `create-gatsby`  together with a new prompt  for users to choose between JavaScript and TypeScript. This PR updates docs to reflect these changes and how users can use them. 
https://www.gatsbyjs.com/docs/tutorial/part-1/#create-a-gatsby-site
[sc-44636]

chore(docs): update main tutorial to incorporate TS Updates to create-gatsby

---

docs/docs/reference/config-files/gatsby-config.md

- Clarify that the current default setting for `trailingSlash` is `legacy`. As it was stated, the reader would likely be confused by "Until Gatsby v4" since Gatsby v4 is currently available.
- Split a run-on sentence into two sentences.

chore(docs): Update `trailingSlash` default wording

---

.circleci/config.yml

Temporary version lock. Something in the most recent `yarn` release broke this.

fix(gatsby): Lock yarn version to previous for tests

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

Fixes a bug where remote url doesn't provide extension and doesn't apply it when found from source file

fix(gatsby-core-utils): fix urls without extension

---

docs/docs/reference/config-files/gatsby-config.md

There was a question in our public discussion about whether trailingSlash had any effect on functions urls. It does not effect functions.

docs(gatsby): Specify trailingSlash is pages only

---

docs/docs/how-to/custom-configuration/typescript.md

docs: specify gatsby versions supporting particular TS features

---

docs/docs/mdx/importing-and-using-components.md

This PR simply updates a link that was resulting in a 404 to what I believe the intended URL should be.
Became aware of this issue from a #docs-feedback-firehose message here: https://gatsbyjs.slack.com/archives/C02HQF29DJN/p1645942095266779
Docs page can be found here: https://www.gatsbyjs.com/docs/mdx/importing-and-using-components/
And I believe the link associated with "Writing Pages in MDX Guide" should point to: https://www.gatsbyjs.com/docs/how-to/routing/mdx/#part-2-writing-pages-in-mdx

[docs] update writing pages in MDX link to correct url

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

When requesting files with the same cacheKey, there were still a few bugs that I fixed and added tests for.

fix(gatsby-core-utils): fix caching when using remote-file

---

packages/gatsby-parcel-config/lib/index.json
packages/gatsby-parcel-config/package.json
packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
packages/gatsby/src/utils/parcel/__tests__/fixtures/ts-only-in-local-plugin/plugins/gatsby-plugin-local/gatsby-config.ts
packages/gatsby/src/utils/parcel/__tests__/fixtures/ts-only-in-local-plugin/plugins/gatsby-plugin-local/gatsby-node.ts
yarn.lock

Right now, because of https://github.com/parcel-bundler/parcel/issues/5476#issuecomment-769058504 when you have `.ts` file only in local plugin, but not in the root of the repo the output is "messed up" - compiled files are in unexpected locations which means gatsby can't load proper gatsby-node file.
This PR looks to first add failing test case covering above and in next commit add "workoarund" (by adding customer namer plugin)

chore(gatsby-parcel-config): stabilize ts compilation parcel output

---

integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts

Sorts avif before webp in picture tag
Fixes #35019

fix(gatsby-plugin-utils): make sure avif, webp are sorted correctly

---

docs/docs/how-to/custom-configuration/typescript.md

The correct command is `npx tsc --init`

chore(docs): typo in typescript documentation

---

integration-tests/gatsby-source-wordpress/__tests__/index.js
integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
integration-tests/gatsby-source-wordpress/test-fns/env-browser.js
integration-tests/gatsby-source-wordpress/test-fns/plugin-options.js

It seems IMAGE_CDN jobs slowed down the source-wordpress integration test Gatsby site build times by over 2x. We will investigate next week but in the meantime this PR stops the tests from failing

fix(gatsby-source-wordpress): default options build integration test

---

packages/gatsby-plugin-sharp/package.json
packages/gatsby-remark-copy-linked-files/package.json
packages/gatsby-transformer-sharp/package.json
yarn.lock

Upgrades `probe-image-size` to `^7.0.0` to fix the `MaxListenersExceededWarning` console error caused by versions prior to  [https://github.com/nodeca/probe-image-size/commit/a6da059439614c399b79c09ea1d406a3e4300b27](https://github.com/nodeca/probe-image-size/commit/a6da059439614c399b79c09ea1d406a3e4300b27)
Thanks to @hendra-go for discovering the cause of the issue. 
Fixes #34795

fix(gatsby-plugin-sharp): Upgrade `probe-image-size` to fix memory leak warning

---

packages/gatsby-transformer-excel/package.json
packages/gatsby-transformer-excel/src/gatsby-node.js
yarn.lock

`gatsby-transformer-excel` currently reads files into binary strings.  This results in a wasteful conversion under the hood (`fs.readFile` reads into a Buffer then encodes, `XLSX` decodes the binary string back to a Buffer).  The patch uses `XLSX.readFile` directly if a node has an absolute path.
n/a
n/a

fix(gatsby-transformer-excel): Use `readFile` Buffer

---

packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
packages/gatsby/src/utils/babel-loader.js
packages/gatsby/src/utils/webpack-utils.ts

There was a key named "browerslist". Fix the spelling and make it camel case like the others.

fix(gatsby): Misspelled cacheIdentifier key

---

README.md

This PR removes the temporary banner for GatsbyConf 2022 that was added in #34782.
N/A
- Related to #34782.  Pinging @pragmaticpat and @LekoArts to as a heads up since y'all helped with the original PR that added the banner. 😄

chore: Remove GatsbyConf 2022 banner from README

---

packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
packages/gatsby/src/schema/graphql-engine/lmdb-bundling-patch.ts

This fix is already in master and problem occurs when latest gatsby-core-utils is installed by a plugin.
We patch any version of lmdb now and make sure we only load one
Fixes #34912

fix(gatsby): make sure node-gyp gets replaced

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

Backporting https://github.com/gatsbyjs/gatsby/pull/35039 to the 4.9 release branch
(cherry picked from commit https://github.com/gatsbyjs/gatsby/commit/2f361ccdbbd11c43495d54f8202919757831a023)

fix(gatsby-core-utils): multiple requests with different outputdir (#35039)

---

docs/docs/query-extraction.md

chore(docs): Update query-extraction.md to point to TS file instead of old JS

---

packages/gatsby/src/schema/print.ts
packages/gatsby/src/schema/schema.js
packages/gatsby/src/schema/types/built-in-types.ts

This adjust our InternalTypes list for schema printing and removes wrong `Json` type from it
Fixes #34610

fix(gatsby): fix schema printing for gatsby-transformer-json

---

packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
packages/gatsby-plugin-gatsby-cloud/src/models/enums/build-status.ts

Add three (3) new messages:
`UPLOADING`:
`QUEUED`:
`BUILDING`:

(feat Preview UI): Added more build status messages

---

packages/gatsby-telemetry/src/telemetry.ts
packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
packages/gatsby/src/utils/worker/__tests__/config.ts
packages/gatsby/src/utils/worker/__tests__/datastore.ts
packages/gatsby/src/utils/worker/__tests__/jobs.ts
packages/gatsby/src/utils/worker/__tests__/queries.ts
packages/gatsby/src/utils/worker/__tests__/schema.ts
packages/gatsby/src/utils/worker/__tests__/share-state.ts

Let's us know how many ts files are found by the `entries` glob
[ch47088]

feat(gatsby): Capture number of compiled TS files in Telemetry

---

packages/gatsby/src/schema/resolvers.ts

I've ran into a case where `context` was undefined resulting in: 
```js
TypeError: Cannot read properties of undefined (reading 'telemetryResolverTimings')",
"    at wrappedTracingResolver (/home/thomas/Workspace/aardling/2022.dddeurope.com/node_modules/gatsby/src/schema/resolvers.ts:679:17)",
```
there was a check on `if (context?.tracer)` already but not on the `telemtryResolverTimings`
No updates need

fix(gatsby): null check for context

---

packages/create-gatsby/src/questions/cmses.json

Add peer dependencies of `gatsby-source-wordpress` to schema used when selecting Wordpress in `create-gatsby`.
None needed
Fixes https://github.com/gatsbyjs/gatsby/issues/35106
[sc-47446]

fix(create-gatsby): Update wordpress deps in schema

---

docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md

Improves documenation especially if deciding to use a different repository to host the source for the gh-page hosted on the direct username.github.io subdomain
As above.
Closes #35117

docs(gh-pages): improve separate repository instructions

---

docs/docs/conceptual/data-fetching.md

I've changed the `node-fetch` import to use the commonJs method. 
[node-fetch from v3 is an ESM-only module - you are not able to import it with require()](https://www.npmjs.com/package/node-fetch)

chore(docs): update documentation for node-fetch to use CommonJS

---

packages/gatsby-core-utils/src/utils/get-lmdb.ts

On Gatsby Cloud it breaks as it can't find gatsby/package.json, by moving it to try-catch it fallsback to lmdb version of gatsby-core-utils which get normalized by alias resolving in the webpack config.

fix(gatsby-core-utils): move package.json check to try catch

---

packages/create-gatsby/src/questions/cmses.json

Add peer dependencies of `gatsby-source-wordpress`, `gatsby-source-contentful`,  `gatsby-source-datocms`, `gatsby-source-shopify`and `gatsby-source-sanity` to schema used when selection Is made in `create-gatsby`.
None needed
[sc-47448]

fix(create-gatsby): update deps for cms source plugins

---

docs/docs/reference/release-notes/v4.10/index.md

Release notes for 4.10
[Rendered View](https://github.com/gatsbyjs/gatsby/blob/release-notes-4.10/docs/docs/reference/release-notes/v4.10/index.md)

chore(docs): 4.10 Release Notes

---

packages/gatsby-cli/src/handlers/plugin-add-utils.ts

Due to https://github.com/babel/babel-loader/issues/166#issuecomment-417894775, Babel can't access the TS preset unless resolved explicitly.
Reason for this is in `create-gatsby` we `require` handlers from `gatsby-cli` (presumably to avoid adding Babel deps to `create-gatsby` since they may not be needed if customers don't select plugins in the questionnaire [?]) and as a result of the above issue Babel isn't aware of the preset available in `gatsby-cli`.
Validated locally by pointing `create-gatsby` to my fork of `gatsby-starter-minimal-ts` with the patch applied - https://github.com/tyhopp/gatsby-starter-minimal-ts.
This will need to be released as a patch before https://github.com/gatsbyjs/gatsby/pull/35128 can be merged
No new docs needed
[sc-47001]

fix(gatsby-cli): Resolve babel preset ts explicitly

---

docs/docs/how-to/routing/scroll-restoration.md

I thought the key value might actually matter for some sort of css selector, but its doesn't. Other people seemed confused as well. Additionally, I expected the target widget to stay at the same position regardless of page, but it changed per page. I may add a useScrollRestorationGlobal hook to meet my needs (for a global navbar) that others might find useful as well. Cheers! This is my first pull request.
Docs for this are found here https://www.gatsbyjs.com/docs/how-to/routing/scroll-restoration/

chore(docs): Add context to useScrollRestoration usage

---

packages/gatsby-plugin-gatsby-cloud/src/constants.js

Lowered `INTERACTIONS_BEFORE_FEEDBACK` value to 3 in order to prompt the user for feedback more often.

fix(gatsby-plugin-gatsby-cloud): Lowered `INTERACTIONS_BEFORE_FEEDBACK` value to 3

---

packages/gatsby-plugin-utils/package.json

Fixes https://github.com/gatsbyjs/gatsby/issues/35164

fix(gatsby-plugin-utils): Add missing fs-extra dep

---

packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
packages/gatsby-plugin-preact/src/gatsby-node.js

Fixes aliases in Preact
https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact
Fixes #35145

fix(gatsby-plugin-preact): fix preact alias

---

packages/gatsby-cli/src/__tests__/handlers/plugin-add.ts
starters/gatsby-starter-minimal-ts/gatsby-config.js
starters/gatsby-starter-minimal-ts/gatsby-config.ts

Originally part of https://github.com/gatsbyjs/gatsby/pull/35074.
Change the `gatsby-starter-minimal-ts` Gatsby config from a JS to TS file. This should only be merged after the next minor release to avoid breaking existing `create-gatsby` functionality.
No change needed, documented in https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#gatsby-configts
[sc-47519]

feat(starters): Minimal TS starter gatsby-config.ts

---

packages/gatsby-plugin-google-gtag/README.md

Currently this link doesn't work (Service Unavailable). This PR updates the link

chore(gatsby-plugin-google-gtag): Update broken link

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/internal-plugins/functions/gatsby-node.ts

Someone on Discord was struggling with the old error message and yeah, the old message is not clear enough that `src/api` is a reserved folder

fix(gatsby): Improve functions compilation error

---

docs/docs/using-client-side-only-packages.md
packages/gatsby/src/utils/api-node-docs.ts

1. I added an additional description to the onCreateWebpackConfig documentation section. 
2. Swapped walkthroughs 3 and 4. Using React's native method example should come before the example of the loadable components.
Cc: @PaulieScanlon

chore(docs): Move `loadable-components` instructions

---

packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
packages/gatsby-source-filesystem/src/create-remote-file-node.js

fix(gatsby-source-filesystem): cleanup tests

---

examples/using-remark/src/utils/typography.js
packages/gatsby-cli/src/reporter/prepare-stack-trace.ts
packages/gatsby-graphiql-explorer/src/app/app.js
packages/gatsby-link/src/parse-path.js
packages/gatsby-plugin-image/src/image-utils.ts
packages/gatsby-plugin-sharp/src/process-file.js
packages/gatsby-remark-embed-snippet/src/index.js
packages/gatsby-transformer-react-docgen/src/doclets.js
packages/gatsby/src/bootstrap/redirects-writer.ts
packages/gatsby/src/cache/cache-fs.ts
packages/gatsby/src/utils/webpack.config.js
scripts/gatsby-changelog-generator/generate.js
scripts/gatsby-changelog-generator/render.js
scripts/i18n/sync.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
No user facing change
None

refactor: replace deprecated String.prototype.substr()

---

packages/gatsby/src/redux/actions/public.js

https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect
the createRedirect API is outdated and does not include `conditions`. It also shows an example of using `Language: 'zn'` which is an incorrect implementation. I also added some examples so it's more clear how to actually use these.
I'm also unsure how to remove the `rest: {}` from the end of params, as I don't see it anywhere in the code but it seems like that shouldn't be on the docs

chore(docs): add conditions to createRedirect api docs

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts
packages/gatsby-plugin-sharp/src/__tests__/trace-svg.js
packages/gatsby-plugin-sharp/src/gatsby-node.js
packages/gatsby-plugin-sharp/src/gatsby-worker.js
packages/gatsby-plugin-sharp/src/index.js
packages/gatsby-plugin-sharp/src/process-file.js
packages/gatsby-plugin-sharp/src/trace-svg.js

I've found some windows quirks during testing image-cdn.
I've added tests and fixed them.
1) When excludeDigest was given and the file already got requested, we could end up with a / path and a \\ path on windows which would not copy if it's inside public folder
2) trace-svg with long urls could end up with .. which is not a proper filename on windows.

fix(gatsby-plugin-sharp,gatsby-core-utils): windows quirks

---

packages/gatsby-source-filesystem/README.md
packages/gatsby-source-filesystem/src/__tests__/create-file-node-from-buffer.js
packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js

This pull request fixes the inconsistency within `createFileNodeFromBuffer()` function of `gatsby-source-filesystem` if a hash is calculated and not provided.
The `name` argument of this function has a [default value of `hash`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js#L128). However, the `hash` parameter is optional. if not given, it is [calculated within the same function](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js#L156). In this case, `name` remains `undefined`, which throws an error when [`createFilePath()`](https://github.com/gatsbyjs/gatsby/blob/82e3c8a9e17e20ad80483ec277f55f175eca6067/packages/gatsby-core-utils/src/filename-utils.ts#L55 …

fix(gatsby-source-filesystem): use correct hash when using createFileNodeFromBuffer

---

docs/docs/how-to/adding-common-features/adding-search.md

👋 I work on Typesense, which is an open source alternative to Algolia and an easier-to-use alternative to Elasticsearch. I built a Gatsby plugin for Typesense a while ago and we've had Gatsby users using it for a while, so figured it would good to add it to the docs. 
Under "Use an API-based search engine"
I had opened a PR in the previous Gatsby docs repo which I can't seem to find now, and I was told to hold off on it and resubmit it once the new docs site was up.

chore(docs): Add Typesense as a search engine option

---

docs/docs/how-to/styling/tailwind-css.md

A pattern has emerged where users include a glob to the `public` directory in their Tailwind config, which causes unintended side effects in Gatsby builds:
- https://discord.com/channels/484383807575687178/958086444101009438
- sc-46625
- sc-37151
- sc-36342
We link to [this Tailwind doc](https://tailwindcss.com/docs/content-configuration) from [our how-to guide for using Tailwind](https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/#4-configuring-your-content-path). That Tailwind doc has a section that says:
> Some frameworks hide their main HTML entry point in a different place than the rest of your templates (often public/index.html), so if you are adding Tailwind classes to that file make sure it’s included in your configuration as well
I suspect this may be one of the reasons …

chore(docs): Add note to tailwind doc

---

packages/gatsby/src/utils/__tests__/cache.ts
packages/gatsby/src/utils/cache.ts

Use global root directory instead of process.cwd for cache initialisation

fix(gatsby): use gatsby root instead of process.cwd

---

packages/gatsby-core-utils/package.json

Fixes our exports map for gatsby-core-utils.
The current problem occurs when you try to do the following `const {slash} = require('gatsby-core-utils/dist/path')`. Node will resolve this path `gatsby-core-utils/dist/dist/path.js`.
With the new rule we also catch the dist path and thus resolve to the correct file.

fix(gatsby-core-utils): fix exports map

---

packages/gatsby/src/datastore/in-memory/indexing.ts
packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/node-model.js

After https://github.com/gatsbyjs/gatsby/pull/34747 we have a regression when Node.js decides to do garbage collect nodes mid query execution (after filtering but before sorting) when sorting on fields with resolvers (fields that need materialization). It doesn't happen always (GC is not deterministic :) ) but it was happening fairly reliably (on at least one query of the site I debugged) before applying this fix
If node is GCed before sort happens we will loose `__gatsby_resolved` field as it's not persisted, so when sorting is about to start there is potential the node partial will have `undefined` instead of actual value if `__gatsby_resolved` is not there anymore
[ch47474]

fix(gatsby): fix intermittent wrong sort results when sorting on materialized field

---

docs/docs/how-to/local-development/gatsby-on-linux.md
docs/docs/tutorial/part-0/index.mdx

Feedback widget feedback came in, saying that the gatsby on linux page uses outdated Node versions. Indeed.
So I've updated the nvm installation + Node to 16 (also in the tutorial)

chore(docs): Update Node installation instructions

---

packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js

This bug was discovered when investigating this CS issue: https://app.shortcut.com/gatsbyjs/story/46489/images-on-wp-site-reverting-to-old-files-after-content-changes
This change is an improvement to the HTML image matching logic. It ensures that an existing image node is always found first, before relying on the fallback logic.

fix(gatsby-source-wordpress): logic for matching image nodes

---

docs/docs/reference/release-notes/v4.11/index.md

Fixing typo on `gatsby-source-mogodb`:
https://www.gatsbyjs.com/docs/reference/release-notes/v4.11/#notable-bugfixes--improvements

chore(docs): typo in 4.11 release notes

---

e2e-tests/production-runtime/cypress/integration/1-production.js
e2e-tests/production-runtime/gatsby-node.js
e2e-tests/production-runtime/src/pages/index.js
packages/gatsby/src/commands/serve.ts
packages/gatsby/src/utils/find-page-by-path.ts

In DSG mode, When special characters like  `한글` is used as page path, we 404 when trying to find page and page-data for that path. This PR addressed that by decoding the path before finding a matching page
Fixes #35241
[sc-48355]

fix(gatsby): fix DSG special char 404 issue

---

e2e-tests/development-runtime/cypress/integration/ssr.js
e2e-tests/production-runtime/cypress/integration/ssr.js
packages/gatsby/src/utils/page-ssr-module/entry.ts

In SSR pages, querystring encoding is not preserved as with other pages types. This ends up making `location.search ` to  be correct when querystring key or value contains special characters like `%23`(`#`). This PR addresses this issue by making sure querystring encoing is preserved in SSR mode — Just like in other page types
Fixes #35254
[sc-48353]

fix(gatsby): fix decoding issue in SSR

---

packages/gatsby/index.d.ts

This PR adds the [already documented](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createPage) optional `ownerNodeId` prop to the Page type representing args to `createPage`.
[Documentation exists here.](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createPage)

fix(gatsby): add missing `ownerNodeId` prop to Page type

---

docs/docs/deploying-to-gitlab-pages.md

Fix missing `deploy` stage that otherwise would not trigger deployment resulting in page 404

chore(docs): Update `.gitlab-ci.yml` deploy

---

packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js

fix(gatsby-plugin-gatsby-cloud): don't add `undefined` to preload path if assetPrefix is falsy

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

Hello, 
Currently with both `latest` and `next` versions of `gatsby-plugin-netlify-cms` are not fully compatible with `react@18`, and throw an error. Also reproducible with [`gatsby-starter-netlify-cms
`](https://www.gatsbyjs.com/starters/netlify-templates/gatsby-starter-netlify-cms) if upgraded to `react@18`:
```
Package subpath './umd/react.production.min.js' is not defined
```
The issue seems to be related to how the plugin is utilizing the [`WebpackCopyPlugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) to copy the `umd` distribution of `react` and `react-dom`:
https://github.com/gatsbyjs/gatsby/blob/0809c20968713db91fb09a7e56aebc70aa111ea8/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L210-L222
With version 18 of `react` and `react-dom` the `exports` field has been …

fix(gatsby-plugin-netlify-cms): react18-compatible require resolve

---

integration-tests/node-manifest/__tests__/create-node-manifest.test.js
integration-tests/node-manifest/gatsby-node.js
integration-tests/node-manifest/package.json
integration-tests/node-manifest/utils/get-gatsby-process.js
packages/gatsby/src/utils/node-manifest.ts

Node Manifest files are used to tie a unique revision state of a piece of content in a data source to a gatsby page generated from that exact data. In some cases, this is causing upwards of 150K plus node manifest files to get written to disk which can cause performance degradation in certain cases.
This helps PR introduces a limit to the number of node manifest files written to disk during a gatsby build which can be controlled with the env var `NODE_MANIFEST_FILE_LIMIT`.
If the number of node manifests that are queued to get written to disk is greater than `NODE_MANIFEST_FILE_LIMIT`, then the node manifest "candidates" are sorted by their `updatedAtUTC` field timestamp. That sorted list of node manifests is used to queue up file writes file writes are then stopped as soon as the …

fix(gatsby): limit node manifest creation limit

---

e2e-tests/trailing-slash/cypress/integration/always.js
e2e-tests/trailing-slash/src/pages/index.js
packages/gatsby-link/src/rewrite-link-path.js

Modify relative links based on trailing slash option
Fixes #35419
[sc-49188]

fix(gatsby-link): modify relative links based on trailing slash option

---

packages/gatsby-transformer-screenshot/src/gatsby-node.js

With the current **4.12.1** version I get the following error message when building. This is due to the fact that during the migration from better-queue to fastq (#32941) the dependency was not completely replaced. In the package.json the dependency was replaced, but was probably forgotten in the file `gatsby-transformer-screenshot\gatsby-node.js`.
```
Error in ".\node_modules\gatsby-transformer-screenshot\gatsby-node.js": Queue.promise is not a function
TypeError: Queue.promise is not a function
- gatsby-node.js:14 Object.<anonymous>
[project-name]/[gatsby-transformer-screenshot]/gatsby-node.js:14:31
```

fix(gatsby-transformer-screenshot): finished migration from better-queue to fastq

---

packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js

hello there,
I found a cookie her [Plugin Options > presets[].options](https://github.com/gatsbyjs/gaatsby/edit/master/packages/gatsby-source-wordpress/docs/plugin-options.md)
```diff
{
resolve: `gatsby-source-wordpress`,
options: {
presets: [
{
-       name: `DEVELOP`,
+       presetName: `DEVELOP`,
useIf: () => process.env.NODE_ENV === `development`,
options: {
type: {
__all: {
limit: 1,
},
},
},
},
],
},
}
```
Fixes https://github.com/gatsbyjs/gatsby/issues/35453

chore(gatsby-source-wordpress): Fix typo in `presets[].options`

---

packages/gatsby-dev-cli/src/__tests__/watch.js
packages/gatsby-dev-cli/src/index.js
packages/gatsby-dev-cli/src/local-npm-registry/index.js
packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
packages/gatsby-dev-cli/src/utils/__tests__/get-dependant-packages.js
packages/gatsby-dev-cli/src/utils/__tests__/traverse-package-deps.js
packages/gatsby-dev-cli/src/utils/check-deps-changes.js
packages/gatsby-dev-cli/src/utils/get-monorepo-package-json-path.js
packages/gatsby-dev-cli/src/utils/traverse-package-deps.js
packages/gatsby-dev-cli/src/watch.js

Testing potential solution for `gatsby-dev-cli` issue encountered in https://github.com/gatsbyjs/gatsby/pull/35446 where new package is not being handled

fix(gatsby-dev-cli): use package name not directory name

---

docs/docs/how-to/previews-deploys-hosting/deploying-to-s3-cloudfront.md

The previous link was not working. I messaged the author and he provided me with the new location of the article on GitHub
The URL being updated is the very last item on the [Deploying to S3/CloudFront Documentation](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-s3-cloudfront/)
N/A

chore(docs):Update Link URL

---

e2e-tests/gatsby-script/cypress/integration/inline-scripts.ts
e2e-tests/gatsby-script/cypress/integration/scripts-with-sources.ts
e2e-tests/gatsby-script/cypress/support/index.ts
e2e-tests/gatsby-script/scripts.ts
e2e-tests/gatsby-script/src/components/script-mark-records.tsx
e2e-tests/gatsby-script/src/components/script-resource-records.tsx
e2e-tests/gatsby-script/src/pages/index.tsx
e2e-tests/gatsby-script/src/pages/inline-scripts.tsx
e2e-tests/gatsby-script/src/pages/scripts-with-sources.tsx
e2e-tests/gatsby-script/src/utils/on-load.ts
packages/gatsby-script/.eslintrc.yaml
packages/gatsby-script/src/__tests__/gatsby-script.tsx
packages/gatsby-script/src/gatsby-script.tsx

Implements the ability to use an `onLoad` callback for scripts with sources. Usage looks like:
```tsx
<Script
src={scripts.three}
strategy={ScriptStrategy.postHydrate}
onLoad={(event: Event) => { console.log(`Hello world`) }}
/>
```
Inline scripts do not support this behavior and we'll note that in later documentation PR(s).
It also includes two other things:
- A cache for scripts so that loading occurs only once in all the various navigation scenarios (see test cases)
- Handling for edge case of pre-hydrate scripts loaded after client side navigation (e.g. via Gatsby link). In this case it will be treated effectively the same as post-hydrate scripts. This is a temporary fix and we should explore better solutions
To be done in later PR(s).
[sc-48841]
[sc-49445]

feat(gatsby-script): On load callback, cache

---

e2e-tests/gatsby-script/cypress/integration/inline-scripts.ts
e2e-tests/gatsby-script/cypress/integration/scripts-with-sources.ts
e2e-tests/gatsby-script/src/pages/index.tsx
e2e-tests/gatsby-script/src/pages/inline-scripts.tsx
e2e-tests/gatsby-script/src/pages/scripts-with-sources.tsx
e2e-tests/gatsby-script/src/utils/callbacks.ts
e2e-tests/gatsby-script/src/utils/on-load.ts
packages/gatsby-script/src/gatsby-script.tsx

Implements the ability to use an onError callback for scripts with sources. Usage looks like:
```tsx
<Script
src={scripts.three}
strategy={ScriptStrategy.postHydrate}
onError={(event: Event) => { console.log(`Hello world`) }}
/>
```
**Limitations**
The `onError` callback works only for scripts with sources using the `post-hydrate` or `idle` strategies. It does not work with inline scripts.
To be included in a later PR(s).
[sc-49066]

feat(gatsby-script): On error callback

---

packages/gatsby-source-drupal/src/__tests__/fixtures/file.json
packages/gatsby-source-drupal/src/__tests__/index.js

Added a small unit test to make sure we're generating image CDN data

feat(gatsby-source-drupal): image cdn tests

---

docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md

I've recently discovered that my repositories have grown significantly (100s of MB in size), in big part because I was using the `gh-pages` packages to publish the builds. Other tools, for example [Travis CI GitHub deploy](https://docs.travis-ci.com/user/deployment/pages/), didn't have this issue. I discovered that it was because `gh-pages` doesn't force push by default. In the case of Gatsby where the source code is the only "truth" of history and the build is significant in size, I found it very useful to use the `-f`option by default. This is a first impulse/idea, let me know if you have comments, questions, and feel free to amend, reject etc this pull request.
- https://www.npmjs.com/package/gh-pages
- https://docs.travis-ci.com/user/deployment/pages/
```
%> gh-pages --help
Usage: …
```

chore(docs): Add note about optimizing GitHub publish

---

docs/docs/reference/release-notes/gatsby-version-support.md

Since we're targeting Q4 for the next major version, let's make sure the `until` dates for Gatsby 3 and 4 accurately reflect that.

chore(docs): Corrected the version end dates

---

packages/gatsby/src/utils/source-nodes.ts

This often means something went wrong during sourcing.

fix(gatsby): Improve warning when a source plugin doesn't create a node

---

starters/gatsby-starter-minimal-ts/tsconfig.json

While using our minimal starter I didn't see my global namespace working in `gatsby-node.ts` files. This was because the tsconfig didn't include those files by default.

chore(starters): Update `tsconfig.json`

---

docs/docs/how-to/local-development/gatsby-on-linux.md
packages/gatsby-transformer-excel/README.md

All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/

chore(docs): remove git.io urls

---

packages/gatsby-source-drupal/src/normalize.js
packages/gatsby-source-drupal/src/utils.js

This fixes a bug in the source-drupal Image CDN changes that just went out where inc builds may fail in some cases.

fix(gatsby-source-drupal): fix Image CDN optional chaining call

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/fetch-remote-file.ts

Fixes "Source and destination must not be the same" when a url is fetched twice with the same directory

fix(gatsby-core-utils): fix Source and destination must not be the same

---

packages/gatsby/src/commands/build.ts
packages/gatsby/src/utils/jobs/worker-messaging.ts

Currently during a build we await `waitUntilAllJobsComplete()` before restarting the worker pool. Because of [a race condition](https://github.com/gatsbyjs/gatsby/issues/35055#issuecomment-1112001208), this resolves before `JOB_COMPLETE` has been dispatched for the final job. In certain circumstances when running with a single worker, this would cause an EPIPE error where the parent would attempt to send `JOB_COMPLETE` to a worker that was in the process of shutting down.
This PR adds a counter, similar to the one used for `waitUntilAllJobsComplete`, but inside `worker-messaging`, directly tracking jobs that have been dispatched to the worker. We then await that too before restarting the pool.
I initially wanted to await it inside `waitUntilAllJobsComplete`, but importing anything from …

fix(gatsby): wait for worker jobs to complete

---

packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/transform-union.js

In union list fields `null` should not be returned for any item - but there's currently a WPGraphQL bug where null can be returned and that causes our resolver to throw errors. This PR protects against that.

fix(gatsby-source-wordpress): Prevent throwing errors when item is undefined

---

starters/default/src/pages/index.js

The footer links appended the same utm's twice. This update makes sure we only append the utm's once per link.

fix(starters): Remove duplicate UTM params

---

packages/gatsby/package.json
yarn.lock

Gatsby includes `event-source-polyfill` at this line: https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby/cache-dir/polyfill-entry.js#L4
Recent 1.0.26 release included [a change with possibly unwanted side-effects](https://github.com/Yaffle/EventSource/commit/de137927e13d8afac153d2485152ccec48948a7a). More details can be found in this HN post: https://news.ycombinator.com/item?id=30963600
Fixes https://github.com/gatsbyjs/gatsby/issues/35530

chore(gatsby): Pin event-source-polyfill

---

packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js

sometimes preview nodes do not have a slug - but some users will use slugs to build page urls. So we should make sure we have something for the slug.

feat(gatsby-source-wordpress): always include draft slugs

---

packages/gatsby-cli/src/structured-errors/error-map.ts

https://github.com/gatsbyjs/gatsby/issues/35589 shows that the message could be improved by directly pointing to https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#current-limitations

fix(gatsby): Better TS compilation error

---

packages/gatsby-source-contentful/src/create-schema-customization.js

I believe Image CDN for Contentful was only working on Gatsby core versions that didn't support Image CDN yet - via the polyfill. Because the RemoteFile interface wasn't added here.

fix(gatsby-source-contentful): Add RemoteFile interface

---

docs/docs/how-to/testing/unit-testing.md

The bug https://github.com/facebook/jest/issues/9771 was fixed in Jest 28 so updating our docs.

chore(docs): Update Unit Testing for Jest 28

---

packages/gatsby/index.d.ts

This PR fixes the Typescript Types for the headers in `GetServerDataReturn`. Using an actual map doesn't work and will be ignored by Gatsby, it needs to be an object. Details about this bug are described in this issue:
https://github.com/gatsbyjs/gatsby/issues/35527#issuecomment-1113254855

fix(gatsby): use correct types for the response headers

---

packages/gatsby-plugin-image/src/components/layout-wrapper.tsx

If the image is cached add extra line to also remove the opacity of the placeholder.
Fixes #35628

fix(gatsby-plugin-image): fix race condition

---

packages/gatsby-source-drupal/src/gatsby-node.js

I missed this when I added image cdn support to drupal

fix(gatsby-source-drupal): add placeholder style name plugin option to the options schema

---

packages/gatsby-script/src/gatsby-script.tsx
packages/gatsby/src/commands/serve.ts
packages/gatsby/src/internal-plugins/partytown/gatsby-browser.tsx
packages/gatsby/src/internal-plugins/partytown/gatsby-node.ts
packages/gatsby/src/internal-plugins/partytown/proxy.ts

`off-main-thread` scripts should be usable in `gatsby develop`
https://github.com/gatsbyjs/gatsby/pull/35647
[sc-50632]

feat(gatsby): Support for off-main-thread in develop

---

packages/gatsby-plugin-sitemap/README.md

In the Sitemap plugin; the `excludedRoute` param for filterPages says "Element from `exclude` Array"... it should say `excludes`.
And remove period at the end of that as I don't see others with one.
https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#filterPages
n/a

sitemap plugin readme has incorrect array name reference

---

e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-ssr-browser-apis.js
e2e-tests/development-runtime/gatsby-browser.js
e2e-tests/development-runtime/gatsby-script-scripts.js
e2e-tests/development-runtime/src/pages/gatsby-script-navigation.js
e2e-tests/development-runtime/src/pages/gatsby-script-ssr-browser-apis.js
e2e-tests/development-runtime/src/wrap-page-element.js
e2e-tests/development-runtime/src/wrap-root-element.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-ssr-browser-apis.js
e2e-tests/production-runtime/gatsby-browser.js
e2e-tests/production-runtime/gatsby-script-scripts.js
e2e-tests/production-runtime/gatsby-ssr.js
e2e-tests/production-runtime/src/pages/gatsby-script-navigation.js
e2e-tests/production-runtime/src/pages/gatsby-script-ssr-browser-apis.js
e2e-tests/production-runtime/src/wrap-page-element.js
e2e-tests/production-runtime/src/wrap-root-element.js

Co-authored-by: Jude Agboola <marvinjudehk@gmail.com>
Test `post-hydrate` and `idle` scripts in `wrapPageElement` and `wrapRootElement` in production and develop runtime e2e tests.
N/A
[sc-49168]

test(gatsby-script): SSR and browser APIs

---

packages/gatsby/index.d.ts

According to https://www.gatsbyjs.org/docs/actions/#createNode &
https://github.com/gatsbyjs/gatsby/blob/fd1d8ccc8dd27c316d24f91475a24702d228910c/packages/gatsby/src/redux/actions/public.js#L869-L888
the return signature of `createNode` should be a Promise instead of just a plain void.

fix(gatsby): correct the types of `createNode` action return

---

benchmarks/md/package.json
benchmarks/mdx/package.json
package.json
packages/gatsby-page-utils/package.json
packages/gatsby-plugin-offline/package.json
packages/gatsby-source-wordpress/package.json
packages/gatsby/package.json
yarn.lock

`glob@7.2.2` release was borked for Windows users (see https://github.com/gatsbyjs/gatsby/issues/35654 ). `glob@7.2.3` fixed that so this bump just tries to make it easier for users who already installed problematic version before `glob` had fixed version published (bumping transitive deps is always a pain)
Fixes https://github.com/gatsbyjs/gatsby/issues/35654
Upstream issues:
- https://github.com/isaacs/node-glob/issues/471
- https://github.com/isaacs/node-glob/issues/474

chore: bump glob to 7.2.3

---

e2e-tests/production-runtime/cypress/integration/assets.js

The `assets.js` e2e test can be flaky on the test that loads 2 different font files. This is an attempt to "deflake" it.
Example flaky test:
```
Running:  assets.js                                                                      (3 of 32)
Estimated: 0 seconds
webpack assets
1) should only create one font file (no duplicates with different hashes)
✓ should load image import (153ms)
✓ should load file import (143ms)
✓ should load static folder asset (124ms)
3 passing (991ms)
1 failing
1) webpack assets
should only create one font file (no duplicates with different hashes):
AssertionError: expected 'http://localhost:9000/static/merriweather-latin-300italic-fe29961474f8dbf77c0aa7b9a629e4bc.woff2' to match /merriweather-latin-300-/i
at Context.eval …
```

test(gatsby): Attempt to deflake assets.js e2e test

---

e2e-tests/production-runtime/cypress/integration/compilation-hash.js

I poked around this test a bit more and couldn't figure out the flakiness. It'll take a bit more investigation, but I think we should bump this one up a few more times. It shouldn't add more than 10s to the total runtime if all attempts fail.

test(gatsby): Give one compilation-hash test 2 more retries

---

e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js

React 18 sped up the time to `componentDidMount`, so we were hitting a flaky case more often. Waiting for a second after loading the page should give it more than enough time to make sure it's called.

test(gatsby): Add buffer time to failing react 18 e2e tests

---

e2e-tests/development-runtime/.gitignore
e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-inline-scripts.js
e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-scripts-with-sources.js
e2e-tests/development-runtime/gatsby-config.js
e2e-tests/development-runtime/package.json
e2e-tests/development-runtime/playwright.config.ts
e2e-tests/development-runtime/playwright/gatsby-script-off-main-thread.spec.ts
e2e-tests/development-runtime/src/pages/gatsby-script-off-main-thread.js
e2e-tests/development-runtime/src/pages/gatsby-script-scripts-with-sources.js
e2e-tests/production-runtime/.gitignore
e2e-tests/production-runtime/cypress/integration/gatsby-script-inline-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-scripts-with-sources.js
e2e-tests/production-runtime/gatsby-config.js
e2e-tests/production-runtime/package.json
e2e-tests/production-runtime/playwright.config.ts
e2e-tests/production-runtime/playwright/gatsby-script-off-main-thread.spec.ts
e2e-tests/production-runtime/src/pages/gatsby-script-off-main-thread.js
e2e-tests/production-runtime/src/pages/gatsby-script-scripts-with-sources.js
packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap

End-to-end tests for gatsby-script off-main-thread loading strategy.
[Partytown cannot be tested in Cypress](https://github.com/BuilderIO/partytown/issues/179), so we're using [Playwright](https://playwright.dev) instead.
I attempted to point Playwright to the Chrome executable in [our test Docker image](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node14.15.0-chrome86-ff82/Dockerfile) via the [`PLAYWRIGHT_BROWSERS_PATH` env var](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) but it looks like Playwright wants it in a *particular* directory, not just *any* directory.
For now we install the Chromium executable Playwright wants in a post install script in the prod/develop e2e tests. A better solution probably looks something like creating our …

test(gatsby-script): Off main thread e2e

---

packages/gatsby-page-utils/src/apply-trailing-slash-option.ts

It seems people link to `.xml` files (see https://github.com/gatsbyjs/gatsby/discussions/35680), so we'll just handle `.xml` and `.pdf` for now as those seem like common things to link to. Even though one shouldn't use `<Link />` for it (as a side-note).

fix(gatsby): Apply `never` trailing slash to xml & pdf

---

e2e-tests/production-runtime/cypress/integration/gatsby-script-scripts-with-sources.js
packages/gatsby-script/src/gatsby-script.tsx

Apply [`crossorigin="anonymous"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) to off-main-thread scripts by default.
N/A
N/A

feat(gatsby-script): Apply crossorigin anonymous to off-main-thread scripts

---

packages/gatsby-cli/src/create-cli.ts

Currently during `gatsby serve` `process.env.NODE_ENV` is `undefined` instead of `production` like we expect.
Attempted to create a serve integration test in https://github.com/gatsbyjs/gatsby/tree/master/integration-tests/gatsby-cli/__tests__, but due to [Jest setting NODE_ENV to test](https://jestjs.io/docs/environment-variables) I time boxed it and tested manually locally instead.
N/A
[sc-50871]

feat(gatsby-cli): Apply production node env to gatsby serve

---

.circleci/config.yml
packages/gatsby-dev-cli/README.md
packages/gatsby-dev-cli/src/index.js
packages/gatsby-dev-cli/src/local-npm-registry/index.js
packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
packages/gatsby-dev-cli/src/watch.js

https://github.com/yarnpkg/berry/issues/4443 won't be resolved soon. So we'll need to update our yarn pnp tests to not use portals anymore. With some modifications we can use `gatsby-dev-cli`.
[ch50764]
Unblocks https://github.com/gatsbyjs/gatsby/pull/35446

chore: `yarn_pnp` tests uses `gatsby-dev-cli` instead of portals

---

packages/gatsby/index.d.ts

https://github.com/gatsbyjs/gatsby/blob/e3d57c0fb8ab8a89b29fd613a519340574b1239a/packages/gatsby-cli/src/handlers/plugin-add-utils.ts#L36 in create-gatsby uses a key to correctly add multiple same plugins. It'll stay in the config unless removed, so it's valid but people can remove it.
This updates the types to add `__key`.
Fixes https://github.com/gatsbyjs/gatsby/issues/35706

chore(gatsby): Update `IPluginRefObject` type

---

e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-duplicate-scripts.js
e2e-tests/development-runtime/src/pages/gatsby-script-duplicate-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-duplicate-scripts.js
e2e-tests/production-runtime/src/pages/gatsby-script-duplicate-scripts.js
packages/gatsby-script/src/gatsby-script.tsx

Handles duplicate scripts (same `src`) with `onLoad`/`onError` callbacks. We expect them to execute despite the duplicate script not being added to the DOM.
Example case:
- Script A, comes first in the DOM and is injected
- Script B is a duplicate of Script A, comes second in the DOM and is not injected because it's a duplicate, but we handle its `onLoad`/`onError` callbacks
Behavior:
- If Script A has not yet executed `onLoad`/`onError`, we capture Script B's `onLoad`/`onError` callbacks so that when Script A's callbacks do execute, we also execute Script B's callbacks with the same event
- If Script A has already executed `onLoad`/`onError`, we have captured the event(s) from Script A's callback execution and execute Script B's callback(s) with the same event(s)
Will be added to …

feat(gatsby-script): Handle duplicate script callbacks

---

e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-duplicate-scripts.js
e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-inline-scripts.js
e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-scripts-with-sources.js
e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-ssr-browser-apis.js
e2e-tests/development-runtime/package.json
e2e-tests/development-runtime/src/pages/gatsby-script-duplicate-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-duplicate-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-inline-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-scripts-with-sources.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-ssr-browser-apis.js
packages/gatsby-script/src/gatsby-script.tsx

- Refactor script key caching slightly to only add to cache if id or src exists
- Ensure duplicate script callbacks are executed even if the first script does not have callbacks
- Adds `waitForRouteChange` to all `cy.visit` calls in script component tests because it seems to help reduce flakes when Cypress moves too fast before the page finishes loading
N/A
[sc-50935]

feat(gatsby-script): Duplicate script callbacks if no injected script callbacks

---

packages/gatsby-source-wordpress/src/gatsby-browser.ts

At some point html image hydration stopped working. Most likely this was due to Image CDN changes. I made some fixes here so it works again for React 17 and 18

fix(gatsby-source-wordpress): html image hydration for React 17 & 18

---

.github/workflows/schedule-stale.yml

GitHub asks developers to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows. 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve …

chore(stale-action): Add GitHub token permissions

---

docs/docs/how-to/performance/improving-site-performance.md
docs/docs/reference/built-in-components/gatsby-script.md

Documentation for the Gatsby script component.
Pages added:
- Gatsby script reference page - [Rendered file](https://github.com/gatsbyjs/gatsby/blob/42390799d500c3015b826eff84fd0c1b0a7227c6/docs/docs/reference/built-in-components/gatsby-script.md)
Pages modified:
- Improving site performance how to guide, section on loading third party scripts - [Rendered file](https://github.com/gatsbyjs/gatsby/blob/42390799d500c3015b826eff84fd0c1b0a7227c6/docs/docs/how-to/performance/improving-site-performance.md#step-2-use-the-gatsby-script-component-to-load-scripts-performantly)
[sc-48161]

chore(docs): Gatsby script component

---

docs/docs/how-to/testing/unit-testing.md
docs/docs/reference/release-notes/v4.15/index.md

`gatsby-script` is an ES module and it needs to be added to the `transformIgnorePatterns` key in user's Jest configs if they use Jest.
- Updates https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/#2-creating-a-configuration-file-for-jest
- Updates https://www.gatsbyjs.com/docs/reference/release-notes/v4.15/
Fixes #35736

chore(docs): Add gatsby-script to transformIgnorePatterns in Jest config

---

.yarnrc
yarn.lock

Some people, like me, use a custom registry when loading packages. Thats fun and nice, but when forgetting to reset this value, these custom registries might end up in our `yarn.lock`.
This ensures everyone is using `https://registry.yarnpkg.com` and removes all references to `https://registry.npmjs.org/`. (These probably have been added by myself at some point when I messed up resetting my config 🙈 )
With this change, we should reduce the LOC changed in PRs that update yarn.lock and use a different registry.

chore: clean up yarn.lock

---

e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-both-callbacks.js
e2e-tests/development-runtime/src/pages/gatsby-script-both-callbacks.js
e2e-tests/development-runtime/src/pages/gatsby-script-duplicate-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-both-callbacks.js
e2e-tests/production-runtime/src/pages/gatsby-script-both-callbacks.js
e2e-tests/production-runtime/src/pages/gatsby-script-duplicate-scripts.js
packages/gatsby-script/src/gatsby-script.tsx

Fix case where `onLoad` does not fire when both `onLoad` and `onError` callbacks are passed to the script component. Edge case that fell through the cracks since the e2e tests tested `onLoad` and `onError` cases separately.
N/A
[sc-51154]

fix(gatsby-script): Make load callback work when both load and error callbacks defined

---

docs/docs/reference/built-in-components/gatsby-script.md

Miscellaneous improvements to the Gatsby Script reference documentation. See the changes [rendered](https://github.com/gatsbyjs/gatsby/blob/28f219787bcc7bb9bca9a519130a07e1a27c1800/docs/docs/reference/built-in-components/gatsby-script.md).
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-script/

chore(docs): Improve gatsby-script reference docs

---

docs/docs/how-to/images-and-media/working-with-video.md

Fix the mismatch between the videoSrcURL prop and the videoSourceURL markdown key.
Fix the mismatch between the videoSrcURL prop and the videoSourceURL markdown key in the markdown example in the working with video doc.
Fixes #35750

chore(docs): Fix `videoSourceURL` markdown key mismatch

---

benchmarks/gabe-fs-mdx/src/templates/blog-post.js
packages/gatsby-plugin-mdx/src/gatsby-node.ts

For now, we won't have any compiled MDX code in GraphQL. This removes the (unfinished) resolved that added compiled MDX.

mdx-v2: remove mdx from graphql

---

packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
packages/gatsby/src/schema/graphql-engine/print-plugins.ts

With current setup for engine bundling we first run asset relocator before removing exports we don't need. In best case it's wasteful, in worst case the surface area for asset relocator increases and users are hitting problems because of code in unrelated lifecycles that don't play well with asset relocator.
Example code snippet that will cause problems when generating engines today:
```
exports.onPreBootstrap = () => {
const someFilePath = `${__dirname}/package.json`
console.log({ someFilePath })
}
```
Result in following error when validating:
```
Error: Module parse failed: Unexpected token (92:23)
File was processed with these loaders:
* ./node_modules/@vercel/webpack-asset-relocator-loader/dist/index.js
* ./node_modules/gatsby/dist/schema/graphql-engine/webpack-remove-apis-loader
.js …
```

fix(gatsby): remove exports first before using asset relocator

---

integration-tests/functions/test-helpers.js
packages/gatsby/src/internal-plugins/functions/middleware.ts

The samples we have for forcing Raw body currently don't always work (in particular if request payload is `application/json` type, we would still use `.json()` body parser).
This prioritize `.raw()` parser so it is first middleware that can handle a request body as this is the most common use case for changing types in default config.
Note that users could workaround this with something like snippet below before this change:
```
export const config = {
bodyParser: {
// expected - we have those in our examples
raw: { type: `*/*` },
// un-expected
json: { type: `something-that-will-never-match-hack` },
text: { type: `something-that-will-never-match-hack` },
urlencoded: { type: `something-that-will-never-match-hack`, extended: true },
}
}
```
Ideally we expand documentation with more details …

fix(function): prioritize raw body parser

---

packages/gatsby/src/utils/webpack-utils.ts

Remove `removeOffCanvasPaths` optimisation, which has known issues: https://github.com/svg/svgo/issues/1646.
This is not enabled by default in SVGO, so there is more risk, because such optimizations are less widely tested

fix(gatsby): Remove `removeOffCanvasPaths` svgo option

---

docs/tutorial/building-a-theme.md

Signed-off-by: Josh Cox <josh@webhosting.coop>
Addressing my own issue, along with the suggested updates from @tyhopp 
Update references to `data` directory in filesystem source plugin snippets to be real paths.
Updates https://www.gatsbyjs.com/tutorial/building-a-theme/
Resolves #35784

chore(docs): Update outdated building a theme tutorial snippets

---

e2e-tests/development-runtime/cypress/integration/hot-reloading/new-file.js
packages/gatsby-plugin-sharp/src/image-data.ts

Caches image metadata between builds
Currently gatsby-plugin-sharp uses an in-memory cache to store image metadata during a build, but it is not persisted between builds. This means that the relatively expensive dominant color calculations need to be re-done each time. This PR switches to use the `GatsbyCache` if it is available, falling back to the in-memory cache otherwise. In my tests, this saved over a minute for warm-cache builds of a site with 100 images.

feat(gatsby-plugin-sharp): cache image metadata

---

packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js

Check the `pluginOptions.type.MediaItem.exclude` before fetching referenced media items during page updates
Fixes #35460

fix(gatsby-source-wordpress): bug patch for issue 35460

---

docs/docs/reference/graphql-data-layer/schema-customization.md

This updates a typo in the docs where they were suggesting people use the `_typeName` field, when it should actually be lowercase `_typename`

fix(docs): Lowercase typename

---

packages/gatsby-plugin-sharp/src/image-data.ts

Downsize the input image before calculating the dominant color
When calculating the dominant color for the default image placeholder, we use sharp's `stats()` function. sharp uses the input image for its calculations, which gives the most accurate result, but can be very slow to calculate for large images. This PR instead resizes the image to the default blurred placeholder size, and uses that to calculate the dominant color. This may be a less accurate respresentation, but it is Good Enough for a placeholder that is only seen for a second or so at most.
In my tests running on an M1 mac mini, on a selection of source images around 10MP in size, this took around 40% of the time as the status quo.

perf(gatsby-plugin-image): downsize image before extracting dominant color

---

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
packages/babel-plugin-remove-graphql-queries/src/index.ts
packages/gatsby-worker/src/__tests__/integration.ts
packages/gatsby/src/bootstrap/__tests__/__snapshots__/resolve-module-exports.ts.snap
packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
yarn.lock

This blocks our current renovate PRs as they run `yarn-deduplicate` and with that there is a type error and snapshot updates that needs fixing.

chore: De-Duplicate lock file

---

.jestSetup.js
packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
packages/gatsby-source-wordpress/__tests__/process-node.test.js
packages/gatsby/index.d.ts
packages/gatsby/src/redux/actions/internal.ts
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/index.ts
packages/gatsby/src/redux/reducers/index.ts
packages/gatsby/src/redux/reducers/queries.ts
packages/gatsby/src/redux/reducers/telemetry.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/worker/__tests__/queries.ts
packages/gatsby/src/utils/worker/child/queries.ts
packages/gatsby/src/utils/worker/pool.ts

This gives us a way to count the number of unique Image CDN source urls that are processed during a gatsby build. The one downside being that we cannot include images from pages that use SSR or DSG since those are not processed during the initial build.
- Source URL's are added to a new object in the store called `telemetry` and stored in the `gatsbyImageSourceUrls` JS Set inside of that. (i.e. source URL's are added to `telemetry.gatsbyImageSourceUrls`)
- I chose to use a Set for this since we only want to store unique values which Set does this by default
- Adds an action / reducer case to clear this set so that the Inc Build CLI can clear this piece of Gatsby state after it reads it and reports it back to BigQuery / Gatsby Cloud
- Source URL's are added only if …

feat(gatsby, gatsby-plugin-utils): add image cdn source urls to redux

---

docs/docs/how-to/custom-configuration/typescript.md

chore(docs): Remove `__dirname` limitation from TS doc

---

docs/docs/how-to/testing/testing-react-components.md

Add missing information about installation in the [Testing React Components page](https://www.gatsbyjs.com/docs/how-to/testing/testing-react-components/).
The documentation for Testing React Components has incomplete information about installation when using the latest version of Jest.
The documentation mentions that for Jest 27,  you need to set the `testEnvironment` in `jest.config.js` to `jsdom`,  in order for React Testing Library to work properly. However, Jest 28 [removed the jest-environment-jsdom module](https://jestjs.io/blog/2022/04/25/jest-28#breaking-changes), so you now need to install it separately if you are using Jest 28 or higher (as confirmed by the [react-testing-library docs](https://testing-library.com/docs/react-testing-library/setup/#jest-28)). As a result, if you …

chore(docs): Add Jest 28 `jest-environment-jsdom` information

---

docs/docs/reference/built-in-components/gatsby-script.md

Add section to Gatsby script reference doc about using `resolveUrl`. Includes a common example use case about tag managers.
Also adds a prominent note explaining why the `off-main-thread` strategy is experimental.
Updates https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-script/
[sc-51763]

chore(docs): Add resolveUrl section to gatsby-script docs

---

packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-transformer-documentationjs/src/__tests__/fixtures/code.jsx
packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js
packages/gatsby-transformer-documentationjs/src/gatsby-node.js

Adds support for jsx files in `gatsby-transformer-documentationjs`.
Used the [sample site](https://github.com/kieuvyn12/gatsby-bug-reproduction) provided by @kieuvyn12 to validate the fix.
Fixes #35842

fix(gatsby-transformer-documentationjs): Support jsx

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
packages/gatsby/src/schema/graphql-engine/shims/ts-node.js
packages/gatsby/src/schema/graphql-engine/standalone-regenerate.ts

When something like this:
```js
require(`ts-node`).register({
compilerOptions: {
module: `commonjs`,
target: `es2017`,
},
})
```
is used inside `gatsby-node` (or other files bundled by engines), it results in failing validation:
```
Error: Generated engines use disallowed import "/usr/src/app/www/node_modules/  typescript/lib/typescript.js". Only allowed imports are to Node.js builtin mod  ules or engines internals.
```
~We don't actually need to functionality of `ts-node/register` (or likely any "register" of this kind - `@babel/register`, `@parcel/register`, `pirates` etc) because we are bundling things so we can apply transformation those packages/modules do at compilation time.~
~The part that I'm yet to figure out is how to honor `register()` options in our compilation - with PR …

fix(gatsby): show meaningful error message when engines try to bundle ts-node

---

packages/gatsby-source-drupal/README.md

Document in the README how to use a custom header from `gatsby-config.js` to specify a media type for Drupal JSON API. This can fix `406 Not Acceptable` errors.
Affects only docs.

chore(gatsby-source-drupal): Document fix for 406

---

packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts
packages/gatsby/src/utils/graphql-typegen/utils.ts

Small QoL improvement, see [#35420 (comment)](https://github.com/gatsbyjs/gatsby/discussions/35420?sort=new#discussioncomment-2839418)
Sorts the `documents` given to the TS Codegen so that the output `gatsby-types.d.ts` has the same order and thus when people commit it less random diff on changes.

fix(gatsby): Stabilize types output of GraphQL Typegen

---

packages/gatsby-link/.babelrc
packages/gatsby-page-utils/.babelrc
packages/gatsby-plugin-canonical-urls/.babelrc
packages/gatsby-plugin-canonical-urls/src/gatsby-browser.js
packages/gatsby-plugin-canonical-urls/src/gatsby-ssr.js
packages/gatsby-plugin-catch-links/.babelrc
packages/gatsby-plugin-catch-links/src/gatsby-browser.js
packages/gatsby-plugin-facebook-analytics/.babelrc
packages/gatsby-plugin-page-creator/.babelrc

Make sure we don't use browser compilation for node packages, this keeps async await etc.

fix: use proper babelrc configs for compiling packages

---

packages/babel-preset-gatsby-package/lib/__tests__/__snapshots__/index.js.snap
packages/babel-preset-gatsby-package/lib/index.js
packages/babel-preset-gatsby-package/package.json
packages/gatsby-cli/package.json
packages/gatsby-cli/rollup.config.js
packages/gatsby/src/bootstrap/requires-writer.ts
packages/gatsby/src/utils/changed-pages.ts
packages/gatsby/src/utils/sanitize-node.js

We're using a lot of lodash and it's a 500kb library. It's also used in DSG & SSR. By using this module we reduce the DSG/SSR engine.
I have to patch INK to make this work 100%, i'll do that in a follow up PR. Nonetheless it's a good idea.

chore: reduce lodash usage

---

docs/docs/how-to/local-development/graphql-typegen.md

Fix query type name in [GraphQL Typegen guide](https://www.gatsbyjs.com/docs/how-to/local-development/graphql-typegen/#using-the-autogenerated-queries-types) from `Queries.TypegenPage` to `Queries.TypegenPageQuery`
In the GraphQL Typegen guide, the query type name is listed as `Queries.TypegenPage`, but it actually should be `Queries.TypegenPageQuery` (as illustrated in the [example repo](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-graphql-typegen/src/pages/index.tsx)). As it is now, following the guide will produce a TS error:
`Namespace 'Queries' has no exported member 'TypegenPage'`
This PR changes the example type name from  `Queries.TypegenPage` to `Queries.TypegenPageQuery`

chore(docs): fix query type name in Typegen guide

---

packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts

This fixes engine compilation in case there is more than one `babel-loader` / `@babel/preset-typescript` in dependencies when using Yarn PnP. (this can happen when using f.e. storybook side-by-side with gatsby, it doesn't have to be direct dependency)
[ch52154]

fix(gatsby): resolve babel-loader and @babel/preset-typescript before passing to webpack

---

docs/docs/creating-and-modifying-pages.md

The document https://www.gatsbyjs.com/docs/creating-and-modifying-pages/ has an outdated section about trailing slashes: https://www.gatsbyjs.com/docs/creating-and-modifying-pages/#removing-trailing-slashes
This is not necessary anymore as there is now an option to change that behavior: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#trailingslash
Removed that section and added a link to trailingSlashes option

chore(docs): Remove trailing slashes section in creating-and-modifying-pages

---

e2e-tests/production-runtime/gatsby-node.ts
packages/gatsby/index.d.ts
packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts

First commit show a problem with current setup:
```
failed Validating Rendering Engines - 0.942s
error Built Rendering Engines failed validation failed validation.
Please open an issue with a reproduction at https://github.com/gatsbyjs/gatsby/issues/new for more help
Error: Module build failed (from ./node_modules/gatsby/dist/schema/graphql-eng  ine/webpack-remove-apis-loader.js):
SyntaxError: unknown: Unexpected token, expected "from" (5:12)
3 | import { createContentDigest } from [  32m"gatsby-core-utils"
4 | import { addRemoteFilePolyfillInterface } f  rom "gatsby-plugin-utils/polyfill-remote-file"
> 5 | import type { GatsbyNode   } from "gatsby"
|             ^
6 |
7 | export const onPreBootstrap:   GatsbyNode["onPreBootstrap"] = () =>   {
8 |   fs.copyFileSync(
```
(pasted from …

fix(gatsby): apply ts transformation before removing exports for gatsby-node.ts for engines

---

docs/docs/how-to/styling/tailwind-css.md

I'm dramatically reducing the Tailwind CSS guide to what it should really be. We had the maintenance burden of showing multiple ways of using it + multiple versions. That's not our job, we should just point to the official docs and highlight the specifics we have to comment on, namely now `content` quirks inside `tailwind.config.js`.
[View Rendered](https://github.com/gatsbyjs/gatsby/blob/docs/tailwindcss-typegen/docs/docs/how-to/styling/tailwind-css.md)
Fixes https://github.com/gatsbyjs/gatsby/issues/35775

chore(docs): Clean up Tailwind CSS guide

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/utils/parcel/compile-gatsby-files.ts

Sometimes Parcel (cache?) gets in a weird state where it doesn't output compiled files anymore, but the compilation itself doesn't report any errors (?).
This adds validation checks and retry mechanism in case we hit that problem.
Some notes / thoughts:
We do remove any compiled files from our output dir before running Parcel ( to get rid of potentially stale files from previous builds ) - can this be a factor in this behaviour we are seeing? It works most of the time, so it would seem like it's not a complete "no-no", but might be part of why this happens, sometimes.
We could instead maybe remove files that were not bundled in current run, but then it would mean that we potentially might use stale compiled files if there are other reasons for Parcel not outputting those files 🤷 …

fix(gatsby): add retry mechanism for gatsby-node/config.ts compilation

---

packages/gatsby-parcel-config/CHANGELOG.md
packages/gatsby-script/CHANGELOG.md

Our nightly cronjob to update the changelogs was failing on:
- `gatsby-parcel-config` didn't have a CHANGELOG
- `gatsby-script` was missing entries that the script wanted to reference
See run: https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/83628/workflows/9fb61310-783b-4a72-ad96-71a25106c247/jobs/996869
Manually fixed both things now and CI should be happy next run.

chore(changelog): Add gatsby-parcel-config & update gatsby-script

---

docs/docs/how-to/performance/improving-build-performance.md

In #35702, we added flexibility for only polyfilling es6 modules when needed. This adds a section to our build performance doc explaining how to take advantage of this speed increase.
[sc-51371]

chore(docs): Update build performance doc to include browserslist config for faster builds

---

integration-tests/functions/package.json
integration-tests/functions/src/api/ignore-lmdb-require.js
integration-tests/functions/test-helpers.js
packages/gatsby/src/internal-plugins/functions/gatsby-node.ts

Fixes issue with the latest `lmdb` version that attempts to `require('bun:ffi')`, causing webpack to throw:
```
ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "bun:ffi" is not handled by plugins (Unhandled scheme).
```
Commit in `lmdb` - https://github.com/kriszyp/lmdb-js/commit/d0b34e378b484eeb062760230afa6dcfc8cde8b9#diff-eaeaef20374135190e0d86b94c44d3bce6e01fe6081d849d72791166b2bc60f2
We observed this error when importing `gatsby-core-utils` (which lists `lmdb` as a dep) in a Gatsby Function.
This PR ignores `lmdb` requires entirely in Gatsby function bundling since [we do not support bundling native deps in functions](https://www.gatsbyjs.com/docs/reference/functions/getting-started/#limitations), and warns if a require attempt is made.
N/A
[sc-52335]

fix(gatsby): Ignore lmdb requires in function bundling

---

packages/gatsby/src/internal-plugins/partytown/gatsby-node.ts

toPath doesn't need to be encoded as its just being passed as data
encodedURL must be encoded using encodeURIComponent as it is being used in a component of a URI

fix(gatsby): Partytown URI encoding of redirect parameters

---

packages/gatsby-plugin-mdx/package.json
packages/gatsby-plugin-mdx/src/compile-mdx.ts
packages/gatsby-plugin-mdx/src/error-utils.ts
packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts
packages/gatsby-plugin-mdx/src/gatsby-mdx-loader.ts
packages/gatsby-plugin-mdx/src/gatsby-node.ts
packages/gatsby-plugin-mdx/src/get-source-plugins-as-remark-plugins.ts
packages/gatsby-plugin-mdx/src/index.ts
packages/gatsby-plugin-mdx/src/plugin-options.ts
packages/gatsby-plugin-mdx/src/rehype-metadata-extractor.ts
packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts
packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
packages/gatsby-plugin-mdx/src/remark-path-prefix-plugin.ts
packages/gatsby-plugin-mdx/src/types.ts
packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-autolink-headers/src/__tests__/index.js
packages/gatsby-remark-autolink-headers/src/index.js
yarn.lock

Work in progress. This will generate ToC & excerpt, but will fail on wesbos website due to unrelated pageQuery issues

feat(gatsby-plugin-mdx): add ToC and excerpt support

---

.circleci/config.yml
integration-tests/head-function-export/.gitignore
integration-tests/head-function-export/README.md
integration-tests/head-function-export/__tests__/ssr-html-output.js
integration-tests/head-function-export/gatsby-config.js
integration-tests/head-function-export/jest-transformer.js
integration-tests/head-function-export/jest.config.js
integration-tests/head-function-export/package.json
integration-tests/head-function-export/shared-data/head-function-export.js
integration-tests/head-function-export/src/components/head-function-export.js
integration-tests/head-function-export/src/pages/404.js
integration-tests/head-function-export/src/pages/head-function-export/basic.js
integration-tests/head-function-export/src/pages/head-function-export/page-query.js
integration-tests/head-function-export/src/pages/head-function-export/re-exported-function.js
integration-tests/head-function-export/src/pages/head-function-export/static-query-component.js
integration-tests/head-function-export/src/pages/index.js

Test that the head elements actually end up in the SSR'ed HTML.
The production-runtime e2e test does the same but in the browser, and we want to make sure that we're not being tricked by the browser runtime inserting head elements.
N/A
[sc-52563]

test(head-function-export): Ensure head elements in SSR'ed HTML

---

packages/gatsby/src/schema/__tests__/queries.js

Test added in https://github.com/gatsbyjs/gatsby/pull/35369 currently fail because https://github.com/gatsbyjs/gatsby/pull/35947 also happened between opening first PR and merging it. This just adjust test setup to work.

test(gatsby): fix tests setup for queries after using babel-plugin-lodash

---

integration-tests/ssr/__tests__/ssr.js
integration-tests/ssr/src/pages/head-function-export.js

Make sure head function export works in DEV_SSR mode. Test is failing but should pass once we duplicate changes made in `static-entry` to `ssr-develop-static-entry`.
N/A
[sc-52407]

test(head-function-export): Test in DEV_SSR mode

---

renovate.json5
scripts/renovate-config-generator.js

With our current configuration renovate creates separate PRs for `gatsby` and `gatsby-core-utils` (see https://github.com/gatsbyjs/gatsby/pull/36034) to upgrade `lmdb`. We should align those versions by grouping `lmdb` (similar to e.g. Parcel https://github.com/gatsbyjs/gatsby/pull/36036/)

chore(renovate): Move lmdb into its own group

---

packages/gatsby/src/redux/actions/public.js

Fixes issue we've seen where a user provides objects that are not serializable by v8 (e.g. a `Promise`) in `createPages`, and as a result experienced failed builds.
Re-uses the `sanitizeNode` util we use to sanitize nodes to now also sanitize page state.
N/A
[sc-52897]
- Using `benchmarks/create-pages` benchmark project
- 1000 pages
- Added junk context object with breadth ~100 and depth ~20
- 5 runs each
TLDR (5 runs averaged)
Master - Average build time is 59.31 seconds
With sanitization - Average build time is 57.73 seconds
Master - Average heapUsed is 1,144,850,710.4 bytes
With sanitization - Average heapUsed is  1,033,399,563.2 bytes
---
All runs
```
success createPages - 7.339s
success extract queries from components - 3.576s
success Building production JavaScript and CSS bundles - …
```

feat(gatsby): Sanitize redux page state

---

packages/gatsby/cache-dir/static-entry.js

Currently if an error occurs in `renderToPipeableStream` the build process stalls. This this will throw the error and allow the main process to display it.
N/A
[sc-52995]
Fixes https://github.com/gatsbyjs/gatsby/issues/36075

fix(gatsby): Show error, exit process on SSR error

---

packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/ssr-develop-static-entry.js

We are getting hydration issues IF timing wise we decide to render loading indicator (aka preperessing resources take longer than 1 second). The problem is because we re-use `renderer` to render indicators, and we set `renderer` to use `hydrate` based on wether html is there for the site - if the content is there and we want to use `hydrate` on the page content, we will also use `hydrate` on indicators. This moves the logic dictating wether to use `render` or `hydrate` to internals of our `renderer` function.
It also adjusts DEV_SSR slightly to not generate router wrapper div if we will render "client-only" page, so we don't need extra special case - this means that DEV_SSR (for client-only pages) will produce just:
```
<div id="___gatsby"></div>
```
instead of
```
<div id="___gatsby"> …
```

fix(gatsby): hydration issues when load is low enough to show indicator

---

docs/docs/how-to/testing/unit-testing.md

After upgrading to Gatsby 4.18 all tests using Gatsbys <Link> component started to fail. Link is ESM now, too.
Fixes https://github.com/gatsbyjs/gatsby/issues/36079

chore(docs): Add `gatsby-link` to `transformIgnorePatterns`

---

docs/docs/how-to/testing/unit-testing.md

When I run `jest` with the proposed configuration I get this warning:
● Deprecation Warning:
Option "testURL" was replaced by passing the URL via "testEnvironmentOptions.url".
Please update your configuration.
Configuration Documentation:
https://jestjs.io/docs/configuration

chore(docs): update jest.config.js

---

packages/gatsby-parcel-namer-relative-to-cwd/package.json

Move to deps to hopefully fix some dependency weirdness that might happen as seen in https://github.com/gatsbyjs/gatsby/issues/35952
https://github.com/gatsbyjs/gatsby/issues/35952
[ch53025]

fix(parcel-namer-relative-to-cwd): move @parcel/namer-default from peerDeps to deps

---

packages/gatsby-graphiql-explorer/src/app/__tests__/snippets.js
packages/gatsby-graphiql-explorer/src/app/snippets.js

Amend Code Exporter Page Query GraphQL query in `gatsby-graphiql-explorer`
- Rename Component to `Page` from `ComponentName` for Page Query only
- Add condition to only replace query if it has no `name`. 
The following query in GraphiQL... 
```graphql
query MyQuery($id: String) {
sitePage(id: {eq: $id}) {
path
}
}
```
Should export as... 
```graphql
export const query = graphql`
query MyQuery($id: String) {
sitePage(id: {eq: $id}) {
path
}
}
`
```
Not like this. 
```graphql
export const query = graphql`
{
sitePage(id: {eq: $id}) {
path
}
}
`
```
Here's an example of the full Page Query with this change.
```javascript
import React from "react"
import { graphql } from "gatsby"
const Page = ({ data }) => <pre>{JSON.stringify(data, null, 4)}</pre>
export const query = graphql`
query …
```

feat(gatsby-graphiql-explorer): Amend Query name if available

---

e2e-tests/development-runtime/cypress/integration/head-function-export/html-insertion.js
e2e-tests/development-runtime/cypress/integration/head-function-export/navigation.js
e2e-tests/development-runtime/cypress/integration/head-function-export/warnings.js
e2e-tests/development-runtime/shared-data/head-function-export.js
e2e-tests/development-runtime/src/components/head-function-export.js
e2e-tests/development-runtime/src/pages/head-function-export/basic.js
e2e-tests/development-runtime/src/pages/head-function-export/warnings.js
e2e-tests/production-runtime/cypress/integration/head-function-export/html-insertion.js
e2e-tests/production-runtime/cypress/integration/head-function-export/navigation.js
e2e-tests/production-runtime/shared-data/head-function-export.js
e2e-tests/production-runtime/src/components/head-function-export.js
e2e-tests/production-runtime/src/pages/head-function-export/basic.js
integration-tests/head-function-export/__tests__/ssr-html-output.js
integration-tests/head-function-export/shared-data/head-function-export.js
integration-tests/head-function-export/src/components/head-function-export.js
integration-tests/head-function-export/src/pages/head-function-export/basic.js
packages/gatsby/cache-dir/head/constants.js
packages/gatsby/cache-dir/head/utils.js

Allow `script` tag for e.g. JSON-LD usage

fix(gatsby): Allow script in Gatsby Head

---

docs/docs/mdx/writing-pages.md

I'm learning Gatsby, and I stumbled on an outdated link in the docs.
The link is found at this URL:
https://www.gatsbyjs.com/docs/mdx/writing-pages/
And within this block of text:
> You can read more about using React components from other libraries in the [Importing and Using components in MDX guide](https://www.gatsbyjs.com/docs/how-to/routing/mdx/importing-and-using-components/).
I updated the link's URL path, so that it now points to the correct location.

chore(docs): fix outdated link

---

packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
packages/gatsby-source-contentful/src/source-nodes.js

This is similar to a change I made to gatsby-source-drupal which also saved significant time https://github.com/gatsbyjs/gatsby/pull/33419

feat(gatsby-source-contentful): skip expensive touchNode step when unnecessary

---

packages/gatsby/cache-dir/__tests__/static-entry.js
packages/gatsby/cache-dir/static-entry.js

In https://github.com/gatsbyjs/gatsby/pull/34030 meta tags were sorted/moved in front of e.g. `<style>` tags. But the order of those meta tags was also reversed.
This PR fixes it.
Fixes https://github.com/gatsbyjs/gatsby/issues/35818

fix(gatsby): Keep order in moved meta tags

---

e2e-tests/production-runtime/cypress/integration/head-function-export/use-location.js
e2e-tests/production-runtime/shared-data/head-function-export.js
e2e-tests/production-runtime/src/pages/head-function-export/page-with-uselocation.js
packages/gatsby/cache-dir/head/head-export-handler-for-browser.js

Wrap `Head` with `LocationContext.Provider`  to allow hooks or components that depends on `LocationContext.Provider` to work ( e.g `useLocation`)

fix(gatsby): Wrap Head with <Location>

---

packages/gatsby-plugin-react-helmet/README.md
packages/gatsby-plugin-react-helmet/src/gatsby-node.js

Points people to the new Gatsby Head API
[ch52560]

chore(gatsby-plugin-react-helmet): Add deprecation notice

---

packages/gatsby-plugin-image/src/components/hooks.ts

Uses `<Partial>` so that not full `Node` is necessary. Otherwise people would need to type their results fully. Also allow `null` because our graphqlTypegen feature creates `gatsbyImageData: import('gatsby-plugin-image').IGatsbyImageData } | null`
Fixes https://github.com/gatsbyjs/gatsby/issues/35748
[ch53435]

fix(gatsby-plugin-image): Correct type for getImage

---

packages/gatsby-source-wordpress/docs/features/gatsby-link.md
packages/gatsby-source-wordpress/docs/plugin-options.md
packages/gatsby-source-wordpress/gatsby-config.js
packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js

This PR makes the following true:
Because links in html fields are so common in WordPress, `gatsby-source-wordpress` auto-installs `gatsby-plugin-catch-links` for you. In 99% of cases this works well, but for some sites you may need to configure catch-links yourself. You can disable the automatically included version of `gatsby-plugin-catch-links` by setting the environment variable `WORDPRESS_CATCH_LINKS` to a string of `false`. Once it's disabled you can install it yourself and configure it's plugin options in your gatsby-config.js

feat(gatsby-source-wordpress): use env var to disable catch links

---

packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js

Prevent auto escaping of textContent for <script>  tags. 
[See Discussion](https://github.com/gatsbyjs/gatsby/discussions/35841#discussioncomment-3179192)
https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/#rich-snippets
[sc-53448]

fix(gatsby): prevent escaping textContent for scripts

---

docs/docs/reference/built-in-components/gatsby-link.md

My goal ist do add some content that will allow me to search for history.back and navigate(-1) and find _anything_. Right now, this can only be figured out by trial and error.
This section is kept very brief. I wanted to reference the `navigate(-1)` solution but also hint at its limitations (the way I understand them right now… there might be a better way to check if there actually is a prev page (that is on my site)).
This it the solution I am adding to https://github.com/FixMyBerlin/fixmy.safetycheck right now (currently in a branch).
None

chore(docs): Add section about `navigate(-1)`

---

packages/gatsby-link/package.json

`index.d.ts` was missing from `files` key.
Fixes https://github.com/gatsbyjs/gatsby/issues/36198

fix(gatsby-link): Publish types

---

packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/public-resolver.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts

When using gatsby develop/serve or non image cdn, urls with spaces etc would give a non working image/file.

fix(gatsby-plugin-utils): fix encoding issue for image-cdn

---

docs/docs/how-to/testing/unit-testing.md

When `@babel/preset-typescript` is not installed, the preprocessing from Jest will fail, if `jest-preprocess.js` is defined as described.

chore(docs): Add dependency for TypeScript testing

---

docs/docs/how-to/styling/using-local-fonts.md

The original note was a bit confusing and needed at least a comma.
Single line change to online documentation.

chore(docs): Clarify note in "local font" how-to

---

docs/tutorial/remark-plugin-tutorial.md

If one were to follow this tutorial for building a [Remark transformer plugin](https://www.gatsbyjs.com/tutorial/remark-plugin-tutorial/), they may get an error
> Must use import to load ES Module: gatsby-config.js
require() of ES modules is not supported.
It's because the plugin in the demo uses newer versions of `unist-util-visit`, which is an ESM module.
There are many workarounds for this, but I think within the context of learning to build a plugin, downgrading `unist-util-visit` to old versions that use Commmon JS is serviceable.

chore(docs): Instruct to install v2 of `unist-util-visit` in remark tutorial

---

docs/docs/reference/built-in-components/gatsby-head.md

Adds usage note to the Head API documentation that using with `react-helmet`  can cause unexpected results.
Documents #36193

chore(docs): Add `react-helmet` note in Gatsby Head reference

---

packages/gatsby-link/src/rewrite-link-path.js
packages/gatsby/package.json
yarn.lock

Apparently Storybook can't handle that import, so I released a new version of reach-router https://github.com/gatsbyjs/reach-router/commit/184547a5c41d869baf98c683dda32fefc0c697ab to export it from the package.
Relates to https://github.com/gatsbyjs/gatsby/issues/36210

fix(gatsby-link): Update resolve import

---

packages/create-gatsby/src/questions/features.json

Remove `gatsby-plugin-react-helmet` and associated dependencies from `create-gatsby` since [Head API is](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/) now GA
[sc-53434]

chore(create-gatsby): Remove gatsby-plugin-react-helmet

---

e2e-tests/path-prefix/cypress/integration/navigate.js
e2e-tests/path-prefix/cypress/integration/path-prefix.js
e2e-tests/path-prefix/package.json
e2e-tests/path-prefix/scripts/serve.js
e2e-tests/path-prefix/src/pages/index.js
e2e-tests/path-prefix/src/pages/ssr.js
packages/gatsby/src/commands/serve.ts

Start with failing test and SSR page to `path-prefix` e2e tests and couple of assertions, will be followed by a fix to make it green
Fixes #35406

fix(gatsby): use pathPrefix for SSR/DSG page-data requests with `gatsby serve`

---

starters/gatsby-starter-minimal-ts/src/pages/index.tsx

This is a copy of https://github.com/gatsbyjs/gatsby-starter-minimal-ts/pull/2 which was opened by a community member.

fix(starters): Key prop to docs list

---

peril.settings.json
starters/gatsby-starter-minimal-ts/src/pages/index.tsx
starters/gatsby-starter-wordpress-blog/package.json

Noticed that a PR opened up in `gatsby-starter-minimal-ts` earlier today didn't have the Gatsby Bot response to it that I was expecting. I'm led to understand this was because it was not included in the peril settings — so this PR adds the missing starters to those peril settings!

chore: update peril settings for starters

---

e2e-tests/mdx/cypress/integration/fs-api.js
e2e-tests/mdx/src/pages/fs-api/{Mdx.fields__slug}.js

We just re-added the compatibility to the https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/
This adds simple e2e tests for it
Based on #36238

MDX v2: e2e tests for  fs routing api

---

starters/blog/gatsby-config.js
starters/blog/gatsby-ssr.js
starters/blog/package-lock.json
starters/blog/package.json
starters/blog/src/components/seo.js
starters/blog/src/pages/404.js
starters/blog/src/pages/index.js
starters/blog/src/pages/using-typescript.tsx
starters/blog/src/templates/blog-post.js
starters/default/gatsby-config.js
starters/default/gatsby-ssr.js
starters/default/package-lock.json
starters/default/package.json
starters/default/src/components/seo.js
starters/default/src/pages/404.js
starters/default/src/pages/index.js
starters/default/src/pages/page-2.js
starters/default/src/pages/using-ssr.js
starters/default/src/pages/using-typescript.tsx
starters/default/src/templates/using-dsg.js
starters/gatsby-starter-wordpress-blog/gatsby-config.js
starters/gatsby-starter-wordpress-blog/gatsby-ssr.js
starters/gatsby-starter-wordpress-blog/package-lock.json
starters/gatsby-starter-wordpress-blog/package.json
starters/gatsby-starter-wordpress-blog/src/components/seo.js
starters/gatsby-starter-wordpress-blog/src/pages/404.js
starters/gatsby-starter-wordpress-blog/src/templates/Page.js
starters/gatsby-starter-wordpress-blog/src/templates/Post.js
starters/gatsby-starter-wordpress-blog/src/templates/blog-post-archive.js

Migrate Starters to [Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/)
[sc-53425]

chore(starters): Migrate starters to Head API

---

packages/gatsby/src/commands/develop.ts
packages/gatsby/src/commands/types.ts
packages/gatsby/src/utils/get-ssl-cert.ts
packages/gatsby/src/utils/start-server.ts

https://github.com/gatsbyjs/gatsby/pull/35675 broke https option, this change restores it
Fixes #36241

fix(gatsby): fix --https option for develop

---

packages/gatsby/index.d.ts

fix(gatsby): add `webhookBody` to `SourceNodesArgs` interface

---

packages/gatsby/src/schema/node-model.js

This require showed up in a performance profile as taking ~600ms (~5-10%) during a large query as `resolveField` is called a lot. We can memoize the require to avoid this.

fix(gatsby): move require out of hot function

---

packages/gatsby-source-shopify/src/create-operations.ts

In non-CI environments, we have an activity to track when queries are long-running. In CI environments (`CI=1`), we have no knowledge of long-running queries. This should help us have more insight into a shopify site's long build times.
Example:
```
warning Operation gid://shopify/BulkOperation/{SOME_ID} is still running after 60 seconds with status "RUNNING"
warning Operation gid://shopify/BulkOperation/{SOME_ID} is still running after 120 seconds with status "RUNNING" 
```
[sc-51358]

feat(gatsby-source-shopify): Add query runtime warning for CI environments

---

docs/docs/gatsby-provision.md
docs/docs/reference/config-files/gatsby-provision.md

Adds a page to our docs for the `gatsby-provision` convention, existing `gatsby-provision-*` packages, as well as guidelines for creating authoring your own `gatsby-provision-*` package.
Still need to determine the best place for this doc to live. Very open to suggestions. Feels somewhere between `gatsby-source` plugins and Gatsby config files to me.
EDIT: decided the most fitting place was in Reference > Config Files.
[sc-52287](https://app.shortcut.com/gatsbyjs/story/52287/ga-documentation-for-cms-content-provisioning)

chore: add docs on `gatsby-provision`

---

docs/docs/debugging-html-builds.md
docs/docs/glossary/server-side-rendering.md
docs/docs/how-to/local-development/troubleshooting-common-errors.md
integration-tests/gatsby-cli/__tests__/build-ssr-errors.js
packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/utils/flags.ts

Highlight `DEV_SSR` a bit more
[ch53803]

fix(gatsby): Add DEV_SSR note to 95312 error

---

docs/docs/starters.md
starters/README.md

This PR gets the docs page on starters to be up to date, namely by updating the table of "official" starters and updating the notes about starter submissions being closed.
[sc-53720](https://app.shortcut.com/gatsbyjs/story/53720/update-starters-docs-page-to-be-accurate)

chore(starters): update starters docs page

---

packages/gatsby-plugin-react-helmet/src/__mocks__/react-helmet.js
packages/gatsby-plugin-react-helmet/src/__tests__/gatsby-ssr.js
packages/gatsby-plugin-react-helmet/src/gatsby-ssr.js

With the introduction of [Gatsby head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/), users won't be able to migrate piecemeal because this plugin appends empty `<title>` tag to pages so that when you specify a `Head` export with a `<title>`, you end up with multiple title tags subsequently breaking Seo.
This change ensures that empty title tags aren't appended
[sc-53780]

fix(gatsby-plugin-react-helment): stop appending empty title tags

---

e2e-tests/mdx/cypress/integration/pages.js
e2e-tests/mdx/gatsby-config.js
e2e-tests/mdx/package.json
packages/gatsby-plugin-mdx/package.json
packages/gatsby-plugin-mdx/src/__tests__/remark-mdx-html-plugin.ts
packages/gatsby-plugin-mdx/src/plugin-options.ts
packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-autolink-headers/src/__tests__/index.js
packages/gatsby-remark-autolink-headers/src/index.js
yarn.lock

While checking for compatibility of our change to `gatsby-remark-autolink-headers`, I figured that we broke it.
So I tried to find a way to render the output of `gatsby-remark-autolink-headers` without altering the plugin itself. By doing this, we can preserve compatibility.
This might improve support for other `(gatsby-)remark-*` plugins as well.
Additionally, `gatsby-remark-autolink-headers` didn't render the link to the headline, only the icon was rendered. This is now fixed as wenn. (needed `passThrough: ['element']`)

MDX v2: turn mdast from gatsby-remark plugins into hast

---

packages/gatsby-plugin-typescript/src/gatsby-node.js

Combining newer versions of `gatsby-plugin-typescript`(>=4.19) with an older version of `gatsby`(<4.19) leads to the errors like the below
```
ERROR #98123  WEBPACK
Generating JavaScript bundles failed
Unknown option: .resourceQuery. Check out https://babeljs.io/docs/en/babel-core/#options for more
information about options.
File: src/pages/index.tsx
```
This is happening because older versions of `gatsby`(<4.19) do not recognize the `resourceQuery` option.
This PR addresses this by checking if the gatsby version supports it before passing the option
Fixes #36304

fix(gatsby-plugin-typescript): only use resourceQuery for supported version of gatsby

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/bootstrap/__mocks__/get-config/tsx-dir/gatsby-confi.tsx
packages/gatsby/src/bootstrap/__tests__/get-config-file.ts
packages/gatsby/src/bootstrap/get-config-file.ts
packages/gatsby/src/utils/__tests__/is-near-match.ts
packages/gatsby/src/utils/is-near-match.ts
packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
packages/gatsby/src/utils/parcel/__tests__/fixtures/misnamed-js/gatsby-node.jsx
packages/gatsby/src/utils/parcel/__tests__/fixtures/misnamed-ts/gatsby-node.tsx
packages/gatsby/src/utils/parcel/compile-gatsby-files.ts

- Handles `gatsby-config` being in TS for the error 10124 (right now it would say to rename a gatsby-config.tsx to gatsby-config.js)
- Adds new 10128 error to warn against gatsby-node.jsx and gatsby-node.tsx
I decided to put this into the compileGatsbyFiles section as it's really early in the Gatsby process and Parcel would just skip the `.tsx` files and we'd have to do "backward investigation" later in the process. So it was easy to just check things here.
This only works for root gatsby-node files though, not for local plugins. Since I wanted to timebox this PR I didn't account for it, if it's absolutely necessary it could certainly be added
Fixes https://github.com/gatsbyjs/gatsby/issues/36127
[ch53998]

fix(gatsby): Panic on gatsby-node.jsx/gatsby-node.tsx

---

docs/docs/reference/routing/creating-routes.md
packages/gatsby/src/redux/actions/public.js

I ran into this weird behavior when creating a multilingual site where the paths were coming pre-encoded from the CMS. I was expecting that Gatsby would recognise pre-encoded paths and make the necessary adjustments so that I wouldn't have to do handle anything but I later found that paths MUST be encoded or pages break and bad things happen :o
I think this could be changed internally so that we don't have to rely on the developer to pass the correct value and instead handle the encoding inside Gatsby. For the meantime however, a docs update should suffice so that developers don't have to dig into the internals to understand whether or not unicode is supported and how to use it.
TLDR; Made a few changes to the API docs to mention how paths should not be encoded when containing unicode …

chore(docs): Pre-encoded unicode characters can't be used in paths

---

packages/gatsby/index.d.ts

So I've ran into this while I defined a `interface CustomPluginOptions extends PluginOptions` in a plugin. I extend the `PluginOptions` from gatsby here so that I can use it in the gatsby-config and in the gatsby-node APIs.
But with `plugins` being required TS complained that my plugin didn't define `plugins`.
```ts
import type { GatsbyConfig, PluginRef } from "gatsby"
import type { CustomPluginOptions } from "plugin"
const config: GatsbyConfig = {
plugins: [
{
resolve: `plugin`,
options: {
api_key: process.env.api_key,
plugins: [], // This here is necessary to add at the moment
} as CustomPluginOptions,
},
] as PluginRef[],
}
export default config
```
I know, we set this by default, but for using this type in 3rd party packages it's annoying

chore(gatsby): Make `plugins` in `PluginOptions` type optional

---

packages/gatsby-source-filesystem/src/gatsby-node.js

We might introduce a simpler way to access this information in the future that wouldn't require this redundant~ `assign`. For the time being this is what I would do here though
cc @LekoArts

Refactor `meta.state` access in `gatsby-source-filesystem`

---

integration-tests/gatsby-pipeline/__tests__/fetch-remote-file/index.js

I downloaded the file locally and the MD5 hash is correct. So something must have changed on Unsplash's end, hard to tell. I couldn't find any reasons why the tests should fail otherwise. So just updating it then...

chore: Fix pipeline tests

---

jest.config.js
jest.environment.ts
packages/gatsby/src/utils/__tests__/cache-lmdb.ts
packages/gatsby/src/utils/cache-lmdb.ts

First problem - our test suites are not really isolated when it comes to lmdb - once lmdb is opened in a process it will remain opened until closed.
Second problem - `global` is resetted between test suites/files - that means neither we or lmdb internally can use anything "global" like to prevent opening new dbs in new test suites tespite those dbs being in fact already openend.
This PR does few things:
- make use of custom environment to just close all lmdb instances after test suite is done to prevent dangling open handles (it can read `global` object for the test suite that might have been mutated - in our case references to open lmdb dbs)
- add `global` tracking for `cache-lmdb` (we already use it for datastore)

fix(test): clear and close lmdb after each test suite

---

packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
packages/gatsby/cache-dir/fast-refresh-overlay/utils.js
packages/gatsby/package.json
yarn.lock

We currently use the [stack-trace](https://www.npmjs.com/package/stack-trace) module for error parsing during `gatsby develop`. It is [meant for use in Node.js environments](https://github.com/felixge/node-stack-trace/issues/19#issuecomment-831945248), so it doesn't work in Safari and Firefox.
This PR makes a change to use the [error-stack-parser](https://github.com/stacktracejs/error-stack-parser), which has pretty much the same API and handles differences in browser `Error` objects.
Our existing e2e tests didn't catch this because we only test in Chrome. I'm opting not to add tests for this because we would need to (probably) migrate the existing tests to Playwright (Cypress does not support Safari) and also install multiple browser executables (which would add to our CI run time).
N/A …

fix(gatsby): Make runtime error overlay work in non-v8 browsers

---

packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/engines-helpers.ts

Track if a site uses the [Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/)
[sc-53800]

feat(gatsby): Telemetry tracking for Head API

---

packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx

Fixes `onLoad` callback execution on first load. Also moves `onStartLoad` in this scenario to execute at the right time (not in the load event listener callback).
N/A
Fixes https://github.com/gatsbyjs/gatsby/issues/36373
[sc-54332]

fix(gatsby-plugin-image): Make onLoad callback work on first load

---

packages/gatsby-script/package.json
packages/gatsby-script/src/gatsby-script.tsx

Import our Reach Router fork the same way we do in Gatsby Link. Originally used the other import because it appeared to not use the same module as Gatsby core otherwise.
Also adds Reach Router as a peer dependency.
N/A
N/A

fix(gatsby-script): Reach router import

---

packages/gatsby-plugin-mdx/src/get-source-plugins-as-remark-plugins.ts
packages/gatsby-plugin-mdx/src/plugin-options.ts
packages/gatsby-plugin-utils/src/types.ts
packages/gatsby/src/utils/js-chunk-names.ts

- Fix issue with plugin options from e.g. `gatsby-remark-images` not getting passed through
- Fix issue with too long chunk names

fix(gatsby-plugin-mdx): Hashing and pluginOptions

---

packages/gatsby-plugin-preact/package.json
packages/gatsby/cache-dir/app.js
packages/gatsby/package.json
yarn.lock

Optimistic bump - but might need more changes to work ( https://github.com/pmmmwh/react-refresh-webpack-plugin/releases/tag/v0.5.0 mentions some breaking changes)
[ch54232]

chore(gatsby): upgrade @pmmmwh/react-refresh-webpack-plugin

---

packages/gatsby-source-filesystem/package.json
packages/gatsby/package.json
packages/gatsby/src/state-machines/__tests__/query-running.ts
packages/gatsby/src/state-machines/data-layer/services.ts
packages/gatsby/src/state-machines/develop/services.ts
packages/gatsby/src/state-machines/query-running/services.ts
packages/gatsby/src/utils/state-machine-logging.ts
yarn.lock

`xstate@4.33.0` introduced console warning about flag that will become future default, while trying to migrate to use it we found some quirks that don't seem to be ironed out fully ( https://github.com/gatsbyjs/gatsby/pull/36342#issuecomment-1216487472 ) and might still change so for now (until there is clarity on those quirks) let's pin xstate.
This also adds _some_ unit tests to query-running machine in particular around things that change behavior

chore: pin xstate

---

docs/docs/reference/built-in-components/gatsby-head.md

Remove outdated note on compatibility with with `react-helmet` since this was fixed in https://github.com/gatsbyjs/gatsby/pull/36303
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/
[sc-54042]

chore(docs): Remove outdated note on compatibility with with `react-helmet`

---

packages/gatsby/src/commands/types.ts
packages/gatsby/src/utils/get-public-path.ts

Just minor internal type addition. We don't use this field in TS code (yet), but type should at least be correct (at very least for code completion in js code)

chore: add prefixPaths field on IProgram type

---

packages/gatsby-cli/src/reporter/reporter.ts

Child processes (in particular PQR) don't have same verbose setting as main process, this ensures that child processes will use same setting as main process

fix(gatsby-cli): preserve verbosity in spawned child processes

---

e2e-tests/development-runtime/src/pages/head-function-export/basic.js
e2e-tests/production-runtime/src/pages/head-function-export/basic.js
packages/gatsby/cache-dir/head/head-export-handler-for-browser.js
packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js

Prevent `Head` from breaking if it contains root level text (text node)
```js
export const Head = () => (
<>
Break 
<title>Head Export</title>
</>
);
```
Adding some text like "Break" above will throw errors on trying to access the `attribute` object on a text node since text nodes have no attribute key
This fix is important for users using a CMS(like WordPress  where the text they're trying to pass also contains invalid head elements and root level text(s)
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/
A user reported this issue on discord https://discord.com/channels/484383807575687178/537691356487876624/1009100830261129356

fix(gatsby): Prevent errors if `Head` has root text node

---

integration-tests/gatsby-pipeline/__tests__/fetch-remote-file/index.js
integration-tests/gatsby-pipeline/gatsby-node.js

Unsplash seems to be changing the files and thus failing our tests. So we moved the files to our GCS. I've downloaded the images from those URLs and each ran `npx md5-file photoA.jpeg` to generate the new hashes for the tests

chore: Use GCS for pipeline tests

---

examples/using-gatsby-image/plugins/gatsby-source-remote-images/gatsby-node.js

Ref: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#dont-mutate-nodes-outside-of-expected-apis

chore: update using-image-processing example

---

docs/docs/how-to/sourcing-data/headless-cms.md

Added Webiny to the list of CMSs you can use with Gatsby
- Added Webiny to the table
- Pointed to our starter
- Added link to our docs

feat(docs): add webiny to headless cms list

---

.jestSetup.js
packages/gatsby-plugin-sharp/package.json
packages/gatsby-plugin-utils/package.json
packages/gatsby-remark-images/package.json
packages/gatsby-transformer-sharp/package.json
yarn.lock

In https://github.com/gatsbyjs/node-potrace/pull/4, we updated our potrace fork to use to use `jimp-compact` over `jimp` and published a new version. This PR bumps up packages to use the latest version (`2.3.0` as of now) as min version

chore(gatsby-plugin-sharp,gatsby-plugin-utils,gatsby-remark-images,gatsby-transformer-sharp): bump min potrace version

---

packages/gatsby/src/utils/webpack-error-utils.ts

```
warn ./src/pages/index.js?export=default
Attempted import error: 'red' is not exported from './index.module.scss' (imported as 'styles').
warn ./src/pages/index.js?export=head
Attempted import error: 'red' is not exported from './index.module.scss' (imported as 'styles').
```
With the introduction of Head API, the modulePath can have a resourceQuery so this removes `?export=head` from the error above
[sc-53668]

fix(gatsby): remove resource query from warnings

---

docs/docs/reference/config-files/gatsby-config.md
examples/functions-google-gmail/README.md
examples/functions-google-oauth/README.md

This PR is fix some spelling.
- docs/docs/reference/config-files/gatsby-config.md
- examples/functions-google-gmail/README.md
- examples/functions-google-oauth/README.md

chore(docs): Fix some typos

---

docs/docs/tutorial/part-3/index.mdx

A very minor change updating the outdated plugin count to a rounder more accurate number.

chore(docs): Update plugin count in part 3 of the tutorial

---

docs/docs/tutorial/part-2/index.mdx

the header export example contains an invalid closing tag

chore(docs): fix incorrect closing tag in tutorial

---

packages/gatsby-source-graphql/src/gatsby-node.js

gatsby-source-graphql throws warning when passing in `dataLoaderOptions` in `gatsby-config.js`.
```
warn Warning: there are unknown plugin options for "gatsby-source-graphql": dataLoaderOptions
Please open an issue at https://ghub.io/gatsby-source-graphql if you believe this option is valid.
```
Grabbed initial types from [dataLoaderOptions](https://github.com/graphql/dataloader/blob/main/src/index.js)

fix(gatsby-source-graphql): add dataLoaderOptions validation to gatsby-source-graphql

---

package.json
packages/gatsby/src/utils/flags.ts

Add Partial Hydration flag to gatsby
[sc-54448]

feat(gatsby): add partial hydration flag

---

packages/gatsby/src/commands/build.ts
packages/gatsby/src/internal-plugins/functions/gatsby-node.ts

One log was giving us confusing results, and it doesn't apply to functions build context, so I removed it. 
The other log added gives us a verbose log of the node environment we're building in.
```
verbose running command: build
verbose Running build in "production" mode
success compile gatsby files - 0.897s
success load gatsby config - 0.023s
```

chore(gatsby): Add env log for build and remove incorrect log for functions

---

docs/docs/reference/routing/creating-routes.md

This PR fixes the code snippet that demonstrates how to create routes using the `createPages` function in `gatsby-node.js`.
Currently, it is:
```js
data.allMarkdownRemark.forEach(node => {
// code
})
```
I think it should be:
```js
data.allMarkdownRemark.nodes.forEach(node => {
// code
})
```
Thank you :)

fix(docs): fix creating routes code snippet

---

packages/gatsby/cache-dir/gatsby-browser-entry.js

Immediatly export functions from imports if they are unused. Helps webpack with tree-shaking.

fix(gatsby): improve import/export in gatsby-browser-entry

---

packages/gatsby-plugin-sharp/src/gatsby-node.js
packages/gatsby-transformer-remark/src/create-schema-customization.js
packages/gatsby-transformer-remark/src/extend-node-type.js
packages/gatsby-transformer-remark/src/gatsby-node.js
packages/gatsby/src/bootstrap/load-plugins/load-internal-plugins.ts
packages/gatsby/src/bootstrap/requires-writer.ts
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/commands/build-utils.ts
packages/gatsby/src/commands/build.ts
packages/gatsby/src/commands/serve.ts
packages/gatsby/src/constants.ts
packages/gatsby/src/query/query-runner.ts
packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/schema/graphql-engine/entry.ts
packages/gatsby/src/schema/index.js
packages/gatsby/src/services/initialize.ts
packages/gatsby/src/utils/babel-loader-helpers.ts
packages/gatsby/src/utils/page-data.ts
packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts

In preparation for v5 canaries, This PR makes codepaths behind `_CFLAGS_.GATSBY_MAJOR === 4` conditions the default and also removes non `_CFLAGS_.GATSBY_MAJOR === 4` codepaths.
[sc-54975]

chore(gatsby, gatsby-transformer-remark, gatsby-plugin-sharp): Cleanup v4 compile flag conditions

---

packages/gatsby-dev-cli/src/local-npm-registry/index.js
packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
packages/gatsby-dev-cli/src/watch.js

NPM 8.5 added forced errors when publishing a package in monorepo when `.npmrc` file are in package and not in root ( https://github.com/npm/cli/issues/4605 ). This caused new users trying to use `gatsby-dev-cli` to go through weird steps to be able to use our autoincluded verdaccio setup. This changes just outputs `.npmrc` file (with dummy auth information) to monorepo root (as well as continue to add it to packages for previous versions) making gatsby-dev-cli "just" work agai
Fixes https://github.com/gatsbyjs/gatsby/issues/36497

fix(gatsby-dev-cli): adjust setup to 'just work' with npm 8.5

---

.circleci/config.yml
e2e-tests/contentful/package.json
e2e-tests/development-runtime/package.json
e2e-tests/mdx/package.json
e2e-tests/path-prefix/package.json
e2e-tests/production-runtime/package.json
e2e-tests/themes/package.json
e2e-tests/trailing-slash/package.json
e2e-tests/visual-regression/package.json
integration-tests/artifacts/package.json
integration-tests/cache-resilience/package.json
integration-tests/functions/package.json
integration-tests/gatsby-cli/package.json
integration-tests/gatsby-pipeline/package.json
integration-tests/gatsby-source-wordpress/package.json
integration-tests/head-function-export/package.json
integration-tests/images/package.json
integration-tests/long-term-caching/package.json
integration-tests/node-manifest/package.json
integration-tests/ssr/package.json
integration-tests/structured-logging/package.json
packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts
packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts
packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
packages/gatsby-plugin-mdx/src/remark-path-prefix-plugin.ts
packages/gatsby/src/utils/webpack/bundle.ts
yarn.lock

- Adds resolutions to e2e test for broken typings package
- Fixes typescript types for mdx

fix: ci pipeline

---

packages/gatsby/index.d.ts

https://www.gatsbyjs.com/docs/api-proxy/#proxying-api-requests-in-development

chore(gatsby): perfect `GatsbyConfig.proxy` type

---

packages/gatsby/cache-dir/loader.js
packages/gatsby/src/bootstrap/requires-writer.ts

Allow our production loader to load head & page component separately

feat(gatsby): split up head & page component loading

---

packages/gatsby/cache-dir/server-utils/writable-as-promise.js
packages/gatsby/cache-dir/static-entry.js

Fixes errors that get swallowed during React 18's `renderToPipeableStream`.
Currently the error is logged (so at least there's some info), but the stack trace and code frame don't have it.
Example component with error:
```jsx
import * as React from "react"
import { Link } from "gatsby"
const IndexPage = () => {
// This is the error
throw new Error(`Hello`)
return <></>
}
export default IndexPage
```
Current stack trace and code frame:
```sh
ERROR #95313 
Building static HTML failed
See our docs page for more info on this error: https://gatsby.dev/debug-html
107 |         route: route,
108 |         params: params,
> 109 |         uri: "/" + uriSegments.slice(0, index).join("/")
| ^
110 |       };
111 |       break;
112 |     }
WebpackError: Worker exited before finishing task
- …
```

fix(gatsby): Handle renderToPipeableStream errors

---

packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/node-model.js

Resolver / graphql context that plugins can inject was not available during materialization. This will happen only if the query would sort or filter on fields with custom resolvers that rely on that custom context, so it wasn't failing all the time (just depending on query).
https://github.com/datocms/gatsby-source-datocms/issues/196

fix(gatsby): pass custom graphql context provided by createResolverContext to materialization executor

---

packages/gatsby/package.json
yarn.lock

Gatsby currently has an unmet peer dependency in `react-refresh@0.9.0`.
This updates the dependency to the latest version which falls within the required versions based on [`@pmmmwh/react-refresh-webpack-plugin` peerDependencies suggestion](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/5b0ef9b2ee2fb2f4323df3ec628c26b9c72bf0c7/package.json#L116)
n/a

chore(gatsby): Update `react-refresh` to `^0.14.0`

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

You shouldn't add `content` unless node can be transformed. As is, this just duplicates the content which increases memory & slows all IO.

chore(docs): Remove `content` from sourcing guide

---

packages/gatsby-link/src/__tests__/rewrite-link-path.js
packages/gatsby-link/src/rewrite-link-path.js

When trailingSlash: never and PREFIX_PATH is defined root page address is not properly generated. Instead of `/prefix` it gets geenrated as `/prefix/`

fix(gatsby-link): Correct handling of trailingSlash & pathPrefix

---

scripts/create-release-notes.js
scripts/create-release-notes.template.md

Creating release notes is a cumbersome process of copying previous notes. This should automate it for us. 🥳 
Usage:
```
node create-release-notes.js 4.22 2022-08-30
```
https://github.com/gatsbyjs/gatsby/pull/36464/commits/728e2799a45f41a7783947e92ca8bec279ae67d9 / https://github.com/gatsbyjs/gatsby/pull/36464 was created with this script as an example.

chore(gatsby): Create release notes template script

---

packages/gatsby-cli/rollup.config.js
patches/v5/1-node-engine.patch
patches/v5/2-gatsby-cli-rollup-node-target.patch

Creates patch files to bump min Node version to 18
Needs to be updated in a separate PR
[ch53285]

chore: Bump min Node version to 18

---

docs/docs/how-to/routing/layout-components.md

The path `/docs/tutorial/part-3/` points to documentation for adding plugins, not nested layout documentation so the link text "Creating nested layout components in Gatsby" is incorrect. I can't find the updated documentation for nested layouts so this just makes the link text to match the content at that path, "Add Features with Plugins".

chore(docs): Update "Layout components" related links

---

scripts/create-release-notes.js

Create release docs script fails at the PR creation step since it requires a `base` branch param, this adds it
N/A
https://github.com/gatsbyjs/gatsby/pull/36465

chore(gatsby): Add required base param to create PR call

---

examples/using-mdx/content/posts/blog-1.mdx
examples/using-mdx/content/posts/blog-2.mdx
examples/using-mdx/gatsby-config.js
examples/using-mdx/gatsby-node.js
packages/gatsby-plugin-mdx/README.md

In https://github.com/gatsbyjs/gatsby/commit/7233c49ea4f459d941b284e9c9c9cfb187b9ddb1 the `store` arg was added but the example wasn't updated accordingly.
Fixes https://github.com/gatsbyjs/gatsby/issues/36591

chore(gatsby-plugin-mdx): Update "headings" instructions

---

docs/docs/tutorial/part-4/index.mdx
docs/docs/tutorial/part-5/index.mdx

change seo component import line in src/pages/blog.js file import Seo from '../../components/seo' --> import Seo from '../components/seo'

chore(docs): Fix `Seo` imports in tutorial

---

packages/gatsby-plugin-sitemap/README.md

To avoid others to wonder what's in that object as i did

chore(gatsby-plugin-sitemap): Add info about `page` object to README

---

packages/gatsby/index.d.ts

According to https://github.com/gatsbyjs/gatsby/discussions/35841#discussioncomment-3357209 there is a `loadPageDataSync` function, which returns the page context to the corresponding `pathname`. So far this was not reflected in the type definitions, what is changed with this PR.
Related to #36354

chore(gatsby): Add `loadPageDataSync` property to `onRenderBody` TS type

---

packages/gatsby-plugin-mdx/src/__tests__/gatsby-layout-loader.ts
packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts

When updating a site/theme of mine, I've run into a problem:
```shell
React is not defined
```
Because it used this without importing React
```jsx
export default function GatsbyMDXWrapper(props) {
return React.createElement(MDXContent, props, React.createElement(GATSBY_COMPILED_MDX, props));
}
```
[ch54694]

fix(gatsby-plugin-mdx): Add React import when not defined

---

patches/v5/0-gatsby-peerdeps.patch
patches/v5/1-node-engine.patch

Update v5 peerdep-patch. It had a reference to a monorepo plugin which got bumped by our v4 release, I modified the patch so it's not included anymore

chore: modify patch peer-deps for v5 after release

---

docs/docs/reference/built-in-components/gatsby-script.md

This fixes two code examples on [Gatsby Script API docs](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-script/#off-main-thread-strategy-experimental), concerning how forward events work for `off-main-thread` script using Partytown.
This might seem trivial, but I got tripped up myself copying the code from these examples.
The current example shows that `gtag` is forwarded from Script 1 (`https://www.googletagmanager.com/gtag/js`), but this is incorrect because:
- This script doesn't create `gtag` function, but rather `dataLayer.push`. An example from [Partytown's docs](https://partytown.builder.io/google-tag-manager#forward-events) also corroborates this.
- In fact, this script does not need to forward any event, as the `dataLayer.push` function is also used in the …

chore(docs): Fix Partytown forward events examples

---

docs/docs/reference/built-in-components/gatsby-link.md

Recent feedback via the widget in our docs indicates that readers were unable to find specific information that either:
- Already exists in the doc somewhere further down the page, or
- Could be found in Reach Router's doc but was missing from our rehash of the information in their doc
This change attempts to:
- Make clear what parts of the `Link` and `navigate` APIs originate from Reach Router and what parts are added by us
- Direct readers to Reach Router's docs as the source of truth for the parts that come from them
- Make usage sections more succinct so chances of discovery for what readers are looking for is higher (which includes moving Egghead videos to be additional resources links)
- Create table for Gatsby-provided properties and include `type`
See the [rendered …

chore(docs): Improve Gatsby Link reference doc

---

packages/gatsby/src/query/file-parser.js

Error context was renemad wrongly recently. This reverts that. For reference - here's error map entry that is using `context.filePath` (and not `context.cleanFilePath`): https://github.com/gatsbyjs/gatsby/blob/9714823ec2e6a32ba096348ad608c031eff2056e/packages/gatsby-cli/src/structured-errors/error-map.ts#L156-L164
Currently JS syntax errors result in errors like this (`undefined` is the problematic bit):
```
ERROR #85911  GRAPHQL
There was a problem parsing "undefined"; any GraphQL
fragments or queries in this file were not processed.
This may indicate a syntax error in the code, or it may be a file type
that Gatsby does not know how to parse.
File: src/pages/ssr.js
failed extract queries from components - 0.048s
```

fix(gatsby): add missing filePath information in extraction errors

---

docs/docs/glossary.md
docs/docs/reference/gatsby-cli.md
packages/gatsby-cli/README.md

- Make the reference doc more concise where possible
- Remove the `gatsby plugin <arg>` command since it appears to be unmaintained
- Sync doc with package readme, which is necessary since third parties like npmjs.com render the readme
See the [changes rendered](https://github.com/gatsbyjs/gatsby/blob/docs/docs-day-gatsby-cli/docs/docs/reference/gatsby-cli.md).
https://www.gatsbyjs.com/docs/reference/gatsby-cli/
[sc-55710]

chore(docs): Improve Gatsby CLI reference doc

---

packages/gatsby/src/utils/api-browser-docs.ts

Use React 18 APIs in `replaceHydrateFunction` example in the Gatsby Browser APIs reference doc. Refer users of React 17 or earlier to the React docs. Tested locally, works.
Note about the "it's very important to call the `callback` after rendering" message, I tested without the callback with React 17 APIs and it worked fine so I removed it.
https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#replaceHydrateFunction
[sc-52945]

chore(docs): Use React 18 APIs in replaceHydrateFunction example

---

packages/gatsby-source-wordpress/README.md

Fixes license link in [gatsby-source-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress)'s README
N / A
N / A

chore(gatsby-source-wordpress): Fix license link

---

docs/docs/glossary.md
docs/docs/reference/gatsby-cli.md
packages/gatsby-cli/README.md

New glossary item "Run Script" doesn't have its own page, so links should be fragments.
https://www.gatsbyjs.com/docs/glossary/#run-script
N/A

chore(docs): Fix run script glossary link

---

docs/docs/reference/built-in-components/gatsby-head.md

Indicate in the documentation that you can't currently access context provided via [`WrapRootElement`](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapRootElement) inside the `Head` function

chore(docs): Add `wrapRootElement` + Head API limitation

---

packages/gatsby-cli/src/__tests__/index.ts
packages/gatsby-cli/src/index.ts
packages/gatsby/src/utils/parcel/compile-gatsby-files.ts

Follow-up to https://github.com/gatsbyjs/gatsby/pull/36560
Forgot two places where we also set this. Just searched for `14.15.0` in VS Code to find it.
We'll need to update https://www.gatsbyjs.com/docs/upgrading-node-js/ in separate PR

chore: More Node 18 bumps

---

packages/gatsby-core-utils/src/physical-cpu-count.ts

I got this warning when running `gatsby build`: 
egrep: warning: egrep is obsolescent; using grep -E
This PR fixes the warning.

fix(gatsby-core-utils): Use `grep -E` instead of `egrep`

---

docs/docs/how-to/testing/visual-testing-with-storybook.md

- Update docs as per solution for issue: https://github.com/storybookjs/storybook/issues/17176#issuecomment-1012394666
- Community plugin https://storybook.js.org/addons/storybook-addon-gatsby is not up to date which is causing issues - removing this section
The above mentioned issue was created on the 12 Jan and there has only been one commit to this file since then (https://github.com/gatsbyjs/gatsby/commit/d3e0cd9b7fc5ee0b6ac799163fbc03b90e2374d5) which does not address this issue.
docs: https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/#manual-configuration
plugin: https://storybook.js.org/addons/storybook-addon-gatsby
https://github.com/storybookjs/storybook/issues/17176#issuecomment-1012394666

chore(docs): Update storybook main.js docs

---

packages/gatsby/package.json
yarn.lock

In https://github.com/gatsbyjs/gatsby/pull/36553 it was updated, but in https://github.com/gatsbyjs/gatsby/pull/36485 we accidentally reverted to old version.

chore(gatsby): Update react-refresh again

---

packages/gatsby/src/utils/webpack.config.js

In https://github.com/gatsbyjs/gatsby/pull/36485 the `shared` was changed to:
```js
shared: {
test: module => isCssModule(module),
```
It should stay `!isCssModule`.

fix(gatsby): Regression in shared chunks

---

packages/gatsby-plugin-gatsby-cloud/src/__tests__/routes.js
packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
packages/gatsby-plugin-gatsby-cloud/src/ipc.js

Adding extra ipc message to count total page count
Fixes [sc-55649]

feat(gatsby-plugin-gatsby-cloud): add total page count ipc

---

packages/gatsby-source-contentful/README.md

Fixed incorrect `image` prop value in the `GatsbyImage` component returned in the image embed Options code sample. `image` variable is undefined; should be `gatsbyImageData` per [Gatsby Image Plugin](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#gatsbyimage) docs.

chore(gatsby-source-contentful): Correct image embed code sample

---

packages/gatsby/cache-dir/static-entry.js

Wrap `WrapRootElement` before rendering slice. This makes context provided in `WrapRootElement` available when rendering slices
[sc-55896]

fix(gatsby): Wrap `WrapRootElement` before rendering slice

---

packages/gatsby-dev-cli/package.json
yarn.lock

Upgrade verdaccio to v5, release notes - https://github.com/verdaccio/verdaccio/issues/2141.
N/A
N/A

chore(gatsby-dev-cli): Upgrade to verdaccio v5

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/commands/build-html.ts

Couple things went missing during rebase of partial hydration branches. This makes sure we see structured errors again
N/A
N/A

fix(gatsby): Add back missing partial hydration error handling change

---

packages/gatsby/src/utils/webpack/loaders/partial-hydration-reference-loader.ts
packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
packages/gatsby/src/utils/webpack/utils/__tests__/__snapshots__/create-normalized-module-key.ts.snap
packages/gatsby/src/utils/webpack/utils/__tests__/create-normalized-module-key.ts
packages/gatsby/src/utils/webpack/utils/create-normalized-module-key.ts

Normalize module keys between the partial hydration webpack loader and plugin.
Previously the actual resource path was used, which caused problems because the different modules can be loaded in the loader and plugin based off of what is declared in `package.json`.
N/A
[sc-55773]

feat(gatsby): Normalize module keys between webpack plugin and loader

---

packages/gatsby/src/utils/webpack-utils.ts

We use a base64 hash for CSS modules, and the (non-variant) [base64 lexicon](https://datatracker.ietf.org/doc/html/rfc4648#section-4) contains the the plus character (`+`), which is the [adjacent-sibling combinator](https://www.w3.org/TR/selectors-4/#adjacent-sibling-combinators) (`.a + .b`) in CSS.
Switch to `hex` instead. Tried `base64url` (introduced in Node `14.18.0`) but it doesn't work (maybe webpack docs are incorrect, will look into this).
Paper trail:
- `css-loader` docs recommend `base64` - https://webpack.js.org/loaders/css-loader/#localidentname
- `webpack` core `output.hashDigest` docs mention `base64` - https://webpack.js.org/configuration/output/#outputhashdigest and that it supports all other encodings Node supports
- Encodings Node supports - …

fix(gatsby): Use hex hash for CSS modules

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts

In our current implementation the client module manifest is wiped on subsequent builds, breaking hydration.
This happens because we run `PartialHydrationPlugin` during the `build-javascript` stage, and on subsequent builds webpack doesn't revisit untouched files and uses the cache instead.
This change restores the previous manifest when `PartialHydrationPlugin` runs and merges it with any new client modules found.
React has a similar implementation looking for `.client.js` files (the old API) in a `beforeCompile` hook to iterate over later - https://github.com/facebook/react/blob/3f70e68cea8d2ed0f53d35420105ae20e22ce428/packages/react-server-dom-webpack/src/ReactFlightWebpackPlugin.js#L110-L132. We could do something similar, but it would be more expensive with the new API because we'd …

fix(gatsby): Persist manifest on cached builds

---

scripts/release-next-major.js

Due to way lerna decides canary versions, the most recent alpha releases are not guaranteed to be "greater than lexigraphically":
To workaround this this PR adds date time string to preid - that will look like ~ `alpha-v5.d20221004t085711` and then lerna will still attach the "random" (not really random, but in our case pretty random) number after that

chore(v5): insert datetime string as postfix in version when releasing v5 canaries

---

packages/gatsby/src/commands/build-html.ts

Adds a `try/catch` around our alias handling for Partial Hydration. Previously the `require.resolve` failed the build if the image plugin wasn't installed.
[ch56435]

fix(gatsby): Don't fail build on missing gatsby-plugin-image for Partial Hydration

---

packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts
packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts

This updates to chunk splitting for partial hydration and manifest generation:
1. Manifest: don't add every chunk from chunk groups that client module is present
2. When we split client module we also follow its dependencies / imports and move them to newly splitted chunk (unless they are part of `app` chunk - this prevents putting for example `react` modules in last client chunk we create as every component depend on react pretty much)
3. We also adjust our `webpack.stats.json` to ignore assets for splitted partial hydration chunks as otherwise we would have `<script>` for every one of those in every html page (they would be listed as part of `app` chunkgroup)
4. We use same compilation hook as `SplitChunksPlugin` does, as otherwise splitChunkPlugin wasn't working correctly
[ch-55777]

fix(partial-hydration): move client components to separate chunks

---

packages/gatsby/src/redux/actions/public.js
packages/gatsby/src/redux/actions/restricted.ts

Adds technical API doc blocks for slices
- [Reference Doc](https://github.com/gatsbyjs/gatsby/pull/36694)
- [How-to Doc](https://github.com/gatsbyjs/gatsby/pull/36720)
- [Technical API Doc](https://github.com/gatsbyjs/gatsby/pull/36721)
- [Cloud Doc](https://github.com/gatsbyjs/gatsby/pull/36722)
[sc-55256]

chore(docs): Slices API Technical Docs

---

packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts

Without defining `process.env.GATSBY_SLICE` we get following in produced engine:
```
if ( true && process.env.GATSBY_SLICES) {
const formattedSlices = traverseSlicesUsedByTemplates(pagePath, componentPath, overrideSlices, slicesUsedByTemplates, slices);
if (formattedSlices) {
body += `,"slicesMap":${JSON.stringify(formattedSlices)}`;
}
}
```
which means `page-data` will be missing expected `slicesMap`
[ch-56652]

fix: define process.env.GATSBY_SLICE so produced engines use conditional slices paths

---

packages/gatsby/src/redux/reducers/html.ts

When migrating from v4 to v5 the new structures in `html` reducer doesn't exist and currently migration / clear cache code doesn't properly set them up. This currently results in one of the following errors:
1. (if there was just packages bump and slices are not used):
```
success write out requires - 0.003s
ERROR 
UNHANDLED REJECTION Cannot read properties of undefined (reading 'add')
TypeError: Cannot read properties of undefined (reading 'add')
- html.ts:419 htmlReducer
[gatsby-starter-contentful-homepage-slices-fastly-on-all-jam]/[gatsby]/src/redux/reducers/html.ts:419:45
```
2. (if createSlice was used):
```
success building schema - 0.300s
ERROR #11321  PLUGIN
"gatsby-node.js" threw an error while running the createPages lifecycle:
Cannot read properties of undefined (reading …
```

fix(gatsby): cache clear when upgrading from version without slices support cache

---

packages/gatsby-page-utils/src/__tests__/create-path.ts
packages/gatsby-page-utils/src/create-path.ts

replaces Windows path seperator to UNIX path seperator
Fixes [#36758](https://github.com/gatsbyjs/gatsby/issues/36758)

fix(gatsby-page-utils): path creation on windows filesystem

---

packages/gatsby-codemods/src/bin/__tests__/gatsby-codemods-test.js
packages/gatsby-codemods/src/bin/cli.js

Fix small regression in codemods
[ch-56641]

fix(gatsby-codemods): fix spawning jscodeshift process

---

packages/gatsby/src/utils/page-data.ts
packages/gatsby/src/utils/page-ssr-module/entry.ts

- moves slice-data read before we read static query context for given page template
- read static query context for slice templates and merge all of them back together with page template
- it additionally wraps slice-data reads in phantom activity so opentracing / opentelemetry has a span for it to improve observability
Test setup with a slice template has `useStaticQuery` usage with one of imported components
before:
500 error in browser + following logs
```
You can now view gatsby-starter-contentful-homepage in the browser.
⠀
http://localhost:9000/
ERROR 
Rendering html for "/privacy" failed. The result of this StaticQuery could not be fetched.
This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues …
```

fix(gatsby): support slices containing static queries during SSR/DSG

---

patches/v5/4-slices-api.patch

This:
- adjusts types to allow passing children in as that is supported  (`<Slice>SomeContent</Slice>`)
- renames `SliceProps` to `SlicePlaceholderProps` to clear potential confusion what if we refer to Slice placeholder usage or Slice component/template implementation
- adds types for props that can be used in Slice component/template - sample input and output from `tsc` - https://gist.github.com/pieh/c4d127003e15bae87c329a841adafc4e (valid component is completely valid, other component have tsc errors in the gist - note that the setup in the gist is wrong as slice component/template need to have single default export, but for type checking that doesn't matter)
- 
[ch-56671]

chore(gatsby): add types for SliceComponentProps, rename SliceProps to SlicePlaceholderProps, add jsdocs for those types

---

packages/gatsby/cache-dir/slice.js
packages/gatsby/cache-dir/static-entry.js

We are not (yet?) supporting nested slices. Currently on usage we throw pretty non-descriptive error message:
```
failed Building slices HTML (22) - 0.088s
ERROR 
Slice context "undefined" is not supported.
```
This PR looks to add more context in scenarios where nested slices are used - currently state of PR shows:
```
failed Building slices HTML (22) - 0.112s
ERROR 
Nested slices are not supported.
Slice component "counter" (/home/misiek/dev/rome-test-site/src/layouts/counter.js) tried to render <Slice id="nested"/>
See https://v5.gatsbyjs.com/docs/reference/built-in-components/gatsby-slice#nested-slices
```
[ch-56713]

fix: add more meaningful error message when nested slices are used

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md

chore(docs): Update v4 to v5 migration to use `next`

---

docs/docs/how-to/adding-common-features/creating-a-sitemap.md
docs/docs/how-to/plugins-and-themes/using-a-plugin-in-your-site.md
packages/gatsby-plugin-sitemap/README.md
packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
packages/gatsby-plugin-sitemap/src/__tests__/options-validation.js
packages/gatsby-plugin-sitemap/src/options-validation.js

Changes the default folder location of the sitemap files to the root of the page, previously it was `/sitemap`.
Will need a mention in the migration guide: https://github.com/gatsbyjs/gatsby/pull/36763
[ch53288]
Fixes https://github.com/gatsbyjs/gatsby/issues/34811

BREAKING(gatsby-plugin-sitemap): Change `output` default to `/`

---

docs/docs/how-to/sourcing-data/headless-cms.md

Added Dialoguewise to the list of CMSs you can use with Gatsby
- Added Dialoguewise to the table
- Added link to guide and docs

chore(docs): added Dialoguewise to headless cms list

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md

Add unified page props section to future breaking changes in v5 migration guide.
https://github.com/gatsbyjs/gatsby/blob/v5-docs/docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
[sc-56692]

docs(v5): Unified page props

---

integration-tests/gatsby-cli/__tests__/build-ssr-errors.js
packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
packages/gatsby-cli/src/reporter/__tests__/index.ts
packages/gatsby-cli/src/structured-errors/__tests__/construct-error.ts
packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/utils/__tests__/extract-undefined-global.ts
packages/gatsby/src/utils/extract-undefined-global.ts
packages/gatsby/src/utils/worker/child/render-html.ts

Handle slice HTML rendering errors.
- Handle generic rendering error with extra context to help with debugging
- Handle undefined global in SSR error
- Fix and make generic the undefined global matching logic, add tests
N/A
[sc-56605]

feat(gatsby,gatsby-cli): Slice HTML rendering error handling

---

docs/docs/how-to/custom-configuration/typescript.md

add a definition for CSS Modules for this error when i use CSS Modules in TypeScript:
```shell
TS2307: Cannot find module './layout.module.css' or its corresponding type declarations.
```
Reference:
- found solution here: https://stackoverflow.com/a/68011107/1930509

chore(docs): TypeScript and Gatsby: add info for CSS Modules

---

.circleci/config.yml
e2e-tests/contentful/package.json
e2e-tests/development-runtime/package.json
e2e-tests/mdx/package.json
e2e-tests/path-prefix/package.json
e2e-tests/production-runtime/package.json
e2e-tests/themes/package.json
e2e-tests/trailing-slash/package.json
e2e-tests/visual-regression/package.json
integration-tests/artifacts/package.json
integration-tests/cache-resilience/package.json
integration-tests/functions/package.json
integration-tests/gatsby-cli/package.json
integration-tests/gatsby-pipeline/package.json
integration-tests/gatsby-source-wordpress/package.json
integration-tests/head-function-export/package.json
integration-tests/images/package.json
integration-tests/long-term-caching/package.json
integration-tests/node-manifest/package.json
integration-tests/ssr/package.json
integration-tests/structured-logging/package.json

Revert the `resolutions` for `responselike` from https://github.com/gatsbyjs/gatsby/pull/36544 since we're now on Node 18
[ch55366]

chore: Revert "responselike" resolutions

---

packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
packages/gatsby-plugin-typescript/src/gatsby-node.js
packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts

The logic of `onCreateWebpackConfig` already exists in `gatsby`. It wasn't removed mid v4 because of possible dependency issues.
[ch53270]

chore(gatsby-plugin-typescript): Remove obsolete `onCreateWebpackConfig`

---

packages/gatsby-plugin-gatsby-cloud/src/constants.js

This PR re-introduces the `LINK_REGEX` constant that I believe was erroneously removed here: https://github.com/gatsbyjs/gatsby/pull/35586/files#diff-3cfde586499cf0544b902496d3bfc2636c027a2d5d750bc4099083265a767548L40
I don't believe any documentation needs updated, but the relevant doc is here: https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/#headers
Fixes https://github.com/gatsbyjs/gatsby/issues/36624

fix(gatsby-plugin-gatsby-cloud): Re-add constant LINK_REGEX

---

packages/gatsby-core-utils/README.md

Updated the `gatsby-core-utils` README to fix a typo in the `cpuCoreCount()` function arguments. The code being referenced here is actually checking for a different value than what is documented (underscore vs dash):
https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-core-utils/src/cpu-core-count.ts#L29
N/A
None

chore(gatsby-core-utils): Update README with correct cpuCoreCount args

---

packages/gatsby-codemods/src/transforms/__tests__/sort-and-aggr-graphql.ts
packages/gatsby-codemods/src/transforms/sort-and-aggr-graphql.ts
packages/gatsby/src/query/__tests__/transform-documents.ts
packages/gatsby/src/query/transform-document.ts

Example problematic query:
```graphql
allMdx(sort: { order: ASC, fields: fields___slug })
```
Queries like one above are causing issues with current transform - the problem lies in fact that v4 API had `sort.fields` and then the value of a field to sort on also had `fields` in it - `fields___slug`
The codemod will apply transformations in a loop until it no longer apply any changes. The issue is that the checks were not sufficient and transformation still thought that query after initial transform looked like old one (because it had `sort.fields`):
```graphql
allMarkdownRemark(sort: { fields: { slug: ASC }})
```
This PR adds a check to see if `field` is providing enum or list of enums with actual values and will mark query as new one if there are no values there.

fix: handle 'fields' field edge case in sort/aggr codemod

---

packages/gatsby-cli/src/reporter/errors.ts
packages/gatsby/cache-dir/fast-refresh-overlay/components/hooks.js
packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
packages/gatsby/cache-dir/fast-refresh-overlay/utils.js
packages/gatsby/cache-dir/slice.js
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
packages/gatsby/src/utils/babel-loader-helpers.ts
packages/gatsby/src/utils/babel/babel-plugin-add-slice-placeholder-location.ts
packages/gatsby/src/utils/babel/find-slices.ts
packages/gatsby/src/utils/dev-ssr/parse-error.ts
packages/gatsby/src/utils/start-server.ts

React component stack trace is not always showing source code location (see https://github.com/facebook/react/blob/2cf4352e1c81a5b8c3528519a128c20e8e65531d/packages/shared/ReactComponentStackFrame.js#L135-L137 ).
This makes it hard to show a relevant codeframe from the user when we are throwing validation errors inside gatsby / slice placeholder component internals as we would point to gatsby internals which is irrelevant to users.
This PR:
- add babel plugin to add `__renderedBylocation` prop to all stages aside from `build-javascript`
- adds `error.forcedLocation` on slice validation errors
- adjusts dev overlay to use `error.forcedLocation` if provided (and fallback to inspecting stack trace if not) - this also needed dev server adjustments to handle cases where location is already one …

feat: inject source location data to Slice usage and show errors in places where user renders them and not in gatsby internals

---

packages/gatsby/src/utils/babel/babel-plugin-add-slice-placeholder-location.ts

This was causing a build error during sourcing for dotcom

fix(gatsby): remove jsx from comment

---

packages/gatsby-plugin-mdx/package.json
packages/gatsby-plugin-mdx/src/plugin-options.ts
yarn.lock

Adds https://github.com/remarkjs/remark-unwrap-images to `gatsby-plugin-mdx`. To quote its README:
> This package is a [unified](https://github.com/unifiedjs/unified) ([remark](https://github.com/remarkjs/remark)) plugin that searches for paragraphs which contain only images (possibly in links) and nothing else, and then remove those surrounding paragraphs.
We didn't do this during the v4 lifecycle as this can be considered a breaking change.
I'll add notes about this in https://github.com/gatsbyjs/gatsby/pull/36763
Fixes https://github.com/gatsbyjs/gatsby/issues/36211
Fixes https://github.com/gatsbyjs/gatsby/issues/16239
[ch53708]

fix(gatsby-plugin-mdx): Unwrap images

---

benchmarks/source-agilitycms/src/agility/utils.js
examples/using-type-definitions/gatsby-node.js
packages/gatsby/src/query/__tests__/data-tracking.js
packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/__tests__/queries.js
packages/gatsby/src/schema/node-model.js

In https://github.com/gatsbyjs/gatsby/pull/33489 I added deprecation notices to `nodeModel.runQuery` and `nodeModel.getAllNodes`. One year later it's time to remove them.
Will be added to https://github.com/gatsbyjs/gatsby/pull/36763
[ch57153]

fix(gatsby): Remove runQuery & getAllNodes from nodeModel

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

Did an initial pass on improving the tutorial. Some notes on additional changes I think should be made:
- we really need to make the mental model clear for what a source plugin is. Having talked to a number of people in process of building a source plugin, they're often missing understanding of even very basic things. So similar to the main tutorial we should have people go step-by-step through the whole sweep of the data layer e.g. the different actions, showing them the LMDB file on disk, etc.
- the example needs to a lot simpler — Apollo, etc. gets in the way of understanding things. Plus we should steer people towards Got
- the tutorial mixes basic & advanced features — we should separate the basic tutorial from advanced features like relationships, images, content sync
- make really …

fix(docs): Update the create a source plugin tutorial

---

packages/gatsby-plugin-mdx/src/error-utils.ts
packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts

Add the `mdxPath` to the relevant errors to not only point out the template but also the specific MDX file it failed on.
[ch57295]

fix(gatsby-plugin-mdx): Better AST error

---

packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
packages/gatsby-plugin-typescript/src/gatsby-node.js
packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts

This reverts commit 7abda3470cad4538ec0932c5a28a4d55a7a90dd3.
After publishing the mentioned PR TypeScript support in MDX stopped working 😬 
[ch57294]

Revert "chore(gatsby-plugin-typescript): Remove obsolete `onCreateWebpackConfig` (#36814)"

---

packages/gatsby/src/schema/__tests__/fixtures/node-model.js
packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/node-model.js

Our tracking for finding nodes that contain nested objects only handles case when those nested objects are not shared in multiple nodes (1:1 mapping). This makes it possible to lose mapping information and result in very confusing bugs or errors ( see #36728). This adjusts the mapping to be 1:N
Closes #36728
Closes #36776
[ch-56457]

fix(gatsby): track multiple root nodes and not just one

---

.circleci/config.yml
integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js

Correctly use Node 18 in WordPress E2E tests. For WordPress we use dedicated VMs so the general node image used for the other tests doesn't apply. An image with pre-installed Node 18 doesn't exist: https://circleci.com/developer/images?imageType=machine
[ch56802]

chore: Wordpress Tests with Node 18

---

packages/gatsby-plugin-typescript/src/gatsby-node.js

Remove version check for v5, see comment https://github.com/gatsbyjs/gatsby/pull/36869#discussion_r1002946481 for context.
N/A
[sc-57312]

chore(gatsby-plugin-typescript): Remove version check

---

packages/gatsby-transformer-remark/package.json
packages/gatsby-transformer-remark/src/utils/time-to-read.js
yarn.lock

Fixes an `npm audit` warning. Option was changed to be aligned with https://github.com/apostrophecms/sanitize-html#what-if-i-dont-want-to-allow-any-tags

chore(gatsby-transformer-remark): Update sanitize-html

---

packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
packages/gatsby-cli/src/reporter/loggers/ink/components/trees.tsx
packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
packages/gatsby-cli/src/util/generate-trees.ts

Improves the build output of Slices and aligns it with the existing "Pages" tree.
Ink:
Yurnalist:
[ch56648]

feat(gatsby-cli): Fancier Slices Tree

---

packages/gatsby/src/services/initialize.ts

We hash plugin versions and package.json but we don't include gatsby version when only a yarn.lock or package-lock changes. This fixes it
Fixes [sc-57559]

fix(gatsby): Also clear cache on gatsby version change

---

packages/gatsby/src/utils/webpack/plugins/static-query-mapper.ts

This is refactor needed for Partial Hydration changes ( https://github.com/gatsbyjs/gatsby/pull/36923 is relying on this )
This moves discovery of static queries and slice placholders used / needed by page templates to earlier webpack phase (before chunks and chunkGraph is created). Instead of opearting on Chunks and ChunkGroups, mapper now operates just on modules and moduleGraph.
IMO it also simplifies the logic as right now idea is rather simple:
1. Based on information from static analysis ("extract queries") we already did and know which files contain static queries and `<Slice>` placeholders, we find corresponding webpack modules in compilation. We also find modules that represent page templates and some boundary points (`async-requires`, entry point modules (`app.js` or …

refactor: track static queries and slice placeholder using module graph instead of chunk graph and do it in earlier webpack step

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/src/components/title-named-export.js
integration-tests/artifacts/src/components/title-re-export.js
integration-tests/artifacts/src/pages/import-re-export.js
packages/gatsby/src/utils/webpack/plugins/static-query-mapper.ts

Remove check for re-exports in static query mapper webpack plugin and add a test.
See the [relevant comment]( https://github.com/gatsbyjs/gatsby/pull/36922/files/8ccf720b183cb11525874f81bf69230725af5869#r1009345906) from https://github.com/gatsbyjs/gatsby/pull/36922 for more context.
N/A
[sc-57702]

feat(gatsby): Traverse re-exports in static query mapper

---

packages/gatsby/src/utils/webpack.config.js
packages/gatsby/src/utils/webpack/loaders/client-components-requires-writer-loader.ts
packages/gatsby/src/utils/webpack/loaders/virtual.js
packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts

There's quite a lot changes in this PR, but main one is that instead of trying to modify ChunkGraph after it's created, we modify mostly ModuleGraph (for non-css assets) before ChunkGraph is created. This allow webpack to just build correct ChunkGraph from start.
Idea is rather simple:
- we remove connection between between `async-requires` and page templates. If this is the only reason for page templates to be bundled, that result in never creating chunks for page templates. If page template is marked as client component (or page template is imported by a client component) webpack will bundle it. This is much easier to reason with that removing modules/chunks manually as we just let webpack do it's usual thing and don't have to massage ChunkGraph ourselves.
- we add dynamic imports for …

fix: partial hydration chunking

---

packages/gatsby/src/bootstrap/load-config/index.ts
packages/gatsby/src/utils/flags.ts

- Removes slices flag
- Make slices and partial hydration either-or until they're interoperable (i.e. when partial hydration is GA)
No change needed, already noted in the limitations section of the [how-to guide](https://github.com/gatsbyjs/gatsby/pull/36763/files#diff-1e83b274855cf14f2ef8d8010fe461f4d229debf4356e8249218ecd79c3d2248)
[sc-57316]

chore(gatsby): Remove slice flag

---

packages/gatsby/src/redux/reducers/html.ts

We currently mark html for (re)stitching when:
- slices used by a page changed (special case is first time slice is produced - it is like it changed from nothing to something)
- when special scripts slice is regenerated (basically when browser bundle changes)
But we were not (re)stitching when just base page was regenerated and none of the slices used by a page did (there might be 0 user slices, there is always at least 1 special gatsby scripts slice).
This result in following empty slice placeholder on outputted html:
This PR just makes sure we mark page for (re)stitching if it was regenerated

fix(gatsby): stitch slices if just page html was regenerating without any of used slices regenerating

---

packages/gatsby-remark-embed-snippet/src/index.js

At the moment embed plugin does not recognize `csproj` files (they are somehow similar to `package.json` but from dotnet world)
And because of that no highlight available from prism and other plugins 🤷‍♂️

feat(gatsby-remark-embed-snippet): added csproj to language map so it will be recognized as xml

---

docs/docs/tutorial/part-4/index.mdx

It may have been just me, but when I was following [this part](https://www.gatsbyjs.com/docs/tutorial/part-4/#:~:text=export%20default%20BlogPage-,Pro%20Tip%3A,-The%20Gatsby%20Head) of the tutorial. I copied and pasted the code and replaced what I already had in the Head of my blog page, since I was following it sequentially. I faced various errors since the GraphQL query didn't have the data for the metadata; only to realize this was already handled by the Seo components some steps ago. So I wanted to make a note to make it clear that this wasn't necessary since we had the Seo component already.
Also, the video tutorial (pretty good!) doesn't mention or show this tip so it took me longer to realize my mistake.
https://www.gatsbyjs.com/docs/tutorial/part-4/
No related issues.

chore(docs): Add clarification for Pro Tip on Part 4 of tutorial

---

packages/gatsby-link/index.d.ts

Since the merge of https://github.com/gatsbyjs/gatsby/pull/36888, `gatsby-link` is no longer exporting the type as default, typescript no longer provides typings for `Link` components.
Currently the `gatsby` package is exporting `Link` but there is no type for it defined in `index.d.ts` in `gatsby-link` only `GatsbyLink`.
As this is only a typing issue, the use of the component is working fine, but there is no intellisense support.
This PR renames the `GatsbyLink` type definition to `Link` to resolve this issue.
Shouldn't need any mention or update in docs.
Related to PR https://github.com/gatsbyjs/gatsby/pull/36888

chore(gatsby-link): Correct type export

---

packages/gatsby/cache-dir/slice.js

This is implementation detail we use for better code frames that currently is:
a) exposed to slice template itself (should not be there)
b) can change the props hash when `<Slice>` placeholder change position in js file and therefore force rebuilds we don't want or need

fix: drop `__renderedByLocation` prop when calculating slice props hashes and don't expose it to slice component

---

packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts

This is mostly for test purposes where webpack config gets recreated and each time it is recreated we lose "previous state" and act like it's entirely new thing. Hoisting those variables outside of `apply()` function/method scope allow re-use of those variables in future re-compilations
[ch-57103]

chore: preserve previous webpack stats derived values, even if we restart webpack itself

---

README.md
packages/gatsby/README.md

Updates content on main READMEs
[ch57301]

chore: Update main README

---

package.json

Same as https://github.com/gatsbyjs/gatsby/pull/33638 - use `latest-v4` dist tag for v4 releases

chore(lerna): Use latest-v4 npm dist tag in 4.24 branch

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md

Note about multiple GraphQL versions to v4 => v5 migration doc.

chore(docs): Add multiple graphql versions to v4-v5 migration

---

docs/docs/conceptual/graphql-concepts.md

- fix the typo in graphql-concepts fragments section
Fixes #36991

chore(docs): fix graphql-concepts typo

---

docs/docs/reference/release-notes/v5.0/index.md

In the v5 Release Notes, the anchor link to "Slice API" was broken.
This PR fixes this.
This link in GitHub release is also broken.
https://github.com/gatsbyjs/gatsby/releases/tag/gatsby%405.0.0
```diff
Welcome to gatsby@5.0.0 release (November 2022 #1)
Key highlights of this release:
- - [Slices API](https://www.gatsbyjs.com/docs/reference/release-notes/v5.0/#slices-api) - Only re-build individual slices of your page
+ - [Slice API](https://www.gatsbyjs.com/docs/reference/release-notes/v5.0/#slice-api) - Only re-build individual slices of your page
- [Partial Hydration (Beta)](https://www.gatsbyjs.com/docs/reference/release-notes/v5.0/#partial-hydration-beta) - Improve frontend performance by shipping less JavaScript
- [GraphiQL …
```

chore(docs): Fix broken link in v5 Release Notes

---

docs/docs/custom-html.md
docs/docs/reference/release-notes/v5.0/index.md

Adds an overview video to the release notes and edits the docs about `html.js` a bit.

chore(docs): Add overview video to release notes (+ other misc)

---

packages/gatsby/package.json
packages/gatsby/src/utils/start-server.ts
yarn.lock

See https://github.com/graphql/express-graphql/pull/816 + `express-graphql` doesn't have updated peer deps for graphql@16, causing quite a lot of problems when installing with npm (for whatever reason yarn seems to more resilient to things like that). This is attempt at 1:1 replacement preserving some customizations we had weith `express-graphql` ( showing stack traces per graphql error + showing some toggles as extensions)
[ch-58093]

chore: migrate from express-graphql to graphql-http

---

docs/docs/how-to/performance/using-slices.md

Small change to leverage (what I think was intended) returning JSX from the array, instead of a forEach. 
https://www.gatsbyjs.com/docs/how-to/performance/using-slices/
n/a

fix(docs): update forEach to use map

---

packages/gatsby-graphiql-explorer/src/app.jsx

Allow refresh endpoint in GraphiQL explorer to be enabled with `ENABLE_GATSBY_REFRESH_ENDPOINT=true`, currently only works with `ENABLE_GATSBY_REFRESH_ENDPOINT=1` due to the unary plus.
Briefly tried adding `gatsby-core-utils` as a dep to use the `isTruthy` util, but that didn't work for some reason so I added a limited version of the logic instead.
- https://www.gatsbyjs.com/docs/refreshing-content/
- https://www.gatsbyjs.com/docs/how-to/querying-data/running-queries-with-graphiql/#enable-refresh-content-button
Fixes https://github.com/gatsbyjs/gatsby/issues/37002

fix(graphiql-explorer): Adjust env var truthiness logic

---

docs/docs/reference/release-notes/migrating-from-v2-to-v3.md

Fix Known Issue in legacy browsers (IE 11): "Object doesn't support property or method 'setPrototypeOf'"
Add changes to migration guide (version 2 to 3) to outline steps for addressing a known issue when migrating to Webpack5 (a requirement for GatsbyJS v3) and targeting IE 11 legacy browser. The change describes the error displayed in browser, how to create a custom polyfill, and how to inject it into Webpack using gatsby-node.js onCreateWebpackConfig API.
The following link describes browser support for Gatsby v3, but fails to mention this known issue:
https://v3.gatsbyjs.com/docs/how-to/custom-configuration/browser-support/#polyfills

chore(docs): Add IE 11 note to v2 to v3 migration guide

---

e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-inline-scripts.js
e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-scripts-with-sources.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-inline-scripts.js
e2e-tests/production-runtime/cypress/integration/gatsby-script-scripts-with-sources.js

Encountered flakes in a prior CI run related to `cy.go` back/forward commands. Add wait for route change like we have in other places to hopefully avoid that
N/A
N/A

chore(e2e-tests): Wait for route change on back/forward

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md

adding clarity as to when you might need to add --legacy-peer-deps (tiny change)

chore(docs): Clarify language in v4 to v5 migration guide

---

renovate.json5
scripts/renovate-config-generator.js

While working on #31385, I realized that I have Cypress v9 in front of me, while v11 is already out.
We already included cypress into renovate, which was the intention to update the e2e cypress versions --> https://github.com/gatsbyjs/gatsby/pull/35375

build: include e2e tests in renovate config

---

packages/gatsby-source-wordpress/ARCHITECTURE.md
packages/gatsby-source-wordpress/src/gatsby-node.ts
packages/gatsby-source-wordpress/src/utils/run-steps.ts

This will allow us to remove extra exports in DSG

chore(gatsby-source-wordpress): remove runApisInSteps and call runApiSteps for each gatsby-node api

---

docs/docs/quick-start.md

Adds -- to force the -y to be passed along
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/quick-start.md#use-flags
Fixes #37019

chore(docs): Add `--` to quick start flags

---

packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
packages/gatsby-core-utils/src/filename-utils.ts
packages/gatsby-source-filesystem/src/utils.js

Tried decode url-encoded filename before to store remote file. So it can be served properly via generated publicURL 
Fixes #35636

fix(gatsby-core-utils): decode uri-encode filename for remote file

---

packages/gatsby-plugin-google-analytics/package.json

With this PR I update the gatsby-plugin-google-analytics' minimatch to ^3.1.2.
The 3.0.4 has a [high severity vulnerability](https://github.com/advisories/GHSA-f8q6-p94x-37v3) and it has been reported in my project where I use this plugin.

chore(gatsby-plugin-google-analytics): Update `minimatch`

---

packages/gatsby-source-filesystem/package.json
packages/gatsby/package.json
yarn.lock

Related to @pieh's comment [here](https://github.com/gatsbyjs/gatsby/pull/36342#issuecomment-1216344897). We've fixed the mentioned issue in XState so hopefully, this should allow you to migrate.

Upgrade XState to the latest 4.33.3

---

packages/gatsby/src/services/calculate-dirty-queries.ts
packages/gatsby/src/state-machines/query-running/actions.ts
packages/gatsby/src/state-machines/query-running/index.ts
packages/gatsby/src/state-machines/query-running/types.ts

I think that this should resolve the issue reported by @pieh here: https://github.com/gatsbyjs/gatsby/pull/36342#issuecomment-1216344897
Note that I have no knowledge about this code, I've just analyzed the shape of the machine, and how it's using this context data and I've concluded that it was mostly used **locally** by this particular `invoke`. It was, sort of, used as an argument for this service, and to achieve that it was first set on the context and later on removed from it (from within `onDone`). So since this was "temporary" context data, I've just refactored this to use what was already available on the `event` itself and removed the redundant code.

Use `pendingQueryRuns` available on the event

---

packages/gatsby-plugin-google-gtag/README.md
packages/gatsby-plugin-google-gtag/src/gatsby-browser.js

This adds a new `delayOnRouteUpdate` option to `gatsby-plugin-google-gtag`, which is needed for correct pageview events when page transitions are in use. (e.g. with https://www.gatsbyjs.com/plugins/gatsby-plugin-transition-link/). Without this parameter, for sites that have route change animations, pageview events are logged based on the old page instead of the new page.
This ports over a change that I made to the previous (now-deprecated) `gatsby-plugin-google-analytics`: https://github.com/gatsbyjs/gatsby/pull/15610. However, I've renamed the option to `delayOnRouteUpdate` which I think is more descriptive.
Updated the README for this plugin, similarly to https://github.com/gatsbyjs/gatsby/pull/15610.
Fixes #15504

feat(gatsby-plugin-google-gtag): Add `delayOnRouteUpdate` option

---

packages/gatsby-source-contentful/src/__tests__/__snapshots__/create-schema-customization.js.snap
packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
packages/gatsby-source-contentful/src/__tests__/normalize.js
packages/gatsby-source-contentful/src/create-schema-customization.js
packages/gatsby-source-contentful/src/normalize.js
packages/gatsby-source-contentful/src/source-nodes.js

ctf-next: use link extension instead of adding ___NODE to field names

---

packages/gatsby-plugin-sitemap/README.md

Updates documentation for `gatsby-plugin-sitemap` to clarify `filterPages`' reliance on the `excludes` array. It seems easy to miss this coupling otherwise, where one might think that simply defining the `filterPages` functions will ensure it gets called. This was discussed in issue #36830.
The documentation changes would be applied to the README document at:
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#filterpages--boolean
Fixes https://github.com/gatsbyjs/gatsby/issues/36830

chore(gatsby-plugin-sitemap): Clarify filterPages' reliance on the excludes array

---

integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
integration-tests/gatsby-source-wordpress/gatsby-config.js
packages/gatsby-source-wordpress/docs/plugin-options.md
packages/gatsby-source-wordpress/src/steps/create-schema-customization/build-types.js
packages/gatsby-source-wordpress/src/steps/create-schema-customization/helpers.js
packages/gatsby-source-wordpress/src/steps/create-schema-customization/index.js
packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/index.js
packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/recursively-transform-fields.js
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/identify-and-store-ingestable-types.js
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/is-excluded.js
packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js

This allows the `options.type.MediaItem.excludeFieldNames` to be able to exclude field names on the MediaItem type during sourcing.
While fixing this I discovered interface types that have no fields due to an implementing type having every field on that interface excluded needed to be auto excluded so that this fix doesn't cause build errors.
I released a canary as `gatsby-source-wordpress@7.2.0-alpha-wordpress-exclude-fields-on-media-item.14`

feat(gatsby-source-wordpress): MediaItem.excludeFieldNames / auto exclude interface types that have no fields

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

The source plugin author docs explain how to use `unstable_createNodeManifest`, but in doing so the docs say to make a wrapper util and name it `createNodeManifest`, this is confusing because it's not necessarily obvious when skimming the doc how `createNodeManifest` is different from `unstable_createNodeManifest`. It looks like someone just forgot to add the `unstable_` prefix.
This PR changes `createNodeManifest` to `customCreateNodeManifest` to make that a bit clearer.

chore(docs): customCreateNodeManifest

---

packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js

The message there was a bit confusing for some people so this clarifies it

chore(gatsby-source-wordpress): make duplicate node message clearer

---

packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
packages/gatsby-cli/src/structured-errors/construct-error.ts
packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby-cli/src/structured-errors/types.ts

Make `type` in errorMapEntry optionally accept `context` as function so that e.g. stage can be passed through
[ch58503]

fix(gatsby-cli): Make type optionally accept context

---

integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
integration-tests/gatsby-source-wordpress/gatsby-config.js
packages/gatsby-source-wordpress/docs/plugin-options.md
packages/gatsby-source-wordpress/src/steps/create-schema-customization/build-types.js
packages/gatsby-source-wordpress/src/steps/create-schema-customization/helpers.js
packages/gatsby-source-wordpress/src/steps/create-schema-customization/index.js
packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/index.js
packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/recursively-transform-fields.js
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/identify-and-store-ingestable-types.js
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/is-excluded.js
packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js

Backporting #37062 to the 4.24 release branch
(cherry picked from commit [`0501ed3`](https://github.com/gatsbyjs/gatsby/commit/0501ed3b02cec8e19953bbe5cb90766eed996823))

feat(gatsby-source-wordpress): MediaItem.excludeFieldNames / auto exclude interface types that have no fields (#37062)

---

docs/docs/how-to/routing/mdx.md
packages/gatsby-plugin-mdx/README.md

Clarify README and docs in response to https://github.com/gatsbyjs/gatsby/issues/37048

chore(docs): Clarify MDX sourcing instructions

---

e2e-tests/mdx/cypress/integration/using-esm-only-remark-rehype-plugins.js
e2e-tests/mdx/gatsby-config.mjs
e2e-tests/mdx/package.json
e2e-tests/mdx/src/pages/using-esm-only-rehype-remark-plugins.mdx

Test that ESM-only Remark / Rehype plugins work with `gatsby-plugin-mdx`
[ch-58541]

test(gatsby): test that ESM only rehype/remark plugins work in `gatsby-plugin-mdx`

---

jest.config.js
packages/gatsby/src/bootstrap/__tests__/get-config-file.ts
packages/gatsby/src/bootstrap/get-config-file.ts

Adjust jest config to allow esm to be tested in `get-config` and Also detect esm in `src` directory to make test pass
[sc-58545]

test(gatsby): Adjust jest config, make get-config test pass in esm cases

---

packages/gatsby-remark-images/README.md
packages/gatsby-remark-images/src/index.js
packages/gatsby-transformer-sharp/src/supported-extensions.js

Build my mdx website with gatsby-plugin-mdx and gatsby-remark-images, `avif` image not show.
my gatsby-config.js
```
{
resolve: `gatsby-plugin-mdx`,
options: {
gatsbyRemarkPlugins: [
{
resolve: `gatsby-remark-images`,
options: {
maxWidth: 1200,
},
},
],
},
```
In [document](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/) it say gatsby support avif out-of-the-box. So I tried to add `avif` to the `supportedExtensions` and it works well.
What's more  I noticed the `README.md` said it only support `jpeg` and `png`, but in fact gatsby-plugin-mdx (or gatsby-remark-images) can support `webp` and `tiff` out of box.

feat(gatsby-transformer-sharp): Add `avif` to supportedExtensions

---

packages/gatsby-link/package.json
packages/gatsby-react-router-scroll/package.json
packages/gatsby-script/package.json
packages/gatsby/package.json
yarn.lock

Updates `@gatsbyjs/reach-router` from a pre-major version to stable v2
No difference between current and new: https://diff.intrinsic.com/@gatsbyjs/reach-router/2.0.0-v2.0.3/2.0.0

chore: Bump @gatsbyjs/reach-router to v2.0.0

---

packages/gatsby/src/services/initialize.ts
packages/gatsby/src/utils/parcel/compile-gatsby-files.ts

Track if a site `gatsby-config.mjs` or `gatsby-node.mjs`
[sc-58321]

feat(gatsby): Telemetry tracking for ESM 

---

packages/gatsby-source-wordpress/docs/features/media-item-processing.md

This documents the new MediaItem.excludeFieldNames option that was added in the last few weeks.

docs(gatsby-source-wordpress): document new MediaItem.excludeFieldNames option

---

docs/docs/how-to/local-development/graphql-typegen.md
docs/docs/reference/config-files/gatsby-config.md
packages/gatsby/index.d.ts
packages/gatsby/src/joi-schemas/__tests__/joi.ts
packages/gatsby/src/joi-schemas/joi.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts

This PR makes the GraphQL codegen document search paths configurable from the Gatsby configuration file.
Integrated into `gatsby-config.md`
Fixes #35853
Related to #35966
Related to #36157

feat(gatsby): Add `documentSearchPaths` option to `graphqlTypegen`

---

docs/docs/how-to/performance/using-slices.md
docs/docs/how-to/testing/unit-testing.md

Coming from https://github.com/gatsbyjs/gatsby/discussions/37139 the request pointed out that our docs could need an upgrade for when someone wants to test a component that contains a `Slice` placeholder.

chore(docs): Add Slice placeholder to unit testing mocks

---

docs/docs/how-to/styling/theme-ui.md
examples/using-vanilla-extract/package.json
packages/create-gatsby/src/questions/features.json
packages/create-gatsby/src/questions/styles.json

- Use `gatsby-plugin-google-gtag` instead of `gatsby-plugin-google-analytics` since the latter will get deprecated by Google
- Change install deps for Theme UI and vanilla-extract (correct peerDeps now)
- Update Theme UI docs
- Update vanilla-extract example

fix(create-gatsby): Update questionare

---

packages/gatsby-plugin-page-creator/src/gatsby-node.ts
packages/gatsby-source-shopify/src/gatsby-node.ts
packages/gatsby-source-wordpress/src/gatsby-node.ts
packages/gatsby-source-wordpress/src/utils/run-steps.ts
packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap

We made this API stable in v4 and should now remove the conditional codepaths as it also causes some troubles with TS => ESM conversion where the conditional exports are `undefined`
https://github.com/gatsbyjs/gatsby/pull/33062

fix: Remove obsolete `unstable_onPluginInit` codepaths

---

e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js
e2e-tests/development-runtime/gatsby-node.js
e2e-tests/development-runtime/src/pages/collection-routing/{GatsbyPathMaterializedParent.childType__name}/{GatsbyPathMaterializedParent.name}.js
packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
packages/gatsby-plugin-page-creator/src/create-pages-from-changed-nodes.ts
packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
packages/gatsby-plugin-page-creator/src/derive-path.ts
packages/gatsby-plugin-page-creator/src/gatsby-node.ts
packages/gatsby-plugin-page-creator/src/tracked-nodes-state.ts
packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/resolvers.ts

This adds a new method to `nodeModel` called `getFieldValue`. Previously inside `gatsby-plugin-page-creator` the `derivePath` function was using `_.get` on the Node but if you e.g. use `@link` directive those nested fields were not materialized yet.
The new `getFieldValue` runs `prepareNodes` under the hood before getting the value.
No updates needed
[ch58643]
Fixes https://github.com/gatsbyjs/gatsby/issues/37103

fix(gatsby,gatsby-plugin-page-creator): Materialize nodes in gatsbyPath

---

packages/gatsby/src/utils/worker/child/render-html.ts

Improves the error page shown when html rendering fails while in Gatsby Preview mode.
Error page looks roughly like this now:
[ch58983]

feat(gatsby): Better renderHtml Preview Error

---

e2e-tests/path-prefix/cypress/integration/asset-prefix.js
e2e-tests/path-prefix/gatsby-node.js
e2e-tests/path-prefix/src/components/layout.js
packages/gatsby/cache-dir/loader.js

If an asset or path prefix has been set and prefix paths is enabled, slice data should loaded using that prefix.
As slice data are non-HTML resources, they should follow the existing documentation for asset prefixes in https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/asset-prefix/
Addresses https://github.com/gatsbyjs/gatsby/discussions/37143

fix(gatsby): Use path prefix when loading slice data

---

packages/gatsby-plugin-sharp/README.md
packages/gatsby-plugin-sharp/src/gatsby-node.js
packages/gatsby-plugin-sharp/src/image-data.ts
packages/gatsby-plugin-sharp/src/index.js

https://github.com/gatsbyjs/gatsby/pull/37165 tried to fix an error that really should be fixed by correctly passing `failOn` to all our sharp pipelines.
https://github.com/gatsbyjs/gatsby/discussions/37151
[ch59059]

fix(gatsby-plugin-sharp): Pass `failOn` to all pipelines

---

packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/query/query-runner.ts
packages/gatsby/src/utils/__tests__/page-data.ts
packages/gatsby/src/utils/page-data.ts
packages/gatsby/src/utils/worker/child/render-html.ts

The goal of this PR is to improve the readability of errors while HTML rendering and the warnings about long running queries.  It's improved by removing verbosity that isn't that all too helpful.
- The HTML rendering error previously output the whole page data object **including** the GraphQL and getServerData results. I removed these results from the error as the thrown errors by GraphQL are already good enough to find out what the error is. While yes, having the whole GraphQL result available is also a way of spotting where data is missing, normally the GraphQL errors are good enough to spot the error. There is really only a yes/no on this, as truncating the result data would be a hit or miss. Maybe we'd not truncate the relevant parts, maybe we would.
- The long running queries warning …

fix(gatsby): Improve readability of page data / long running query warnings

---

docs/docs/how-to/testing/visual-testing-with-storybook.md

Per this discussion, this is required for React 17 + Gatsby + Storybook to work, adding this line fixes it.  Without this note, it is tough to know why there is a bug.  Hopefully this helps users following the guide.
https://github.com/gatsbyjs/gatsby/discussions/36293

chore(docs): Add auto config change for `react-dom` in Storybook

---

packages/gatsby-source-wordpress/docs/features/media-item-processing.md

1. Removed a couple example fields from options.type.MediaItem.excludeFieldNames that can cause problems for some sites to exclude.
2. Added a note about why you might want to disable static files/images in html fields

docs(gatsby-source-wordpress): improve media item docs for large sites

---

packages/gatsby/src/bootstrap/get-config-file.ts
packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
packages/gatsby/src/bootstrap/resolve-js-file-path.ts
packages/gatsby/src/bootstrap/resolve-module-exports.ts
packages/gatsby/src/utils/import-gatsby-plugin.ts

Fixes for errors on Windows after https://github.com/gatsbyjs/gatsby/pull/37068:
```
Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received 
protocol 'c:'
```
Fixes #37251
https://github.com/nodejs/node/issues/31710

fix(gatsby): use file:// protocol when importing gatsby-config/node

---

packages/gatsby-plugin-image/src/babel-plugin-parse-static-images.ts
packages/gatsby-plugin-image/src/node-apis/parser.ts

The `state.filename` from babel isn't normalized, the `filename` coming from `preprocessSource` is. So there was a mismatch between the hashes on Windows. This fixes it by also normalizing was comes from babel.
https://github.com/gatsbyjs/gatsby/issues/37251#issuecomment-1351287128

fix(gatsby-plugin-image): Normalize filename for correct hashing

---

packages/gatsby-transformer-remark/README.md
packages/gatsby-transformer-remark/src/__tests__/gatsby-node.js
packages/gatsby-transformer-remark/src/gatsby-node.js

The same as https://github.com/gatsbyjs/gatsby/pull/35830 but now just for `gatsby-transformer-remark`.
I polished the README a bit and added the new plugin option.
[ch59306]

fix(gatsby-transformer-remark): Disallow JS frontmatter by default

---

docs/docs/reference/config-files/gatsby-config.md

Added a note to the docs for GraphQL TypeGen that states that directorySearchPaths is only available in Gatsby 5.3 or later.

chore(docs): Add version hints to `graphqlTypegen`

---

packages/gatsby-plugin-google-analytics/README.md

To avoid leading people to a different plugin named gatsby-plugin-gtag (which I almost used instead of gatsby-plugin-google-gtag) : https://www.gatsbyjs.com/plugins/gatsby-plugin-gtag/

chore(gatsby-plugin-google-analytics): Fix typo in README

---

packages/create-gatsby/src/__tests__/init-starter.ts
packages/create-gatsby/src/init-starter.ts
packages/gatsby-cli/src/init-starter.ts

This PR ensures that we always use `--legacy-peer-deps` when installing packages from `create-gatsby`/`gatsby-cli`. Additionally, I also added the `no-audit` flag to suppress the irrelevant warnings.
[ch59546]

fix(create-gatsby,gatsby-cli): Always use `--legacy-peer-deps`

---

packages/gatsby/src/schema/graphql-engine/standalone-regenerate.ts
packages/gatsby/src/utils/webpack/loaders/webpack-remove-exports-loader.ts

We use custom loader to remove gatsby-node lifecycles that are not relevant to engines runtime in https://github.com/gatsbyjs/gatsby/blob/86e16851efd497fecd6cf3995239b606bd5d365a/packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts#L114-L131
This however is currently not always working as expected as the loader currently expect sourceMap to be generated alongside transformed code before using the transformed code. If map is not generated we discard transformed code.
This PR allow usage of transformed code if it's not accompanied by sourcemap - we will only do passthrough if transformed code is not generated.

fix(gatsby): [rendering engines] use results of exports removal if sourceMap was not generated alongside transformed code

---

packages/gatsby/src/utils/webpack-utils.ts

Currently `file-loader` / `url-loader` emits duplicate to seperate locations:
- `public/static`:
- `.cache/page-ssr/routes/static`:
`public/static` is where we want assets to go, as those are the assets that will be uploaded. This outpath is used during `build-javascript` or `develop` stage.
`.cache/page-ssr/routes/static`  is result of using output settings for `build-html` / `develop-html` ( https://github.com/gatsbyjs/gatsby/blob/770748d33f8fbe08adf4c7911d71f453bb14befb/packages/gatsby/src/utils/webpack.config.js#L144-L149 )
This PR adjust `url-loader` and `file-loader` for `build-html` and `develop-html` stages to output to `public` while preserving what urls are generated.
Alternatively there is option to skip asset emission ( https://v4.webpack.js.org/loaders/file-loader/#emitfile …

fix(gatsby): don't output file-loader assets to .cache

---

packages/gatsby-worker/src/__tests__/integration.ts

Optimistic timeout increase to hopefully decrease amount of flaked windows unit tests. Example of that https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/88109/workflows/510b5017-fc05-4388-ab35-e4e02705e8a1/jobs/1063569/tests#failed-test-0
I did not investigate wether it's timeout issue or there is different reason for flakiness on Windows CI, so this is mostly cheap experiment to run

test(gatsby-worker): increase jest timeout

---

docs/docs/how-to/querying-data/use-static-query.md
docs/docs/reference/built-in-components/gatsby-slice.md

Documents existing limitation that `<Slice />` placeholders and `useStaticQuery` must be used in files in the `src` directory.
- https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-slice/#restrictions-on-using-slice-placeholder
- https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/
[sc-59741]

docs: Add src dir limitation to slices and useStaticQuery

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

`getNodesByType` is decomposed from the actions, but it's never used, so I removed it.

docs(how-to): remove unecessary decomposition

---

packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-images/src/index.js

While the [HTML img spec](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) does not mention the case of duplicate `alt` and `title` attributes on an `img` element (that I can find), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#the_title_attribute) does mention we shouldn't do that so that screen readers do not make duplicate announcements.
The [HTML spec general guidelines](https://html.spec.whatwg.org/multipage/images.html#general-guidelines) say that `title` is fine as supplemental information, so we want to keep the ability to set both `alt` and `title`, just not default the value of `title` to `alt` if `title` is not explicitly set in markdown.
Setting the default of `title` to an empty string means that the `img` element [will not …

fix(gatsby-remark-images): Do not fallback title value to alt value

---

docs/docs/how-to/performance/partial-hydration.md

Since we required Node 18 for this, users will have npm 7+ and need the `--legacy-peer-deps` flag.  Otherwise they get an error using the current install command in the docs.

chore(docs): Add `--legacy-peer-deps` flag for experimental React

---

docs/docs/reference/built-in-components/gatsby-script.md

Add existing limitation to docs.
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-script/#limitations
Resolves https://github.com/gatsbyjs/gatsby/issues/37024

chore(docs): Add wrapRootElement limitation to off-main-thread

---

packages/gatsby-source-contentful/src/gatsby-node.js

`contentTypeFilter` plugin option is missing from Joi schema, and there's a warning when running gatsby build

fix(gatsby-source-contentful): Add contentTypeFilter to Joi schema

---

packages/gatsby/package.json
yarn.lock

Backporting https://github.com/gatsbyjs/gatsby/pull/37401 to the 4.25 release branch
(cherry picked from commit https://github.com/gatsbyjs/gatsby/commit/7a382f2b080ad02dbecbb93d21c9e90e9f529162)

chore(deps): Bump yaml-loader (#37401)

---

packages/gatsby/index.d.ts

I've found https://stackoverflow.com/questions/75017011/gatsby-5-ts-and-new-slice-component and it's a valid bug:
The root cause is the lack of this feature request that would allow our intended usage: https://github.com/microsoft/TypeScript/issues/17867
So we're sacrificing some type guards here but all the proposed solutions in the issue and on SO didn't work.
No update needed

chore(gatsby): Improve SlicePlaceholderProps type

---

docs/docs/how-to/testing/unit-testing.md

Update import statement for `pathsToModuleNameMapper` from `ts-jest/utils` to `ts-jest`, in 'Using tsconfig paths' section of the Unit Testing Guide.
Currently, attempting to follow the tutorial will result in an error: `Cannot find module 'ts-jest/utils'`. Since [ts-jest@28 and later](https://kulshekhar.github.io/ts-jest/docs/28.0/getting-started/paths-mapping/#jest-config-with-helper), `pathsToModuleNameMapper` is imported directly from `ts-jest`, instead of `ts-jest/utils`. This PR brings the import statement in the docs up to date.

chore(docs): Fix `ts-jest` import statement in Unit Testing Guide

---

packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/write-queries-to-disk.js

A recent [integration test failure](https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/88382/workflows/71669500-8172-4961-9f78-953bc56f4cb6/jobs/1067411) happens because we check for `no such file or directory, stat` when the error message is `no such file or directory, lstat`.
Instead use the `force` option of `rmSync`, which ignores exceptions if the path doesn't exist.
If this doesn't fix it then I'll change this to compare `no such file or directory` since we don't care about `stat` vs `lstat` anyway here.
N/A
N/A

fix(gatsby-source-wordpress): Force removal of types

---

packages/gatsby-plugin-mdx/src/__tests__/remark-mdx-html-plugin.ts
packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts

Change the wrapping element type we generate when handling html nodes from `div` to `span` so that remark plugins can handle inline elements.
This avoids situations where the generated `div` becomes a child of elements with a phrasing content model like `<p>`, which is invalid HTML.
Nice explanation of this I found - https://stackoverflow.com/questions/8397852/why-cant-the-p-tag-contain-a-div-tag-inside-it/34683474#34683474
N/A
Resolves https://github.com/gatsbyjs/gatsby/issues/37292

fix(gatsby-plugin-mdx): Default remark node to span

---

e2e-tests/path-prefix/cypress/integration/asset-prefix.js
e2e-tests/path-prefix/cypress/integration/path-prefix.js
e2e-tests/path-prefix/package.json
e2e-tests/path-prefix/src/pages/file-loader.js
packages/gatsby/src/utils/webpack-utils.ts

In https://github.com/gatsbyjs/gatsby/pull/37284 we stopped duplicate output of files, but also removed the ability to set `assetPrefix` and `pathPrefix` for files handled by `file-loader`. This change restores that functionality.
N/A
Fixes https://github.com/gatsbyjs/gatsby/issues/37427

fix(gatsby): Restore asset, path prefix for file-loader handled files

---

packages/gatsby-source-drupal/src/gatsby-node.js

This async function isn't being awaited. I have a theory this is causing a problem for large sites (or maybe for all sites randomly) but I haven't verified that. This should be awaited either way though so should be good to merge.

fix(gatsby-source-drupal): await async handleDeletedNode

---

packages/gatsby-plugin-preload-fonts/package.json

Just minor maintaince kind of things as right now the `--ignore` syntax for mocks doesn't work (for me). This replicates syntax from "tests" to also be used for "mocks"
This prevents following untracked files to show after `yarn bootstrap`:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
packages/gatsby-plugin-preload-fonts/__mocks__/
packages/gatsby-plugin-preload-fonts/logger-mock.js
```

chore(gatsby-plugin-preload-fonts): don't transpile mocks

---

packages/gatsby/src/utils/__tests__/browserslist.js
packages/gatsby/src/utils/browserslist.ts

This PR fixes the logic in `getBrowsersList` to properly handle [multi-environment Browserslist configs](https://github.com/browserslist/browserslist#configuring-for-different-environments).
More info available in #29943, though the root issue is the current logic always choosing `config.defaults` - with a multi-environment config, this may return `[]` which (improperly) passes through the current logic check. This can have some pretty undesirable effects on parts of the build, including it currently breaking the `hasES6ModuleSupport` helper and causing a build failure (see the [reproduction repo](https://github.com/chrissantamaria/gatsby-getbrowserslist-bug)).
Fortunately, the fix is pretty simple: browserslist exposes a [`loadConfig` …

fix(gatsby): Multi-environment browserslist configs

---

e2e-tests/development-runtime/plugins/gatsby-node-typegen/gatsby-node.ts
packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
packages/gatsby/src/bootstrap/load-plugins/validate.ts

We're adding `resolvedCompiledGatsbyNode` to the `IPluginInfo` object but weren't using that for the pluginOptionsSchema validation.
I'm adding the test case into the graphql-typegen file since it's already an existing local TS plugin.
[ch59987]
Fixes https://github.com/gatsbyjs/gatsby/issues/37319

fix(gatsby): pluginOptionsSchema in local TS plugin

---

packages/gatsby-source-contentful/src/__fixtures__/preserve-back-links.js
packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
packages/gatsby-source-contentful/src/__tests__/normalize.js
packages/gatsby-source-contentful/src/normalize.js
packages/gatsby-source-contentful/src/source-nodes.js

Some Contentful delta sync updates are currently stripping previously created back reference links when they shouldn't.
This happen because when we create a link map (which we call `foreighReferenceMap` in the plugin) we only used entries that were created or updated since last sync. If sync didn't update referencing entry, then updated entries would lose backreferences to referecing entry.
To fix the problem this PR maintains state of `foreighReferenceMap` between `sourceNodes` runs keeping it fully saturated at all times. Traversing everything in each `sourceNodes` runs would be expensive so `foreignReferenceMap` now also have sort of "delta updates":
- I introduced `foreignReferenceMapState` which is object with
-  `backLinks` (which is exact same structure as `foreignReferenceMap`, so …

fix(gatsby-source-contentful): maintain back reference map between runs

---

e2e-tests/development-runtime/cypress/integration/functionality/yaml.js
e2e-tests/development-runtime/src/pages/webpack-loader/yaml.js
e2e-tests/development-runtime/src/test-files/input.yaml
packages/gatsby/src/utils/webpack-utils.ts

In https://github.com/gatsbyjs/gatsby/pull/37401 we bumped `yaml-loader` but missed the change https://github.com/eemeli/yaml-loader/pull/27. This PR fixes https://github.com/gatsbyjs/gatsby/issues/37453 by using the correct settings.
Fixes https://github.com/gatsbyjs/gatsby/issues/37453
[ch60027]

fix(gatsby): Use correct settings for yaml-loader

---

packages/gatsby/cache-dir/loader.js

Check the path that goes into `loadPage` and see if it's something we should actually fetch.
[ch59303]

fix(gatsby): Check rawPath in loadPage

---

docs/docs/reference/release-notes/v5.0/index.md

The code snippet references `{content}`, which I believe should be `{children}`.
- N/A
- None that I could find - happy to add one to link to this if you'd like!

docs: fix v5 release notes slice example

---

packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/resolvers.ts
packages/gatsby/src/schema/utils.ts

`context.nodeModel.findAll` currently doesn't work with new `sort` syntax/structure - it still expects olds syntax with `fields` and `order` fields which was largely based as-is in #36708 as we only changed "front" in graphql schema and immediately converted to old structures for internal processing, but just in our resolver. `nodeModel` still expects old structure today, which shold be considered a bug.
[sc-60184]

fix(gatsby): nodeModel.findAll supports v5 sort argument structure

---

packages/gatsby-source-wordpress/src/steps/source-nodes/index.ts
packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js

While testing https://github.com/gatsbyjs/gatsby/pull/37478 I discovered there are some cases where not providing an empty array here as a default causes problems
I also realized the code checks for `webhookBody.preview` which doesn't ever exist and as a result causes source-wordpress to re-source all data when restarting pods. So I simplified that check and fixed it

fix(gatsby-source-wordpress): fix preview issues

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
packages/gatsby-plugin-mdx/README.md

Point out in migration guide that MDX had a major release in addition to the version bump for v5. Also improve the MDX readme a little bit more.
https://github.com/gatsbyjs/gatsby/discussions/37441#discussioncomment-4715063

chore(docs): Improve v5 migration guide around MDX

---

packages/gatsby-react-router-scroll/src/scroll-handler.tsx

Fixes the following issue:
When a user visits an anchor link (i.e. from an external website or by entering it in their browser) and then scrolls, if the user revisits the same link (again, from an external website or by entering it in their browser) they are taken to where they last scrolled to instead of the actual anchor point.
Note that this PR makes fixes that were missed from issue [#28555](https://github.com/gatsbyjs/gatsby/pull/28555).
Please note the following comment that was made some time ago in the `scroll-handler.js`:
```
/**  There are two pieces of state: the browser url and
* history state which keeps track of scroll position
* Native behaviour prescribes that we ought to restore scroll position
* when a user navigates back in their browser (this is the `POP` action)
* …
```

fix(gatsby-react-router-scroll): fix issues with anchor links

---

e2e-tests/development-runtime/cypress/integration/head-function-export/html-insertion.js
e2e-tests/development-runtime/shared-data/head-function-export.js
e2e-tests/development-runtime/src/pages/head-function-export/ssr.js
e2e-tests/production-runtime/cypress/integration/head-function-export/html-insertion.js
e2e-tests/production-runtime/shared-data/head-function-export.js
e2e-tests/production-runtime/src/pages/head-function-export/ssr.js
packages/gatsby/cache-dir/__tests__/head/utils.js
packages/gatsby/cache-dir/head/utils.js
packages/gatsby/index.d.ts

Pass `serverData` as prop (from `getServerData`) to `Head`
[ch-60342]

fix(gatsby): pass serverData to Head

---

packages/gatsby/src/services/initialize.ts

Some source plugins rely on the webhook body to work properly for preview (source-wordpress for ex grabs a jwt from the webhook body). The webhook body can be lost on initial builds if Gatsby isn't running when a user previews. This PR adds an env var to get initial webhook body values from an env var so they can be passed through when first starting Gatsby.

feat(gatsby): add initial webhook body env var to bootstrap context

---

docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md

The build might end minutes after the fetch happens which could lead to data not getting fetched on the next run if there were changes between the fetch and the end of the build.

chore(docs): set the timestamp for the lastFetch to when the fetch starts

---

docs/docs/how-to/performance/using-slices.md

Updates the How-to documentation for Slices to call out the speed improvements on the Enterprise tier.

chore(docs): Update slices how-to to reference enterprise tier

---

packages/gatsby/src/bootstrap/load-plugins/validate.ts

In https://github.com/gatsbyjs/gatsby/pull/37440/ I forgot our windows helper 🙈 
https://github.com/gatsbyjs/gatsby/discussions/33704#discussioncomment-4756763

fix(gatsby): Use windows import helper for validate

---

packages/gatsby/src/utils/webpack.config.js

When one uses `gatsby-plugin-image` the `react-dom-server` is included into the framework chunk.
Before:
After:
[ch60411]
Fixes https://github.com/gatsbyjs/gatsby/issues/37281

fix(gatsby): Move "react-dom-server" out of framework chunk

---

docs/docs/reference/built-in-components/gatsby-slice.md

chore(docs): Update gatsby-slice.md to reference styled components non-support

---

docs/docs/reference/built-in-components/gatsby-head.md
examples/using-gatsby-head/gatsby-ssr.tsx
examples/using-gatsby-head/src/components/seo.tsx

Follow up to https://github.com/gatsbyjs/gatsby/pull/37449 updating docs supporting new feature
[sc-59890]

chore(docs): Update Head API about `<html>` and `<body>` attributes

---

packages/gatsby-plugin-utils/src/index.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts

When one wants to create nodes (either for Image CDN file or image) and use TypeScript to assert the shape of the `NodeInput` object, one was at a loss since no types for that were exported.
With this PR you then can use it like this:
```ts
import type { IRemoteImageNodeInput } from "gatsby-plugin-utils"
const assetNode: IRemoteImageNodeInput = {
id,
url: data.url,
mimeType: `image/jpg`,
filename: data.url,
width: data.width,
height: data.height,
placeholderUrl: `${data.url}?w=%width%&h=%height%`,
alt: data.alt,
parent: null,
children: [],
internal: {
type: NODE_TYPES.Asset,
contentDigest: gatsbyApi.createContentDigest(data),
},
}
```

fix(gatsby-plugin-utils): Export two `IRemoteFile` utility types

---

integration-tests/ssr/gatsby-node.js
integration-tests/ssr/pages-using-engines.js
integration-tests/ssr/src/components/test-slice.js
integration-tests/ssr/src/pages/slice-usage-ssr.js
integration-tests/ssr/src/pages/slice-usage.js
packages/gatsby/cache-dir/slice.js
packages/gatsby/cache-dir/ssr-develop-static-entry.js
packages/gatsby/src/bootstrap/requires-writer.ts

Add missing support for slices when using DEV_SSR flag + tests in `integration-tests/ssr` confirming it works.
First commit just with tests fails, second passes.
Fixes #37537
[ch-60639]

fix(gatsby): support slices in DEV_SSR

---

e2e-tests/mdx/cypress/integration/fs-api.js
e2e-tests/mdx/src/pages/file with space.mdx
e2e-tests/mdx/src/pages/file+with+plus.mdx
e2e-tests/mdx/src/pages/fs-api/plus+and+static+query/{Mdx.fields__slug}.js
e2e-tests/mdx/src/pages/fs-api/space and static query/{Mdx.fields__slug}.js
packages/gatsby/src/utils/webpack/plugins/__tests__/static-query-mapper.ts
packages/gatsby/src/utils/webpack/plugins/static-query-mapper.ts

Let Static Queries work in files that are using `contentFilePath` with spaces/+ in it.
Fixes #37528

fix(gatsby): fix static query mapping when contentFilePath contains a space

---

docs/docs/how-to/routing/mdx.md

On line 396 change from `post.jsx` to `posts.jsx` to match file name of `posts.jsx` in line 356 and line 358

chore(docs): Update MDX layout template instructions

---

packages/gatsby/cache-dir/dev-loader.js
packages/gatsby/src/bootstrap/__tests__/requires-writer.js
packages/gatsby/src/bootstrap/requires-writer.ts
packages/gatsby/src/query/__tests__/file-parser.js
packages/gatsby/src/query/file-parser.js
packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
packages/gatsby/src/redux/reducers/components.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/utils/worker/__tests__/share-state.ts

Right now, in develop we create `Head` modules for every page template even if that template doesn't actually implement `Head`. Theorhetically this would be fine, but on larger projects this result in quite an increase of needed memory by webpack compilation, so this PR is crude way to limit impact of it by allowing memory usage be more in line with what it used to be before `Head` API was introduced.
As we do want people to use that API over alternatives we will have to figure out how memory usage can be optimized when `Head` is actually implemented by templates
#36899

perf(gatsby): don't create Head modules in develop if it's not used

---

packages/gatsby/index.d.ts

Removes non-existent `navigate` function from `PageProps`
Fixes https://github.com/gatsbyjs/gatsby/issues/37620

chore(gatsby): Remove `navigate` from `PageProps`

---

docs/docs/reference/built-in-components/gatsby-head.md

The following sample code leads to a SyntaxError with unterminated JSX contents.
```jsx
export function Head() {
return (
<>
<html lang="en">
<body className="my-body-class">
<title>Hello World</title>
</>
)
}
```
`<html>` and `<body>` should ends with `/>`:
```jsx
export function Head() {
return (
<>
<html lang="en" />
<body className="my-body-class" />
<title>Hello World</title>
</>
)
}
```

chore(docs): Fix typo in Head API reference

---

packages/gatsby-cli/src/structured-errors/error-map.ts

Fix a small typo in `98001` error

chore: Fix typo in error message

---

packages/gatsby/index.d.ts

Our types for `printTypeDefinitions` actions in `index.d.ts` is wrong and doesn't match actual signature ( https://github.com/gatsbyjs/gatsby/blob/7dfef0383c206142acf1a700306688615f66e3a7/packages/gatsby/src/redux/actions/restricted.ts#L350-L364 )
Fixes #37642

fix(gatsby): fix types for printTypeDefinitions action

---

packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
packages/gatsby-plugin-preact/src/gatsby-node.js
packages/gatsby/src/utils/webpack.config.js

With https://github.com/gatsbyjs/gatsby/pull/37508 our internals for the `framework` chunk changed. I decided to not do the optimization for `react-dom/server` yet as we haven't heard complaints about that in combination with Preact and its compat layer also works different so I'm not convinced that this is even needed. We could change it at a later stage, for now I just wanted to fix the test itself.
Used `gatsby-plugin-preact` in a test site, chunking seems correct:
Fixes https://github.com/gatsbyjs/gatsby/issues/37653

fix(gatsby-plugin-preact): Adjust framework chunk overwrite

---

packages/gatsby/cache-dir/head/head-export-handler-for-browser.js

Monkey patching `console.error` counts with `string` passed as a first argument, but it can be whatever value.
I'm using react-intl which logs `Error` instances using `console.error`.
In general, monkey patching is a last resort solution and shouldn't be used at all. It is a huge pain in the ass and would be lovely if it would be merged soon.

fix(gatsby): Use optional chaining in `onHeadRendered`

---

docs/docs/reference/gatsby-cli.md

Fixes dead link at https://nodejs.dev/en/learn/the-npx-nodejs-package-runner/ where the page has since been removed, and points it to the `npx` package on npm.

chore(docs): fix dead link on gatsby-cli doc

---

docs/docs/how-to/custom-configuration/typescript.md

This is a one-line PR to update the Typescript documentation around  `require.resolve` vs `path.resolve`
The example diff makes it look like the leading `./` should be omitted but (in my case at least) this caused the path to be invalid.
n/a
n/a

chore(docs): Update `path.resolve` example to include leading `./`

---

packages/gatsby/src/utils/__tests__/js-chunk-names.ts
packages/gatsby/src/utils/js-chunk-names.ts

Pages using `?__contentFilePath` result in leaking of absolute fs path to produced bundles. This PR makes that path relative before generating `componentChunkName`, making `__contentFilePath` part on par with actual template behaviour
Added unit tests. E2E of mdx should make sure it doesn't cause regression
Fixes #37677

fix(gatsby): hide absolute path of __contentFilePath in component chunk name

---

packages/gatsby/cache-dir/fast-refresh-overlay/style.js

Wrong error screen background position.
The error occurs if after scrolling on the page we get a gatsby error, the background of the error screen is absolute, so it always stays at the beginning of the page.
Bug fixed by changing position backdrop to fixed.

fix(gatsby): Change backdrop position to `fixed`

---

docs/docs/how-to/adding-common-features/adding-search.md

Removed link to gatsby ElasticSearch plugin. 
The plugin's GitHub repo does not exist anymore.
https://github.com/search?q=@logilab/gatsby-plugin-elasticsearch

chore(docs): Update "Adding search"

---

packages/gatsby-cli/src/reporter/reporter-progress.ts
packages/gatsby-cli/src/reporter/reporter-timer.ts
packages/gatsby-cli/src/reporter/reporter.ts
packages/gatsby/src/utils/__tests__/api-runner-node.js
packages/gatsby/src/utils/__tests__/fixtures/api-runner-node/test-plugin-activity-map/gatsby-node.js
packages/gatsby/src/utils/__tests__/fixtures/api-runner-node/test-plugin-progress-map/gatsby-node.js
packages/gatsby/src/utils/api-runner-node.js

Currently when using `activityTimer` inside a plugin and then calling `.panicOnBuild` on that activity, the `pluginName` is not passed.
Therefore the custom error from `setErrorMap` can't be found (because `pluginName` is required).
This fixes it by optionally passing `pluginName` to `activityTimer` & `createProgress` so that `panic` and `panicOnBuild` methods on them can work correctly.
Updated the `api-runner-node` tests
Found this while working on https://github.com/gatsbyjs/gatsby/pull/37538

fix(gatsby): Pass `pluginName` to `reporter.activityTimer` & `reporter.createProgress`

---

packages/gatsby/src/bootstrap/load-config/index.ts

We are skipping setting some baseline flags when config file doesn't exist and that result in some very different code paths being used - in particular not enabling Slices flow
https://github.com/gatsbyjs/gatsby/issues/37706 mentions this, but it's not main issue there

fix: setup base flags when config file doesn't exist

---

integration-tests/artifacts/__tests__/index.js
integration-tests/artifacts/src/components/react-lazily-imported.js
integration-tests/artifacts/src/pages/react-lazy.js
packages/gatsby/src/utils/webpack/get-ssr-chunk-hashes.ts

This PR adds test case for using `React.lazy` ily imported component, editing it and asserts that templates importing it are regenereated.
First commit are just added tests that do fail. Second commit actually fixes the problem (?) and make tests green.
Added test case for `artifacts` tests
Addresses #37706

fix(gatsby): track changes to lazy components

---

packages/gatsby-dev-cli/src/local-npm-registry/verdaccio-config.js

Add `self_path` to our verdaccio configuration to hopefully fix an error that is currently thrown as `configPath property is required` (most likely introduced with https://github.com/verdaccio/verdaccio/pull/3658)

fix(gatsby-dev-cli): Add `self_path` to verdaccio config

---

packages/gatsby/package.json
yarn.lock

Remove obsolete package from gatsby that causes deprecation warning during install. This was added for gatsby-admin but not removed when gatsby-admin was removed itself. Can't find any other uses for it.
#23734
#33278

chore(gatsby): Remove obsolete `st` package

---

docs/docs/how-to/performance/partial-hydration.md

Our documentation state limitation that existed before https://github.com/gatsbyjs/gatsby/pull/36960 . This was merged and removed that limitation
Fixes #37730

docs: Update partial-hydration.md and remove outdated incompatibility note

---

packages/gatsby-plugin-page-creator/src/gatsby-node.ts

This PR fixes a bug in the development server where pages that are deleted and re-created in the data layer don't actually have their pages re-created if the user has `trailingSlash: always`, either explicitly or as the default. The issue seems to stem from `knownPagePaths` being passed a path generated without regard for the `trailingSlash` option when creating a page, but checks for the actual path of the page that does respect `trailingSlash` when deleting.
No features change from this bugfix, so I don't think any new documentation is needed.
No automated tests yet, I manually tested in a minimal project that was suffering from this issue by rearranging stuff in dist.
Quick screencasts of manual changes with console logs:
Current: …

fix(gatsby-plugin-page-creator): Track correct `knownPagePaths`

---

packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts
packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts

Fix to bug #37704 using @meganesu 's potential solution and updating the tests as required by @LekoArts . 
I'm afraid I do not know where to find this plugin's documentation 😞 
I added tests to:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts
As mentioned [here](https://github.com/gatsbyjs/gatsby/pull/37708#issuecomment-1449478932), I've added the new formatted headlines and ensured the expected behaviour. 
Fixes https://github.com/gatsbyjs/gatsby/issues/37704

fix(gatsby-plugin-mdx): Account for links/inline code in ToC

---

docs/tutorial/building-a-theme.md

- [Importing `Themed` from Theme UI from the incorrect path](https://theme-ui.com/mdx/themed)
- There are missing dependencies to actually using `gatsby-plugin-theme-ui`

chore(docs): Update "Building a theme" tutorial

---

packages/gatsby/src/utils/webpack.config.js

In our webpack caching setup, correctly look for .js and .mjs variants of `gatsby-node.mjs`. The bug mentioned in https://github.com/gatsbyjs/gatsby/discussions/37069#discussioncomment-5022158 happened when one used `onCreateWebpackConfig` in a `gatsby-node.mjs` file.
Didn't add any
Fixes https://github.com/gatsbyjs/gatsby/discussions/37069#discussioncomment-5022158

fix(gatsby): Correctly cache gatsby-node.mjs in webpack

---

packages/gatsby-cli/src/create-cli.ts

It currently does not look like there's a way to enable React profiling other than passing the cli argument `--profile`. This PR adds support for a `REACT_PROFILE` env var to set that flag in situations where the flag cannot be passed, such as with builds on Gatsby Cloud.
Before merging and releasing this change, I would want to update documentation in two places:
- https://support.gatsbyjs.com/hc/en-us/articles/360052322954-Environment-Variables-Specific-to-Gatsby-Cloud
- https://www.gatsbyjs.com/docs/profiling-site-performance-with-react-profiler/#using-the-profiler-api
I need to determine how to test this. I don't see any relevant unit tests. And I'm not sure how to go about testing this change absent of using `patch-package` / locally adjusting `gatsby` in my `node_modules` for a …

feat:(gatsby-cli) - support REACT_PROFILE env var value to set profile cli argument

---

docs/docs/profiling-site-performance-with-react-profiler.md

This should have gone out with https://github.com/gatsbyjs/gatsby/pull/37754 but better late than never!
Updates here: https://www.gatsbyjs.com/docs/profiling-site-performance-with-react-profiler/#using-the-profiler-api
N/A
N/A

chore(docs): update react profile docs to include reference to `REACT_PROFILE`

---

packages/gatsby-source-shopify/__tests__/__snapshots__/create-operations.ts.snap
packages/gatsby-source-shopify/__tests__/__snapshots__/create-schema-customization.ts.snap
packages/gatsby-source-shopify/__tests__/__snapshots__/source-from-operation.ts.snap
packages/gatsby-source-shopify/src/create-operations.ts
packages/gatsby-source-shopify/src/helpers.ts
packages/gatsby-source-shopify/src/process-bulk-results.ts
packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
packages/gatsby-source-shopify/src/query-builders/products-query.ts
packages/gatsby-source-shopify/src/type-builders/location-type.ts
packages/gatsby-source-shopify/src/type-builders/order-type.ts
packages/gatsby-source-shopify/src/type-builders/product-type.ts
packages/gatsby-source-shopify/src/type-builders/product-variant-type.ts

Move to Gatsby Node Id instead of shopify ids to make relationships. I've added _fields so we don't introduce a possible breaking change for users using onCreateNode

feat(gatsby-source-shopify): use gatsby node id to enable relationships

---

packages/gatsby/src/redux/reducers/inference-metadata.ts
packages/gatsby/src/redux/types.ts
packages/gatsby/src/schema/index.js

These changes drop gatsbyjs.com schema building time from 16s to 7s.
For a Contentful site with 4.9M nodes it drops schema building time from 520s to 380s. It also allows the 4.9M node site to build with significantly less memory. Previously it needed 64Gi of memory, now it can build with 24Gi with these changes (+ some other changes I'll be PRing soon).
Vlad previously added code in https://github.com/gatsbyjs/gatsby/pull/19781/files#diff-d380fd3fbf5adf3933e07c737228eb75e520cdc7a5050d4d6b710acd5256d40cR48 that lets the event loop breathe between inferring each node type which was good. 
The problem with that though is it means for each node type, every node of that type will be loaded into memory before node can have an opportunity to garbage collect if it needs to. Enough memory is …

fix(gatsby): don't block event loop during inference

---

e2e-tests/development-runtime/SHOULD_NOT_SERVE
e2e-tests/development-runtime/package.json
e2e-tests/production-runtime/SHOULD_NOT_SERVE
e2e-tests/production-runtime/package.json
packages/gatsby-plugin-sharp/src/gatsby-node.js
packages/gatsby-plugin-sharp/src/index.js

Lazy images express handler should not handle serving assets other than result of currently triggered job as we do have `express.static` for that earlier in request handlers chain
Added e2e tests for dev and prod runtime

fix(gatsby-plugin-sharp): don't serve static assets that are not result of currently triggered deferred job

---

packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
packages/gatsby/src/bootstrap/load-plugins/validate.ts

The gatsby-plugin-mdx uses `gatsbyRemarkPlugins` as its sub plugin key, but gatsby only checks for the `plugins` key, which causes issue #37792 .
Fixes #37792

fix(gatsby): Validate sub plugins options

---

packages/create-gatsby/src/index.ts

Use the `siteName` inside the summary message instead of `dirName`.
Also removed an unnecessary `any` TS type assertion and updated a docs link.
I did run the CLI with the changes applied locally. It now looks like this:
```shell
➜ node ../work/gatsby/packages/create-gatsby/cli.js
create-gatsby version 3.9.0-next.0
Welcome to Gatsby!
This command will generate a new Gatsby site for you in /Users/lejoe/code/playground with the setup you select. Let's answer some
questions:
What would you like to call your site?
✔ · My Gatsby Site
What would you like to name the folder where your site will be created?
✔ playground/ my-gatsby-site
✔ Will you be using JavaScript or TypeScript?
· JavaScript
✔ Will you be using a CMS?
· No (or I'll add it later)
✔ Would you like to install a styling system?
· …
```

fix(create-gatsby): Use correct name in summary message

---

packages/gatsby/src/schema/infer/add-inferred-fields.js

For large Contentful sites the deprecation notice is really noisy, but also logging out all of the deprecations to stdout can be costly/slow. There's a really good chance it will be some time before contentful uses schema customization, so imo it's a good idea to make this less noisy. 
The type/field names are really only useful for debugging and 99% of users don't need to see it.

fix(gatsby): make `___NODE` convention less noisy

---

packages/gatsby-remark-autolink-headers/README.md

Fix typo `redudant` to `redundant `.

chore(gatsby-remark-autolink-headers): Fix typo in README

---

packages/gatsby-transformer-sqip/src/extend-node-type.js

Locally the `contentful` e2e test site was failing because `gatsby-transformer-sqip` tried to write to `/node_modules`. This PR changes the `cacheDir` location to the `.cache` folder.
The files will land here now: `.cache/caches/gatsby-transformer-sqip/intermediate-files`.
Also see this screenshot:
No change needed
Existing ones should pass
N/A

fix(gatsby-transformer-sqip): Use correct cache location

---

docs/docs/how-to/cloud/set-node-version.md

People run into issues a lot where they change node version and it doesn't take effect right away. Adding some notes here on how they can resolve this.

chore(docs): Update "Set Node.js version" cloud

---

packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts

This allows hosting images/files on other domains and with different route prefixes

feat(gatsby-plugin-utils): make image cdn urls configurable

---

packages/gatsby-source-wordpress/src/steps/persist-cached-images.ts
packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/fetch-and-create-non-node-root-fields.js
packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js
packages/gatsby-source-wordpress/src/steps/source-nodes/index.ts
packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/fetch-node-updates.js
packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/delete.js
packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
packages/gatsby-source-wordpress/src/utils/gatsby-features.ts

This PR adds support for the new `enableStatefulSourceNodes` API I added in https://github.com/gatsbyjs/gatsby/pull/37782
canary available as `gatsby-source-wordpress@7.9.0-stateful-wp.2`

feat(gatsby-source-wordpress): opt out of stale node checks

---

.circleci/config.yml
e2e-tests/themes/development-runtime/content/posts/dune.mdx
e2e-tests/themes/development-runtime/package.json
e2e-tests/themes/gatsby-theme-about/gatsby-config.js
e2e-tests/themes/gatsby-theme-about/gatsby-node.js
e2e-tests/themes/gatsby-theme-about/package.json
e2e-tests/themes/gatsby-theme-about/src/templates/post.jsx
e2e-tests/themes/production-runtime/content/posts/dune.mdx
e2e-tests/themes/production-runtime/cypress/integration/pages.js
e2e-tests/themes/production-runtime/package.json
e2e-tests/themes/production-runtime/src/gatsby-theme-about/templates/post.jsx
packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js

Mimics the logic we already have in https://github.com/gatsbyjs/gatsby/blob/0e9feebf11d071fb912ad25649b068eb39b78d8b/packages/gatsby/src/redux/actions/public.js#L323-L324 (and below) inside the Shadowing resolver.
This way the correct component path containing the resourceQuery is returned.
Not needed, this should already have worked.
Added an test to the `themes` E2E suite
Fixes https://github.com/gatsbyjs/gatsby/issues/37925

fix(gatsby): Shadowing with resourceQuery

---

docs/docs/reference/functions/getting-started.md

This PR simply adds more information about limitations of Gatsby functions and surfaces more clearly how to configure functions to work with different data formats within the `/getting-started` docs page for functions.
This is simply a docs change.
N/A
N/A

chore(docs): doc update on Gatsby functions

---

packages/gatsby-source-contentful/src/normalize.js

I introduced a small regression in https://github.com/gatsbyjs/gatsby/pull/37910. 
`entryNode` items may be null via https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/normalize.js#L496. This PR just checks that the entry node item exists before calling `createNode` on it

fix(gatsby-source-contentful): don't call `createNode` on `null`

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

The `gatsby-plugin-netlify-cms` together with the `PARTIAL_HYDRATION` feature flag fails production `build`.
The `admin` part should always be client-side rendered, thus the plugin is interfering with the CMS application and failing the build.
In addition, the netfliy-cms-app seems to be stuck at `v16` of react, so RSC and netlify-cms should be incompatible until then.
Given the recent [rebranding](https://www.netlify.com/blog/netlify-cms-to-become-decap-cms/) to DecapCMS, let me know if this package would be deprecated and if any of it's code would be moved, so I can contribute there.
For anyone trying out the [Partial Hydration](https://github.com/gatsbyjs/gatsby/discussions/36608) and being stuck &mdash; The bellow workaround seems to do the job just fine.
```jsx
{
resolve: …
```

fix(gatsby-plugin-netlify-cms): ignore PartialHydrationPlugin

---

packages/gatsby/src/utils/webpack.config.js

We currently disable any split chunking for our html gen bundle (`build-html`). This can result in very large bundles being produced when large module/package is shared between many page templates and in output bundle we have copies of that large module in each template it was used.
This PR set (explicitely) default webpack split chunking config for our `build-html` bundle allowing large modules/packages to be split to shared ones and potentially decreasing size of produced SSR/DSG engines
The webpack defaults we used are taken from https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks 
--edit
Some numbers from trying this change on gatsbjs.com builds (average from 4 runs from cold cache):
- baseline: `173.7s`
- with changes: `153.7s`
I'm not sure I trust those …

feat(gatsby): apply default webpack split chunking config to html gen bundle

---

packages/gatsby/src/commands/build-html.ts

Fixed typos when running `gatsby build`. Previously it said 
```js
"stiching slices"
...
stichQueue.push(pagePath)
```
when it should be 
```js
"stitching slices"
...
stitchQueue.push(pagePath)
```
This fix didn't warrant any documentation
No tests were added.

fix(gatsby): Correct `stitching slices` build activity name

---

examples/using-drupal/gatsby-config.js
examples/using-drupal/src/pages/index.js
examples/using-drupal/src/pages/recipes.js
examples/using-drupal/src/pages/{DrupalRecipes.title}.js
packages/babel-preset-gatsby-package/package.json
packages/gatsby-source-drupal/README.md
packages/gatsby-source-drupal/src/gatsby-node.ts
packages/gatsby-source-drupal/src/normalize.ts
packages/gatsby-source-drupal/src/utils.ts

Adds support for type prefixes to the Drupal source plugin. When set, all types generated by the plugin are prefixed with that value. This is analogous to similar options in the Shopify and WordPress plugins.
I've added it to the README

feat(gatsby-source-drupal): add `typePrefix` option

---

packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts

Use JSON to pass the loader options in a safer way
No API changes
No tests
Fixes https://github.com/gatsbyjs/gatsby/issues/37978

fix(gatsby): avoid plus2space conversion using json encoded options

---

packages/gatsby/cache-dir/static-entry.js

Fixes a bug with `window.pagePath` value not properly escaped.
Fixes https://github.com/gatsbyjs/gatsby/issues/36348

fix(gatsby): encode window.pagePath to get valid JS code

---

packages/gatsby/src/utils/webpack/get-ssr-chunk-hashes.ts

Apparently this is possible (chunkgroup can be child of itself ...):
So this PR adds a way to break `ChunkGroup` children cycles when figuring out compund hash for templates (when visiting lazy imports)

fix(gatsby): handle cyclic chunkgroup children

---

docs/docs/tutorial/getting-started/part-6/index.mdx

`Don't forget` -> `Remember`. This is more concise, and better for people's memory. We remember *to do* things better than we remember *not to do* things.

chore(docs): Improve wording in main tutorial part 6

---

packages/gatsby-source-drupal/src/__tests__/fixtures/file.json
packages/gatsby-source-drupal/src/__tests__/index.js
packages/gatsby-source-drupal/src/normalize.ts

When detecting image nodes, `gatsby-source-drupal` looks for the `attributes.filemime` field. However this doesn't appear to be set in [this site](https://live-contentacms.pantheonsite.io/api/files) at least, but rather the `attributes.mimetype` is set. Presumably this is due to either an update or a change in config. This means that images are not being detected, so image CDN does not work. 
This PR fixes it by checking both the `filemime` and `mimetype` fields. 
Added test case and fixture

fix(gatsby-source-drupal): find mimetype field

---

e2e-tests/development-runtime/SHOULD_NOT_SERVE
e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/overlay-endpoints.js
packages/gatsby/src/commands/build-html.ts
packages/gatsby/src/utils/start-server.ts
packages/gatsby/src/utils/webpack/utils/is-file-inside-compilations.ts

This adds additional checks before serving codeframes that are used in error overlay to avoid serving unintended content
Added test case ensuring we don't serve source files not related/used in current project

fix(gatsby): don't serve codeframes for files outside of compilation

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md

Updated the code span in the document migrating-from-v4-to-v5.md

chore(docs): Typo in v4 to v5 migration guide

---

packages/gatsby-source-contentful/README.md

Fix `gatsby-source-contentful` docs for the `pageLimit` configuration option.
Its default value is `1000`, not `100`: https://github.com/gatsbyjs/gatsby/blob/cbc0b359f14f345e8d89b9d18863d52fa45ca951/packages/gatsby-source-contentful/src/plugin-options.js#L5-L17

chore(gatsby-source-contentful): Fix docs pageLimit default value

---

docs/docs/reference/graphql-data-layer/schema-customization.md

`buildInputType` is not a function of the gatsby `createSchemaCustomization` schema object, according to the error generated, so I updated the documentation Gatsby Type Builder function references.
Apparently, the schema object has `buildInputObjectType` not `buildInputType`. It also contains additional functions `buildEnumType` and `buildScalarType`.  So Gatsby’s documentation is incorrect, according to the actual Gatsby code.
Looks like the Gatsby documentation is incorrect  . The documenation at https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#gatsby-type-builders  states the following:
```
Type Builders also exist for Input, Interface and Union types: buildInputType, buildInterfaceType, and buildUnionType. Note that the createTypes action also accepts …
```

chore(docs): Update schema-customization type builder types

---

packages/gatsby-source-wordpress/src/gatsby-node.ts
packages/gatsby-source-wordpress/src/steps/auth-handling.ts
packages/gatsby-source-wordpress/src/steps/index.ts
packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts

https://github.com/gatsbyjs/gatsby/pull/32303 removes `options.auth` from plugin options to prevent leaking them to browser. However this later causes problems for engines as they are missing auth information.
This PR keeps removal of auth, but it restores it later after browser plugin options is written out. Above PR added tests to ensure secrets are not leaked, so we should be still guarded against that

fix(gatsby-source-wordpress): allow using engines when using wordpress auth

---

packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts

https://github.com/gatsbyjs/gatsby/pull/38104 showed that you can't use some modern JS syntax in MDX layout components. This is most probably due to us using `2020` in the acorn parser.
The docs at https://github.com/acornjs/acorn/tree/master/acorn/ say:
> ecmaVersion: Indicates the ECMAScript version to parse. Must be either 3, 5, 6 (or 2015), 7 (2016), 8 (2017), 9 (2018), 10 (2019), 11 (2020), 12 (2021), 13 (2022), 14 (2023), or "latest" (the latest the library supports). This influences support for strict mode, the set of reserved words, and support for new syntax features.
I think we should be fine moving it to `latest` as we use https://babeljs.io/docs/babel-preset-env which also always defaults to "latest".
https://github.com/gatsbyjs/gatsby/pull/38104 is handling docs
Existing …

fix(gatsby-plugin-mdx): Use `latest` for acorn's `ecmaVersion`

---

packages/gatsby-transformer-screenshot/README.md
packages/gatsby-transformer-screenshot/src/gatsby-node.js

Removes old AWS endpoint that we no longer provide/pay for.
Allow people to provide their own endpoint instead.
README updated
Fixes https://github.com/gatsbyjs/gatsby/issues/38129

feat(gatsby-transformer-screenshot): Add screenshotEndpoint option

---

docs/docs/how-to/previews-deploys-hosting/deploying-to-other-services.md

Added Flightcontrol as a method for deploying Gatsby Projects

chore(docs): Add Flightcontrol to "Deploying to Other Services"

---

packages/gatsby-plugin-feed/package.json

This should remove the following warning from npm: (when depending on `gatsby-plugin-feed`)
```
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
```

chore(gatsby-plugin-feed): depend on `joi` instead of `@hapi/joi`

---

packages/gatsby/src/redux/reducers/type-owners.ts

Looks like in https://github.com/gatsbyjs/gatsby/pull/37782 type owners check was added to the `TOUCH_NODE` action which is likely causing this issue. I tried this PR locally on a repro from the linked issue and it seemed to resolve it.
canary available as `gatsby@5.11.0-touch-nodes-fix.4`
Fixes https://github.com/gatsbyjs/gatsby/issues/38117

fix(gatsby): allow touching nodes owned by another plugin

---

docs/docs/how-to/styling/using-local-fonts.md

One major misspelling ('fill' -> 'will').
And then further down just a re-wording for clarity. This later part can be excluded if needed/wanted.

chore(docs): Improve "using-local-fonts"

---

packages/gatsby-remark-custom-blocks/package.json
packages/gatsby-remark-graphviz/package.json
packages/gatsby-remark-responsive-iframe/package.json
yarn.lock

Author published a breaking change in a patch release, so this is pinning `unist-util-find`.
See https://github.com/blahah/unist-util-find/issues/12
Fixes https://github.com/gatsbyjs/gatsby/issues/38258

fix: Pin broken `unist-util-find` dep

---

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.ts.snap
packages/babel-plugin-remove-graphql-queries/src/index.ts
packages/gatsby/src/utils/babel-loader-helpers.ts

- Fixes the static query directory to reflect where the data exists for newer versions of Gatsby
- Always removes static queries for Storybook builds, which are necessary for Storybook component stories with static queries
Storybook is not able to process static queries in components, so the presence of any static queries will break Storybook builds. The solution for this in [Gatsby's documentation](https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/) is to add `babel-plugin-remove-graphql-queries` to Storybook's webpack config, however this won't work out of the box since the static data path defined in `babel-plugin-remove-graphql-queries` is out of date. It will also only run for when `NODE_ENV = test` even though for Storybook we want to run it all the time. …

fix(babel-plugin-remove-graphql-queries): Correct `staticQueryDir` default and improved Storybook support

---

e2e-tests/README.md

I tried running the e2e test `playwright` and `cypress` but the documentation leads me to wrong direction.
`cd e2e-tests/gatsby-image` with this command running, since `gatsby-image` repository does not exists anymore in `master` branch. This PR updates it with `cd e2e-tests/development-runtime` since `development-runtime` repository exists. The similar applies when running tests with `./scripts/e2e-test.sh "e2e-tests/gatsby-image" "yarn test"` this command. Its gives error as : 
```
Copy e2e-tests/gatsby-image into /tmp/tmp.88bVJaY4bg to isolate test
cp: cannot stat 'e2e-tests/gatsby-image/.': No such file or directory
````
This PR just changes the outdated repo to the currently used repo.
No test added
Just a documentation fix. 
This PR does not fix any issue.

chore(e2e-tests): change deprecated e2e test repo name

---

e2e-tests/development-runtime/cypress/integration/slices/slice-via-create-page.js
e2e-tests/development-runtime/gatsby-node.js
e2e-tests/development-runtime/src/components/mapped-slice.js
e2e-tests/development-runtime/src/pages/404.js
e2e-tests/production-runtime/cypress/integration/slices/slice-via-create-page.js
e2e-tests/production-runtime/gatsby-node.ts
e2e-tests/production-runtime/src/components/mapped-slice.js
e2e-tests/production-runtime/src/pages/404.js
packages/gatsby/src/internal-plugins/prod-404-500/gatsby-node.js

When creating copy of 404 / 500 pages (from `/404/` to `/404.html`), slices overrides where not copied over. This casued slice aliasing not work in those pages.
Yes, e2e cases added to dev and prod runtimes
Fixes #38263

fix(gatsby): copy slices overrides to 404.html copy

---

docs/docs/reference/release-notes/migrating-from-v4-to-v5.md

Clarify the upgrade react step when migrating from v4 to v5. The previous step for upgrading Gatsby first has similar documentation. 
If I follow the guide on node 18 / npm 9 and run the upgrade react command (`npm install react@latest react-dom@latest`) before resolving all the other dependencies I get errors like the image below. It appears until the dependency resolution is complete by later steps `--legacy-peer-deps` is expected.
Running with `--legacy-peer-deps` results in success.

chore(docs): clarify react upgrade with --legacy-peer-deps

---

packages/gatsby-source-contentful/rich-text.d.ts
packages/gatsby-source-contentful/src/rich-text.js

GraphQL Typegen feature generates TypeScript types — [they are nullable by default](https://www.gatsbyjs.com/docs/how-to/local-development/graphql-typegen/#non-nullable-types). This should be handled for Contentful Rich Text.

fix(gatsby-source-contentful): handle nullable fields

---

docs/docs/how-to/local-development/gatsby-on-windows.md

The location of the `npm-cache/_libvips` directory seems to be incorrect in the documentation. On my Windows 11 setup, it’s located under `AppData/Local`, not `AppData/Roaming`:
Whereas the `AppData/Roaming` directory doesn't have have an `npm-cache` directory at all:

docs: update `npm-cache` directory location

---

docs/docs/reference/built-in-components/gatsby-script.md

Just fix a 1 letter typo on the Script page of the doc

Fix tiny typo (1 letter)

---

packages/gatsby/src/utils/__tests__/get-latest-gatsby-files.ts
packages/gatsby/src/utils/get-latest-gatsby-files.ts

This fixes fetching latest js and json files (for `apis.json` and `adapters.js`)

fix: fix fetching adapters manifest from latest gatsby version

---

packages/gatsby/src/internal-plugins/functions/api-function-webpack-loader.ts

Changes done to API functions compilation recently (part of adapters work) caused a regression where functions fail to compile correctly on Windows (due to path seperator / escape interaction). This converts windows style path to unix style path in a place where it cause a problem (better/safer to normalize to unix ones than trying to ensure appropiate escaping `\` escaping is applied)
Fixes #38481

fix(gatsby): fix api function compilation on Windows

---

packages/gatsby-cli/src/structured-errors/error-map.ts
packages/gatsby/src/utils/adapter/manager.ts

With release of adapters we introduced a way for adapters to report back if they support handling of `pathPrefix` and `trailingSlash` options. In that release we made gatsby break builds if user options were unsupported by adapter as it did make sense to not allow potentially faulty deploys. 
However because this wasn't major version bump it can be deemed as breaking change (especially if previously used deployment plugin didn't hard break on their own), so this change stops build failures and instead just prints a warning.
Users might be able to add their own support in some cases (in particular path prefix could be supported on Netlify with https://answers.netlify.com/t/deploy-gatsby-site-to-netlify-with-prefix-paths/1267/6 at least for static assets, but that wouldn't work for DSG/SSR …

fix(gatsby): don't break builds when using features unsupported by adapter

---

packages/gatsby/src/schema/node-model.js

As per https://github.com/gatsbyjs/gatsby/pull/37477, the nodeModel can use the new sort syntax
https://github.com/gatsbyjs/gatsby/discussions/36242#discussioncomment-6864575
https://github.com/gatsbyjs/gatsby/pull/37477

docs: Update node-model.js to new sort syntax

---

packages/gatsby-plugin-gatsby-cloud/README.md

Update gatsby-cloud-plugin README

---

packages/gatsby-adapter-netlify/src/__tests__/route-handler.ts
packages/gatsby-adapter-netlify/src/route-handler.ts

Current implementation can throw with
```
RangeError: Maximum call stack size exceeded
at String.replace (<anonymous>)
```
kind of errors. This will replace implementation and add unit tests to catch regressions in the future.
First commit just add a unit test suite + do minor refactors to module to make it easier to test (tests will fail showcasing current problem)
Second commit will change implementation and get tests to pass (proving the fix)

fix(gatsby-adapter-netlify): handle cases with large cached _redirects and/or _headers files

---

packages/gatsby-source-npm-package-search/src/gatsby-node.js

Adjust `source-npm-package-search` to pick up READMEs for
- `gatsby-plugin-gatsby-cloud`
- `gatsby-source-contentful`
from unpkg.com instead of Algolia's outdated `npm-search` to make information from
- https://github.com/gatsbyjs/gatsby/pull/38480
- https://github.com/gatsbyjs/gatsby/pull/38479
accessible to gatsbyjs.com users.
Icky/smelly, but working (tested locally).
cc @stephan1echung @pieh

chore(source-npm-package-search): bespoke treatment for `plugin-gatsby-cloud` and `source-contentful`

---

packages/gatsby/src/utils/cache-lmdb.ts
packages/gatsby/src/utils/page-ssr-module/lambda.ts

This makes `caches-lmdb` AND `gatsby-core-utils` `getStorage` open lmdb cache/storage instances in writeable location (in case CWD in lambda environment is not writeable). The FS rewrites we have there now doesn't apply to LMDB (fs handling of lmdb is not in Node.js land) so we have to explicitly deal with "fs rewrite" when LMDB is concerned. We were already addressing this for main LMDB instance (datastore), but this expands it to `cache` and `storage` usage of lmdb as well.
`gatsby-core-utils` is already using `global.__GATSBY.root` - https://github.com/gatsbyjs/gatsby/blob/47ec2ac04235d9ae45614a4596a250a44398e9cf/packages/gatsby-core-utils/src/utils/get-storage.ts#L29-L32
This PR adds similar usage to lmdb cache usage, as well as actually sets the root to writeable location in lambda …

fix(gatsby): open lmdb instances in writeable locations in generated ssr/dsg function

---

packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
packages/gatsby/src/utils/adapter/__tests__/fixtures/state.ts
packages/gatsby/src/utils/adapter/__tests__/manager.ts
packages/gatsby/src/utils/adapter/manager.ts

Fixes: https://linear.app/netlify/issue/FRA-20/external-redirects-have-a-forced-slash-added
If `route.path` begins with `http(s)://`, we shouldn't add a leading slash to it.
Fixes FRA-20

fix(gatsby): don't force leading slash for external paths in routes manifest

---

docs/docs/how-to/previews-deploys-hosting/deploying-to-other-services.md

We released the new Static Site Hosting and updated the docs so on our end. Changing the title to "Kinsta" is just more universal
It's only a minor documentation change

docs: Changes the name of one of the service

---

.circleci/config.yml

With current setup and yesterday's release of Yarn 4 we get following in our pnp tests
```
Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 18.0.0). Upgrade Node, or set `YARN_IGNORE_NODE=1` in your environment.
Yarn Package Manager - 4.0.0
$ yarn <command>
You can also print more details about any of these commands by calling them with 
the `-h,--help` flag right after the command name.
Exited with code exit status 1
```
This just bumps node version when running Yarn PnP tests to allow to continue using and testing latest Yarn / berry

test: bump node version for pnp tests

---

packages/gatsby/index.d.ts
packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
packages/gatsby/src/utils/adapter/__tests__/manager.ts
packages/gatsby/src/utils/adapter/constants.ts
packages/gatsby/src/utils/adapter/manager.ts
packages/gatsby/src/utils/adapter/types.ts

Adjustment to reduce the header file size. 
Based off of work done by https://github.com/gatsbyjs/gatsby/pull/38561. The primary difference is the equality checks for filtering the headers. `includes` doesn't work since JS checks for reference equality. 
Unit tests 
Fixes https://linear.app/netlify/issue/FRA-17/reduce-headers-file-size

fix(gatsby): Adapter header rules

---

packages/gatsby-adapter-netlify/src/index.ts

Added (info) logging for Gatsby cache store/restore based on the Slack conversation: https://netlify.slack.com/archives/C01TKAEBP3Q/p1697118392823289?thread_ts=1697112765.098159&cid=C01TKAEBP3Q
N/A
N/A
https://github.com/netlify/pillar-support/issues/779

chore: added logging for cache handling

---

e2e-tests/adapters/cypress/e2e/redirects.cy.ts
e2e-tests/adapters/gatsby-node.ts
e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
e2e-tests/adapters/src/pages/routes/redirect/existing-force.jsx
e2e-tests/adapters/src/pages/routes/redirect/hit-de.jsx
e2e-tests/adapters/src/pages/routes/redirect/hit-us.jsx
packages/gatsby-adapter-netlify/src/__tests__/route-handler.ts
packages/gatsby-adapter-netlify/src/route-handler.ts
packages/gatsby-core-utils/.gitignore
packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
packages/gatsby/src/utils/adapter/__tests__/fixtures/state.ts
packages/gatsby/src/utils/adapter/__tests__/manager.ts
packages/gatsby/src/utils/adapter/manager.ts

(Moved from https://github.com/gatsbyjs/gatsby/pull/38640)
https://linear.app/netlify/issue/FRA-19/force-is-not-honoured
https://linear.app/netlify/issue/FRA-21/conditions-on-redirects-are-not-honoured
When a [redirect is created](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect), it can accept a force parameter that can trigger the redirect even if the fromPath matches a piece of content. However, this functionality isn't working with the Adapter, possibly because the parameter isn't being passed along into the [routes handler](https://github.com/gatsbyjs/gatsby/blob/3af35ae0de6aae4bb700279317f6beec46ea50ad/packages/gatsby-adapter-netlify/src/route-handler.ts#L158-L206).

fix: respect 'force' and 'conditions' properties on redirects

---

.circleci/config.yml
e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
e2e-tests/adapters/gatsby-node.ts
e2e-tests/adapters/package.json
e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
e2e-tests/adapters/src/pages/index.jsx
e2e-tests/adapters/src/pages/routes/remote-file.jsx
e2e-tests/adapters/src/pages/routes/ssr/remote-file.jsx
e2e-tests/adapters/src/templates/remote-file-from-context.jsx
packages/gatsby-adapter-netlify/package.json
packages/gatsby-adapter-netlify/src/__tests__/file-cdn-url-generator.ts
packages/gatsby-adapter-netlify/src/__tests__/image-cdn-url-generator.ts
packages/gatsby-adapter-netlify/src/file-cdn-handler.ts
packages/gatsby-adapter-netlify/src/file-cdn-url-generator.ts
packages/gatsby-adapter-netlify/src/index.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/public-resolver.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/public-url-resolver.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/__tests__/url-generator.ts
packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
packages/gatsby/index.d.ts
packages/gatsby/src/utils/adapter/manager.ts
packages/gatsby/src/utils/adapter/types.ts
packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
packages/gatsby/src/utils/page-ssr-module/lambda.ts
types/gatsby-monorepo/global.d.ts
yarn.lock

This is just very quick draft building on top of https://github.com/gatsbyjs/gatsby/pull/38685 (a lot of similar code being replicated from IMAGE_CDN to FILE_CDN - needs more work, but at least let's try to see it in practice (completely untested even locally yet)

feat: provide custom FILE_CDN url generator from adapter

---

packages/gatsby-source-contentful/src/create-schema-customization.ts

As discussed in the gatsby-source-contentful major version thread (https://github.com/gatsbyjs/gatsby/discussions/38585#discussioncomment-7680012), there is a tiny little bug in the rich text linked asset query. The Gatsby GraphQL Node Model method `findAll` requires the query params to be wrapped in a `filter` object.
[See the findAll docs here](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/node-model/#findAll).
I did not add tests for the fix. Let me know if I should!

fix(contentful): rich text linked asset filter

---

packages/gatsby/adapters.js

https://github.com/gatsbyjs/gatsby/pull/38745 only allowed `gatsby-adapter-netlify@1.0.3` for `gatsby@">=5.0.0 <5.12.10"` versions. While that is fine when adapter is auto installed - it cause problems for users that already have lower version of adapter installed - see https://github.com/gatsbyjs/gatsby/issues/38752.
This is just quick relaxing of version range and there will be more follow up work done to prevent broken deploys in the future as mentioned in the issue - however that requires more work/time and more testing.
This was tested with monkey-patching adapters code (we do pull adapters manifest from `@latest` npm version, so I just hardcoded this change instead of pulling) and installation still worked fine:
```bash
> gatsby -v 
Gatsby version: 5.12.4
> netlify build --offline …
```

fix(gatsby): allow gatsby-adapter-netlify@">=1.0.0 <=1.0.3" for gatsby@<5.12.10

---

e2e-tests/adapters/netlify.toml
packages/gatsby-adapter-netlify/README.md

Update examples, test cases to reflect https://docs.netlify.com/image-cdn/overview/#remote-path

fix(docs): update remote url docs

---

packages/gatsby-cli/.babelrc
packages/gatsby-cli/package.json
packages/gatsby-cli/src/create-cli.ts
packages/gatsby-source-wordpress/.babelrc.js
packages/gatsby-source-wordpress/package.json
packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/generate-queries-from-ingestable-types.js
packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts
yarn.lock

vulnerability found through:
`gatsby@5.13.0-> gatsby-cli@^5.13.0 -> clipboardy@^2.3.0 -> execa@^1.0.0`
Solved by upgrading `clipboardy` to `^3.0.0`
Reduced vulnerabilities found with `yarn audit --groups dependencies` from 227 to 225
Tests remain unaffected.

chore(gatsby-cli,gatsby-source-wordpress): bump clipboardy

---

packages/create-gatsby/src/plugin-schemas.json
packages/gatsby-source-contentful/README.md

This bit me today when I wanted to use it. Apparently `forceFullSync` was removed years ago. 
@axe312ger mentioned he'd remove it in the new version, but since that's not live yet I'm proposing it here.
None
related to https://github.com/gatsbyjs/gatsby/pull/33238
caused by https://github.com/gatsbyjs/gatsby/pull/33207

fix(gatsby-source-contentful): remove outdated `forceFullSync` option from readme

---

packages/gatsby-link/index.d.ts

Gatsby's navigate() function uses @reach/router's navigate() function, but the latter returns a Promise, while the former does not. This PR updates the type of the gatsby's navigate() function to accurately reflect this.
The documentation is already correct:
https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function
https://reach.tech/router/api/navigate
fixes #22151 (which has gone stale)
related to issue #25123
related to pull request #24214

fix(types): navigate doesn't return anything

---

packages/gatsby-codemods/src/bin/cli.js

Currently, `gatsby-codemods` indiscriminantly calls the `jscodeshift` shell script for *nix and MinGW, CYGWIN, which is shell- or OS-specific and guarantees interoperability issues such as below (in PowerShell):
On
Moreover, the abovementioned shell script merely calls the Javascript source file, which is a needless indirection for NodeJS (i.e., Javascript call a shell script to call Javascript).
Result after my commit:
Published: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#graphql-schema-changes-to-sort-and-aggregation-fields
Source: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/reference/release-notes/migrating-from-v4-to-v5.md#graphql-schema-changes-to-sort-and-aggregation-fields
Ran `npx gatsby-codemods@latest sort-and-aggr-graphql . …

fix(gatsby-codemods): call jscodeshift natively

---

.jestSetup.js
packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
packages/gatsby/src/utils/parcel/__tests__/fixtures/error-in-code-ts/gatsby-node.ts
packages/gatsby/src/utils/parcel/compile-gatsby-files.ts

Seems like ARM macs parcel (at least version we use) cause quite a bit of problems and results in often seg faults - this tries to run parcel in child process so we can try to handle segfaults by clearing just parcel cache and retrying (few times)
Possibly fixes https://github.com/gatsbyjs/gatsby/issues/38483

fix(gatsby): try to automatically recover when parcel segfaults

---

packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
packages/gatsby/src/utils/adapter/__tests__/manager.ts
packages/gatsby/src/utils/adapter/manager.ts

before on left, with the change in the pr on right for sample reproduction with 10000 dummy pages (this is zoomed in on execution of just this line https://github.com/gatsbyjs/gatsby/blob/94b24825c8811ca968fadade3a0529406bc5390d/packages/gatsby-adapter-netlify/src/route-handler.ts#L262-L263 ):
Note that in above cpu profile biggest drain is actually way content of `_headers` file is produced and not necessarily amount of them (tho they both combined cause the problem). String concatenations for each route ( https://github.com/gatsbyjs/gatsby/blob/94b24825c8811ca968fadade3a0529406bc5390d/packages/gatsby-adapter-netlify/src/route-handler.ts#L242 ) and then headers concatenation in https://github.com/gatsbyjs/gatsby/blob/94b24825c8811ca968fadade3a0529406bc5390d/packages/gatsby-adapter-netlify …

perf: use must-revalidate cache-control header as common and only create header routes for routes with different cache-control

---

e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
e2e-tests/adapters/src/pages/routes/ssr/remote-file.jsx
packages/gatsby-adapter-netlify/src/file-cdn-url-generator.ts
packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
packages/gatsby/src/schema/graphql-engine/entry.ts
packages/gatsby/src/utils/page-ssr-module/lambda.ts

This PR fixes issues when `fs.createWriteStream` (and few others) are being used in functions/lambdas that are mounted in read-only locations
Example error could look like this:
```
Jan 24, 11:05:05 AM: error [gatsby-source-contentful] Could not getDominantColor from image TypeError: Cannot read properties of undefined (reading 'apply')
Jan 24, 11:05:05 AM: at new WriteStream (/var/task/.cache/query-engine/index.js:6355:29)
Jan 24, 11:05:05 AM: at Object.createWriteStream (/var/task/.cache/query-engine/index.js:6378:12)
Jan 24, 11:05:05 AM: at /var/task/.cache/query-engine/index.js:16689:75
Jan 24, 11:05:05 AM: at new Promise (<anonymous>)
Jan 24, 11:05:05 AM: at requestRemoteNode (/var/task/.cache/query-engine/index.js:16687:10)
Jan 24, 11:05:05 AM: at fetchFile …
```

fix: add missing fs method rewrites to handle fetchRemoteFile in dsg/ssr engine

---

.circleci/config.yml
packages/gatsby-source-wordpress/src/steps/create-schema-customization/helpers.js

Schema diffing was added by default to help catch issues with how the local WP schema is generated. In 99% of cases this is not helpful, so it was a mistake to make this the default behaviour.
This is only useful as a diagnostic tool when investigating a bug

fix(gatsby-source-wordpress): only diff wpgraphql schema if the user opts in

---

packages/gatsby/src/utils/stack-trace-utils.ts

With esm source plugins, the stack trace util can't find the right path to read:
Sample trace of the problem where the real error is obscured
```
Error: ENOENT: no such file or directory, open 'file:///usr/src/app/www/node_modules/example-source-plugin/index.js'
at Object.openSync (node:fs:600:3)
at Object.readFileSync (node:fs:468:35)
at getNonGatsbyCodeFrame (/usr/src/app/www/node_modules/gatsby/src/utils/stack-trace-utils.ts:74:19)
at createNode (/usr/src/app/www/node_modules/gatsby/src/redux/actions/public.js:736:33)
at /usr/src/app/www/node_modules/gatsby/src/redux/actions/public.js:835:21
at /usr/src/app/www/node_modules/redux-thunk/lib/index.js:23:18
at boundActionCreator (/usr/src/app/www/node_modules/redux/lib/redux.js:586:12)
at Object.doubleBoundActionCreators.<computed> [as …
```

fix(gatsby): resolve url file paths before reading

---

.circleci/config.yml
packages/gatsby-source-contentful/src/__tests__/__snapshots__/create-schema-customization.js.snap
packages/gatsby-source-contentful/src/create-schema-customization.ts
packages/gatsby-source-contentful/src/gatsby-node.ts
packages/gatsby-source-contentful/src/normalize.ts
packages/gatsby-source-contentful/src/report.ts
packages/gatsby-source-contentful/src/rich-text.ts
packages/gatsby/index.d.ts
packages/gatsby/scripts/__tests__/api.js
packages/gatsby/scripts/output-api-file.js
packages/gatsby/src/joi-schemas/joi.ts
packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/types/node-interface.ts

While [upgrading gatsby-source-contentful to its new version](#30855), we figured out that Gatsby is parsing JSON and Rich Text fields for references, while the plugin does handle these on its own.
In discussion with @pieh, we decided to implement a flag into Gatsby, which prevents nodes from being parsed for trackable inline objects. This is a huge performance improvement for the new gatsby-source-contentful version, while potentially providing a performance improvement to all other plugins that implement external data and/or handle references on their own.
Nodes will get an additional, optional internal boolean property: `node.internal.dontTrackInlineObjects`.
By default, none of Gatsbys behavior will change. Plugin developers and users implementing their own node types have to opt into …

perf(gatsby): add a way to skip tracking inline objects

---

packages/gatsby/package.json
yarn.lock

https://github.com/vercel/webpack-asset-relocator-loader/releases/tag/v1.7.4 that was released yesterday cause troubles and fails builds with engines now with error like:
```
ReferenceError: __nccwpck_require__ is not defined
- index.js:7160 module.exports
/tmp/tmp.uHDtGPCssB/integration-tests/lmdb-regeneration/.cache/query-engine/    index.js:7160:26
- index.js:267372 __webpack_require__
/tmp/tmp.uHDtGPCssB/integration-tests/lmdb-regeneration/.cache/query-engine/    index.js:267372:42
- index.js:246 Object.<anonymous>
/tmp/tmp.uHDtGPCssB/integration-tests/lmdb-regeneration/.cache/query-engine/    index.js:246:19
- index.js:267372 __webpack_require__
/tmp/tmp.uHDtGPCssB/integration-tests/lmdb-regeneration/.cache/query-engine/    index.js:267372:42
- index.js:115 …
```

chore: pin @vercel/webpack-asset-relocator-loader

---

.circleci/config.yml
e2e-tests/adapters/cypress/e2e/headers.cy.ts
e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
e2e-tests/adapters/cypress/e2e/trailing-slash.cy.ts
e2e-tests/adapters/gatsby-config.ts
e2e-tests/adapters/gatsby-node.ts
e2e-tests/adapters/src/pages/index.jsx
e2e-tests/adapters/src/pages/routes/ssg/remote-file.jsx
e2e-tests/adapters/src/pages/routes/ssg/static.jsx
packages/gatsby-adapter-netlify/src/route-handler.ts
packages/gatsby/src/utils/adapter/create-headers.ts
packages/gatsby/src/utils/adapter/manager.ts
packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
packages/gatsby/src/utils/page-ssr-module/entry.ts

Adapter was regenerating `_headers` content for each static route in routes manifest which was resulting in really poor performance with large sites, this fixes it to generate `_headers` content only once.
Some measurements of impact on `adapt()` perf (I temporarily added timer for that - it is not part of this PR) on test site
before:
```
success [gatsby-adapter-netlify] adapt() - 92.711s
```
after:
```
success [gatsby-adapter-netlify] adapt() - 0.050s
```
The changes can be tested using canary releases:
```
gatsby@headers-perf
gatsby-adapter-netlify@headers-perf
```
Adapter tests and in particular header tests continue to pass. Added some adjustments to fixture (and some test updates), but they are not changing what was asserted before - just adding to them with additional case of …

perf(gatsby-adapter-netlify): improve adapt() performance

---

docs/docs/reference/release-notes/gatsby-version-support.md

Removes end date for v5 support as we currently have no intention to drop support for this version.

chore(docs): update v5 support date

---

packages/gatsby/src/schema/node-model.js

rename getNodeByIds to getNodesByIds in documentation

Fix getNodesByIds typo

---

docs/docs/how-to/local-development/starters.md
docs/docs/tutorial/getting-started/part-0/index.mdx

1. Update the Node.js version requirements. 👉 [nodejs v21.x: the punycode module is deprecated](https://nodejs.org/docs/latest-v21.x/api/deprecations.html#DEP0040)
2. Add a terminal command.

Docs update.

---

packages/gatsby-adapter-netlify/README.md

Adding missing `.default` to documentation
Fixes #38606

Fixing missing .default #38606

---

docs/docs/reference/config-files/gatsby-node.md

The link is confusing because it is to the current page. This causes an issue when reading because it seems like you have to follow the link to learn more on the intro.
Just removing a link
N/A
N/A

Remove link to self

---

.github/actions/gatsby-site-showcase-validator/package.json
integration-tests/ssr/package.json
packages/gatsby-plugin-offline/package.json
packages/gatsby-remark-copy-linked-files/package.json
packages/gatsby-remark-graphviz/package.json
packages/gatsby-remark-images-contentful/package.json
packages/gatsby-remark-images/package.json
packages/gatsby-remark-prismjs/package.json
packages/gatsby-remark-responsive-iframe/package.json
packages/gatsby-source-wordpress/package.json
yarn.lock

`cheerio` recently was released as stable with set of breaking changes that previous RC version didn't have. One of the main ones is related to this https://github.com/cheeriojs/cheerio/issues/3986#issuecomment-2278902668 in https://github.com/gatsbyjs/gatsby/blob/33f18ba7a98780a887d33e72936da57a6c58932a/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js#L8 which currently released wordpress plugin cause problems for users that are installing plugin manually now or tried to regenerate lock file / updated packages.
Because stable version requires `node@>=18.17`, it's not something that can be merged without the need to bump major for lot of packages, so instead of migrating wordpress plugin import, we are pinning to last available version before required …

fix: pin cheerio

---

README.md

I went to look up your contribution docs while reading this repo live on a stream. The link for the contributing guide went to a nonexistent page (`https://www.gatsbyjs.com/contributing/how-to-contribute/`) on the gatsby official website. This PR adjusts that link direct to `the https://www.gatsbyjs.com/contributing/` instead. 
fixes [#39134](https://github.com/gatsbyjs/gatsby/issues/39134)
no documentation necessary
No tests necessary
No Related issues

updating a readme dead link

---

packages/gatsby-source-shopify/__tests__/fixtures/index.ts
packages/gatsby-source-shopify/src/update-cache.ts
packages/gatsby-source-shopify/types/interface.d.ts

Handling of incremental data update in shopify has quite bad memory characteristics:
- we are loading all of the shopify nodes into memory and strongly retain them for the duration of `updateCache` function
- we are creating countless temporary objects that are being GCed soon after while loading all the nodes to memory
This avoid loading all of the nodes and holding them strongly in memory. Instead it does handle it in batches (per node type) and allow event loop turn in between batches.
When testing with 30k shopify products here's how memory usage looks like comparatively:
On the left is `latest` (with just some extra logs/activities, but no functional changes otherwise), on the right it's with changes in this PR - notice the time difference - 152s vs 9s for build and notice how on the …

perf: don't load all shopify nodes into memory at once and avoid creating many temp objects

---

README.md

Gatsby Cloud was shut down last month. Replace references in the README with Netlify.
N/A
N/A
https://github.com/gatsbyjs/gatsby/issues/38738, https://github.com/gatsbyjs/gatsby/pull/38712

docs(readme): replace refs to Gatsby Cloud

---

packages/gatsby-link/index.d.ts

The usage of the original navigation function type created problems when using spreaded parameters. Since the navigate implementation in gatsby does not have the same call signature as @reach/router anyways (the promise returned by @reach/router is ignored), it is easier to define our own interface than to overwrite the types from @reach/router.
Fixes #39158

Fix type of navigate method

---

e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs

Deploy previews aren't currently subject to the same retention policy as regular deploys, as such we end up keeping our test runs around for longer than we intend. Switching to branch deploys (i.e. giving all test runs the next-e2e-tests alias) allows them to be picked up by the daily soft deletion worker.

test: use branch/alias deploys for e2e test suite

---

.circleci/config.yml

pnpm@10 has a lot of breaking changes: https://github.com/pnpm/pnpm/releases/tag/v10.0.0
This is (maybe?) causing our pnpm integration tests to fail: https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/94731/workflows/6d8d91ae-462a-490a-9cc8-82c7d0be2dcd/jobs/1167083
N/A
N/A
N/A

ci: pin pnpm used in pnpm integration tests to v9

---

packages/gatsby-source-shopify/__tests__/__snapshots__/create-operations.ts.snap
packages/gatsby-source-shopify/__tests__/__snapshots__/create-schema-customization.ts.snap
packages/gatsby-source-shopify/src/plugin-options-schema.ts
packages/gatsby-source-shopify/src/query-builders/locations-query.ts
packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
packages/gatsby-source-shopify/src/type-builders/location-type.ts
packages/gatsby-source-shopify/src/type-builders/product-variant-type.ts

This upgrades the default Shopify API version in `gatsby-source-shopify` from 2024-04 to 2025-01.
Due to fields being moved/removed in the Shopify API, this upgrade **includes breaking changes**.
- `ProductVariant.requiresShipping` has been removed but is still available at `InventoryItem.requiresShipping`
- `InventoryItem.productBased` and `InventoryItem.shippingMethods` have been removed
- `Locations.fulfillmentService.shippingMethods` has been removed
- `ShopifyProductVariant.weight` and `ShopifyProductVariant.weightUnit` now require `locations` to be set in your `shopifyConnections` via the plugin options.
We have also deprecated a number of fields. Please update your system to use the recommended alternative to avoid breaking changes in future version changes.
- …

feat!(gatsby-source-shopify): upgrade from Shopify API version 2024-04 to 2025-01

---

packages/gatsby-graphiql-explorer/package.json
packages/gatsby-plugin-mdx/package.json
packages/gatsby/package.json
packages/gatsby/src/utils/webpack/get-ssr-chunk-hashes.ts
yarn.lock

Seems like most recent webpack release (`5.99.0`) is causing errors in produced query-engine:
```
ReferenceError: isNonNullType is not defined
- index.js:89893 detectCycleRecursive
/tmp/tmp.4RDvdYSxaA/e2e-tests/production-runtime/.cache/query-engine/index.j    s:89893:7
- index.js:89550 validateTypes
/tmp/tmp.4RDvdYSxaA/e2e-tests/production-runtime/.cache/query-engine/index.j    s:89550:7
- index.js:89327 validateSchema
/tmp/tmp.4RDvdYSxaA/e2e-tests/production-runtime/.cache/query-engine/index.j    s:89327:3
- index.js:89340 assertValidSchema
/tmp/tmp.4RDvdYSxaA/e2e-tests/production-runtime/.cache/query-engine/index.j    s:89340:18
- index.js:94638 validate
/tmp/tmp.4RDvdYSxaA/e2e-tests/production-runtime/.cache/query-engine/index.j    s:94638:72
- index.js:264992 GraphQLRunner.validate …
```

fix: pin webpack

---

e2e-tests/adapters/cypress/e2e/headers.cy.ts
packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
yarn.lock

Less disruptive alternative to https://github.com/gatsbyjs/gatsby/pull/39297 that ensures that globally installed libvips in build environment does not impact produced functions (and allow them to be always self-contained)

fix: ensure rendering engine has vendored libvips

---

docs/docs/how-to/styling/tailwind-css.md

This PR updated the Tailwind documentation to include new sections for Tailwind v3 and Tailwind v4. Tailwind v3 docs are largely the same, with the exception of updating the url to be a valid tailwind url. The v4 documentation links to the installation and upgrade guide for v4 since there's no official docs for Gatsby on the v4 documentation page for Tailwind.
Docs located at: `docs/docs/how-to/styling/tailwind-css.md`
Documentation change, no tests run
Fixes #39312

chore(docs): update documentation for tailwind css
