docs/sites.yml

It would be great to be listed here. Thank you!

Add React Native Explorer to sites.yml

---

docs/docs/gatsby-starters.md

Adding new starter to docs as suggested in https://github.com/gatsbyjs/gatsby/issues/7669

New starter based on HTML5 UP template 'Directive'

---

docs/sites.yml

We use Gatsby for our main website and build some projects with it for our clients

Add 500Tech

---

translations/es/CONTRIBUTING_ES.md

docs: fix image path in CONTRIBUTING_ES.md

---

docs/docs/page-query.md

Update link to 'browsing GraphiQL'

---

docs/sites.yml

update categories and source_url for Ocean artUp showcase submission

---

www/src/templates/template-starter-showcase.js

update external dependencies on detail page - starter showcase #6716

---

docs/sites.yml

Adding blog to showcase -> for master

Adding Blog

---

packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.js.snap
packages/gatsby/src/utils/babel-loader-helpers.js

Remove deprecated babel option

---

www/src/views/starter-showcase/filtered-showcase.js

Starter showcase: All filters visible

---

docs/docs/building-apps-with-gatsby.md

There are two paragraphs explaining the same behavior but the second one seems to be more descriptive.

Remove duplicate paragraph

---

docs/tutorial/part-one/index.md

Very minor text change (leftover from v1) to avoid confusion

Update folder name text

---

docs/docs/how-gatsby-works-with-github-pages.md

- Fixed grammar and added notes for clarity

Updated content and added link to gh-pages

---

docs/docs/gatsby-link.md

Updating docs to make it clear how to pass state with the `Link` Component

Gatsby Link improvement re: passing state state

---

.travis.yml

Add names for Travis test stages

---

packages/gatsby-plugin-layout/README.md

[v2] fix: docs typo gatsby-plugin-layout
fix: issue #7789

[v2] fix: issue #7789

---

docs/sites.yml

Propose Node.js HBase to showcase sites

---

docs/sites.yml

Add https://www.peterkroyer.at/en/ to sites.yml

---

www/src/data/StarterShowcase/startersData/gatsby-starter-solid-state.md

add entry for gatsby-starter-solid-state :)

---

packages/gatsby-source-npm-package-search/README.md

docs(gatsby-source-npm-package-search): wrap plugin config with brackets

---

docs/sites.yml

Propose Node.js HBase to sites showcase

---

docs/blog/2017-10-17-building-i18n-with-gatsby/index.md
docs/docs/plugin-authoring.md
docs/docs/testing-components-with-graphql.md
examples/hn/src/components/layout.js
examples/using-hjson/src/pages/index.js
examples/using-multiple-providers/src/pages/index.js
integration-tests/production-runtime/README.md
packages/gatsby-plugin-layout/README.md
packages/gatsby-transformer-excel/README.md
packages/gatsby-transformer-excel/src/gatsby-node.js
www/src/templates/template-starter-showcase.js

Looks like a bunch of files are not formatted on `master`. All these changes are done by running `yarn format`.
We should probably look at enforcing formatting on every commit or something like that!

Formatting

---

www/src/components/layout.js
www/src/components/navigation.js
www/src/pages/index.js
www/src/templates/template-blog-post.js
www/src/templates/template-contributor-page.js
www/src/templates/template-starter-showcase.js

remove outbound link

---

docs/docs/gatsby-starters.md

Re-adding my starter to gatsby-starters.md, due to #7829

add gatsby-starter-solid-state to gatsby-starters.md

---

packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/static-entry.js

Fix pathPrefix causing erroneous redirects

---

packages/gatsby-transformer-csv/README.md

This PR cleans up formatting in the gatsby-transformer-csv README.

docs(transformer-csv): clean up readme

---

packages/gatsby-transformer-javascript-frontmatter/README.md

This PR cleans up formatting in the gatsby-transformer-javascript-frontmatter README.

docs(transformer-javascript-frontmatter): clean up readme

---

packages/gatsby-transformer-json/README.md

This PR cleans up some typos and formatting in the gatsby-transformer-json README.

docs(transformer-json): clean up readme

---

packages/gatsby-transformer-xml/README.md

This PR cleans up some typos and code formatting in the gatsby-transformer-xml README.

docs(transformer-xml): clean up readme

---

packages/gatsby-transformer-yaml/README.md

This PR cleans up some typos and formatting in the gatsby-transformer-yaml README.

docs(transformer-yaml): fix typos in readme

---

packages/gatsby-transformer-toml/README.md

This PR fixes a minor typo in the gatsby-transformer-toml README.

docs(transformer-toml): fix readme typo

---

packages/gatsby-codemods/src/transforms/navigate-calls.js

Specify line terminator for Appveyor

Fix Appveyor codemod test

---

packages/gatsby-plugin-google-analytics/README.md
packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js

Add support for Create Only Fields in Google Analytics plugin

---

packages/gatsby-plugin-layout/src/gatsby-node.js
packages/gatsby-plugin-layout/src/wrap-page.js

Fixes https://github.com/gatsbyjs/gatsby/pull/7459#issuecomment-415058379

[gatsby-plugin-layout] check if layout component module is resolved in ssr/webpack

---

packages/gatsby/cache-dir/loader.js

[v2] [cache-dir] Fix prefetch undefined 404s

---

www/src/fonts/Webfonts/futurapt_book_macroman/stylesheet.css
www/src/fonts/Webfonts/futurapt_bookitalic_macroman/stylesheet.css
www/src/fonts/Webfonts/futurapt_demi_macroman/stylesheet.css
www/src/fonts/Webfonts/futurapt_demiitalic_macroman/stylesheet.css

Stop including css for svg/eot as they were causing subfont trouble (also not needed)

---

docs/docs/gatsby-starters.md

gatsby-starter-bootstrap demo link updated

---

www/src/templates/template-creator-details.js

pass location to creator template from props

---

docs/sites.yml

I want to add my blog to the showcase site

[docs] Add Mokkapps website to showcase sites

---

www/src/data/sidebars/doc-links.yaml

The recipes page is not a stub anymore

---

docs/docs/site-showcase-submissions.md

We could also introduce community voting as part of featured sites at some point! Like maybe reserve two featured spots for community choice awards? @KyleAMathews

Featured sites criteria edit

---

packages/gatsby-plugin-offline/src/gatsby-node.js

and make sure to use it  through `modifyUrlPrefix`

[v2][gatsby-plugin-offline] Fix offline handling with path-prefixed websites

---

docs/sites.yml

👋 We are a brand new React / React Native based agency! Here is our [new website](https://www.premieroctet.com/) for the showcase!
Thanks for Gatsby ❤️

[docs] Add Premier Octet website to showcase

---

docs/docs/gatsby-on-windows.md

Added instructions for Visual Studio 2017

---

www/src/components/masthead.js
www/src/components/slider.js

Add new header to v1 website

---

www/package.json

See https://github.com/escaladesports/react-hubspot-form/pull/14 for updates

Use deferred-loading Hubspot JS on v1 site

---

scripts/publish-site.sh

Removes errors about missing files

Update netlify build script

---

docs/docs/styled-components.md

Similar to #7249. Not sure about exact position of the video in the text.

[docs] Add styled-components Egghead lesson

---

packages/gatsby-source-mongodb/src/gatsby-node.js

This is basically an addition to the PR #7225 created by @michalczaplinski, specific to the version 1 of Gatsby.
Only the destination branch is different.
I consider this a fix that should really be present in both versions.
I hope you can accept this PR in order to have an updated version of `gatsby-source-mongodb` published.
(cherry picked from commit a1588d5c363af080de6723da5b04b6b2e5d36239)

[v1] Fix race condition in gatsby-source-mongodb (#7225)

---

packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js

Quick Netlify CMS plugin update to redirect Netlify Identity logins to the right path.

fix netlify cms admin path redirect

---

packages/gatsby-plugin-react-css-modules/src/gatsby-node.js

Passed down plugin options for gatsby-plugin-react-css-modules.

---

docs/docs/awesome-gatsby.md

Adding a link to the Gatsby community on Hashnode

---

packages/cypress-gatsby/package.json

based on comments from @KyleAMathews, @DSchau and https://github.com/lerna/lerna/issues/953 :)

make cypress-gatsby package private for now, so we dont publish it

---

docs/docs/submit-to-creator-showcase.md
www/src/data/sidebars/doc-links.yaml

@berraknil here it is.
What fields would someone fill in if they want to show their site showcase submissions as part of their "portfolio"?

Creator Showcase submission instructions

---

packages/gatsby-plugin-sitemap/README.md

Don't need to resolve plugin in `gastby-config` with default configuration.

[plugin-sitemap] update README

---

.travis.yml
examples/gatsbygram/cypress/plugins/index.js
examples/gatsbygram/package.json
scripts/integration-test.sh

Starting on the process of getting e2e tests running vs. local changes of Gatsby instead of the installed versions.
(I think there will be some refinement here, but wanted to get some 👀 on it)

test: use local changes to gatsby packages/plugins in e2e test

---

docs/docs/gatsby-starters.md

Add the starter I created to the list of starter to spread the word and give back what I learned to the community!

Add gatsby-starter-mate

---

docs/sites.yml

Thoriumsim.com is built with Gatsby v2 as a marketing, documentation, and blog site for my spaceship simulator software. It hosts the docs, blog, and various pages for service requests, donations, and announcements. It even uses Gatsby to transform markdown documents into a JSON API!
Gatsby is really slick, and provides all of the primitives I need to make complicated sites while keeping it all simple and approachable. Thanks guys! 👍

Add Thoriumsim.com to the site showcase.

---

packages/gatsby/src/schema/infer-graphql-type.js

Fix crash in schema generation

---

packages/gatsby/package.json

fix npm packaging

---

docs/sites.yml

Hi there!
Recently re-worked my personal site to be powered by Gatsby <3
Would love to add it to the showcase!

Add personal site to showcase

---

docs/docs/migrating-from-v1-to-v2.md

fix ToC links in migration guide

---

packages/gatsby-remark-autolink-headers/src/gatsby-browser.js

fix autolink-headers for in page hash navigation

---

docs/sites.yml

Add Nike Just Do It & Hopper to site showcase

---

docs/blog/2018-09-14-gatsby-v2.md

Thank you for the awesome work, congrats 🎉

correct my English name

---

docs/sites.yml

Adding some details around Hopper
Thanks for adding it 👍 
Many amazing website to come.

Updating Hopper and adding Narative built_by

---

docs/docs/creating-global-styles.md

* page/ -> pages/
* src/pags/index.js -> src/pages/index.js

Fix typos on "Creating Global Styles" page

---

docs/docs/sourcing-from-netlify-cms.md

Fix grammar typo

---

docs/sites.yml

Adds my profile website which is written in gatsby. Please let me know if you have any questions.
Thank you.

adds joseph chambers website

---

packages/gatsby/cache-dir/json-store.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/public-page-renderer-prod.js

fixes https://github.com/gatsbyjs/gatsby/issues/8181

add key to PageRenderer

---

integration-tests/gatsby-image/src/pages/index.js

fix linting

---

README.md

Update README for v2 release

---

www/static/robots.txt

remove robots.txt

---

www/gatsby-ssr.js

This is listed under 'opportunites' in Lighthouse audits

[www] Add dns-prefetch for external domains

---

packages/gatsby/README.md

Update gatsby README

---

docs/docs/site-showcase-submissions.md

Fixing grammar

---

docs/sites.yml

Added momnotebook.com to showcase

---

docs/sites.yml

Add https://impossiblefoods.com/ to showcase

---

docs/sites.yml

Add Aurora EOS to Showcase

---

docs/sites.yml

Adding howtobookcheapflights.com to the showcase.

Adding howtobookcheapflights.com to sites.yml

---

packages/gatsby-source-graphql/README.md

👋  hey folks, this is a very cool feature.
I've fixed the your README's md. 
@freiksenet it recommended you as my reviewer, while I'm adding you, did you know that I've got stitching working on our Artsy staging API now? I'm getting there 👍 my blog post is gonna even be more epic'er now that I've got more tools for stitching verification.

Update README.md for gatsby-source-graphql

---

docs/sites.yml

Add an update to featuring our showcase

Showcase update featuring MadeComfy

---

packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
packages/gatsby-transformer-remark/src/__tests__/extend-node.js

Fixes: #8074
Also related to this PR https://github.com/gatsbyjs/gatsby/pull/7759

[gatsby-transformer-remark] Properly run assertion on extend-node test

---

www/src/components/sidebar/scroll-sync-sidebar.js

Make the `_getItemIds` method, in the `scroll-sync-sidebar` component, recursive.
It was in the *todo* comments, so I thought I should go ahead and do it.
And also because: *"To iterate is human, to recurse, divine."*

[www] Improvements to scroll-sync-sidebar

---

packages/gatsby/cache-dir/loader.js

fix #8285  - findPage - custom matchPath for page - page already in scope

fix #8285 - findPage - custom matchPath for page - page already in scope

---

packages/gatsby-transformer-screenshot/src/gatsby-node.js

Fail quietly on screenshot node errors

---

www/src/templates/template-creator-details.js
www/src/views/community/community-header.js
www/src/views/community/index.js

Tested in different layouts as best as I could, please let me know if you see anything wrong/missing, also any other feedback :)

Responsive Design/Mobile Layout for Creators Showcase

---

docs/docs/v2-release-notes.md

Draft of v2 release notes to match v1 release notes

---

docs/docs/gatsby-cli.md

Updated doc with details from other source

---

www/src/data/sidebars/doc-links.yaml

deleted docs we decided we don't need anymore

---

docs/sites.yml

Update Mokkapps showcase entry

---

integration-tests/production-runtime/cypress/integration/plugins/index.js
integration-tests/production-runtime/cypress/integration/production.js
integration-tests/production-runtime/src/pages/404.js
integration-tests/production-runtime/src/pages/index.js

Add tests for non existent page routes, check 404 exists

---

docs/sites.yml

Added built-by and description for updated site. Are updated screenshots generated automatically?

Update site showcase listing for iammatthias.com

---

docs/tutorial/part-zero/index.md
www/src/pages/docs/index.js

Docs: added node and Git prerequesties #8210

Added prerequesties

---

docs/sites.yml

Added loige.co to sites

---

docs/docs/gatsby-starters.md

- add three new starters
- add links to docs and demos for all starters

Update info about Gatsby Starter Kit on the starters listing

---

www/package.json
www/src/components/plugin-searchbar-body.js

Remove markdown syntax from plugin page search results.

---

docs/sites.yml

Added Wire website to be featured

---

docs/docs/audit-with-lighthouse.md

Fixes the missing images cc @shannonbux

www: fix images on audit with lighthouse doc

---

docs/sites.yml

Adds https://hawaiinational.bank to sites.yml

---

packages/gatsby-image/README.md

The current post referenced is for Gatsby Image V1. I've updated my post to V2 and added the blog link to the readme.

Adding blog post link to readme

---

docs/blog/2018-09-17-lullabot-podcast.md

new-blogpost-lullabot

---

docs/sites.yml

add missing url field to sites.yml

---

www/src/components/showcase-details.js

replaces instances of `next.gatsbyjs.org`

[www] replace next. with www.

---

www/src/components/masthead.js

update main header

---

docs/docs/graphql-reference.md

Add skip parameter to graphql-reference

docs(graphql-reference): add skip parameter

---

docs/docs/reach-router-and-gatsby.md
docs/docs/routing.md
www/src/data/sidebars/doc-links.yaml

Requesting feedback on: 
- position of this section
- docs within it
- names of the docs within it

Routing section

---

examples/using-page-transitions/README.md

So I can mention it at https://spectrum.chat/thread/3059e2da-f509-437a-a15a-6323d4469d38

Add a link to a live version of this example

---

docs/docs/gatsby-starters.md

added gatsby-starter-craft to gatsby starters page

---

www/src/templates/template-docs-markdown.js

[www] don't crash builds when there are no guides

---

docs/docs/migrating-from-v1-to-v2.md

Add link to TOC, and clarify.
Edit: Fixes #8469

[docs] Update migration guide TOC

---

docs/sites.yml

uses Gatsby v2, styled-components and css grid heavily

add personal blog and portfolio site

---

docs/docs/gatsby-starters.md

The PR only adds another starter project which can be used to make [MDX](https://mdxjs.com/) working in Gatsby. I didn't find any running example for it, so I thought it may be valuable to share this minimal project. People can either use it or just see how it works and do their own version of it.

Yet another starter Gatsby Starter Project:  Gatsby with MDX

---

docs/docs/recipes.md
docs/docs/using-unstructured-data.md
docs/tutorial/part-four/index.md
www/src/data/sidebars/doc-links.yaml
www/src/data/sidebars/tutorial-links.yaml

Unstructured data first drafts

---

CODEOWNERS

This protects some critical areas of the codebase by requiring an approving review by a member of teams that are especially familiar with specific parts of the code.

chore: add code owners for www and critical plugins

---

docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
docs/blog/2018-06-07-build-a-gatsby-blog-using-the-cosmic-js-source-plugin/index.md
docs/blog/2018-08-24-gatsby-aws-hosting/index.md
docs/blog/2018-1-18-strapi-and-gatsby/index.md
docs/docs/ecommerce-tutorial/index.md
docs/docs/gatsby-starters.md
docs/docs/image-tutorial.md
docs/docs/netlify-cms.md
docs/docs/source-plugin-tutorial.md
docs/docs/styled-components.md
docs/docs/wordpress-source-plugin-tutorial.md
docs/tutorial/part-four/index.md
docs/tutorial/part-one/index.md
docs/tutorial/part-three/index.md
docs/tutorial/part-two/index.md
www/src/pages/docs/index.js

docs(v1): update gatsby new with pinned v1 version

---

docs/docs/rfc-process.md

Almost identical to READme in RFC repo

Rfc process doc

---

packages/gatsby-source-graphql/README.md

This PR is just a spelling fix. I'm looking forward to trying the actual feature with the GitHub API!

Typo fix in gatsby-source-graphql/README.md

---

packages/gatsby/src/commands/develop.js
packages/gatsby/src/commands/serve.js

[cli] Fix unhandled rejection when no browser found

---

docs/blog/2018-09-17-gatsby-v2.md
docs/blog/2018-09-24-reach-router/index.md

Add blog post on v2 routing

---

docs/docs/building-a-blog.md
docs/docs/building-a-portfolio.md
docs/docs/building-a-site-with-asynchronous-data.md
docs/docs/building-a-site-with-authentication.md
docs/docs/building-an-e-commerce-site.md
docs/docs/building-an-image-heavy-site.md
docs/docs/client-data-fetching.md
docs/docs/gatsby-project-structure.md
docs/docs/recipes.md
www/src/data/sidebars/doc-links.yaml

Updates to sidebar

---

CODEOWNERS

chore: add code owners for ecosystem related yaml

updated CODEOWNERS

---

www/gatsby-node.js

@fk want to check if I did this right?

Added redirect

---

docs/docs/gatsby-starters.md

Add gatsby-mdx-starter to the list of starters

---

examples/gatsbygram/README.md

Think it should read 2.0 or is there any reason…?

docs: Upgrade Gatsby Version in Gatsbygram Readme

---

www/package.json

chore(www): bump gatsby version

---

www/src/templates/template-starter-showcase.js

[www] fix builds, missed var name

---

packages/gatsby-image/src/index.js

Closes #7585, closes #7587, and closes #7606

Fix: added key prop to tag and allowed custom key for tags

---

docs/docs/introducing-graphiql.md
www/src/data/sidebars/doc-links.yaml

* Fix „Introducing GraphiQL“ video
* Don’t mark „Introducing GraphiQL“ as stub
* Fix „Introducing GraphiQL“ image
Ref. #8599
/cc @shannonbux

[www][docs] Fix "Introducing GraphiQL" things

---

www/gatsby-node.js
www/src/pages/starters.js
www/src/views/shared/collapsible.js
www/src/views/starter-library/filtered-starters.js
www/src/views/starter-library/index.js
www/src/views/starter-library/starter-list.js

closes #7785.
- adds version filtering
- adds indication of major version for each starter on library thumbnail

[www/starters] add gatsby version filtering to starter library

---

docs/community/creators.yml

Recent creator addition had incomplete pathname for image.

fix(www/creators): fix image path

---

docs/sites.yml

Add oasome.blog in showcase sites

---

docs/sites.yml

This is our first gatsby site - more will follow. We'd love to be included in the showcase that's for sure.

Include ezagrar.at in showcase

---

docs/tutorial/part-one/index.md

Minor: Changed singular verb after plural noun

---

.circleci/config.yml

See: https://circleci.com/docs/2.0/reusing-config
Not 100% sure this PR will succeed 🙃

ci: attempt to reuse config for Circle

---

docs/starters.yml

Update starters.yml - Gatsby Starter Blog Grommet

---

docs/starters.yml

- Capitalize all tags
- Remove 'date' field
- Change `Styling:HTML5UP` to `HTML5UP`
- Update my own starters' entries

Update starters.yaml (own entries + general updates)

---

www/gatsby-node.js

Fixes DX issue for `www` @jlengstorf

[www/starters] add default field for starter gatsby major version

---

docs/docs/gatsby-link.md

Just a small typo I found on the `gatsby-link` page, nothing special, but I'm glad to help!

Fix typo in gatsby-link doc

---

docs/docs/gatsby-style-guide.md

Fix a broken link and fix a typo

---

docs/docs/babel.md

added `the` to ease reading and understanding

added 'the' to Babel doc

---

docs/sites.yml

Hello! I was going about adding my site to the bottom of `site.yml`, and I unfortunately discovered that the most recent addition (https://www.kelvinkamau.app/) to the showcase had blatantly plagiarized my code without giving my proper attribution. I do have my repo for the site open source (for now) at https://github.com/bchiang7/v4.
Here is his website: https://www.kelvinkamau.app/
Here is my website: https://brittanychiang.com/
I was wondering if there was anyone who has the power to moderate the showcase, since I know it's not my jurisdiction to remove anyone's submission. However, seeing as they essentially plagiarized my code and submitted it to the showcase under their name, I was wondering if there could be an exception to remove their submission. If not, I understand, and I can …

Add Brittany Chiang to showcase

---

docs/blog/2018-09-27-sendgrid-knowledge-center-cuts-page-load-times-in-half-with-gatsby/index.md

Closes ichabod-cranes/mansion#1239

Sendgrid case study blogpost

---

docs/starters.yml

TypeScript and Contentful starter

TypeScript and Contentful starter

---

packages/gatsby-link/src/index.js

navigateTo deprecation points to other deprecated method

---

plopfile.js

Fix wording in plopfile

---

docs/docs/deploying-to-aerobatic.md

Add Deploying to Aerobatic section

---

docs/tutorial/part-one/index.md
docs/tutorial/part-zero/index.md

A few enhancements/fixes to part 0 of the Gatsby tutorial series.

Proofreading: Part 0

---

docs/docs/gatsby-style-guide.md

Follow up of https://github.com/gatsbyjs/gatsby/pull/8758

Code titles info to style guide

---

docs/docs/deploying-to-heroku.md
docs/docs/sourcing-from-drupal.md

fixes #8740 
Added the content here and formatted it too with links pointing out to the right locations.
@KyleAMathews please review! Thanks

add sourcing-from-drupal.md

---

www/src/data/sidebars/doc-links.yaml

#7166 - going to close this issue

---

docs/docs/babel.md

added title to sample dotfile for custom babel.js configuration

added title to sample babelrc

---

docs/docs/submit-to-creator-showcase.md

Added words to understand easily

---

examples/simple-auth/src/components/Login.js
examples/simple-auth/src/components/PrivateRoute.js

Switch from `navigate` to `redirectTo`, fixes #8783.
Not 100% sure _why_ the old code didn't work, but this does fix it.

Routing fix for simple-auth example

---

packages/gatsby-transformer-csv/package.json
packages/gatsby-transformer-json/package.json
packages/gatsby-transformer-remark/package.json
packages/gatsby-transformer-xml/package.json

Bump peer deps. See #8794 for context as to _why_ this matters :)

chore: add peer deps for some transformer packages

---

docs/docs/plugins.md

I hope i added this in the correct file.
Context: this is related to PR #8695 and issue #7518

Explain how to load a plugin from a different location

---

docs/sites.yml

Add AirBnB Cereal to the site showcase

---

docs/starters.yml

I updated some of the information for my starter on the starter library -  [gatsby-starter-gcn](https://github.com/ryanwiemer/gatsby-starter-gcn)

Update gatsby-starter-gcn description and tags  

---

docs/docs/deploying-to-gitlab-pages.md

Add Deploying to GitLab Pages section

---

packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-ssr.js.snap
packages/gatsby-plugin-feed/src/__tests__/gatsby-ssr.js

Added tests for the SSR part of `gatsby-plugin-feed`. Please let me know if anything needed further. Thanks!

test: add tests for gatsby-plugin-feed

---

docs/docs/gatsby-link.md

Not sure if you think this is a good addition but we ended up implementing it in our build & I thought it might be useful for others.

[DOCS] Update gatsby-link.md to include file download check

---

docs/docs/create-transformer-plugin.md

This could be like a WIP. I am not sure i included every aspect of it. I am open to suggestions.
I basically started working on this because the page is empty and i was working on a transformer in the morning.

Start documenting transformer plugins

---

azure-pipelines.yml

chore(azure-pipelines): split scripts into separate steps

---

docs/sites.yml

Update my website descriptions and add a new website to the showcase: 
[https://subtle-ui.netlify.com/](https://subtle-ui.netlify.com/)

Update Descriptions and Add new Site To The Showcase

---

docs/sites.yml

Hey, I wanted to submit my site to the showcase 🙂

Site showcase submission

---

docs/sites.yml

Update site showcase

---

packages/gatsby-plugin-manifest/README.md

update Web App Manifest compat

---

docs/starters.yml

Adding v2 starter based built with Bulma

[v2/starter] Gatsby v2 Starter based on Bulma

---

www/src/views/starter-library/starter-list.js

The original hyperlink pointed to a blank issue and now there's a doc with submission instructions. Not sure how to do links properly in a .js file.

Updated hyperlink

---

docs/tutorial/part-three/index.md

Updating code diff highlighting to accurately reflect final changes to src/components/layout.js.

Updated code diff highlighting

---

docs/docs/deploying-to-netlify.md

The indentation made it a code block

Remove code block

---

README.md

Changes:
1. Minor typo fixes.
2. Added a few missing commas (,).
3. Made minor changes to the styling of the document for easy readability.

Typo fixes and minor styling changes

---

docs/blog/2018-10-08-hacktoberfest-kickoff/index.md
docs/blog/2018-10-09-hacktoberfest-kickoff/index.md

adds hacktoberfest kickoff blog post

add hacktoberfest kickoff blog post

---

docs/sites.yml
docs/starters.yml

Required before https://github.com/gatsbyjs/peril-gatsbyjs/pull/41 can merge.

fix: update sites and starters YAML to pass validation

---

packages/gatsby-transformer-pdf/package.json
packages/gatsby-transformer-yaml/package.json

chore: one liner changes to force new version

---

docs/starters.yml

Hey,
Here is a new starter I develop.
I tried to document it as much as I can. See the repo's readme for more information: https://github.com/maxpou/gatsby-starter-morning-dew

add starter gatsby-starter-morning-dew

---

docs/docs/graphql-reference.md

I used this on a recent project, found some references in other GraphQL documentation. thought it could be useful for other people too.
HELP WANTED: I'm afraid I wasn't able to figure out how to create an iFrame with the interactive Graphql as displayed elsewhere on this page, I would appreciate some help to do that.

[Docs] Added GraphQL Query aliasing guide

---

docs/sites.yml

Add Emergence to gatsby showcase

---

docs/docs/component-css.md
docs/docs/post-css.md

PR: Content migration - Post CSS

---

packages/gatsby/cache-dir/load-directly-or-404.js
packages/gatsby/cache-dir/register-service-worker.js

fix(register-service-worker): show an error if installing SW not over HTTPS

---

docs/docs/contributor-swag.md

added link to swag store to descriptive text under Details header. I had to Google to find the link, might be nice to have it right here.

Minor tweak to the file

---

docs/sites.yml

prettier is very picky about its yaml :(

fix(showcase): format sites.yaml

---

docs/sites.yml

Added Bear Archery to showcase

---

examples/client-only-paths/package.json

Update package.json in client-only-paths example

---

docs/docs/unit-testing.md

Add missing moduleNameMapper key to TypeScript unit testing config

---

docs/docs/plugin-authoring.md
docs/docs/source-plugin-tutorial.md
docs/docs/submit-to-plugin-library.md
www/src/data/sidebars/doc-links.yaml

Created submit-to-plugin-library.md

---

docs/sites.yml

Added my portfolio site back to Showcase after issue #8934

Add David James Portfolio to Showcase

---

packages/gatsby-plugin-react-css-modules/src/gatsby-node.js

Runs a quick check to sanitize pluginOptions

---

docs/sites.yml

docs : added more sites to gatsby showcase

---

www/src/components/chart.js

change charts to percent

---

CHANGELOG.md

Spelling error corrected.

---

docs/docs/create-transformer-plugin.md

Fixes broken URL. Also replaces `gatsby-transform-remark` with `gatsby-transformer-remark` - the wrong name was referenced from the plugin.

Add leading slash to absolute URL

---

packages/gatsby-transformer-pdf/README.md

fix(docs): fix link gatsby-transformer-pdf/README

---

docs/sites.yml

Add Microlink website to showcase

---

docs/blog/2018-10-09-uptick-docs-contributions-hacktoberfest/index.md
docs/blog/2018-10-12-uptick-docs-contributions-hacktoberfest/index.md

Hello! Probably would be good to post this today if it looks good to go! I'll be offline from now on so just make any edits as you see fit!

docs(blog): add hacktoberfest uptick blog post

---

docs/starters.yml

Added Cosmic JS starters to library

---

docs/sites.yml

fix(showcase): remove/merge duplicate entries

---

docs/docs/migrating-from-v1-to-v2.md

Fix instructions in migration guide saying to use "next" version

---

packages/gatsby-source-wikipedia/package.json

Add axios as dependency to gatsby-source-wikipedia

---

docs/starters.yml

Add gatsby-universal to starter showcase.

---

docs/sites.yml

I added the hypertextcandy.com site to the Showcase.

Add Hypertext Candy to Showcase

---

docs/sites.yml

Update showcase entry for janosh.io with extended description of supported features

---

docs/sites.yml

Hi,
My website is now running under Gatsby 🎉 
I did it with the started: [maxpou/gatsby-starter-morning-dew](https://github.com/maxpou/gatsby-starter-morning-dew).
Thanks!

Update showcase - add maxpou.fr

---

docs/blog/2018-10-15-beyond-static-intro/index.md

Fixes an invalid date in the blog post I just merged 😅

chore: fix date

---

docs/docs/add-page-metadata.md
docs/docs/add-seo-component.md
www/src/data/sidebars/doc-links.yaml

Fixes #4921
So I was at a [hacktoberfest event](https://hacktoberfestffm.de/) this evening and this is what I came up with!
I also saw that the `add-page-metadata` document is already finished but not in the sidebar.

docs(www): Adding a SEO component

---

packages/gatsby-plugin-offline/package.json

Update Gatsby version to latest to solve issue #9145

Update Gatsby version to latest to solve issue 9145

---

docs/tutorial/part-four/index.md

Fixed image links in index.md

---

docs/starters.yml

Since https://github.com/gatsbyjs/gatsby/pull/8076 is merged I can savely publish my prismic starter.
Also needed for the doc https://github.com/gatsbyjs/gatsby/pull/8956

Add gatsby-starter-prismic

---

docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
docs/blog/2017-09-26-embracing-graphql/index.md
docs/blog/2017-11-06-migrate-hugo-gatsby/index.md
docs/blog/2018-03-07-why-we-created-the-plugin-library/index.md
docs/blog/2018-07-20-why-we-built-the-site-showcase/index.md
docs/docs/centralizing-your-sites-navigation.md
docs/docs/html-generation.md
docs/docs/node-tracking.md
docs/docs/preparing-for-site-launch.md
docs/docs/query-execution.md
docs/docs/query-extraction.md
docs/docs/schema-connections.md
docs/docs/schema-gql-type.md
docs/docs/testing-components-with-graphql.md
docs/docs/testing-css-in-js.md
docs/docs/third-party-graphql.md
docs/docs/write-pages.md
docs/sites.yml
docs/starters.yml

Cherry pick out just commit "Fix spelling" https://github.com/gatsbyjs/gatsby/pull/8873/commits/07a1321c501f230e65f8992e27fcef3bed9d0501 from https://github.com/gatsbyjs/gatsby/pull/8873 to make that less of a monster and less merge conflicty!

Docs: Fix spelling

---

docs/blog/2017-02-21-1-0-progress-update-where-came-from-where-going/index.md

minor change and requested change addressed

---

www/src/pages/features.js

https://github.com/gatsbyjs/gatsby/pull/9155 changed casing in .csv headers and we need to adjust query for that
also additional casing change in page code to make it consistent

fix(www): adjust query after changes in csv

---

docs/docs/graphql.md

'conceptual guide' link was pointing to an un-styled md file on the live docs site. Where the link error is https://www.gatsbyjs.org/docs/graphql/

Fixed link typo

---

docs/sites.yml

Add my personal website [dantecalderon.com](https://dantecalderon.com/) to sites.yml.

Add dantecalderon.com to sites.yml

---

docs/blog/2018-09-27-sendgrid-knowledge-center-cuts-page-load-times-in-half-with-gatsby/index.md

fix(docs): Fix image alt text

---

docs/docs/environment-variables.md

The existing documentation was all correct, but ambiguous and confusing in places, with a weird mix of assumed and non-assumed knowledge. It was also very unclear how Additional Environments were working.

Add detail and clarity around Environment Vars

---

docs/blog/2018-06-18-why-narative-loves-gatsby/index.md

@calcsam I've updated the blog post with some great details about Narative (as discussed).

Updating Narative's blog post with company accomplishments

---

docs/sites.yml

This adds Flamingo to the showcase. See #9168.
I also tried to fit this site into an already existing category, but thought that 'beauty' would make a good addition anyways. Otherwise maybe Health & Wellness might work(?).

Update showcase - add Flamingo (shopflamingo.com)

---

packages/gatsby-transformer-remark/package.json
yarn.lock

potentially fix issue reported by #9174 (I don't want to autoclose lol)

chore(gatsby-transformer-remark): upgrade hast-util-raw

---

www/package.json

chore(www): bump gatsby-transformer-remark

---

docs/starters.yml

Adding a new starter to the list.

Add lumen v2 starter

---

packages/gatsby-image/README.md

Update copy on gatsby-image README

---

docs/docs/how-to-contribute.md

Rephrase a confusing bullet

---

packages/gatsby-plugin-offline/package.json
yarn.lock

This contains a fix for a bug with [redirected responses](https://twitter.com/jeffposnick/status/1053379608698077185); see https://github.com/GoogleChrome/workbox/releases/tag/v3.6.3

Update Workbox to 3.6.3

---

docs/docs/preparing-your-environment.md
www/src/data/sidebars/doc-links.yaml

small cleanup tasks
- Missing overview for "Preparing your environment" section
- Update docs sidebar for pages that are no longer stubs / duplicative / no longer relevant

docs cleanup tasks

---

docs/sites.yml

I'm adding a site that I worked on to the showcase.

Add The Noted Project to sites.yml

---

docs/starters.yml

as per https://github.com/gatsbyjs/gatsby/issues/7005

feat(starters): add 416serg/gatsby-starter-lightbox

---

docs/sites.yml

Added LANDR to sites.yaml showcase, as suggested in #9315

---

docs/docs/creating-global-styles.md

- Changed the emotion import as `react-emotion` is fine, too
- Improved the shell commands

www(docs): Change emotion import + minor edits

---

www/src/components/search-form.js

fix(www): search not initializing after client-side routing

---

examples/using-javascript-transforms/src/components/HelmetBlock/index.js
packages/gatsby-plugin-offline/src/__tests__/index.html
www/src/components/layout.js
www/src/components/package-readme.js
www/src/components/showcase-details.js
www/src/templates/template-blog-post.js
www/src/templates/template-docs-markdown.js
www/src/templates/template-starter-page.js
www/src/views/starter-library/index.js

Fix for issue #9288 
Replaced "name=og:<some-name>" -> "property=og<some-name>."

update open graph meta tags attributes from name to property

---

docs/docs/using-unstructured-data.md
www/src/data/sidebars/doc-links.yaml

Update unstructured data doc
Todo:
- link to blog post when it goes up

Update unstructured data doc

---

docs/sites.yml

Added https://www.gotmilk.com/ to Showcase

---

docs/sites.yml

Added 2 sites to the showcase

---

docs/docs/add-a-manifest-file.md
docs/docs/add-offline-support.md
docs/docs/add-page-metadata.md

Some links were broken in the docs.

Fixed docs links

---

docs/sites.yml

Added https://www.markets.com/ to the site showcase

---

docs/sites.yml

Added some sites to showcase

---

www/src/views/starter-library/filtered-starters.js

Change initial load from 9 starters to 12

---

www/src/views/showcase/featured-sites.js
www/src/views/showcase/filtered-showcase.js

- fix: display 12 sites in featured site list
- [#9393](https://github.com/gatsbyjs/gatsby/issues/9393)

fix: display 12 sites in filtered sites grid

---

examples/using-styled-components/package.json
examples/using-styled-components/src/pages/index.js

- Update to v4
- Use the new global style API
- Replace inline style with styled
- Remove stray backticks (again...)

feat(examples): update styled components example

---

examples/using-remark/src/pages/2018-01-27---custom-components/index.md

Fixed the broken link
Fixes #9426

Fix issue #9426

---

docs/blog/gatsbygram-case-study/index.md

There was a small typo which I have fixed. :)

fix(blog): fix minor typo

---

docs/docs/awesome-gatsby.md

I wrote about why I chose Gatsby to rebuild my portfolio website and also covered other topics on image optimization with gatsby-image and hosting to Netlify. It has been published in the freeCodeCamp Medium publication and has reached over 1k claps! Super happy to have been able to spread the word about Gatsby!

feat(docs): add Gatsby tutorial published in FreeCodeCamp pub to awesome gatsby page

---

docs/sites.yml

Add weihnachtsmarkt.ms to sites

---

packages/gatsby-source-filesystem/src/gatsby-node.js

The corresponding code was removed in #8859.

chore(gatsby-source-filesystem): remove outdated comments

---

packages/gatsby-plugin-jss/src/gatsby-ssr.js
packages/gatsby/cache-dir/api-ssr-docs.js
packages/gatsby/cache-dir/static-entry.js

Not sure about the branch for this one. Just a small patch based off of cpboyd's solution for this issue: https://github.com/gatsbyjs/gatsby/issues/7716
closes #7716

fix(gatsby-plugin-jss): use separate SheetsRegistry for each page

---

docs/sites.yml

feat(showcase): add WK to showcases

---

docs/blog/2018-04-25-how-gatsby-changes-teams-website-development-workflow/index.md

fix(blog): improve grammar

---

docs/docs/add-a-service-worker.md
docs/docs/ecommerce-tutorial/index.md
docs/docs/schema-gql-type.md
docs/docs/sourcing-from-contentful.md

Add file name emphasis to docs

---

docs/docs/caching.md

This PR will close #9151 
This doc talks about best practices, and I have read up on them to come to this conclusion. Please let me know if I'm missing anything or if I need to write a more detailed document for the same 
(the max-age should ideally be set based on how often you are likely to update your website)

Update caching.md to conform to webpack 4 standard

---

examples/README.md

Fix typo in `examples/README.md`

---

packages/gatsby-source-contentful/README.md

Corrected a typo in README.md .

Typo fix in gatsby-source-contentful/README.md

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

ref https://github.com/netlify/netlify-cms/issues/1456 , https://github.com/netlify/netlify-cms/issues/683

fix(gatsby-plugin-netlify-cms): automatic redirect

---

docs/docs/visual-testing-with-storybook.md

As suggested by @calcsam in https://github.com/gatsbyjs/gatsby/pull/9120#issuecomment-433676737, here's my review comments in its own PR.
Follows https://www.gatsbyjs.org/docs/gatsby-style-guide/#write-concisely
cc @kkemple @shannonbux
Also use “you” as the pronoun, following the [style guide](https://www.gatsbyjs.org/docs/gatsby-style-guide/#use-you-as-the-pronoun).

Make text a little less wordy, as people generally don't read long text on-screen

---

docs/docs/recipes.md

Addresses #9523 
- Changed "full docs" link to point at https://www.gatsbyjs.org/docs 
- Reordered ToC based on the section layout

Fix link issues in recipes page

---

packages/gatsby/src/redux/actions.js

Update documentation spelling in actions.js

---

docs/sites.yml

Add usehooks.com

---

docs/sites.yml

Edit sites.yml. Edit Caddy smells like trees

---

docs/sites.yml

Clubhouse just launched a new brand and a beautiful website that was built using the latest and greatest gatsby v2
"Featured" material 😉
https://clubhouse.io

Add Clubhouse to showcases

---

docs/sites.yml

Added  http://artmuseum.princeton.edu/asian-art/   to showcase
Closes #9586

feat(showcase): add Asian Art Museum to showcase

---

benchmarks/create-pages/README.md
benchmarks/markdown/README.md

Add some details on how to run the benchmarks (create-pages, and markdown). I was looking for performance comparisons for a node optimization and it was not initially obvious how to run it. I since figured it out.  Here for example is a 3% performance improvement through the optimization in node.
NEW
```
success Building static HTML for pages — 0.613 s — 5001/5001 10403.89 pages/second
info Done building in 10.092 sec
```
OLD
```
success Building static HTML for pages — 0.631 s — 5001/5001 10071.25 pages/second
info Done building in 10.353 sec
```

  Update benchmark running instructions.

---

www/src/templates/template-blog-post.js

Remove background, box-shadow and border-bottom from author image (9593)

---

docs/tutorial/part-zero/index.md

Mostly edited punctuation. Also, changed an abbreviation to match the style guide.

Edited for punctuation and style guide

---

docs/docs/page-query.md

Fix broken links on page-query doc

---

www/src/pages/404.js

Recently I made some changes to the docs #9486 which included deleting one file. But that doc page has already been indexed by the search engines & when opening shows :point_down: 
But there is not message or information for the user about what happened & what do to next.
So I made some changes to improve UX :+1:

Improves Page Not Found UX

---

www/src/pages/index.js

Grammatical fix: "set up" is two words (except when it's a noun)

---

examples/using-remark/gatsby-node.js

example-using-remark reject Promise on error

---

www/src/views/shared/sidebar.js
www/src/views/starter-library/filtered-starters.js

Add `overflowY: scroll` to filtered starters sidebar

---

docs/docs/headless-cms.md

Added Kentico Cloud to the list of supported CMSes

Added Kentico Cloud to the list of supported CMSes

---

docs/docs/using-unstructured-data.md

removed extra 'to' from the docs

docs: removed duplicated 'to' from the docs

---

docs/sites.yml

feat(showcase): add a11ywithlindsey.com

---

packages/gatsby-source-contentful/README.md
packages/gatsby-source-graphql/README.md
packages/gatsby-source-wordpress/README.md

This PR adds some boilerplate text for plugins that have secret data,
access tokens, etc. Open to tweaking language here, this is a decent
first pass, so certainly open to suggestions or other approaches.
cc @jlengstorf @KyleAMathews @pieh

chore: tweak readme for various plugins that use secrets/keys

---

docs/sites.yml

seems like those aren't accessible anymore and it breaks www build

fix(showcase): remove about.sourcegraph.com and upgizmo.com

---

docs/sites.yml

We built this site using Gatsby v2 and Prismic and would love to add it to your showcase.

Add DEKEMA to the site showcase

---

docs/sites.yml

- Update my own entry
- Add Design System to entries appropriately + Rename `DesignSystems` to `Design System`

feat(www): Update showcase

---

docs/docs/how-code-splitting-works.md

Fixed the spelling of "custimize" on Line to 27 to read "customize"

Fix spelling Line 27

---

docs/sites.yml

Closes #9729 : Added Ghost docs and Bellhops websites to Showcase

---

www/src/components/layout.js
www/src/components/layout/layout-with-heading.js

Also added a reminder in the `Layout` component that the another component need to be updated if we change the content of banner.

fix(www): update banner content in layout-with-heading

---

docs/blog/2018-2-3-sites-with-headless-cms/index.md

Adding link for better accessibility

---

docs/starters.yml

Update starters.yml to add jamstack-hackathon-starter

---

docs/docs/headless-cms.md

One of two changes for https://github.com/gatsbyjs/gatsby/issues/9757
Second change will be a complete guide for ButterCMS. I'll open a new PR for that.

Adds ButterCMS to source list of CMS systems

---

packages/gatsby-plugin-google-gtag/README.md

docs(gatsby-plugin-google-gtag): fix opt out snippet

---

docs/sites.yml

Added acclimate.io consulting website to showcase

---

docs/tutorial/part-two/index.md

While reading the tutorial doc, I noticed one line that appeared to be missing the title markup.

Add missing title markup.

---

docs/blog/2018-11-07-gatsby-for-apps/index.md

docs(blog): minor tweaks to gatsby for web apps

---

package.json
packages/gatsby-plugin-catch-links/CHANGELOG.md

chore: restore version script

---

docs/starters.yml

Adds gatsby-starter-plone which uses gatsby-source-plone to the Starters library

Add gatsby-starter-plone to Starters library

---

packages/gatsby/src/commands/develop.js

fix: development proxy throws unhandled exceptions

---

docs/docs/environment-variables.md

+1 -1 small typo fix for example in doc/environment-variables.md

---

docs/docs/awesome-gatsby.md

I added a blog post about deploying a static Gatsby app to Heroku to the list of Gatsby tutorials.

Added a blog post to the "Awesome Gatsby" list

---

docs/docs/add-offline-support-with-a-service-worker.md

- Updated dead link "/audit-with-lighthouse/" to "/docs/audit-with-lighthouse/"
- Updated dead link "/add-a-manifest-file/" to "/docs/add-a-manifest-file/"

Updated dead links

---

docs/starters.yml

fix(www): Change Plone starter entry

---

packages/gatsby/src/utils/api-browser-docs.js

docs: add example for disableCorePrefetching

---

docs/blog/2018-11-11-introducing-gatsby-themes/index.md

alter chris blog post date

---

docs/sites.yml

My site is already added to showcase. I published the source code so I added information.

fix(showcase): update showcase entry

---

docs/sites.yml

Hi all, we built our company site with Gatsby, Contentful and Netlify! 
Thanks for building such an amazing ecosystem ❤️

Add Flyright to the Gatsby site showcase

---

docs/docs/working-with-images.md

Improved markdown/Syntax Highlighting

---

docs/docs/unit-testing.md

Following [suggestions](https://github.com/gatsbyjs/gatsby/pull/9795#issuecomment-436809926) from @shannonbux to improve `unit-testing.md` further

Improving unit-testing.md

---

docs/docs/sourcing-from-prismic.md

A bit more information in the Netlify part.

feat(www): Additional Netlify information in Prismic guide

---

docs/blog/2018-08-09-swag-store/index.md

Improved markdown - for correct displaying link

Improved markdown

---

docs/sites.yml

Add Vets Who Code to showcase

---

packages/gatsby-plugin-react-helmet/README.md

Fix broken link in README for gatsby-plugin-react-helmet

---

www/src/components/share-menu.js
www/src/views/starter/meta.js

Issue #9591  Fixed CSS to have Share button match sizing of Visit Demo button. Fixed functionality of the Share button to have the drop down disappear when clicking anywhere outside of the menu.

Fixed CSS for Starter Template Share button

---

docs/sites.yml

feat(showcase): add Patreon Blog and Full Beaker sites

---

docs/sites.yml

Adding an entry for https://citywideholdup.org

---

docs/docs/unit-testing.md

removes unnecessary closing bracket in code example

Fixes example syntax for unit testing

---

docs/docs/production-app.md

docs(production-app): Typo fix

---

docs/docs/static-query.md

Add notice about StaticQuery only working with JSX

---

docs/sites.yml

Add [Propapanda's](https://propapanda.eu/) site to showcase

add Propapanda's site to showcase

---

www/src/components/layout.js
www/src/components/layout/layout-with-heading.js

@lindaleebumblebee @KyleAMathews

Change banner text, add outbound link tracking

---

docs/blog/gatsby-first-beta-release.md

`infastructure` => `infrastructure`

docs(gatsby-first-beta-release): Fix

---

docs/blog/2018-1-25-building-a-site-with-react-and-contentful/index.md

some `entires` had photos => some `entries` had photos

docs(blog): Fix

---

docs/sites.yml

Uses [Gatsby Source Meetup](https://github.com/phacks/gatsby-source-meetup) to gather Meetup.com information 😊

Add “JAMstack.paris” to showcase

---

docs/sites.yml

Added amazing DexWallet to the gatsby showcase

---

docs/blog/2018-02-09-announcing-gatsby-manor-themes-for-gatsbyjs/index.md

fix dead links

---

docs/docs/seo.md

Hey, just noticed the term PRPL pattern in "SEO with Gatsby", turns out we actually have another doc page about that.

Add PRPL pattern doc link

---

docs/sites.yml

Add particle.io

---

docs/starters.yml

Starter for Machine learning and scientific writing

Added a GatsbyV2 starter

---

www/README.md

Fix typo in README.md

---

docs/sites.yml

Adds https://tandem.co.uk to sites list

Adding Tandem website to sites list

---

package.json
packages/gatsby/package.json
packages/gatsby/src/bootstrap/load-plugins/__tests__/validate.js
packages/gatsby/src/bootstrap/load-plugins/load.js
packages/gatsby/src/bootstrap/load-plugins/validate.js
yarn.lock

feat(gatsby): warn user about incompatible plugins

---

packages/gatsby-plugin-offline/README.md

docs(gatsby-plugin-offline): Add instructions for removing service worker

---

docs/sites.yml

Hello the Gatsby Team,
First of all, thanks for the great product you're building, and the community around it.
At [Monbanquet.fr](https://monbanquet.fr) we're using it for our main production website and it's been great so far, both in terms of user and developer experience.
As it's my first PR here, hit me up if I did something wrong :)
Cheers

[Showcase] Add Monbanquet.fr to the showcase list

---

README.md

Add licensing information to the `README` file which is a usual practice being followed 👍

Add licensing information

---

docs/sites.yml

Multiple tags were put into one

fix(www): Remove multiple entries from sites tags

---

docs/blog/2017-11-08-migrate-from-jekyll-to-gatsby/index.md
docs/blog/2018-06-16-announcing-gatsby-v2-beta-launch/index.md
docs/docs/deploying-to-aerobatic.md
docs/docs/query-behind-the-scenes.md
docs/docs/unit-testing.md
docs/docs/visual-testing-with-storybook.md

Fix some typos of 'gatsby'

---

package.json
yarn.lock

see https://github.com/mysticatea/npm-run-all/issues/150

chore: bump npm-run-all version

---

docs/docs/creating-a-sitemap.md

This was created using the package (gatsby-plugin-sitemap), I followed the guidelines and ran it through Hemingway (Just as a side note Where has this been all my life?!) - I do think it is a bit brief - Please do tell me how I can work to improve it! Really Appreciate it :)

Documentation: Created XML Sitemap Post

---

www/src/data/sidebars/doc-links.yaml

Got rid of the * as the link now isn't a stub

Made the 'create a sitemap' link active rather than the stub link colour

---

docs/starters.yml

Add Gatsby + Bulma CSS starter kit.

Add new starter kit

---

www/src/components/homepage/homepage-blog-posts.js

@greglobinski @amberleyromo 
Currently the second "View all posts" links to the homepage instead of the blog

fix(www): Update "View all" component

---

docs/sites.yml

Added joinup.io to users

---

docs/sites.yml

Added jacobdcastro.com to site showcase. 'Featured' set to 'false' and all possible YAML entries are filled out, even optional ones.

add new site to showcase

---

docs/sites.yml

Add two educational sites to showcase.

feat(showcase): add www.gatsbytutorials.com and www.upandrunningtutorials.com

---

packages/gatsby-plugin-react-helmet/README.md

They removed Helmet from "layout.js" and moved it to "site-metadata.js"

GatsbyJS.org example to site-metadata.js component

---

docs/sites.yml

I'd like to add my portfolio website to the gatsby showcase.
Thanks for all the great work you're doing! 💪
Thank you.

Add grooovinger.com to showcase

---

docs/sites.yml

Add Kylemcd.com to sites

---

www/src/components/shared/pullquote.js

Fix the issue described in https://github.com/gatsbyjs/gatsby/pull/10193#issuecomment-443839783

fix(www): remove inconsistency in pullquote styling

---

packages/gatsby-source-wordpress/README.md

Mention that if two-factor authentication is enabled then you need to create an Application-Specific Password.

[gatsby-source-wordpress] README - WP & 2-FA

---

docs/sites.yml

Adding a new site to the list. My new [VSCode Power User](https://VSCode.pro) course site. Thanks a lot, Gatsby for enabling me to do make such an awesome PWA with offline support that didn't cost me months.
Looking forward, peace! ✌️

📦 NEW: VSCode.pro

---

examples/using-emotion/package.json

chore(examples/using-emotion): update gatsby-plugin-emotion to v3

---

docs/tutorial/part-two/index.md

In line with part one, the link to the next part should use the part's name.

Adds a more descriptive link purpose

---

packages/gatsby-plugin-sass/README.md

Remove extra `a` in `gatsby-plugin-sass` docs.

Fix typo in gatsby-plugin-sass README

---

www/src/data/sidebars/doc-links.yaml

fix(www): Awesome Gatsby Link

---

docs/docs/awesome-gatsby.md

With the re-add of "Awesome Gatsby" to the sidebar (thanks again @LekoArts) just a couple link changes, and added a podcast.

fix(docs): link fixes, podcast addition

---

docs/sites.yml

Add Ad Hoc Homework to sites.yml

---

docs/sites.yml

I'd like to add satispay.com to showcase list.

Add satispay.com to showcase

---

docs/docs/recipes.md

Previously the "starter list" linked to a page that wasn't found. This fixes it and updates the copy to reflect the current name.

Fix Starter Library URL and update copy

---

docs/docs/add-offline-support-with-a-service-worker.md

fix(docs): prompt => confirm

---

docs/sites.yml

docs: add ClinciJS website into showcase

---

docs/sites.yml

Add kobit.in to showcase
I released a site. Thanks.

Add kobit.in to showcase

---

docs/starters.yml

Adding a new starter to the list.

Add new starter

---

docs/docs/how-to-contribute.md

@pieh @DSchau would these changes throw off anything in OSS process?

Updating for docs contributions

---

docs/docs/environment-variables.md

In this context, what we want is "its", not "it's".

Remove apostrophe

---

docs/docs/gatsby-cli.md

"Lets" as in allows, rather than "let's", meaning "let us".

let's -> lets

---

docs/docs/authentication-tutorial.md

add jamstack hackathon starter

---

docs/docs/how-to-contribute.md
packages/gatsby-transformer-remark/README.md

Quick fix for #10522 getting merged which will fail the linter

chore: make the linter happy

---

.github/ISSUE_TEMPLATE/feature_request.md
benchmarks/create-pages/README.md
benchmarks/markdown/README.md
docs/tutorial/index.md

Improved some grammar

---

www/src/components/function-list.js

added key to the container div

---

packages/gatsby/package.json
yarn.lock

fix(gatsby): bump minimum react-hot-loader version to get quick fix

---

docs/sites.yml

Surf -> Surfing
React-Native -> React Native

docs(showcase): Update two tags

---

docs/blog/2018-12-04-gatsby-analogy/index.md
www/src/components/shared/pullquote.js

Adds a basic source citation to blog pullquotes, if supplied.

Add pullquote citation

---

docs/starters.yml

Hi, I've added a new starter that I created - https://awesome-gatsby-starter.netlify.com/
Thanks!

Add awesome-gatsby-starter

---

docs/docs/awesome-gatsby.md

I added a link to the Gatsby Days playlist from YouTube.

fix(docs): Updated awesome-gatsby.md file to include Gatsby Days Playlist

---

www/src/pages/plugins.js

A la #10450, add a feedback instance to the plugin lib.

add unbird feedback component to plugin lib

---

docs/docs/awesome-gatsby.md

Update podcasts with Jason Lengstorf on React Podcast.

Update podcasts list

---

.circleci/config.yml

(this will diff vs. master I believe; which would not be meaningful
here)

ci: remove circleci assertion for changed files

---

starters/blog/package-lock.json
starters/default/package-lock.json
starters/hello-world/package-lock.json

Updates `package-lock.json` for our three official starters

Update starter lock files so that npm audit is clear

---

e2e-tests/production-runtime/cypress/integration/prefetching.js
e2e-tests/production-runtime/cypress/integration/production.js
e2e-tests/production-runtime/cypress/integration/resource-loading-resilience.js
e2e-tests/production-runtime/package.json
e2e-tests/production-runtime/scripts/chunks.js
e2e-tests/production-runtime/src/pages/404.js
e2e-tests/production-runtime/src/pages/page-2.js
packages/cypress-gatsby/api-handler.js
packages/cypress-gatsby/commands.js
packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/loader.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/src/internal-plugins/query-runner/pages-writer.js

Code is complete. Mostly tests are WIP - they should work, but test suite will probably take a very long time, so just testing it in current state to see if I need to adjust it
fixes #9346 (chunk 43 in the error on gatsbyjs.org is pages manifest)

fix(gatsby): handle missing pages metadata chunk

---

docs/sites.yml

added a new website to showcase.

added a new website

---

starters/blog/package-lock.json
starters/blog/package.json
starters/default/package-lock.json
starters/default/package.json
starters/hello-world/package-lock.json
starters/hello-world/package.json

chore(starters): bump lock file to gatsby@2.0.76 to fix dev 404 error

---

www/src/utils/typography.js

fix(www): Disable ligatures for code blocks in documentation

---

docs/docs/authentication-tutorial.md

chore: format

---

docs/starters.yml

Hello! I added the starter created by me based on the default starter, gatsby-starter-cv
**link:** https://devchico.com/gatsby-starter-cv/
tks!

add gatsby-starter-cv

---

docs/starters.yml

hi, I appended a new starter to the starters.yml, please check it out...
no yet.

add netlify identity starter

---

docs/docs/environment-variables.md

Closes https://github.com/gatsbyjs/gatsby/issues/10328

Document ENABLE_GATSBY_REFRESH_ENDPOINT

---

docs/sites.yml

Yet another showcase for the list
* https://songwang.io/
* https://github.com/wangsongiam/songwang.io

add songwang.io to sites list

---

docs/sites.yml

We updated and redesigned my wife's photography website.

Add Kirsten Noelle website to the showcase

---

packages/gatsby-source-graphql/src/gatsby-node.js

Hi there! 👋This is just a small pull request to fix a minor spelling error in an invariant violation message in `gatsby-source-graphql`.

Fix minor spelling error, requiers -> requires

---

docs/sites.yml

This adds ev-ibiza.com to the showcase.

[showcase] add ev-ibiza.com to showcase

---

packages/gatsby-transformer-sharp/README.md

Fixes https://github.com/gatsbyjs/gatsby/issues/10232 as per Slack discussion

feat(gatsby-transformer-sharp): Add note about source plugin

---

docs/sites.yml

I would like to add my [personal website](https://shamann.fr/) to your showcase.  
Thank you for your great work <3

Add shamann.fr to Showcase

---

docs/sites.yml

This PR adds [my personal website](https://wongmjane.com) to the showcase. It is built with Gatsby v2 and leverages the plugin ecosystem to delivery smooth PWA experience to readers.

Add Jane Manchun Wong's website to showcase

---

docs/starters.yml

Updated the starters with gatsby careers starter available https://hardcore-darwin-d7328f.netlify.com/

Add gatsby careers starter

---

docs/starters.yml

They both now use `react-spring` and `gatsby-mdx` 👍

feat(starters): Update Emma, Emilia & Cara starter

---

docs/docs/sourcing-from-databases.md
www/src/data/sidebars/doc-links.yaml

Add in links to packages referencing how to source data from databases

Update sourcing from databases

---

examples/using-asciidoc/gatsby-config.js
examples/using-asciidoc/gatsby-node.js
examples/using-asciidoc/package.json
examples/using-asciidoc/src/pages/index.js
examples/using-asciidoc/src/pages/test.adoc
examples/using-asciidoc/src/templates/article.js

feat: update asciidoc example to use new transformer plugin

---

packages/gatsby-transformer-react-docgen/src/Doclets.js
packages/gatsby-transformer-react-docgen/src/__tests__/Doclets.js
packages/gatsby-transformer-react-docgen/src/__tests__/fixtures/classes.js
packages/gatsby-transformer-react-docgen/src/__tests__/on-node-create.js
yarn.lock

react-docgen: add multiple same doclet values as array

---

docs/docs/client-data-fetching.md

Build out client data fetching stub.

feat(docs): build out client data fetching stub

---

docs/docs/client-data-fetching.md

chore: fix lint error

---

docs/starters.yml

Updated starters with gatsby minimal porfolio website and blog. Live version: https://saikrishna.me/

Add gatsby minimal porfolio website blog starter

---

docs/sites.yml

Hi everyone,  
I would like to add my personal website built with Gatsby and BulmaCSS to your showcase.  
Thank you so much 🙏👋

Add Luca Crea's portfolio to showcase

---

packages/gatsby/src/internal-plugins/query-runner/query-watcher.js

Follow-up to https://github.com/gatsbyjs/gatsby/pull/10765

docs(gatsby): Minor tweak to warning message

---

.circleci/config.yml
scripts/clone-and-validate.sh

Will slightly speed up the install/setup step for validating starters

fix(ci): do not run (unnecessary) install step for starters validation

---

docs/sites.yml

Hey everyone, I added our website to the showcase. I would be glad if you merge it. ☺️

docs: add exposify.de to showcase

---

www/README.md
www/src/components/unbird.js
www/src/pages/plugins.js
www/src/templates/template-docs-local-packages.js
www/src/views/starter-library/index.js

(not just main lib view).
related: #9678

feat(www): add plugin feedback form to all plugin pages

---

docs/docs/unit-testing.md

Indicate Code Sample is JS

---

docs/starters.yml

Updated the details for my personal starter, [gatsby-starter-typescript-plus](https://www.gatsbyjs.org/starters/resir014/gatsby-starter-typescript-plus/).
N/A

docs(www): updated details for gatsby-starter-typescript-plus

---

docs/starters.yml

Add purgeCSS to features

---

README.md

Added `follow on twitter` badge to the docs.

chore(readme): add follow on twitter badge

---

www/src/components/layout.js
www/src/components/layout/layout-with-heading.js

requested by @lindaleebumblebee

.org banner: behind the scenes promo

---

docs/starters.yml

I created a new starter with Styled-System, Typography.js and more.

feat(starters): add gatsby-starter-styled

---

docs/sites.yml

Add Steak Point and edit Peter Kroyer

feat(site-showcase): add https://www.steakpoint.at/

---

www/gatsby-node.js
www/src/templates/template-blog-post.js

Fixes https://github.com/gatsbyjs/gatsby/issues/10800

fix(www): fallback to hostname of canonicalLink if publishedAt is not specified

---

.forestry/front_matter/templates/blog.yml
.forestry/front_matter/templates/docs.yml
.forestry/settings.yml
www/package.json

This adds front matter template configuration files and other configuration required for Forestry.io.

Add Forestry.io configuration

---

.prettierignore

#10925 had some lint issues, this (should) fix them.

chore: fix forestry yml files from #10925

---

packages/gatsby-source-contentful/README.md

Adds a caveat to gatsby-source-contentful README.md.
Addresses #6933

docs(gatsby-source-contentful): add note about node_locale filtering

---

docs/sites.yml

Add my personal website [Takumon blog](https://takumon.com/) to sites.yml.

Add Takumon blog to sites.yml

---

docs/sites.yml

Added DayThirty website to Showcase 😄 
N/A

Added DayThirty website to Showcase

---

docs/sites.yml

Hello! First PR here so I hope I didn't bork anything. 
We rebuilt Jean Luc Ponty's official site with Gatsby, Prismic.io, and Netlify. Hoping it will be a good add to the showcase. Thanks!

docs/showcase: Add ponty.com to showcase.

---

docs/sites.yml

Another site submission for the esteemed Gatsby Showcase. Thanks!

docs/showcase: Add rfallp.com to showcase.

---

docs/starters.yml

Add a starter to build traveler blog based on official blog starter

add one more starter: traveler-blog

---

docs/starters.yml

Adds a description to gatsby-starter-tailwind.

Add description to gatsby-starter-tailwind

---

docs/sites.yml

Added my portfolio to the site showcase, thank you for your consideration!

added Cole Walker's Portfolio to site showcase

---

docs/docs/pair-programming.md

I've updated the language to clarify that these sessions are intended for community and open source projects, not commercial support.

Update language for pair programming page

---

examples/gatsbygram/gatsby-browser.js

There is a statement which can be simplified to a simple single return statement.

chore(examples): shorten if else statement

---

docs/docs/creating-slugs-for-pages.md

fix(docs): redirect boundActionCreators link to actions

---

examples/image-processing/src/pages/index.js
examples/using-contentful/src/pages/image-api.js
examples/using-contentful/src/pages/index.js
examples/using-css-modules/src/pages/index.js
examples/using-drupal/src/pages/index.js
examples/using-drupal/src/pages/recipes.js
examples/using-drupal/src/templates/recipe.js
examples/using-redirects/src/pages/index.js
packages/gatsby/cache-dir/static-entry.js
www/src/components/evaluation-table.js
www/src/pages/features.js

Some packages throw aslant warnings and this PR resolve them.
Fixes #10943

chore: Fix ESLint warnings

---

docs/tutorial/part-eight/index.md

Fix punctuation and grammar for better readability.

fix: grammar and punctuation marks!

---

docs/docs/seo.md

Incorporated https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline#notes into the SEO doc

feat(docs): Update SEO instructions

---

docs/starters.yml

Add a starter to build gatsby-sseon-starter based on official blog starter

add one more starter: gatsby-sseon-starter

---

docs/sites.yml

Stitch Fix is no longer using GatsbyJS

fix(showcase): Remove Stitch Fix from featured sites

---

docs/docs/headless-cms.md

Added Cosmic to the Headless CMS page

fix(docs): added Cosmic to headless-cms page

---

docs/starters.yml

Made some progress in my updates/revamps

feat(www): Update LekoArts' starters

---

docs/docs/gatsby-on-windows.md

Minor spelling mistake and grammar usage errors fixed in docs.

fix(docs): typo and grammar errors in gatsby-on-windows.md

---

docs/starters.yml

update gatsby-starter-blog-grommet information

---

docs/docs/performance-tracing.md

Minor errors in grammar and miscellaneous spelling and punctuation errors fixed in docs.

fix(docs): minor grammar and misc errors in performance-tracing.md

---

docs/docs/page-node-dependencies.md

fix(docs): minor typo in page-node-dependencies.md

---

docs/docs/page-creation.md

Minor spelling mistakes and omission fixed in docs.

fix(docs): minor typo errors in page-creation.md

---

docs/docs/html-generation.md

fix(docs): grammar and misc errors in html-generation.md

---

docs/sites.yml

Adds two recent Gatsby sites to the Showcase: an opera singer and a health-related charity.

[showcase] Add Ashley Thouret and The AZOOR Society

---

docs/starters.yml

added gatsby-craftcms-barebones to starters

added gatsby-craftcms-barebones to starters

---

packages/gatsby/cache-dir/default-html.js

Refactor the `<HTML />` component into a function component instead of a class component.
N/A

refactor: convert default-html to a function component

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

Watch CMS files during local development so changes can be viewed by refreshing (rather than requiring a manual restart of the dev server).
Closes #10767

improvement(gatsby-plugin-netlify-cms): watch cms files

---

www/README.md
www/src/pages/plugins.js
www/src/templates/template-docs-local-packages.js
www/src/templates/template-docs-remote-packages.js
www/src/views/starter-library/index.js

@DSchau ready for when you make that change.
Fixes #11143

fix: env var name change for build

---

docs/sites.yml

Not sure about the categories.

[Showcase] npm.cardiv.de

---

docs/docs/adding-images-fonts-files.md

Just my first try at contributing, this one point seemed awkwardly worded

fix(docs): Update adding-images-fonts-files.md

---

yarn.lock

Update lock file to match changes from https://github.com/gatsbyjs/gatsby/pull/11186
Refs https://github.com/gatsbyjs/gatsby/pull/11186

chore: Update lockfile

---

packages/gatsby/src/schema/__tests__/infer-graphql-input-type-test.js

The input filter InputObjectType is on a `filter` field. This adjusts the tests to check the correct type

fix(gatsby): Fix input filter tests

---

docs/blog/2019-01-24-swag-store/index.md

The link to Whimsical was broken so I fixed it :-)

Fix broken link in index.md

---

docs/docs/ecommerce-tutorial/index.md

- Fix misspelling of "Component"
- Added a missing "of" after "entails"
- Added missing commas
- Capitalised "sku" for consistency with the rest of the tutorial

fix(Docs) Correct some spelling and grammar in eCommerce tutorial

---

packages/gatsby/src/redux/__tests__/run-sift.js
packages/gatsby/src/redux/run-sift.js

Unfortunately I introduced a small regression today with #11149. This fixes it and updates the test. I am very sorry for this!!

fix(gatsby): Fix regression introduced in #11149

---

docs/docs/create-source-plugin.md
docs/docs/create-transformer-plugin.md

cc @KyleAMathews, updated with an example.

Update create transformer plugin doc

---

docs/blog/2019-01-25-blazing-fast-development-with-gatsby-and-sanity-io/index.md

I had one of the configuration keys inversed – sorry!

fix(docs): correct configuration key for sanity blog post

---

docs/docs/contributor-swag.md

+ Added mention of free item **per tier** instead of just one free item **per contributor**

fix(docs): Editing the fine print of contributor-swag

---

docs/starters.yml

Add gatsby-material-ui-business-starter starter

---

www/src/data/sidebars/doc-links.yaml

Follow up to #10898 adding a link to this document to the overall nav hierarchy!

feat: add tailwind-css to doc hierarchy

---

packages/gatsby-source-filesystem/README.md

docs(gatsby-source-filesystem): improve description

---

docs/blog/2019-01-28-building-a-large-ecommerce-website-with-gatsby-at-daniel-wellington/index.md

Tweak language in the Daniel Wellington post

docs: edit Daniel Wellington post

---

docs/blog/2019-01-28-building-a-large-ecommerce-website-with-gatsby-at-daniel-wellington/index.md

Fix link for Daniel Wellington

doc: fix-wellington-link

---

docs/tutorial/part-two/index.md

Remove Extraneous Word

---

docs/tutorial/part-four/index.md

Fix wording.
Change
"... learn now how to ..."
to
"... now learn how to ...".

Fix Wording

---

packages/gatsby-plugin-manifest/package.json
packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
packages/gatsby-plugin-sharp/package.json
packages/gatsby-remark-images-contentful/package.json
packages/gatsby-transformer-sharp/package.json
yarn.lock

Bumps sharp dep in all packages that directly depend on it:
- gatsby-plugin-manifest
- gatsby-plugin-sharp
- gatsby-remark-images-contentful
- gatsby-transformer-sharp

chore(*): bump sharp dep

---

docs/starters.yml

Submitting a starter to the Start Library:
**[repo](https://github.com/robinmetral/gatsby-starter-under-construction) · [demo](https://gatsby-starter-under-construction.netlify.com/)**
This starter is intended to be used as an "**under construction**" placeholder for a domain, but can also be used as a simple **personal site** (ex: [robinmetral.com](https://robinmetral.com/)) or **landing page**.
* All configuration is done in `gatsby-config.js`, the page can be live in minutes
* Customizable CSS background from [an expanding list](https://gatsby-starter-under-construction.netlify.com/patterns) adapted from [Lea Verou](https://leaverou.github.io/css3patterns/)'s collection
* Dynamically imports any Google Fonts chosen in `gatsby-config.js`
* Social icons from …

Submit under-construction to Starter Library

---

docs/sites.yml

[Showcased Website](https://partners.wqu.org/)

chore(showcase): Add WQU Partners to showcase

---

docs/docs/using-graphql-playground.md

Fix typo on title and intro section

Fix "GraphQL" typo

---

docs/blog/2019-01-30-flamingo-case-study/index.md

chore(blog): tweak pullquote

---

package.json
yarn.lock

Update to prettier so https://github.com/prettier/prettier/issues/5801 gets resolved

chore(gatsby): update Prettier to fix unwanted TTY behavior in CI

---

docs/blog/2018-02-09-announcing-gatsby-manor-themes-for-gatsbyjs/index.md
docs/blog/2018-07-07-the-gatsby-plugin-page-creator/index.md
docs/blog/2019-01-30-why-themes/index.md
docs/blog/2019-01-31-why-themes/index.md

feat(docs): Add 'Why Themes' blog post

---

docs/sites.yml

Add federico.giac.one to showcases.
Thanks in advance

feat(showcase): add https://federico.giac.one/

---

docs/sites.yml

Added the Station website.
Kudos to the Gatsby team for building such a great tool 🔥

feat(showcase): add https://getstation.com/

---

docs/blog/2019-01-30-flamingo-case-study/index.md

chore(blog): tweak flamingo language

---

docs/docs/gatsby-style-guide.md

On reading through the style guide for the first time, I found a few typos and things that could be improved! So here is my first Gatsby PR.
None.

docs: Updates to docs/style-guide for accuracy, etc.

---

docs/blog/2019-01-29-themes-update-child-theming-and-component-shadowing/index.md

fix(blog): wrap title containing colon in quotes

---

docs/blog/2019-01-29-themes-update-child-theming-and-component-shadowing/index.md

fix(blog): update post date (it's 2019!)

---

docs/sites.yml

Just adding Equithon, waterloo's largest social innovation hackathon, as well as my portfolio site to the showcase 😄 
_None_

feat(showcase): Add Equithon and portfolio site to showcase

---

docs/blog/2019-01-29-gatsby-eng-hiring-philosophy/index.md

feat(docs): add company blogspot

---

docs/docs/adding-images-fonts-files.md

fix(doc): Remove broken link (fixes #11297)

---

examples/hn/src/templates/story.js
packages/gatsby-cli/src/reporter/prepare-stack-trace.js

This PR removes some unneeded checks and removes an unreachable code in an `else` which is never reached.

chore: remove redundant code

---

docs/starters.yml

This PR adds Hello Friend starter for blogs and personal websites.

docs(starter): Add hello-friend starter

---

docs/docs/community.md

chore(docs): add hashnode to gatsby community section

---

package.json
yarn.lock

Upgrade `babel-eslint` to v10
N/A

chore(*): Upgrade babel-eslint

---

docs/docs/creating-prefixed-404-pages-for-different-languages.md
docs/docs/localization-i18n.md
www/src/data/sidebars/doc-links.yaml

docs(i18n): Show how to create prefixed 404 pages

---

www/src/components/layout.js
www/src/components/layout/layout-with-heading.js

The webinar has happened, so update the text of the banner message.

fix(www): Update banner message

---

docs/sites.yml

Hope you don't mind if I add myself to the site showcase now that my Gatsby site is live! 😜

docs(showcase): add MarcySutton.com to showcase

---

www/package.json

just to trigger packages reinstall

chore(www): bump gatsby dep

---

starters/README.md

wrong order of arguments  in `gatsby new`

fix(docs): update starter creation readme

---

docs/docs/headless-cms.md

feat(docs): add Sanity info to headless CMS docs

---

www/src/data/sidebars/tutorial-links.yaml

Update sidebar link to correspond with changes made in https://github.com/gatsbyjs/gatsby/pull/11556
Related to #11556

[docs] Fix broken sidebar link in tutorial page zero

---

docs/docs/creating-prefixed-404-pages-for-different-languages.md

docs: fix typo

---

starters/README.md

starter/readme: add full path to starter

---

docs/docs/create-source-plugin.md

Added the missing `add` word to fix the sentence.

docs(create-source-plugin.md): fix sentence

---

packages/gatsby-source-wordpress/README.md

This PR fixes two errors in the custom normalizers example.

Fix code example for custom normalizers

---

docs/sites.yml

Added two new websites built on Gatsby for the Showcase.

docs(showcase): added BIGBrave and KegTracker sites to showcase

---

package.json

chore(gatsby): Add jest:loki script

---

docs/starters.yml

Some tags were wrong, unnecessary or in the wrong format

fix(starters): Tags cleanup

---

docs/sites.yml

Request to add our agency's GatsbyJS website, Incremental.com.au, to the GatsbyJS showcase.
We'd love to see it featured!
None

feat(showcase): add Incremental.com.au

---

docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md

The code blocks for `package.json` files have been converted to JSON , as well as the tag. Originally tagged as JSX and written as a JavaScript object. 
Minor edit to inline `mv` command.

fix(blog): 2019-01-01 json code blocks

---

packages/gatsby/package.json
packages/gatsby/src/internal-plugins/query-runner/query-compiler.js
yarn.lock

fix(gatsby): Move to @gatsbyjs scoped version of relay-compiler

---

packages/gatsby/package.json

Update relay version once again

---

scripts/on-lint-error.js

chore: Revert "chore: lint-staged commits even on error"

---

docs/starters.yml

I've created a Shopify Gatsby starter to quickly build an e-commerce experience store with Gatsby.
It's work in progress but the shop functionality is working. 
https://github.com/AlexanderProd/gatsby-shopify-starter

docs(starters): Added Shopify Gatsby starter

---

packages/gatsby/src/db/loki/nodes-query.js

Make Loki behave like Sift for `eq: null`

fix(gatsby): Fix Loki for eq: null

---

docs/starters.yml

docs(starters): update gatsby-shopify starter tags

---

docs/starters.yml

Adding the first version of my API doc generator.

docs(starters): add api doc generator

---

packages/gatsby-source-shopify/README.md

docs(gatsby-source-shopify): Add missing `s` into `edges` string

---

packages/gatsby/src/db/loki/nodes-query.js
packages/gatsby/src/redux/run-sift.js
packages/gatsby/src/schema/__tests__/kitchen-sink.js
packages/gatsby/src/schema/__tests__/node-model.js
packages/gatsby/src/schema/__tests__/run-query.js
packages/gatsby/src/schema/infer/index.js
packages/gatsby/src/schema/node-model.js
packages/gatsby/src/schema/schema.js

This is for #11480 
* Add node model tests
* Minor fixes
* Also minor stuff for abstract types (=> comment inline)
The failing unit test in CI is because we need #11857

[schema] Add node model tests

---

docs/docs/node-interface.md

Inspired by Joshua Aggas on Twitter:
https://twitter.com/JJAggas/status/1097933371097927680

chore(docs): link to node creation in node reference

---

docs/sites.yml

feat(site-showcase): Add nodejs.dev website

---

examples/using-wordpress/src/layouts/index.js

Changing the type checking from the inexistent `location` prop to the correct `children` prop.
None that I'm aware of.

Minor fix on prop type checking

---

docs/docs/awesome-gatsby.md

Added a link to tutorial for running a Gatsby + Ghost based blog on AWS

Docs: Add tutorial for Gatsby+Ghost+AWS

---

docs/docs/headless-cms.md
docs/docs/sourcing-from-graphcms.md
docs/starters.yml

Updating information and examples for using Gatsby with GraphCMS

Docs/headless cms/sourcing from graphcms

---

docs/docs/sourcing-from-graphcms.md

I'm still getting used to the merge process at Gatsby, and I missed this in in #11655.

docs(www): fixing a linting issue in graphcms doc

---

docs/docs/headless-cms.md

docs(www): Fixed a spacing issue

---

www/src/views/starter/meta.js

Changing the icon for the "View Demo" Link on the Starter View Page, like in #11671

chore(www): change icon of view demo link for starters

---

docs/tutorial/part-eight/index.md

should be `https://github.com/gatsbyjs/gatsby-starter-hello-world`

docs(www): Correct link of `Gatsby's Hello-World Starter` repo in the tutorial doc

---

docs/docs/sourcing-from-kentico-cloud.md

Added a guide on how to source content from Kentico Cloud.

docs: Create a guide on sourcing from Kentico Cloud

---

docs/docs/headless-cms.md

Add link to new Kentico Cloud doc

chore(docs): add link to Kentico Cloud

---

docs/sites.yml

Added 'sheffielders.org' to sites.yml for Gatsby showcase.

docs(sites): Added Sheffielders 

---

docs/docs/headless-cms.md

Changed the link from a pull request to a file

Update link to sourcing from Kentico Cloud guide

---

docs/starters.yml

Add `Gatsby blog starter with AMP to PWA` in starter blog.

docs(starters): Add Gatsby blog starter with AMP to PWA

---

docs/starters.yml

docs(starters): add markdown starter

---

examples/gatsbygram/gatsby-node.js

Fix typo in comment in gatsbygram example.

chore(examples): fix typo in gatsbygram example

---

docs/contributing/gatsby-style-guide.md

querying-data-with-graphl -> querying-data-with-graphpl
N/A

chore(docs): fix typo in gatsby-style-guide

---

packages/gatsby/src/db/index.js
packages/gatsby/src/db/loki/index.js
packages/gatsby/src/redux/index.js

When persisting state, await the `saveState` promises and catch potential errors.

fix(gatsby): Catch errors when persisting state

---

packages/gatsby/src/schema/schema.js

This is for #11480 
See https://github.com/gatsbyjs/gatsby/pull/11480#discussion_r259638520

[schema] Handle multiple return values from setFieldsOnGraphQLNodeType

---

packages/gatsby/src/schema/infer/__tests__/__snapshots__/infer.js.snap
packages/gatsby/src/schema/infer/__tests__/infer.js
packages/gatsby/src/schema/infer/add-inferred-fields.js

[schema] Fix conflicting fields priority on nested type

---

docs/sites.yml

Would you please add our brand new site constanziayurashko.com, build with GatsbyJS, to the showcase compartment

docs(starters): Add constanziayurashko.com to showcased sites

---

docs/docs/static-query.md

Referenced from Jason Lengstorf's Gatsby + GraphCMS live-stream webinar.

docs(www): Add hooks to static-query docs

---

docs/docs/adding-analytics.md

The main problem with documentation on GitHub is they are not showing filename, and I'm not sure that we can easily fix that, but anyway, file content really disappoint from the first look.
- changed file content
- removed duplicate note about replacing "with your own Tracking ID"
- added reference link to gatsby-config.js documentation page
Related to #11957

fixed adding-analytics.md

---

docs/blog/2019-02-27-reactiflux-q-and-a/index.md

Add the Reactiflux Q and A blog post cc @lindaleebumblebee

chore(blog): add reactiflux q and a post

---

docs/sites.yml

Added GVD Renovations Gatsby site to showcase!

chore(site-showcase): add GVD Renovations site

---

docs/docs/awesome-gatsby.md

This PR adds a Gatsby tutorial to the list of awesome resources in the docs.

Docs: Add Gatsby blog post

---

docs/starters.yml

* added gatsby-blogger to starters
* Updated docs/starters.yml

chore(starters): add gatsby-blogger

---

docs/sites.yml

submitting site showcase for 'timehacker'

chore(showcase): add timehacker.app

---

docs/sites.yml

chore(showcase): Add styled-system.com

---

packages/gatsby-source-contentful/src/extend-node-type.js
packages/gatsby-source-contentful/src/normalize.js

PR exposes JSON AST on Contentful Rich Text Node; added a deprecation note for `nodeType`.

 feat(gatsby-source-contentful): Expose JSON AST on Contentful Rich Text Node

---

docs/sites.yml

Built on Gatsby + Prismic 🐨🇦🇺🌈
Submitted Little & Big to Site Gatsby Showcase

chore(showcase): Add littleandbig.com.au

---

docs/docs/routing.md

https://twitter.com/jhooks/status/1100992131282292736
We have a problem here :) -- our content is not properly cross-linked.
Marcy's on vacation, so anyone else should feel free to review & merge.

chore(docs): fill out parent routing stub

---

docs/sites.yml

Submitting my blog to the site showcase.

chore(showcase): add iamdeveloper.com

---

packages/gatsby/src/schema/schema.js

[schema] Make original field resolver available on info

---

packages/gatsby/src/schema/resolvers.js
packages/gatsby/src/schema/types/node-interface.js
packages/gatsby/src/schema/types/pagination.js

[schema] Make output fields non-null

---

docs/docs/environment-variables.md
packages/gatsby-plugin-catch-links/README.md
packages/gatsby-plugin-manifest/README.md
packages/gatsby-plugin-remove-trailing-slashes/README.md
packages/gatsby-transformer-excel/README.md

docs update: `behaviour` -> `behavior`
(none)

chore(docs): "behaviour" to "behavior"

---

docs/sites.yml

Thank you for a great project!
I added [catnose99.com](https://catnose99.com) to sites.yml

chore(showcase): Add catnose99.com

---

www/gatsby-config.js

Enables `anonymize: true` on https://www.gatsbyjs.org
#11891

fix(www): fix gdpr for google analytics

---

docs/contributing/gatsby-style-guide.md

Add a note about preferring US English
https://github.com/gatsbyjs/gatsby/pull/12171

fix(docs): Add a note on using American English

---

www/src/components/button.js
www/src/components/homepage/homepage-blog.js
www/src/components/homepage/homepage-ecosystem.js
www/src/components/homepage/homepage-section.js
www/src/components/masthead.js
www/src/pages/index.js

Add ga instrumentation for the main CTAs on the gatsbyjs.org

Add ga for main CTAs on gatsbyjs.org

---

examples/using-wordpress/gatsby-node.js
packages/gatsby-source-wordpress/README.md

Updates example site gatsby-node.js to match documentation.
Previously implemented in #11739.

fix(gatsby-source-wordpress): Sync sample w/docs

---

docs/sites.yml

Adding my updated portfolio written in Gatsby to the Site Showcase

chore(showcase): Adding lannonbr.com to site showcase

---

docs/sites.yml

Added my portfolio, https://bakedbird.com in sites.yml for the showcase.

chore(site-showcase): add bakedbird.com

---

docs/sites.yml

Submitting my blog to the site showcase.

chore(showcase): add gine.me

---

docs/sites.yml

Submitting my blog to the site showcase!
:)

chore(showcase): Add xfuture-blog.com

---

docs/docs/awesome-gatsby.md

adding link to course created by [Osio Labs](https://osiolabs.com/)

docs: add https://gatsbyguides.com/ to Awesome Gatsby list

---

docs/sites.yml

Updated sites.yml to include my personal portfolio into the show case!!

docs(sites): Add my gatsby portfolio to site showcase

---

docs/starters.yml

Add LivingDocs example at the bottom of starters.yml
Fixes #12205 
_not sure if submitting to Master is the best, I checked the guidelines and it seems like it is, but please let me know!_

docs(starters): Add LivingDocs magazine example to starter library for issue #12205

---

docs/sites.yml

docs(sites): Update sites.yml: add Weingut Goeschl

---

docs/sites.yml

Updated sites.yml to include my company web app into the showcase

docs(sites): add ii site to showcase

---

docs/blog/2018-08-24-gatsby-aws-hosting/index.md

remove extra space from `gatsby-cli` install in blog post.

docs(www): remove extra space

---

docs/sites.yml

I added my personal blog made with Gatsby !
Currently learning React.js / Next.js and Gatsby and it's great so far ! 🎉 
Thank's ❤️

docs(showcase): add blog.keziahmoselle.fr

---

docs/sites.yml

chore(showcase): Add hashtech.guru

---

docs/starters.yml

chore(starters): rename muhajirframe to muhajirdev (username renamed)

---

docs/docs/sourcing-from-buttercms.md

fix(docs): dangerouslySetInnerHTML tag

---

docs/sites.yml

This adds https://testingjavascript.com/ and https://howtoegghead.com to `sites.yml`.

feat(showcase): add how to egghead

---

www/src/components/diagram.js
www/src/components/masthead.js

Credit for the headline text goes to @jlengstorf

feat(www): Change .org headline/subheadline + make them larger

---

docs/sites.yml

added aquagruppen.se to docs/sites.yml

docs(sites): add aquagruppen.se

---

docs/docs/quick-start.md

fix(www): Add command to install global cli to quick-start

---

docs/sites.yml

Added my [portfolio website](https://www.kirankumarambati.me) to showcase
N/A

docs(sites): Added kirankumarambati.me to showcase

---

docs/starters.yml

Upgraded my starter to Gatsby v2 and updated accordingly. Added more tags and a description.

chore(starters): update description of gatsby-starter-ecommerce

---

docs/blog/2019-03-05-dot-org-messaging-survey/index.md

Blogpost to go out on March 5th.
Too long?
Quotes ok?

feat(blog): add org messaging survey blog post

---

packages/gatsby/src/bootstrap/index.js
packages/gatsby/src/commands/develop.js

fix(core): Only delete html/css files during prod builds

---

docs/sites.yml

Add categories to site showcase
Closes #12320

chore(showcase): add categories Josef Aidt site

---

docs/blog/2019-03-05-dot-org-messaging-survey/index.md

chore(docs): fix lint error with recent blog post

---

packages/gatsby/src/schema/__tests__/queries.js
packages/gatsby/src/schema/schema.js
packages/gatsby/src/schema/types/filter.js
packages/gatsby/src/schema/types/node-interface.js

This is for #11480 
Workaround for compatibility with v2.

[schema] Make id field on InputObjectType type String

---

docs/sites.yml

This website using gatsbyjs for frontend and using wordpress for backend( using gatsby-source-wordpress )
source code is [here](https://github.com/hesamkaveh/sansi)

docs(sites): Add hesamkaveh.com 

---

packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/schema.js

[schema] Check for type names reserved for internal use

---

packages/gatsby/src/schema/__tests__/rebuild-schema.js
packages/gatsby/src/schema/infer/__tests__/merge-types.js
packages/gatsby/src/schema/schema.js
packages/gatsby/src/schema/types/__tests__/sort-and-filter.js
packages/gatsby/src/schema/types/date.js
packages/gatsby/src/schema/types/filter.js

[schema] Allow custom scalars in input filter

---

packages/gatsby/src/schema/schema.js

Correctly camelcase connections

---

docs/sites.yml

Recently added my weblog to gatsby showcase, but have an extra title that didn't use

fix gatsby showcase file

---

examples/gatsbygram/data/posts.json

Changed avatar URLs to valid Instagram CDN URLs
Fixes #12147

fix(examples): use updated avatar URLs

---

docs/blog/2019-03-04-new-schema-customization/index.md

Copied the code example and noticed that a closing parenthesis was missing.

chore(blog): add missing parenthesis to code example

---

docs/docs/sourcing-from-graphcms.md

Remove npx mention

---

docs/docs/awesome-gatsby.md

New tutorial added that help us build a coffee shop from scratch with Gatsby

Build Gatsby coffee shop tutorial add

---

docs/starters.yml

Adding a Testing category.
Also fixed some small errors in tags (e-commerce, Antd)

feat(www): Add Testing category

---

examples/using-type-definitions/gatsby-node.js
examples/using-type-definitions/type-defs.gql
packages/gatsby/src/schema/__tests__/build-schema.js
packages/gatsby/src/schema/infer/__tests__/infer.js
packages/gatsby/src/schema/infer/add-inferred-fields.js
packages/gatsby/src/schema/infer/index.js
packages/gatsby/src/schema/schema.js
packages/gatsby/src/schema/types/date.js
packages/gatsby/src/schema/types/directives.js

This is for #11480 
* Added code frame to SDL parsing error message.
* Adjusted using-type-definitions example to also import typedefs from external .gql file.
* Consistent quotes in error messages.

[schema] Add code frame to SDL parsing error

---

docs/starters.yml

Sooo, I wanted to do a TypeScript project. Here it is :D What a wild ride...
Also added Cypress to two other starters so I updated their info

feat(www): Add Jodie starter

---

docs/sites.yml

This url isn't a Gatsby site :(

chore(www): Remove non-Gatsby site from the showcase

---

packages/gatsby/src/bootstrap/index.js

fix(gatsby): correct bootstrap emit order

---

packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

Fixes https://github.com/gatsbyjs/gatsby/issues/12446

fix(gatsby-plugin-netlify-cms): Add listener for /admin

---

packages/gatsby-source-contentful/README.md

PR updates mentions and examples of Contentful Rich Text feature.
//cc: @Khaledgarbaya

docs(gatsby-source-contentful): Update Contentful Rich Text examples

---

docs/sites.yml

Add https://oern.tv to showcase.

chore(showcase): add oern.tv to showcase

---

docs/sites.yml

Adding https://oliver-gomes.github.io/v4/ to sites.yml
My Portfolio add, *fingercrossed* for a feature 😅

chore(showcase): add https://oliver-gomes.github.io/v4/ to showcase

---

docs/contributing/submit-to-starter-library.md

Minor update. I encountered these problems when I was making my first PR. Added them in documentation to help other people.

docs(www): add note about npm run format

---

docs/docs/page-query.md

chore(docs): grammatical tweak to page query docs

---

www/src/pages/docs/index.js

chore(docs): fix grammatical error in docs index page

---

docs/sites.yml

Adds "guillaumebriday.fr" to showcase.

chore(showcase): add guillaumebriday.fr to showcase

---

packages/gatsby-plugin-sitemap/src/gatsby-node.js

docs(gatsby-plugin-sitemap): fix typo in comment

---

docs/sites.yml

Built with GatsbyJS, hosted on netlify and with contentful as an CMS.

chore(showcase): add seomonitor.com

---

www/src/components/banner.js

Switch webinar link to new webinar

chore(www): switch webinar title

---

docs/blog/2019-02-27-reactiflux-q-and-a/index.md

chore(blog): update reactiflux post

---

docs/docs/visual-testing-with-storybook.md

Update webpack config example for latest storybook (5.0.0)
Fixes #12550

fix(docs): update storybook docs to support v5

---

docs/sites.yml

Hi,
I added my portfolio [jeanregisser.com](https://jeanregisser.com) to Showcase.
Cheers,

chore(showcase): add jeanregisser.com

---

docs/sites.yml

Add axcept.io to showcase
None

chore(showcase): add axcept.io to showcase

---

packages/gatsby-transformer-remark/src/__tests__/utils.js
packages/gatsby-transformer-remark/src/extend-node-type.js
packages/gatsby-transformer-remark/src/utils.js

this tests will fail - I will push commit fixing code when unit tests finish - just to showcase the problem

move eachPromise to utils file and add (failing) tests

---

docs/sites.yml

Adds https://chaseohlson.com to site showcase.

chore(showcase): Adds chaseohlson.com

---

docs/sites.yml

Add supremekun.com to the app showcase list. 
Supremekun is an online marketplace app for streetwear fashions.

chore(showcase): add Supremekun.com 

---

docs/sites.yml

Reverts gatsbyjs/gatsby#12585
(Not a Gatsby site?)

chore(showcase): remove supremekun

---

docs/blog/2019-03-11-dot-org-prototypes/index.md

Updated for typo index.md

---

docs/blog/2019-03-11-dot-org-prototypes/index.md

Fixing wrong merge from #12602 🤦‍♂️ 🤦‍♂️ 🤦‍♂️

fix(blog): Typo in /blog/2019-03-11-dot-org-prototypes

---

docs/sites.yml

Adds https://zslabs.com and https://www.gremlin.com to site showcase. Thanks! 🚀

chore(showcase): Add zslabs.com and gremlin.com

---

docs/sites.yml

Running the site showcase through my new [validator](https://github.com/lannonbr/gatsby-site-showcase-validator), I found a few sites which are no longer Gatsby sites.

chore(showcase): Cleaning up Site Showcase

---

docs/blog/2019-03-15-design-code-blog-post/index.md

chore(blog): fix typo
