examples/gatsbygram/gatsby-node.js
examples/hn/gatsby-node.js
examples/using-drupal/gatsby-node.js
packages/gatsby/lib/utils/api-runner-node.js
www/gatsby-node.js

Per #886 this is another source of sites getting built successfully when they should have died.

Die when plugins return an error

---

README.md

Added my website to list of sites built with Gatsby.

Added Adarsh Pyarelal's personal website

---

README.md

Add yisela.com to the list of sites built with Gatsby.

Add yisela.com

---

docs/docs/api-proxy.md
packages/gatsby/src/joi-schemas/joi.js
packages/gatsby/src/utils/develop.js
www/src/pages/docs/doc-links.yaml

Adds configuration for proxying local API requests to `gatsby-config.js`.

[1.0] Api proxy

---

packages/gatsby-transformer-react-docgen/src/Doclets.js
packages/gatsby-transformer-react-docgen/src/extend-node-type.js
packages/gatsby-transformer-react-docgen/src/on-node-create.js
packages/gatsby-transformer-react-docgen/src/parse.js

May be more here to come, just the last few little things i’m needing as I build out the react-bootstrap docs.

Pass node into react-docgen handlers

---

examples/using-postcss-sass/package.json

Connects to #1015
Change-Type: chore

1.0 bump gatsby-plugin-postcss-sass in using-postcss-sass example

---

packages/gatsby-link/src/index.js

Addresses https://github.com/gatsbyjs/gatsby/issues/1018

[1.0] Prevents swallowing onClick in gatsby-link

---

README.md

The link for the Lumen demo was broken.

Lumen link updated

---

examples/client-only-paths/src/html.js
examples/gatsbygram/src/html.js
examples/hn/src/html.js
examples/image-processing/src/html.js
examples/no-plugins/src/html.js
examples/no-trailing-slashes/src/html.js
examples/redux/src/html.js
examples/sitemap/src/html.js
examples/using-drupal/src/html.js
examples/using-glamor/src/html.js
examples/using-postcss-sass/src/html.js
examples/using-styled-components/src/html.js

replacing react.createClass with ES6 classes in exmaples html.js
adding PropTypes

[1.0] replacing react.createClass with ES6 classes in exmaples html.js

---

www/src/components/sidebar-body.js
www/src/components/tutorial-sidebar.js
www/src/layouts/index.js
www/src/utils/typography.js

[1.0] Moar ui stuff

---

README.md

Added arun.is (Arun Venkatesan's site) to featured Gatsby sites based on Kyle's suggestion: https://twitter.com/kylemathews/status/875382218599800832

Added arun.is to Site

---

www/src/layouts/index.js

… so simple that I feel I missed something ;)

[1.0] www: Make the header fixed for tablets and up

---

examples/no-plugins/gatsby-config.js
examples/using-postcss-sass/package.json
packages/gatsby-plugin-postcss-sass/src/gatsby-node.js
packages/gatsby/package.json
packages/gatsby/src/cache-dir/develop-static-entry.js
packages/gatsby/src/utils/develop-html.js
packages/gatsby/src/utils/develop.js
packages/gatsby/src/utils/webpack.config.js

Improve develop-html stage

---

examples/using-remark/src/templates/template-tag-page.js

[1.0][using-remark] Remove console.log

---

docs/docs/creating-and-modifying-pages.md
packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
packages/gatsby/src/redux/__tests__/__snapshots__/pages.js.snap
packages/gatsby/src/redux/reducers/pages.js

[1.0] Link pages to their plugin creators for easier understanding/debugging fixes #1281

---

examples/using-sass/README.md
examples/using-sass/gatsby-config.js
examples/using-sass/package.json
examples/using-sass/src/html.js
examples/using-sass/src/layouts/index.js
examples/using-sass/src/pages/index.js
examples/using-sass/src/styles/_variables.scss
examples/using-sass/src/styles/main.scss

Well, I'm not actually seeing the issue mentioned in #1278 in this example, but here is a basic example.

Add an example for using the sass plugin

---

examples/image-processing/package.json

[1.0][image-processing] Fix author

---

packages/gatsby-remark-responsive-iframe/README.md

- adds example usage
- updates plugin name

update gatsby-remark-responsive-iframe readme

---

docs/docs/migrating-from-v0-to-v1.md
examples/feed/gatsby-node.js
examples/sitemap/gatsby-node.js
examples/using-remark/gatsby-node.js
www/gatsby-node.js

Forgot to do this earlier with #1325

Fix createNodeField usages in code

---

README.md

I ran into some confusion when trying to deploy to Github Pages last night. Hopefully this makes it clearer

Update README to make it clearer about deploying to gh pages

---

README.md

This PR adds my new Gatsby starter to the list in the README.
Master currently points to v0 version of it, but I have already begun working on migrating it to Gatsby v1.
I hope I can gather some more feedback about the visual design decisions I have made to make the v1 release as full as possible.
PS. v1 featurelist is really impressive. Kudos for your work!

Adds Material Blog starter to the list of starters.

---

CHANGELOG.md

Update CHANGELOG to reflect new package name

---

www/src/gatsby-negative.svg
www/src/pages/index.js

Fixed the logo color along the way, but not the favicon stuffs yet.

Futura for homepage blocks

---

packages/gatsby-transformer-sharp/README.md

Hopefully this helps someone find their way more easily :)

Add link to live demo

---

packages/gatsby-transformer-react-docgen/package.json

Fix dependencies

---

docs/docs/migrating-from-v0-to-v1.md

Fix "gastsby" to "gatsby" on line 34

---

packages/gatsby-source-wordpress/README.md

Update README.md for source-wp

---

examples/using-typescript/package.json
examples/using-typescript/src/declarations.d.ts
examples/using-typescript/src/pages/404.tsx
examples/using-typescript/src/pages/index.tsx

Just some fixes of typescript example types/lint

Improve typescript example

---

packages/gatsby-remark-images/README.md
packages/gatsby-remark-images/src/index.js

Feature 1:
- Now alt tags will be automatically generated from the file name if an alt tag is not present.
Feature 2:
- Images being links are now optional

Gatsby remark images default alt tags and optional linking

---

docs/docs/add-custom-webpack-config.md

figured to submit PR to fix broken links as I go through docs 😄

Updates add-custom-webpack-config.md to fix broken links

---

packages/gatsby/src/utils/develop.js

This [PR](https://github.com/gatsbyjs/gatsby/pull/1478) had a small typo in it which caused gatsby-dev-cli to not work for me 😅

Fix reference to program.directory

---

v0-README.md

I'd love to add this to the v0 docs since my website was tweeted on the official Gatsby twitter! It utilizes Gatsby and WebGL together 😊

Add effulgence.io website

---

docs/docs/building-with-components.md

double '... use use ...' word in the sentence

double '... use use ...' word in the sentence

---

www/gatsby-config.js
www/package.json

Make the docs more SEO-friendly and guarantee that a core plugin builds.

Add sitemap plugin to www

---

packages/gatsby-plugin-feed/src/gatsby-ssr.js

I forgot that each SSR component needed a unique key.

Add index, since we now support multiple feeds

---

docs/docs/gatsby-starters.md

add glitch-gatsby-starter-blog

---

packages/gatsby-link/src/index.js
packages/gatsby-plugin-glamor/package.json
packages/gatsby-plugin-glamor/src/gatsby-browser.js
packages/gatsby-plugin-glamor/src/gatsby-node.js
packages/gatsby-plugin-glamor/src/gatsby-ssr.js
packages/gatsby/src/cache-dir/default-html.js
packages/gatsby/src/cache-dir/root.js

This bug was introduced by (#1550)

Remove the slash between the pathPrefix and pathname when navigating

---

docs/docs/plugins.md

Fix for: [issue 1602]( https://github.com/gatsbyjs/gatsby/issues/1602)

Fix for issues/1602

---

examples/using-wordpress/README.md

https://github.com/gatsbyjs/gatsby/issues/1419

Create Wordpress example site README.md

---

packages/gatsby-link/src/__tests__/index.js
packages/gatsby-plugin-coffeescript/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-coffeescript/src/__tests__/gatsby-node.js
packages/gatsby-plugin-coffeescript/src/__tests__/index.js
packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-plugin-sharp/src/__tests__/index.js
packages/gatsby-plugin-sharp/src/index.js
packages/gatsby-plugin-typescript/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
packages/gatsby-plugin-typescript/src/__tests__/index.js
packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-autolink-headers/src/__tests__/index.js
packages/gatsby-remark-autolink-headers/src/index.js
packages/gatsby-remark-copy-linked-files/src/__tests__/index.js
packages/gatsby-remark-responsive-iframe/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-responsive-iframe/src/__tests__/index.js
packages/gatsby-remark-responsive-iframe/src/index.js
packages/gatsby-remark-smartypants/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-smartypants/src/__tests__/index.js
packages/gatsby-remark-smartypants/src/index.js
packages/gatsby-source-filesystem/src/__tests__/gatsby-node.js
packages/gatsby-source-filesystem/src/__tests__/index.js

Added a bunch of tests to serve as a baseline for expected functionality.
Let me know if you'd like any further detail!

add a bunch of tests for various plugins

---

packages/gatsby-source-wordpress/src/gatsby-node.js

https://github.com/gatsbyjs/gatsby/issues/1612

Update to include use case of WP-API-MENUS items

---

packages/gatsby-source-wordpress/src/gatsby-node.js

https://github.com/gatsbyjs/gatsby/issues/1612

Fixing createNode doesn't exists

---

README.md

Finally made a personal blog for myself :tada: 
Thanks for providing an awesome static generator for that! :smile:

Adds vagr9k.me to the showcase.

---

packages/gatsby-transformer-yaml/package.json
packages/gatsby-transformer-yaml/src/gatsby-node.js

Add missing deps

---

docs/tutorial/part-two/index.md

Not sure if it should be the em dash or the 3/4 normals dashes.

fix dash type in tutorial part two

---

docs/tutorial/part-three/index.md

Currently enjoying the tutorial and noticed one small issue to fix!

Fix missing space

---

docs/tutorial/part-three/index.md

Another one, this didn't work so I copied the config from Part Two which works for me.

Fix gatsby-config.js example

---

packages/gatsby/src/internal-plugins/query-runner/gatsby-node.js
packages/gatsby/src/redux/actions.js

This fixes windows path issues that cropped up in #1503 on commit 750d2731492c1e50b6207f1df064291e2f82f8b6.

fix windows path issues *sigh*

---

www/gatsby-config.js
www/src/html.js
www/src/utils/typography.js

… and remove now obsolete things.
Stumbled upon when noticing that hot reloading typography in dev didn't work.

[www] Fix Typography.js plugin options

---

packages/gatsby-transformer-json/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-transformer-json/src/__tests__/gatsby-node.js

This PR fixes the gatsby-transform-json tests, as we discovered the the bug when discussing this [PR](https://github.com/gatsbyjs/gatsby/pull/1465)

test(transform-json): Fix tests

---

packages/gatsby-source-wordpress/README.md

Updated the readme to reflect the actual state of the plugin

Update gatsby-source-wordpress README.md

---

docs/docs/deploy-gatsby.md

Added some s3 and cloudfront info

Update deploy-gatsby.md 

---

packages/gatsby/package.json
packages/gatsby/src/utils/webpack.config.js

Also updated to the new argument format.

Upgrade static-site-generator-webpack-plugin to latest version.

---

README.md

Thank you for all the great work. My site is finally migrated to Gatsby! :)

Add kostasbariotis.com to showcase

---

appveyor.yml

Working on trying to cache some things, and do builds of many examples on publish

Appveyor Performance Improvements

---

packages/gatsby-transformer-remark/README.md

I struggled and googled for answers until I asked about it in the community. Would be helpful for others.

Added link to blog post for more detail

---

docs/docs/plugins.md

One of the most popular web analytics solutions besides Google Analytics

Added yandex-metrika plugin to community plugins

---

docs/docs/plugins.md

- Integrates inversify for dependency injection
- Great for TS projects
- Also helps with making it easy to set up and bind redux to the root gatsby component

Add protoculture as a community plugin

---

README.md

Add website

---

docs/docs/create-source-plugin.md
docs/docs/node-interface.md
examples/using-mongodb/gatsby-config.js
packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
packages/gatsby-source-contentful/src/normalize.js
packages/gatsby-source-mongodb/README.md
packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js
packages/gatsby-transformer-documentationjs/src/gatsby-node.js
packages/gatsby-transformer-react-docgen/src/__tests__/on-node-create.js
packages/gatsby-transformer-react-docgen/src/on-node-create.js
packages/gatsby-transformer-remark/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-transformer-remark/src/__tests__/gatsby-node.js
packages/gatsby-transformer-remark/src/on-node-create.js
packages/gatsby/src/redux/actions.js

This broke the Remark transformer as it doesn't process markdown File nodes without this shift.

mime-db switched to text/markdown from text/x-markdown for the mimeType of markdown

---

README.md

My website is automatically deployed with Travis and Rclone to S3 and then served with Cloudflare for CDN and SSL.

Add knpw.rs to showcase.

---

docs/docs/plugins.md

Hi,
Really enjoying using Gatsby!
I'm currently creating a careers page for our company and wanted to share the source plugin for [Workable](https://www.workable.com/) that I made.
Feel free to take a look at the repo and point out any mistakes I may have made.
Thank you! :)

Add gatsby-source-workable

---

docs/docs/plugins.md
packages/gatsby/src/joi-schemas/joi.js
packages/gatsby/src/redux/actions.js

Improve source docs + allow null in parent field on nodes

---

packages/gatsby/src/utils/build.js

Realized this never got updated from Gatsby v0. We don't create a bundle.js anymore :-D
Any thoughts on the new wording?

Update build message for v1

---

appveyor.yml

should be handled during bootstrap now

remove explicit build step

---

packages/gatsby/cache-dir/component-renderer.js
www/src/components/blog-post-preview-item.js
www/src/components/masthead-bg.js
www/src/components/masthead.js
www/src/components/navigation-mobile.js
www/src/components/navigation.js
www/src/layouts/index.js
www/src/pages/docs/index.js
www/src/templates/template-blog-post.js
www/src/utils/typography.js

Pardon the messy diff, ran format.
I was using or instead of and 🤦‍♂️

Fix shouldComponentUpdate for component-renderer

---

README.md

Sorry guys I forgot to add the source code in the first PR.
Thank you for the awesome Gatsby project.

Add source code for angeloocana.com

---

docs/docs/plugins.md

Add Community Plugins:
- gatsby-plugin-i18n-tags
- gatsby-plugin-i18n-readnext

Add community plugins i18n-tags and i18n-readnext

---

docs/tutorial/part-four/index.md

typo in tutorial docs fixed

---

packages/gatsby/src/utils/develop.js

Not sure what is going on or how this didn't get updated before

Fix missing reference

---

docs/docs/plugins.md

- Add gatsby-remark-emoji to community plugin list
- Order community plugins by name

[docs] Add remark-emoji to community plugins and re-order by name

---

docs/docs/plugins.md

Adding community plugin `gatsby-plugin-copy`

Add gatsby-plugin-copy to list of community plugins

---

README.md

I finished my site and the performance rocks thanks to Gatsby👍 
If it's ok, I would love to share my site with source codes for others. 😃

added songwang.io to showcase

---

README.md

Adding [Digital Psychology](http://digitalpsychology.io) to the showcase + source code 🤓
Thank you for creating such a great project!

Add DigitalPsychology.io to showcase

---

README.md

Hello! I'd love to add mParticle's doc site to the Gatsby showcase. Thank you.

Add mParticle's doc site to showcase

---

docs/blog/2017-09-13-why-is-gatsby-so-fast/index.md

Fix blog typos

---

packages/gatsby-source-contentful/src/gatsby-node.js
yarn.lock

This fixes issue #2021 and removes a TODO from the code.

Contentful sources now have individual sync tokens

---

README.md

add my blog starter to show case.

add magicly blog to show case

---

packages/gatsby-transformer-json/README.md

for people who take examples literally, like me. thanks!

Updated example formatting

---

README.md

[Sourcegraph's website](https://about.sourcegraph.com) is built using GatsbyJS - would love to share it in the showcase!

Add Sourcegraph website to showcase

---

docs/docs/creating-and-modifying-pages.md

Made a tiny modification to the README. The `promise` within the `async` function is not required.

Promise within async function not required

---

README.md

just hope people will know about gatsby, this open source awesome. Thanks who founded this. Many thanks

add Phu Quoc Works to the showcase

---

README.md

I've had an extremely smooth experience so far. Thanks for creating Gatsby! :smile:

Add Kabir Goel's website to showcase

---

docs/docs/adding-images-fonts-files.md
docs/docs/environment-variables.md
docs/tutorial/part-four/index.md
docs/tutorial/part-one/index.md
docs/tutorial/part-two/index.md
examples/using-contentful/src/templates/category.js
examples/using-remark/src/pages/2017-01-02---responsive-images-and-iframes/index.md
www/src/components/blog-post-preview-item.js
www/src/components/diagram.js
www/src/components/navigation.js

A couple of small fixes to improve the overall accessibility, both in code samples and on the landing page. 
My main focus was fixing the tutorial so that all images would have ALT text. I find it important to spread good practices especially in the documentation.

Add basic accessibility fixes

---

docs/blog/2017-09-26-embracing-graphql/index.md

Copy edits for grammar & punctuation

Stylistic edits to Tim's blog post

---

README.md

It was great learning some react & js with gatsby. Thanks for creating this powerful tool!

add Gabriel Adorf's Portfolio to showcase

---

packages/gatsby/cache-dir/production-app.js

Make redirects much faster in production

---

README.md

This PR adds an amazing site by MozillaDevs about CSS Grid Playground. 💯

ADD: Showcase —CSS Grid Playground by MozillaDev

---

packages/gatsby-source-wordpress/src/__tests__/normalize.js
packages/gatsby-source-wordpress/src/gatsby-node.js
packages/gatsby-source-wordpress/src/normalize.js

Excluding entities without ID should fix https://github.com/gatsbyjs/gatsby/issues/2260

[gatsby-source-wordpress] Gatsby Develop exits with a TypeError fix

---

README.md

Fix typo on Gatsby word on README.md file.

docs(readme_typo)

---

docs/docs/plugins.md

it's a WIP but figured i'd list it anyway in case someone else needed it

added community plugin 'source-google-sheets'

---

packages/gatsby-source-wordpress/src/fetch.js

Pass _auth object to getWPCOMAccessToken so _auth is defined

---

packages/gatsby-link/index.d.ts

fix: add missing def for navigateTo in gatsby-link

---

docs/docs/deploy-gatsby.md

Docs: deploy - typo

---

README.md

Cheers for allowing me to create a new portfolio site with a blog using the Wordpress API and React. Really enjoyed working with Gatsby!
Also fixed a missing space with previous Mozilla showcase link.

Add David James' Website to Showcase

---

docs/docs/creating-and-modifying-pages.md

Let users know it is possible to choose a custom layout in `createPage`, and not only via `onCreatePage`.

showing that a custom layout can be choosen in `createPage`

---

packages/gatsby-image/README.md

Fix mistake in example code for gatsby-image

---

packages/gatsby-cli/README.md

Looks like some of the full stops are missing

Update README.md of gatsby-cli

---

packages/gatsby-image/src/index.js

Removed the console log introduced in https://github.com/gatsbyjs/gatsby/commit/76cda50d75dd9ea8950b74b8ebc97bc0380d2250.

Removed the console log in the gatsby-image package

---

README.md

I created my website with gatsbyjs; let's add another example of cool things you can create with gatsbyjs.

Add personal blog to showcase

---

docs/tutorial/part-four/index.md

Example code gives React warning about unique "key" prop.

Fix tutorial-part-four my-files.js example code

---

docs/docs/plugins.md

The plugin will allow you to use [klipse](https://github.com/viebel/klipse) from markdown. It will
inject the needed scripts & styles.

Add plugin: gatsby-plugin-klipse

---

packages/gatsby-transformer-json/README.md
packages/gatsby-transformer-yaml/README.md

I didn't know how to make it work before I found #2259

Update readme so newbies understand how to make transformers work

---

examples/redux/.babelrc

Revert "Create .babelrc"

---

packages/gatsby-image/README.md
packages/gatsby-image/src/index.js
packages/gatsby/src/schema/__tests__/infer-graphql-input-type-from-fields-test.js
packages/gatsby/src/schema/infer-graphql-input-fields-from-fields.js

Adds option to add className to gatsby-image outer wrapper.

Add outerWrapperClassName prop to gatsby-image.

---

packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
packages/gatsby/src/utils/babel-config.js

No need for a possessive apostrophe with `it` :)

Grammar pedantry

---

packages/gatsby/package.json

Fix watch script in gatsby packages fixes #2451

---

packages/gatsby-plugin-google-analytics/README.md
packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js

Might be helpful for users from Germany (or other countries with such a data privacy policy).
Yeah, first feature PR!

[gatsby-plugin-google-analytics] Added "_anonymizeIP" function

---

docs/docs/gatsby-starters.md

This starter adds localization to **gatsby-starter-default**

Add gatsby-starter-default-i18n to docs

---

packages/gatsby-remark-copy-linked-files/README.md
packages/gatsby-remark-copy-linked-files/package.json

This fixes 2 issues I just ran into this evening.
See my [comments](https://github.com/gatsbyjs/gatsby/pull/1571#pullrequestreview-69744793) on PR #1571

Fix a missing dependency

---

docs/blog/author.yaml

Adding details for Sam as an author.

Added Samuel Goudie to authors for blog article.

---

docs/blog/2017-10-17-building-i18n-with-gatsby/index.md

Including edits from draft round. Added front-matter too.

Added article for 'Building i18n with Gatsby'

---

README.md

Thank you for the great work you're doing - Gatsby is amazing. I enjoyed building this site with it!

Add Design Systems Weekly to README

---

docs/docs/coming-from-react-to-gatsby

A suggestion from an interviewee

Example Stub Article

---

docs/docs/gatsby-style-guide.md

? marks might have made the links non-functional. Also I fixed a typo

edited some header links that didn't work

---

examples/image-processing/src/pages/index.js

[examples/image-processing] Fix anchor links

---

www/src/pages/features.js

As reported/suggested by @tjgilpin in https://github.com/gatsbyjs/gatsby/pull/2443#issuecomment-337716552

[www] Features: Fix typo

---

www/package.json
www/src/components/markdown-page-footer.js
www/src/templates/template-docs-markdown.js
www/src/templates/template-docs-packages.js

A little experiment. Will add a form for written feedback tomorrow.

[www] Add thumbs up/down to docs pages

---

packages/gatsby-remark-copy-linked-files/src/index.js
packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-images/src/__tests__/index.js
packages/gatsby-remark-images/src/index.js
packages/gatsby-remark-responsive-iframe/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-responsive-iframe/src/index.js
packages/gatsby-transformer-sharp/src/extend-node-type.js

Fix
https://github.com/gatsbyjs/gatsby/issues/2536
https://github.com/gatsbyjs/gatsby/issues/2493

fix for cheerio v1

---

packages/gatsby/src/schema/infer-graphql-input-fields.js

[gatsby] Meaningful GraphQL Invariant Object Errors

---

.github/stale.yml

@KyleAMathews You'll need to install the stalebot app through here. https://github.com/apps/stale
The bot runs every hour. I tested on my own repos first, within 10 minutes it ran and marked all existing stale repos. If those marked as stale do not see activity for 15 days they will then be closed.

Stalebot config.

---

docs/blog/2017-10-16-making-website-building-fun/index.md

Noticed two small typos in the (otherwise fantastic!) essay on `gatsby-image` & the importance of finding the right layer of abstraction when approaching a problem.
Unrelated to aforementioned typos — I was actually reminded of @chenglou's [excellent talk](https://www.youtube.com/watch?v=mVVNJKv9esE) "On the Spectrum of Abstraction" from last year's react-europe conference. Love it when engineers take the time to [stop and really consider](https://www.youtube.com/watch?v=f84n5oFoZBc) _how_ we approach our craft, as a fundamentally creative endeavor.
(For that matter, Fred Brooks was touching on these themes way back in 1986 with [_No Silver Bullet_](https://en.wikipedia.org/wiki/No_Silver_Bullet) — I'd argue that React / Gatsby et al. provide a similar reduction in "accidental complexity" …

[blog] Fix typos in "Making website building fun" post.

---

docs/docs/gatsby-starters.md

Hi,
I added my gatsby-starter to the gatsbyjs homepage :).
Kind regards

Added starter to the gatsbyjs homepage

---

README.md

Thanks Kyle! I love gatsby's plugins, very handy. Used them in my site and happy to help others with it

Update README.md with new page

---

www/src/components/sidebar-body.js

[www] Correct sidebar item active state dot position

---

docs/docs/gatsby-starters.md

Fixed gatsby-typescript-starter demo link.

Fixed demo link

---

www/src/pages/docs/doc-links.yaml

Added 6 new stubs in the guide section

---

packages/gatsby-source-wordpress/src/normalize.js

Resolves https://github.com/gatsbyjs/gatsby/issues/2564

Skip trying to link to wordpress media if there is no media

---

docs/tutorial/part-one/index.md

Improved double quote consistency in doc

---

docs/tutorial/part-two/index.md

Complete double quote usage where possible

---

docs/tutorial/part-three/index.md

"Double quotes everywhere" - unknown

Complete double quote usage

---

www/src/pages/docs/doc-links.yaml

The stub articles aren't showing up in gatsbyjs.org

---

docs/docs/environment-variables.md

Here you go! Let me know if there are any changes you'd like me to make to what I have :).

Include info about environment vars for gatsby config

---

packages/gatsby-source-wordpress/src/normalize.js

Hello!
Just adding the two Gatsby plugins I created for integrating Stripe Checkout or Stripe Elements into a Gatsby project.
Let me know if there's anything I should change about where I put them in the docs :).
Thanks!

Add Stripe plugins to docs page

---

packages/gatsby/src/redux/actions.js

Add pathPrefix in createRedirect

---

docs/docs/gatsby-starters.md

Added gatsby-starter-portfolio-emma to gatsby-starters

Added gatsby-starter-portfolio-emma

---

README.md

Added GraphCMS's new website to the Showcase

Add a site to Showcase

---

docs/tutorial/part-one/index.md

Update to Tutorial Part One

---

packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js

Hello, this a little change to avoid twice send page view. 
You already send the page view in router update.
Thank you!

Twice page view

---

packages/gatsby-remark-copy-linked-files/README.md

Designate that file to be copied is local

Update readme description to be less ambiguous

---

packages/gatsby-plugin-sharp/src/index.js
packages/gatsby/src/commands/build-html.js
packages/gatsby/src/internal-plugins/query-runner/query-compiler.js
packages/gatsby/src/redux/actions.js

Add RelayParser to convertASTDocuments call

---

packages/gatsby/package.json
packages/gatsby/src/commands/serve.js
packages/gatsby/src/redux/index.js
packages/gatsby/src/utils/globals.js
www/package.json
yarn.lock

Update serve command

---

package.json
packages/gatsby/package.json
packages/gatsby/src/redux/index.js
yarn.lock

The copyfiles package happened to be [removed](https://github.com/gatsbyjs/gatsby/commit/bff0cd377359ad1432a1da042349793096cb8d37?diff=unified#diff-d42476695f98af8f85d595ac39bc0653L35).

attempt to fix ci errors

---

docs/docs/plugins.md

Hi there,
I created a Github source plugin that I'd like to share with the community.

Adding Github Source Plugin

---

README.md

Thank you Kyle! I use Gatsby to rebuild my blog. The source code is also released so that other developer may find this is useful as a blog system.

Update README.md with Calpa's Blog

---

packages/gatsby-image/README.md
packages/gatsby-image/src/index.js

Add onLoad prop to gatsby-image

---

docs/docs/gatsby-starters.md

This adds gatsby-starter-bootstrap-netlify to starters in docs

add gatsby-starter-bootstrap-netlify to starters

---

packages/gatsby/src/utils/webpack.config.js

…with the specified host.
https://github.com/gatsbyjs/gatsby/issues/2837

replacing hardcoded localhost value in develop command's logging

---

examples/using-react-url-query/.eslintrc
examples/using-react-url-query/.gitignore
examples/using-react-url-query/README.md
examples/using-react-url-query/gatsby-browser.js
examples/using-react-url-query/gatsby-config.js
examples/using-react-url-query/gatsby-ssr.js
examples/using-react-url-query/package.json
examples/using-react-url-query/src/components/NumberInput.js
examples/using-react-url-query/src/components/SearchInput.js
examples/using-react-url-query/src/pages/index.js

Shows how to bind URL query params using [react-url-query](https://github.com/pbeshai/react-url-query).

Add example: using-react-url-query

---

README.md

Add the API Platform website to the showcase

---

README.md

Website: https://bottender.js.org/
Source: https://github.com/bottenderjs/bottenderjs.github.io

Added Bottender docs to the showcase

---

packages/gatsby-link/index.d.ts

gatsby-link add withPrefix to typescript #2887

---

packages/gatsby/package.json
packages/gatsby/src/joi-schemas/joi.js
yarn.lock

This error confused several people recently who tried using an empty
string

Add custom error for node.parent validation

---

packages/gatsby/src/commands/develop.js

Don't return early early when detecting the port

---

docs/docs/deploy-gatsby.md

Added more explanation to docs to help with easy deployment.

Failed to get remote.origin.url Error

---

docs/docs/gatsby-starters.md

I added gatsby-styled-blog-starter  to the list of starters on docs page

added  gatsby-styled-blog-starter 

---

docs/docs/gatsby-starters.md

Adding another starter-template to the docs.

Add gatsby-starter-docs

---

README.md

npm downloads

---

docs/docs/plugins.md

Relevant to #332, this PR includes a link to a plugin that facilitates local site searching. If there is anything else I need to do with this PR, additional information, documentation, etc. please let me know.

(docs) Include link to search plugin

---

docs/docs/gatsby-starters.md

Add link to `gatsby-starter-deck`, a starter to create presentations using Gatsby.
GitHub: https://github.com/fabe/gatsby-starter-deck
Demo: https://gatsby-deck.netlify.com

Add `gatsby-starter-deck`.

---

packages/gatsby/src/commands/develop.js

Missed this one in last PR.
Fix for #1655

[develop] Use req.path to check for public files

---

packages/gatsby/src/internal-plugins/component-page-creator/__tests__/gatsby-node.js
packages/gatsby/src/internal-plugins/component-page-creator/validate-path.js

Prevent type declaration files to generate pages

---

examples/using-redux/README.md

I've noticed this question come up a couple of times, so added a short note to the redux example's README.

Add a brief explanation about setting up redux with Gatsby

---

docs/docs/create-source-plugin.md

fixed typo in text

---

docs/docs/deploy-gatsby.md

It would probably help with https://github.com/gatsbyjs/gatsby/issues/3107 (I saw other people encountered that issue)

Make it clearer Gatsby isn't minifying HTML

---

docs/docs/awesome-gatsby.md
www/src/pages/docs/doc-links.yaml

Please add additional resources!

Create a 'Awesome Gatsby' page

---

packages/gatsby-plugin-netlify/README.md

Documenting redirects

---

packages/gatsby-transformer-yaml/README.md

This addresses #3081.
Affects `README.md` in `gatsby-transformer-yaml`
Short summary:
- Updates docs to reflect current state of plugin
- Changes the wording of several parts to make it more readable

#3081 Docs readme gatsby transformer yaml

---

www/src/components/used-by.js

Those logos look clickable! This PR makes them so. Obviously slightly selfish since we're one of those links, but they do look clickable. Feel free to close 😜  😇

Adds links to logos in used-by section

---

README.md

Adds [planninglabs.nyc](https://planninglabs.nyc) to the showcase list

Add showcase project

---

.yarnrc
docs/docs/creating-and-modifying-pages.md
packages/gatsby-plugin-remove-trailing-slashes/gatsby-node.js

Per discussion in https://github.com/gatsbyjs/gatsby/pull/3223

[gatsby-plugin-remove-trailing-slashes] - update docs

---

docs/docs/how-gatsby-works-with-github-pages.md

Typo on docs/docs/how-gatsby-works-with-github-pages.md

---

docs/tutorial/part-four/index.md

Just another WordPress dev out trying new things. Noticed the incorrect usage of `WordPress` and felt compelled to create a PR. Thanks for your consideration. Loving Gatsby!

capital P dangit

---

docs/docs/how-gatsby-works-with-github-pages.md

Github -> GitHub

---

README.md

Adding [fabianschultz.com](https://fabianschultz.com) to the showcase ✌️

Add site to showcase

---

README.md

caddy smells like trees added to readme

---

README.md

Adding my wife's photography portfolio to the showcase.  📷 [knw.io](https://www.knw.io)

Add KNW Photography to the website showcase

---

README.md

as suggested in https://twitter.com/gatsbyjs/status/948224957338849281.

Add manu.ninja to showcase

---

docs/tutorial/part-three/index.md

Wondering if it makes sense to always use periods or colons before code examples. Probably consistency matters more than anything. Happy to go through and change everything according to your preference @kylemathews.

A few smaller changes

---

docs/docs/gatsby-starters.md

gatsby-starter-ceevee a single page portfolio

Add new gatsby-starter project/template/theme

---

docs/tutorial/part-one/index.md

I was running through the tutorial, but lorempixel.com was giving me some issues. Unsplash.com has great photos and their api improved load time significantly for me.

Changed Random Photo Source

---

docs/docs/plugins.md

[www] Add gatsby-plugin-canonical-urls to docs/plugins

---

README.md

Add k-create site + source

---

docs/docs/gatsby-starters.md

For people who 🚀 ship a lot. Nothing fancy.

A simple Gatsby starter

---

README.md

this PR adds chocolate-free.com website to the list

Add chocolatefree.com website

---

docs/docs/gatsby-starters.md

My bad, I did not carefully see that an indentation rule is being followed. I have fixed it now.

Edit file, solves styling with correct indentation

---

packages/gatsby/src/schema/infer-graphql-type.js

This fixes #2886 - author of issue described the problem, so check issue for more context

Fix filtering on date type fields in graphql query

---

docs/docs/plugins.md

Also created an example site for the plugin 👍 
https://confident-perlman-063f75.netlify.com/

Add gatsby-source-behance to plugins list

---

docs/docs/building-with-components.md

Fix typo in building with components section

---

docs/docs/gatsby-starters.md

Add Strata starter to the list.

Add Strata starter

---

docs/tutorial/part-one/index.md

A few typo corrections and clarified wording. There are more big changes to address later.

Easy edits based off of observing Eden go thru tutorials

---

packages/gatsby-remark-katex/package.json

Update katex package to 0.8.3

---

www/src/templates/template-blog-post.js

[www] Fix <link rel=„author“> href

---

docs/docs/querying-with-graphql.md

I also think it could be cool to explain just a few use cases that answer this question: "Why is GraphQL so cool?"
I also expected to see code examples for image stuff. Also, a random thing about colons that I learned last year is this:
a full sentence must precede the colon :)

Some minor edits

---

docs/docs/plugins.md

Hi, I've written a little plugin for Directus CMS and thought I'd stick it in here.
Thanks

Added gatsby-source-directus to the plugins page

---

docs/docs/plugins.md

Updated the docs with a plugin we built for adding Bugherd integration 😄

Added `gatsby-plugin-bugherd` to community plugins

---

docs/blog/2018-01-18-how-boston-gov-used-gatsby-to-be-selected-as-an-amazon-hq2-candidate-city/index.md
docs/docs/building-apps-with-gatsby.md
docs/docs/gatsby-starters.md
docs/docs/querying-with-graphql.md
packages/gatsby-source-filesystem/src/create-remote-file-node.js
packages/gatsby-source-wordpress/src/gatsby-node.js
packages/gatsby-source-wordpress/src/normalize.js
www/src/html.js

So I got the Basic Auth working... these curly brackets around headers were not so nice - did not know what was wrong for hours 💩

WordPress Media Download Basic Auth Fix

---

package.json
packages/gatsby/src/commands/develop.js
yarn.lock

eslint was throwing before linting due to a bug they've since patched
This gets it running again and fixes existing formatting that was not eslint config compliant

[v2] Fix eslint

---

docs/blog/2018-1-18-strapi-and-gatsby/index.md

Avatar and bio still coming, will make those edits and edit yaml later

Strapi blog post content

---

docs/docs/deploy-gatsby.md

Added the task to deploy to Github Pages in Organizations pages like organization.github.io

Added deploy task to gh-pages in Org pages

---

packages/gatsby-plugin-glamor/README.md
packages/gatsby-plugin-glamor/package.json
yarn.lock

[v2]  move glamor to peerDependencies

---

README.md

I added two of my GatsbyJS projects to the README section. I hope this is alright, if not I totally understand. I'm a big fan of Gatsby.
Thanks for your time.

README showcase update

---

packages/gatsby-cli/src/create-cli.js

Show help and recommend when the command is wrong

---

docs/docs/gatsby-starters.md

Seems like "Features" or something other is messing up the indentation and therefore messing up the whole idea of two sub-entries. So I just did two separate entries now.
--> https://github.com/gatsbyjs/gatsby/pull/3664

Fix gatsby-starter-portfolio-emilia PR

---

README.md

Added a website made for a client... built with gatsby / netlify :)

Add Flooring Factories Outlets to Showcase

---

packages/gatsby-source-faker/README.md

it was using wrong markdown syntax

docs(faker): update link

---

packages/gatsby-plugin-sharp/package.json
packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
yarn.lock

The snapshot changes seem ok. The before and after images for these changes are tiny, but I've attached them here if anyone wants to take a look. 
Note there's two images on each line, a before and an after. 
**Accounts for pixel density** 
**Can optionally ignore pixel density**

Update to sharp v19

---

packages/gatsby-cli/src/init-starter.js

Go with @VinSpee's original plan in #3690

Use ssh form of git address fixes #3702

---

docs/docs/plugins.md

[www] Add gatsby-source-faker to official plugins list

---

packages/gatsby-plugin-netlify/README.md

I think this was forgotten in https://github.com/gatsbyjs/gatsby/pull/3463. Thanks for this plugin (and Gatsby as a whole of course)!

Fix default value in Netlify plugin readme

---

README.md

@KyleAMathews Hack Club's switched to Gatsby, hurray! 🎈🎉✨
(I'm not sure how you feel about this placement, happy to change it)

Add Hack Club to projects list

---

docs/docs/adding-a-list-of-markdown-blog-posts.md

Fix link to Adding Markdown Pages in List docs

---

docs/docs/plugins.md

Add unsplash source as community plugin

---

packages/gatsby/src/internal-plugins/query-runner/query-watcher.js

This is common issue many new users have - they try to run queries in non page/layout components and trying to figure out why they don't get any data. This is meant to increase developer expierience.
Just please someone suggest more meaningful warning message - one in this PR is just placeholder :)

warn about queries in non page/layout components

---

README.md

Adding Dona Rita to Readme's showcase section.
More info about this project: https://medium.com/netlify/jamstack-with-gatsby-netlify-and-netlify-cms-a300735e2c5d

Adding new Showcase example (with source)

---

docs/docs/building-apps-with-gatsby.md

Just a little typo correction. :)

Corrected typo on building-apps-with-gatsby.md

---

packages/gatsby/src/internal-plugins/query-runner/query-compiler.js

don't try to extract queries from directories

---

packages/gatsby-cli/src/init-starter.js

Use HTTPS to clone starters

---

README.md

update odayaka.net to showcase

update odayaka.net to showcase

---

docs/tutorial/part-one/index.md

After doing this tutorial as a complete beginner myself, I thought a couple of lines could be made even more newby-friendly.

[www] Tutorial: Minor edits for absolute beginners

---

packages/gatsby/cache-dir/api-ssr-docs.js

Noticed this typo when trying to get SSR working for the first time.
Cheers!

import `Helmet` not `helmet`

---

README.md

Gatsby Manor makes themes for GatsbyJS.

update showcase with Gatsby Manor

---

docs/blog/2018-2-6-choosing-a-back-end/index.md

Talked to Ross Whitehouse, the author, via Medium private message to confirm the errors. Gotten permission to submit PR for the edit.

Fix mistake in a blog post

---

docs/docs/plugins.md

I'm not sure this is the best place for this note, but there's not (yet) docs that give a more technical overview of how plugins work.
Refs #3834

Add note about plugin options

---

packages/gatsby/src/redux/actions.js

@Swizec I think this would have caught your error from last week

Validate when creating a page that the page component exists

---

packages/gatsby-transformer-react-docgen/README.md

Until there's a better answer for issue #4003.
Refs: #4003

Add note on PropTypes

---

packages/gatsby/src/redux/index.js

fixes #2929 
This was silently not working for months (thanks to me 😢  ). `trackSubObjectsToRootNodeId` was undefined when it was called and try/catch block would silently swallow error.
I wonder how this bug wasn't discovered earlier.

Fix tracking parent nodes when loading redux state from cache

---

README.md

Included sauce as the build config might be handy for anyone looking to build with gatsby-plugin-sharp on CircleCI 😄

add portfolio site to the readme showcase

---

packages/gatsby/src/redux/actions.js
packages/gatsby/src/redux/index.js
packages/gatsby/src/schema/__tests__/node-tracking-test.js
packages/gatsby/src/schema/node-tracking.js
packages/gatsby/src/schema/run-sift.js
packages/gatsby/src/schema/types/type-file.js

This moves node tracking code to dedicated file and adds some basic tests.

node tracking - add tests

---

packages/gatsby-plugin-sharp/src/index.js

This at least partially addresses #3757

[gatsby-plugin-sharp] add support for tiff images and add some error handling

---

README.md

Add portfolio of Preston Richey to README showcase

---

README.md

[My first production site](https://www.beachhutpoole.co.uk) built with Gatsby and some great Gatsby plugins.

Add Beach Hut Poole to Site Showcase

---

packages/gatsby/src/utils/api-node-docs.js

Follow up on the conversation https://github.com/gatsbyjs/gatsby/pull/4090

fix documentation's example import statement

---

packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js

Updated Link import for v2  in raw_dev-404-page.js

Updated Link import for v2 in raw_dev-404-page.js

---

packages/gatsby-image/index.d.ts

Typescript definitions for gatsby-image

Add ts declaration file for package gatsby-image

---

packages/gatsby-plugin-sharp/src/index.js

This is workaround for bug in sharp https://github.com/lovell/sharp/issues/1134 and should be later reverted when it's fixed upstream
fixes #4142

[gatsby-plugin-sharp] don't use "attention" or "entropy" crop strategy when scaling

---

CONTRIBUTING.md

Hey, so I found this typo while going through the documentation. It's a minor fix, so it doesn't need your immediate attention. I just wanted to get this in before I forgot about it.
Thanks for all your work! 💖

Fix minor typo in`CONTRIBUTING.md`

---

packages/gatsby-source-faker/README.md

since the npm script is adding the package as a dev dependency, yarn should do the same

add -D to yarn add

---

packages/gatsby/src/schema/run-sift.js

it will cache nodes that are tracked so no need to re-track nodes each time it runs

follow up for "Fixes to speed up running queries" 

---

README.md

I'm super proud of my new gatsby based portfolio, would love for it to be added. 
http://juliette.sh/
https://github.com/laurajuliette/juliette.sh

Update showcase, with my beautiful new portfolio

---

README.md

Hello!
I built a side project of mine, “Théâtres Parisiens” — a directory of all the theaters in Paris — with Gatsby. I liked using it so much, thank you!
This is a PR to add the website and the sources to the showcase.

Add “Théâtres Parisiens” to the showcase

---

docs/docs/netlify-cms.md

It's really easy to miss this 😅

Highlight "trailing slash is required"

---

README.md

Hey, I really love using Gatsby and would like to add my [website / blog](https://jiahao.codes) to the showcase!
I've also blogged about my migration from Jekyll and my setup of the new website in a two part post [here](https://jiahao.codes/blog/why-i-upgraded-my-website/). 
Cheers! 😄

Add Jia Hao's Website to showcase

---

docs/tutorial/part-four/index.md

Add specific step about changing to the new directory

---

packages/gatsby/src/bootstrap/load-plugins/load.js

Fix issue with resolving local plugins

---

docs/docs/plugins.md

Add gatsby-source-strapi to community plugins list

---

docs/docs/querying-with-graphql.md

GraphQL queries are only run when the Component is a
Page or Layout.
I spent a good couple hours trying to understand this.  It
wasn't all bad, since I learned lots.
Hopefully this comment can help spare others. :-)

docs: Clarify queries and Components

---

docs/docs/gatsby-starters.md

Timeline view, responsive, uses flexbox.

Add new Portfolio Theme

---

docs/docs/plugins.md

Add gatsby-source-mozaik to community plugins list

---

Dockerfile

Skip libvips and builds tools as sharp v0.20.0 now downloads binaries

---

packages/gatsby-remark-images/README.md

docs: move gatsby-plugin-sharp to main plugins array

---

docs/docs/add-custom-webpack-config.md

issue : #4053 
Do let me know if i have made a mistake! Thanks!

Add example for modifying babel loader

---

README.md

Hey!
I've recently rewrote the website of my faculties student union from hugo to gatsby. 
I have to say, it's a wonderful tool to work with!

Add kandohok.hu to showcase

---

www/src/pages/docs/index.js

Unfortunately we have to use real HTML there instead of Markdown :3

CLI commands: HTML instead of Markdown

---

docs/tutorial/index.md
docs/tutorial/part-one/index.md
www/src/pages/docs/tutorial-links.yml

I took out all the "simple, easy, basic" words and reformatted a few things. @amberleyromo Would you mind reviewing this for me? A couple UX projects are coming to mind based on these edits (i.e. special visual cues for the "challenge" things, and perhaps hover states for definitions and tips.

Minor edits to standardize format and language

---

packages/gatsby-transformer-javascript-frontmatter/README.md

a minor one..but it confused me in the beginning ;-)
hope I changed the correct ones and didn't miss anything?

changed various occurences of "data" (from the deprecated gatsby-transformer-static-exports) to reflect the new name "frontmatter"

---

docs/blog/2018-02-09-announcing-gatsby-manor-themes-for-gatsbyjs/index.md

Gatsby Manor is actually in alpha mode.

Update blog post with accurate info

---

www/src/components/evaluation-table-section-title.js
www/src/utils/typography.js

[www] Increase default <h3> top margin

---

docs/docs/adding-tags-and-categories-to-blog-posts.md

ESLint is complaining:
> Casing of lodash/kebabcase does not match the underlying filesystem. (import/no-unresolved)

Fix ESLint error

---

examples/using-styletron/src/html.js

Sorry for these tiny PRs...Found another one :)

Update styletron example site title

---

www/static/google007cad3f98c003c0.html

Verify for google search console.

upload google search console html file

---

examples/gatsbygram/scrape.js

Instagram changed the structure of the graphQl object. This updates scrape.js to use the updated/changed field names

Updates scrape.js for gatsbygram

---

packages/gatsby-plugin-google-analytics/src/gatsby-browser.js

Fix query params not captured in Google Analytics (#4527)

---

packages/gatsby-transformer-javascript-frontmatter/package.json
packages/gatsby-transformer-javascript-frontmatter/src/gatsby-node.js

On my project I use typescript. So, I need to get frontmatter from typescript files as well.

[gatsby-transformer-javascript-frontmatter] Parse out js and typescript files

---

packages/gatsby/src/redux/reducers/components.js

I've being bothered a lot by the problem that the cache is cleared after change, and I remember that problem is fixed in master branch and also been merged to v2 branch, but I find that there is something wrong with the merge, so that's it.
@KyleAMathews could you please release a new version if this been merged, quite annoying problem, thanks

[v2] fix wrong merge

---

README.md

Add Ledgy to Showcase

---

packages/gatsby-remark-prismjs/README.md
packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js
packages/gatsby-remark-prismjs/src/__tests__/index.js
packages/gatsby-remark-prismjs/src/highlight-code.js
packages/gatsby-remark-prismjs/src/index.js

This is the second attempt at issue #4556
In addition, it fixes issue #4597

innerCode should be run through Prismjs as well (try 2)

---

packages/gatsby-cli/src/reporter/index.js
packages/gatsby/src/redux/actions.js
packages/gatsby/src/redux/index.js
packages/gatsby/src/utils/cache.js
packages/gatsby/src/utils/create-node-id.js

Covered a few areas to begin with. 
Close #4120

Add jsdoc comments to several sections

---

README.md

We just finished our company website based on **GatsbyJS**, using also **Redux**, **i18next** and **styled-components**.

Add Hapticmedia to the showcase

---

packages/gatsby/cache-dir/loader.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/static-entry.js
packages/gatsby/src/bootstrap/index.js
packages/gatsby/src/internal-plugins/query-runner/gatsby-node.js
packages/gatsby/src/internal-plugins/query-runner/pages-writer.js
packages/gatsby/src/internal-plugins/query-runner/query-runner.js
packages/gatsby/src/redux/actions.js
packages/gatsby/src/redux/reducers/layouts.js
packages/gatsby/src/redux/reducers/pages.js
packages/gatsby/src/utils/test-require-error.js

Merging @pieh's work on the new query loading setup into the existing branch.

[WIP][v2] build updates

---

.babelrc.js
packages/gatsby-transformer-react-docgen/src/Doclets.js
packages/gatsby-transformer-react-docgen/src/__tests__/Doclets.js

could be back ported to v1 as well

fix some jsdoc parsing bits

---

packages/gatsby/cache-dir/json-store.js
packages/gatsby/src/commands/develop.js
packages/gatsby/src/internal-plugins/query-runner/pages-writer.js
packages/gatsby/src/internal-plugins/query-runner/query-runner.js
packages/gatsby/src/redux/index.js
packages/gatsby/src/redux/reducers/index.js
packages/gatsby/src/redux/reducers/json-data-paths.js
packages/gatsby/src/redux/reducers/layouts.js
packages/gatsby/src/redux/reducers/pages.js
packages/gatsby/src/utils/websocket-manager.js

The client will request the data for each page as needed.

[v2] Enable cached query results to be loaded

---

README.md

I have created a new website/blog using GatsbyJS and Netlify.
If you like it, I will be happy.

Update README.md, add philippczernitzki.me

---

README.md

Replacing hunterchang.com with CodeBushi.

Add CodeBushi to showcase

---

docs/docs/gatsby-starters.md

Add new starter info to documentation

Add Gatsby Starter Bloomer

---

docs/docs/gatsby-starters.md

Add gatsby-starter-i18n-lingui to the doc

Add gatsby-starter-i18n-lingui

---

README.md

Migrated from my blog from WordPress to Gatsby

Adding a new site built with Gatsby

---

packages/gatsby/src/internal-plugins/query-runner/pages-writer.js

this avoid writing `(a)sync-requires.js` when just data changes in develop mode - it compares page dependencies on react components (both page and layout component) and compare it to previous dependency map - if nothing change since last run, it bails early

[json-loader] dont recompile on data change

---

docs/docs/seo.md

It's implying that we don't client render — which we do — so remove that fragment since not important to message of the sentence.

Correct potential miscommunication in SEO doc

---

README.md

add my example site to showcase list

add Bartosz Dominiak site to showcase

---

packages/gatsby-plugin-google-analytics/README.md

See: https://github.com/gatsbyjs/gatsby/issues/4815

Fix spelling error

---

README.md

Where do you usually add more websites (top/middle/bottom/random?)

Add Storybook to Websites built with Gatsby

---

docs/docs/gatsby-starters.md

- Post
- Pagination
- Categories
- Tags
- Search
- Put React Application into post
- Put Tweet into post
- Draft (set hide to true)
- Copy codes with clicking button
- Portfolio
- Resume

add new starter (gatsby advanced blog)

---

www/src/pages/plugins.js

This should fix the failing build on `master`

[www] add missing import

---

packages/gatsby/src/internal-plugins/query-runner/redirects-writer.js
packages/gatsby/src/redux/reducers/redirects.js

this avoid writing `redirects.json` when just data changes in develop mode

[json-loader] dont recompile on data change - part 2

---

docs/tutorial/part-four/index.md
docs/tutorial/part-one/index.md
docs/tutorial/part-three/index.md
docs/tutorial/part-two/index.md

Following up on issue #4577 (now closed)
Is "change" the right word in this phrasing?
"Similar to part one, open a new terminal window and run the following commands to install and then change to your new tutorial-part-two directory:"

Explained what cd means for starter installation

---

packages/gatsby-remark-embed-snippet/src/__tests__/__snapshots__/index.js.snap
packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/highlight-code.js.snap
packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js
packages/gatsby-remark-prismjs/src/highlight-code.js

When using the highlighting lines, don't add an extra trailing newline.

Don't add an extra trailing newline part deux

---

packages/gatsby/src/utils/websocket-manager.js

[v2] Clean up active path when a user disconnects

---

packages/gatsby-transformer-remark/src/extend-node-type.js

hey @pieh 
this is the PR you were asking for,
Closes #4860

fix(gatsby-transfomer-remark): memory leak of ASTPromiseMap

---

README.md

Today I just finished launching my website based on Gatsby + Netlify + Netlify CMS + AWS SES!
Viva la Gatsby!
Signed-off-by: stam <junkboy0315@gmail.com>

add yuuniworks.com to showcase

---

README.md

Signed-off-by: me@chinloongtan.com

Add chinloongtan.com to showcase

---

packages/gatsby-plugin-netlify-cms/package.json

Signed-off-by: Daniel Mahon <danielmahon@users.noreply.github.com>

Adds missing extract-text-webpack-plugin dependancy

---

docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
packages/gatsby-image/README.md

fix links in blog post and plugin readme

---

packages/gatsby-plugin-stylus/package.json
packages/gatsby-plugin-stylus/src/gatsby-node.js

Fix build process using gatsby-plugin-stylus together with gatsby-plugin-netlify-cms according to gatsby-plugin-sass.
Signed-off-by: Jan Winterfeld <jan@markenbegeisterung.de>

fix gatsby-cms-stylus build command according to gatsby-plugin-sass

---

packages/gatsby-transformer-csv/README.md

added instructions to use the plugin `gatsby-transformer-csv`
Signed-off-by: Sébastien Belmon <sebastien.belmon@gmail.com>

added instructions to use gatsby-transformer-csv

---

packages/gatsby-source-filesystem/README.md

[gatsby-source-filesystem] Fix URL to guide

---

dangerfile.js

I've left the file there for next time a rule should be added.

Remove DCO check as it's no longer a requirement for PRs

---

docs/blog/2018-04-04-gatsby-contentful-starter-tutorial/index.md

Article is written from the Contentful first-person POV. Gatsby blog articles should be written from individual first-person POV or no first-person POV.

Remove Contentful first-person

---

README.md

Thanks for creating Gatsby and for all of your hard work! We’ve enjoyed building our new marketing website with it 🙏

Add Dovetail (dovetailapp.com) to website examples

---

README.md

Hey! 👋 
To all the contributors of this project, thank you guys so much for building/maintaining this. 🙇
Just revamped my personal website using Gatsby and wanted to add it to the list of websites on your showcase. 🙂

Add abinavseelan.com to Showcase

---

packages/gatsby/cache-dir/loader.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/static-entry.js
packages/gatsby/src/internal-plugins/query-runner/pages-writer.js

inline needed data for page in html and delay loading rest of it after initial mount has been completed

[v2] break out pages.json and json data paths from app bundle

---

docs/tutorial/part-seven/index.md

I think line 308's `src/pages/my-files.js` is wrong.
It should be `src/pages/index.js` isn't it?

I found wrong word (tutorial #7)

---

Breaking Changes.md

Refs the discussion on https://github.com/gatsbyjs/gatsby/issues/5133#issuecomment-384682812

Add react and react-dom install step

---

docs/tutorial/part-one/index.md

https://github.com/gatsbyjs/gatsby/issues/5133

Further removal of semi from tutorial

---

packages/gatsby-source-contentful/src/normalize.js
packages/gatsby/src/utils/eslint-config.js

make sure we consistently use createNodeId

[v2] [gatsby-source-contentful] fix normalize id issues

---

Breaking Changes.md

https://github.com/gatsbyjs/gatsby/issues/5133#issuecomment-385636143
https://github.com/gatsbyjs/rfcs/blob/remove-layouts/text/0000-remove-special-layout-components.md
https://github.com/gatsbyjs/gatsby/pull/4887

Added info regarding removal of Layouts

---

packages/gatsby-1-config-extract-plugin/__mocks__/extract-text-webpack-plugin.js
packages/gatsby-1-config-extract-plugin/src/__tests__/index.js
packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
packages/gatsby/src/schema/__tests__/build-node-types-test.js
packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js

All that's left after this is the tests for `gatsby-plugin-sass` and `gatsby-plugin-less`
Refs #5131

[v2] yet more test fixes

---

packages/gatsby/cache-dir/json-store.js

the `pages` is undefined, and the omit is wrong actually

[v2] fix json-store regression

---

packages/gatsby/cache-dir/root.js
packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js

dev-404-page is completely broken

[v2] fix dev-404-page

---

README.md

Add Tinder Interracial Couple Emoji Project to showcase

---

docs/tutorial/part-four/index.md

A minor fix to show that layouts are basically just normal components.

[v2 Documentation] Fixed index components into layout components

---

docs/docs/wordpress-source-plugin-tutorial.md

Fragments don't work on Graphiql

Quick fix for wordpress source plugin tutorial

---

README.md

Another quick website that I made with Gatsby. 😀
https://www.workshop-in-the-woods.com/

Add workshop-in-the-woods.com to the showcase

---

examples/using-wordpress/gatsby-node.js

I thought that the post will be put /post/{slug} , but it is put /${slug}.
so I changed the comment.

Fix post path comment

---

packages/gatsby-transformer-remark/README.md

I don't know if it's the original article but at least it looks fairly similar

Fix broken link to tutorial for building blog

---

docs/docs/working-with-images.md
www/src/pages/docs/doc-links.yaml

Add @melissamcewen's new docs page to the sidebar (from https://github.com/gatsbyjs/gatsby/pull/4191)

Add new docs page to sidebar

---

www/src/components/navigation.js
www/src/layouts/index.js
www/src/pages/blog/index.js
www/src/pages/plugins.js

Remove the banner as the workshops have finished.
Reverts #4788 and #4808

Remove workshop banner

---

examples/gatsbygram/gatsby-browser.js

[v2] fix gatsbygram build

---

packages/gatsby-plugin-guess-js/README.md

@KyleAMathews Great addition for the Guess.js plugin, I fixed a small typo in the README

[gatsby-plugin-guess-js] fix a small README typo

---

packages/gatsby-source-wordpress/src/normalize.js

[gatsby-source-wordpress] check if parent exists

---

examples/gatsbygram/src/components/modal.js
examples/gatsbygram/src/pages/about.js
examples/gatsbygram/src/pages/index.js
www/src/pages/blabhdf.js

 [v2] Fix gatsbygram UI tests

---

www/src/components/blog-post-preview-item.js

[www] Prevent image twitch in Chrome when hovering a blog index card

---

packages/gatsby/cache-dir/static-entry.js

I took this from [comment](https://github.com/gatsbyjs/gatsby/issues/2807#issuecomment-388304366) on #2807 and it fixed our problems of IE10 not loading scripts.

Fix for IE10 not loading scripts

---

packages/gatsby/cache-dir/static-entry.js

Code changed in #5404, this comment no longer relevant.

Remove old comment

---

docs/tutorial/part-seven/index.md

[v2][tut. part 7] Use "you" instead of "we" where appropriate

---

docs/tutorial/part-one/index.md

[v2][tut. part 1] Use "you" instead of "we" where appropriate

---

docs/tutorial/part-three/index.md

[v2][tut. part 3] Use "you" instead of "we" where appropriate

---

docs/tutorial/part-four/index.md

[v2][tut. part 4] Use "you" instead of "we" where appropriate

---

docs/tutorial/part-five/index.md

[v2][tut. part 5] Use "you" instead of "we" where appropriate

---

docs/tutorial/part-six/index.md

[v2][tut. part 6] Use "you" instead of "we" where appropriate

---

docs/tutorial/part-four/index.md

Fixing what `format-markdown` missed and some line highlight numbers.

[v2][tut. part 4] Bracket consistency on code blocks

---

www/package.json
www/src/pages/blog/tags.js
www/src/pages/colors.js
www/src/pages/docs/actions.js
www/src/pages/docs/browser-apis.js
www/src/pages/docs/node-apis.js
www/src/pages/docs/ssr-apis.js
www/src/pages/features.js
www/src/pages/plugins.js
www/src/templates/tags.js
www/src/templates/template-contributor-page.js
www/src/templates/template-docs-local-packages.js
www/src/templates/template-docs-remote-packages.js

Plus fixes to a couple of small issues.

[v2][www] Add global layout to pages and templates that don’t have it yet.

---

.github/ISSUE_TEMPLATE/question.md

For usage questions it's useful to have as much info as possible. Update the _Question or discussion_ template to ask for more info.

Update question or discussion template

---

yarn.lock

[v2] Run bootstrap

---

README.md

How did I miss this and never add it? Gatsby since the v0 days :D

add my personal website to showcase

---

packages/gatsby-source-contentful/README.md

This PR improves the contentful-source-plugin docs by adding a Configuration options section that describes all possible options to use with the plugin

[source-contentful] Improve documentation

---

packages/gatsby/src/utils/webpack.config.js

This adds a public path env option for webpack

added public path env option for webpack

---

packages/gatsby/cache-dir/static-entry.js

Avoid using document.write to load Gatsby scripts. Instead of adding scripts to the head with attribute `defer`, add them at the end of the body with attribute `async`.
Write a script to the page that then uses `document.write` to add more scripts to the page
At the end of `index.html`:
```html
<script id="gatsby-script-loader">
/*<![CDATA[*/
window.page = {
"componentChunkName": "component---src-templates-page-js",
"jsonName": "index",
"path": "/"
};
window.dataPath = "path---index-82fEX6UEOpZ11Gd4vKJx0g2o24";
["/app-8642ea1a08cf2be8b6d7.js", "/0-0c88d85d720173ed1467.js", "/2-2d016db56e46f9e7a91b.js",
"/1-2d7ce2f4b4aadcee44dd.js", "/4-08094623edd3288221a9.js",
"/component---src-templates-page-js-ca7d22bfb4c1d16431a3.js"
].forEach(function (s) {
document.write('<script src="' + s + '" …
```

[v2] Simpler in-page bundle and data loading

---

www/gatsby-node.js

Mirror of https://github.com/gatsbyjs/gatsby/pull/5539

[v2][www] Fix missing blog posts

---

packages/gatsby/package.json

Add a valid entry point for the `gatsby` package

---

packages/gatsby-transformer-json/README.md

Also added some colons because GitHub doesn't allow single character changes. :P

No semicolons inside json objects

---

packages/gatsby/cache-dir/page-renderer.js

also fix bad merge on lifecycles

Add back `replaceComponentRenderer` API

---

www/src/components/layout.js
www/src/components/sidebar-body.js
www/src/pages/docs/actions.js
www/src/pages/docs/browser-apis.js
www/src/pages/docs/index.js
www/src/pages/docs/node-apis.js
www/src/pages/docs/ssr-apis.js
www/src/pages/features.js
www/src/templates/template-docs-markdown.js

This feels like a better pattern, instead of importing PageWithSidebar for every docs page that needs it.
https://github.com/gatsbyjs/gatsby/issues/5348#issuecomment-389814208

[v2][www] Abstracted sidebar to layout component

---

packages/gatsby-plugin-manifest/src/gatsby-node.js

this one should use "sizes" (it doesn't use sharp transformer)

[v2] revert one change from #5250

---

docs/docs/how-to-contribute.md

Remove DCO docs

---

docs/blog/author.yaml

In relation to blog post Introduction to Gatsby

Adding author info

---

www/src/data/sites.yml

Hi, This is my first PR in my life o(╯□╰)o. 
Gatsby.js is awesome, so I recreate my blog from Hexo. It takes my five days, and I will keep maintain and develop it! 
Please include my [blog](https://blog.yangerxiao.com), showing up in the readme.md.

add site showcase

---

package.json
packages/gatsby/src/schema/__tests__/__snapshots__/data-tree-utils-test.js.snap
packages/gatsby/src/schema/__tests__/data-tree-utils-test.js
packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js
packages/gatsby/src/schema/build-connection-fields.js
packages/gatsby/src/schema/build-node-types.js
packages/gatsby/src/schema/data-tree-utils.js
packages/gatsby/src/schema/infer-graphql-input-fields-from-fields.js
packages/gatsby/src/schema/infer-graphql-input-fields.js
packages/gatsby/src/schema/infer-graphql-type.js
packages/gatsby/src/schema/type-conflict-reporter.js
packages/gatsby/src/schema/types/type-file.js

This backports #5155 and #5497 to master

backport schema handling changes from v2

---

packages/gatsby-source-contentful/src/fragments.js

So it would be a deprecation instead of breaking change.

[v2][source-contentful] Restore legacy sizes and resolutions fragments

---

examples/using-csv/package.json

[v2] Update csv example

---

packages/gatsby-source-wordpress/README.md

Added a troubleshooting section to the README to solve the problem where ACF returns back a boolean, when it should ideally be `null` to prevent conflicting data types in GraphQL. 
Should help with issues like #4461 & #5692

Documentation for unknown fields on ACF for WordPress

---

examples/using-medium/package.json
examples/using-medium/src/components/layout.js
examples/using-medium/src/pages/index.js

[v2] Update medium example

---

examples/no-plugins/package.json
examples/no-plugins/src/components/layout.js
examples/no-plugins/src/html.js
examples/no-plugins/src/pages/a.js
examples/no-plugins/src/pages/b.js
examples/no-plugins/src/pages/c.js
examples/no-plugins/src/pages/index.js

[v2] Update no-plugins example

---

examples/using-excel/package.json

[v2] Update excel example

---

docs/tutorial/part-five/index.md
docs/tutorial/part-four/index.md
docs/tutorial/part-seven/index.md
docs/tutorial/part-six/index.md

Refs: https://github.com/gatsbyjs/gatsby/issues/5607
[Working repo of tutorial](https://github.com/ryanditjia/gatsby-v2-tutorial-emotion) (see branches).

[WIP][v2] Edit tutorial to use emotion instead of glamorous

---

packages/gatsby-transformer-sharp/src/fragments.js

Similar to https://github.com/gatsbyjs/gatsby/pull/5678
Fixes #5690

[v2][gatsby-transformer-sharp] restore legacy fragments

---

examples/styleguide/gatsby-node.js
examples/styleguide/package.json
examples/styleguide/src/templates/ComponentPage/ComponentPage.js
examples/styleguide/src/templates/ComponentPage/components/ComponentPreview/index.js
examples/styleguide/src/templates/ComponentPage/components/Example/index.js
examples/styleguide/src/templates/ComponentPage/index.js
examples/styleguide/src/templates/TOC/TOC.js
examples/styleguide/src/templates/TOC/index.js

Refs #5598
GraphQL avoids path context because path is conflicting field, so I replaced path to filePath.

[v2] Update styleguide example

---

examples/using-page-loading-indicator/package.json

[v2] Update page loading indicator example

---

examples/using-css-modules/package.json

[v2] Update using css modules example

---

examples/using-css-modules/src/pages/sassy-page.js

Add more cheese

---

packages/gatsby/src/cache-dir/page-renderer.js

This was a page conflict fix on my end, the location state was updated inconsistently so in prod sites never actually navigate since the `state.location` was always stale in cDU
I removed the state so it should be a bit more resilient to react 16.3 and the change in 16.4

Fix page renderer

---

packages/gatsby-transformer-remark/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-transformer-remark/src/on-node-create.js

Reverts gatsbyjs/gatsby#5557
The `internal` object is strictly defined and shouldn't have random fields on it.

Revert "Add rawMarkdownBody to node.internal"

---

examples/using-path-prefix/package.json

[v2] Update using-path-prefix example

---

examples/using-remark-copy-linked-files/gatsby-node.js
examples/using-remark-copy-linked-files/package.json
examples/using-remark-copy-linked-files/src/components/Bio.js
examples/using-remark-copy-linked-files/src/components/layout.js
examples/using-remark-copy-linked-files/src/pages/index.js
examples/using-remark-copy-linked-files/src/templates/blog-post.js

[v2] Update using-remark-copy-linked-file example

---

docs/docs/gatsby-starters.md

Add "cara" starter to list

---

packages/gatsby-transformer-remark/src/__tests__/__snapshots__/gatsby-node.js.snap
packages/gatsby-transformer-remark/src/on-node-create.js

PR #5557 was reverted in PR #5769, but the change is actually OK. Re-adding the change here.

Reinstate reverted PR 5557

---

docs/docs/migrating-from-v1-to-v2.md

Link directly to edit page

---

docs/tutorial/part-one/index.md

While doing the tutorial I noticed that the actual output for running the site for the first time is now different from what is written in there.
It probably got changed but never updated in the doc. I thought to change it to make the tutorial as identical to the real experience as possible :)

Update output text for the site's first run

---

docs/docs/deploy-gatsby.md

Typo/grammar fix! Plural -> Possessive. It looks like this was caught in other parts of the doc!

[Typo] Update deploy-gatsby.md

---

packages/gatsby-source-contentful/scripts/download-data.js
packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
packages/gatsby-source-contentful/src/__tests__/data.json

(currently used data snapshot is quite outdated)

[gatsby-source-contentful] update data and jest snapshots

---

docs/docs/migrating-from-v1-to-v2.md

* Add missing filenames to associated code snippets where applicable
* Format filenames consistently
* Update `sizes` to `fluid` in **Don't query nodes by ID** code snippet to match updates in **Rename responsive image queries**

[v2] Clarify filenames and update `sizes` to `fluid`

---

packages/gatsby/src/utils/webpack.config.js

Upstream fixes from my last 2 PRs

Upstream fixes

---

examples/using-remark/gatsby-node.js

styling seems to be broken, but this can be fixed in follow up

[v2][using-remark] fix build

---

examples/using-remark/gatsby-config.js
examples/using-remark/package.json
examples/using-remark/src/layouts/index.js
examples/using-remark/src/pages/excerpt-example.js
examples/using-remark/src/pages/index.js
examples/using-remark/src/styles/index.js
examples/using-remark/src/templates/template-blog-post.js
examples/using-remark/src/utils/typography.js
yarn.lock

The fonts weren't being loaded, added gatsby-plugin-typography to fix.

[v2] Fix styling for remark example

---

packages/gatsby-plugin-catch-links/README.md

Update docs for gatsby-plugin-catch-links

---

packages/gatsby/src/cache-dir/develop-static-entry.js
packages/gatsby/src/utils/webpack.config.js

resolve #5825, this is also a followup of #5057

[v2] cleanup MiniCssExtractPlugin from develop stage

---

README.md
www/src/data/sites.yml

I created my blog and portfolio by GatsbyJS. GatsbyJS is very fast. Thank you.
Please include [my site](https://mottox2.com) to showcase.

Add my site to showcase

---

examples/using-jss/package.json

Ref: https://github.com/gatsbyjs/gatsby/issues/5598

[v2] Update using-jss example

---

packages/gatsby/src/utils/webpack-utils.js

[v2] Use contenthash for CSS 

---

packages/gatsby/.gitignore

[v2] gitignore fix

---

docs/docs/migrating-from-v1-to-v2.md

ref https://github.com/gatsbyjs/gatsby/pull/5881#pullrequestreview-128627822

[v2] remove temporary link

---

www/src/components/evaluation-table.js

[v2][www] eslint fix

---

docs/docs/migrating-from-v1-to-v2.md

Add missing import to upgrade docs

---

README.md

Add relevant notes and links about V2.
re gatsbyjs/gatsby#5762

docs: update V2 README for beta

---

docs/docs/migrating-from-v1-to-v2.md

Since I couldn't find any paragraph about this change I added something :)

Add "Link" part to upgrade docs

---

docs/docs/add-custom-webpack-config.md

As I used this today I figured I share it with the other ppl who might want to do the same :)

Add example to webpack config

---

www/src/components/evaluation-table.js
www/src/components/used-by.js

this really bothered me so i decided to do a small PR. no visual or functionality changes here, just added things to address warnings coming up when i develop in `www`.
check the commit log for things addressed.
evidence of things i am addressing..
this warning comes from the TEXT of docs/actions.js and isnt actual code we use. we should probably make our warnings smarter since others may use the words "boundACtionCreators"

fix minor warnings in v2/www

---

www/static/robots.txt

Add robots.txt to disallow indexing next.gatsbyjs.org

---

lerna.json
package.json
yarn.lock

Update Lerna to v3

---

www/gatsby-config.js
www/package.json

Add gatsby-plugin-netlify-cache to cache image thumbnails

---

docs/blog/2018-06-16-announcing-gatsby-v2-beta-launch/index.md

Clarify question on upgrading to v2 — you "can" upgrade not "should"

---

docs/docs/how-gatsby-works-with-github-pages.md

Missing double quote

---

examples/using-mongodb/gatsby-node.js
examples/using-mongodb/package.json
examples/using-mongodb/src/layouts/index.js
examples/using-mongodb/src/pages/index.js
examples/using-mongodb/src/templates/item.js

[v2] Update using-mongodb example

---

docs/docs/site-showcase-submissions.md

Update link to site.yml

---

docs/tutorial/part-two/index.md

[v2] Fix unused Container component references in part-two of tutorial

---

packages/gatsby/src/cache-dir/gatsby-browser-entry.js

Fix #5978 
I didn't change any of the docs, not sure which version you prefer to highlight

support children render prop for StaticQuery

---

packages/gatsby-remark-custom-blocks/README.md

closes: #5904 
Added more information about how to use `gatsby-remark-custom-blocks`

More docs around gatsby-remark-custom-blocks

---

docs/docs/site-showcase-submissions.md

Correct link (again)

---

docs/docs/babel.md

Correct name of the babel plugin for class props

---

README.md

Add Bench accounting to showcase

---

docs/docs/awesome-gatsby.md

Adding the browser extensions to Awesome Gatsby Tools.

[www] Add is-gatsby browser extension to awesome-gatsby

---

scripts/www-data-explorer.js

Fix building the gatsbyjs.org data explorer for v2

---

docs/docs/gatsby-starters.md

Added gatsby-starter-tachyons

---

www/gatsby-node.js
www/src/components/showcase-details.js
www/src/pages/showcase.js

Increase number of showcase sites in build

---

docs/docs/migrating-from-v1-to-v2.md

Add docs on using v2 starters

---

packages/gatsby-source-filesystem/src/gatsby-node.js

using single state machine for all instances of `gatsby-source-filesystem` plugin will sometimes cause nodes from one instance to not be created when second instance changed state
fixes #5991
fixes #5980

[gatsby-source-filesystem] create separate state machines for each instance of plugin

---

packages/gatsby/src/utils/webpack.config.js

Update SSL for FriendlyErrorsWebpackPlugin

---

docs/docs/add-custom-webpack-config.md

docs(add custom webpack config): update examples

---

packages/gatsby-plugin-react-css-modules/src/gatsby-node.js

Pull in correct dep for plugin-react-css-modules

---

docs/blog/2018-06-14-escalade-sports-from-5000-to-5-in-hosting/index.md

[master] Fix broken external links for the latest blog post

---

README.md
docs/docs/gatsby-starters.md
docs/docs/migrating-from-v1-to-v2.md

v2 starter docs

---

docs/blog/2018-06-16-announcing-gatsby-v2-beta-launch/index.md

Merge #6070 before this.
Refs: #5973

Link to the v2 starters

---

docs/sites.yml

Add Pride of the Meadows to website list

---

packages/gatsby-transformer-react-docgen/src/Doclets.js

Fix `transformer-react-docgen` tests on Windows
Closes #5725

Strip \r characters from the end of doclet content

---

docs/docs/migrating-from-v1-to-v2.md

Refs: https://github.com/gatsbyjs/gatsby/issues/6054.

[v2][migration guide] Add import graphql function

---

www/src/html.js

Load defer docsearch script and preload stylesheet for #6107

not blocking render with docsearch assets

---

www/src/html.js

Preload docsearch script and no blocking docsearch css #6107

preload and not bloking docsearch assets

---

packages/gatsby/index.d.ts

Export graphql TypeScript definition from gatsby package

---

www/src/templates/template-docs-markdown.js

Fixes https://github.com/gatsbyjs/gatsby/issues/6132.

[v2] Fix doc not centered

---

docs/sites.yml

Signed-off-by: lesliecdub <lcohn-wein@canvasunited.com>

Adding NYC Pride 2019 site to showcase sites.yml

---

www/src/components/blog-post-preview-item.js
www/src/components/function-list.js
www/src/components/markdown-page-footer.js
www/src/components/showcase-details.js
www/src/pages/blog/index.js
www/src/pages/blog/tags.js
www/src/pages/index.js
www/src/pages/showcase.js
www/src/templates/tags.js
www/src/templates/template-blog-post.js
www/src/templates/template-contributor-page.js
www/src/templates/template-docs-local-packages.js
www/src/templates/template-docs-remote-packages.js
www/src/templates/template-showcase-details.js

https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#import-graphql-from-gatsby

[www] Import graphql from Gatsby

---

packages/gatsby-image/README.md

Creating this PR into `master` because the docs have changed since `v1`, but I'm happy to either rebase this or create a second PR with the equivalent change for `v1` if you'd like!

docs(gatsby-image): Minor cleanup

---

www/src/pages/showcase.js

…and sidebar height, fixes #6202

[www] Showcase: Fix header `position:sticky` `top`

---

packages/gatsby-image/README.md

Fixed table syntax error.

---

packages/gatsby-plugin-typescript/README.md

fixed a letter

---

docs/docs/migrating-from-v1-to-v2.md

Fix a small typo

---

docs/docs/migrating-from-v1-to-v2.md

fix markdown typo

---

www/src/components/navigation-mobile.js

[www] Prevent shrinking of mobile nav buttons/icons

---

www/src/components/sidebar/body.js
www/src/components/sidebar/section.js
www/src/components/sidebar/sidebar.js
www/src/utils/sidebar/create-link.js

- Fix position of horizontal rules/1px separators.
- Fix hover bullet point/selected indicator vertical position.
- Add dashed lines and improved vertical spacing for „Tutorial“ subitems.
Fixes #6190

[www] IA redesign: Fix mobile navigation UI

---

.github/PULL_REQUEST_TEMPLATE.md
docs/docs/how-to-contribute.md

What we were telling people to do vs what we actually wanted them to do was slightly different. This was understandably a bit confusing.

Update guidance around branches to reflect how we are handling PRs

---

packages/gatsby/src/utils/webpack-utils.js

Something I came over randomly.

Fix typo in type annotations

---

translations/es/CONTRIBUTING_ES.md

Not sure if these images were originally in Spanish, but I don't see Spanish versions in the repo's history. Anyways, this replaces the broken images with English images.

Fix broken images

---

packages/gatsby/cache-dir/__tests__/loader.js
packages/gatsby/cache-dir/app.js
packages/gatsby/cache-dir/loader.js
packages/gatsby/cache-dir/page-renderer.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/root.js

Fix circular dependency errors
Refs: #6127

Pass apiRunner into loader

---

README.md

add blog showcase

---

packages/gatsby/src/bootstrap/load-plugins/validate.js
packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js
packages/gatsby/src/internal-plugins/load-babel-config/utils.js
packages/gatsby/src/redux/__tests__/babelrc.js

Concat bad errors so good plugins don't overwrite bad

---

packages/gatsby-source-mongodb/src/gatsby-node.js

chore(source-mongodb): Added mongo_id field

---

packages/gatsby/src/utils/webpack.config.js

See https://reactjs.org/docs/cross-origin-errors.html for further details

Avoid React cross-origin errors

---

packages/gatsby-plugin-netlify/README.md

Fixed typo

---

www/src/components/banner.js
www/src/components/layout.js

[www] Move banner to component

---

README.md

GaiAma is still on v1 but will upgrade soon, Rescue Amazonian Rainforest uses v2 already 🥇 hehe
Gatsby Rules 💯

add GaiAma and Rescue Amazonian Rainforest to showacse

---

docs/sites.yml

 Add site to showcase sites.yml

---

packages/gatsby-plugin-page-creator/src/gatsby-node.js
packages/gatsby/src/bootstrap/page-hot-reloader.js
packages/gatsby/src/utils/websocket-manager.js

more adjustments to `pages` being Map instead of array
closes #6382

gatsby develop fixes after hulksmash

---

docs/docs/adding-search.md

Fix typo in "elasticlunr"

---

packages/gatsby-transformer-remark/src/extend-node-type.js

Fix passing files into remark plugins

---

docs/tutorial/part-four/index.md

Newbies might be scared by the error they get if they save pages/index.js before the layout exists.

Moved layout before pages/index.js to prevent error

---

docs/tutorial/part-two/index.md

It's supposed to say `http://localhost:8000` because that's where the Gatsby site is being served.

Fix Typo in Url

---

packages/gatsby/src/bootstrap/page-hot-reloader.js

Fix hot pages loading in v2

---

docs/sites.yml

Add site (Healthcare Logic) to showcase sites.yml

---

docs/tutorial/part-four/index.md

Highlight one more line

---

docs/sites.yml

https://github.com/WeOpenly/localgov.fyi -- I thought this would be a 'feature-worthy' submission, because I've not come across any search engines that were built with Gatsby! Also, some backstory if it's relevant - https://news.ycombinator.com/item?id=17516723

Add localgov.fyi to site showcase

---

packages/gatsby-plugin-sharp/src/index.js

fixes https://github.com/gatsbyjs/gatsby/issues/6394

Adds resize alias for queueImageResizing

---

docs/docs/wordpress-source-plugin-tutorial.md

changed `https:/` to `https://`

minor link fix

---

packages/gatsby/src/commands/develop-html.js

Fixes https://github.com/gatsbyjs/gatsby/issues/6421

Unbreak `gatsby develop`

---

packages/gatsby/src/commands/develop-html.js

Fix develop

---

packages/gatsby-cli/package.json

Add a missing dependency

---

docs/docs/migrating-from-v1-to-v2.md
packages/gatsby-source-filesystem/README.md

documented breaking change in createRemoteFileNode

---

benchmarks/create-pages/package.json
packages/gatsby/src/utils/html-renderer-queue.js
packages/gatsby/src/utils/worker.js

This adds batching for static page generation concurrency, reducing the IPC load between the master and child nodes

Batching for concurrency

---

packages/gatsby/src/utils/webpack-utils.js

fix postcss-loader

---

docs/docs/gatsby-starters.md

Added DevBlog to the list of starter templates.

Add DevBlog Starter

---

packages/gatsby/src/internal-plugins/query-runner/query-runner.js
packages/gatsby/src/schema/run-sift.js

Fixes #6480 and https://github.com/gatsbyjs/gatsby-starter-blog/issues/111

Only cache resolved nodes in production

---

docs/sites.yml

edit codebushi.com

---

www/gatsby-node.js
www/src/components/showcase-details.js
www/src/pages/showcase.js

Remove limit on sites since we're building next.gatsbyjs.org site (soon) on machine w/o build timeouts + caching

---

packages/gatsby/src/bootstrap/index.js
packages/gatsby/src/internal-plugins/query-runner/query-runner.js

Instead create on the fly.
Fixes #6446

Don't precreate directories for query results

---

docs/sites.yml

This is just a temp fix to get the site building again. Should actually revert this and check a category exists before using it in https://github.com/gatsbyjs/gatsby/blob/master/www/src/views/showcase/filtered-showcase.js#L80

Remove sites without a category

---

docs/sites.yml
www/src/views/showcase/filtered-showcase.js

Revert "Remove sites without a category" / fix the underlying bug

---

docs/docs/how-to-contribute.md

Update contributing docs

---

packages/gatsby/src/bootstrap/index.js

#6514 removed a bit too much, this reinstates a line.
Closes #6524

Ensure public/static exists

---

docs/docs/ecommerce-tutorial/index.md

fix markdown code block typo

---

www/src/components/email-capture-form.js
www/src/components/navigation.js
www/src/pages/newsletter.js

closes: #6236 
interactions:
initial:
success:
message:

[www] Adding a simple newsletter page

---

docs/sites.yml

Hi Folks, 
Could you please  add the new `Life Without Barriers | Foster Care` site to your showcase?
Much appreciated.
Thank you for an awesome static site generator!

Add LWB Foster Care site to showcase

---

docs/sites.yml

Add details to lekoarts in showcase

---

docs/docs/site-showcase-submissions.md

- switch to YAML syntax highlighting
- use valid YAML comments for easier copy-pasting
- clarify language

docs: update YAML template

---

packages/gatsby/package.json
yarn.lock

Updates `serve` dependency to version 9.2.0. #6546

updates serve to version 9.2.0 #6546

---

www/src/data/sidebars/doc-links.yaml

Fix URL typo

---

packages/gatsby/package.json
yarn.lock

Updates `serve` dependency to version 9.2.0 #6546

updates packages/gatsby v1 serve dep to version 9.2.0

---

docs/sites.yml

Changed the title and added the `built_by`.
Why is my site not appearing in the site showcase? I can't find it.

Updating lekoarts entry

---

docs/sites.yml

add to bejamas.io, zensum, statushub to gatsby showcase

---

packages/gatsby-source-wordpress/README.md

Update readme.md with ACF Options example

---

www/src/components/sidebar/sidebar.js

Proposed change for #6512

---

docs/sites.yml

Added gouravsood.com blog for showcase

---

docs/sites.yml

For now, I selected the Technology category but I would suggest Programming as a new category instead.

add Nikita to Gatsby feature sites

---

docs/sites.yml

Added Gatsby site: https://moetez.me

Add moetez.me to website list

---

docs/sites.yml

Adding Eventos orellana.com

---

docs/sites.yml

Ic showcase

---

packages/gatsby-transformer-remark/src/extend-node-type.js
packages/gatsby/src/redux/index.js
packages/gatsby/src/schema/build-node-types.js
packages/gatsby/src/utils/api-node-docs.js
packages/gatsby/src/utils/api-runner-node.js

Don't persist state so often & use cheaper method for generating api run ids

---

docs/sites.yml

Adds my personal website to the showcase: https://twitter.com/gatsbyjs/status/1021108825414225920

Adds jonastebbe.com to showcase

---

docs/sites.yml

Add Figma to Showcase

---

docs/docs/graphql-reference.md

Seems that the section is actually under `part-five`, not `part-four`, so this is a small fix that may save someone 30 seconds or so in the future :)

docs: Fixed link to introducing-graphiql

---

docs/docs/gatsby-starters.md

Add `lite` to starters page

---

docs/sites.yml

So excited for this! Gatbsy is amazing 😄

Add Insomnia to Showcase

---

docs/docs/static-query.md

docs: Clarify StaticQuery docs.

---

docs/blog/2018-07-17-announcing-gatsby-preview/index.md

Fix broken link

---

docs/sites.yml

The site showcases the use of styled-components and Contentful with Gatsby v2.
It creates the new content category "science".

Add science outreach site ocean-artup.eu

---

packages/gatsby-source-filesystem/README.md

#6697 Fix typo in gatsby-source-filesystem readme

---

docs/sites.yml

Submitting my portfolio site

---

docs/sites.yml

Adding personal website / blog for RyanFitzgerald.ca to Showcase.

Add RyanFitzgerald.ca

---

.travis.yml
packages/gatsby/src/redux/__tests__/pages.js
packages/gatsby/src/schema/__tests__/node-tracking-test.js

Adds Node 10.x as a testing dependency in Travis. Also fixes two breaking tests in 10.x by mocking readFile and writeFile in `fs-extra`

Added Node 10.x testing dependency

---

packages/gatsby/src/utils/html-renderer-queue.js
packages/gatsby/src/utils/worker.js

This PR improves speed of HTML rendering and add activity status
Closes #6618

Change chunk size for segments, update activity status in HTML renderer

---

packages/gatsby-transformer-screenshot/README.md

Fix link syntax

---

docs/sites.yml

Add Kaizen website to Showcase list

Showcase list update

---

docs/tutorial/part-seven/index.md

tiny grammatical error

---

docs/sites.yml

Add unow.fr website to showcase sites.yml

---

www/src/views/showcase/filtered-showcase.js
www/src/views/showcase/index.js

Fixes https://github.com/gatsbyjs/gatsby/issues/6748

add banner height to sidebar height and showcase top calculations

---

packages/gatsby-remark-prismjs/package.json
yarn.lock

This PR solves the issue #4002. 
I updated PrismJS to its newest version (1.15.0) as @m-allanson suggested in the thread.

#4002 update prismjs version to 1.15.0

---

README.md
docs/sites.yml

Personal site is still on v1. Been doing a lot at work with v2 and hope to be able to add that to the showcase later.

Add self to showcase

---

packages/gatsby/src/utils/api-node-docs.js

I just found this typo in the doc while I was learning about this. Figured I should make a quick PR!!

Small Typo in doc

---

docs/docs/gatsby-starters.md

Add [`gatsby-universal`](https://github.com/fabe/gatsby-universal) starter 🔮

Add gatsby-universal starter.

---

packages/gatsby-transformer-screenshot/package.json
packages/gatsby-transformer-screenshot/src/gatsby-node.js

Adds concurrency limit and retries on failure to screenshot plugin

Make screenshot plugin more reliable

---

docs/sites.yml

Adding my portofolio url

---

www/src/assets/featured-sites-icons--white.svg
www/src/views/showcase/showcase-list.js

fixes https://github.com/gatsbyjs/gatsby/issues/6742

Add star icon to featured sites

---

docs/sites.yml

Fixing typo (soz)

---

packages/gatsby/src/commands/develop.js

Fix a typo

---

packages/gatsby-remark-autolink-headers/README.md

Refs: https://github.com/gatsbyjs/gatsby/issues/5764#issuecomment-408831896
Edit by @pieh:
Closes #5764

Add note regarding placing autolink-headers before prismjs

---

docs/docs/source-plugin-tutorial.md

Fixes doc for v2.
Closes: #6857

Fix starter install for v2 doc

---

packages/gatsby/src/commands/develop.js

This check is already performed a line above

Remove duplicated code

---

docs/sites.yml

Add sapegin.me to the showcase

---

docs/docs/debugging.md
www/src/data/sidebars/doc-links.yaml
www/src/templates/template-docs-markdown.js

- add support for listing child guides under an overview
- write an intro for the debuggin section
close #6582

feat: add debugging overview

---

README.md

This simplifies the language of how we're handling v1 maintenance, per feedback from @shannonbux and @calcsam in #6843.

docs: simplify v1 bugfix language

---

docs/sites.yml

Add malikbrowne.com to sites.yml

add malikbrowne.com to sites.yml

---

packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
packages/babel-plugin-remove-graphql-queries/src/index.js
packages/gatsby/src/internal-plugins/query-runner/__tests__/__snapshots__/file-parser.js.snap
packages/gatsby/src/internal-plugins/query-runner/__tests__/file-parser.js

don't try to modify closing StaticQuery tag

---

docs/docs/image-tutorial.md
docs/docs/migrating-from-v1-to-v2.md
docs/docs/querying-with-graphql.md

Update docs to import graphql

---

packages/gatsby-plugin-offline/README.md

Fix typo in gatsby-plugin-offline readme

---

docs/tutorial/part-five/index.md
docs/tutorial/part-seven/index.md
docs/tutorial/part-six/index.md

Replaces a stale PR https://github.com/gatsbyjs/gatsby/pull/5673#event-1765104203.
Closes https://github.com/gatsbyjs/gatsby/issues/5612.

[Tutorial] Add notice regarding tutorial 4 – 7 series

---

docs/docs/source-plugin-tutorial.md

Typo fix in source-plugin-tutorial.md

---

docs/docs/community.md

Added newsletter link to community page

---

integration-tests/long-term-caching/README.md
packages/gatsby/src/utils/webpack.config.js

Use contenthash instead of chunkhash for javascript files 

---

docs/sites.yml

Add Gatsby based portfolio to site documentation

Add Max McKinney portfolio to sites.yml

---

docs/docs/source-plugin-tutorial.md

Fixes #6857 and makes code blocks more consistent

---

docs/docs/site-showcase-submissions.md

Following up on [this discussion](https://github.com/gatsbyjs/gatsby/pull/6692#issuecomment-407380519).

add source_url, date_added, gatsby_version to showcase-submissions

---

docs/docs/migrating-from-v1-to-v2.md

This PR updates the migration guide with the following objectives in mind.
[Preview](https://github.com/gatsbyjs/gatsby/blob/77c2c8f68ea61acfed55e2563a10963a9a65d01e/docs/docs/migrating-from-v1-to-v2.md)
Closes #6593 
Closes #6613

V2 migration guide updates

---

www/src/components/email-capture-form.js
www/src/components/hubspot-form.js
www/src/utils/form-styles.js

Add some style to the Hubspot form in the new blog post - I assume @fk might want to modify this

Add some style to hubspot form

---

docs/docs/migrating-from-v1-to-v2.md

This fixes incorrect title for Updating your dependencies in migration guide for v2

Fix broken title in v2 migration guide

---

docs/sites.yml

- title: Dave Lindberg Marketing & Design
main_url: 'https://davelindberg.com/'
source_url: 'https://github.com/Dave-Lindberg/dl-gatsby'
featured: false
description: >-
My work revolves around solving problems for people in business, using integrated design and marketing strategies to improve sales, increase brand engagement, generate leads and achieve goals.
categories:
- Creative
- Design
- Featured
- Marketing
- SEO
- Portfolio

Site Submission for Showcase

---

docs/sites.yml

This reverts commit 44a09fce3b3d9e1b9e533ec29efdc065847e5918.

Revert "Site Submission for Showcase (#6997)"

---

docs/sites.yml

Add in dave lindberg site again

---

www/src/views/shared/styles.js
www/src/views/showcase/featured-sites.js

Styles got deleted in the merge, adding them back

add missing styles

---

packages/gatsby-transformer-remark/README.md

Update transformer-remark README to reflect which markdown extensions we actually support

---

docs/tutorial/part-one/index.md
docs/tutorial/part-zero/index.md

fix tutorial part one highlighting issue pointed out by @KyleAMathews, other misc language tweaking.

(fix) tutorial: clarified some language, fixed link

---

docs/sites.yml

Remove chiedo.tv as site isn't loading which is breaking gatsbyjs.org build

---

README.md

Make installing v1 default in README

---

packages/gatsby/package.json
packages/gatsby/src/utils/webpack.config.js

Don't show twice the same success message

---

packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js

Fix anonymize option in google analytics plugin

---

packages/gatsby/cache-dir/json-store.js

json store should update on location change

---

www/src/data/sidebars/tutorial-links.yaml

Noticed these while testing something else

Fix a couple of tutorial links

---

docs/docs/migrating-from-v1-to-v2.md
packages/gatsby/src/utils/api-browser-docs.js

Fix/remove docs on old APIs from @reach/router change

---

docs/docs/awesome-gatsby.md

Jason Lengstorf was interviewed about Gatsby on The Changelog in July.

Update podcasts w new interview on The Changelog

---

packages/gatsby-cli/src/create-cli.js

Improve message when 'gatsby' is missing fixes #7086

---

benchmarks/create-pages/package.json
docs/docs/migrating-from-v1-to-v2.md
packages/gatsby-react-router-scroll/package.json
packages/gatsby/src/bootstrap/resolve-module-exports.js

Check if plugins are using es6 and commonjs together and error

---

docs/docs/v1-release-notes.md

This should be enough to close #5731 for now?

Add links to v1 docs

---

packages/gatsby-plugin-sass/README.md

Update README.md – gastby-plugin-sass – known issue with url() resolution

---

docs/docs/migrating-from-v1-to-v2.md

Add a note about CSS Modules classnames containing dashes

---

packages/gatsby-source-wordpress/README.md

Fixing spelling error

---

docs/tutorial/part-zero/index.md
www/src/data/sidebars/tutorial-links.yaml

(#7118): Clarify prettier instructions and update tutorial sidebar

---

docs/docs/environment.md
docs/docs/preparing-your-environment.md
www/src/data/sidebars/doc-links.yaml

Closes #6590.
I don't see that anything else is required here really. If someone wants more detail, linking out to the new part zero with full install instructions takes care of that.
Any thoughts on anything else that might be helpful here? Pretty much thinking this is just a useful, short landing on the docs side, outside of the tutorial.
Also changed the title/sidebar to be consistent.

[v2] docs "Preparing your environment" overview

---

docs/sites.yml

Added my blog to sites

---

packages/gatsby/cache-dir/navigation.js

Fix showing dev 404 page when there isn't one in development

---

docs/tutorial/part-one/index.md

Update index.md - simple grammar correction (left out a word)

---

docs/sites.yml

Added Website of Sahyadri Open Source Community to Showcase.

Add SOSC.org.in to showcase

---

docs/tutorial/part-one/index.md

Fix typo in tutorial

---

docs/sites.yml

Add thibmaek.com to sites.yml

---

www/src/pages/blog/index.js
www/src/pages/docs/index.js
www/src/pages/index.js

Add the email capture form on several more pages

---

docs/sites.yml

Add learnreact.design to site showcase

Add learnreact.design to sites.yml

---

www/src/data/sidebars/doc-links.yaml

Fix yaml error in doc-links.yaml

---

examples/using-csv/src/pages/index.js
examples/using-drupal/src/pages/index.js
examples/using-drupal/src/pages/recipes.js
examples/using-drupal/src/templates/recipe.js
examples/using-emotion-prismjs/src/components/layout.js
examples/using-emotion-prismjs/src/pages/index.js
examples/using-excel/src/pages/index.js
examples/using-faker/src/layouts/index.js
examples/using-faker/src/pages/index.js
examples/using-gatsby-source-graphql/src/components/BlogPost.js
examples/using-gatsby-source-graphql/src/pages/index.js
examples/using-hjson/src/pages/index.js
examples/using-javascript-transforms/src/components/BlogPostChrome/index.js
examples/using-javascript-transforms/src/mainPages/contact.js
examples/using-javascript-transforms/src/mainPages/index.js
examples/using-mongodb/src/components/story-item.js
examples/using-remark-copy-linked-files/src/pages/index.js
examples/using-sqip/src/components/layout.js
examples/using-wordpress/src/components/PostIcons.js

Run the global-graphql-calls codemod on all example sites. Refs #6122

Run global-graphql-calls codemod on examples

---

docs/docs/gatsby-link.md
docs/docs/migrating-from-v1-to-v2.md
packages/gatsby-link/src/index.js
packages/gatsby/cache-dir/gatsby-browser-entry.js
packages/gatsby/cache-dir/loader.js
packages/gatsby/cache-dir/navigation.js
packages/gatsby/src/bootstrap/index.js
www/src/components/layout.js
www/src/components/search-form.js
www/src/components/url-query.js
www/src/templates/template-showcase-details.js

Move programmatic navigation to "navigate" mirroring @reach/router + some fixes for prefetching

---

packages/gatsby/cache-dir/navigation.js
packages/gatsby/cache-dir/production-app.js
packages/gatsby/cache-dir/root.js

Ryan Florence says this is necessary for React Suspense.

Move onRouteUpdate calls to use @reach navigate's promise to ensure navigation always is actually done & committed to DOM

---

packages/gatsby-codemods/README.md
packages/gatsby-codemods/package.json

All the v2 work is being published as `@next` atm, so I've updated the version and install instructions to match.

Set initial version for codemod package

---

docs/sites.yml

Added our latest project using Gatsby and Wordpress RestAPI. Thank you !

Added tobiemarierrobitaille.com to sites.yml

---

docs/docs/migrating-from-v1-to-v2.md
packages/gatsby-codemods/README.md

Clearer usage instructions and add to migration guide

Clearer codemod instructions

---

docs/sites.yml

add Mega House Creative agency to site showcase.

add megahousecreative to sites.yml

---

www/package.json

Update www to latest gatsby

---

packages/gatsby-source-mongodb/src/gatsby-node.js

This fixes #7223 .
Additionally, this replaces the `cursor.each()` method which is deprecated according to [mongo docs](http://mongodb.github.io/node-mongodb-native/2.2/api/Cursor.html#each).
I'm not sure how to test the change properly other than updating the `using-mongodb` example to use a larger database or creating a repo with a local plugin. Would appreciate any direction on this!
Also, my first PR to a major open source project 🚀 🙂

Fix race condition in gatsby-source-mongodb

---

docs/docs/deploying-and-hosting.md

This PR adds content to the deploying and hosting guides overview.
Closes #6589

Deploying and hosting guides overview

---

packages/gatsby/src/utils/webpack.config.js

Here is a fix for #7187 . Sorry for the delay :)

Make --no-uglify flag work again

---

packages/gatsby-transformer-sharp/package.json

this references and hopefully closes https://github.com/gatsbyjs/gatsby/issues/6985 
@Andarist could we close it?

add missing package dependencies

---

docs/docs/customization.md

This PR adds content to the custom configuration overview doc.
Closes #6588

[v2] Custom configuration overview doc

---

examples/styleguide/src/templates/ComponentPage/ComponentPage.js
examples/styleguide/src/templates/TOC/TOC.js
packages/gatsby-plugin-catch-links/src/catch-links.js
packages/gatsby-plugin-sitemap/src/gatsby-ssr.js
www/src/utils/sidebar/create-link.js

More for #6913. Sorry for kind of a mixed diff. If you don't like it I can separate this PR.

Import <Link /> from a gatsby package

---

packages/gatsby-plugin-manifest/README.md

docs(gatsby-plugin-manifest): add missing quotes

---

docs/docs/static-query.md

This is a pull request for this issue https://github.com/gatsbyjs/gatsby/issues/7297

Issue 7297 - Amend static query code

---

www/src/pages/index.js

Add margin bottom to 'Read more' button on index page

---

www/src/components/email-capture-form.js
www/src/pages/blog/index.js
www/src/pages/docs/index.js
www/src/pages/index.js

Cherry-pick the Hubspot newsletter subscription changes over from `master`

V1 email form changes

---

docs/docs/images-and-files.md
www/src/data/sidebars/doc-links.yaml

feat: add an images and files overview

---

docs/docs/gatsby-starters.md

Small documentation update for the Gatsby Material Starter section in the docs :)
Thanks for creating and maintaining this great project!

Update Gatsby Material Starter feature list.

---

packages/gatsby-source-drupal/src/gatsby-node.js

Fixes #7075
This should probably be applied to version 1 as well, should I create a seperate PR for that?

Ignore 405 responses from drupal jsonapi

---

docs/docs/testing-components-with-graphql.md
docs/docs/unit-testing.md

* Add unit testing guide
* Typo fixes
* Proofreading
* Add info on testing gatsby-link
* Updates for style
* Switch yarn to npm
* Add babel presets to npm install
* Small edits
* Small edits from review
* Add loader shim and __PATH_PREFIX__ global
* Add testing graphql doc
* Rename
* Mock Gatsby rather than removing graphql and using MemoryRouter
* Add filename for gatsby mock
* Update LInk mock so all props can be displayed
* Details on why you might not want to mock Link
* Add not on use of StaticQuery, and a little on component purity
* Update for @reach/router
* Add testURL to Jest config
Because of facebook/jest#6766

[docs] Add unit testing guide (#6678)

---

docs/sites.yml

Adding www.timelyapp.com to `sites.yml`
PS: I absolutely love building websites with Gatsby, thanks for all your hard work!

Add timelyapp.com to sites.yml

---

packages/gatsby/cache-dir/api-ssr-docs.js
packages/gatsby/src/utils/api-browser-docs.js

proper wrapXElement docs fixes

---

docs/sites.yml

Added and updated some details for bastionbot.org website in sites.yml for gatsby showcase.

Update details of bastionbot.org in sites.yml

---

packages/gatsby-plugin-layout/README.md

Remove superfluous parenthesis

---

packages/gatsby-plugin-catch-links/README.md

docs(gatsby-plugin-catch-links): update api reference in readme

---

docs/docs/adding-analytics.md
docs/docs/adding-forms.md
docs/docs/adding-search.md
docs/docs/adding-third-party-services.md
www/src/data/sidebars/doc-links.yaml

Ref: #7294
Added stubs for the following pages:
- Adding third-party services
- Adding search  (page was already there, moved it to the 3rd party section)
- Adding analytics
- Adding forms

Docs: Stubs for Adding third-party services and it's children

---

www/src/components/sidebar/scrollbar-position-provider.js
www/src/components/sidebar/sidebar.js
www/src/components/sidebar/sticky-responsive-sidebar.js

This PR attempts to fix some of the behavior issues in the sidebar for certain docs pages.
Closes #7422

Docs sidebar refactor

---

www/src/components/sidebar/scrollbar-position-provider.js
www/src/components/sidebar/sidebar.js

Throttle scroll position tracking of docs sidebar

---

docs/sites.yml

I was having so much fun in creating the site for my e-Residency startup at [tensiq.com](https://tensiq.com) using React Native Web and Gatsby. I'm really proud of pushing this in the showcase pool `sites.yml` to share the results. Thank you for creating Gatsby and all the incredibly useful plugins.

Add tensiq.com to sites.yml

---

docs/sites.yml

Because we're one of the cool kids now :)

adding SendGrid to sites.yml!

---

packages/gatsby-remark-prismjs/README.md

Fix typo in README.md of gatsby-remark-prismjs

---

docs/docs/recipes.md

closes #6572 
Draft "recipes" doc

[v2] docs "Recipes" doc

---

docs/sites.yml

Upate site showcase

---

www/gatsby-node.js
www/src/components/pagination/PaginationLink.js
www/src/components/pagination/index.js
www/src/templates/template-blog-list.js

@NickyMeuleman I cherry-picked your commit and am PR-ing against v1. Had to resolve some conflicts and want to confirm it was done correctly. If so, please feel free to merge in. 
cc @fk

v1-pagination

---

packages/gatsby-remark-images-contentful/package.json

Fixes https://github.com/gatsbyjs/gatsby/issues/7653

Add gatsby-plugin keyword for plugin search
